### PR TITLE
Change Unbonding time to fast in the test by governance

### PR DESCRIPTION
**Pull request by dzmitryhil**
Change Unbonding time to fast in the test by governance and remove the constant config from the testing.

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/250)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/250)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/250#-NGQOzdGCWfhejkv9Ftl:-NGQOzdHDd0lzQxf1hKW:b-fjzl0m) (no related file):*
This PR: https://reviewable.io/reviews/CoreumFoundation/coreum/248#-
introduces library for creating and removing validators, which is then used by one other test.
Tests run in parallel, so it might happen that the other test is executed with long unbonding period. We need to update unbonding period before running other tests, which probably means this test must run in separate group (like upgrading).

___
___
*[`integration-tests/staking/staking.go` line 126 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/250#-NGQPcrd1obn3taZ6tNc:-NGQPcrd1obn3taZ6tNd:bkwbsg4) ([raw file](https://github.com/coreumfoundation/coreum/blob/cfd91d53b2646c8abfc116895ec04bdac37af70f/integration-tests/staking/staking.go#L126)):*
> ```Go
> 	initialUnbondingTime := stakingParams.Params.UnbondingTime
> 
> 	// defer to restore the time to default after the test
> ```

Continuing on thread I started in the top comment, I think this should not be done. Tests requiring long unbonding time should be run in one group, then unboding time should be set to short one and then the rest of the tests should be executed. Otherwise tests playing with validators might fail.
___
*[`integration-tests/staking/staking.go` line 231 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/250#-NGQQK8c6EgPgh8ox9FP:-NGQQK8d5R3aKIt-TQtf:b-p48j5q) ([raw file](https://github.com/coreumfoundation/coreum/blob/cfd91d53b2646c8abfc116895ec04bdac37af70f/integration-tests/staking/staking.go#L231)):*
> ```Go
> 			},
> 		),
> 		govtypes.OptionYes,
> ```

the method is named `ProposeAndVoteYes` so passing `Yes` here seems to be redundant

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/250)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/250#-NGQOzdGCWfhejkv9Ftl:-NGQSls2DvvajnaSJMhS:b-mw8wzz) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This PR: https://reviewable.io/reviews/CoreumFoundation/coreum/248#-
introduces library for creating and removing validators, which is then used by one other test.
Tests run in parallel, so it might happen that the other test is executed with long unbonding period. We need to update unbonding period before running other tests, which probably means this test must run in separate group (like upgrading).
</blockquote></details>

This is not a lib, this is the func shared among different tests. The unbending time affects only that test that's why it is used here. I don't see other tests which might be affected for now.

___
___
*[`integration-tests/staking/staking.go` line 126 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/250#-NGQPcrd1obn3taZ6tNc:-NGQT7ax3qgRmIKDcWRu:bnbwqea) ([raw file](https://github.com/coreumfoundation/coreum/blob/cfd91d53b2646c8abfc116895ec04bdac37af70f/integration-tests/staking/staking.go#L126)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Continuing on thread I started in the top comment, I think this should not be done. Tests requiring long unbonding time should be run in one group, then unboding time should be set to short one and then the rest of the tests should be executed. Otherwise tests playing with validators might fail.
</blockquote></details>

Let's proceed with the top thread, I've replied there.
___
*[`integration-tests/staking/staking.go` line 231 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/250#-NGQQK8c6EgPgh8ox9FP:-NGQTKuIBHB-zLgYu9wI:bgq3z1a) ([raw file](https://github.com/coreumfoundation/coreum/blob/cfd91d53b2646c8abfc116895ec04bdac37af70f/integration-tests/staking/staking.go#L231)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

the method is named `ProposeAndVoteYes` so passing `Yes` here seems to be redundant
</blockquote></details>

Agree, left after the refactoring. Updated now.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/250)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/250#-NGQOzdGCWfhejkv9Ftl:-NGQWUchDumjQB2yEAnv:b-ogovax) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is not a lib, this is the func shared among different tests. The unbending time affects only that test that's why it is used here. I don't see other tests which might be affected for now.
</blockquote></details>

But what if this and that test run in parallel?

___

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/250)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/250)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/250#-NGQOzdGCWfhejkv9Ftl:-NGRAfBK39W0xnzOScT6:bfaa54w) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But what if this and that test run in parallel?
</blockquote></details>

That's it ok, since this proposal is used in that test only

___

**Review by wojtek-coreum — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/250)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil)

___
*[`integration-tests/staking/staking.go` line 124 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/250#-NGWjnTM1Mi9JPcWGne6:-NGWjnTM1Mi9JPcWGne7:b-ioxl1w) ([raw file](https://github.com/coreumfoundation/coreum/blob/b9f4bfec2d7da8ca56c37617afd1060cff31f457/integration-tests/staking/staking.go#L124)):*
> ```Go
> 	stakingParams, err := stakingClient.Params(ctx, &stakingtypes.QueryParamsRequest{})
> 	require.NoError(t, err)
> 	initialUnbondingTime := stakingParams.Params.UnbondingTime
> ```

I'm not sure
is it really safe since we run tests in parallel ?  multiple of them might change this param and other collisions are possible also ?
___
*[`integration-tests/staking/staking.go` line 221 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/250#-NGWk9JCC2QgGHXXhjhn:-NGWk9JCC2QgGHXXhjho:b-hlpu06) ([raw file](https://github.com/coreumfoundation/coreum/blob/b9f4bfec2d7da8ca56c37617afd1060cff31f457/integration-tests/staking/staking.go#L221)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// TODO(dhil) refactor other tests to use that func for the standard propose + vote action.
> ```

oh I actually changes this part significantly in my gov integration test
it is done a bit differently now

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/250)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

___
*[`integration-tests/staking/staking.go` line 124 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/250#-NGWjnTM1Mi9JPcWGne6:-NGWrmvxD89FV9f3EHJC:b-rj1ord) ([raw file](https://github.com/coreumfoundation/coreum/blob/b9f4bfec2d7da8ca56c37617afd1060cff31f457/integration-tests/staking/staking.go#L124)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm not sure
is it really safe since we run tests in parallel ?  multiple of them might change this param and other collisions are possible also ?
</blockquote></details>

Yes, should be safe,  we do it just here and test the the unbending here and return it back.

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/250)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Review by ysv — DISMISSED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Pull request merged**
