### PR TITLE
Update GitHub action versions to latest.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Update GitHub action versions to latest.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/791)

### CODE REVIEW

**Review by miladz68 — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/791)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/791)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/791)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/791)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`.github/workflows/ci.yml` line 116 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/791#-NswwI0U6xP0c8zBX4W9:-NswwI0U6xP0c8zBX4WA:b-k5cyjm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/71d3579f648d42d214afe8c3017276ff01f7962b/.github/workflows/ci.yml#L116)):*
> ```YAML
>       - name: Setup WASM cache
>         uses: actions/cache@v4
>         if: ${{ matrix.wasm-cache }}
> ```

Why do you remove all those ifs?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/791)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`.github/workflows/ci.yml` line 116 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/791#-NswwI0U6xP0c8zBX4W9:-Nsx2B_kEvhjegql3lNO:b60vt9w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/71d3579f648d42d214afe8c3017276ff01f7962b/.github/workflows/ci.yml#L116)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why do you remove all those ifs?
</blockquote></details>

Because of 2 reasons. 
1) Some ifs are always  - true
2) We use a common cache for all subcommands, so no need to make it optional

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/791)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
