### PR TITLE
Add github/CODEOWNERS file with the list of default reviewers

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/178)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/178)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/178#-NBxA1jZ6uI0F-4Zf48y:-NBxA1jZ6uI0F-4Zf48z:b-bnqeza) (no related file):*
If everyone is fine I will add the same file to crust

___

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/178)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @miladz68)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/178)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/178)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

**Pull request merged**
