### PR TITLE
added base64 encoding support to publick key type

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/115)

### CODE REVIEW

**Review by oliverasistemas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/115)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/types/key.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/115#-N88xjrt-_XpcAZV-5Iq:-N88xjrt-_XpcAZV-5Ir:b-99tqhd) ([raw file](https://github.com/coreumfoundation/coreum/blob/c218f0f6a85d6f9bc14885502d679aeb28202f2b/pkg/types/key.go#L30)):*
> ```Go
> // EncodeBase64 returns base64 encoded string representation
> func (s *Secp256k1PublicKey) EncodeBase64() string {
> 	return base64.RawStdEncoding.EncodeToString(*s)
> ```

I am not seeing where these functions are used?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/115)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @xlab, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/115)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @xlab)

___
*[`pkg/types/key.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/115#-N88xjrt-_XpcAZV-5Iq:-N8x7TX73AImUEZC2Y2s:b77mo29) ([raw file](https://github.com/coreumfoundation/coreum/blob/c218f0f6a85d6f9bc14885502d679aeb28202f2b/pkg/types/key.go#L30)):*
<details><summary><i>Previously, oliverasistemas (Adolfo Olivera) wrote…</i></summary><blockquote>

I am not seeing where these functions are used?
</blockquote></details>

It is probably to be used in crust but lets wait for @miladz68 response

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/115)* status: all files reviewed, 1 unresolved discussion (waiting on @xlab)

___
*[`pkg/types/key.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/115#-N88xjrt-_XpcAZV-5Iq:-N95QL3x5L4vsTeSvqQd:bcixeo5) ([raw file](https://github.com/coreumfoundation/coreum/blob/c218f0f6a85d6f9bc14885502d679aeb28202f2b/pkg/types/key.go#L30)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

It is probably to be used in crust but lets wait for @miladz68 response
</blockquote></details>

the idea was to use base64 encoded addresses in faucet, crust and network config. But with the input @xlab provided, I used addresses, and it seems the be the more correct way. 

So I will close this PR.

**Pull request closed without merging**
