### PR TITLE
Add funding-mnemonic and staker-mnemonics integration tests args.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/199)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/199)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/integration_test.go` line 42 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/199#-NCxpEST5WC3m2Vw2K2-:-NCxpEST5WC3m2Vw2K20:b-ujp0nf) ([raw file](https://github.com/coreumfoundation/coreum/blob/88f8270d57de3ee55d12236202c30fe2035ccc59/integration-tests/integration_test.go#L42)):*
> ```Go
> 
> 	flag.StringVar(&coredAddress, "cored-address", "tcp://localhost:26657", "Address of cored node started by znet")
> 	flag.StringVar(&fundingPrivKey, "priv-key", "LPIPcUDVpp8Cn__g-YMntGts-DfDbd2gKTcgUgqSLfY", "Base64-encoded private key used to fund accounts required by tests")
> ```

Please add a FIXME here to remove this flag later
___
*[`integration-tests/integration_test.go` line 45 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/199#-NCxpJxH3IVOfEM7LCpD:-NCxpJxH3IVOfEM7LCpE:bwe8on4) ([raw file](https://github.com/coreumfoundation/coreum/blob/88f8270d57de3ee55d12236202c30fe2035ccc59/integration-tests/integration_test.go#L45)):*
> ```Go
> 	// TODO (dhil) those values are needed here for the backward compatibility of the crust, during the migration from priv keys to mnemonics
> 	flag.StringVar(&fundingMnemonic, "funding-mnemonic", "", "Funding account mnemonic required by tests")
> 	flag.StringVar(&stakerMnemonics, "staker-mnemonics", "", "Comma separated staker accounts mnemonics required by tests")
> ```

Use `StringsSliceVar` instead to be able to provide them like this:
```
--staker-mnemonic="..." --staker-mnemonic="..." --staker-mnemonic="..."
```

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/199)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/199)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/integration_test.go` line 42 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/199#-NCxpEST5WC3m2Vw2K2-:-NCxtw8j7vnLalaKimH0:b-9g0yz2) ([raw file](https://github.com/coreumfoundation/coreum/blob/88f8270d57de3ee55d12236202c30fe2035ccc59/integration-tests/integration_test.go#L42)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please add a FIXME here to remove this flag later
</blockquote></details>

No need, one comment covers all.
___
*[`integration-tests/integration_test.go` line 45 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/199#-NCxpJxH3IVOfEM7LCpD:-NCy6_TT-SLm2NhOwZtr:bl2cmvv) ([raw file](https://github.com/coreumfoundation/coreum/blob/88f8270d57de3ee55d12236202c30fe2035ccc59/integration-tests/integration_test.go#L45)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Use `StringsSliceVar` instead to be able to provide them like this:
```
--staker-mnemonic="..." --staker-mnemonic="..." --staker-mnemonic="..."
```
</blockquote></details>

I've not found the default flags parser like this. I can write my own:

```go
type stringsFlag []string

func (i *stringsFlag) String() string {
    return strings.Join(i,",")
}

func (i *stringsFlag) Set(value string) error {
    *i = append(*i, value)
    return nil
}
```

And the usage will be

```go
flag.Var(&stakerMnemonics, "staker-mnemonics", "Comma separated staker accounts mnemonics required by tests")
```

Does it worth it?

And the implementation on the crust side will be more complicated as well.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/199)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/integration_test.go` line 45 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/199#-NCxpJxH3IVOfEM7LCpD:-NCy9nq1ChCd3Rr-CMvO:bmamsom) ([raw file](https://github.com/coreumfoundation/coreum/blob/88f8270d57de3ee55d12236202c30fe2035ccc59/integration-tests/integration_test.go#L45)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I've not found the default flags parser like this. I can write my own:

```go
type stringsFlag []string

func (i *stringsFlag) String() string {
    return strings.Join(i,",")
}

func (i *stringsFlag) Set(value string) error {
    *i = append(*i, value)
    return nil
}
```

And the usage will be

```go
flag.Var(&stakerMnemonics, "staker-mnemonics", "Comma separated staker accounts mnemonics required by tests")
```

Does it worth it?

And the implementation on the crust side will be more complicated as well.

</blockquote></details>

Updated the code with it, check it now.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/199)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/integration_test.go` line 42 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/199#-NCxpEST5WC3m2Vw2K2-:-NCyNymXAr51nnwWvPXK:bsw2pie) ([raw file](https://github.com/coreumfoundation/coreum/blob/88f8270d57de3ee55d12236202c30fe2035ccc59/integration-tests/integration_test.go#L42)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

No need, one comment covers all.
</blockquote></details>

so put it one line above :-)
___
*[`integration-tests/integration_test.go` line 45 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/199#-NCxpJxH3IVOfEM7LCpD:-NCyNLGNA_z-T1wp7ObQ:buikytz) ([raw file](https://github.com/coreumfoundation/coreum/blob/88f8270d57de3ee55d12236202c30fe2035ccc59/integration-tests/integration_test.go#L45)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated the code with it, check it now.
</blockquote></details>

ahh yea... because this testing framework uses `flag`, not `'pflag`. That's one of the reasons why I originally didn't want to use `go test` framework to run integration tests.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/199)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/integration_test.go` line 42 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/199#-NCxpEST5WC3m2Vw2K2-:-NCyoUld52Rj1xfr1uSN:bvec8ba) ([raw file](https://github.com/coreumfoundation/coreum/blob/88f8270d57de3ee55d12236202c30fe2035ccc59/integration-tests/integration_test.go#L42)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

so put it one line above :-)
</blockquote></details>

I don't need, I'll do it, so I remember :-)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/199)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @ysv)

**Pull request merged**
