### PR TITLE
added query to list burnt NFTs

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/521)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/521)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/query.proto` line 129 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/521#-NXUQSHG6INjrkzXKSp0:-NXUQSHG6INjrkzXKSp1:b-35xlgk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6ca9f85e7f6fcf53e5dd60e1fc89344ceb0f6107/proto/coreum/asset/nft/v1/query.proto#L129)):*
> ```proto
> }
> 
> message QueryBurntNFTsInClassRequest {
> ```

@wojtek-coreum @ysv 
Do we need them both or we can keep only `QueryBurntNFTs` with both `class_id` and `nft_id` (optional) attributes?  So if you query for both and the result is empty then it isn't burnt. 
___
*[`x/asset/nft/keeper/grpc_query.go` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/521#-NXUPL7T0bNrpstVkCg9:-NXUPL7T0bNrpstVkCgA:b-d7yww5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6ca9f85e7f6fcf53e5dd60e1fc89344ceb0f6107/x/asset/nft/keeper/grpc_query.go#L23)):*
> ```Go
> 	IsWhitelisted(ctx sdk.Context, classID, nftID string, account sdk.AccAddress) (bool, error)
> 	GetWhitelistedAccountsForNFT(ctx sdk.Context, classID, nftID string, q *query.PageRequest) ([]string, *query.PageResponse, error)
> 	ListBurnt(ctx sdk.Context, classID string, q *query.PageRequest) (*query.PageResponse, []string, error)
> ```

The name is different from the style we followed before.
I propose:
ListBurnt - >GetBurnt
___
*[`x/asset/nft/types/keys.go` line 114 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/521#-NXUQMynDyGByIy5q7ky:-NXUQMynDyGByIy5q7kz:b-5mi4t2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6ca9f85e7f6fcf53e5dd60e1fc89344ceb0f6107/x/asset/nft/types/keys.go#L114)):*
> ```Go
> 
> // CreateClassBurningKey constructs the key for the burning of non-fungible token.
> func CreateClassBurningKey(classID string) ([]byte, error) {
> ```

You can use it in the `CreateBurningKey` as well.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/521)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/521)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/query.proto` line 129 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/521#-NXUQSHG6INjrkzXKSp0:-NXiMMB67JXPv9EKlFD0:bh87nvt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6ca9f85e7f6fcf53e5dd60e1fc89344ceb0f6107/proto/coreum/asset/nft/v1/query.proto#L129)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@wojtek-coreum @ysv 
Do we need them both or we can keep only `QueryBurntNFTs` with both `class_id` and `nft_id` (optional) attributes?  So if you query for both and the result is empty then it isn't burnt. 
</blockquote></details>

We already discussed this and decided to go with separate queries. 
___
*[`x/asset/nft/keeper/grpc_query.go` line 23 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/521#-NXUPL7T0bNrpstVkCg9:-NXiMmmOClO9WM_TLVhG:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6ca9f85e7f6fcf53e5dd60e1fc89344ceb0f6107/x/asset/nft/keeper/grpc_query.go#L23)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The name is different from the style we followed before.
I propose:
ListBurnt - >GetBurnt
</blockquote></details>

Done.
___
*[`x/asset/nft/types/keys.go` line 114 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/521#-NXUQMynDyGByIy5q7ky:-NXiN5YNDjnJD2iLBHgK:ba75p3g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6ca9f85e7f6fcf53e5dd60e1fc89344ceb0f6107/x/asset/nft/types/keys.go#L114)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You can use it in the `CreateBurningKey` as well. 
</blockquote></details>

Doing that will append key length twice. we will need to introduce another helper function to do that properly, which is overkill.

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/521)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/521)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`proto/coreum/asset/nft/v1/query.proto` line 120 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/521#-NXpKHMb8CsiSGkrF6WY:-NXpKHMb8CsiSGkrF6WZ:b-j2xh1w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8d91bd9dc1f5150119a21e7a250972061ae62673/proto/coreum/asset/nft/v1/query.proto#L120)):*
> ```proto
> }
> 
> message QueryBurntNFTRequest {
> ```

What do you think about naming it `QueryIsNFTBurntRequest` and name it accordingly everywhere: `IsNFTBurnt` including query service etc

if you disagree I will resolve & approve

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/521)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/query.proto` line 120 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/521#-NXpKHMb8CsiSGkrF6WY:-NXtJQL1BSwNI842VRG6:bue7v75) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8d91bd9dc1f5150119a21e7a250972061ae62673/proto/coreum/asset/nft/v1/query.proto#L120)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

What do you think about naming it `QueryIsNFTBurntRequest` and name it accordingly everywhere: `IsNFTBurnt` including query service etc

if you disagree I will resolve & approve
</blockquote></details>

I don't have a strong opinion here, I also thought about it before and also here and I kind of agree with it. But I in the past I used `IsWhitelisted` and `IsFrozen` in previous queries and the result of the discussion was not to use `Is` prefix. So to follow on the same style I did not use `Is` Prefix.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/521)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/query.proto` line 120 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/521#-NXpKHMb8CsiSGkrF6WY:-NXtSbneACJVJrAfBosi:b236mb3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8d91bd9dc1f5150119a21e7a250972061ae62673/proto/coreum/asset/nft/v1/query.proto#L120)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't have a strong opinion here, I also thought about it before and also here and I kind of agree with it. But I in the past I used `IsWhitelisted` and `IsFrozen` in previous queries and the result of the discussion was not to use `Is` prefix. So to follow on the same style I did not use `Is` Prefix.
</blockquote></details>

I also removed is prefix from the field to completely match the previous style.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/521)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/521)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
