### PR TITLE
Set commit timeout to 0.5s for IBC tests

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/857)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/857)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @masihyeganeh, @miladz68, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/857)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/857#-Nz3DWHO8VYbjStj_Sqg:-Nz3DWHO8VYbjStj_Sqh:b-k14zf8) (no related file):*
Did you try to make it even faster?

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/857)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/857#-Nz3DWHO8VYbjStj_Sqg:-Nz3IfQSDcRE0R2chnwf:b5jwtou) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Did you try to make it even faster?
</blockquote></details>

no, the task was about setting it to 0.5s :-)

___

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/857)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh, @miladz68, and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/857)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/857)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
