### PR TITLE
Foundation for storing integration tests next to the code

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/122)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/122)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8cy7jk1Law1XDetuAu:-N8cy7jl8S4Z23ujYehv:b-x2fe53) (no related file):*
Keep in mind that this code:

```go
// T is an interface wrapper around *testing.T
type T interface {
	Errorf(format string, args ...interface{})
	FailNow()
}

// PrepareFunc defines function which is executed before environment is deployed
type PrepareFunc func(ctx context.Context) error

// RunFunc defines function which is responsible for running the test
type RunFunc func(ctx context.Context, t T)
```

will be used by all the tests in all the repos so maybe it's worth putting it in `coreum-tools`

___

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/122)* status: all files reviewed, 4 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`tests/bank/transfer.go` line 22 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8heaT94JuYAO5xltp9:-N8heaT94JuYAO5xltpA:bbz4k49) ([raw file](https://github.com/coreumfoundation/coreum/blob/c01e9ea6bc420348340ade2990031977de94446c/tests/bank/transfer.go#L22)):*
> ```Go
> 	return func(ctx context.Context) error {
> 			return chain.Network.FundAccount(wallet.Key.PubKey(),
> 				testing.MustCoin(types.NewCoin(big.NewInt(100), chain.Network.TokenSymbol())).String())
> ```

check for error and return, do not use panic.
___
*[`tests/testing/helpers.go` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8hfbqkEJiSRkRAYBQB:-N8hfbqkEJiSRkRAYBQC:bckuoz3) ([raw file](https://github.com/coreumfoundation/coreum/blob/c01e9ea6bc420348340ade2990031977de94446c/tests/testing/helpers.go#L11)):*
> ```Go
> func RandomWallet() types.Wallet {
> 	_, privKey := types.GenerateSecp256k1Key()
> 	return types.Wallet{Name: rnd.GetRandomName(), Key: privKey}
> ```

`GetRandomName` is overkill for testing, just use address or whatever. it adds around 900 lines of code with no utility.
___
*[`tests/testing/helpers.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8hewCL9b_kvGc59R-D:-N8hewCL9b_kvGc59R-E:b-jn4mf9) ([raw file](https://github.com/coreumfoundation/coreum/blob/c01e9ea6bc420348340ade2990031977de94446c/tests/testing/helpers.go#L15)):*
> ```Go
> 
> // MustCoin panics if `err` is not nil, returns `coin` otherwise
> func MustCoin(coin types.Coin, err error) types.Coin {
> ```

this should be removed, panics are undesirable in tests.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/122)* status: all files reviewed, 6 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8cy7jk1Law1XDetuAu:-N8hb7lC5n520C0iwXC1:b-45h4yh) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Keep in mind that this code:

```go
// T is an interface wrapper around *testing.T
type T interface {
	Errorf(format string, args ...interface{})
	FailNow()
}

// PrepareFunc defines function which is executed before environment is deployed
type PrepareFunc func(ctx context.Context) error

// RunFunc defines function which is responsible for running the test
type RunFunc func(ctx context.Context, t T)
```

will be used by all the tests in all the repos so maybe it's worth putting it in `coreum-tools`
</blockquote></details>

me & Milad:
1. Why do we need `type T` isn't it better to just use testing.T instead ?

2. it doesn't make sense for use to have PrepareFunc & RunFunc here defined as a public type. Our idea is to just define them as private type alias `prepareFunc = func(ctx context.Context) error` just for shorter testing funcs signature. And if needed we can define PrepareFunc method in crust

___
___
*[`tests/index.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8hgNNrAY8-Lz6fPfqj:-N8hgNNrAY8-Lz6fPfqk:blglrk9) ([raw file](https://github.com/coreumfoundation/coreum/blob/c01e9ea6bc420348340ade2990031977de94446c/tests/index.go#L1)):*
> ```Go
> package tests
> ```

we also think that this folder should be named not just tests but tests/integration or smth similar to clarify that it is not just unit test which are will also be in repo
___
*[`tests/testing/helpers.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8heyuyACybHRQrGPis:-N8heyuyACybHRQrGPit:bd6086b) ([raw file](https://github.com/coreumfoundation/coreum/blob/c01e9ea6bc420348340ade2990031977de94446c/tests/testing/helpers.go#L1)):*
> ```Go
> package testing
> ```

do we understand you correctly that idea of creating `./testing` under tests is to group all functionality which is not actual testing but various test utilities ?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/122)* status: all files reviewed, 6 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`tests/index.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8hgNNrAY8-Lz6fPfqj:-N8hh68C7mBBLaoG_d5W:bl9vbvg) ([raw file](https://github.com/coreumfoundation/coreum/blob/c01e9ea6bc420348340ade2990031977de94446c/tests/index.go#L1)):*
> tests/integration
Or could be integration-tests

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/122)* status: all files reviewed, 6 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8cy7jk1Law1XDetuAu:-N8hoYdn77StQetC9gWD:bkphi9g) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

me & Milad:
1. Why do we need `type T` isn't it better to just use testing.T instead ?

2. it doesn't make sense for use to have PrepareFunc & RunFunc here defined as a public type. Our idea is to just define them as private type alias `prepareFunc = func(ctx context.Context) error` just for shorter testing funcs signature. And if needed we can define PrepareFunc method in crust


</blockquote></details>

Ad.1. I don't understand. `type T` is `testing.T`. If you mean `testing.T` from crust then it require importing crust in coreum which we want to avoid

Ad.2. 
- `TestSet` is a public type imported by `crust` from `coreum`
- It means that `SingleChainSignature` must be public
- It means that PrepareFunc and RunFunc must be public too.

I could define `SingleChainSignature func(chain Chain) (PrepareFunc, RunFunc)`
as `SingleChainSignature func(chain Chain) (func(ctx context.Context) error, func(ctx context.Context, t T))`
instead, but it is much less readable.

___
___
*[`tests/testing/helpers.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8heyuyACybHRQrGPis:-N8hpSOz4BmHuJYx1Nan:by0jdeq) ([raw file](https://github.com/coreumfoundation/coreum/blob/c01e9ea6bc420348340ade2990031977de94446c/tests/testing/helpers.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we understand you correctly that idea of creating `./testing` under tests is to group all functionality which is not actual testing but various test utilities ?
</blockquote></details>

yes, it contains types and helpers required for the testing infrastructure. As I mentioned in the comment at the top, most of them will be required by integration tests in other products so maybe they should be moved to some common place

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/122)* status: 0 of 6 files reviewed, 6 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`tests/testing/helpers.go` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8hfbqkEJiSRkRAYBQB:-N8htX7B3HQuBc7F50Mt:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/c01e9ea6bc420348340ade2990031977de94446c/tests/testing/helpers.go#L11)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

`GetRandomName` is overkill for testing, just use address or whatever. it adds around 900 lines of code with no utility.
</blockquote></details>

Done.
___
*[`tests/testing/helpers.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8hewCL9b_kvGc59R-D:-N8htXWT1gKeUbyNjsjw:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/c01e9ea6bc420348340ade2990031977de94446c/tests/testing/helpers.go#L15)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this should be removed, panics are undesirable in tests.
</blockquote></details>

Done.
___
*[`tests/index.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8hgNNrAY8-Lz6fPfqj:-N8hta2J7XU6juIoqxGd:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/c01e9ea6bc420348340ade2990031977de94446c/tests/index.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

> tests/integration
Or could be integration-tests
</blockquote></details>

Done.
___
*[`tests/bank/transfer.go` line 22 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8heaT94JuYAO5xltp9:-N8htW3u7DbteN3WK6ri:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/c01e9ea6bc420348340ade2990031977de94446c/tests/bank/transfer.go#L22)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

check for error and return, do not use panic.
</blockquote></details>

Done.

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/122)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8cy7jk1Law1XDetuAu:-N8hux0a7-fggXhHIzS-:bdge969) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ad.1. I don't understand. `type T` is `testing.T`. If you mean `testing.T` from crust then it require importing crust in coreum which we want to avoid

Ad.2. 
- `TestSet` is a public type imported by `crust` from `coreum`
- It means that `SingleChainSignature` must be public
- It means that PrepareFunc and RunFunc must be public too.

I could define `SingleChainSignature func(chain Chain) (PrepareFunc, RunFunc)`
as `SingleChainSignature func(chain Chain) (func(ctx context.Context) error, func(ctx context.Context, t T))`
instead, but it is much less readable.
</blockquote></details>

1. 
```
type T interface {
	require.TestingT
	//Errorf(format string, args ...interface{})
	//FailNow()
}
```
2. discussed on the call lets proceed with private alias to the type

___

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/122)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/122#-:-N8hxJUsAZm9VRDulYk3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, and @xlab)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/122)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8cy7jk1Law1XDetuAu:-N8i0Y3D6hN6R9eGBnIU:buv4dkv) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1. 
```
type T interface {
	require.TestingT
	//Errorf(format string, args ...interface{})
	//FailNow()
}
```
2. discussed on the call lets proceed with private alias to the type
</blockquote></details>

2. Now I see that those types and tests live in different packages so they must be exported anyway

___

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, and @xlab)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/122)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`integration-tests/bank/transfer.go` line 19 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8i1lSp17huVVOGwims:-N8i1lSq6cyncRRNrb6M:b-qqnwg) ([raw file](https://github.com/coreumfoundation/coreum/blob/cf518ac875c0083590e1d3854e1c766ec8a5efa3/integration-tests/bank/transfer.go#L19)):*
> ```Go
> 	wallet := testing.RandomWallet()
> 
> 	// First returned value is the slice of objects representing prerequisites for the test
> ```

fix the comment
___
*[`integration-tests/testing/types.go` line 17 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8i1wnd5tAX3JqRc5Ux:-N8i1wnd5tAX3JqRc5Uy:b-f78gv6) ([raw file](https://github.com/coreumfoundation/coreum/blob/cf518ac875c0083590e1d3854e1c766ec8a5efa3/integration-tests/testing/types.go#L17)):*
> ```Go
> 
> // PrepareFunc defines function which is executed before environment is deployed
> type PrepareFunc func(ctx context.Context) error
> ```

if we want to do this using type alias it should be `type PrepareFunc = type PrepareFunc func(ctx context.Context) error`

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/122)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`integration-tests/bank/transfer.go` line 19 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8i1lSp17huVVOGwims:-N8i3DWsBU-kJMHmdrsb:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/cf518ac875c0083590e1d3854e1c766ec8a5efa3/integration-tests/bank/transfer.go#L19)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

fix the comment
</blockquote></details>

Done.
___
*[`integration-tests/testing/types.go` line 11 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8i2IjcDWeBze-SuyUG:-N8i4JY037QbJF2mKer6:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/cf518ac875c0083590e1d3854e1c766ec8a5efa3/integration-tests/testing/types.go#L11)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1. this change is still missing
```
type T interface {
	require.TestingT
	//Errorf(format string, args ...interface{})
	//FailNow()
}
```

2. `// T is an interface wrapper around *testing.T` comment is sort of confusing because when I see testing.T I expect std library testing pkg
</blockquote></details>

Done.
___
*[`integration-tests/testing/types.go` line 17 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/122#-N8i1wnd5tAX3JqRc5Ux:-N8i2tXrAfbkCRSCv-1u:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/cf518ac875c0083590e1d3854e1c766ec8a5efa3/integration-tests/testing/types.go#L17)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

if we want to do this using type alias it should be `type PrepareFunc = type PrepareFunc func(ctx context.Context) error`
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, and @xlab)

**Pull request merged**
