### PR TITLE
Add new queries and messages to the wasm handler and contracts

### PR DESCRIPTION
**Pull request by keyleu**
# Description

- Added URI and URIHash to the AssetFT contract and tested.
- Made BurnRate and CommissionRate not optional (they must be sent always anyways or it will return an error).
- Added all new AssetNFT messages and queries to the wasm handler. Modified the contract to include them all and wrote tests for each one.
- Modified coreum wasm sdk to include all new messages.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/699)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/699)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> Reviewed 8 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/699)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 7 of 12 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/699)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/699)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Pull request merged**
