### PR TITLE
add more deterministic gas types for staking module

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/235)

### CODE REVIEW

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/235)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/235)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/staking/staking.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/235#-NEkQSv44Kh3wOxB4W2v:-NEkQSv596xs9-Mg_Cyw:b-dbmx19) ([raw file](https://github.com/coreumfoundation/coreum/blob/667dd7365cfe5ed3c4bd16fb25e120fae7955000/integration-tests/staking/staking.go#L41)):*
> ```Go
> 		1,
> 		sdk.NewInt(0),
> 	)).Add(testing.ComputeNeededBalance(
> ```

GasLimitByMsgs consumes the vararg of messages so you can pass them all.



_Code quote:_
```Go
GasLimitByMsgs
```
___
*[`integration-tests/staking/staking.go` line 65 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/235#-NEkR70P0XjK8XavF4aP:-NEkR70P0XjK8XavF4aQ:bahvwtx) ([raw file](https://github.com/coreumfoundation/coreum/blob/667dd7365cfe5ed3c4bd16fb25e120fae7955000/integration-tests/staking/staking.go#L65)):*
> ```Go
> 	// Edit Validator
> 	editValidatorMsg := &stakingtypes.MsgEditValidator{
> 		Description:      stakingtypes.Description{Details: "updated Details"},
> ```

Baybe var or constant for that value "updated Details" ?



_Code quote:_
```Go
upda
```
___
*[`integration-tests/staking/staking.go` line 78 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/235#-NEkRJJn6w365SXoZgpi:-NEkRJJn6w365SXoZgpj:b-juwklj) ([raw file](https://github.com/coreumfoundation/coreum/blob/667dd7365cfe5ed3c4bd16fb25e120fae7955000/integration-tests/staking/staking.go#L78)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	resp, err := stakingClient.Validator(ctx, &stakingtypes.QueryValidatorRequest{
> ```

Didn't get the naming convention for the variables. In some places you can just "resp", in some  "ddResp" and so on. It would be nice to see all in the same style :-)
___
*[`integration-tests/staking/staking.go` line 84 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/235#-NEkQz7i4UQeWKZkTt-u:-NEkQz7i4UQeWKZkTt-v:b-q1thvs) ([raw file](https://github.com/coreumfoundation/coreum/blob/667dd7365cfe5ed3c4bd16fb25e120fae7955000/integration-tests/staking/staking.go#L84)):*
> ```Go
> 	require.NoError(t, err)
> 	assert.EqualValues(t, "updated Details", resp.GetValidator().Description.Details)
> 	assert.EqualValues(t, int64(chain.GasLimitByMsgs(editValidatorMsg)), editValidatorRes.GasUsed)
> ```

This asserion should be done just after the execution.
___
*[`integration-tests/staking/staking.go` line 129 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/235#-NEkQqaG4UTFkGpf0Tlt:-NEkQqaG4UTFkGpf0Tlu:b9shsjp) ([raw file](https://github.com/coreumfoundation/coreum/blob/667dd7365cfe5ed3c4bd16fb25e120fae7955000/integration-tests/staking/staking.go#L129)):*
> ```Go
> 
> 	require.NoError(t, err)
> 	assert.Equal(t, int64(chain.GasLimitByMsgs(redelegateMsg)), redelegateResult.GasUsed)
> ```

This assetiong should be done after the execution

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/235)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/staking/staking.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/235#-NEkQSv44Kh3wOxB4W2v:-NEoDX2cBx0vKlkHsFIr:bkdhbp5) ([raw file](https://github.com/coreumfoundation/coreum/blob/667dd7365cfe5ed3c4bd16fb25e120fae7955000/integration-tests/staking/staking.go#L41)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

GasLimitByMsgs consumes the vararg of messages so you can pass them all.
</blockquote></details>

that is design for scenarios where there are multiple messages in a single tx, so it would not be that accurate if we use that. 
___
*[`integration-tests/staking/staking.go` line 65 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/235#-NEkR70P0XjK8XavF4aP:-NEoDjTn4zVu7W44Qpk5:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/667dd7365cfe5ed3c4bd16fb25e120fae7955000/integration-tests/staking/staking.go#L65)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Baybe var or constant for that value "updated Details" ?
</blockquote></details>

Done.
___
*[`integration-tests/staking/staking.go` line 78 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/235#-NEkRJJn6w365SXoZgpi:-NEoE8HR12YWhdjvHSAW:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/667dd7365cfe5ed3c4bd16fb25e120fae7955000/integration-tests/staking/staking.go#L78)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Didn't get the naming convention for the variables. In some places you can just "resp", in some  "ddResp" and so on. It would be nice to see all in the same style :-)
</blockquote></details>

Done.
___
*[`integration-tests/staking/staking.go` line 84 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/235#-NEkQz7i4UQeWKZkTt-u:-NEoEGhGDAnyjmwYTaJR:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/667dd7365cfe5ed3c4bd16fb25e120fae7955000/integration-tests/staking/staking.go#L84)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This asserion should be done just after the execution.
</blockquote></details>

Done.
___
*[`integration-tests/staking/staking.go` line 129 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/235#-NEkQqaG4UTFkGpf0Tlt:-NEoEPU042Jv52aITWFF:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/667dd7365cfe5ed3c4bd16fb25e120fae7955000/integration-tests/staking/staking.go#L129)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This assetiong should be done after the execution
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/235)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/staking/staking.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/235#-NEkQSv44Kh3wOxB4W2v:-NEovnHU0RWnTgx5agEs:b-90b45v) ([raw file](https://github.com/coreumfoundation/coreum/blob/667dd7365cfe5ed3c4bd16fb25e120fae7955000/integration-tests/staking/staking.go#L41)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

that is design for scenarios where there are multiple messages in a single tx, so it would not be that accurate if we use that. 
</blockquote></details>

Ok, leave it as is.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/235)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/235)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
