### PR TITLE
Added more characters for NFT class symbol and NFT ID

### PR DESCRIPTION
**Pull request by miladz68**
# Description
This PR allows extends the NFT class symbol and NFT ID validation to allow more characters.
# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/700)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/700)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`x/asset/nft/types/token.go` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/700#-Ni5WELbDkiF63NlayiF:-Ni5WELbDkiF63NlayiG:bh3frz5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4d85e12da63423ec44adbd336af19f9207e2e69d/x/asset/nft/types/token.go#L20)):*
> ```Go
> 	// the address length might be up to 66 symbols and the demon length must be less than 101
> 	// this leaves room for 33 characters, but we round it down to 30 to be conservative.
> 	nftSymbolRegexStr = `^[a-zA-Z][a-zA-Z0-9/:._]{0,30}$`
> ```

depending on our decision for FT we should either allow or disallow `/` here

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/700)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/types/token.go` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/700#-Ni5WELbDkiF63NlayiF:-Ni8Nq3qBPXPSciPX8XK:b-v8ehny) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4d85e12da63423ec44adbd336af19f9207e2e69d/x/asset/nft/types/token.go#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

depending on our decision for FT we should either allow or disallow `/` here
</blockquote></details>

well I think it is safe for FT, but let's discuss it there.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/700)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/700)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
