### PR TITLE
Bump up wasmd to v0.30.0 and cosmos-sdk to v0.45.11

### PR DESCRIPTION
**Pull request by dzmitryhil**
* Bump up new versions
* Remove ignite dependency
* Bump up IBC version to 4th

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/304)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/304)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/304)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

___
*[`go.mod` line 16 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/304#-NJkElaq8TBwY9ZzrrpD:-NJkElaq8TBwY9ZzrrpE:bizk1ih) ([raw file](https://github.com/coreumfoundation/coreum/blob/630572d7777d56723cd3ae1dad37dc1b2a6bb61b/go.mod#L16)):*
> ```XML
> 	github.com/cosmos/cosmos-sdk v0.45.9
> 	github.com/cosmos/go-bip39 v1.0.0
> 	github.com/cosmos/ibc-go/v3 v3.3.0
> ```

do we also need to briefly review diff between ibc v3 vs v4 ?
___
*[`app/openapi/console.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/304#-NJkPNgh1L3bBGOILcnc:-NJkPNgh1L3bBGOILcnd:b3w81ip) ([raw file](https://github.com/coreumfoundation/coreum/blob/b966f9c54ced60f8342e212a39e1faaff72d90c6/app/openapi/console.go#L1)):*
> ```Go
> package openapi
> ```

is it a generic code copied from somewhere ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/304)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`go.mod` line 16 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/304#-NJkElaq8TBwY9ZzrrpD:-NJndqFVEd6BHLJ9XzL9:bx5b4uj) ([raw file](https://github.com/coreumfoundation/coreum/blob/630572d7777d56723cd3ae1dad37dc1b2a6bb61b/go.mod#L16)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we also need to briefly review diff between ibc v3 vs v4 ?
</blockquote></details>

Actually we just need to properly investigate the v4 once we integrate it fully.
___
*[`app/openapi/console.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/304#-NJkPNgh1L3bBGOILcnc:-NJne3agDwVDBes7ZHPY:b-rq6ofn) ([raw file](https://github.com/coreumfoundation/coreum/blob/b966f9c54ced60f8342e212a39e1faaff72d90c6/app/openapi/console.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it a generic code copied from somewhere ?
</blockquote></details>

It's copied from the ignite, but it's so simple so I decided not to add the reference.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/304)* status: all files reviewed, 2 unresolved discussions (waiting on @ysv)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/304)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Pull request merged**
