### PR TITLE
Integrate the DEX settings creation and update to the assetft.

### PR DESCRIPTION
**Pull request by dzmitryhil**
Integrate the DEX settings creation and update to the assetft.

* Extend the token issuance with optional DEX settings
* Extend Token and Tokens queries with the DEX settings
* Add MsgUpdateDEXSettings to update the DEX setting with the deterministic gas support.
* Add DEXSettings query to query the settings independently of the token (will be needed for the not assetft tokens)
* Update genesis export/import
* Add/Update corresponding CLIs
* Add integration tests

# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/934)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/934)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

___
*[`x/deterministicgas/config.go` line 95 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/934#-O5No90a1b0W_XAd7XlT:-O5No90a1b0W_XAd7XlU:b3hvydt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e528258d8985546614f50e3756d765ad6f79d9d1/x/deterministicgas/config.go#L95)):*
> ```Go
> 		// TODO(v5): Once we add a new token upgrade MsgUpgradeTokenV2 we should remove this one and re-estimate gas.
> 		MsgToMsgURL(&assetfttypes.MsgUpgradeTokenV1{}):    constantGasFunc(25_000),
> 		MsgToMsgURL(&assetfttypes.MsgUpdateDEXSettings{}): constantGasFunc(10_000),
> ```

I think we usuall make these undeterministic since it might have listings in future. double check it please.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/934)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`x/deterministicgas/config.go` line 95 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/934#-O5No90a1b0W_XAd7XlT:-O5NsCXj-fhos8P68sj6:b-qpgrz6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e528258d8985546614f50e3756d765ad6f79d9d1/x/deterministicgas/config.go#L95)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think we usuall make these undeterministic since it might have listings in future. double check it please.
</blockquote></details>

This operation is simple write to the state.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/934)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 30 of 30 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/934)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
