### PR TITLE
Enable & partially configure coreum-mainnet-1 network

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/409)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/409)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/409)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`pkg/config/network.go` line 109 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/409#-NP1DDB2-vZpsfGLLqXa:-NP28msW7siLmI8VPVqk:b5g9lyx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e89e45cd2056551228927a98002333ccabac1df7/pkg/config/network.go#L109)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I think it still should be disabled
</blockquote></details>

no
I need it to be enabled because this binary will be used by management to generate keys & addresses to sign txs. 
___
*[`pkg/config/network.go` line 314 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/409#-NP1DYzJ95hPIk8NO44i:-NP29UzM846xOBd9zqOV:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72faf7cc6ec032d6fe83dfb2d09d81f0f941077c/pkg/config/network.go#L314)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If there is no `Enabled` flag then this function name makes no sense
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/409)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`pkg/config/network.go` line 314 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/409#-NP1DYzJ95hPIk8NO44i:-NP2QhzF00998dU4M_Mb:bacpaip) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72faf7cc6ec032d6fe83dfb2d09d81f0f941077c/pkg/config/network.go#L314)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There are still `enabledNetworks` in the body

**Review by miladz68 — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/409)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`pkg/config/network.go` line 314 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/409#-NP1DYzJ95hPIk8NO44i:-NP2_X-1BKbQ0hgrcpN9:bj24vqs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72faf7cc6ec032d6fe83dfb2d09d81f0f941077c/pkg/config/network.go#L314)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

There are still `enabledNetworks` in the body
</blockquote></details>

I think the whole networks function can be removed.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/409)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`pkg/config/network.go` line 314 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/409#-NP1DYzJ95hPIk8NO44i:-NP2jERr0ht_fMhr_0tA:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72faf7cc6ec032d6fe83dfb2d09d81f0f941077c/pkg/config/network.go#L314)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think the whole networks function can be removed. 
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/409)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/409)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/409)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Pull request merged**
