### PR TITLE
Action for creating a release containing built `cored` binary

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/204)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/204)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/release.yml` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXUUWCJ0cnA1boU5Q:-NDCXUUWCJ0cnA1boU5R:b9o7czp) ([raw file](https://github.com/coreumfoundation/coreum/blob/a4413252b0aed9da3c76b44294fe89907e368f2c/.github/workflows/release.yml#L3)):*
> ```YAML
> name: release
> on:
>   workflow_dispatch:
> ```

You can start the workflow if the tag starts with "v*"
```
on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0
```
___
*[`.github/workflows/release.yml` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXlty1wyBB1zMF3Iv:-NDCXlty1wyBB1zMF3Iw:bucfxi0) ([raw file](https://github.com/coreumfoundation/coreum/blob/a4413252b0aed9da3c76b44294fe89907e368f2c/.github/workflows/release.yml#L11)):*
> ```YAML
>       - name: Go version used to build crust tool
>         run: go version
>       - name: Setup go cache
> ```

Not sure about the cache, I would go without it at all.
___
*[`.github/workflows/release.yml` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXz5Y9hTyTg7-DeCJ:-NDCXz5Y9hTyTg7-DeCK:blqus05) ([raw file](https://github.com/coreumfoundation/coreum/blob/a4413252b0aed9da3c76b44294fe89907e368f2c/.github/workflows/release.yml#L49)):*
> ```YAML
>         with:
>           token: ${{ secrets.GITHUB_TOKEN }}
>           files: cored-${{ steps.tag.outputs.result }}-linux-amd64
> ```

I would keep the name same for all release.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/204)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/release.yml` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXUUWCJ0cnA1boU5Q:-NDCd6tVCINyGP9qXTSC:b-ag4qoo) ([raw file](https://github.com/coreumfoundation/coreum/blob/a4413252b0aed9da3c76b44294fe89907e368f2c/.github/workflows/release.yml#L3)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You can start the workflow if the tag starts with "v*"
```
on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0
```
</blockquote></details>

I know but do we want to do it automatically? For now I intentionally decided to allow only manual execution
___
*[`.github/workflows/release.yml` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXlty1wyBB1zMF3Iv:-NDCdFlg3SlUpN_ubbEc:b1sg25d) ([raw file](https://github.com/coreumfoundation/coreum/blob/a4413252b0aed9da3c76b44294fe89907e368f2c/.github/workflows/release.yml#L11)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not sure about the cache, I would go without it at all.
</blockquote></details>

I also would ignore the cache, done it only to avoid complains. @ysv If you agree I will remove cache
___
*[`.github/workflows/release.yml` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXz5Y9hTyTg7-DeCJ:-NDCdS2V1UUhC4tcMilN:bs23fmy) ([raw file](https://github.com/coreumfoundation/coreum/blob/a4413252b0aed9da3c76b44294fe89907e368f2c/.github/workflows/release.yml#L49)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would keep the name same for all release.
</blockquote></details>

I don't have an opinion. Both ways are ok for me. @ysv ?

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/204)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`.github/workflows/release.yml` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXUUWCJ0cnA1boU5Q:-NDCuBb_Ee9DfCTkZvQM:bmzydau) ([raw file](https://github.com/coreumfoundation/coreum/blob/81c754d2b1c1c735b2bfc2c686c4a7dec482a17e/.github/workflows/release.yml#L3)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I know but do we want to do it automatically? For now I intentionally decided to allow only manual execution
</blockquote></details>

does it have some sort of button to start manual execution ?
Can you show pls how it could be started ?
___
*[`.github/workflows/release.yml` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXlty1wyBB1zMF3Iv:-NDCu83_3zC5-i0FlPPN:bm1fqoa) ([raw file](https://github.com/coreumfoundation/coreum/blob/81c754d2b1c1c735b2bfc2c686c4a7dec482a17e/.github/workflows/release.yml#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I also would ignore the cache, done it only to avoid complains. @ysv If you agree I will remove cache
</blockquote></details>

I agree for releases we can ignore cache both go & docker
___
*[`.github/workflows/release.yml` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCvS4j2o3nL1vfoGqv:-NDCvS4j2o3nL1vfoGqw:bta03s) ([raw file](https://github.com/coreumfoundation/coreum/blob/81c754d2b1c1c735b2bfc2c686c4a7dec482a17e/.github/workflows/release.yml#L44)):*
> ```YAML
>           script: return context.ref.replace(/refs\/tags\//, '');
>       - name: Create asset
>         run: ln crust/bin/.cache/docker/cored/cored cored-${{ steps.tag.outputs.result }}-linux-amd64
> ```

is there a specific reason to use link instead of just copying it ?
___
*[`.github/workflows/release.yml` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXz5Y9hTyTg7-DeCJ:-NDCuqXoBVT5nGeTUfNM:b-c0wsv2) ([raw file](https://github.com/coreumfoundation/coreum/blob/81c754d2b1c1c735b2bfc2c686c4a7dec482a17e/.github/workflows/release.yml#L49)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't have an opinion. Both ways are ok for me. @ysv ?
</blockquote></details>

well id depends
Is it binary name or name of archive created ?
because of archive it makes sense to have version as for binary I don't have strong opinion

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/204)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/release.yml` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXz5Y9hTyTg7-DeCJ:-NDCvrBI9RGIogUXI_0x:b-ciuknx) ([raw file](https://github.com/coreumfoundation/coreum/blob/81c754d2b1c1c735b2bfc2c686c4a7dec482a17e/.github/workflows/release.yml#L49)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

well id depends
Is it binary name or name of archive created ?
because of archive it makes sense to have version as for binary I don't have strong opinion 
</blockquote></details>

The name of binary. So it should be the same.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/204)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/release.yml` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXUUWCJ0cnA1boU5Q:-NDDMfCB9TgP19SNVSUe:b-38g39e) ([raw file](https://github.com/coreumfoundation/coreum/blob/81c754d2b1c1c735b2bfc2c686c4a7dec482a17e/.github/workflows/release.yml#L3)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

does it have some sort of button to start manual execution ?
Can you show pls how it could be started ?
</blockquote></details>

https://github.com/CoreumFoundation/coreum/actions/workflows/ci.yml

There is "Run workflow" button in top-right corner. It will be the same for `release` once this PR is in master
___
*[`.github/workflows/release.yml` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXlty1wyBB1zMF3Iv:-NDDNVCWByErxt5vc0fZ:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/81c754d2b1c1c735b2bfc2c686c4a7dec482a17e/.github/workflows/release.yml#L11)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree for releases we can ignore cache both go & docker
</blockquote></details>

Done
___
*[`.github/workflows/release.yml` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCvS4j2o3nL1vfoGqv:-NDDME2j7WZXkzRq3mkL:b-wshhi4) ([raw file](https://github.com/coreumfoundation/coreum/blob/81c754d2b1c1c735b2bfc2c686c4a7dec482a17e/.github/workflows/release.yml#L44)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is there a specific reason to use link instead of just copying it ?
</blockquote></details>

creating a hard link is faster and does not take disk space
___
*[`.github/workflows/release.yml` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXz5Y9hTyTg7-DeCJ:-NDDNS4z-Sh9N3peSSl-:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/81c754d2b1c1c735b2bfc2c686c4a7dec482a17e/.github/workflows/release.yml#L49)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The name of binary. So it should be the same. 
</blockquote></details>

Done

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/204)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/release.yml` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXUUWCJ0cnA1boU5Q:-NDDf9V22WJ6Wb3QXoRg:b-17ug9z) ([raw file](https://github.com/coreumfoundation/coreum/blob/81c754d2b1c1c735b2bfc2c686c4a7dec482a17e/.github/workflows/release.yml#L3)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

https://github.com/CoreumFoundation/coreum/actions/workflows/ci.yml

There is "Run workflow" button in top-right corner. It will be the same for `release` once this PR is in master
</blockquote></details>

It seem unsusal to me :-)
If we say that we want just v* releases why we need to perform one more action?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/204)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/204)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`.github/workflows/release.yml` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXUUWCJ0cnA1boU5Q:-NDSYsnJBvoW5_Ib-Y0v:bq5iiiz) ([raw file](https://github.com/coreumfoundation/coreum/blob/81c754d2b1c1c735b2bfc2c686c4a7dec482a17e/.github/workflows/release.yml#L3)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It seem unsusal to me :-)
If we say that we want just v* releases why we need to perform one more action?
</blockquote></details>

yes I agree with Dmitry lets avoid extra manual step from our release process 
___
*[`.github/workflows/release.yml` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCvS4j2o3nL1vfoGqv:-NDSZ9rRB8jKeEruNZbP:bj83rd9) ([raw file](https://github.com/coreumfoundation/coreum/blob/81c754d2b1c1c735b2bfc2c686c4a7dec482a17e/.github/workflows/release.yml#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

creating a hard link is faster and does not take disk space
</blockquote></details>

I would still proceed with copying because it is easier to understand & basic thingy known by everyone
But ln is ok, resolving
___
*[`.github/workflows/release.yml` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXz5Y9hTyTg7-DeCJ:-NDSZXM429CKlwNhS6uv:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/81c754d2b1c1c735b2bfc2c686c4a7dec482a17e/.github/workflows/release.yml#L49)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done
</blockquote></details>

ok

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/204)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/release.yml` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDCXUUWCJ0cnA1boU5Q:-NDT7-ktDwWDXxrPOwYZ:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/81c754d2b1c1c735b2bfc2c686c4a7dec482a17e/.github/workflows/release.yml#L3)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes I agree with Dmitry lets avoid extra manual step from our release process 
</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/204)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/release.yml` line 6 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDT7btX9-8BnMY5uQqc:-NDT7btX9-8BnMY5uQqd:b-vg0ylv) ([raw file](https://github.com/coreumfoundation/coreum/blob/57e29d36fd5d7aaef09693ed95a7417588a28f4f/.github/workflows/release.yml#L6)):*
> ```YAML
>     branches: [ master ]
>     tags:
>       - "^v[0-9]+.[0-9]+.[0-9]+"
> ```

Why it's limited? I mean why not just v* ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/204)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/release.yml` line 6 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/204#-NDT7btX9-8BnMY5uQqc:-NDWg_Bj0SLguO5ie9My:b6msg0x) ([raw file](https://github.com/coreumfoundation/coreum/blob/57e29d36fd5d7aaef09693ed95a7417588a28f4f/.github/workflows/release.yml#L6)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why it's limited? I mean why not just v* ?
</blockquote></details>

to not create release if someone added tag with any word starting with `v`

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/204)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/204)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Pull request merged**
