### PR TITLE
DRAFT: Add TODO's to IBC integration-tests

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/503)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/503)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @wojtek-coreum)

**Review by miladz68 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/503)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/503)* status: all files reviewed, 7 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/asset_ft_test.go` line 154 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/503#-NW1yR1J8rPj1w9qS2JP:-NW1yR1J8rPj1w9qS2JQ:b5x53x3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0f0104d67508b51f352c4d22fc1c05e9807e7c31/integration-tests/ibc/asset_ft_test.go#L154)):*
> ```Go
> 
> // TODO:
> //  1. peerChainToCoreumChannelID this param is named like this in both functions but it should be vice versa in one of them
> ```

It seems correct in both. In the first, we need to get the expected balance denom, and in the second the denom to use. . Need to discuss to understand the your reasons to rename/revert it.
___
*[`integration-tests/ibc/asset_ft_test.go` line 155 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/503#-NW1ypfK03BE_Y2TLoW5:-NW1ypfK03BE_Y2TLoW6:b-4snmgn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0f0104d67508b51f352c4d22fc1c05e9807e7c31/integration-tests/ibc/asset_ft_test.go#L155)):*
> ```Go
> // TODO:
> //  1. peerChainToCoreumChannelID this param is named like this in both functions but it should be vice versa in one of them
> //  2. peerChainToCoreumChannelID & coreumToPeerChainEscrowAddress these 2 args are not really needed to be passed because you have both chains as args so it is easier to determine chainID & escrow address inside this function. This will simplify the func and make mistakes less likely.
> ```

Right, but we already have them in the test and those functions are the functions for that specific for the test.
___
*[`integration-tests/ibc/asset_ft_test.go` line 156 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/503#-NW2GKFjDwOSfqZzYnjV:-NW2GKFk7i36AeDyF7wr:bgzf3tq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0f0104d67508b51f352c4d22fc1c05e9807e7c31/integration-tests/ibc/asset_ft_test.go#L156)):*
> ```Go
> //  1. peerChainToCoreumChannelID this param is named like this in both functions but it should be vice versa in one of them
> //  2. peerChainToCoreumChannelID & coreumToPeerChainEscrowAddress these 2 args are not really needed to be passed because you have both chains as args so it is easier to determine chainID & escrow address inside this function. This will simplify the func and make mistakes less likely.
> //  3. each function should be have a single scope of responsibility and I don't really like that this one does 2 things. It should be refactored to either 2 funcs or maybe we can abstract it into single and have if or additional arg to determine if sender is issuer.
> ```

It's possible if we OK to duplicate the code. 
___
*[`integration-tests/ibc/asset_ft_test.go` line 157 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/503#-NW2GQZN3_ojyHy7eIFW:-NW2GQZN3_ojyHy7eIFX:b56ce55) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0f0104d67508b51f352c4d22fc1c05e9807e7c31/integration-tests/ibc/asset_ft_test.go#L157)):*
> ```Go
> //  2. peerChainToCoreumChannelID & coreumToPeerChainEscrowAddress these 2 args are not really needed to be passed because you have both chains as args so it is easier to determine chainID & escrow address inside this function. This will simplify the func and make mistakes less likely.
> //  3. each function should be have a single scope of responsibility and I don't really like that this one does 2 things. It should be refactored to either 2 funcs or maybe we can abstract it into single and have if or additional arg to determine if sender is issuer.
> //  4. direct mentions of other peer chains (osmosis, gaia) should be removed inside this function eg: expectedOsmosisRecipientBalance
> ```

That's a typo, should be fixed. Agree.
___
*[`integration-tests/ibc/asset_ft_test.go` line 158 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/503#-NW2GUca-elWwTtY8-SC:-NW2GUca-elWwTtY8-SD:b-c17ftz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0f0104d67508b51f352c4d22fc1c05e9807e7c31/integration-tests/ibc/asset_ft_test.go#L158)):*
> ```Go
> //  3. each function should be have a single scope of responsibility and I don't really like that this one does 2 things. It should be refactored to either 2 funcs or maybe we can abstract it into single and have if or additional arg to determine if sender is issuer.
> //  4. direct mentions of other peer chains (osmosis, gaia) should be removed inside this function eg: expectedOsmosisRecipientBalance
> //  5. ideally we should refactor sendToPeerChainFromCoreumFTIssuerAndNonIssuer & sendFromPeerChainAndValidateZeroCommissionOnEscrow to a single func but I'm not sure if it is possibe
> ```

It's also possible if we are OK to duplicate the code. 
___
*[`integration-tests/ibc/transfer_test.go` line 24 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/503#-NW2Go2CBvuIeHOYJkkt:-NW2Go2DDmwghd7bc3iQ:bt8rof9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0f0104d67508b51f352c4d22fc1c05e9807e7c31/integration-tests/ibc/transfer_test.go#L24)):*
> ```Go
> 
> 	// TODO: (Same comments apply to TestIBCTransferFromGaiaToCoreumAndBack.)
> 	//  1. here it should be coreumToGaiaChannelID := coreumChain.GetIBCChannelID
> ```

Need to discuss to understand the your reasons to rename/revert it.
___
*[`integration-tests/ibc/transfer_test.go` line 25 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/503#-NW2Gb0aC-lcU0RTR306:-NW2Gb0aC-lcU0RTR307:b-azlzg5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0f0104d67508b51f352c4d22fc1c05e9807e7c31/integration-tests/ibc/transfer_test.go#L25)):*
> ```Go
> 	// TODO: (Same comments apply to TestIBCTransferFromGaiaToCoreumAndBack.)
> 	//  1. here it should be coreumToGaiaChannelID := coreumChain.GetIBCChannelID
> 	//  2. In crust we should come up with another naming convention for channels
> ```

Didn't get what you mean by "naming convention for channels". In the IBC channels are generated on the chain side.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/503)* status: all files reviewed, 7 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Pull request closed without merging**
