### PR TITLE
Make new linter (1.48.0) happy

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/138)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/138)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/138)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`app/app.go` line 245 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/138#-N9aIoEi10-Bx6WK0qIT:-N9aIoEi10-Bx6WK0qIU:bz5w8hv) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca69c4ee5b318753f37d8f0ac814fb3507ca4f94/app/app.go#L245)):*
> ```Go
> 
> // New returns a reference to an initialized blockchain app
> //nolint:funlen,gofmt,goimports // Disable linting for code generated by Cosmos SDK, gofmt and goimports are crazy about this place without reason
> ```

what exactly do you mean by crazy ?
What is the error here ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/138)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`app/app.go` line 245 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/138#-N9aIoEi10-Bx6WK0qIT:-N9aOEUw2-_icmpnlpmi:bfwyoe5) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca69c4ee5b318753f37d8f0ac814fb3507ca4f94/app/app.go#L245)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what exactly do you mean by crazy ?
What is the error here ?
</blockquote></details>

It just says that file is not `gofmt-ed` pointing to the line `// New returns a reference to an initialized blockchain app`

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/138)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`app/app.go` line 245 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/138#-N9aIoEi10-Bx6WK0qIT:-N9aONal4Jet3C29gGxx:bazh8x7) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca69c4ee5b318753f37d8f0ac814fb3507ca4f94/app/app.go#L245)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It just says that file is not `gofmt-ed` pointing to the line `// New returns a reference to an initialized blockchain app`
</blockquote></details>

it happens in situation if there is `//go:embed` or `//nolint` in next line. I think it might be related to lack of space after `//` - which is correct

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/138)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @xlab)

___
*[`app/app.go` line 245 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/138#-N9aIoEi10-Bx6WK0qIT:-N9afibHA4BsJc0OWpjH:b-smkhgg) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c76fe44800134cdbf529a9b88974ba63fbadbab/app/app.go#L245)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

it happens in situation if there is `//go:embed` or `//nolint` in next line. I think it might be related to lack of space after `//` - which is correct
</blockquote></details>

I see
Strange thing

I guess it is related to golang 1.19 

Ok resolving it for now but lets keep an eye on it

**Pull request merged**
