### PR TITLE
Adjust sequence of methods in keepers of FT and NFT

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/417)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/417)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/417)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/417#-NPSRxB1-Mlf4nTGlPzj:-NPSRxB1-Mlf4nTGlPzk:b-ewam2b) (no related file):*
What is the logic applied here to order methods ? And what is the difference comparing to previous version ?

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/417)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/417#-NPSRxB1-Mlf4nTGlPzj:-NPVzYt95yU9RBZUGY_m:bpx47p4) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

What is the logic applied here to order methods ? And what is the difference comparing to previous version ?
</blockquote></details>

I grouped methods by the features (issuing, minting...) having similar feature order in both modules (issue, mint, burn freeze, whitelist)

___

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/417)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Pull request merged**
