### PR TITLE
Add docs for asset extension

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description
Docs for asset extension

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/849)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/849)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/849#-NyU3Lo1-013RkiRF7wZ:-NyU3Lo1-013RkiRF7w_:bfs9di8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec72aabe1784f9737726127423291012e21480fa/x/asset/ft/spec/README.md#L132)):*
> ```Markdown
> 
> ### Extension
> Extension is a powerful feature which let the admin override the functionalities of the token completely by attaching a smart contract to the token that can administrate it. When a bank transfer is initiated, the smart contract account receives the amount plus any commission or burn amount if they should be applied, then it is called via a sudo call with the information related to the bank transfer and the context information. The smart contract then can decide to do whatever it decides with the transfer which may include overriding of any behavior for the features explained before.
> ```

which lets



_Code quote:_
```Markdown
which let
```
___
*[`x/asset/ft/spec/README.md` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/849#-NyU3Sut4VUtFmEO7VKS:-NyU3Sut4VUtFmEO7VKT:b-dq3ulf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec72aabe1784f9737726127423291012e21480fa/x/asset/ft/spec/README.md#L132)):*
> ```Markdown
> 
> ### Extension
> Extension is a powerful feature which let the admin override the functionalities of the token completely by attaching a smart contract to the token that can administrate it. When a bank transfer is initiated, the smart contract account receives the amount plus any commission or burn amount if they should be applied, then it is called via a sudo call with the information related to the bank transfer and the context information. The smart contract then can decide to do whatever it decides with the transfer which may include overriding of any behavior for the features explained before.
> ```

not completely, there are still some limitaions.



_Code quote:_
```Markdown
functionalities of the token completely
```
___
*[`x/asset/ft/spec/README.md` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/849#-NyU3wu26yIhjR1T-gVf:-NyU3wu30FyC20YEqPV0:b-258154) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec72aabe1784f9737726127423291012e21480fa/x/asset/ft/spec/README.md#L132)):*
> ```Markdown
> 
> ### Extension
> Extension is a powerful feature which let the admin override the functionalities of the token completely by attaching a smart contract to the token that can administrate it. When a bank transfer is initiated, the smart contract account receives the amount plus any commission or burn amount if they should be applied, then it is called via a sudo call with the information related to the bank transfer and the context information. The smart contract then can decide to do whatever it decides with the transfer which may include overriding of any behavior for the features explained before.
> ```

this is is not accurate. it can overwrite some of the behaviors but not all the features, for example it cannot overwrite minting.  



_Code quote:_
```Markdown
overriding of any behavior for the features explained before.
```
___
*[`x/asset/ft/spec/README.md` line 166 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/849#-NyU39W48WY_sxIaDYmb:-NyU39W48WY_sxIaDYmc:b5n10zb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec72aabe1784f9737726127423291012e21480fa/x/asset/ft/spec/README.md#L166)):*
> ```Markdown
>   - `ibc_purpose`: if it is an ibc transfer, indicates whether it's an outgoing, incoming, acknowledged or timed-out transfer
> 
> There is a template implementation of extension in `x/asset/ft/keeper/test-contracts/asset-extension` which can be used as a reference to implement other extensions.
> ```

`x/asset/ft/keeper/test-contracts/asset-extension` this is not a template, this is for testing but people can take inspiration from it.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/849)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/849#-NyU3Lo1-013RkiRF7wZ:-NyUO8kL-Pen6X_xMy-6:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec72aabe1784f9737726127423291012e21480fa/x/asset/ft/spec/README.md#L132)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

which lets
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/849#-NyU3Sut4VUtFmEO7VKS:-NyUOMWRECuMLpGYnNN5:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec72aabe1784f9737726127423291012e21480fa/x/asset/ft/spec/README.md#L132)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

not completely, there are still some limitaions.
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/849#-NyU3wu26yIhjR1T-gVf:-NyUOQbbB2vXtHfYsm11:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec72aabe1784f9737726127423291012e21480fa/x/asset/ft/spec/README.md#L132)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this is is not accurate. it can overwrite some of the behaviors but not all the features, for example it cannot overwrite minting.
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 166 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/849#-NyU39W48WY_sxIaDYmb:-NyUOw9nBNEpJ4Obc8lO:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec72aabe1784f9737726127423291012e21480fa/x/asset/ft/spec/README.md#L166)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

`x/asset/ft/keeper/test-contracts/asset-extension` this is not a template, this is for testing but people can take inspiration from it.
</blockquote></details>

Done.

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/849)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/849)* status: all files reviewed, 6 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 132 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/849#-NyV-VsYDQZ_7lamSczr:-NyV-VsZ27y3qEJ4SKyf:bcg9jy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b2b3da824561ea6ad0070dcb4e554c527941b404/x/asset/ft/spec/README.md#L132)):*
> ```Markdown
> 
> ### Extension
> Extension is a powerful feature which lets the admin override some functionalities of the token by attaching a smart contract to the token that can administrate it. When a bank transfer is initiated, the smart contract account receives the amount plus any commission or burn amount if they should be applied, then it is called via a sudo call with the information related to the bank transfer and the context information. The smart contract then can decide to do whatever it decides with the transfer which may include overriding of some behaviors for the features explained before.
> ```

IMO, it allows us to intercept the `send` with the attached funds. And optionally use built-in assetft functions, but not override. 



_Code quote:_
```Markdown
Extension is a powerful feature which lets the admin override some functionalities of the token by attaching a smart contract to the token that can administrate it.
```
___
*[`x/asset/ft/spec/README.md` line 136 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/849#-NyV0-ut01VdFTRZAJxf:-NyV0-ut01VdFTRZAJxg:b-aoe28m) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b2b3da824561ea6ad0070dcb4e554c527941b404/x/asset/ft/spec/README.md#L136)):*
> ```Markdown
> ```rust
> #[cw_serde]
> pub enum SudoMsg {
> ```

It would be nice for @keyleu to try to write such a contract as a ref impl, to check whether the docs are good enough.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/849)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 132 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/849#-NyV-VsYDQZ_7lamSczr:-NyVAPKUDYclEbtUB8D8:bmgglq2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b2b3da824561ea6ad0070dcb4e554c527941b404/x/asset/ft/spec/README.md#L132)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO, it allows us to intercept the `send` with the attached funds. And optionally use built-in assetft functions, but not override.
</blockquote></details>

The attached fund is for the previous implementation, with sudo we don't have it.
Also it can override functionalities. For example it can ignore the commission rate, or it can send a part of it to another account or whatever the smart contract developer decides to do.
___
*[`x/asset/ft/spec/README.md` line 136 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/849#-NyV0-ut01VdFTRZAJxf:-NyVAwBU9_YqTj8sCxbJ:bcrz6n) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b2b3da824561ea6ad0070dcb4e554c527941b404/x/asset/ft/spec/README.md#L136)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It would be nice for @keyleu to try to write such a contract as a ref impl, to check whether the docs are good enough.
</blockquote></details>

Yeah. Let's merge it and let him implement one and if it needs more change, we can do it after that

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/849)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Pull request merged**
