### PR TITLE
Move znet/integration-tests utils to pkg to make it reusable.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

In order to make the integration-tests framework reusabe I've moved it to the `znet` package. The only part which wasn't moved was the creation of the channels in run-time, since it uses the cosmos relayer as a go-dependency.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/659)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 37 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/659)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/659#-NerX2xU38Xe3ECcjgRG:-NerX2xU38Xe3ECcjgRH:b-dg9hl9) (no related file):*
in general looks good for me I just disagree with 2 things:

1. I'm not sure we should move & expose all helpers from integration-tests. IMO we should expose only parts related to Coreum chain & things which are likely to be used in other component integration-tests in the nearest future. IMO we don't need to put governance, IBC things there. My concern is that by creating this pkg we kind of define interface & ideally we shouln't brake it in the future to make maintenance of other components easier. I would keep only needed right now things in pkg (WASM, CoreumChain etc)

2. I still don't like znet name here. Lets better name in pkg/integration-tests or pkg/integration-test-utils but not znet. 

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/659)* status: 5 of 46 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/659#-NerX2xU38Xe3ECcjgRG:-NeruS1d0oeDyQwZibLs:b-io501x) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

in general looks good for me I just disagree with 2 things:

1. I'm not sure we should move & expose all helpers from integration-tests. IMO we should expose only parts related to Coreum chain & things which are likely to be used in other component integration-tests in the nearest future. IMO we don't need to put governance, IBC things there. My concern is that by creating this pkg we kind of define interface & ideally we shouln't brake it in the future to make maintenance of other components easier. I would keep only needed right now things in pkg (WASM, CoreumChain etc)

2. I still don't like znet name here. Lets better name in pkg/integration-tests or pkg/integration-test-utils but not znet.
</blockquote></details>

1. Agreed to keep in the integration-test go files which are not needed for the bridge
2. Decided to call it `testutil/integration`

Done

___

**Review by ysv — APPROVED** [review]
> Reviewed 32 of 32 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/659)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 37 files at r1, 32 of 32 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/659)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, and @wojtek-coreum)

___
*[`pkg/keyring/keyring.go` line 29 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/659#-NfAAy_L9vbsF_--t3d3:-NfAAy_L9vbsF_--t3d4:b-x86ki4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3e716cbeec41f03ded3fa18e3b75c37b23da995f/pkg/keyring/keyring.go#L29)):*
> ```Go
> }
> 
> // Read operations:
> ```

I think we should remove this comment
___
*[`pkg/keyring/keyring.go` line 108 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/659#-NfAB0j4EKEnOFd18wgv:-NfAB0j4EKEnOFd18wgw:b5icywz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3e716cbeec41f03ded3fa18e3b75c37b23da995f/pkg/keyring/keyring.go#L108)):*
> ```Go
> }
> 
> // Write operations:
> ```

I think we should remove this as well.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/659)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, and @wojtek-coreum)

___
*[`pkg/keyring/keyring.go` line 29 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/659#-NfAAy_L9vbsF_--t3d3:-NfAV82KBv5NGn_5ZPp1:b-lh449s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3e716cbeec41f03ded3fa18e3b75c37b23da995f/pkg/keyring/keyring.go#L29)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think we should remove this comment
</blockquote></details>

But it was here before, same as next comment. And it was here to simplify the usage of the RW lock.

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/659)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu and @wojtek-coreum)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/659)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/659)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu, @wojtek-coreum, and @ysv)

**Pull request merged**
