### PR TITLE
Document IBC feature

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/551)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/551)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/551#-NZQIHR_577nZo36Uwzn:-NZQIHR_577nZo36Uwzo:b-pmj12u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6862c8ec73717861b6618aa0d1ffc6acf1f3a957/x/asset/ft/spec/README.md#L15)):*
> ```Markdown
> - Global Freeze
> - Whitelist
> - IBC transfers
> ```

Why `transfers` is plural?
___
*[`x/asset/ft/spec/README.md` line 49 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/551#-NZQIvm_D3k0T_l9yVt6:-NZQIvm_D3k0T_l9yVt7:bty2v9t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6862c8ec73717861b6618aa0d1ffc6acf1f3a957/x/asset/ft/spec/README.md#L49)):*
> ```Markdown
> The issuer has the option to provide `BurnRate` when issuing a new token. This value is a number between 0 and 1, and if it is above zero, in every transfer, some additional tokens will be burnt on top of the transferred value, from the senders address. The tokens to be burnt are calculated by multiplying the TransferAmount by burn rate, and rounding it up to an integer value.
> 
> If IBC feature is enabled for the token then the burn rate is applied to outgoing IBC transfers.
> ```

How about use `applies` in present instead of the past (same for all places)?
___
*[`x/asset/ft/spec/README.md` line 85 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/551#-NZQIC0J6CI8quilI6yZ:-NZQIC0J6CI8quilI6y_:br8gbxx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6862c8ec73717861b6618aa0d1ffc6acf1f3a957/x/asset/ft/spec/README.md#L85)):*
> ```Markdown
> If the freezing feature is enabled on a token, then the issuer of the token can globally freeze that token, which means that nobody except the issuer can send that token. In other words, only the issuer will be able to send to other accounts. The issuer can also globally unfreeze and remove this limitation.
> 
> If IBC is enabled for the token and token is globaly frozen then only the issuer can send them over IBC transfer protocol.
> ```

globally

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/551)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 373 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/551#-NZQKoBy9p3YaWVYhuX3:-NZQKoBy9p3YaWVYhuX4:b-scsrai) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6862c8ec73717861b6618aa0d1ffc6acf1f3a957/x/asset/ft/spec/README.md#L373)):*
> ```Markdown
>   </tr>
>   <tr>
>     <td>IBC Send to issuer</td>
> ```

Do we need it for the IBC ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/551)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/551#-NZQIHR_577nZo36Uwzn:-NZQKcCHBY_PKikoT3Uc:b-cm7smk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6862c8ec73717861b6618aa0d1ffc6acf1f3a957/x/asset/ft/spec/README.md#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why `transfers` is plural?
</blockquote></details>

why shouldn't?
___
*[`x/asset/ft/spec/README.md` line 49 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/551#-NZQIvm_D3k0T_l9yVt6:-NZQKkkd3e8zoJi96PZk:bjazjwz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6862c8ec73717861b6618aa0d1ffc6acf1f3a957/x/asset/ft/spec/README.md#L49)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How about use `applies` in present instead of the past (same for all places)?
</blockquote></details>

The current form is correct. This is not a past simple - it is a passive voice. "Burn rate" is not a creature able to do anything so saying "burn rate does sth" would be incorrect. Also, if "burn rate applies" is used, then the question is "what does it apply?". This is "the algorithm which applies the burn rate", so "burn rate is applied by the algorithm".
___
*[`x/asset/ft/spec/README.md` line 85 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/551#-NZQIC0J6CI8quilI6yZ:-NZQLmYv9OFRNl4-wSIw:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6862c8ec73717861b6618aa0d1ffc6acf1f3a957/x/asset/ft/spec/README.md#L85)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

globally
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 373 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/551#-NZQKoBy9p3YaWVYhuX3:-NZQLoUhA3EBln8ftu-P:b-yjtvwp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6862c8ec73717861b6618aa0d1ffc6acf1f3a957/x/asset/ft/spec/README.md#L373)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do we need it for the IBC ?
</blockquote></details>

Then we could remove "Send to issuer" too

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/551)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/551#-NZQIHR_577nZo36Uwzn:-NZQMtsY0Dk1EAzJdVgX:b-kps9rl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6862c8ec73717861b6618aa0d1ffc6acf1f3a957/x/asset/ft/spec/README.md#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why shouldn't?
</blockquote></details>

IMO `transfer` sounds more  natural, same as module. 
___
*[`x/asset/ft/spec/README.md` line 49 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/551#-NZQIvm_D3k0T_l9yVt6:-NZQN9pB3zc_JMDGcOvJ:btlzzyl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6862c8ec73717861b6618aa0d1ffc6acf1f3a957/x/asset/ft/spec/README.md#L49)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The current form is correct. This is not a past simple - it is a passive voice. "Burn rate" is not a creature able to do anything so saying "burn rate does sth" would be incorrect. Also, if "burn rate applies" is used, then the question is "what does it apply?". This is "the algorithm which applies the burn rate", so "burn rate is applied by the algorithm".
</blockquote></details>

I know that it was correct. I was a spelling change proposal not the correction.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/551)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/551#-NZQIHR_577nZo36Uwzn:-NZQr9gr8WHbIqj90Jkv:bln6tl1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6862c8ec73717861b6618aa0d1ffc6acf1f3a957/x/asset/ft/spec/README.md#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO `transfer` sounds more  natural, same as module. 
</blockquote></details>

But we support many IBC transfers not only one :-)
___
*[`x/asset/ft/spec/README.md` line 49 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/551#-NZQIvm_D3k0T_l9yVt6:-NZQrFs02Mgs6Hy4FusS:bvpz8ze) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6862c8ec73717861b6618aa0d1ffc6acf1f3a957/x/asset/ft/spec/README.md#L49)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I know that it was correct. I was a spelling change proposal not the correction.
</blockquote></details>

Then I don't understand your suggestion.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/551)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/551#-NZQIHR_577nZo36Uwzn:-NZQuQU03Cy4LiSIadRx:b-lbut5x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6862c8ec73717861b6618aa0d1ffc6acf1f3a957/x/asset/ft/spec/README.md#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But we support many IBC transfers not only one :-)
</blockquote></details>

What do you mean?

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/551)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/551)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/551#-NZQIHR_577nZo36Uwzn:-NZVQbcq8NlYDxCmxTf4:b8cjrw2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6862c8ec73717861b6618aa0d1ffc6acf1f3a957/x/asset/ft/spec/README.md#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

I mean that if there is a cats hairdresser, he/she is able serve many cats, not only one. Our blockchain is able to serve many IBC transfers,turning IBC off after sending the first one, would be ridiculous :-)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/551)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Pull request merged**
