### PR TITLE
Automate x/deterministicgas doc generation using go:generate

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/463)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/463)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/spec/generate.go` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSfV6851pneCYj9wD38:-NSfV6851pneCYj9wD39:b8ssblx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fa426c665834e28f625edd6f4918fb05e5a45bb3/x/deterministicgas/spec/generate.go#L21)):*
> ```Go
> 	readmeTmpl string
> 
> 	specialCases = []string{
> ```

How about using type instead of string?
___
*[`x/deterministicgas/spec/generate.go` line 40 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSfUstm2Q2opMkpe23h:-NSfUstm2Q2opMkpe23i:bfz8jmf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fa426c665834e28f625edd6f4918fb05e5a45bb3/x/deterministicgas/spec/generate.go#L40)):*
> ```Go
> 	cfg := deterministicgas.DefaultConfig()
> 	for msgType, gasFunc := range cfg.GasByMessageMap() {
> 		if lo.Contains(specialCases, msgType) {
> ```

Minor, but with the map it seems like a use case for a map.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/463)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/spec/README.tmpl.md` line 7 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSfVZnoBRWO2lzZjrEy:-NSfVZnoBRWO2lzZjrEz:b-el9toz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fa426c665834e28f625edd6f4918fb05e5a45bb3/x/deterministicgas/spec/README.tmpl.md#L7)):*
> ```Markdown
> ## Intro
> 
> Coreum is using a deterministic gas model for its transactions. Meaning that given a transaction type (e.g
> ```

is using -> uses ?



_Code quote:_
```Markdown
Coreum is using a deterministic gas model for its transactions. Meaning that given a transaction type (e.g
`/coreum.asset.ft.v1.MsgIssueGasPrice`) one can know how much gas will be used beforehand, and this amount is fixed if some
preconditions are met. Of course this deterministic gas does not apply to the type of transactions that have a
complicated, nondeterministic execution path (e.g `/cosmwasm.wasm.v1.MsgExecuteContract`). We provide tables with all
```

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/463)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/463)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/deterministicgas/spec/generate.go` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSfV6851pneCYj9wD38:-NSg6DRCDuuJGsUQGIoM:b7sfgr7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fa426c665834e28f625edd6f4918fb05e5a45bb3/x/deterministicgas/spec/generate.go#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How about using type instead of string?
</blockquote></details>

do you mean to define a separate type for this ?
smth like this

```
type MsgType string
```

and use it instead of string everywhere ?
___
*[`x/deterministicgas/spec/generate.go` line 40 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSfUstm2Q2opMkpe23h:-NSg6r6HDTqYFluVErUt:batnsyn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fa426c665834e28f625edd6f4918fb05e5a45bb3/x/deterministicgas/spec/generate.go#L40)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Minor, but with the map it seems like a use case for a map. 
</blockquote></details>

I refactored it to map but now I realised that it introduces non-determinism because map is not ordered. As result this cycle produces different md doc each time: 
`for msgType := range specialCases`

I can of course rewrite it with map but this will introduce more hustle 

So it is probably better to use slice here
___
*[`x/deterministicgas/spec/README.tmpl.md` line 7 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSfVZnoBRWO2lzZjrEy:-NSg70S4-M6aJ82iwU2q:bb7f2mf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fa426c665834e28f625edd6f4918fb05e5a45bb3/x/deterministicgas/spec/README.tmpl.md#L7)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

is using -> uses ?
</blockquote></details>

done

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/463)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/deterministicgas/config_test.go` line 137 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjsX4e9n2BSicCcg2N:-NSjsX4e9n2BSicCcg2O:b-8diqm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/config_test.go#L137)):*
> ```Go
> 		t.Run("deterministic: "+deterministicgas.MsgType(sdkMsg), func(t *testing.T) {
> 			gas, ok := cfg.GasRequiredByMessage(sdkMsg)
> 			fmt.Printf("%v: %v\n", deterministicgas.MsgType(sdkMsg), gas)
> ```

leftover or you really want to print this?
___
*[`x/deterministicgas/config_test.go` line 147 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjs_BPE9-8QQpU4QLp:-NSjs_BPE9-8QQpU4QLq:b-7ropln) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/config_test.go#L147)):*
> ```Go
> 		t.Run("nondeterministic: "+deterministicgas.MsgType(sdkMsg), func(t *testing.T) {
> 			gas, ok := cfg.GasRequiredByMessage(sdkMsg)
> 			fmt.Printf("%v: %v\n", deterministicgas.MsgType(sdkMsg), gas)
> ```

ditto
___
*[`x/deterministicgas/spec/generate.go` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjt8x62Hxfh927ZShQ:-NSjt8x62Hxfh927ZShR:b-7km98k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L21)):*
> ```Go
> 	readmeTmpl string
> 
> 	specialCases = []string{
> ```

Maybe it could be done by testing that map entry is not equal to the result of `constantGasFunc`? To avoid the need for setting special cases in two places.
___
*[`x/deterministicgas/spec/generate.go` line 69 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjuQQw2Psayr6P86PE:-NSjuQQw2Psayr6P86PF:b-2m0tg1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L69)):*
> ```Go
> 	}
> 
> 	generatorComment := `[//]: # (GENERATED DOC.)
> ```

Set it inside `readmeTmpl`
___
*[`x/deterministicgas/spec/generate.go` line 72 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSju-y_EKdop2LebHwq:-NSju-y_EKdop2LebHwr:b-luzdlw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L72)):*
> ```Go
> [//]: # (DO NOT EDIT MANUALLY!!!)`
> 
> 	readmeBuf := new(bytes.Buffer)
> ```

write it directly to a file, without buffer in between
___
*[`x/deterministicgas/spec/generate.go` line 90 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjvH9z2Q3poH92XW7L:-NSjvH9z2Q3poH92XW7M:brtza54) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L90)):*
> ```Go
> 		GeneratorComment:              generatorComment,
> 		FixedGas:                      cfg.FixedGas,
> 		SigVerifyCost:                 1000,
> ```

1000 -> params.SigVerifyCostSecp256k1
___
*[`x/deterministicgas/spec/generate.go` line 91 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjvLGA--MQtXfyNWbL:-NSjvLGA--MQtXfyNWbM:bqt163i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L91)):*
> ```Go
> 		FixedGas:                      cfg.FixedGas,
> 		SigVerifyCost:                 1000,
> 		TxSizeCostPerByte:             10,
> ```

10 -> params.TxSizeCostPerByte
___
*[`x/deterministicgas/spec/README.md` line 71 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjvmpZA9GOxRM-xy6_:-NSjvmpZA9GOxRM-xy6a:b1nje3m) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/README.md#L71)):*
> ```Markdown
> | Message Type | Gas |
> |--------------|-----|
> | `/cosmos.authz.v1beta1.MsgExec                               ` | [special case](#special-cases) |
> ```

spaces should be after "`"
___
*[`x/deterministicgas/spec/README.md` line 139 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjvfBt3sMzWfTj3KlE:-NSjvfBt3sMzWfTj3KlF:b1nje3m) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/README.md#L139)):*
> ```Markdown
> | Message Type |
> |--------------|
> | `/cosmos.crisis.v1beta1.MsgVerifyInvariant                   ` |
> ```

spaces should be after "`"
___
*[`x/deterministicgas/spec/README.tmpl.md` line 70 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjvwQVBE5HglLGreuD:-NSjvwQVBE5HglLGreuE:b-93p2p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/README.tmpl.md#L70)):*
> ```Markdown
> | Message Type | Gas |
> |--------------|-----|
> {{ .DeterministicMessagesTable }}
> ```

I would prefer to use `{{ repeat }}` and construct the table here, not in go

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/463)* status: all files reviewed, 11 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/deterministicgas/spec/generate.go` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSfV6851pneCYj9wD38:-NSk9CMF1q9tBdRpVsws:b2nhswy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fa426c665834e28f625edd6f4918fb05e5a45bb3/x/deterministicgas/spec/generate.go#L21)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do you mean to define a separate type for this ?
smth like this

```
type MsgType string
```

and use it instead of string everywhere ?
</blockquote></details>

Yes
___
*[`x/deterministicgas/spec/generate.go` line 40 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSfUstm2Q2opMkpe23h:-NSk9IS_9GehHl-CA2mz:bmizjuj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fa426c665834e28f625edd6f4918fb05e5a45bb3/x/deterministicgas/spec/generate.go#L40)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I refactored it to map but now I realised that it introduces non-determinism because map is not ordered. As result this cycle produces different md doc each time: 
`for msgType := range specialCases`

I can of course rewrite it with map but this will introduce more hustle 

So it is probably better to use slice here

</blockquote></details>

Agree, resolved.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/463)* status: 0 of 5 files reviewed, 11 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/deterministicgas/config_test.go` line 137 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjsX4e9n2BSicCcg2N:-NSuAGDsC79vExzVmKRm:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/config_test.go#L137)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

leftover or you really want to print this?
</blockquote></details>

Done.
___
*[`x/deterministicgas/config_test.go` line 147 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjs_BPE9-8QQpU4QLp:-NSuAGZVDsCw7StC8HpM:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/config_test.go#L147)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`x/deterministicgas/spec/generate.go` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSfV6851pneCYj9wD38:-NSwRQB1CE4JcAqzcEpw:b-ogzwm1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fa426c665834e28f625edd6f4918fb05e5a45bb3/x/deterministicgas/spec/generate.go#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

I made this change but not sure if it looks better
check it pls and let me know 
___
*[`x/deterministicgas/spec/generate.go` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjt8x62Hxfh927ZShQ:-NSwb9Fq-4TQrepced7K:bkiil5z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L21)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Maybe it could be done by testing that map entry is not equal to the result of `constantGasFunc`? To avoid the need for setting special cases in two places.
</blockquote></details>

made it with reflection
in terms of non-duplicating this vars it definitely looks better
But in terms of tricks it's overkill IMO
___
*[`x/deterministicgas/spec/generate.go` line 69 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjuQQw2Psayr6P86PE:-NSuAVT2Ah8i_WjbEawl:brthgjz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L69)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Set it inside `readmeTmpl`
</blockquote></details>

I can do this but then it seems like you are not supposed to edit `README.tmpl.md`itself which is not true
___
*[`x/deterministicgas/spec/generate.go` line 72 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSju-y_EKdop2LebHwq:-NSuBN4_DxH_G47O3mAH:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L72)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

write it directly to a file, without buffer in between
</blockquote></details>

Done.
___
*[`x/deterministicgas/spec/generate.go` line 90 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjvH9z2Q3poH92XW7L:-NSuC1U-9z587CRWjjTX:b42qdou) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L90)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

1000 -> params.SigVerifyCostSecp256k1
</blockquote></details>

yes but how can I fetch these params if they are stored inside auth module params. And to access them I need Auth keeper

I would also prefer to fetch these 2 values from primary source but don't see any optimal solution for this.
___
*[`x/deterministicgas/spec/generate.go` line 91 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjvLGA--MQtXfyNWbL:-NSuDFzWBIi3Ni8PTTTq:b-t0qeac) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L91)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

10 -> params.TxSizeCostPerByte
</blockquote></details>

same as prev
___
*[`x/deterministicgas/spec/README.md` line 71 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjvmpZA9GOxRM-xy6_:-NSwNxgY1yowcPEgm173:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/README.md#L71)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

spaces should be after "`"
</blockquote></details>

Done.
___
*[`x/deterministicgas/spec/README.md` line 139 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjvfBt3sMzWfTj3KlE:-NSwNyDl9quu3h6ZONJ1:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/README.md#L139)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

spaces should be after "`"
</blockquote></details>

Done.
___
*[`x/deterministicgas/spec/README.tmpl.md` line 70 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjvwQVBE5HglLGreuD:-NSwNypJEs8cEwpK1ZkT:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/README.tmpl.md#L70)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would prefer to use `{{ repeat }}` and construct the table here, not in go
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/463)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/deterministicgas/config.go` line 194 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSyZR5i3PNYGd1_oAyL:-NSyZR5i3PNYGd1_oAyM:bezg3js) ([raw file](https://github.com/CoreumFoundation/coreum/blob/49a3d2a8ecef929237fe4a5ef0681e2bf948890f/x/deterministicgas/config.go#L194)):*
> ```Go
> // "/cosmos.distribution.v1beta1.MsgFundCommunityPool"
> // "/coreum.asset.ft.v1.MsgMint".
> func MsgTypeURL(msg sdk.Msg) MsgType {
> ```

That's a bit weird because `MsgTypeURL` returns the URL of the message type, calling it `MsgType`. Now, in the entire file it seems that terms "message type" and "URL of the message type" are used interchangabely, which is confusing.
___
*[`x/deterministicgas/spec/generate.go` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjt8x62Hxfh927ZShQ:-NSygrOE5YifZKbGfY7d:b-z22xgj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L21)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

made it with reflection
in terms of non-duplicating this vars it definitely looks better
But in terms of tricks it's overkill IMO
</blockquote></details>

Check this commit I created on top of your PR: https://github.com/CoreumFoundation/coreum/commit/a1b6a51cd426cab68c43bfc038e80b81188ce148

At least some more self-describing function names might be generated for reflection.
___
*[`x/deterministicgas/spec/generate.go` line 90 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjvH9z2Q3poH92XW7L:-NSy_kds7IPxux3E-SID:bb3tnuy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L90)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes but how can I fetch these params if they are stored inside auth module params. And to access them I need Auth keeper

I would also prefer to fetch these 2 values from primary source but don't see any optimal solution for this.
</blockquote></details>

I don't understand. Can't you import auth module where those constants are defined?

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/463)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/spec/generate.go` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSfV6851pneCYj9wD38:-NSykb_5AKMF8JJFwsP2:blq00e6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fa426c665834e28f625edd6f4918fb05e5a45bb3/x/deterministicgas/spec/generate.go#L21)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I made this change but not sure if it looks better
check it pls and let me know 
</blockquote></details>

IMO this version looks better.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/463)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/deterministicgas/config.go` line 194 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSyZR5i3PNYGd1_oAyL:-NT-0ipH55ZSA-7Ft-ew:b-bfuioy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/49a3d2a8ecef929237fe4a5ef0681e2bf948890f/x/deterministicgas/config.go#L194)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

That's a bit weird because `MsgTypeURL` returns the URL of the message type, calling it `MsgType`. Now, in the entire file it seems that terms "message type" and "URL of the message type" are used interchangabely, which is confusing.
</blockquote></details>

MsgType -> MsgURL
`MsgToMsgURL()`
___
*[`x/deterministicgas/spec/generate.go` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjt8x62Hxfh927ZShQ:-NTJOrZFBkMwIqG9rnWV:b-j2dr6o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L21)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Check this commit I created on top of your PR: https://github.com/CoreumFoundation/coreum/commit/a1b6a51cd426cab68c43bfc038e80b81188ce148

At least some more self-describing function names might be generated for reflection.
</blockquote></details>

as we agreed on the call
I will keep using current version with minor change to avoid this complex regular expressions 
___
*[`x/deterministicgas/spec/generate.go` line 90 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjvH9z2Q3poH92XW7L:-NT-2dUpDzb9E3rpL6VH:bb7f2mf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L90)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't understand. Can't you import auth module where those constants are defined? 
</blockquote></details>

done
___
*[`x/deterministicgas/spec/generate.go` line 91 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjvLGA--MQtXfyNWbL:-NT-2gqh7vNxOmIpIXQQ:b-7rl0kd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L91)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

same as prev
</blockquote></details>

done

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/463)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/deterministicgas/spec/generate.go` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjt8x62Hxfh927ZShQ:-NTNaooc5qM2xgfLgcGZ:bi97wm9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L21)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

as we agreed on the call
I will keep using current version with minor change to avoid this complex regular expressions 
</blockquote></details>

The current version is ok, but if you take a look at the commit I provided above and change:

```go
func nondeterministicGasFunc() gasByMsgFunc {
	return func(msg sdk.Msg) (uint64, bool) {
		return 0, false
	}
}
```

to:

```go
func nondeterministicGasFunc(msg sdk.Msg) (uint64, bool) {
	return 0, false
}
```

you will simplify, both the original logic and generator

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/463)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/deterministicgas/spec/generate.go` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NSjt8x62Hxfh927ZShQ:-NTO-4T-1_1MI16KxR-L:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e9ef253b575eca9363080cbe9b8916f7c5f85a6/x/deterministicgas/spec/generate.go#L21)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The current version is ok, but if you take a look at the commit I provided above and change:

```go
func nondeterministicGasFunc() gasByMsgFunc {
	return func(msg sdk.Msg) (uint64, bool) {
		return 0, false
	}
}
```

to:

```go
func nondeterministicGasFunc(msg sdk.Msg) (uint64, bool) {
	return 0, false
}
```

you will simplify, both the original logic and generator
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/463)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/deterministicgas/spec/generate.go` line 38 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/463#-NTO1P4BC5wgINkCZi0g:-NTO1P4BC5wgINkCZi0h:b32n0o4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9c664284a830e84f87f2a44f9453cdf81ea0564/x/deterministicgas/spec/generate.go#L38)):*
> ```Go
> 	for msgURL, gasFunc := range cfg.GasByMessageMap() {
> 		fnFullName := runtime.FuncForPC(reflect.ValueOf(gasFunc).Pointer()).Name()
> 		fnParts := strings.Split(fnFullName, "/")
> ```

Non-blocking: You could split by `.` instead of `/` here, leading to shorter string in the `if` below

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/463)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

___
*[`x/deterministicgas/spec/generate.go` line 38 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/463#-NTO1P4BC5wgINkCZi0g:-NTO27MX960rdQn5a6oz:b-nj1v5o) ([raw file](https://github.com/coreumfoundation/coreum/blob/d9c664284a830e84f87f2a44f9453cdf81ea0564/x/deterministicgas/spec/generate.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Non-blocking: You could split by `.` instead of `/` here, leading to shorter string in the `if` below
</blockquote></details>

I actually prefer longer version with `deterministicgas.` in prefix

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 5 files at r3, 2 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/463)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Pull request merged**
