### PR TITLE
Separation of issuer and admin for fungible tokens

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: 20 of 29 files reviewed, 4 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 45 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nw4Yp1i1pV-nCVrvJns:-Nw4Yp1i1pV-nCVrvJnt:b-pr566j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28bd017f41f629d085660674bf084a21f6f4ea58/proto/coreum/asset/ft/v1/tx.proto#L45)):*
> ```proto
> 
>   // TransferAdmin changes admin of a fungible token.
>   rpc TransferAdmin(MsgTransferAdmin) returns (EmptyResponse);
> ```

Don't we need the admin removal ?
@ysv @miladz68 @wojtek-coreum 
___
*[`x/asset/ft/keeper/migrations.go` line 39 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nw4XLDFAtgA6nIdAa2y:-Nw4XLDFAtgA6nIdAa2z:b3g8fdn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28bd017f41f629d085660674bf084a21f6f4ea58/x/asset/ft/keeper/migrations.go#L39)):*
> ```Go
> 
> // Migrate3to4 migrates from version 3 to 4.
> func (m Migrator) Migrate3to4(ctx sdk.Context) error {
> ```

You also need to add upgrade integration test for it, please check (integration-tests/upgrade/upgrade_test.go). 
It might require the crust changes as well.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: 20 of 29 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1361 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nvl9mYh8a6gm-zzzLUJ:-NwKT864CvahoTd3JFGV:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/90405fd39f701b6e2494c3687188f054c783555b/integration-tests/modules/wasm_test.go#L1361)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

by wasm contract you mean our rust sdk ?
</blockquote></details>

Done.
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 45 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nw4Yp1i1pV-nCVrvJns:-Nw9SUkv7IUwdZzDMc3v:b-mxb28e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28bd017f41f629d085660674bf084a21f6f4ea58/proto/coreum/asset/ft/v1/tx.proto#L45)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Don't we need the admin removal ?
@ysv @miladz68 @wojtek-coreum
</blockquote></details>

A follow up question would be:
Are we going to support having multiple admins for a token or not
___
*[`x/asset/ft/keeper/migrations.go` line 39 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nw4XLDFAtgA6nIdAa2y:-NwKUKbTDcXA5b0xWAKT:b2isutq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28bd017f41f629d085660674bf084a21f6f4ea58/x/asset/ft/keeper/migrations.go#L39)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You also need to add upgrade integration test for it, please check (integration-tests/upgrade/upgrade_test.go). 
It might require the crust changes as well.
</blockquote></details>

Should I write an upgrade for v4 or v3patch3?
___
*[`x/asset/ft/migrations/v3/definitions.go` line 25 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nvl5ZgC2uR8Kf0OYrU5:-NwKUcPLC9RjLjs8PsZ-:b-evs9so) ([raw file](https://github.com/CoreumFoundation/coreum/blob/90405fd39f701b6e2494c3687188f054c783555b/x/asset/ft/migrations/v3/definitions.go#L25)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

definition has the issuer field, use that
</blockquote></details>

I'm gonna need the subunit anyways, so it won't do much here

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: 19 of 29 files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 45 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nw4Yp1i1pV-nCVrvJns:-NwOBRIWA2Wj8cM8H7Eb:b-7gycxr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28bd017f41f629d085660674bf084a21f6f4ea58/proto/coreum/asset/ft/v1/tx.proto#L45)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

A follow up question would be:
Are we going to support having multiple admins for a token or not
</blockquote></details>

I mean do we need an sdm.Message to remove admin completely?

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: 19 of 29 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 45 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nw4Yp1i1pV-nCVrvJns:-NwOFgki7kLaBXCSYL5o:b-wgrejf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28bd017f41f629d085660674bf084a21f6f4ea58/proto/coreum/asset/ft/v1/tx.proto#L45)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I mean do we need an sdm.Message to remove admin completely?
</blockquote></details>

I don't think so. This would limit sovereignty of a token indefinitely. If you have a use-case for it, we can discuss it after daily
___
*[`x/asset/ft/keeper/migrations.go` line 39 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nw4XLDFAtgA6nIdAa2y:-NwOGwit2vGSKYxULLSP:bh3shan) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28bd017f41f629d085660674bf084a21f6f4ea58/x/asset/ft/keeper/migrations.go#L39)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Should I write an upgrade for v4 or v3patch3?
</blockquote></details>

And also I think I need to wait for https://github.com/CoreumFoundation/coreum/pull/809 to merge first

**Review by miladz68 — APPROVED** [review]
> Reviewed 9 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 45 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nw4Yp1i1pV-nCVrvJns:-NwOaThv1t8ua7PMCEuF:bjm5m9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28bd017f41f629d085660674bf084a21f6f4ea58/proto/coreum/asset/ft/v1/tx.proto#L45)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I don't think so. This would limit sovereignty of a token indefinitely. If you have a use-case for it, we can discuss it after daily
</blockquote></details>

we would like to have that feature probably. But we should discuss it with Reza first.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 45 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nw4Yp1i1pV-nCVrvJns:-NwOoYhf2tTiGkRIpMNP:b1q1d8k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28bd017f41f629d085660674bf084a21f6f4ea58/proto/coreum/asset/ft/v1/tx.proto#L45)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we would like to have that feature probably. But we should discuss it with Reza first.
</blockquote></details>

Let's discuss it today.
___
*[`x/asset/ft/keeper/migrations.go` line 39 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nw4XLDFAtgA6nIdAa2y:-NwOoc4XBX2XU9Ikwg4m:bbw4lxl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28bd017f41f629d085660674bf084a21f6f4ea58/x/asset/ft/keeper/migrations.go#L39)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

And also I think I need to wait for https://github.com/CoreumFoundation/coreum/pull/809 to merge first
</blockquote></details>

Right.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: 13 of 32 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 45 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nw4Yp1i1pV-nCVrvJns:-Nwd72N3B6iULSzPGkL6:bk0rgcg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28bd017f41f629d085660674bf084a21f6f4ea58/proto/coreum/asset/ft/v1/tx.proto#L45)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

It is decided that we need this feature but as an other task
</blockquote></details>

Dropping admin functionality added

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: 13 of 32 files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1361 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nwd76q19XwAp81MtwAq:-Nwd76q19XwAp81MtwAr:b-akmjit) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c3845a67ab12cebfbedc3f1ee52b1bdfeaad2fda/integration-tests/modules/wasm_test.go#L1361)):*
> ```Go
> 	requireT.NoError(json.Unmarshal(queryOut, &wasmTokenRes))
> 	wasmTokenRes.Token.Version = expectedToken.Version // test should work with any version
> 	// TODO(masih): Remove this line, once WASM SDK is updated
> ```

@keyleu Could you please add a TODO for the WASM SDK update to resolve all ` Remove this line, once WASM SDK is updated` comments. 
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 136 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nwd5-pq7jy_xDVqtDnH:-Nwd5-pq7jy_xDVqtDnI:beqp5xb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c3845a67ab12cebfbedc3f1ee52b1bdfeaad2fda/proto/coreum/asset/ft/v1/tx.proto#L136)):*
> ```proto
> }
> 
> message MsgDropAdmin {
> ```

You mentioned that it should be in a separate task, but it's here :-)
`RemoveAdmin` IMO is a better name or `ClearAdmin` (similar to wasm). @ysv @miladz68 @wojtek-coreum WDYT ?
___
*[`x/asset/ft/keeper/keeper.go` line 983 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nwd5voz497aoxRKpEaJ:-Nwd5voz497aoxRKpEaK:b-2rwolv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c3845a67ab12cebfbedc3f1ee52b1bdfeaad2fda/x/asset/ft/keeper/keeper.go#L983)):*
> ```Go
> 
> 	if def.IsAdmin(addr) {
> 		return sdkerrors.Wrap(cosmoserrors.ErrUnauthorized, "issuer's balance can't be frozen")
> ```

Update error text, and check whether there are other errors with `issuer`.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: 13 of 32 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 136 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nwd5-pq7jy_xDVqtDnH:-NwdMvau2zLldIbF7y5M:b-mhb0n8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c3845a67ab12cebfbedc3f1ee52b1bdfeaad2fda/proto/coreum/asset/ft/v1/tx.proto#L136)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You mentioned that it should be in a separate task, but it's here :-)
`RemoveAdmin` IMO is a better name or `ClearAdmin` (similar to wasm). @ysv @miladz68 @wojtek-coreum WDYT ?
</blockquote></details>

Yeah, I was going to do that in a separate PR, but since my PRs are open for a while and they have some fundamental changed, I did it here.
I'm open to change the name but it is good enough IMO
___
*[`x/asset/ft/keeper/keeper.go` line 983 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nwd5voz497aoxRKpEaJ:-NwdNRH74tE_R1wGGbPC:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c3845a67ab12cebfbedc3f1ee52b1bdfeaad2fda/x/asset/ft/keeper/keeper.go#L983)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Update error text, and check whether there are other errors with `issuer`.
</blockquote></details>

Done.

**Review by miladz68 — DISMISSED** [review]
> Reviewed 19 of 19 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 136 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nwd5-pq7jy_xDVqtDnH:-NwdNwvP9ijuT8ySIDke:b-rxeq5d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c3845a67ab12cebfbedc3f1ee52b1bdfeaad2fda/proto/coreum/asset/ft/v1/tx.proto#L136)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Yeah, I was going to do that in a separate PR, but since my PRs are open for a while and they have some fundamental changed, I did it here.
I'm open to change the name but it is good enough IMO
</blockquote></details>

ClearAdmin is better.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: 11 of 32 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 136 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nwd5-pq7jy_xDVqtDnH:-Nwdbw72BwPzPLg2bSDo:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c3845a67ab12cebfbedc3f1ee52b1bdfeaad2fda/proto/coreum/asset/ft/v1/tx.proto#L136)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

ClearAdmin is better.
</blockquote></details>

Done.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: 11 of 32 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1361 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nwd76q19XwAp81MtwAq:-Nwddc7A8O4Zt-95Ota2:b-i41ttc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c3845a67ab12cebfbedc3f1ee52b1bdfeaad2fda/integration-tests/modules/wasm_test.go#L1361)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@keyleu Could you please add a TODO for the WASM SDK update to resolve all ` Remove this line, once WASM SDK is updated` comments.
</blockquote></details>

We have a task for this already.

**Review by miladz68 — APPROVED** [review]
> Reviewed 18 of 21 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nwe1TkiCLN-QcQtJYKc:-Nwe1TkiCLN-QcQtJYKd:bhurio) (no related file):*
The code is good now. Blocked until we finish discussions. 

___

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/805#-Nwe1TkiCLN-QcQtJYKc:-NwoEv_aDpAdb-VWDL3s:b8nsszg) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The code is good now. Blocked until we finish discussions.
</blockquote></details>

We decided that everything related to issuer should be handed over to admin which is current implementation

___

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 7 of 28 files at r1, 1 of 19 files at r4, 10 of 21 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, 12 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 8 of 12 files at r9, 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 4 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 9 of 9 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 9 of 9 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/805)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Pull request merged**
