### PR TITLE
wasmd branch importing module

### PR DESCRIPTION
**Pull request by oliverasistemas**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)

### CODE REVIEW

**Review by xlab — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N5d6ULXBMxwv-pZbO1n:-N5dRTDt6kbRiYX7gncC:blkw7yx) (no related file):*
> It will make troubles once we add more and more modules

Cosmos SDK practice is to add modules in the App yeah

> cosmos SDK is released forcing us to merge their and our changes.

Yes, and not just in the app, but across every corner of the project

> so the modifications made by us are mostly isolated from the original code generated by ignite.

Ignite's part in the `app` is almost useless, it's very simple to add a few lines. Ignite is needed in other places.

> Instead we could create separate function(s) in wasmconfig package which receive needed arguments (ModuleBasics, apps) and modify them accordingly

Let's not overcomplicate the app init logic and just follow common Cosmos SDK approach. It's already BaseApp that's being wrapped, our `App` is purely our chan logic and there is no sense to abstract away from the own logic. And yes, we should know `App` code from those files by heart.

___
___
*[`cored/app/app.go` line 119 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N5d3oQX4AbPErxAnQDf:-N5dSYaoDmB8FR0GnWRm:b-d8wkdi) ([raw file](https://github.com/coreumfoundation/coreum/blob/c76aefc2cec2d2505a696abd989ffe8bd1c1309a/cored/app/app.go#L119)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would recommend to leave this function untouched (for easier upgrades in the future) and instead create a function `wasmconfig.AddGovProposalHandlers(govProposalHandlers []govclient.ProposalHandler) []govclient.ProposalHandler`

taking the original handlers and extending them by those required by wasm. The `wasmconfig.AddGovProposalHandlers` should be called in the place where `getGovProposalHandlers` is called now.
</blockquote></details>

Replacing a single line of `govProposalHandlers = append(govProposalHandlers, wasmclient.ProposalHandlers...)` with `wasmconfig.AddGovProposalHandlers` doesn't change anything at the moment.
___
*[`cored/app/app.go` line 123 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N5b8IQY4IZv8FkAYOCb:-N5dS_s2-Ast_u5dUaD6:bib64r1) ([raw file](https://github.com/coreumfoundation/coreum/blob/c76aefc2cec2d2505a696abd989ffe8bd1c1309a/cored/app/app.go#L123)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

or preallocate slice: `govProposalHandlers := make([]govclient.ProposalHandler, len(wasmclient.ProposalHandlers))` so `copy` doesn't panic
</blockquote></details>

There are many ways to do that, but why avoid just a simple `append`. The easiest solution is on the surface, if used properly append is harmless there.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 5 unresolved discussions (waiting on @oliverasistemas and @xlab)

___
*[`app/app.go` line 123 at r14](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N68BTYW1kxJNkfxd3aj:-N68BTYX2Vlkx2wqQZoi:b-mqtaky) ([raw file](https://github.com/coreumfoundation/coreum/blob/4df0f2ba0b7e1d3e0986e669176701577172dfe6/app/app.go#L123)):*
> ```Go
> 	// this line is used by starport scaffolding # stargate/app/govProposalHandlers
> 
> 	copy(govProposalHandlers, wasmclient.ProposalHandlers)
> ```

It will panic because `govProposalHandlers` is not allocated
___
*[`app/app.go` line 306 at r14](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N68Buhq9Juy0mHpkZ6F:-N68Buhq9Juy0mHpkZ6G:btlaztp) ([raw file](https://github.com/coreumfoundation/coreum/blob/4df0f2ba0b7e1d3e0986e669176701577172dfe6/app/app.go#L306)):*
> ```Go
> 	// this line is used by starport scaffolding # stargate/app/scopedKeeper
> 
> 	scopedWASMKeeper := app.CapabilityKeeper.ScopeToModule(wasm.ModuleName)
> ```

This line is far away from the place where `scopedWASMKeeper` is really used.
You could just call `app.CapabilityKeeper.ScopeToModule(wasm.ModuleName)` directly there
___
*[`app/app.go` line 404 at r14](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N68CHul3OlwKbXAq_4W:-N68CHul3OlwKbXAq_4X:b-rk17b3) ([raw file](https://github.com/coreumfoundation/coreum/blob/4df0f2ba0b7e1d3e0986e669176701577172dfe6/app/app.go#L404)):*
> ```Go
> 	)
> 
> 	enabledProposals := wasm.EnableAllProposals
> ```

You don't need `enabledProposals`, you may use `wasm.EnableAllProposals` directly in both places below
___
*[`app/app.go` line 405 at r14](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N68CQ1o5rK7H4skgCxf:-N68CQ1o5rK7H4skgCxg:bez7bfx) ([raw file](https://github.com/coreumfoundation/coreum/blob/4df0f2ba0b7e1d3e0986e669176701577172dfe6/app/app.go#L405)):*
> ```Go
> 
> 	enabledProposals := wasm.EnableAllProposals
> 	if len(enabledProposals) != 0 {
> ```

Do we need this `if` at all? Might it happen that `wasm.EnableAllProposals`? If the authors make this slice empty without removing it, we should just remove the next line at that moment

**Comment by xlab** [comment]
*[`app/app.go` line 123 at r14](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N68BTYW1kxJNkfxd3aj:-N68q6EWEUkBCX8sZo4Z:b-mnyapt) ([raw file](https://github.com/coreumfoundation/coreum/blob/4df0f2ba0b7e1d3e0986e669176701577172dfe6/app/app.go#L123)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It will panic because `govProposalHandlers` is not allocated
</blockquote></details>

I think we already had a lengthy discussion that `append` must be used there.

**Review by xlab — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 5 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, and @xlab)

**Review by oliverasistemas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N5d6ULXBMxwv-pZbO1n:-N5jXuNWAxFNEZ74ngNY:bt4sodl) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

My thoughts from Slack



</blockquote></details>

@wojtek-coreum @xlab I believe current approach is simpler for now.

___
___
*[`cored/app/app.go` line 119 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N5d3oQX4AbPErxAnQDf:-N5jYXVp6B-CeHa-jviS:brbalw5) ([raw file](https://github.com/coreumfoundation/coreum/blob/c76aefc2cec2d2505a696abd989ffe8bd1c1309a/cored/app/app.go#L119)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

Replacing a single line of `govProposalHandlers = append(govProposalHandlers, wasmclient.ProposalHandlers...)` with `wasmconfig.AddGovProposalHandlers` doesn't change anything at the moment.
</blockquote></details>

I agree with @xlab

**Review by xlab — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 5 unresolved discussions (waiting on @oliverasistemas and @wojtek-coreum)

___
*[`app/app.go` line 120 at r15](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N6Iz7tb1iRGKHthB3Zi:-N6Iz7tb1iRGKHthB3Zj:b-xi9jrx) ([raw file](https://github.com/coreumfoundation/coreum/blob/e12c7c8271afb7c0400e3ba3632fe09f8022873f/app/app.go#L120)):*
> ```Go
> 	// this line is used by starport scaffolding # stargate/app/govProposalHandlers
> 
> 	copy(govProposalHandlers, wasmclient.ProposalHandlers)
> ```

This line is still buggy

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 5 unresolved discussions (waiting on @oliverasistemas and @wojtek-coreum)

**Review by oliverasistemas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`cored/app/app.go` line 306 at r13](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N5d5f9C35arEc6QaYWC:-N6cZfbZ8_vACwZKEdrz:bzgbg6s) ([raw file](https://github.com/coreumfoundation/coreum/blob/c76aefc2cec2d2505a696abd989ffe8bd1c1309a/cored/app/app.go#L306)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This line is far away from the place where `scopedWASMKeeper` is really used.
You could just call `app.CapabilityKeeper.ScopeToModule(wasm.ModuleName)` directly there
</blockquote></details>

Inline scoped scopedWASMKeeper

**Review by oliverasistemas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`app/app.go` line 306 at r14](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N68Buhq9Juy0mHpkZ6F:-N6c_C1PCoNWZ_GwsH_k:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/4df0f2ba0b7e1d3e0986e669176701577172dfe6/app/app.go#L306)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This line is far away from the place where `scopedWASMKeeper` is really used.
You could just call `app.CapabilityKeeper.ScopeToModule(wasm.ModuleName)` directly there
</blockquote></details>

Done.

**Review by oliverasistemas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`app/app.go` line 123 at r14](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N68BTYW1kxJNkfxd3aj:-N6cfSHD3oTiPhV8CfC_:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/4df0f2ba0b7e1d3e0986e669176701577172dfe6/app/app.go#L123)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>


</blockquote></details>

Done.
___
*[`app/app.go` line 120 at r15](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N6Iz7tb1iRGKHthB3Zi:-N6cfU766FO9SMeH8shu:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e12c7c8271afb7c0400e3ba3632fe09f8022873f/app/app.go#L120)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

This line is still buggy
</blockquote></details>

Done.

**Review by oliverasistemas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @wojtek-coreum and @xlab)

___
*[`app/app.go` line 404 at r14](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N68CHul3OlwKbXAq_4W:-N6cjFqu3CjonmT-rF0Q:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/4df0f2ba0b7e1d3e0986e669176701577172dfe6/app/app.go#L404)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You don't need `enabledProposals`, you may use `wasm.EnableAllProposals` directly in both places below
</blockquote></details>

Done.
___
*[`app/app.go` line 405 at r14](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N68CQ1o5rK7H4skgCxf:-N6cjGAl7c8PsFtlp6vd:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/4df0f2ba0b7e1d3e0986e669176701577172dfe6/app/app.go#L405)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do we need this `if` at all? Might it happen that `wasm.EnableAllProposals`? If the authors make this slice empty without removing it, we should just remove the next line at that moment
</blockquote></details>

Done.

**Review by xlab — DISMISSED** [review]
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 5 unresolved discussions (waiting on @wojtek-coreum and @xlab)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 2 unresolved discussions (waiting on @oliverasistemas and @xlab)

___
*[`app/app.go` line 120 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N6lovZkDz4DoAsU0PoP:-N6lovZlCo0EeyWRmmlk:b-shcyhq) ([raw file](https://github.com/coreumfoundation/coreum/blob/9d14096391ab64e476a1ebfaa1b756994fe53b61/app/app.go#L120)):*
> ```Go
> 	// this line is used by starport scaffolding # stargate/app/govProposalHandlers
> 
> 	govProposalHandlers = append(govProposalHandlers, wasmclient.ProposalHandlers...)
> ```

tiny improvement: `govProposalHandlers := append([]govclient.ProposalHandler{}, ...`

**Review by oliverasistemas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @xlab)

___
*[`app/app.go` line 120 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N6lovZkDz4DoAsU0PoP:-N6nmE1uBz9WWgItk5FM:bocycvl) ([raw file](https://github.com/coreumfoundation/coreum/blob/9d14096391ab64e476a1ebfaa1b756994fe53b61/app/app.go#L120)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

tiny improvement: `govProposalHandlers := append([]govclient.ProposalHandler{}, ...`
</blockquote></details>

@wojtek-coreum  I am not sure I understand which is the improvement or the change you want to be applied.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`app/app.go` line 120 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N6lovZkDz4DoAsU0PoP:-N6o4I-v4jS16LZKMUDz:b567gdi) ([raw file](https://github.com/coreumfoundation/coreum/blob/9d14096391ab64e476a1ebfaa1b756994fe53b61/app/app.go#L120)):*
<details><summary><i>Previously, oliverasistemas (Adolfo Olivera) wrote…</i></summary><blockquote>

@wojtek-coreum  I am not sure I understand which is the improvement or the change you want to be applied.
</blockquote></details>

You don't need to declare empty slice on one line and add items to it on second one. You may do both in one place. I don't care too much but it makes easier to understand the code when I don't need to check what's already inside `govProposalHandlers` when I see `append(govProposalHandlers...`

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`app/wasmconfig/config.go` line 15 at r19](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N6o4uG19EIm-7AFKPPu:-N6o4uG20MD_fW0_3_PI:b-rj0wx6) ([raw file](https://github.com/coreumfoundation/coreum/blob/1160dd6d147091204e7df6e95c6d2422be1e46d3/app/wasmconfig/config.go#L15)):*
> ```Go
> )
> 
> // DefaultWASMConfig Returns wasm config
> ```

Returns wasm -> returns WASM

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r19, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 3 unresolved discussions (waiting on @oliverasistemas and @xlab)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 4 unresolved discussions (waiting on @oliverasistemas and @xlab)

___
*[`pkg/config/genesis/genesis.tmpl.json` line 214 at r21](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N6rSByI9cGWW5RIb-mY:-N6rSByJ34H0dPXtjNlc:b-gpr0bv) ([raw file](https://github.com/coreumfoundation/coreum/blob/6488c4161413cf8b67f4e89d563ea8914f5ec041/pkg/config/genesis/genesis.tmpl.json#L214)):*
> ```JSON
>     "wasm": {
>       "params": {
>         "instantiate_default_permission": "Everybody",
> ```

what does it mean? should it be set globally for every network (mainnet, devnet...) or should it be parameterized?

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 2 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 4 unresolved discussions (waiting on @oliverasistemas and @xlab)

**Review by oliverasistemas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @xlab)

___
*[`app/app.go` line 120 at r18](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N6lovZkDz4DoAsU0PoP:-N72ANtxAo1_oQGfL8QI:bd7ya48) ([raw file](https://github.com/coreumfoundation/coreum/blob/9d14096391ab64e476a1ebfaa1b756994fe53b61/app/app.go#L120)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You don't need to declare empty slice on one line and add items to it on second one. You may do both in one place. I don't care too much but it makes easier to understand the code when I don't need to check what's already inside `govProposalHandlers` when I see `append(govProposalHandlers...`
</blockquote></details>

This is cosmetic and I am not 100% sure that this change is not going to mess with ignite scaffolding comments. which might depend on the variable been initialized before. 
___
*[`pkg/config/genesis/genesis.tmpl.json` line 214 at r21](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N6rSByI9cGWW5RIb-mY:-N72AyLjA2RhNG3MyGlW:b-8rptdp) ([raw file](https://github.com/coreumfoundation/coreum/blob/6488c4161413cf8b67f4e89d563ea8914f5ec041/pkg/config/genesis/genesis.tmpl.json#L214)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what does it mean? should it be set globally for every network (mainnet, devnet...) or should it be parameterized?
</blockquote></details>

It is probably going to be parameterized in the future. 
___
*[`app/wasmconfig/config.go` line 15 at r19](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N6o4uG19EIm-7AFKPPu:-N72AlMO4doF4ZIw6qMF:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/1160dd6d147091204e7df6e95c6d2422be1e46d3/app/wasmconfig/config.go#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Returns wasm -> returns WASM
</blockquote></details>

Done

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 2 unresolved discussions (waiting on @oliverasistemas and @xlab)

___
*[`app/wasmconfig/config.go` line 15 at r19](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N6o4uG19EIm-7AFKPPu:-N7F4e53EwGt-HjHJnL1:bk9fzjq) ([raw file](https://github.com/coreumfoundation/coreum/blob/1160dd6d147091204e7df6e95c6d2422be1e46d3/app/wasmconfig/config.go#L15)):*
<details><summary><i>Previously, oliverasistemas (Adolfo Olivera) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Returns -> returns

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 2 unresolved discussions (waiting on @oliverasistemas and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N7K2pwe7SCtFouctFXx:-N7K2pwf9CQ4nIu07ZFk:bs74dsw) (no related file):*
This PR is fine. Just blocking it until integration test is ready in `crust`.

___

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91#-:-N7K33Nm02AFw-FPjQjN:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @oliverasistemas and @xlab)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 2 unresolved discussions (waiting on @oliverasistemas and @xlab)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 2 unresolved discussions (waiting on @oliverasistemas and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/91#-N7K2pwe7SCtFouctFXx:-N7b86BY9Yh6VDMHX4aX:b9i17pj) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This PR is fine. Just blocking it until integration test is ready in `crust`.
</blockquote></details>

Changed it to non-blocking so it might be merged if integration tests are ready before I come back

___

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 2 unresolved discussions (waiting on @oliverasistemas and @xlab)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 3 of 3 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 2 unresolved discussions (waiting on @oliverasistemas and @xlab)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 2 files at r22, 1 of 1 files at r25, 3 of 3 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 2 unresolved discussions (waiting on @oliverasistemas and @xlab)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 2 unresolved discussions (waiting on @oliverasistemas and @xlab)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: 5 of 29 files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 2 files at r12, 3 of 7 files at r14, 1 of 2 files at r22, 6 of 15 files at r29, 1 of 1 files at r30, 1 of 1 files at r31, 11 of 12 files at r32, 5 of 5 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @xlab)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 4 of 5 files at r33, 21 of 21 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 1 unresolved discussion (waiting on @xlab)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 2 of 21 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 1 unresolved discussion (waiting on @xlab)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r33, 2 of 21 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 3 unresolved discussions (waiting on @oliverasistemas and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/91#-NAKooNu103EC6krJ5J6:-NAKooNu103EC6krJ5J7:b1ijmhv) (no related file):*
@dzmitryhil is it possible to do smth with this PR because it show plenty of files not related to it in diff ?
Probably some issue with rebasing

___
___
*[`app/wasmconfig/config.go` line 8 at r34](https://reviewable.io/reviews/coreumfoundation/coreum/91#-NAKof-y1rdyoRpKGseC:-NAKof-y1rdyoRpKGseD:b-h9hg89) ([raw file](https://github.com/coreumfoundation/coreum/blob/5eb6e12dacc5d9c1c1a1e6dd897c66ef19bf77ae/app/wasmconfig/config.go#L8)):*
> ```Go
> 
> // config default values
> const (
> ```

can you make a brief review of this params
Are these good values ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 3 unresolved discussions (waiting on @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/91#-NAKooNu103EC6krJ5J6:-NAL676qEI8Z5rUZIB9m:bpi3v06) (no related file):*
> plenty
Is see just 6 files: https://github.com/CoreumFoundation/coreum/pull/91/files

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 3 unresolved discussions (waiting on @xlab and @ysv)

___
*[`app/wasmconfig/config.go` line 8 at r34](https://reviewable.io/reviews/coreumfoundation/coreum/91#-NAKof-y1rdyoRpKGseC:-NANk9BuAkC8WMYCowh0:b-4pda9g) ([raw file](https://github.com/coreumfoundation/coreum/blob/5eb6e12dacc5d9c1c1a1e6dd897c66ef19bf77ae/app/wasmconfig/config.go#L8)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can you make a brief review of this params
Are these good values ?
</blockquote></details>

They seems good enough, but the wasmd chain for example, allow to modify them per node, the same I would do. I wrote that point yesterday, so we will be able to deliver it in the separate PR.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: 28 of 30 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/wasmconfig/config.go` line 8 at r34](https://reviewable.io/reviews/coreumfoundation/coreum/91#-NAKof-y1rdyoRpKGseC:-NANksZ_DxGjxOSsviyU:b2xyk2m) ([raw file](https://github.com/coreumfoundation/coreum/blob/5eb6e12dacc5d9c1c1a1e6dd897c66ef19bf77ae/app/wasmconfig/config.go#L8)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

They seems good enough, but the wasmd chain for example, allow to modify them per node, the same I would do. I wrote that point yesterday, so we will be able to deliver it in the separate PR.
</blockquote></details>

I've updated the PR with the usage of the DefaultWasmConfig() provided by the wasm module directly. And as I mentioned in prev comment we will add an ability to override it per node later.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 2 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 3 unresolved discussions (waiting on @xlab and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 2 files at r35.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 2 unresolved discussions (waiting on @xlab and @ysv)

___
*[`app/wasmconfig/config.go` line 8 at r34](https://reviewable.io/reviews/coreumfoundation/coreum/91#-NAKof-y1rdyoRpKGseC:-NAON_5q4lOtq9AsSNYq:bqewkut) ([raw file](https://github.com/coreumfoundation/coreum/blob/5eb6e12dacc5d9c1c1a1e6dd897c66ef19bf77ae/app/wasmconfig/config.go#L8)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I've updated the PR with the usage of the DefaultWasmConfig() provided by the wasm module directly. And as I mentioned in prev comment we will add an ability to override it per node later.
</blockquote></details>

sounds reasonable

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/91)* status: all files reviewed, 2 unresolved discussions (waiting on @xlab and @ysv)

**Pull request merged**
