### PR TITLE
Turn off buggy WASM metrics

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

Due to buggy initialization of metrics collector, WASM causes panics when metrics are collected.
Bug is described here: https://github.com/CosmWasm/wasmd/issues/1574
and fixed here: https://github.com/CosmWasm/wasmd/pull/1575

Once v0.42 is released we may uncomment this code. Task has been created for this.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/637)

### CODE REVIEW

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/637)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @vertex451, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/637)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @vertex451, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 567 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/637#-Nddwq_ZAYiz_GnjcxR-:-Nddwq_ZAYiz_GnjcxR0:b253iaj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/97df6f4e89051035c2c6c9141a4174d4a7035f7e/app/app.go#L567)):*
> ```Go
> 
> 	// FIXME (wasmd-1575): This is commented out temporarily because it causes panics in telemetry server due to buggy
> 	// initialization of wasm vm in version v0.41 of wasmd.
> ```

But if it's fixed probably it's better to update the dependency?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/637)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/637)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, and @ysv)

___
*[`app/app.go` line 567 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/637#-Nddwq_ZAYiz_GnjcxR-:-Nddxeqq3s1lyZN-Uj4t:bhdx9rb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/97df6f4e89051035c2c6c9141a4174d4a7035f7e/app/app.go#L567)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But if it's fixed probably it's better to update the dependency?
</blockquote></details>

To the latest commit in master? But I'm not sure they follow the same very useful policy that every commit in master should work. That's why I prefer to wait until new official release.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/637)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @ysv)

___
*[`app/app.go` line 567 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/637#-Nddwq_ZAYiz_GnjcxR-:-NddygBE3VYvzi1fLolJ:bozn8ig) ([raw file](https://github.com/CoreumFoundation/coreum/blob/97df6f4e89051035c2c6c9141a4174d4a7035f7e/app/app.go#L567)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

To the latest commit in master? But I'm not sure they follow the same very useful policy that every commit in master should work. That's why I prefer to wait until new official release.
</blockquote></details>

Ok, agree. Do we have a corresponding task to enable it back?

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/637)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/637)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

___
*[`app/app.go` line 567 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/637#-Nddwq_ZAYiz_GnjcxR-:-NdeQ_rb7ZltI42eAbAI:bb7s9zy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/97df6f4e89051035c2c6c9141a4174d4a7035f7e/app/app.go#L567)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Ok, agree. Do we have a corresponding task to enable it back?
</blockquote></details>

yes

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/637)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
