### PR TITLE
Use sudo entry point for asset extension invocation

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)

### CODE REVIEW

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 198 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-NxqdcAICVzGX37E8EXd:-NxqdcAICVzGX37E8EXe:b86r4gs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/afba813a119d7c18f63c572c9af184ff9e676594/x/asset/ft/keeper/before_send.go#L198)):*
> ```Go
> 			CommissionAmount: commissionAmount,
> 			Context: sudoExtensionTransferContext{
> 				IBCPurpose: ibcPurposeToExtensionString(ibcPurpose),
> ```

Maybe you can add these two here now:
```
SenderIsSmartContract:    cwasmtypes.IsSendingSmartContract(ctx, sender.String()),
RecipientIsSmartContract: cwasmtypes.IsReceivingSmartContract(ctx, recipient.String()),
```
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 77 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Nxqf0pSAYobJc2Pibuc:-Nxqf0pSAYobJc2Pibud:b-qmd8zg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb42e0e131301db7a541aa6d284868e0f7aadadb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L77)):*
> ```XML
>     // check that amount is present in the attached funds, and attached funds is enough
>     // to cover the transfer.
>     let has_sufficient_funds = info
> ```

Why it is deleted?

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 198 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-NxqdcAICVzGX37E8EXd:-NxvptFJ9iUn14qwJBxY:b-3kyk6w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/afba813a119d7c18f63c572c9af184ff9e676594/x/asset/ft/keeper/before_send.go#L198)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this is a little more complicated that just those 2 functions. we have to check with the keeper as well. So I left it out for you to do with your tests.
</blockquote></details>

So, please leave comments or just remember to remind me

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 198 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-NxqdcAICVzGX37E8EXd:-Ny-PVrtE8kTKLGuT59_:b5jxfkw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/afba813a119d7c18f63c572c9af184ff9e676594/x/asset/ft/keeper/before_send.go#L198)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

So, please leave comments or just remember to remind me
</blockquote></details>

sure thing. I will let you know.

**Review by masihyeganeh — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 32 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-VFTwDqcs-61GTOg_:-Ny-VFTwDqcs-61GTOga:bibup4c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72f2ec9b729934a6f3006410d197e669084db9c8/x/asset/ft/keeper/before_send.go#L32)):*
> ```Go
> 	BurnAmount       sdkmath.Int                  `json:"burn_amount,omitempty"`
> 	CommissionAmount sdkmath.Int                  `json:"commission_amount,omitempty"`
> 	Context          sudoExtensionTransferContext `json:"context,omitempty"`
> ```

If the type is exported, then all the types used inside should be exported too
___
*[`x/asset/ft/keeper/before_send.go` line 42 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-VWNE86hhliDvpN_E:-Ny-VWNE86hhliDvpN_F:bzi0ysa) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72f2ec9b729934a6f3006410d197e669084db9c8/x/asset/ft/keeper/before_send.go#L42)):*
> ```Go
> }
> 
> func ibcPurposeToExtensionString(p wibctransfertypes.Purpose) string {
> ```

why the defined constants cannot be used directly?
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 62 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-WLhS-btY4H3TZXdr:-Ny-WLhS-btY4H3TZXds:bo26son) ([raw file](https://github.com/CoreumFoundation/coreum/blob/34d7081e16822126133b13c55e49e2b975c23bdb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L62)):*
> ```XML
>     recipient: String,
> ) -> CoreumResult<ContractError> {
>     // TODO remove this if statement.
> ```

comment removed, but the `if` is still there

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 36 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-VZR03Eui0F-YKo68:-Ny-VZR03Eui0F-YKo69:bfeq76v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72f2ec9b729934a6f3006410d197e669084db9c8/x/asset/ft/keeper/before_send.go#L36)):*
> ```Go
> 
> //nolint:tagliatelle // these will be exposed to rust and must be snake case.
> type sudoExtensionTransferContext struct {
> ```

If the message `SudoExtensionTransferMsg` is exported, all it's types should be exported. 
___
*[`x/asset/ft/keeper/before_send.go` line 39 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-W2nK1Cfi80eML4A8:-Ny-W2nK1Cfi80eML4A9:b-qg8t4c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72f2ec9b729934a6f3006410d197e669084db9c8/x/asset/ft/keeper/before_send.go#L39)):*
> ```Go
> 	SenderIsSmartContract    bool   `json:"sender_is_smart_contract"`
> 	RecipientIsSmartContract bool   `json:"recipient_is_smart_contract"`
> 	IBCPurpose               string `json:"ibc_purpose"`
> ```

You integrate the IBC in that PR, but I don't see tests for it. 
___
*[`x/asset/ft/keeper/before_send.go` line 42 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-VqUe7-kj9XjY5nqK:-Ny-VqUe7-kj9XjY5nqL:blyxgg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72f2ec9b729934a6f3006410d197e669084db9c8/x/asset/ft/keeper/before_send.go#L42)):*
> ```Go
> }
> 
> func ibcPurposeToExtensionString(p wibctransfertypes.Purpose) string {
> ```

IMO you can use `wibctransfertypes.Purpose` strings, and if the `Purpose` isn't set in the context, "none".

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 32 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-VFTwDqcs-61GTOg_:-Ny-X70X73IS-CX09nQg:b6brru2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72f2ec9b729934a6f3006410d197e669084db9c8/x/asset/ft/keeper/before_send.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If the type is exported, then all the types used inside should be exported too
</blockquote></details>

Unexported the type. 
___
*[`x/asset/ft/keeper/before_send.go` line 36 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-VZR03Eui0F-YKo68:-Ny-XA7u0frzDZJN_-gQ:b6brru2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72f2ec9b729934a6f3006410d197e669084db9c8/x/asset/ft/keeper/before_send.go#L36)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

If the message `SudoExtensionTransferMsg` is exported, all it's types should be exported.
</blockquote></details>

Unexported the type. 
___
*[`x/asset/ft/keeper/before_send.go` line 39 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-W2nK1Cfi80eML4A8:-Ny-XBZlBE11jpvqkz1e:bizmo4o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72f2ec9b729934a6f3006410d197e669084db9c8/x/asset/ft/keeper/before_send.go#L39)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You integrate the IBC in that PR, but I don't see tests for it.
</blockquote></details>

I am not integrating the IBC, I will do it in a separate PR, the interface is there so me and Masih can work in parallel. 
___
*[`x/asset/ft/keeper/before_send.go` line 42 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-VWNE86hhliDvpN_E:-Ny-XQ-i3HCh2D2CV2-J:bf9ng6m) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72f2ec9b729934a6f3006410d197e669084db9c8/x/asset/ft/keeper/before_send.go#L42)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why the defined constants cannot be used directly?
</blockquote></details>

rust is using snake case for their enums.
___
*[`x/asset/ft/keeper/before_send.go` line 42 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-VqUe7-kj9XjY5nqK:-Ny-XcpR2WVVatxZYyGP:b-m9g2f3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72f2ec9b729934a6f3006410d197e669084db9c8/x/asset/ft/keeper/before_send.go#L42)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO you can use `wibctransfertypes.Purpose` strings, and if the `Purpose` isn't set in the context, "none".
</blockquote></details>

rust is using snake case for their enums. that is why I am converting them. I can use rust macros to parse strings but that would not look nice on the rust side. or change the strings here. 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 62 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-WLhS-btY4H3TZXdr:-Ny-Y-YI0VJErBgbyA0L:btx1sl7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/34d7081e16822126133b13c55e49e2b975c23bdb/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L62)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

comment removed, but the `if` is still there
</blockquote></details>

yes, I cannot think of another way to add these test conditions. the original plan was to use this contract both for testing and for template, but I now see that it cannot be acheived, and we need a separate contract to serve as template.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 42 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-VqUe7-kj9XjY5nqK:-Ny-ZkP4ElycT6KlWEEX:b5u1g8f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72f2ec9b729934a6f3006410d197e669084db9c8/x/asset/ft/keeper/before_send.go#L42)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

rust is using snake case for their enums. that is why I am converting them. I can use rust macros to parse strings but that would not look nice on the rust side. or change the strings here.
</blockquote></details>

But wount it work if you use `ibc_transfer_timeout` for example on the rust side?

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 42 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-VqUe7-kj9XjY5nqK:-Ny-b5df52ydjdYlxL5h:b-pzbex7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72f2ec9b729934a6f3006410d197e669084db9c8/x/asset/ft/keeper/before_send.go#L42)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But wount it work if you use `ibc_transfer_timeout` for example on the rust side?
</blockquote></details>

it would work on the rust side. but the string on the go side is `ibcTransferTimeout` and I need to change that one. also `ibcTransfer` at the start of the string is repetitive and redundant.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 42 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-VqUe7-kj9XjY5nqK:-Ny-c-jX8etNVu1xOMg7:b-e64u4u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72f2ec9b729934a6f3006410d197e669084db9c8/x/asset/ft/keeper/before_send.go#L42)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it would work on the rust side. but the string on the go side is `ibcTransferTimeout` and I need to change that one. also `ibcTransfer` at the start of the string is repetitive and redundant.
</blockquote></details>

Did you just try to use the snake case on the rust side and keep the camel case in the go?.
If you don't want to use  `ibcTransfer` prefix, why not remove it from the`wibctransfertypes.Purpose`, will it break something?

**Review by wojtek-coreum — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 42 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-VqUe7-kj9XjY5nqK:-Ny-gHpx3VuQ_D8lYyt_:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/72f2ec9b729934a6f3006410d197e669084db9c8/x/asset/ft/keeper/before_send.go#L42)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Did you just try to use the snake case on the rust side and keep the camel case in the go?.
If you don't want to use  `ibcTransfer` prefix, why not remove it from the`wibctransfertypes.Purpose`, will it break something?
</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 43 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-gM-JDFSQkV2Jaelg:-Ny-gM-JDFSQkV2Jaelh:bfs965l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f298fbe3d7a5e8623fcbc8bbcd9e37617c4f3a74/x/asset/ft/keeper/before_send.go#L43)):*
> ```Go
> 
> func ibcPurposeToExtensionString(ctx sdk.Context) string {
> 	ibcPurpose, _ := wibctransfertypes.GetPurpose(ctx)
> ```

ibcPurpose, ok := wibctransfertypes.GetPurpose(ctx)
You should use `ok` instead of empty string.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 43 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/832#-Ny-gM-JDFSQkV2Jaelg:-Ny-hCcYB6VExSGQahmz:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f298fbe3d7a5e8623fcbc8bbcd9e37617c4f3a74/x/asset/ft/keeper/before_send.go#L43)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

ibcPurpose, ok := wibctransfertypes.GetPurpose(ctx)
You should use `ok` instead of empty string.
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/832)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
