### PR TITLE
improved TestIBCTransferFromGaiaToCoreumAndBack test

### PR DESCRIPTION
**Pull request by vertex451**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/520)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/520)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/ibc/transfer_test.go` line 68 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/520#-NX9EBbW8kwOfIg4cU5V:-NX9EBbW8kwOfIg4cU5W:b-ftqccn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ee36a93aadabbe95d196000a57fdaf0de7ed95fd/integration-tests/ibc/transfer_test.go#L68)):*
> ```Go
> 
> 	// Fund accounts
> 	coreumChain.Faucet.FundAccounts(ctx, t, integrationtests.FundedAccount{
> ```

`Messages: []sdk.Msg{&banksyptes.MsgSend{}},` is missing
___
*[`integration-tests/ibc/transfer_test.go` line 100 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/520#-NX9EXKi3IuVb03raWRc:-NX9EXKi3IuVb03raWRd:b-k0zgkk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ee36a93aadabbe95d196000a57fdaf0de7ed95fd/integration-tests/ibc/transfer_test.go#L100)):*
> ```Go
> 	)
> 	requireT.NoError(err)
> 	coreumChain.AwaitForBalance(ctx, t, coreumToGaiaSender, expectedBalanceAtCoreum)
> ```

you may check the final balance using normal bank client because the operation is done immediately

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/520)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/transfer_test.go` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/520#-NXAQZJRA11GhUhhdxQL:-NXAQZJRA11GhUhhdxQM:b-ejkk3f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ee36a93aadabbe95d196000a57fdaf0de7ed95fd/integration-tests/ibc/transfer_test.go#L63)):*
> ```Go
> 
> 	// Generate accounts
> 	gaiaAccount := gaiaChain.GenAccount()
> ```

What is the issue with prev name `gaiaSender` ?
___
*[`integration-tests/ibc/transfer_test.go` line 68 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/520#-NX9EBbW8kwOfIg4cU5V:-NXAQruM5hf7LJvRcksh:b5cnr65) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ee36a93aadabbe95d196000a57fdaf0de7ed95fd/integration-tests/ibc/transfer_test.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`Messages: []sdk.Msg{&banksyptes.MsgSend{}},` is missing
</blockquote></details>

Right and `Amount:  coreumChain.NewCoin(sdk.NewInt(1000000)),` should be removed as well. 
___
*[`integration-tests/ibc/transfer_test.go` line 80 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/520#-NXAR3CM9Z9AAfdEcIdx:-NXAR3CM9Z9AAfdEcIdy:b6c6nbt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ee36a93aadabbe95d196000a57fdaf0de7ed95fd/integration-tests/ibc/transfer_test.go#L80)):*
> ```Go
> 	})
> 
> 	// 1. Send from gaiaAccount to coreumToCoreumSender
> ```

Not sure that we need the `1.` `2.` indexes on the comment.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/520)* status: all files reviewed, 4 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/520)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/520)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/520)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/520)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @ysv)

___
*[`integration-tests/ibc/transfer_test.go` line 100 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/520#-NX9EXKi3IuVb03raWRc:-NXnoT1t3y5P3N54QSg0:bd0u6qe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ee36a93aadabbe95d196000a57fdaf0de7ed95fd/integration-tests/ibc/transfer_test.go#L100)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

I replaced that row with the following code:
```
	bankClient := banktypes.NewQueryClient(coreumChain.ClientContext)
	queryBalanceResponse, err := bankClient.Balance(ctx, &banktypes.QueryBalanceRequest{
		Address: coreumToGaiaSender.String(),
		Denom:   expectedBalanceAtCoreum.Denom,
	})
	requireT.NoError(err)
	assert.Equal(t, expectedBalanceAtCoreum.Amount, queryBalanceResponse.Balance.Amount)
```
Is it worth replacing? For me, the previous row seemed to be fine.

And also, I don't understand why a normal bank balance check guarantees the correct balance, what if we hit the moment before the send transaction will be included in a block?
</blockquote></details>

But `AwaitBalance` have long timeout causing dealys if the test does not pass

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/520)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @ysv)

___
*[`integration-tests/ibc/transfer_test.go` line 108 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/520#-NXnodNp9xIOQ6tgOm39:-NXnodNqCavF9hEjqUvp:bv0dfkq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/10dfa34fca87a3d24e2c52c70289eaf4db1620cc/integration-tests/ibc/transfer_test.go#L108)):*
> ```Go
> 	})
> 	requireT.NoError(err)
> 	assert.Equal(t, expectedBalanceAtCoreum.Amount, queryBalanceResponse.Balance.Amount)
> ```

Please use Amount.String() here to produce readable output

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/520)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/520)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/520)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Pull request merged**
