### PR TITLE
Allow burning for all and global freezing ignoring for the issuer

### PR DESCRIPTION
**Pull request by dzmitryhil**
* Allow the issuer to burn always and for others accounts if the burbing is enabled
* Allow the issuer to send coins even if the global freezing is enabled

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/assetft_test.go` line 665 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL1tcRM42sUAJHXBYaZ:-NL1tcRM42sUAJHXBYa_:b-tiqoc) ([raw file](https://github.com/coreumfoundation/coreum/blob/e8f6626e5a864627bd4c00e237201fcefed12a1b/integration-tests/modules/assetft_test.go#L665)):*
> ```Go
> 		freezeMsg,
> 	)
> 	assertT.True(sdkerrors.ErrUnauthorized.Is(err))
> ```

I thought a bit more about this error type & it probably makes sense to keep it
Unauthorized is different from FeatureDisabled & it is more specific
___
*[`x/asset/ft/keeper/freeze.go` line 91 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL1zROY3XaBYw7WqWXR:-NL1zROY3XaBYw7WqWXS:b-t79wni) ([raw file](https://github.com/coreumfoundation/coreum/blob/e8f6626e5a864627bd4c00e237201fcefed12a1b/x/asset/ft/keeper/freeze.go#L91)):*
> ```Go
> 
> 	// the issuer can use token even if it's globally frozen
> 	if k.isGloballyFrozen(ctx, ft.Denom) && ft.Issuer != addr.String() {
> ```

I would move this to aseparate if
it sounds more natural 
```
// on the 1st place to explicitly show that issuer don't care about freezing
if ft.Issuer == addr.String {
  return nil
}

if !featureEnabled {
  return nil 
}


```
___
*[`x/asset/ft/keeper/keeper.go` line 211 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL1w82H3su25iAM_O3d:-NL1w82H3su25iAM_O3e:bqm8ywg) ([raw file](https://github.com/coreumfoundation/coreum/blob/e8f6626e5a864627bd4c00e237201fcefed12a1b/x/asset/ft/keeper/keeper.go#L211)):*
> ```Go
> 
> func (k Keeper) checkFeatureAllowed(addr sdk.AccAddress, ftd types.FTDefinition, feature types.TokenFeature) error {
> 	featureEnabled := lo.Contains(ftd.Features, feature)
> ```

I suggest to refactor logic in a more structured way

on the first step handle burning feature logic since it is differnt from others and then everything else. I also suggest to change this to 2 funcs

```
func checkFeatureAllowed {
  if !isFeatureAllowed {
    return error
  }
}

func isFeatureAllowed() {
  if feature == types.TokenFeature_burn {
    return ftd.IsFeatureEnabled(...) || ftd.Issuer == addr.String
  }

  return ftd.IsFeatureEnabled(...) && ftd.Issuer == addr.String
}
```
we can also make these 2 methods methods of ftd not keeper

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 665 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL1tcRM42sUAJHXBYaZ:-NL4p1OqB_egPCXNxgIA:bn0oa2m) ([raw file](https://github.com/coreumfoundation/coreum/blob/e8f6626e5a864627bd4c00e237201fcefed12a1b/integration-tests/modules/assetft_test.go#L665)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I thought a bit more about this error type & it probably makes sense to keep it
Unauthorized is different from FeatureDisabled & it is more specific
</blockquote></details>

Actually I don't see a big difference.
___
*[`x/asset/ft/keeper/freeze.go` line 91 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL1zROY3XaBYw7WqWXR:-NL4x38s3rNCw7dbzp54:bksqkhe) ([raw file](https://github.com/coreumfoundation/coreum/blob/e8f6626e5a864627bd4c00e237201fcefed12a1b/x/asset/ft/keeper/freeze.go#L91)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would move this to aseparate if
it sounds more natural 
```
// on the 1st place to explicitly show that issuer don't care about freezing
if ft.Issuer == addr.String {
  return nil
}

if !featureEnabled {
  return nil 
}


```
</blockquote></details>

But in that case the logic will be different from what we have. In you snippet you say that issuer can't have the frozen balance. If you are good with that I'll add it that way.



_Code quote:_
```Go
 k.isGloballyFrozen(ctx, ft.D
```
___
*[`x/asset/ft/keeper/keeper.go` line 211 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL1w82H3su25iAM_O3d:-NL50KGqARtjz8-eYMb4:b-wec5t3) ([raw file](https://github.com/coreumfoundation/coreum/blob/e8f6626e5a864627bd4c00e237201fcefed12a1b/x/asset/ft/keeper/keeper.go#L211)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I suggest to refactor logic in a more structured way

on the first step handle burning feature logic since it is differnt from others and then everything else. I also suggest to change this to 2 funcs

```
func checkFeatureAllowed {
  if !isFeatureAllowed {
    return error
  }
}

func isFeatureAllowed() {
  if feature == types.TokenFeature_burn {
    return ftd.IsFeatureEnabled(...) || ftd.Issuer == addr.String
  }

  return ftd.IsFeatureEnabled(...) && ftd.Issuer == addr.String
}
```
we can also make these 2 methods methods of ftd not keeper

</blockquote></details>

Refactored and moved as methods to the `Definition`.



_Code quote:_
```Go
checkFeatureAllowed(addr 
```

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/assetft_test.go` line 665 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL1tcRM42sUAJHXBYaZ:-NL62M_L0JQYnjtwg6Nu:bhr3us4) ([raw file](https://github.com/coreumfoundation/coreum/blob/e8f6626e5a864627bd4c00e237201fcefed12a1b/integration-tests/modules/assetft_test.go#L665)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually I don't see a big difference.
</blockquote></details>

lets keep featureDisabled


___
*[`x/asset/ft/keeper/freeze.go` line 91 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL1zROY3XaBYw7WqWXR:-NL62iRT9gtbdzFlDPpQ:b-ne89pl) ([raw file](https://github.com/coreumfoundation/coreum/blob/e8f6626e5a864627bd4c00e237201fcefed12a1b/x/asset/ft/keeper/freeze.go#L91)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But in that case the logic will be different from what we have. In you snippet you say that issuer can't have the frozen balance. If you are good with that I'll add it that way.
</blockquote></details>

I see
yes our idea was that issuer can't have frozen balance. 
Can you pls quickly check that it is implemented in this way & we have test for this ? 
it should not be allowed to issue MsgFreeze against issuer because it doesn't make sense. 
So IMO issuer check could be moved to top
___
*[`x/asset/ft/keeper/keeper.go` line 211 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL1w82H3su25iAM_O3d:-NL63dY53dXRoWqMjrEV:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/e8f6626e5a864627bd4c00e237201fcefed12a1b/x/asset/ft/keeper/keeper.go#L211)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Refactored and moved as methods to the `Definition`.
</blockquote></details>

ok
___
*[`x/asset/ft/types/token.go` line 121 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL67SDlBEYZrg_oOfbm:-NL67SDlBEYZrg_oOfbn:bgv7a4l) ([raw file](https://github.com/coreumfoundation/coreum/blob/280ab29a8bc9ef96cddb317ab7761a8eb4e28568/x/asset/ft/types/token.go#L121)):*
> ```Go
> 	featureEnabled := ftd.IsFeatureEnabled(feature)
> 	// issuer can use any enabled feature and burning even if it is disabled
> 	if ftd.IsIssuer(addr) {
> ```

minor:

do you find this version with if & return merged confusing ?
```
return featureEnabled || feature == TokenFeature_burn
```
instead of
```
		if featureEnabled || feature == TokenFeature_burn {
			return true
		}
```

Because as for me it looks better but I don't insist much

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 665 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL1tcRM42sUAJHXBYaZ:-NL6DL8c-DSb-8Z3felL:bg3k077) ([raw file](https://github.com/coreumfoundation/coreum/blob/e8f6626e5a864627bd4c00e237201fcefed12a1b/integration-tests/modules/assetft_test.go#L665)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets keep featureDisabled



</blockquote></details>

The feature can be disabled, but the issue still can use it right? That's why that error is a bit redundant as for me.
___
*[`x/asset/ft/keeper/freeze.go` line 91 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL1zROY3XaBYw7WqWXR:-NL6DclLANzNFN5NFYX3:b-5y8kuy) ([raw file](https://github.com/coreumfoundation/coreum/blob/e8f6626e5a864627bd4c00e237201fcefed12a1b/x/asset/ft/keeper/freeze.go#L91)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I see
yes our idea was that issuer can't have frozen balance. 
Can you pls quickly check that it is implemented in this way & we have test for this ? 
it should not be allowed to issue MsgFreeze against issuer because it doesn't make sense. 
So IMO issuer check could be moved to top
</blockquote></details>

Actually we have a proposition from Wojtek to test that it's prohibited, so we can add your change here as well.
___
*[`x/asset/ft/types/token.go` line 121 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL67SDlBEYZrg_oOfbm:-NL6EORB3GIEdxcunMQZ:by6rfuk) ([raw file](https://github.com/coreumfoundation/coreum/blob/280ab29a8bc9ef96cddb317ab7761a8eb4e28568/x/asset/ft/types/token.go#L121)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:

do you find this version with if & return merged confusing ?
```
return featureEnabled || feature == TokenFeature_burn
```
instead of
```
		if featureEnabled || feature == TokenFeature_burn {
			return true
		}
```

Because as for me it looks better but I don't insist much
</blockquote></details>

Good idea, updated.

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: 14 of 15 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/asset/ft/types/errors.go` line 13 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL6QPc_0FbHniKXB-Q9:-NL6QPc_0FbHniKXB-QA:bv317j0) ([raw file](https://github.com/coreumfoundation/coreum/blob/2feafc03a8767fbbbb155680592fd7564faac5c8/x/asset/ft/types/errors.go#L13)):*
> ```Go
> 	ErrFTNotFound = sdkerrors.Register(ModuleName, 2, "fungible token not found")
> 	// ErrFeatureNotActive is returned when an operation is performed on a token which is missing a required feature
> 	ErrFeatureNotActive = sdkerrors.Register(ModuleName, 3, "token feature is not active")
> ```

Revert & name it `FeatureDisabled` ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: 7 of 17 files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/types/errors.go` line 13 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL6QPc_0FbHniKXB-Q9:-NLKQEeu0aQbUAVNi51P:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2feafc03a8767fbbbb155680592fd7564faac5c8/x/asset/ft/types/errors.go#L13)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Revert & name it `FeatureDisabled` ?
</blockquote></details>

Done.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/assetft_test.go` line 665 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL1tcRM42sUAJHXBYaZ:-NLL8f2R9EQEcc7nMcLw:bdqf1yj) ([raw file](https://github.com/coreumfoundation/coreum/blob/e8f6626e5a864627bd4c00e237201fcefed12a1b/integration-tests/modules/assetft_test.go#L665)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The feature can be disabled, but the issue still can use it right? That's why that error is a bit redundant as for me.
</blockquote></details>

I think we should interpret burning as `public burning` so issuer can always burn but if `public burning` feature is enabled then anyone could burn

IDK if we should rename it somehow to clarify to users or just adding it into doc should be enough 
WDYT ?
___
*[`x/asset/ft/keeper/freeze.go` line 91 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL1zROY3XaBYw7WqWXR:-NLLgbG1-dK-mO0uIq8g:b-u1q7u5) ([raw file](https://github.com/coreumfoundation/coreum/blob/e8f6626e5a864627bd4c00e237201fcefed12a1b/x/asset/ft/keeper/freeze.go#L91)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually we have a proposition from Wojtek to test that it's prohibited, so we can add your change here as well.
</blockquote></details>

ok moved thre
___
*[`x/asset/ft/types/errors.go` line 15 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NLLhCmM3cqR6LPpOZz3:-NLLhCmM3cqR6LPpOZz4:b1gxqzr) ([raw file](https://github.com/coreumfoundation/coreum/blob/dabdca97eaa456951a436e5279b8ec160da6b772/x/asset/ft/types/errors.go#L15)):*
> ```Go
> 	ErrInvalidKey = sdkerrors.Register(ModuleName, 3, "invalid key")
> 	// ErrFeatureDisabled is returned when used disabled feature.
> 	ErrFeatureDisabled = sdkerrors.Register(ModuleName, 4, "invalid input")
> ```

fix error name here also `"invalid input"`

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 665 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NL1tcRM42sUAJHXBYaZ:-NLLi-qT27AiqJhlCr24:b-8kcxi7) ([raw file](https://github.com/coreumfoundation/coreum/blob/e8f6626e5a864627bd4c00e237201fcefed12a1b/integration-tests/modules/assetft_test.go#L665)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think we should interpret burning as `public burning` so issuer can always burn but if `public burning` feature is enabled then anyone could burn

IDK if we should rename it somehow to clarify to users or just adding it into doc should be enough 
WDYT ?
</blockquote></details>

Actually any if we don't have private burning, jet burning is enough.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @wojtek-coreum)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 12 files at r1, 3 of 5 files at r2, 9 of 10 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`x/asset/ft/types/token.go` line 112 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NLMOfrH8Muo3RT2Cilr:-NLMOfrH8Muo3RT2Cils:bt1q0kr) ([raw file](https://github.com/coreumfoundation/coreum/blob/7e0bec4b44b3645302f56114b7b5f1900d6fbb50/x/asset/ft/types/token.go#L112)):*
> ```Go
> 	}
> 
> 	if !ftd.IsFeatureEnabled(feature) {
> ```

we can remove this function `IsFeatureAllowed` completely, and the next if funciton with this

if !ftd.IsFeatureEnabled(feature)  => if !ftd.IsFeatureEnabled(feature)  && ftd.IsIssuer(addr) 

This way we will have one less function. and more readable code IMO.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/asset/ft/types/token.go` line 112 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NLMOfrH8Muo3RT2Cilr:-NLPNEdcDP0zNwMvDh6X:b-x41xlk) ([raw file](https://github.com/coreumfoundation/coreum/blob/7e0bec4b44b3645302f56114b7b5f1900d6fbb50/x/asset/ft/types/token.go#L112)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we can remove this function `IsFeatureAllowed` completely, and the next if funciton with this

if !ftd.IsFeatureEnabled(feature)  => if !ftd.IsFeatureEnabled(feature)  && ftd.IsIssuer(addr) 

This way we will have one less function. and more readable code IMO.
</blockquote></details>

We shouldn't remove it. For the FT it used directly. for the NFT we will use it as well once we add the integration with the `BeforeTransfer`.



_Code quote:_
```Go
IsFeatureEnabled
```

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`x/asset/ft/types/token.go` line 112 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NLMOfrH8Muo3RT2Cilr:-NLPWblu5kh1k1G6Szez:b34evu) ([raw file](https://github.com/coreumfoundation/coreum/blob/7e0bec4b44b3645302f56114b7b5f1900d6fbb50/x/asset/ft/types/token.go#L112)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We shouldn't remove it. For the FT it used directly. for the NFT we will use it as well once we add the integration with the `BeforeTransfer`.
</blockquote></details>

These methods are defined on the FungibleTokenDefinition types, I don't think we can or should reuse them for NFT.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/types/token.go` line 112 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NLMOfrH8Muo3RT2Cilr:-NLPk4ga-maufuI7DDHf:b-a3dphw) ([raw file](https://github.com/coreumfoundation/coreum/blob/7e0bec4b44b3645302f56114b7b5f1900d6fbb50/x/asset/ft/types/token.go#L112)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

These methods are defined on the FungibleTokenDefinition types, I don't think we can or should reuse them for NFT. 
</blockquote></details>

Oh, this fuction was requested by @ysv

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/types/token.go` line 112 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NLMOfrH8Muo3RT2Cilr:-NLQaZOc3ATOgFrJsXNz:bcwfh8o) ([raw file](https://github.com/coreumfoundation/coreum/blob/7e0bec4b44b3645302f56114b7b5f1900d6fbb50/x/asset/ft/types/token.go#L112)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Oh, this fuction was requested by @ysv 
</blockquote></details>

The `IsFeatureAllowed` as method makes the code cleaner.

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

___
*[`x/asset/ft/types/token.go` line 112 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/332#-NLMOfrH8Muo3RT2Cilr:-NLQg7CS6EtwW7So0-2i:bgsx6ez) ([raw file](https://github.com/coreumfoundation/coreum/blob/7e0bec4b44b3645302f56114b7b5f1900d6fbb50/x/asset/ft/types/token.go#L112)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The `IsFeatureAllowed` as method makes the code cleaner.
</blockquote></details>

I will resolve it here, but I think it is actually less clear now.

**Review by ysv — APPROVED** [review]
> Reviewed 13 of 14 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 13 of 14 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
