### PR TITLE
[WIP] Order matching

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

Still working on unit tests which might reveal bugs.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/795)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 8 of 15 files at r1, 1 of 8 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/795)* status: 21 of 30 files reviewed, 21 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCwrwtCS7TW7VDbslt:-NvCwrwtCS7TW7VDbslu:bmtzfup) (no related file):*
only partially reviewed
will continue review later

___
___
*[`integration-tests/modules/dex_test.go` line 84 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCdzlHCoCj9G5mTzKi:-NvCdzlHCoCj9G5mTzKj:bhw40cb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/integration-tests/modules/dex_test.go#L84)):*
> ```Go
> 	denom1 := assetfttypes.BuildDenom(msgIssue1.Subunit, issuer1)
> 	denom2 := assetfttypes.BuildDenom(msgIssue2.Subunit, issuer2)
> ```

nit: the code up to here is likely to be repeated a lot in dex tests so I suggest to move it to helper func 
Now or later
___
*[`integration-tests/modules/dex_test.go` line 86 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCe8f64K14tsGOSK58:-NvCe8f64K14tsGOSK59:b-5wq3x1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/integration-tests/modules/dex_test.go#L86)):*
> ```Go
> 
> 	msgOrder1 := &types.MsgCreateLimitOrder{
> 		Sender:    issuer1.String(),
> ```

more real use-case is to create orders from non-issuer accounts
___
*[`proto/coreum/dex/v1/event.proto` line 15 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCePP5A_SqBFG6R0e9:-NvCePP5A_SqBFG6R0eA:b-xej4mu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/proto/coreum/dex/v1/event.proto#L15)):*
> ```proto
>   string subunit = 4;
>   uint32 precision = 5;
>   string initial_amount = 6 [
> ```

I would name it amount
Same as in `message OrderLimit `
___
*[`proto/coreum/dex/v1/event.proto` line 18 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCeUZ4BYp_b3eTxyHm:-NvCeUZ4BYp_b3eTxyHn:b-yg0dri) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/proto/coreum/dex/v1/event.proto#L18)):*
> ```proto
>     (gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int",
>     (gogoproto.nullable) = false
>   ];
> ```

why don't we include price in event ?
___
*[`proto/coreum/dex/v1/tx.proto` line 17 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCj4pj-PmA7GBy8SHH:-NvCj4pj-PmA7GBy8SHI:b4hlk7c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/proto/coreum/dex/v1/tx.proto#L17)):*
> ```proto
> 
> // MsgIssue defines message to issue new fungible token.
> message MsgCreateLimitOrder {
> ```

I suggest to name it just Order and remove limit everywhere.

1. IMO we should stick to single type everywhere because they are not that different. And even if we implement market orders in the future we can just make 1 field optional.

2. IMO we can delegate market orders to UI. I checked how other DEXes do and for market orders they just do estimation on UI and create limit with e.g 10% overhead. This is also better for users
___
*[`proto/coreum/dex/v1/tx.proto` line 20 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCj5pn-SWBnLKpQ5th:-NvCj5pn-SWBnLKpQ5ti:b-foav3x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/proto/coreum/dex/v1/tx.proto#L20)):*
> ```proto
>   string sender = 1;
>   cosmos.base.v1beta1.Coin amount = 2 [(gogoproto.nullable) = false];
>   cosmos.base.v1beta1.DecCoin sell_price = 3 [(gogoproto.nullable) = false];
> ```

client should be able to provide `order id` or determine it before creation. 
Will be addressed here on in the next PR ?
___
*[`x/dex/keeper/keeper.go` line 54 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCjmLdBHRksfJVlXrX:-NvCjmLdBHRksfJVlXrY:b-8on4aq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/keeper/keeper.go#L54)):*
> ```Go
> 
> 	tStore := ctx.TransientStore(k.transientStoreKey)
> 	tStore.Set(types.CreateOrderKey(k.nextOrderID(ctx)), orderBytes)
> ```

nit: these 2 lines could be merged

`ctx.TransientStore(k.transientStoreKey).Set(..`



_Code quote:_
```Go
	tStore := ctx.TransientStore(k.transientStoreKey)
	tStore.Set(types.CreateOrderKey(k.nextOrderID(ctx)), orderBytes)
```
___
*[`x/dex/keeper/keeper.go` line 100 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCvBS_DKwR5UnarVvD:-NvCvBS_DKwR5UnarVvE:b-sjc4vb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/keeper/keeper.go#L100)):*
> ```Go
> 
> 	store := ctx.KVStore(k.storeKey)
> 	iteratorA := prefix.NewStore(store,
> ```

So I guess the algorithm has changed since we have cross market matching ?

Because initially we were planning to load orderbooks into memory and then do matching

BTW Is cross-market matching implemented in this PR ?
___
*[`x/dex/keeper/keeper.go` line 130 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCw854DPYOlD5kX7Ra:-NvCw854DPYOlD5kX7Rb:b-sildk1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/keeper/keeper.go#L130)):*
> ```Go
> 			return err
> 		}
> 		if orderB == nil || orderA.Order.Price().GT(sdk.OneDec().Quo(orderB.Order.Price())) {
> ```

can we somehow avoid division. I'm not sure it is ok



_Code quote:_
```Go
orderA.Order.Price().GT(sdk.OneDec().Quo(orderB.Order.Price()))
```
___
*[`x/dex/keeper/keeper.go` line 151 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCw_GbCiUcA4S8dCLz:-NvCw_GbCiUcA4S8dCM-:bxxlycb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/keeper/keeper.go#L151)):*
> ```Go
> 		}
> 		if fullyMatched {
> 			if err := k.dropOrder(ctx, orderB); err != nil {
> ```

just `return k.dropOrder(ctx, orderB)`
___
*[`x/dex/keeper/keeper.go` line 350 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCkrZ1DDMbikxyn7K1:-NvCkrZ1DDMbikxyn7K2:b-ukhpto) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/keeper/keeper.go#L350)):*
> ```Go
> func (k Keeper) orderByID(ctx sdk.Context, orderID uint64) (*orderWrapper, error) {
> 	store := ctx.KVStore(k.storeKey)
> 	bz := store.Get(types.CreateOrderKey(orderID))
> ```

nit: these 2 lines could be merged



_Code quote:_
```Go
	store := ctx.KVStore(k.storeKey)
	bz := store.Get(types.CreateOrderKey(orderID))
```
___
*[`x/dex/keeper/keeper_test.go` line 18 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCphPrBYNodLFVcoEI:-NvCphPrBYNodLFVcoEJ:b1kogi6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/keeper/keeper_test.go#L18)):*
> ```Go
> )
> 
> func TestMatching(t *testing.T) {
> ```

these test is complicated to review IMO we should try to visualize it.
We were usually using excel table for this. Or maybe we can do it somehow in code
___
*[`x/dex/keeper/keeper_test.go` line 84 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCrDZf04ZRCaIcSRKP:-NvCrDZf04ZRCaIcSRKQ:b-95efg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/keeper/keeper_test.go#L84)):*
> ```Go
> 	}{
> 		{
> 			Name: "single_order",
> ```

if we test matching here it is also reasonable to test output trades
___
*[`x/dex/keeper/keeper_test.go` line 261 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCmJN232ib4rDDCtss:-NvCmJN232ib4rDDCtst:bbj1k0v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/keeper/keeper_test.go#L261)):*
> ```Go
> 		},
> 		{
> 			Name: "better_price_is_used_1",
> ```

WDYM better_price ?
In this case price of first order coming to orderbook should be used (if they match)
___
*[`x/dex/keeper/keeper_test.go` line 285 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCmjJk18y4hmzlv5KT:-NvCmjJk18y4hmzlv5KU:b-q3vcco) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/keeper/keeper_test.go#L285)):*
> ```Go
> 		},
> 		{
> 			Name: "better_price_is_used_2",
> ```

if I understand this test case correctly:

order1: sell 25 BBB for 0.5 AAA per BBB
order2: sell 10 AAA for    1 BBB per AAA 

matching:
1. order1 comes to orderbook => no order on opposite side detected => just store order1
2. order2 comes to  to orderbook => oposite order exist => compare if order prices match:

order2 is ready to pay up to 1 AAA per BBB and order1 sells each BBB for 0.5 AAA so: 
1 AAA per BBB >= 0.5 AAA BBB.
**And you much these orders using price which exists in orderbook so 1st order has priority.**
So order1 gets 10 AAA & spends 5 BBB and order2 spends 10 AAA & gets 5 BBB

Resulting orderbook:
order1: sell 20 BBB for 0.5 AAA per BBB


### So I think the algorithm is incorrect
___
*[`x/dex/keeper/keeper_test.go` line 285 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCud-vEwiHHkkloMYt:-NvCud-vEwiHHkkloMYu:bwcgjs2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/keeper/keeper_test.go#L285)):*
> ```Go
> 		},
> 		{
> 			Name: "better_price_is_used_2",
> ```

not reviewing other test-cases since I think the algorithm is wrong
___
*[`x/dex/types/keys.go` line 54 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCs8ID8VSG5_2PdtN4:-NvCs8ID8VSG5_2PdtN5:bdqcm4i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/types/keys.go#L54)):*
> ```Go
> 
> // CreateOrderQueueKey creates the key for an order inside transient queue.
> func CreateOrderQueueKey(denomOfferedSeq, denomRequestedSeq, orderID uint64, price sdk.Dec) []byte {
> ```

pls explain this method and put better comment

Do you use key to order orders by price ?
IMO we need tast cases for it to make sure it works properly



_Code quote:_
```Go
CreateOrderQueueKey(
```
___
*[`x/dex/types/keys.go` line 90 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCt5af-2VOHdUNWYC8:-NvCt5af-2VOHdUNWYC9:b-m148th) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/types/keys.go#L90)):*
> ```Go
> 
> func priceToUint64s(price sdk.Dec) (uint64, uint64) {
> 	wholePart := price.TruncateInt()
> ```

nit: I prefer `intPart`.
It is also more logical since u use TruncateInt()

but ok with whole part also
___
*[`x/dex/types/keys.go` line 91 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCsllX34XixrUoMVRf:-NvCsllX34XixrUoMVRg:b3leprw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/types/keys.go#L91)):*
> ```Go
> func priceToUint64s(price sdk.Dec) (uint64, uint64) {
> 	wholePart := price.TruncateInt()
> 	decPart := price.Sub(wholePart.ToLegacyDec()).Mul(sdk.NewDecFromInt(sdk.NewIntFromUint64(1000000000000000000))).
> ```

this is usually called fractionalPart eg. fracPart



_Code quote:_
```Go
decPart
```
___
*[`x/dex/types/keys.go` line 91 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvCtQyn0k4k4VeGBazC:-NvCtQyn0k4k4VeGBazD:bd7k9ve) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/types/keys.go#L91)):*
> ```Go
> func priceToUint64s(price sdk.Dec) (uint64, uint64) {
> 	wholePart := price.TruncateInt()
> 	decPart := price.Sub(wholePart.ToLegacyDec()).Mul(sdk.NewDecFromInt(sdk.NewIntFromUint64(1000000000000000000))).
> ```

is it safe to split price like this ?
Does it cover all edge cases ? do we have tests & validations for this ?



_Code quote:_
```Go
decPart := price.Sub(wholePart.ToLegacyDec()).Mul(sdk.NewDecFromInt(sdk.NewIntFromUint64(1000000000000000000))).
```

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/795)* status: 21 of 30 files reviewed, 34 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`proto/coreum/dex/v1/orders.proto` line 13 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvDIOWP0hVtGAsGl9B8:-NvX3eEM2hqjm4JdIjPr:b-k0xf0p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/proto/coreum/dex/v1/orders.proto#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How about using ASK/BID terms for the orders?
WDYT @ysv @miladz68 ?
</blockquote></details>

Since we want to have cross-order matching we don't have ask/bid or buy/sell. Since buy on BTC/USD is sell on USD/BTC we decided to just specify what you sell and for how much
___
*[`proto/coreum/dex/v1/orders.proto` line 14 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvDGpNDDN9PHDEkrfID:-NvX3_DF5g9t3hNXk2ig:bkbe1ib) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/proto/coreum/dex/v1/orders.proto#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO it's better to separate the price and denom. Here you use them together, but the `price + denom` is not a `Coin`.

WDYT @ysv @miladz68 ?
</blockquote></details>

yes, makes sense 
___
*[`x/dex/keeper/keeper.go` line 61 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvDJRuf4vBuQy9uPm_r:-NvX3vKHAxzIiTfx3c4m:b-1l0otj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/keeper/keeper.go#L61)):*

This should definitely be addressed in one or another way.

> process in the next block the orders that we were not able to process

This is more reasonable. Rejecting doesn't make sense
___
*[`x/dex/keeper/keeper.go` line 135 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvDMXmO4_vYg5Yq5VUu:-NvX47aNDwC08d967z2T:b-oj75uf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/x/dex/keeper/keeper.go#L135)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's try not to use `Dec`, since it's legacy. We can discuss what to do with it, but in general, it would be nice to use Int as much as possible.  Also not sure about the `RoundInt`, the values should be without the reminders, so if there is a reminder it should lead to an error. 
@ysv @miladz68  Let's discuss.
</blockquote></details>

definitely. 
IMO math should be very strict, well tested and definitely not legacy

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/795)* status: 21 of 30 files reviewed, 34 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/dex/v1/orders.proto` line 13 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/795#-NvDIOWP0hVtGAsGl9B8:-NwF8J-VDYm2grblEVwx:b-4cbfz4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/320a63b8264d33f942223a34302f378bc46d1cf3/proto/coreum/dex/v1/orders.proto#L13)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Since we want to have cross-order matching we don't have ask/bid or buy/sell. Since buy on BTC/USD is sell on USD/BTC we decided to just specify what you sell and for how much
</blockquote></details>

buy/sell is OK as well.

**Review by ysv — COMMENTED** [review]
> Reviewed 2 of 15 files at r1, 6 of 8 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/795)* status: all files reviewed, 33 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

**Pull request closed without merging**
