### PR TITLE
Remove types/key.go and refactor accordingly

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/222)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/222)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/ci.yml` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/222#-NEAqgPzESlr8EOo5mvu:-NEAqgQ-4oKNb2sq4jUK:b-r0s0n6) ([raw file](https://github.com/coreumfoundation/coreum/blob/a6967f99e84ea247fc3ac027bd17bebddae55c5d/.github/workflows/ci.yml#L46)):*
> ```YAML
>       - name: Lint, run unit tests and build
>         run: crust build lint/coreum test/coreum images --log-format=yaml
> # FIXME(dhil) remove once we update the crust
> ```

why do you need to turn off tests?
___
*[`integration-tests/testing/helpers.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/222#-NEArfkC5qZGLERK0zZp:-NEArfkD9wf7F_Hs0JhO:bwn6n7j) ([raw file](https://github.com/coreumfoundation/coreum/blob/a6967f99e84ea247fc3ac027bd17bebddae55c5d/integration-tests/testing/helpers.go#L15)):*
> ```Go
> func RandomWallet() types.Wallet {
> 	privKey := cosmossecp256k1.GenPrivKey()
> 	return types.Wallet{Name: sdk.AccAddress(privKey.PubKey().Bytes()).String(), Key: *privKey}
> ```

PubKey().Bytes() -> PubKey().Address()
___
*[`pkg/staking/staking.go` line 19 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/222#-NEAt3eN4Eh2aP0mM6f9:-NEAt3eN4Eh2aP0mM6fA:b9b4vux) ([raw file](https://github.com/coreumfoundation/coreum/blob/a6967f99e84ea247fc3ac027bd17bebddae55c5d/pkg/staking/staking.go#L19)):*
> ```Go
> func PrepareTxStakingCreateValidator(
> 	clientCtx tx.ClientContext,
> 	validatorPublicKey ed25519.PublicKey,
> ```

callers pass secp public key now, but this function still takes ed25519
___
*[`pkg/types/types.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/222#-NEAtNv65eYb5ErnVgS7:-NEAtNv7EB8DBhfebM_U:blv2f6t) ([raw file](https://github.com/coreumfoundation/coreum/blob/a6967f99e84ea247fc3ac027bd17bebddae55c5d/pkg/types/types.go#L26)):*
> ```Go
> // String returns string representation of the wallet
> func (w Wallet) String() string {
> 	return w.Name + "@" + sdk.AccAddress(w.Key.PubKey().Bytes()).String()
> ```

PubKey.Bytes() -> PubKey().Address()

and it might be simplified to w.Address().String()

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/222)* status: 8 of 12 files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/222#-NEAqgPzESlr8EOo5mvu:-NEAxqAN5chvfk2Hw2gz:b-rdkncs) ([raw file](https://github.com/coreumfoundation/coreum/blob/a6967f99e84ea247fc3ac027bd17bebddae55c5d/.github/workflows/ci.yml#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why do you need to turn off tests?
</blockquote></details>

The crust uses the coreum legacy types to spin up the nodes, I've remove those types so it won't work until we merge the coreum and update crust. The crust PR is raised as well.
___
*[`integration-tests/testing/helpers.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/222#-NEArfkC5qZGLERK0zZp:-NEAy_wx8QaCRl48rO3V:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a6967f99e84ea247fc3ac027bd17bebddae55c5d/integration-tests/testing/helpers.go#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

PubKey().Bytes() -> PubKey().Address()
</blockquote></details>

Done.



_Code quote:_
```Go
sdk.AccAddress(privKey.Pu
```
___
*[`pkg/staking/staking.go` line 19 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/222#-NEAt3eN4Eh2aP0mM6f9:-NEAz7Tb2WPF9SES1i0K:b-rvqg5s) ([raw file](https://github.com/coreumfoundation/coreum/blob/a6967f99e84ea247fc3ac027bd17bebddae55c5d/pkg/staking/staking.go#L19)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

callers pass secp public key now, but this function still takes ed25519
</blockquote></details>

It was written that way before,  so I just resused the prev logic if the test.
Now I've refactored it. 
Also found that "github.com/cosmos/cosmos-sdk/crypto/keys/ed25519" PrivKey is deprecated, and proposed to use "crypto/ed25519" so I've refactored where it was possible to use those imports. 
___
*[`pkg/types/types.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/222#-NEAtNv65eYb5ErnVgS7:-NEAz6pD9tHiQKpXnjn_:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a6967f99e84ea247fc3ac027bd17bebddae55c5d/pkg/types/types.go#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

PubKey.Bytes() -> PubKey().Address()

and it might be simplified to w.Address().String()
</blockquote></details>

Done.



_Code quote:_
```Go
w.Name + "@" + sdk.AccAddress(w.Key.PubKey().Bytes()).String()
```

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/222)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/222)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/222#-NEAk8YG-jkbg6Zo7uHw:-NEAk8YG-jkbg6Zo7uHx:b-5f5yys) (no related file):*
have you tested that integration tests are running successfully in your local machine ?

___
___
*[`pkg/config/network.go` line 288 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/222#-NEAjSTHBG35rx0-KrY2:-NEAjSTHBG35rx0-KrY3:b-z9uxkw) ([raw file](https://github.com/coreumfoundation/coreum/blob/a6967f99e84ea247fc3ac027bd17bebddae55c5d/pkg/config/network.go#L288)):*
> ```Go
> }
> 
> // FIXME REFACTOR THAT FUNC
> ```

can you put a better description to what needs to be refactored ?

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/222)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by wojtek-coreum — APPROVED** [review]

**Pull request merged**
