### PR TITLE
Add asset ft issuance operation simulation.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Add asset ft issuance operation simulation.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/748)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/748)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`app/simulation_test.go` line 96 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlcHhNR33Rtcwg4V0Qh:-NlcHhNR33Rtcwg4V0Qi:basd64e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/app/simulation_test.go#L96)):*
> ```Go
> // fauxMerkleModeOpt returns a BaseApp option to use a dbStoreAdapter instead of
> // an IAVLStore for faster simulation speed.
> func fauxMerkleModeOpt(bapp *baseapp.BaseApp) {
> ```

minor: Maybe just define this function in the line where it is used
___
*[`x/asset/ft/simulation/operations.go` line 71 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlcIGcn77h0rU1UH0ox:-NlcIGcn77h0rU1UH0oy:b-sfra5u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L71)):*
> ```Go
> }
> 
> func (op *OperationFactory) simulateMsgIssue() simtypes.Operation {
> ```

There are no arguments here so you may remove the external function
___
*[`x/asset/ft/simulation/operations.go` line 125 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlcJ5zF2E5x8LI9razv:-NlcJ5zF2E5x8LI9razw:b-ieuyas) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L125)):*
> ```Go
> }
> 
> func (op *OperationFactory) sendMsg(
> ```

it seems to be a common function to all the message types, no?
___
*[`x/deterministicgas/types/gas.go` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlcJGBo0b-29nWzgnKw:-NlcJGBo0b-29nWzgnKx:by3h9ko) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/deterministicgas/types/gas.go#L18)):*
> ```Go
> 
> const (
> 	fuseGasMultiplier    = 1000
> ```

I know you explained this, but I don't remember. Why is it needed?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/748)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/simulation_test.go` line 96 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlcHhNR33Rtcwg4V0Qh:-NlgYyLQBYSH2ucbf9aV:b-1zwgbi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/app/simulation_test.go#L96)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

minor: Maybe just define this function in the line where it is used
</blockquote></details>

We will reuse it later since we will have different test types.
___
*[`x/asset/ft/simulation/operations.go` line 71 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlcIGcn77h0rU1UH0ox:-Nlg_gWM3jTRmelROLhb:bbiro5r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L71)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

There are no arguments here so you may remove the external function
</blockquote></details>

Didn't get that comment
___
*[`x/asset/ft/simulation/operations.go` line 125 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlcJ5zF2E5x8LI9razv:-Nlg_kBS6kK6TcSt8tsA:bj283if) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L125)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

it seems to be a common function to all the message types, no?
</blockquote></details>

For now we don't use it anywther else. So I would keep it here until we have different use case.
___
*[`x/deterministicgas/types/gas.go` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlcJGBo0b-29nWzgnKw:-Nlg_t9D6yFaUB_vlzyS:b3aov8s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/deterministicgas/types/gas.go#L18)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I know you explained this, but I don't remember. Why is it needed?
</blockquote></details>

The simulation fails since the `10` multiplier is not enough for the withdrawal of the validator commission. We have a task to fix it either by updating the simulation or by updating the withdrawal of the validator commission.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/748)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/ft/simulation/operations.go` line 71 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlcIGcn77h0rU1UH0ox:-NlhEHrM4kDz8dbjoB3E:b-xfbtq7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L71)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Didn't get that comment
</blockquote></details>

```go
func simulateMsgIssue(
		r *rand.Rand, app *baseapp.BaseApp, ctx sdk.Context,
		accs []simtypes.Account, chainID string,
	) (simtypes.OperationMsg, []simtypes.FutureOperation, error) {
		senderAcc, _ := simtypes.RandomAcc(r, accs)
		msg, skip := op.randomIssueMsg(ctx, r, senderAcc.Address)
		if skip {
			return simtypes.NoOpMsg(types.ModuleName, TypeMsgIssue, "skip issue"), nil, nil
		}

		err := op.sendMsg(ctx, r, chainID, []cryptotypes.PrivKey{senderAcc.PrivKey}, app, senderAcc.Address, msg)
		if err != nil {
			return simtypes.NoOpMsg(types.ModuleName, msg.Type(), "invalid issuance"), nil, err
		}

		return simtypes.NewOperationMsg(msg, false, "", nil), nil, nil
	}
```

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/748)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`app/app.go` line 907 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhB_a87ZhdT2Ed4F1t:-NlhB_a87ZhdT2Ed4F1u:b-vjurmi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/app/app.go#L907)):*
> ```Go
> 
> 	// exclude the nft simulation since it is incompatible with the asset nft
> 	simModules := excludeModules(app.ModuleManager.Modules, []string{nft.ModuleName})
> ```

do they mint NFT with invalid IDs for assetNFT ?
I'm wondering how they mint them if there is no such msg in x/nft from cosmos ?
___
*[`app/simulation_test.go` line 30 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhC0dD6y7yIuInEp9W:-NlhC0dD6y7yIuInEp9X:b2baksb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/app/simulation_test.go#L30)):*
> ```Go
> //
> //	`go test ./app -run TestFullAppSimulation -v -Enabled=true \
> //		-Verbose=true -NumBlocks=100 -BlockSize=200 -Commit=true -Period=5`.
> ```

`-BlockSize=200` is it a number of txs ?

-Commit=true - what is the meaning of this ?
___
*[`x/asset/ft/simulation/operations.go` line 71 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlcIGcn77h0rU1UH0ox:-NlhEVpM2Al_CljOv726:bn1a6nd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L71)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

```go
func simulateMsgIssue(
		r *rand.Rand, app *baseapp.BaseApp, ctx sdk.Context,
		accs []simtypes.Account, chainID string,
	) (simtypes.OperationMsg, []simtypes.FutureOperation, error) {
		senderAcc, _ := simtypes.RandomAcc(r, accs)
		msg, skip := op.randomIssueMsg(ctx, r, senderAcc.Address)
		if skip {
			return simtypes.NoOpMsg(types.ModuleName, TypeMsgIssue, "skip issue"), nil, nil
		}

		err := op.sendMsg(ctx, r, chainID, []cryptotypes.PrivKey{senderAcc.PrivKey}, app, senderAcc.Address, msg)
		if err != nil {
			return simtypes.NoOpMsg(types.ModuleName, msg.Type(), "invalid issuance"), nil, err
		}

		return simtypes.NewOperationMsg(msg, false, "", nil), nil, nil
	}
```
</blockquote></details>

agree with Wojtek
___
*[`x/asset/ft/simulation/operations.go` line 114 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhGOE64adkXpi8ZpSG:-NlhGOE64adkXpi8ZpSH:b-a2n6ky) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L114)):*
> ```Go
> 		// and the fee_collector has the asset_ft_tokens with the SendCommissionRate and BurnRate
> 		BurnRate: sdkmath.LegacyNewDec(int64(simtypes.RandIntBetween(r, 1, 1000))).QuoInt64(10000),
> 		// SendCommissionRate: sdkmath.LegacyNewDec(int64(simtypes.RandIntBetween(r, 1, 1000))).QuoInt64(10000),
> ```

but I can see that you uncommented burn_rate. Can't we uncomment send commission now also ?
I think if influences the same way, isn't it ?
___
*[`x/asset/ft/simulation/operations.go` line 115 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhEgbe5YpJPtPor1mq:-NlhEgbe5YpJPtPor1mr:bv15ze5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L115)):*
> ```Go
> 		BurnRate: sdkmath.LegacyNewDec(int64(simtypes.RandIntBetween(r, 1, 1000))).QuoInt64(10000),
> 		// SendCommissionRate: sdkmath.LegacyNewDec(int64(simtypes.RandIntBetween(r, 1, 1000))).QuoInt64(10000),
> 		URI:     simtypes.RandStringOfLength(r, types.MaxURILength),
> ```

nit: can we generate string up to `types.MaxURILength` but not always  ?
___
*[`x/asset/ft/simulation/operations.go` line 129 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhG2boDQwekBv2hFDx:-NlhG2bp7Eh-IQUZWtQD:bx45uf0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L129)):*
> ```Go
> 	r *rand.Rand,
> 	chainID string,
> 	privkeys []cryptotypes.PrivKey,
> ```

nit: privKeys ?
___
*[`x/deterministicgas/types/gas.go` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhG9JO7tof1kkigzhm:-NlhG9JO7tof1kkigzhn:b-lzfkar) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/deterministicgas/types/gas.go#L18)):*
> ```Go
> 
> const (
> 	fuseGasMultiplier    = 1000
> ```

leave todo here ?
I think we shouldn't go to prod with this value

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/748)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 907 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhB_a87ZhdT2Ed4F1t:-NlhULoZ5jucyKjMoQ-S:blomv8d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/app/app.go#L907)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do they mint NFT with invalid IDs for assetNFT ?
I'm wondering how they mint them if there is no such msg in x/nft from cosmos ?
</blockquote></details>

They register them VIA keeper and genesis
___
*[`app/simulation_test.go` line 30 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhC0dD6y7yIuInEp9W:-NlhWA2ABm3wfsvGU9Rk:bb4uyyz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/app/simulation_test.go#L30)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`-BlockSize=200` is it a number of txs ?

-Commit=true - what is the meaning of this ?
</blockquote></details>

You can read about those flags here: https://github.com/cosmos/cosmos-sdk/blob/v0.47.6/x/simulation/client/cli/flags.go#L36
___
*[`x/asset/ft/simulation/operations.go` line 71 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlcIGcn77h0rU1UH0ox:-NlhWXlF-phZldB0Zvxx:b-8hqtmb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L71)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

agree with Wojtek
</blockquote></details>

Got you, updated.
___
*[`x/asset/ft/simulation/operations.go` line 114 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhGOE64adkXpi8ZpSG:-NlhWbbb0LIs9O6L30AZ:bpgm9nx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L114)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but I can see that you uncommented burn_rate. Can't we uncomment send commission now also ?
I think if influences the same way, isn't it ?
</blockquote></details>

By mistake. The simulation doesn't work with the commission.
___
*[`x/asset/ft/simulation/operations.go` line 115 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhEgbe5YpJPtPor1mq:-NlhWpUBEBWUT90mLwat:b-t7my8k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L115)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: can we generate string up to `types.MaxURILength` but not always  ?
</blockquote></details>

Didn't get the comment. What do you mean `but not always` ?
___
*[`x/asset/ft/simulation/operations.go` line 129 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhG2boDQwekBv2hFDx:-NlhWySa7xKj9yYafE7_:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L129)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: privKeys ?
</blockquote></details>

Done

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/748)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/748)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

___
*[`x/asset/ft/simulation/operations.go` line 115 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhEgbe5YpJPtPor1mq:-Nli7CSSCOk8qVr3E7aM:b-1ax2kh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L115)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Didn't get the comment. What do you mean `but not always` ?
</blockquote></details>

I mean generate string of size 1 up to `types.MaxURILength`

But not always generate string of `types.MaxURILength` size

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/748)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/748)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/simulation/operations.go` line 115 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhEgbe5YpJPtPor1mq:-NlwMnmB7EnvqyWtYk21:bu5o78d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L115)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I mean generate string of size 1 up to `types.MaxURILength`

But not always generate string of `types.MaxURILength` size
</blockquote></details>

But that's how it should be, isn't it?

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/748)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/748)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @miladz68)

___
*[`docs/static/openapi.json` line 4039 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlwnaUPDqkg_19LJ_Zw:-NlwnaUPDqkg_19LJ_Zx:b-6cgdw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/88cfb5793952300a933c2cdf251c6314a8b5afea/docs/static/openapi.json#L4039)):*
> ```JSON
>       }
>     },
>     "/cosmos/group/v1/group_info/{group_id}": {
> ```

is it added to this PR by mistake or it should be here ?

I'm ok but I think it is a mistake
___
*[`x/asset/ft/simulation/operations.go` line 115 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhEgbe5YpJPtPor1mq:-Nlwmybe0F8vz4s6QS8u:b9lkm8x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L115)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But that's how it should be, isn't it?
</blockquote></details>

`// RandStringOfLength generates a random string of a particular length`

It generates string of length `types.MaxURILength` each time

But it should be random length 

```
simtypes.RandStringOfLength(r, simtypes.RandIntBetween(r, 1, types.MaxURILength)))
```

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/748)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`docs/static/openapi.json` line 4039 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlwnaUPDqkg_19LJ_Zw:-Nlww62U3yLe2sZkpag_:b-x7w6km) ([raw file](https://github.com/CoreumFoundation/coreum/blob/88cfb5793952300a933c2cdf251c6314a8b5afea/docs/static/openapi.json#L4039)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it added to this PR by mistake or it should be here ?

I'm ok but I think it is a mistake
</blockquote></details>

The PR is already there, the squash should remove the duplicate part.
___
*[`x/asset/ft/simulation/operations.go` line 115 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhEgbe5YpJPtPor1mq:-NlwxNuPDV5Hzav-x-m7:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/asset/ft/simulation/operations.go#L115)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`// RandStringOfLength generates a random string of a particular length`

It generates string of length `types.MaxURILength` each time

But it should be random length 

```
simtypes.RandStringOfLength(r, simtypes.RandIntBetween(r, 1, types.MaxURILength)))
```
</blockquote></details>

Updated.
___
*[`x/deterministicgas/types/gas.go` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/748#-NlhG9JO7tof1kkigzhm:-NlwxRfv8aOdyZZKsFKG:bk56a6v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c73859ded3d138c3b25851169bfe0e6768ab1536/x/deterministicgas/types/gas.go#L18)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

leave todo here ?
I think we shouldn't go to prod with this value
</blockquote></details>

At least not for now :-)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/748)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/748)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
