### PR TITLE
Init wasm pinned codes

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/173)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/173)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/173#-NBpKQHh5inIgfhL6Euo:-NBpKQHh5inIgfhL6Eup:b-xduy48) (no related file):*
Could you please create a document in repo describing all the integrated features of WASM?

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/173)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/173#-NBpKQHh5inIgfhL6Euo:-NBpdGF52eNK9XW8IFpN:b-u45o5f) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you please create a document in repo describing all the integrated features of WASM?
</blockquote></details>

Hm, this is not a feature. This is config to make wasm work correctly in any state. So the only feature is end-to-end integrated wasm :-) We could copy the wasm doc, but that seems too much.

___

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/173)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/173#-NBpKQHh5inIgfhL6Euo:-NBprjCb8SR1OQuiOQVm:b-qkq3p2) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Hm, this is not a feature. This is config to make wasm work correctly in any state. So the only feature is end-to-end integrated wasm :-) We could copy the wasm doc, but that seems too much.
</blockquote></details>

In every place where you integrate(d) sth related to wasm, could you paste a link to appropriate part of the doc describing it?

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/173)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/173#-NBpKQHh5inIgfhL6Euo:-NBpxOaD-WiofGl4i53M:b-1polqw) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

In every place where you integrate(d) sth related to wasm, could you paste a link to appropriate part of the doc describing it?
</blockquote></details>

The wasm module contains just one doc, which described the conetps in general. This part of the code, touches just a small part of the the integration, so it makes no sense to add such references here. The same about the other places of the integration.
You can open for example "InitializePinnedCodes" and read the comment below it, it already descripts what it does. The same for other points of integration. In case it doesn't describe what it does I'm ok, to add such comment.

___

**Review by wojtek-coreum — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/173)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @ysv)

**Review by begmaroman — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/173)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/173)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
