### PR TITLE
Add test to verify testnet genesis hash.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/359)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/359)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/network_test.go` line 217 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/359#-NMXxC379kS2QuyGZLnj:-NMXxC379kS2QuyGZLnk:b-qgl9rh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/92232cf07c65887bf265fabb34d048edae9ca743/pkg/config/network_test.go#L217)):*
> ```Go
> func TestGenesisHash(t *testing.T) {
> 	type args struct {
> 		chainID constant.ChainID
> ```

just move this variable into the tests struct.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/359)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/network_test.go` line 217 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/359#-NMXxC379kS2QuyGZLnj:-NMY2zNH6EdOGv6L24pD:bh5rzk7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/92232cf07c65887bf265fabb34d048edae9ca743/pkg/config/network_test.go#L217)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's prepared for the mainnet, once it's done we will just extend that test.
</blockquote></details>

you don't need this extra type even for mainnet. just put chainID directly there instead of wrapping it in `args` struct.

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/359)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/359)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/359)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

___
*[`pkg/config/network_test.go` line 224 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/359#-NMZV-Nt2gyKAIE8FuNb:-NMZV-Nt2gyKAIE8FuNc:bvwiviu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9cc1717717c5ed931a3e07e9554a6bb1d4b3628f/pkg/config/network_test.go#L224)):*
> ```Go
> 			name:     "testnet",
> 			chainID:  constant.ChainIDTest,
> 			wantHash: "12273f3e0bc97e848cccdc67225a3d7c54c42243d6ec7f01a7bcfc4ede63cacd",
> ```

minor:
maybe it makes sense to add command to generate this hash as comment
but it is so simple so I'm not sure we need it

also checked on my machine and hash is the same

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/359)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

___
*[`pkg/config/network_test.go` line 224 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/359#-NMZV-Nt2gyKAIE8FuNb:-NMca4FPE7WF7dBLPoP2:b-k19i1w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9cc1717717c5ed931a3e07e9554a6bb1d4b3628f/pkg/config/network_test.go#L224)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The test itself, is that command :-)
</blockquote></details>

true )

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/359)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

___
*[`pkg/config/network_test.go` line 276 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/359#-NMd1Pgd1HjP1-7LZU4q:-NMd1Pgd1HjP1-7LZU4r:bw6c0c8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f0e739a602c588f732b2e6a22c33ad0b90f95091/pkg/config/network_test.go#L276)):*
> ```Go
> 			err = json.Unmarshal(bankGenesis, &bankGenesisState)
> 			require.NoError(t, err)
> 			require.Equal(t, tt.wantSupply.Amount.String(), bankGenesisState.Supply.AmountOf(tt.wantSupply.Denom).String())
> ```

what about verifying that the sum of account balances in genesis is equal to the total supply?

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/359)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

___
*[`pkg/config/network_test.go` line 276 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/359#-NMd1Pgd1HjP1-7LZU4q:-NMd2fX_BSXjy_LXix1h:buaufn1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f0e739a602c588f732b2e6a22c33ad0b90f95091/pkg/config/network_test.go#L276)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This validation is included in the genesis validation of the bank module if the supply isn't zero.
</blockquote></details>

But it is done only when blockchain is started. On the other hand we validate hash so it guarantees already that genesis is not different from what we run in production

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/359)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
