### PR TITLE
Add comment about `crisis` to deterministic gas

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/286)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/286)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/286)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/286)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/286)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/286)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by ysv — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/286#-:-NIqwWoW-HhBYpdpDmP6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
