### PR TITLE
Upgrade Cosmos SDK version to v0.46.0

### PR DESCRIPTION
**Pull request by dzmitryhil**
* update the cosmos-sdk dependency to v0.46.0 and all related dependencies to be compatible with it
* updated go version to 1.19
* update IBC to v5
* remove monitoringp module
* update the basic ante handler behaviour to follow the updated SDK's
* remove ignite dependencies
* remove legacy dependencies
* update the integration tests corresponding to the sdk updates
* update the DeterministicGasConfig to 140000 since the updated handlers require more by default

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/144)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 28 of 30 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/144)* status: all files reviewed, 13 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA8k8nq2a6hZ0O7C-RK:-NA8k8nq2a6hZ0O7C-RL:bp9shkf) (no related file):*
I see this PR drops support for ignite code generation. Personally I have nothing against but I think it should be a team decision

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9RI_F1b_x00QcbfwD:-NA9RI_F1b_x00QcbfwE:b-xinktm) (no related file):*
Despite upgrading existing infrastructure to new cosmos, this PR also installs some additional modules and provides refactoring on massive scale. Not sure if doing all of these in single PR is a good idea. To be honest I have completely no idea  what some parts of the code do, so I can't fully review it. I think it should be divided into smaller concepts.

___
___
*[`.gitignore` line 2 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA8jF8R5nDVfq66QTVC:-NA8jF8R5nDVfq66QTVD:b-36go8f) ([raw file](https://github.com/coreumfoundation/coreum/blob/4a8363d4a7463a31acbcd646a33e10d927894218/.gitignore#L2)):*
> ```ignore
> .idea
> *.iml
> ```

what's the iml?
___
*[`go.mod` line 6 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA8jNyp8zG-fDZArUNP:-NA8jNyp8zG-fDZArUNQ:blnmjvk) ([raw file](https://github.com/coreumfoundation/coreum/blob/4a8363d4a7463a31acbcd646a33e10d927894218/go.mod#L6)):*
> ```XML
> 
> require (
> 	cosmossdk.io/math v1.0.0-beta.3 // indirect
> ```

did you run `go mod tidy` or `crust tidy`? imports with `// indirect normally go to the second block
___
*[`go.mod` line 10 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA8jie40f_uv72qmv47:-NA8jie40f_uv72qmv48:be8tbx4) ([raw file](https://github.com/coreumfoundation/coreum/blob/4a8363d4a7463a31acbcd646a33e10d927894218/go.mod#L10)):*
> ```XML
> 	github.com/cosmos/cosmos-sdk v0.46.0
> 	github.com/cosmos/go-bip39 v1.0.0
> 	github.com/cosmos/ibc-go/v5 v5.0.0-beta1
> ```

Do we want to use beta software?
___
*[`app/app.go` line 184 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9Qm-05YuVycbzecT_:-NA9Qm-1-aiOUbWHXMCx:b-e13nb0) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/app/app.go#L184)):*
> ```Go
> 	userHomeDir, err := os.UserHomeDir()
> 	if err != nil {
> 		panic(fmt.Sprintf("Failed to get home dir %s", err.Error()))
> ```

```go
panic(errors.Wrap(err, "failed to get home directory"))
```
___
*[`app/app.go` line 281 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9RaJnAQ5q3cRucTJ_:-NA9RaJnAQ5q3cRucTJa:b-7xjxug) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/app/app.go#L281)):*
> ```Go
> 	// configure state listening capabilities using AppOptions
> 	// we are doing nothing with the returned streamingServices and waitGroup in this case
> 	if _, _, err := streaming.LoadStreamingServices(bApp, appOpts, appCodec, keys); err != nil {
> ```

what is it about?
___
*[`app/app.go` line 430 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9S-CCEcMlRhkuyHU-:-NA9S-CCEcMlRhkuyHU0:b-g8o4ro) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/app/app.go#L430)):*
> ```Go
> 	)
> 
> 	app.UpgradeKeeper = upgradekeeper.NewKeeper(
> ```

Code duplication, it is already done above
___
*[`app/network_test.go` line 355 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9TAtn8w41VY117B1Q:-NA9TAtn8w41VY117B1R:bu76aoe) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/app/network_test.go#L355)):*
> ```Go
> }
> 
> func setField(object interface{}, fieldName string, value interface{}) {
> ```

ahhahha :D
___
*[`integration-tests/bank/gas.go` line 71 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9U-ddCOZHHCKh1sn7:-NA9U-ddCOZHHCKh1sn8:bmdflu4) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/integration-tests/bank/gas.go#L71)):*
> ```Go
> 				for i, sender, receiver := numOfTransactions, wallet1, wallet2; i >= 0; i, sender, receiver = i-1, receiver, sender {
> 					gasUsed, err := sendAndReturnGasUsed(ctx, client, sender, receiver, toSend, maxGasAssumed, *chain.Network)
> 					require.NoError(t, err)
> ```

Please leave `asset` here, otherwise max gas collected so far is not logged
___
*[`integration-tests/bank/gas.go` line 78 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9U9enBlCnWnawNd9f:-NA9U9eo3O3ol_6cH8gi:b-5acyo7) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/integration-tests/bank/gas.go#L78)):*
> ```Go
> 					sender.AccountSequence++
> 				}
> 				require.LessOrEqual(t, margin*float64(maxGasUsed), float64(maxGasAssumed))
> ```

same thing
___
*[`pkg/client/client.go` line 240 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9UN3w1yr3fHu8a178:-NA9UN3w1yr3fHu8a179:b-d69z8u) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/pkg/client/client.go#L240)):*
> ```Go
> }
> 
> func asSDKError(err error, expectedSDKErr *cosmoserrors.Error) *cosmoserrors.Error { //nolint:staticcheck // the client is deprecated as well
> ```

why those `nolint` are required? what is deprecated?
___
*[`testutil/network/network.go` line 20 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9Up26D7lwnI1uJcQT:-NA9Up26D7lwnI1uJcQU:b-adl4m2) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/testutil/network/network.go#L20)):*
> ```Go
> )
> 
> // PrintLogger defines a simple logger used for the network test.
> ```

If you need logger, please use `logger` package. Also for unit tests, `t` provides logging

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/144)* status: all files reviewed, 13 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA8k8nq2a6hZ0O7C-RK:-NA9aPin21gdJdugwGU4:b-cetvzf) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I see this PR drops support for ignite code generation. Personally I have nothing against but I think it should be a team decision
</blockquote></details>

As I mention on the team call 2 days ago, the ignite uses the dependencies incompatible with the cosmos-sdk v0.46, so we had to remove it, that's why we have. So it was agreed. 

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9RI_F1b_x00QcbfwD:-NA9ajye2Ooztrn4Ydr3:b-7j4uhq) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Despite upgrading existing infrastructure to new cosmos, this PR also installs some additional modules and provides refactoring on massive scale. Not sure if doing all of these in single PR is a good idea. To be honest I have completely no idea  what some parts of the code do, so I can't fully review it. I think it should be divided into smaller concepts.
</blockquote></details>

What exect modules? The only I see is the "ica" used for the ibc-go/v5. 
And as I mention during the daily call as a part of the SDK migration I proposed to move to the v5 IBC. And it was accepted.

___
___
*[`.gitignore` line 2 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA8jF8R5nDVfq66QTVC:-NA9bVAy1HECXsOSpLtm:bban2ho) ([raw file](https://github.com/coreumfoundation/coreum/blob/4a8363d4a7463a31acbcd646a33e10d927894218/.gitignore#L2)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what's the iml?
</blockquote></details>

The intellij idea generated files.
___
*[`go.mod` line 6 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA8jNyp8zG-fDZArUNP:-NA9bdbYCTBy2KWqgrmw:b9ad8b) ([raw file](https://github.com/coreumfoundation/coreum/blob/4a8363d4a7463a31acbcd646a33e10d927894218/go.mod#L6)):*
> go mod tidy
Sure, the "go mod tidy"
___
*[`go.mod` line 10 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA8jie40f_uv72qmv47:-NA9bfu46Z08ujw6dVAu:b-7h7f2j) ([raw file](https://github.com/coreumfoundation/coreum/blob/4a8363d4a7463a31acbcd646a33e10d927894218/go.mod#L10)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do we want to use beta software?
</blockquote></details>

Right. And it was discussed on the daily caller :-) And I mentioned that it's a beta.
___
*[`app/app.go` line 184 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9Qm-05YuVycbzecT_:-NA9c3v619kTcItSosEi:bvr6wja) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/app/app.go#L184)):*
> errors.Wrap
What is the pupose to do it for the panic?
___
*[`app/app.go` line 281 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9RaJnAQ5q3cRucTJ_:-NA9cdW79Qcqx6AMMv_y:b-aqgx0j) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/app/app.go#L281)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what is it about?
</blockquote></details>

Here is the spec: https://github.com/cosmos/cosmos-sdk/tree/main/store/streaming
___
*[`app/app.go` line 430 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9S-CCEcMlRhkuyHU-:-NA9cw_f9CFQYKTJe2ox:b-rr7k4r) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/app/app.go#L430)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Code duplication, it is already done above
</blockquote></details>

Agree, fixed.



_Code quote:_
```Go
upgradekeeper.NewKeeper(
```
___
*[`app/network_test.go` line 355 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9TAtn8w41VY117B1Q:-NA9d-PS9QM5EkilvlFB:bl1igvb) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/app/network_test.go#L355)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ahhahha :D
</blockquote></details>

:-) I general I wouldn either updated the account generator or just use one prefix for all environments. Since it doesn't seem required.
___
*[`integration-tests/bank/gas.go` line 71 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9U-ddCOZHHCKh1sn7:-NA9dG_S8M7YsyhDdMJa:b40aekz) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/integration-tests/bank/gas.go#L71)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please leave `asset` here, otherwise max gas collected so far is not logged
</blockquote></details>

Ok, updarted.
But if it's failed here, what is the purpose to proceed?
___
*[`integration-tests/bank/gas.go` line 78 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9U9enBlCnWnawNd9f:-NA9dZmd-u-VU9kM5Czn:bumj8gr) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/integration-tests/bank/gas.go#L78)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

same thing
</blockquote></details>

restored



_Code quote:_
```Go
gasUsed, err := sendAndReturnGasUsed(ctx, cl
```
___
*[`pkg/client/client.go` line 240 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9UN3w1yr3fHu8a178:-NA9dbWkDsJHGqhdTSlj:b-fkezl1) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/pkg/client/client.go#L240)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why those `nolint` are required? what is deprecated?
</blockquote></details>

*cosmos errors.Error moved to another package, but since we are updating the client I decided not to touch it.
___
*[`testutil/network/network.go` line 20 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9Up26D7lwnI1uJcQT:-NA9eIk4A9HWDEFps6nm:bqo0o7i) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/testutil/network/network.go#L20)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If you need logger, please use `logger` package. Also for unit tests, `t` provides logging
</blockquote></details>

Good catch. Removed the struct, and use the 't' as logger.



_Code quote:_
```Go
type PrintLogger struct{}
```

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/144)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9RI_F1b_x00QcbfwD:-NA9netv3ev9Th9xKIuv:bd4duq4) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What exect modules? The only I see is the "ica" used for the ibc-go/v5. 
And as I mention during the daily call as a part of the SDK migration I proposed to move to the v5 IBC. And it was accepted.
</blockquote></details>

Now I see that only `router` and `ica` - `authz` is just moved to another line. But the rest of the comment still applies

___
___
*[`.gitignore` line 2 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA8jF8R5nDVfq66QTVC:-NA9k5Qu4byneXs-ePjt:b-1gjdcf) ([raw file](https://github.com/coreumfoundation/coreum/blob/4a8363d4a7463a31acbcd646a33e10d927894218/.gitignore#L2)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The intellij idea generated files.
</blockquote></details>

And it generates them  not under `.idea` dir?
___
*[`go.mod` line 6 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA8jNyp8zG-fDZArUNP:-NA9mTfw6yJQodxW-jxg:bxojb9b) ([raw file](https://github.com/coreumfoundation/coreum/blob/4a8363d4a7463a31acbcd646a33e10d927894218/go.mod#L6)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

> go mod tidy
Sure, the "go mod tidy"
</blockquote></details>

I tried and indeed it does not rearrange them.
But if you put everything in single `require` group and then run `go mod tidy`, then `indirect` imports land in their own group
___
*[`app/app.go` line 184 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9Qm-05YuVycbzecT_:-NA9j8kb99uzjRidSfRv:b612d1s) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/app/app.go#L184)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

> errors.Wrap
What is the pupose to do it for the panic?
</blockquote></details>

because `Wrap` stacks errors and produces string already, but it's a minor thing
___
*[`app/network_test.go` line 355 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9TAtn8w41VY117B1Q:-NA9mqMt-A6P6IVaGgIZ:b770r6i) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/app/network_test.go#L355)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

:-) I general I wouldn either updated the account generator or just use one prefix for all environments. Since it doesn't seem required.
</blockquote></details>

The problem is that you still may have only one configuration at a time. So if we decide to start two different chains in parallel with different config (for testing IBC) then we wouldn't be able to generate addresses for both of them at the same time. I don't agree with this hack, I still prefer to write our own address encoder which uses local configuration.
___
*[`integration-tests/bank/gas.go` line 71 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9U-ddCOZHHCKh1sn7:-NA9jeYQD33nUZLn41eQ:b-vbzqup) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/integration-tests/bank/gas.go#L71)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Ok, updarted.
But if it's failed here, what is the purpose to proceed?
</blockquote></details>

Because if it fails on 10th transaction it's still valuable what was the max gas consumed by one of the 9 transactions.
___
*[`pkg/client/client.go` line 240 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9UN3w1yr3fHu8a178:-NA9nFsc1V1eUrHRzs0C:b-1ejly1) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/pkg/client/client.go#L240)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

*cosmos errors.Error moved to another package, but since we are updating the client I decided not to touch it.
</blockquote></details>

please leave a comment in the client PR

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/144)* status: 28 of 30 files reviewed, 9 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9RI_F1b_x00QcbfwD:-NAACdR_EKnKwAHJ86hF:b5i29z8) (no related file):*
> router
Right, both are for the IBC, since we have agreed to integrate them completely I would leave them all. And let's discuss the need together with the IBC full integration.

___
___
*[`.gitignore` line 2 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA8jF8R5nDVfq66QTVC:-NAA9WlzBnbtK_URn04B:b-faghl7) ([raw file](https://github.com/coreumfoundation/coreum/blob/4a8363d4a7463a31acbcd646a33e10d927894218/.gitignore#L2)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

And it generates them  not under `.idea` dir?
</blockquote></details>

it might use the root for the .iml and .idea as well
___
*[`go.mod` line 6 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA8jNyp8zG-fDZArUNP:-NAA9ihGAV2NBe3Tfse8:b-u9cj4l) ([raw file](https://github.com/coreumfoundation/coreum/blob/4a8363d4a7463a31acbcd646a33e10d927894218/go.mod#L6)):*
> require
I see. Updated the grouping. 
___
*[`app/app.go` line 184 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9Qm-05YuVycbzecT_:-NAAA9ld5TANQeoyQN2N:b-kng7aj) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/app/app.go#L184)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

because `Wrap` stacks errors and produces string already, but it's a minor thing
</blockquote></details>

I thought that panic would produce it as well, but now have understood that in case of panic recovery we might miss it. Update with the errors.Wrap.
___
*[`app/network_test.go` line 355 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9TAtn8w41VY117B1Q:-NAAB4rl2GqvJt6-a89h:bcyvn99) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/app/network_test.go#L355)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The problem is that you still may have only one configuration at a time. So if we decide to start two different chains in parallel with different config (for testing IBC) then we wouldn't be able to generate addresses for both of them at the same time. I don't agree with this hack, I still prefer to write our own address encoder which uses local configuration.
</blockquote></details>

The topic is to wide to be thread in the PR :-)
___
*[`pkg/client/client.go` line 240 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9UN3w1yr3fHu8a178:-NAABBxX8Q483BijxSFb:b9fxxwx) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/pkg/client/client.go#L240)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

please leave a comment in the client PR
</blockquote></details>

Already left the comment after the nolint: "the client is deprecated as well" to indicated that I don't update the package since we are going to refactor it anyway.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/144)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 184 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NADaEvT6LCDFkPr3CkE:-NADaEvT6LCDFkPr3CkF:b-9rvtxl) ([raw file](https://github.com/coreumfoundation/coreum/blob/d026936011a680475e29fdaf861dbeba73e13186/app/app.go#L184)):*
> ```Go
> 	userHomeDir, err := os.UserHomeDir()
> 	if err != nil {
> 		panic(errors.Wrap(err, "Failed to get home dir"))
> ```

Failed -> failed, there is a convention saying that error text should start with lowercase letter

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/144)* status: 29 of 30 files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 184 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NADaEvT6LCDFkPr3CkE:-NADh0F50eA6b7UP4br0:b-mnhymw) ([raw file](https://github.com/coreumfoundation/coreum/blob/d026936011a680475e29fdaf861dbeba73e13186/app/app.go#L184)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Failed -> failed, there is a convention saying that error text should start with lowercase letter
</blockquote></details>

Agree,  updated.  Copy-paste :-) I supposed the linter would't allow to do it.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/144)* status: 29 of 30 files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 184 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NADaEvT6LCDFkPr3CkE:-NADlWWp4UEz0b31q0XE:bfncewm) ([raw file](https://github.com/coreumfoundation/coreum/blob/d026936011a680475e29fdaf861dbeba73e13186/app/app.go#L184)):*
> pupposed
* supposed
*

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/144)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/144)* status: 27 of 30 files reviewed, 11 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.gitignore` line 4 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NAEbPYi75iQBgPOyW-u:-NAFCo1n5MMHrZmLDoLM:b-5swv1i) ([raw file](https://github.com/coreumfoundation/coreum/blob/a63092c3e18693daeda860fb8be2589f1e3eb122/.gitignore#L4)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets make a rule to group these files and add comments to new sections
</blockquote></details>

Updated now grouped by folders and then by files
___
*[`go.mod` line 10 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA8jie40f_uv72qmv47:-NAFZbaH0K8u4gdJmM2X:b-wqzi31) ([raw file](https://github.com/coreumfoundation/coreum/blob/4a8363d4a7463a31acbcd646a33e10d927894218/go.mod#L10)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok for me
</blockquote></details>

so we keep it
___
*[`go.mod` line 158 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NAEU9Gm2tZkzYhbVK54:-NAFUwdV67hip-igJYwJ:by01ely) ([raw file](https://github.com/coreumfoundation/coreum/blob/a63092c3e18693daeda860fb8be2589f1e3eb122/go.mod#L158)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I was hoping that they fixed this strange thingy in v0.46 because it causes issues & some vulnerabilities

@dzmitryhil can you pls check what is the status of dropping this replace on cosmos-sdk side ?
</blockquote></details>

From what I see the replacement is in the SDK as well



_Code quote:_
```XML
github.com/gogo/protobuf
```
___
*[`app/app.go` line 281 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NA9RaJnAQ5q3cRucTJ_:-NAFV7WX7z0Sdn5HvImZ:bz3drhc) ([raw file](https://github.com/coreumfoundation/coreum/blob/ec31cc789fb9240eaddc2e0463833db5445d6a6b/app/app.go#L281)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Quickly went through it but can't really get possible use-cases for this streaming 
Do you have any more info on how we can use it ? Because approach seems to be interesting and the first thing comes up for me is to subsribe via WS/grpc stream to KV store updates

Is it the case ?
</blockquote></details>

The difference is that you can subsribt the store state change directly. With tx you can read the TXs and prepare the state or you can subscribe the event (which might be published by the devs). 
Should I remove it, guys, or we will keep it until the app.go revice task?
___
*[`app/app.go` line 609 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NAEeHeo0GBD7QfGa366:-NAFVqEq9moys5WaxKAC:b594plr) ([raw file](https://github.com/coreumfoundation/coreum/blob/a63092c3e18693daeda860fb8be2589f1e3eb122/app/app.go#L609)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

why did we move it to the bottom of the list everywhere ?
</blockquote></details>

No major reason, will retrun it just not to show the diff
___
*[`app/export.go` line 133 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NAEeiPa7pLcW4jLlEzN:-NAFWft4-2DmQAzT1UW-:bnbv4dr) ([raw file](https://github.com/coreumfoundation/coreum/blob/a63092c3e18693daeda860fb8be2589f1e3eb122/app/export.go#L133)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

we use `errors.Errorf/Wrap etc` everywhere
here it should be `errors.Wrap(err, "error while incrementing period")`
</blockquote></details>

Updated for all "fmt.Errorf" .
___
*[`app/genesis/genesis.tmpl.json` line 141 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NAEmC88D-uoaMRq27T8:-NAFXhuX0aYnkC-QDWDP:b-impddl) ([raw file](https://github.com/coreumfoundation/coreum/blob/a63092c3e18693daeda860fb8be2589f1e3eb122/app/genesis/genesis.tmpl.json#L141)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

non-blocking:
how do we make this type of updates of genesis on running chain ?
</blockquote></details>

I would return to this discussion as a part of the full IBC integration, since I'm not so good with it now :-)
___
*[`app/genesis/genesis.tmpl.json` line 198 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NAEm5t-0FBvN2jXklzx:-NAFCgEA-DmNIJMC2u9v:b5pjxhf) ([raw file](https://github.com/coreumfoundation/coreum/blob/a63092c3e18693daeda860fb8be2589f1e3eb122/app/genesis/genesis.tmpl.json#L198)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what does this mean ?
</blockquote></details>

min_commission_rate is the chain-wide minimum commission rate that a validator can charge their delegators
___
*[`app/openapi/console.go` line 1 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/144#-NAEmjMqEjUwxkuq3TVW:-NAFXsWZ2yWEhlirOtyD:b-c86och) ([raw file](https://github.com/coreumfoundation/coreum/blob/a63092c3e18693daeda860fb8be2589f1e3eb122/app/openapi/console.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what is the responsibility of this handler ?
</blockquote></details>

To retrun the swagger UI.

**Pull request closed without merging**
