### PR TITLE
Close some TODO/FIXMEs & add more context to remaining ones (batch 1)

### PR DESCRIPTION
**Pull request by ysv**
# Description

Some TODOs which were not needed anymore were deleted. 
And also I added v4 to most of left because they could not be fixed right now and will be resolved in v4+ release.
Other TODO/FIXME will be fixed in standalone PRs

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/702)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/702)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`app/app.go` line 182 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/702#-NiK91nI9WZWDYWybT9O:-NiK91nJDrw5qoUpo2A6:b-58bcds) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f53528d6ac5f01522c9aba721d0cf6f6fba03fe3/app/app.go#L182)):*
> ```Go
> 		gov.NewAppModuleBasic(
> 			[]govclient.ProposalHandler{
> 				// TODO(v4): Remove once IBC upgrades to the new param management mechanism. Check ibc-go/modules/core/02-client/types/params.go
> ```

IBC release a new version v7.3 but no changes related to params are included
___
*[`app/upgrade/v3/upgrade.go` line 107 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/702#-NiK8sCDBRmzn-iVQKoW:-NiK8sCDBRmzn-iVQKoX:b-q9dfos) ([raw file](https://github.com/CoreumFoundation/coreum/blob/97367ac08f43f10793d9bf8a37495799b13f5155/app/upgrade/v3/upgrade.go#L107)):*
> ```Go
> 
> 				// coreum:
> 				// TODO(migration-away-from-x/params): Add migration of params for Coreum modules. Skipping them for now.
> ```

@miladz68 
I saw you added assertions for our params in upgrade integratio tests also. Could you pls double check and verify if nothing is skipped
___
*[`app/upgrade/v3/upgrade.go` line 116 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/702#-NiK8cFT6LITEdL1QHY0:-NiK8cFT6LITEdL1QHY1:b-3kz6yo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/97367ac08f43f10793d9bf8a37495799b13f5155/app/upgrade/v3/upgrade.go#L116)):*
> ```Go
> 
> 				if lo.Contains([]string{
> 					// TODO(migration-away-from-x/params): Add migration of params for Coreum modules. Skipping them for now.
> ```

@miladz68 pls double check
We don't need this for our modules, do we ?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/702)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/deterministicgas/config.go` line 82 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/702#-NiKPDOk4Q_phE_9Scei:-NiKPDOk4Q_phE_9Scej:byw8mhz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f53528d6ac5f01522c9aba721d0cf6f6fba03fe3/x/deterministicgas/config.go#L82)):*
> ```Go
> 		MsgToMsgURL(&assetfttypes.MsgGloballyUnfreeze{}):    constantGasFunc(5_000),
> 		MsgToMsgURL(&assetfttypes.MsgSetWhitelistedLimit{}): constantGasFunc(9_000),
> 		// Once we add a new token upgrade MsgUpgradeTokenV2 we should remove this one and re-estimate gas.
> ```

I think `TODO` should be kept here. Otherwise we won't find it.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/702)* status: 6 of 19 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`tools/tools.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/702#-NiL0iyU8A-rhvFK68_B:-NiL0iyU8A-rhvFK68_C:bli7qp7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/97367ac08f43f10793d9bf8a37495799b13f5155/tools/tools.go#L1)):*
> ```Go
> //go:build tools
> ```

@wojtek-coreum @miladz68 @dzmitryhil we don't need this file anymore, do we ?
___
*[`x/deterministicgas/config.go` line 82 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/702#-NiKPDOk4Q_phE_9Scei:-NiL0vMK1NT_a5md6WCw:b-2uzmfl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f53528d6ac5f01522c9aba721d0cf6f6fba03fe3/x/deterministicgas/config.go#L82)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I think `TODO` should be kept here. Otherwise we won't find it.
</blockquote></details>

ok,
I don't think we need it because message will be added here and editor will see the comment but I'm ok to keep it
___
*[`x/wnft/keeper/keeper.go` line 31 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/702#-NiL56hR0mB8MqhD8vUs:-NiL56hR0mB8MqhD8vUt:b-ehqhzd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/97367ac08f43f10793d9bf8a37495799b13f5155/x/wnft/keeper/keeper.go#L31)):*
> ```Go
> // Send overwrites Send method of the original keeper.
> // Copied from https://github.com/cosmos/cosmos-sdk/blob/a1143138716b64bc4fa0aa53c0f0fa59eb675bb7/x/nft/keeper/msg_server.go#L14
> // FIXME(v47-nft-migration): once we update the nft to sdk nft, that methods must be updated as well.
> ```

this method is the same on current x/nft module
But we can't replace this hack anyhow so I keep it as it is

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/702)* status: 4 of 20 files reviewed, 5 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`tools/tools.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/702#-NiL0iyU8A-rhvFK68_B:-NiZEX90CI1eUtTNXtmo:b-78r8zl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/97367ac08f43f10793d9bf8a37495799b13f5155/tools/tools.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

@wojtek-coreum @miladz68 @dzmitryhil we don't need this file anymore, do we ?
</blockquote></details>

That file was created for the ignite support, but I guess @wojtek-coreum extended it with the `grpc-gateway` to generate code. I guess we still needed.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/702)* status: 4 of 20 files reviewed, 6 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`integration-tests/modules/wasm_test.go` line 1960 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/702#-Ni_oDlTD6eSCWt9218e:-Ni_oDlTD6eSCWt9218f:b-3c7ew2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/82f3b657e532a0b8f8ab45e62b72c0a4a14234a5/integration-tests/modules/wasm_test.go#L1960)):*
> ```Go
> 			b[i] = letterRunes[rand.Intn(len(letterRunes))]
> 		}
> 		// Make sure string is not one of reserved subunits/symbols and if it is regenerate it.
> ```

the probability was quite low but it happened :)

` subunit cannot start with ibc: invalid input: invalid input`

https://github.com/CoreumFoundation/coreum/actions/runs/6748086865/job/18345681849?pr=702#step:13:2281
___
*[`tools/tools.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/702#-NiL0iyU8A-rhvFK68_B:-Ni_oRcJEYdSoQiYs56f:b-nhpubc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/97367ac08f43f10793d9bf8a37495799b13f5155/tools/tools.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

That file was created for the ignite support, but I guess @wojtek-coreum extended it with the `grpc-gateway` to generate code. I guess we still needed.
</blockquote></details>

Because I found similar file in crust `crust/build/tools/goinstall.go`
And I think it replaces this one. So deps are installed from the one specified in crust

Waiting for Wojtek's input

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 9 of 9 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/702)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68)

___
*[`tools/tools.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/702#-NiL0iyU8A-rhvFK68_B:-NicYi_ABOGGLRoSYNMi:bpdddjk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/97367ac08f43f10793d9bf8a37495799b13f5155/tools/tools.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Because I found similar file in crust `crust/build/tools/goinstall.go`
And I think it replaces this one. So deps are installed from the one specified in crust

Waiting for Wojtek's input
</blockquote></details>

Fuck, I spent a day finding the correct packages in the source code of ignite and they were here all the time... Yeah, we don't need it anymore.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/702)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/702)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
