### PR TITLE
Update wasm_test names (IBC tests post review).

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/559)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/559)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/ibc/wasm_test.go` line 262 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/559#-NZduSO4DUtP6tvgK1Rh:-NZduSO4DUtP6tvgK1Ri:b-w4l6wu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7071ddd73457cf7863416187f06b5f3c9ace34b0/integration-tests/ibc/wasm_test.go#L262)):*
> ```Go
> 
> 	// check that current state is expected
> 	// the order of assertion is important because we are waiting for the expected none zero counter first to be sure
> ```

none zero -> non-zero
___
*[`integration-tests/ibc/wasm_test.go` line 277 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/559#-NZduYae4GHTItH6pItL:-NZduYae4GHTItH6pItM:b-80qmfn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7071ddd73457cf7863416187f06b5f3c9ace34b0/integration-tests/ibc/wasm_test.go#L277)):*
> ```Go
> }
> 
> // executeWasmIncrement executes increment method on the contract which call another contract and increments the counter.
> ```

which calls

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/559)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/wasm_test.go` line 262 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/559#-NZduSO4DUtP6tvgK1Rh:-NZeQ6TP7kMl3Dp3WJMk:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7071ddd73457cf7863416187f06b5f3c9ace34b0/integration-tests/ibc/wasm_test.go#L262)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

none zero -> non-zero
</blockquote></details>

Done.
___
*[`integration-tests/ibc/wasm_test.go` line 277 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/559#-NZduYae4GHTItH6pItL:-NZeQARr-cx6XCZdZ96R:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7071ddd73457cf7863416187f06b5f3c9ace34b0/integration-tests/ibc/wasm_test.go#L277)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

which calls
</blockquote></details>

Done.

**Review by keyleu — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/559)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/559)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/deterministicgas/types/gas.go` line 141 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/559#-NZetHqGBy_JEu9YgF4w:-NZetHqGBy_JEu9YgF4x:b-6s880c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a42a1a6482e08b43416d320b8dcdbd6237f0139f/x/deterministicgas/types/gas.go#L141)):*
> ```Go
> 
> 	b, _ := json.Marshal(msg)
> 	fmt.Printf("GasFactor:%f, MsgURL:%s, Message: %s\n", gasFactor, msgURL, string(b))
> ```

remove this ?

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/559)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/559)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/559)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
