### PR TITLE
Implement DEX good_til_block_height.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Implement DEX good_til_block_height.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/947)

### CODE REVIEW

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 37 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/947)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/dex/keeper/keeper.go` line 36 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/947#-O6LXjF63uCvpq-CKedB:-O6LXjF73oCFx4tDnhIe:b-asr0l4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f8d9235fb74be53817b101b0c3183135268c0e7c/x/dex/keeper/keeper.go#L36)):*
> ```Go
> 	authority          string
> }
> ```

Please create a task, so we won't forget it
___
*[`x/dex/keeper/keeper_good_til_test.go` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/947#-O6LYTLy4OPHRIEIrkzc:-O6LYTLy4OPHRIEIrkzd:bxvzycz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f8d9235fb74be53817b101b0c3183135268c0e7c/x/dex/keeper/keeper_good_til_test.go#L18)):*
> ```Go
> )
> 
> func TestKeeper_GoodTill(t *testing.T) {
> ```

Is it `GoodTill` or `GoodTil`? Please make it consistent

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/947)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`x/dex/keeper/keeper.go` line 36 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/947#-O6LXjF63uCvpq-CKedB:-O6LcvSL41UhmJIy7fPL:b-hdgu6q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f8d9235fb74be53817b101b0c3183135268c0e7c/x/dex/keeper/keeper.go#L36)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Please create a task, so we won't forget it
</blockquote></details>

I've added it, just forgot to remove the comment, thanks.
___
*[`x/dex/keeper/keeper_good_til_test.go` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/947#-O6LYTLy4OPHRIEIrkzc:-O6Ld3HpEqavtKw3YXqD:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f8d9235fb74be53817b101b0c3183135268c0e7c/x/dex/keeper/keeper_good_til_test.go#L18)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Is it `GoodTill` or `GoodTil`? Please make it consistent
</blockquote></details>

Updated.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 35 of 37 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/947)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/947)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
