### PR TITLE
Set absolute frozen amount

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

New transaction type is introduced to set absolute frozen amount.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/668)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/668)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/deterministicgas/config.go` line 76 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/668#-NgTVoXH9ByP2c3z37e2:-NgTVoXH9ByP2c3z37e3:b-muy021) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e534b24f0f07ba7342a39d6ee5709fa44e8223d4/x/deterministicgas/config.go#L76)):*
> ```Go
> 		MsgToMsgURL(&assetfttypes.MsgMint{}):                constantGasFunc(11000),
> 		MsgToMsgURL(&assetfttypes.MsgBurn{}):                constantGasFunc(23000),
> 		MsgToMsgURL(&assetfttypes.MsgFreeze{}):              constantGasFunc(5000),
> ```

I set gas to 5000 to all freezing-related txes because it seems to be a better value

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/668)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/deterministicgas/config.go` line 76 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/668#-NgTVoXH9ByP2c3z37e2:-NgTWjao0UFjgTFEkPHc:b-l4c861) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e534b24f0f07ba7342a39d6ee5709fa44e8223d4/x/deterministicgas/config.go#L76)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I set gas to 5000 to all freezing-related txes because it seems to be a better value
</blockquote></details>

to 8500 and 5000

**Review by miladz68 — APPROVED** [review]
> Reviewed 11 of 14 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/668)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/668)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 328 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/668#-NgTmMJN9eb8E9FBlBdP:-NgY3kvWDlm6OdB3AkDb:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/91a39812180387cceada8572ceb5a190130cea50/x/asset/ft/keeper/keeper.go#L328)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

As we agreed before the unexported methods should be after all exported. 
And better to finish the method name with `verb`.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper.go` line 405 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/668#-NgTnfE_3HLEhon5sysv:-NgY3AZy1SnI29TAYcoA:b-3tlsw3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/91a39812180387cceada8572ceb5a190130cea50/x/asset/ft/keeper/keeper.go#L405)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't you check it in the `freezingChecks` ?
</blockquote></details>

Because in the other two methods condition is different:

```go
if !coin.IsPositive() {
```

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/668)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/668#-:-NgZ-2Yi7jXuvhCu9HHs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

**Pull request merged**
