### PR TITLE
Burnt NFT IDs cannot be reused

### PR DESCRIPTION
**Pull request by wojtek-coreum**
- create a dictionary of burnt NFTs
- check that dictionary when NFT is minted
- remove invariants
- fix error checks in all the integration tests
- remove `nosnakecase`

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: 12 of 17 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 239 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPr7SHf-rozqDYSxkAm:-NPvPluC9wluWcd9rJ0j:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4d1b396d7e4402306f54d638e88a77d7a06d3d8f/x/asset/nft/keeper/keeper.go#L239)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Maybe `ID was %q already defined for the class` to distinguish the errors.
</blockquote></details>

Done.

**Review by ysv — CHANGES_REQUESTED** [review]
> check that directory when NFT is minted

 check that dictionary right ?

> Reviewed 12 of 15 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-:-NPvogjV8DSYcqIHU2pD:b-ml53o4)* status: all files reviewed, 12 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 19 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwEbWtCYzacnJHBo_3:-NPwEbWtCYzacnJHBo_4:b-22jzqd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb779d685ebc56e57a2568516c81cd27174ca59e/proto/coreum/asset/nft/v1/genesis.proto#L19)):*
> ```protobuf
>   repeated FrozenNFT frozen_nfts = 3 [(gogoproto.nullable) = false, (gogoproto.customname) = "FrozenNFTs"];
>   repeated WhitelistedNFTAccounts whitelisted_nft_accounts = 4 [(gogoproto.nullable) = false, (gogoproto.customname) = "WhitelistedNFTAccounts"];
>   repeated BurntNFT burnt_nfts = 5 [(gogoproto.nullable) = false, (gogoproto.customname) = "BurntNFTs"];
> ```

do we have to change genesis.tmpl ?
___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 33 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwDfelCpkfGTw8cmJz:-NPwDfem3wTQR_AsQElo:b-vhuxln) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb779d685ebc56e57a2568516c81cd27174ca59e/proto/coreum/asset/nft/v1/genesis.proto#L33)):*
> ```protobuf
> }
> 
> message BurntNFT {
> ```

have you checked how cosmos nft module behaves in case of burning ?
Does it completely deletes NFT with to trace left at all ? 
___
*[`x/asset/nft/module.go` line 108 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwFjsn9R8g2iYbONzo:-NPwFjso08S16SZay6GZ:bpuyts6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb779d685ebc56e57a2568516c81cd27174ca59e/x/asset/nft/module.go#L108)):*
> ```Go
> 		AppModuleBasic: NewAppModuleBasic(cdc),
> 		keeper:         keeper,
> 		nftKeeper:      nftKeeper,
> ```

I didn't get this change
Why do we need to store nftKeeper separately if we already have it inside `keeper.Keeper` ?
___
*[`x/asset/nft/keeper/invariant.go` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwFA03DtNigTXe_umF:-NPwFA03DtNigTXe_umG:bbq9nkn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a6174cd1c72ca25b8121871afcdd1651858270f/x/asset/nft/keeper/invariant.go#L15)):*
> ```Go
> const (
> 	OriginalClassExistsInvariantName = "original-class-exists"
> 	WhitelistingInvariantName        = "whitelisting"
> ```

should we add inviriant to check that Burnt NFTs doen't exist in cosmos NFT module store ?
Possibly not this PR but separate task
___
*[`x/asset/nft/keeper/keeper.go` line 663 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPr8KZN4sBovPQjH-gm:-NPwIc8cEB1ShYQsdrEB:b6i85nk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4d1b396d7e4402306f54d638e88a77d7a06d3d8f/x/asset/nft/keeper/keeper.go#L663)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not sure about that switch, it looks better with ifs as for me. 
@ysv @miladz68  ?
</blockquote></details>

also prefer if else
___
*[`x/asset/nft/keeper/keeper.go` line 22 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwGC-z5ZEO0YtMaOoS:-NPwGC-z5ZEO0YtMaOoT:brmoxqm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb779d685ebc56e57a2568516c81cd27174ca59e/x/asset/nft/keeper/keeper.go#L22)):*
> ```Go
> 	frozenNFTStoreValue      = []byte{0x01}
> 	whitelistedNFTStoreValue = []byte{0x01}
> 	burntNFTStoreValue       = []byte{0x01}
> ```

minor: 
maybe it makes sense to define smth like `TrueStoreValue = []byte{0x01}` and then assign other vars to it `frozenNFTStoreValue = TrueStoreValue` t since we repeat magical 0x01 a few times.

not sure
___
*[`x/asset/nft/keeper/keeper.go` line 285 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwH91m3EGa3sQdmE1G:-NPwH91m3EGa3sQdmE1H:b-tpgvye) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb779d685ebc56e57a2568516c81cd27174ca59e/x/asset/nft/keeper/keeper.go#L285)):*
> ```Go
> 	}
> 
> 	// if the token is burnt the storage needs to be cleaned up.
> ```

add note that we don't cleanup whitelists for now
___
*[`x/asset/nft/keeper/keeper.go` line 294 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwH69KESeb1omDmS2n:-NPwH69KESeb1omDmS2o:b-5xi6cx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb779d685ebc56e57a2568516c81cd27174ca59e/x/asset/nft/keeper/keeper.go#L294)):*
> ```Go
> 	}
> 
> 	return k.SetBurnt(ctx, classID, id)
> ```

this should be called inside Burn method IMO
___
*[`x/asset/nft/keeper/keeper.go` line 299 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwEIIX2H8vSYiH033R:-NPwEIIX2H8vSYiH033S:bfsljwg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb779d685ebc56e57a2568516c81cd27174ca59e/x/asset/nft/keeper/keeper.go#L299)):*
> ```Go
> // IsBurnt return whether a non-fungible token is burnt or not.
> func (k Keeper) IsBurnt(ctx sdk.Context, classID, nftID string) (bool, error) {
> 	store := ctx.KVStore(k.storeKey)
> ```


___
*[`x/asset/nft/keeper/keeper.go` line 310 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwIB6aDMdz9dFOPrRy:-NPwIB6aDMdz9dFOPrRz:b4yxii0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb779d685ebc56e57a2568516c81cd27174ca59e/x/asset/nft/keeper/keeper.go#L310)):*
> ```Go
> // SetBurnt marks the nft burnt, but does not make any checks
> // should not be used directly outside the module except for genesis.
> func (k Keeper) SetBurnt(ctx sdk.Context, classID, nftID string) error {
> ```

Before setting this value it makes sense for me to check `IsBurnt`. If it is then error probably
___
*[`x/asset/nft/keeper/keeper.go` line 316 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwHIwFBGFrLxWDhwJd:-NPwHIwFBGFrLxWDhwJe:b-q4k0fo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb779d685ebc56e57a2568516c81cd27174ca59e/x/asset/nft/keeper/keeper.go#L316)):*
> ```Go
> 	}
> 	store := ctx.KVStore(k.storeKey)
> 	store.Set(key, burntNFTStoreValue)
> ```

minor:
no store var needed

`ctx.KVStore(k.storeKey).Set(...)`
___
*[`x/asset/nft/keeper/keeper_test.go` line 236 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwIiTREhIglWNtoNN3:-NPwIiTREhIglWNtoNN4:b-nxguq2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a6174cd1c72ca25b8121871afcdd1651858270f/x/asset/nft/keeper/keeper_test.go#L236)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// mint the nft one more time
> ```

seriously we had test where we minted an NFT with the same ID twice ??

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: all files reviewed, 12 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 19 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwEbWtCYzacnJHBo_3:-NPwJPDXDpgFx8P6YSsu:b-uovwic) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb779d685ebc56e57a2568516c81cd27174ca59e/proto/coreum/asset/nft/v1/genesis.proto#L19)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we have to change genesis.tmpl ?
</blockquote></details>

thankfully not, empty slice is the default value for non-existing field.
___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 33 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwDfelCpkfGTw8cmJz:-NPwJdVDCQqrgv0QdQpc:b-ucv2oj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb779d685ebc56e57a2568516c81cd27174ca59e/proto/coreum/asset/nft/v1/genesis.proto#L33)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

have you checked how cosmos nft module behaves in case of burning ?
Does it completely deletes NFT with to trace left at all ? 
</blockquote></details>

Yes, it does:
```go
nftStore.Delete([]byte(nftID))
```
___
*[`x/asset/nft/module.go` line 108 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwFjsn9R8g2iYbONzo:-NPwJilg-rOcEX9MNMaz:ba516kn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb779d685ebc56e57a2568516c81cd27174ca59e/x/asset/nft/module.go#L108)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I didn't get this change
Why do we need to store nftKeeper separately if we already have it inside `keeper.Keeper` ?
</blockquote></details>

Because invariant needs it. I could create a method in keeper to return the other one. But this way is better IMO.
___
*[`x/asset/nft/keeper/invariant.go` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwFA03DtNigTXe_umF:-NPwJxVD4nMaqfIKqsGD:b-zehw8s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a6174cd1c72ca25b8121871afcdd1651858270f/x/asset/nft/keeper/invariant.go#L15)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should we add inviriant to check that Burnt NFTs doen't exist in cosmos NFT module store ?
Possibly not this PR but separate task
</blockquote></details>

yes, good idea
___
*[`x/asset/nft/keeper/keeper.go` line 285 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwH91m3EGa3sQdmE1G:-NPwK8Rl5RbY8oPsvwSo:bin9l5q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb779d685ebc56e57a2568516c81cd27174ca59e/x/asset/nft/keeper/keeper.go#L285)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

add note that we don't cleanup whitelists for now
</blockquote></details>

we will never do this
___
*[`x/asset/nft/keeper/keeper.go` line 310 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwIB6aDMdz9dFOPrRy:-NPwKVXI7_HE14Jbg5kE:bdeqhpn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb779d685ebc56e57a2568516c81cd27174ca59e/x/asset/nft/keeper/keeper.go#L310)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Before setting this value it makes sense for me to check `IsBurnt`. If it is then error probably
</blockquote></details>

Why? It is not possible to burn the nft twice. In that case the error is returned much earlier.
___
*[`x/asset/nft/keeper/keeper_test.go` line 236 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwIiTREhIglWNtoNN3:-NPwKgSf6oEfkOnzMYIj:b-77k284) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a6174cd1c72ca25b8121871afcdd1651858270f/x/asset/nft/keeper/keeper_test.go#L236)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

seriously we had test where we minted an NFT with the same ID twice ??
</blockquote></details>

:-) Our reviewing process is not perfect yet

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: all files reviewed, 12 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 294 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwH69KESeb1omDmS2n:-NPwKJRY3DrHvPEhPf45:b6sbmbd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cb779d685ebc56e57a2568516c81cd27174ca59e/x/asset/nft/keeper/keeper.go#L294)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

this should be called inside Burn method IMO
</blockquote></details>

??? It is

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: all files reviewed, 12 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 663 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPr8KZN4sBovPQjH-gm:-NQ-1GcH0enHml9DWcrG:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4d1b396d7e4402306f54d638e88a77d7a06d3d8f/x/asset/nft/keeper/keeper.go#L663)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

also prefer if else
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: 16 of 17 files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 299 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwEIIX2H8vSYiH033R:-NQ-3w7u28Fb8mx6sZuX:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b8173c5beb6d774f33f2005413ec1a361d534f17/x/asset/nft/keeper/keeper.go#L299)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>


</blockquote></details>

Done.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/asset/nft/module.go` line 108 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwFjsn9R8g2iYbONzo:-NPxHa3DE1hIAiOZaMBn:b3ixfni) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b8173c5beb6d774f33f2005413ec1a361d534f17/x/asset/nft/module.go#L108)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Because invariant needs it. I could create a method in keeper to return the other one. But this way is better IMO.
</blockquote></details>

we need it only for invariant

why can't we keep it as it was before ?
```
k.nftKeeper.HasNFT(ctx, frozen.ClassID, nftID)
```


I don't have strong preference here but just want to understand
@miladz68 @dzmitryhil WDYT ?
___
*[`x/asset/nft/keeper/keeper.go` line 285 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwH91m3EGa3sQdmE1G:-NPxFiBY-NptY2hGLUbF:b-gp16nc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b8173c5beb6d774f33f2005413ec1a361d534f17/x/asset/nft/keeper/keeper.go#L285)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

we will never do this
</blockquote></details>

but add note anyways since it is not obvious
___
*[`x/asset/nft/keeper/keeper.go` line 310 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwIB6aDMdz9dFOPrRy:-NPxGFctDZR3hxJuHUk7:b-bnwpz7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b8173c5beb6d774f33f2005413ec1a361d534f17/x/asset/nft/keeper/keeper.go#L310)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why? It is not possible to burn the nft twice. In that case the error is returned much earlier.
</blockquote></details>

because we call it directly in genesis
and in general it feels like logical check IMO since we expose this method

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`x/asset/nft/module.go` line 108 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwFjsn9R8g2iYbONzo:-NQ02Gn4DyQaZTwww0jP:bnxzudi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b8173c5beb6d774f33f2005413ec1a361d534f17/x/asset/nft/module.go#L108)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

we need it only for invariant

why can't we keep it as it was before ?
```
k.nftKeeper.HasNFT(ctx, frozen.ClassID, nftID)
```


I don't have strong preference here but just want to understand
@miladz68 @dzmitryhil WDYT ?
</blockquote></details>

ah, I see now, they are in the same packages so private field might be accessed directly. Ok, will do this.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/module.go` line 108 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwFjsn9R8g2iYbONzo:-NQ05buW1IL4-jr-f42K:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b8173c5beb6d774f33f2005413ec1a361d534f17/x/asset/nft/module.go#L108)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ah, I see now, they are in the same packages so private field might be accessed directly. Ok, will do this.
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 285 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwH91m3EGa3sQdmE1G:-NQ05stTB5MtLnvlEd0m:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b8173c5beb6d774f33f2005413ec1a361d534f17/x/asset/nft/keeper/keeper.go#L285)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but add note anyways since it is not obvious
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 310 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NPwIB6aDMdz9dFOPrRy:-NQ06ltD3DQGzuhAvJCb:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b8173c5beb6d774f33f2005413ec1a361d534f17/x/asset/nft/keeper/keeper.go#L310)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

because we call it directly in genesis
and in general it feels like logical check IMO since we expose this method
</blockquote></details>

Done.

**Review by ysv — DISMISSED** [review]
> Reviewed 4 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Review by ysv — DISMISSED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 11 of 15 files at r1, 2 of 3 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by miladz68 — COMMENTED** [review]
> Reviewed 3 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: 17 of 19 files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

___
*[`x/asset/nft/keeper/keeper.go` line 277 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NQ5RuaeCHlyu7y6Gnzg:-NQ5RuaeCHlyu7y6Gnzh:b-sg1il1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/988cc8a4adba311109b61aac47adabf137961cdc/x/asset/nft/keeper/keeper.go#L277)):*
> ```Go
> 	}
> 
> 	//nolint:nestif // removing this complexity will not help with code readability
> ```

this logic is already implemented in `isNFTSendable` but I understand that it is a bit different there

I suggest to move the whole logic of NFT burning permissions to a separate method `isNFTBurnable` similar to sending & keep all logic there
___
*[`x/asset/nft/keeper/keeper.go` line 277 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NQ5VL83B13B1ojBpL1a:-NQ5VL83B13B1ojBpL1b:bt8kyv2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/988cc8a4adba311109b61aac47adabf137961cdc/x/asset/nft/keeper/keeper.go#L277)):*
> ```Go
> 	}
> 
> 	//nolint:nestif // removing this complexity will not help with code readability
> ```

Also isNFTSendable doesn't have this check `ndfd.IsFeatureEnabled(types.ClassFeature_freezing)`
Should we add it there ?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 277 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NQ5RuaeCHlyu7y6Gnzg:-NQ5Wp5I4h6TtZH6sxsu:b-24pg70) ([raw file](https://github.com/CoreumFoundation/coreum/blob/988cc8a4adba311109b61aac47adabf137961cdc/x/asset/nft/keeper/keeper.go#L277)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

this logic is already implemented in `isNFTSendable` but I understand that it is a bit different there

I suggest to move the whole logic of NFT burning permissions to a separate method `isNFTBurnable` similar to sending & keep all logic there


</blockquote></details>

I tried that, but the logic of removing the freezing will not fit there. and the function will only be used here, so I saw no added value and reverted. 
___
*[`x/asset/nft/keeper/keeper.go` line 277 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/429#-NQ5VL83B13B1ojBpL1a:-NQ5XWll6YpUTYg3F0xY:b-ug78kg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/988cc8a4adba311109b61aac47adabf137961cdc/x/asset/nft/keeper/keeper.go#L277)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Also isNFTSendable doesn't have this check `ndfd.IsFeatureEnabled(types.ClassFeature_freezing)`
Should we add it there ?
</blockquote></details>

I don't think it is needed there, since it is handled there differently but checking the error type. I refactored the code and used similar approach. please check again.

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 5 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/429)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
