### PR TITLE
Refactor integration of asset FT with the DEX to accept all `DEXActions` by asset FT required to be applied.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Refactor integration of asset FT with the DEX to accept all `DEXActions` by asset FT required to be applied.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1025)

### CODE REVIEW

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1025)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1025)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`x/asset/ft/keeper/keeper_dex.go` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/1025#-OByJuI0AYE3h_VuFS3K:-OByJuI0AYE3h_VuFS3L:b1y3icu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/adc5f4d51760cb59e6cfdcefb35a4329102f685e/x/asset/ft/keeper/keeper_dex.go#L14)):*
> ```Go
> 
> 	"github.com/CoreumFoundation/coreum/v5/x/asset/ft/types"
> 	cwasmtypes "github.com/CoreumFoundation/coreum/v5/x/wasm/types"
> ```

should it not be wasmtypes instead of cwasmtypes ?
___
*[`x/dex/keeper/keeper_matching.go` line 242 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/1025#-OByU3yy8iLe2PLMWoz-:-OByU3yy8iLe2PLMWoz0:b8telau) ([raw file](https://github.com/CoreumFoundation/coreum/blob/adc5f4d51760cb59e6cfdcefb35a4329102f685e/x/dex/keeper/keeper_matching.go#L242)):*
> ```Go
> }
> 
> func (k Keeper) getMakerLockerAndExpectedToReceiveCoins(
> ```

locker -> locked

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1025)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/asset/ft/keeper/keeper_dex.go` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/1025#-OByJuI0AYE3h_VuFS3K:-OByVBmaDdzUGjDk97yZ:bsga1a4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/adc5f4d51760cb59e6cfdcefb35a4329102f685e/x/asset/ft/keeper/keeper_dex.go#L14)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

should it not be wasmtypes instead of cwasmtypes ?
</blockquote></details>

This is the coreum wasm type, not just wasm. So the name is correct. 
___
*[`x/dex/keeper/keeper_matching.go` line 242 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/1025#-OByU3yy8iLe2PLMWoz-:-OByVRIZ98wxWZ0YQ9EA:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/adc5f4d51760cb59e6cfdcefb35a4329102f685e/x/dex/keeper/keeper_matching.go#L242)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

locker -> locked
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1025)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
