### PR TITLE
Upated new governance params related to v0.50

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/962)

### CODE REVIEW

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/962)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/962)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`app/upgrade/v5/upgrade.go` line 53 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/962#-O77j3gxA3jve0B8jEBi:-O77j3gxA3jve0B8jEBj:b-w5dtel) ([raw file](https://github.com/CoreumFoundation/coreum/blob/55434d97d9dfa24528014997efe6dc7d5ae4ddbf/app/upgrade/v5/upgrade.go#L53)):*
> ```Go
> 			)
> 			govParams.MinDepositRatio = sdkmath.LegacyMustNewDecFromStr("0.01").String()
> 			govParams.BurnVoteQuorum = true
> ```

Are those values final?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/962)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`app/upgrade/v5/upgrade.go` line 53 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/962#-O77j3gxA3jve0B8jEBi:-O78YZikDWVBjtnDszhq:b2nhswy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/55434d97d9dfa24528014997efe6dc7d5ae4ddbf/app/upgrade/v5/upgrade.go#L53)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Are those values final?
</blockquote></details>

Yes

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/962)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/962#-:-O79Tmku8TyMeAx1bHr8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/962)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
