### PR TITLE
Regenerate OpenAPI

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/755)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/755)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/755)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`pkg/store/string.go` line 9 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/755#-Nm18Hw18tHtLj9LZFh0:-Nm18Hw18tHtLj9LZFh1:b-6d762e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/66cc1256270e9d69f45a18e5725d9c3b1c48286e/pkg/store/string.go#L9)):*
> ```Go
> 
> // This file is copy of the sdk
> // https://github.com/cosmos/cosmos-sdk/blob/2582f0aab7b2cbf66ade066fe570a4622cf0b098/internal/conv/string.go
> ```

I guess this comment does not apply anymore, or the commit version should change ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/755)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`pkg/store/string.go` line 9 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/755#-Nm18Hw18tHtLj9LZFh0:-Nm1Ajdu3vgoZHT8UnJI:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/66cc1256270e9d69f45a18e5725d9c3b1c48286e/pkg/store/string.go#L9)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I guess this comment does not apply anymore, or the commit version should change ?
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/755)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
