### PR TITLE
Improve integration tests timeouts to work with fast block time.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

The current integration tests' timeout is set with the expectation that the coreum block time and IBC chains block time are slower than 1 sec. So when we run them against the zent with faster block time, for example, 0.5sec, they pass with the time more than they can. Hence to improve it we can update the retry timeouts we use.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/579)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
considering current values for retrials should we add a validation to crust to limit block time >0.5s ?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/579#-:-N_nGiyNEBtm9i_qvEoa:b8iyjqj)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/chain_ibc.go` line 125 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/579#-N_nH0vs1ty5akX9bI_7:-N_nH0vs1ty5akX9bI_8:b2kttqq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4fad91b7f55f130a6d1a55b25df02794061298fd/integration-tests/chain_ibc.go#L125)):*
> ```Go
> 	retryCtx, retryCancel := context.WithTimeout(ctx, 30*time.Second)
> 	defer retryCancel()
> 	err := retry.Do(retryCtx, 100*time.Millisecond, func() error {
> ```

question:
Why do we have 500ms in some places & 100ms in other ?

what is the difference ?
___
*[`integration-tests/ibc/transfer_test.go` line 138 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/579#-N_nGJk-0RmPSJLT6def:-N_nGJk0DeqJWgdvCpyM:bjw8gw8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4fad91b7f55f130a6d1a55b25df02794061298fd/integration-tests/ibc/transfer_test.go#L138)):*
> ```Go
> 	osmosisChain := chains.Osmosis
> 
> 	gaiaToCoreumChannelID := osmosisChain.AwaitForIBCChannelID(ctx, t, ibctransfertypes.PortID, coreumChain.ChainSettings.ChainID)
> ```

all further vars should also be renamed accordingly:
gaiaToCoreumChannelID -> `osmosisToCoreumChannelID`

etc

**Review by miladz68 — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/579)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

**Review by dzmitryhil — COMMENTED** [review]
Actually - not. The tests work well with any block time.

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/579#-:-N_sCn383hjMYMf7kEGI:bvlucwz)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/chain_ibc.go` line 125 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/579#-N_nH0vs1ty5akX9bI_7:-N_sCrrbA3Ps-ZXxfJJg:b-unirc0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4fad91b7f55f130a6d1a55b25df02794061298fd/integration-tests/chain_ibc.go#L125)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

question:
Why do we have 500ms in some places & 100ms in other ?

what is the difference ?
</blockquote></details>

100ms for the operation which we expect to be executed with low delay, e.g. tx submission. And 500ms for operations we expect to be executed with high delay, e.g. channels creation.
___
*[`integration-tests/ibc/transfer_test.go` line 138 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/579#-N_nGJk-0RmPSJLT6def:-N_sDC6c55YXaqnY0GFm:byitxza) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4fad91b7f55f130a6d1a55b25df02794061298fd/integration-tests/ibc/transfer_test.go#L138)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

all further vars should also be renamed accordingly:
gaiaToCoreumChannelID -> `osmosisToCoreumChannelID`

etc
</blockquote></details>

Make sense. Updated.

**Review by ysv — APPROVED** [review]
but for IBC tests it should be 1s+, no ?



> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/579#-:-N_sLcoN2KdWE6OvF1tM:b-5kbl91)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/579)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by dzmitryhil — COMMENTED** [review]
Yes for IBC it will be one sec.

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/579#-:-N_sV7zQ9f1C6uSyArOg:bpmxj4g)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/579)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
