### PR TITLE
Apply whitelisting rules when minting NFTs

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

This PR replaces previous one:
https://github.com/CoreumFoundation/coreum/pull/674

Approach taken there was a complete failure because to check whitelisting nft must be minted first so it was a chicken & egg problem.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/675)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/675)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 328 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/675#-Ngwfz4q73AAFhExYem9:-Ngwfz4q73AAFhExYemA:be93jlk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/69ae6f4acd5af841742e09433835a89a589a79eb/x/asset/nft/keeper/keeper.go#L328)):*
> ```Go
> 	}
> 
> 	moduleAddr := k.accountKeeper.GetModuleAddress(types.ModuleName)
> ```

This is the same approach taken in bank module. NFT is minted to the module account and then transferred to the final recipient. This way all the conditions (features) are implemented in one place.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/675)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/keeper/transfer.go` line 9 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/675#-Nh5u2utAnHCR_TEQk42:-Nh5u2utAnHCR_TEQk43:b2bgl3s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b4583ef6eb60defaba331685e0b9f7054491c05b/x/asset/nft/keeper/transfer.go#L9)):*
> ```Go
> // Transfer wraps the original transfer function of the nft keeper to include our custom interceptor.
> func (k Keeper) Transfer(ctx sdk.Context, classID, nftID string, receiver sdk.AccAddress) error {
> 	if err := k.beforeTransfer(ctx, classID, nftID, receiver); err != nil {
> ```

why are we changing the design here ?

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/675)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/675)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/675)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

___
*[`x/wnft/types/exptected_keepers.go` line 7 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/675#-Nh6la1W95iOjkmezmuN:-Nh6la1W95iOjkmezmuO:b-e7crtj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b4583ef6eb60defaba331685e0b9f7054491c05b/x/wnft/types/exptected_keepers.go#L7)):*
> ```Go
> // NonFungibleTokenProvider defines the interface to intercept within nft method calls.
> type NonFungibleTokenProvider interface {
> 	Transfer(ctx sdk.Context, classID string, nftID string, receiver sdk.AccAddress) error
> ```

```classID string, nftID string``` -> ```classID, nftID string``

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/675)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68)

___
*[`x/asset/nft/keeper/transfer.go` line 9 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/675#-Nh5u2utAnHCR_TEQk42:-Nh75XNdB7zY1VSx5wX2:bwi3bgv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b4583ef6eb60defaba331685e0b9f7054491c05b/x/asset/nft/keeper/transfer.go#L9)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

why are we changing the design here ?
</blockquote></details>

Because it's simpler. All NFTs are our Asset NFTs so we may just have Transfer method inside this module and call it from the wrapper. It's not required for this PR, it's a side effect of my first approach.

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/675)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

___
*[`x/asset/nft/keeper/transfer.go` line 9 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/675#-Nh5u2utAnHCR_TEQk42:-NhB1EmO6CqAFLxOarRM:bw86hkn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e9e037d71627a8bc5c2850d99653ee91cde21fa2/x/asset/nft/keeper/transfer.go#L9)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Because it's simpler. All NFTs are our Asset NFTs so we may just have Transfer method inside this module and call it from the wrapper. It's not required for this PR, it's a side effect of my first approach.
</blockquote></details>

although all nfts are our NFTs, it might not be the case once nft-ibc-transfer is introduced. even other types of NFTs might come at some point. I see no benefit. 
either way, it seems the other team members are fine, so I will unblock.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/675)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

___
*[`x/wnft/types/exptected_keepers.go` line 7 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/675#-Nh6la1W95iOjkmezmuN:-NhBa06x4X2kSiuynQUa:b-rhs7fe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e9e037d71627a8bc5c2850d99653ee91cde21fa2/x/wnft/types/exptected_keepers.go#L7)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

```classID string, nftID string``` -> ```classID, nftID string``
</blockquote></details>

This is copied from cosmos so let's leave it as is

**Pull request merged**
