### PR TITLE
Minor IBC integration-test improvements & fixes

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/chain.go` line 212 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-NViYP3j-UHO3eayj8io:-NViYP3j-UHO3eayj8ip:bdwfhly) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08e5527c5ca51749adf95c17bb4feb1bdd8b8005/integration-tests/chain.go#L212)):*
> ```Go
> 		defer requestCancel()
> 
> 		balanceRes, err := bankClient.Balance(requestCtx, &banktypes.QueryBalanceRequest{
> ```

I did it intentionally, to because you might use wrong denom during the development, and that error will show you the current state.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
Change the PR to Draft probably? Is see the commented code in it, but I guess it's temporary.

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-:-NVn_Ube4RJNIGlbG4d-:b-41pssw)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — COMMENTED** [review]
yes my fault
fixed now

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-:-NVnimov55w-jTClYxXB:b-nbab84)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/chain.go` line 212 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-NViYP3j-UHO3eayj8io:-NVngcI-3FqhbrJ3SIKk:bgkp0f3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08e5527c5ca51749adf95c17bb4feb1bdd8b8005/integration-tests/chain.go#L212)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I did it intentionally, to because you might use wrong denom during the development, and that error will show you the current state.
</blockquote></details>

I see
Rollbacked & added comment there
___
*[`integration-tests/ibc/transfer_test.go` line 64 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-NVnhrGBBHzaatv7XZET:-NVnhrGBBHzaatv7XZEU:b9jvx8o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9675c6608d69e7e8ae58b1b61fb9835534853455/integration-tests/ibc/transfer_test.go#L64)):*
> ```Go
> 	coreumRecipient := coreumChain.GenAccount()
> 
> 	sendToCoreumCoin := gaiaChain.NewCoin(sdk.NewInt(2000))
> ```

IMO it is beneficial to send different amounts in different tests to make sure we don't have accidental successes because of using the same amounts. I had this confusion while running tests because I had failurs & in both `TestIBCTransferFromCoreumToGaiaAndBack` & `TestIBCTransferFromGaiaToCoreumAndBack` we have same amount 1000 & they run in parallel

Maybe it is even better to use `rand.Int` in such places

WDYT ?
___
*[`integration-tests/ibc/helpers.go` line 3 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-NVniR-Z33aJkPgUzNqu:-NVniR-Z33aJkPgUzNqv:b-mbcuyj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9675c6608d69e7e8ae58b1b61fb9835534853455/integration-tests/ibc/helpers.go#L3)):*
> ```Go
> //go:build integrationtests
> 
> package ibc
> ```

since this code is only used inside integration-tests/ibc I think it is reasonable to store it here

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, 3 of 3 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/chain.go` line 235 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-NVnw9sm7Eifdjvdm8-G:-NVnw9sm7Eifdjvdm8-H:bm34viy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/845013bb0a789aeab33597bb210f88f8ec2c2c76/integration-tests/chain.go#L235)):*
> ```Go
> 
> // GetIBCChannelID returns the first opened channel of the IBC connected chain peer.
> func (c ChainContext) GetIBCChannelID(ctx context.Context, destChainID string) (string, error) {
> ```

Minor: I like "peer" word more and I think we use it consistently everywhere
___
*[`integration-tests/ibc/transfer_test.go` line 64 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-NVnhrGBBHzaatv7XZET:-NVnwaD36dyViRZMdlzt:b-f9714i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9675c6608d69e7e8ae58b1b61fb9835534853455/integration-tests/ibc/transfer_test.go#L64)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO it is beneficial to send different amounts in different tests to make sure we don't have accidental successes because of using the same amounts. I had this confusion while running tests because I had failurs & in both `TestIBCTransferFromCoreumToGaiaAndBack` & `TestIBCTransferFromGaiaToCoreumAndBack` we have same amount 1000 & they run in parallel

Maybe it is even better to use `rand.Int` in such places

WDYT ?
</blockquote></details>

Agree to use different amounts but let's avoid randomness

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/ibc/transfer_test.go` line 64 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-NVnhrGBBHzaatv7XZET:-NVoq6It4_h3UKizALNz:b-vh8jxj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9675c6608d69e7e8ae58b1b61fb9835534853455/integration-tests/ibc/transfer_test.go#L64)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Agree to use different amounts but let's avoid randomness
</blockquote></details>

agree, will keep hardcoded but different amounts

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/helpers.go` line 1 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-NW15BZX3PwtPjsCj6PI:-NW15BZY2H-9fP3wF5S8:b8749iv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e37cb4ed92e2b4a17ad9aa313aad2989df5ae9c3/integration-tests/ibc/helpers.go#L1)):*
> ```Go
> //go:build integrationtests
> ```

Let's keep the file name, and still call it ibc.go.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 1 of 1 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 3 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/transfer_test.go` line 64 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-NVnhrGBBHzaatv7XZET:-NW1X24y3DXHn1Z97x58:b4tc4ov) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9675c6608d69e7e8ae58b1b61fb9835534853455/integration-tests/ibc/transfer_test.go#L64)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

agree, will keep hardcoded but different amounts
</blockquote></details>

But how does the different amount help?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

___
*[`integration-tests/ibc/transfer_test.go` line 64 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-NVnhrGBBHzaatv7XZET:-NW1h2ZF4ILjgKzUw7xn:b-4eepzo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9675c6608d69e7e8ae58b1b61fb9835534853455/integration-tests/ibc/transfer_test.go#L64)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But how does the different amount help?
</blockquote></details>

because these amounts might unintentionally match and will not detect a mistake in tests

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

___
*[`integration-tests/ibc/transfer_test.go` line 64 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-NVnhrGBBHzaatv7XZET:-NW1hdqI6Kqj4-2sVeH2:b26x7k3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9675c6608d69e7e8ae58b1b61fb9835534853455/integration-tests/ibc/transfer_test.go#L64)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

because these amounts might unintentionally match and will not detect a mistake in tests
</blockquote></details>

same issue as we have here: 
https://github.com/CoreumFoundation/coreum/pull/503/files#diff-fdb4e65de50064f97071dbab024f3e4655b8c86de59115e67b47e8197824b068R23

Since all channels are named channel-0 we have mistake in our tests but because of same naming they pass

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

___
*[`integration-tests/ibc/transfer_test.go` line 64 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-NVnhrGBBHzaatv7XZET:-NW1jWBd5VqR3I0Pb_UY:b-4lusn8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9675c6608d69e7e8ae58b1b61fb9835534853455/integration-tests/ibc/transfer_test.go#L64)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

same issue as we have here: 
https://github.com/CoreumFoundation/coreum/pull/503/files#diff-fdb4e65de50064f97071dbab024f3e4655b8c86de59115e67b47e8197824b068R23

Since all channels are named channel-0 we have mistake in our tests but because of same naming they pass
</blockquote></details>

But the accounts are new each time, if the issue with the amount the account won't receive it.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

___
*[`integration-tests/ibc/transfer_test.go` line 64 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-NVnhrGBBHzaatv7XZET:-NW1mD51C31VyjpEWTCy:bwl7w1w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9675c6608d69e7e8ae58b1b61fb9835534853455/integration-tests/ibc/transfer_test.go#L64)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But the accounts are new each time, if the issue with the amount the account won't receive it.
</blockquote></details>

What are the benefits of using same amounts ?

IMO there are no. While using different will protect agains these type of issues, it has already happened for channel names that is why it is always better to use different amounts as a rule, maybe in this case it is unlikely to happen but it helps in general.  Also it makes debugging easier. 


Debugging example:
E.g when I see 2000 in logs I know that refer to a specific test. But if I see 1000 everywhere it could any tests


Screenshot 2023-05-22 at 11.31.12

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

___
*[`integration-tests/ibc/transfer_test.go` line 64 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/497#-NVnhrGBBHzaatv7XZET:-NW1s3r432qAiZKmeJPC:b3gwgyi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9675c6608d69e7e8ae58b1b61fb9835534853455/integration-tests/ibc/transfer_test.go#L64)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

What are the benefits of using same amounts ?

IMO there are no. While using different will protect agains these type of issues, it has already happened for channel names that is why it is always better to use different amounts as a rule, maybe in this case it is unlikely to happen but it helps in general.  Also it makes debugging easier. 


Debugging example:
E.g when I see 2000 in logs I know that refer to a specific test. But if I see 1000 everywhere it could any tests


Screenshot 2023-05-22 at 11.31.12
</blockquote></details>

OK, let's leave that comment until we discuss the https://github.com/CoreumFoundation/coreum/pull/503/files#diff-fdb4e65de50064f97071dbab024f3e4655b8c86de59115e67b47e8197824b068R23

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/497)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
