### PR TITLE
Issue fee for FT and mint fee for NFT

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: 0 of 51 files reviewed, 9 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 393 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXhMUh-IJj4T0jL5J5:-NKXhMUh-IJj4T0jL5J6:b-mu45at) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/app/app.go#L393)):*
> ```Go
> 		app.NFTKeeper,
> 		// for the assetnft we use the clear bank keeper without the assets integration because it interacts only with native token.
> 		originalBankKeeper,
> ```

What is the reason to use the original bank keeper in the NFT ?
___
*[`integration-tests/modules/assetft_test.go` line 57 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXhx7M3DohnVlL9FN4:-NKXhx7M3DohnVlL9FN5:bq3ixcr) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/integration-tests/modules/assetft_test.go#L57)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// check that balance is 0 meaning issue fee was taken
> ```

You could check the burning event here to be sure that it's burnt.
___
*[`integration-tests/modules/assetft_test.go` line 67 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXkVVY7M3U0q0sZT0E:-NKXkVVY7M3U0q0sZT0F:bfa3h2h) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/integration-tests/modules/assetft_test.go#L67)):*
> ```Go
> 	requireT.Equal(chain.NewCoin(sdk.ZeroInt()).String(), resp.Balance.String())
> }
> ```

What about params change tests for both FT and NFT ?
___
*[`pkg/config/network.go` line 71 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXiXR0BbqUP_jrHbvJ:-NKXiXR0BbqUP_jrHbvK:b-us8365) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/pkg/config/network.go#L71)):*
> ```Go
> 
> 		assetFTConfig = AssetFTConfig{
> 			IssueFee: sdk.NewIntFromUint64(10000000),
> ```

Optional: For the readability better to split long number by `_`. (Same comment relates to `testNetwork()` func.)
___
*[`x/asset/ft/keeper/issue.go` line 43 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXk5P90GCPNfoBh3wR:-NKXk5PAE9TJ8VQ1-j-Q:bf1wxe) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/x/asset/ft/keeper/issue.go#L43)):*
> ```Go
> 
> 	params := k.GetParams(ctx)
> 	if params.IssueFee.IsPositive() {
> ```

Why there are no keeper tests? For example of a used doesn't have enough coins. (Same relates to NFT)
___
*[`x/asset/ft/types/genesis.go` line 5 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXjLYH4gJoF_MHrA5B:-NKXjLYH4gJoF_MHrA5C:b-r35rta) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/x/asset/ft/types/genesis.go#L5)):*
> ```Go
> // DefaultGenesis returns the default FT genesis state.
> func DefaultGenesis() *GenesisState {
> 	// TODO(dhil) replace with real implementation
> ```

Remove the comments please they are not valid anymore.
___
*[`x/asset/ft/types/params.go` line 23 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXjXEyD_PhX_7iMnLZ:-NKXjXEyD_PhX_7iMnL_:bsp5d03) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/x/asset/ft/types/params.go#L23)):*
> ```Go
> func DefaultParams() Params {
> 	return Params{
> 		IssueFee: sdk.NewInt64Coin("stake", 0),
> ```

Use `sdk.DefaultBondDenom` indtead of  "stake". same comment for the NFT)
___
*[`x/asset/ft/types/params.go` line 28 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXlF5r39L0HyrIuGZ-:-NKXlF5r39L0HyrIuGZ0:b-cqef6h) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/x/asset/ft/types/params.go#L28)):*
> ```Go
> 
> // ValidateBasic validates parameters.
> func (m Params) ValidateBasic() error {
> ```

I haven't found tests for it, same for NFT.
___
*[`x/asset/ft/types/params.go` line 37 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXjfdhCVRpsDAncurW:-NKXjfdhCVRpsDAncurX:b-5vdud6) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/x/asset/ft/types/params.go#L37)):*
> ```Go
> 		return errors.Errorf("invalid parameter type: %T", i)
> 	}
> 	if fee.IsNil() || fee.IsNegative() {
> ```

fee can alos be checked by `fee.IsValid()` (same comment for the NFT)
___
*[`x/asset/nft/genesis_test.go` line 14 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXle5c65naCbsdE8lh:-NKXle5c65naCbsdE8li:bi6zx0e) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/x/asset/nft/genesis_test.go#L14)):*
> ```Go
> )
> 
> func TestImportAndExportGenesis(t *testing.T) {
> ```

The correct name is `InitAndExportGenesis`

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 22 of 51 files at r1, 28 of 28 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: all files reviewed, 9 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: 42 of 53 files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`app/app.go` line 393 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXhMUh-IJj4T0jL5J5:-NKXpkaA74zkYPaDFb6G:bv1gqbk) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/app/app.go#L393)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the reason to use the original bank keeper in the NFT ?
</blockquote></details>

because we transfer only cored there so we don't need functionality provided by the wrapper
___
*[`integration-tests/modules/assetft_test.go` line 67 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXkVVY7M3U0q0sZT0E:-NKXpurE4QuYec9PCF3T:b7d5csu) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/integration-tests/modules/assetft_test.go#L67)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about params change tests for both FT and NFT ?
</blockquote></details>

Done in latest commit
___
*[`x/asset/ft/keeper/issue.go` line 43 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXk5P90GCPNfoBh3wR:-NKXq9x_2wwYt3cJHVui:bx436t7) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/x/asset/ft/keeper/issue.go#L43)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why there are no keeper tests? For example of a used doesn't have enough coins. (Same relates to NFT)
</blockquote></details>

Do we need them? If there are no coins to cover burn fee, burning will fail by definition

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: 42 of 53 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/types/genesis.go` line 5 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXjLYH4gJoF_MHrA5B:-NKXsCrZEpQOrIRm8AMx:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/x/asset/ft/types/genesis.go#L5)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Remove the comments please they are not valid anymore.
</blockquote></details>

Done.
___
*[`x/asset/ft/types/params.go` line 23 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXjXEyD_PhX_7iMnLZ:-NKXs4mhCL4xpVVQTdW5:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/x/asset/ft/types/params.go#L23)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Use `sdk.DefaultBondDenom` indtead of  "stake". same comment for the NFT)
</blockquote></details>

Done.
___
*[`x/asset/ft/types/params.go` line 37 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXjfdhCVRpsDAncurW:-NKXs7S39eGz6IapuOyL:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/x/asset/ft/types/params.go#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

fee can alos be checked by `fee.IsValid()` (same comment for the NFT)
</blockquote></details>

Done.
___
*[`x/asset/nft/genesis_test.go` line 14 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXle5c65naCbsdE8lh:-NKXs8dj4bq0r96E72Zj:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/x/asset/nft/genesis_test.go#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The correct name is `InitAndExportGenesis`
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: 42 of 55 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/types/params.go` line 28 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXlF5r39L0HyrIuGZ-:-NKXzI68-j8z_2Y-edP5:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/x/asset/ft/types/params.go#L28)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I haven't found tests for it, same for NFT.
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: 42 of 55 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 57 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXhx7M3DohnVlL9FN4:-NKY3xeA2cTUN1-lNO_-:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/integration-tests/modules/assetft_test.go#L57)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You could check the burning event here to be sure that it's burnt.
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: 42 of 57 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/issue.go` line 43 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKXk5P90GCPNfoBh3wR:-NKYAUin0f0v8Z-DVcV-:b-d8f5m8) ([raw file](https://github.com/coreumfoundation/coreum/blob/d1612a9ed8e9a57d40b5b59ebc199a9f9583d4c3/x/asset/ft/keeper/issue.go#L43)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do we need them? If there are no coins to cover burn fee, burning will fail by definition
</blockquote></details>

I added some

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: 42 of 57 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: 41 of 57 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/network_test.go` line 73 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKlY0jA9iy6lBOxn-3y:-NKlY0jA9iy6lBOxn-3z:b5gfj15) ([raw file](https://github.com/coreumfoundation/coreum/blob/f26fafa50107307e54ac7a1986b29352afe9bedb/pkg/config/network_test.go#L73)):*
> ```Go
> 		},
> 		AssetFTConfig: config.AssetFTConfig{
> 			IssueFee: sdk.NewIntFromUint64(10_00_000),
> ```

Check the zeros amount

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 15 of 51 files at r1, 26 of 28 files at r2, 1 of 3 files at r4, 5 of 8 files at r5, 4 of 4 files at r6, 4 of 4 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper_test.go` line 235 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKleleb-yNxryh274KK:-NKleleb-yNxryh274KL:b-4wp9l8) ([raw file](https://github.com/coreumfoundation/coreum/blob/f26fafa50107307e54ac7a1986b29352afe9bedb/x/asset/ft/keeper/keeper_test.go#L235)):*
> ```Go
> }
> 
> func TestKeeper_Issue_WithoutFee(t *testing.T) {
> ```

non blocking
Consider `TestKeeper_Issue_WithZeroBurnFee` as the test name.
___
*[`x/asset/nft/module.go` line 65 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKlfFhH6psk0puJa3gx:-NKlfFhH6psk0puJa3gy:b-m3g8yx) ([raw file](https://github.com/coreumfoundation/coreum/blob/f26fafa50107307e54ac7a1986b29352afe9bedb/x/asset/nft/module.go#L65)):*
> ```Go
> 	var genState types.GenesisState
> 	if err := cdc.UnmarshalJSON(bz, &genState); err != nil {
> 		return fmt.Errorf("failed to unmarshal %s genesis state: %w", types.ModuleName, err)
> ```

pkg/errors, instead of fmt

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: 52 of 60 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`pkg/config/network_test.go` line 73 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKlY0jA9iy6lBOxn-3y:-NKmegK5C6i7Rymv1hKq:b-181b1x) ([raw file](https://github.com/coreumfoundation/coreum/blob/f26fafa50107307e54ac7a1986b29352afe9bedb/pkg/config/network_test.go#L73)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Check the zeros amount
</blockquote></details>

There is test `TestKeeper_Issue_WithZeroIssueFee`
___
*[`x/asset/nft/module.go` line 65 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKlfFhH6psk0puJa3gx:-NKmd1-z-3CVQ9XPMEoV:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/f26fafa50107307e54ac7a1986b29352afe9bedb/x/asset/nft/module.go#L65)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

pkg/errors, instead of fmt 
</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: 52 of 60 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/network_test.go` line 73 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKlY0jA9iy6lBOxn-3y:-NKmknfo3qtzGSP6yIsN:b-uqishl) ([raw file](https://github.com/coreumfoundation/coreum/blob/f26fafa50107307e54ac7a1986b29352afe9bedb/pkg/config/network_test.go#L73)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

There is test `TestKeeper_Issue_WithZeroIssueFee`
</blockquote></details>

In that case the value should be written as "1_000_000"

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 5 of 8 files at r5, 4 of 4 files at r6, 1 of 4 files at r7, 2 of 2 files at r8, 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`pkg/config/network_test.go` line 73 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKlY0jA9iy6lBOxn-3y:-NKmtB6Y-fNtFC1-TsHy:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/f26fafa50107307e54ac7a1986b29352afe9bedb/pkg/config/network_test.go#L73)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

In that case the value should be written as "1_000_000"
</blockquote></details>

Done.



_Code quote:_
```Go
10_00_000
```

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: 59 of 60 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 8 of 8 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 13 of 51 files at r1, 26 of 28 files at r2, 1 of 3 files at r4, 4 of 8 files at r5, 4 of 4 files at r6, 1 of 4 files at r7, 2 of 2 files at r8, 8 of 8 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: all files reviewed, 4 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

___
*[`integration-tests/modules/assetft_test.go` line 82 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKwSV9VARozQZBkEyel:-NKwSV9VARozQZBkEyem:b-iinl5m) ([raw file](https://github.com/coreumfoundation/coreum/blob/2702c5bb2e17934c6fa66e5aa3b4820ea5817295/integration-tests/modules/assetft_test.go#L82)):*
> ```Go
> // TestAssetFTIssueFeeProposal tests proposal upgrading issue fee
> func TestAssetFTIssueFeeProposal(t *testing.T) {
> 	// This test can't be run together with other tests because it affects balances due to unexpected issue fee.
> ```

what are we going to do with it ?
Because I had the same concern
___
*[`integration-tests/modules/assetnft_test.go` line 412 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKwTrFz2ujuZffJZeOq:-NKwTrFz2ujuZffJZeOr:bnlqibp) ([raw file](https://github.com/coreumfoundation/coreum/blob/2702c5bb2e17934c6fa66e5aa3b4820ea5817295/integration-tests/modules/assetnft_test.go#L412)):*
> ```Go
> }
> 
> //nolint:dupl
> ```

minor: why is it duplicated ?
___
*[`pkg/config/network_test.go` line 73 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKwUDkIBedW2aBruydj:-NKwUDkIBedW2aBruydk:b-nz378q) ([raw file](https://github.com/coreumfoundation/coreum/blob/2702c5bb2e17934c6fa66e5aa3b4820ea5817295/pkg/config/network_test.go#L73)):*
> ```Go
> 		},
> 		AssetFTConfig: config.AssetFTConfig{
> 			IssueFee: sdk.NewIntFromUint64(10_000_000),
> ```

minor:
I would add comment `// 10 core` & `0.5 core`

For NFT I would also highlight that in real chain we have it set to 0 but here it is 0.5 for more complex testing purpose
___
*[`pkg/config/genesis/genesis.tmpl.json` line 27 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKwUas70C1YCE0edqAO:-NKwUas70C1YCE0edqAP:b-50lxmi) ([raw file](https://github.com/coreumfoundation/coreum/blob/2702c5bb2e17934c6fa66e5aa3b4820ea5817295/pkg/config/genesis/genesis.tmpl.json#L27)):*
> ```JSON
>     "assetft": {
>       "params": {
>         "issue_fee": {
> ```

immature idea:
should we have `[]Coin` here instead of a single object ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 412 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKwTrFz2ujuZffJZeOq:-NKwbWSV51Lbcm0ECBKZ:bbv57nd) ([raw file](https://github.com/coreumfoundation/coreum/blob/c33004e00f8361ee9b761ff0416f44e7d0d3b171/integration-tests/modules/assetnft_test.go#L412)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: why is it duplicated ?
</blockquote></details>

Moved common code to gov
___
*[`pkg/config/network_test.go` line 73 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKwUDkIBedW2aBruydj:-NKwZW7ZD4uMHPewML1X:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/c33004e00f8361ee9b761ff0416f44e7d0d3b171/pkg/config/network_test.go#L73)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
I would add comment `// 10 core` & `0.5 core`

For NFT I would also highlight that in real chain we have it set to 0 but here it is 0.5 for more complex testing purpose
</blockquote></details>

Done

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`integration-tests/modules/assetft_test.go` line 82 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKwSV9VARozQZBkEyel:-NKwd6P12OD2B54cSJOX:b16kor8) ([raw file](https://github.com/coreumfoundation/coreum/blob/c33004e00f8361ee9b761ff0416f44e7d0d3b171/integration-tests/modules/assetft_test.go#L82)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Nothing, test reverts the value at the end. We may eventually implement test groups so tests which might run together are in the same group, like it was before moving to new framework.
</blockquote></details>

I see what is the difference
We don't put `t.Parallel`here like we do in other tests. Am I right ?

I think it is worth mentioning in comment that we do not put t.Parallel because it is not recommended to run this one in parallel with others

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 82 at r10](https://reviewable.io/reviews/coreumfoundation/coreum/320#-NKwSV9VARozQZBkEyel:-NKweBVl6maLrXLxzOtJ:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/c33004e00f8361ee9b761ff0416f44e7d0d3b171/integration-tests/modules/assetft_test.go#L82)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I see what is the difference
We don't put `t.Parallel`here like we do in other tests. Am I right ?

I think it is worth mentioning in comment that we do not put t.Parallel because it is not recommended to run this one in parallel with others
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/320)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
