### PR TITLE
Adjust deterministic gas values & add missing msg types

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/352)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/352)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/352#-NM3y8FZ29n84PQa6-_O:-NM3y8F_9YGVoRrAD2eJ:bngvxy9) (no related file):*
I had to make a few gymnastics & multiple iterations to come up with proper values. It is better to discuss it on call with all details.

Metrics before adjusting them:
```
deterministic_gas_factor_sum{msg_name="coreum.asset.ft.v1.MsgBurn"} 2.581457108259201
deterministic_gas_factor_count{msg_name="coreum.asset.ft.v1.MsgBurn"} 4
deterministic_gas_factor_sum{msg_name="coreum.asset.ft.v1.MsgFreeze"} 0.20792727172374725
deterministic_gas_factor_count{msg_name="coreum.asset.ft.v1.MsgFreeze"} 3
deterministic_gas_factor_sum{msg_name="coreum.asset.ft.v1.MsgGloballyFreeze"} 1.0140000581741333
deterministic_gas_factor_count{msg_name="coreum.asset.ft.v1.MsgGloballyFreeze"} 1
deterministic_gas_factor_sum{msg_name="coreum.asset.ft.v1.MsgGloballyUnfreeze"} 0.48399999737739563
deterministic_gas_factor_count{msg_name="coreum.asset.ft.v1.MsgGloballyUnfreeze"} 1
deterministic_gas_factor_sum{msg_name="coreum.asset.ft.v1.MsgIssue"} 27.410874903202057
deterministic_gas_factor_count{msg_name="coreum.asset.ft.v1.MsgIssue"} 31
deterministic_gas_factor_sum{msg_name="coreum.asset.ft.v1.MsgMint"} 0.895085733383894
deterministic_gas_factor_count{msg_name="coreum.asset.ft.v1.MsgMint"} 3
deterministic_gas_factor_sum{msg_name="coreum.asset.ft.v1.MsgSetWhitelistedLimit"} 0.6854857131838799
deterministic_gas_factor_count{msg_name="coreum.asset.ft.v1.MsgSetWhitelistedLimit"} 5
deterministic_gas_factor_sum{msg_name="coreum.asset.ft.v1.MsgUnfreeze"} 0.27878181636333466
deterministic_gas_factor_count{msg_name="coreum.asset.ft.v1.MsgUnfreeze"} 3
deterministic_gas_factor_sum{msg_name="coreum.asset.nft.v1.MsgBurn"} 1.0241999626159668
deterministic_gas_factor_count{msg_name="coreum.asset.nft.v1.MsgBurn"} 1
deterministic_gas_factor_sum{msg_name="coreum.asset.nft.v1.MsgIssueClass"} 3.2639999389648438
deterministic_gas_factor_count{msg_name="coreum.asset.nft.v1.MsgIssueClass"} 4
deterministic_gas_factor_sum{msg_name="coreum.asset.nft.v1.MsgMint"} 3.551800012588501
deterministic_gas_factor_count{msg_name="coreum.asset.nft.v1.MsgMint"} 3
deterministic_gas_factor_sum{msg_name="coreum.nft.v1beta1.MsgSend"} 0.7915999889373779
deterministic_gas_factor_count{msg_name="coreum.nft.v1beta1.MsgSend"} 1
deterministic_gas_factor_sum{msg_name="cosmos.authz.v1beta1.MsgExec"} 1.0475000087171793
deterministic_gas_factor_count{msg_name="cosmos.authz.v1beta1.MsgExec"} 2
deterministic_gas_factor_sum{msg_name="cosmos.authz.v1beta1.MsgGrant"} 0.9800000190734863
deterministic_gas_factor_count{msg_name="cosmos.authz.v1beta1.MsgGrant"} 1
deterministic_gas_factor_sum{msg_name="cosmos.authz.v1beta1.MsgRevoke"} 0.35514286160469055
deterministic_gas_factor_count{msg_name="cosmos.authz.v1beta1.MsgRevoke"} 1
deterministic_gas_factor_sum{msg_name="cosmos.bank.v1beta1.MsgMultiSend"} 7.909080147743225
deterministic_gas_factor_count{msg_name="cosmos.bank.v1beta1.MsgMultiSend"} 14
deterministic_gas_factor_sum{msg_name="cosmos.bank.v1beta1.MsgSend"} 1447.9954303354025
deterministic_gas_factor_count{msg_name="cosmos.bank.v1beta1.MsgSend"} 1323
deterministic_gas_factor_sum{msg_name="cosmos.distribution.v1beta1.MsgFundCommunityPool"} 0.3032200038433075
deterministic_gas_factor_count{msg_name="cosmos.distribution.v1beta1.MsgFundCommunityPool"} 1
deterministic_gas_factor_sum{msg_name="cosmos.distribution.v1beta1.MsgSetWithdrawAddress"} 0.08736000210046768
deterministic_gas_factor_count{msg_name="cosmos.distribution.v1beta1.MsgSetWithdrawAddress"} 1
deterministic_gas_factor_sum{msg_name="cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward"} 1.1015416383743286
deterministic_gas_factor_count{msg_name="cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward"} 2
deterministic_gas_factor_sum{msg_name="cosmos.distribution.v1beta1.MsgWithdrawValidatorCommission"} 0.44694000482559204
deterministic_gas_factor_count{msg_name="cosmos.distribution.v1beta1.MsgWithdrawValidatorCommission"} 1
deterministic_gas_factor_sum{msg_name="cosmos.feegrant.v1beta1.MsgGrantAllowance"} 0.7625384330749512
deterministic_gas_factor_count{msg_name="cosmos.feegrant.v1beta1.MsgGrantAllowance"} 1
deterministic_gas_factor_sum{msg_name="cosmos.feegrant.v1beta1.MsgRevokeAllowance"} 0.19584615528583527
deterministic_gas_factor_count{msg_name="cosmos.feegrant.v1beta1.MsgRevokeAllowance"} 1
deterministic_gas_factor_sum{msg_name="cosmos.gov.v1beta1.MsgDeposit"} 4.854545593261719
deterministic_gas_factor_count{msg_name="cosmos.gov.v1beta1.MsgDeposit"} 1
deterministic_gas_factor_sum{msg_name="cosmos.gov.v1beta1.MsgSubmitProposal"} 10.274505222216249
deterministic_gas_factor_count{msg_name="cosmos.gov.v1beta1.MsgSubmitProposal"} 15
deterministic_gas_factor_sum{msg_name="cosmos.gov.v1beta1.MsgVote"} 34.033500015735626
deterministic_gas_factor_count{msg_name="cosmos.gov.v1beta1.MsgVote"} 39
deterministic_gas_factor_sum{msg_name="cosmos.gov.v1beta1.MsgVoteWeighted"} 2.5830000042915344
deterministic_gas_factor_count{msg_name="cosmos.gov.v1beta1.MsgVoteWeighted"} 3
deterministic_gas_factor_sum{msg_name="cosmos.staking.v1beta1.MsgBeginRedelegate"} 2.889744997024536
deterministic_gas_factor_count{msg_name="cosmos.staking.v1beta1.MsgBeginRedelegate"} 1
deterministic_gas_factor_sum{msg_name="cosmos.staking.v1beta1.MsgCreateValidator"} 9.217600114643574
deterministic_gas_factor_count{msg_name="cosmos.staking.v1beta1.MsgCreateValidator"} 6
deterministic_gas_factor_sum{msg_name="cosmos.staking.v1beta1.MsgDelegate"} 2.7363137006759644
deterministic_gas_factor_count{msg_name="cosmos.staking.v1beta1.MsgDelegate"} 2
deterministic_gas_factor_sum{msg_name="cosmos.staking.v1beta1.MsgEditValidator"} 0.5143199861049652
deterministic_gas_factor_count{msg_name="cosmos.staking.v1beta1.MsgEditValidator"} 2
deterministic_gas_factor_sum{msg_name="cosmos.staking.v1beta1.MsgUndelegate"} 6.6640784740448
deterministic_gas_factor_count{msg_name="cosmos.staking.v1beta1.MsgUndelegate"} 3
deterministic_gas_factor_sum{msg_name="cosmwasm.wasm.v1.MsgClearAdmin"} 1.6357500553131104
deterministic_gas_factor_count{msg_name="cosmwasm.wasm.v1.MsgClearAdmin"} 2
deterministic_gas_factor_sum{msg_name="cosmwasm.wasm.v1.MsgUpdateAdmin"} 1.9957499504089355
deterministic_gas_factor_count{msg_name="cosmwasm.wasm.v1.MsgUpdateAdmin"} 2

```


after final adjustment iteration:

```
deterministic_gas_factor_sum{msg_name="coreum.asset.ft.v1.MsgBurn"} 3.928304374217987
deterministic_gas_factor_count{msg_name="coreum.asset.ft.v1.MsgBurn"} 4
deterministic_gas_factor_sum{msg_name="coreum.asset.ft.v1.MsgFreeze"} 2.2020000290870667
deterministic_gas_factor_count{msg_name="coreum.asset.ft.v1.MsgFreeze"} 2
deterministic_gas_factor_sum{msg_name="coreum.asset.ft.v1.MsgGloballyFreeze"} 1.0140000581741333
deterministic_gas_factor_count{msg_name="coreum.asset.ft.v1.MsgGloballyFreeze"} 1
deterministic_gas_factor_sum{msg_name="coreum.asset.ft.v1.MsgGloballyUnfreeze"} 0.9679999947547913
deterministic_gas_factor_count{msg_name="coreum.asset.ft.v1.MsgGloballyUnfreeze"} 1
deterministic_gas_factor_sum{msg_name="coreum.asset.ft.v1.MsgIssue"} 31.326285660266876
deterministic_gas_factor_count{msg_name="coreum.asset.ft.v1.MsgIssue"} 31
deterministic_gas_factor_sum{msg_name="coreum.asset.ft.v1.MsgMint"} 2.8480000346899033
deterministic_gas_factor_count{msg_name="coreum.asset.ft.v1.MsgMint"} 3
deterministic_gas_factor_sum{msg_name="coreum.asset.ft.v1.MsgSetWhitelistedLimit"} 4.038199990987778
deterministic_gas_factor_count{msg_name="coreum.asset.ft.v1.MsgSetWhitelistedLimit"} 4
deterministic_gas_factor_sum{msg_name="coreum.asset.nft.v1.MsgBurn"} 0.9601874947547913
deterministic_gas_factor_count{msg_name="coreum.asset.nft.v1.MsgBurn"} 1
deterministic_gas_factor_sum{msg_name="coreum.asset.nft.v1.MsgIssueClass"} 4.0799999833106995
deterministic_gas_factor_count{msg_name="coreum.asset.nft.v1.MsgIssueClass"} 4
deterministic_gas_factor_sum{msg_name="coreum.asset.nft.v1.MsgMint"} 2.73215389251709
deterministic_gas_factor_count{msg_name="coreum.asset.nft.v1.MsgMint"} 3
deterministic_gas_factor_sum{msg_name="coreum.nft.v1beta1.MsgSend"} 0.9894999861717224
deterministic_gas_factor_count{msg_name="coreum.nft.v1beta1.MsgSend"} 1
deterministic_gas_factor_sum{msg_name="cosmos.authz.v1beta1.MsgExec"} 1.0195599794387817
deterministic_gas_factor_count{msg_name="cosmos.authz.v1beta1.MsgExec"} 1
deterministic_gas_factor_sum{msg_name="cosmos.authz.v1beta1.MsgGrant"} 0.9842857122421265
deterministic_gas_factor_count{msg_name="cosmos.authz.v1beta1.MsgGrant"} 1
deterministic_gas_factor_sum{msg_name="cosmos.authz.v1beta1.MsgRevoke"} 0.9955999851226807
deterministic_gas_factor_count{msg_name="cosmos.authz.v1beta1.MsgRevoke"} 1
deterministic_gas_factor_sum{msg_name="cosmos.bank.v1beta1.MsgMultiSend"} 12.007909506559372
deterministic_gas_factor_count{msg_name="cosmos.bank.v1beta1.MsgMultiSend"} 12
deterministic_gas_factor_sum{msg_name="cosmos.bank.v1beta1.MsgSend"} 1323.2128574848175
deterministic_gas_factor_count{msg_name="cosmos.bank.v1beta1.MsgSend"} 1317
deterministic_gas_factor_sum{msg_name="cosmos.distribution.v1beta1.MsgFundCommunityPool"} 1.0107333660125732
deterministic_gas_factor_count{msg_name="cosmos.distribution.v1beta1.MsgFundCommunityPool"} 1
deterministic_gas_factor_sum{msg_name="cosmos.distribution.v1beta1.MsgSetWithdrawAddress"} 0.8736000061035156
deterministic_gas_factor_count{msg_name="cosmos.distribution.v1beta1.MsgSetWithdrawAddress"} 1
deterministic_gas_factor_sum{msg_name="cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward"} 2.0331538319587708
deterministic_gas_factor_count{msg_name="cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward"} 2
deterministic_gas_factor_sum{msg_name="cosmos.distribution.v1beta1.MsgWithdrawValidatorCommission"} 1.017272710800171
deterministic_gas_factor_count{msg_name="cosmos.distribution.v1beta1.MsgWithdrawValidatorCommission"} 1
deterministic_gas_factor_sum{msg_name="cosmos.feegrant.v1beta1.MsgGrantAllowance"} 0.9912999868392944
deterministic_gas_factor_count{msg_name="cosmos.feegrant.v1beta1.MsgGrantAllowance"} 1
deterministic_gas_factor_sum{msg_name="cosmos.feegrant.v1beta1.MsgRevokeAllowance"} 1.018399953842163
deterministic_gas_factor_count{msg_name="cosmos.feegrant.v1beta1.MsgRevokeAllowance"} 1
deterministic_gas_factor_sum{msg_name="cosmos.gov.v1beta1.MsgDeposit"} 1.0269230604171753
deterministic_gas_factor_count{msg_name="cosmos.gov.v1beta1.MsgDeposit"} 1
deterministic_gas_factor_sum{msg_name="cosmos.gov.v1beta1.MsgSubmitProposal"} 15.022446131333709
deterministic_gas_factor_count{msg_name="cosmos.gov.v1beta1.MsgSubmitProposal"} 15
deterministic_gas_factor_sum{msg_name="cosmos.gov.v1beta1.MsgVote"} 38.90571445226669
deterministic_gas_factor_count{msg_name="cosmos.gov.v1beta1.MsgVote"} 39
deterministic_gas_factor_sum{msg_name="cosmos.gov.v1beta1.MsgVoteWeighted"} 3.1570000648498535
deterministic_gas_factor_count{msg_name="cosmos.gov.v1beta1.MsgVoteWeighted"} 3
deterministic_gas_factor_sum{msg_name="cosmos.staking.v1beta1.MsgBeginRedelegate"} 1.037866234779358
deterministic_gas_factor_count{msg_name="cosmos.staking.v1beta1.MsgBeginRedelegate"} 1
deterministic_gas_factor_sum{msg_name="cosmos.staking.v1beta1.MsgCreateValidator"} 6.065789461135864
deterministic_gas_factor_count{msg_name="cosmos.staking.v1beta1.MsgCreateValidator"} 6
deterministic_gas_factor_sum{msg_name="cosmos.staking.v1beta1.MsgDelegate"} 2.02249276638031
deterministic_gas_factor_count{msg_name="cosmos.staking.v1beta1.MsgDelegate"} 2
deterministic_gas_factor_sum{msg_name="cosmos.staking.v1beta1.MsgEditValidator"} 1.9781538844108582
deterministic_gas_factor_count{msg_name="cosmos.staking.v1beta1.MsgEditValidator"} 2
deterministic_gas_factor_sum{msg_name="cosmos.staking.v1beta1.MsgUndelegate"} 5.145937383174896
deterministic_gas_factor_count{msg_name="cosmos.staking.v1beta1.MsgUndelegate"} 5
deterministic_gas_factor_sum{msg_name="cosmwasm.wasm.v1.MsgClearAdmin"} 2.013230800628662
deterministic_gas_factor_count{msg_name="cosmwasm.wasm.v1.MsgClearAdmin"} 2
deterministic_gas_factor_sum{msg_name="cosmwasm.wasm.v1.MsgUpdateAdmin"} 1.9957499504089355
deterministic_gas_factor_count{msg_name="cosmwasm.wasm.v1.MsgUpdateAdmin"} 2
```

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/352#-NM3yhDR8DGKkPd_KEm8:-NM3yhDR8DGKkPd_KEm9:b-jogun6) (no related file):*
Blocking for myself. 
If we agree with all values I will update our table (or no to be discussed option with table generation)

___
___
*[`pkg/config/deterministic_gas.go` line 54 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/352#-NM3xuOt5xLjphkc1Xp4:-NM3xuOt5xLjphkc1Xp5:b-qlfgc5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/67cbc66cb9a28f30fb42dec46b61d3d765abb11e/pkg/config/deterministic_gas.go#L54)):*
> ```Go
> 		MsgType(&assetfttypes.MsgSetWhitelistedLimit{}): constantGasFunc(5000),
> 
> 		// asset/nft
> ```

I kept these values here as commented to preserve them since they were adjusted 
___
*[`pkg/config/deterministic_gas.go` line 213 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/352#-NM3yZ7t-ZkKGFOmrfwi:-NM3yZ7t-ZkKGFOmrfwj:blvfwv5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/67cbc66cb9a28f30fb42dec46b61d3d765abb11e/pkg/config/deterministic_gas.go#L213)):*
> ```Go
> }
> 
> func bankMultiSendMsgGasFunc(bankMultiSendPerOperationGas uint64) gasByMsgFunc {
> ```

note that I've changed the logic of multisend gas calculation before previous one wansn't precise

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/352)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/deterministic_gas.go` line 54 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/352#-NM3xuOt5xLjphkc1Xp4:-NM4171F8B7sYWQIukps:b32w1t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/67cbc66cb9a28f30fb42dec46b61d3d765abb11e/pkg/config/deterministic_gas.go#L54)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I kept these values here as commented to preserve them since they were adjusted 
</blockquote></details>

Ok

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/352)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/init.go` line 49 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/352#-NM4qjBT4QrQ1U4ZUXeV:-NM4qjBT4QrQ1U4ZUXeW:b-cv7z91) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8375b96e48a34997c04bb28f9f575b994ed4408d/integration-tests/init.go#L49)):*
> ```Go
> 
> 	flag.StringVar(&coredAddress, "cored-address", "tcp://localhost:26657", "Address of cored node started by znet")
> 	flag.StringVar(&fundingMnemonic, "funding-mnemonic", "pitch basic bundle cause toe sound warm love town crucial divorce shell olympic convince scene middle garment glimpse narrow during fix fruit suffer honey", "Funding account mnemonic required by tests")
> ```

here is the cmd args from crust so I use exactly the same. To make it easier to run tests from IDE

```
     - "-test.parallel"
    - "24"
    - "-cored-address"
    - "tcp://localhost:26657"
    - "-log-format"
    - "yaml"
    - "-funding-mnemonic"
    - "pitch basic bundle cause toe sound warm love town crucial divorce shell olympic convince scene middle garment glimpse narrow during fix fruit suffer honey"
    - "-staker-mnemonic"
    - "biology rigid design broccoli adult hood modify tissue swallow arctic option improve quiz cliff inject soup ozone suffer fantasy layer negative eagle leader priority"
    - "-staker-mnemonic"
    - "enemy fix tribe swift alcohol metal salad edge episode dry tired address bless cloth error useful define rough fold swift confirm century wasp acoustic"
    - "-staker-mnemonic"
    - "act electric demand cancel duck invest below once obvious estate interest solution drink mango reason already clean host limit stadium smoke census pattern express
```

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/352)* status: all files reviewed, 5 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/352)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
