### PR TITLE
Generate genesis file from input config file

### PR DESCRIPTION
**Pull request by miladz68**
# Description
This PR adds a CLI command which allows to generate a genesis file from a given input config file. The point of the PR is to remove genesis creation logic from crust, so crust will be less dependent on coreum version, and can create correct genesis by just interacting with the cored binary, and will not need to import genesis template.
# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/747)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/747)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`cmd/cored/cosmoscmd/generate_network.go` line 89 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/747#-NlX8HnG45BQXVvWjm3-:-NlX8HnG45BQXVvWjm30:bnftyy6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f0ef3ae0d30ccf464401de1d94d3d120fb5b470/cmd/cored/cosmoscmd/generate_network.go#L89)):*
> ```Go
> 
> 			if genCfg.Denom != "" {
> 				sdk.DefaultBondDenom = genCfg.Denom
> ```

why is it needed?
___
*[`cmd/cored/cosmoscmd/generate_network.go` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/747#-NlX8qAtDzaEGSdGlLxu:-NlX8qAtDzaEGSdGlLxv:br33p6r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f0ef3ae0d30ccf464401de1d94d3d120fb5b470/cmd/cored/cosmoscmd/generate_network.go#L132)):*
> ```Go
> 	customparamsGenesis := customparamstypes.DefaultGenesisState()
> 	if !cfg.CustomParamsConfig.MinSelfDelegation.IsNil() &&
> 		cfg.CustomParamsConfig.MinSelfDelegation.IsPositive() {
> ```

shouldn't it return error if it's not positive?
___
*[`cmd/cored/cosmoscmd/generate_network.go` line 139 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/747#-NlX8zhrAb_q0he32hjd:-NlX8zhrAb_q0he32hje:b4gnres) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f0ef3ae0d30ccf464401de1d94d3d120fb5b470/cmd/cored/cosmoscmd/generate_network.go#L139)):*
> ```Go
> 	// assetft params
> 	assetftGenesis := assetfttypes.DefaultGenesis()
> 	assetftGenesis.Params.IssueFee.Amount = sdk.NewInt(10_000_000)
> ```

Here and below: shouldn't all the numbers be taken from config file?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/747)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`cmd/cored/cosmoscmd/generate_network.go` line 139 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/747#-NlX8zhrAb_q0he32hjd:-NlXnYzE7TS3Z56DJpk4:bu4i7v1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f0ef3ae0d30ccf464401de1d94d3d120fb5b470/cmd/cored/cosmoscmd/generate_network.go#L139)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Here and below: shouldn't all the numbers be taken from config file?
</blockquote></details>

Same question.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/747)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`cmd/cored/cosmoscmd/generate_network.go` line 89 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/747#-NlX8HnG45BQXVvWjm3-:-NlbdarD1kUgy0d0-vTs:b-sited5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f0ef3ae0d30ccf464401de1d94d3d120fb5b470/cmd/cored/cosmoscmd/generate_network.go#L89)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why is it needed?
</blockquote></details>

All modules read the bond denom from this variable, when creating the default genesis.
___
*[`cmd/cored/cosmoscmd/generate_network.go` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/747#-NlX8qAtDzaEGSdGlLxu:-NlbeZZkEVc19Qyy5kLB:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f0ef3ae0d30ccf464401de1d94d3d120fb5b470/cmd/cored/cosmoscmd/generate_network.go#L132)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

shouldn't it return error if it's not positive?
</blockquote></details>

Done.
___
*[`cmd/cored/cosmoscmd/generate_network.go` line 139 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/747#-NlX8zhrAb_q0he32hjd:-NlbeaFFCNfsvOqtTS2C:bnrumox) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6f0ef3ae0d30ccf464401de1d94d3d120fb5b470/cmd/cored/cosmoscmd/generate_network.go#L139)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Same question.
</blockquote></details>

if all config is taken from the file, then we have the same situation that crust must know all the config of all the modules and actively manage it. 
the point is that crust should know as little as possible.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/747)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/747)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/747)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
