### PR TITLE
Added SendAuthorization for sending specific NFTs.

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/678)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/678)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/modules/assetnft_test.go` line 1899 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-Nh6cyWnBDN9nGRZYQkM:-Nh6cyWnBDN9nGRZYQkN:b-w6mhco) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d7fa4fcb471c300f962d421b120d7f0849f6dbc2/integration-tests/modules/assetnft_test.go#L1899)):*
> ```Go
> 	requireT.ElementsMatch([]assetnfttypes.NFTIdentifier{
> 		{ClassId: classID, Id: nftID},
> 		{ClassId: classID, Id: "not-minted-yet"},
> ```

so we are able to provide grant even before an NFT is minted ?
I guess we are not able to validate this right ?
___
*[`integration-tests/modules/assetnft_test.go` line 1925 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-Nh6csLkETRdTQUHQ5zP:-Nh6csLkETRdTQUHQ5zQ:bgx4wpa) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d7fa4fcb471c300f962d421b120d7f0849f6dbc2/integration-tests/modules/assetnft_test.go#L1925)):*
> ```Go
> 	})
> 	requireT.NoError(err)
> 	requireT.Equal(1, len(gransRes.Grants))
> ```

do you mean that we remove NFT ID from the list once it is send for a first time ?

I'm not sure it is logical lets discuss
___
*[`proto/coreum/asset/nft/v1/authz.proto` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-Nh6dct50wBcprj8m7l9:-Nh6dct50wBcprj8m7lA:bal6x5m) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d7fa4fcb471c300f962d421b120d7f0849f6dbc2/proto/coreum/asset/nft/v1/authz.proto#L20)):*
> ```proto
> }
> 
> message NFTIdentifier {
> ```

nit: we usually use ID or Id in our code-base but have never seen Identifier
Is there a specific reason to name it like this ?
I guess to differentiate from `string id = 2;` ?

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/678)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/modules/assetnft_test.go` line 1815 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-Nh6gryg5fkwJKp_TkAd:-Nh6gryg5fkwJKp_TkAe:b35y252) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d7fa4fcb471c300f962d421b120d7f0849f6dbc2/integration-tests/modules/assetnft_test.go#L1815)):*
> ```Go
> 	chain.FundAccountWithOptions(ctx, t, grantee, integration.BalancesOptions{
> 		Messages: []sdk.Msg{
> 			&nft.MsgSend{},
> ```

I' wondering how this amount of gas is enough here 
Because autzh.Exec adds overhead.
it means that extra gas is required if you execute nft.MsgSend inside auth.Exec

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/678)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/678)* status: all files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 1815 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-Nh6gryg5fkwJKp_TkAd:-Nh72G5t7HC_wsS6fpcZ:bzje0w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d7fa4fcb471c300f962d421b120d7f0849f6dbc2/integration-tests/modules/assetnft_test.go#L1815)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I' wondering how this amount of gas is enough here 
Because autzh.Exec adds overhead.
it means that extra gas is required if you execute nft.MsgSend inside auth.Exec
</blockquote></details>

you are right that it is not enough, I only need some funds to register the account so authz will work. I later the account with the exact message. I will refactor it to have 1udevcore
___
*[`integration-tests/modules/assetnft_test.go` line 1899 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-Nh6cyWnBDN9nGRZYQkM:-NhB-zH-5jY4WZ0ORgVb:b-avwyso) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d7fa4fcb471c300f962d421b120d7f0849f6dbc2/integration-tests/modules/assetnft_test.go#L1899)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so we are able to provide grant even before an NFT is minted ?
I guess we are not able to validate this right ?
</blockquote></details>

that is correct, there is no way to verify it, and that's how it works for FTs as well. that I can grant you coin, even if the coin does not exist. 
___
*[`integration-tests/modules/assetnft_test.go` line 1925 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-Nh6csLkETRdTQUHQ5zP:-NhB0EtK7oNTZq_fvq5Z:bb8ksp3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d7fa4fcb471c300f962d421b120d7f0849f6dbc2/integration-tests/modules/assetnft_test.go#L1925)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do you mean that we remove NFT ID from the list once it is send for a first time ?

I'm not sure it is logical lets discuss
</blockquote></details>

discussed and it is logical to do this. 
___
*[`proto/coreum/asset/nft/v1/authz.proto` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-Nh6dct50wBcprj8m7l9:-NhB0Lxj8R63yJ_zfQMl:b-sqlp55) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d7fa4fcb471c300f962d421b120d7f0849f6dbc2/proto/coreum/asset/nft/v1/authz.proto#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: we usually use ID or Id in our code-base but have never seen Identifier
Is there a specific reason to name it like this ?
I guess to differentiate from `string id = 2;` ?
</blockquote></details>

well we use nftID for the id of the nft, but this type is the combination of classID-nftID. I know the name is not good, but I am out of ideas on this one.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/678)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 1928 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-NhBkFjQBfLG4heUjlFq:-NhBkFjQBfLG4heUjlFr:b-2bqf49) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3adc55b2fc69c7478ffdd49a94c94190faf72205/integration-tests/modules/assetnft_test.go#L1928)):*
> ```Go
> 	requireT.ElementsMatch([]assetnfttypes.NFTIdentifier{
> 		{ClassId: classID, Id: "not-minted-yet"},
> 	}, updatedGrant.Nfts)
> ```

missing test case: overwriting the existing list of nfts (both with new list and empty one)
___
*[`proto/coreum/asset/nft/v1/authz.proto` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-Nh6dct50wBcprj8m7l9:-NhBiOPh6I7dbhDzU0DT:bosfio5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d7fa4fcb471c300f962d421b120d7f0849f6dbc2/proto/coreum/asset/nft/v1/authz.proto#L20)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

well we use nftID for the id of the nft, but this type is the combination of classID-nftID. I know the name is not good, but I am out of ideas on this one.
</blockquote></details>

Maybe NFTFingerprint :D
___
*[`x/asset/nft/types/send_authorization.go` line 13 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-NhBj-eKEa24zraDiO_3:-NhBj-eKEa24zraDiO_4:b4kig8x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3adc55b2fc69c7478ffdd49a94c94190faf72205/x/asset/nft/types/send_authorization.go#L13)):*
> ```Go
> 
> // NewSendAuthorization returns a new SendAuthorization object.
> func NewSendAuthorization(nfts []NFTIdentifier) *SendAuthorization {
> ```

What if someone creates an authorization with empty list of nfts. According to the implementation, that authorization will be stored and never removed (until overriden), right?
On the other hand we must store it because otherwise it is not possible to cancel previously-created auth, right?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/678)* status: all files reviewed, 6 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 1928 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-NhBkFjQBfLG4heUjlFq:-NhQJGQD0NueupXgxfPP:b-j726bq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3adc55b2fc69c7478ffdd49a94c94190faf72205/integration-tests/modules/assetnft_test.go#L1928)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

missing test case: overwriting the existing list of nfts (both with new list and empty one)
</blockquote></details>

that test is not part of the code that we write, but part of the authz module behavoir. I decided not to test it, since there is no way to modify that behavior with our code. 
___
*[`x/asset/nft/types/send_authorization.go` line 13 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-NhBj-eKEa24zraDiO_3:-NhQIN7ZE-CthoFLF_Hr:b9z8lvl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3adc55b2fc69c7478ffdd49a94c94190faf72205/x/asset/nft/types/send_authorization.go#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What if someone creates an authorization with empty list of nfts. According to the implementation, that authorization will be stored and never removed (until overriden), right?
On the other hand we must store it because otherwise it is not possible to cancel previously-created auth, right?
</blockquote></details>

good point, added to the validate basic method.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/678)* status: all files reviewed, 6 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`proto/coreum/asset/nft/v1/authz.proto` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-Nh6dct50wBcprj8m7l9:-NhQJaxE9TN1435ng1fP:b-vyunrc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d7fa4fcb471c300f962d421b120d7f0849f6dbc2/proto/coreum/asset/nft/v1/authz.proto#L20)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Maybe NFTFingerprint :D
</blockquote></details>

I think NFT Identifier is good enough.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/678)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`proto/coreum/asset/nft/v1/authz.proto` line 21 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-NhVnNT18mJRBK9C1Fvw:-NhVnNT18mJRBK9C1Fvx:bimgcvq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5dbeac6dc96bc311484f85b6b91decf44978d51f/proto/coreum/asset/nft/v1/authz.proto#L21)):*
> ```proto
> 
> message NFTIdentifier {
>   // class_id defines the unique identifier of the nft classification, similar to the contract address of ERC721
> ```

Not sure that we need that reference here `similar to the contract address of ERC721`.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/678)* status: all files reviewed, 3 unresolved discussions (waiting on @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/678)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68)

___
*[`integration-tests/modules/assetnft_test.go` line 1815 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/678#-Nh6gryg5fkwJKp_TkAd:-NhaK5Gu7suXDw2jb0ot:b5xtxmy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d7fa4fcb471c300f962d421b120d7f0849f6dbc2/integration-tests/modules/assetnft_test.go#L1815)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you are right that it is not enough, I only need some funds to register the account so authz will work. I later the account with the exact message. I will refactor it to have 1udevcore
</blockquote></details>

nit: I see
Lets just add comment why we need 1 here maybe ?

**Pull request merged**
