### PR TITLE
Integrate asset FT extensions with the DEX.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Integrate asset FT extensions with the DEX.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1029)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1, 4 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1029)* status: 5 of 16 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/1029#-OCIBZyy-8dDZzM-QnQI:-OCIBZyz8WrVE2KgqqNP:b-dx4dej) (no related file):*
you should run `cargo fmt` in the root of the project. some of the style changes that you editor has applied are not default rust style. 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 282 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/1029#-OCILVSuCkcfGQUKxDC8:-OCILVSuCkcfGQUKxDC9:btti38k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/107cb872b3a50d5ba1e69109c4371850cc520270/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L282)):*
> ```XML
> 
>     let bank_balance = query_bank_balance(deps, account, &token.denom)?;
>     let whitelisted_balance = query_whitelisted_balance(deps, account, &token.denom)?;
> ```

we should account for expected to receieve when calculating whitelisting, to showcase how full integration looks likes.
___
*[`x/asset/ft/keeper/keeper_dex.go` line 105 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/1029#-OCIeaLG-r7EB9rWHcr0:-OCIeaLG-r7EB9rWHcr1:b188cbr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/107cb872b3a50d5ba1e69109c4371850cc520270/x/asset/ft/keeper/keeper_dex.go#L105)):*
> ```Go
> 	expectedToSpend, expectedToReceive sdk.Coin,
> ) error {
> 	if err := k.dexCheckExpectedToSpend(ctx, order, expectedToSpend, expectedToReceive); err != nil {
> ```

I might be a little confused, but I am not seeing where the whitelisting limits are enforced.

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 8 of 16 files at r1, 6 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1029)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/ft/keeper/keeper_dex_test.go` line 1067 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1029#-OCXuzxl5_U0HhIvp9__:-OCXuzxl5_U0HhIvp9_a:b-7ilvfu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/37bcc418a3f9f6c8bf1bc05c344a42fb48cb044c/x/asset/ft/keeper/keeper_dex_test.go#L1067)):*
> ```Go
> 	testApp.MintAndSendCoin(t, ctx, acc, sdk.NewCoins(coinWithoutExtension))
> 
> 	// the extension controls all features, bot to locked, amount
> ```

typo?
___
*[`x/asset/ft/keeper/keeper_dex_test.go` line 1119 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1029#-OCXwMUz9RZ_BjgUz2Sd:-OCXwMUz9RZ_BjgUz2Se:b-5akzua) ([raw file](https://github.com/CoreumFoundation/coreum/blob/37bcc418a3f9f6c8bf1bc05c344a42fb48cb044c/x/asset/ft/keeper/keeper_dex_test.go#L1119)):*
> ```Go
> 	)
> 
> 	coinWithExtensionProhibitedToReceive := sdk.NewCoin(extensionDenom, sdkmath.NewInt(104))
> ```

Please define these magic numbers as a constant just like `integration-tests/modules/assetft_extension_test.go`
___
*[`x/asset/ft/keeper/keeper_dex.go` line 407 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/1029#-OCXk7Is4xMSmxEXhKrS:-OCXk7Is4xMSmxEXhKrT:bigx2kz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/37bcc418a3f9f6c8bf1bc05c344a42fb48cb044c/x/asset/ft/keeper/keeper_dex.go#L407)):*
> ```Go
> 	}
> 
> 	if spendDef.IsFeatureEnabled(types.Feature_extension) {
> ```

Should we just check if extension is enabled? I believe it's better to change such conditions to check if they implemented that entry point (`extension_place_order` in this case). I'm not sure if we can check for that or not, but I believe it's the better implementation

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 16 files at r1, 2 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1029)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`x/asset/ft/keeper/keeper_dex.go` line 105 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/1029#-OCIeaLG-r7EB9rWHcr0:-OCYFbR29KBQfYXZJcYI:b-oq70tp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/107cb872b3a50d5ba1e69109c4371850cc520270/x/asset/ft/keeper/keeper_dex.go#L105)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

In `dexCheckExpectedToReceive`
</blockquote></details>

I am not sure about whitelisting edge cases. let's discuss in a call. 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 282 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/1029#-OCILVSuCkcfGQUKxDC8:-OCYG51e1lilbPIBEp9P:b-k65mh8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/107cb872b3a50d5ba1e69109c4371850cc520270/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L282)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You can query it with the asset FT, `Balance` query.
</blockquote></details>

I mean that we should do this in our integration tests as a showcase.

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1029)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1029)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1029)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1029)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1029)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1029)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
