### PR TITLE
Fix unit tests and linters after the migration to cosmos sdk v0.47.1

### PR DESCRIPTION
**Pull request by dzmitryhil**
* Fix unit tests
* Replace "github.com/cosmos/cosmos-sdk/types/errors" to "cosmossdk.io/errors"
* Replace "github.com/cosmos/cosmos-sdk/types".Int to "cosmossdk.io/math".Int

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/467)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 114 of 114 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/467)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`.github/workflows/ci.yml` line 36 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIo4b_EFIyFVo5G48r:-NTIo4ba57IjW7i_37KC:b-ngac12) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/.github/workflows/ci.yml#L36)):*
> ```YAML
>             docker-cache: true
>           - ci_step: "integration tests coreum-modules"
>             command: "crust build/integration-tests" # FIXME restore once we fix it
> ```

Tests should not be blocked for all the PRs just because they fail in `v0.47-migration`.
Another approach should be taken:
- configure `v0.47-migration` branch as a protected one, like ``master`
- define different CI action for that branch
___
*[`integration-tests/modules/assetft_test.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIpwAc5e98li9fbT8J:-NTIpwAd3nAh1x3HnZxK:b-39z76e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/integration-tests/modules/assetft_test.go#L13)):*
> ```Go
> 	tmjson "github.com/cometbft/cometbft/libs/json"
> 	sdk "github.com/cosmos/cosmos-sdk/types"
> 	cosmoserrors "github.com/cosmos/cosmos-sdk/types/errors"
> ```

why not `sdkerrors`? we use `sdk` and `sdkmath` so `sdkerrors` seem to be a natural choice
___
*[`integration-tests/modules/wasm_test.go` line 452 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIqY1k0r2GiLeDAXph:-NTIqY1k0r2GiLeDAXpi:b-g33pjg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/integration-tests/modules/wasm_test.go#L452)):*
> ```Go
> 
> 	// pin smart contract
> 	proposalMsg, err := chain.Governance.NewMsgSubmitProposal(ctx, proposer, &wasmtypes.PinCodesProposal{ //nolint:staticcheck // we need to keep backward compatibility
> ```

what's the problem here?
___
*[`testutil/cli/tx.go` line 15 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIqtjh1qZTTXLaMpI9:-NTIqtji5hzX9l39KcMd:bsgbuwz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/testutil/cli/tx.go#L15)):*
> ```Go
> 
> // ExecTxCmdAndWaitNextBlock is a func to execute tx cmd.
> func ExecTxCmdAndWaitNextBlock(clientCtx client.Context, testNetwork *network.Network, cmd *cobra.Command, extraArgs []string) (sdk.TxResponse, error) {
> ```

Where is the "AndWaitNextBlock" part implemented?
___
*[`testutil/network/network.go` line 131 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIrKUb7Cv0Gxr6Fmf7:-NTIrKUb7Cv0Gxr6Fmf8:b-4ji5ei) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/testutil/network/network.go#L131)):*
> ```Go
> 
> 	encoding := config.NewEncodingConfig(app.ModuleBasics)
> 	chainID := "chain-" + tmrand.NewRand().Str(6)
> ```

Can't we use `SimAppChainID` constant?
___
*[`x/deterministicgas/config.go` line 95 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIskvS7NTdqqpZRzV2:-NTIskvS7NTdqqpZRzV3:b-wu4ksy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/x/deterministicgas/config.go#L95)):*
> ```Go
> 		// gov
> 		// FIXME(v47-deterministic): check that if we want to support both go types
> 		MsgType(&govtypesv1beta1.MsgVote{}):         constantGasFunc(7000),
> ```

Are you sure that we should integrate both v1 and v1beta1? It seems weird. Also usually v1 is a newer (final) version than v1-beta1. So I don't understand this relation here.
___
*[`x/deterministicgas/config.go` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIt8IOAY-olo4y1oc2:-NTIt8IOAY-olo4y1oc3:beq2mpt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/x/deterministicgas/config.go#L128)):*
> ```Go
> 		&cfg,
> 		[]sdk.Msg{
> 			// auth
> ```

Are those new messages nondeterministic by their nature or we just haven't checked them yet? If they need to be understood, please leave a TODO.
___
*[`x/deterministicgas/config.go` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTItZ9f6rUdzdvaNXis:-NTItZ9f6rUdzdvaNXit:b-1s4xqh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/x/deterministicgas/config.go#L128)):*
> ```Go
> 		&cfg,
> 		[]sdk.Msg{
> 			// auth
> ```

Do we want to write tests for all the new messages?
___
*[`x/wbank/module_test.go` line 52 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIuM-QA9oxeCoBDO63:-NTIuM-R8_e-WVWnbErh:bom9wya) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/x/wbank/module_test.go#L52)):*
> ```Go
> // Since we override the "Register Services" we want to be sure that the after the update of the SDK,
> // The original bank won't have unexpected migrations.
> func TestAppModuleOriginalBak_RegisterServices(t *testing.T) {
> ```

Bak -> Bank

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/467)* status: all files reviewed, 9 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 36 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIo4b_EFIyFVo5G48r:-NTO8Y_S-G-kGkWg_IuZ:bsxwig3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/.github/workflows/ci.yml#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Tests should not be blocked for all the PRs just because they fail in `v0.47-migration`.
Another approach should be taken:
- configure `v0.47-migration` branch as a protected one, like ``master`
- define different CI action for that branch
</blockquote></details>

They a blocked since they are broken. We will restore them, once we fix all of them.
___
*[`integration-tests/modules/assetft_test.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIpwAc5e98li9fbT8J:-NTO8ftN3pynEsFmGGKk:b-tdi2ol) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/integration-tests/modules/assetft_test.go#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why not `sdkerrors`? we use `sdk` and `sdkmath` so `sdkerrors` seem to be a natural choice
</blockquote></details>

The `sdkerrors` we use for `cosmossdk.io/errors`  and `cosmoserrors` for  `github.com/cosmos/cosmos-sdk/types/errors`, we need both since they are different. 
___
*[`integration-tests/modules/wasm_test.go` line 452 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIqY1k0r2GiLeDAXph:-NTO8soFEjX3ejcVuJDi:b-r7tgo0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/integration-tests/modules/wasm_test.go#L452)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what's the problem here?
</blockquote></details>

Deprecated code - linter.
___
*[`testutil/cli/tx.go` line 15 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIqtjh1qZTTXLaMpI9:-NTO9Lv87QaRBD0v3MPc:b-zgeaex) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/testutil/cli/tx.go#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Where is the "AndWaitNextBlock" part implemented?
</blockquote></details>

It was initially there, then I found that we don't need it. Updated the name.



_Code quote:_
```Go
ExecTxCmdAndWaitNextBlock(clientCtx client.Context, testNet
```

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/467)* status: all files reviewed, 9 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`testutil/network/network.go` line 131 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIrKUb7Cv0Gxr6Fmf7:-NTO9tOU1KoZMiclKQ6A:b-q49ja9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/testutil/network/network.go#L131)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Can't we use `SimAppChainID` constant?
</blockquote></details>

We should try to remove that constant later, that's why I don't use it.
___
*[`x/deterministicgas/config.go` line 95 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIskvS7NTdqqpZRzV2:-NTOA-Zl7sPC14ekRSXy:b-dj9k27) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/x/deterministicgas/config.go#L95)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Are you sure that we should integrate both v1 and v1beta1? It seems weird. Also usually v1 is a newer (final) version than v1-beta1. So I don't understand this relation here.
</blockquote></details>

For now - yes. Since we need it at least to pass our integration tests before we refactor them fully.
___
*[`x/deterministicgas/config.go` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIt8IOAY-olo4y1oc2:-NTOAA8VDhjW9SW_V5nL:bh51jn9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/x/deterministicgas/config.go#L128)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Are those new messages nondeterministic by their nature or we just haven't checked them yet? If they need to be understood, please leave a TODO.
</blockquote></details>

We already have that task, they are nondeterministic since they are the part of the new way of the gov.
___
*[`x/deterministicgas/config.go` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTItZ9f6rUdzdvaNXis:-NTOAHpRECsfp6aRmt9C:b2r6lfz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/x/deterministicgas/config.go#L128)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do we want to write tests for all the new messages?
</blockquote></details>

No sure, they are not new, just new way of gov, we didn't have tests for them before.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/467)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`.github/workflows/ci.yml` line 36 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIo4b_EFIyFVo5G48r:-NTOCtUh-TPEZi88Gbep:bxta88r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/.github/workflows/ci.yml#L36)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

They a blocked since they are broken. We will restore them, once we fix all of them.
</blockquote></details>

Ah, ok. This branch targets `v0.47-migration`, not `'master`. But then, why do you block it in the CI? Who cares that CI in `v0.47-migration` is broken? It is actually a good thing because it means that nobody merges it accidentally before fixing all the issues.
___
*[`integration-tests/modules/assetft_test.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIpwAc5e98li9fbT8J:-NTODbq68ylNOwn-viux:bp50jp7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/integration-tests/modules/assetft_test.go#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The `sdkerrors` we use for `cosmossdk.io/errors`  and `cosmoserrors` for  `github.com/cosmos/cosmos-sdk/types/errors`, we need both since they are different. 
</blockquote></details>

So they didn't fully migrate errors to `cosmossdk.io/errors`?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/467)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 36 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIo4b_EFIyFVo5G48r:-NTT441b2aZjPdp26p3G:b-iisz1o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/.github/workflows/ci.yml#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ah, ok. This branch targets `v0.47-migration`, not `'master`. But then, why do you block it in the CI? Who cares that CI in `v0.47-migration` is broken? It is actually a good thing because it means that nobody merges it accidentally before fixing all the issues.
</blockquote></details>

The CI will be included once we merge the `v0.47-migration` so it will behave the same as master, it meath you won't be able to merge until tests pass. 
___
*[`integration-tests/modules/assetft_test.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIpwAc5e98li9fbT8J:-NTT4igxDH7T01AmsiFl:bi64h68) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/integration-tests/modules/assetft_test.go#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

So they didn't fully migrate errors to `cosmossdk.io/errors`?
</blockquote></details>

Kind of, they migrate wrapper to the `cosmossdk.io/errors`. 
___
*[`x/wbank/module_test.go` line 52 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIuM-QA9oxeCoBDO63:-NTT4xqtAq9N4K63vcWN:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/x/wbank/module_test.go#L52)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Bak -> Bank
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/467)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`.github/workflows/ci.yml` line 36 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIo4b_EFIyFVo5G48r:-NTYi8c4E6_uGkc197jK:bjcozn0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/.github/workflows/ci.yml#L36)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The CI will be included once we merge the `v0.47-migration` so it will behave the same as master, it meath you won't be able to merge until tests pass. 
</blockquote></details>

I understand. I just don't get why you want to remove it here.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/467)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 36 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NTIo4b_EFIyFVo5G48r:-NTn37JU3oTu31oC7QoZ:bzhmohu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f077cd2c4043947bd76cb3c7200cb87020184408/.github/workflows/ci.yml#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I understand. I just don't get why you want to remove it here.
</blockquote></details>

But what was the option? If the integration tests don't work, we shouldn't include them in the CI.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/467)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 89 of 114 files at r1, 6 of 6 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 20 of 20 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/467)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`app/app.go` line 982 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU69ONF4e2YwZYGyeOi:-NU69ONF4e2YwZYGyeOj:b-i77azi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2deebbefd169da2332288184b2dece22c66fecc2/app/app.go#L982)):*
> ```Go
> 
> // BlockedAddresses returns all the app's blocked account addresses.
> func BlockedAddresses() map[string]bool {
> ```

what does `blocked addresses` mean ?
___
*[`app/export.go` line 37 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU69clBC2iZu6_NNzAD:-NU69clBC2iZu6_NNzAE:bja1qqc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2a3d34d07628ffcb46c499c09e1871775de22555/app/export.go#L37)):*
> ```Go
> 
> 	validators, err := staking.WriteValidators(ctx, app.StakingKeeper)
> 	if err != nil {
> ```

I see that we always return error here but IMO previous behaviour was more correct. 
I mean to return empty object in case of error
___
*[`app/export.go` line 79 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU69mat8Qt4Ygp3N1GS:-NU69mat8Qt4Ygp3N1GT:b-hnvq0g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2a3d34d07628ffcb46c499c09e1871775de22555/app/export.go#L79)):*
> ```Go
> 		_, err := app.DistrKeeper.WithdrawValidatorCommission(ctx, val.GetOperator())
> 		if err != nil {
> 			panic(err)
> ```

why is this error ignored ?
___
*[`integration-tests/modules/assetft_test.go` line 10 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU6ATaiCcLFHqbIwiy2:-NU6ATaiCcLFHqbIwiy3:b-vlra56) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2deebbefd169da2332288184b2dece22c66fecc2/integration-tests/modules/assetft_test.go#L10)):*
> ```Go
> 	"time"
> 
> 	sdkmath "cosmossdk.io/math"
> ```

is sdkmath is default value for this package used by cosmos ?
IMO cosmosmath (same logic as `cosmoserrors`) is a bit better but if sdkmath is used everywhere then lets keep it
___
*[`testutil/simapp/account.go` line 24 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU6Byld83tLJpMuuhkV:-NU6Byld83tLJpMuuhkW:b-4ld6vl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2deebbefd169da2332288184b2dece22c66fecc2/testutil/simapp/account.go#L24)):*
> ```Go
> }
> 
> func addTestAddrs(s *App, ctx sdk.Context, accNum int, accAmt sdkmath.Int, strategy GenerateAccountStrategy) []sdk.AccAddress {
> ```

minor: why renamed to `s` ?
___
*[`testutil/simapp/simapp.go` line 85 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU6CZnf0EG6wl_M01u4:-NU6CZnf0EG6wl_M01u5:b4kiiui) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2deebbefd169da2332288184b2dece22c66fecc2/testutil/simapp/simapp.go#L85)):*
> ```Go
> 	)
> 	if err != nil {
> 		panic(fmt.Sprintf("can't generate genesis state with valet, err: %s", err))
> ```

`valet` ?



_Code quote:_
```Go
valet
```
___
*[`x/asset/ft/module.go` line 126 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU6CoAbEz45AB45_29V:-NU6CoAbEz45AB45_29W:b-umzxfl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2deebbefd169da2332288184b2dece22c66fecc2/x/asset/ft/module.go#L126)):*
> ```Go
> /* func (am AppModule) Route() sdk.Route {
> 	return sdk.Route{}
> } *?
> ```

`*/` ?
___
*[`x/asset/ft/keeper/keeper_test.go` line 14 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU6ICyF9OZHj3W6i_TO:-NU6ICyF9OZHj3W6i_TP:btp298m) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2deebbefd169da2332288184b2dece22c66fecc2/x/asset/ft/keeper/keeper_test.go#L14)):*
> ```Go
> 	"github.com/cosmos/cosmos-sdk/crypto/keys/secp256k1"
> 	sdk "github.com/cosmos/cosmos-sdk/types"
> 	cosmoserrors "github.com/cosmos/cosmos-sdk/types/errors"
> ```

what is the difference between sdkerrors  & cosmoserrors ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/467)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`app/app.go` line 982 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU69ONF4e2YwZYGyeOi:-NU6oqeK8XlC-y9U769h:b-oigbd4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2deebbefd169da2332288184b2dece22c66fecc2/app/app.go#L982)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what does `blocked addresses` mean ?
</blockquote></details>

we don't use them, removed. In general, the addresses blocked by the bank. 



_Code quote:_
```Go
 BlockedAddresses() map[string]bool {
```
___
*[`app/export.go` line 37 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU69clBC2iZu6_NNzAD:-NU6pCC18F_d_8EJOzRy:b-cnop9f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2a3d34d07628ffcb46c499c09e1871775de22555/app/export.go#L37)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I see that we always return error here but IMO previous behaviour was more correct. 
I mean to return empty object in case of error
</blockquote></details>

That's the coped code from the SDK, but agree restored.
___
*[`app/export.go` line 79 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU69mat8Qt4Ygp3N1GS:-NU6pH8v4fL_7VqWz_6m:b-cnop9f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2a3d34d07628ffcb46c499c09e1871775de22555/app/export.go#L79)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

why is this error ignored ?
</blockquote></details>

That's the coped code from the SDK, but agree restored.
___
*[`integration-tests/modules/assetft_test.go` line 10 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU6ATaiCcLFHqbIwiy2:-NU6pJHd2MTrpP8zRhgN:b-2afjwk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2deebbefd169da2332288184b2dece22c66fecc2/integration-tests/modules/assetft_test.go#L10)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is sdkmath is default value for this package used by cosmos ?
IMO cosmosmath (same logic as `cosmoserrors`) is a bit better but if sdkmath is used everywhere then lets keep it
</blockquote></details>

Yes, that's a new standard, in some modules they still use the legacy import but they marked as legacy and will be removed. So that's the only option to use the cosmoserrors and cosmossdk.io/math.
___
*[`testutil/simapp/account.go` line 24 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU6Byld83tLJpMuuhkV:-NU6qJl0BoG_kuzAZAaI:b93o0hp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2deebbefd169da2332288184b2dece22c66fecc2/testutil/simapp/account.go#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: why renamed to `s` ?
</blockquote></details>

Because multiple addresses.



_Code quote:_
```Go
addTestAddrs(s *App, ctx sdk.Context,
```
___
*[`testutil/simapp/simapp.go` line 85 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU6CZnf0EG6wl_M01u4:-NU6qQFT6Hn6kDqj-9pD:bt2vr1b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2deebbefd169da2332288184b2dece22c66fecc2/testutil/simapp/simapp.go#L85)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`valet` ?
</blockquote></details>

Fixed.



_Code quote:_
```Go
	panic(fmt.Sprintf("can't generate genesis state with v
```
___
*[`x/asset/ft/module.go` line 126 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU6CoAbEz45AB45_29V:-NU6qXO78Fkf675riJiA:bkgbusj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2deebbefd169da2332288184b2dece22c66fecc2/x/asset/ft/module.go#L126)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`*/` ?
</blockquote></details>

Typo, removed



_Code quote:_
```Go
} *?
```
___
*[`x/asset/ft/keeper/keeper_test.go` line 14 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/467#-NU6ICyF9OZHj3W6i_TO:-NU6qZleCPfEhH039di7:baze9jf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2deebbefd169da2332288184b2dece22c66fecc2/x/asset/ft/keeper/keeper_test.go#L14)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what is the difference between sdkerrors  & cosmoserrors ?
</blockquote></details>

sdkerrors - wrappers for errors
cosmoserrors - errors with some logic (Unauthorized and so on...)

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/467)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Pull request merged**
