### PR TITLE
Implemented IBC in asset extension

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/841)

### CODE REVIEW

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/841)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 101 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/841#-Ny55raF2cLDqcJMDOoe:-Ny55raG3zrTqPMYIITC:bs73opo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/075b6fbbad936904bb5165af721138dc7d4e02ee/x/asset/ft/keeper/before_send.go#L101)):*
> ```Go
> 			// back to the sender by the IBC transfer module.
> 			// It should succeed even if the issuer decided, for whatever reason, to freeze the escrow address.
> 			// It is done before cehcking for global freeze because refunding should not be blocked by this.
> ```

typo. `cehcking` -> `checking`
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 144 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/841#-Ny57MWLAzghnyqac8SX:-Ny57MWLAzghnyqac8SY:bi565td) ([raw file](https://github.com/CoreumFoundation/coreum/blob/075b6fbbad936904bb5165af721138dc7d4e02ee/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L144)):*
> ```XML
>     }
> 
>     // Ignore freezing if the transfer is an IBC transfer in. In case of IBC transfer comint into the chain
> ```

type. `comint` -> `coming`
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 268 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/841#-Ny57wmM-HoAE5aBLs12:-Ny57wmM-HoAE5aBLs13:byzduhs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/075b6fbbad936904bb5165af721138dc7d4e02ee/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L268)):*
> ```XML
>     features: &Vec<u32>,
> ) -> Result<(), ContractError> {
>     if recipient.to_string() == token.issuer
> ```

Why `issuer` and not `admin`?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/841)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 103 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/841#-Ny5888R-7KNRr5cBSs1:-Ny5888R-7KNRr5cBSs2:b4za0m2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/075b6fbbad936904bb5165af721138dc7d4e02ee/x/asset/ft/keeper/before_send.go#L103)):*
> ```Go
> 			// It is done before cehcking for global freeze because refunding should not be blocked by this.
> 			// Otherwise, funds would be lost forever, being blocked on the escrow account.
> 			if wibctransfertypes.IsPurposeAck(ctx) || wibctransfertypes.IsPurposeTimeout(ctx) {
> ```

RThis thing is done inside `isCoinReceivable`. Why is it copied here?

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/841)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/ibc/asset_extension_ft_test.go` line 37 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/841#-Ny58UI68DqXDxIrjjjy:-Ny58UI68DqXDxIrjjjz:bqrdtmk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/075b6fbbad936904bb5165af721138dc7d4e02ee/integration-tests/ibc/asset_extension_ft_test.go#L37)):*
> ```Go
> 	ctx, chains := integrationtests.NewChainsTestingContext(t)
> 	coreumChain := chains.Coreum
> 	coreumIssuer := coreumChain.GenAccount()
> ```

Let's use `admin` instead
___
*[`integration-tests/ibc/asset_extension_ft_test.go` line 99 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/841#-Ny58wxG6VrCJHCBuO52:-Ny58wxG6VrCJHCBuO53:b-cmejoq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/075b6fbbad936904bb5165af721138dc7d4e02ee/integration-tests/ibc/asset_extension_ft_test.go#L99)):*
> ```Go
> 	)
> 
> 	coreumIssuer := coreumChain.GenAccount()
> ```

Same. `admin` please
___
*[`integration-tests/ibc/asset_extension_ft_test.go` line 139 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/841#-Ny59HvM1kCV9rg3McO2:-Ny59HvN2jlWyH2cFAsF:b2x5r27) ([raw file](https://github.com/CoreumFoundation/coreum/blob/075b6fbbad936904bb5165af721138dc7d4e02ee/integration-tests/ibc/asset_extension_ft_test.go#L139)):*
> ```Go
> 		ExtensionSettings: &assetfttypes.ExtensionIssueSettings{
> 			CodeId: codeID,
> 			Funds:  sdk.NewCoins(),
> ```

Just don't provide this param if you don't want to send any fund

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/841)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/841)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/asset_extension_ft_test.go` line 37 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/841#-Ny58UI68DqXDxIrjjjy:-Ny5MCO_6SAnYS4SogcN:b-i3ub5a) ([raw file](https://github.com/CoreumFoundation/coreum/blob/075b6fbbad936904bb5165af721138dc7d4e02ee/integration-tests/ibc/asset_extension_ft_test.go#L37)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Let's use `admin` instead
</blockquote></details>

but it is the issuer ! 
___
*[`integration-tests/ibc/asset_extension_ft_test.go` line 99 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/841#-Ny58wxG6VrCJHCBuO52:-Ny5MFKb8xk63CS2i9SV:brx2yk6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/075b6fbbad936904bb5165af721138dc7d4e02ee/integration-tests/ibc/asset_extension_ft_test.go#L99)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Same. `admin` please
</blockquote></details>

same as above. 
___
*[`integration-tests/ibc/asset_extension_ft_test.go` line 139 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/841#-Ny59HvM1kCV9rg3McO2:-Ny5MgubAqRAGIP1dKH9:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/075b6fbbad936904bb5165af721138dc7d4e02ee/integration-tests/ibc/asset_extension_ft_test.go#L139)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Just don't provide this param if you don't want to send any fund
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/before_send.go` line 103 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/841#-Ny5888R-7KNRr5cBSs1:-Ny5LEqME2Jo3KRUdXny:b-t8dibd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/075b6fbbad936904bb5165af721138dc7d4e02ee/x/asset/ft/keeper/before_send.go#L103)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

RThis thing is done inside `isCoinReceivable`. Why is it copied here?
</blockquote></details>

this check is done inside `isCoinReceivable` so zero fees are calculated. It is coppied here since we don't want to invoke the extension in case of a rejection and timeout. 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 144 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/841#-Ny57MWLAzghnyqac8SX:-Ny5LnIg0I5Q9xpmWVr8:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/075b6fbbad936904bb5165af721138dc7d4e02ee/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L144)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

type. `comint` -> `coming`
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 268 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/841#-Ny57wmM-HoAE5aBLs12:-Ny5LrfO0JIhryOmfGZN:b-a2ujfl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/075b6fbbad936904bb5165af721138dc7d4e02ee/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L268)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Why `issuer` and not `admin`?
</blockquote></details>

Changed.

**Review by masihyeganeh — DISMISSED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/841)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/asset_extension_ft_test.go` line 37 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/841#-Ny58UI68DqXDxIrjjjy:-Ny5UDqG6u_8uf-vbr43:b-82hohz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/075b6fbbad936904bb5165af721138dc7d4e02ee/integration-tests/ibc/asset_extension_ft_test.go#L37)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

but it is the issuer !
</blockquote></details>

We don't have issuer anymore. But I won't insist. This one is also acceptable
___
*[`integration-tests/ibc/asset_extension_ft_test.go` line 99 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/841#-Ny58wxG6VrCJHCBuO52:-Ny5UPA-55cFSt_zJb0u:b-82hohz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/075b6fbbad936904bb5165af721138dc7d4e02ee/integration-tests/ibc/asset_extension_ft_test.go#L99)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

We don't have issuer anymore. But I won't insist. This one is also acceptable

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/841)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/841)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 2 of 4 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/841)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
