### PR TITLE
Update `crust`

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/887)

### CODE REVIEW

**Review by masihyeganeh — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/887)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/887)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/coreum/build.go` line 58 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/887#-O-LWgHr64ghvaOUO9Wp:-O-LWgHs70HvFNTCOa1O:b-ivz8cd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5cd1799a08dbd495ce1af63eb6556bb27f0577f0/build/coreum/build.go#L58)):*
> ```Go
> 		BinOutputPath:  binaryPath,
> 		CGOEnabled:     true,
> 		Tags:           tagsLocal,
> ```

It's done here: https://reviewable.io/reviews/CoreumFoundation/coreum/886

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/887)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`build/coreum/build.go` line 58 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/887#-O-LWgHr64ghvaOUO9Wp:-O-LXcOJDE7o6icKHHFh:b-fghrsn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5cd1799a08dbd495ce1af63eb6556bb27f0577f0/build/coreum/build.go#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's done here: https://reviewable.io/reviews/CoreumFoundation/coreum/886
</blockquote></details>

but that PR is much harder. For now I just need to get an existing builder to be compatible with new crust

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/887)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`build/coreum/build.go` line 58 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/887#-O-LWgHr64ghvaOUO9Wp:-O-LXuSf1Aff1kRZi1vI:b-ses75y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5cd1799a08dbd495ce1af63eb6556bb27f0577f0/build/coreum/build.go#L58)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but that PR is much harder. For now I just need to get an existing builder to be compatible with new crust
</blockquote></details>

ohhh... I see it's not that easy. Okay. Let's do it there

**Pull request closed without merging**
