### PR TITLE
Update doc

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description
Add transfer admin and clear admin to doc

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/838)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/838)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/838#-Ny-_SWPDTYnaSsr4lYb:-Ny-_SWPDTYnaSsr4lYc:b-joi8ax) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3de89564620cb1f8cd4018d3685d63d33caae873/x/asset/ft/spec/README.md#L39)):*
> ```Markdown
> 
> ### Transferring admin
> Each token, has an issuer who issued the token and the address if this account is stored on token as issuer and also is there on the denom as explained before. But there is also an admin role which is an account that administrates the token, which is the same issuer account when issuing a new token.
> ```

Can refrease this somehow? I've read it three times, before understood :-)
You just need to say the initial admin is issuer of the token, but it's possible to change it. 



_Code quote:_
```Markdown
Each token, has an issuer who issued the token and the address if this account is stored on token as issuer and also is there on the denom as explained before. But there is also an admin role which is an account that administrates the token, which is the same issuer account when issuing a new token.
```
___
*[`x/asset/ft/spec/README.md` line 43 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/838#-Ny-_s_34NjHhXHLKMYt:-Ny-_s_34NjHhXHLKMYu:bnd2jqh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3de89564620cb1f8cd4018d3685d63d33caae873/x/asset/ft/spec/README.md#L43)):*
> ```Markdown
> 
> ### Clearing admin
> Tokens can also lose their admin forever. For example if a token is supposed to be a community token which no one has any more privilege then others, admin can be cleared from the token.
> ```

IMO no need to provide an example of why it can be removed. Just explain how it works.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/838)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/838#-Ny-_SWPDTYnaSsr4lYb:-Ny5099K6aWYWvjQam5s:b-8ezqwz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/45f6e9ff474368cc92e0d86d1377d5783c9d2296/x/asset/ft/spec/README.md#L39)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Can refrease this somehow? I've read it three times, before understood :-)
You just need to say the initial admin is issuer of the token, but it's possible to change it.
</blockquote></details>

Let me know if it is now easier to understand or not
___
*[`x/asset/ft/spec/README.md` line 43 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/838#-Ny-_s_34NjHhXHLKMYt:-Ny50EOv2oHL4J8UxPVk:b-8ezqwz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/45f6e9ff474368cc92e0d86d1377d5783c9d2296/x/asset/ft/spec/README.md#L43)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO no need to provide an example of why it can be removed. Just explain how it works.
</blockquote></details>

Let me know if it is now easier to understand or not

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/838)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/838)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 70 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/838#-Ny50uOQ3j9fa--ztC2D:-Ny50uOQ3j9fa--ztC2E:b-5irrri) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a714b435a4746841ae08f9384ab46e7c46c2f81a/x/asset/ft/spec/README.md#L70)):*
> ```Markdown
> Send commission rate is never applied if smart contract is the sender.
> 
> If a token doesn't have admin (ClearAdmin called on it), the commission rate would set to zero, since there is no account to send the commissions to.
> ```

rate would *be* set to zero

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/838)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 70 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/838#-Ny50uOQ3j9fa--ztC2D:-Ny54Mtl5zqq0fR2PHNB:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a714b435a4746841ae08f9384ab46e7c46c2f81a/x/asset/ft/spec/README.md#L70)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

rate would *be* set to zero
</blockquote></details>

Done.

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/838)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/838)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/838)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
