### PR TITLE
Add URI and URIHash to the asset FT.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Add URI and URIHash to the asset FT.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/685)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/685)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/upgrade/ft_new_attributes_test.go` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/685#-Nheof0j4kAhA_wI99Kx:-Nheof0j4kAhA_wI99Ky:b7pj95s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6df9b1f0157c95a7506a3a89244d605b96e67c0f/integration-tests/upgrade/ft_new_attributes_test.go#L70)):*
> ```Go
> 	require.Equal(t, ftt.token, tokenRes.Token)
> 
> 	// create a token with URI and URIHash
> ```

This part might be moved to `modules` because we run them after upgrading anyway

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/685)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/upgrade/ft_new_attributes_test.go` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/685#-Nheof0j4kAhA_wI99Kx:-NhfBbISES9xHyXNbNG_:bkn733x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6df9b1f0157c95a7506a3a89244d605b96e67c0f/integration-tests/upgrade/ft_new_attributes_test.go#L70)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This part might be moved to `modules` because we run them after upgrading anyway
</blockquote></details>

It is already there, in the modules. Do you propose to remove that creation?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/685)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/upgrade/ft_new_attributes_test.go` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/685#-Nheof0j4kAhA_wI99Kx:-NhfD34lCsFk-_K8Fj1p:b53eo3h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6df9b1f0157c95a7506a3a89244d605b96e67c0f/integration-tests/upgrade/ft_new_attributes_test.go#L70)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It is already there, in the modules. Do you propose to remove that creation?
</blockquote></details>

Yea, then doing it here doesn't make sense

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/685)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/upgrade/ft_new_attributes_test.go` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/685#-Nheof0j4kAhA_wI99Kx:-NhfJ-zo3o1kZzgZJKBh:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6df9b1f0157c95a7506a3a89244d605b96e67c0f/integration-tests/upgrade/ft_new_attributes_test.go#L70)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Yea, then doing it here doesn't make sense
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/685)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 21 of 22 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/685)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @miladz68)

___
*[`integration-tests/upgrade/ft_new_attributes_test.go` line 68 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/685#-NhfcYnEE9YgjPn-OeKi:-NhfcYnF7f763ODpfAkN:b-ijmnzn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/39d4a0ea9686a6c59706af9a605d66eac4734d80/integration-tests/upgrade/ft_new_attributes_test.go#L68)):*
> ```Go
> 	})
> 	requireT.NoError(err)
> 	require.Equal(t, ftt.token, tokenRes.Token)
> ```

should we assert that URI & URIHash are empty strings by default after upgrade ?
Or this is already done as side effect by comparing `ftt.token & tokenRes.Token` ?
___
*[`x/asset/ft/genesis_test.go` line 50 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/685#-NhfcsAV0_vvagNT8tqT:-NhfcsAWCWMm7QGC0O7Q:b-g3wosv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/39d4a0ea9686a6c59706af9a605d66eac4734d80/x/asset/ft/genesis_test.go#L50)):*
> ```Go
> 			SendCommissionRate: sdk.MustNewDecFromStr(fmt.Sprintf("0.%d", i+1)),
> 			Version:            i,
> 			URI:                fmt.Sprintf("https://my-class-meta.invalid/%d", i),
> ```

nit: 
I can see that you use `my-class-meta.invalid` but this URI is valid, isn't it ?
Because I usually use invalid in name, description etc to identify invalid objects/attributes etc

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/685)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/upgrade/ft_new_attributes_test.go` line 68 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/685#-NhfcYnEE9YgjPn-OeKi:-NhfiFdq5LRLIWbe3MFk:bb2avzm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/39d4a0ea9686a6c59706af9a605d66eac4734d80/integration-tests/upgrade/ft_new_attributes_test.go#L68)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should we assert that URI & URIHash are empty strings by default after upgrade ?
Or this is already done as side effect by comparing `ftt.token & tokenRes.Token` ?
</blockquote></details>

Already done as side effect by comparing.
___
*[`x/asset/ft/genesis_test.go` line 50 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/685#-NhfcsAV0_vvagNT8tqT:-NhfiL_d5uhugmuTzfa4:ba70b1s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/39d4a0ea9686a6c59706af9a605d66eac4734d80/x/asset/ft/genesis_test.go#L50)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: 
I can see that you use `my-class-meta.invalid` but this URI is valid, isn't it ?
Because I usually use invalid in name, description etc to identify invalid objects/attributes etc
</blockquote></details>

That's the standard we follow in all tests with the URI and URIHash, the `.invalid` is just a domain name which doesn't exist.

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/685)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by ysv — APPROVED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/685)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
