### PR TITLE
Check the NFT data for nil when updating the dynamic data.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Check the NFT data for nil when updating the dynamic data.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/813)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/813)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`x/asset/nft/keeper/keeper.go` line 382 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/813#-NweGAUkB_6iuoCO0Z2r:-NweGAUkB_6iuoCO0Z2s:b-qvhgg7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08eead3976ce811ac3311a06c0db833f295e58b7/x/asset/nft/keeper/keeper.go#L382)):*
> ```Go
> 		return sdkerrors.Wrapf(types.ErrNFTNotFound, "nft with classID:%s and ID:%s not found", classID, id)
> 	}
> 	if storedNFT.Data == nil {
> ```

btw do we have check that our Data changes are compatible with v3 ?

Maybe we need to add test into upgrade integration tests ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/813)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 382 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/813#-NweGAUkB_6iuoCO0Z2r:-NwiQVaY4QqICtth8yM4:b-d3s91r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/08eead3976ce811ac3311a06c0db833f295e58b7/x/asset/nft/keeper/keeper.go#L382)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

btw do we have check that our Data changes are compatible with v3 ?

Maybe we need to add test into upgrade integration tests ?
</blockquote></details>

We didn't change the data, so it's compatible.

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/813)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/813)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @wojtek-coreum)

**Pull request merged**
