### PR TITLE
Usd DNS for default coreum seeds.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/837)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/837)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`pkg/config/network.go` line 48 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/837#-NxrkD0-AgXd28BqiqaH:-NxrkD0-AgXd28BqiqaI:bbx6s28) ([raw file](https://github.com/CoreumFoundation/coreum/blob/15309690cdc9cd96a3c18640be9344ca1462bf1e/pkg/config/network.go#L48)):*
> ```Go
> 				SeedPeers: []string{
> 					"64391878009b8804d90fda13805e45041f492155@seed-sirius.testnet-1.coreum.dev:26656",  // seed-sirius
> 					"53f2367d8f8291af8e3b6ca60efded0675ff6314@seed-antares.mainnet-1.coreum.dev:26656", // seed-antares
> ```

should it be testnet-1 here ?



_Code quote:_
```Go
seed-antares.mainnet-1.coreum.dev:26656"
```

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/837)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/config/network.go` line 48 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/837#-NxrkD0-AgXd28BqiqaH:-NxuiCOMEgvF5nkyJJyq:b-1nj4ok) ([raw file](https://github.com/CoreumFoundation/coreum/blob/15309690cdc9cd96a3c18640be9344ca1462bf1e/pkg/config/network.go#L48)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should it be testnet-1 here ?
</blockquote></details>

Correct, fixed in registry, but missed here. Updated.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/837)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/837)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @wojtek-coreum)

**Pull request merged**
