### PR TITLE
Added CLI command to QueryRecommendedGasPrice

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/571)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/571)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/client/cli/query.go` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/571#-N_Eu5ws0drHtkZoRPrA:-N_Eu5ws0drHtkZoRPrB:b-cg53li) ([raw file](https://github.com/CoreumFoundation/coreum/blob/34e0fd2b67bba2349db85543e19fdfa7b6916dfc/x/feemodel/client/cli/query.go#L84)):*
> ```Go
> // GetRecommendedGasPriceCmd returns command for getting recommended gas price.
> func GetRecommendedGasPriceCmd() *cobra.Command {
> 	afterFlag := "after"
> ```

Move the flag to the top, near to other flags, please. 
___
*[`x/feemodel/client/cli/query.go` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/571#-N_EuBMsE3FeXAktD97l:-N_EuBMsE3FeXAktD97m:b-qhefdk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/34e0fd2b67bba2349db85543e19fdfa7b6916dfc/x/feemodel/client/cli/query.go#L87)):*
> ```Go
> 	cmd := &cobra.Command{
> 		Use:   "recommended-gas-price",
> 		Short: "Query for recommended gas price for `after` blocks in future",
> ```

Use %s for the flag.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/571)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/feemodel/client/cli/query.go` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/571#-N_EuBMsE3FeXAktD97l:-N_EvB4B7odjxRCr6EGf:b-7tdf7d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/34e0fd2b67bba2349db85543e19fdfa7b6916dfc/x/feemodel/client/cli/query.go#L87)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Use %s for the flag.
</blockquote></details>

agree
___
*[`x/feemodel/client/cli/query.go` line 111 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/571#-N_EvIKI0hmh-CA4wOG8:-N_EvIKI0hmh-CA4wOG9:b-6uj2ut) ([raw file](https://github.com/CoreumFoundation/coreum/blob/34e0fd2b67bba2349db85543e19fdfa7b6916dfc/x/feemodel/client/cli/query.go#L111)):*
> ```Go
> 	}
> 	flags.AddQueryFlagsToCmd(cmd)
> 	cmd.Flags().Uint32(afterFlag, 10, "how many blocks in future to predict gas price for.")
> ```

predict -> estimate

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/571)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/571)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/client/cli/query.go` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/571#-N_Eu5ws0drHtkZoRPrA:-N_FZzta4kGrUW-6T5ff:b-287lb5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/34e0fd2b67bba2349db85543e19fdfa7b6916dfc/x/feemodel/client/cli/query.go#L84)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Move the flag to the top, near to other flags, please. 
</blockquote></details>

this is not a global flag, it is only used but this cmd
___
*[`x/feemodel/client/cli/query.go` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/571#-N_EuBMsE3FeXAktD97l:-N_F_Kh-3CFh9XYJmUUK:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/34e0fd2b67bba2349db85543e19fdfa7b6916dfc/x/feemodel/client/cli/query.go#L87)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

agree
</blockquote></details>

Done.
___
*[`x/feemodel/client/cli/query.go` line 111 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/571#-N_EvIKI0hmh-CA4wOG8:-N_F_PaH4b0bp3nfVPZG:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/34e0fd2b67bba2349db85543e19fdfa7b6916dfc/x/feemodel/client/cli/query.go#L111)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

predict -> estimate
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/571)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/feemodel/client/cli/query.go` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/571#-N_Eu5ws0drHtkZoRPrA:-N_I5wR8D9GDB4x7ftaQ:bj3plnx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/34e0fd2b67bba2349db85543e19fdfa7b6916dfc/x/feemodel/client/cli/query.go#L84)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this is not a global flag, it is only used but this cmd
</blockquote></details>

and define it as `const`
___
*[`x/feemodel/client/cli/query_test.go` line 43 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/571#-N_I6BTa9y1OxruUKwf5:-N_I6BTa9y1OxruUKwf6:b-v1n1mj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5c58abcf534da7ab45ac9e1b39ffb2b7cc305d01/x/feemodel/client/cli/query_test.go#L43)):*
> ```Go
> 	require.NoError(t, json.Unmarshal(buf.Bytes(), &resp))
> 
> 	assert.Less(t, sdk.ZeroDec().MustFloat64(), resp.Low.Amount.MustFloat64())
> ```

The tested value should go first because then constructed error messages are easier to understand. Here you would get sth like "0 is expected to be less than 1000`

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/571)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/571)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/571)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/571)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/client/cli/query.go` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/571#-N_Eu5ws0drHtkZoRPrA:-N_IuXeGCA4dNNGcBIBh:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/34e0fd2b67bba2349db85543e19fdfa7b6916dfc/x/feemodel/client/cli/query.go#L84)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

and define it as `const`
</blockquote></details>

Done.
___
*[`x/feemodel/client/cli/query_test.go` line 43 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/571#-N_I6BTa9y1OxruUKwf5:-N_IuzvN5KhLWsySQBBt:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5c58abcf534da7ab45ac9e1b39ffb2b7cc305d01/x/feemodel/client/cli/query_test.go#L43)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The tested value should go first because then constructed error messages are easier to understand. Here you would get sth like "0 is expected to be less than 1000`
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/571)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/571)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/571)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/571)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
