### PR TITLE
added nft invariants

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/405)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/405)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/asset/nft/keeper/invariant.go` line 27 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/405#-NOsq8B17Ue6A0kJCnDw:-NOsq8B17Ue6A0kJCnDx:bgd8f8n) ([raw file](https://github.com/CoreumFoundation/coreum/blob/06762fe109c1caa7a07dfc34d21dcb03bf2a742a/x/asset/nft/keeper/invariant.go#L27)):*
> ```Go
> 
> // FrozenNFTExistsInvariant checks that all frozen NFTs have counterpart on the original Cosmos SDK NFT module.
> func FrozenNFTExistsInvariant(k Keeper) sdk.Invariant {
> ```

I'm not sure if `frozen-exist` is correct name for the invariant since you check plenty of things but not only existence inside it:
1. original NFT exists
2. class definition exists
3. freezing enabled

Maybe it should just have more general name like "frozen-nfts" or "freezing" ?
(Same for whitelisting)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/405)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`x/asset/nft/keeper/invariant.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/405#-NP18AdU3diGWBWOzn07:-NP18AdU3diGWBWOzn08:b-yqq6dw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/06762fe109c1caa7a07dfc34d21dcb03bf2a742a/x/asset/nft/keeper/invariant.go#L16)):*
> ```Go
> 	OriginalClassExistsInvariantName  = "original-class-exist"
> 	WhitelistedNFTExistsInvariantName = "whitelisted-exist"
> 	FrozenNFTExistsInvariantName      = "frozen-exist"
> ```

In the variables and functions you use "Exists", but in the values "exist"
___
*[`x/asset/nft/keeper/invariant.go` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/405#-NP19rJhA-qRt4oJB1K_:-NP19rJhA-qRt4oJB1Ka:bdjqlsv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/06762fe109c1caa7a07dfc34d21dcb03bf2a742a/x/asset/nft/keeper/invariant.go#L63)):*
> ```Go
> 		return sdk.FormatInvariant(
> 			types.ModuleName, FrozenNFTExistsInvariantName,
> 			fmt.Sprintf("number of missing metadata entries %d\n%s", violationsCount, msg),
> ```

error message is incorrect, it's more related to metadata in bank module referenced by ft

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/405)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/keeper/invariant.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/405#-NP18AdU3diGWBWOzn07:-NP1T44bCC_N7qaoW6pK:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/06762fe109c1caa7a07dfc34d21dcb03bf2a742a/x/asset/nft/keeper/invariant.go#L16)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

In the variables and functions you use "Exists", but in the values "exist"
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/invariant.go` line 27 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/405#-NOsq8B17Ue6A0kJCnDw:-NP1T4YF0tg-RzPHY0m1:b-cqeog8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/06762fe109c1caa7a07dfc34d21dcb03bf2a742a/x/asset/nft/keeper/invariant.go#L27)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm not sure if `frozen-exist` is correct name for the invariant since you check plenty of things but not only existence inside it:
1. original NFT exists
2. class definition exists
3. freezing enabled

Maybe it should just have more general name like "frozen-nfts" or "freezing" ?
(Same for whitelisting)
</blockquote></details>

I agree, Done. 
___
*[`x/asset/nft/keeper/invariant.go` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/405#-NP19rJhA-qRt4oJB1K_:-NP1T8pd0DnIuxNK2zsp:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/06762fe109c1caa7a07dfc34d21dcb03bf2a742a/x/asset/nft/keeper/invariant.go#L63)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

error message is incorrect, it's more related to metadata in bank module referenced by ft
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/405)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/405)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/405)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/405)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/405)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Pull request merged**
