### PR TITLE
edited freeze short description

### PR DESCRIPTION
**Pull request by vertex451**
This was requested by @ysv

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/458)

### CODE REVIEW

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/458)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/458)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`x/asset/ft/client/cli/tx.go` line 251 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/458#-NRcFuRz5WWN4pzoJ_hg:-NRcFuRz5WWN4pzoJ_hh:b-fzut9s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/259be96baf22a42f3988f9f1cdb82aeac08c5072/x/asset/ft/client/cli/tx.go#L251)):*
> ```Go
> 		Use:   "freeze [account_address] [amount] --from [sender]",
> 		Args:  cobra.ExactArgs(2),
> 		Short: "Freeze a portion or a full amount of fungible token",
> ```

It's still not true, because it's posible to freeze more than the current balance

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/458)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/458)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Pull request merged**
