### PR TITLE
Add the FungibleTokenDefinition genesis import and export

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/262)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/262)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 32 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/262#-NH3IxfVAt2JJMXxaYlz:-NH3IxfVAt2JJMXxaYm-:bn41ngl) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e2816a94a2fb29998ddb98a8a35e133d0a03a24/.github/workflows/ci.yml#L32)):*
> ```YAML
>             docker-cache: true
>           - ci_step: "integration tests"
>             command: "crust build/integration-tests images --log-format=yaml" # FIXME(dhil) return back once we update the crust -> && crust znet test --log-format=yaml
> ```

Have to do it because of the changes in the genesis template.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/262)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/262)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/262)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`.github/workflows/ci.yml` line 32 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/262#-NH3IxfVAt2JJMXxaYlz:-NH3xLD-Eis5Hz99CEpH:b1cg1ss) ([raw file](https://github.com/coreumfoundation/coreum/blob/3e2816a94a2fb29998ddb98a8a35e133d0a03a24/.github/workflows/ci.yml#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Have to do it because of the changes in the genesis template. 
</blockquote></details>

I don't think this is needed since those fields in genesis will be empty and hence omitted in integration tests.

**Pull request merged**
