### PR TITLE
Add concurrent safe keyring to integration-tests

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/263)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/263)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/263)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/testing/keyring.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/263#-NH3tqW28reSs_NvQq9U:-NH3tqW28reSs_NvQq9V:b7pq6gw) ([raw file](https://github.com/coreumfoundation/coreum/blob/29eea68bb4d48fb5348686db8f91805750c5272b/integration-tests/testing/keyring.go#L17)):*
> ```Go
> type concurrentSafeKeyring struct {
> 	kr keyring.Keyring
> 	mu *sync.RWMutex
> ```

please move it above `kr` so we know that `kr` is protected
___
*[`integration-tests/testing/keyring.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/263#-NH3u0GU4Wa6xIAjBtHA:-NH3u0GU4Wa6xIAjBtHB:b-jab6jo) ([raw file](https://github.com/coreumfoundation/coreum/blob/29eea68bb4d48fb5348686db8f91805750c5272b/integration-tests/testing/keyring.go#L38)):*
> ```Go
> func (csk concurrentSafeKeyring) SupportedAlgorithms() (keyring.SigningAlgoList, keyring.SigningAlgoList) {
> 	csk.mu.RLock()
> 	defer csk.mu.RUnlock()
> ```

I believe this method does not need protection as algorithms are immutable
___
*[`integration-tests/testing/keyring.go` line 136 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/263#-NH3uYQUDFLpmcxyDuZ1:-NH3uYQUDFLpmcxyDuZ2:b-geitfh) ([raw file](https://github.com/coreumfoundation/coreum/blob/29eea68bb4d48fb5348686db8f91805750c5272b/integration-tests/testing/keyring.go#L136)):*
> ```Go
> }
> 
> func (csk concurrentSafeKeyring) Sign(uid string, msg []byte) ([]byte, types.PubKey, error) {
> ```

Isn't it read only operation?
___
*[`integration-tests/testing/keyring.go` line 143 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/263#-NH3ub-yDMKpppWKhSnq:-NH3ub-yDMKpppWKhSnr:b-geitfh) ([raw file](https://github.com/coreumfoundation/coreum/blob/29eea68bb4d48fb5348686db8f91805750c5272b/integration-tests/testing/keyring.go#L143)):*
> ```Go
> }
> 
> func (csk concurrentSafeKeyring) SignByAddress(address sdk.Address, msg []byte) ([]byte, types.PubKey, error) {
> ```

Isn't it read only operation?

**Review by miladz68 — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/263)* status: all files reviewed, 4 unresolved discussions (waiting on @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Pull request merged**
