### PR TITLE
Allow smart contract to create fungible token

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: 0 of 13 files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGH0W_E-aYHEiiG3SfG:-NGH0W_E-aYHEiiG3SfH:b-eif3x1) ([raw file](https://github.com/coreumfoundation/coreum/blob/b886c80ce93abe6818602bdecb23e670bea429a9/integration-tests/wasm/bank_send.go#L23)):*
> ```Go
> )
> 
> type bankInstantiatePayload struct{}
> ```

Why do you need the empty struct now? You can remove it and use the `struct{}{}` instead.
___
*[`integration-tests/wasm/bank_send.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGH0Qwu36zRZM1syX0e:-NGH0Qwu36zRZM1syX0f:b-jeqzr0) ([raw file](https://github.com/coreumfoundation/coreum/blob/b886c80ce93abe6818602bdecb23e670bea429a9/integration-tests/wasm/bank_send.go#L37)):*
> ```Go
> )
> 
> // TestFungibleTokenWasmContract runs a contract deployment flow and tests that the contract is able to use Bank module
> ```

I guess that comment should have been touched.



_Code quote:_
```Go
TestFungibleTokenWasmContract
```
___
*[`integration-tests/wasm/fungible_token.go` line 22 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGH1lRr7l2yzcgdhpVY:-NGH1lRr7l2yzcgdhpVZ:b749x7s) ([raw file](https://github.com/coreumfoundation/coreum/blob/b886c80ce93abe6818602bdecb23e670bea429a9/integration-tests/wasm/fungible_token.go#L22)):*
> ```Go
> )
> 
> type fungibleTokenInstantiatePayload struct{}
> ```

That payload isn't needed as well.
___
*[`integration-tests/wasm/fungible_token.go` line 76 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGH2Jmh1d5gqZgKjBS1:-NGH2Jmh1d5gqZgKjBS2:b-6up2wa) ([raw file](https://github.com/coreumfoundation/coreum/blob/b886c80ce93abe6818602bdecb23e670bea429a9/integration-tests/wasm/fungible_token.go#L76)):*
> ```Go
> 		create: {
> 			Symbol:    symbol,
> 			Amount:    "5000",
> ```

I would move the "5000" to a variable. You can keep it in `sdk.Int, call `.String()` here and use as Int in the last assertion. 
___
*[`integration-tests/wasm/fungible_token.go` line 83 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGH24q5BLOVNslic0Z_:-NGH24q5BLOVNslic0Za:busbjmy) ([raw file](https://github.com/coreumfoundation/coreum/blob/b886c80ce93abe6818602bdecb23e670bea429a9/integration-tests/wasm/fungible_token.go#L83)):*
> ```Go
> 
> 	txf = txf.WithSimulateAndExecute(true)
> 	_, err = Execute(ctx, clientCtx, txf, contractAddr, createPayload, sdk.Coin{})
> ```

Could you please check what is the gas spent on the TX? 
___
*[`x/asset/types/types.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGH-mIK93sS0yNR9Rfq:-NGH-mIK93sS0yNR9Rfr:b-tllzlw) ([raw file](https://github.com/coreumfoundation/coreum/blob/b886c80ce93abe6818602bdecb23e670bea429a9/x/asset/types/types.go#L1)):*
> ```Go
> package types
> ```

Let's rename that file to wasm.go

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: 0 of 13 files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/wasm/bank_send.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGH0W_E-aYHEiiG3SfG:-NGL4whOAnfcqUV3Bez0:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/b886c80ce93abe6818602bdecb23e670bea429a9/integration-tests/wasm/bank_send.go#L23)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need the empty struct now? You can remove it and use the `struct{}{}` instead.
</blockquote></details>

Done.
___
*[`integration-tests/wasm/bank_send.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGH0Qwu36zRZM1syX0e:-NGL4zU7E09C1tnvzO7K:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/b886c80ce93abe6818602bdecb23e670bea429a9/integration-tests/wasm/bank_send.go#L37)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I guess that comment should have been touched.
</blockquote></details>

Done.
___
*[`integration-tests/wasm/fungible_token.go` line 22 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGH1lRr7l2yzcgdhpVY:-NGL50-N54OfIokTTYlA:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/b886c80ce93abe6818602bdecb23e670bea429a9/integration-tests/wasm/fungible_token.go#L22)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

That payload isn't needed as well.
</blockquote></details>

Done.
___
*[`integration-tests/wasm/fungible_token.go` line 76 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGH2Jmh1d5gqZgKjBS1:-NGL51aA7UB5JU_Z2zJ_:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/b886c80ce93abe6818602bdecb23e670bea429a9/integration-tests/wasm/fungible_token.go#L76)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would move the "5000" to a variable. You can keep it in `sdk.Int, call `.String()` here and use as Int in the last assertion. 
</blockquote></details>

Done.
___
*[`integration-tests/wasm/fungible_token.go` line 83 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGH24q5BLOVNslic0Z_:-NGL6mcP8RAJxchYYufa:bidbq14) ([raw file](https://github.com/coreumfoundation/coreum/blob/b886c80ce93abe6818602bdecb23e670bea429a9/integration-tests/wasm/fungible_token.go#L83)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you please check what is the gas spent on the TX? 
</blockquote></details>

195385
___
*[`x/asset/types/types.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGH-mIK93sS0yNR9Rfq:-NGL54bJ7biBjuPCOqEg:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/b886c80ce93abe6818602bdecb23e670bea429a9/x/asset/types/types.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's rename that file to wasm.go
</blockquote></details>

Done.

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 13 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`integration-tests/wasm/fungible_token.go` line 86 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOVPY45UyVwmgM5AKv:-NGOVPY45UyVwmgM5AKw:b-xl7kjn) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/integration-tests/wasm/fungible_token.go#L86)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	logger.Get(ctx).Info("Fungible token issued by smart contract", zap.Int64("gasUsed", gasUsed))
> ```

does it make sense to add check that gasUsed > deterministicFees.MsgIssueFungibleToken ?
___
*[`integration-tests/wasm/testdata/fungible-token/src/contract.rs` line 57 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOYIiaElFZp5-DoWXn:-NGOYIib1MNAfvHEId-V:bxnn78p) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/integration-tests/wasm/testdata/fungible-token/src/contract.rs#L57)):*
> ```XML
> }
> 
> fn create_token(
> ```

As far as I understand this .rs file consists of 2 main parts:
1. contract logic itself
2. SDK-like part where you define types funcs etc to be used

Can we split it into 2 .rs files so it is more visible and easier to share with contract devs ? or it is going to be too painful to import a file in rust ?
___
*[`integration-tests/wasm/testdata/fungible-token/src/contract.rs` line 57 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOYealA6DHxJ14hhsB:-NGOYealA6DHxJ14hhsC:b-gc58rt) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/integration-tests/wasm/testdata/fungible-token/src/contract.rs#L57)):*
> ```XML
> }
> 
> fn create_token(
> ```

`issue_token`
I know that they are synonyms in this context but lets use a single version `issue` everywhere to not confuse users in the future 
___
*[`x/wasm/types/encoder.go` line 11 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOVzL31TpB0rbX-u7q:-NGOVzL31TpB0rbX-u7r:bdt4phu) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/x/wasm/types/encoder.go#L11)):*
> ```Go
> )
> 
> // Handler handles encoding of custom emssage
> ```

typo `emssage`
___
*[`x/wasm/types/encoder.go` line 15 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOWcje75rx7JySm8cB:-NGOWcje75rx7JySm8cC:b-1nqel5) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/x/wasm/types/encoder.go#L15)):*
> ```Go
> 
> // NewCustomEncoder encodes custom messages received from smart contracts
> func NewCustomEncoder(handlers ...Handler) *wasmkeeper.MessageEncoders {
> ```

Once we are on call I want you to explain this part to me
I sort of understand it partially but want to have a full view
___
*[`x/asset/types/wasm.go` line 15 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOWUbFEZoUqS2DHH3e:-NGOWUbFEZoUqS2DHH3f:b94ezuf) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/x/asset/types/wasm.go#L15)):*
> ```Go
> 	for msgType, msg := range messages {
> 		if msgType == "MsgIssueFungibleToken" {
> 			var createFungibleTokenMsg MsgIssueFungibleToken
> ```

minor: createFungibleTokenMsg -> issueFungibleTokenMsg ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: 7 of 14 files reviewed, 6 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/wasm/fungible_token.go` line 86 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOVPY45UyVwmgM5AKv:-NGQG4ckBA9qA-oBBSWf:b-5puu8v) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/integration-tests/wasm/fungible_token.go#L86)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

does it make sense to add check that gasUsed > deterministicFees.MsgIssueFungibleToken ?
</blockquote></details>

I don't think so. We enforce it elsewhere
___
*[`integration-tests/wasm/testdata/fungible-token/src/contract.rs` line 57 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOYIiaElFZp5-DoWXn:-NGQJVnIECD0RUvCc25m:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/integration-tests/wasm/testdata/fungible-token/src/contract.rs#L57)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

As far as I understand this .rs file consists of 2 main parts:
1. contract logic itself
2. SDK-like part where you define types funcs etc to be used

Can we split it into 2 .rs files so it is more visible and easier to share with contract devs ? or it is going to be too painful to import a file in rust ?
</blockquote></details>

Done
___
*[`integration-tests/wasm/testdata/fungible-token/src/contract.rs` line 57 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOYealA6DHxJ14hhsB:-NGQJbK21If3Y0xvxNIq:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/integration-tests/wasm/testdata/fungible-token/src/contract.rs#L57)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`issue_token`
I know that they are synonyms in this context but lets use a single version `issue` everywhere to not confuse users in the future 
</blockquote></details>

Done
___
*[`x/wasm/types/encoder.go` line 11 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOVzL31TpB0rbX-u7q:-NGQKM2H2BvP6pD8EnUw:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/x/wasm/types/encoder.go#L11)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

typo `emssage`
</blockquote></details>

Done
___
*[`x/asset/types/wasm.go` line 15 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOWUbFEZoUqS2DHH3e:-NGQKFdb2FkicR8AJk0v:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/x/asset/types/wasm.go#L15)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: createFungibleTokenMsg -> issueFungibleTokenMsg ?
</blockquote></details>

Done

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r1, 4 of 8 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: all files reviewed, 12 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/wasm/fungible_token.go` line 24 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRChUg09WzeXh8VU5U:-NGRChUg09WzeXh8VU5V:bj5s23s) ([raw file](https://github.com/coreumfoundation/coreum/blob/112cc8854d49f5984bb1d96160c6d3ea6269197c/integration-tests/wasm/fungible_token.go#L24)):*
> ```Go
> )
> 
> type fungibleTokenCreateRequest struct {
> ```

`issueFungibleTokenRequest` seems like a better name
___
*[`integration-tests/wasm/testdata/fungible-token/Cargo.lock` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRDdnP2kD74AhSxNns:-NGRDdnP2kD74AhSxNnt:blxuc4r) ([raw file](https://github.com/coreumfoundation/coreum/blob/112cc8854d49f5984bb1d96160c6d3ea6269197c/integration-tests/wasm/testdata/fungible-token/Cargo.lock#L1)):*
> ```TOML
> # This file is automatically @generated by Cargo.
> ```

I left this comment on Max's PRs 3 times and I don't think I got an answer. So I repeat it here
we create `Cargo.lock` `Cargo.toml` files for every test that we create for wasm. is it possible to merge these files into 1 ?
___
*[`integration-tests/wasm/testdata/fungible-token/src/contract.rs` line 12 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRNCVV1h5CptJyZSh2:-NGRNCVV1h5CptJyZSh3:b-1ef7ar) ([raw file](https://github.com/coreumfoundation/coreum/blob/112cc8854d49f5984bb1d96160c6d3ea6269197c/integration-tests/wasm/testdata/fungible-token/src/contract.rs#L12)):*
> ```XML
> 
> // version info for migration info
> const CONTRACT_NAME: &str = "crates.io:hello";
> ```

maybe creates.io:test-fungible-token is better name for this contract.
___
*[`integration-tests/wasm/testdata/fungible-token/src/contract.rs` line 16 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRSoC3EtBbJDy2rADt:-NGRSoC3EtBbJDy2rADu:bc66lo5) ([raw file](https://github.com/coreumfoundation/coreum/blob/112cc8854d49f5984bb1d96160c6d3ea6269197c/integration-tests/wasm/testdata/fungible-token/src/contract.rs#L16)):*
> ```XML
> 
> #[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
> pub struct State {
> ```

for this specific test we don't need to store any thing, we just want to see if messages are routed via smart contracts correctly. 
___
*[`integration-tests/wasm/testdata/fungible-token/src/contract.rs` line 34 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRT6Eg-bFQ4qq7hUSE:-NGRT6Eg-bFQ4qq7hUSF:b-mlxbkp) ([raw file](https://github.com/coreumfoundation/coreum/blob/112cc8854d49f5984bb1d96160c6d3ea6269197c/integration-tests/wasm/testdata/fungible-token/src/contract.rs#L34)):*
> ```XML
> 
>     set_contract_version(deps.storage, CONTRACT_NAME, CONTRACT_VERSION)?;
>     STATE.save(deps.storage, &state)?;
> ```

commented above that we don't need this. 
___
*[`x/wasm/types/encoder.go` line 24 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRUmb6EDBNhtAQGKWn:-NGRUmb6EDBNhtAQGKWo:bhdbmm6) ([raw file](https://github.com/coreumfoundation/coreum/blob/112cc8854d49f5984bb1d96160c6d3ea6269197c/x/wasm/types/encoder.go#L24)):*
> ```Go
> 			res := make([]sdk.Msg, 0, len(messages))
> 
> 			for _, h := range handlers {
> ```

maybe one central switch statement inside wasm module would be simpler and more performant than a for loop of handlers 
___
*[`x/asset/types/wasm.go` line 15 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOWUbFEZoUqS2DHH3e:-NGRFSw74Ierlbn_6g1Z:by4jd17) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/x/asset/types/wasm.go#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Actually `msgIssueFungibleToken` is correct

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: all files reviewed, 12 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/wasm/types/encoder.go` line 24 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRUmb6EDBNhtAQGKWn:-NGReGqp17NbgNtCCfaP:b50qc43) ([raw file](https://github.com/coreumfoundation/coreum/blob/112cc8854d49f5984bb1d96160c6d3ea6269197c/x/wasm/types/encoder.go#L24)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

maybe one central switch statement inside wasm module would be simpler and more performant than a for loop of handlers 
</blockquote></details>

It would be, but its against the concept that it is a responsibility of module defining the message to handle it.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: 5 of 21 files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/wasm/fungible_token.go` line 24 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRChUg09WzeXh8VU5U:-NGVOjl52ripa1-q33I7:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/3b60340f9b8072b40ada1eed67d55d5c6712aa37/integration-tests/wasm/fungible_token.go#L24)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

`issueFungibleTokenRequest` seems like a better name
</blockquote></details>

Done.
___
*[`integration-tests/wasm/testdata/fungible-token/Cargo.lock` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRDdnP2kD74AhSxNns:-NGVOpqC3YIwXvGjQUU_:b8suhor) ([raw file](https://github.com/coreumfoundation/coreum/blob/3b60340f9b8072b40ada1eed67d55d5c6712aa37/integration-tests/wasm/testdata/fungible-token/Cargo.lock#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I left this comment on Max's PRs 3 times and I don't think I got an answer. So I repeat it here
we create `Cargo.lock` `Cargo.toml` files for every test that we create for wasm. is it possible to merge these files into 1 ?
</blockquote></details>

If we treat each smart contract as separate project then every of them needs separate cargo files. We could join them together but then we will get single binary containing all the smart contracts and I don't know how it is handled by cosmwasm
___
*[`integration-tests/wasm/testdata/fungible-token/src/contract.rs` line 12 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRNCVV1h5CptJyZSh2:-NGVRoZGD2_W6urpBgx0:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/3b60340f9b8072b40ada1eed67d55d5c6712aa37/integration-tests/wasm/testdata/fungible-token/src/contract.rs#L12)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

maybe creates.io:test-fungible-token is better name for this contract.
</blockquote></details>

Done.
___
*[`integration-tests/wasm/testdata/fungible-token/src/contract.rs` line 16 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRSoC3EtBbJDy2rADt:-NGVRl0A7jC0nwqJZqG9:b-3h1cca) ([raw file](https://github.com/coreumfoundation/coreum/blob/3b60340f9b8072b40ada1eed67d55d5c6712aa37/integration-tests/wasm/testdata/fungible-token/src/contract.rs#L16)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

for this specific test we don't need to store any thing, we just want to see if messages are routed via smart contracts correctly. 
</blockquote></details>

we still do this:

```
    set_contract_version(deps.storage, CONTRACT_NAME, CONTRACT_VERSION)?;
    STATE.save(deps.storage, &state)?;
```

and this:

```
    let state = STATE.load(deps.storage)?;
    if info.sender != state.owner {
        return Err(ContractError::Unauthorized {});
    }
```
___
*[`x/asset/types/wasm.go` line 15 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOWUbFEZoUqS2DHH3e:-NGVXjXjAovsCXDmaOYy:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/x/asset/types/wasm.go#L15)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Actually `msgIssueFungibleToken` is correct
</blockquote></details>

Done

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 13 files at r1, 3 of 8 files at r2, 1 of 7 files at r3, 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: all files reviewed, 10 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r3, 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`x/wasm/types/encoder.go` line 24 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRUmb6EDBNhtAQGKWn:-NGWeuJp4yCmYLxT3OV6:brc33a2) ([raw file](https://github.com/coreumfoundation/coreum/blob/3b60340f9b8072b40ada1eed67d55d5c6712aa37/x/wasm/types/encoder.go#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It would be, but its against the concept that it is a responsibility of module defining the message to handle it.
</blockquote></details>

I prefer Wojtek's approach here

Milad, I think on your approach we will end up having smth similar to our deterministic fees which looks ugly
___
*[`integration-tests/wasm/fungible_token.go` line 86 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOVPY45UyVwmgM5AKv:-NGWfgfT4K-qOgn-RUFa:b1w98va) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/integration-tests/wasm/fungible_token.go#L86)):*
> We enforce it elsewhere

where do we check it exactly ?

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: all files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum)

___
*[`integration-tests/wasm/testdata/fungible-token/Cargo.lock` line 1 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRDdnP2kD74AhSxNns:-NGWhRQz5IdoPnMaycy5:b-8k178m) ([raw file](https://github.com/coreumfoundation/coreum/blob/3b60340f9b8072b40ada1eed67d55d5c6712aa37/integration-tests/wasm/testdata/fungible-token/Cargo.lock#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If we treat each smart contract as separate project then every of them needs separate cargo files. We could join them together but then we will get single binary containing all the smart contracts and I don't know how it is handled by cosmwasm
</blockquote></details>

I think it is still possible to get different binaries for each smart contract, just needs a little digging. I sense that you agree it is the better approach. I will resolve it here and we can do it in another task. 
___
*[`integration-tests/wasm/testdata/fungible-token/src/contract.rs` line 16 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRSoC3EtBbJDy2rADt:-NGWkjIT4xBkuLvmSvfn:bd2w0rv) ([raw file](https://github.com/coreumfoundation/coreum/blob/3b60340f9b8072b40ada1eed67d55d5c6712aa37/integration-tests/wasm/testdata/fungible-token/src/contract.rs#L16)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

we still do this:

```
    set_contract_version(deps.storage, CONTRACT_NAME, CONTRACT_VERSION)?;
    STATE.save(deps.storage, &state)?;
```

and this:

```
    let state = STATE.load(deps.storage)?;
    if info.sender != state.owner {
        return Err(ContractError::Unauthorized {});
    }
```
</blockquote></details>

I don't think any of them are really needed

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: 20 of 21 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/wasm/fungible_token.go` line 86 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOVPY45UyVwmgM5AKv:-NG_gYRO6H0MhrpD5ESw:b-chd1ax) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/integration-tests/wasm/fungible_token.go#L86)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> We enforce it elsewhere

where do we check it exactly ?
</blockquote></details>

Actually we missed it. Added it in the other test
___
*[`integration-tests/wasm/testdata/fungible-token/src/contract.rs` line 16 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRSoC3EtBbJDy2rADt:-NG_fA_850h2pG0poy8m:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/3b60340f9b8072b40ada1eed67d55d5c6712aa37/integration-tests/wasm/testdata/fungible-token/src/contract.rs#L16)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think any of them are really needed 
</blockquote></details>

Done.
___
*[`integration-tests/wasm/testdata/fungible-token/src/contract.rs` line 34 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGRT6Eg-bFQ4qq7hUSE:-NG_fCC11XJAeaTmPOYV:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/3b60340f9b8072b40ada1eed67d55d5c6712aa37/integration-tests/wasm/testdata/fungible-token/src/contract.rs#L34)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

commented above that we don't need this. 
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: 19 of 22 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/wasm/types/encoder.go` line 15 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/247#-NGOWcje75rx7JySm8cB:-NGb8viDBAZ0klXM0zeP:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/2e3f7a244cc994e476528c787e6b9d00b57db1ae/x/wasm/types/encoder.go#L15)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Once we are on call I want you to explain this part to me
I sort of understand it partially but want to have a full view
</blockquote></details>

Done.

**Review by ysv — DISMISSED** [review]
> Reviewed 6 of 7 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 6 of 7 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/247)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
