### PR TITLE
Add generate-devnet CLI command.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Add command which helps to generate devnet for new validator set.
Example

```bash
cored generate-devnet --chain-id coreum-devnet-1 --output-path devnet-gen --validator-name vone --validator-name vtwo
```

The command above will generate the config for two validators (`vone` and `vtwo`) in the `devnet-gen` folder.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/721)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/721)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 45 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqQtMR-XfLpT_UtxDc:-NjqQtMS74A_KHtLJnbr:biuvcmk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/21310ecc6f09a59e9dc56b394690e22d4b0397f8/cmd/cored/cosmoscmd/generate_devnet.go#L45)):*
> ```Go
> 		Use:   "generate-devnet",
> 		Short: "Generate devnet configuration files",
> 		Long:  `Generate devnet validators's and node's configuration files.`,
> ```

`validators' and nodes'`
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 85 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqRM-z8xBz6arhbbfx:-NjqRM-z8xBz6arhbbfy:b-gowese) ([raw file](https://github.com/CoreumFoundation/coreum/blob/21310ecc6f09a59e9dc56b394690e22d4b0397f8/cmd/cored/cosmoscmd/generate_devnet.go#L85)):*
> ```Go
> 
> 				network.NodeConfig.Name = validatorName
> 				cfg = network.NodeConfig.TendermintNodeConfig(cfg)
> ```

Do we have any config customizations which should be set in the config? seed node addresses, store config etc.
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 120 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqRkVh9xLYWwD8tgrh:-NjqRkVh9xLYWwD8tgri:b-9gqivt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/21310ecc6f09a59e9dc56b394690e22d4b0397f8/cmd/cored/cosmoscmd/generate_devnet.go#L120)):*
> ```Go
> 			for _, validatorName := range validatorNames {
> 				validatorOutputPath := filepath.Join(outputPath, validatorName, string(network.ChainID()))
> 				genDocBytes, err := network.EncodeGenesis()
> ```

This may be done outside the loop

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/721)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 45 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqQtMR-XfLpT_UtxDc:-NjqaANn-6T3z4BE1S-D:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/21310ecc6f09a59e9dc56b394690e22d4b0397f8/cmd/cored/cosmoscmd/generate_devnet.go#L45)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`validators' and nodes'`
</blockquote></details>

Done.
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 85 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqRM-z8xBz6arhbbfx:-Njq_uen8RYLpU-zmyDF:bo9vcsj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/21310ecc6f09a59e9dc56b394690e22d4b0397f8/cmd/cored/cosmoscmd/generate_devnet.go#L85)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do we have any config customizations which should be set in the config? seed node addresses, store config etc.
</blockquote></details>

For now - not. We agree to go with the simple version and extend it once it is needed on the dev-op side.
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 120 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqRkVh9xLYWwD8tgrh:-Njq_sICEU1Owh2epsiQ:boe9toz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/21310ecc6f09a59e9dc56b394690e22d4b0397f8/cmd/cored/cosmoscmd/generate_devnet.go#L120)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This may be done outside the loop
</blockquote></details>

`validatorName` is the part of the path

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/721)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqhVtlEfYbLwYZWXxv:-NjqhVtlEfYbLwYZWXxw:b-gz3lxm) (no related file):*
What I have just realized is that we are implementing this command and it is very similar to what we wanted to have as result of crust refactoring (no cored dependency etc)

I think we should consider exted this cmd later & crust<>coreum interactions to binary

___
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 41 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-Njqfv2t1SVzecaLCEj-:-Njqfv2t1SVzecaLCEj0:b234i1s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/324c4faf344b87ce31c19f416cd026def5fffc5b/cmd/cored/cosmoscmd/generate_devnet.go#L41)):*
> ```Go
> 
> // GenerateDevnetCmd returns a command that generates devnet files needed to start the devnet.
> func GenerateDevnetCmd() *cobra.Command {
> ```

since --chain-id is a flag in this CLI it could be any network but not only devnet.
E.g `--localnet-1`

Shouldn't we use some generic name here ?
Or you prefer to keep it simple for now ?
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 45 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqgC-_-cVqUClWQXc5:-NjqgC-_-cVqUClWQXc6:b-78qbe0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/324c4faf344b87ce31c19f416cd026def5fffc5b/cmd/cored/cosmoscmd/generate_devnet.go#L45)):*
> ```Go
> 		Use:   "generate-devnet",
> 		Short: "Generate devnet configuration files",
> 		Long:  `Generate devnet validators' and nodes' configuration files.`,
> ```

What about genesis ? Does the command generate it also ?
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 49 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqgM058fCB-WDT0vB0:-NjqgM058fCB-WDT0vB1:b3c9wiq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/324c4faf344b87ce31c19f416cd026def5fffc5b/cmd/cored/cosmoscmd/generate_devnet.go#L49)):*
> ```Go
> 		RunE: func(cmd *cobra.Command, args []string) error {
> 			network := app.ChosenNetwork
> 			if app.ChosenNetwork.ChainID() != constant.ChainIDDev {
> ```

I thought that we want to have denvet-2,3... ?
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 73 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqgWXz7Qpv7TOC5Kpd:-NjqgWXz7Qpv7TOC5Kpe:b-gei0ly) ([raw file](https://github.com/CoreumFoundation/coreum/blob/324c4faf344b87ce31c19f416cd026def5fffc5b/cmd/cored/cosmoscmd/generate_devnet.go#L73)):*
> ```Go
> 				return errors.Wrap(err, "failed to get absolute path")
> 			}
> 			fmt.Printf("Generating devnet config to ouptut path: %s\n", outputPath)
> ```

should we use some logger here or fmt is ok ?
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 81 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqgqO7-lpiV1xgWqXE:-NjqgqO7-lpiV1xgWqXF:b-s37xal) ([raw file](https://github.com/CoreumFoundation/coreum/blob/324c4faf344b87ce31c19f416cd026def5fffc5b/cmd/cored/cosmoscmd/generate_devnet.go#L81)):*
> ```Go
> 				configDir := filepath.Join(validatorOutputPath, nodeConfigDirName)
> 				if err := os.MkdirAll(configDir, 0o700); err != nil {
> 					return errors.Wrap(err, "failed to make config directory")
> ```

here is a config structure we have for testnet 
Would be handy (for DevOps) if here we generate it in similar way

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/721)* status: all files reviewed, 9 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqhVtlEfYbLwYZWXxv:-NjqvexG0o20TfKakOD3:byr4flj) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

What I have just realized is that we are implementing this command and it is very similar to what we wanted to have as result of crust refactoring (no cored dependency etc)

I think we should consider exted this cmd later & crust<>coreum interactions to binary
</blockquote></details>

Right.

___
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 41 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-Njqfv2t1SVzecaLCEj-:-NjqvjXcDcNLeGeamwiV:b-g4eq49) ([raw file](https://github.com/CoreumFoundation/coreum/blob/324c4faf344b87ce31c19f416cd026def5fffc5b/cmd/cored/cosmoscmd/generate_devnet.go#L41)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

since --chain-id is a flag in this CLI it could be any network but not only devnet.
E.g `--localnet-1`

Shouldn't we use some generic name here ?
Or you prefer to keep it simple for now ?
</blockquote></details>

I prefer to keep it as is. Since it works with the devnet only, and we even validate the devnet chain-id flag in the command. 
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 45 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqgC-_-cVqUClWQXc5:-NjqvvuA9y40lzRa4qzv:b-98qrtz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/324c4faf344b87ce31c19f416cd026def5fffc5b/cmd/cored/cosmoscmd/generate_devnet.go#L45)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

What about genesis ? Does the command generate it also ?
</blockquote></details>

Yes, it generates all files including the genesis.
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 49 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqgM058fCB-WDT0vB0:-Njqvzfi-NBZRBK8C6PI:b262jrk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/324c4faf344b87ce31c19f416cd026def5fffc5b/cmd/cored/cosmoscmd/generate_devnet.go#L49)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I thought that we want to have denvet-2,3... ?
</blockquote></details>

For not it's very hard to archive. We need to discuss it.
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 73 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqgWXz7Qpv7TOC5Kpd:-Njqw4wu4o4yVuMbES6m:b-6vfyhe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/324c4faf344b87ce31c19f416cd026def5fffc5b/cmd/cored/cosmoscmd/generate_devnet.go#L73)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should we use some logger here or fmt is ok ?
</blockquote></details>

I use the `fmt` here similar to the cosmos SDK for the corresponding command. 
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 81 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqgqO7-lpiV1xgWqXE:-NjqwGZMAD3qlsDm_V0t:b80p4mw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/324c4faf344b87ce31c19f416cd026def5fffc5b/cmd/cored/cosmoscmd/generate_devnet.go#L81)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

here is a config structure we have for testnet 
Would be handy (for DevOps) if here we generate it in similar way


</blockquote></details>

And we already do it that way

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/721)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 120 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqRkVh9xLYWwD8tgrh:-Njr4s1O0y3vBCJQJKaT:b-6vll4j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/21310ecc6f09a59e9dc56b394690e22d4b0397f8/cmd/cored/cosmoscmd/generate_devnet.go#L120)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`validatorName` is the part of the path
</blockquote></details>

But here nothing depends on the name: `genDocBytes, err := network.EncodeGenesis()` and genesis by definition is the same for everyone

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/721)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 120 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqRkVh9xLYWwD8tgrh:-NjrjGWk46Und5XbJTUy:bn1a6nd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/21310ecc6f09a59e9dc56b394690e22d4b0397f8/cmd/cored/cosmoscmd/generate_devnet.go#L120)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But here nothing depends on the name: `genDocBytes, err := network.EncodeGenesis()` and genesis by definition is the same for everyone
</blockquote></details>

agree with Wojtek
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 41 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-Njqfv2t1SVzecaLCEj-:-NjrioFn6PUsdqfBhIEx:bpk7a3s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/324c4faf344b87ce31c19f416cd026def5fffc5b/cmd/cored/cosmoscmd/generate_devnet.go#L41)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I prefer to keep it as is. Since it works with the devnet only, and we even validate the devnet chain-id flag in the command.
</blockquote></details>

ok for this stage
for furhter improvements lets discuss separately
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 45 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqgC-_-cVqUClWQXc5:-Njrj3YXCbsxdk_nrihV:b-eyf2gd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/324c4faf344b87ce31c19f416cd026def5fffc5b/cmd/cored/cosmoscmd/generate_devnet.go#L45)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes, it generates all files including the genesis.
</blockquote></details>

nit:
then it is not only  `validators' and nodes' configuration files`

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/721)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 120 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqRkVh9xLYWwD8tgrh:-Njuln9u8OH-fckx3TF_:b57joj0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/21310ecc6f09a59e9dc56b394690e22d4b0397f8/cmd/cored/cosmoscmd/generate_devnet.go#L120)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

agree with Wojtek
</blockquote></details>

Now I see what you mean. Updated. 
___
*[`cmd/cored/cosmoscmd/generate_devnet.go` line 45 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/721#-NjqgC-_-cVqUClWQXc5:-Njul_Z09G-aU5xYXm7h:b-4zc5eo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/324c4faf344b87ce31c19f416cd026def5fffc5b/cmd/cored/cosmoscmd/generate_devnet.go#L45)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit:
then it is not only  `validators' and nodes' configuration files`
</blockquote></details>

But genesis is  a `configuration` file as well IMO. But updated to be more clear.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/721)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/721)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
