### PR TITLE
Remove recipient from MsgIssueFungibleToken message

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: 0 of 25 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/client/cli/tx.go` line 104 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/289#-NJ9RTNl6q3b8ksPJlb-:-NJ9RTNl6q3b8ksPJlb0:b-ajmmom) ([raw file](https://github.com/coreumfoundation/coreum/blob/54ac88c22e0eb8d5d4aec1bee13b8cedfe60e41a/x/asset/client/cli/tx.go#L104)):*
> ```Go
> 			if args[4] != "" {
> 				var ok bool
> 				initialAmount, ok = sdk.NewIntFromString(args[4])
> ```

You removed 3d arg but read 4th here. The 4th now is 3d.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`x/asset/client/cli/tx.go` line 104 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/289#-NJ9RTNl6q3b8ksPJlb-:-NJFgmjqBxcGmytWeQzI:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/54ac88c22e0eb8d5d4aec1bee13b8cedfe60e41a/x/asset/client/cli/tx.go#L104)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You removed 3d arg but read 4th here. The 4th now is 3d.
</blockquote></details>

Done.

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 5 of 5 files at r3, 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 16 of 18 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/asset/whitelist.go` line 28 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/289#-NJKd1z_71Bkj4XtWf3i:-NJKd1z_71Bkj4XtWf3j:b-t6esia) ([raw file](https://github.com/coreumfoundation/coreum/blob/fd870f4400645bafd11aa8970f1918f9c87768a5/integration-tests/asset/whitelist.go#L28)):*
> ```Go
> 				&assettypes.MsgIssueFungibleToken{},
> 				&assettypes.MsgSetWhitelistedLimitFungibleToken{},
> 				&assettypes.MsgSetWhitelistedLimitFungibleToken{},
> ```

why was second MsgSetWhitelistedLimitFungibleToken added?
___
*[`integration-tests/asset/whitelist.go` line 134 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/289#-NJKdxCZ5N2Ea_XKcafF:-NJKdxCZ5N2Ea_XKcafG:bl9iv8b) ([raw file](https://github.com/coreumfoundation/coreum/blob/fd870f4400645bafd11aa8970f1918f9c87768a5/integration-tests/asset/whitelist.go#L134)):*
> ```Go
> 		},
> 	},
> 		&assettypes.MsgSetWhitelistedLimitFungibleToken{
> ```

Instead of doing this, you may send tokens directly from issuer to random account, and you won't need additional messages

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/asset/whitelist.go` line 28 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/289#-NJKd1z_71Bkj4XtWf3i:-NJKf5Mk4zu0Yd0a-vu3:b-qoun3c) ([raw file](https://github.com/coreumfoundation/coreum/blob/fd870f4400645bafd11aa8970f1918f9c87768a5/integration-tests/asset/whitelist.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why was second MsgSetWhitelistedLimitFungibleToken added?
</blockquote></details>

we have to send a tx where we issue, setlimit and transfer. earlier it was just 1 issue that did all 3

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: 33 of 34 files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/asset/whitelist.go` line 28 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/289#-NJKd1z_71Bkj4XtWf3i:-NJKjTg48yOgneQooQHP:bb0hnfk) ([raw file](https://github.com/coreumfoundation/coreum/blob/fd870f4400645bafd11aa8970f1918f9c87768a5/integration-tests/asset/whitelist.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But this test is about verifying that whitelisting unwhitelistable token fails. So doing it once is enough
</blockquote></details>

I see your point, removed
___
*[`integration-tests/asset/whitelist.go` line 134 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/289#-NJKdxCZ5N2Ea_XKcafF:-NJKiwrWCy7yR23Oashf:bfzosy5) ([raw file](https://github.com/coreumfoundation/coreum/blob/fd870f4400645bafd11aa8970f1918f9c87768a5/integration-tests/asset/whitelist.go#L134)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Instead of doing this, you may send tokens directly from issuer to random account, and you won't need additional messages
</blockquote></details>

but that means that I have to refactor the test for the new logic (some of the assertions will fail). I am not refactoring the tests logic here, just removing a field.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`integration-tests/asset/whitelist.go` line 134 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/289#-NJKdxCZ5N2Ea_XKcafF:-NJKkdEV3lkWNXIfpxFD:batpvw) ([raw file](https://github.com/coreumfoundation/coreum/blob/fd870f4400645bafd11aa8970f1918f9c87768a5/integration-tests/asset/whitelist.go#L134)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

but that means that I have to refactor the test for the new logic (some of the assertions will fail). I am not refactoring the tests logic here, just removing a field. 
</blockquote></details>

But removing the field changes the logic of the test. Because you actually use tested functionality to prepare conditions for testing that functionality.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: 33 of 35 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/asset/whitelist.go` line 134 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/289#-NJKdxCZ5N2Ea_XKcafF:-NJKl73f4JD593kWxCgY:b500huj) ([raw file](https://github.com/coreumfoundation/coreum/blob/fd870f4400645bafd11aa8970f1918f9c87768a5/integration-tests/asset/whitelist.go#L134)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But removing the field changes the logic of the test. Because you actually use tested functionality to prepare conditions for testing that functionality.
</blockquote></details>

Ok let's refactor it. it will take longer to discuss it actually

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/index.go` line 30 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/289#-NJKv1Y82crTPCvajo0S:-NJKv1Y82crTPCvajo0T:b-6eki3k) ([raw file](https://github.com/coreumfoundation/coreum/blob/ffc9662bf5dd713506437d46b7c4d9c324cc6835/integration-tests/index.go#L30)):*
> ```Go
> 				asset.TestMintFungibleToken,
> 				asset.TestBurnFungibleToken,
> 				// auth.TestUnexpectedSequenceNumber,
> ```

leftover
___
*[`integration-tests/asset/whitelist.go` line 312 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/289#-NJKupA76N3Y2NEeuxD4:-NJKupA76N3Y2NEeuxD5:by2vi8a) ([raw file](https://github.com/coreumfoundation/coreum/blob/60bb7908a8476725670ece334ab81826d15a61b9/integration-tests/asset/whitelist.go#L312)):*
> ```Go
> 	requireT.Equal(sdk.NewCoin(denom, sdk.NewInt(19599)).String(), balance.GetBalance().String())
> 
> 	// Ensure that recipient holds 0
> ```

This is the case originaly requested by @ysv . I don't care much but for him it was important

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

___
*[`integration-tests/asset/whitelist.go` line 312 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/289#-NJKupA76N3Y2NEeuxD4:-NJKvuKs69Ljmwp7sKss:b-kq09so) ([raw file](https://github.com/coreumfoundation/coreum/blob/60bb7908a8476725670ece334ab81826d15a61b9/integration-tests/asset/whitelist.go#L312)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is the case originaly requested by @ysv . I don't care much but for him it was important
</blockquote></details>

I am not in the loop about the discussion so I am not sure what needs to be added here. 
since we are not transfering stuff from the recipient account, I removed that check. 
If I know what the discussion was, I will be able to write a check for it .
___
*[`integration-tests/index.go` line 30 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/289#-NJKv1Y82crTPCvajo0S:-NJKvsavE44zu05vajDu:bvth56w) ([raw file](https://github.com/coreumfoundation/coreum/blob/ffc9662bf5dd713506437d46b7c4d9c324cc6835/integration-tests/index.go#L30)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

leftover
</blockquote></details>

reverted

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

___
*[`integration-tests/asset/whitelist.go` line 312 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/289#-NJKupA76N3Y2NEeuxD4:-NJKwy---g45LD_KpX6i:b-o6lno) ([raw file](https://github.com/coreumfoundation/coreum/blob/60bb7908a8476725670ece334ab81826d15a61b9/integration-tests/asset/whitelist.go#L312)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I am not in the loop about the discussion so I am not sure what needs to be added here. 
since we are not transfering stuff from the recipient account, I removed that check. 
If I know what the discussion was, I will be able to write a check for it .
</blockquote></details>

The idea was to set both balance and whitelisted balance to 0 and verify that transferring to that account is impossible

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 14 of 14 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: 34 of 37 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/asset/whitelist.go` line 312 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/289#-NJKupA76N3Y2NEeuxD4:-NJL-2bR0qs3rJ4Cmndj:bsn582i) ([raw file](https://github.com/coreumfoundation/coreum/blob/60bb7908a8476725670ece334ab81826d15a61b9/integration-tests/asset/whitelist.go#L312)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The idea was to set both balance and whitelisted balance to 0 and verify that transferring to that account is impossible
</blockquote></details>

Added a test case for it.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — COMMENTED** [review]
> Reviewed 7 of 25 files at r1, 4 of 5 files at r3, 8 of 18 files at r4, 1 of 2 files at r5, 13 of 14 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 14 files at r9.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 14 of 14 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/289)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
