### PR TITLE
Upgrade vulnerable dependencies

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: 0 of 28 files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/807#-Nw4ZK3gEfEnnigPSioW:-Nw4ZK3gEfEnnigPSioX:bqt7wm8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4626924ebcf3d7fae61629fe87e2bb95b6a25b24/go.mod#L14)):*
> ```XML
> 	// TODO(v4) Remove it: https://github.com/cosmos/cosmos-sdk/issues/10409
> 	github.com/gin-gonic/gin => github.com/gin-gonic/gin v1.9.0
> 	// Remove this line after updating crust
> ```

1) Make the commet `FIXME: ...` please, for such case. 
2) Is the crust version you need already in PR ?
___
*[`build/go.mod` line 7 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/807#-Nw4ZkPXEQEhXNPrJyN0:-Nw4ZkPXEQEhXNPrJyN1:b-7qaytw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4626924ebcf3d7fae61629fe87e2bb95b6a25b24/build/go.mod#L7)):*
> ```XML
> replace (
> 	github.com/CoreumFoundation/coreum/v4 => ../
> 	golang.org/x/exp => golang.org/x/exp v0.0.0-20230711153332-06a737ee72cb
> ```

Is it the same `replace` as in coreum go.mod? If yes, leave same comment here as well please.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: 0 of 28 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/807#-Nw4ZK3gEfEnnigPSioW:-Nw89Shi2yRPZW8VfkJ2:b9p30nr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4626924ebcf3d7fae61629fe87e2bb95b6a25b24/go.mod#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

1) Make the commet `FIXME: ...` please, for such case. 
2) Is the crust version you need already in PR ?
</blockquote></details>

1. Fixed
2. Yes
___
*[`build/go.mod` line 7 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/807#-Nw4ZkPXEQEhXNPrJyN0:-Nw89WDvErSpEcqkLT6u:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4626924ebcf3d7fae61629fe87e2bb95b6a25b24/build/go.mod#L7)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is it the same `replace` as in coreum go.mod? If yes, leave same comment here as well please.
</blockquote></details>

Done.

**Review by miladz68 — DISMISSED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: 21 of 28 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/807#-Nw4ZK3gEfEnnigPSioW:-NwKUrYq4a9wvCTA79pf:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4626924ebcf3d7fae61629fe87e2bb95b6a25b24/go.mod#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

So you can import it aready by hash. And leave TODO to update later, isn't it?
</blockquote></details>

Done.

**Review by miladz68 — DISMISSED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 21 of 28 files at r1, 4 of 7 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 21 of 28 files at r1, 4 of 7 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/807#-NwQCBID2DqtctUQWhTE:-NwQCBID2DqtctUQWhTF:bjuz18v) (no related file):*
Lets add @keyleu to review rust changes

___

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @masihyeganeh, and @wojtek-coreum)

**Review by keyleu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @masihyeganeh and @wojtek-coreum)

___
*[`integration-tests/contracts/modules/bank-send/Cargo.toml` line 31 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/807#-NwddIT-8Wr6SunJpU7n:-NwddIT-8Wr6SunJpU7o:budacmw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3fdc0eeb75f6b154b81cc30a3619e3321533cd41/integration-tests/contracts/modules/bank-send/Cargo.toml#L31)):*
> ```TOML
> 
> [dependencies]
> cosmwasm-std = "1.2.3"
> ```

1.5.3 here

**Review by miladz68 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh and @wojtek-coreum)

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: 27 of 29 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/807#-NwQCBID2DqtctUQWhTE:-NwdxOvp2qF0K3GoPgNM:b-896fix) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Lets add @keyleu to review rust changes
</blockquote></details>

Done.

___
___
*[`integration-tests/contracts/modules/bank-send/Cargo.toml` line 31 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/807#-NwddIT-8Wr6SunJpU7n:-NwdxNuzDmCoHI1f9uxv:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/33d9de21c15825fae47015e4ada79669552590bb/integration-tests/contracts/modules/bank-send/Cargo.toml#L31)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

1.5.3 here
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu and @wojtek-coreum)

**Review by keyleu — COMMENTED** [review]
> Reviewed 20 of 28 files at r1, 4 of 7 files at r4, 3 of 3 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

**Review by keyleu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 3 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/807)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
