### PR TITLE
Implement DEX order storing with ordered price represented as num/exponent

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Implement DEX order storing with ordered price represented as num/exponent

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/902)

### CODE REVIEW

**Review by masihyeganeh — COMMENTED** [review]
I left some non-blocking comments, and I see some TODOs that are better to be addressed before merging

> Reviewed 13 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/902#-:-O0xwIwFE8L-r6dZk50F:bkmkdea)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`pkg/math/big/int.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/902#-O0xqpdQEPRoBK3vMJNc:-O0xqpdQEPRoBK3vMJNd:b-t6jgjs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2297fccd8800d11bbda77ea0f84bffeb147d073/pkg/math/big/int.go#L16)):*
> ```Go
> 
> // IntTenToThePower returns 10 to the power of x.
> func IntTenToThePower(x *big.Int) *big.Int {
> ```

I'm suggesting to have a more general function that calculates N to the power of M, and use Currying to pass N and receive this function in return
___
*[`pkg/store/ordered_bytes.go` line 46 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/902#-O0xsOTO7KMSIjECcHeQ:-O0xsOTO7KMSIjECcHeR:buadk8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2297fccd8800d11bbda77ea0f84bffeb147d073/pkg/store/ordered_bytes.go#L46)):*
> ```Go
> 		return 0, nil, errors.Errorf("invalid bytes length, min %d", Uint8OrderedBytesSize)
> 	}
> 	return b[0], b[Uint8OrderedBytesSize:], nil
> ```

The binary packages has nice functions dedicated to these types of bytes manipulation. Isn't it better to use them in every function here?
___
*[`pkg/store/ordered_bytes.go` line 51 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/902#-O0xs31020xfhrtT-kS7:-O0xs31020xfhrtT-kS8:b-ecb65y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2297fccd8800d11bbda77ea0f84bffeb147d073/pkg/store/ordered_bytes.go#L51)):*
> ```Go
> // AppendUint64ToOrderedBytes converts uint64 into ordered bytes and appends it to bytes array.
> func AppendUint64ToOrderedBytes(b []byte, v uint64) []byte {
> 	return binary.BigEndian.AppendUint64(b, v)
> ```

Are you sure about this endianness? Yesterday we discussed that LittleEndian is right to preserve the ordering

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/902)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @ysv)

___
*[`pkg/math/big/int.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/902#-O0xqpdQEPRoBK3vMJNc:-O10R9BA-cz9LCVdpkoB:b-f6l449) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2297fccd8800d11bbda77ea0f84bffeb147d073/pkg/math/big/int.go#L16)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I'm suggesting to have a more general function that calculates N to the power of M, and use Currying to pass N and receive this function in return
</blockquote></details>

I need just`TenToThePower` now, and that function is quite popular :-). Later once I need just power func, I'll add it and reuse. 
___
*[`pkg/store/ordered_bytes.go` line 46 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/902#-O0xsOTO7KMSIjECcHeQ:-O10S-J7CG4qwTRJ0lQs:bgytdop) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2297fccd8800d11bbda77ea0f84bffeb147d073/pkg/store/ordered_bytes.go#L46)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

The binary packages has nice functions dedicated to these types of bytes manipulation. Isn't it better to use them in every function here?
</blockquote></details>

Which exectly? 
___
*[`pkg/store/ordered_bytes.go` line 51 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/902#-O0xs31020xfhrtT-kS7:-O10RfKc2CP9SuIbDB1J:b-3ntzc5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2297fccd8800d11bbda77ea0f84bffeb147d073/pkg/store/ordered_bytes.go#L51)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Are you sure about this endianness? Yesterday we discussed that LittleEndian is right to preserve the ordering
</blockquote></details>

Actually, we discussed excaly BigEndian yesterday. And we already use it for the ordering BTW in the delay module.

**Review by dzmitryhil — COMMENTED** [review]
The TODOs will be addressed in the different tasks.

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/902#-:-O110OjJ7Gr9otgcOsp_:brft0jy)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/902)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`pkg/store/ordered_bytes.go` line 46 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/902#-O0xsOTO7KMSIjECcHeQ:-O11ahux71X86FIe0ZeL:b-z2gl8x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2297fccd8800d11bbda77ea0f84bffeb147d073/pkg/store/ordered_bytes.go#L46)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Which exectly?
</blockquote></details>

Everywhere you're reading from bytes to well known type or writing back. It is just a suggestion to refactor this file to wrap a []byte parameter and manipulate it only using binary functions. But your implementation works well as is. Just a style thing

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 3 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/902)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
