### PR TITLE
Run Cosmos relayer process inside `TestIBCCallFromSmartContract` integration test

### PR DESCRIPTION
**Pull request by ysv**
# Description

This PR changes TestIBCCallFromSmartContract to start and stop cosmos relayer inside test.
We need this to fully remove Cosmos Relayer from crust because that is the only place where we need it.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/673)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/673)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/ibc.go` line 69 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/673#-NgrODdhBIe7dGsbuhzG:-NgrODdhBIe7dGsbuhzH:bv585wm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31ba274276350b5bacec523de152d10634a135ef/integration-tests/ibc/ibc.go#L69)):*
> ```Go
> 	pathName := fmt.Sprintf("%s-%s", srcChain.ChainSettings.ChainID, dstChain.ChainSettings.ChainID)
> 
> 	// port name samples:
> ```

Why do we need that here?
___
*[`integration-tests/ibc/ibc.go` line 110 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/673#-NgrOUGh9-vGOl8amuCi:-NgrOUGh9-vGOl8amuCj:b5mqpue) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31ba274276350b5bacec523de152d10634a135ef/integration-tests/ibc/ibc.go#L110)):*
> ```Go
> 	go func() {
> 		err := <-relErrCh
> 		if !errors.Is(err, context.Canceled) {
> ```

Why do you ignore all errors a part form `context.Canceled` ?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/673)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/ibc/ibc.go` line 69 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/673#-NgrODdhBIe7dGsbuhzG:-Ngr_Uim9fVQRZ99MUt6:b-hfpv0l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31ba274276350b5bacec523de152d10634a135ef/integration-tests/ibc/ibc.go#L69)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we need that here?
</blockquote></details>

removed
___
*[`integration-tests/ibc/ibc.go` line 110 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/673#-NgrOUGh9-vGOl8amuCi:-Ngr_Wl_0fSIStdgxsoK:b-401i4l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31ba274276350b5bacec523de152d10634a135ef/integration-tests/ibc/ibc.go#L110)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you ignore all errors a part form `context.Canceled` ?
</blockquote></details>

fixed, good point

The idea is to ignore context.Canceled and don't report it as test failure but do report all other errors

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/673)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/673)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/ibc/ibc.go` line 110 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/673#-NgsJUpDEx0fbybFCVJM:-NgsJUpDEx0fbybFCVJN:br51xvh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0af05ece99e641cc2d052e19a4b2dec815ab9571/integration-tests/ibc/ibc.go#L110)):*
> ```Go
> 			return
> 		}
> 		require.NoError(t, err, "Cosmos Relayer start error")
> ```

`require.*` functions don't work as expected inside goroutines and cannot be used there
___
*[`integration-tests/ibc/wasm_test.go` line 162 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/673#-NgsJq9K1gi8WyB6nf6A:-NgsJq9K1gi8WyB6nf6B:b-n49iom) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0af05ece99e641cc2d052e19a4b2dec815ab9571/integration-tests/ibc/wasm_test.go#L162)):*
> ```Go
> // TestIBCCallFromSmartContract tests the WASM contract calls via WASM IBC channel.
> func TestIBCCallFromSmartContract(t *testing.T) {
> 	// Temporary skip this test because it is incompatible with crust but crust PR needs changes from coreum.
> ```

Add TODO or FIXME here

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/673)* status: all files reviewed, 3 unresolved discussions (waiting on @ysv)

___
*[`integration-tests/ibc/ibc.go` line 110 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/673#-NgrOUGh9-vGOl8amuCi:-NgsQU1C7kiztwths3pB:bayx378) ([raw file](https://github.com/CoreumFoundation/coreum/blob/31ba274276350b5bacec523de152d10634a135ef/integration-tests/ibc/ibc.go#L110)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

fixed, good point

The idea is to ignore context.Canceled and don't report it as test failure but do report all other errors
</blockquote></details>

With this I'm OK.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/673)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/673#-NgxJ8_U1gx_dtHZRiZh:-NgxJ8_U1gx_dtHZRiZi:b-t225hg) (no related file):*
It seems that we don't need these changes

___

**Comment by ysv** [comment]
Not needed
Relaying via Hermes works

**Pull request closed without merging**
