### PR TITLE
Improve DEX place-order CLI

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

* Add detailed examples for the DEX `place-order` CLI.
* Use default string representation for all DEX enums.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1050)

### CODE REVIEW

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1050)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/dex/client/cli/tx.go` line 71 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/1050#-ODzKPI-0AHKCBmcKDqh:-ODzKPI-0AHKCBmcKDqi:bqiurq4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ae5be2122871fcf95ce5c8730084a8dac778011b/x/dex/client/cli/tx.go#L71)):*
> ```Go
> 
> Example:
> $ %s tx %s cored tx dex place-order ORDER_TYPE_LIMIT "my-order-id1" denom1 denom2 1000 SIDE_SELL --price 12e-1 --time-in-force=TIME_IN_FORCE_GTC --from [sender]
> ```

The `%s tx %s` will produce `cored tx dex`. You don't need to add it again

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1050)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`x/dex/client/cli/tx.go` line 71 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/1050#-ODzKPI-0AHKCBmcKDqh:-ODzUiT1EnsCAQ4RcK2V:b-8ezbo2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ae5be2122871fcf95ce5c8730084a8dac778011b/x/dex/client/cli/tx.go#L71)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

The `%s tx %s` will produce `cored tx dex`. You don't need to add it again
</blockquote></details>

Agree, updated.

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1050)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1050)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1050)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
