### PR TITLE
Remove `znet` environment on integration test failure

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/895)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/895)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @masihyeganeh, @miladz68, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/895)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`build/coreum/tests.go` line 131 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/895#-O-uAnMB9Vb_-vWlZBdo:-O-uAnMB9Vb_-vWlZBdp:bh0z6dw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7fa39b3f2cb0aef594d4c24fec45f60d2afa4d91/build/coreum/tests.go#L131)):*
> ```Go
> 	}
> 
> 	return nil
> ```

I guess you wanted to return retErr and not nil ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/895)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`build/coreum/tests.go` line 131 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/895#-O-uAnMB9Vb_-vWlZBdo:-O-uI4GuCFA2vLKQBmWA:b-xmbxob) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7fa39b3f2cb0aef594d4c24fec45f60d2afa4d91/build/coreum/tests.go#L131)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I guess you wanted to return retErr and not nil ?
</blockquote></details>

no, I want to return `nil`

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/895)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/895)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

**Pull request closed without merging**
