### PR TITLE
Integrate cosmos-sdk group module

### PR DESCRIPTION
**Pull request by ysv**
# Description

This PR integrates new cosmos-sdk `group` module including:
- integration tests
- deterministicgas
- upgrade v3 integration

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/679)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/679)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`app/app.go` line 194 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/679#-Nh6yith5-AZ0NzJjNL6:-Nh6yith5-AZ0NzJjNL7:bdcy9bb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/db456aa35a9ae97cc91d8ce7053818b9d8ff2921/app/app.go#L194)):*
> ```Go
> 		slashing.AppModuleBasic{},
> 		feegrantmodule.AppModuleBasic{},
> 		groupmodule.AppModuleBasic{},
> ```

I added group module in the same sequence as ignite puts it when generating a new project. Is it correct approach ?
___
*[`app/app.go` line 556 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/679#-Nh7-GbhEVn-sKzwfL0y:-Nh7-GbhEVn-sKzwfL0z:b-ntyhgn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/db456aa35a9ae97cc91d8ce7053818b9d8ff2921/app/app.go#L556)):*
> ```Go
> 	)
> 
> 	groupConfig := group.DefaultConfig()
> ```

note: there are no params for this module. Only this config

**Review by miladz68 — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/679)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/679#-NhBDHvhBROywqec4XRK:-NhBDHvhBROywqec4XRL:b9t3qwj) (no related file):*
You probably need to add storage key of the module to upgrade v3

___
___
*[`app/app.go` line 194 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/679#-Nh6yith5-AZ0NzJjNL6:-NhB48zl1CfmJhzEPFmI:b-dhke1b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/db456aa35a9ae97cc91d8ce7053818b9d8ff2921/app/app.go#L194)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I added group module in the same sequence as ignite puts it when generating a new project. Is it correct approach ?
</blockquote></details>

I don't think it matters, it only matters in the ordering of Begin and End blocker, only if this modules depends on another module.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/679)* status: all files reviewed, 5 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`app/app.go` line 110 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/679#-NhQKsg82vvC4zxmlssy:-NhQKsg82vvC4zxmlssz:b-2qc1im) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7e7c1b3d1b7c4ee84291f8cb04840c13281edcc2/app/app.go#L110)):*
> ```Go
> 	"github.com/spf13/cast"
> 
> 	"github.com/cosmos/cosmos-sdk/x/nft"
> ```

Add it after the cosmos imports.
___
*[`integration-tests/modules/group_test.go` line 211 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/679#-NhQLvBE3TfLFTQJpnHU:-NhQLvBE3TfLFTQJpnHV:b-5ld489) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7e7c1b3d1b7c4ee84291f8cb04840c13281edcc2/integration-tests/modules/group_test.go#L211)):*
> ```Go
> 			&group.MsgCreateGroupWithPolicy{},
> 			&group.MsgCreateGroupWithPolicy{},
> 			&group.MsgCreateGroupWithPolicy{}, // fixme
> ```

`// fixme` ?
___
*[`x/deterministicgas/config.go` line 129 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/679#-NhQM9cu4PuswzkX05e6:-NhQM9cu4PuswzkX05e7:bypwtfx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7e7c1b3d1b7c4ee84291f8cb04840c13281edcc2/x/deterministicgas/config.go#L129)):*
> ```Go
> 		MsgToMsgURL(&govtypesv1.MsgDeposit{}): constantGasFunc(52000),
> 
> 		// group // FIXME: Find reasonable values for other msg types.
> ```

`FIXME` ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/679)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/679#-NhBDHvhBROywqec4XRK:-NhQMF-PC2VWxS1f7nOC:byr4flj) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

You probably need to add storage key of the module to upgrade v3
</blockquote></details>

Right.

___

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/679)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/modules/group_test.go` line 279 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/679#-NhaUlfU7QTx13f0GaPQ:-NhaUlfU7QTx13f0GaPR:b-nxn7pf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7e7c1b3d1b7c4ee84291f8cb04840c13281edcc2/integration-tests/modules/group_test.go#L279)):*
> ```Go
> 			{
> 				Address: groupMembers[0].Address,
> 				Weight:  "0", // to remove member we should set it's weight to 0
> ```

it's -> its

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/679)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/679#-NhBDHvhBROywqec4XRK:-NhgwFmoCLhTnmXoXaM_:b-896fix) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Right.
</blockquote></details>

Done.

___
___
*[`app/app.go` line 110 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/679#-NhQKsg82vvC4zxmlssy:-Nhgw3LeBFafuDoAzMoG:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7e7c1b3d1b7c4ee84291f8cb04840c13281edcc2/app/app.go#L110)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Add it after the cosmos imports.
</blockquote></details>

Done.
___
*[`integration-tests/modules/group_test.go` line 211 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/679#-NhQLvBE3TfLFTQJpnHU:-Nhgw8Bt2_hu95cOqhOB:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7e7c1b3d1b7c4ee84291f8cb04840c13281edcc2/integration-tests/modules/group_test.go#L211)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`// fixme` ?
</blockquote></details>

Done.
___
*[`integration-tests/modules/group_test.go` line 279 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/679#-NhaUlfU7QTx13f0GaPQ:-Nhgw9RR1oFr1iNvyR6l:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7e7c1b3d1b7c4ee84291f8cb04840c13281edcc2/integration-tests/modules/group_test.go#L279)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

it's -> its
</blockquote></details>

Done.
___
*[`x/deterministicgas/config.go` line 129 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/679#-NhQM9cu4PuswzkX05e6:-NhgwBJ76usOPVrwlalx:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7e7c1b3d1b7c4ee84291f8cb04840c13281edcc2/x/deterministicgas/config.go#L129)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`FIXME` ?
</blockquote></details>

Done.

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/679)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil and @miladz68)

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/679)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/679)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/679)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
