### PR TITLE
Read wasm vm options from app and cli params

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/166)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/166)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`cmd/cored/cosmoscmd/root.go` line 407 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/166#-NBkwzlX8ow7oG4INmQl:-NBkwzlX8ow7oG4INmQm:b-2lvil5) ([raw file](https://github.com/coreumfoundation/coreum/blob/2926f79d452d42816d843910336f7bf4f68b3381/cmd/cored/cosmoscmd/root.go#L407)):*
> ```Go
> 
> 	// WASMConfig defines configuration for the wasm module.
> 	type WASMConfig struct {
> ```

@miladz68 @ysv should it become a part of our NetworkConfig?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/166)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`cmd/cored/cosmoscmd/root.go` line 407 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/166#-NBkwzlX8ow7oG4INmQl:-NBlDNmZ8EAr2kEjZ7vF:b-41h6ju) ([raw file](https://github.com/coreumfoundation/coreum/blob/2926f79d452d42816d843910336f7bf4f68b3381/cmd/cored/cosmoscmd/root.go#L407)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@miladz68 @ysv should it become a part of our NetworkConfig?
</blockquote></details>

Those are the default app values, which might be different per node. The NetworkConfig contains the values which must be same.

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/166)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/166)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @ysv)

**Pull request merged**
