### PR TITLE
Minor changes in naming used to test upgrades

### PR DESCRIPTION
**Pull request by wojtek-coreum**
@ysv This PR addresses your comments in https://reviewable.io/reviews/CoreumFoundation/coreum/223

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/244)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/244)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/244)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/244)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/244)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
