### PR TITLE
Update query handler and separate contracts with legacy bindings and stargate/grpc for transactions

### PR DESCRIPTION
**Pull request by keyleu**
# Description

- As discussed, we're deprecating the wasm_handler. This PR separates contracts for both asset FT and asset NFT into two contracts, one using the proto types and stargate (grpc when we upgrade to v50 and cosmwasm 2.0) for transactions and one using the handler (which we won't keep updating at the moment).

- The queries we will deprecate them when we upgrade because of the discussion regarding how stargate queries are marshalled currently, so for now we keep using the handler for the queries (which we needed to update anyways for backward compatibility with the Data field)

- Updated the wasm_handler queier to work with DataDynamic types.
- Added examples of doing Clawback from Smart Contract.

- Left to do for the future, in next upgrade: Whitelist Stargate queries and write tests in the new FT/NFT contracts.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/827)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/827)* status: 0 of 28 files reviewed, 3 unresolved discussions (waiting on @keyleu, @masihyeganeh, @miladz68, and @ysv)

___
*[`integration-tests/contracts/modules/ft/src/contract.rs` line 331 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/827#-NxNPJhr-PzeEK_hRUn9:-NxNPJhr-PzeEK_hRUnA:bl370zj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b0a63af56ffd1edc65270b51f70e9907a991661/integration-tests/contracts/modules/ft/src/contract.rs#L331)):*
> ```XML
> 
>     Ok(Response::new()
>         .add_attribute("method", "globally_unfreeze")
> ```

`clawback`
___
*[`x/wasm/handler/query.go` line 668 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/827#-NxNRRhjEYw9OuLwo2fW:-NxNRRhjEYw9OuLwo2fX:b-5ik64v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b0a63af56ffd1edc65270b51f70e9907a991661/x/wasm/handler/query.go#L668)):*
> ```Go
> }
> 
> func unmarshalData(data *codectypes.Any) (string, error) {
> ```

Use switch instead
```func unmarshalData(data *codectypes.Any) (string, error) {
	switch data.TypeUrl {
	case "/" + proto.MessageName((*assetnfttypes.DataBytes)(nil)):
		var datab assetnfttypes.DataBytes
		err := proto.Unmarshal(data.Value, &datab)
		if err != nil {
			return "", errors.WithStack(err)
		}
		return base64.StdEncoding.EncodeToString(datab.Data), nil
	case "/" + proto.MessageName((*assetnfttypes.DataDynamic)(nil)):
		var datadynamic assetnfttypes.DataDynamic
		err := proto.Unmarshal(data.Value, &datadynamic)
		if err != nil {
			return "", errors.WithStack(err)
		}
		bytes, err := datadynamic.Marshal()
		if err != nil {
			return "", errors.WithStack(err)
		}
		return base64.StdEncoding.EncodeToString(bytes), nil
	default:
		return "", errors.Errorf("unsupported data type %s", data.TypeUrl)
	}
}


```
___
*[`x/wasm/handler/query.go` line 668 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/827#-NxNRg499a3pTUxSsE3j:-NxNRg499a3pTUxSsE3k:b-at9x8g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b0a63af56ffd1edc65270b51f70e9907a991661/x/wasm/handler/query.go#L668)):*
> ```Go
> }
> 
> func unmarshalData(data *codectypes.Any) (string, error) {
> ```

I see that you use the `unmarshalData` for both class data and NFT data, and it might be OK, but be attentive, with the transactions, since the DataDynamic is for the NFT data only !!!

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/827)* status: 0 of 28 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`integration-tests/contracts/modules/ft/src/contract.rs` line 331 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/827#-NxNPJhr-PzeEK_hRUn9:-NxNzrzFDJtYcDNXHUfu:b-886gsx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b0a63af56ffd1edc65270b51f70e9907a991661/integration-tests/contracts/modules/ft/src/contract.rs#L331)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`clawback`
</blockquote></details>

Fixed
___
*[`x/wasm/handler/query.go` line 668 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/827#-NxNRRhjEYw9OuLwo2fW:-NxO067Q8QGg0kIxy_L-:bac7da6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b0a63af56ffd1edc65270b51f70e9907a991661/x/wasm/handler/query.go#L668)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Use switch instead
```func unmarshalData(data *codectypes.Any) (string, error) {
	switch data.TypeUrl {
	case "/" + proto.MessageName((*assetnfttypes.DataBytes)(nil)):
		var datab assetnfttypes.DataBytes
		err := proto.Unmarshal(data.Value, &datab)
		if err != nil {
			return "", errors.WithStack(err)
		}
		return base64.StdEncoding.EncodeToString(datab.Data), nil
	case "/" + proto.MessageName((*assetnfttypes.DataDynamic)(nil)):
		var datadynamic assetnfttypes.DataDynamic
		err := proto.Unmarshal(data.Value, &datadynamic)
		if err != nil {
			return "", errors.WithStack(err)
		}
		bytes, err := datadynamic.Marshal()
		if err != nil {
			return "", errors.WithStack(err)
		}
		return base64.StdEncoding.EncodeToString(bytes), nil
	default:
		return "", errors.Errorf("unsupported data type %s", data.TypeUrl)
	}
}


```
</blockquote></details>

Changed, ty for this. Was actually looking for a way to get the name instead of writing it.
___
*[`x/wasm/handler/query.go` line 668 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/827#-NxNRg499a3pTUxSsE3j:-NxO09W329c53H7TXlvB:b-3pbjie) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7b0a63af56ffd1edc65270b51f70e9907a991661/x/wasm/handler/query.go#L668)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I see that you use the `unmarshalData` for both class data and NFT data, and it might be OK, but be attentive, with the transactions, since the DataDynamic is for the NFT data only !!!
</blockquote></details>

Yes, I'm aware of this, since it's only used for queries it's OK because it will always be DataBytes for Class. I did it to not create unnecessary duplication of code.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/827)* status: 0 of 28 files reviewed, all discussions resolved (waiting on @masihyeganeh, @miladz68, and @ysv)

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 26 of 28 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/827)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @ysv)

___
*[`integration-tests/contracts/modules/ft-legacy/Cargo.toml` line 38 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/827#-NxkVOHt7n4RSElYSGe9:-NxkVOHt7n4RSElYSGeA:b-q3gwjm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1b3e6c9b60a9f8cf92408b3df4c074cfdcbb9339/integration-tests/contracts/modules/ft-legacy/Cargo.toml#L38)):*
> ```TOML
> thiserror = "1.0.50"
> # TODO(keyleu): Update dependency once final version of coreum-wasm-sdk crate is pushed
> coreum-wasm-sdk = { git = "https://github.com/CoreumFoundation/coreum-wasm-sdk.git", branch = "keyne/upgrade-wasm-sdk" }
> ```

I see that you are using `coreum-wasm-sdk = "0.2.4"` for ntf-legacy and the new branch for `ft-legacy`. I think it makes sense to actually use the old released version for both
___
*[`integration-tests/modules/wasm_test.go` line 1933 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/827#-NxkX47E8XRKBMIzG_-r:-NxkX47E8XRKBMIzG_-s:b7oispk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1b3e6c9b60a9f8cf92408b3df4c074cfdcbb9339/integration-tests/modules/wasm_test.go#L1933)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	classID := assetnfttypes.BuildClassID(issueClassReqNoWhitelist.Symbol, sdk.MustAccAddressFromBech32(contractAddrNoWhitelist)) //nolint:lll
> ```

You could actually work around the line limit by moving the parameters to a new line
___
*[`integration-tests/modules/wasm_test.go` line 2003 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/827#-NxkXNpe8QxSjz-lLBbr:-NxkXNpe8QxSjz-lLBbs:bo6z6m4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1b3e6c9b60a9f8cf92408b3df4c074cfdcbb9339/integration-tests/modules/wasm_test.go#L2003)):*
> ```Go
> 
> 	// Mint a mutable NFT with both Owner and Issuer as editors
> ```

nit: unnecessary blank line

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/827)* status: 24 of 28 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`integration-tests/contracts/modules/ft-legacy/Cargo.toml` line 38 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/827#-NxkVOHt7n4RSElYSGe9:-Nxl1R4EAfzOBkk9OfbC:b-kxnvn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1b3e6c9b60a9f8cf92408b3df4c074cfdcbb9339/integration-tests/contracts/modules/ft-legacy/Cargo.toml#L38)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I see that you are using `coreum-wasm-sdk = "0.2.4"` for ntf-legacy and the new branch for `ft-legacy`. I think it makes sense to actually use the old released version for both
</blockquote></details>

Actually need it for ft-legacy because I added the globally_frozen field to Token which wasn't present there (nothing was added to nft).
___
*[`integration-tests/modules/wasm_test.go` line 1933 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/827#-NxkX47E8XRKBMIzG_-r:-Nxl7Ptm315Y_u-YGcb7:bt2vr1b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1b3e6c9b60a9f8cf92408b3df4c074cfdcbb9339/integration-tests/modules/wasm_test.go#L1933)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

You could actually work around the line limit by moving the parameters to a new line
</blockquote></details>

Fixed.
___
*[`integration-tests/modules/wasm_test.go` line 2003 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/827#-NxkXNpe8QxSjz-lLBbr:-Nxl7aRb2RPEfjlFeBKl:brpmqc3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1b3e6c9b60a9f8cf92408b3df4c074cfdcbb9339/integration-tests/modules/wasm_test.go#L2003)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

nit: unnecessary blank line
</blockquote></details>

removed.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/827)* status: 23 of 28 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/827)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
