### PR TITLE
Wasm asset NFT / native NFT integration

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/428)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/428)* status: all files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPvHMtX0Uqw-zWBhNlb:-NPvHMtX0Uqw-zWBhNlc:boah79u) (no related file):*
I remember that in the past we had a wasm contract which intentionally sent two submessages from a single call to test that it works. Now I see that we no longer have that test. Do you remember what happened?

___
___
*[`integration-tests/modules/wasm_test.go` line 155 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPvHwS9EAV4ITa1C-EO:-NPvHwS9EAV4ITa1C-EP:b-5qtana) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/integration-tests/modules/wasm_test.go#L155)):*
> ```Go
> const (
> 	// tx.
> 	nonFungibleTokenMethodMint                nonFungibleTokenMethod = "mint"
> ```

nftMethodMint
___
*[`integration-tests/modules/wasm_test.go` line 173 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPvI04V5CE4p9yoKHzl:-NPvI04V5CE4p9yoKHzm:brl4ip) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/integration-tests/modules/wasm_test.go#L173)):*
> ```Go
> 
> //nolint:tagliatelle
> type nonFungibleTokenClass struct {
> ```

nftClass
___
*[`integration-tests/modules/testdata/wasm/nft/src/contract.rs` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPvCASVEcuguB4bZXqV:-NPvCASVEcuguB4bZXqW:b3za0wv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/integration-tests/modules/testdata/wasm/nft/src/contract.rs#L1)):*
> ```XML
> use coreum_wasm_sdk::assetnft::{
> ```

instead of importing everything like here with aliases I would prefer to have just this:

```rs
use coreum_wasm_sdk::assetnft;
```

and then e.g.:

```rs
assetnft::Msg::IssueClass {
    // ...
}
```

This is what namespaces are for, and by creating aliases for all the imported types you reinvent the wheel here.
___
*[`integration-tests/modules/testdata/wasm/nft/src/contract.rs` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPvCziA5l26RiFthHg8:-NPvCziA5l26RiFthHg9:b2nhjzr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/integration-tests/modules/testdata/wasm/nft/src/contract.rs#L124)):*
> ```XML
>     Owner { id: String },
>     Supply {},
>     Nft { id: String }, // we use Nft not NFT since NFT is decoded as n_f_t
> ```

NFT
___
*[`integration-tests/modules/testdata/wasm/sdk/src/assetnft.rs` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPv6UfBCg9DImUrqKwP:-NPv6UfBCg9DImUrqKwQ:baxu63g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/integration-tests/modules/testdata/wasm/sdk/src/assetnft.rs#L14)):*
> ```XML
>     pub uri: Option<String>,
>     pub uri_hash: Option<String>,
>     pub data: Option<String>,
> ```

Wouldn't `Bytes` be a better choice than `String`?
___
*[`integration-tests/modules/testdata/wasm/sdk/src/nft.rs` line 11 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPv6bXc7PCk5UgeVI4v:-NPv6bXc7PCk5UgeVI4w:baxu63g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/integration-tests/modules/testdata/wasm/sdk/src/nft.rs#L11)):*
> ```XML
>     pub uri: Option<String>,
>     pub uri_hash: Option<String>,
>     pub data: Option<String>,
> ```

Wouldn't `Bytes` be a better choice than `String`?
___
*[`x/wasm/handler/custom.go` line 40 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPv78Qk2ij4DwgXEb9n:-NPv78Qk2ij4DwgXEb9o:b7opsqz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/x/wasm/handler/custom.go#L40)):*
> ```Go
> 	URI         string                       `json:"uri"`
> 	URIHash     string                       `json:"uri_hash"`
> 	Data        string                       `json:"data"`
> ```

why not []byte?
___
*[`x/wasm/handler/custom.go` line 105 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPv7CIK2N0lwNQyJ65G:-NPv7CIK2N0lwNQyJ65H:b7opsqz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/x/wasm/handler/custom.go#L105)):*
> ```Go
> 	URI         string                       `json:"uri"`
> 	URIHash     string                       `json:"uri_hash"`
> 	Data        string                       `json:"data"`
> ```

why not []byte?
___
*[`x/wasm/handler/custom.go` line 173 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPv7gmX9oJnaQJ39gHe:-NPv7gmX9oJnaQJ39gHf:b-jk2z4o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/x/wasm/handler/custom.go#L173)):*
> ```Go
> 				return nil, err
> 			}
> 			msgs := make([]sdk.Msg, 0)
> ```

```go
			if decodedMsg == nil {
				return nil, nil
			}

			if err := decodedMsg.ValidateBasic(); err != nil {
				return nil, errors.WithStack(err)
			}

			return []sdk.Msg{decodedMsg}, nil

```
___
*[`x/wasm/handler/custom.go` line 469 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPv9B1Z0qCJ4fIMHWQE:-NPv9B1Z0qCJ4fIMHWQF:ba9tkrk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/x/wasm/handler/custom.go#L469)):*
> ```Go
> }
> 
> func executeQuery[T, K any](
> ```

`K` is always a `[]byte`
___
*[`x/wasm/handler/custom.go` line 469 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPv9H1Y-nGgoUzGUj7e:-NPv9H1Y-nGgoUzGUj7f:bkyp3l9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/x/wasm/handler/custom.go#L469)):*
> ```Go
> }
> 
> func executeQuery[T, K any](
> ```

Instead of having `T` wouldn't it be simpler to accept `resp interface{}` and pass it to marshaller?

**Review by ysv — CHANGES_REQUESTED** [review]
`Wasm asset NFT + NFT and new design`
1. name is not really clear
2. NFT is repeated twice

> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-:-NPwJ7sYEuS5O9xFLtZj:bve4aq8)* status: all files reviewed, 16 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPvHMtX0Uqw-zWBhNlb:-NPwJK6W0dErI2WGkseS:bwww1rf) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We wanted to test that the wasm supports that functionality, and it's supported. So since we no longer have a use case for it, I removed that part during the contract rebuild. But if you guys @ysv @miladz68 @wojtek-coreum  consider it important I can add an additional method to check it.
</blockquote></details>

I prefer to keep it 

___
___
*[`integration-tests/modules/wasm_test.go` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPx71LvC_-CuGdEb06Y:-NPx71LvC_-CuGdEb06Z:b-q5i6su) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/integration-tests/modules/wasm_test.go#L39)):*
> ```Go
> 	fungibleTokenWASM []byte
> 	//go:embed testdata/wasm/nft/artifacts/nft.wasm
> 	nonFungibleTokenWASM []byte
> ```

minor: I would prefer to use ftWASM & nftWASM here
___
*[`integration-tests/modules/wasm_test.go` line 155 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPvHwS9EAV4ITa1C-EO:-NPx76LZ2NrK0YnHQKnL:b-9n8czv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/integration-tests/modules/wasm_test.go#L155)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still see old version
___
*[`integration-tests/modules/wasm_test.go` line 173 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPvI04V5CE4p9yoKHzl:-NPx7QeQCt5GzuBM5EvX:b2us19) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/integration-tests/modules/wasm_test.go#L173)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I agree everything should be renamed to ft/nft if possible
___
*[`integration-tests/modules/testdata/wasm/sdk/src/core.rs` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPx9HYU9ijyrDOlv5pe:-NPx9HYU9ijyrDOlv5pf:b4m1y8m) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/integration-tests/modules/testdata/wasm/sdk/src/core.rs#L1)):*
> ```XML
> use crate::{assetft, assetnft, nft};
> ```

minor: is this file named core because it is core for SDK or because of coreum ?
If this is related to coreum maybe `coreum.rs` ?
___
*[`integration-tests/modules/testdata/wasm/sdk/src/nft.rs` line 11 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPv6bXc7PCk5UgeVI4v:-NPx8Yex1nq7S7gL4xnK:b-8nwk5v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/integration-tests/modules/testdata/wasm/sdk/src/nft.rs#L11)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The `Bytes` is not a standard type. If you want to use it we need to find which to use `std::io::Bytes` or `bytes::Bytes` or something else. If you know which type fits here better let's use it.
@ysv @miladz68 what are your thoughts?

</blockquote></details>

Frankly speaking I'm not able to comment here

Probably bytes would be better but only if:
- we are sure which Bytes we should use
- it is common to use bytes in Rust
___
*[`x/wasm/handler/custom.go` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPxEENh-isc96CeIyR1:-NPxEENh-isc96CeIyR2:bftpcct) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/x/wasm/handler/custom.go#L1)):*
> ```Go
> package handler
> ```

I would probably prefer to split it into files because NFT & AssetNFT too similar & it is confusing
___
*[`x/wasm/handler/custom.go` line 34 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPxEi391wq5wEr_vYWp:-NPxEi391wq5wEr_vYWq:b-snv79x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/x/wasm/handler/custom.go#L34)):*
> ```Go
> //
> //nolint:tagliatelle // we keep the name same as consume
> type AssetNFTMsgIssueClass struct {
> ```

I would prefer to avoid usage of these types as much as possible 

At least add comments to them
___
*[`x/wasm/handler/custom.go` line 40 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPv78Qk2ij4DwgXEb9n:-NPx9U1hC-BXtzzxONJ3:bk2isci) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/x/wasm/handler/custom.go#L40)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

will be discussed in the first thread
</blockquote></details>

even if we use string on Rust side I would prefer to use []byte here if possible

**Review by wojtek-coreum — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/428)* status: 24 of 29 files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/wasm/handler/custom.go` line 469 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NPv9H1Y-nGgoUzGUj7e:-NQ0YIzVBsJp28DXc_FC:bhbzv4r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/140623905227bcc284909021cec222358fefddaf/x/wasm/handler/custom.go#L469)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

And why is it better? You will have the same code fore each if, IMO it isn't better.
</blockquote></details>

Exactly, this is the same code without additional indirection introduced by that function and callback

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 2 of 5 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/428)* status: 26 of 29 files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r3, 9 of 9 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/428)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`x/wasm/handler/message.go` line 33 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/428#-NQ19hlvBaQVOs6e8ard:-NQ19hlvBaQVOs6e8are:bqrxkpx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6b0dcc458e19816b2cc49361defc86d4354ec5d6/x/wasm/handler/message.go#L33)):*
> ```Go
> //
> //nolint:tagliatelle // we keep the name same as consume
> type AssetNFTMsgIssueClass struct {
> ```

we can keep these structures unexposed to outside world `assetNFTMsgIssueClass`

same for other structures

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/428)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 16 of 27 files at r1, 2 of 5 files at r3, 4 of 9 files at r5, 5 of 5 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/428)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
