### PR TITLE
Implemented skip unsafe flag for our integration tests

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/init.go` line 56 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NSoY0AJ7ECTJ39JWShh:-NSoY0AJ7ECTJ39JWShi:b67l2hr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7aaddc0fa2ffccb7872b4987d259bd2606e6dc2c/integration-tests/init.go#L56)):*
> ```Go
> 	flag.StringVar(&logFormat, "log-format", string(logger.ToolDefaultConfig.Format), "Format of logs produced by tests")
> 	flag.StringVar(&chainID, "chain-id", string(constant.ChainIDDev), "Which chain-id to use (coreum-devnet-1, coreum-testnet-1,...)")
> 	flag.BoolVar(&skipUnsafe, "skip-unsafe", true, "skip unsafe tests for example ones related to governance")
> ```

But how do we check that the flag is required?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/init.go` line 56 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NSoY0AJ7ECTJ39JWShh:-NSojQA06_RNyOgnhFQF:bwzia40) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7aaddc0fa2ffccb7872b4987d259bd2606e6dc2c/integration-tests/init.go#L56)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But how do we check that the flag is required?
</blockquote></details>

we don't check that it is required, but we default it true and rely on crust to ensure that it always false if you use crust (in CI). the default flag package does not have a method to ensure a flag is provided and we need to process cmd args manually to make sure it is provided which is a little ugly.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NSqxvET8twU3DIf1utj:-NSqxvET8twU3DIf1utk:b-1jh7ao) (no related file):*
Have you 100% checked all tests ?

___
___
*[`integration-tests/chain.go` line 171 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NSqx5hG2F8esQ50YPip:-NSqx5hG2F8esQ50YPiq:bfhewn0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7aaddc0fa2ffccb7872b4987d259bd2606e6dc2c/integration-tests/chain.go#L171)):*
> ```Go
> 
> // SetSkipUnsafe sets skip unsafe flag.
> func (c *Chain) SetSkipUnsafe(skipUnsafe bool) {
> ```

I disagree that it should be a method & field of chain
I see a better place for it: put this field into global variable `cfg`

and we can just make it function not method

```
func SkipUnsafe(t *testing.T) {
  if cfg.skipUnsafe {
   t.SkipNow()
  }
}
```

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NSqxvET8twU3DIf1utj:-NSth2oR7RfmeKDpzo6K:bwl853q) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Have you 100% checked all tests ?
</blockquote></details>

I have. 

___
___
*[`integration-tests/chain.go` line 171 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NSqx5hG2F8esQ50YPip:-NStii_SEwDp_Zt7PRc1:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7aaddc0fa2ffccb7872b4987d259bd2606e6dc2c/integration-tests/chain.go#L171)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I disagree that it should be a method & field of chain
I see a better place for it: put this field into global variable `cfg`

and we can just make it function not method

```
func SkipUnsafe(t *testing.T) {
  if cfg.skipUnsafe {
   t.SkipNow()
  }
}
```


</blockquote></details>

Done.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NSu2drV7sff3nB7YhP4:-NSu48_HBlU-bvVxRsoi:b53b5qy) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would say that it should be done the other way. Unsafe tests should be skipped by default and executed only if `--unsafe` flag is provided
</blockquote></details>

This has already been discussed
I had opinion similar to yours and Milad & Dzmitry suggested current behaviour 

Don't have strong opinion here. Could be discussed again if needed

___
___
*[`integration-tests/chain.go` line 172 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NSu4iGDD5vY6DBP5ddP:-NSu4iGE9L418hnrNk-Y:bws9txf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fde90f2f054b9cdef79102684df892f39ac702ff/integration-tests/chain.go#L172)):*
> ```Go
> // unsafe tests can only be run against a locally running chain since they modify parameters
> // of the chain.
> func (c Chain) SkipUnsafe(t *testing.T) {
> ```

doesn't make sense for me to make it a method of chain
just usual func is ok

side benefit is that you can call it right in the beginning of func then before initialization of chain variable

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/chain.go` line 172 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NSu4iGDD5vY6DBP5ddP:-NSuMTjOAMBYmQDjwpHX:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fde90f2f054b9cdef79102684df892f39ac702ff/integration-tests/chain.go#L172)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

doesn't make sense for me to make it a method of chain
just usual func is ok

side benefit is that you can call it right in the beginning of func then before initialization of chain variable
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: 1 of 10 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NSu2drV7sff3nB7YhP4:-NSuMmgB8kmGK1fzmBOt:b-8rvd5j) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

This has already been discussed
I had opinion similar to yours and Milad & Dzmitry suggested current behaviour 

Don't have strong opinion here. Could be discussed again if needed
</blockquote></details>

I think in 99% of cases boolean flag is used to set sth to true, not to false.

___

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NSu2drV7sff3nB7YhP4:-NTENmMj9tLbnwIk5e_j:bwsh5bl) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I think in 99% of cases boolean flag is used to set sth to true, not to false.
</blockquote></details>

@ysv how about we call the flag `run-unsafe` and keep the default value to `false` ?

___

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 9 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @silverspase)

___
*[`.github/workflows/ci.yml` line 19 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NTI1WcuETb-BUwmmnGe:-NTI1WcuETb-BUwmmnGf:bnftyy6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1d66057f494c8c0676ddb22441315023247da710/.github/workflows/ci.yml#L19)):*
> ```YAML
>           "build", 
>           "integration tests coreum-modules", 
>           # "integration tests coreum-upgrade", 
> ```

why is it needed?
___
*[`integration-tests/chain.go` line 175 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NTI1ua77T16eqHyTf1u:-NTI1ua77T16eqHyTf1v:b-9b3l2f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1d66057f494c8c0676ddb22441315023247da710/integration-tests/chain.go#L175)):*
> ```Go
> // unsafe tests can only be run against a locally running chain since they modify parameters
> // of the chain.
> func SkipUnsafe(t *testing.T) {
> ```

`chain.go` is not the best file for this function

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

___
*[`.github/workflows/ci.yml` line 19 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NTI1WcuETb-BUwmmnGe:-NTIZHId88C38VqrH8bc:b5y4wsp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1d66057f494c8c0676ddb22441315023247da710/.github/workflows/ci.yml#L19)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why is it needed?
</blockquote></details>

upgrade test is considered an unsafe test and we skip it, it means the upgrade action never takes place and the test fails. 
___
*[`integration-tests/chain.go` line 175 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NTI1ua77T16eqHyTf1u:-NTIhEm127rpwZuzm0AT:b-11h7q9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1d66057f494c8c0676ddb22441315023247da710/integration-tests/chain.go#L175)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`chain.go` is not the best file for this function
</blockquote></details>

none of the other files are good as well tbh.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

___
*[`.github/workflows/ci.yml` line 19 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NTI1WcuETb-BUwmmnGe:-NTIh_BTBYjMSvxA2GX-:b3l1maj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1d66057f494c8c0676ddb22441315023247da710/.github/workflows/ci.yml#L19)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

upgrade test is considered an unsafe test and we skip it, it means the upgrade action never takes place and the test fails. 
</blockquote></details>

we can enable it back after crust is integrated to run unsafe tests.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @silverspase)

___
*[`integration-tests/chain.go` line 175 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NTI1ua77T16eqHyTf1u:-NTInGdq69erOOCEmK1A:b-wcqtj7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1d66057f494c8c0676ddb22441315023247da710/integration-tests/chain.go#L175)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

none of the other files are good as well tbh. 
</blockquote></details>

You are right, let's create a new one like `testing.go`

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

___
*[`integration-tests/chain.go` line 175 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NTI1ua77T16eqHyTf1u:-NTIoqMd1UleINhoykx-:b-ck3tqn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1d66057f494c8c0676ddb22441315023247da710/integration-tests/chain.go#L175)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You are right, let's create a new one like `testing.go`
</blockquote></details>

but that is not a very informative name, how about `helpers.go` ?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @silverspase)

___
*[`integration-tests/chain.go` line 175 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NTI1ua77T16eqHyTf1u:-NTIy7k007Im3S4afQgK:bapsdta) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1d66057f494c8c0676ddb22441315023247da710/integration-tests/chain.go#L175)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

but that is not a very informative name, how about `helpers.go` ?
</blockquote></details>

entropies of both names are equal :D. Both are ok for me.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`integration-tests/chain.go` line 175 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NTI1ua77T16eqHyTf1u:-NTJUONG6AAWffFSEnBZ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1d66057f494c8c0676ddb22441315023247da710/integration-tests/chain.go#L175)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

entropies of both names are equal :D. Both are ok for me.
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/464#-NSu2drV7sff3nB7YhP4:-NTKHAfj9am0--UFIRvG:brqrncn) (no related file):*
`run-unsafe` makes a bit more sense for me so agree with Wojtek a bit more

> I think in 99% of cases boolean flag is used to set sth to true, not to false.
Because of this mostly

Still not critical and both options are acceptable for me

___

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/464)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
