### PR TITLE
Change WASM behaviour to default: burn vesting balance when instantiating contract

### PR DESCRIPTION
**Pull request by ysv**
…antiating contract

# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/741)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/741)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/741)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`testutil/integration/faucet.go` line 133 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/741#-NlP6Xv34gLkv6eCotw2:-NlRUgt44XWhskOKrILd:b-7vek00) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5faf37e4c2357e92410bc4843e9ee9e5c4c9895/testutil/integration/faucet.go#L133)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

it seems that we have some issue in faucet parallelism 
this tmp hotfix works & I will continue investigation later & push full fix on a separate PR
</blockquote></details>

Ok, is it the limit of the txs?

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/741)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/741)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

___
*[`testutil/integration/faucet.go` line 133 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/741#-NlP6Xv34gLkv6eCotw2:-NlSUv1P-eQidle_yAJF:bxwx1p4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5faf37e4c2357e92410bc4843e9ee9e5c4c9895/testutil/integration/faucet.go#L133)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Ok, is it the limit of the txs?
</blockquote></details>

limit of requests which are packed into a single tx
I would say it is number of outputs in tx but that is not 100% true because single request might contain multiple account

**Pull request merged**
