### PR TITLE
added init function to ibc integration tests package

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/init.go` line 30 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_XlwcUA2PGnKw8_HKt:-N_XlwcUA2PGnKw8_HKu:b-4kc3nx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/80c8a9d6c126a10a5114ee048c17b6cd69379fac/integration-tests/ibc/init.go#L30)):*
> ```Go
> 
> func parseIBCFlags() {
> 	flagSet := flag.NewFlagSet("ibc", flag.ExitOnError)
> ```

What is the purpose of that flag?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/init.go` line 30 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_XlwcUA2PGnKw8_HKt:-N_Xnyqm0udTrsf31tIz:bgjez66) ([raw file](https://github.com/CoreumFoundation/coreum/blob/80c8a9d6c126a10a5114ee048c17b6cd69379fac/integration-tests/ibc/init.go#L30)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the purpose of that flag?
</blockquote></details>

to parse ibc specific flags

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/init.go` line 30 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_XlwcUA2PGnKw8_HKt:-N_YtG8MAHOZxhXn5Dld:b-koweet) ([raw file](https://github.com/CoreumFoundation/coreum/blob/80c8a9d6c126a10a5114ee048c17b6cd69379fac/integration-tests/ibc/init.go#L30)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

moved them back to integrationtest package, since they errored out here. 
</blockquote></details>

Didn't get last comment, in what case they errors out?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/init.go` line 30 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_XlwcUA2PGnKw8_HKt:-N_ZKGfVBr73LUiisMIU:b-9mbbps) ([raw file](https://github.com/CoreumFoundation/coreum/blob/80c8a9d6c126a10a5114ee048c17b6cd69379fac/integration-tests/ibc/init.go#L30)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Didn't get last comment, in what case they errors out?
</blockquote></details>

if we start znet with integrationtest-module, then passing ibc info to test binary will error out.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_bf2yy77PYqUugbvoI:-N_bf2yy77PYqUugbvoJ:b-q57cr7) (no related file):*
I still encourage to consider lazy-loading. The less code in init the better

___
___
*[`integration-tests/init.go` line 50 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_bdibn4XNkosxDkvtZ:-N_bdibn4XNkosxDkvt_:b-gu3cco) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c82645c3672c3ffedb7d5a3e77c441b11a7e4e93/integration-tests/init.go#L50)):*
> ```Go
> var (
> 	ctx          context.Context
> 	ChainsHolder Chains
> ```

I liked "Chains" more

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/init.go` line 50 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_bdibn4XNkosxDkvtZ:-N_bmzk_0lfaWO_i7GhJ:bwag20h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c82645c3672c3ffedb7d5a3e77c441b11a7e4e93/integration-tests/init.go#L50)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I liked "Chains" more
</blockquote></details>

Me too

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_bf2yy77PYqUugbvoI:-N_c6obZEDPwWKdnHqKj:b-896fix) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I still encourage to consider lazy-loading. The less code in init the better
</blockquote></details>

Done.

___
___
*[`integration-tests/init.go` line 50 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_bdibn4XNkosxDkvtZ:-N_c6baLD6KMmnfmy3Sx:b-2ew4v0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c82645c3672c3ffedb7d5a3e77c441b11a7e4e93/integration-tests/init.go#L50)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Me too
</blockquote></details>

Me too. 
but suggest names for the struct so the name will not conflict with var name. I am out of ideas.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/init.go` line 50 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_bdibn4XNkosxDkvtZ:-N_h43vu4anxpALMupI_:b-1f4bai) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c82645c3672c3ffedb7d5a3e77c441b11a7e4e93/integration-tests/init.go#L50)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Me too. 
but suggest names for the struct so the name will not conflict with var name. I am out of ideas. 
</blockquote></details>

Decided to use NewCoreumTestingContext and NewChainsTestingContext for the initialisation.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/init.go` line 50 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_bdibn4XNkosxDkvtZ:-N_rlgqn5YnFHpCjc38h:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c82645c3672c3ffedb7d5a3e77c441b11a7e4e93/integration-tests/init.go#L50)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Decided to use NewCoreumTestingContext and NewChainsTestingContext for the initialisation. 
</blockquote></details>

Done.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/init.go` line 153 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_ruXOe0GKig2I7ZFdh:-N_ruXOe0GKig2I7ZFdi:b37ccj7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d7540b054be4a722a18ca379441148c566720d85/integration-tests/init.go#L153)):*
> ```Go
> 
> // GetGaiaChain returns the configured gaia chain.
> func GetGaiaChain(t *testing.T) Chain {
> ```

you keep these methods in integration-tests not ibc on purpose, right ?
Because I thought maybe it makes sense to move it to ibc.
On the other hand we should still keep flags in integration-tests 
___
*[`integration-tests/ibc/asset_ft_test.go` line 340 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_rtT9bCQr5HhpWLsZ8:-N_rtT9bCQr5HhpWLsZ9:b-nll4zs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d7540b054be4a722a18ca379441148c566720d85/integration-tests/ibc/asset_ft_test.go#L340)):*
> ```Go
> 	t.Parallel()
> 
> 	ctx, coreumChain := integrationtests.NewCoreumTestingContext(t)
> ```

when we were on the call I proposed idea to keep the interface of `NewCoreumTestingContext(t)` and trigger lazy loading inside it.

So NewCoreumTestingContext should still return chains as slice and call GetGaiaChain & GetOsmosisChain inside. The main idea was to keep same funcs & their interfaces.

Benefit of your approach is that you init what you actually need I think.

But if you prefer current version I'm ok to discuss.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/init.go` line 153 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_ruXOe0GKig2I7ZFdh:-N_s3MJxC6vQDLMG9TP7:b-46cnb2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d7540b054be4a722a18ca379441148c566720d85/integration-tests/init.go#L153)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

you keep these methods in integration-tests not ibc on purpose, right ?
Because I thought maybe it makes sense to move it to ibc.
On the other hand we should still keep flags in integration-tests 
</blockquote></details>

My understanding of the discussion on the call was that it makes sense to keep the flag definition and variable initialization in the same place, and not to distribute the logic. this was the argument against using separate init functions.
___
*[`integration-tests/ibc/asset_ft_test.go` line 340 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_rtT9bCQr5HhpWLsZ8:-N_s3xr_6SR_X-WgattJ:b7spzj4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d7540b054be4a722a18ca379441148c566720d85/integration-tests/ibc/asset_ft_test.go#L340)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

when we were on the call I proposed idea to keep the interface of `NewCoreumTestingContext(t)` and trigger lazy loading inside it.

So NewCoreumTestingContext should still return chains as slice and call GetGaiaChain & GetOsmosisChain inside. The main idea was to keep same funcs & their interfaces.

Benefit of your approach is that you init what you actually need I think.

But if you prefer current version I'm ok to discuss.
</blockquote></details>

since we are using lazy loading and defining new functions anyways, the struct is not really helpful anyways, so I decided to remove it.

**Review by ysv — DISMISSED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/init.go` line 153 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_sVObp5egZecWrEJYM:-N_sVObp5egZecWrEJYN:bihz41y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c6f5ff2985da82b24e808c87a017994fe32d0166/integration-tests/init.go#L153)):*
> ```Go
> 
> // GetGaiaChain returns the configured gaia chain.
> func GetGaiaChain(t *testing.T) Chain {
> ```

But we agreed to do the initialisation on `integrationtests.NewCoreumTestingContext(t)` 
@ysv right?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/init.go` line 153 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_sVObp5egZecWrEJYM:-N_sVXw2Bg5_zID4B3Q4:b51ei95) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c6f5ff2985da82b24e808c87a017994fe32d0166/integration-tests/init.go#L153)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But we agreed to do the initialisation on `integrationtests.NewCoreumTestingContext(t)` 
@ysv right?
</blockquote></details>

Same for the `integrationtests.NewChains`. In that case you won't even need to update tests.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/init.go` line 153 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_sVObp5egZecWrEJYM:-N_sWVEM8vlP6YVAQgOX:b-wmuqf4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c6f5ff2985da82b24e808c87a017994fe32d0166/integration-tests/init.go#L153)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Same for the `integrationtests.NewChains`. In that case you won't even need to update tests. 
</blockquote></details>

that would defeat the purpose of this PR, the purpose is to initialize the first time it is needed. if it is initialized in NewCoreumTestingContext, then it will error out in case IBC components are not started but znet.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/init.go` line 50 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_bdibn4XNkosxDkvtZ:-N_sqoBEDlgpAyQwFsPv:byb3kuj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c82645c3672c3ffedb7d5a3e77c441b11a7e4e93/integration-tests/init.go#L50)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Pushed new changes. review again
___
*[`integration-tests/init.go` line 153 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/574#-N_sVObp5egZecWrEJYM:-N_sepNi1d1ckdxDPGWP:byeleax) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c6f5ff2985da82b24e808c87a017994fe32d0166/integration-tests/init.go#L153)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

that would defeat the purpose of this PR, the purpose is to initialize the first time it is needed. if it is initialized in NewCoreumTestingContext, then it will error out in case IBC components are not started but znet. 
</blockquote></details>

agreed, new changes are pushed now

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451 and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451 and @wojtek-coreum)

**Review by miladz68 — COMMENTED** [review]
> Dismissed @wojtek-coreum from a discussion.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/574)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
