### PR TITLE
Fixed todos in preparation for v5 release

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/884)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/884)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/884)* status: all files reviewed, 3 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/884#-O-LEECC9uZIILhpUdGp:-O-LDDtc0ZtSS_w3HzAw:b-9os8l) (no related file):*
I suggest to add todos in all the new places requiring inspection before next upgrade:
- list of messages touching deposits in ante
- list of types where we check token extension in deterministic gas

___
___
*[`app/app.go` line 764 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/884#-O-LDQ--BQUzlBMb4O_V:-O-LDQ--BQUzlBMb4O_W:b-ax26cp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f753affb92521fa4c1dcb0febfe7ede3fce1381/app/app.go#L764)):*
> ```Go
> 	app.Ics20WasmHooks.ContractKeeper = &app.WasmKeeper
> 
> 	// TODO(v5): drop once we drop gov v1beta1 compatibility.
> ```

Can't we drop `v1beta1` in v4? We have already integrated `v1`
___
*[`x/asset/nft/keeper/keeper.go` line 857 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/884#-O-LE0GFDxxYZ-UkH7FK:-O-LE0GFDxxYZ-UkH7FL:b4av79e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f753affb92521fa4c1dcb0febfe7ede3fce1381/x/asset/nft/keeper/keeper.go#L857)):*
> ```Go
> 		switch editor {
> 		case types.DataEditor_admin:
> 			// TODO(v5) use admin instead of issuer once the admin is introduced
> ```

Admin is there, so it might be fixed in v4

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/884)* status: all files reviewed, 3 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/884#-O-LEECC9uZIILhpUdGp:-O-LKF275ltiQITYnuqV:b9fz1rq) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I suggest to add todos in all the new places requiring inspection before next upgrade:
- list of messages touching deposits in ante
- list of types where we check token extension in deterministic gas
</blockquote></details>

for number 1, I added a todo to the related PR, it is not yet in master
for number 2, we have added a test that will warn us if new messages are added to the system and are not handled.

___
___
*[`app/app.go` line 764 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/884#-O-LDQ--BQUzlBMb4O_V:-O-LJgWq5pHsVHxGXnrB:bof6k2f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f753affb92521fa4c1dcb0febfe7ede3fce1381/app/app.go#L764)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Can't we drop `v1beta1` in v4? We have already integrated `v1`
</blockquote></details>

No, cosmos sdk still supports v1beta1 and v1 will not work without it.
___
*[`x/asset/nft/keeper/keeper.go` line 857 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/884#-O-LE0GFDxxYZ-UkH7FK:-O-LJoOa9-GZAB4s_63E:b3ex8i6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f753affb92521fa4c1dcb0febfe7ede3fce1381/x/asset/nft/keeper/keeper.go#L857)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Admin is there, so it might be fixed in v4
</blockquote></details>

admin is not introduced for NFTs.

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 5 of 9 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/884)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/884)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
