### PR TITLE
Add asset FT dex_whitelisted_denoms feature and integrate it with DEX.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Add asset FT restrict_dex feature with denoms_to_trade_with setting and integrate it with DEX.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/961)

### CODE REVIEW

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 30 of 30 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/961)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/961)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`proto/coreum/asset/ft/v1/token.proto` line 20 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/961#-O7-jGb6-Td9ljWQUqxJ:-O7-jGb6-Td9ljWQUqxK:b-ba2s53) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5aaf6030f67d14ba0a974c9c1cd9d6cd08cd702/proto/coreum/asset/ft/v1/token.proto#L20)):*
> ```proto
>   extension = 7;
>   block_dex = 8;
>   restrict_dex = 9;
> ```

maybe restrict_tradable_tokens ? 
___
*[`proto/coreum/asset/ft/v1/token.proto` line 79 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/961#-O7-feg_AjRCzP7Nf2im:-O7-feg_AjRCzP7Nf2in:b-fr0nap) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5aaf6030f67d14ba0a974c9c1cd9d6cd08cd702/proto/coreum/asset/ft/v1/token.proto#L79)):*
> ```proto
>   string admin = 15;
>   DEXSettings dex_settings = 16 [(gogoproto.customname) = "DEXSettings"];
>   DEXRestrictions dex_restrictions = 17 [(gogoproto.customname) = "DEXRestrictions"];
> ```

This can go inside the `dex_settings`. 
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 66 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/961#-O7-g-czDrgvXcI0vSXo:-O7-g-czDrgvXcI0vSXp:b-kdppbb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5aaf6030f67d14ba0a974c9c1cd9d6cd08cd702/proto/coreum/asset/ft/v1/tx.proto#L66)):*
> ```proto
> 
>   // UpdateDEXRestrictions updates token DEX restrictions.
>   rpc UpdateDEXRestrictions(MsgUpdateDEXRestrictions) returns (EmptyResponse);
> ```

This should be a smaller API to only update tradable tokens. later we might want to introduce some restrictions that are not updatable. 
___
*[`x/asset/ft/keeper/keeper.go` line 1505 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/961#-O7-iEoA0K2AF2LHzqKN:-O7-iEoA0K2AF2LHzqKO:bigyj5b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5aaf6030f67d14ba0a974c9c1cd9d6cd08cd702/x/asset/ft/keeper/keeper.go#L1505)):*
> ```Go
> 			return err
> 		}
> 		if restrictions != nil && len(restrictions.DenomsToTradeWith) != 0 {
> ```

the check for empty slice is not needed. it will be handled by `lo.Contains`
___
*[`x/deterministicgas/config.go` line 98 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/961#-O7-jZEGAbOcJUXqTRae:-O7-jZEGAbOcJUXqTRaf:b15rwj3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5aaf6030f67d14ba0a974c9c1cd9d6cd08cd702/x/deterministicgas/config.go#L98)):*
> ```Go
> 		MsgToMsgURL(&assetfttypes.MsgUpgradeTokenV1{}):        constantGasFunc(25_000),
> 		MsgToMsgURL(&assetfttypes.MsgUpdateDEXSettings{}):     constantGasFunc(10_000),
> 		MsgToMsgURL(&assetfttypes.MsgUpdateDEXRestrictions{}): constantGasFunc(15_000),
> ```

isn't it a list of tokens that can be a big list ? then it should be non-deterministic.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/961)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`proto/coreum/asset/ft/v1/token.proto` line 20 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/961#-O7-jGb6-Td9ljWQUqxJ:-O72aBee6qBmgiuVkaut:b-abu71k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5aaf6030f67d14ba0a974c9c1cd9d6cd08cd702/proto/coreum/asset/ft/v1/token.proto#L20)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

maybe restrict_tradable_tokens ?
</blockquote></details>

The `restrict_dex`  allows to update the `dex_restrictions` where for now we have the denoms to trade with.
___
*[`proto/coreum/asset/ft/v1/token.proto` line 79 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/961#-O7-feg_AjRCzP7Nf2im:-O72aNvmEg4mRBH0dg90:b-ng6s3d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5aaf6030f67d14ba0a974c9c1cd9d6cd08cd702/proto/coreum/asset/ft/v1/token.proto#L79)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

This can go inside the `dex_settings`.
</blockquote></details>

The difference is that settings can be updated without the `restrict_dex` feature enabled. 
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 66 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/961#-O7-g-czDrgvXcI0vSXo:-O72a_As95xVaI6h8rvt:b-y7zt90) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5aaf6030f67d14ba0a974c9c1cd9d6cd08cd702/proto/coreum/asset/ft/v1/tx.proto#L66)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

This should be a smaller API to only update tradable tokens. later we might want to introduce some restrictions that are not updatable.
</blockquote></details>

This is possible, but in that case we need to change the settings update as well, to update everything independently, and keep all settings inside the DEXSettings.
___
*[`x/asset/ft/keeper/keeper.go` line 1505 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/961#-O7-iEoA0K2AF2LHzqKN:-O72byfyAXZtCXWg-3fL:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5aaf6030f67d14ba0a974c9c1cd9d6cd08cd702/x/asset/ft/keeper/keeper.go#L1505)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the check for empty slice is not needed. it will be handled by `lo.Contains`
</blockquote></details>

Done.
___
*[`x/deterministicgas/config.go` line 98 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/961#-O7-jZEGAbOcJUXqTRae:-O72b_G0E9ORlaV2kfk_:b-yfgrqb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5aaf6030f67d14ba0a974c9c1cd9d6cd08cd702/x/deterministicgas/config.go#L98)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

isn't it a list of tokens that can be a big list ? then it should be non-deterministic.
</blockquote></details>

We can make it more complicated and do it per token.

**Review by masihyeganeh — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/961)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 29 of 30 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/961)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`proto/coreum/asset/ft/v1/token.proto` line 20 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/961#-O7-jGb6-Td9ljWQUqxJ:-O734nyW9BCskItp7PD6:b738t4z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5aaf6030f67d14ba0a974c9c1cd9d6cd08cd702/proto/coreum/asset/ft/v1/token.proto#L20)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The `restrict_dex`  allows to update the `dex_restrictions` where for now we have the denoms to trade with.
</blockquote></details>

We can call it `restrict_dex_tokens`.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/961)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`x/deterministicgas/config.go` line 98 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/961#-O7-jZEGAbOcJUXqTRae:-O7XfRlwBIRbfCWqqwPv:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b5aaf6030f67d14ba0a974c9c1cd9d6cd08cd702/x/deterministicgas/config.go#L98)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

or mark it non-deterministic. either way is fine.
</blockquote></details>

Done

**Review by miladz68 — APPROVED** [review]
> Reviewed 35 of 35 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/961)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — DISMISSED** [review]
> Reviewed 28 of 35 files at r4, 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/961)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 304 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/961#-O7ckFVe2Yj8SQTCR10p:-O7ckFVe2Yj8SQTCR10q:btcoaer) ([raw file](https://github.com/CoreumFoundation/coreum/blob/89e994dbb34aedb13397cb99c45846d5bfb78cce/integration-tests/modules/assetft_test.go#L304)):*
> ```Go
> 		},
> 		Features: []assetfttypes.Feature{
> 			assetfttypes.Feature_dex_dex_whitelisted_denoms,
> ```

I don't like this naming with two dexes, but not that important

**Review by miladz68 — APPROVED** [review]
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/961)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/961)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/961)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 304 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/961#-O7ckFVe2Yj8SQTCR10p:-O7hNiG2Euj4WOYPw1a1:b-bu91xm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/89e994dbb34aedb13397cb99c45846d5bfb78cce/integration-tests/modules/assetft_test.go#L304)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I don't like this naming with two dexes, but not that important
</blockquote></details>

Updated

**Review by miladz68 — APPROVED** [review]
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/961)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
