### PR TITLE
Add integration-test to check sequences for multisig account

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/524)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/524)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/auth_test.go` line 200 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/524#-NXjZuIE7fKDRzrNYy-U:-NXjZuIE7fKDRzrNYy-V:brph87i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/da1c2613c7e24a5c170a8cd6cbb2381df11e45d9/integration-tests/modules/auth_test.go#L200)):*
> ```Go
> 
> // TestAuthMultisigSequences tests the cosmos-sdk sequences behaviour for multisig account.
> func TestAuthMultisigSequences(t *testing.T) {
> ```

I wasn't sure which sequence number is used in case of multisig account signing: is it signer sequence or multisig acc sequence.
I wrote this test for myself initially to determine this. Now it is clear that *multisig* sequence is always used

If this was obvious for everyone I can close this PR

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/524)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/auth_test.go` line 200 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/524#-NXjZuIE7fKDRzrNYy-U:-NXoihZA9WSIJtsQTsyG:b-8kq8i8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/da1c2613c7e24a5c170a8cd6cbb2381df11e45d9/integration-tests/modules/auth_test.go#L200)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Clear. Thanks, we can close it. 
</blockquote></details>

I was clear, Additional information is that I believe that the sequence number of the all the signers get incremented as well.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/524)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/auth_test.go` line 200 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/524#-NXjZuIE7fKDRzrNYy-U:-NXyzx766uXt_1DVleOu:b-kbvkmv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/da1c2613c7e24a5c170a8cd6cbb2381df11e45d9/integration-tests/modules/auth_test.go#L200)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I was clear, Additional information is that I believe that the sequence number of the all the signers get incremented as well. 
</blockquote></details>

@miladz68 

I don't think so.  Check this command:

```
cored --chain-id=coreum-mainnet-1 --node=https://full-node-curium.mainnet-1.coreum.dev:26657 q auth account core1ccvqyk7kar7ct0mz8l6wj3qxgefllg8nrrvxg0
```

I use that address to sign multisig txses, but the account itself does not exist on the blockchain, so it doesn't have sequence set.

@ysv 
I think this test is not needed

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/524)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/524)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`integration-tests/modules/auth_test.go` line 200 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/524#-NXjZuIE7fKDRzrNYy-U:-NY2w6vu5PN6gC5-TT6R:baw61xs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/da1c2613c7e24a5c170a8cd6cbb2381df11e45d9/integration-tests/modules/auth_test.go#L200)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@miladz68 

I don't think so.  Check this command:

```
cored --chain-id=coreum-mainnet-1 --node=https://full-node-curium.mainnet-1.coreum.dev:26657 q auth account core1ccvqyk7kar7ct0mz8l6wj3qxgefllg8nrrvxg0
```

I use that address to sign multisig txses, but the account itself does not exist on the blockchain, so it doesn't have sequence set.

@ysv 
I think this test is not needed
</blockquote></details>

well we observed that when bob provided his signature for the 2 multisig transactions, and we broadcasted the first one, we could not use his second signature for the second transaction, so somewhere it is getting tracked.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/524)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/auth_test.go` line 200 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/524#-NXjZuIE7fKDRzrNYy-U:-NY30HcR-6eA3BYYNv6d:bamy7em) ([raw file](https://github.com/CoreumFoundation/coreum/blob/da1c2613c7e24a5c170a8cd6cbb2381df11e45d9/integration-tests/modules/auth_test.go#L200)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

well we observed that when bob provided his signature for the 2 multisig transactions, and we broadcasted the first one, we could not use his second signature for the second transaction, so somewhere it is getting tracked. 
</blockquote></details>

it happened because after executing the first one, sequence of multisig was incremented, not his one

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/524)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`integration-tests/modules/auth_test.go` line 200 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/524#-NXjZuIE7fKDRzrNYy-U:-NY31AIP8iw-fNfa3z9e:b-w0yspi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/da1c2613c7e24a5c170a8cd6cbb2381df11e45d9/integration-tests/modules/auth_test.go#L200)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

it happened because after executing the first one, sequence of multisig was incremented, not his one
</blockquote></details>

got it.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/524)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/auth_test.go` line 200 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/524#-NXjZuIE7fKDRzrNYy-U:-NY3DWl8BoOUhJHdHh6Q:bnt1m4g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/da1c2613c7e24a5c170a8cd6cbb2381df11e45d9/integration-tests/modules/auth_test.go#L200)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

got it.
</blockquote></details>

Extended the test to answer Wojtek's & Milad's question.
As you can see only multisig acc sequence gets incremented while signers still have old values

Important finding for myself was that a single address can actually sign multiple txs and don't broadcast them if they go from different accounts

If no open discussions are left I'm going to close the PR

**Pull request closed without merging**
