### PR TITLE
Remove restore key for the docker cache to reset it on reinit.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/548)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/548)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`.github/workflows/ci.yml` line 113 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/548#-NZ5Njga0NQjpF0qKNy-:-NZ5Njga0NQjpF0qKNy0:b-di2iyo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/97d5de12102099d25ebb976c8b13578ff764d219/.github/workflows/ci.yml#L113)):*
> ```YAML
>         with:
>           key: ${{ runner.os }}-docker-${{ steps.get-year-week.outputs.date }} # year-week key
>           restore-keys: |
> ```

what about go and wasm cache? we have the same option there, Should it be removed?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/548)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 113 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/548#-NZ5Njga0NQjpF0qKNy-:-NZ67NGtCDIpLyfMpJqw:b-g1gddp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/97d5de12102099d25ebb976c8b13578ff764d219/.github/workflows/ci.yml#L113)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what about go and wasm cache? we have the same option there, Should it be removed?
</blockquote></details>

Discussion is in crust repo

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/548)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 113 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/548#-NZ5Njga0NQjpF0qKNy-:-NZ6ieso51ZEqdznVJZv:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/coreum/blob/97d5de12102099d25ebb976c8b13578ff764d219/.github/workflows/ci.yml#L113)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Discussion is in crust repo
</blockquote></details>

Updated.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/548)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/548)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/548)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/548)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
