### PR TITLE
Move cored client from `crust` to `coreum`

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/120)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/120)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`go.mod` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/120#-N8YNRZx7QyWc3V-x1LF:-N8YNRZx7QyWc3V-x1LG:b84rdzq) ([raw file](https://github.com/coreumfoundation/coreum/blob/01b3e9855204068c7e3087b92c1a2bca7a234003/go.mod#L12)):*
> ```XML
> 
> require (
> 	github.com/CoreumFoundation/coreum-tools v0.2.0
> ```

don't we already have 2.1 used in the other PR ?
___
*[`app/network_test.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/120#-N8YOJmQ93aZD4QcRBfP:-N8YOJmQ93aZD4QcRBfQ:b-nwxibd) ([raw file](https://github.com/coreumfoundation/coreum/blob/01b3e9855204068c7e3087b92c1a2bca7a234003/app/network_test.go#L30)):*
> ```Go
> 	pubKey, privKey := types.GenerateSecp256k1Key()
> 	clientCtx := NewDefaultClientContext()
> 	tx, err := staking.PrepareTxStakingCreateValidator(clientCtx, ed25519.PublicKey(pubKey), privKey, "1000core")
> ```

I suggest, this method `PrepareTxStakingCreateValidator` should become as a method of client type.
___
*[`pkg/staking/staking.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/120#-N8YOr80C0a8HpKxZakS:-N8YOr80C0a8HpKxZakT:boaoek3) ([raw file](https://github.com/coreumfoundation/coreum/blob/01b3e9855204068c7e3087b92c1a2bca7a234003/pkg/staking/staking.go#L1)):*
> ```Go
> package staking
> ```

I think this code belongs to the client domain and should not be moved into a separate package.
___
*[`pkg/tx/sign.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/120#-N8YP4br7bP_JUC8QMe6:-N8YP4br7bP_JUC8QMe7:b-pd0j3r) ([raw file](https://github.com/coreumfoundation/coreum/blob/01b3e9855204068c7e3087b92c1a2bca7a234003/pkg/tx/sign.go#L1)):*
> ```Go
> package tx
> ```

as I argued above, I think this code belongs to the client domain and should not be moved into a separate package.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/120)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`go.mod` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/120#-N8YNRZx7QyWc3V-x1LF:-N8YP_n8971wzmpahTdh:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/01b3e9855204068c7e3087b92c1a2bca7a234003/go.mod#L12)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

don't we already have 2.1 used in the other PR ?
</blockquote></details>

Done.
___
*[`app/network_test.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/120#-N8YOJmQ93aZD4QcRBfP:-N8YPcZv4osFva6grdwF:bi2lufe) ([raw file](https://github.com/coreumfoundation/coreum/blob/01b3e9855204068c7e3087b92c1a2bca7a234003/app/network_test.go#L30)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I suggest, this method `PrepareTxStakingCreateValidator` should become as a method of client type.
</blockquote></details>

I have two ideas in my mind:
- move this to the client like you said
- or do the oposite and move `PrepareTxBankSend` outside the client

We will discuss it at some point but this PR is only about moving client code, without any changes in implementation.
___
*[`pkg/staking/staking.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/120#-N8YOr80C0a8HpKxZakS:-N8YQ7UB-xQF7zZsHH52:btsl6c0) ([raw file](https://github.com/coreumfoundation/coreum/blob/01b3e9855204068c7e3087b92c1a2bca7a234003/pkg/staking/staking.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think this code belongs to the client domain and should not be moved into a separate package.
</blockquote></details>

Like I said above, we will discuss how to arrange everything better bu for now I'm just moving the code from one repo to another.
___
*[`pkg/tx/sign.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/120#-N8YP4br7bP_JUC8QMe6:-N8YQ8AD9vPMdhEPZ55u:b-7ropln) ([raw file](https://github.com/coreumfoundation/coreum/blob/01b3e9855204068c7e3087b92c1a2bca7a234003/pkg/tx/sign.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

as I argued above, I think this code belongs to the client domain and should not be moved into a separate package.
</blockquote></details>

ditto

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/120)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`app/network_test.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/120#-N8YOJmQ93aZD4QcRBfP:-N8YSLOa0QUO1-jgNpAq:bvh8xth) ([raw file](https://github.com/coreumfoundation/coreum/blob/01b3e9855204068c7e3087b92c1a2bca7a234003/app/network_test.go#L30)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Didn't you always argue that things should be done the correct way from the get go ? let's reach a decision how it should be done in this PR and do it accordingly
</blockquote></details>

Sure, we may do it today if you want to but still I would prefer to do it in a separate PR because this one is just a mechanical copy, I don't want to change logic here.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/120)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/client/client.go` line 12 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/120#-N8YReAC7F8f8csPsn8U:-N8YReAC7F8f8csPsn8V:buhcayy) ([raw file](https://github.com/coreumfoundation/coreum/blob/242cd32c8cb5a6b971de44ac379dc392b7803139/pkg/client/client.go#L12)):*
> ```Go
> 	"github.com/CoreumFoundation/coreum-tools/pkg/must"
> 	"github.com/CoreumFoundation/coreum-tools/pkg/retry"
> 	cosmosclient "github.com/cosmos/cosmos-sdk/client"
> ```

we don't need `cosmosclient` alias here, since it no longer clashes with another client package. 
___
*[`pkg/staking/staking.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/120#-N8YOr80C0a8HpKxZakS:-N8YSFatBSZivascqnn7:bt0sb8t) ([raw file](https://github.com/coreumfoundation/coreum/blob/01b3e9855204068c7e3087b92c1a2bca7a234003/pkg/staking/staking.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Like I said above, we will discuss how to arrange everything better bu for now I'm just moving the code from one repo to another.
</blockquote></details>

I mistakenly resolved this.
I know that this is copied code, but I think it should be copied to the client package, or at least as subfolder inside the client package. In either case this functionality should be exposed to the end user as single abstraction.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/120)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`pkg/client/client.go` line 12 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/120#-N8YReAC7F8f8csPsn8U:-N8YT-X7EzotpWx-dBc3:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/242cd32c8cb5a6b971de44ac379dc392b7803139/pkg/client/client.go#L12)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we don't need `cosmosclient` alias here, since it no longer clashes with another client package. 
</blockquote></details>

Done.
___
*[`pkg/staking/staking.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/120#-N8YOr80C0a8HpKxZakS:-N8YT7sH-bSc31BtXRAb:bluisbr) ([raw file](https://github.com/coreumfoundation/coreum/blob/01b3e9855204068c7e3087b92c1a2bca7a234003/pkg/staking/staking.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I mistakenly resolved this.
I know that this is copied code, but I think it should be copied to the client package, or at least as subfolder inside the client package. In either case this functionality should be exposed to the end user as single abstraction.
</blockquote></details>

It can't exist in `client` because `client` imports `app`, then unit tests in `app` would have to import `client` causing circular dependency.
I was rather thinking about leaving it as is and create yet another package `bank` and move `PrepareTxBankSend` there, so (as @xlab suggested) we don't keep all the tx generators for all the modules in a single place. Let's discuss during/after daily today.

**Review by miladz68 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/120#-:-N8YXvFb6LxQSneK55Mv:bnfp4nl)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

**Pull request merged**
