### PR TITLE
Fix proto annotations and remove amino json interface

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/924)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/924)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`x/asset/ft/types/msgs.go` line 157 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/924#-O4AOdpG-5zSojLyjvuf:-O4AOdpG-5zSojLyjvug:bboqy5q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b0212cd78d605ede229fe1e75be9f398ec196126/x/asset/ft/types/msgs.go#L157)):*
> ```Go
> 
> // GetSigners returns the message signers.
> func (m MsgIssue) GetSigners() []sdk.AccAddress {
> ```

How does the current signer verifiction work?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/924)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

___
*[`x/asset/ft/types/msgs.go` line 157 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/924#-O4AOdpG-5zSojLyjvuf:-O4AY8Zd2u1g8OYrAwxg:b-2fbvw7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b0212cd78d605ede229fe1e75be9f398ec196126/x/asset/ft/types/msgs.go#L157)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How does the current signer verifiction work?
</blockquote></details>

it is using proto reflection.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/924)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

___
*[`x/asset/ft/types/msgs.go` line 157 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/924#-O4AOdpG-5zSojLyjvuf:-O4AZ9HyAhZTvkNTSB3y:b-o3mvkw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b0212cd78d605ede229fe1e75be9f398ec196126/x/asset/ft/types/msgs.go#L157)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it is using proto reflection.
</blockquote></details>

What if there is no signer proto option in the message,  will such message be accepted?

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/924)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/924#-O4A_U4zBgig45HkF13J:-O4A_U5-1F6MmvzXUgyf:b-6rgpev) ([raw file](https://github.com/CoreumFoundation/coreum/blob/afe87728cbf7b9287293f0c8ddee92af31ebb7dd/proto/coreum/asset/ft/v1/tx.proto#L18)):*
> ```proto
> service Msg {
>   option (cosmos.msg.v1.service) = true;
> ```

Would you please tell me what this does? Does it generate new methods? Just asking to know

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/924)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/924)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
