### PR TITLE
Migrate copied nft module to cosmos sdk nft module

### PR DESCRIPTION
**Pull request by miladz68**
# Description
Earlier version of Coreum used Cosmos SDK v0.45 which did not have nft module, so we backported that module from v0.46. Now that we have moved to Cosmos SDK v0.47, we can migrate to the native nft module inside the SDK. This PR achieves just that. 
# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/666)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 52 of 52 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/666)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`app/app.go` line 198 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgII4c1-GJ1_aILzMdX:-NgII4c1-GJ1_aILzMdY:bpmjgp6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9527f15ee9af3cc9b1cdd981f61a4dfe3526f2e/app/app.go#L198)):*
> ```Go
> 		feemodel.AppModuleBasic{},
> 		wnft.AppModuleBasic{},
> 		cnftmodule.AppModuleBasic{},
> ```

Why is it needed now? Isn't it the `wnft` module which does whatever is needed?
___
*[`integration-tests/modules/assetnft_test.go` line 1476 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgIKgIU4RF9M0DDGSGr:-NgIKgIV9bSDDOF3B0oq:b-6hc1wl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bae640be7221a25d7eb016ae740cbc7d10da708d/integration-tests/modules/assetnft_test.go#L1476)):*
> ```Go
> 
> // TestAssetNFTAminoMultisig tests that assetnft module works seamlessly with amino multisig.
> func TestAssetNFTAminoMultisig(t *testing.T) {
> ```

why is it removed?
___
*[`integration-tests/upgrade/nft_migration_test.go` line 96 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgIPNAUBhLH2Dr4mck0:-NgIPNAUBhLH2Dr4mck1:b-pf1mwz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9527f15ee9af3cc9b1cdd981f61a4dfe3526f2e/integration-tests/upgrade/nft_migration_test.go#L96)):*
> ```Go
> }
> 
> func (nut *nftMigrationTest) After(t *testing.T) {
> ```

Try to send using new tx type
___
*[`x/asset/nft/keeper/keeper.go` line 138 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgINqG49JabkFwhqEXj:-NgINqG49JabkFwhqEXk:borsaf0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bae640be7221a25d7eb016ae740cbc7d10da708d/x/asset/nft/keeper/keeper.go#L138)):*
> ```Go
> 
> 	id := types.BuildClassID(settings.Symbol, settings.Issuer)
> 	if err := nft.ValidateClassID(id); err != nil {
> ```

why removed?
___
*[`x/asset/nft/types/token.go` line 115 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgINeD_0VWGxDvZ7uaQ:-NgINeD_0VWGxDvZ7uaR:brhm8rg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bae640be7221a25d7eb016ae740cbc7d10da708d/x/asset/nft/types/token.go#L115)):*
> ```Go
> 	}
> 
> 	if err := nft.ValidateNFTID(id); err != nil {
> ```

Why removed?
___
*[`x/nft/keeper/grpc_query.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgIJF2Y0OCDZVSix3lu:-NgIJF2ZCeBTvaUf7Ahb:b-hbrjoi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9527f15ee9af3cc9b1cdd981f61a4dfe3526f2e/x/nft/keeper/grpc_query.go#L13)):*
> ```Go
> var _ nft.QueryServer = Keeper{}
> 
> // Balance return the number of NFTs of a given class owned by the owner, same as balanceOf in ERC721.
> ```

returns
___
*[`x/nft/keeper/grpc_query_test.go` line 34 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgIKwYz7MrUbEfj4Su5:-NgIKwYz7MrUbEfj4Su6:b-5sz319) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9527f15ee9af3cc9b1cdd981f61a4dfe3526f2e/x/nft/keeper/grpc_query_test.go#L34)):*
> ```Go
> 				req = &nft.QueryBalanceRequest{}
> 			},
> 			cosmosnft.ErrEmptyClassID.Error(),
> ```

are the error messages, and their codes and namespaces same as before? If not, then this is not backward compatible
___
*[`x/nft/keeper/msg_server.go` line 15 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgIMtIwBMAs7sFGQeAu:-NgIMtIwBMAs7sFGQeAv:b-v0g9hd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9527f15ee9af3cc9b1cdd981f61a4dfe3526f2e/x/nft/keeper/msg_server.go#L15)):*
> ```Go
> // Send implement Send method of the types.MsgServer.
> func (k Keeper) Send(goCtx context.Context, msg *nft.MsgSend) (*nft.MsgSendResponse, error) {
> 	_, err := k.wkeeper.Send(goCtx, &cosmosnft.MsgSend{
> ```

For other keeper methods you have wrappers in `k` where you convert nft struct between types. But here you do it on the caller side. I would prefer to stick to that decision and have wrapping `Send` method in `k`.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/666)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 198 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgII4c1-GJ1_aILzMdX:-NgJENQyAv4sFvCHtIyB:b5ac1sh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9527f15ee9af3cc9b1cdd981f61a4dfe3526f2e/app/app.go#L198)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why is it needed now? Isn't it the `wnft` module which does whatever is needed?
</blockquote></details>

we need to be able to process `coreum.nft.v1beta1` messages as legacy route. in the pas `wnft` handled that route, but now `wnft` is handling `cosmos.nft.v1beta1` so we are intoruding this to handle the old legacy routes. 
___
*[`integration-tests/modules/assetnft_test.go` line 1476 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgIKgIU4RF9M0DDGSGr:-NgJG96o2hOQDksEj_90:bu7ro4g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bae640be7221a25d7eb016ae740cbc7d10da708d/integration-tests/modules/assetnft_test.go#L1476)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why is it removed?
</blockquote></details>

we introduced the amino to the NFT module, but the orignial nft module does not implement it. so we are not able to support the Amino for NFT anymore. 
___
*[`integration-tests/upgrade/nft_migration_test.go` line 96 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgIPNAUBhLH2Dr4mck0:-NgJGSEz5txMCHFxbo9I:bqz89wk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9527f15ee9af3cc9b1cdd981f61a4dfe3526f2e/integration-tests/upgrade/nft_migration_test.go#L96)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Try to send using new tx type
</blockquote></details>

we do that in a separate integration test. 
___
*[`x/asset/nft/keeper/keeper.go` line 138 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgINqG49JabkFwhqEXj:-NgJGgS17eo_da91TvRp:b-bixi6j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bae640be7221a25d7eb016ae740cbc7d10da708d/x/asset/nft/keeper/keeper.go#L138)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why removed?
</blockquote></details>

the `nft` module has remove the validation criteria for class id. we have this check here, so our generated id will not class with the validation of the `nft` module. since `nft` module is not doing validation, this check is not needed. 
___
*[`x/asset/nft/types/token.go` line 115 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgINeD_0VWGxDvZ7uaQ:-NgJHE4L9NaCsQiP8Ww6:bvfscvz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bae640be7221a25d7eb016ae740cbc7d10da708d/x/asset/nft/types/token.go#L115)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why removed?
</blockquote></details>

nft  id validation was part of the `nft` module and it is now removed, so the only validation that must be enforced is the one introduced by `assetnft` module. 
___
*[`x/nft/keeper/grpc_query.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgIJF2Y0OCDZVSix3lu:-NgJI-1v-hq9DBKHq0ky:b-8mtps) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9527f15ee9af3cc9b1cdd981f61a4dfe3526f2e/x/nft/keeper/grpc_query.go#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

returns
</blockquote></details>

this comments are copied from the cosmos sdk v0.45, and the grammar error exists in the original code as well. Originally we thought we should not try to fix them. 
___
*[`x/nft/keeper/grpc_query_test.go` line 34 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgIKwYz7MrUbEfj4Su5:-NgJIW_D8MQZahbknAGq:bk7xr1z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9527f15ee9af3cc9b1cdd981f61a4dfe3526f2e/x/nft/keeper/grpc_query_test.go#L34)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

are the error messages, and their codes and namespaces same as before? If not, then this is not backward compatible
</blockquote></details>

error codes are the same, but the error messages are not. I agree that this is breaking change, but this breaking change was introduced in v0.47 and probably exists all over the cosmos SDK codebase. so I don't think we can do much about it. 
___
*[`x/nft/keeper/msg_server.go` line 15 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgIMtIwBMAs7sFGQeAu:-NgJJ7dy2QCcdeH3KK63:b-4lqohb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9527f15ee9af3cc9b1cdd981f61a4dfe3526f2e/x/nft/keeper/msg_server.go#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

For other keeper methods you have wrappers in `k` where you convert nft struct between types. But here you do it on the caller side. I would prefer to stick to that decision and have wrapping `Send` method in `k`.
</blockquote></details>

It is the same strategy between query and tx handlers where we convert the types and pass it down. It is not different, or maybe I don't fully get your comment ?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/666)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/upgrade/nft_migration_test.go` line 96 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgIPNAUBhLH2Dr4mck0:-NgJOznv6gt34bJew8EN:b7al4th) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9527f15ee9af3cc9b1cdd981f61a4dfe3526f2e/integration-tests/upgrade/nft_migration_test.go#L96)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we do that in a separate integration test.
</blockquote></details>

But we don't do this for nft minted before the upgrade
___
*[`x/nft/keeper/msg_server.go` line 15 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgIMtIwBMAs7sFGQeAu:-NgJPPpTA7pQumDHO7FM:b-u9nkzh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9527f15ee9af3cc9b1cdd981f61a4dfe3526f2e/x/nft/keeper/msg_server.go#L15)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It is the same strategy between query and tx handlers where we convert the types and pass it down. It is not different, or maybe I don't fully get your comment ?
</blockquote></details>

Ignore this, my mind is still on holidays

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/666)* status: 51 of 52 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/upgrade/nft_migration_test.go` line 96 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgIPNAUBhLH2Dr4mck0:-NgJcQOS1_xCMqBMMBhn:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9527f15ee9af3cc9b1cdd981f61a4dfe3526f2e/integration-tests/upgrade/nft_migration_test.go#L96)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But we don't do this for nft minted before the upgrade
</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/666)* status: 51 of 52 files reviewed, 7 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgN2PgN1VHNIXTQlHaN:-NgN2PgN1VHNIXTQlHaO:bg3un23) (no related file):*
Please search for `The name is updated from "nft" to "cnft" to keep an ability to migrate to sdk native module.` comment.  Is it still valid?

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgN5Y0xCy5ap2J1HzxI:-NgN5Y0xCy5ap2J1HzxJ:b-pnk3ve) (no related file):*
From what I understand currently we use old root store key with the new cosmos SDK module. IMO it would be nice to migrate to cosmos key as well, in order to drop the support completely from the next release. But that is not required.

___
___
*[`integration-tests/modules/legacy_nft_assetnft_test.go` line 123 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgN441A6N6FKihmJmgI:-NgN441A6N6FKihmJmgJ:b-ydla3x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/87e4b2c17ec55f303dec1aa3638194ff7daecf38/integration-tests/modules/legacy_nft_assetnft_test.go#L123)):*
> ```Go
> 
> 	// change the owner
> 	sendMsg := &nft.MsgSend{
> ```

You use `nft.MsgSend` but how about use the `cosmosnft.MsgSend` as well ? And same for the queries. 
___
*[`integration-tests/upgrade/nft_migration_test.go` line 96 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgN7U3C9PMa2tpS-rn7:-NgN7U3C9PMa2tpS-rn8:bjiijp3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/87e4b2c17ec55f303dec1aa3638194ff7daecf38/integration-tests/upgrade/nft_migration_test.go#L96)):*
> ```Go
> }
> 
> func (nut *nftMigrationTest) After(t *testing.T) {
> ```

IMO in the after we should test both cosmos and legacy API to be sure that the data is still accesable with the legacy API after the migration. 
___
*[`x/asset/nft/keeper/keeper.go` line 137 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgN4v2DDLnPQ15fTuT_:-NgN4v2DDLnPQ15fTuTa:b-31etse) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bae640be7221a25d7eb016ae740cbc7d10da708d/x/asset/nft/keeper/keeper.go#L137)):*
> ```Go
> 	}
> 
> 	id := types.BuildClassID(settings.Symbol, settings.Issuer)
> ```

Why don't we validate it anymore? 
___
*[`x/asset/nft/types/token.go` line 115 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgN56RHAskvEwFhL_tb:-NgN56RHAskvEwFhL_tc:bp3tzqm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bae640be7221a25d7eb016ae740cbc7d10da708d/x/asset/nft/types/token.go#L115)):*
> ```Go
> 	}
> 
> 	if err := nft.ValidateNFTID(id); err != nil {
> ```

Why don't we validate it anymore?

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/666)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/666)* status: 51 of 53 files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgN2PgN1VHNIXTQlHaN:-NgO6rV2-SjIIMrs_3iL:bm4qbym) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Please search for `The name is updated from "nft" to "cnft" to keep an ability to migrate to sdk native module.` comment.  Is it still valid?
</blockquote></details>

that comment is part of the legacy module. it is ok to keep it to understand why we did this, and later we will remove the whole module. 

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgN5Y0xCy5ap2J1HzxI:-NgO7-vK46P2Qbr4CupL:b-dn1l8j) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

From what I understand currently we use old root store key with the new cosmos SDK module. IMO it would be nice to migrate to cosmos key as well, in order to drop the support completely from the next release. But that is not required.
</blockquote></details>

Good idea, Done. 

___
___
*[`integration-tests/modules/legacy_nft_assetnft_test.go` line 123 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgN441A6N6FKihmJmgI:-NgNrcbK7XPY1t7mXx-x:bvsqrxv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/87e4b2c17ec55f303dec1aa3638194ff7daecf38/integration-tests/modules/legacy_nft_assetnft_test.go#L123)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You use `nft.MsgSend` but how about use the `cosmosnft.MsgSend` as well ? And same for the queries.
</blockquote></details>

cosmosnft.MsgSend is tested in the other file `assetnft_test.go` here we specifically test the legacy handlers. 
___
*[`integration-tests/upgrade/nft_migration_test.go` line 96 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgN7U3C9PMa2tpS-rn7:-NgO77KSCOesVwU6HtmE:be9oaq4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/87e4b2c17ec55f303dec1aa3638194ff7daecf38/integration-tests/upgrade/nft_migration_test.go#L96)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO in the after we should test both cosmos and legacy API to be sure that the data is still accesable with the legacy API after the migration.
</blockquote></details>

We do just a single test here to make sure that the data is correctly migrated. the behavior of the APIs is tested in integration tests and unit tests. 
___
*[`x/asset/nft/keeper/keeper.go` line 137 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgN4v2DDLnPQ15fTuT_:-NgNs1k2D7ftj67xhLjQ:b-2ohj2b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bae640be7221a25d7eb016ae740cbc7d10da708d/x/asset/nft/keeper/keeper.go#L137)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't we validate it anymore?
</blockquote></details>

wojtek asked the same.
the `nft` module has remove the validation criteria for class id. we have this check here, so our generated id will not clash with the validation of the `nft` module. since `nft` module is not doing validation, this check is not needed.
___
*[`x/asset/nft/types/token.go` line 115 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/666#-NgN56RHAskvEwFhL_tb:-NgNsI3uDIjdqYScliT9:b-quu7zh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bae640be7221a25d7eb016ae740cbc7d10da708d/x/asset/nft/types/token.go#L115)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't we validate it anymore?
</blockquote></details>

nft id validation was part of the `nft` module and it is now removed, so the only validation that must be enforced is the one introduced by `assetnft` module.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/666)* status: 51 of 53 files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/666)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
