### PR TITLE
Add support for textual sign mode

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/960)

### CODE REVIEW

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/960)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/960)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/960)* status: all files reviewed, 3 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`app/app.go` line 457 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/960#-O6uO7Ds-RoP06F56opU:-O6uO7Ds-RoP06F56opV:b-fac4ql) ([raw file](https://github.com/CoreumFoundation/coreum/blob/efd51272c852d091df3671d2fdf261a70238c237/app/app.go#L457)):*
> ```Go
> 	)
> 
> 	enabledSignModes := make([]signingtypes.SignMode, 0)
> ```

The code is duplicated in multiple places. 
___
*[`cmd/cored/cosmoscmd/root.go` line 94 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/960#-O6uOAxMAePs2L9CZoe5:-O6uOAxMAePs2L9CZoe6:b-davs3e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/efd51272c852d091df3671d2fdf261a70238c237/cmd/cored/cosmoscmd/root.go#L94)):*
> ```Go
> 				return err
> 			}
> 			if !initClientCtx.Offline {
> ```

Is it possible to test it with the CLI tests?
___
*[`integration-tests/modules/assetft_test.go` line 2365 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/960#-O6uNb98ExM80EfjO_Bn:-O6uNb98ExM80EfjO_Bo:b-w6g2rs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/efd51272c852d091df3671d2fdf261a70238c237/integration-tests/modules/assetft_test.go#L2365)):*
> ```Go
> 
> // TestAssetFTClawbackWithTextualSigning checks clawback functionality of fungible tokens with textual signing..
> func TestAssetFTClawbackWithTextualSigning(t *testing.T) {
> ```

IMO the test with the signing should be in the auth tests, also I would use the bank send instead of clawback, which is the simplest operation.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/960)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`app/app.go` line 457 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/960#-O6uO7Ds-RoP06F56opU:-O6uZQQjDrweX6fxjZhD:b-i3l16j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/efd51272c852d091df3671d2fdf261a70238c237/app/app.go#L457)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The code is duplicated in multiple places.
</blockquote></details>

It's just two places, and it should apply to two place and the implementation is different, one uses bankKeeper and one uses GRPC
___
*[`cmd/cored/cosmoscmd/root.go` line 94 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/960#-O6uOAxMAePs2L9CZoe5:-O6uZcVm8nGphdCspfen:b-ywqv3d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/efd51272c852d091df3671d2fdf261a70238c237/cmd/cored/cosmoscmd/root.go#L94)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is it possible to test it with the CLI tests?
</blockquote></details>

I tried, but couldn't make it work. The problem is that it uses `clientCtx.CmdContext` here:
https://github.com/cosmos/cosmos-sdk/blob/v0.50.9/client/tx/tx.go#L129
And we don't have this cmdContext.
Let me know if it is something obvious and I'm missing something
___
*[`integration-tests/modules/assetft_test.go` line 2365 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/960#-O6uNb98ExM80EfjO_Bn:-O6uOqgN6WmJdkIiZPy2:b-v6577q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/efd51272c852d091df3671d2fdf261a70238c237/integration-tests/modules/assetft_test.go#L2365)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO the test with the signing should be in the auth tests, also I would use the bank send instead of clawback, which is the simplest operation.
</blockquote></details>

Because it has a new representation of TX, I believe we should test it with one of our own message types to make sure it works

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/960)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
