### PR TITLE
Add the MULTISIG.md with the CLI description and example

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/158)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/158)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`MULTISIG.md` line 7 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/158#-NBHaDba8UjKid7KTfrB:-NBHcdiL2PBtwd13AWeb:b-vtfxxo) ([raw file](https://github.com/coreumfoundation/coreum/blob/895db09a310ebc7c47ca5e2be4dbc4f101fbe65a/MULTISIG.md#L7)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> The sample below describes the full from

full flow from ?
</blockquote></details>

Right, typo. Updated.



_Code quote:_
```Markdown
The sample below describes the full from the creation of the multisig account to the tx broadcast.
```
___
*[`MULTISIG.md` line 8 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/158#-NBHaIxv3EFnzid7d41Z:-NBHclen3ovqgwyYKoJr:b-8ezbo2) ([raw file](https://github.com/coreumfoundation/coreum/blob/895db09a310ebc7c47ca5e2be4dbc4f101fbe65a/MULTISIG.md#L8)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

coreum -> cored
</blockquote></details>

Agree, updated.
___
*[`MULTISIG.md` line 53 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/158#-NBHacXjAX_A6pkoJxqE:-NBHcyXfBx26yT26JILS:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/895db09a310ebc7c47ca5e2be4dbc4f101fbe65a/MULTISIG.md#L53)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

has -> hash
</blockquote></details>

Updated.



_Code quote:_
```Markdown
coredev-00 q tx "the-tx-has"
```
___
*[`MULTISIG.md` line 112 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/158#-NBHb37v0gEP2B_awnbm:-NBHd3N_Ci3okJ5mG15P:b-kfjxza) ([raw file](https://github.com/coreumfoundation/coreum/blob/895db09a310ebc7c47ca5e2be4dbc4f101fbe65a/MULTISIG.md#L112)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This command will overwrite `bank-signed-tx.json` created when k1's signature was added.
Maybe `bank-unsigned-tx.json` should be replaced by `bank-signed-tx.json` in the command?
</blockquote></details>

Right, we can override it, since we don't need to prev signed tx with just one signer. 



_Code quote:_
```Markdown
coredev-00 tx multisign bank-unsigned-tx.json k1k2k3 k1sign.json k2sign.json > bank-signed-tx.json
```

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/158)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`MULTISIG.md` line 112 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/158#-NBHb37v0gEP2B_awnbm:-NBHi-dnAhQAR5bFA3Qw:b-bhsklx) ([raw file](https://github.com/coreumfoundation/coreum/blob/895db09a310ebc7c47ca5e2be4dbc4f101fbe65a/MULTISIG.md#L112)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Right, we can override it, since we don't need to prev signed tx with just one signer. 
</blockquote></details>

ah, now I see how it works

**Review by ysv — CHANGES_REQUESTED** [review]
Is it possible to write integration/unit test for this flow ?

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/158#-:-NBHl8uF4PZvQR1N7hb6:b-qqsfio)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @miladz68)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/158#-NBHlZrgAxetzl5MR-S_:-NBHlZrgAxetzl5MR-Sa:baqee01) (no related file):*
1. I don't like to have such files on the root of the repo maybe we can move it to ./docs ?
2.we use crust binaries here (coredev-00) while coreum repo know nothing about this binary. I think we should directly refer to cored binary here

___

**Review by ysv — CHANGES_REQUESTED** [review]
or it is too complicated and requires much time ?

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/158#-:-NBHmDNi4loz5wGPfD3A:bjwse42)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @miladz68)

**Review by dzmitryhil — COMMENTED** [review]
It sould be possible, will do it in the separate PR.

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/158#-:-NBHs0Us8zuH1rnvKfib:b-gh2rqq)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/158#-NBHlZrgAxetzl5MR-S_:-NBHsG7-DpbVx7o_fgWv:b-qlo01l) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1. I don't like to have such files on the root of the repo maybe we can move it to ./docs ?
2.we use crust binaries here (coredev-00) while coreum repo know nothing about this binary. I think we should directly refer to cored binary here
</blockquote></details>

1 Moved to the docs.
2. Ok, updated. 

___

**Review by ysv — APPROVED** [review]
ok but depending on time it takes we can do this in scope of this task or move for the next sprint

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/158#-:-NBI2JIT9abfw1yMERkh:b-duwux8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/158)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Pull request merged**
