### PR TITLE
Add upgrade integration-test to verify that WASM works as expected

### PR DESCRIPTION
**Pull request by ysv**
# Description

This PR adds upgrade integration-test where we:
1. create simple-state (counter increment) WASM contract inside old v2.0.2 version & check it
2. then upgrade to the latest master
3. check if contract work as expected & state is preserved after migration

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/639)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/639)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

___
*[`integration-tests/modules/wasm_test.go` line 48 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/639#-Ndf8I5C40uhpIjXazTJ:-Ndf8I5C40uhpIjXazTK:b6jpuo8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05d98fc4dfe9572cf8631054ad0fc1200bd9e26b/integration-tests/modules/wasm_test.go#L48)):*
> ```Go
> )
> 
> // simple state models
> ```

as you can see I have moved simple state helper funcs & datatypes to `integration-tests/contracts/modules/simple-state.go` since I need this contract in 2 places now

I still keep other contract helpers here
If you are like this approach I can also move bank, authz & fungible tokens there.
Or we can keep them as they are I don't have strong preference here

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/639)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/639)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @wojtek-coreum)

___
*[`integration-tests/modules/wasm_test.go` line 48 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/639#-Ndf8I5C40uhpIjXazTJ:-Ndir7hFAQsHqd2DxnwV:b-rol4ne) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05d98fc4dfe9572cf8631054ad0fc1200bd9e26b/integration-tests/modules/wasm_test.go#L48)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

as you can see I have moved simple state helper funcs & datatypes to `integration-tests/contracts/modules/simple-state.go` since I need this contract in 2 places now

I still keep other contract helpers here
If you are like this approach I can also move bank, authz & fungible tokens there.
Or we can keep them as they are I don't have strong preference here
</blockquote></details>

IMO we don't need it until we have a reason for it.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/639)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/639)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @wojtek-coreum)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/639)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @wojtek-coreum)

___
*[`integration-tests/modules/wasm_test.go` line 48 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/639#-Ndf8I5C40uhpIjXazTJ:-NdjJP9lCo3vqSjgFVFw:bqv1236) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05d98fc4dfe9572cf8631054ad0fc1200bd9e26b/integration-tests/modules/wasm_test.go#L48)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO we don't need it until we have a reason for it.
</blockquote></details>

I agree
will keep it only for simple-state for now

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/639)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
