### PR TITLE
Adjust CI to use public `crust` repo and remove non-`cored` code

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/102)

### CODE REVIEW

**Review by xlab — APPROVED** [review]
> Reviewed 74 of 75 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @oliverasistemas, and @ysv)

**Review by xlab — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @oliverasistemas, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 74 of 75 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @oliverasistemas)

**Review by oliverasistemas — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
