### PR TITLE
Set fractional gas price

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/188)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/188)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/tx/sign.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/188#-NCPu_AN27LwyzUrQ5A0:-NCPu_AN27LwyzUrQ5A1:bsl5nct) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff81ddf5a540dad35df2a13a79f4b77c3d0c8f6e/pkg/tx/sign.go#L36)):*
> ```Go
> 
> 		// Ceil().RoundInt() is here to be compatible with the sdk's TxFactory
> 		fee := sdk.NewCoin(input.GasPrice.Denom, input.GasPrice.Amount.Mul(gasLimit.ToDec()).Ceil().RoundInt())
> ```

Could share where?
___
*[`x/feemodel/types/params.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/188#-NCPuPri0qzMkvqJtlEr:-NCPuPri0qzMkvqJtlEs:bq70bnt) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff81ddf5a540dad35df2a13a79f4b77c3d0c8f6e/x/feemodel/types/params.go#L38)):*
> ```Go
> 	return Params{
> 		// TODO: Find good parameters before launching mainnet
> 		InitialGasPrice:         sdk.MustNewDecFromStr("0.0625"),
> ```

As far as I understand those values are based on something? On what?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/188)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/types/params.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/188#-NCPuPri0qzMkvqJtlEr:-NCPvjYzAYrHK8_6JTs1:b-30092s) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff81ddf5a540dad35df2a13a79f4b77c3d0c8f6e/x/feemodel/types/params.go#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

As far as I understand those values are based on something? On what?
</blockquote></details>

on calculations made by @ysv

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/188)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/tx/sign.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/188#-NCPu_AN27LwyzUrQ5A0:-NCQ9Fgp6MeSpc_naxz7:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff81ddf5a540dad35df2a13a79f4b77c3d0c8f6e/pkg/tx/sign.go#L36)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could share where?
</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/188)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`x/feemodel/types/params.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/188#-NCPuPri0qzMkvqJtlEr:-NCTzAq10FX5gn4Tco0S:b-myx1q9) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff81ddf5a540dad35df2a13a79f4b77c3d0c8f6e/x/feemodel/types/params.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

on calculations made by @ysv 
</blockquote></details>

Update the docs, please,  the current values in the docs:
```
 InitialGasPrice         | string (int) | "1500"    |
| MaxGasPrice             | string (int) | "1500000" |
| MaxDiscount             | string (dec) | "0.5"   
```

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/188)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`x/feemodel/types/params.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/188#-NCPuPri0qzMkvqJtlEr:-NCU-zqU29072trerLKC:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff81ddf5a540dad35df2a13a79f4b77c3d0c8f6e/x/feemodel/types/params.go#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Update the docs, please,  the current values in the docs:
```
 InitialGasPrice         | string (int) | "1500"    |
| MaxGasPrice             | string (int) | "1500000" |
| MaxDiscount             | string (dec) | "0.5"   
```

</blockquote></details>

Done.

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/188)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/188)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`x/feemodel/spec/03_params.md` line 9 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/188#-NCUhstzEijxUj6FvQ4F:-NCUhstzEijxUj6FvQ4G:byvxq83) ([raw file](https://github.com/coreumfoundation/coreum/blob/c603b319e846578010dda878972c685d25042400/x/feemodel/spec/03_params.md#L9)):*
> ```Markdown
> The feemodel module contains the following parameters:
> 
> | Key                     | Type         | Example  |
> ```

ideally we should also update fee charts
Is it going to take much time ?

I'm thinking if we should do this now or ask Dai to make them more beautiful and also updated these values together ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/188)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`x/feemodel/spec/03_params.md` line 9 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/188#-NCUhstzEijxUj6FvQ4F:-NCZCKs3ECdxDInGohJ6:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/c603b319e846578010dda878972c685d25042400/x/feemodel/spec/03_params.md#L9)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ideally we should also update fee charts
Is it going to take much time ?

I'm thinking if we should do this now or ask Dai to make them more beautiful and also updated these values together ?
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/188)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

**Pull request merged**
