### PR TITLE
Implement amino txs encode/decode for coreum modules.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/566)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 16 of 17 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/566)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/types/msgs.go` line 440 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/566#-N_83XKKE73D1m8XWIgs:-N_83XKKE73D1m8XWIgt:b2nidpt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ab6974a315b284ba8b12a649e176b46c3a4773ee/x/asset/ft/types/msgs.go#L440)):*
> ```Go
> )
> 
> func init() {
> ```

ugh

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/566)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/types/msgs.go` line 440 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/566#-N_83XKKE73D1m8XWIgs:-N_8pwIx3Lr0HqJ2kv5K:b-12mre) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ab6974a315b284ba8b12a649e176b46c3a4773ee/x/asset/ft/types/msgs.go#L440)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ugh
</blockquote></details>

Cosmos style :-) Even the location at the end is cosmos style :-)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/566)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 16 of 17 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/566)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`tests/amino_test.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/566#-N_E0VVt8qfvI0tT4e0X:-N_E0VVu6g5dnz98iqtI:b-x0h5pj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ab6974a315b284ba8b12a649e176b46c3a4773ee/tests/amino_test.go#L1)):*
> ```Go
> package tests
> ```

I'm ok with everything, but don't like idea of creating one more root folder. 
maybe we can put it to x or app ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/566)* status: 17 of 19 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`tests/amino_test.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/566#-N_E0VVt8qfvI0tT4e0X:-N_E2KaR6V6U88HmdMeL:beyzhmo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ab6974a315b284ba8b12a649e176b46c3a4773ee/tests/amino_test.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm ok with everything, but don't like idea of creating one more root folder. 
maybe we can put it to x or app ?
</blockquote></details>

`app` is a good place. Moved.

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/566)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/566)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/566)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/566)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Pull request merged**
