### PR TITLE
extend nft whitelist integration test

### PR DESCRIPTION
**Pull request by pgoos**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)

### CODE REVIEW

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @pgoos, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/assetnft_test.go` line 840 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOPSn896gkWRT9-USxg:-NOPSn8A5oQukiFfay0j:b-tsu9uk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a2cd5a08e785c78de87868986a783d3d6fa605fe/integration-tests/modules/assetnft_test.go#L840)):*
> ```Go
> 				&nft.MsgSend{},
> 				&nft.MsgSend{},
> 				&nft.MsgSend{},
> ```

we should require 2 items in this list, not 3

**Review by pgoos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/assetnft_test.go` line 840 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOPSn896gkWRT9-USxg:-NOPTRbc2gBreLTBDsui:bl4cthr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a2cd5a08e785c78de87868986a783d3d6fa605fe/integration-tests/modules/assetnft_test.go#L840)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we should require 2 items in this list, not 3
</blockquote></details>

We need 3, because we do 3 send txs from recipient. 
* 1st one fails (recipient2 not whitelisted), 
* 2nd succeeds (recipient2 whitelisted), 
* 3rd one fails (after applying RemoveNftWhitelist for recipient2)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @pgoos, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/assetnft_test.go` line 840 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOPSn896gkWRT9-USxg:-NOPUX7X3jybzbQ6X819:b8x8vur) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a2cd5a08e785c78de87868986a783d3d6fa605fe/integration-tests/modules/assetnft_test.go#L840)):*
<details><summary><i>Previously, pgoos (Piotr Gesicki) wrote…</i></summary><blockquote>

We need 3, because we do 3 send txs from recipient. 
* 1st one fails (recipient2 not whitelisted), 
* 2nd succeeds (recipient2 whitelisted), 
* 3rd one fails (after applying RemoveNftWhitelist for recipient2)
</blockquote></details>

I understand now. I left another comment down below. 
___
*[`integration-tests/modules/assetnft_test.go` line 939 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOPUJxT1W9_9ZIK2YLq:-NOPUJxT1W9_9ZIK2YLr:bgn6eyi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a2cd5a08e785c78de87868986a783d3d6fa605fe/integration-tests/modules/assetnft_test.go#L939)):*
> ```Go
> 
> 	// send again from recipient to non-whitelisted recipient2 (send must fail)
> 	sendMsg = &nft.MsgSend{
> ```

recipient1 no longer has the NFT, it has already sent to recipient2, so naturally the send will fail. so this action does not test the intended behavior.

**Review by pgoos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/assetnft_test.go` line 840 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOPSn896gkWRT9-USxg:-NOPUosG6P5T-fyL2rVr:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a2cd5a08e785c78de87868986a783d3d6fa605fe/integration-tests/modules/assetnft_test.go#L840)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I understand now. I left another comment down below. 
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetnft_test.go` line 939 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOPUJxT1W9_9ZIK2YLq:-NOPUraa2lE0ISHdjgEZ:btrxb59) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a2cd5a08e785c78de87868986a783d3d6fa605fe/integration-tests/modules/assetnft_test.go#L939)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

recipient1 no longer has the NFT, it has already sent to recipient2, so naturally the send will fail. so this action does not test the intended behavior. 
</blockquote></details>

You are right. In that case I am gonna change testing logic a bit:
* `recipient2` contains NFT
* `recipient` is applied `RemoveNftWhitelist` message
* `recipient2` tries to send the NFT to `recipient` (it must fail)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @pgoos, and @silverspase)

___
*[`integration-tests/modules/assetnft_test.go` line 792 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOU6QDaBD66RL59bL1A:-NOU6QDaBD66RL59bL1B:b-uhubx5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/26657ed69f8c83efe43fa8090d911757c5f883cf/integration-tests/modules/assetnft_test.go#L792)):*
> ```Go
> 
> 	// whitelist recipient for the NFT
> 	MsgAddToWhitelist := &assetnfttypes.MsgAddToWhitelist{
> ```

this should be `msgAddToWhitelist`
___
*[`integration-tests/modules/assetnft_test.go` line 868 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOU6Uq76hYftzsv9gEL:-NOU6Uq76hYftzsv9gEM:b-uhubx5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/26657ed69f8c83efe43fa8090d911757c5f883cf/integration-tests/modules/assetnft_test.go#L868)):*
> ```Go
> 
> 	// whitelist recipient2 for the NFT
> 	MsgAddToWhitelist = &assetnfttypes.MsgAddToWhitelist{
> ```

this should be `msgAddToWhitelist`
___
*[`integration-tests/modules/assetnft_test.go` line 883 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOU6okO2umaltscRI-9:-NOU6okO2umaltscRI-A:bhq9kf9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/26657ed69f8c83efe43fa8090d911757c5f883cf/integration-tests/modules/assetnft_test.go#L883)):*
> ```Go
> 	requireT.EqualValues(chain.GasLimitByMsgs(MsgAddToWhitelist), res.GasUsed)
> 
> 	queryRes, err = nftClient.Whitelisted(ctx, &assetnfttypes.QueryWhitelistedRequest{
> ```

this test already verifies that querying works
___
*[`integration-tests/modules/assetnft_test.go` line 892 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOU6tpOCATE3euh0Ewb:-NOU6tpOCATE3euh0Ewc:bqniba9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/26657ed69f8c83efe43fa8090d911757c5f883cf/integration-tests/modules/assetnft_test.go#L892)):*
> ```Go
> 
> 	// assert the whitelisting event
> 	whitelistEvents, err = event.FindTypedEvents[*assetnfttypes.EventAddedToWhitelist](res.Events)
> ```

this test already verifies that event is created
___
*[`integration-tests/modules/assetnft_test.go` line 911 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOU6g8G96OJKmJE8U1H:-NOU6g8G96OJKmJE8U1I:b-1snbk2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/26657ed69f8c83efe43fa8090d911757c5f883cf/integration-tests/modules/assetnft_test.go#L911)):*
> ```Go
> 
> 	// unwhitelist the account
> 	MsgRemoveFromWhitelist := &assetnfttypes.MsgRemoveFromWhitelist{
> ```

`msgRemoveFromWhitelist` - check if there are other capitalized cases

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @pgoos, and @silverspase)

**Review by pgoos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/assetnft_test.go` line 792 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOU6QDaBD66RL59bL1A:-NOUL1Pq8pkn7X5LLTZm:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7c40eb092b073f362b44d0ff736428e120ba0143/integration-tests/modules/assetnft_test.go#L792)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this should be `msgAddToWhitelist`
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetnft_test.go` line 868 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOU6Uq76hYftzsv9gEL:-NOUL2gKAvB4OFJEQ4Mw:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7c40eb092b073f362b44d0ff736428e120ba0143/integration-tests/modules/assetnft_test.go#L868)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this should be `msgAddToWhitelist`
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetnft_test.go` line 883 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOU6okO2umaltscRI-9:-NOUL46m1qEutq0loouf:bss4a2b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7c40eb092b073f362b44d0ff736428e120ba0143/integration-tests/modules/assetnft_test.go#L883)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this test already verifies that querying works
</blockquote></details>

Removed.
___
*[`integration-tests/modules/assetnft_test.go` line 892 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOU6tpOCATE3euh0Ewb:-NOUL7I2-LSVm5oLRmeQ:bss4a2b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7c40eb092b073f362b44d0ff736428e120ba0143/integration-tests/modules/assetnft_test.go#L892)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this test already verifies that event is created
</blockquote></details>

Removed.
___
*[`integration-tests/modules/assetnft_test.go` line 911 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOU6g8G96OJKmJE8U1H:-NOUL8y4A6tOxzYCik0C:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7c40eb092b073f362b44d0ff736428e120ba0143/integration-tests/modules/assetnft_test.go#L911)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`msgRemoveFromWhitelist` - check if there are other capitalized cases
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @pgoos, and @silverspase)

___
*[`integration-tests/modules/assetnft_test.go` line 882 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOUMi4N3EphfTnbg-EA:-NOUMi4N3EphfTnbg-EB:bky6ar1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/afdaebc514eb5d328e7710b059c93a7a8c739e76/integration-tests/modules/assetnft_test.go#L882)):*
> ```Go
> 	)
> 	requireT.NoError(err)
> 	requireT.EqualValues(chain.GasLimitByMsgs(msgAddToWhitelist), res.GasUsed)
> ```

this doesn't need to be tested again either

**Review by pgoos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 882 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/398#-NOUMi4N3EphfTnbg-EA:-NOUPW3FEpyzBW9owUZy:bss4a2b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/afdaebc514eb5d328e7710b059c93a7a8c739e76/integration-tests/modules/assetnft_test.go#L882)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this doesn't need to be tested again either
</blockquote></details>

Removed.

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/398)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Pull request merged**
