### PR TITLE
added integration tests for update and remove contract admin

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/337)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/337)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 399 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/337#-NLVGjP28_jMbeX3GBb1:-NLVGjP28_jMbeX3GBb2:bqf6nv9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a7a032959d1c5998eb8bf6641d057828a863b367/integration-tests/modules/wasm_test.go#L399)):*
> ```Go
> 	}))
> 
> 	txf := chain.TxFactory().
> ```

Why do you need to move in to that variable here if you use it directly in other cases?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/337)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 399 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/337#-NLVGjP28_jMbeX3GBb1:-NL_ZCkD5XgfpIUtfJlz:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a7a032959d1c5998eb8bf6641d057828a863b367/integration-tests/modules/wasm_test.go#L399)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need to move in to that variable here if you use it directly in other cases?
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/337)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/337)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/wasm_test.go` line 449 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/337#-NLty3lk9Cg1Mtgtadmi:-NLty3lk9Cg1Mtgtadmj:b3xjf3w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2916cae7607cc1222a4a900164ece5872e33c7b9/integration-tests/modules/wasm_test.go#L449)):*
> ```Go
> 	requireT.EqualValues(chain.GasLimitByMsgs(msgUpdateAdmin), res.GasUsed)
> 
> 	// clear admin
> ```

after you clear admin it is impossible to update it anymore, is it ? (just a question no need for testing)
___
*[`pkg/config/deterministic_gas.go` line 105 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/337#-NLtxZEF5qms08vP-dyW:-NLtxZEF5qms08vP-dyX:bgoj0g6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2916cae7607cc1222a4a900164ece5872e33c7b9/pkg/config/deterministic_gas.go#L105)):*
> ```Go
> 		&dgr,
> 		// wasm
> 		// TODO (milad): rewise gas config for WASM msgs.
> ```

is this todo still relevant ? 
will you rewise other msg types in the next PR or it is completed now ?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/337)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 449 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/337#-NLty3lk9Cg1Mtgtadmi:-NLuVet_AkjjAgdYMtAo:b-hb2wth) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2916cae7607cc1222a4a900164ece5872e33c7b9/integration-tests/modules/wasm_test.go#L449)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

after you clear admin it is impossible to update it anymore, is it ? (just a question no need for testing)
</blockquote></details>

you cannot. 
___
*[`pkg/config/deterministic_gas.go` line 105 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/337#-NLtxZEF5qms08vP-dyW:-NLuVkII2siqMaXvF3Gh:b-pu8t0v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2916cae7607cc1222a4a900164ece5872e33c7b9/pkg/config/deterministic_gas.go#L105)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is this todo still relevant ? 
will you rewise other msg types in the next PR or it is completed now ?
</blockquote></details>

It is not, removed.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/337)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/337)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
