### PR TITLE
Move deterministic gas config to `x/deterministicgas`

### PR DESCRIPTION
**Pull request by wojtek-coreum**
Deterministic gas config depends on wasm and any executable importing it must be compiled with libwasmvm.
`pkg/config` package must not require this dependency because it is imported by other modules. That's why deterministic gas config must be moved.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/361)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/361)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/361#-NMbtDaB-KJTGdDD6aI3:-NMbtDaB-KJTGdDD6aI4:b-k0ibv1) (no related file):*
It might be easier to review this PR commit by commit

___

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/361)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/361#-NMchiHgAZaiaD6f_q04:-NMchiHgAZaiaD6f_q05:b-72tm69) (no related file):*
Everything looks good IMO except one thing.
I propose to rename `DeterministicGasRequirements` structure because:

1. Deterministic word is not that correct since it contains config for both deterministic & undeterministic msgs
2. I don't like word Requirements here. We picked it to not conflict with config package name. But now it is not applicable anymore since we moved it to another pkg

I propose to rename it to `deterministicgas.Config` or `deterministicgas.GasConfig` in all places
We can also use `deterministicgas.Params` but It might confuse with cosmos SDK params

___

**Review by miladz68 — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/361)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/361)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/361#-NMchiHgAZaiaD6f_q04:-NMhCpPC-7tlhD6pJlT1:b-896fix) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Everything looks good IMO except one thing.
I propose to rename `DeterministicGasRequirements` structure because:

1. Deterministic word is not that correct since it contains config for both deterministic & undeterministic msgs
2. I don't like word Requirements here. We picked it to not conflict with config package name. But now it is not applicable anymore since we moved it to another pkg

I propose to rename it to `deterministicgas.Config` or `deterministicgas.GasConfig` in all places
We can also use `deterministicgas.Params` but It might confuse with cosmos SDK params

</blockquote></details>

Done.

___

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/361)* status: all files reviewed, 6 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

___
*[`integration-tests/chain.go` line 24 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/361#-NMhmddsCfqKZD2GPfN-:-NMhmddsCfqKZD2GPfN0:b-xcudtt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/103e0d56b61bf944cf08ad4207db35b3dd8a92fb/integration-tests/chain.go#L24)):*
> ```Go
> 	ClientContext    tx.ClientContext
> 	NetworkConfig    config.NetworkConfig
> 	DeterministicGas deterministicgas.Config
> ```

minor:
DeterministicGas -> DeterministicGasConfig



_Code quote:_
```Go
DeterministicGas
```
___
*[`x/auth/ante/ante.go` line 23 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/361#-NMhmViV4fWQHx-EX2qW:-NMhmViV4fWQHx-EX2qX:bsu75u4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/103e0d56b61bf944cf08ad4207db35b3dd8a92fb/x/auth/ante/ante.go#L23)):*
> ```Go
> // HandlerOptions are the options required for constructing a default SDK AnteHandler.
> type HandlerOptions struct {
> 	DeterministicGasRequirements deterministicgas.Config
> ```

can you also check places like this `DeterministicGasRequirements` -> `DeterministicGasConfig`

so we need to make sure we use new naming everywhere no `Requirements` anymore
___
*[`x/deterministicgas/ante/ante.go` line 38 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/361#-NMhn0XeAbgtg2RmAooW:-NMhn0XeAbgtg2RmAooX:brs0v0q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/103e0d56b61bf944cf08ad4207db35b3dd8a92fb/x/deterministicgas/ante/ante.go#L38)):*
> ```Go
> type AddBaseGasDecorator struct {
> 	ak                           authante.AccountKeeper
> 	deterministicGasRequirements deterministicgas.Config
> ```

no Requirements
___
*[`x/deterministicgas/config.go` line 39 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/361#-NMhmwv62zqp4Vvb2Lth:-NMhmwv62zqp4Vvb2Lti:bjmw3qv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/103e0d56b61bf944cf08ad4207db35b3dd8a92fb/x/deterministicgas/config.go#L39)):*
> ```Go
> // DefaultConfig returns default config for deterministic gas.
> func DefaultConfig() Config {
> 	dgr := Config{
> ```

dgr -> c/conf ...
___
*[`x/deterministicgas/config.go` line 136 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/361#-NMhmqjJ6Vwkx7xuCAUe:-NMhmqjJ6Vwkx7xuCAUf:bguuwkv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/103e0d56b61bf944cf08ad4207db35b3dd8a92fb/x/deterministicgas/config.go#L136)):*
> ```Go
> // TxBaseGas is the free gas we give to every transaction to cover costs of
> // tx size and signature verification. TxBaseGas is covered by FixedGas.
> func (dgr Config) TxBaseGas(params authtypes.Params) uint64 {
> ```

dgr -> c/conf ...

in all places
___
*[`x/deterministicgas/config_test.go` line 116 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/361#-NMhmyN0AtMGTThshcgJ:-NMhmyN0AtMGTThshcgK:bjmw3qv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/103e0d56b61bf944cf08ad4207db35b3dd8a92fb/x/deterministicgas/config_test.go#L116)):*
> ```Go
> 	}
> 
> 	dgr := deterministicgas.DefaultConfig()
> ```

dgr -> c/conf ...

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 8 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/361)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
