### PR TITLE
Make integration-tests stable

### PR DESCRIPTION
**Pull request by ysv**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/761)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/761)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`pkg/client/tx.go` line 297 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/761#-NmpPd6P2DTmofVuHcQe:-NmpiT4gESDXLIyADJ-f:b8o20so) ([raw file](https://github.com/CoreumFoundation/coreum/blob/be0d72d5e632cded16246fc825829c56f13ea661/pkg/client/tx.go#L297)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

waiting for 3 extra blocks helps and makes test stable in CI

if you are ok with this approach I can move this (block number to wait) into `TimeoutConfig` structure.
I propose to use 3 for integration-tests and for now 0 by default inside client because I'm not sure if this should be behaviour of default client. 

We can live with this  solution inside integration-tests for some time and see if this resolves our issue because right now I tried to run CI for ~10 times and had no failures
</blockquote></details>

I think it is ok for now.

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/761)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/761)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`pkg/client/tx.go` line 297 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/761#-NmpPd6P2DTmofVuHcQe:-NnJTtwx3mtVFmfVD_M_:bmz2463) ([raw file](https://github.com/CoreumFoundation/coreum/blob/be0d72d5e632cded16246fc825829c56f13ea661/pkg/client/tx.go#L297)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think it is ok for now.
</blockquote></details>

ok, moved it to a separate config & fixed some one issue in tests

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/761)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @wojtek-coreum)

**Pull request merged**
