### PR TITLE
The integration of the cosmos-sdk NFT module to the coreum chain.

### PR DESCRIPTION
**Pull request by dzmitryhil**
The PR is from the batch with the updates to the branch with the copy

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 48 of 52 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: 46 of 52 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`app/app.go` line 200 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4DmuxAHugBYOHTuK-:-NH4Dmuy4Opz4ZftkOn6:bkm5see) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/app/app.go#L200)):*
> ```Go
> 		wasm.ModuleName:                {authtypes.Burner},
> 		assettypes.ModuleName:          {authtypes.Minter, authtypes.Burner},
> 		nft.ModuleName:                 nil,
> ```

is it needed?
___
*[`x/nft/client/testutil/test_helper.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4HOHcB9yM_yAh28dz:-NH4HOHcB9yM_yAh28e-:b-hi01y6) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/x/nft/client/testutil/test_helper.go#L14)):*
> ```Go
> )
> 
> func ExecSend(val *sdknetwork.Validator, args []string) (testutil.BufferWriter, error) { //nolint:revive // test helper
> ```

what's wrong about revive in this file?
___
*[`x/nft/conv/doc.go` line 2 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4Foon6qjcTtP-AhYx:-NH4Foon6qjcTtP-AhYy:b1x9e2x) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/x/nft/conv/doc.go#L2)):*
> ```Go
> // Package conv provides internal functions for convertions and data manipulation
> package conv
> ```

do we need this file?
___
*[`x/nft/conv/string.go` line 10 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4GSVzBX9KV4_MIAAb:-NH4GSVzBX9KV4_MIAAc:b-mgskph) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/x/nft/conv/string.go#L10)):*
> ```Go
> // UnsafeStrToBytes uses unsafe to convert string into byte array. Returned bytes
> // must not be altered after this function is called as it will cause a segmentation fault.
> func UnsafeStrToBytes(s string) []byte {
> ```

interesting, will use it in my project
___
*[`x/nft/keeper/keys.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4FAn31LHE7SJcr89r:-NH4FAn31LHE7SJcr89s:b-z2o5rf) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/x/nft/keeper/keys.go#L14)):*
> ```Go
> 
> var (
> 	ClassKey             = []byte{0x01} //nolint:revive // store key
> ```

why does revive complaint?

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 52 of 52 files at r1.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: 50 of 52 files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`testutil/network/network.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4SDXoC_Yr2bglQS2i:-NH4SDXoC_Yr2bglQS2j:b-m86fvl) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/testutil/network/network.go#L34)):*
> ```Go
> 	// Config defines the necessary configuration used to bootstrap and start an
> 	// in-process local testing network
> 	Config = network.Config
> ```

does this imported network package run a full node with n number of validators ? I am think if this is true we can completely replace crust with this ?
___
*[`x/nft/conv/doc.go` line 2 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4RPgg7EgpmYUiki4K:-NH4RPgg7EgpmYUiki4L:b-y48i7t) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/x/nft/conv/doc.go#L2)):*
> ```Go
> // Package conv provides internal functions for convertions and data manipulation
> package conv
> ```

let's mention from where this package is copied

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: 50 of 52 files reviewed, 7 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 200 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4DmuxAHugBYOHTuK-:-NH4fVzrCxU7HqoYgwR7:bgzs3wj) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/app/app.go#L200)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

is it needed?
</blockquote></details>

It was in the sdk integration, but based on the code we don't need it, removed.



_Code quote:_
```Go
	nft.ModuleName:                 nil,
```
___
*[`testutil/network/network.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4SDXoC_Yr2bglQS2i:-NH4fdVo4IfBeiHnjaOZ:b2gddus) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/testutil/network/network.go#L34)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

does this imported network package run a full node with n number of validators ? I am think if this is true we can completely replace crust with this ?
</blockquote></details>

Yes you can, and I told the team about it 2 months ago :-)
We can keep the crust but add a mode for the integration test to run them against the simapp network, that will speed up the development.
___
*[`x/nft/client/testutil/test_helper.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4HOHcB9yM_yAh28dz:-NH4gBFOA4QbBYiLqt6Q:b-y4921n) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/x/nft/client/testutil/test_helper.go#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what's wrong about revive in this file?
</blockquote></details>

The file isn't _test, and you need to comment on all exported. I decided not to touch the filename to see the changes better.



_Code quote:_
```Go
func ExecSend(val *sdknetwork.Validator, args []string) (testutil.BufferWriter, error) {
```
___
*[`x/nft/conv/doc.go` line 2 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4Foon6qjcTtP-AhYx:-NH4gTNfBetEfylw39vM:b-glu9ry) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/x/nft/conv/doc.go#L2)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

do we need this file?
</blockquote></details>

Nope, removed. We don't use the go docs.



_Code quote:_
```Go
// Package conv provides internal fu
```
___
*[`x/nft/conv/doc.go` line 2 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4RPgg7EgpmYUiki4K:-NH4gX-O6yu9L0mA9ZY6:b-om2p8h) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/x/nft/conv/doc.go#L2)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's mention from where this package is copied 
</blockquote></details>

Sure, updated. 
___
*[`x/nft/conv/string.go` line 10 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4GSVzBX9KV4_MIAAb:-NH4hArG64t76oY5x87a:b2nh4j5) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/x/nft/conv/string.go#L10)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

interesting, will use it in my project
</blockquote></details>

:-)
___
*[`x/nft/keeper/keys.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4FAn31LHE7SJcr89r:-NH4hD30EGbicdq2Z5iB:b-fzm4mr) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/x/nft/keeper/keys.go#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why does revive complaint?
</blockquote></details>

Yes, comments for names.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`testutil/network/network.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4SDXoC_Yr2bglQS2i:-NH4tAGGAfvy-XOBfzZE:b-zcbo8v) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/testutil/network/network.go#L34)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes you can, and I told the team about it 2 months ago :-)
We can keep the crust but add a mode for the integration test to run them against the simapp network, that will speed up the development.
</blockquote></details>

I remember the discussion some time ago, but the unanswered question was whether it supports multiple validators and we assume that it does not support it.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`testutil/network/network.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4SDXoC_Yr2bglQS2i:-NH55l3DDO2XOv9Mhpv9:b4swxwr) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/testutil/network/network.go#L34)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I remember the discussion some time ago, but the unanswered question was whether it supports multiple validators and we assume that it does not support it. 
</blockquote></details>

But it supports :-)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: all files reviewed, 5 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 48 of 52 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH9osj-7XEEv36vbie1:-NH9osj0AwIzdfBePrpe:bjzfyg1) (no related file):*
I can see that we have only x/nft didn't we confirm to have x/wnft also or it is not needed anymore ?

___
___
*[`x/nft/client/testutil/query.go` line 386 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH9sEWc45Phjqdr_Bzr:-NH9sEWc45Phjqdr_Bzs:b-7z2fch) ([raw file](https://github.com/coreumfoundation/coreum/blob/1d7ada652e527145bd9870fa213012ff21b44a55/x/nft/client/testutil/query.go#L386)):*
> ```Go
> }
> 
> func (s *IntegrationTestSuite) TestQuerySupply() { //nolint:revive // test
> ```

can we disable for a whole file ?
___
*[`proto/coreum/nft/v1beta1/query.proto` line 14 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH9pSBX1A84_kA8m90w:-NH9pSBX1A84_kA8m90x:b-qxb7pf) ([raw file](https://github.com/coreumfoundation/coreum/blob/1d7ada652e527145bd9870fa213012ff21b44a55/proto/coreum/nft/v1beta1/query.proto#L14)):*
> ```protobuf
>   // Balance queries the number of NFTs of a given class owned by the owner, same as balanceOf in ERC721
>   rpc Balance(QueryBalanceRequest) returns (QueryBalanceResponse) {
>     option (google.api.http).get = "/coreum/nft/v1beta1/balance/{owner}/{class_id}";
> ```

do we have `/cosmos` in all other std module REST APIs also ?

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

___
*[`x/nft/conv/string.go` line 10 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH9x3v7DlRqhpSnir6g:-NH9x3v8Dav4J8VS2R81:brtqsam) ([raw file](https://github.com/coreumfoundation/coreum/blob/1d7ada652e527145bd9870fa213012ff21b44a55/x/nft/conv/string.go#L10)):*
> ```Go
> // UnsafeStrToBytes uses unsafe to convert string into byte array. Returned bytes
> // must not be altered after this function is called as it will cause a segmentation fault.
> func UnsafeStrToBytes(s string) []byte {
> ```

where do we use this ?
I see usage of it in tests only

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`x/nft/keeper/keys.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4FAn31LHE7SJcr89r:-NHOGv_y4fv2_2awNTyC:b-8qkqz6) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/x/nft/keeper/keys.go#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes, comments for names. 
</blockquote></details>

Can't we add the comments then?

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil)

___
*[`x/nft/client/testutil/query.go` line 386 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH9sEWc45Phjqdr_Bzr:-NHPD8Y70F5tF-A5FvsC:b-kzr062) ([raw file](https://github.com/coreumfoundation/coreum/blob/1d7ada652e527145bd9870fa213012ff21b44a55/x/nft/client/testutil/query.go#L386)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

In the comon linter doc only in the crust. But it will be weird since it's shared among multiple repos.
</blockquote></details>

I mean this
Because this directive is repeated a lot of times in this file for each function so we can disable in completely. WDYT ?


___
*[`x/nft/conv/string.go` line 10 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH9x3v7DlRqhpSnir6g:-NHPDTmmEXHvNfL9qe3H:b-c8nzf9) ([raw file](https://github.com/coreumfoundation/coreum/blob/1d7ada652e527145bd9870fa213012ff21b44a55/x/nft/conv/string.go#L10)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes, but it's sage
</blockquote></details>

if it is a common code which we will use in other modules I suggest to move it to coreum/pkg (store/key.go probably is a good place)
___
*[`x/nft/conv/string.go` line 10 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NHPDmtx22_rqsLR6sUa:-NHPDmty4-RQPXqbjSBM:bwvvwdd) ([raw file](https://github.com/coreumfoundation/coreum/blob/1d7ada652e527145bd9870fa213012ff21b44a55/x/nft/conv/string.go#L10)):*
> ```Go
> // UnsafeStrToBytes uses unsafe to convert string into byte array. Returned bytes
> // must not be altered after this function is called as it will cause a segmentation fault.
> func UnsafeStrToBytes(s string) []byte {
> ```

Is this code introduced by you or it is done like this in cosmos SDK ?

so the main benefit is that it uses zero allocation but in terms of speed I'm not sure if it is faster because keys are not that long to copy them while type casting is s expensive operation AFAIK
___
*[`proto/coreum/nft/v1beta1/query.proto` line 14 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH9pSBX1A84_kA8m90w:-NHPEv-58DKPICpmABaP:bqt3erb) ([raw file](https://github.com/coreumfoundation/coreum/blob/1d7ada652e527145bd9870fa213012ff21b44a55/proto/coreum/nft/v1beta1/query.proto#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

yes we have cosmos there
</blockquote></details>

so actually all our REST endpoints look like this `localhost:1317/cosmos/gov/...` ?
But we are not going to expose REST API officially or we do ? I know that we need it at least for keplr

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: 52 of 54 files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/nft/client/testutil/query.go` line 386 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH9sEWc45Phjqdr_Bzr:-NHUI1_t7sfhMVWENZKK:b5du9tr) ([raw file](https://github.com/coreumfoundation/coreum/blob/1d7ada652e527145bd9870fa213012ff21b44a55/x/nft/client/testutil/query.go#L386)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I mean this
Because this directive is repeated a lot of times in this file for each function so we can disable in completely. WDYT ?



</blockquote></details>

Right, updated, thanks. 
___
*[`x/nft/conv/string.go` line 10 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH9x3v7DlRqhpSnir6g:-NHUI6pX24ZPddsrDdr1:b-bziq8w) ([raw file](https://github.com/coreumfoundation/coreum/blob/1d7ada652e527145bd9870fa213012ff21b44a55/x/nft/conv/string.go#L10)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

if it is a common code which we will use in other modules I suggest to move it to coreum/pkg (store/key.go probably is a good place)
</blockquote></details>

This is used by that module only, I don't see the use case for us for now.
___
*[`x/nft/conv/string.go` line 10 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NHPDmtx22_rqsLR6sUa:-NHUIOHp3Lq5Qr7c1N2I:b-i1f4vw) ([raw file](https://github.com/coreumfoundation/coreum/blob/1d7ada652e527145bd9870fa213012ff21b44a55/x/nft/conv/string.go#L10)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Is this code introduced by you or it is done like this in cosmos SDK ?

so the main benefit is that it uses zero allocation but in terms of speed I'm not sure if it is faster because keys are not that long to copy them while type casting is s expensive operation AFAIK
</blockquote></details>

This is the SDK-related code, It was copied from the v0.46 SDK version
___
*[`x/nft/keeper/keys.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH4FAn31LHE7SJcr89r:-NHUIwEw67vxo7PtNXtY:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/x/nft/keeper/keys.go#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Can't we add the comments then?
</blockquote></details>

Updated.
___
*[`proto/coreum/nft/v1beta1/query.proto` line 14 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH9pSBX1A84_kA8m90w:-NHUHTof7VFar6aqKOB5:bnbet4q) ([raw file](https://github.com/coreumfoundation/coreum/blob/1d7ada652e527145bd9870fa213012ff21b44a55/proto/coreum/nft/v1beta1/query.proto#L14)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so actually all our REST endpoints look like this `localhost:1317/cosmos/gov/...` ?
But we are not going to expose REST API officially or we do ? I know that we need it at least for keplr 
</blockquote></details>

The API you share is the cosmos API, our API is (example from feemodel): `/coreum/feemodel/v1/min_gas_price` you can check the swagger doc as well.

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

___
*[`proto/coreum/nft/v1beta1/query.proto` line 14 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH9pSBX1A84_kA8m90w:-NHVFmQz-zqwJvfVH27o:bozezys) ([raw file](https://github.com/coreumfoundation/coreum/blob/1d7ada652e527145bd9870fa213012ff21b44a55/proto/coreum/nft/v1beta1/query.proto#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The API you share is the cosmos API, our API is (example from feemodel): `/coreum/feemodel/v1/min_gas_price` you can check the swagger doc as well. 
</blockquote></details>

ok
I just think that it would be nice to have everything coreum branded but it is probably impossible so lets keep it as is

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NHZg-6m0pRKPjxnD437:-NHZg-6nBIs2remzNzaX:b650ks1) (no related file):*
x/nft/simulation/operations.go:74

```golang
spendableCoins := bk.SpendableCoins(ctx, sender.Address)
fees, err := simtypes.RandomFees(r, ctx, spendableCoins)
if err != nil {
    return simtypes.NoOpMsg(nft.ModuleName, TypeMsgSend, err.Error()), nil, err
}

spendLimit := spendableCoins.Sub(fees)
if spendLimit == nil {
    return simtypes.NoOpMsg(nft.ModuleName, TypeMsgSend, "spend limit is nil"), nil, nil
}
```

In expectedKeepers we have SpendableCoins and the only place we use it is in tests
I just don't understand why we need bank keeper in x/nft at all ?

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NHZgJlz1l6x4505yPBb:-NHZgJlz1l6x4505yPBc:b-g4vdsb) (no related file):*
Since most of files in x/nft are copied from cosmos but we are not sure which version exactly etc
WDYT about annotating all of them and putting comment that this module was copied from cosmos-sdk version <sha256> of commit with minor changes. Then we can easier trace & review changes and later update it. Currently I can't be sure which version you used

___
___
*[`proto/coreum/nft/v1beta1/query.proto` line 14 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NH9pSBX1A84_kA8m90w:-NHZfqBNCrAee_mgNwO-:b-p4boor) ([raw file](https://github.com/coreumfoundation/coreum/blob/1d7ada652e527145bd9870fa213012ff21b44a55/proto/coreum/nft/v1beta1/query.proto#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not sure since it's expected for the 3d party integrations to have such cosmos routes. 
</blockquote></details>

I agree that is why it brings more issues so lets keeep I'm ok

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: 53 of 55 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NHZg-6m0pRKPjxnD437:-NHZh9lx2KpB0E5u5yGF:bj0jwxi) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

x/nft/simulation/operations.go:74

```golang
spendableCoins := bk.SpendableCoins(ctx, sender.Address)
fees, err := simtypes.RandomFees(r, ctx, spendableCoins)
if err != nil {
    return simtypes.NoOpMsg(nft.ModuleName, TypeMsgSend, err.Error()), nil, err
}

spendLimit := spendableCoins.Sub(fees)
if spendLimit == nil {
    return simtypes.NoOpMsg(nft.ModuleName, TypeMsgSend, "spend limit is nil"), nil, nil
}
```

In expectedKeepers we have SpendableCoins and the only place we use it is in tests
I just don't understand why we need bank keeper in x/nft at all ?

</blockquote></details>

In the tests :-)
I saw it as well, and even wanted to redo it, but then I understood that we should keep the code as is for the further easier merge or changes detection.

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NHZgJlz1l6x4505yPBb:-NHZhS5X5iESenImK8Qz:b9rh2wm) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Since most of files in x/nft are copied from cosmos but we are not sure which version exactly etc
WDYT about annotating all of them and putting comment that this module was copied from cosmos-sdk version <sha256> of commit with minor changes. Then we can easier trace & review changes and later update it. Currently I can't be sure which version you used
</blockquote></details>

Right, I've created the README.md the module root with the description and revision version.

___

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 52 files at r1, 2 of 2 files at r2, 3 of 4 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil)

___
*[`testutil/rest/rest.go` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NHcancVCsoZe5DzCDyT:-NHcancW9BePwFx4YB1w:bstomxf) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/testutil/rest/rest.go#L12)):*
> ```Go
> // GetRequest defines a wrapper around an HTTP GET request with a provided URL.
> // An error is returned if the request or reading the body fails.
> func GetRequest(url string) ([]byte, error) {
> ```

I see that this function is used only in tests but would be nice to use context with timeout here
___
*[`x/nft/simulation/test_helpers.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NHcbK4YCrwAg1VERQk9:-NHcbK4YCrwAg1VERQkA:b-3rvuj9) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/x/nft/simulation/test_helpers.go#L15)):*
> ```Go
> 
> const (
> 	// DefaultGenTxGas defines the default gas tp spend on tx.
> ```

tp -> to

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum)

___
*[`testutil/rest/rest.go` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NHcancVCsoZe5DzCDyT:-NHcj38v1qQhLaYoHdxi:bb025jg) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/testutil/rest/rest.go#L12)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I see that this function is used only in tests but would be nice to use context with timeout here
</blockquote></details>

Right, I saw it as well, but that's the SDK way and the idea is to keep the code as much the same as original.
___
*[`x/nft/simulation/test_helpers.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/264#-NHcbK4YCrwAg1VERQk9:-NHcjUhBAFmiLZJI8bQ6:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/6b161c9310c3b9a02d51f959e94fd73af9e9467e/x/nft/simulation/test_helpers.go#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

tp -> to
</blockquote></details>

Done.



_Code quote:_
```Go
 DefaultGenTxGas defines the default gas tp spend on tx.
```

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/264)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Pull request merged**
