### PR TITLE
Implement v3 app-upgrade with migration from cosmos sdk v45 to v47

### PR DESCRIPTION
**Pull request by ysv**
# Description

The main purpose of this PR is to add `app/upgrade/v3/upgrade.go` which correctly migrates from v2.0.2 (cosmos v45) to v3 (cosmos v47). It also contains fixed integration tests for the upgrade.
This PR also contains some side changes:
- Moved legacy methods from `Governance` to `GovernanceLegacy` inside integration-tests. Once fully to new sdk & govv1 GovernanceLegacy will probably be removed
- Removed integrations tests related to previous upgrades
- Added TODOs to be resolved in future PRs

Blocked by related crust PR https://github.com/CoreumFoundation/crust/pull/277

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-Ncbxjv7CYD20Bnrn7_O:-Ncbxjv7CYD20Bnrn7_P:b-8rq4kd) (no related file):*
Block: crust PR should be merged first

___

**Review by ysv — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
Merge the `v0.47-migration-v2` please to check that it's compatible with the current `v0.47-migration-v2` state.

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-:-Ncfj_tL3hV-Nrg5tzA3:b-oxlh9e)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-Ncg1i7L6gLFi3aDEcrG:-Ncg1i7M5YDIyvg4NG8s:b-gi8ziv) (no related file):*
https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/UPGRADING.md#simulation

```
Remove `RandomizedParams` from `AppModuleSimulation` interface.
``

Remove the usage please, or add the reference to that page to the task `FIXME(v47-module-config)` 
```


___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgDTM81q-QOMHh9chY:-NcgDTM81q-QOMHh9chZ:b9b7sz5) (no related file):*
This migration is optional based on the doc: https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/UPGRADING.md#new-proposalproposer-field
But what if there is a proposal that is pending before the upgrade? Will it pass or fail, or halt the chain? IMO we need to check it at least in the source code.

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgEtK32hK0IPZh4lJI:-NcgEtK32hK0IPZh4lJJ:b728txn) (no related file):*
Since we haven't decided what to do with the `IBC Fee hooks`, we need to add a task to return back to migration and decide whether to call `SetFeeEnabled` for all transfer channels or not.

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgGdJZ4EGFVpWg04d3:-NcgGdJZ4EGFVpWg04d4:b5my1z0) (no related file):*
What about the upgrade integration test to test all the changes you made in the upgrade?

___

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 14 files at r1, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: all files reviewed, 8 unresolved discussions (waiting on @vertex451, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci-v0.47-migration.yml` line 49 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcbELLCDyOWGaljHviX:-NccHR4S7Jx2wsIKWkbK:b-q8ilnv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/139b3541f4a21e59808f2e3e154555102a7a1b66/.github/workflows/ci-v0.47-migration.yml#L49)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

@miladz68 this if for your IBC PR
</blockquote></details>

gotcha
___
*[`app/upgrade/v3/upgrade.go` line 104 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcbqzYr99jod97pw6Ii:-NcgGSFVEKzeFymBSkz5:bcb0hyh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d715181cddc96329677e98cbd3a19b96d57ff698/app/upgrade/v3/upgrade.go#L104)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

as far as I know we don't have interchain accounts integrated.
That is why I don't need to migrate params for them also upgrade works without this part

Confusing part is that we have Msgs https://github.com/CoreumFoundation/coreum/blob/v0.47-migration-v2/app/amino_test.go#L78

But I still think ICAs are not integrated. pls correct me if I'm wrong
</blockquote></details>

ICAs are not integrated and you don't need to migrate them. The reason that they are in the test is not clear to me as well,  maybe just a precaution for the time that we decide to integrate them. 
___
*[`integration-tests/gov_legacy.go` line 29 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NccHmSr4nW_mXHnrUBf:-NccHmSr4nW_mXHnrUBg:bhqg9bl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/80529e250c5c1fe3f39172d4a9712fa033d4d26c/integration-tests/gov_legacy.go#L29)):*
> ```Go
> // 2. Migrate to new proposal types. Mostly initialize by NewMsgSubmitProposalV1 method.
> // 3. Get rid of interactions with cored v2 (inside upgrade tests) which uses v1beta1 API.
> type GovernanceLegacy struct {
> ```

we don't need this, all the legacy functionalities are supported with 1 or 2 functions. Let's dicsuss it in a meeting

**Review by ysv — COMMENTED** [review]
But it is already up to date 


> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-:-NcgJjEN3rvFbMPIjz7g:b5vry59)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-Ncg1i7L6gLFi3aDEcrG:-NcgLCxwAW9jze6cFKtx:bx6bmta) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/UPGRADING.md#simulation

```
Remove `RandomizedParams` from `AppModuleSimulation` interface.
``

Remove the usage please, or add the reference to that page to the task `FIXME(v47-module-config)`
```

</blockquote></details>

we don't have this method mentions at all 


___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgGdJZ4EGFVpWg04d3:-NcgLKhTBDGgRwKnQdAV:boiybzx) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about the upgrade integration test to test all the changes you made in the upgrade?
</blockquote></details>

they should definitely be added but not in scope of this PR & task

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgEtK32hK0IPZh4lJI:-NcgLReU31Ph01Ahfps3:bghcd43) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Since we haven't decided what to do with the `IBC Fee hooks`, we need to add a task to return back to migration and decide whether to call `SetFeeEnabled` for all transfer channels or not.
</blockquote></details>

I agree
lets add it to umbrella task ? Or you want me to leave todo in code also ?

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgDTM81q-QOMHh9chY:-NcgQhZc3QsIN6ugWKgh:b-1n19l) (no related file):*
very good point thx I skipped it

I'm ok to add this but I have no idea which value we should set there. Should it be module account ?

> IMO we need to check it at least in the source code.
Lets write an integration-test for it. 

___
___
*[`app/upgrade/v3/upgrade.go` line 104 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcbqzYr99jod97pw6Ii:-NcgLiEn1f1E5Mx1X2Ia:b-e7e9lr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d715181cddc96329677e98cbd3a19b96d57ff698/app/upgrade/v3/upgrade.go#L104)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

ICAs are not integrated and you don't need to migrate them. The reason that they are in the test is not clear to me as well,  maybe just a precaution for the time that we decide to integrate them.
</blockquote></details>

ok removed
___
*[`integration-tests/gov_legacy.go` line 29 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NccHmSr4nW_mXHnrUBf:-NcgLj_N916upM9AoVcQ:b-9481b2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/80529e250c5c1fe3f39172d4a9712fa033d4d26c/integration-tests/gov_legacy.go#L29)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we don't need this, all the legacy functionalities are supported with 1 or 2 functions. Let's dicsuss it in a meeting
</blockquote></details>

There are multiple reasons I decided to split them. It is not only because of these 2 funcs
I can explain in the call all details

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
You are right, compared with different branch. 

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-:-NcgStSH7p1kgYYgon3d:b-n8rgu)* status: 14 of 15 files reviewed, 4 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-Ncg1i7L6gLFi3aDEcrG:-NcgSA0UB80NWyy61F6f:b-6u1pdu) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

we don't have this method mentions at all 

</blockquote></details>

Yes, we have. 



___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgDTM81q-QOMHh9chY:-NcgTDqY2lLhCc5nJIGr:b-xslepq) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

very good point thx I skipped it

I'm ok to add this but I have no idea which value we should set there. Should it be module account ?

> IMO we need to check it at least in the source code.
Lets write an integration-test for it.
</blockquote></details>

The module address makes sense. Let's at least test that with an empty address it will still work, and if - yes, we can ignore it. 

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgEtK32hK0IPZh4lJI:-NcgTRz08pZToc2oSJNC:b-ui5d75) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree
lets add it to umbrella task ? Or you want me to leave todo in code also ?
</blockquote></details>

Better to add to the umbrella.

___

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-Ncg1i7L6gLFi3aDEcrG:-NcgU_Bn4e0PzHzwNC5M:b-623exj) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes, we have. 


</blockquote></details>

Are u sure you have up to date branch ?
This code doesn't exist in mine 

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgEtK32hK0IPZh4lJI:-NcgV5DW1k_83GpTVIhF:b-8b11j9) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Better to add to the umbrella.
</blockquote></details>

Added

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgDTM81q-QOMHh9chY:-NcgVO8hEl_dA_7GX7rJ:bmdwatg) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The module address makes sense. Let's at least test that with an empty address it will still work, and if - yes, we can ignore it.
</blockquote></details>

added to integration-tests ticket

___

**Review by ysv — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

**Review by ysv — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 10 files at r2, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: all files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`app/upgrade/v3/upgrade.go` line 142 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-Ncgda6m1fCwGWhxqbgJ:-NcgoO1n08bUyMUtWNq2:b-b1rqvq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2fdda29e6310fb9f44f7ccd40e3f6c3bfabc0cf4/app/upgrade/v3/upgrade.go#L142)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is it safe to go v4 -> v5 -> v7? Is it possible to apply v6 later? I imagine it isn't. And probably skipping version is a call for problems.
</blockquote></details>

since we don't have interchain accounts, this migration does not apply, so the comment is not really needed IMO.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: all files reviewed, 9 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-Ncg1i7L6gLFi3aDEcrG:-NcgqwKEABiyJycXS47h:b3godj8) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Are u sure you have up to date branch ?
This code doesn't exist in mine
</blockquote></details>

You are right. That was the issue with my IDE (the same was with my previous comment), I did the pull VIA CLI and now I don't see that code. 

___

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 5 of 14 files at r1, 5 of 10 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: all files reviewed, 9 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 14 files at r1, 4 of 10 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: all files reviewed, 8 unresolved discussions (waiting on @vertex451, @wojtek-coreum, and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: 12 of 15 files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`app/upgrade/v3/upgrade.go` line 68 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgcMJZ65AhcfUkVh25:-NchKLup6i37tQFHmOsd:b-7tdf7d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2fdda29e6310fb9f44f7ccd40e3f6c3bfabc0cf4/app/upgrade/v3/upgrade.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

using `StoreKey` constant is a better choice, it points to `ModuleName` anyway but let's follow the convention
</blockquote></details>

agree
___
*[`app/upgrade/v3/upgrade.go` line 94 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-Ncgd3H_3kdARO8UiOqr:-NchL2Kp-ugwkluDHNTZ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2fdda29e6310fb9f44f7ccd40e3f6c3bfabc0cf4/app/upgrade/v3/upgrade.go#L94)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Define this once outside for loop
</blockquote></details>

Done.
___
*[`app/upgrade/v3/upgrade.go` line 124 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgdFGw6I13sNAfyujW:-NchADxi7ekct8nPlnR_:brl3zg7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2fdda29e6310fb9f44f7ccd40e3f6c3bfabc0cf4/app/upgrade/v3/upgrade.go#L124)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why are params migrated from one deprecated module to another deprecated one?
</blockquote></details>

I have checked and probably x/consensus is not deprecated
___
*[`app/upgrade/v3/upgrade.go` line 142 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-Ncgda6m1fCwGWhxqbgJ:-NchAYYe2m9wG3Z4IKVD:bj8czos) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2fdda29e6310fb9f44f7ccd40e3f6c3bfabc0cf4/app/upgrade/v3/upgrade.go#L142)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

since we don't have interchain accounts, this migration does not apply, so the comment is not really needed IMO.
</blockquote></details>

will remove comment
___
*[`integration-tests/upgrade/ft_test.go` line  at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgbZuc5oXaPbTgCvzn:-NchO-ZE51RPagDcTSQC:bzg5o8t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2fdda29e6310fb9f44f7ccd40e3f6c3bfabc0cf4/integration-tests/upgrade/ft_test.go#L)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Previous upgrade tests should not be blindly removed. There are tests which should be moved to the `modules`, like testing features and enabled/disabled IBC
</blockquote></details>

restored & added to the next task
___
*[`integration-tests/upgrade/nft_test.go` line  at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgboLn3xiCOpTT4giA:-NchO1Z-EgWGnyk4uU87:bzg5o8t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2fdda29e6310fb9f44f7ccd40e3f6c3bfabc0cf4/integration-tests/upgrade/nft_test.go#L)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

those tests should be inspected as well
</blockquote></details>

restored & added to the next task

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)

___
*[`app/upgrade/v3/upgrade.go` line 89 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgcgOX0GFdwqaD57bJ:-Ncvn84k193MO1vqTxu8:b533fbt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2fdda29e6310fb9f44f7ccd40e3f6c3bfabc0cf4/app/upgrade/v3/upgrade.go#L89)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Did this module have any params in v0.45. If yes, then maybe we should remove them from store?
</blockquote></details>

as far as I understand it works a bit differently here.

In this line we init the params table inside legacy x/params module unless it already exists so migration runs successfully.

Here is an example of x/mint:
- here they init params table unless exist https://github.com/cosmos/cosmos-sdk/pull/12363/files#diff-eff63269a2122bd0bc1c08f3d029aa99812aa47ce9fd85ef531dc3e04327ffc5L36
- here they run migration itself: https://github.com/cosmos/cosmos-sdk/pull/12363/files#diff-70c6456dd59864aed21d7193e52f59428d405cdf436f5c70a57b1d074d14caf4R22

But since creation of params table was removed in v47 now we should init it inside upgrade so Migrate function succeeds.
That is how I understand it

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)

___
*[`app/upgrade/v3/upgrade.go` line 89 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgcgOX0GFdwqaD57bJ:-Ncvur8m1UiWdoI6Ntar:br793k8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2fdda29e6310fb9f44f7ccd40e3f6c3bfabc0cf4/app/upgrade/v3/upgrade.go#L89)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

as far as I understand it works a bit differently here.

In this line we init the params table inside legacy x/params module unless it already exists so migration runs successfully.

Here is an example of x/mint:
- here they init params table unless exist https://github.com/cosmos/cosmos-sdk/pull/12363/files#diff-eff63269a2122bd0bc1c08f3d029aa99812aa47ce9fd85ef531dc3e04327ffc5L36
- here they run migration itself: https://github.com/cosmos/cosmos-sdk/pull/12363/files#diff-70c6456dd59864aed21d7193e52f59428d405cdf436f5c70a57b1d074d14caf4R22

But since creation of params table was removed in v47 now we should init it inside upgrade so Migrate function succeeds.
That is how I understand it
</blockquote></details>

Also I have checked IBC module 02-client pkg
And they don't have params migration in version 7.2.0 (we use it) but they do have it in master
`ibc-go/modules/core/02-client/keeper/migrations.go:39`

So as far as I understand params migration for IBC will be included in the next IBC version v8 I guess

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 4 of 5 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/625)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @vertex451)

**Pull request merged**
