### PR TITLE
Set CI to use local build

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/775)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/775)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/ci.yml` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/775#-Np-j6dv7kAkdmZdIrM5:-Np-j6dv7kAkdmZdIrM6:b-zb1qbh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6129c3ed4e181f9e6f4a11b874e12a6530c45275/.github/workflows/ci.yml#L128)):*
> ```YAML
>         with:
>           key: ${{ runner.os }}-docker-v2-${{ steps.get-year-week.outputs.date }} # year-week key
>       - name: Set crust binaries cache
> ```

This should no longer be needed because no in this case previously downloaded binaries are relinked without redownloading them.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/775)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/775)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/775#-Np-j6dv7kAkdmZdIrM5:-Np4JLCSBcGCxdVmMant:b-pikvqv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6129c3ed4e181f9e6f4a11b874e12a6530c45275/.github/workflows/ci.yml#L128)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This should no longer be needed because no in this case previously downloaded binaries are relinked without redownloading them.
</blockquote></details>

But where to you save them?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/775)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/ci.yml` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/775#-Np-j6dv7kAkdmZdIrM5:-Np4Yy_n36H3B5aMO7ML:bmrgg5x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6129c3ed4e181f9e6f4a11b874e12a6530c45275/.github/workflows/ci.yml#L128)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But where to you save them?
</blockquote></details>

builder creates them and stores in `<repo>/bin` dir when tool is needed

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/775)* status: 2 of 8 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/775)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`.github/workflows/ci.yml` line 26 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/775#-NpK7y-764DwUPBNQhB2:-NpK7y-764DwUPBNQhB3:b-bro8de) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0a4caff9538c481442260d8e61ade9017e1a15ca/.github/workflows/ci.yml#L26)):*
> ```YAML
>         include:
>           - ci_step: "lint"
>             command: "coreum-builder lint"
> ```

nit: now I can see coreum-builder is not only responsible for building app but also for linting, tests, docs generation, releases etc

I'm not sure if builder is descriptive enough name (even though I suggested it before).
Do you think it is ok ? WDYT @dzmitryhil @miladz68 ?

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/775)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

**Pull request merged**
