### PR TITLE
Validate that FT and NFT features are in the defined set

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/530)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/530)* status: 0 of 22 files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/upgrade/ft.go` line 581 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb12Fh4W1cxx2G64Yb:-NYb12Fi0githIQ8HrHN:b-5n9qtt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/integration-tests/upgrade/ft.go#L581)):*
> ```Go
> 		Description:   "AAA Description",
> 		InitialAmount: sdk.NewInt(1000),
> 		Features: []assetfttypes.Feature{
> ```

What about testing the duplicated features, they should be removed as well? Same comment for the NFT.
___
*[`x/asset/ft/keeper/keeper.go` line 97 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb20T52rF-dIUCDSqH:-NYb20T52rF-dIUCDSqI:b-yrj28) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/keeper/keeper.go#L97)):*
> ```Go
> // IterateAllDefinitions iterates over all token definitions and applies the provided callback.
> // If true is returned from the callback, iteration is halted.
> func (k Keeper) IterateAllDefinitions(ctx sdk.Context, cb func(types.Definition) (bool, error)) error {
> ```

Why do you need to update the interface of the method, you can achieve what you need with the previous version as well.  (same for the NFT)
___
*[`x/asset/ft/legacy/v1/features.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb2a8f-TnkQVX-cQfe:-NYb2a8f-TnkQVX-cQff:b-esl0y9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/legacy/v1/features.go#L17)):*
> ```Go
> // MigrateFeatures migrates asset ft features state from v1 to v2.
> // It removes features which are outside the allowed scope.
> func MigrateFeatures(ctx sdk.Context, keeper FTKeeper, allowedFeatures map[int32]string) error {
> ```

As far as I remember we wanted to remove duplicated features as well, since it was possible to do it before. 
___
*[`x/asset/ft/legacy/v1/features.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb35mz538lxLlN4b-d:-NYb35n-55uxz0Tg1BvK:b-f8udtn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/legacy/v1/features.go#L17)):*
> ```Go
> // MigrateFeatures migrates asset ft features state from v1 to v2.
> // It removes features which are outside the allowed scope.
> func MigrateFeatures(ctx sdk.Context, keeper FTKeeper, allowedFeatures map[int32]string) error {
> ```

The input is `allowedFeatures map[int32]string` but that isn't true since you filter the `IBC` later. IMO better to define the list here without using it as a function param.  (same for the NFT)
___
*[`x/asset/ft/types/token.go` line 186 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb3j4m-vGHax4MaiNp:-NYb3j4m-vGHax4MaiNq:bfl4jdc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/types/token.go#L186)):*
> ```Go
> 
> // ValidateFeatures verifies that provided features belong to the defined set.
> func ValidateFeatures(features []Feature) error {
> ```

Unit tests? (same for the NFT)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/530)* status: 0 of 22 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 97 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb20T52rF-dIUCDSqH:-NYb6GSj0r6wiOjJRqxH:b-1c8d0u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/keeper/keeper.go#L97)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need to update the interface of the method, you can achieve what you need with the previous version as well.  (same for the NFT)
</blockquote></details>

I need to be able to return the error from the cb
___
*[`x/asset/ft/legacy/v1/features.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb2a8f-TnkQVX-cQfe:-NYb6MQT0OMdP3CxMaCa:bbwljvt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/legacy/v1/features.go#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

As far as I remember we wanted to remove duplicated features as well, since it was possible to do it before. 
</blockquote></details>

Good point, completely missed that!
___
*[`x/asset/ft/legacy/v1/features.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb35mz538lxLlN4b-d:-NYb6RJWDZd4kPg_6Pl8:bt2dsnq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/legacy/v1/features.go#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The input is `allowedFeatures map[int32]string` but that isn't true since you filter the `IBC` later. IMO better to define the list here without using it as a function param.  (same for the NFT)
</blockquote></details>

I need to define it as a param to be able to write unit test. After the fix, I'm able to create the token only with the valid set of features. So to test that invalid features are filtered out, I trick the list of allowed features passed to the `MigrateFeatures`.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/530)* status: 0 of 24 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/upgrade/ft.go` line 581 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb12Fh4W1cxx2G64Yb:-NYbgFZW1FbzwMu-WYyJ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/integration-tests/upgrade/ft.go#L581)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about testing the duplicated features, they should be removed as well? Same comment for the NFT.
</blockquote></details>

Done.
___
*[`x/asset/ft/legacy/v1/features.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb2a8f-TnkQVX-cQfe:-NYbgKOB506h09EunZvx:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/legacy/v1/features.go#L17)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Good point, completely missed that!
</blockquote></details>

Done
___
*[`x/asset/ft/types/token.go` line 186 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb3j4m-vGHax4MaiNp:-NYbgHBDCDNEhG_LRwjX:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/types/token.go#L186)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Unit tests? (same for the NFT)
</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/530)* status: 0 of 25 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 97 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb20T52rF-dIUCDSqH:-NYqmk793IEtPr7mvPcV:b-wzxoa) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/keeper/keeper.go#L97)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I need to be able to return the error from the cb
</blockquote></details>

Why do you need this? You can do VIA error assigning, but in general I don't see a reason to return it. 
___
*[`x/asset/ft/legacy/v1/features.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb35mz538lxLlN4b-d:-NYqnBCdATDbnkF_ib4D:bguw0fg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/legacy/v1/features.go#L17)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I need to define it as a param to be able to write unit test. After the fix, I'm able to create the token only with the valid set of features. So to test that invalid features are filtered out, I trick the list of allowed features passed to the `MigrateFeatures`.
</blockquote></details>

In that case list all allowed feature as inmut without the filtration of the IBC in the func.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 11 of 22 files at r1, 13 of 14 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/530)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/530)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 97 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb20T52rF-dIUCDSqH:-NYrdr2I-_noH40NYbKq:b-qttff0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/keeper/keeper.go#L97)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need this? You can do VIA error assigning, but in general I don't see a reason to return it. 
</blockquote></details>

doing it via assigning is a weird hack when no proper interface is available
___
*[`x/asset/ft/legacy/v1/features.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb35mz538lxLlN4b-d:-NYrdyly2siyhf0_orZW:b-h3c83c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/legacy/v1/features.go#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

In that case list all allowed feature as inmut without the filtration of the IBC in the func. 
</blockquote></details>

I've redone it

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/530)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/legacy/v1/features.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb35mz538lxLlN4b-d:-NYrfXrk70d4w0B5UTDl:b-38taa2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/legacy/v1/features.go#L17)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I've redone it
</blockquote></details>

The `if f == types.Feature_ibc {` still looks redundant. If you know that you support only the list of features, better to define that list, instead of filtering the `ibc`;

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/530)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/legacy/v1/features.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb35mz538lxLlN4b-d:-NYrgF947pCjKIIdfHzj:b-rigafn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/legacy/v1/features.go#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The `if f == types.Feature_ibc {` still looks redundant. If you know that you support only the list of features, better to define that list, instead of filtering the `ibc`;  
</blockquote></details>

@ysv @miladz68 WDYT ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/530)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/legacy/v1/features.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/530#-NYb35mz538lxLlN4b-d:-NYrjCpuEfzODKNaxzRU:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dba21db8b7fd8d785bd1fcb26640e394d108f24a/x/asset/ft/legacy/v1/features.go#L17)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv @miladz68 WDYT ?
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/530)* status: 23 of 25 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 10 of 22 files at r1, 12 of 14 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/530)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/530)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/530)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
