### PR TITLE
Added cli to fetch ft & nft params

### PR DESCRIPTION
**Pull request by vertex451**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/500)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/500)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/500)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/client/cli/query.go` line 288 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/500#-NVo34WVCr2DrsFd2eto:-NVo34WVCr2DrsFd2etp:bmhx91n) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1f80f07ed93efa70da7936e3fba41ce803f853da/x/asset/ft/client/cli/query.go#L288)):*
> ```Go
> 	cmd := &cobra.Command{
> 		Use:   "params",
> 		Short: "Query the current assetft parameters",
> ```

assetft -> use types.ModuleName instead (same for all text).
___
*[`x/asset/ft/client/cli/query_test.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/500#-NVo3Y5y3qQsKRoKcxWx:-NVo3Y5y3qQsKRoKcxWy:bxu499l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1f80f07ed93efa70da7936e3fba41ce803f853da/x/asset/ft/client/cli/query_test.go#L99)):*
> ```Go
> 	requireT.NoError(ctx.Codec.UnmarshalJSON(buf.Bytes(), &resp))
> 
> 	expectedIssueFee := sdk.Coin{Denom: constant.DenomDev, Amount: sdk.NewInt(10_000_000)}
> ```

Why it's constant? You should use iether the default values from types, or don't check it at all (same for the NFT test). 
___
*[`x/asset/nft/client/cli/query.go` line 254 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/500#-NVo3CIx9NdT3tDi7g9m:-NVo3CIx9NdT3tDi7g9n:b-tm4h4d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1f80f07ed93efa70da7936e3fba41ce803f853da/x/asset/nft/client/cli/query.go#L254)):*
> ```Go
> 	cmd := &cobra.Command{
> 		Use:   "params",
> 		Short: "Query the current assetnft parameters",
> ```

assetnft -> use types.ModuleName instead (same for all text).

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/500)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/500)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase and @ysv)

___
*[`x/asset/ft/client/cli/query.go` line 288 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/500#-NVo34WVCr2DrsFd2eto:-NW14qQC6o-gMWA8T4tT:b-ojzbok) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1f80f07ed93efa70da7936e3fba41ce803f853da/x/asset/ft/client/cli/query.go#L288)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Don't see the changes.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/500)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/500)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
