### PR TITLE
Test pinning and unpinning smart contracts

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/243)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/243)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/simple_state.go` line 127 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/243#-NFDcINUA8YV2UEqe-sx:-NFDcINVEtZn10LwNdOv:b-dho1s8) ([raw file](https://github.com/coreumfoundation/coreum/blob/53fa7e0e1912917f274bb4edf2aa4e23bc485980/integration-tests/wasm/simple_state.go#L127)):*
> ```Go
> 	requireT.False(IsPinned(ctx, clientCtx, codeID))
> 
> 	incrementAndVerify(ctx, clientCtx, txf, contractAddr, requireT, 1340)
> ```

gas usage should be decreased after the pinning of a smart contract, is it checked anywhere ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/243)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/wasm/simple_state.go` line 127 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/243#-NFDcINUA8YV2UEqe-sx:-NFIT3nuB69kZqSxfqA1:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/53fa7e0e1912917f274bb4edf2aa4e23bc485980/integration-tests/wasm/simple_state.go#L127)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

gas usage should be decreased after the pinning of a smart contract, is it checked anywhere ?
</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/243)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/simple_state.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/243#-NFE5w1b28hkBWs97f3Y:-NFE5w1b28hkBWs97f3Z:b-oaehbp) ([raw file](https://github.com/coreumfoundation/coreum/blob/53fa7e0e1912917f274bb4edf2aa4e23bc485980/integration-tests/wasm/simple_state.go#L35)):*
> ```Go
> // TestSimpleStateWasmContract runs a contract deployment flow and tries to modify the state after deployment.
> // This is a E2E check for the WASM integration, to ensure it works for a simple state contract (Counter).
> func TestSimpleStateWasmContract(ctx context.Context, t testing.T, chain testing.Chain) {
> ```

It it's gov test the name of the test should correspond.
___
*[`integration-tests/wasm/simple_state.go` line 84 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/243#-NFE60psCq6spqI6dbHS:-NFE60psCq6spqI6dbHT:b82fbo3) ([raw file](https://github.com/coreumfoundation/coreum/blob/53fa7e0e1912917f274bb4edf2aa4e23bc485980/integration-tests/wasm/simple_state.go#L84)):*
> ```Go
> 
> 	// execute contract to increment the count
> 	incrementAndVerify(ctx, clientCtx, txf, contractAddr, requireT, 1338)
> ```

Better to have a name that corresponds the logic instead of the comment
___
*[`integration-tests/wasm/simple_state.go` line 105 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/243#-NFE6MqS9wl5yZuxgbiC:-NFE6MqS9wl5yZuxgbiD:bdcczzk) ([raw file](https://github.com/coreumfoundation/coreum/blob/53fa7e0e1912917f274bb4edf2aa4e23bc485980/integration-tests/wasm/simple_state.go#L105)):*
> ```Go
> 	requireT.NoError(chain.Governance.WaitForVotingToPass(ctx, uint64(proposalID)))
> 
> 	requireT.True(IsPinned(ctx, clientCtx, codeID))
> ```

As @miladz68 mentioned the gas for the contract execution should be less than unpinned so we should check it.
___
*[`integration-tests/wasm/simple_state.go` line 127 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/243#-NFDcINUA8YV2UEqe-sx:-NFE6CPR3wZ_zD-83X2c:b7ktn3j) ([raw file](https://github.com/coreumfoundation/coreum/blob/53fa7e0e1912917f274bb4edf2aa4e23bc485980/integration-tests/wasm/simple_state.go#L127)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

gas usage should be decreased after the pinning of a smart contract, is it checked anywhere ?
</blockquote></details>

agree it should
___
*[`integration-tests/wasm/simple_state.go` line 145 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/243#-NFE6iDq7-UiBoqPM2Tt:-NFE6iDq7-UiBoqPM2Tu:b-p2ub79) ([raw file](https://github.com/coreumfoundation/coreum/blob/53fa7e0e1912917f274bb4edf2aa4e23bc485980/integration-tests/wasm/simple_state.go#L145)):*
> ```Go
> ) {
> 	// execute contract to increment the count
> 	incrementPayload, err := methodToEmptyBodyPayload(increment)
> ```

It's optional, but the reading of the code

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/243)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/wasm/simple_state.go` line 84 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/243#-NFE60psCq6spqI6dbHS:-NFJN-MfB2ijaUFsgpRH:b3kre) ([raw file](https://github.com/coreumfoundation/coreum/blob/53fa7e0e1912917f274bb4edf2aa4e23bc485980/integration-tests/wasm/simple_state.go#L84)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Better to have a name that corresponds the logic instead of the comment
</blockquote></details>

?
___
*[`integration-tests/wasm/simple_state.go` line 105 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/243#-NFE6MqS9wl5yZuxgbiC:-NFJN16P7NPV2POfFeOr:bek5wz4) ([raw file](https://github.com/coreumfoundation/coreum/blob/53fa7e0e1912917f274bb4edf2aa4e23bc485980/integration-tests/wasm/simple_state.go#L105)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

As @miladz68 mentioned the gas for the contract execution should be less than unpinned so we should check it.
</blockquote></details>

we check it
___
*[`integration-tests/wasm/simple_state.go` line 127 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/243#-NFDcINUA8YV2UEqe-sx:-NFJMpXN2RF9mkJEJWhy:b-r0s9c1) ([raw file](https://github.com/coreumfoundation/coreum/blob/53fa7e0e1912917f274bb4edf2aa4e23bc485980/integration-tests/wasm/simple_state.go#L127)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

agree it should
</blockquote></details>

It does now
___
*[`integration-tests/wasm/simple_state.go` line 145 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/243#-NFE6iDq7-UiBoqPM2Tt:-NFJMw1o2O02eahJQ1LZ:b3kre) ([raw file](https://github.com/coreumfoundation/coreum/blob/53fa7e0e1912917f274bb4edf2aa4e23bc485980/integration-tests/wasm/simple_state.go#L145)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's optional, but the reading of the code
</blockquote></details>

?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/243)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/wasm/simple_state.go` line 35 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/243#-NFE5w1b28hkBWs97f3Y:-NFMzHOW9JTn7PxSwzti:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/53fa7e0e1912917f274bb4edf2aa4e23bc485980/integration-tests/wasm/simple_state.go#L35)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It it's gov test the name of the test should correspond.
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/243#-:-NFN5RMc2zCBcGZu1tcd:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/243)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/243)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`integration-tests/wasm/simple_state.go` line 105 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/243#-NFE6MqS9wl5yZuxgbiC:-NFN8_jV1AjM-vSMPUjq:b-x6zpb4) ([raw file](https://github.com/coreumfoundation/coreum/blob/53fa7e0e1912917f274bb4edf2aa4e23bc485980/integration-tests/wasm/simple_state.go#L105)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

we check it
</blockquote></details>

That was the PR version mismatch. Those comments were related to prev version. So don't pay attention on them, they are outdated.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/243)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`integration-tests/wasm/simple_state.go` line 145 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/243#-NFE6iDq7-UiBoqPM2Tt:-NFN8kei9_eN6kf7nkGR:b-x6zpb4) ([raw file](https://github.com/coreumfoundation/coreum/blob/53fa7e0e1912917f274bb4edf2aa4e23bc485980/integration-tests/wasm/simple_state.go#L145)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

?
</blockquote></details>

That was the PR version mismatch. Those comments were related to prev version. So don't pay attention on them, they are outdated.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/243)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/243)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
