### PR TITLE
Add time-in-force & fix some cli params

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/993)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/993)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/993)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh and @ysv)

___
*[`x/dex/client/cli/tx.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/993#-O8p8JOeCkXfCdSFMPNk:-O8p8JOfBEHR-7VBQO1V:becq1u6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2282faa97614fad4781e87ed3cce9508bb8f1b6f/x/dex/client/cli/tx.go#L59)):*
> ```Go
> func CmdPlaceOrder() *cobra.Command {
> 	var availableTimeInForces []string
> 	for i, n := range types.TimeInForce_name {
> ```

Use `lo.Values` instead + `sort.Strings` to prevent random out. 
___
*[`x/dex/client/cli/tx.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/993#-O8p8udWDA6KElluf07T:-O8p8udWDA6KElluf07U:b-sbvhf9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2282faa97614fad4781e87ed3cce9508bb8f1b6f/x/dex/client/cli/tx.go#L99)):*
> ```Go
> 			case OrderTypeLimit:
> 				orderType = types.ORDER_TYPE_LIMIT
> 				if timeInForce != types.TIME_IN_FORCE_GTC {
> ```

Didn't get this logic. 
For the `Market` we support `TIME_IN_FORCE_UNSPECIFIED` only other types for the `Limit`. 
Also you don't need to return the following error, just pass it to the object.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/993)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`x/dex/client/cli/tx.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/993#-O8p8JOeCkXfCdSFMPNk:-O8pIgL514XIh4OvG1oB:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2282faa97614fad4781e87ed3cce9508bb8f1b6f/x/dex/client/cli/tx.go#L59)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Use `lo.Values` instead + `sort.Strings` to prevent random out.
</blockquote></details>

Done.
___
*[`x/dex/client/cli/tx.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/993#-O8p8udWDA6KElluf07T:-O8pJ63eCtwXwtu0a7pD:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2282faa97614fad4781e87ed3cce9508bb8f1b6f/x/dex/client/cli/tx.go#L99)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Didn't get this logic. 
For the `Market` we support `TIME_IN_FORCE_UNSPECIFIED` only other types for the `Limit`. 
Also you don't need to return the following error, just pass it to the object.
</blockquote></details>

Done.

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/993)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/993)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/993)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/993)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/993)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
