### PR TITLE
Add IBC test to upgrade integration-tests

### PR DESCRIPTION
**Pull request by ysv**
# Description

integration-tests/upgrade test added:

IBC transfer: Coreum -> Gaia & Gaia -> Coreum before upgrade
IBC transfer back: Gaia -> Coreum & Coreum -> Gaia after upgrade

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/648)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/648)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/648)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451, @wojtek-coreum, and @ysv)

___
*[`integration-tests/upgrade/ibc_test.go` line 61 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/648#-Ne8Z7Ko7L8vjT4vvrnx:-Ne8Z7Ko7L8vjT4vvrny:billieg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4dff257aacd6bd2a888617e38faf7bfbd943dfd5/integration-tests/upgrade/ibc_test.go#L61)):*
> ```Go
> 	txRes, err := coreumChain.ExecuteIBCTransfer(ctx, t, coreumSender, sendToGaiaCoin, gaiaChain.ChainContext, gaiaRecipient)
> 	requireT.NoError(err)
> 	requireT.EqualValues(txRes.GasUsed, coreumChain.GasLimitByMsgs(&ibctransfertypes.MsgTransfer{}))
> ```

IMO we don't need to check it in the upgrade test.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/648)* status: 1 of 6 files reviewed, all discussions resolved (waiting on @miladz68, @vertex451, and @wojtek-coreum)

___
*[`integration-tests/upgrade/ibc_test.go` line 61 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/648#-Ne8Z7Ko7L8vjT4vvrnx:-NeDAr84AlahXQGbMtB6:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4dff257aacd6bd2a888617e38faf7bfbd943dfd5/integration-tests/upgrade/ibc_test.go#L61)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO we don't need to check it in the upgrade test.
</blockquote></details>

Done

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/648)* status: 1 of 6 files reviewed, all discussions resolved (waiting on @miladz68, @vertex451, and @wojtek-coreum)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/648)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/648#-NeDbcHi3_TQW3fHWBBa:-NeE3FxECbRC95zw3uas:b-1t5r53) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why do we need this? Isn't it enough to run `coreum-ibc` tests after the upgrade?
</blockquote></details>

discussed on call
It makes sense because we IBC transfer before upgrade but return back after 

___

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/648)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451 and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/648)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
