### PR TITLE
Use testnet prefixes in the CLI examples.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/383)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/383)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`pkg/config/constant/const.go` line 36 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/383#-NNlAv1bDRR9I5LFRCk6:-NNlAv1bDRR9I5LFRCk7:b-jcodli) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a5762c0a5cdcb30b4d30ca2ee8ee23ecab75fbc2/pkg/config/constant/const.go#L36)):*
> ```Go
> 
> const (
> 	// AddressSampleTest is valida testnet address used for samples.
> ```

valida
___
*[`x/asset/nft/client/cli/tx.go` line 289 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/383#-NNlB30mEynMDzQ0qJrz:-NNlB30mEynMDzQ0qJs-:b-rmo7d5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a5762c0a5cdcb30b4d30ca2ee8ee23ecab75fbc2/x/asset/nft/client/cli/tx.go#L289)):*
> ```Go
> $ %s tx %s whitelist abc-%s id1 %s --from [sender]
> `,
> 				version.AppName, types.ModuleName, constant.AddressSampleTest, constant.AddressSampleTest,
> ```

instead of providing parameter twice, you could use `%[3]s`

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/383)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/383)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/383)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/383)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/383)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
