### PR TITLE
Add non-negative-balances and bank-metadata-matches FT module invariants.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/326)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/326)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/freeze.go` line 136 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NKvxsbiESw20wNxxr6P:-NKvxsbiESw20wNxxr6Q:beu3nc0) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/freeze.go#L136)):*
> ```Go
> 		address, err := types.AddressFromBalancesStore(iterator.Key())
> 		if err != nil {
> 			k.Logger(ctx).With("key", iterator.Key(), "err", err).Error("failed to get address from frozen balances store")
> ```

you don't need to log it, panic describes everything
___
*[`x/asset/ft/keeper/freeze.go` line 143 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NKvy2xA0jLqlVnbBWGq:-NKvy2xA0jLqlVnbBWGr:b-9w79hj) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/freeze.go#L143)):*
> ```Go
> 		k.cdc.MustUnmarshal(iterator.Value(), &balance)
> 
> 		if cb(address, balance) {
> ```

usually in such cases (AFAIK) `true` is used to continue, and `false` rto break, which is more intuitive I think

**Review by miladz68 — DISMISSED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/326)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/326)* status: all files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1hFme9YAUsHvlYvaU:-NL1hFme9YAUsHvlYvaV:b-kwh63x) (no related file):*
does it make sense to run all invariants check after integration tests ?

___
___
*[`x/asset/ft/keeper/freeze.go` line 128 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1hiqg25SAKCG1dJDX:-NL1hiqg25SAKCG1dJDY:bdgg12z) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/freeze.go#L128)):*
> ```Go
> // IterateAllFrozenBalances iterates over all frozen balances of all accounts and applies the provided callback.
> // If true is returned from the callback, iteration is halted.
> func (k Keeper) IterateAllFrozenBalances(ctx sdk.Context, cb func(sdk.AccAddress, sdk.Coin) bool) {
> ```

I would prefer to implement this on top of `balanceStore` & reuse for both whitelisting & freezing to avoid code duplication
___
*[`x/asset/ft/keeper/freeze.go` line 136 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NKvxsbiESw20wNxxr6P:-NL1i-ZN2gbwGsYR-eKb:b-wyr63y) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/freeze.go#L136)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you don't need to log it, panic describes everything
</blockquote></details>

I agree with Wojtek
___
*[`x/asset/ft/keeper/freeze.go` line 143 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NKvy2xA0jLqlVnbBWGq:-NL1iDbi9jbMJFrQfKTQ:buxykeh) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/freeze.go#L143)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

usually in such cases (AFAIK) `true` is used to continue, and `false` rto break, which is more intuitive I think
</blockquote></details>

I didn't get this comment
Any clue @dzmitryhil ?
___
*[`x/asset/ft/keeper/invariants.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1j2aO9j6RDaQlCEjG:-NL1j2aO9j6RDaQlCEjH:b-unfm47) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants.go#L13)):*
> ```Go
> // RegisterInvariants registers the bank module invariants
> func RegisterInvariants(ir sdk.InvariantRegistry, k Keeper) {
> 	ir.RegisterRoute(types.ModuleName, "non-negative-balances", NonNegativeBalancesInvariant(k))
> ```

minor:
I would move `non-negative-balances` & `"bank-metadata-matches"` to constants since each of them is used twice
___
*[`x/asset/ft/keeper/invariants.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1jkkODNPG8GAI_NQ6:-NL1jkkODNPG8GAI_NQ7:b-okc7yr) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants.go#L14)):*
> ```Go
> func RegisterInvariants(ir sdk.InvariantRegistry, k Keeper) {
> 	ir.RegisterRoute(types.ModuleName, "non-negative-balances", NonNegativeBalancesInvariant(k))
> 	ir.RegisterRoute(types.ModuleName, "bank-metadata-matches", BankMetadataMatchesInvariant(k))
> ```

I suggest to rename to `bank-metadata-exists` or `-registered`
___
*[`x/asset/ft/keeper/invariants.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1mSneCdGLohnGHz59:-NL1mSneCdGLohnGHz5A:b56exnk) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants.go#L17)):*
> ```Go
> }
> 
> // NonNegativeBalancesInvariant checks that all accounts in the application have non-negative fungible token specific balances.
> ```

`fungible token specific balances.` what is the meaning of specific balance ?
Maybe we should name it smth like: `feature balances`
___
*[`x/asset/ft/keeper/invariants.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1jSDZ9Bwn5oSg_hez:-NL1jSDZ9Bwn5oSg_hf-:b-6zad40) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants.go#L37)):*
> ```Go
> 			if balance.IsNegative() {
> 				count++
> 				msg += fmt.Sprintf("\t%s has a whitelisted frozen balance of %s\n", addr, balance)
> ```

`has a negative whitelisted balance of`
___
*[`x/asset/ft/keeper/invariants.go` line 70 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1iRTt8AZuO12B2pXz:-NL1iRTt8AZuO12B2pY-:b-xnpq0i) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants.go#L70)):*
> ```Go
> 		return sdk.FormatInvariant(
> 			types.ModuleName, "bank-metadata-matches",
> 			fmt.Sprintf("amount of broken metadata found %d\n%s", count, msg),
> ```

more proper spelling will be smth like`number of missing metadata entries %d`
___
*[`x/asset/ft/keeper/invariants_test.go` line 53 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1lbfs9Q63xY5uE_9D:-NL1lbfs9Q63xY5uE_9E:b-5cnbym) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants_test.go#L53)):*
> ```Go
> 	ftKeeper.SetFrozenBalances(ctx, recipient, sdk.Coins{sdk.Coin{
> 		Denom:  denom,
> 		Amount: sdk.NewInt(-1),
> ```

I'm scared that it is so easy to set amount to a negative value
on which stage do we validate Amount to be positive ? only in validateBasic ?
___
*[`x/asset/ft/keeper/whitelist.go` line 65 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1m5Pn5EUQkkD0g9Bc:-NL1m5Pn5EUQkkD0g9Bd:bb9hfur) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/whitelist.go#L65)):*
> ```Go
> // IterateAllWhitelistedBalances iterates over all whitelisted balances of all accounts and applies the provided callback.
> // If true is returned from the callback, iteration is halted.
> func (k Keeper) IterateAllWhitelistedBalances(ctx sdk.Context, cb func(sdk.AccAddress, sdk.Coin) bool) {
> ```

to be moved to `balance_store.go`
___
*[`x/asset/ft/keeper/whitelist.go` line 73 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1m9X44qIsRnAowJL0:-NL1m9X44qIsRnAowJL1:b-19ih3u) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/whitelist.go#L73)):*
> ```Go
> 		address, err := types.AddressFromBalancesStore(iterator.Key())
> 		if err != nil {
> 			k.Logger(ctx).With("key", iterator.Key(), "err", err).Error("failed to get address from whitelisted balances store")
> ```

same as previously
panic returns everything no logging needed IMO

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/326)* status: all files reviewed, 12 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1hFme9YAUsHvlYvaU:-NL4hrk431QFEMwsyjN6:br2sy03) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

does it make sense to run all invariants check after integration tests ?
</blockquote></details>

We can do it once the crisis fix is in place.

___
___
*[`x/asset/ft/keeper/freeze.go` line 128 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1hiqg25SAKCG1dJDX:-NL4mj9lEAaThY4TBUhV:bcvjgzp) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/freeze.go#L128)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would prefer to implement this on top of `balanceStore` & reuse for both whitelisting & freezing to avoid code duplication
</blockquote></details>

Good idea. Done.
___
*[`x/asset/ft/keeper/freeze.go` line 136 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NKvxsbiESw20wNxxr6P:-NL4ml-85wYXbBB3SHmV:b-4g7ta0) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/freeze.go#L136)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree with Wojtek
</blockquote></details>

I've refactored that part, removed the logger and stared returning error.
___
*[`x/asset/ft/keeper/freeze.go` line 143 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NKvy2xA0jLqlVnbBWGq:-NL1Ettf1Quf1y0RGD5y:bwyz62s) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/freeze.go#L143)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I didn't get this comment
Any clue @dzmitryhil ?
</blockquote></details>

I understood. This comment is about we when we should stop iteration.
That's the cosmos SDK way. So that's why it's done so.
___
*[`x/asset/ft/keeper/invariants.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1j2aO9j6RDaQlCEjG:-NL4nATJBzuocls_4TR9:b-1eh3wi) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants.go#L13)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
I would move `non-negative-balances` & `"bank-metadata-matches"` to constants since each of them is used twice
</blockquote></details>

Sure, done.
___
*[`x/asset/ft/keeper/invariants.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1jkkODNPG8GAI_NQ6:-NL4nBmfDVYUXVciSnto:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants.go#L14)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I suggest to rename to `bank-metadata-exists` or `-registered`
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/invariants.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1mSneCdGLohnGHz59:-NL4nJSM-kvDbuGCj58r:b-8ezbo2) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants.go#L17)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`fungible token specific balances.` what is the meaning of specific balance ?
Maybe we should name it smth like: `feature balances`
</blockquote></details>

Agree, updated.
___
*[`x/asset/ft/keeper/invariants.go` line 37 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1jSDZ9Bwn5oSg_hez:-NL4nXi6CEgx2JLeM1u3:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants.go#L37)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`has a negative whitelisted balance of`
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/invariants.go` line 70 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1iRTt8AZuO12B2pXz:-NL4naAPCQHRnVuLN3SA:b-a36jdb) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants.go#L70)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

more proper spelling will be smth like`number of missing metadata entries %d`
</blockquote></details>

Agree, done.
___
*[`x/asset/ft/keeper/invariants_test.go` line 53 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1lbfs9Q63xY5uE_9D:-NL4nlCMBJmH7fbBV-Ki:bukyg3s) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants_test.go#L53)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm scared that it is so easy to set amount to a negative value
on which stage do we validate Amount to be positive ? only in validateBasic ?
</blockquote></details>

That's ok. Since it's DAO layer. 
___
*[`x/asset/ft/keeper/whitelist.go` line 65 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1m5Pn5EUQkkD0g9Bc:-NL4nqch8F3GYAjE0WLC:btubb1f) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/whitelist.go#L65)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

to be moved to `balance_store.go`
</blockquote></details>

That func remains here, but call the `balance_store` now.
___
*[`x/asset/ft/keeper/whitelist.go` line 73 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1m9X44qIsRnAowJL0:-NL4nvxs9z7hrHVrbxjj:b-dddl6p) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/whitelist.go#L73)):*
> That func remains here, but call the `balance_store` now.
That func remains here, but call the `balance_store` now.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/326)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1hFme9YAUsHvlYvaU:-NLKy7h03RCKtSTFm3zP:b-yr1uo2) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We can do it once the crisis fix is in place.
</blockquote></details>

added as idea to clickup

___
___
*[`x/asset/ft/keeper/freeze.go` line 128 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NLKyOQG4wTxUS-kH2tE:-NLKyOQG4wTxUS-kH2tF:b-fr2w0p) ([raw file](https://github.com/coreumfoundation/coreum/blob/435d902c72c53ebdaecf44a170a85e0c0a5b3536/x/asset/ft/keeper/freeze.go#L128)):*
> ```Go
> // IterateAllFrozenBalances iterates over all frozen balances of all accounts and applies the provided callback.
> // If true is returned from the callback, iteration is stopped.
> func (k Keeper) IterateAllFrozenBalances(ctx sdk.Context, cb func(sdk.AccAddress, sdk.Coin) bool) error {
> ```

minor:
do we really need this oneliner func now ?
we just call it once so it makes sense to call `k.frozenAccountsBalanceStore(ctx).IterateAllBalances(cb)` directly IMO
___
*[`x/asset/ft/keeper/invariants.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1jkkODNPG8GAI_NQ6:-NLKyq7ZEjVdcPlqheIx:b-6tu694) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants.go#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still see `"bank-metadata-matches"`
___
*[`x/asset/ft/keeper/invariants.go` line 42 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NLKzsSr7hz9zSB7bko3:-NLKzsSr7hz9zSB7bko4:b-bh1lfx) ([raw file](https://github.com/coreumfoundation/coreum/blob/435d902c72c53ebdaecf44a170a85e0c0a5b3536/x/asset/ft/keeper/invariants.go#L42)):*
> ```Go
> 		if err != nil {
> 			count++
> 			msg += fmt.Sprintf("catched error on IterateAllFrozenBalances %s\n", err)
> ```

in this err msg I don't like 2 things:
1. you use catch which refers to try-catch error handling mechanism which is not true for golang
2. I don't like to include func name in error msg

lets change it to smth like:
`fmt.Sprintf("%s invariant check for freezing failed: %s\n", NonNegativeBalancesInvariantName, err`
___
*[`x/asset/ft/keeper/whitelist.go` line 65 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NLL3UStBnRZplLTQGC2:-NLL3USuE5zsn35Si0s4:b169p23) ([raw file](https://github.com/coreumfoundation/coreum/blob/435d902c72c53ebdaecf44a170a85e0c0a5b3536/x/asset/ft/keeper/whitelist.go#L65)):*
> ```Go
> // IterateAllWhitelistedBalances iterates over all whitelisted balances of all accounts and applies the provided callback.
> // If true is returned from the callback, iteration is halted.
> func (k Keeper) IterateAllWhitelistedBalances(ctx sdk.Context, cb func(sdk.AccAddress, sdk.Coin) bool) error {
> ```

minor:
do we really need this oneliner func ?

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/326)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`x/asset/ft/keeper/invariants_test.go` line 53 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1lbfs9Q63xY5uE_9D:-NLL3eV14dOdMuY5uNIa:b4isr86) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants_test.go#L53)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

That's ok. Since it's DAO layer. 
</blockquote></details>

Moved discussion into slack

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/326)* status: all files reviewed, 4 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/freeze.go` line 128 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NLKyOQG4wTxUS-kH2tE:-NLL7yf33hm8rVDLIpxi:bhjtp5p) ([raw file](https://github.com/coreumfoundation/coreum/blob/435d902c72c53ebdaecf44a170a85e0c0a5b3536/x/asset/ft/keeper/freeze.go#L128)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
do we really need this oneliner func now ?
we just call it once so it makes sense to call `k.frozenAccountsBalanceStore(ctx).IterateAllBalances(cb)` directly IMO
</blockquote></details>

IMO we shouldn't touch the keys used the keeper, the invariant is outside so the keeper should provide the methods. That's why I would keep those methods.
___
*[`x/asset/ft/keeper/invariants.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1jkkODNPG8GAI_NQ6:-NLL8PL226RIHtVqXW-F:b-bw8e14) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants.go#L14)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

still see `"bank-metadata-matches"`
</blockquote></details>

Updated.
___
*[`x/asset/ft/keeper/invariants.go` line 42 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NLKzsSr7hz9zSB7bko3:-NLL91UU0vOfHL9pG7QR:b-njutpf) ([raw file](https://github.com/coreumfoundation/coreum/blob/435d902c72c53ebdaecf44a170a85e0c0a5b3536/x/asset/ft/keeper/invariants.go#L42)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

in this err msg I don't like 2 things:
1. you use catch which refers to try-catch error handling mechanism which is not true for golang
2. I don't like to include func name in error msg

lets change it to smth like:
`fmt.Sprintf("%s invariant check for freezing failed: %s\n", NonNegativeBalancesInvariantName, err`
</blockquote></details>

1. That's what we want in the invariant - we want to get all errors not just first error.
2. The error text is updated.
___
*[`x/asset/ft/keeper/whitelist.go` line 65 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NLL3UStBnRZplLTQGC2:-NLL9Gm2BL81o2oXZZIU:b4ivwko) ([raw file](https://github.com/coreumfoundation/coreum/blob/435d902c72c53ebdaecf44a170a85e0c0a5b3536/x/asset/ft/keeper/whitelist.go#L65)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
do we really need this oneliner func ?
</blockquote></details>

Replied in the same thread.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/326)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`x/asset/ft/keeper/invariants.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1jkkODNPG8GAI_NQ6:-NLLYZcj68xP9iPSvPa0:b-xwyaw1) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants.go#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated.
</blockquote></details>

what about constant name `BankMetadataMatchesInvariantName` ?
___
*[`x/asset/ft/keeper/invariants.go` line 42 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NLKzsSr7hz9zSB7bko3:-NLL_qFrDzyenmcm7MzS:b-swcny0) ([raw file](https://github.com/coreumfoundation/coreum/blob/435d902c72c53ebdaecf44a170a85e0c0a5b3536/x/asset/ft/keeper/invariants.go#L42)):*
> That's what we want in the invariant - we want to get all errors not just first error.

I agree but just don't want to use catch word here

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/326)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/invariants.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NL1jkkODNPG8GAI_NQ6:-NLLaStk2hPpxzefhNla:b5pulce) ([raw file](https://github.com/coreumfoundation/coreum/blob/9a3becd580ef51211af23520b851a51890ffff05/x/asset/ft/keeper/invariants.go#L14)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what about constant name `BankMetadataMatchesInvariantName` ?
</blockquote></details>

Right :-) .Updated.
___
*[`x/asset/ft/keeper/invariants.go` line 42 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/326#-NLKzsSr7hz9zSB7bko3:-NLLagG0B5keHd4R5Fbm:bso5xlg) ([raw file](https://github.com/coreumfoundation/coreum/blob/435d902c72c53ebdaecf44a170a85e0c0a5b3536/x/asset/ft/keeper/invariants.go#L42)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> That's what we want in the invariant - we want to get all errors not just first error.

I agree but just don't want to use catch word here
</blockquote></details>

Right, it's removed.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/326)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 1 of 1 files at r4, 4 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/326)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
