### PR TITLE
Add convenient function `testing.MustNewCoin` used in integration tests

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/152)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/152)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/helpers.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/152#-NAnQmbu69gQsKwHHwTD:-NAnQmbu69gQsKwHHwTE:bgv59y9) ([raw file](https://github.com/coreumfoundation/coreum/blob/43153b60043dd720cd1830a9353340df40d3ef4a/integration-tests/testing/helpers.go#L25)):*
> ```Go
> func MustNewCoin(t T, amount sdk.Int, denom string) types.Coin {
> 	c, err := types.NewCoin(amount.BigInt(), denom)
> 	require.NoError(t, err)
> ```

let's better panic here, not to pass the T here

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/152)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/helpers.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/152#-NAnQsSv8PvMb4d4970t:-NAnQsSv8PvMb4d4970u:b-suu35) ([raw file](https://github.com/coreumfoundation/coreum/blob/43153b60043dd720cd1830a9353340df40d3ef4a/integration-tests/testing/helpers.go#L32)):*
> ```Go
> func MustNewIntFromString(t T, v string) sdk.Int {
> 	i, ok := sdk.NewIntFromString(v)
> 	require.True(t, ok, "creating sdk.Int from string failed")
> ```

Same here, panic is default for the Must as for me.

**Review by miladz68 — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/152)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/helpers.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/152#-NAnQsSv8PvMb4d4970t:-NAnRBnr0nQ8gj8HGdu0:bkr0zs1) ([raw file](https://github.com/coreumfoundation/coreum/blob/43153b60043dd720cd1830a9353340df40d3ef4a/integration-tests/testing/helpers.go#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Same here, panic is default for the Must as for me.
</blockquote></details>

I would say rename to `RequireNew...` and not panic.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/152)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/helpers.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/152#-NAnQsSv8PvMb4d4970t:-NAnRdpy2rjcAktfV-Fp:b-o1gpa9) ([raw file](https://github.com/coreumfoundation/coreum/blob/43153b60043dd720cd1830a9353340df40d3ef4a/integration-tests/testing/helpers.go#L32)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I would say rename to `RequireNew...` and not panic. 
</blockquote></details>

`Require` word does not really leads to the logic of `require` package. It might mean that this function makes some operation which requires a coin. `Must` is more goish way of saying that code breaks on error

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, and @ysv)

**Pull request merged**
