### PR TITLE
Add more integration tests for staking module min delegation

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/281)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/281)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/staking/staking.go` line 190 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/281#-NIapLWI4hW_fsmbJEAB:-NIapLWJ5fWGQay6Yfpm:b46c48m) ([raw file](https://github.com/coreumfoundation/coreum/blob/89a34b2748dc7d15c002c8305843867e01ce61bb/integration-tests/staking/staking.go#L190)):*
> ```Go
> // TestValidatorUpdateWithLowMinSelfDelegation checks validator can update its parameters even if the new min self
> // delegation is higher than current validator self delegation.
> func TestValidatorUpdateWithLowMinSelfDelegation(ctx context.Context, t testing.T, chain testing.Chain) {
> ```

what about updating self delegation to higher number?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/281)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/staking/staking.go` line 190 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/281#-NIapLWI4hW_fsmbJEAB:-NIauMO9Ak7QY9QL4pJh:b-30pzju) ([raw file](https://github.com/coreumfoundation/coreum/blob/89a34b2748dc7d15c002c8305843867e01ce61bb/integration-tests/staking/staking.go#L190)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what about updating self delegation to higher number?
</blockquote></details>

Actually we do it, in the defer of the function. We first decrease it and then increase back.

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/281)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/281)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
