### PR TITLE
Move duplicated `getIssueFee` & `getMintFee` helpers to `CoreumChain` in integr-tests

### PR DESCRIPTION
**Pull request by ysv**
## Description

This PR replaces duplicated `getIssueFee` helper func in multiple locations with a single `QueryAssetFTParams` method inside `CoreumChain` struct.
Same refactoring applied to asset/nft params to avoid same issue in the future.
The idea is to avoid code duplication & have a single universal method to query all params for asset/ft & asset/nft modules.

This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/581)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/581)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`integration-tests/coreum.go` line 186 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/581#-NaB3dfG4eE_1c1DYDKP:-NaB3dfG4eE_1c1DYDKQ:b5ii8tg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cf9e821dc93d4243b517214d33bd45da039dc8e1/integration-tests/coreum.go#L186)):*
> ```Go
> // QueryAssetFTParams queries for asset/ft module params and returns them.
> func (c CoreumChain) QueryAssetFTParams(ctx context.Context, t *testing.T) assetfttypes.Params {
> 	queryClient := assetfttypes.NewQueryClient(c.ClientContext)
> ```

You need to add t.Testing() for that func and text func, if you pass the t *testing.T as arg. This is good practice since helps the testing framework separate test and helper functions and in case of logs or errors, show proper line in the test.

**Review by miladz68 — DISMISSED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/581)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451, @wojtek-coreum, and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/581)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

___
*[`integration-tests/coreum.go` line 186 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/581#-NaB3dfG4eE_1c1DYDKP:-NaBJpla4bRkP-FZhH4s:bpa656u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cf9e821dc93d4243b517214d33bd45da039dc8e1/integration-tests/coreum.go#L186)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You need to add t.Testing() for that func and text func, if you pass the t *testing.T as arg. This is good practice since helps the testing framework separate test and helper functions and in case of logs or errors, show proper line in the test.
</blockquote></details>

I guess you meant to add `t.Helper()`

Done

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/581)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`integration-tests/coreum.go` line 186 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/581#-NaB3dfG4eE_1c1DYDKP:-NaBq_ZxCB2w1ap18_3X:bbw4lxl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cf9e821dc93d4243b517214d33bd45da039dc8e1/integration-tests/coreum.go#L186)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I guess you meant to add `t.Helper()`

Done
</blockquote></details>

Right.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/581)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @miladz68, @vertex451, and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/581)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @wojtek-coreum)

**Pull request merged**
