### PR TITLE
Fix release workflow regexp

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/240)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/240)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/240)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/release.yml` line 30 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/240#-NEu1yuV-XQ_tKt61btD:-NEu1yuWCI4HP14MePUp:bdxc82k) ([raw file](https://github.com/coreumfoundation/coreum/blob/5a7cf56c949498d3250366afae5f79a5579a442d/.github/workflows/release.yml#L30)):*
> ```YAML
>       - name: Create Release
>         id: create_release
>         uses: actions/create-release@v1
> ```

this action is deprecated
___
*[`.github/workflows/release.yml` line 39 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/240#-NEu284H6zEv8hpRDBzq:-NEu284H6zEv8hpRDBzr:bdxc82k) ([raw file](https://github.com/coreumfoundation/coreum/blob/5a7cf56c949498d3250366afae5f79a5579a442d/.github/workflows/release.yml#L39)):*
> ```YAML
>           prerelease: true
>       - name: Upload cored-linux-amd64
>         uses: actions/upload-release-asset@v1
> ```

this action is deprecated

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/240)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/release.yml` line 39 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/240#-NEu284H6zEv8hpRDBzq:-NEuYPPD0btYbADtWtOX:bj8gm6s) ([raw file](https://github.com/coreumfoundation/coreum/blob/5a7cf56c949498d3250366afae5f79a5579a442d/.github/workflows/release.yml#L39)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this action is deprecated
</blockquote></details>

I compared the prev and current workflows to be sure the issue with the settings. 
It will be rolled back once we fix it.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/240)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/240)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
