### PR TITLE
Bumped Coreum go module version to v2

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/569)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 188 of 188 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 34 of 34 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 27 of 27 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/569)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @silverspase)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/569#-N_cFtsM4n73aGOasnnQ:-N_cFtsM4n73aGOasnnR:b-9cx03g) (no related file):*
One small comment from me is to commit name.

I think we will have another commit where we bump coreum to v2 in terms of binary
Here it is better to specify that it is related to module: `Bumped Coreum module version to v2`

___

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/569)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @silverspase)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/569#-N_cFtsM4n73aGOasnnQ:-N_cGCUa-BhiqVQpgIzz:b9z1nop) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

One small comment from me is to commit name.

I think we will have another commit where we bump coreum to v2 in terms of binary
Here it is better to specify that it is related to module: `Bumped Coreum module version to v2`
</blockquote></details>

or `Bumped Coreum go module version to v2`

___

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/569)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/569#-N_cFtsM4n73aGOasnnQ:-N_capUq-hbQHoazusAR:b-896fix) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

or `Bumped Coreum go module version to v2`
</blockquote></details>

Done.

___

**Review by ysv — APPROVED** [review]
> Reviewed 124 of 188 files at r1, 23 of 34 files at r2, 10 of 11 files at r3, 20 of 27 files at r4, 8 of 8 files at r5, 30 of 30 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/569)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
