### PR TITLE
Run CI workflow using self-hosted runner & minor CI hotfixes

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/402)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/402)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/402)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/402)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/402)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/402)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Pull request merged**
