### PR TITLE
Fix TestDeterministicGas_DeterministicMessages

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/958)

### CODE REVIEW

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/958)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/958)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`integration-tests/modules/distribution_test.go` line 155 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/958#-O6fEhklEp1EpfRXJ2mB:-O6fEhklEp1EpfRXJ2mC:bqj79jt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3d7dc1dc3253cc4a93d9d49a249de88c3484b456/integration-tests/modules/distribution_test.go#L155)):*
> ```Go
> 			&distributiontypes.MsgWithdrawDelegatorReward{},
> 		},
> 		Amount: amountToDelegate.Add(sdkmath.NewInt(5_000)),
> ```

What does the `5_000` mean here?
___
*[`x/deterministicgas/config.go` line 136 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/958#-O6fF0T44ZAyfouBgp24:-O6fF0T44ZAyfouBgp25:bbebel1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3d7dc1dc3253cc4a93d9d49a249de88c3484b456/x/deterministicgas/config.go#L136)):*
> ```Go
> 		MsgToMsgURL(&feegranttypes.MsgGrantAllowance{}):  constantGasFunc(11_000),
> 		MsgToMsgURL(&feegranttypes.MsgRevokeAllowance{}): constantGasFunc(2_500),
> 		MsgToMsgURL(&feegranttypes.MsgPruneAllowances{}): constantGasFunc(500),
> ```

Is it possible to prune multiple allowances so the gas spent is different from one to another message? If - yes, this message is undeterministic.

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/958)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/958)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/distribution_test.go` line 155 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/958#-O6fEhklEp1EpfRXJ2mB:-O6fX8LGAe8SlReXcPBs:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3d7dc1dc3253cc4a93d9d49a249de88c3484b456/integration-tests/modules/distribution_test.go#L155)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What does the `5_000` mean here?
</blockquote></details>

Done.
___
*[`x/deterministicgas/config.go` line 136 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/958#-O6fF0T44ZAyfouBgp24:-O6fX9UdEgB56vxEvo0E:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3d7dc1dc3253cc4a93d9d49a249de88c3484b456/x/deterministicgas/config.go#L136)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is it possible to prune multiple allowances so the gas spent is different from one to another message? If - yes, this message is undeterministic.
</blockquote></details>

Done.

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/958)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/958)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 5 files at r2, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/958)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/958)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
