### PR TITLE
Add protobuf breaking change check.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/366)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/366)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/366#-NMd28G1Ay0MXsFzFKb2:-NMd28G1Ay0MXsFzFKb3:b6h2ik6) (no related file):*
Please explain during the daily what this PR is about because I have no idea what those new proto files are about

___

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/366)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`.github/workflows/proto.yml` line 14 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/366#-NMmCTYX4aI3fWEgq3Vq:-NMmCTYX4aI3fWEgq3Vr:bwfhwd3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8976ae35fed9c6f59fb595b56c268620eb87743a/.github/workflows/proto.yml#L14)):*
> ```YAML
>       - uses: bufbuild/buf-breaking-action@v1
>         with:
>           against: 'https://github.com/CoreumFoundation/coreum.git#branch=master'
> ```

empty line is needed.
___
*[`third_party/proto/google/api/httpbody.proto` line 78 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/366#-NMmKU9I2vh2tXYVMFvm:-NMmKU9J546Emh-C8dzD:b45za1i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8976ae35fed9c6f59fb595b56c268620eb87743a/third_party/proto/google/api/httpbody.proto#L78)):*
> ```protobuf
>   // for streaming APIs.
>   repeated google.protobuf.Any extensions = 3;
> }
> ```

empty line here.

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
