### PR TITLE
Remove not needed TODOs and FIXMEs

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/392)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/392)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`pkg/config/network.go` line 616 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/392#-NOKAe3aA72czPIcM4Uu:-NOKAe3b82CBylCi2_Ba:b-k3agz5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3a2d9efe3cd5105bd0a74aa858a94a7d73a7d78f/pkg/config/network.go#L616)):*
> ```Go
> 	}
> 
> 	// TODO: remove this check once all preconfigured networkConfigs are enabled
> ```

this one is actually relevant I would say
Can you move it to somewhere near mainnet network config & I will remove it once I add mainnet ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/392)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/config/network.go` line 616 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/392#-NOKAe3aA72czPIcM4Uu:-NOKbx2h2d-UpVy1ao9L:b-z1lbyp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3a2d9efe3cd5105bd0a74aa858a94a7d73a7d78f/pkg/config/network.go#L616)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

this one is actually relevant I would say
Can you move it to somewhere near mainnet network config & I will remove it once I add mainnet ?
</blockquote></details>

It is a duplicate. The same TODO exists near the `Enabled` field

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/392)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/392)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Pull request merged**
