### PR TITLE
Add URI and URIHash to the asset FT issuance CLI.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Add URI and URIHash to the asset FT issuance CLI.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/697)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/697#-:-Ni3pKzDDx5TumR5A-pl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/client/cli/tx.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/697#-Ni3pDfS3q3oPoyEruGj:-Ni3pDfS3q3oPoyEruGk:b-ctx1b2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1b0ae0d45435a069715fc2798bd27bcc105320c/x/asset/ft/client/cli/tx.go#L74)):*
> ```Go
> 	sort.Strings(allowedFeatures)
> 	cmd := &cobra.Command{
> 		Use:   "issue [symbol] [subunit] [precision] [initial_amount] [description] [uri] [uri_hash] --from [issuer] --features=" + strings.Join(allowedFeatures, ",") + " --burn-rate=0.12 --send-commission-rate=0.2",
> ```

I think it should be optional via flags, so it is backward compatible.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/697)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`x/asset/ft/client/cli/tx.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/697#-Ni3pDfS3q3oPoyEruGj:-Ni5WbY27FbuO293y_68:b1lm52r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1b0ae0d45435a069715fc2798bd27bcc105320c/x/asset/ft/client/cli/tx.go#L74)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think it should be optional via flags, so it is backward compatible.
</blockquote></details>

I tend to agree

Is it really required param in API ? if no then should be opt here also

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/697)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`x/asset/ft/client/cli/tx.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/697#-Ni3pDfS3q3oPoyEruGj:-Ni8OaTI2LdTjDCJn7o2:btt3ixr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1b0ae0d45435a069715fc2798bd27bcc105320c/x/asset/ft/client/cli/tx.go#L74)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I tend to agree

Is it really required param in API ? if no then should be opt here also
</blockquote></details>

it can be empty in the API, as far as I know.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/697)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/client/cli/tx.go` line 74 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/697#-Ni3pDfS3q3oPoyEruGj:-Ni8lDgV21XcUi6VhYXE:b-kyqt8h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1b0ae0d45435a069715fc2798bd27bcc105320c/x/asset/ft/client/cli/tx.go#L74)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it can be empty in the API, as far as I know.
</blockquote></details>

I though the same as well, but later I found that in the NFT they are args, that's why decided to make the same here.

**Review by ysv — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/697)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/697)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/697)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
