### PR TITLE
Cross-feature test scenarios

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/325)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/325)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/cross_feature_test.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NKrEtC42x5Xfo25FN0v:-NKrEtC42x5Xfo25FN0w:b-bkym7d) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc9c5133ed7d028721df79bac610a82b88cc1161/x/asset/ft/keeper/cross_feature_test.go#L49)):*
> ```Go
> //
> // # Sending cored + FT
> // - test sending FT together with cored when FT transfer should fail/succeed due to whitelist/freezing
> ```

All is good. Few test from me to discuss/add. 
* Issue with empty amount and then Mint. That test is simple but I've not found it.
* Add permission tests to try to perform all actions on behalf of other accounts. That might be even as a separate test file.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/325)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/cross_feature_test.go` line 16 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NKsFDOQB6foZ1XjXhK_:-NKsFDOQB6foZ1XjXhKa:b7e71c6) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc9c5133ed7d028721df79bac610a82b88cc1161/x/asset/ft/keeper/cross_feature_test.go#L16)):*
> ```Go
> //
> // # Issuer + Global Freeze
> // - on the other hand global freeze means that nobody can send and receive tokens
> ```

issuer should not be affected by global freeze, and should be able to send
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 22 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NKsFRj21a5qgPBwP7Iu:-NKsFRj21a5qgPBwP7Iv:bbau5x2) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc9c5133ed7d028721df79bac610a82b88cc1161/x/asset/ft/keeper/cross_feature_test.go#L22)):*
> ```Go
> //
> // # Mint + Global Freeze
> // - if global freeze is active minting should fail
> ```

issuer is not affected by global freeze so minting should be fine. 
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NKsFcVb1pjZdUR65PHw:-NKsFcVb1pjZdUR65PHx:b96mllm) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc9c5133ed7d028721df79bac610a82b88cc1161/x/asset/ft/keeper/cross_feature_test.go#L24)):*
> ```Go
> // - if global freeze is active minting should fail
> //
> // # Burn + Global Freeze
> ```

it should only affect non-issuers

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/325)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/cross_feature_test.go` line 16 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NKsFDOQB6foZ1XjXhK_:-NL5E5IoEKaHA71dZIZ4:bv3vwnh) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc9c5133ed7d028721df79bac610a82b88cc1161/x/asset/ft/keeper/cross_feature_test.go#L16)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

issuer should not be affected by global freeze, and should be able to send
</blockquote></details>

Removed from that list since already implemented in my PR.
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 22 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NKsFRj21a5qgPBwP7Iu:-NL5ELn-DPLMCEQWI7bx:bw9dcfd) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc9c5133ed7d028721df79bac610a82b88cc1161/x/asset/ft/keeper/cross_feature_test.go#L22)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

issuer is not affected by global freeze so minting should be fine. 
</blockquote></details>

Agree, removed.
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NKsFcVb1pjZdUR65PHw:-NL5EQXF0p4GeTnyvDgY:bw9dcfd) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc9c5133ed7d028721df79bac610a82b88cc1161/x/asset/ft/keeper/cross_feature_test.go#L24)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it should only affect non-issuers 
</blockquote></details>

Agree, removed.



_Code quote:_
```Go
Burn + Global Freeze
```

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/325)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/325)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/325)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/325)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/325)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLj5QF0USvVW2HtKZk:-NLLj5QF0USvVW2HtKZl:b-hi9cuy) (no related file):*
Publishing a first comment for now
Will continue review

___
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 10 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLgRVx1MvisdcJUTUi:-NLLgRVx1MvisdcJUTUj:b4qdzqp) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L10)):*
> ```Go
> //
> // # Issuer + Freeze
> // - freezing balance for issuer account should not be possible, issuer may always receive and send funds
> ```

todo the next change in x/asset/ft/keeper/freeze.go `func isCoinSpendable`:
```
// on the 1st place to explicitly show that issuer don't care about freezing
if ft.Issuer == addr.String {
  return nil
}

if !featureEnabled {
  return nil 
}
```

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/325)* status: all files reviewed, 9 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/325)* status: all files reviewed, 9 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/cross_feature_test.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NKrEtC42x5Xfo25FN0v:-NLQWfLE0dzzI2iZjDca:bngv2xd) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc9c5133ed7d028721df79bac610a82b88cc1161/x/asset/ft/keeper/cross_feature_test.go#L49)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> Issue with empty amount and then Mint. That test is simple but I've not found it.

reasonable IMO

> Add permission tests to try to perform all actions on behalf of other accounts. That might be even as a separate test file.

yes i like this idea to centralize it in a single place
</blockquote></details>

Added: `issue the FT with the minimum possible filled data and apply Mint/Freeze/Whitelist/Burn`
Added: `Add table test that check the access to all features by issuer and non issuer with the enabled and disabled features`
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 10 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLgRVx1MvisdcJUTUi:-NLQVGzi8axfpCAsQoSN:bi2zu49) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L10)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

todo the next change in x/asset/ft/keeper/freeze.go `func isCoinSpendable`:
```
// on the 1st place to explicitly show that issuer don't care about freezing
if ft.Issuer == addr.String {
  return nil
}

if !featureEnabled {
  return nil 
}
```
</blockquote></details>

Is it related to that PR ? You can add it to the task with the FT refactoring. 
https://app.clickup.com/t/862j03h9n
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 13 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLkd5U5mDIK3gRN-BZ:-NLQVTdm1qoZpyBaPKXC:bjyoahd) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L13)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

tx whitelisting balance for issuer account should error out
</blockquote></details>

It's includded before.
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 20 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLluqJBEao6IKR0uUO:-NLQVavM-F1_vmUr_bDB:b-utckp2) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

```
Burn rate + issuer
- Burn rate should not apply when sent to/from issuer

Send commission + issuer
- Send commission should not apply when sent to/from issuer
```
</blockquote></details>

We already have that test. 
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 24 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLnmBY17TNYZbZngUz:-NLQVg9xBbDakT0DUYag:b-me3qrm) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we have tests checking that new whitelisted amount could be less than current balance ?
</blockquote></details>

But we can have the whitelisted more then  current balance.
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 35 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLp0ma7aWlXCH35LFt:-NLQWPPH41515O8PxnqX:bqmjwcz) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L35)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

maybe it makes sense also to check:
 `Burn rate + Send Commission + Freeze`
E.g 
Balance: 11
Send amount: 10
Burn Rate: 10%
Send Commission 10%

Expected behaviour: failure
</blockquote></details>

Added.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/325)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/cross_feature_test.go` line 45 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLoNaPAZAc0z5sKT3c:-NLQXBWP1mdgF_QKdGyk:b1jzj2e) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L45)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`FT + IBCed asset`

does it make sense to check that all FT features are ignored for non FT asset but not CORE e.g IBCed asset ?


</blockquote></details>

We already have such test.
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 46 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLplPn2n_C4d3OBBj0:-NLQXJKQ3EEhbUeeSrxN:bsuayf8) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L46)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

MsgMultisend + Commission & Burn Rate
</blockquote></details>

Added the remark: `All tests must be applied for to send and multi-send`
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 46 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLppSI-725iSdafJBu:-NLQXehB3GEojLiScZN-:b-9t7la0) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L46)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

AuthzExec & different permissions
</blockquote></details>

Do we need it ? Becase we don't have custom.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/325)* status: all files reviewed, 9 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/325)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`x/asset/ft/keeper/cross_feature_test.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NKrEtC42x5Xfo25FN0v:-NLQvPXt0l9qlp_moR-e:b-7f0y79) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc9c5133ed7d028721df79bac610a82b88cc1161/x/asset/ft/keeper/cross_feature_test.go#L49)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Added: `issue the FT with the minimum possible filled data and apply Mint/Freeze/Whitelist/Burn`
Added: `Add table test that check the access to all features by issuer and non issuer with the enabled and disabled features`
</blockquote></details>

ok
but should we then remove these checks spread across different functionality specific tests & just keep here ?
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 20 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLluqJBEao6IKR0uUO:-NLQuHZu2czMLi5UWK7V:b-kz3bcw) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L20)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We already have that test. 
</blockquote></details>

do you mean we have it out of scope of this PR ? because here I don't see it
I just want to make sure we have both from & to
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 24 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLnmBY17TNYZbZngUz:-NLQuie9Ev5oCS5T_wOj:b-4mawa3) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L24)):*
I meant:

> do we have tests checking that new whitelisted amount could not be less than current balance ?
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 45 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLoNaPAZAc0z5sKT3c:-NLQvfcR7renlmuR1aaT:bz880u3) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L45)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We already have such test.
</blockquote></details>

can you put a reference pls ?
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 46 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLppSI-725iSdafJBu:-NLQvm-M5GLHVgFCxBjU:b-wcmovf) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L46)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do we need it ? Becase we don't have custom.
</blockquote></details>

I mean next:
1. issuer grants access to Address1
2. Address1 issues token on behalf of issuer using AuthExec
3. Address1 is able to mint/freeze/whitelist etc. Checking a few of them is enough IMO

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/325)* status: all files reviewed, 5 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/cross_feature_test.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NKrEtC42x5Xfo25FN0v:-NLQwn6iCXhfs0dcRhmk:b44j6y) ([raw file](https://github.com/coreumfoundation/coreum/blob/dc9c5133ed7d028721df79bac610a82b88cc1161/x/asset/ft/keeper/cross_feature_test.go#L49)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok
but should we then remove these checks spread across different functionality specific tests & just keep here ?
</blockquote></details>

As for me - not. Better to add them additionaly and as integration tests.
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 20 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLluqJBEao6IKR0uUO:-NLQydgJ3u9PMuqUheJ4:blvuvb9) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do you mean we have it out of scope of this PR ? because here I don't see it
I just want to make sure we have both from & to
</blockquote></details>

That is tested in that PR: (https://reviewable.io/reviews/CoreumFoundation/coreum/321#-)
Out of scope of that. But I'm ok to add it if you prefer. 
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 24 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLnmBY17TNYZbZngUz:-NLQw_YG1svLjIMhCY3O:blivdph) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I meant:

> do we have tests checking that new whitelisted amount could not be less than current balance ?


</blockquote></details>

But in what cases we should check it? It looks more like the invariant. 
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 45 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLoNaPAZAc0z5sKT3c:-NLQx-LaCburohp9sgJG:byva8xz) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L45)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can you put a reference pls ?
</blockquote></details>

They are widespread across the repo. But Agree, let's add it as a table test.
Added: `Add table test to check that a native token skips all features checks`
___
*[`x/asset/ft/keeper/cross_feature_test.go` line 46 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/325#-NLLppSI-725iSdafJBu:-NLQxhEn6AJ-pEmNj3VI:b-lpx7s9) ([raw file](https://github.com/coreumfoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L46)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I mean next:
1. issuer grants access to Address1
2. Address1 issues token on behalf of issuer using AuthExec
3. Address1 is able to mint/freeze/whitelist etc. Checking a few of them is enough IMO
</blockquote></details>

Ok, let's add them. Added.
`
Add test to issue a token with freeze and whitelisting features and test those features from the issuer and non-issuer accounts executed on behalf of a grantee
`

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/325)* status: all files reviewed, 5 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/325)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

___
*[`x/asset/ft/keeper/cross_feature_test.go` line 24 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/325#-NLLnmBY17TNYZbZngUz:-NLXh4arAFcs-6PLnpQn:b7zyp3i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L24)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But in what cases we should check it? It looks more like the invariant. 
</blockquote></details>

I mean smth like this:

1. set whitelisted limit to 10 ABC on address1
2. send 10 ABC to address 1
3. set whitelisted limit to 9 ABC on address1

or we already have it ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/325)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

___
*[`x/asset/ft/keeper/cross_feature_test.go` line 24 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/325#-NLLnmBY17TNYZbZngUz:-NL_JXIW1MDkhsTu9KfD:b-hf8zg6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I mean smth like this:

1. set whitelisted limit to 10 ABC on address1
2. send 10 ABC to address 1
3. set whitelisted limit to 9 ABC on address1

or we already have it ?
</blockquote></details>

Haven't found that case. Valid agree. And it's important as well. I would add it into the whitelisting directly because it looks like not composite.

Added to that list as well.

Let's discuss it on the call today. Since not sure that we should fail in that case.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/325)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/325)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/325)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

___
*[`x/asset/ft/keeper/cross_feature_test.go` line 10 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/325#-NLLgRVx1MvisdcJUTUi:-NLuEL6JD23TC-v7Ee3l:bp7e3rq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/baa63e6bfe3f19362b6a772db13a0819114f9017/x/asset/ft/keeper/cross_feature_test.go#L10)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is it related to that PR ? You can add it to the task with the FT refactoring. 
https://app.clickup.com/t/862j03h9n
</blockquote></details>

I prefer to check the feature first, since if it isn't enabled we don't need to move on. Then agree, we can check the issue separately.

**Comment by dzmitryhil** [comment]
The PR is approived and the tests moved to the task

**Pull request closed without merging**
