### PR TITLE
Remove deprecated REST proposal handlers

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/374)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/374)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`app/app.go` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/374#-NNM9B-e8q7aR2mw4Wmo:-NNM9B-e8q7aR2mw4Wmp:b2z4qou) ([raw file](https://github.com/CoreumFoundation/coreum/blob/26b03a700d9cf3d5d87d2c150ccd6715a8bab9c6/app/app.go#L132)):*
> ```Go
> var ChosenNetwork config.Network
> 
> func getGovProposalHandlers() []govclient.ProposalHandler {
> ```

could you provide quick explanation for the changes ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/374)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`app/app.go` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/374#-NNM9B-e8q7aR2mw4Wmo:-NNN1pQg5mgStMM735KA:b-2rahje) ([raw file](https://github.com/CoreumFoundation/coreum/blob/26b03a700d9cf3d5d87d2c150ccd6715a8bab9c6/app/app.go#L132)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

could you provide quick explanation for the changes ?
</blockquote></details>

Removed handlers are for proposals submitted using REST. REST is deprecated and also REST handlers in WASM are marked as deprecated. All the proposals go through grpc handlers anyway so we don't need REST interface.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/374)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

___
*[`app/app.go` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/374#-NNM9B-e8q7aR2mw4Wmo:-NN_ft58Ao6yvVSfa_gr:b-k0st6y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/26b03a700d9cf3d5d87d2c150ccd6715a8bab9c6/app/app.go#L132)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Removed handlers are for proposals submitted using REST. REST is deprecated and also REST handlers in WASM are marked as deprecated. All the proposals go through grpc handlers anyway so we don't need REST interface.
</blockquote></details>

Rest is not deprecated it seems like. the old way they handled the rest is deprecated. So if we remove this endpoints, does it mean there is new rest handlers exposed ?
I think we need to get on the same page on what we mean by REST is deprecated.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/374)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

___
*[`app/app.go` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/374#-NNM9B-e8q7aR2mw4Wmo:-NNaT1PX1xCZErJdj8nv:b7y8w2b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/26b03a700d9cf3d5d87d2c150ccd6715a8bab9c6/app/app.go#L132)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Rest is not deprecated it seems like. the old way they handled the rest is deprecated. So if we remove this endpoints, does it mean there is new rest handlers exposed ?
I think we need to get on the same page on what we mean by REST is deprecated. 
</blockquote></details>

WASM deprecated their function returning handlers for this method. And this method uses rest router, and I think that router is going to be deprecated too

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/374)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/374)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

___
*[`app/app.go` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/374#-NNM9B-e8q7aR2mw4Wmo:-NNkUWJ97Q6-UXAq9L05:b-pvauix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5023c8450ec93f8427ec65211c13e08b25b26fc6/app/app.go#L132)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

WASM deprecated their function returning handlers for this method. And this method uses rest router, and I think that router is going to be deprecated too
</blockquote></details>

I think it will be deprecated once the proposal model has changed, and I think it is changed in v0.47 where the proposals will only  dispatch message messages. so the handler will be a simple grpc method. but since we are not on v0.47 we should keep this.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/374)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

___
*[`app/app.go` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/374#-NNM9B-e8q7aR2mw4Wmo:-NNkp7EjA-qmjaPpItyU:b-2nerb4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5023c8450ec93f8427ec65211c13e08b25b26fc6/app/app.go#L132)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think it will be deprecated once the proposal model has changed, and I think it is changed in v0.47 where the proposals will only  dispatch message messages. so the handler will be a simple grpc method. but since we are not on v0.47 we should keep this.
</blockquote></details>

But the proposal model already supports grpc

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/374)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

___
*[`app/app.go` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/374#-NNM9B-e8q7aR2mw4Wmo:-NNlGrA60Q0QFNfiX2o7:bshblfo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5023c8450ec93f8427ec65211c13e08b25b26fc6/app/app.go#L132)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But the proposal model already supports grpc
</blockquote></details>

If we are sure that every one of them has a grpc counterpart, then it is ok.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/374)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

___
*[`app/app.go` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/374#-NNM9B-e8q7aR2mw4Wmo:-NNlLFjq18TtDXOFWNts:b-rhexu7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5023c8450ec93f8427ec65211c13e08b25b26fc6/app/app.go#L132)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

If we are sure that every one of them has a grpc counterpart, then it is ok. 
</blockquote></details>

yes, I checked it

**Pull request merged**
