### PR TITLE
Implemented complex integration tests phase 4

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/416)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
nice test cases :thumbsup: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/416#-:-NPXATCz7FvS85Ekd0QB:br692qz)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/authz_test.go` line 140 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/416#-NPX9_XO4QVe4PwaLYQc:-NPX9_XO4QVe4PwaLYQd:b-mu8uya) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2c0379cf55e1a293b55ea12419b1c08840d4d09/integration-tests/modules/authz_test.go#L140)):*
> ```Go
> 
> // TestAuthz tests the authz module works well with assetft module.
> func TestAuthzWithAssetFT(t *testing.T) {
> ```

I would probably move this to assetft_test since we mostly test ft here not authz
___
*[`integration-tests/modules/authz_test.go` line 212 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/416#-NPX9sQs9CVBaFGNXVp8:-NPX9sQs9CVBaFGNXVp9:bf7jyrm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2c0379cf55e1a293b55ea12419b1c08840d4d09/integration-tests/modules/authz_test.go#L212)):*
> ```Go
> 		Sender:  granter.String(),
> 		Account: recipient.String(),
> 		Coin:    sdk.NewCoin(denom, sdk.NewInt(1_000)),
> ```

lets use different amounts for freezing & whitelisting

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/416)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/authz_test.go` line 140 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/416#-NPX9_XO4QVe4PwaLYQc:-NPXLfpu8TkSqKd4zHY-:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2c0379cf55e1a293b55ea12419b1c08840d4d09/integration-tests/modules/authz_test.go#L140)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree. 
</blockquote></details>

Done.
___
*[`integration-tests/modules/authz_test.go` line 212 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/416#-NPX9sQs9CVBaFGNXVp8:-NPXM0Bo35nOWTv0UzAR:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2c0379cf55e1a293b55ea12419b1c08840d4d09/integration-tests/modules/authz_test.go#L212)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets use different amounts for freezing & whitelisting
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/416)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 1469 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/416#-NPasEw19GILTlzbM48T:-NPasEw19GILTlzbM48U:b-woom3p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f691cc6b7d087370eefd5d4b1a597c00479b1ea2/integration-tests/modules/assetft_test.go#L1469)):*
> ```Go
> 
> 	// query frozen tokens
> 	frozenBalance, err := ftClient.FrozenBalance(ctx, &assetfttypes.QueryFrozenBalanceRequest{
> ```

this is not needed
___
*[`integration-tests/modules/assetft_test.go` line 1476 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/416#-NPasSY54R7M00ubApXr:-NPasSY54R7M00ubApXs:bcdjboi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f691cc6b7d087370eefd5d4b1a597c00479b1ea2/integration-tests/modules/assetft_test.go#L1476)):*
> ```Go
> 	requireT.EqualValues(sdk.NewCoin(denom, sdk.NewInt(650)), frozenBalance.Balance)
> 
> 	// try to send more than available (300 + 60) (1000 - 650(frozen) = 350 is available)
> ```

test should send the available balance (350) and transaction should fail because commission rate does not fit intoavailable balance

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/416)* status: all files reviewed, 4 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 1469 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/416#-NPasEw19GILTlzbM48T:-NPbgWd_5A3BBfvAFGHw:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f691cc6b7d087370eefd5d4b1a597c00479b1ea2/integration-tests/modules/assetft_test.go#L1469)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this is not needed
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetft_test.go` line 1476 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/416#-NPasSY54R7M00ubApXr:-NPbgi6zA0W2BYmaa7--:b-n2jwi3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f691cc6b7d087370eefd5d4b1a597c00479b1ea2/integration-tests/modules/assetft_test.go#L1476)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

test should send the available balance (350) and transaction should fail because commission rate does not fit intoavailable balance
</blockquote></details>

I don't see how that improves the test ?

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/416)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/416)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @silverspase)

___
*[`x/asset/ft/keeper/keeper_test.go` line 1462 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/416#-NPuoqka8xwP4fM-As-N:-NPuoqkb85_OsFzcL-2m:b-eh3i42) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d1d872910fad541edeed3460ee64886c65a36331/x/asset/ft/keeper/keeper_test.go#L1462)):*
> ```Go
> 				sdk.NewCoin(bondDenom, sdk.NewInt(20)),
> 			)},
> 			// the recipient2 has whitelisted balance so that is the max amount recipient2 can receive
> ```

why max? you whitelisted 100

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/416)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`x/asset/ft/keeper/keeper_test.go` line 1462 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/416#-NPuoqka8xwP4fM-As-N:-NQ-vqRU4Jq7-4NOi_cU:b6nx25i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d1d872910fad541edeed3460ee64886c65a36331/x/asset/ft/keeper/keeper_test.go#L1462)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why max? you whitelisted 100
</blockquote></details>

reduced whitelisting to 10

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/416)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/416)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/416)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
