### PR TITLE
Implemented the soulbound feature for NFTs

### PR DESCRIPTION
**Pull request by miladz68**
# Description
This PR implements the soulbound feature for the NFTs. Soulbound NFTs cannot be sent or received by users. 
# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/693)

### CODE REVIEW

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/693)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/693#-Ni-xxOtBhJWb6iSauH1:-Ni-xxOtBhJWb6iSauH2:b3vofwv) (no related file):*
Please note that tests are missing.

___

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/693)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/693#-Ni-xxOtBhJWb6iSauH1:-Ni3cA-R1nIAHA3md4LY:b21xha2) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Please note that tests are missing.
</blockquote></details>

tests are now implemented. 

___

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 4 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/693)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`docs/static/openapi.json` line 7291 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/693#-Ni3jM1YB9b7WSjUZdg4:-Ni3jM1YB9b7WSjUZdg5:bnks0au) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a10d2549d6e93d0e4d34e195b6b8d2821a7ec142/docs/static/openapi.json#L7291)):*
> ```JSON
>         "whitelisting",
>         "disable_sending",
>         "soulbound"
> ```

@ysv When do we update the spec and table with features?

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/693)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`docs/static/openapi.json` line 7291 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/693#-Ni3jM1YB9b7WSjUZdg4:-Ni4XJMICnXERORf4OKN:b-eet9mm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a10d2549d6e93d0e4d34e195b6b8d2821a7ec142/docs/static/openapi.json#L7291)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv When do we update the spec and table with features?
</blockquote></details>

Before release
added this one to checklist 
___
*[`integration-tests/modules/assetnft_test.go` line 2057 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/693#-Ni4YF_e8QoEafNSh1BX:-Ni4YF_e8QoEafNSh1BY:b-le3983) ([raw file](https://github.com/CoreumFoundation/coreum/blob/16ba0fc85ad1b03708e84db16a407f08a86c3b81/integration-tests/modules/assetnft_test.go#L2057)):*
> ```Go
> }
> 
> func TestAssetNFTSoulbound(t *testing.T) {
> ```

nit: I think we added feature where we can mint with destination
Could you test if for soul-bound NFT also pls ?
___
*[`integration-tests/modules/assetnft_test.go` line 2124 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/693#-Ni4XyKF4vZC5uMxD_Jn:-Ni4XyKF4vZC5uMxD_Jo:btncgif) ([raw file](https://github.com/CoreumFoundation/coreum/blob/16ba0fc85ad1b03708e84db16a407f08a86c3b81/integration-tests/modules/assetnft_test.go#L2124)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// try to send from recipient to issuer (it is not allowed)
> ```

hm, I'm not sure about this behaviour. 
I thought that issuer can always receive/send sould-bound NFTs but none else.
Because in current implementation NFT will stay on users acc forever.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/693)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 2057 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/693#-Ni4YF_e8QoEafNSh1BX:-Ni4aoQs2iDYkQISv8b6:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/16ba0fc85ad1b03708e84db16a407f08a86c3b81/integration-tests/modules/assetnft_test.go#L2057)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: I think we added feature where we can mint with destination
Could you test if for soul-bound NFT also pls ?
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetnft_test.go` line 2124 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/693#-Ni4XyKF4vZC5uMxD_Jn:-Ni4afSY2IuGB_xlSYAA:b-8rzcje) ([raw file](https://github.com/CoreumFoundation/coreum/blob/16ba0fc85ad1b03708e84db16a407f08a86c3b81/integration-tests/modules/assetnft_test.go#L2124)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

hm, I'm not sure about this behaviour. 
I thought that issuer can always receive/send sould-bound NFTs but none else.
Because in current implementation NFT will stay on users acc forever.
</blockquote></details>

Yes, but if the user can send it back, it will not be soulbound.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/693)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/693)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/693)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
