### PR TITLE
Integration test with go tests

### PR DESCRIPTION
**Pull request by dzmitryhil**
Use native go test framework for the integration tests.

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/301)

### CODE REVIEW

**Review by miladz68 — DISMISSED** [review]
> Reviewed 62 of 62 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/301)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/301#-NJk7q2-5Bo33tU1DaQO:-NJk7q2-5Bo33tU1DaQP:bujbc5a) (no related file):*
I did not review very deep. I just trust that most files have moved around and just approved. 

___

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 62 of 62 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/301)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/301#-NJk7q2-5Bo33tU1DaQO:-NJkj3rF-0nYPrEBAQEa:bnm1k8h) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I did not review very deep. I just trust that most files have moved around and just approved. 
</blockquote></details>

Also didn't check everything test by test
But overall restructuring looks good for me

___
___
*[`integration-tests/modules/wasm_test.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/301#-NJkyngK8NNtsxqevQjl:-NJkyngK8NNtsxqevQjm:b-b0od5x) ([raw file](https://github.com/coreumfoundation/coreum/blob/760bc256646e3d8807af91fbb470d8517a628cc6/integration-tests/modules/wasm_test.go#L1)):*
> ```Go
> //go:build integrationtests
> ```

minor:
it might make sense to use integrationt_tests as tag here for readability
___
*[`integration-tests/upgrade/upgrade_test.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/301#-NJkjNPJ--Ghem0jY0c2:-NJkjNPJ--Ghem0jY0c3:bsbipxr) ([raw file](https://github.com/coreumfoundation/coreum/blob/760bc256646e3d8807af91fbb470d8517a628cc6/integration-tests/upgrade/upgrade_test.go#L1)):*
> ```Go
> //go:build integrationtests
> ```

should it have the same build tag as `modules` or a different one ?

It depends on logic you want to put into this tags.
I would say it could be `integration_tests_modules` & `integrationt_tests_upgrade`
Or we can keep it as it is

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/301)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/301#-NJkyngK8NNtsxqevQjl:-NJneGoB71Q7Z0G8r_L6:b-tnjuk3) ([raw file](https://github.com/coreumfoundation/coreum/blob/760bc256646e3d8807af91fbb470d8517a628cc6/integration-tests/modules/wasm_test.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
it might make sense to use integrationt_tests as tag here for readability
</blockquote></details>

The package name is "integrationtests" that's why I decided to use that tag as well. If you still consider that we should rename it, let me know please. I don't have strong opinion on that.
___
*[`integration-tests/upgrade/upgrade_test.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/301#-NJkjNPJ--Ghem0jY0c2:-NJneafN3sMMK6dT3bIp:b9irwqt) ([raw file](https://github.com/coreumfoundation/coreum/blob/760bc256646e3d8807af91fbb470d8517a628cc6/integration-tests/upgrade/upgrade_test.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should it have the same build tag as `modules` or a different one ?

It depends on logic you want to put into this tags.
I would say it could be `integration_tests_modules` & `integrationt_tests_upgrade`
Or we can keep it as it is
</blockquote></details>

It was in the initial version, but then I understood that each package will be build to it's own binary, so we can use just one tag for the simplicity.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 62 of 62 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/301)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/chain.go` line 54 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/301#-NJnmN3FB4LuU1bEbdOD:-NJnmN3FB4LuU1bEbdOE:b-7rb2zv) ([raw file](https://github.com/coreumfoundation/coreum/blob/760bc256646e3d8807af91fbb470d8517a628cc6/integration-tests/chain.go#L54)):*
> ```Go
> // If the mnemonic is already imported the method will just return the address.
> func (c ChainContext) ImportMnemonic(mnemonic string) sdk.AccAddress {
> 	// prevent double import
> ```

what does it mean?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/301)* status: 61 of 62 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/chain.go` line 54 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/301#-NJnmN3FB4LuU1bEbdOD:-NJnxOzLA_-OZPLL39-r:b-h2eqhd) ([raw file](https://github.com/coreumfoundation/coreum/blob/760bc256646e3d8807af91fbb470d8517a628cc6/integration-tests/chain.go#L54)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what does it mean?
</blockquote></details>

It was done because of the wrong tests execution, I fixed the execution, but missed that part. We don't need it anymore. Thanks for the catch, Removed now.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/301)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/301)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, 70 of 70 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/301)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil)

___
*[`integration-tests/modules/wasm_test.go` line 612 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/301#-NJsolG49ydxOXFf8lYB:-NJsolG49ydxOXFf8lYC:bb5dclb) ([raw file](https://github.com/coreumfoundation/coreum/blob/f63b391c1c74d745578d1f892852534017119ceb/integration-tests/modules/wasm_test.go#L612)):*
> ```Go
> 
> // IsWASMContractPinned returns true if smart contract is pinned
> func IsWASMContractPinned(ctx context.Context, clientCtx tx.ClientContext, codeID uint64) (bool, error) {
> ```

non-blocking
I wonder why we need to export it ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/301)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68)

___
*[`integration-tests/modules/wasm_test.go` line 612 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/301#-NJsolG49ydxOXFf8lYB:-NJt225i-qE2_Oymc9VA:bjauyqz) ([raw file](https://github.com/coreumfoundation/coreum/blob/b52c63efb49bc7b495a0bad950166ac02a9afa9b/integration-tests/modules/wasm_test.go#L612)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking
I wonder why we need to export it ?
</blockquote></details>

It was exported before. But I agree, we don't need it. Updated.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/301)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 69 of 70 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/301)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Pull request merged**
