### PR TITLE
Move building system from `crust`

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

Files in `build/coreum` are simply copied from `crust/build/coreum`.
Other files in this PR are copied and adjusted.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/757)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/757)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/757#-Nmq8twT3DQO5gtTHLrx:-Nmq8twT3DQO5gtTHLry:b-cmm0g) (no related file):*
I have a few general questions which would be nice to clarify before we move forward e.g:
1. how and by which component (crust/coreum) build dependencies are installed and managed (golang, rust etc) ?
2. what if e.g we have golang 1.20 in faucet and 1.21 in coreum ?  
3. where do we store linter config ?

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/757)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/757#-Nmq8twT3DQO5gtTHLrx:-Nnbhb4r0ERo8XKDwspj:baexa6d) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I have a few general questions which would be nice to clarify before we move forward e.g:
1. how and by which component (crust/coreum) build dependencies are installed and managed (golang, rust etc) ?
2. what if e.g we have golang 1.20 in faucet and 1.21 in coreum ?  
3. where do we store linter config ?
</blockquote></details>

And one more question from me:
4. Is it OK that coreum depends on the crust or it should be a different repo?

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/757)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/757#-Nmq8twT3DQO5gtTHLrx:-NoBA_YmC2-xA7FzeLIr:betq0yw) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

And one more question from me:
4. Is it OK that coreum depends on the crust or it should be a different repo?
</blockquote></details>

1. Script `bin/coreum` in coreum repo does everything. But it delegates tasks to code imported from `crust`. If tool is needed it is installed automatically using the version from the imported `crust`.
2. https://reviewable.io/reviews/CoreumFoundation/crust/339#- solves this by keeping dependencies versioned by the version of imported crust
3. It is stored in the binary and saved under versioned directory

___

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 21 of 24 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/757)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`bin/coreum` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/757#-NomdN99E7nyimC8jd4k:-NomdN99E7nyimC8jd4l:byx1wfz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dcb9fdf2d806ec92a6613c79eec0ee538ef11c4e/bin/coreum#L1)):*
> ```
> #!/bin/bash
> ```

so all build  commands go through this wrapper similar to the way it works in crust ?
Maybe, to be more explicit  it should be named smth like `cored-builder` or `coreum-builder` or `build` instead of builder  ?
___
*[`build/index.go` line 18 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/757#-Nomq_uLC6m32WBuXEg3:-Nomq_uN4X4SdjaIm2Nu:b-wkl9gu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dcb9fdf2d806ec92a6613c79eec0ee538ef11c4e/build/index.go#L18)):*
> ```Go
> 	"build/integration-tests/upgrade": coreum.BuildIntegrationTests(coreum.TestUpgrade),
> 	"generate":                        coreum.Generate,
> 	"images":                          coreum.BuildCoredDockerImage,
> ```

nit: I'm not sure if images in plural is applicable here since you build a single one

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/757)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/757#-NomtLUIEMnTvijkj9Jl:-NomtLUIEMnTvijkj9Jm:b-nk65jy) (no related file):*
@wojtek-coreum could you pls create an umbrella task in backlog with description of all steps needed to finalize this.
Pls don't forget that we also want to have Makefile in Coreum

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/757)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`build/index.go` line 18 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/757#-Nomq_uLC6m32WBuXEg3:-NopFxjC4zHkcZVCwJcL:btdhtnq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dcb9fdf2d806ec92a6613c79eec0ee538ef11c4e/build/index.go#L18)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: I'm not sure if images in plural is applicable here since you build a single one
</blockquote></details>

I want to avid situation where in one repo you have `image` and in another `images`. Command `images` builds all the available images, single image is just an edge case.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/757)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`bin/coreum` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/757#-NomdN99E7nyimC8jd4k:-NopG_t1DHRMvBzp20Sq:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/dcb9fdf2d806ec92a6613c79eec0ee538ef11c4e/bin/coreum#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so all build  commands go through this wrapper similar to the way it works in crust ?
Maybe, to be more explicit  it should be named smth like `cored-builder` or `coreum-builder` or `build` instead of builder  ?
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/757)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/757)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/757#-NomtLUIEMnTvijkj9Jl:-NoqGaGKD_3hUTO9uOwL:b-snwm8m) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

@wojtek-coreum could you pls create an umbrella task in backlog with description of all steps needed to finalize this.
Pls don't forget that we also want to have Makefile in Coreum
</blockquote></details>

https://app.clickup.com/t/86873z34d

___

**Review by dzmitryhil — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/757#-:-NovnT8JC7TCzM1IWL77:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
