### PR TITLE
Integrate gov module

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/249)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/249)* status: 0 of 13 files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/gov/gov.go` line 33 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/249#-NGQ4YhfADRMcVkT3hbz:-NGTIPRZ6E8XDayD3ERz:b-vb0h1a) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c50b9ee5b5f60a70d77c16c2c484bd6cae436a6/integration-tests/gov/gov.go#L33)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't use the FundAccountsWithOptions?
</blockquote></details>

it wasn't there initially when I started this PR
Updated
___
*[`integration-tests/gov/gov.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/249#-NGQ4rN74LUDVtyOXdFE:-NGTITW1-XfB8FDPYVkc:b-4dqo24) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c50b9ee5b5f60a70d77c16c2c484bd6cae436a6/integration-tests/gov/gov.go#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

ProposeV2 ? The method name is weird.
</blockquote></details>

it was WIP thingy
___
*[`integration-tests/gov/gov.go` line 64 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/249#-NGQ4xif05F6qlZchDmu:-NGTIcOnC036xgpbnzPi:bt5m9pc) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c50b9ee5b5f60a70d77c16c2c484bd6cae436a6/integration-tests/gov/gov.go#L64)):*
> StatusF

renamed to requirePropStatusFunc
___
*[`integration-tests/gov/gov.go` line 79 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/249#-NGQ53ZYBeAZdwByfOVx:-NGTWvc3EHRwhHITF_Gj:b-7tfmjp) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c50b9ee5b5f60a70d77c16c2c484bd6cae436a6/integration-tests/gov/gov.go#L79)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How about to chech the deterministic gas?
</blockquote></details>

added
___
*[`integration-tests/testing/gov.go` line 187 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/249#-NGQ5Sod4DR5slh9l45l:-NGTJTJb0pNS4LaBO5Uw:b-wiogth) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c50b9ee5b5f60a70d77c16c2c484bd6cae436a6/integration-tests/testing/gov.go#L187)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This not a good idea to tread constants as its. This is just an enum. Better to use it with the a enum.
</blockquote></details>

agree fixed
___
*[`integration-tests/testing/gov.go` line 211 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/249#-NGQ5gLKBaokzZXSHM6Y:-NGTJUx0Br3S9hG8ltQN:bvwoxj) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c50b9ee5b5f60a70d77c16c2c484bd6cae436a6/integration-tests/testing/gov.go#L211)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Are you sure that the method is reusable by many tests? If not then better to keep it in the test you need. 
</blockquote></details>

refactored other parts now it is not needed
___
*[`integration-tests/testing/network.go` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/249#-NGQAdMb6bmQDIb7C_YO:-NGTJb8U9Gf6cWfJ8dTU:bdwlqno) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c50b9ee5b5f60a70d77c16c2c484bd6cae436a6/integration-tests/testing/network.go#L12)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the reason to change it?  If you are ok with the devenet config better to use the default. And remove that value.
</blockquote></details>

actually this param was introduced by wrong understanding its meaning I guess
and in reality we don't need to customize it currently

I can probably remove it agree
___
*[`pkg/config/deterministic_gas.go` line 25 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/249#-NGTZIUcDzjewffjBAJu:-NGTZIUcDzjewffjBAJv:b1ru6tv) ([raw file](https://github.com/coreumfoundation/coreum/blob/60cce408ec6cc73920c39ceb5fe67d63bf919dc6/pkg/config/deterministic_gas.go#L25)):*
> ```Go
> 
> 		// Q: Should I subtract FixedGas ?
> 		GovSubmitProposal: 145000,
> ```

here are the values I got
```
govtypes.MsgSubmitProposal: // 145849, 141842, 145909, 143653, 145909
govtypes.MsgVote: // 57548, 57554, 57554
govtypes.MsgVoteWeighted: // 57365, 58073, 61310, 61316, 61310
govtypes.MsgDeposit: // 89111, 103979, 141782, 141842, 141782
```

should I round them up as they are or subtract FixedGas and then round ?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/249)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/testing/gov.go` line 187 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/249#-NGQ5Sod4DR5slh9l45l:-NGWmxyM80QzFuJa-cwP:bscvyys) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c50b9ee5b5f60a70d77c16c2c484bd6cae436a6/integration-tests/testing/gov.go#L187)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would prefer `switch` here. 
</blockquote></details>

I agree fixed

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/249)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/249)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/249)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Pull request merged**
