### PR TITLE
Implement send fee for token transfers

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: 0 of 28 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJe67vb3l2acJG2JAXh:-NJe67vb3l2acJG2JAXi:b-sjzcce) (no related file):*
This is draft because it is implemented on top of #300. Will be converted to regular PR once that one is merged.

___

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: 0 of 28 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/burn_rate_and_send_fee_test.go` line 92 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJiZpT86ttpmJURSYIV:-NJiZpT86ttpmJURSYIW:bk8ot37) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/keeper/burn_rate_and_send_fee_test.go#L92)):*
> ```Go
> 
> //nolint:dupl // We don't care
> func TestKeeperCalculateSendFee(t *testing.T) {
> ```

Do we need 2 methods and tests or we can use one?
___
*[`x/asset/ft/keeper/keeper.go` line 110 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJi_N7V-R6RerHHOQzi:-NJi_N7V-R6RerHHOQzj:b-nsv4gl) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/keeper/keeper.go#L110)):*
> ```Go
> 				}
> 			}
> 			if !ft.SendFee.IsNil() && ft.SendFee.IsPositive() && ft.Issuer != inAddress.String() {
> ```

What about the idea to use the common function for the multi send and send ?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/ft/keeper/burn_rate_and_send_fee_test.go` line 92 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJiZpT86ttpmJURSYIV:-NJj21O52nYGNYseSxbP:b-tnneii) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/keeper/burn_rate_and_send_fee_test.go#L92)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do we need 2 methods and tests or we can use one?
</blockquote></details>

These are separate features so I think it's a good idea to first test each of them separately, and then together because they interfere in some way
___
*[`x/asset/ft/keeper/keeper.go` line 110 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJi_N7V-R6RerHHOQzi:-NJj1NgE5lReLUjA28mg:bmrfswo) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/keeper/keeper.go#L110)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about the idea to use the common function for the multi send and send ?
</blockquote></details>

There is TODO:

```
// TODO: we should try to express this function in terms of BeforeInputOutputCoins so
// we will have a single place to enforce our logic
```

and we will do this in separate PR

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: all files reviewed, 5 unresolved discussions (waiting on @wojtek-coreum)

___
*[`integration-tests/assetft/burn_rate.go` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkR9vT2P5qXkiynmg3:-NJkR9vT2P5qXkiynmg4:buxwf2q) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/integration-tests/assetft/burn_rate.go#L52)):*
> ```Go
> 		Features:      []types.TokenFeature{},
> 		BurnRate:      sdk.MustNewDecFromStr("0.10"),
> 		SendFee:       sdk.NewDec(0),
> ```

the thing is that in task description we decided to name it `send_commission_rate`.
I at like word rate there

If you insist we might rename it. 

But lets discuss this on call before doing any renaming 

___
*[`x/asset/ft/keeper/burn_rate_and_send_fee_test.go` line 19 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkSZXy0290brG0NFbG:-NJkSZXy0290brG0NFbH:bep31mr) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/keeper/burn_rate_and_send_fee_test.go#L19)):*
> ```Go
> 
> //nolint:dupl // We don't care
> func TestKeeperCalculateBurnCoin(t *testing.T) {
> ```

I don't like copying these 2 test cases here & in TestKeeperCalculateSendFee
why can't we just test `calculateRate` func and that is it
___
*[`x/asset/ft/keeper/keeper.go` line 74 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkU18a1mMgC9G9aj_n:-NJkU18a1mMgC9G9aj_o:btm1kyc) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/keeper/keeper.go#L74)):*
> ```Go
> 
> func (k Keeper) applySendFee(ctx sdk.Context, ft types.TokenDefinition, fromAddress, toAddress sdk.AccAddress, coin sdk.Coin) error {
> 	if !ft.SendFee.IsNil() && ft.SendFee.IsPositive() && ft.Issuer != fromAddress.String() && ft.Issuer != toAddress.String() {
> ```

IDK why but I don't like this if statement & what is more it is repeated 4 times

The only improvement I see so far is to change it like this:
```
if ft.SendFee.IsNil() || ft.SendFee.IsNegative() || ft.Issuer == fromAddress.String() && ft.Issuer == toAddress.String() {
  return nil
}
```
it looks more natural in this way but ideally would be to centralize this logic in a single place
any ideas ?
___
*[`x/asset/ft/types/ft.go` line 132 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkUvTy5HyLF-ZmOwdH:-NJkUvTy5HyLF-ZmOwdI:bt402vg) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/types/ft.go#L132)):*
> ```Go
> 	}
> 
> 	if !isDecPrecisionValid(rate, 4) {
> ```

can we move this 4 to constant ?
___
*[`x/asset/ft/types/ft_test.go` line 221 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkV8wm2zq8Agt29YjP:-NJkV8wm2zq8Agt29YjQ:b-7gzngu) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/types/ft_test.go#L221)):*
> ```Go
> 
> //nolint:dupl // We don't care
> func TestValidateSendFee(t *testing.T) {
> ```

I suggest to test `validateRate` only to avoid duplication
or you can call both methods one by one under a single Test function



_Code quote (from x/asset/ft/types/ft.go):_
```Go
validateRate
```

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: all files reviewed, 5 unresolved discussions (waiting on @ysv)

___
*[`x/asset/ft/keeper/burn_rate_and_send_fee_test.go` line 19 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkSZXy0290brG0NFbG:-NJnbcRw09m3VN6RgJOF:b-81v5fq) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/keeper/burn_rate_and_send_fee_test.go#L19)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't like copying these 2 test cases here & in TestKeeperCalculateSendFee
why can't we just test `calculateRate` func and that is it
</blockquote></details>

Because I prefer to test features, not internal function. Internal function might change but feature should work the same way. Also, one feature might be removed or modified and that should not affect the test of the other one.
___
*[`x/asset/ft/keeper/keeper.go` line 74 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkU18a1mMgC9G9aj_n:-NJnc0xJBxFazxJV28ly:bzhiqdg) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/keeper/keeper.go#L74)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IDK why but I don't like this if statement & what is more it is repeated 4 times

The only improvement I see so far is to change it like this:
```
if ft.SendFee.IsNil() || ft.SendFee.IsNegative() || ft.Issuer == fromAddress.String() && ft.Issuer == toAddress.String() {
  return nil
}
```
it looks more natural in this way but ideally would be to centralize this logic in a single place
any ideas ?
</blockquote></details>

Both ways are equally bad :-) The thing that these are business conditions and they must be somewhere in the code. IMO we shouldn't try to unify those conditions between send fee and burn rate because they are identical only accidentally and eventually condition set for one feature may be modified and it should not affect the other one.
___
*[`x/asset/ft/types/ft_test.go` line 221 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkV8wm2zq8Agt29YjP:-NJncWI70gbQGC1d1EXB:bqla4jx) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/types/ft_test.go#L221)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I suggest to test `validateRate` only to avoid duplication
or you can call both methods one by one under a single Test function
</blockquote></details>

see my other comment

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: 27 of 28 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/ft/types/ft.go` line 132 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkUvTy5HyLF-ZmOwdH:-NJnkq5j9brFYU7y9WfC:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/types/ft.go#L132)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can we move this 4 to constant ?
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: 27 of 28 files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: all files reviewed, 5 unresolved discussions (waiting on @ysv)

___
*[`integration-tests/assetft/burn_rate.go` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkR9vT2P5qXkiynmg3:-NJo86N81QfLoXvC8L0V:b-e8513m) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/integration-tests/assetft/burn_rate.go#L52)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

the thing is that in task description we decided to name it `send_commission_rate`.
I at like word rate there

If you insist we might rename it. 

But lets discuss this on call before doing any renaming 


</blockquote></details>

good point

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum)

___
*[`x/asset/ft/keeper/burn_rate_and_send_fee_test.go` line 19 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkSZXy0290brG0NFbG:-NJoFsb58aZDCjrzzE9F:b-c3ncpn) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/keeper/burn_rate_and_send_fee_test.go#L19)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Because I prefer to test features, not internal function. Internal function might change but feature should work the same way. Also, one feature might be removed or modified and that should not affect the test of the other one.
</blockquote></details>

well yes that is also true
but even linter tells that logic is duplicated
maybe we can at least share test cases between these 2 functions ?

Or have a single test running both cases
___
*[`x/asset/ft/keeper/keeper.go` line 74 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkU18a1mMgC9G9aj_n:-NJoVAdC6g8NBbeNRGuS:b-9kg4ds) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/keeper/keeper.go#L74)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Both ways are equally bad :-) The thing that these are business conditions and they must be somewhere in the code. IMO we shouldn't try to unify those conditions between send fee and burn rate because they are identical only accidentally and eventually condition set for one feature may be modified and it should not affect the other one.
</blockquote></details>

okay I mostly agree
IMO option with `||` or is easier to read mentally 
But if you don't think so lets keep `&&` 

I'm neutral on this one
___
*[`x/asset/ft/types/ft_test.go` line 221 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkV8wm2zq8Agt29YjP:-NJoWg8f2ocnPWq1rSCc:b-h20kjl) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/types/ft_test.go#L221)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

see my other comment
</blockquote></details>

same as in other test I see 2 options:
1. share test cases between these 2 funcs
2. have a single Test func testing both

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: 9 of 30 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/assetft/burn_rate.go` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkR9vT2P5qXkiynmg3:-NJouCRy0PytBojc3ToC:bb7zzgx) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/integration-tests/assetft/burn_rate.go#L52)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

good point 
</blockquote></details>

yea, `send fee` is much simpler and equally descriptive term 
___
*[`x/asset/ft/keeper/burn_rate_and_send_fee_test.go` line 19 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkSZXy0290brG0NFbG:-NJotusq9JV9Ryevy87j:b-tk31uq) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/keeper/burn_rate_and_send_fee_test.go#L19)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

well yes that is also true
but even linter tells that logic is duplicated
maybe we can at least share test cases between these 2 functions ?

Or have a single test running both cases

</blockquote></details>

Doing this does not make sense IMO, burn test cases have `burnAmount` while send fee test cases have `sendFee` amount. I really don't see a reason to unify them in any way just because some concepts are similar.

**Review by miladz68 — APPROVED** [review]
> Reviewed 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: 23 of 51 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`x/asset/ft/keeper/burn_rate_and_send_fee_test.go` line 19 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkSZXy0290brG0NFbG:-NJu3ghBAjHWHm6Ja70n:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/x/asset/ft/keeper/burn_rate_and_send_fee_test.go#L19)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Doing this does not make sense IMO, burn test cases have `burnAmount` while send fee test cases have `sendFee` amount. I really don't see a reason to unify them in any way just because some concepts are similar.
</blockquote></details>

ok
___
*[`integration-tests/assetft/burn_rate.go` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkR9vT2P5qXkiynmg3:-NJu5DW02QYHav60d80s:b-dpw2gy) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/integration-tests/assetft/burn_rate.go#L52)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

yea, `send fee` is much simpler and equally descriptive term 
</blockquote></details>

as discussed lets rename to send_commission_rate

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: 6 of 51 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/assetft/burn_rate.go` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJkR9vT2P5qXkiynmg3:-NJugs9q0XoYbQUSG1aj:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fc6e6bb62ca3fc7e598979e88a1a679631cbce0/integration-tests/assetft/burn_rate.go#L52)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

as discussed lets rename to send_commission_rate
</blockquote></details>

Done.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 4 of 21 files at r3, 22 of 28 files at r4, 1 of 1 files at r5, 22 of 22 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 21 files at r3, 22 of 28 files at r4, 1 of 1 files at r5, 22 of 22 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`x/asset/ft/keeper/burn_rate_and_send_fee_test.go` line 136 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJzDkTZ-B5caayURBXj:-NJzDkTZ-B5caayURBXk:b3rx2qa) ([raw file](https://github.com/coreumfoundation/coreum/blob/a90a42f4db8390ad5be863f96b4b0ead598da4dc/x/asset/ft/keeper/burn_rate_and_send_fee_test.go#L136)):*
> ```Go
> 			rate:               "0.1234",
> 			sendAmount:         97,
> 			sendCommissionRate: 12,
> ```

minor:
Here rate is not needed in the name. Should be: `sendCommission` / `sendCommissionAmount`
___
*[`x/asset/ft/keeper/issue.go` line 23 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJzE4WVBxqDBByyfiX6:-NJzE4WVBxqDBByyfiX7:bp5jyjy) ([raw file](https://github.com/coreumfoundation/coreum/blob/a90a42f4db8390ad5be863f96b4b0ead598da4dc/x/asset/ft/keeper/issue.go#L23)):*
> ```Go
> 		return "", err
> 	}
> 	if err := types.ValidateSendCommissionFee(settings.SendCommissionRate); err != nil {
> ```

ValidateSendCommissionRate
___
*[`x/asset/ft/keeper/keeper.go` line 75 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJzF9js8rM8m9IGibPE:-NJzF9js8rM8m9IGibPF:b-bmpiao) ([raw file](https://github.com/coreumfoundation/coreum/blob/a90a42f4db8390ad5be863f96b4b0ead598da4dc/x/asset/ft/keeper/keeper.go#L75)):*
> ```Go
> func (k Keeper) applySendCommissionRate(ctx sdk.Context, ft types.FTDefinition, fromAddress, toAddress sdk.AccAddress, coin sdk.Coin) error {
> 	if !ft.SendCommissionRate.IsNil() && ft.SendCommissionRate.IsPositive() && ft.Issuer != fromAddress.String() && ft.Issuer != toAddress.String() {
> 		sendCommissionRate := ft.CalculateSendCommissionRateAmountAmount(coin)
> ```

sendCommissionRate -> sendCommission/sendCommissionAmount
___
*[`x/asset/ft/types/msgs.go` line 36 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJzEHMX55TecHUBeS3R:-NJzEHMX55TecHUBeS3S:bp5jyjy) ([raw file](https://github.com/coreumfoundation/coreum/blob/a90a42f4db8390ad5be863f96b4b0ead598da4dc/x/asset/ft/types/msgs.go#L36)):*
> ```Go
> 		return err
> 	}
> ```

ValidateSendCommissionRate

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: 45 of 51 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/ft/keeper/issue.go` line 23 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJzE4WVBxqDBByyfiX6:-NKIcuRfAp1dNfzuQ4PX:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/d10db909d2dfc4ff3f91854fa4e53cde70eed743/x/asset/ft/keeper/issue.go#L23)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ValidateSendCommissionRate
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper.go` line 75 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJzF9js8rM8m9IGibPE:-NKId7wmA42dJgZhU8-M:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/d10db909d2dfc4ff3f91854fa4e53cde70eed743/x/asset/ft/keeper/keeper.go#L75)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

sendCommissionRate -> sendCommission/sendCommissionAmount
</blockquote></details>

Done.
___
*[`x/asset/ft/types/msgs.go` line 36 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/302#-NJzEHMX55TecHUBeS3R:-NKIdEvE8mLRf3pQO9IL:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/d10db909d2dfc4ff3f91854fa4e53cde70eed743/x/asset/ft/types/msgs.go#L36)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ValidateSendCommissionRate
</blockquote></details>

Done.

**Review by ysv — DISMISSED** [review]
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 23 of 28 files at r4, 1 of 1 files at r5, 16 of 22 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/302)* status: 48 of 51 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Pull request merged**
