### PR TITLE
Introduce Makefile

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`Makefile` line 20 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-NwjZseQCWA5iBkeSGJS:-NwjZseQCWA5iBkeSGJT:b56k5di) ([raw file](https://github.com/CoreumFoundation/coreum/blob/95b34fe6d1bb2abf15e335fe1a130baf314f8ae9/Makefile#L20)):*
> ```Makefile
> dependencies:
> 	../crust/bin/crust download
> 	../faucet/bin/faucet-builder download
> ```

coreum should not try to build faucet or crust
___
*[`.github/workflows/ci.yml` line 35 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-Nwj_33B1Hebs1ZpOKoh:-Nwj_33B1Hebs1ZpOKoi:bgrtua1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/95b34fe6d1bb2abf15e335fe1a130baf314f8ae9/.github/workflows/ci.yml#L35)):*
> ```YAML
>             codecov-name: coreum
>           - ci_step: "integration tests coreum-modules"
>             command: make integration-tests-modules
> ```

creating and running the env should be done by crust, running the integration tests should be done by the make file.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: all files reviewed, 3 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`Makefile` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-Nwmnzf6DJ2AdumcxVkI:-Nwmnzf6DJ2AdumcxVkJ:bgc5hb9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/95b34fe6d1bb2abf15e335fe1a130baf314f8ae9/Makefile#L1)):*
> ```Makefile
> .PHONY: lint
> ```

Add `wasm` and `generate` as well please, since it's required for the development.
___
*[`Makefile` line 20 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-NwjZseQCWA5iBkeSGJS:-Nwmn-W49BB0ntBROo7D:bok4yji) ([raw file](https://github.com/CoreumFoundation/coreum/blob/95b34fe6d1bb2abf15e335fe1a130baf314f8ae9/Makefile#L20)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

coreum should not try to build faucet or crust
</blockquote></details>

IMO
* faucet tests should be called in the faucet only
* Ideally we should use the crust binary or import a lib to run the znet (discussable), but not in scope of the current PR.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: all files reviewed, 4 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`Makefile` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-NwmoIoj0BixbcdqZm4_:-NwmoIoj0BixbcdqZm4a:b-ocejj0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/95b34fe6d1bb2abf15e335fe1a130baf314f8ae9/Makefile#L1)):*
> ```Makefile
> .PHONY: lint
> ```

If you have a reference to `curst` or `faucet` you should validate that the repo exists under that path.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: all files reviewed, 5 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`Makefile` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-Nwn4p1fBQScal8zKNQy:-Nwn4p1fBQScal8zKNQz:bhdoif3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/95b34fe6d1bb2abf15e335fe1a130baf314f8ae9/Makefile#L1)):*
> ```Makefile
> .PHONY: lint
> ```

What about the `release` ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: all files reviewed, 5 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`Makefile` line 20 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-NwjZseQCWA5iBkeSGJS:-NwnACMK1-Yp9lGfHyMO:b9sn434) ([raw file](https://github.com/CoreumFoundation/coreum/blob/95b34fe6d1bb2abf15e335fe1a130baf314f8ae9/Makefile#L20)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO
* faucet tests should be called in the faucet only
* Ideally we should use the crust binary or import a lib to run the znet (discussable), but not in scope of the current PR.
</blockquote></details>

To build the correct go cache in CI I need to download all the dependencies/ But IMO we should remove that cache shit completely from the CI, it creates more problems than it solves.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: all files reviewed, 5 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`Makefile` line 20 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-NwjZseQCWA5iBkeSGJS:-NwnpD-2A5e6z6K5Zc94:b-ldxrbg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/95b34fe6d1bb2abf15e335fe1a130baf314f8ae9/Makefile#L20)):*
> faucet tests should be called in the faucet only

@ysv what do you think? We agreed that it is should be done in faucet repo only

> Ideally we should use the crust binary or import a lib to run the znet (discussable), but not in scope of the current PR.

We will do it in next iteration
___
*[`.github/workflows/ci.yml` line 35 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-Nwj_33B1Hebs1ZpOKoh:-NwntEmM2QYShkkxTvyC:b-24rs7a) ([raw file](https://github.com/CoreumFoundation/coreum/blob/95b34fe6d1bb2abf15e335fe1a130baf314f8ae9/.github/workflows/ci.yml#L35)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

creating and running the env should be done by crust, running the integration tests should be done by the make file.
</blockquote></details>

we agreed to keep it like it is

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`Makefile` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-Nwmnzf6DJ2AdumcxVkI:-Nwnx1DV4ezHrZN5Ns81:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/95b34fe6d1bb2abf15e335fe1a130baf314f8ae9/Makefile#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Add `wasm` and `generate` as well please, since it's required for the development.
</blockquote></details>

Done.
___
*[`Makefile` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-Nwn4p1fBQScal8zKNQy:-Nwnx1XE5icEOuIFDfEs:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/95b34fe6d1bb2abf15e335fe1a130baf314f8ae9/Makefile#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about the `release` ?
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`Makefile` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-NwmoIoj0BixbcdqZm4_:-Nwo0Bgg6VjuZStl7A7a:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/95b34fe6d1bb2abf15e335fe1a130baf314f8ae9/Makefile#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

If you have a reference to `curst` or `faucet` you should validate that the repo exists under that path.
</blockquote></details>

Done.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`Makefile` line 20 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-NwjZseQCWA5iBkeSGJS:-NwoUhii0StSiUmT5OpK:byz92am) ([raw file](https://github.com/CoreumFoundation/coreum/blob/95b34fe6d1bb2abf15e335fe1a130baf314f8ae9/Makefile#L20)):*
> what do you think? We agreed that it is should be done in faucet repo only

I'm ok
___
*[`Makefile` line 46 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-NwoUkR889u_tzGIm0Om:-NwoUkR889u_tzGIm0On:b-a0rw7x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d348798beadda7d342e0c77ed6a834438bc7c1cb/Makefile#L46)):*
> ```Makefile
> 	../crust/bin/crust znet stop
> 	../crust/bin/crust znet coverage-convert
> 	../crust/bin/crust znet remove
> ```

I don't like this repetition of `./crust/bin/crust` & `./bin/coreum-builder ` a lot of times.
Can we move it to some variable or func ?

**Review by miladz68 — COMMENTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @wojtek-coreum)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @wojtek-coreum)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: all files reviewed, 3 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`Makefile` line 3 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-NwtsjHH8CkVbNoBgrD6:-NwtsjHH8CkVbNoBgrD7:bdp38sn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d348798beadda7d342e0c77ed6a834438bc7c1cb/Makefile#L3)):*
> ```Makefile
> .PHONY: lint
> lint:
> 	./bin/coreum-builder lint
> ```

but how to build coreum-builder itself using Make ?

Also would be nice to make sure that coreum-builder is up to date before running any of commands

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: all files reviewed, 3 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`Makefile` line 3 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/816#-NwtsjHH8CkVbNoBgrD6:-NwtuTwP-Fk4HVw6sPot:b-tqwr3p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d348798beadda7d342e0c77ed6a834438bc7c1cb/Makefile#L3)):*
> Also would be nice to make sure that coreum-builder is up to date before running any of commands

not sure if this should be done in makefile or inside coreum-builder itself

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/816)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

**Pull request merged**
