### PR TITLE
Implement the NFT asset burning

### PR DESCRIPTION
**Pull request by dzmitryhil**
* Keep Burning + features
* CLI burning tx/query + features
* Deterministic gas
* Integration tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: 0 of 35 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKCcIUm-Qgb3AJKeaB9:-NKCcIUm-Qgb3AJKeaBA:bjn8p44) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/go.mod#L34)):*
> ```XML
> 	github.com/tendermint/tm-db v0.6.7
> 	go.uber.org/zap v1.23.0
> 	google.golang.org/genproto v0.0.0-20221207170731-23e4bf6bdc37
> ```

I intentionally left the updated dependencies by the ignite, since they don't break the code and even newer. I hope it will help not to revert the changes in `go.mod` after the code regeneration.

**Review by miladz68 — APPROVED** [review]
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 9 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil)

___
*[`go.mod` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKCcIUm-Qgb3AJKeaB9:-NKxg0OoEWcIxF613_C3:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/go.mod#L34)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I intentionally left the updated dependencies by the ignite, since they don't break the code and even newer. I hope it will help not to revert the changes in `go.mod` after the code regeneration.
</blockquote></details>

ok
___
*[`proto/coreum/asset/nft/v1/nft.proto` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKxivpgEg6tftso4YXa:-NKxivpgEg6tftso4YXb:b-rrafup) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/proto/coreum/asset/nft/v1/nft.proto#L15)):*
> ```protobuf
> 
> // NFTClassDefinition defines the non-fungible token class settings to store.
> message NFTClassDefinition {
> ```

according to our last discusison it should be `ClassDefinition` ?
___
*[`proto/coreum/asset/nft/v1/nft.proto` line 20 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKxgtIc-BgmxLDOlgn7:-NKxgtIc-BgmxLDOlgn8:b-ptnrzu) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/proto/coreum/asset/nft/v1/nft.proto#L20)):*
> ```protobuf
> }
> 
> // NFTClass is a full representation of the non-fungible token class.
> ```

should we mention that it is a copy of original NFT module + a few fields on top ?
___
*[`proto/coreum/asset/nft/v1/nft.proto` line 21 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKxkqQxC1Cbkoo9Z77a:-NKxkqQy9fo1TaDuos4R:b-3e4f5a) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/proto/coreum/asset/nft/v1/nft.proto#L21)):*
> ```protobuf
> 
> // NFTClass is a full representation of the non-fungible token class.
> message NFTClass {
> ```

according to our last discusison it should be `Class` ?
___
*[`x/asset/nft/client/cli/tx.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKxkKGfCbsJLirgS0kc:-NKxkKGfCbsJLirgS0kd:b-8fakio) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/x/asset/nft/client/cli/tx.go#L41)):*
> ```Go
> // CmdTxIssueClass returns IssueClass cobra command.
> func CmdTxIssueClass() *cobra.Command {
> 	allowedFeatures := make([]string, 0, len(types.ClassFeature_name)) //nolint:nosnakecase // generated variable
> ```

`//nolint:nosnakecase` ignore in a whole function ?
___
*[`x/asset/nft/client/cli/tx.go` line 161 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKxkZH9Bbdy4725GK-x:-NKxkZH9Bbdy4725GK-y:b-t2m3yq) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/x/asset/nft/client/cli/tx.go#L161)):*
> ```Go
> 
> Example:
> $ %s tx asset-nft mint abc-devcore1tr3w86yesnj8f290l6ve02cqhae8x4ze0nk0a8 id1 --from [sender]
> ```

`tx asset-nft burn` ?
___
*[`x/asset/nft/keeper/keeper.go` line 131 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKxl7Qt-fwb2XclknDg:-NKxl7Qt-fwb2XclknDh:ba28ekw) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/x/asset/nft/keeper/keeper.go#L131)):*
> ```Go
> 	}
> 
> 	if k.nftKeeper.GetOwner(ctx, classID, id).String() != owner.String() {
> ```

on the last call with Reza we decided to change it to anyone who owns NFT if burnable is enabled
___
*[`x/asset/nft/keeper/keeper.go` line 151 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKxlJ8k3jVLlhCZWeAX:-NKxlJ8k3jVLlhCZWeAY:b-7f98p8) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/x/asset/nft/keeper/keeper.go#L151)):*
> ```Go
> 	}
> 
> 	class, _ := k.nftKeeper.GetClass(ctx, classID)
> ```

error ignored ?
___
*[`x/asset/nft/keeper/keeper_test.go` line 164 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKzPYJGBhhbkCrhAUWN:-NKzPYJGBhhbkCrhAUWO:b-h79c6o) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/x/asset/nft/keeper/keeper_test.go#L164)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// try to burn none existing nft
> ```

minor: none -> non

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: 6 of 60 files reviewed, 7 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/nft.proto` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKxivpgEg6tftso4YXa:-NL0s8Yb5AoPqfxP3zqU:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/proto/coreum/asset/nft/v1/nft.proto#L15)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

according to our last discusison it should be `ClassDefinition` ?
</blockquote></details>

Done.



_Code quote:_
```protobuf
message NFTClassDefinition {
```
___
*[`proto/coreum/asset/nft/v1/nft.proto` line 20 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKxgtIc-BgmxLDOlgn7:-NL0sAY07g-6SZoKYg5U:b-a4il1b) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/proto/coreum/asset/nft/v1/nft.proto#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should we mention that it is a copy of original NFT module + a few fields on top ?
</blockquote></details>

Nope. That's our type so we don't need to add any reference.
___
*[`proto/coreum/asset/nft/v1/nft.proto` line 21 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKxkqQxC1Cbkoo9Z77a:-NL0sFgZ0cnZmvkmm6NK:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/proto/coreum/asset/nft/v1/nft.proto#L21)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

according to our last discusison it should be `Class` ?
</blockquote></details>

Done.
___
*[`x/asset/nft/client/cli/tx.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKxkKGfCbsJLirgS0kc:-NL0sQCc3PoA25mJebXk:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/x/asset/nft/client/cli/tx.go#L41)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`//nolint:nosnakecase` ignore in a whole function ?
</blockquote></details>

Done.



_Code quote:_
```Go
// CmdTxIssueClass returns IssueClass cobra command.
```
___
*[`x/asset/nft/client/cli/tx.go` line 161 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKxkZH9Bbdy4725GK-x:-NL0szyzBC66Ahp4euTW:b-bu91xm) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/x/asset/nft/client/cli/tx.go#L161)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`tx asset-nft burn` ?
</blockquote></details>

Updated
___
*[`x/asset/nft/keeper/keeper.go` line 131 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKxl7Qt-fwb2XclknDg:-NL0tQHM630Zdwpq0pos:b-ch2jel) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/x/asset/nft/keeper/keeper.go#L131)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

on the last call with Reza we decided to change it to anyone who owns NFT if burnable is enabled
</blockquote></details>

Updated the logic:

* If the burning is enabled owner can burn it's NFTs
* If the burning is disabled only the issuer can burn  it's NFTs



_Code quote:_
```Go
nft with classID:%s and ID:%s no
```
___
*[`x/asset/nft/keeper/keeper.go` line 151 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKxlJ8k3jVLlhCZWeAX:-NL1-dM45rpU5fPswqZ0:b-2bu1ep) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/x/asset/nft/keeper/keeper.go#L151)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

error ignored ?
</blockquote></details>

it's not an error. Is flag (bool). But I've added that additional check as well.
___
*[`x/asset/nft/keeper/keeper_test.go` line 164 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NKzPYJGBhhbkCrhAUWN:-NL11Y_V7nGKKF_Wgxci:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/72d137b75fdd170dbcc612db60d6f7c8baf146b0/x/asset/nft/keeper/keeper_test.go#L164)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: none -> non
</blockquote></details>

Done.

**Review by ysv — DISMISSED** [review]
> Reviewed 10 of 41 files at r2, 44 of 44 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

___
*[`x/asset/nft/types/token.go` line 124 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NL74pld4vc5ibM5xlZw:-NL74pld4vc5ibM5xlZx:bfrnu4) ([raw file](https://github.com/coreumfoundation/coreum/blob/3ea2ca652230365130fc45dae8e419ae2158d35c/x/asset/nft/types/token.go#L124)):*
> ```Go
> 
> 	// non-issuer can use only burning and only if it is enabled
> 	if featureEnabled && feature == ClassFeature_burn {
> ```

these could be simplified to just:

```
return featureEnabled && feature == ClassFeature_burn
```



_Code quote:_
```Go
	// non-issuer can use only burning and only if it is enabled
	if featureEnabled && feature == ClassFeature_burn {
		return true
	}

	return false
```

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: 49 of 61 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/types/token.go` line 124 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NL74pld4vc5ibM5xlZw:-NLKVKey3tkXKz9t1Slc:bxu9frk) ([raw file](https://github.com/coreumfoundation/coreum/blob/3ea2ca652230365130fc45dae8e419ae2158d35c/x/asset/nft/types/token.go#L124)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

these could be simplified to just:

```
return featureEnabled && feature == ClassFeature_burn
```
</blockquote></details>

Updated. Also addred the handling of the `ErrFeatureDisabled`.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: 49 of 61 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`proto/coreum/asset/nft/v1/nft.proto` line 12 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NLKVXu19EEmxtk5f22z:-NLKVXu19EEmxtk5f23-:b-xmaxdu) ([raw file](https://github.com/coreumfoundation/coreum/blob/08f80d8d5fba96d05ea37f3016026f55bca7e301/proto/coreum/asset/nft/v1/nft.proto#L12)):*
> ```protobuf
> enum ClassFeature {
>   burning = 0;
>   freezing = 1;
> ```

I needed one more feture to complete the `CheckFeatureAllowed` test, that's why added all with the order we aligin on, order not to fix it later. :-)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

___
*[`proto/coreum/asset/nft/v1/nft.proto` line 12 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NLKVXu19EEmxtk5f22z:-NLKvzIP6tQC_vo5T0kk:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/08f80d8d5fba96d05ea37f3016026f55bca7e301/proto/coreum/asset/nft/v1/nft.proto#L12)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I needed one more feture to complete the `CheckFeatureAllowed` test, that's why added all with the order we aligin on, order not to fix it later. :-) 
</blockquote></details>

ok
___
*[`x/asset/nft/types/errors.go` line 15 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NLKwMbV81vJCvv_H_Tb:-NLKwMbV81vJCvv_H_Tc:b9ewoqi) ([raw file](https://github.com/coreumfoundation/coreum/blob/08f80d8d5fba96d05ea37f3016026f55bca7e301/x/asset/nft/types/errors.go#L15)):*
> ```Go
> 	ErrClassNotFound = sdkerrors.Register(ModuleName, 3, "non-fungible token class not found")
> 	// ErrFeatureDisabled is returned when used disabled feature.
> 	ErrFeatureDisabled = sdkerrors.Register(ModuleName, 4, "invalid input")
> ```

fix message "invalid input"

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

___
*[`x/asset/nft/types/errors.go` line 15 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NLKwMbV81vJCvv_H_Tb:-NLL7cEh6QtcPPmLm4bc:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/08f80d8d5fba96d05ea37f3016026f55bca7e301/x/asset/nft/types/errors.go#L15)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

fix message "invalid input"
</blockquote></details>

Done.



_Code quote:_
```Go
ErrFeatureDisabled = sdkerrors.Register(ModuleName, 4, "invalid input")
```

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 41 files at r2, 37 of 44 files at r3, 1 of 3 files at r4, 12 of 12 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/keeper_test.go` line 197 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NLKx9O39ApHECYoH1ki:-NLKx9O39ApHECYoH1kj:b-xhon6t) ([raw file](https://github.com/coreumfoundation/coreum/blob/08f80d8d5fba96d05ea37f3016026f55bca7e301/x/asset/nft/keeper/keeper_test.go#L197)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// try to burn the nft one more time
> ```

one missing case, try to burn from non-issuer, owner account should work.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/keeper_test.go` line 197 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NLKx9O39ApHECYoH1ki:-NLLKQAo4-Wvgg_NFPmO:bn9n0s2) ([raw file](https://github.com/coreumfoundation/coreum/blob/08f80d8d5fba96d05ea37f3016026f55bca7e301/x/asset/nft/keeper/keeper_test.go#L197)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

one missing case, try to burn from non-issuer, owner account should work. 
</blockquote></details>

I do it in the test.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @silverspase)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

___
*[`x/asset/nft/keeper/keeper_test.go` line 197 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NLKx9O39ApHECYoH1ki:-NLMK_a89Z_9MLYk-GmV:b-thlq8g) ([raw file](https://github.com/coreumfoundation/coreum/blob/08f80d8d5fba96d05ea37f3016026f55bca7e301/x/asset/nft/keeper/keeper_test.go#L197)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I do it in the test. 
</blockquote></details>

i see one burnable nft getting minted, and its owner is the issuer. Maybe I am missing it ?

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

___
*[`x/asset/nft/keeper/keeper_test.go` line 197 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NLKx9O39ApHECYoH1ki:-NLMSdAW6YLKxu4wwKX5:b-52507o) ([raw file](https://github.com/coreumfoundation/coreum/blob/08f80d8d5fba96d05ea37f3016026f55bca7e301/x/asset/nft/keeper/keeper_test.go#L197)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

```
// try to burn from not owner account
err = assetNFTKeeper.Burn(ctx, recipient, classID, nftID)
requireT.ErrorIs(sdkerrors.ErrUnauthorized, err)
``
```

</blockquote></details>

I mean try to burn from an account which is the owner but not the issuer. when the flag is enabled this should work fine, but when the flag is disabled this should fail. I guess you have tests for the second case but not for the first case.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: 60 of 61 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/keeper_test.go` line 197 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/314#-NLKx9O39ApHECYoH1ki:-NLPN3Xb9x-0yH1oC2Og:b-hzczr8) ([raw file](https://github.com/coreumfoundation/coreum/blob/08f80d8d5fba96d05ea37f3016026f55bca7e301/x/asset/nft/keeper/keeper_test.go#L197)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I mean try to burn from an account which is the owner but not the issuer. when the flag is enabled this should work fine, but when the flag is disabled this should fail. I guess you have tests for the second case but not for the first case. 
</blockquote></details>

Got you now. Added.



_Code quote:_
```Go
// try to burn the nft one more time
```

**Review by miladz68 — DISMISSED** [review]
> Reviewed 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 9 of 10 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/314)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
