### PR TITLE
Set LedgerAppName to Coreum inside CLI commands

### PR DESCRIPTION
**Pull request by ysv**
# Description

In this PR I set keyring option `LedgerAppName` to `Coreum`. 

I thought that this option influences which app is chosen by ledger but it works differently. Actually ledger-go doesn't validate which app is used. Which means that you can sign Coreum tx with any Cosmos app as long as HD path prefix matches.

As result this option just customizes error message which is triggered when no app is opened: 
`Error executing cmd, err: please open the Coreum app on the Ledger device - error: [APDU_CODE_DATA_INVALID]`

cosmos/cosmos-sdk@v0.47.5/crypto/ledger/ledger_secp256k1.go:301

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/665)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/665)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu, @miladz68, and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/665)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu and @miladz68)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/665)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/665)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu)

**Pull request merged**
