### PR TITLE
Use frozen coins for bank keeper SpendableBalance.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

The PR contains the SpendableBalance bank keeper wrapping to substitute the frozen amount from the available spendable amount. In case the denom is globally frozen the total balance is used as frozen. Also, that change is applied to the asset ft balance query.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/683)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/683)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 429 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/683#-Nh_mwEl95sJuenw_yah:-Nh_mwEl95sJuenw_yai:b-9wnf93) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acc7151b7c125208adef8bf0f7368a31f0b8565f/integration-tests/modules/assetft_test.go#L429)):*
> ```Go
> }
> 
> func TestSpendableBalanceQuery(t *testing.T) {
> ```

Please add a similar test for native (non-FT) token (udevcore - without freezing obviously). It should work now but you never know what happens in the future.
___
*[`integration-tests/modules/assetft_test.go` line 491 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/683#-Nh_lQJb18azpUbp4zzI:-Nh_lQJcBsZOAcFafbUN:bqnn4bf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acc7151b7c125208adef8bf0f7368a31f0b8565f/integration-tests/modules/assetft_test.go#L491)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	recipientSpendableBalanceBeforeFreesRes, err := bankClient.SpendableBalanceByDenom(ctx, &banktypes.QuerySpendableBalanceByDenomRequest{
> ```

BeforeFreeze
___
*[`x/wbank/keeper/keeper.go` line 120 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/683#-Nh_mEVR6ZWl46XEHqDT:-Nh_mEVR6ZWl46XEHqDU:b-r8wh51) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acc7151b7c125208adef8bf0f7368a31f0b8565f/x/wbank/keeper/keeper.go#L120)):*
> ```Go
> 	for i := range res.Balances {
> 		spendableCoin := k.getSpendableCoin(sdk.UnwrapSDKContext(ctx), addr, res.Balances[i])
> 		res.Balances[i] = spendableCoin
> ```

Just move `res.Balances[i]` to the line above
___
*[`x/wbank/keeper/keeper_test.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/683#-Nh_nbyi4W987si-H3aj:-Nh_nbyi4W987si-H3ak:b-sz06e8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acc7151b7c125208adef8bf0f7368a31f0b8565f/x/wbank/keeper/keeper_test.go#L32)):*
> ```Go
> 
> 	totalTokens := 10
> 	amountToSemd := sdkmath.NewInt(100)
> ```

amountToSend
___
*[`x/wbank/keeper/keeper_test.go` line 73 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/683#-Nh_nshZBM4vEN9u27gc:-Nh_nshZBM4vEN9u27gd:b-38gfl1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acc7151b7c125208adef8bf0f7368a31f0b8565f/x/wbank/keeper/keeper_test.go#L73)):*
> ```Go
> 	requireT.NoError(err)
> 	requireT.Equal(
> 		balances.AmountOfNoDenomValidation(denom).Sub(coinToFreeze.Amount).String(),
> ```

Why "NoDenomValidation"?

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/683)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil and @miladz68)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/683#-NhaXgWuDINtMRpLT0Mq:-NhaXgWuDINtMRpLT0Mr:b-vhyh08) (no related file):*
Would be nice to have better description to this PR
Because I see that you made some decent improvements but they are not exactly what we had in task 

___

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/683)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil and @miladz68)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/683#-NhaXgWuDINtMRpLT0Mq:-NhaYdkw95xmwrUcg_TS:b-z21yc3) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Would be nice to have better description to this PR
Because I see that you made some decent improvements but they are not exactly what we had in task
</blockquote></details>

This is also important for better reviews in the future

___

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/683)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/683)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/683)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/683)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
