### PR TITLE
Take data size into account when computing deterministic gas for NFT messages

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

If large data chunk is provided constant deterministic gas might be exceeded. To fix this, we compute deterministic gas based on the data length.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/718)

### CODE REVIEW

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/718)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

___
*[`x/deterministicgas/config.go` line 364 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/718#-NjMIiiS5OwdT6Z_mCVm:-NjMIiiS5OwdT6Z_mCVn:b-w9khdm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e1ce0923abebd809e04320ace1f063c35c11fe4c/x/deterministicgas/config.go#L364)):*
> ```Go
> 		var dataLen int
> 		switch m := msg.(type) {
> 		case *assetnfttypes.MsgIssueClass:
> ```

What about the URL and URLHash, do we have limits there?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/718)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

___
*[`x/deterministicgas/config.go` line 364 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/718#-NjMIiiS5OwdT6Z_mCVm:-NjMVFdk56MKIzCQqD-H:b-zbpes) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e1ce0923abebd809e04320ace1f063c35c11fe4c/x/deterministicgas/config.go#L364)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about the URL and URLHash, do we have limits there?
</blockquote></details>

max uri length = 256 bytes
max uri hash = 128 bytes

Do we want to add it here?

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/718)* status: 1 of 6 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/718)* status: 1 of 7 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 2 of 4 files at r2, 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/718)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/718#-:-NjqdGyG2oa5LQWTmf-R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/718)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum)

___
*[`x/deterministicgas/config.go` line 41 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/718#-NjqjiWh1c6TTp2r_pb2:-NjqjiWh1c6TTp2r_pb3:b-l1nj0s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9e58e959cdf02690a06064309592936f637acbc1/x/deterministicgas/config.go#L41)):*
> ```Go
> 	BankMultiSendPerOperationsGas = 35000
> 	AuthzExecOverhead             = 1500
> 	NFTMsgIssueClassCost          = 16_000
> ```

```
BankSendPerCoinGas            = 50000
BankMultiSendPerOperationsGas = 35000
```

In these 2 we use `Gas` in the end
I think we should replace Cost -> Gas

Also since it is not full price but also price for bytes should be added on top I would name it smth like. NFTIssueClassBaseGas

```

```
___
*[`x/deterministicgas/config.go` line 377 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/718#-NjqkKG6600GD17SCyH2:-NjqkKG6600GD17SCyH3:behyvgj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9e58e959cdf02690a06064309592936f637acbc1/x/deterministicgas/config.go#L377)):*
> ```Go
> 
> 		gas := uint64(dataLen)*storeConfig.WriteCostPerByte + constGas
> 		if dataLen > 0 {
> ```

Is data stored separately ?
I thought that we write it together with whole NFT so number of writes is not dependent on data presence

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/718)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/deterministicgas/config.go` line 41 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/718#-NjqjiWh1c6TTp2r_pb2:-Njr1vUbCrLHfoieMQtM:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9e58e959cdf02690a06064309592936f637acbc1/x/deterministicgas/config.go#L41)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

```
BankSendPerCoinGas            = 50000
BankMultiSendPerOperationsGas = 35000
```

In these 2 we use `Gas` in the end
I think we should replace Cost -> Gas

Also since it is not full price but also price for bytes should be added on top I would name it smth like. NFTIssueClassBaseGas

```

```
</blockquote></details>

Done.
___
*[`x/deterministicgas/config.go` line 377 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/718#-NjqkKG6600GD17SCyH2:-Njr22GYB9f6gB1ktk3r:b-hdr43y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9e58e959cdf02690a06064309592936f637acbc1/x/deterministicgas/config.go#L377)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Is data stored separately ?
I thought that we write it together with whole NFT so number of writes is not dependent on data presence
</blockquote></details>

good catch, you are right. Done

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/718)* status: all files reviewed, 2 unresolved discussions (waiting on @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/718)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
