### PR TITLE
Add ante handler decorator requiring deterministic gas for defined messages

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/112)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/112)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/112#-N7RMoDL1e66girzNjQm:-N7RMoDS9HnHKvyhR3B5:b-btmdj7) (no related file):*
This PR is related to another one in crust: https://reviewable.io/reviews/coreumfoundation/crust/26

___

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/112)* status: all files reviewed, 1 unresolved discussion (waiting on @oliverasistemas, @xlab, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/112)* status: all files reviewed, 1 unresolved discussion (waiting on @oliverasistemas, @xlab, and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/112)* status: all files reviewed, 1 unresolved discussion (waiting on @oliverasistemas, @xlab, and @ysv)

**Pull request merged**
