### PR TITLE
Complex ft integration tests (phase 2)

### PR DESCRIPTION
**Pull request by pgoos**
This PR implements the following integration test scenarios:
```
// # Mint + Burn rate
// - burn rate should not apply when tokens are received by the issuer because of minting
//
// # Mint + Send commission
// - send commission should not apply when tokens are received by the issuer because of minting
//
// # Burn + Burn rate
// - burn rate should not apply when tokens are burnt
//
// # Burn + Send commission
// - send commission should not apply when tokens are burnt
//
// # Burn + Freeze
// - when someone wants to burn more than is allowed by non-frozen balance tx should fail
//
// # Burn rate + Freeze
// - when burn rate causes a non-frozen balance to be exceeded, tx should fail
//
// # Burn rate + Send Commission + Freeze
// - when there is enough unfrozen coins for the burn rate, but not enough for commission (and vice versa), tx should fail

```

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/418)

### CODE REVIEW

**Review by pgoos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/418)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2015 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPXD-Ut5gouyZjs80iy:-NPYVyno-Qfo2qxvk_Av:b-1fbsfh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1077d32b272c2f45a3c36e6dd751c404f592cc86/integration-tests/modules/assetft_test.go#L2015)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How about merge this test and burning rate? The same comment all tests where you do the same for commission and burn rates.
@miladz68 @ysv @wojtek-coreum what to you think ?
</blockquote></details>

done. Merged burn rate and send commission rate cases on minting/burning scenarios

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/418)* status: all files reviewed, 8 unresolved discussions (waiting on @pgoos, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2015 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPXD-Ut5gouyZjs80iy:-NPacouD1ZOdnAeRbJRg:bmkuefk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1077d32b272c2f45a3c36e6dd751c404f592cc86/integration-tests/modules/assetft_test.go#L2015)):*
<details><summary><i>Previously, pgoos (Piotr Gesicki) wrote…</i></summary><blockquote>

done. Merged burn rate and send commission rate cases on minting/burning scenarios
</blockquote></details>

I am still seeing 2 tests here. 
___
*[`integration-tests/modules/assetft_test.go` line 1960 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPaT8xB2ziKPRINGPXR:-NPaT8xB2ziKPRINGPXS:b-cwvxby) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L1960)):*
> ```Go
> 
> // TestAssetFTBurnRate_OnMinting verifies both burn rate and send commision rate are not applied on received minted tokens
> func TestAssetFTBurnRate_SendCommissionRate_OnMinting(t *testing.T) {
> ```

Maybe `TestAssetFT_RatesAreNotAppliedOnMinting` is a better name ? wdyt ?
___
*[`integration-tests/modules/assetft_test.go` line 2002 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPacWDP2SrUXvxUd7TK:-NPacWDQ79EcOfulB0tO:bk02234) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L2002)):*
> ```Go
> 
> 	requireT.NoError(err)
> 	tokenIssuedEvents, err := event.FindTypedEvents[*assetfttypes.EventIssued](res.Events)
> ```

you don't need to assert this event, we already do it in other test and that is enough. 
___
*[`integration-tests/modules/assetft_test.go` line 2186 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPadfFs7fa8SmzEIB3_:-NPadfFs7fa8SmzEIB3a:b-hky5y6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L2186)):*
> ```Go
> 
> 	requireT.NoError(err)
> 	tokenIssuedEvents, err := event.FindTypedEvents[*assetfttypes.EventIssued](res.Events)
> ```

same comment, asserting event is not needed. 
___
*[`integration-tests/modules/assetft_test.go` line 2194 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPadyTd7-Xmwnm_CbXS:-NPadyTd7-Xmwnm_CbXT:bhmwivh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L2194)):*
> ```Go
> 		FromAddress: issuer.String(),
> 		ToAddress:   recipient.String(),
> 		Amount:      sdk.NewCoins(sdk.NewCoin(denom, sdk.NewInt(500))),
> ```

let's send 550 so after freeze and burn, there is still 50 balance available. 
___
*[`integration-tests/modules/assetft_test.go` line 2287 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPafkGAAMAKZ8URcIra:-NPafkGAAMAKZ8URcIrb:bk84ufk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L2287)):*
> ```Go
> 	)
> 
> 	// Issue an fungible token
> ```

an => a
___
*[`integration-tests/modules/assetft_test.go` line 2386 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPahA6k9Wf8KhnA1dGn:-NPahA6k9Wf8KhnA1dGo:b-nz7i4r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L2386)):*
> ```Go
> 
> // TestAssetFTFreeze_WithBurnRate_WithSendCommissionRate_1 verifies that
> // it is not possible apply a burn rate on sending tokens - outside of freezing limit (when send commission rate value is within limit)
> ```

possible => possible to
___
*[`integration-tests/modules/assetft_test.go` line 2387 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPagN5QA5YiXBWTGsU7:-NPagN5RASMGji7TH0Q6:b5kfngb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L2387)):*
> ```Go
> // TestAssetFTFreeze_WithBurnRate_WithSendCommissionRate_1 verifies that
> // it is not possible apply a burn rate on sending tokens - outside of freezing limit (when send commission rate value is within limit)
> func TestAssetFTFreeze_WithBurnRate_WithSendCommissionRate_1(t *testing.T) {
> ```

this test postfixed with 1 and the next test are exactly the same, the only difference is burn and commision rates. maybe you can merge them into a single table test.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/418)* status: all files reviewed, 10 unresolved discussions (waiting on @pgoos, @silverspase, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2254 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPapv6Y-jgVcyCXLX_w:-NPapv6Y-jgVcyCXLX_x:b9av5ir) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L2254)):*
> ```Go
> }
> 
> // TestAssetFTFreezeAndBurnRate verifies that it is not possible apply a burn rate on sending tokens - outside of freezing limit
> ```

possible **to** apply
___
*[`integration-tests/modules/assetft_test.go` line 2494 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPar10_5wuy4Q-3ZXEt:-NPar10_5wuy4Q-3ZXEu:b-k18b7f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L2494)):*
> ```Go
> 	})
> 
> 	// try send from recipient1 to recipient2. Tx should fail because burn rate value
> ```

try to

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/418)* status: all files reviewed, 11 unresolved discussions (waiting on @pgoos, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPas-n64nKy53-pBqbV:-NPas-n64nKy53-pBqbW:b-xqluf4) (no related file):*
Please remove `Piotr/` from PR title

___

**Review by pgoos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/418)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPas-n64nKy53-pBqbV:-NPbBNue2RsZiIUaAXak:b-896fix) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please remove `Piotr/` from PR title
</blockquote></details>

Done.

___
___
*[`integration-tests/modules/assetft_test.go` line 2015 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPXD-Ut5gouyZjs80iy:-NPbLO1H3xVV-ZXMYbHq:bg8cgs7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1077d32b272c2f45a3c36e6dd751c404f592cc86/integration-tests/modules/assetft_test.go#L2015)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I am still seeing 2 tests here. 
</blockquote></details>

what are you referring to @miladz68 ?
___
*[`integration-tests/modules/assetft_test.go` line 1960 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPaT8xB2ziKPRINGPXR:-NPbBgMW7wsmgTItZgii:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L1960)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Maybe `TestAssetFT_RatesAreNotAppliedOnMinting` is a better name ? wdyt ?
</blockquote></details>

Done.



_Code quote:_
```Go
TestAssetFTBurnRate_SendCommissionRate_OnMinting(
```
___
*[`integration-tests/modules/assetft_test.go` line 2002 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPacWDP2SrUXvxUd7TK:-NPbLHce4kYYJMsgnuRA:brpmqc3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L2002)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you don't need to assert this event, we already do it in other test and that is enough. 
</blockquote></details>

removed.
___
*[`integration-tests/modules/assetft_test.go` line 2186 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPadfFs7fa8SmzEIB3_:-NPbLRVV0IiEFDkz08ex:brpmqc3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L2186)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

same comment, asserting event is not needed. 
</blockquote></details>

removed.
___
*[`integration-tests/modules/assetft_test.go` line 2194 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPadyTd7-Xmwnm_CbXS:-NPbN_ez7MChhaVWgckx:b-dw3uuf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L2194)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's send 550 so after freeze and burn, there is still 50 balance available. 
</blockquote></details>

updated to 550.



_Code quote:_
```Go
TestAssetFTFreezeAndBurn
```
___
*[`integration-tests/modules/assetft_test.go` line 2254 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPapv6Y-jgVcyCXLX_w:-NPbNm3R6RaETfYOXeWz:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L2254)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

possible **to** apply
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetft_test.go` line 2287 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPafkGAAMAKZ8URcIra:-NPbO7Kj-jNgl-IRXw6E:bb7f2mf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L2287)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

an => a
</blockquote></details>

done
___
*[`integration-tests/modules/assetft_test.go` line 2386 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPahA6k9Wf8KhnA1dGn:-NPbO9rD1NJX3pBB1bS0:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L2386)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

possible => possible to
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetft_test.go` line 2494 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/418#-NPar10_5wuy4Q-3ZXEt:-NPbOzij0-vlx8yBTok1:bb7f2mf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed64886234381b6703bdf031967d1ce53cafa40e/integration-tests/modules/assetft_test.go#L2494)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

try to
</blockquote></details>

done

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/418)* status: all files reviewed, 5 unresolved discussions (waiting on @pgoos, @silverspase, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/418)* status: all files reviewed, 4 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/418)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/418)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
