### PR TITLE
Made genesis gov module params configurable

### PR DESCRIPTION
**Pull request by begmaroman**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/164)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/164)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`app/network.go` line 417 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/164#-NBSUSdyBQPsQCr4ZPWl:-NBSUSdyBQPsQCr4ZPWm:b-feqxjn) ([raw file](https://github.com/coreumfoundation/coreum/blob/86343b6b152ae1a123470f90497b768c4e9bd418/app/network.go#L417)):*
> ```Go
> 		TokenSymbol:              n.tokenSymbol,
> 		FeeModelParams:           n.FeeModel().Params(),
> 		ProposalMinDepositAmount: n.gov.ProposalConfig.MinDepositAmount,
> ```

please create one field for entire `n.gov`
___
*[`integration-tests/testing/network.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/164#-NBSUi4V4kWQiPGuq53i:-NBSUi4V4kWQiPGuq53j:bg5w5eg) ([raw file](https://github.com/coreumfoundation/coreum/blob/86343b6b152ae1a123470f90497b768c4e9bd418/integration-tests/testing/network.go#L14)):*
> ```Go
> const (
> 	// MinDepositAmount is the minimum proposal deposit amount to be collected in order to activate it.
> 	MinDepositAmount = 1000
> ```

you don't need to export these constants. In test you should access values from network config

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/164)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/testing/network.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/164#-NBSUi4V4kWQiPGuq53i:-NBSWJ48AMSrcxKajTC4:b-2q4og4) ([raw file](https://github.com/coreumfoundation/coreum/blob/86343b6b152ae1a123470f90497b768c4e9bd418/integration-tests/testing/network.go#L14)):*
<details><summary><i>Previously, begmaroman (Roman Behma) wrote…</i></summary><blockquote>

done
</blockquote></details>

I meant all the constants here

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/164)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @miladz68)

**Review by begmaroman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/164)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/testing/network.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/164#-NBSUi4V4kWQiPGuq53i:-NBSWhjrBby3oNg1Y-9Z:b-9w9dmq) ([raw file](https://github.com/coreumfoundation/coreum/blob/86343b6b152ae1a123470f90497b768c4e9bd418/integration-tests/testing/network.go#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I meant all the constants here
</blockquote></details>

Do you think it looks better: "(time.Second / 2).String()"? I would prefer to keep these two timing-related values in the constants.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/164)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`integration-tests/testing/network.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/164#-NBSUi4V4kWQiPGuq53i:-NBSa0y24-5vcsaptqE1:b-npoo9v) ([raw file](https://github.com/coreumfoundation/coreum/blob/86343b6b152ae1a123470f90497b768c4e9bd418/integration-tests/testing/network.go#L14)):*
<details><summary><i>Previously, begmaroman (Roman Behma) wrote…</i></summary><blockquote>

Do you think it looks better: "(time.Second / 2).String()"? I would prefer to keep these two timing-related values in the constants. 
</blockquote></details>

first of all you have `500 * time.Millisecond`
then I'm not saying that you should remove constants, keep them if you find them useful, just don't export them

**Review by begmaroman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/164)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/testing/network.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/164#-NBSUi4V4kWQiPGuq53i:-NBWUuCF9CMm5MBn8UIp:b-15gcp5) ([raw file](https://github.com/coreumfoundation/coreum/blob/86343b6b152ae1a123470f90497b768c4e9bd418/integration-tests/testing/network.go#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

first of all you have `500 * time.Millisecond`
then I'm not saying that you should remove constants, keep them if you find them useful, just don't export them
</blockquote></details>

What are the procs of using 500 * time.Millisecond? It completely does not matter IMO.
Made them private.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/164)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/164)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/164)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/164)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

___
*[`integration-tests/testing/network.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/164#-NBSUi4V4kWQiPGuq53i:-NBX7IDkE5gqNmvU2ldz:blhw7rt) ([raw file](https://github.com/coreumfoundation/coreum/blob/86343b6b152ae1a123470f90497b768c4e9bd418/integration-tests/testing/network.go#L14)):*
> What are the procs ..

There are not. Writing `500 * time.Millisecond` is just a common way of doing it. I've never seen a code using `time.Second / 2`

**Pull request merged**
