### PR TITLE
Update signatures & addresses in `validator-*.json` files for devnet

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/194)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
I still use the same mnemonics for generating these files but different HD paths (needs to be discussed)
As for automating this I created a dirty bash script but it is not ready to be commited so I prefer to discuss it also.

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/194#-:-NCaGbJNDh6alnQbPZik:bwq9blm)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/194)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/194#-NCczCLi2JLVNxrjAsrN:-NCczCLi2JLVNxrjAsrO:bmt8uj9) (no related file):*
Please add unit test verifying that signatures are correct.

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/194#-NCczJLo-JAzFOriWOF9:-NCczJLo-JAzFOriWOFA:bjq0jo0) (no related file):*
Please document the procedure

___

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/194)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/194#-NCczJLo-JAzFOriWOF9:-NDe-CF66PR3m9lCELmp:bb7f2mf) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please document the procedure
</blockquote></details>

done

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/194#-NCczCLi2JLVNxrjAsrN:-NDe-qtkCHXOT6gB_WQl:b-pv9tu3) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please add unit test verifying that signatures are correct.
</blockquote></details>

making it through unit tests without using cosmos SDK is quite complex & requires a lot of copy-pasting and will be very time consuming because they do a lot of magic there

I 2 next solutions:

1st
```
// in network.go add. The usage of this func is allowed in tests only
func SetSDKConfigNoSeal() {
 // does everything same as SetSDKConfig except calling Seal()
 // so we can set different prefixes for different networks during testing
}

// write tests to validate txs one by one for different networks
// test should be located in coreum/pkg/config/networks/ because in coreum/pkg/config/ we seal config in init() so it is not safe to override it
// signature checking will be done with code similar to cosmos-sdk@v0.45.5/x/auth/client/cli/validate_sigs.go:61 but adjusted
```

2nd
```
// Add GenTxs signature validation in network initialization
func NewNetwork(c NetworkConfig) Network {
      // ...
      for _, genTx := range c.GenTxs {
		validateSignature(genTx)
	}
}
// signature checking will be done with code similar to cosmos-sdk@v0.45.5/x/auth/client/cli/validate_sigs.go:61 but adjusted
```

Which one do you prefer ?

___

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/194)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/194)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/194#-NCczCLi2JLVNxrjAsrN:-NDgXvBz46mM3XCUWsgh:bbg2rj2) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

making it through unit tests without using cosmos SDK is quite complex & requires a lot of copy-pasting and will be very time consuming because they do a lot of magic there

I 2 next solutions:

1st
```
// in network.go add. The usage of this func is allowed in tests only
func SetSDKConfigNoSeal() {
 // does everything same as SetSDKConfig except calling Seal()
 // so we can set different prefixes for different networks during testing
}

// write tests to validate txs one by one for different networks
// test should be located in coreum/pkg/config/networks/ because in coreum/pkg/config/ we seal config in init() so it is not safe to override it
// signature checking will be done with code similar to cosmos-sdk@v0.45.5/x/auth/client/cli/validate_sigs.go:61 but adjusted
```

2nd
```
// Add GenTxs signature validation in network initialization
func NewNetwork(c NetworkConfig) Network {
      // ...
      for _, genTx := range c.GenTxs {
		validateSignature(genTx)
	}
}
// signature checking will be done with code similar to cosmos-sdk@v0.45.5/x/auth/client/cli/validate_sigs.go:61 but adjusted
```

Which one do you prefer ?
</blockquote></details>

The idea is to catch problems in PR, not at the time of deployment. So I guess that 1st option is the one to go with

___
___
*[`pkg/config/genesis/genesis.tmpl.json` line 18 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/194#-NDgYPfQ7niLjGqtlISD:-NDgYPfR16f6urg1alUC:bpny81f) ([raw file](https://github.com/coreumfoundation/coreum/blob/2c252800c3a2219ae0f0257f91b4763e85f9a1a9/pkg/config/genesis/genesis.tmpl.json#L18)):*
> ```JSON
>     "validator": {
>       "pub_key_types": [
>         "ed25519",
> ```

let's remove this one and use only secp
___
*[`pkg/config/networks/coreum-devnet-1/validator-0.json` line 7 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/194#-NDgYXPBDfff_7C0FYny:-NDgYXPC1u6wZFp_QB-f:b70a64u) ([raw file](https://github.com/coreumfoundation/coreum/blob/2c252800c3a2219ae0f0257f91b4763e85f9a1a9/pkg/config/networks/coreum-devnet-1/validator-0.json#L7)):*
> ```JSON
>         "@type": "/cosmos.staking.v1beta1.MsgCreateValidator",
>         "description": {
>           "moniker": "staker0",
> ```

it's not a staker, but validator, so names should be like `validator-X` for example

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/194)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/config/networks/networks_test.go` line 91 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/194#-NDhXOr79JDjrxSGfbFd:-NDh_fQe-vCpR4b267UH:b-dbifws) ([raw file](https://github.com/coreumfoundation/coreum/blob/8a89d5ea7018bd7e724ac9939ceba55f5acc59aa/pkg/config/networks/networks_test.go#L91)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

The thing is that tx I provided in `invalidSignatureTx` would pass cosmo-sdk validation in ofline mode `cored tx validate-signatures --offline` because they don't check it fully so I decided to test negative scenario also

Moved to another test
</blockquote></details>

oh, please add a comment explaining this there

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/194)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`pkg/config/networks/networks_test.go` line 91 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/194#-NDhXOr79JDjrxSGfbFd:-NDyumGg8zKwHGizEtdr:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/8a89d5ea7018bd7e724ac9939ceba55f5acc59aa/pkg/config/networks/networks_test.go#L91)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

oh, please add a comment explaining this there
</blockquote></details>

Done.

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/194)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/194)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`tx.json` line 2 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/194#-NE-Ua7uAGuQgOoZiD8c:-NE-Ua7uAGuQgOoZiD8d:bswpx2y) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad246fdd775dc7df6214d1e084b0ff8e30532a5f/tx.json#L2)):*
> ```JSON
> {
>   "body": {
> ```

was this file added accidentally?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/194)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`tx.json` line 2 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/194#-NE-Ua7uAGuQgOoZiD8c:-NE0-Zt3BxQCQc7DplVU:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ad246fdd775dc7df6214d1e084b0ff8e30532a5f/tx.json#L2)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

was this file added accidentally?
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
