### PR TITLE
Test DEX messages and queries in wasm

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description
Test DEX messages and queries in wasm
Use module_query_safe for gRPC query accept list
Update rust dependencies

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1012)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1012)* status: 0 of 44 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`integration-tests/contracts/modules/ft/src/msg.rs` line 18 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/1012#-OA1V1rw3hNecsVUpu28:-OA1V1rw3hNecsVUpu29:b-8dtmxx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/17424fe1e0653fe16e39d7483a8937e103ccba81/integration-tests/contracts/modules/ft/src/msg.rs#L18)):*
> ```XML
>     pub uri_hash: Option<String>,
>     pub extension_settings: Option<ExtensionIssueSettings>,
>     pub dex_settings: Option<DexSettings>,
> ```

DexSetting - Uppercase `DEX`, same for GO, and the custom ?

**Review by miladz68 — DISMISSED** [review]
> Reviewed 29 of 37 files at r1, 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1012)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1012)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/contracts/modules/ft/src/msg.rs` line 18 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/1012#-OA1V1rw3hNecsVUpu28:-OA1X4hV0WNe69qbQHLk:bnpihrh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/17424fe1e0653fe16e39d7483a8937e103ccba81/integration-tests/contracts/modules/ft/src/msg.rs#L18)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

DexSetting - Uppercase `DEX`, same for GO, and the custom ?
</blockquote></details>

But this is auto generated from the proto

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1012)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 27 of 37 files at r1, 14 of 15 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1012)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1012)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 27 of 37 files at r1, 14 of 15 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1012)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

**Pull request merged**
