### PR TITLE
Enable wasm snapshots

### PR DESCRIPTION
**Pull request by dzmitryhil**
Blocked by the restruct PR

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/171)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/171)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/171#-NBpJdfD5FNFXvzmXn56:-NBpJdfD5FNFXvzmXn57:b-ljlgfi) (no related file):*
If this PR is done on top of the other one, please set the other branch as a target of this one. Otherwise after approving changes here, all of them related to both PRs will be merged into master

___

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/171)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/171#-NBpJdfD5FNFXvzmXn56:-NBpK-cv0IqD-rLS32Ek:b-t2agb6) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If this PR is done on top of the other one, please set the other branch as a target of this one. Otherwise after approving changes here, all of them related to both PRs will be merged into master
</blockquote></details>

or leave this comment blocking until the other PR is merged

___

**Review by wojtek-coreum — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/171)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/171#-NBpJdfD5FNFXvzmXn56:-NBpKBmCBFxMDNmNAsrp:b-px0qxy) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

or leave this comment blocking until the other PR is merged
</blockquote></details>

oh, I see it was merged already

___

**Review by begmaroman — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/171)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
