### PR TITLE
Add `go generate` command to generate deterministic gas doc

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/473)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/473)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/473)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/473)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/deterministicgas/spec/generate.go` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/473#-NTYoIPm3BUxhsrUaW8p:-NTYoIPm3BUxhsrUaW8q:b69ud4x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/310462b11b4ecd194f09f4698794319156a198b6/x/deterministicgas/spec/generate.go#L18)):*
> ```Go
> )
> 
> //go:generate go run . ./README.md
> ```

this command is already defined in this file: `coreum/x/deterministicgas/config.go`

if you prefer to move it here them lets keep it in a single place

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/473)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/473)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

___
*[`x/deterministicgas/spec/generate.go` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/473#-NTYoIPm3BUxhsrUaW8p:-NTYtDg60xt1vUI0nk8b:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/310462b11b4ecd194f09f4698794319156a198b6/x/deterministicgas/spec/generate.go#L18)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

this command is already defined in this file: `coreum/x/deterministicgas/config.go`

if you prefer to move it here them lets keep it in a single place
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/473)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
