### PR TITLE
Run the CI in parallel

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/225)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/225)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/225#-NEFgWGkDuBbs2Q7irFV:-NEFgWGl5Gxii9ad_Kvi:bwntvgm) ([raw file](https://github.com/coreumfoundation/coreum/blob/3a8a4284898b6bf485ecbdd30b8280ca293f4734/.github/workflows/ci.yml#L17)):*
> ```YAML
>         include:
>           - ci_step: "lint"
>             command: "crust lint/coreum"
> ```

Just use yaml format it looks good
___
*[`.github/workflows/ci.yml` line 74 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/225#-NEFgCyDCFxSXid1hlKM:-NEFgCyDCFxSXid1hlKN:bngpqc0) ([raw file](https://github.com/coreumfoundation/coreum/blob/3a8a4284898b6bf485ecbdd30b8280ca293f4734/.github/workflows/ci.yml#L74)):*
> ```YAML
>         run: echo "$(pwd)/crust/bin" >> $GITHUB_PATH
>       - name: Run ${{ matrix.ci_step }}
>         run: ${{ matrix.command }}
> ```

an empty line at the end of file would be nice.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/225)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/225#-NEFgWGkDuBbs2Q7irFV:-NEFijMk7Hcu4rJzN6zA:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/3a8a4284898b6bf485ecbdd30b8280ca293f4734/.github/workflows/ci.yml#L17)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Just use yaml format it looks good
</blockquote></details>

Done.
___
*[`.github/workflows/ci.yml` line 74 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/225#-NEFgCyDCFxSXid1hlKM:-NEFiUfs7_OKygDiyPhb:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/3a8a4284898b6bf485ecbdd30b8280ca293f4734/.github/workflows/ci.yml#L74)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

an empty line at the end of file would be nice. 
</blockquote></details>

Done.

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/225)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/225#-NEFkM_B6M1YqtopTAOe:-NEFkM_B6M1YqtopTAOf:bjwq7n8) ([raw file](https://github.com/coreumfoundation/coreum/blob/5351480b4d5caef42141bee907fdc9d770e849db/.github/workflows/ci.yml#L27)):*
> ```YAML
>             docker-cache: false
>           - ci_step: "build & znet test"
>             command: "crust build images --log-format=yaml && crust znet test --log-format=yaml"
> ```

to optimize even more. 
`crust build/integration-tests images --log-format=yaml && crust znet test --log-format=yaml`

**Review by miladz68 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/225)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/225)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 27 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/225#-NEFkM_B6M1YqtopTAOe:-NEFkvAw-hF4ug7uICx5:b5q5220) ([raw file](https://github.com/coreumfoundation/coreum/blob/5351480b4d5caef42141bee907fdc9d770e849db/.github/workflows/ci.yml#L27)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

to optimize even more. 
`crust build/integration-tests images --log-format=yaml && crust znet test --log-format=yaml`
</blockquote></details>

Agree, updated. Alos restored the "build" to execute in parallel.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/225)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/ci.yml` line 32 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/225#-NEFm1uA0PDSqAgkYdEo:-NEFm1uA0PDSqAgkYdEp:b-l1b2ew) ([raw file](https://github.com/coreumfoundation/coreum/blob/a1eab01b2e3ed5a67d7e448ac3aacbf3e9058eed/.github/workflows/ci.yml#L32)):*
> ```YAML
>             docker-cache: false
>           - ci_step: "integration tests"
>             command: "crust build/integration-tests images --log-format=yaml && crust znet test --log-format=yaml"
> ```

`build/znet` is needed as well

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/225)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/225)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`.github/workflows/ci.yml` line 32 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/225#-NEFm1uA0PDSqAgkYdEo:-NEFmU5gCV9d-lKsSgpU:bohcccs) ([raw file](https://github.com/coreumfoundation/coreum/blob/a1eab01b2e3ed5a67d7e448ac3aacbf3e9058eed/.github/workflows/ci.yml#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`build/znet` is needed as well
</blockquote></details>

ah wait, `crust znet` will build it

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Review by miladz68 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Pull request merged**
