### PR TITLE
Use BIP44 coin_type for CORE when generating HD paths

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/211)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/211)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`app/app.go` line 118 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDEBm_N9VqWDN1Crt8s:-NDEBm_O5mx_MpRBwLhn:blbzt07) ([raw file](https://github.com/coreumfoundation/coreum/blob/ce6d1e6d702c911000fefec48fc9d6d9fcb901f2/app/app.go#L118)):*
> ```Go
> 
> 	// DefaultChainID is the default chain id of the network
> 	DefaultChainID = config.Devnet
> ```

For me it is really convenient to have devnet as default chain so I don't need to pass CHAIN_ID to each cli command. And since we don't have any other network enabled I think it is ok to keep it like this for now

@wojtek-coreum @dzmitryhil @miladz68 LMK if you agree with this 
___
*[`pkg/config/network.go` line 50 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDEJXHiAu279ot1uQod:-NDEJXHiAu279ot1uQoe:b-mqgcr9) ([raw file](https://github.com/coreumfoundation/coreum/blob/a2b2178a40e005ec51d933732d8227025f334a85/pkg/config/network.go#L50)):*
> ```Go
> const (
> 	// coreBIP44CoinType is the CORE coin type as defined in SLIP44 (https://github.com/satoshilabs/slips/blob/master/slip-0044.md)
> 	coreBIP44CoinType uint32 = 990
> ```

According to BIP44 all testnet coins should use 1 as coin type "Testnet (all coins)"
However I've checked a few chains and it seems that all of them use the same coin type in testnet & mainnet except BTC e.g:
- ETH same coin_type. Tested by importing the same mnemonic in testnet & mainnet 
- ADA same coin_type but different address prefixes (addr1 vs addr_test1). Difference starts only on address generation step where depending on network they add different prefix https://github.com/uniVocity/cardano-tutorials/blob/master/cardano-addresses.md#generating-a-payment-address
- XRP same coin_type (tested by importing same mnemonic in mainnet & testnet and got the same address => pub key)
- cosmos SDK based chains mostly use the same because SDK config is global object and it might require to recompile binary unless they do the same trick as we did for addresses. E.g terra https://github.com/terra-money/core/blob/main/app/const.go#L11
- BNB chain same coin_type (not sure)

So I guess that it is ok to to use the same coin type. However using different is a bit more secure
___
*[`pkg/config/network.go` line 50 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDEOx8y2VU-265cP-WJ:-NDEOx8y2VU-265cP-WK:bshsi9s) ([raw file](https://github.com/coreumfoundation/coreum/blob/a2b2178a40e005ec51d933732d8227025f334a85/pkg/config/network.go#L50)):*
> ```Go
> const (
> 	// coreBIP44CoinType is the CORE coin type as defined in SLIP44 (https://github.com/satoshilabs/slips/blob/master/slip-0044.md)
> 	coreBIP44CoinType uint32 = 990
> ```

As for different assets none issues separate address for different asset. So I guess it is more like per blockchain thingy

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/211)* status: all files reviewed, 6 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`app/app.go` line 118 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDEBm_N9VqWDN1Crt8s:-NDRS5WRBmd4F85Hvco9:b-7tdf7d) ([raw file](https://github.com/coreumfoundation/coreum/blob/ce6d1e6d702c911000fefec48fc9d6d9fcb901f2/app/app.go#L118)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

For me it is really convenient to have devnet as default chain so I don't need to pass CHAIN_ID to each cli command. And since we don't have any other network enabled I think it is ok to keep it like this for now

@wojtek-coreum @dzmitryhil @miladz68 LMK if you agree with this 
</blockquote></details>

agree
___
*[`cmd/cored/cosmoscmd/flags.go` line 52 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDRTWhc8utvwxEMBnnn:-NDRTWhd8_GKxZbcermB:bsbkzez) ([raw file](https://github.com/coreumfoundation/coreum/blob/a2b2178a40e005ec51d933732d8227025f334a85/cmd/cored/cosmoscmd/flags.go#L52)):*
> ```Go
> 		return config.Network{}, err
> 	}
> 	network.SetSDKConfig()
> ```

I don't think it's a good place to call this as it's outside of "pre process flags" scope.
___
*[`cmd/cored/cosmoscmd/init.go` line 43 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDRUMqT7GLmlRjh4uSq:-NDRUMqT7GLmlRjh4uSr:bprzkti) ([raw file](https://github.com/coreumfoundation/coreum/blob/1677557a6194bd4e683220510cbd5092a76019df/cmd/cored/cosmoscmd/init.go#L43)):*
> ```Go
> 				return errors.Wrapf(err, "got error getting chain-id flag")
> 			}
> 			if chainID == "" {
> ```

Minor: I remember that in the past I proposed to ignore this `if` too and depend on `NetworkByChainID` returning an error because config for chain "" does not exist. You and @miladz68 argued then that it is still better to handle this condition separately.  I have nothing against removing it now - just bringing attention to the fact that it changes some earlier decision.
___
*[`integration-tests/testing/chain.go` line 42 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDRV5OC8vfT6Kw1GR4q:-NDRV5OC8vfT6Kw1GR4r:b5jbvlg) ([raw file](https://github.com/coreumfoundation/coreum/blob/a2b2178a40e005ec51d933732d8227025f334a85/integration-tests/testing/chain.go#L42)):*
> ```Go
> // private key and stores mnemonic in Keyring.
> func (c ChainContext) RandomWallet() sdk.AccAddress {
> 	hdPath := hd.CreateHDPath(sdk.GetConfig().GetCoinType(), 0, 0).String()
> ```

As I understand hdpath, it's goal is to never use the same values for two keys. The idea is to use different (incremented?) number for account or index
___
*[`pkg/config/network.go` line 50 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDEJXHiAu279ot1uQod:-NDRSbW9BXK3IIj_KYar:b-kx1iwq) ([raw file](https://github.com/coreumfoundation/coreum/blob/a2b2178a40e005ec51d933732d8227025f334a85/pkg/config/network.go#L50)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

According to BIP44 all testnet coins should use 1 as coin type "Testnet (all coins)"
However I've checked a few chains and it seems that all of them use the same coin type in testnet & mainnet except BTC e.g:
- ETH same coin_type. Tested by importing the same mnemonic in testnet & mainnet 
- ADA same coin_type but different address prefixes (addr1 vs addr_test1). Difference starts only on address generation step where depending on network they add different prefix https://github.com/uniVocity/cardano-tutorials/blob/master/cardano-addresses.md#generating-a-payment-address
- XRP same coin_type (tested by importing same mnemonic in mainnet & testnet and got the same address => pub key)
- cosmos SDK based chains mostly use the same because SDK config is global object and it might require to recompile binary unless they do the same trick as we did for addresses. E.g terra https://github.com/terra-money/core/blob/main/app/const.go#L11
- BNB chain same coin_type (not sure)

So I guess that it is ok to to use the same coin type. However using different is a bit more secure
</blockquote></details>

But I would prefer to follow standards rather than crappy implementations. If standard instructs us to use 1, then let's use 1. That's why we implemented config per network - to be able to do things correctly.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/211)* status: 6 of 12 files reviewed, 5 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`app/app.go` line 118 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDEBm_N9VqWDN1Crt8s:-NDTz1By-m61WeFQb5yS:b-s5x7u7) ([raw file](https://github.com/coreumfoundation/coreum/blob/ce6d1e6d702c911000fefec48fc9d6d9fcb901f2/app/app.go#L118)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

For now yes, but in the future, the default should be the mainnet. 
</blockquote></details>

for sure
___
*[`cmd/cored/cosmoscmd/flags.go` line 52 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDRTWhc8utvwxEMBnnn:-NDU1sx42pIo_B879oqp:bf06k03) ([raw file](https://github.com/coreumfoundation/coreum/blob/a2b2178a40e005ec51d933732d8227025f334a85/cmd/cored/cosmoscmd/flags.go#L52)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't think it's a good place to call this as it's outside of "pre process flags" scope.
</blockquote></details>

partially makes sense for me
moved to `func main()` together with `	app.ChosenNetwork = network` now it looks more logical

The thing is that in most cases we have to call SetSDKConfig right after initialization so was trying to keep it as close as possible
___
*[`cmd/cored/cosmoscmd/init.go` line 43 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDRUMqT7GLmlRjh4uSq:-NDTzCU9-yvp2fYQ-ThP:b79nw8a) ([raw file](https://github.com/coreumfoundation/coreum/blob/1677557a6194bd4e683220510cbd5092a76019df/cmd/cored/cosmoscmd/init.go#L43)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Minor: I remember that in the past I proposed to ignore this `if` too and depend on `NetworkByChainID` returning an error because config for chain "" does not exist. You and @miladz68 argued then that it is still better to handle this condition separately.  I have nothing against removing it now - just bringing attention to the fact that it changes some earlier decision.
</blockquote></details>

frankly speaking I don't remember this part but it does the same thing in 2 places so I decided to just pass it 
It looks  ok for me now
___
*[`integration-tests/testing/chain.go` line 42 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDRV5OC8vfT6Kw1GR4q:-NDU-xNUEOhc_xiXTZWF:b-qc2r77) ([raw file](https://github.com/coreumfoundation/coreum/blob/a2b2178a40e005ec51d933732d8227025f334a85/integration-tests/testing/chain.go#L42)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

As I understand hdpath, it's goal is to never use the same values for two keys. The idea is to use different (incremented?) number for account or index
</blockquote></details>

this incremented account/index is used within key and in the most cases it stays the same
___
*[`pkg/config/network.go` line 50 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDEJXHiAu279ot1uQod:-NDU0iuF0IXrLoBKOIQO:blahhkh) ([raw file](https://github.com/coreumfoundation/coreum/blob/a2b2178a40e005ec51d933732d8227025f334a85/pkg/config/network.go#L50)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's discuss it, but I agree with the Wojtek, the defaults seems not relatable. 
</blockquote></details>

lets discuss because maybe it is better & not an issue for us but will case troubles & misunderstanding for mobile devs etc
___
*[`pkg/config/network.go` line 89 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDT76PY0lvSQgJodLVG:-NDU0ka81pvcATyOGx5e:bse8xqb) ([raw file](https://github.com/coreumfoundation/coreum/blob/a2b2178a40e005ec51d933732d8227025f334a85/pkg/config/network.go#L89)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Where do we use it?
</blockquote></details>

I just changed it to be explicitly set to false (it is already like this by default)
we use e.g in cli if you pass not enabled network it will error

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/211)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/chain.go` line 42 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDRV5OC8vfT6Kw1GR4q:-NDWh_c64eG2qRvoJeOr:b-yetvna) ([raw file](https://github.com/coreumfoundation/coreum/blob/a2b2178a40e005ec51d933732d8227025f334a85/integration-tests/testing/chain.go#L42)):*
> this incremented account/index is used within key

WDYM?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/211)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/config/network.go` line 50 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDWlZcyBZ0ugsrX628y:-NDWlZcyBZ0ugsrX628z:b-utklok) ([raw file](https://github.com/coreumfoundation/coreum/blob/0af4aa1beea108432d1f4a5a4ef975868a47dcf8/pkg/config/network.go#L50)):*
> ```Go
> const (
> 	// coreBIP44CoinType is the CORE coin type as defined in SLIP44 (https://github.com/satoshilabs/slips/blob/master/slip-0044.md)
> 	coreBIP44CoinType uint32 = 990
> ```

I think it should be exported and you can move it to the other constants block.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/211)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/211)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/testing/chain.go` line 42 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDRV5OC8vfT6Kw1GR4q:-NDXLvl7DV8Kol-uM6_c:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a2b2178a40e005ec51d933732d8227025f334a85/integration-tests/testing/chain.go#L42)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> this incremented account/index is used within key

WDYM?
</blockquote></details>

Done.
___
*[`pkg/config/network.go` line 50 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/211#-NDWlZcyBZ0ugsrX628y:-NDXLwFL5N93n5UQ6-cZ:b-7ql1td) ([raw file](https://github.com/coreumfoundation/coreum/blob/0af4aa1beea108432d1f4a5a4ef975868a47dcf8/pkg/config/network.go#L50)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I think it should be exported and you can move it to the other constants block. 
</blockquote></details>

fixed

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/211)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @miladz68)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/211)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Pull request merged**
