### PR TITLE
Spec for `delay` module

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/576)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/576)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/576)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/delay/spec/README.md` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/576#-N_nFDjj0Ml1bYEQJjAF:-N_nKw4p1WgwlTm3zyD9:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6164021bfdd61cff8aa68ad599494aad06477688/x/delay/spec/README.md#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

x/delay
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/576)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/576)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
