### PR TITLE
Changes required to generate OpenAPI spec

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

These changes are required by the crust PR: https://reviewable.io/reviews/CoreumFoundation/crust/281#-

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/632#-NdArQpy9tr6u_jkq6ID:-NdArQpzEV4PHM61VXr8:b-p3ajme) (no related file):*
I think you should make this PR against mater now. 

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/632#-NdArQpy9tr6u_jkq6ID:-NdAtEvs873Y9KaWQAMI:b-896fix) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think you should make this PR against mater now.
</blockquote></details>

Done.

___

**Review by ysv — DISMISSED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @vertex451)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @miladz68 and @vertex451)

___
*[`proto/cosmos/ics23/v1/proofs.proto` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/632#-NdEsvL07XZ1W2rEXlfh:-NdEsvL07XZ1W2rEXlfi:b-y7yn4c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/46e80d23cd65b94d2a5c1341fb77d8322bfab610/proto/cosmos/ics23/v1/proofs.proto#L1)):*
> ```proto
> syntax = "proto3";
> ```

Could you please explain why do we need that file.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @miladz68 and @vertex451)

___
*[`proto/cosmos/ics23/v1/proofs.proto` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/632#-NdEsvL07XZ1W2rEXlfh:-NdEusf_2O8RwygUookE:ba62psk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/46e80d23cd65b94d2a5c1341fb77d8322bfab610/proto/cosmos/ics23/v1/proofs.proto#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you please explain why do we need that file.
</blockquote></details>

It is required by `ibc.core.connection.v1` package and surprisingly cosmos does not provide it. It is embedded in ignite too (I took it from there).

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @miladz68 and @vertex451)

___
*[`proto/cosmos/ics23/v1/proofs.proto` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/632#-NdEsvL07XZ1W2rEXlfh:-NdFcvkc7UZtaWTQm58H:b8r6gwb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/46e80d23cd65b94d2a5c1341fb77d8322bfab610/proto/cosmos/ics23/v1/proofs.proto#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It is required by `ibc.core.connection.v1` package and surprisingly cosmos does not provide it. It is embedded in ignite too (I took it from there).
</blockquote></details>

But in that case, it should be located in the `third_party` folder.

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

___
*[`proto/cosmos/ics23/v1/proofs.proto` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/632#-NdEsvL07XZ1W2rEXlfh:-NdUCdIoCEw_aFGI8jJF:b3h3vcb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/46e80d23cd65b94d2a5c1341fb77d8322bfab610/proto/cosmos/ics23/v1/proofs.proto#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But in that case, it should be located in the `third_party` folder.
</blockquote></details>

What about `cosmos/msg/v1/msg.proto` then? Should it be moved too?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

___
*[`proto/cosmos/ics23/v1/proofs.proto` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/632#-NdEsvL07XZ1W2rEXlfh:-NdURXbe2DZD3jFazgTC:bz24lqq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/46e80d23cd65b94d2a5c1341fb77d8322bfab610/proto/cosmos/ics23/v1/proofs.proto#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What about `cosmos/msg/v1/msg.proto` then? Should it be moved too?
</blockquote></details>

It should be as well.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451 and @wojtek-coreum)

___
*[`proto/cosmos/msg/v1/msg.proto` line 0 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/632#-NddhMKWAuIJ7Jnq6f-e:-NddhMKWAuIJ7Jnq6f-f:bhzek3r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/edca9dc94eb1be4bfa5174712c671552b3c64225/proto/cosmos/msg/v1/msg.proto#L0)):*
this file is deleted and not moved to `third_party` is that intended ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @vertex451)

___
*[`proto/cosmos/msg/v1/msg.proto` line  at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/632#-NddhMKWAuIJ7Jnq6f-e:-Nddy9WG4se3Hu20FITU:blmnzy6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/edca9dc94eb1be4bfa5174712c671552b3c64225/proto/cosmos/msg/v1/msg.proto#L)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this file is deleted and not moved to `third_party` is that intended ?
</blockquote></details>

Yes, because it is present in cosmos sdk. I don't know why it was copied to our repo.

**Review by ysv — DISMISSED** [review]
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @vertex451)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 11 of 11 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/632)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
