### PR TITLE
Allow zero precision for ft tokens

### PR DESCRIPTION
**Pull request by miladz68**
# Description
Allow zero precision for ft tokens
# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/787)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/787)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/modules/assetft_test.go` line 117 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/787#-NroeytnEX-SCdhi2iE5:-NroeytnEX-SCdhi2iE6:b-9ig5vj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/06123529b31ded62ced2ba6a859260c829fc047f/integration-tests/modules/assetft_test.go#L117)):*
> ```Go
> 
> // TestAssetFTIssue tests issue functionality of fungible tokens.
> func TestAssetFTIssue_ZeroPrecision(t *testing.T) {
> ```

I suggest to merge this test with `TestAssetFTIssue`.
I think we should move towards less code in our integration tests because they might become unmaintainable at some point. 

you can change it to table test with 2 cases.
input args for tests is `&assetfttypes.MsgIssue` and output to assert (the only thing I find different) is `expectedMetadata := banktypes.Metadata`. Everything else seems to be same
___
*[`x/asset/ft/keeper/keeper.go` line 320 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/787#-NrofidqBB2b9Orbp0Eh:-Nrofidr68bmYlX5eFIs:b-n8o8qo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/06123529b31ded62ced2ba6a859260c829fc047f/x/asset/ft/keeper/keeper.go#L320)):*
> ```Go
> 	// we are force to have single entry in denom units and also Display must be the
> 	// same as Base.
> 	if precision == 0 {
> ```

nit: maybe it makes sense to write unit-tests for this part if possible

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/787)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 320 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/787#-NrofidqBB2b9Orbp0Eh:-Nrt98KI1nTX9JfI6sUe:b-7tdf7d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/06123529b31ded62ced2ba6a859260c829fc047f/x/asset/ft/keeper/keeper.go#L320)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: maybe it makes sense to write unit-tests for this part if possible
</blockquote></details>

agree

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/787)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 117 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/787#-NroeytnEX-SCdhi2iE5:-Nrt9TXl7e9WEnCuodLm:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/06123529b31ded62ced2ba6a859260c829fc047f/integration-tests/modules/assetft_test.go#L117)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I suggest to merge this test with `TestAssetFTIssue`.
I think we should move towards less code in our integration tests because they might become unmaintainable at some point. 

you can change it to table test with 2 cases.
input args for tests is `&assetfttypes.MsgIssue` and output to assert (the only thing I find different) is `expectedMetadata := banktypes.Metadata`. Everything else seems to be same
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper.go` line 320 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/787#-NrofidqBB2b9Orbp0Eh:-NrtCKqF4BFcwR-oTO2H:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/06123529b31ded62ced2ba6a859260c829fc047f/x/asset/ft/keeper/keeper.go#L320)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

agree
</blockquote></details>

Done.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/787)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`x/asset/ft/keeper/keeper_test.go` line 155 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/787#-NrtZin82FPuAvrU4HKX:-NrtZin82FPuAvrU4HKY:beaeo2c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/87b4a8bc3f1ca87735e4d5b67aa59492393bbc21/x/asset/ft/keeper/keeper_test.go#L155)):*
> ```Go
> }
> 
> func TestKeeper_Issue_ZeroPrecision(t *testing.T) {
> ```

sorry, my comment probably confused you.
I meant unit-tests for token issuance generally not only for `Precision:     0, ` case



_Code quote:_
```Go
TestKeeper_Issue_ZeroPrecision
```

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/787)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`x/asset/ft/keeper/keeper_test.go` line 155 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/787#-NrtZin82FPuAvrU4HKX:-Nrthlz6CuAeVQEaNyZR:b-h6b285) ([raw file](https://github.com/CoreumFoundation/coreum/blob/87b4a8bc3f1ca87735e4d5b67aa59492393bbc21/x/asset/ft/keeper/keeper_test.go#L155)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

sorry, my comment probably confused you.
I meant unit-tests for token issuance generally not only for `Precision:     0, ` case
</blockquote></details>

I still don't get it, we already have tests for token issuance both in unit and integration tests.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/787)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
