### PR TITLE
Create github bugreport template

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/135)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
1. For other repos (crust, faucet etc) I plan to just redirect to coreum repo so we have all issues centralized for now because users might not differentiate crust coreum etc

2. you can play with the result of form provided here: https://github.com/ysv/coreum-2/issues/new/choose

3. I decide to use github [issue form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) because it looks more structured  

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/135#-:-N9XTocEAF3e4hcgLXW0:bsxasaj)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @xlab)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/135)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @xlab, and @ysv)

___
*[`.github/ISSUE_TEMPLATE/bug-report.yaml` line 47 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/135#-N9_7-Pi8XiCLq39u9f8:-N9_7-PjEbWMS_Fd7id6:bv2xlw2) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca34d9692a058da88cb77c3df9341e27f9f1b91d/.github/ISSUE_TEMPLATE/bug-report.yaml#L47)):*
> ```YAML
>       description: If applicable, copy and paste all necessary logs from your console.
>       value: |
>         <details>
> ```

what does `<details>` mean?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/135)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @xlab)

___
*[`.github/ISSUE_TEMPLATE/bug-report.yaml` line 47 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/135#-N9_7-Pi8XiCLq39u9f8:-N9aES9RAmQX9fp_iN4f:b-229hw1) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca34d9692a058da88cb77c3df9341e27f9f1b91d/.github/ISSUE_TEMPLATE/bug-report.yaml#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what does `<details>` mean?
</blockquote></details>

it folds text inside it so we don't have 1k lines of logs making issue description unreadable

Screenshot 2022-08-16 at 12.44.05
Screenshot 2022-08-16 at 12.44.16

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/135)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @xlab)

___
*[`.github/ISSUE_TEMPLATE/bug-report.yaml` line 47 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/135#-N9_7-Pi8XiCLq39u9f8:-N9aFSqq28y3BN3cKAAm:b-aklavt) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca34d9692a058da88cb77c3df9341e27f9f1b91d/.github/ISSUE_TEMPLATE/bug-report.yaml#L47)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

it folds text inside it so we don't have 1k lines of logs making issue description unreadable

Screenshot 2022-08-16 at 12.44.05
Screenshot 2022-08-16 at 12.44.16

</blockquote></details>


Screenshot 2022-08-16 at 12.44.16

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/135)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @xlab)

___
*[`.github/ISSUE_TEMPLATE/bug-report.yaml` line 47 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/135#-N9_7-Pi8XiCLq39u9f8:-N9aFbSm5zzyVjPFiuDa:by27o0w) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca34d9692a058da88cb77c3df9341e27f9f1b91d/.github/ISSUE_TEMPLATE/bug-report.yaml#L47)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>


Screenshot 2022-08-16 at 12.44.16
</blockquote></details>

examle is here
https://github.com/kubernetes/kubernetes/issues/111829

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @xlab)

**Pull request merged**
