### PR TITLE
Add `block` mode to await transaction in CLI

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

Cosmos SDK removed `block` mode. It's inconvenient because it requires extra step to get information a bout executed transaction. We reintroduce the `block` mode by implementing yet another hacky wrapper.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/715)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/715)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`cmd/cored/cosmoscmd/root.go` line 326 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/715#-NjCg_GC01aw0dMM6upM:-NjCg_GC01aw0dMM6upN:b-r1b6wz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1bd60dc296d177bc36fc9a8f8d47df699c0a6a5e/cmd/cored/cosmoscmd/root.go#L326)):*
> ```Go
> 		cmds = cmds[:len(cmds)-1]
> 
> 		if broadcastModeFlag := cmd.LocalFlags().Lookup(flags.FlagBroadcastMode); broadcastModeFlag != nil {
> ```

It would be nice to see the demo, and discuss it.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/715)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

___
*[`cmd/cored/cosmoscmd/root.go` line 326 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/715#-NjCg_GC01aw0dMM6upM:-NjCmQus9lf0DRrwPnei:b67aypy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1bd60dc296d177bc36fc9a8f8d47df699c0a6a5e/cmd/cored/cosmoscmd/root.go#L326)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It would be nice to see the demo, and discuss it.
</blockquote></details>

I agree
A bit complicated to review

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/715)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/715#-NjDoYRQBKJ0wMDXa4ZG:-NjDoYRQBKJ0wMDXa4ZH:b-9ydlp3) (no related file):*
@wojtek-coreum pls add some comments to the code 
You explained it very nice on call and would be nice to have similar explanation in code so it is maintainable

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/715)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @miladz68)

___
*[`cmd/cored/cosmoscmd/root.go` line 326 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/715#-NjCg_GC01aw0dMM6upM:-NjGqzWK6a3EtBLWLJ-l:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1bd60dc296d177bc36fc9a8f8d47df699c0a6a5e/cmd/cored/cosmoscmd/root.go#L326)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree
A bit complicated to review
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/715)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/715#-NjDoYRQBKJ0wMDXa4ZG:-NjH3rns2vsfPSbw5Pxt:b-896fix) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

@wojtek-coreum pls add some comments to the code 
You explained it very nice on call and would be nice to have similar explanation in code so it is maintainable
</blockquote></details>

Done.

___

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/715)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/715)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
