### PR TITLE
Add the v1 migration.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/440)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/440)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/440#-NQa7S67ALAyr4ItRwFr:-NQa7S67ALAyr4ItRwFs:b-y07qy9) (no related file):*
Does it mean that the migration should be run for all the devnets or is it still just about running integration tests?

___

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/440)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`app/app.go` line 627 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/440#-NQaDCsS456KOLFjeGph:-NQaDCsTByOsPvG5wKtZ:bk1h237) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b2b631a625e61533b66583820aa31569c953b45f/app/app.go#L627)):*
> ```Go
> 	}
> 
> 	/**** Upgrades ****/
> ```

I don't understand this part. Let's discuss it after the daily.
___
*[`integration-tests/upgrade/upgrade_test.go` line 142 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/440#-NQaDUPC36Fo6SA3ZJ7a:-NQaDUPC36Fo6SA3ZJ7b:b-afqcon) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b2b631a625e61533b66583820aa31569c953b45f/integration-tests/upgrade/upgrade_test.go#L142)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// check that asst nft is available now
> ```

asst -> asset

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/440)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/440)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`app/upgrade/v1/upgrade.go` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/440#-NQaKxIfBxe73T92UzPW:-NQaKxIfBxe73T92UzPX:be10dmi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6404d2a50df471a02f0b7fff2751e75574c18616/app/upgrade/v1/upgrade.go#L1)):*
> ```Go
> package v1
> ```

this is an upgrade only intended for testnet right ? so maybe instead of calling it v1, we can call it something specific to testnet ? like `testnetv0`.
My point is that we should have a way to tell apart upgrades which will go to both testnet and mainnet and those which are specific to testnet.

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/440)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`app/upgrade/v1/upgrade.go` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/440#-NQaKxIfBxe73T92UzPW:-NQaQ5fH4rn-NuaWCZum:b-lc73kw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6404d2a50df471a02f0b7fff2751e75574c18616/app/upgrade/v1/upgrade.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO v1 is quite good. 
</blockquote></details>

I will unblock, but I want to see what other guys are thinking 
@ysv @wojtek-coreum

**Review by miladz68 — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/440)* status: all files reviewed, 4 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`app/upgrade/v1/upgrade.go` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/440#-NQaKxIfBxe73T92UzPW:-NQdfrFs0YyNk7ftir1b:bal4tv3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6404d2a50df471a02f0b7fff2751e75574c18616/app/upgrade/v1/upgrade.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We don't relate the binary with the environment, we agreed on it before, that's why that upgrade is not the testnet as well IMO.
</blockquote></details>

but do I understand correctly that this upgrade is only related to and will only run on testnet ?

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/440)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`app/upgrade/v1/upgrade.go` line 1 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/440#-NQaKxIfBxe73T92UzPW:-NQeKmyADQnmzSzNascY:bwo2nla) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6404d2a50df471a02f0b7fff2751e75574c18616/app/upgrade/v1/upgrade.go#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This one - yes. 
</blockquote></details>

I agree with Dzmitry IMO it makes sense to call it like this. I'm just thinking if it should be smth like `v1_0` . Because theoretically we can release next vers as `v1_1` if we add new features but don't brake API compatibility. And if we do brake then v2_0
___
*[`integration-tests/upgrade/upgrade_test.go` line 43 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/440#-NQeLOYe6VLN5shFSP3h:-NQeLOYe6VLN5shFSP3i:bpz0asv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a8c150a58eaa7d5a1c228411abcf19a9098b1b1/integration-tests/upgrade/upgrade_test.go#L43)):*
> ```Go
> 	infoBeforeRes, err := tmQueryClient.GetNodeInfo(ctx, &tmservice.GetNodeInfoRequest{})
> 	requireT.NoError(err)
> 	// we start with the binary we if the v0.0.1
> ```

comment is not clear for me
do you mean v0.1.1 ?

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/440)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 2 of 5 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/440)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 2 of 5 files at r2, 2 of 4 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/440)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/440)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/440)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Pull request merged**
