### PR TITLE
[DRAFT, new format only] Use scientific notation for the DEX price string.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Use scientific notation for the DEX price string.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1004)

### CODE REVIEW

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1004)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/dex/spec/README.md` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/1004#-O9Tolic9Qfv2MItGsyL:-O9TolidDZxKQ-8VsKLE:b5uynkm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e4830bbb718c0698a8151a83746cb5c4ac0d05fc/x/dex/spec/README.md#L1)):*
> ```Markdown
> ~~# Coreum DEX Specification
> ```

What's this?
___
*[`x/dex/spec/README.md` line 189 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/1004#-O9TpWz77ZK_teZqMEAR:-O9TpWz77ZK_teZqMEAS:b-i5ubwk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e4830bbb718c0698a8151a83746cb5c4ac0d05fc/x/dex/spec/README.md#L189)):*
> ```Markdown
> * The `price` must match the regex: `^([1-9]\.\d+)(e[-+]\d+)`.
> * The decimal part of the `price` can't end with zero if it's length greater than 2.
> * The exponent is required for all values and sign (+-) is always required. For zero exponent use `e+0``.
> ```

```
`e+0`` => `e+0`
```

I think the exponent should not start with zero unless it is just one zero. It can also be checked in regex `e[\-+](0|[1-9]\d*)`
I'm not sure, but please check if the `-` in `[-+]` should be escaped or not
___
*[`x/dex/types/price.go` line 80 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/1004#-O9TqwDi6sNbzT0sHM7n:-O9TqwDi6sNbzT0sHM7o:bg77avs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e4830bbb718c0698a8151a83746cb5c4ac0d05fc/x/dex/types/price.go#L80)):*
> ```Go
> 		return Price{}, errors.Errorf("exponent part %s, can't start with -0", expPart)
> 	}
> 	if strings.HasPrefix(expPart, "+0") && len(expPart) > 2 {
> ```

I'm not sure if I got this. But how can we have price `1`?
It should be `1.0e+0` (which `1.0e-0` is also correct and it's a problem)
Let me know if I'm not getting it

**Review by miladz68 — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1004)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1004)* status: all files reviewed, 3 unresolved discussions (waiting on @masihyeganeh and @ysv)

___
*[`x/dex/spec/README.md` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/1004#-O9Tolic9Qfv2MItGsyL:-O9URKLN-9YFzlqaCWtc:b-57sz6d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e4830bbb718c0698a8151a83746cb5c4ac0d05fc/x/dex/spec/README.md#L1)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

What's this?
</blockquote></details>

Typo, removed.
___
*[`x/dex/spec/README.md` line 189 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/1004#-O9TpWz77ZK_teZqMEAR:-O9UNRVAD1J3X5iTAti-:b-lekrqv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e4830bbb718c0698a8151a83746cb5c4ac0d05fc/x/dex/spec/README.md#L189)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

```
`e+0`` => `e+0`
```

I think the exponent should not start with zero unless it is just one zero. It can also be checked in regex `e[\-+](0|[1-9]\d*)`
I'm not sure, but please check if the `-` in `[-+]` should be escaped or not
</blockquote></details>

Updated to`^([1-9]\.\d+)(e\+0|e[-+][1-9]\d*)$`, and remove extra validation from the code and spec.
___
*[`x/dex/types/price.go` line 80 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/1004#-O9TqwDi6sNbzT0sHM7n:-O9UMpobANr5-_o1ecX5:b5xa8p9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e4830bbb718c0698a8151a83746cb5c4ac0d05fc/x/dex/types/price.go#L80)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I'm not sure if I got this. But how can we have price `1`?
It should be `1.0e+0` (which `1.0e-0` is also correct and it's a problem)
Let me know if I'm not getting it
</blockquote></details>

The 1 is `1.0e+0`, and the validation prohibits the `-e0` exponent.

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1004)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request closed without merging**
