### PR TITLE
Use original genesis file for EncodeGenesis for testnet and mainnet.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/468)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/468)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/468)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`pkg/config/network_test.go` line 176 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/468#-NTJMZ4Z2HXwciwQQKmR:-NTJMZ4Z2HXwciwQQKmS:b-8jksew) ([raw file](https://github.com/CoreumFoundation/coreum/blob/eb376b6266930a56daed0f2f7eb09e75ea5fd940/pkg/config/network_test.go#L176)):*
> ```Go
> 		{
> 			chainID:     constant.ChainIDTest,
> 			genesisHash: "276d5df3856ccfba9240687f463c9464e10176e0fc355efb7162e36b09b0e3af",
> ```

I didn't get why it changed ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/468)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`pkg/config/network_test.go` line 176 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/468#-NTJMZ4Z2HXwciwQQKmR:-NTJT_oI9bfob_jc1kIs:b-wsf0r9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/eb376b6266930a56daed0f2f7eb09e75ea5fd940/pkg/config/network_test.go#L176)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I didn't get why it changed ?
</blockquote></details>

Because for the genesis of the testnet it used the NFT (empty) which we have in the current codebase.

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/468)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

___
*[`pkg/config/network_test.go` line 176 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/468#-NTJMZ4Z2HXwciwQQKmR:-NTKKJo73CpCBGMpOihG:bn2ats4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/eb376b6266930a56daed0f2f7eb09e75ea5fd940/pkg/config/network_test.go#L176)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Because for the genesis of the testnet it used the NFT (empty) which we have in the current codebase. 
</blockquote></details>

ah so before we were dynamically rendering it but now we read from file
And in reality they are different

**Pull request merged**
