### PR TITLE
Replace the ComputeNeededBalance to ComputeNeededBalanceFromOptions

### PR DESCRIPTION
**Pull request by dzmitryhil**
* Replace the ComputeNeededBalance to ComputeNeededBalanceFromOptions
* Add and integrate new func FundAccountsWithOptions

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/239)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/239)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/bank/gas.go` line 95 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/239#-NF87NP03WrW3N-UaMc6:-NF87NP03WrW3N-UaMc7:bl2e7zq) ([raw file](https://github.com/coreumfoundation/coreum/blob/e7dd65bcd058eaaa4d57c2d40c63b7060dfe0ec6/integration-tests/bank/gas.go#L95)):*
> ```Go
> 		bankSendGas,
> 		1,
> 		amountToSend,
> ```

You need this line there

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/239)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/bank/gas.go` line 95 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/239#-NF87NP03WrW3N-UaMc6:-NF93Jim0coOArOMkBzS:bv6obs7) ([raw file](https://github.com/coreumfoundation/coreum/blob/e7dd65bcd058eaaa4d57c2d40c63b7060dfe0ec6/integration-tests/bank/gas.go#L95)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You need this line there
</blockquote></details>

Which line, I didn't get you?

**Review by miladz68 — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/239)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/239)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/bank/gas.go` line 95 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/239#-NF87NP03WrW3N-UaMc6:-NFIK12Q57syY5mKqgh9:bloeb8a) ([raw file](https://github.com/coreumfoundation/coreum/blob/e7dd65bcd058eaaa4d57c2d40c63b7060dfe0ec6/integration-tests/bank/gas.go#L95)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Which line, I didn't get you?
</blockquote></details>

```
	require.NoError(t, chain.Faucet.FundAccounts(ctx, testing.NewFundedAccount(sender, chain.NewCoin(testing.ComputeNeededBalance(
		chain.NetworkConfig.Fee.FeeModel.Params().InitialGasPrice,
		bankSendGas,
		1,
		amountToSend, <---------------
	)))))

```

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/239)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/bank/gas.go` line 95 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/239#-NF87NP03WrW3N-UaMc6:-NFJIgWD5LWrl73xdNt5:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e7dd65bcd058eaaa4d57c2d40c63b7060dfe0ec6/integration-tests/bank/gas.go#L95)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

```
	require.NoError(t, chain.Faucet.FundAccounts(ctx, testing.NewFundedAccount(sender, chain.NewCoin(testing.ComputeNeededBalance(
		chain.NetworkConfig.Fee.FeeModel.Params().InitialGasPrice,
		bankSendGas,
		1,
		amountToSend, <---------------
	)))))

```
</blockquote></details>

Done.



_Code quote:_
```Go
require.NoError(t, chain.Faucet.FundAccountsWithOptions(ctx, sender, testing.BalancesOptions{
```

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
