### PR TITLE
Use `coreum-wasm-sdk` crate inside smart contracts

### PR DESCRIPTION
**Pull request by wojtek-coreum**
Crate is available here: https://crates.io/crates/coreum-wasm-sdk
Source code: https://github.com/CoreumFoundation/coreum-wasm-sdk

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/469)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/469)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/469#-NTN_KEP2Oow0NQ8hdtz:-NTN_KEP2Oow0NQ8hdu-:br5zz78) (no related file):*
Two items to discuss:

1. For now, I am the owner of the crate, probably I should transfer the ownership to an official account of the foundation
2. We need to write readme for the crate

___

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/469)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/469)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/469)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/469#-NTYnnjJEVqxwq-3wZa2:-NTYnnjJEVqxwq-3wZa3:b-awcfbo) (no related file):*
All is good, blocking to resolve the sdk ownership issue.

___

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/469)* status: all files reviewed, 4 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/469#-NTN_KEP2Oow0NQ8hdtz:-NTZHA3_-cODqVJlDtXI:bmrlq9f) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Two items to discuss:

1. For now, I am the owner of the crate, probably I should transfer the ownership to an official account of the foundation
2. We need to write readme for the crate
</blockquote></details>

1. yes. Please sent all needed instructions to Reza and help him to setup it. We have an account for these type of things here: https://github.com/CoreumDevelopment . Also would be nice to add CI procedure to publish tagged releases automatically to creates. Could you please fully setup the repo that is the idea

2. Pls add it also

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/469#-NTZKd7VCm3sVsNXHghc:-NTZKd7VCm3sVsNXHghd:b-j8eijz) (no related file):*
@dzmitryhil @miladz68 @wojtek-coreum do we need to review sdk itself or it is just a copy of what we had inside coreum repo ?

___
___
*[`integration-tests/modules/testdata/wasm/README.md` line 12 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/469#-NTZKOxN3_VnTxIV5fMb:-NTZKOxN3_VnTxIV5fMc:b-nsd9kj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4fd8b9a68c9dd449d7882c6e6dbbb92678b2c314/integration-tests/modules/testdata/wasm/README.md#L12)):*
> ```Markdown
> * Execute the command:
> ```
> docker run --rm -v "$(pwd)"/../sdk:/sdk -v "$(pwd)":/code \
> ```

IMO it should be replaced with crust cmd after we add it. Or to avoid chaing the file twice you can do it inside this PR

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/469)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/469#-NTZKd7VCm3sVsNXHghc:-NTmBJ8TBJzvK6z_zkT9:bljxdic) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

@dzmitryhil @miladz68 @wojtek-coreum do we need to review sdk itself or it is just a copy of what we had inside coreum repo ?
</blockquote></details>

It's just a copy

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/469)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/testdata/wasm/README.md` line 12 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/469#-NTZKOxN3_VnTxIV5fMb:-NTmBP7r4wh7svDnnolU:b-gylums) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4fd8b9a68c9dd449d7882c6e6dbbb92678b2c314/integration-tests/modules/testdata/wasm/README.md#L12)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO it should be replaced with crust cmd after we add it. Or to avoid chaing the file twice you can do it inside this PR
</blockquote></details>

I will update it once crust PR is merged

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/469)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/469#-NTZKd7VCm3sVsNXHghc:-NTn3jCO27z3rV57rddt:bkfgecb) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It's just a copy
</blockquote></details>

Right, it's copy.

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/469)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @silverspase)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/469#-NTYnnjJEVqxwq-3wZa2:-NTxgDP-0CMR1GPMaVCO:b-20f34g) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

All is good, blocking to resolve the sdk ownership issue.
</blockquote></details>

Ownership is fine now

___

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/469)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
