### PR TITLE
Remove FIXME(v47-dependencies)

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

All new replacements are required. Removing the FIXME. 

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/597)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/597)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`integration-tests/go.mod` line 6 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/597#-NbYUS3B3KTN3QA6Unmb:-NbYUS3C1dA0k7oyZPG4:b-s10s27) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9c57804b679b85a19fe38ffe68e826f3e32555bd/integration-tests/go.mod#L6)):*
> ```XML
> 
> replace (
> 	github.com/CoreumFoundation/coreum/v2 => ../
> ```

I don't understand why we need to replace coreum inside coreum ? can you elaborate ?

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/597)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/597)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @wojtek-coreum)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/597)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/597)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/597)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/597)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/597)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by vertex451 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/597)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Pull request merged**
