### PR TITLE
Restore integration tests

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/212)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/212)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`.github/workflows/ci.yml` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/212#-NDU4jP6-5nsr0goRwB2:-NDU4jP6-5nsr0goRwB3:b-ppzibz) ([raw file](https://github.com/coreumfoundation/coreum/blob/c231076650be6227386f4947e1c0b1910e6163fa/.github/workflows/ci.yml#L46)):*
> ```YAML
>       - name: Lint, run unit tests and build
>         run: crust build lint/coreum test/coreum images --log-format=yaml
> #        FIXME(dhil) temp workaround to let update the crust
> ```

can we merge this after coreum/211 because I need tests to be disabled there because it contains breaking changes for crust

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/212)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @miladz68)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/212)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`.github/workflows/ci.yml` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/212#-NDU4jP6-5nsr0goRwB2:-NDWh8f001wnp6oRh6IO:b-sz7dq5) ([raw file](https://github.com/coreumfoundation/coreum/blob/c231076650be6227386f4947e1c0b1910e6163fa/.github/workflows/ci.yml#L46)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can we merge this after coreum/211 because I need tests to be disabled there because it contains breaking changes for crust
</blockquote></details>

Guys, disabling tests should be considered as a last option if nothing else can work

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/212)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`.github/workflows/ci.yml` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/212#-NDU4jP6-5nsr0goRwB2:-NDWm2PF6hu439XaR-T3:b-yph8mu) ([raw file](https://github.com/coreumfoundation/coreum/blob/c231076650be6227386f4947e1c0b1910e6163fa/.github/workflows/ci.yml#L46)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Guys, disabling tests should be considered as a last option if nothing else can work
</blockquote></details>

Yes, just let me know @ysv  when we can do it.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/212)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman and @miladz68)

___
*[`.github/workflows/ci.yml` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/212#-NDU4jP6-5nsr0goRwB2:-NDWm85H9w7g4_FC4hfl:b-p250or) ([raw file](https://github.com/coreumfoundation/coreum/blob/c231076650be6227386f4947e1c0b1910e6163fa/.github/workflows/ci.yml#L46)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes, just let me know @ysv  when we can do it. 
</blockquote></details>

@wojtek-coreum @ysv. 
The @miladz68 told us yesterday that we should resolve that issue in order not to do it frequently, and I agree with him. So let's discuss how we can do it and do it next sprint.

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/212)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman and @miladz68)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/212)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman and @miladz68)

___
*[`.github/workflows/ci.yml` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/212#-NDU4jP6-5nsr0goRwB2:-NDXMZxq2iMAxUoovhkK:b-jhch5s) ([raw file](https://github.com/coreumfoundation/coreum/blob/c231076650be6227386f4947e1c0b1910e6163fa/.github/workflows/ci.yml#L46)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@wojtek-coreum @ysv. 
The @miladz68 told us yesterday that we should resolve that issue in order not to do it frequently, and I agree with him. So let's discuss how we can do it and do it next sprint.
</blockquote></details>

Nothing could really work for my case also
And I fully agree that we use this too frequently, unfortunately

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/212)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman and @miladz68)

**Pull request merged**
