### PR TITLE
Remove legacy routers and simulations functions

### PR DESCRIPTION
**Pull request by miladz68**
# Description
This PR, removes the functions from Modules, related to legacy routers and simulations. that code was already commented and we needed to reasearch a replacement. As outlined [here](https://docs.cosmos.network/v0.47/migrations/upgrading#appmodule-interface), all those functions are fully deprecated and must be removed. 
# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/607)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/607)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/607#-NbxkIx66-veY-VbEEwo:-NbxkIx66-veY-VbEEwp:bl17wza) (no related file):*
It seems that this PR contains two changes
- ones related to the task
- merges from master

Please fix this PR to contain only related changes. If youwant to merge master into v47 branch please do it separately.

___

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/607)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/607#-NbxkIx66-veY-VbEEwo:-NbxnFSq8akyKRfTy9RO:b-i1xm80) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It seems that this PR contains two changes
- ones related to the task
- merges from master

Please fix this PR to contain only related changes. If youwant to merge master into v47 branch please do it separately.
</blockquote></details>

Yes, same issue on my side
Skipping the review for now

___

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/607)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/607#-NbxkIx66-veY-VbEEwo:-NbxyZQyA_K7IfVnxXNX:b-96m4jg) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Yes, same issue on my side
Skipping the review for now
</blockquote></details>

It is so weird, github said that I was behind the other branch and when I clicked on update, it merged the master :joy: 
I guess you can review it now.  

___

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/607)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

___
*[`x/asset/nft/module.go` line 128 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/607#-NbzYrLaAQ9p_ySCZOTP:-NbzYrLaAQ9p_ySCZOTQ:b-tzcjgh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4972491050232639ac6e8c54d04f8eea2d460b83/x/asset/nft/module.go#L128)):*
> ```Go
> 
> // Route returns the assetnft module's message routing key.
> // FIXME(v47-module-config): remove or replace with corresponding component
> ```

Have you checked that none of these methods should be overiden ?
___
*[`x/wibctransfer/module_test.go` line 50 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/607#-NbzZ-uN0ft9stSVes10:-NbzZ-uN0ft9stSVes11:bn8m3pq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4972491050232639ac6e8c54d04f8eea2d460b83/x/wibctransfer/module_test.go#L50)):*
> ```Go
> // Since we override the "Register Services" we want to be sure that after the update of the SDK,
> // The original transfer module won't have unexpected migrations.
> // FIXME(v47-module-config): validate that the updated wrapping is correct and wraps all required methods.
> ```

have you checked it ?

If interface is used there maybe we can add check 
```
_ InterfaceType = &Implementation
```

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/607)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/module.go` line 128 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/607#-NbzYrLaAQ9p_ySCZOTP:-Nc1q9NsDJeLwr5c5GKq:btzk2iq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4972491050232639ac6e8c54d04f8eea2d460b83/x/asset/nft/module.go#L128)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Have you checked that none of these methods should be overiden ?
</blockquote></details>

yes, as it is mentioned in the linked provied in the description, these methods are now fully deprecated, and don't need a replacement (i.e no replacement is mentioned here, and no replacement done in other chains, e.g wasmd)
___
*[`x/wibctransfer/module_test.go` line 50 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/607#-NbzZ-uN0ft9stSVes10:-Nc1rSNVBpYJIlTAtSKX:b-6p2iie) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4972491050232639ac6e8c54d04f8eea2d460b83/x/wibctransfer/module_test.go#L50)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

have you checked it ?

If interface is used there maybe we can add check 
```
_ InterfaceType = &Implementation
```
</blockquote></details>

no, but that is meant to pass, since we are embedding the original inside the wrapper. it is also checked in app.go where we pass to ibc module.

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/607)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/607)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @vertex451)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/607#-Nc2RbRB2tSQXaY9iwC7:-Nc2RbRCAlsv-hBB5IvY:b-51duce) (no related file):*
If `Route()` is removed from everywhere it means that we don't need these either:
- https://github.com/CoreumFoundation/coreum/blob/master/x/deterministicgas/types/gas.go#L22
- https://github.com/CoreumFoundation/coreum/blob/v0.47-migration-v2/x/deterministicgas/types/gas.go#L23

___

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/607)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/607#-Nc2RbRB2tSQXaY9iwC7:-Nc6YMvJ6UxP-C86guUN:b77bslj) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If `Route()` is removed from everywhere it means that we don't need these either:
- https://github.com/CoreumFoundation/coreum/blob/master/x/deterministicgas/types/gas.go#L22
- https://github.com/CoreumFoundation/coreum/blob/v0.47-migration-v2/x/deterministicgas/types/gas.go#L23
</blockquote></details>

the links you provided are for the gas router. the sdk.Route might not be deprecated in side Router, so fixing that should be done in the task dedicated to fixing the deterministic gas ?

___

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/607)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @vertex451)

**Pull request merged**
