### PR TITLE
Query all types of balances for an account and denom

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 442 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NW2Iy3F0GBDr2pfpaDf:-NW2Iy3F0GBDr2pfpaDg:b-gp6knf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/30636b9ac6d7699aebed3bf9bc156abc7b4033aa/app/app.go#L442)):*
> ```Go
> 		wasmkeeper.WithMessageEncoders(wasmcustomhandler.NewCoreumMsgHandler()),
> 		wasmkeeper.WithQueryPlugins(wasmcustomhandler.NewCoreumQueryHandler(
> 			assetftkeeper.NewQueryService(app.AssetFTKeeper, app.BankKeeper),
> ```

@ysv @miladz68 @wojtek-coreum Do we want to include the Query for the WASM contracts?
___
*[`x/asset/ft/keeper/grpc_query.go` line 93 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NW2IlGLDx_4zbgNIl5T:-NW2IlGLDx_4zbgNIl5U:b-gmo7j0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/30636b9ac6d7699aebed3bf9bc156abc7b4033aa/x/asset/ft/keeper/grpc_query.go#L93)):*
> ```Go
> 		Balance:     qs.bankKeeper.GetBalance(ctx, account, denom).Amount,
> 		Whitelisted: qs.keeper.GetWhitelistedBalance(ctx, account, denom).Amount,
> 		Frozen:      qs.keeper.GetFrozenBalance(ctx, account, denom).Amount,
> ```

You have defined the Locked in the protos, but here it's empty.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: all files reviewed, 4 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NW2JFM583wvseUlGXGh):*
Why the CLI isn't implemented?
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NW2JBtd77Ekgo4Izdbn):*
What about the integration test?

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: all files reviewed, 4 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 442 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NW2Iy3F0GBDr2pfpaDf:-NW63QllCplxBAyy56c_:b-3kbe58) ([raw file](https://github.com/CoreumFoundation/coreum/blob/30636b9ac6d7699aebed3bf9bc156abc7b4033aa/app/app.go#L442)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv @miladz68 @wojtek-coreum Do we want to include the Query for the WASM contracts?
</blockquote></details>

@dzmitryhil which queries exactly ? let's discuss.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NW2JFM583wvseUlGXGh):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why the CLI isn't implemented?
</blockquote></details>

It is
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NW2JBtd77Ekgo4Izdbn):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about the integration test?
</blockquote></details>

They are there
___
*[`app/app.go` line 442 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NW2Iy3F0GBDr2pfpaDf:-NW6JKKxBoXiQ8lG4j88:bri8n36) ([raw file](https://github.com/CoreumFoundation/coreum/blob/30636b9ac6d7699aebed3bf9bc156abc7b4033aa/app/app.go#L442)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@dzmitryhil which queries exactly ? let's discuss. 
</blockquote></details>

yes I guess
___
*[`x/asset/ft/keeper/grpc_query.go` line 93 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NW2IlGLDx_4zbgNIl5T:-NW6JO4iDBP9hVIVI6AP:byoifxw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/30636b9ac6d7699aebed3bf9bc156abc7b4033aa/x/asset/ft/keeper/grpc_query.go#L93)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You have defined the Locked in the protos, but here it's empty.
</blockquote></details>

I removed it from protos later

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: 11 of 14 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`app/app.go` line 442 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NW2Iy3F0GBDr2pfpaDf:-NW6LAzr0UUmddm8mtDQ:b-offp7y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/30636b9ac6d7699aebed3bf9bc156abc7b4033aa/app/app.go#L442)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

yes I guess
</blockquote></details>

added handler here, later on we must add types to wasm sdk. I also see that we are missing other queries (FrozenBalances and WhitelistedBalances)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: 11 of 14 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 442 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NW2Iy3F0GBDr2pfpaDf:-NW6l-t24rg0770huUva:b7r6495) ([raw file](https://github.com/CoreumFoundation/coreum/blob/30636b9ac6d7699aebed3bf9bc156abc7b4033aa/app/app.go#L442)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

added handler here, later on we must add types to wasm sdk. I also see that we are missing other queries (FrozenBalances and WhitelistedBalances)
</blockquote></details>

@ysv Let's add a task to extend the WASM FT test and SDK with that query. 
___
*[`integration-tests/modules/assetft_test.go` line 307 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NW6mhce6Z48PrPiLb15:-NW6mhce6Z48PrPiLb16:b-mzy6pj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7290e34d91905e48368a4df4e1df5abcdd9a2284/integration-tests/modules/assetft_test.go#L307)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	assertT.Equal("30", resp.Whitelisted.String())
> ```

How about move the coins (balance, frozen, whitelisted) to the variables use them in the TXs and assert them at the end instead of strings.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 10 of 13 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 10 of 13 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`app/app.go` line 442 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NW2Iy3F0GBDr2pfpaDf:-NWC8zTo9Wr_NHEOtWYE:b-7tfmjp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/30636b9ac6d7699aebed3bf9bc156abc7b4033aa/app/app.go#L442)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv Let's add a task to extend the WASM FT test and SDK with that query. 
</blockquote></details>

added
___
*[`proto/coreum/asset/ft/v1/query.proto` line 94 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NWC9kHy0OdB6wIegLzT:-NWC9kHy0OdB6wIegLzU:b-mnpw1y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/885bfdefa3b274ed2281f95f9339acb88e0cdb0b/proto/coreum/asset/ft/v1/query.proto#L94)):*
> ```protobuf
> }
> 
> message QueryBalanceResponse {
> ```

Here is the response structure we agreed to have from clickup ticket:
```
{
  denom: uft-abcde
  balance: 100,
  whitelisted: 200,
  frozen: 50,
  locked: 10, // this value comes from vesting.
  source: assetft,
}
```
___
*[`proto/coreum/asset/ft/v1/query.proto` line 94 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NWCA-Hg9X86unZM0J28:-NWCA-Hg9X86unZM0J29:b-qq5vst) ([raw file](https://github.com/CoreumFoundation/coreum/blob/885bfdefa3b274ed2281f95f9339acb88e0cdb0b/proto/coreum/asset/ft/v1/query.proto#L94)):*
> ```protobuf
> }
> 
> message QueryBalanceResponse {
> ```

does this query return balance for non asset FT denoms ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`proto/coreum/asset/ft/v1/query.proto` line 94 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NWC9kHy0OdB6wIegLzT:-NWCB-4m1flpnO_TA3ZB:box96n2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/885bfdefa3b274ed2281f95f9339acb88e0cdb0b/proto/coreum/asset/ft/v1/query.proto#L94)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Here is the response structure we agreed to have from clickup ticket:
```
{
  denom: uft-abcde
  balance: 100,
  whitelisted: 200,
  frozen: 50,
  locked: 10, // this value comes from vesting.
  source: assetft,
}
```
</blockquote></details>

let's discuss it after daily
___
*[`proto/coreum/asset/ft/v1/query.proto` line 94 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NWCA-Hg9X86unZM0J28:-NWCBBSw0g0wQAkpJV6C:b2nign6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/885bfdefa3b274ed2281f95f9339acb88e0cdb0b/proto/coreum/asset/ft/v1/query.proto#L94)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

does this query return balance for non asset FT denoms ?
</blockquote></details>

yes

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @ysv)

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`proto/coreum/asset/ft/v1/query.proto` line 94 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NWC9kHy0OdB6wIegLzT:-NWNSfo_By7eAF-lFknG:bmovjse) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd08cbcb123c771061ff23de61e606a7961d9d21/proto/coreum/asset/ft/v1/query.proto#L94)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

let's discuss it after daily
</blockquote></details>


```
{
  balance: 100,
  whitelisted: 200,
  frozen: 50,
  locked: 10, // this value comes from vesting.
  source: assetft, // native, ibc, assetft
}
```

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`proto/coreum/asset/ft/v1/query.proto` line 94 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NWC9kHy0OdB6wIegLzT:-NWNUygJ5Dz8yXxoMyF4:b-n4w9b2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd08cbcb123c771061ff23de61e606a7961d9d21/proto/coreum/asset/ft/v1/query.proto#L94)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>


```
{
  balance: 100,
  whitelisted: 200,
  frozen: 50,
  locked: 10, // this value comes from vesting.
  source: assetft, // native, ibc, assetft
}
```
</blockquote></details>

final decision:
 ```
{
  balance: 100,
  whitelisted: 200,
  frozen: 50,
  locked: 10, // this value comes from vesting.
}
```
for non-existing denom return 0s

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: 9 of 15 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`proto/coreum/asset/ft/v1/query.proto` line 94 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/504#-NWC9kHy0OdB6wIegLzT:-NWacnrc5wngrHGzWLhB:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd08cbcb123c771061ff23de61e606a7961d9d21/proto/coreum/asset/ft/v1/query.proto#L94)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

final decision:
 ```
{
  balance: 100,
  whitelisted: 200,
  frozen: 50,
  locked: 10, // this value comes from vesting.
}
```
for non-existing denom return 0s
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 5 of 6 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 5 of 6 files at r5, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/504)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
