### PR TITLE
Add genesis sources and include them to the tests.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/442)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/442)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/442#-NQa6Tgp7_87FlQVB4Lh:-NQa6Tgq30AA1Y84BJVQ:bix6jd8) (no related file):*
It should not be done this way. Genesis jsons should be generated from our config written in `network.go` and only then hash should be computed. Otherwise our config may deviate from what is inside those fixed genesis.json files

___

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/442)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/442#-NQa6Tgp7_87FlQVB4Lh:-NQaLr168fS_6eZH5RVQ:b-iax342) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It should not be done this way. Genesis jsons should be generated from our config written in `network.go` and only then hash should be computed. Otherwise our config may deviate from what is inside those fixed genesis.json files
</blockquote></details>

in the next step, we will completely remove the config for mainnet and testnet, and only have it for testnet. after the launch changing the genesis file is meaningless. 

___

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/442)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/442#-NQa6Tgp7_87FlQVB4Lh:-NQarZ_N8ephIHOY50cv:b-e7k1eb) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

in the next step, we will completely remove the config for mainnet and testnet, and only have it for testnet. after the launch changing the genesis file is meaningless. 
</blockquote></details>

then it should be embedded into binary and not read from disk

___

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/442)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/442#-NQa6Tgp7_87FlQVB4Lh:-NQdgOXF54TNTWAaeLb0:bpd9093) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

then it should be embedded into binary and not read from disk
</blockquote></details>

agreed, I did not notice that we are reading it from file. it should be embedded. 

___

**Review by ysv — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/442)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/442)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/442#-NQa6Tgp7_87FlQVB4Lh:-NQeGkI6CkT6XxE1wF3g:bzhezqw) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It can't be embedded. Since the files are on the top directory.
</blockquote></details>

Fro the current stage when we use this file only inside tests it is ok for me
But in the future once we want to have it inside binary it should be embeded I agree 100% but golang seems to not allow to embed from parent directories & the idea was to have this file explicitly in root of the repo. 

The only solution I see for the next stage is to use linux symlink 

However, for this stage & this PR solution is ok

___

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/442)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`pkg/config/network_test.go` line 251 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/442#-NQeH_HS47H1i1UyjHOz:-NQeH_HS47H1i1UyjHP-:b-jku43v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/29f66d0d322b68e50613c9c51339e072ae880d09/pkg/config/network_test.go#L251)):*
> ```Go
> 			require.NoError(t, err)
> 			require.Equal(t, tt.wantHash, fmt.Sprintf("%x", sha256.Sum256(genesisDoc)))
> 			require.Equal(t, tt.wantHash, fmt.Sprintf("%x", sha256.Sum256(genesisFile)))
> ```

I don't see a reason to have 3 sources of truth
Lets just compare generated genesis with genesis inside json

IMO we don't need hashes at all

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/442)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/442#-NQa6Tgp7_87FlQVB4Lh:-NQecJMCBZzqwoRLLXLZ:b7crehc) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually I would keep it as is, since if we don't embed then the binary is smaller.
</blockquote></details>

Let's discuss this during daily because now we have two sources of truth - files and config. This is very bad.

___

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/442)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/442)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/442)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/442)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
