### PR TITLE
Add TimeInForce attribute for the order and integrate GTC type for the matching.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Add TimeInForce attribute for the order and integrate GTC type for the matching.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/955)

### CODE REVIEW

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/955)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`proto/coreum/dex/v1/order.proto` line 48 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/955#-O6_PsRDEk87vjwSvBMG:-O6_PsRDEk87vjwSvBMH:bxq6jfr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/da5da6098746c72b54bd15ae0dbb5acca0d52bf9/proto/coreum/dex/v1/order.proto#L48)):*
> ```proto
> }
> 
> // Type is order type.
> ```

Wrong comment

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/955)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/955)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

___
*[`proto/coreum/dex/v1/order.proto` line 48 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/955#-O6_PsRDEk87vjwSvBMG:-O6_R-3Z45kybYYbetPo:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/coreum/blob/da5da6098746c72b54bd15ae0dbb5acca0d52bf9/proto/coreum/dex/v1/order.proto#L48)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Wrong comment
</blockquote></details>

Updated.

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/955)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
