### PR TITLE
Integrate codecov into integration-tests/modules

### PR DESCRIPTION
**Pull request by ysv**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/777)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/777)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/777)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/777)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

___
*[`build/go.mod` line 3 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/777#-Npd_V-t-a8XUvjV3K-y:-Npd_V-t-a8XUvjV3K-z:b-y03fk6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/432b443103c1671e06c74b3b9625840a2926ebe8/build/go.mod#L3)):*
> ```XML
> module github.com/CoreumFoundation/coreum/build
> 
> // 1.20 is used here because still not all distros deliver 1.21.
> ```

@wojtek-coreum this comment is not relevant here so I removed it
___
*[`build/go.mod` line 21 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/777#-Npd_axh1aQ3ma58Ismx:-Npd_axh1aQ3ma58Ismy:bbmeubl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0a112beccea248277c068c6fb87e89d692bd3101/build/go.mod#L21)):*
> ```XML
> 	github.com/spf13/pflag v1.0.5 // indirect
> 	go.uber.org/multierr v1.11.0 // indirect
> 	// Make sure to not bump x/exp dependency without cosmos-sdk updated because their breaking change is not compatible
> ```

@miladz68 @wojtek-coreum @dzmitryhil pls note this
otherwise weird build failure happens because when you update almost any dep `x/exp` also gets updated

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/777)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

___
*[`build/go.mod` line 3 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/777#-Npd_V-t-a8XUvjV3K-y:-Npdrdq6BN30zAwG81zV:bi3nb8o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/432b443103c1671e06c74b3b9625840a2926ebe8/build/go.mod#L3)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

@wojtek-coreum this comment is not relevant here so I removed it
</blockquote></details>

or you might update it to `1.21 is used ...`

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/777)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
