### PR TITLE
Add function to generate unsigned Tx

### PR DESCRIPTION
**Pull request by miladz68**
# Description
Add function to generate unsigned Tx
# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/778)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/778)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/client/tx.go` line 87 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/778#-NpUHod4Aw08ILZOIcrb:-NpUHod4Aw08ILZOIcrc:b-42jjxd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fd1e810db1c3ebb641b20f012c36c59ca5138049/pkg/client/tx.go#L87)):*
> ```Go
> 		key, err := clientCtx.Keyring().KeyByAddress(clientCtx.FromAddress())
> 		if err != nil {
> 			return nil, errors.Errorf("failed to get key by the address %q from the keyring", clientCtx.FromAddress().String())
> ```

`Wrapf`

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/778)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/client/tx.go` line 87 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/778#-NpUHod4Aw08ILZOIcrb:-NpUX8a161kp5cZqFxUN:b-vuh2i1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fd1e810db1c3ebb641b20f012c36c59ca5138049/pkg/client/tx.go#L87)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I am not getting this, maybe you are pointing to the wrong line ?
</blockquote></details>

Check by text: `failed to get key by the addres`

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/778)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/778)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`pkg/client/tx.go` line 87 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/778#-NpUHod4Aw08ILZOIcrb:-NpUZNlV8K_LxoQ2D7lR:b85xz80) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fd1e810db1c3ebb641b20f012c36c59ca5138049/pkg/client/tx.go#L87)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Check by text: `failed to get key by the addres`
</blockquote></details>

I see now, that line is not part of the code changes. Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/778)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
