### PR TITLE
Check the validator status after the unbondig in the integration tests

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/257)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/257)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/testing/staking.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/257#-NGvLKaf4PYniGcaV-oE:-NGvLKaf4PYniGcaV-oF:b-ruqyts) ([raw file](https://github.com/coreumfoundation/coreum/blob/187633690e5ee4a31a27e480c69c94182a9d56b0/integration-tests/testing/staking.go#L50)):*
> ```Go
> 	)
> 	if err != nil {
> 		return nil, nil, nil, errors.WithStack(err)
> ```

you don't need stack here, `tx.BroadcastTx` is our function and stack is already there

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/257)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/staking.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/257#-NGvLKaf4PYniGcaV-oE:-NGvNC_tE6x2cbQKPVds:bnyc6sv) ([raw file](https://github.com/coreumfoundation/coreum/blob/187633690e5ee4a31a27e480c69c94182a9d56b0/integration-tests/testing/staking.go#L50)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you don't need stack here, `tx.BroadcastTx` is our function and stack is already there
</blockquote></details>

Agree, remove.



_Code quote:_
```Go
logger.Get(ctx).Info("Validator creation executed", zap.String("txHash"
```

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/257)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/257)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
