### PR TITLE
Enable deterministic gas

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/615)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/615)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/615#-NcRyFfdCRWzmKW4ORsw:-NcRyFfdCRWzmKW4ORsx:bwa41qx) (no related file):*
Recalculation of gas limits for messages will be handled separately

___

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/615)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 310 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/615#-NcS3Jn_011ZN-ZHJn1q:-NcS3Jn_011ZN-ZHJn1r:b8snn5v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c7e0e991f6f97af152e43c525add6b4cead7282/app/app.go#L310)):*
> ```Go
> 	bApp.SetVersion(version.Version)
> 	bApp.SetInterfaceRegistry(interfaceRegistry)
> 	// bApp.SetRouter(deterministicgastypes.NewDeterministicGasRouter(bApp.Router(), deterministicGasConfig))  // FIXME(v47-deterministic) enable router
> ```

Question: if we remove the old router, then how do we intercept and enforce (override) our gas policy ?
___
*[`integration-tests/modules/bank_test.go` line 358 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/615#-NcS2yJB3PUkeYP-6nQr:-NcS2yJB3PUkeYP-6nQs:b-6utmi5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d551378b83b1a290e2c70d2c7ef12d29b9fbf08e/integration-tests/modules/bank_test.go#L358)):*
> ```Go
> 		chain.TxFactory().
> 			WithGas(bankSendGas-1). // gas less than expected
> 			WithGas(1),             // gas less than expected
> ```

this seems off, `WithGas(1)` should be removed probably.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/615)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`app/app.go` line 310 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/615#-NcS3Jn_011ZN-ZHJn1q:-NcWSyKD29z0_XilSlG8:b-8ilzuq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0c7e0e991f6f97af152e43c525add6b4cead7282/app/app.go#L310)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Question: if we remove the old router, then how do we intercept and enforce (override) our gas policy ?
</blockquote></details>

In v0.47 the entire router concept is removed. So everything goes through services.
___
*[`integration-tests/modules/bank_test.go` line 358 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/615#-NcS2yJB3PUkeYP-6nQr:-NcWTaKc1ZFZqsHLi5w4:b-tqj6nh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d551378b83b1a290e2c70d2c7ef12d29b9fbf08e/integration-tests/modules/bank_test.go#L358)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this seems off, `WithGas(1)` should be removed probably.
</blockquote></details>

good catch, done

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/615)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/615)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @vertex451)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/615)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @vertex451)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/615)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @vertex451)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/615)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @vertex451)

**Pull request merged**
