### PR TITLE
renamed Balance type to Coin

### PR DESCRIPTION
**Pull request by miladz68**
Rename Balance type to Coin. This change was already introduced in crust repository but since we are moving types and client to Coreum, this needs to be here as well.

---
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/114)

### CODE REVIEW

**Review by oliverasistemas — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/114)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum, @xlab, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/114)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @xlab)

___
*[`pkg/types/types.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/114#-N7umQW0ABZyUlFDfTTO:-N7umQW0ABZyUlFDfTTP:b-7suz0v) ([raw file](https://github.com/coreumfoundation/coreum/blob/31f4708f531f25647ff082e7b4c6b6b9a8a2da14/pkg/types/types.go#L44)):*
> ```Go
> 
> // Validate validates data inside coin
> func (c Coin) Validate() error {
> ```

I really don't like to have Validate method. Everyone don't want / forgets to call it. It also looks a bit strange mostly

What do you think about introducing using `func NewCoind(amount, denom) instead ?
How is it done in Cosmos ? As for my practice I used this pkg a bit and there it is initialized as .New also

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/114)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/types/types.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/114#-N7umQW0ABZyUlFDfTTO:-N7uqL1gAvZABsEiDn0h:b-4ieo4b) ([raw file](https://github.com/coreumfoundation/coreum/blob/31f4708f531f25647ff082e7b4c6b6b9a8a2da14/pkg/types/types.go#L44)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I really don't like to have Validate method. Everyone don't want / forgets to call it. It also looks a bit strange mostly

What do you think about introducing using `func NewCoind(amount, denom) instead ?
How is it done in Cosmos ? As for my practice I used this pkg a bit and there it is initialized as .New also
</blockquote></details>

You are correct Yaroslav. I copied code from wojtek's code without much thinking.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/114)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/types/types.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/114#-N7umQW0ABZyUlFDfTTO:-N7uqaqW7gQ81GRQooOy:b-yv9pcw) ([raw file](https://github.com/coreumfoundation/coreum/blob/31f4708f531f25647ff082e7b4c6b6b9a8a2da14/pkg/types/types.go#L44)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

You are correct Yaroslav. I copied code from wojtek's code without much thinking.
</blockquote></details>

could you change it to non blocking plz ?

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/114)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @oliverasistemas, @wojtek-coreum, and @xlab)

___
*[`pkg/types/types.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/114#-N7umQW0ABZyUlFDfTTO:-N7zqnUc0M9qq7zw3G4r:b-4x7u4g) ([raw file](https://github.com/coreumfoundation/coreum/blob/31f4708f531f25647ff082e7b4c6b6b9a8a2da14/pkg/types/types.go#L44)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

could you change it to non blocking plz ?
</blockquote></details>

Ok resolving this for now.
But pls discuss with Wojtek and make the changes

**Pull request merged**
