### PR TITLE
Implement integration tests for upgrade checking params migration

### PR DESCRIPTION
**Pull request by ysv**
# Description

This PR adds integration tests verifying that all params were properly migrated from old `x/params` to standalone modules.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/635)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/635)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`integration-tests/gov.go` line 267 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/635#-NdYsNGn3YT3PJyZIk0A:-NdYsNGn3YT3PJyZIk0B:b-4epr2b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e899e2cff7f952d53dca1ce1820b02b963963941/integration-tests/gov.go#L267)):*
> ```Go
> func (g Governance) QueryGovParams(ctx context.Context) (*govtypesv1.Params, error) {
> 	govParams, err := g.govClient.Params(ctx, &govtypesv1.QueryParamsRequest{
> 		ParamsType: govtypesv1.ParamTallying, // strange decision by cosmos. Even though it always returns all params (inside Params field) ParamsType is still required (probably legacy from v45).
> ```

Do we need that comment here?
___
*[`integration-tests/upgrade/params_migration_test.go` line 162 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/635#-NdYtLmYAPw19pgta5VH:-NdYtLmYAPw19pgta5VI:bh6x6xd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e899e2cff7f952d53dca1ce1820b02b963963941/integration-tests/upgrade/params_migration_test.go#L162)):*
> ```Go
> 	distrResp, err := distrtypes.NewQueryClient(chain.ClientContext).Params(ctx, &distrtypes.QueryParamsRequest{})
> 	requireT.NoError(err)
> 	assertT.False(pmt.distrParamsBeforeMigration.BaseProposerReward.IsZero())  //nolint:staticcheck
> ```

Why don't you compare the before/after params here?
___
*[`integration-tests/upgrade/params_migration_test.go` line 187 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/635#-NdYu6Lg7mBSqQlHeSJQ:-NdYu6Lg7mBSqQlHeSJR:b-1ak2bi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e899e2cff7f952d53dca1ce1820b02b963963941/integration-tests/upgrade/params_migration_test.go#L187)):*
> ```Go
> 
> 	// wasm
> 	wasmResp, err := wasmtypes.NewQueryClient(chain.ClientContext).Params(ctx, &wasmtypes.QueryParamsRequest{})
> ```

Of top question: sorry missed that last time. Did the wasm migrate to the new way of the params storing?

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/635)* status: all files reviewed, 3 unresolved discussions (waiting on @vertex451, @wojtek-coreum, and @ysv)

**Review by ysv — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/635)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @vertex451, and @wojtek-coreum)

___
*[`integration-tests/gov.go` line 267 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/635#-NdYsNGn3YT3PJyZIk0A:-NdZdgYa7jyf349LDEFb:b-u69gnc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e899e2cff7f952d53dca1ce1820b02b963963941/integration-tests/gov.go#L267)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do we need that comment here?
</blockquote></details>

yes left it in purpose 
Because the behaviour is strange & was unobvious for me

I can remove if you prefer
___
*[`integration-tests/upgrade/params_migration_test.go` line 162 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/635#-NdYtLmYAPw19pgta5VH:-NdZdtBrAH68joM6Qqkc:b-tcy1bt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e899e2cff7f952d53dca1ce1820b02b963963941/integration-tests/upgrade/params_migration_test.go#L162)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't you compare the before/after params here?
</blockquote></details>

I do compare them a few lines below `assertT.Equal(pmt.distrParamsBeforeMigration, distrResp.Params)`

Since some prams are deprecated I can't compare them as they are but need to override
___
*[`integration-tests/upgrade/params_migration_test.go` line 187 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/635#-NdYu6Lg7mBSqQlHeSJQ:-NdZe8Zr7zpVa75KTrOi:bju9rop) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e899e2cff7f952d53dca1ce1820b02b963963941/integration-tests/upgrade/params_migration_test.go#L187)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Yep, they do it in `Migrate3to4`
</blockquote></details>

txh Wojtek

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/635)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451 and @wojtek-coreum)

___
*[`integration-tests/upgrade/params_migration_test.go` line 187 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/635#-NdYu6Lg7mBSqQlHeSJQ:-Nd_3gejDIrMkxWOCTo8:b-ucfkn4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e899e2cff7f952d53dca1ce1820b02b963963941/integration-tests/upgrade/params_migration_test.go#L187)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

txh Wojtek
</blockquote></details>

Thanks.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/635)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451 and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/635)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
