### PR TITLE
Query gas price if auto is set on the flag

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`cmd/cored/cosmoscmd/gas_price.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NJeA5j06dHGiCp0Q9Qm:-NJeA5j06dHGiCp0Q9Qn:bgx2s7l) ([raw file](https://github.com/coreumfoundation/coreum/blob/2981ef63798098f0e522b57016a24ad5dba282f8/cmd/cored/cosmoscmd/gas_price.go#L24)):*
> ```Go
> 
> func queryGasPriceRunE(cmd *cobra.Command, args []string) error {
> 	if flag := cmd.LocalFlags().Lookup(flags.FlagGasPrices); flag != nil && flag.Changed && flag.Value.String() == "auto" {
> ```

Haw about the `constant` for that falg value?
___
*[`x/feemodel/client/cli/query.go` line 56 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NJeAKib-Lo4VJoILmL4:-NJeAKib-Lo4VJoILmL5:b-z7xrci) ([raw file](https://github.com/coreumfoundation/coreum/blob/2981ef63798098f0e522b57016a24ad5dba282f8/x/feemodel/client/cli/query.go#L56)):*
> ```Go
> 
> // QueryGasPriceHelper queries the gas price
> func QueryGasPriceHelper(cmd *cobra.Command) (*types.QueryMinGasPriceResponse, error) {
> ```

Why it's called `Helper`, is it a sdk pattern ?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`cmd/cored/cosmoscmd/gas_price.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NJeA5j06dHGiCp0Q9Qm:-NJjoYQh1ToLn9D-fPL4:b-ynu226) ([raw file](https://github.com/coreumfoundation/coreum/blob/2981ef63798098f0e522b57016a24ad5dba282f8/cmd/cored/cosmoscmd/gas_price.go#L24)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Haw about the `constant` for that falg value?
</blockquote></details>

removed that part as discussed in the call
___
*[`x/feemodel/client/cli/query.go` line 56 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NJeAKib-Lo4VJoILmL4:-NJjiKHr6tzumwwW__0b:b-2l8krj) ([raw file](https://github.com/coreumfoundation/coreum/blob/2981ef63798098f0e522b57016a24ad5dba282f8/x/feemodel/client/cli/query.go#L56)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why it's called `Helper`, is it a sdk pattern ?
</blockquote></details>

it is not a pattern, removed the helper.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

___
*[`cmd/cored/cosmoscmd/gas_price.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NJeA5j06dHGiCp0Q9Qm:-NJjp7YQEQ4YWqcMkOD5:b-xn3s7b) ([raw file](https://github.com/coreumfoundation/coreum/blob/2981ef63798098f0e522b57016a24ad5dba282f8/cmd/cored/cosmoscmd/gas_price.go#L24)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

removed that part as discussed in the call
</blockquote></details>

But we aligin to make it auto in case you provide the "auto" as value from or don't provide the value at all.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`cmd/cored/cosmoscmd/gas_price.go` line 38 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NJnr1C_EgWt7WW-PR97:-NJnr1C_EgWt7WW-PR98:b-dp79tj) ([raw file](https://github.com/coreumfoundation/coreum/blob/0152864c181dd10b531ce7d587dd7d3cea2fd86b/cmd/cored/cosmoscmd/gas_price.go#L38)):*
> ```Go
> 
> func addQueryGasPriceToAllLeafs(cmd *cobra.Command) {
> 	if !cmd.HasSubCommands() {
> ```

I don't know if there are such cases in cosmos sdk but in genera, command may have both subcommands and it's own Run handler
___
*[`cmd/cored/cosmoscmd/gas_price.go` line 39 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NJnrAA85l_u5sEvt3kg:-NJnrAA85l_u5sEvt3kh:b-rsu05y) ([raw file](https://github.com/coreumfoundation/coreum/blob/0152864c181dd10b531ce7d587dd7d3cea2fd86b/cmd/cored/cosmoscmd/gas_price.go#L39)):*
> ```Go
> func addQueryGasPriceToAllLeafs(cmd *cobra.Command) {
> 	if !cmd.HasSubCommands() {
> 		cmd.PreRunE = mergeRunEs(queryGasPriceRunE, cmd.PreRunE)
> ```

Are you sure that everything in cosmos uses only PreRunE?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`cmd/cored/cosmoscmd/gas_price.go` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NJeA5j06dHGiCp0Q9Qm:-NJnx3R_4i_1k41Fz6M7:bs7wumx) ([raw file](https://github.com/coreumfoundation/coreum/blob/2981ef63798098f0e522b57016a24ad5dba282f8/cmd/cored/cosmoscmd/gas_price.go#L24)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But we aligin to make it auto in case you provide the "auto" as value from or don't provide the value at all. 
</blockquote></details>

Done. 
___
*[`cmd/cored/cosmoscmd/gas_price.go` line 38 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NJnr1C_EgWt7WW-PR97:-NJnxVjQ0EccjIRrH38f:b44ox6n) ([raw file](https://github.com/coreumfoundation/coreum/blob/0152864c181dd10b531ce7d587dd7d3cea2fd86b/cmd/cored/cosmoscmd/gas_price.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't know if there are such cases in cosmos sdk but in genera, command may have both subcommands and it's own Run handler
</blockquote></details>

I changed the condition to check that either Run or RunE is not nil.
___
*[`cmd/cored/cosmoscmd/gas_price.go` line 39 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NJnrAA85l_u5sEvt3kg:-NJnvbIC5egBnemUOrdW:b-e3qa5p) ([raw file](https://github.com/coreumfoundation/coreum/blob/0152864c181dd10b531ce7d587dd7d3cea2fd86b/cmd/cored/cosmoscmd/gas_price.go#L39)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Are you sure that everything in cosmos uses only PreRunE?
</blockquote></details>

I am not sure, and I don't need to be, PreRunE is always run before Run and RunE, so before the real command is run, gas prices are fetched and set.

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NJzc_IW8EOQeFo92IRa:-NJzc_IW8EOQeFo92IRb:b-foldm6) (no related file):*
Looks good for me in terms of implementation & code
But blocking it for now before @silverspase reviews & tests it

___
___
*[`cmd/cored/cosmoscmd/root.go` line 247 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NJzclcCABhJr-FQkoLx:-NJzclcCABhJr-FQkoLy:b-92lxfn) ([raw file](https://github.com/coreumfoundation/coreum/blob/514db439f411fd84b516cb67cd8a30e082ec1552/cmd/cored/cosmoscmd/root.go#L247)):*
> ```Go
> 
> 	moduleBasics.AddTxCommands(cmd)
> 	addQueryGasPriceToAllLeafs(cmd)
> ```

minor:
it would be nice to add a comment here or near `addQueryGasPriceToAllLeafs` func

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @miladz68)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NKEEm258lhOMKigE4ZC:-NKEEm258lhOMKigE4ZD:b-lolcwp) (no related file):*
To avoid @silverspase testing this manually we should add unit/integration tests for this CLI behaviour

___

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NJzc_IW8EOQeFo92IRa:-NKISaB15PJU7SbOSij9:blolam7) (no related file):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

Here are my testing results:
</blockquote></details>

added automated tests, please review and check again. 

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NKEEm258lhOMKigE4ZC:-NKIRghwD8V_b2VuZjGt:bq3jnj0) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

To avoid @silverspase testing this manually we should add unit/integration tests for this CLI behaviour
</blockquote></details>

added tests

___
___
*[`cmd/cored/cosmoscmd/root.go` line 247 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NJzclcCABhJr-FQkoLx:-NKISPLvAN9pgcX1C9xf:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/d8623f5e90a22e0308e7e0a6d2c340d91ee76759/cmd/cored/cosmoscmd/root.go#L247)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
it would be nice to add a comment here or near `addQueryGasPriceToAllLeafs` func
</blockquote></details>

Done

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`cmd/cored/cosmoscmd/gas_price_test.go` line 33 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NKIeepy4I9NbTpNqkRD:-NKIeepy4I9NbTpNqkRE:b-t9vx4h) ([raw file](https://github.com/coreumfoundation/coreum/blob/8249f355e22abad654cde492b9d6dc89c0dc85aa/cmd/cored/cosmoscmd/gas_price_test.go#L33)):*
> ```Go
> 			flags: []string{},
> 			feeAssertion: func(t *testing.T, fee sdk.Coins) {
> 				require.True(t, !fee.IsZero())
> ```

`require.False(t, fee.IsZero())
___
*[`cmd/cored/cosmoscmd/gas_price_test.go` line 33 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NKIf8WgAmFu0dFqKJxE:-NKIf8WgAmFu0dFqKJxF:b-vv1nti) ([raw file](https://github.com/coreumfoundation/coreum/blob/8249f355e22abad654cde492b9d6dc89c0dc85aa/cmd/cored/cosmoscmd/gas_price_test.go#L33)):*
> ```Go
> 			flags: []string{},
> 			feeAssertion: func(t *testing.T, fee sdk.Coins) {
> 				require.True(t, !fee.IsZero())
> ```

let's use assert to test other cases even if one of them fails
___
*[`cmd/cored/cosmoscmd/gas_price_test.go` line 51 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NKIevgW8PG6EacjpptU:-NKIevgW8PG6EacjpptV:b3pk4og) ([raw file](https://github.com/coreumfoundation/coreum/blob/8249f355e22abad654cde492b9d6dc89c0dc85aa/cmd/cored/cosmoscmd/gas_price_test.go#L51)):*
> ```Go
> 		},
> 		{
> 			name:  "specific gas prices are provided",
> ```

same test twice?
___
*[`cmd/cored/cosmoscmd/gas_price_test.go` line 58 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NKIf-EK2Oip3MbF6X7P:-NKIf-EK2Oip3MbF6X7Q:b-muuofg) ([raw file](https://github.com/coreumfoundation/coreum/blob/8249f355e22abad654cde492b9d6dc89c0dc85aa/cmd/cored/cosmoscmd/gas_price_test.go#L58)):*
> ```Go
> 		},
> 		{
> 			name:  "specific gas prices are provided",
> ```

here fee is provided

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NKIfhIlEXl53JDDwS5I:-NKIfhIm9Fk0SvEyjO-0:bdlczv4) (no related file):*
Looks good overall
Agree with all Wojtek's comments
Pls fix them

___

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @wojtek-coreum and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NKIfhIlEXl53JDDwS5I:-NKIkw4E0akiXayiZcjz:b-896fix) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Looks good overall
Agree with all Wojtek's comments
Pls fix them
</blockquote></details>

Done.

___
___
*[`cmd/cored/cosmoscmd/gas_price_test.go` line 33 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NKIeepy4I9NbTpNqkRD:-NKIkTFq4jsuuI7jR_Ti:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/8249f355e22abad654cde492b9d6dc89c0dc85aa/cmd/cored/cosmoscmd/gas_price_test.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`require.False(t, fee.IsZero())
</blockquote></details>

Done.
___
*[`cmd/cored/cosmoscmd/gas_price_test.go` line 33 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NKIf8WgAmFu0dFqKJxE:-NKIkU8M8ZdxMatJRzcS:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/8249f355e22abad654cde492b9d6dc89c0dc85aa/cmd/cored/cosmoscmd/gas_price_test.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

let's use assert to test other cases even if one of them fails
</blockquote></details>

Done.
___
*[`cmd/cored/cosmoscmd/gas_price_test.go` line 51 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NKIevgW8PG6EacjpptU:-NKIku33DO4lMsgEx-7B:ba3dfob) ([raw file](https://github.com/coreumfoundation/coreum/blob/8249f355e22abad654cde492b9d6dc89c0dc85aa/cmd/cored/cosmoscmd/gas_price_test.go#L51)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

same test twice?
</blockquote></details>

Removed
___
*[`cmd/cored/cosmoscmd/gas_price_test.go` line 58 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/299#-NKIf-EK2Oip3MbF6X7P:-NKIkv4EDO9-YwvEKmXO:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/8249f355e22abad654cde492b9d6dc89c0dc85aa/cmd/cored/cosmoscmd/gas_price_test.go#L58)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

here fee is provided
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: all files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/299)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
