### PR TITLE
Add all new `With` options to client context

### PR DESCRIPTION
**Pull request by ysv**
# Description

This PR adds all new options for client context introduced in cosmos SDK v47. 

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/627)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/627)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @vertex451, and @wojtek-coreum)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/627)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @vertex451, and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/627)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, and @ysv)

___
*[`pkg/client/context.go` line 183 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/627#-Ncw2BpA8k28wgzDTjll:-Nd--qTO9RVkt-06ma1R:bfmii4o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f11974ce84a9c92012f8852d5abf48cc7e7dd0da/pkg/client/context.go#L183)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

cosmos sdk doesn't have this method but it uses WithClient instead
IMO we Should deprecated this one also
</blockquote></details>

But we want to be able to set bothRPC and GRPC clients, no?

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/627)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451 and @wojtek-coreum)

___
*[`pkg/client/context.go` line 183 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/627#-Ncw2BpA8k28wgzDTjll:-Nd-RMmJDwPn-o27TQNS:bqa9jjw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f11974ce84a9c92012f8852d5abf48cc7e7dd0da/pkg/client/context.go#L183)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But we want to be able to set bothRPC and GRPC clients, no?
</blockquote></details>

@wojtek-coreum WithClient sets RPC and WithGRPCClient set gRPC. 
___
*[`pkg/client/context.go` line 420 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/627#-Nd-PxQq8mDGqqqI8Mt6:-Nd-PxQq8mDGqqqI8Mt7:b-1w5dwe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/18ccc7162603a65367b1a2f953318ea90bff8c0e/pkg/client/context.go#L420)):*
> ```Go
> // WithPreprocessTxHook returns the context with the provided preprocessing hook, which
> // enables chains to preprocess the transaction using the builder.
> func (c Context) WithPreprocessTxHook(preprocessFn client.PreprocessTxFn) Context {
> ```

With this new addition, we maybe able to get rid of our hack introduced to query gas price in CLI.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/627)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451 and @wojtek-coreum)

___
*[`pkg/client/context.go` line 183 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/627#-Ncw2BpA8k28wgzDTjll:-Nd-aSIZ-cNsvh_rZBRQ:b-nnzavi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f11974ce84a9c92012f8852d5abf48cc7e7dd0da/pkg/client/context.go#L183)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@wojtek-coreum WithClient sets RPC and WithGRPCClient set gRPC.
</blockquote></details>

Milad is right
Thx
___
*[`pkg/client/context.go` line 420 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/627#-Nd-PxQq8mDGqqqI8Mt6:-Nd-_xwbDxjF1SGf2Eyg:bjq1jvj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/18ccc7162603a65367b1a2f953318ea90bff8c0e/pkg/client/context.go#L420)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

With this new addition, we maybe able to get rid of our hack introduced to query gas price in CLI.
</blockquote></details>

reasonable point
I will create follow up task

**Pull request merged**
