### PR TITLE
Divide authz into 3 contracts

### PR DESCRIPTION
**Pull request by keyleu**
# Description

Divide the current authz contract into 3 different contracts: one for testing transfer, one for NFT trades and one for stargate operations.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/762)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/762)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 859 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/762#-Nnbfbq3DVBZXyYrD8AL:-Nnbfbq3DVBZXyYrD8AM:b-8kfw7s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/287a74cfecd5010d79c54b7ed65f9bf3903c8db1/integration-tests/modules/wasm_test.go#L859)):*
> ```Go
> 	)
> 	require.NoError(t, err)
> 	requireT.Equal(chain.GasLimitByMsgs(grantMsg), uint64(txResult.GasUsed))
> ```

Why do you need to check that here? IMO if we have tested the deperministic gas in different test, then no need to repeat that check.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/762)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 859 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/762#-Nnbfbq3DVBZXyYrD8AL:-NncJoCD-QVh5PppGhpF:b-wwerrc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/287a74cfecd5010d79c54b7ed65f9bf3903c8db1/integration-tests/modules/wasm_test.go#L859)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need to check that here? IMO if we have tested the deperministic gas in different test, then no need to repeat that check.
</blockquote></details>

Right, removed it.

**Review by ysv — APPROVED** [review]
> Reviewed 23 of 24 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/762)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/762)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/762)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Pull request merged**
