### PR TITLE
Design of proto for whitelisting

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)

### CODE REVIEW

**Review by miladz68 — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/v1/asset.proto` line 10 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/255#-NGuxSJaDVabOLroLyYI:-NGuxSJaDVabOLroLyYJ:bd5sckz) ([raw file](https://github.com/coreumfoundation/coreum/blob/8d617b284f058822b5ff6710905aed1eeeace897/proto/coreum/asset/v1/asset.proto#L10)):*
> ```protobuf
> enum FungibleTokenFeature {
>   freezable = 0 [(gogoproto.enumvalue_customname) = "freezable"];
>   whitelistable = 0 [(gogoproto.enumvalue_customname) = "whitelistable"];
> ```

This must be incremented to 1.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/v1/asset.proto` line 10 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/255#-NGvM_z90miaOPEAoJIq:-NGvM_z90miaOPEAoJIr:b21s7np) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c6d162ac3a68aceaa0f41dc810639192ed03efd/proto/coreum/asset/v1/asset.proto#L10)):*
> ```protobuf
> enum FungibleTokenFeature {
>   freezable = 0 [(gogoproto.enumvalue_customname) = "freezable"];
>   whitelistable = 1 [(gogoproto.enumvalue_customname) = "whitelistable"];
> ```

remove the custom name tag `[(gogoproto.enumvalue_customname) = "whitelistable"]`. It is actually not needed. I added it since there was lowercase/uppercase conflict which we later decided to use lowercase everywhere.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`proto/coreum/asset/v1/asset.proto` line 10 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/255#-NGvM_z90miaOPEAoJIq:-NHOD9bg5f_YZHn2oDEl:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/6c6d162ac3a68aceaa0f41dc810639192ed03efd/proto/coreum/asset/v1/asset.proto#L10)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

remove the custom name tag `[(gogoproto.enumvalue_customname) = "whitelistable"]`. It is actually not needed. I added it since there was lowercase/uppercase conflict which we later decided to use lowercase everywhere. 
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum)

___
*[`proto/coreum/asset/v1/asset.proto` line 10 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/255#-NHPItzr7rn_WwLyvyJJ:-NHPItzr7rn_WwLyvyJK:b-16azje) ([raw file](https://github.com/coreumfoundation/coreum/blob/48c31e8fbe09cb2a6b817bce68049a190b9a5102/proto/coreum/asset/v1/asset.proto#L10)):*
> ```protobuf
> enum FungibleTokenFeature {
>   freezable = 0 [(gogoproto.enumvalue_customname) = "freezable"];
>   whitelistable = 1 [(gogoproto.enumvalue_customname) = "whitelistable"];
> ```

I start to not like these `...able` names we construct for these features
Maybe we should rename all of them to: freeze, whitelist, burn or freezing, whitelisting, burning etc ?

WDYT @dzmitryhil @wojtek-coreum @miladz68 
___
*[`proto/coreum/asset/v1/genesis.proto` line 23 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/255#-NHPKMNt2wmCOLjdZkjg:-NHPKMNt2wmCOLjdZkjh:biyv59f) ([raw file](https://github.com/coreumfoundation/coreum/blob/48c31e8fbe09cb2a6b817bce68049a190b9a5102/proto/coreum/asset/v1/genesis.proto#L23)):*
> ```protobuf
> 
>   // token_definitions keep the fungible token state
>   repeated FungibleTokenDefinition token_definitions  = 1 [(gogoproto.nullable) = false];
> ```

still don't like token_definitions name here
___
*[`proto/coreum/asset/v1/tx.proto` line 61 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/255#-NHPL53ZAeS8vz5e6ECZ:-NHPL53_0A7JFpRX0fzt:b-olq4mp) ([raw file](https://github.com/coreumfoundation/coreum/blob/48c31e8fbe09cb2a6b817bce68049a190b9a5102/proto/coreum/asset/v1/tx.proto#L61)):*
> ```protobuf
> //
> // We decided to whitelist using absolute amounts.
> message MsgSetWhitelistLimitFungibleToken {
> ```

we use Whitelisted in most places E.g in Event name should it be Whitelisted here also ?

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`proto/coreum/asset/v1/asset.proto` line 10 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/255#-NHPItzr7rn_WwLyvyJJ:-NHPVlwr4rnwvLP61v8h:b-xbzexi) ([raw file](https://github.com/coreumfoundation/coreum/blob/48c31e8fbe09cb2a6b817bce68049a190b9a5102/proto/coreum/asset/v1/asset.proto#L10)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I start to not like these `...able` names we construct for these features
Maybe we should rename all of them to: freeze, whitelist, burn or freezing, whitelisting, burning etc ?

WDYT @dzmitryhil @wojtek-coreum @miladz68 
</blockquote></details>

I would use nouns instead of adjectives: whitelisting, freezing, minting, burning
___
*[`proto/coreum/asset/v1/genesis.proto` line 23 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/255#-NHPKMNt2wmCOLjdZkjg:-NHPVY1oA-4b6T86JuKI:bhwh5yh) ([raw file](https://github.com/coreumfoundation/coreum/blob/48c31e8fbe09cb2a6b817bce68049a190b9a5102/proto/coreum/asset/v1/genesis.proto#L23)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

still don't like token_definitions name here
</blockquote></details>

I took it from master... let's discuss if it should be renamed

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/v1/asset.proto` line 10 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/255#-NHPItzr7rn_WwLyvyJJ:-NHPbf528pplGfCb4_S8:bikywx5) ([raw file](https://github.com/coreumfoundation/coreum/blob/48c31e8fbe09cb2a6b817bce68049a190b9a5102/proto/coreum/asset/v1/asset.proto#L10)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would use nouns instead of adjectives: whitelisting, freezing, minting, burning
</blockquote></details>

I agree, let's keep freeze only

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

___
*[`proto/coreum/asset/v1/asset.proto` line 10 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/255#-NHPItzr7rn_WwLyvyJJ:-NHQH1Gm-EM0ndEE1o-D:bfpc7t6) ([raw file](https://github.com/coreumfoundation/coreum/blob/48c31e8fbe09cb2a6b817bce68049a190b9a5102/proto/coreum/asset/v1/asset.proto#L10)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I agree, let's keep freeze only 
</blockquote></details>

resovling will discuss during planning

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`proto/coreum/asset/v1/tx.proto` line 61 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/255#-NHPL53ZAeS8vz5e6ECZ:-NHTUM9h3CHqB_oP0mRQ:b-z9sxbw) ([raw file](https://github.com/coreumfoundation/coreum/blob/48c31e8fbe09cb2a6b817bce68049a190b9a5102/proto/coreum/asset/v1/tx.proto#L61)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

we use Whitelisted in most places E.g in Event name should it be Whitelisted here also ?
</blockquote></details>

Not sure, the message name describes the purpose accurately

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request closed without merging**
