### PR TITLE
Add the CORE denom metadata to the genesis

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/config/genesis/genesis.tmpl.json` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEdwB-5AarO1KtVD74V:-NEdwB-5AarO1KtVD74W:b-6vtsfc) ([raw file](https://github.com/coreumfoundation/coreum/blob/5843b443c728d9609bb035eb1e603d17f498ee05/pkg/config/genesis/genesis.tmpl.json#L52)):*
> ```JSON
>       "denom_metadata": [
>         {
>           "description": "CORE coin",
> ```

dCORE on devnet?
___
*[`pkg/config/genesis/genesis.tmpl.json` line 60 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEdw5039W5L1e0jRkMi:-NEdw5039W5L1e0jRkMj:b-p3lp6f) ([raw file](https://github.com/coreumfoundation/coreum/blob/5843b443c728d9609bb035eb1e603d17f498ee05/pkg/config/genesis/genesis.tmpl.json#L60)):*
> ```JSON
>             },
>             {
>               "denom": "core",
> ```

It should be taken from network config because on devnet we should use `dcore`
___
*[`pkg/config/genesis/genesis.tmpl.json` line 66 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEdwF7A0ZLvBF6S2EPG:-NEdwF7A0ZLvBF6S2EPH:bbsc213) ([raw file](https://github.com/coreumfoundation/coreum/blob/5843b443c728d9609bb035eb1e603d17f498ee05/pkg/config/genesis/genesis.tmpl.json#L66)):*
> ```JSON
>           ],
>           "base": "{{ .TokenSymbol }}",
>           "display": "core",
> ```

dcore on devnet
___
*[`pkg/config/genesis/genesis.tmpl.json` line 67 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEdwGl_-CXFpxnwyqZz:-NEdwGl_-CXFpxnwyq_-:b9jxknv) ([raw file](https://github.com/coreumfoundation/coreum/blob/5843b443c728d9609bb035eb1e603d17f498ee05/pkg/config/genesis/genesis.tmpl.json#L67)):*
> ```JSON
>           "base": "{{ .TokenSymbol }}",
>           "display": "core",
>           "name": "CORE",
> ```

here and below, dCORE on devnet

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`pkg/config/genesis/genesis.tmpl.json` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEdwB-5AarO1KtVD74V:-NEeDGS2CW6D6y5tYHUZ:bnqtvry) ([raw file](https://github.com/coreumfoundation/coreum/blob/5843b443c728d9609bb035eb1e603d17f498ee05/pkg/config/genesis/genesis.tmpl.json#L52)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

dCORE on devnet?
</blockquote></details>

On the explorer we use the CORE, that's why I use the core as well. 
And we don't have such constants yet.
So @miladz68 @wojtek-coreum should we include the new constant or use the CORE on each env and prefixed values for the real denoms?

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`pkg/config/genesis/genesis.tmpl.json` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEdwB-5AarO1KtVD74V:-NEeKYbw3g0U2QAvmmLP:b244eqh) ([raw file](https://github.com/coreumfoundation/coreum/blob/5843b443c728d9609bb035eb1e603d17f498ee05/pkg/config/genesis/genesis.tmpl.json#L52)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

On the explorer we use the CORE, that's why I use the core as well. 
And we don't have such constants yet.
So @miladz68 @wojtek-coreum should we include the new constant or use the CORE on each env and prefixed values for the real denoms?
</blockquote></details>

I think we should include them from the get go, there is no reason to wait since they will be done and we are touching it here. 
___
*[`pkg/config/genesis/genesis.tmpl.json` line 60 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEdw5039W5L1e0jRkMi:-NEeKkE-CCMshYra7dCi:b4c9lyr) ([raw file](https://github.com/coreumfoundation/coreum/blob/5843b443c728d9609bb035eb1e603d17f498ee05/pkg/config/genesis/genesis.tmpl.json#L60)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It should be taken from network config because on devnet we should use `dcore`
</blockquote></details>

:thumbsup:

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/config/genesis/genesis.tmpl.json` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEdwB-5AarO1KtVD74V:-NEebXFk3uErvL0tv37X:b-r420w4) ([raw file](https://github.com/coreumfoundation/coreum/blob/5843b443c728d9609bb035eb1e603d17f498ee05/pkg/config/genesis/genesis.tmpl.json#L52)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think we should include them from the get go, there is no reason to wait since they will be done and we are touching it here. 
</blockquote></details>

Updated. Also renames the constants to folloow the same pattern and cosmo specific.
___
*[`pkg/config/genesis/genesis.tmpl.json` line 60 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEdw5039W5L1e0jRkMi:-NEebc9bClHryaW-PLzC:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/5843b443c728d9609bb035eb1e603d17f498ee05/pkg/config/genesis/genesis.tmpl.json#L60)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

Done.
___
*[`pkg/config/genesis/genesis.tmpl.json` line 66 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEdwF7A0ZLvBF6S2EPG:-NEebcV4CFwvuZtHymdk:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/5843b443c728d9609bb035eb1e603d17f498ee05/pkg/config/genesis/genesis.tmpl.json#L66)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

dcore on devnet
</blockquote></details>

Done.
___
*[`pkg/config/genesis/genesis.tmpl.json` line 67 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEdwGl_-CXFpxnwyqZz:-NEebcw8Baaa8bazYeSp:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/5843b443c728d9609bb035eb1e603d17f498ee05/pkg/config/genesis/genesis.tmpl.json#L67)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

here and below, dCORE on devnet
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: all files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`pkg/config/network.go` line 35 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEfQnjO0MUfv4T9XjM1:-NEfQnjPC2Bh3nF1hUuD:bt5h36s) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d5090b44f91942ba2924d011c4b39199f4a53de/pkg/config/network.go#L35)):*
> ```Go
> // Predefined chains constants
> const (
> 	ChainIDMain       ChainID = "coreum-mainnet-1"
> ```

I would prefer to have global `NetworkConfig` for each network because this is exactly what this struct is for - to group all the settings for network. Now you created set of constants which overrides that concept.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: 14 of 20 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/config/network.go` line 35 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEfQnjO0MUfv4T9XjM1:-NEj2H41Crwsjuyv7BiQ:b-y3hixv) ([raw file](https://github.com/coreumfoundation/coreum/blob/2d5090b44f91942ba2924d011c4b39199f4a53de/pkg/config/network.go#L35)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would prefer to have global `NetworkConfig` for each network because this is exactly what this struct is for - to group all the settings for network. Now you created set of constants which overrides that concept.
</blockquote></details>

Got you, they were created because the Symbol was here. Now I've moved all constants to the NetworkConfig and removed the usage of them.



_Code quote:_
```Go
ChainIDMain
```

**Review by miladz68 — DISMISSED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/testing/network.go` line 38 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEkEbX17JSeVk9VXmpB:-NEkEbX17JSeVk9VXmpC:b-4uk0y) ([raw file](https://github.com/coreumfoundation/coreum/blob/32edb08faa650f8e78bebbcd6a7f9c7489e35dfb/integration-tests/testing/network.go#L38)):*
> ```Go
> 	}
> 
> 	return networkConfig, err
> ```

You also need to remove gentxses and funded accounts because this config is used by crust to create `znet`. Did you test it with `znet`? Do you have corresponding PR for `crust`?
___
*[`integration-tests/testing/network.go` line 38 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEkEm34AuY9L-BHcTu1:-NEkEm34AuY9L-BHcTu2:b-mlo75g) ([raw file](https://github.com/coreumfoundation/coreum/blob/32edb08faa650f8e78bebbcd6a7f9c7489e35dfb/integration-tests/testing/network.go#L38)):*
> ```Go
> 	}
> 
> 	return networkConfig, err
> ```

return `nil` instead of `err`

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/testing/network.go` line 38 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEkEm34AuY9L-BHcTu1:-NEkK-p05pwiUTF6ztZk:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/32edb08faa650f8e78bebbcd6a7f9c7489e35dfb/integration-tests/testing/network.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

return `nil` instead of `err`
</blockquote></details>

Done.



_Code quote:_
```Go
return networkConfig, err
```
___
*[`integration-tests/testing/network.go` line 38 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEkEbX17JSeVk9VXmpB:-NEkK2Wz3xVuYLCg7nIQ:b-czo4wv) ([raw file](https://github.com/coreumfoundation/coreum/blob/32edb08faa650f8e78bebbcd6a7f9c7489e35dfb/integration-tests/testing/network.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You also need to remove gentxses and funded accounts because this config is used by crust to create `znet`. Did you test it with `znet`? Do you have corresponding PR for `crust`?
</blockquote></details>

Didn't get why I need to do it. It's seems out of the scipe for that PR. 
I don't have the crust PR yest.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/testing/network.go` line 38 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEkEbX17JSeVk9VXmpB:-NEkMBprBcCFTR9ntDMm:bi6kvov) ([raw file](https://github.com/coreumfoundation/coreum/blob/32edb08faa650f8e78bebbcd6a7f9c7489e35dfb/integration-tests/testing/network.go#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Didn't get why I need to do it. It's seems out of the scipe for that PR. 
I don't have the crust PR yest.
</blockquote></details>

This network config is used by `znet` and obviously it should not contain validators we set up on real devnet, same for funded accounts. That's why they must be removed from this config.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: 8 of 20 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/testing/network.go` line 38 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEkEbX17JSeVk9VXmpB:-NEkP4dQAI32wMff8BEr:bhy7dkm) ([raw file](https://github.com/coreumfoundation/coreum/blob/32edb08faa650f8e78bebbcd6a7f9c7489e35dfb/integration-tests/testing/network.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This network config is used by `znet` and obviously it should not contain validators we set up on real devnet, same for funded accounts. That's why they must be removed from this config.
</blockquote></details>

https://github.com/CoreumFoundation/crust/pull/131 - the crust PR
I agree they should be remove, but not it the scope of that PR. This PR is about the denoms, but I have to modify the config to get rid of the constants.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/testing/network.go` line 38 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEkEbX17JSeVk9VXmpB:-NEkQ6w24-39g0rf8beE:b2qtt85) ([raw file](https://github.com/coreumfoundation/coreum/blob/32edb08faa650f8e78bebbcd6a7f9c7489e35dfb/integration-tests/testing/network.go#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

https://github.com/CoreumFoundation/crust/pull/131 - the crust PR
I agree they should be remove, but not it the scope of that PR. This PR is about the denoms, but I have to modify the config to get rid of the constants. 

</blockquote></details>

If this PR is merged it will break `znet` - I mean it will work only because `crust` imports older version of cored. I guess the other PR won't pass CI because of this.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: 18 of 20 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/testing/network.go` line 38 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEkEbX17JSeVk9VXmpB:-NEkUQIVAQtAmby6oOlr:b-80fxbn) ([raw file](https://github.com/coreumfoundation/coreum/blob/32edb08faa650f8e78bebbcd6a7f9c7489e35dfb/integration-tests/testing/network.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If this PR is merged it will break `znet` - I mean it will work only because `crust` imports older version of cored. I guess the other PR won't pass CI because of this.
</blockquote></details>

I'll fix the crust soon.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: 18 of 20 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/testing/network.go` line 38 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEkEbX17JSeVk9VXmpB:-NEkXyEcAgGxZj1pVRCU:b-s80gzf) ([raw file](https://github.com/coreumfoundation/coreum/blob/32edb08faa650f8e78bebbcd6a7f9c7489e35dfb/integration-tests/testing/network.go#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I'll fix the crust soon. 
</blockquote></details>

CI passed

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/testing/network.go` line 39 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEkYDSNCBF9WlW6_tDh:-NEkYDSNCBF9WlW6_tDi:b-kb0tkh) ([raw file](https://github.com/coreumfoundation/coreum/blob/eccb3d0fc36d13499664ba9d7762514107da1c95/integration-tests/testing/network.go#L39)):*
> ```Go
> 	}
> 
> 	networkConfig.FundedAccounts = make([]config.FundedAccount, 0)
> ```

just ` = nil` in both places

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/testing/network.go` line 39 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NEkYDSNCBF9WlW6_tDh:-NEkYrobC2Gt0PLf6s7X:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/eccb3d0fc36d13499664ba9d7762514107da1c95/integration-tests/testing/network.go#L39)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

just ` = nil` in both places
</blockquote></details>

Done.



_Code quote:_
```Go
networkConfig.FundedAccounts = make([]config.FundedAccount, 0)
```

**Review by ysv — COMMENTED** [review]
> Reviewed 5 of 18 files at r2, 2 of 6 files at r3, 11 of 12 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/229)* status: all files reviewed, 1 unresolved discussion

___
*[`pkg/config/network.go` line 90 at r7](https://reviewable.io/reviews/coreumfoundation/coreum/229#-NFSncZU1fUbWlgGzqWQ:-NFSncZU1fUbWlgGzqWR:b-qx6s7l) ([raw file](https://github.com/coreumfoundation/coreum/blob/0632c65ff8b5f93a1fe1d7ce42f70651f7c85002/pkg/config/network.go#L90)):*
> ```Go
> 			AddressPrefix: "core",
> 			Denom:         "core",
> 			BaseDenom:     "ucore",
> ```

BaseDenom -> Denom
Denom -> MetadataDisplayDenom

**Pull request merged**
