### PR TITLE
CLI command for upgrading FTs

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/client/cli/tx.go` line 456 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ__7wG5uHG5OmmAr5T:-NZ__7wG5uHG5OmmAr5U:b-wiw9n5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx.go#L456)):*
> ```Go
> // CmdTxUpgradeV1 returns UpgradeV1 cobra command.
> func CmdTxUpgradeV1() *cobra.Command {
> 	const ibcFlag = "ibc-enabled"
> ```

The flag should be located near other flags even if it's the command specific.
___
*[`x/asset/ft/client/cli/tx.go` line 459 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ__GbA7rjVJhEPQklv:-NZ__GbA7rjVJhEPQklw:b1r0xu5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx.go#L459)):*
> ```Go
> 	var ibcEnabled bool
> 	cmd := &cobra.Command{
> 		Use:   "upgrade-v1 [denom] --ibc-enabled=true --from [sender]",
> ```

You %s for flag here and in `Long` example.
___
*[`x/asset/ft/client/cli/tx_test.go` line 333 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_Zfw2DmzbCLBTGxKL:-NZ_ZPA79_cc1YxTCQRp:bep7xx4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L333)):*
> ```Go
> }
> 
> func txError(buf testutil.BufferWriter, err error) error {
> ```

Why not call the `clitestutil.ExecTestCLICmd` inside the function, passing the error here looks ugly.
___
*[`x/asset/ft/client/cli/tx_test.go` line 338 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_ZTELBNg1DKWI37z2:-NZ_ZTELBNg1DKWI37z3:bvg4xk8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L338)):*
> ```Go
> 	}
> 
> 	result := struct {
> ```

This is the `sdk.TxResponse` struct.
___
*[`x/asset/ft/client/cli/tx_test.go` line 351 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_ZsYG1OjPbXx7wKoX:-NZ_ZsYG1OjPbXx7wKoY:bgh4riz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L351)):*
> ```Go
> 	}
> 
> 	return errors.New(result.RawLog)
> ```

Probably for future, but you can decode the error similar like we do int the client to be able check it with the type.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/client/cli/tx.go` line 456 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ__7wG5uHG5OmmAr5T:-NZeBPlUEJsNMKNvnwLz:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx.go#L456)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The flag should be located near other flags even if it's the command specific.
</blockquote></details>

Done.
___
*[`x/asset/ft/client/cli/tx.go` line 459 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ__GbA7rjVJhEPQklv:-NZe7hU29JpI0usG0sLQ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx.go#L459)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You %s for flag here and in `Long` example.
</blockquote></details>

Done.
___
*[`x/asset/ft/client/cli/tx_test.go` line 333 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_Zfw2DmzbCLBTGxKL:-NZeBRtTBge9_0GhcBFz:bjo6ojs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L333)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why not call the `clitestutil.ExecTestCLICmd` inside the function, passing the error here looks ugly.
</blockquote></details>

Actually I like this approach. This trick is used in many go packages to transform the error. Example: https://github.com/samber/lo/blob/master/errors.go#L83
___
*[`x/asset/ft/client/cli/tx_test.go` line 338 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_ZTELBNg1DKWI37z2:-NZe7yUu3R923wzkyRyu:b-9jkdq2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L338)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is the `sdk.TxResponse` struct.
</blockquote></details>

surprisingly, it is not
___
*[`x/asset/ft/client/cli/tx_test.go` line 351 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_ZsYG1OjPbXx7wKoX:-NZeBNja-nVgHm08IXVE:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L351)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Probably for future, but you can decode the error similar like we do int the client to be able check it with the type.
</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/client/cli/tx_test.go` line 333 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_Zfw2DmzbCLBTGxKL:-NZeP0r5AVebeLXs4iHi:b1wkmwu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L333)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Actually I like this approach. This trick is used in many go packages to transform the error. Example: https://github.com/samber/lo/blob/master/errors.go#L83
</blockquote></details>

But you will need to move that function to utils in later tasks, so that util will be more user friendly if it similar to the current. 
___
*[`x/asset/ft/client/cli/tx_test.go` line 338 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_ZTELBNg1DKWI37z2:-NZeP_b_3O4WT7iZnwIR:b-o6zyr5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L338)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

surprisingly, it is not
</blockquote></details>

But all attributes you have in that struct are there as well. What is the difference?

**Review by keyleu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/client/cli/tx.go` line 488 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZeTFRgA3VxTrwrnviA:-NZeTFRgA3VxTrwrnviB:bncafzl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e4f39a65a43d25f49e25ad042eebf703c1a763f4/x/asset/ft/client/cli/tx.go#L488)):*
> ```Go
> 				Sender:     sender.String(),
> 				Denom:      denom,
> 				IbcEnabled: ibcEnabled,
> ```

Shouldn't we actually extract the value of ibcEnabled of the Command first? Won't you always set ibcEnabled to false like this?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/client/cli/tx.go` line 488 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZeTFRgA3VxTrwrnviA:-NZfFeak4exJKb6ERjgS:b697b8y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e4f39a65a43d25f49e25ad042eebf703c1a763f4/x/asset/ft/client/cli/tx.go#L488)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

Shouldn't we actually extract the value of ibcEnabled of the Command first? Won't you always set ibcEnabled to false like this?
</blockquote></details>

`&ibcEnabled` in `cmd.Flags().BoolVar(&ibcEnabled, ` does the magic.
___
*[`x/asset/ft/client/cli/tx_test.go` line 338 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_ZTELBNg1DKWI37z2:-NZfFtIs54Y1pffjGHp7:b-k4qau4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L338)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But all attributes you have in that struct are there as well. What is the difference?
</blockquote></details>

`json.Unmarshal` parses entire struct and it returns an error because of the height. In my struct there is no `Height` so parser ignores it.

**Review by keyleu — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/client/cli/tx_test.go` line 333 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_Zfw2DmzbCLBTGxKL:-NZix9TfES2N3-qPsD-z:b-sl6ql0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L333)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But you will need to move that function to utils in later tasks, so that util will be more user friendly if it similar to the current. 
</blockquote></details>

Or we may use it like this everywhere

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/client/cli/tx_test.go` line 333 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_Zfw2DmzbCLBTGxKL:-NZj8YFcDSualRmpVXGH:b-dyee5t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L333)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Or we may use it like this everywhere
</blockquote></details>

IMO we shouldn't :-) Since you will have 2 lines instead on one. 
___
*[`x/asset/ft/client/cli/tx_test.go` line 338 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_ZTELBNg1DKWI37z2:-NZj9h0v2_UPVif3Ku-J:bjfwnzx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L338)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`json.Unmarshal` parses entire struct and it returns an error because of the height. In my struct there is no `Height` so parser ignores it.
</blockquote></details>

Use the `tmjson "github.com/tendermint/tendermint/libs/json"` instead.
```
var txResponse sdk.TxResponse  
if err := tmjson.Unmarshal(buf.Bytes(), &txResponse); err != nil {  
   return errors.WithStack(err)  
}
```
Works fine.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/client/cli/tx_test.go` line 333 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_Zfw2DmzbCLBTGxKL:-NZk15IX3AmjbEDMsPPT:bl22a47) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L333)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO we shouldn't :-) Since you will have 2 lines instead on one. 
</blockquote></details>

No, we will still have one line :)
___
*[`x/asset/ft/client/cli/tx_test.go` line 338 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_ZTELBNg1DKWI37z2:-NZk1AP4DnFgZAvoKuh0:b-2cxwq3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L338)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Use the `tmjson "github.com/tendermint/tendermint/libs/json"` instead.
```
var txResponse sdk.TxResponse  
if err := tmjson.Unmarshal(buf.Bytes(), &txResponse); err != nil {  
   return errors.WithStack(err)  
}
```
Works fine.
</blockquote></details>

ohh... I always wanted to know what the difference between json and tmjson is. Now I know...

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/client/cli/tx_test.go` line 338 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_ZTELBNg1DKWI37z2:-NZk20EX4_FYnODKu07b:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L338)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ohh... I always wanted to know what the difference between json and tmjson is. Now I know...
</blockquote></details>

Done

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/client/cli/tx_test.go` line 333 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_Zfw2DmzbCLBTGxKL:-NZk8yKIAjXXdxtwLaPW:b-m1009j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L333)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

No, we will still have one line :)
</blockquote></details>

One additional. Let't discuss with the team today.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/client/cli/tx_test.go` line 333 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_Zfw2DmzbCLBTGxKL:-NZkdTpB8iEtBN7zaIhG:bekfzm8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L333)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

One additional. Let't discuss with the team today. 
</blockquote></details>

let's go with single function

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/client/cli/tx_test.go` line 333 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/557#-NZ_Zfw2DmzbCLBTGxKL:-NZyvmLR5fQt0dPSMR1b:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5a395097d895f8c44ce9f84c44309ac417305f09/x/asset/ft/client/cli/tx_test.go#L333)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

let's go with single function
</blockquote></details>

Done

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/557)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
