### PR TITLE
Add multisend test with multiple accounts

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/283)

### CODE REVIEW

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/283)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/283)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/283)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/283)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
