### PR TITLE
Base64 encoding/decoding of datastring

### PR DESCRIPTION
**Pull request by keyleu**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ-uWFW7nyksJssta7-:-NZ-uWFW7nyksJssta70:b-r1zk4r) (no related file):*
What about writing migration to fix existing records? I guess it is a task for core team, not Keyne. Is it in the list? I think it must be assigned and done in the scope of this sprint. @ysv 

___
___
*[`x/wasm/handler/query.go` line 167 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ-t5dRBVZjEzSpE8h8:-NZ-t5dRBVZjEzSpE8h9:b-fhntk2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/252b2360090edf1fc53d09e14819f3369781ff28/x/wasm/handler/query.go#L167)):*
> ```Go
> 
> func convertStringToDataBytes(dataString string) (*codectypes.Any, error) {
> 	databytes, err := base64.StdEncoding.DecodeString(dataString)
> ```

Are we 100% sure that `StdEncoding` is used by the cosmwasm in this case? Neither `URLEncoding`, `RawStdEncoding` nor `RawURLEncoding`? I would love to see in our integration tests data containing some special bytes we know are encoded/decoded differently by each standard.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 3 unresolved discussions (waiting on @keyleu, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ-uWFW7nyksJssta7-:-NZ03ENrBL0Ey-w46cuc:bhc23cz) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What about writing migration to fix existing records? I guess it is a task for core team, not Keyne. Is it in the list? I think it must be assigned and done in the scope of this sprint. @ysv 
</blockquote></details>

the task is in the list and is assigned to me. 

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ03HZ30PCIY4IKD76N:-NZ03HZ30PCIY4IKD76O:bjadmio) (no related file):*
we need to cover 2 more scenarios in integration tests. we need to write random bytes via smart and read it from grpc and ensure that the bytes match exactly, and also the other way around.

___

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ03HZ30PCIY4IKD76N:-NZ04mBy-oxTpS20sgYg:bl44yig) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we need to cover 2 more scenarios in integration tests. we need to write random bytes via smart and read it from grpc and ensure that the bytes match exactly, and also the other way around.
</blockquote></details>

We are one at the start. We are sending "data" which the contract takes as a base64 encoded array of bytes.
Then we query this with grpc and decode it and we see that it matches.

___
___
*[`x/wasm/handler/query.go` line 167 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ-t5dRBVZjEzSpE8h8:-NZ05v4-4sPA3D7C2XyL:bzh0fkp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/252b2360090edf1fc53d09e14819f3369781ff28/x/wasm/handler/query.go#L167)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Are we 100% sure that `StdEncoding` is used by the cosmwasm in this case? Neither `URLEncoding`, `RawStdEncoding` nor `RawURLEncoding`? I would love to see in our integration tests data containing some special bytes we know are encoded/decoded differently by each standard.
</blockquote></details>

According to cosmwasm documentation it uses the normalized base64 encoding with trailing = if needed. At the beginning of the integration test I compare the data that I provide and decode it and check that with StdEncoding it matches

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 3 unresolved discussions (waiting on @keyleu, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ03HZ30PCIY4IKD76N:-NZ094HR23KERQQe0Ht5:b-cxlpm3) (no related file):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

We are one at the start. We are sending "data" which the contract takes as a base64 encoded array of bytes.
Then we query this with grpc and decode it and we see that it matches.
</blockquote></details>

I am not seeing that, I only see the queries go through the wasm, I am not seeing direct grpc read and writes in the test. 

___
___
*[`integration-tests/modules/wasm_test.go` line 1223 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ087ne7Kk48zSAmRyy:-NZ087ne7Kk48zSAmRyz:b6wy5rw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/252b2360090edf1fc53d09e14819f3369781ff28/integration-tests/modules/wasm_test.go#L1223)):*
> ```Go
> 
> 	dataString := "data"
> 	dataBase64Bytes, err := base64.StdEncoding.DecodeString(dataString)
> ```

This seems wrong. we should not have to decode/encode anything here. the whole idea is that the decoding/encoding must be hidden from the end user.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 3 unresolved discussions (waiting on @keyleu, @silverspase, and @ysv)

___
*[`x/wasm/handler/query.go` line 167 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ-t5dRBVZjEzSpE8h8:-NZ0BjCe9jwYRjDQ33hZ:b1j9tf2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/252b2360090edf1fc53d09e14819f3369781ff28/x/wasm/handler/query.go#L167)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

According to cosmwasm documentation it uses the normalized base64 encoding with trailing = if needed. At the beginning of the integration test I compare the data that I provide and decode it and check that with StdEncoding it matches
</blockquote></details>

Could you point me to the line where you do it? Do you use characters/bytes which are encoded differently by those encoders?

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ03HZ30PCIY4IKD76N:-NZ0Cphy7kWECqtTyT8D:b-pv6myl) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I am not seeing that, I only see the queries go through the wasm, I am not seeing direct grpc read and writes in the test. 
</blockquote></details>

comment below.

___
___
*[`integration-tests/modules/wasm_test.go` line 1223 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ087ne7Kk48zSAmRyy:-NZ0CmtA3m99Jae2k7Lm:b438h0x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/252b2360090edf1fc53d09e14819f3369781ff28/integration-tests/modules/wasm_test.go#L1223)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

This seems wrong. we should not have to decode/encode anything here. the whole idea is that the decoding/encoding must be hidden from the end user. 
</blockquote></details>

The instantiate message from the contract is sending data as a Binary. So what the contract initially gets is a base64 wrapped array of bytes. So in our integration tests when we are writing "data" in the issue. The contract is taking this as a base64 encoded array of bytes. Correct me if I'm wrong.
___
*[`x/wasm/handler/query.go` line 167 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ-t5dRBVZjEzSpE8h8:-NZ0DBQu3CG5KTNVcImN:b-vhze8c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/252b2360090edf1fc53d09e14819f3369781ff28/x/wasm/handler/query.go#L167)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you point me to the line where you do it? Do you use characters/bytes which are encoded differently by those encoders?
</blockquote></details>

The discussion with Milad above.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 3 unresolved discussions (waiting on @keyleu, @miladz68, @silverspase, and @ysv)

___
*[`x/wasm/handler/query.go` line 167 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ-t5dRBVZjEzSpE8h8:-NZ0JKuP0z4LJpvJh5TF:b61c2ey) ([raw file](https://github.com/CoreumFoundation/coreum/blob/252b2360090edf1fc53d09e14819f3369781ff28/x/wasm/handler/query.go#L167)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

The discussion with Milad above.
</blockquote></details>

Yea, so the idea is to use sth like "data/and\x00some\nspecial/characters"

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @silverspase, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1223 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ087ne7Kk48zSAmRyy:-NZ0aRgKA8xfaEA5yIMJ:bkklqcv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/252b2360090edf1fc53d09e14819f3369781ff28/integration-tests/modules/wasm_test.go#L1223)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

The instantiate message from the contract is sending data as a Binary. So what the contract initially gets is a base64 wrapped array of bytes. So in our integration tests when we are writing "data" in the issue. The contract is taking this as a base64 encoded array of bytes. Correct me if I'm wrong.
</blockquote></details>

Discussed in the call and decided to make some changes

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1223 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ087ne7Kk48zSAmRyy:-NZ0mJG22OBEplTqzOa-:b-defaq7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/252b2360090edf1fc53d09e14819f3369781ff28/integration-tests/modules/wasm_test.go#L1223)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Discussed in the call and decided to make some changes
</blockquote></details>

Did changes.
___
*[`x/wasm/handler/query.go` line 167 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ-t5dRBVZjEzSpE8h8:-NZ0mHVG50BucXrUvINe:bwgg8a6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/252b2360090edf1fc53d09e14819f3369781ff28/x/wasm/handler/query.go#L167)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Yea, so the idea is to use sth like "data/and\x00some\nspecial/characters"
</blockquote></details>

added a dataString with special characters. Encoded it before we instantiate the NFT so that it's closer to how the user will operate with this contract.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1185 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ0nWzf40tTBmXav1wg:-NZ0nWzf40tTBmXav1wh:b-69aeyt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/940e68953b8ff73619ccd97f49b454ca214ed704/integration-tests/modules/wasm_test.go#L1185)):*
> ```Go
> 
> 	royaltyRate := sdk.MustNewDecFromStr("0.1")
> 	dataString := "@#$%&+=This string when I encode it into base 64 has special characters ~~~~~^^^{^{^:!>!!?><"
> ```

now when I think about it I see we could go wild and test all the values:
```
data := make([]byte, 256)
for i := uint8(0); i < 256; i++ {
    data[i] = i
}
```

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1185 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ0nWzf40tTBmXav1wg:-NZ0pLiZAAIcMaCOGaN5:b-ehakf2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/940e68953b8ff73619ccd97f49b454ca214ed704/integration-tests/modules/wasm_test.go#L1185)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

now when I think about it I see we could go wild and test all the values:
```
data := make([]byte, 256)
for i := uint8(0); i < 256; i++ {
    data[i] = i
}
```
</blockquote></details>

I tried it and it timed out. Are you sure you want this?

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1185 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ0nWzf40tTBmXav1wg:-NZ0pR9JAoEsCXMLcB1e:b-yzaa39) ([raw file](https://github.com/CoreumFoundation/coreum/blob/940e68953b8ff73619ccd97f49b454ca214ed704/integration-tests/modules/wasm_test.go#L1185)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

I tried it and it timed out. Are you sure you want this?
</blockquote></details>

I mean the test has a 30s timeout, we can remove it I guess

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1185 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ0nWzf40tTBmXav1wg:-NZ0qZ8b76FlKE5gBQlD:b4sidg4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/940e68953b8ff73619ccd97f49b454ca214ed704/integration-tests/modules/wasm_test.go#L1185)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

I mean the test has a 30s timeout, we can remove it I guess
</blockquote></details>

I don't get it. I'm pretty sure that go is able to produce 256 numbers in 30 seconds :)
I mean, you don't call the smart contract for each `data[i]`. You do it once for entire `data`.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1185 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ0nWzf40tTBmXav1wg:-NZ0reBl4sZQIXXfy24N:b-htbv6i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/940e68953b8ff73619ccd97f49b454ca214ed704/integration-tests/modules/wasm_test.go#L1185)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't get it. I'm pretty sure that go is able to produce 256 numbers in 30 seconds :)
I mean, you don't call the smart contract for each `data[i]`. You do it once for entire `data`.
</blockquote></details>

Yes but we are still comparing the results we get a lot of times so each time it's comparing that the data matches.
Also every time we query the contract we receive that huge amount of data with it.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1185 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ1AH6m9bUnyvH67hTp:-NZ1BUBv1-XDznXE7SVt:b-2fbhos) ([raw file](https://github.com/CoreumFoundation/coreum/blob/940e68953b8ff73619ccd97f49b454ca214ed704/integration-tests/modules/wasm_test.go#L1185)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

This is not exactly what I meant. I wanted the base64encoded string to contain the special characters (`/` and `+`) 
</blockquote></details>

it does, if you encode the bytes it has the special characters

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1185 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ0nWzf40tTBmXav1wg:-NZ1Jocx0999Cs_yxLGd:b-qmf7mo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/940e68953b8ff73619ccd97f49b454ca214ed704/integration-tests/modules/wasm_test.go#L1185)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

Yes but we are still comparing the results we get a lot of times so each time it's comparing that the data matches.
Also every time we query the contract we receive that huge amount of data with it.
</blockquote></details>

Ok, done it. The timeout was because of a different reason.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1185 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ1AH6m9bUnyvH67hTp:-NZ1Q5Bk31L7TbuTvxVD:burch28) ([raw file](https://github.com/CoreumFoundation/coreum/blob/940e68953b8ff73619ccd97f49b454ca214ed704/integration-tests/modules/wasm_test.go#L1185)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

it does, if you encode the bytes it has the special characters
</blockquote></details>

@miladz68 now it contains all possible values

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1185 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ0nWzf40tTBmXav1wg:-NZ1QDCQ2ZHaGt16G9Sh:bs7mefj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/940e68953b8ff73619ccd97f49b454ca214ed704/integration-tests/modules/wasm_test.go#L1185)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

Ok, done it. The timeout was because of a different reason.
</blockquote></details>

Just put `uint8(0)` to do one conversion at compilation time, not many of them on runtime ;-)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @silverspase, and @ysv)

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1185 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/537#-NZ1AH6m9bUnyvH67hTp:-NZ1SvTP9_N5DArjhL9F:b-twlucs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/940e68953b8ff73619ccd97f49b454ca214ed704/integration-tests/modules/wasm_test.go#L1185)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@miladz68 now it contains all possible values
</blockquote></details>

Yes I also double checked and it contains all special characters, just in case

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/537)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
