### PR TITLE
Check run-unsafe flag for the unsafe functions instead of the unsafe tests.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/506)

### CODE REVIEW

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/506)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/506)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/506#-:-NWCBDza8dduBEGTIrJ-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

___
*[`integration-tests/gov.go` line 65 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/506#-NWC9N5_EaBDhHYgMwQ9:-NWC9N5_EaBDhHYgMwQA:bu0wqr6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ea075429fee321f8d93967e824d8521c79979694/integration-tests/gov.go#L65)):*
> ```Go
> // UpdateParams goes through proposal process to update parameters.
> func (g Governance) UpdateParams(ctx context.Context, t *testing.T, description string, updates []paramproposal.ParamChange) error {
> 	// Fund accounts.
> ```

why not also skip it here ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/506)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @silverspase)

___
*[`integration-tests/gov.go` line 65 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/506#-NWC9N5_EaBDhHYgMwQ9:-NWCq_9Y48z05-k1tDiD:bh91auc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ea075429fee321f8d93967e824d8521c79979694/integration-tests/gov.go#L65)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

why not also skip it here ?
</blockquote></details>

It's skipped in the child function.

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/506)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/506)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/506)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Pull request merged**
