### PR TITLE
Refactor MultiSend interceptor to work only with 1 input

### PR DESCRIPTION
**Pull request by miladz68**
# Description
With a change introduced to bank Multisend in Cosmos SDK v0.47, only a single sender can be specified in Multisend. In this PR we take advantage of this change to make the logic of our interceptor much simpler. 
# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/660)

### CODE REVIEW

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/660)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @wojtek-coreum)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/660)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/660#-NewqgI0AN4XwVHZmAzQ:-NewqgI0AN4XwVHZmAzR:bx3cfee) (no related file):*
Check the tests please they are failed

___
___
*[`x/asset/ft/keeper/before_send.go` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/660#-NewqRbh55HD3m5-mson:-NewqRbh55HD3m5-msoo:b-cvy6z7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e95d32d02009b9c51cab5ff1b96b09384da06505/x/asset/ft/keeper/before_send.go#L86)):*
> ```Go
> 
> 		burnAmount := k.ApplyRate(ctx, def.BurnRate, issuer, sender, outOps)
> 		if err := k.burnIfSpendable(ctx, sender, def, burnAmount); err != nil {
> ```

You burn twice. Why does the unit tests don't show it?
___
*[`x/asset/ft/keeper/before_send.go` line 100 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/660#-NewsFsi0afHXYr3-LAJ:-NewsFsi0afHXYr3-LAK:b-mf50y5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e95d32d02009b9c51cab5ff1b96b09384da06505/x/asset/ft/keeper/before_send.go#L100)):*
> ```Go
> 		}
> 
> 		if err := k.isCoinSpendable(ctx, sender, def, coin.Amount); err != nil {
> ```

Does it make send to check it before burning and commision?
___
*[`x/asset/ft/keeper/before_send.go` line 104 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/660#-Newsi9U22-jID6LqeVN:-Newsi9U22-jID6LqeVO:bsql90k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e95d32d02009b9c51cab5ff1b96b09384da06505/x/asset/ft/keeper/before_send.go#L104)):*
> ```Go
> 		}
> 
> 		return iterateMapDeterministic(outOps, func(account string, amount sdkmath.Int) error {
> ```

The same quesion here, does it make send to check it before burning and commision?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/660)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/660)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/660#-NewqgI0AN4XwVHZmAzQ:-NfADuGu2fFleoZIiSV6:b-896fix) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Check the tests please they are failed
</blockquote></details>

Done.

___
___
*[`x/asset/ft/keeper/before_send.go` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/660#-NewqRbh55HD3m5-mson:-NfACzTL67lXemFln6Wp:b8ugexe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e95d32d02009b9c51cab5ff1b96b09384da06505/x/asset/ft/keeper/before_send.go#L86)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You burn twice. Why does the unit tests don't show it?
</blockquote></details>

well they actually show it. integration and unit tests are failing. 
removed. 
___
*[`x/asset/ft/keeper/before_send.go` line 100 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/660#-NewsFsi0afHXYr3-LAJ:-NfAD5vq7Gfl9Jlgqiuw:b9faqjw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e95d32d02009b9c51cab5ff1b96b09384da06505/x/asset/ft/keeper/before_send.go#L100)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Does it make send to check it before burning and commision?
</blockquote></details>

no, because if want to make sure the sender has enough balance after the rates are applied.
___
*[`x/asset/ft/keeper/before_send.go` line 104 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/660#-Newsi9U22-jID6LqeVN:-NfADKke7p1WKzmQthpw:b-p8u8wy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e95d32d02009b9c51cab5ff1b96b09384da06505/x/asset/ft/keeper/before_send.go#L104)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The same quesion here, does it make send to check it before burning and commision?
</blockquote></details>

Right now we are not modifying the received amount, but any of our features in future might touch it. for the same reason stated above. it makes sense to perform the checks at the end of function.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/660)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/660#-NewqRbh55HD3m5-mson:-NfBNdNX9J9EbIpWBMmv:b-xej4p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e95d32d02009b9c51cab5ff1b96b09384da06505/x/asset/ft/keeper/before_send.go#L86)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

well they actually show it. integration and unit tests are failing. 
removed.
</blockquote></details>

But unit tests should show it as well. Add the test case to the unit tests please.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/660)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by keyleu — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/660)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
