### PR TITLE
Add extension instantiation info

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description
Adds a new optional flag to asset ft issue command that receives a json encoded data to pass to the wasm contract on instantiation

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 33 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O--yyYzCMbnuYPK6yQp:-O--yyYzCMbnuYPK6yQq:b6p63px) ([raw file](https://github.com/CoreumFoundation/coreum/blob/01ba3bb73dcd549e33805778b4843f9130710c32/x/asset/ft/keeper/keeper.go#L33)):*
> ```Go
> type ExtensionInstantiateMsg struct {
> 	Denom             string `json:"denom"`
> 	InstantiationInfo any    `json:"instantiation_info"`
> ```

naming here must match the naming in the external API. try to find a name that is suitable for both places. some thing like `UserProvidedInstantiationMsg`

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 33 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O--yyYzCMbnuYPK6yQp:-O-04Dlh9vv36ODdlXX8:b-4kdjzl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/01ba3bb73dcd549e33805778b4843f9130710c32/x/asset/ft/keeper/keeper.go#L33)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

naming here must match the naming in the external API. try to find a name that is suitable for both places. some thing like `UserProvidedInstantiationMsg`
</blockquote></details>

Done.
Let me know if you want me to change it everywhere

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 5 of 9 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 105 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0Fmwq3IpGDMM344zg:-O-0Fmwq3IpGDMM344zh:b-lgao2e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/21368a0563e330a8744264ddeec9355ce67f319c/proto/coreum/asset/ft/v1/tx.proto#L105)):*
> ```proto
>   ];
>   // optional json encoded data to pass to WASM on instantiation
>   bytes instantiationInfo = 4 [
> ```

it should be instantiationMsg or instantianInfo everywhere. 
___
*[`x/asset/ft/client/cli/tx.go` line 40 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0G14V0YyWbgU12nzE:-O-0G14V0YyWbgU12nzF:b-lgao2e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/21368a0563e330a8744264ddeec9355ce67f319c/x/asset/ft/client/cli/tx.go#L40)):*
> ```Go
> 	ExtensionLabel             = "extension_label"
> 	ExtensionFunds             = "extension_funds"
> 	ExtensionInstantiationInfo = "extension_instantiation_info"
> ```

it should be instantiationMsg or instantianInfo everywhere.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 105 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0Fmwq3IpGDMM344zg:-O-0K3c2EL697ox-KvPp:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/21368a0563e330a8744264ddeec9355ce67f319c/proto/coreum/asset/ft/v1/tx.proto#L105)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it should be instantiationMsg or instantianInfo everywhere.
</blockquote></details>

Done.
___
*[`x/asset/ft/client/cli/tx.go` line 40 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0G14V0YyWbgU12nzE:-O-0K45XCJzwb-Lq7hLN:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/21368a0563e330a8744264ddeec9355ce67f319c/x/asset/ft/client/cli/tx.go#L40)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it should be instantiationMsg or instantianInfo everywhere.
</blockquote></details>

Done.

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1, 2 of 4 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

___
*[`x/asset/ft/client/cli/tx.go` line 194 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0p0gJBiNXgjuugxZB:-O-0p0gJBiNXgjuugxZC:bgprjrx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/client/cli/tx.go#L194)):*
> ```Go
> 				}
> 
> 				extensionInstantiationMsg, err := cmd.Flags().GetString(ExtensionInstantiationMsg)
> ```

Is it a good idea to take it from CLI? Maybe path would be better?
___
*[`x/asset/ft/keeper/keeper.go` line 33 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0pRIi282gNQO4id0G:-O-0pRIi282gNQO4id0H:bfu4dwx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/keeper/keeper.go#L33)):*
> ```Go
> type ExtensionInstantiateMsg struct {
> 	Denom                        string `json:"denom"`
> 	UserProvidedInstantiationMsg any    `json:"user_provided_instantiation_msg"`
> ```

Maybe `InstantiationMsg`? At the end of the day everything is "user-provided"
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 14 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0pin_696lj8ruZSPz:-O-0pin_696lj8ruZSQ-:bn2uyv7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L14)):*
> ```XML
> 
> use crate::msg::{
>     ExecuteMsg, IBCPurpose, InstantiateMsg, QueryUserProvidedInstantiationMsgResponse, QueryMsg, SudoMsg,
> ```

Remove "UserProvided" everywhere
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/state.rs` line 4 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0qDwH5yj_5Nbpn33X:-O-0qDwH5yj_5Nbpn33Y:b4utgs7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/keeper/test-contracts/asset-extension/src/state.rs#L4)):*
> ```XML
> 
> pub const DENOM: Item<String> = Item::new("state");
> pub const EXTRA_DATA: Item<String> = Item::new("extradata");
> ```

Is the `String` a good type for this?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 33 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0pRIi282gNQO4id0G:-O-5VL_XCxBFyKcl3ZaI:b-2d07gf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/keeper/keeper.go#L33)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Denom is not user provided though.
</blockquote></details>

At some point it is :-)
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 14 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0pin_696lj8ruZSPz:-O-5VRP45ax8YP_kA592:b8e11wp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L14)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It is not InstantiationMsg, it is just a part of the message.
</blockquote></details>

then maybe it should be called `InstantiationMsgData`?

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/client/cli/tx.go` line 194 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0p0gJBiNXgjuugxZB:-O-69FkZ-EsBIoJwO4RM:b-c11m9l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/client/cli/tx.go#L194)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is it a good idea to take it from CLI? Maybe path would be better?
</blockquote></details>

From what I see, it should not be some huge, complex data. I believe this is enough. But let's discuss it after the daily today
___
*[`x/asset/ft/keeper/keeper.go` line 33 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0pRIi282gNQO4id0G:-O-69EFF0aaTXR5wJX2J:bikds6o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/keeper/keeper.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

At some point it is :-)
</blockquote></details>

Let's discuss it after the daily today
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 14 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0pin_696lj8ruZSPz:-O-697w_0dWsYIwLN4p8:bikds6o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

then maybe it should be called `InstantiationMsgData`?
</blockquote></details>

Let's discuss it after the daily today
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/state.rs` line 4 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0qDwH5yj_5Nbpn33X:-O-68NK2AaDioLnhVqp9:be9mlvu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/keeper/test-contracts/asset-extension/src/state.rs#L4)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is the `String` a good type for this?
</blockquote></details>

This is just for test. I pass some text to it and just query it to make sure everything works. Extension developers should come up with better data types. We have an example [here](https://github.com/CoreumFoundation/tutorials/tree/extension/whitelist/wasm/extension/src).

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 33 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-6EM0a4JBTZtszYbyg:-O-6EM0a4JBTZtszYbyh:bflj0hy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/keeper/keeper.go#L33)):*
> ```Go
> type ExtensionInstantiateMsg struct {
> 	Denom                        string `json:"denom"`
> 	UserProvidedInstantiationMsg any    `json:"user_provided_instantiation_msg"`
> ```

type should not be any.
___
*[`x/asset/ft/keeper/keeper.go` line 33 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0pRIi282gNQO4id0G:-O-6Gy-S-kcjHTtVr4K_:bx9p3l0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/keeper/keeper.go#L33)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Let's discuss it after the daily today
</blockquote></details>

Decided on IssuanceMsg both for proto and rust msg.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/client/cli/tx.go` line 194 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0p0gJBiNXgjuugxZB:-O-6IkZJ478eRcolc6sp:b-t2683d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/client/cli/tx.go#L194)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

From what I see, it should not be some huge, complex data. I believe this is enough. But let's discuss it after the daily today
</blockquote></details>

follow the method that wasmd has.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: 1 of 9 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/client/cli/tx.go` line 194 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0p0gJBiNXgjuugxZB:-O-6UEBV78psOLomjhV7:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/client/cli/tx.go#L194)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

follow the method that wasmd has.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper.go` line 33 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-0pRIi282gNQO4id0G:-O-6UFlM4fmz8Myh5qzp:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/keeper/keeper.go#L33)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Decided on IssuanceMsg both for proto and rust msg.
</blockquote></details>

Done.

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 33 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-6EM0a4JBTZtszYbyg:-O-6VpXtB3b-0DjTBO0p:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/keeper/keeper.go#L33)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

type should not be any.
</blockquote></details>

Done.

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 8 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 6 of 8 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @ysv)

___
*[`x/asset/ft/client/cli/tx_test.go` line 112 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-5nHlP55p6FDa8_vXq:-O-5nHlQ4aKQRTITV_v3:bqergto) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/client/cli/tx_test.go#L112)):*
> ```Go
> 	}
> 
> 	instantiationMsgBytes, _ := json.Marshal(instantiationMsg)
> ```

Why don't you check the error?

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/client/cli/tx_test.go` line 112 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/871#-O-5nHlP55p6FDa8_vXq:-O-BHMMr0m7AgH7kKykk:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e79ffb07e38ca08d8347f978197bef3d45602932/x/asset/ft/client/cli/tx_test.go#L112)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't you check the error?
</blockquote></details>

Done.

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 4 of 8 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/871)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
