### PR TITLE
Add auth integration-tests for tx with multiple signatures

### PR DESCRIPTION
**Pull request by ysv**
# Description

Add auth integration-tests for tx with multiple signatures.
Note the difference between tx from multisig account vs tx with multiple signatures.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/716)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/716)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/modules/auth_test.go` line 496 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/716#-NjDjZ0Z69245sUUDN7j:-NjDjZ0Z69245sUUDN7k:bb0kg5o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3565fc42c4632a2a5a94a01847d0f7e9aad5f945/integration-tests/modules/auth_test.go#L496)):*
> ```Go
> // Multisig account tx contains single string in array where multiple signatures are combined.
> // While multiple signer account tx contains each signature as a separate element in array.
> func signTxWithMultipleSignatures(
> ```

I made this implementation of this method but that I found out that there is a simpler version:

https://github.com/CoreumFoundation/coreum/commit/e3071776859a19b32e87df4d0feb45438961a377#diff-6807f7a6a19f979293ea8a30fe715faae48f8e8b6735bbaa7f2589756505a039R566-R592

But it only supports Legacy Amino signing mode. S I decided to keep this version (it uses DIRECT mode) even though it looks a bit more complicated.

LMK if you disagree

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/716)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/716)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/716)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/716)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
