### PR TITLE
DEX orders matching with the self order book.

### PR DESCRIPTION
**Pull request by dzmitryhil**
DEX orders matching with the self order book.

* Saving/reading of orders and order books.
* Order book iterator with the read from head and tail capabilities.
* Iterator fuzz test (+ store ordering)
* Matching of orders with the self order book.
* Place, get, match integration test.

# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/910)

### CODE REVIEW

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 42 of 42 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/910)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/dex_test.go` line 150 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2OPzTF2ZO27X1KM_pf:-O2OPzTG7_CGVmPWFWJN:bxzkxqj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff3b7ef9e81d411fa1159efd28f084989d561d28/integration-tests/modules/dex_test.go#L150)):*
> ```Go
> }
> 
> func issuerAssetFT(
> ```

I'm not sure if this is a good name for this function. Maybe something like `issueTokenForAccount` or just `issueToken` is better
___
*[`x/dex/keeper/keeper.go` line 7 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2OZbE5010ckdxjQnbK:-O2OZbE5010ckdxjQnbL:briw4l3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff3b7ef9e81d411fa1159efd28f084989d561d28/x/dex/keeper/keeper.go#L7)):*
> ```Go
> 
> 	sdkerrors "cosmossdk.io/errors"
> 	"github.com/cometbft/cometbft/libs/log"
> ```

Is this correct? Do we actually need cometbft's logger?
___
*[`x/dex/keeper/keeper.go` line 77 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2OXT8W7wvmkuUi7y0O:-O2OXT8W7wvmkuUi7y0P:b8lwk76) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff3b7ef9e81d411fa1159efd28f084989d561d28/x/dex/keeper/keeper.go#L77)):*
> ```Go
> 
> // GetOrderByAddressAndID returns order by holder address and it's ID.
> func (k Keeper) GetOrderByAddressAndID(ctx sdk.Context, acc sdk.AccAddress, orderID string) (types.Order, bool, error) {
> ```

It is not usual in Go codes to have a boolean (found) and error together. Maybe we can return ErrNotFound instead of the bool
___
*[`x/dex/keeper/keeper.go` line 173 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2OaAvj0VMz6YPiQQgZ:-O2OaAvj0VMz6YPiQQg_:b8lwk76) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff3b7ef9e81d411fa1159efd28f084989d561d28/x/dex/keeper/keeper.go#L173)):*
> ```Go
> }
> 
> func (k Keeper) getOrderBookIDByKey(ctx sdk.Context, key []byte) (uint32, bool, error) {
> ```

It is not usual in Go codes to have a boolean (found) and error together. Maybe we can return ErrNotFound instead of the bool
___
*[`x/dex/keeper/keeper.go` line 274 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2Ob81r5tnKgYh0-cHK:-O2Ob81r5tnKgYh0-cHL:b8lwk76) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff3b7ef9e81d411fa1159efd28f084989d561d28/x/dex/keeper/keeper.go#L274)):*
> ```Go
> }
> 
> func (k Keeper) getOrderBookData(ctx sdk.Context, orderBookID uint32) (types.OrderBookData, bool, error) {
> ```

It is not usual in Go codes to have a boolean (found) and error together. Maybe we can return ErrNotFound instead of the bool
___
*[`x/dex/keeper/keeper.go` line 309 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2ObJrRC0bgGmlnY47h:-O2ObJrRC0bgGmlnY47i:b8lwk76) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff3b7ef9e81d411fa1159efd28f084989d561d28/x/dex/keeper/keeper.go#L309)):*
> ```Go
> 	price types.Price,
> 	orderSeq uint64,
> ) (types.OrderBookRecordData, bool, error) {
> ```

It is not usual in Go codes to have a boolean (found) and error together. Maybe we can return ErrNotFound instead of the bool
___
*[`x/dex/keeper/keeper.go` line 344 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2ObdJd7cpZSU98Gb2J:-O2ObdJd7cpZSU98Gb2K:b8lwk76) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff3b7ef9e81d411fa1159efd28f084989d561d28/x/dex/keeper/keeper.go#L344)):*
> ```Go
> }
> 
> func (k Keeper) getOrderData(ctx sdk.Context, orderSeq uint64) (types.OrderData, bool, error) {
> ```

It is not usual in Go codes to have a boolean (found) and error together. Maybe we can return ErrNotFound instead of the bool
___
*[`x/dex/keeper/keeper.go` line 368 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2ObitF2CNtbqfrKGCC:-O2ObitF2CNtbqfrKGCD:b8lwk76) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff3b7ef9e81d411fa1159efd28f084989d561d28/x/dex/keeper/keeper.go#L368)):*
> ```Go
> }
> 
> func (k Keeper) getOrderSeqByID(ctx sdk.Context, accountNumber uint64, orderID string) (uint64, bool, error) {
> ```

It is not usual in Go codes to have a boolean (found) and error together. Maybe we can return ErrNotFound instead of the bool
___
*[`x/dex/keeper/keeper_matching.go` line 146 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2OgFRz1VCimIBMu0Rt:-O2OgFRz1VCimIBMu0Ru:bog2rau) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff3b7ef9e81d411fa1159efd28f084989d561d28/x/dex/keeper/keeper_matching.go#L146)):*
> ```Go
> 		return sdk.Coin{}, err
> 	}
> 	// currently we send the coins to module and from, but later we will implement the locking instead
> ```

Maybe we can add a TODO here, to make it easier to find later
___
*[`x/dex/keeper/keeper_matching.go` line 214 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2Oh69q0PL0syDP82qr:-O2Oh69q0PL0syDP82qs:biw69ho) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff3b7ef9e81d411fa1159efd28f084989d561d28/x/dex/keeper/keeper_matching.go#L214)):*
> ```Go
> 		recordToReduceReceiveAmt   sdkmath.Int
> 	)
> 	if recordToClose.Side == types.Side_buy {
> ```

If you think this function might be called from another places that does not check the `unspecified` variant, please check that too
___
*[`x/dex/keeper/keeper_test.go` line 66 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2On01N13bSe9Vdd0rs:-O2On01N13bSe9Vdd0rt:b-2hq7mu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff3b7ef9e81d411fa1159efd28f084989d561d28/x/dex/keeper/keeper_test.go#L66)):*
> ```Go
> 			baseDenom:                   denom2,
> 			quoteDenom:                  denom3,
> 			expectedSelfOrderBookID:     uint32(2),
> ```

I think `SameOrderBook` vs. `OppositeOrderBook` is better than `SelfOrderBook` vs. `OppositeOrderBook`. WDYT?
___
*[`x/dex/types/keys.go` line 27 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2Opf0O6EqO81yAEmo0:-O2Opf0O6EqO81yAEmo1:bcmxr5p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff3b7ef9e81d411fa1159efd28f084989d561d28/x/dex/types/keys.go#L27)):*
> ```Go
> 	OrderBookKeyPrefix = []byte{0x01}
> 	// OrderBookSeqKey defines the key for the order book sequence.
> 	OrderBookSeqKey = []byte{0x02}
> ```

Some of these has "Prefix" prefix, and some don't. Please unify them

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/910)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 41 of 42 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/910)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

___
*[`proto/coreum/dex/v1/order.proto` line 22 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2TuDlM3OVs1ldLSzEY:-O2TuDlM3OVs1ldLSzEZ:b-cq2s9j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b6c63d9c1caa3e1b75bf3e228b25953d4136cbf7/proto/coreum/dex/v1/order.proto#L22)):*
> ```proto
> message Order {
>   // account is order creator address.
>   string account = 1;
> ```

I think sender or creator is a more descriptive name. should be same name as below.
___
*[`proto/coreum/dex/v1/query.proto` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2Ttvvq4hCXhRAU9ec7:-O2Ttvvq4hCXhRAU9ec8:bz77oex) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b6c63d9c1caa3e1b75bf3e228b25953d4136cbf7/proto/coreum/dex/v1/query.proto#L21)):*
> ```proto
> message QueryOrderRequest {
>   // account is order creator's account.
>   string account = 1;
> ```

I think sender or creator is more descriptive. 
___
*[`x/dex/keeper/keeper.go` line 77 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2OXT8W7wvmkuUi7y0O:-O2TwMto5XPLJU_TsHIT:b-2bvhes) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff3b7ef9e81d411fa1159efd28f084989d561d28/x/dex/keeper/keeper.go#L77)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It can be:
1. val, bool, error
2. pointer_val, error
3. val, error

The issue with the error here, is the handling of it. IMO it looks ugly :-)
But in general, I'm OK to redo it.  @miladz68 @ysv  WDYT ?
</blockquote></details>

I think option 3 is best. Althoug I agree that option 1 is more type safe and clear, but it is not idiomatic Go. 
___
*[`x/dex/types/order.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2Tyt72CPpDlHEpNoy9:-O2Tyt733AtfOur7Nlha:b55z16h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b6c63d9c1caa3e1b75bf3e228b25953d4136cbf7/x/dex/types/order.go#L17)):*
> ```Go
> const (
> 	// maxWordLen defines the maximum word length supported by Int and Uint types.
> 	maxSDKIntWordLen = sdkmath.MaxBitLen / bits.UintSize
> ```

hardcode it. we don't want this to silently change if maxbitlen changes. also add a test to fail if sdkmath.MaxBitLen changes.

**Review by miladz68 — COMMENTED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/910)* status: all files reviewed, 7 unresolved discussions (waiting on @masihyeganeh and @ysv)

**Review by masihyeganeh — DISMISSED** [review]
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/910)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`proto/coreum/dex/v1/order.proto` line 22 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2TuDlM3OVs1ldLSzEY:-O2_lA0h6AZ_1hs2TslW:b5k4wgp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b6c63d9c1caa3e1b75bf3e228b25953d4136cbf7/proto/coreum/dex/v1/order.proto#L22)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The sender is used in the transaction, here we can use `account` or `creator`. I personally, don't see a big difference.
@masihyeganeh WDYT ?
</blockquote></details>

Yeah, `creator` is better IMO

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/910)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`proto/coreum/dex/v1/order.proto` line 22 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/910#-O2TuDlM3OVs1ldLSzEY:-O2ce4vX3ooUH-jIdmlT:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b6c63d9c1caa3e1b75bf3e228b25953d4136cbf7/proto/coreum/dex/v1/order.proto#L22)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Yeah, `creator` is better IMO
</blockquote></details>

Updated.

**Review by miladz68 — APPROVED** [review]
> Reviewed 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/910)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/910)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

**Review by masihyeganeh — DISMISSED** [review]
> Reviewed 16 of 16 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/910)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/910)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/910)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
