### PR TITLE
Update NFT spec with dynamic data.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Update NFT spec with dynamic data.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/831)

### CODE REVIEW

**Review by masihyeganeh — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/831)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/831)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/spec/README.md` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/831#-NxvJ2OY0Ug624dRX2-h:-NxvJ2OY0Ug624dRX2-i:byvamve) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7c610aaf65968232a46bdb2bb2ef6c2bbe3502c1/x/asset/nft/spec/README.md#L39)):*
> ```Markdown
> ### Minting
> The minting is enabled for all issued NFT classes. The minting allows to mint a token for an NFT class by the issuer of the class.
> There are two types that can be used for NFT minting `DataBytes` and `DataDynamic`. The `DataBytes` contains immutable data bytes
> ```

there are two data types.



_Code quote:_
```Markdown
There are two types
```

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/831)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/spec/README.md` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/831#-NxvJ2OY0Ug624dRX2-h:-NxvuaPFEWptZ08AonUA:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7c610aaf65968232a46bdb2bb2ef6c2bbe3502c1/x/asset/nft/spec/README.md#L39)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

there are two data types.
</blockquote></details>

Done.

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/831)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/831)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/831)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
