### PR TITLE
Spec for feemodel

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/spec/README.md` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NBXY8Ij65kBA-LZuYQf:-NBXY8Ij65kBA-LZuYQg:bzay112) ([raw file](https://github.com/coreumfoundation/coreum/blob/da2aca3ee69497b6529da02a8b7f4b1e68652d60/x/feemodel/spec/README.md#L12)):*
> ```Markdown
> ## Abstract
> 
> This document specifies the feemodel module of the Cosmos SDK.
> ```

of the Cosmos SDK ?



_Code quote:_
```Markdown
of the Cosmos SDK
```

**Review by ysv — COMMENTED** [review]
I thought it will also include some charts with our feemodel behaviour and examples.
I think that this doc should contain everything you need to know to understand our fee model fully including not only cosmos part but also business logic, examples etc

By checking other cosmos moduleI see that they concentrate on cosmos part mostly but I'm not sure it makes sense without understanding whole approach

@dzmitryhil @miladz68 @wojtek-coreum WDYT ?

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167#-:-NBY0FiF35xr6eAjKHjt:b-j7jrsg)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

**Review by ysv — COMMENTED** [review]
example of doc with some screenshots https://docs.cosmos.network/v0.46/modules/staking/03_messages.html

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167#-:-NBY9Zeq3b3Y-O5wn0W7:baedgw6)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`x/feemodel/spec/README.md` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NBXY8Ij65kBA-LZuYQf:-NBkrKWPD-2dMFW6TmSI:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/9512d52ff60e67e427044b9892f8ec21ee0e8485/x/feemodel/spec/README.md#L12)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

of the Cosmos SDK ?
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
I think the "Abstract" section describes the idea clearly. I will paste images, the problem with second one is that after generating it with real parameters it doesn't present the idea clearly.

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167#-:-NBkrPhcE0-Z1i0Y-Nxf:b-f85s88)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @miladz68)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167)* status: all files reviewed, 8 unresolved discussions (waiting on @begmaroman and @wojtek-coreum)

___
*[`x/feemodel/spec/README.md` line 16 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC03pCZ9cO2eUt4xU_7:-NC03pCZ9cO2eUt4xU_8:bnh2zzs) ([raw file](https://github.com/coreumfoundation/coreum/blob/760b93ec4507c25f3c9b3aafbb27670ecdf2aa43/x/feemodel/spec/README.md#L16)):*
> ```Markdown
> Two charts are presented below, showing how the implemented fee model behaves. Keep in mind that data presented on those charts were generated using `MaxGasPrice` set to `2000` for better readability, while in reality we use `1500000`.
> 
> Chart below presents the dependency between average gas consumed by last block and minimum gas price required by the network.
> ```

average gas consumed by last block 

Don't we use short EMA here ?
___
*[`x/feemodel/spec/README.md` line 18 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC03wss5KjSRWl46Fc5:-NC03wss5KjSRWl46Fc6:bafihd0) ([raw file](https://github.com/coreumfoundation/coreum/blob/760b93ec4507c25f3c9b3aafbb27670ecdf2aa43/x/feemodel/spec/README.md#L18)):*
> ```Markdown
> Chart below presents the dependency between average gas consumed by last block and minimum gas price required by the network.
> 
> Fee model curve
> ```

I can't get meaning of x axis values on this chart 
What does 0, 10, ... 50 mean ?

Lets discuss this chart on the call
By the way I have feeling that we should also use % in code for `EscalationStartBlockGas`
Also According to source code I see that we use constant value for longEMABlockGas. I think this is worth mentioning in chart description
___
*[`x/feemodel/spec/README.md` line 18 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC08P0a4Jfz_XLZp6Gx:-NC08P0b6saIA8J2ACti:b-al16qa) ([raw file](https://github.com/coreumfoundation/coreum/blob/760b93ec4507c25f3c9b3aafbb27670ecdf2aa43/x/feemodel/spec/README.md#L18)):*
> ```Markdown
> Chart below presents the dependency between average gas consumed by last block and minimum gas price required by the network.
> 
> Fee model curve
> ```

it would be really nice to have vertical lines with description similar to this chart (average block load, optimal block load etc) so it self-explanatory even without text.

We can put logic of this section `There are four regions on the fee model curve:` into chart and it will be easier to understand

Is it possible ?


___
*[`x/feemodel/spec/README.md` line 21 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC04JrE0DDKXMOd4tTT:-NC04JrF3rthWrsbBr_x:b-yjk84e) ([raw file](https://github.com/coreumfoundation/coreum/blob/760b93ec4507c25f3c9b3aafbb27670ecdf2aa43/x/feemodel/spec/README.md#L21)):*
> ```Markdown
> 
> TERMS:
> - *long average block gas* is the EMA (exponential moving average) of gas consumed over last 1000 blocks,
> ```

shouldn't we mention that 10,000 & 10 blocks is configurable here ?
___
*[`x/feemodel/spec/README.md` line 35 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC06BgQD4kPagQP52-B:-NC06BgQD4kPagQP52-C:bywb3pk) ([raw file](https://github.com/coreumfoundation/coreum/blob/760b93ec4507c25f3c9b3aafbb27670ecdf2aa43/x/feemodel/spec/README.md#L35)):*
> ```Markdown
> Second chart presents the model behavior over time, presenting how changes in gas consumed by blocks affect the minimum gas price required by the network.
> 
> Fee model time series
> ```

blue line is fully overlapped by red. Lets remove unless we can do smth with it  because it looks confusing
___
*[`x/feemodel/spec/README.md` line 37 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC06Pyp1G_E8a4oQyJQ:-NC06Pyp1G_E8a4oQyJR:b25p2kr) ([raw file](https://github.com/coreumfoundation/coreum/blob/760b93ec4507c25f3c9b3aafbb27670ecdf2aa43/x/feemodel/spec/README.md#L37)):*
> ```Markdown
> Fee model time series
> 
> - x axis represents gas consumed by the following blocks
> ```

It seems like it represent block number or time or I don't understand smth
___
*[`x/feemodel/spec/README.md` line 38 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC05Ytw0wcSq2nqv7h0:-NC05Ytw0wcSq2nqv7h1:b-lls36q) ([raw file](https://github.com/coreumfoundation/coreum/blob/760b93ec4507c25f3c9b3aafbb27670ecdf2aa43/x/feemodel/spec/README.md#L38)):*
> ```Markdown
> 
> - x axis represents gas consumed by the following blocks
> - lef y axis is related to `ShortEMA` (red line) and `LongEMA` (orange line),
> ```

lef -> left
___
*[`x/feemodel/types/model_sim_test.go` line 20 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC00zmuDZ73i2dBmwDP:-NC00zmv6LvvFnye84yx:b-ai8goe) ([raw file](https://github.com/coreumfoundation/coreum/blob/760b93ec4507c25f3c9b3aafbb27670ecdf2aa43/x/feemodel/types/model_sim_test.go#L20)):*
> ```Go
> 	}
> 	// Output: list of gas prices for each gas usage
> 	// Check x/feemodel/spec/assets/curve.png
> ```

can you also remove references to doc with charts in code
e.g `github.com/CoreumFoundation/coreum/x/feemodel/types/model.go:30`

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167)* status: all files reviewed, 8 unresolved discussions (waiting on @begmaroman, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/spec/README.md` line 16 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC03pCZ9cO2eUt4xU_7:-NC0F5Hr-G3f4HBHMSGx:b-ywj4oz) ([raw file](https://github.com/coreumfoundation/coreum/blob/760b93ec4507c25f3c9b3aafbb27670ecdf2aa43/x/feemodel/spec/README.md#L16)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

average gas consumed by last block 

Don't we use short EMA here ?
</blockquote></details>

yes, will fix
___
*[`x/feemodel/spec/README.md` line 18 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC08P0a4Jfz_XLZp6Gx:-NC0E6Se7LNYwgTDMD0P:b-to0e74) ([raw file](https://github.com/coreumfoundation/coreum/blob/760b93ec4507c25f3c9b3aafbb27670ecdf2aa43/x/feemodel/spec/README.md#L18)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

it would be really nice to have vertical lines with description similar to this chart (average block load, optimal block load etc) so it self-explanatory even without text.

We can put logic of this section `There are four regions on the fee model curve:` into chart and it will be easier to understand

Is it possible ?



</blockquote></details>

do we have a graphic designer who could prepare this? I just took a screenshot from google sheet
___
*[`x/feemodel/spec/README.md` line 18 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC03wss5KjSRWl46Fc5:-NC0FA2hBUVb4A4lzz5a:bgw2sf8) ([raw file](https://github.com/coreumfoundation/coreum/blob/760b93ec4507c25f3c9b3aafbb27670ecdf2aa43/x/feemodel/spec/README.md#L18)):*
x is the short ema

> By the way I have feeling that we should also use % in code for EscalationStartBlockGas

whatever you prefer

> Also According to source code I see that we use constant value for longEMABlockGas.

WDYM?
___
*[`x/feemodel/spec/README.md` line 21 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC04JrE0DDKXMOd4tTT:-NC0EKcZ9ihbcInWId7V:bqqlvi5) ([raw file](https://github.com/coreumfoundation/coreum/blob/760b93ec4507c25f3c9b3aafbb27670ecdf2aa43/x/feemodel/spec/README.md#L21)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

shouldn't we mention that 10,000 & 10 blocks is configurable here ?
</blockquote></details>

It's mentioned in `03_params.md`
___
*[`x/feemodel/spec/README.md` line 35 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC06BgQD4kPagQP52-B:-NC0EWDS3fYIr7Tas8p9:b-s5aw2l) ([raw file](https://github.com/coreumfoundation/coreum/blob/760b93ec4507c25f3c9b3aafbb27670ecdf2aa43/x/feemodel/spec/README.md#L35)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

blue line is fully overlapped by red. Lets remove unless we can do smth with it  because it looks confusing
</blockquote></details>

but it's still important in some way
___
*[`x/feemodel/spec/README.md` line 37 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC06Pyp1G_E8a4oQyJQ:-NC0Eehr0ChlEfqbuYJW:b2rt1hs) ([raw file](https://github.com/coreumfoundation/coreum/blob/760b93ec4507c25f3c9b3aafbb27670ecdf2aa43/x/feemodel/spec/README.md#L37)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

It seems like it represent block number or time or I don't understand smth
</blockquote></details>

yea, my bad, x is the block number

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167)* status: 6 of 8 files reviewed, 8 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/spec/README.md` line 16 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC03pCZ9cO2eUt4xU_7:-NC4_J5I3edO9712XaQ3:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/f014ebc48ca442151a89cf000ebfcb9b1f6bd4c9/x/feemodel/spec/README.md#L16)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

yes, will fix
</blockquote></details>

Done.
___
*[`x/feemodel/spec/README.md` line 37 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC06Pyp1G_E8a4oQyJQ:-NC4a5K6EQ5hmSkRBw6o:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/f014ebc48ca442151a89cf000ebfcb9b1f6bd4c9/x/feemodel/spec/README.md#L37)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

yea, my bad, x is the block number
</blockquote></details>

Done.



_Code quote:_
```Markdown
x axis represents gas consumed by the following blocks
```
___
*[`x/feemodel/spec/README.md` line 38 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC05Ytw0wcSq2nqv7h0:-NC4a7yyDTpUotBb0mCh:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/f014ebc48ca442151a89cf000ebfcb9b1f6bd4c9/x/feemodel/spec/README.md#L38)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lef -> left
</blockquote></details>

Done.
___
*[`x/feemodel/types/model_sim_test.go` line 20 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC00zmuDZ73i2dBmwDP:-NC4ak3H78qe97x188oB:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/f014ebc48ca442151a89cf000ebfcb9b1f6bd4c9/x/feemodel/types/model_sim_test.go#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can you also remove references to doc with charts in code
e.g `github.com/CoreumFoundation/coreum/x/feemodel/types/model.go:30`
</blockquote></details>

Done.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/spec/README.md` line 18 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC03wss5KjSRWl46Fc5:-NC6FmbJ5rjUxjTx4IvT:b-ogjbh0) ([raw file](https://github.com/coreumfoundation/coreum/blob/f014ebc48ca442151a89cf000ebfcb9b1f6bd4c9/x/feemodel/spec/README.md#L18)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

x is the short ema

> By the way I have feeling that we should also use % in code for EscalationStartBlockGas

whatever you prefer

> Also According to source code I see that we use constant value for longEMABlockGas.

WDYM?
</blockquote></details>

we need to go on call to resolve this one
___
*[`x/feemodel/spec/README.md` line 18 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC08P0a4Jfz_XLZp6Gx:-NC6FpR_BLdDY_8nVcnO:b-lwhcaj) ([raw file](https://github.com/coreumfoundation/coreum/blob/f014ebc48ca442151a89cf000ebfcb9b1f6bd4c9/x/feemodel/spec/README.md#L18)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

do we have a graphic designer who could prepare this? I just took a screenshot from google sheet
</blockquote></details>

yeah it would be nice
ok lets keep it with this image & I want Dai to improve it. Can you explain to him what is needed ?

He should be invited to slack soon (asked Reza)

resolving
___
*[`x/feemodel/spec/README.md` line 35 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC06BgQD4kPagQP52-B:-NC6HSGu4JsDEtywKwsg:bnx0qk8) ([raw file](https://github.com/coreumfoundation/coreum/blob/f014ebc48ca442151a89cf000ebfcb9b1f6bd4c9/x/feemodel/spec/README.md#L35)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but it's still important in some way
</blockquote></details>

Still I find it frustrating and everyone will have the same feeling like if we forgot to draw this line at all.
Maybe we can name red line as Gas & ShortEMA and in descr put that they mach mostly

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman and @wojtek-coreum)

___
*[`x/feemodel/spec/README.md` line 21 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC04JrE0DDKXMOd4tTT:-NC6I7lt7C1kZis2MyhU:bodavt8) ([raw file](https://github.com/coreumfoundation/coreum/blob/f014ebc48ca442151a89cf000ebfcb9b1f6bd4c9/x/feemodel/spec/README.md#L21)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It's mentioned in `03_params.md`
</blockquote></details>


we need to go on call to resolve this one

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/spec/README.md` line 35 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC06BgQD4kPagQP52-B:-NCJORQ32wQyDmeNeVOy:b-vx5hcr) ([raw file](https://github.com/coreumfoundation/coreum/blob/f014ebc48ca442151a89cf000ebfcb9b1f6bd4c9/x/feemodel/spec/README.md#L35)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Still I find it frustrating and everyone will have the same feeling like if we forgot to draw this line at all.
Maybe we can name red line as Gas & ShortEMA and in descr put that they mach mostly

</blockquote></details>

But they are really not the same thing

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`x/feemodel/spec/README.md` line 18 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/167#-NC03wss5KjSRWl46Fc5:-NCKjinV5zFOtKHbdfhH:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/f014ebc48ca442151a89cf000ebfcb9b1f6bd4c9/x/feemodel/spec/README.md#L18)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

adding ticket for changing EscalationStartBlockGas to %

Changes:
1. X axis should show full number in thousands
2. Clarify in descr that we fixed long average value and were changing short average for this simulation
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/167)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)

**Pull request merged**
