### PR TITLE
Build system fixes

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/782)

### CODE REVIEW

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/782)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/782)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/782)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/782)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/782)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
