### PR TITLE
Integrate the testnet coreum config.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/340)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/340)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/network_test.go` line 125 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/340#-NLWPMEMEF4c6UwJBPFb:-NLWPMEMEF4c6UwJBPFc:b-2iqtik) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e930027a4d9a5e523760bb276028f9c9817ebd0a/pkg/config/network_test.go#L125)):*
> ```Go
> }
> 
> func TestAddFundsToGenesis(t *testing.T) {
> ```

we introduced a FundAccounts function in this module and this tests, tests that. it is a good tests to have and we should not remove it.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/340)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`pkg/config/network.go` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/340#-NLXif2LA19MP1xDNZvo:-NLXif2LA19MP1xDNZvp:bh76wvk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a5a00178f8de9df711d58f493ed2f2900e37c67a/pkg/config/network.go#L39)):*
> ```Go
> 
> 	//go:embed genesis/gentx/coreum-devnet-1
> 	devGenTxsFS embed.FS
> ```

minor:
I see you renamed devnet to dev in a few places. I still prefer `devnet`
___
*[`pkg/config/network.go` line 114 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/340#-NLVjmJtESDDWD2KFehh:-NLVjmJuC1U4KE7NvGmD:b-lvd12c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a5a00178f8de9df711d58f493ed2f2900e37c67a/pkg/config/network.go#L114)):*
> ```Go
> 		constant.ChainIDTest: {
> 			ChainID:              constant.ChainIDTest,
> 			Enabled:              true,
> ```

can we make testnet default env from now
___
*[`pkg/config/network.go` line 115 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/340#-NLVjiKB9-rqpGir5rAY:-NLVjiKC4Kjtnx8puzvp:b-nbzg8q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a5a00178f8de9df711d58f493ed2f2900e37c67a/pkg/config/network.go#L115)):*
> ```Go
> 			ChainID:              constant.ChainIDTest,
> 			Enabled:              true,
> 			GenesisTime:          time.Date(2023, 1, 1, 12, 0, 0, 0, time.UTC),
> ```

official launch date is 18.01.2023 lets put it here
___
*[`pkg/config/network_test.go` line 258 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/340#-NLXjF2g92nD4AfiXqOS:-NLXjF2g92nD4AfiXqOT:b-njdhux) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a5a00178f8de9df711d58f493ed2f2900e37c67a/pkg/config/network_test.go#L258)):*
> ```Go
> }
> 
> func setField(object interface{}, fieldName string, value interface{}) {
> ```

minor: `unsafeSetField` ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/340)* status: all files reviewed, 4 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/network.go` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/340#-NLXif2LA19MP1xDNZvo:-NL_IIQX7dKQkmD8lzgL:bmiik80) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a5a00178f8de9df711d58f493ed2f2900e37c67a/pkg/config/network.go#L39)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
I see you renamed devnet to dev in a few places. I still prefer `devnet`
</blockquote></details>

Actually I did it becase they called dev in 90% of places. 
___
*[`pkg/config/network.go` line 114 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/340#-NLVjmJtESDDWD2KFehh:-NL_IRoeDk6eXtr0oYyN:bdao4zt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a5a00178f8de9df711d58f493ed2f2900e37c67a/pkg/config/network.go#L114)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can we make testnet default env from now
</blockquote></details>

Sure we can. Updated.
___
*[`pkg/config/network.go` line 115 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/340#-NLVjiKB9-rqpGir5rAY:-NL_J3gU-3B_F76v1VhZ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a5a00178f8de9df711d58f493ed2f2900e37c67a/pkg/config/network.go#L115)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

official launch date is 18.01.2023 lets put it here
</blockquote></details>

Done.



_Code quote:_
```Go
 time.Date(2023, 1, 1, 12, 0, 0, 0, time
```
___
*[`pkg/config/network_test.go` line 258 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/340#-NLXjF2g92nD4AfiXqOS:-NL_J7s07Z79xLZzFazF:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a5a00178f8de9df711d58f493ed2f2900e37c67a/pkg/config/network_test.go#L258)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: `unsafeSetField` ?
</blockquote></details>

Updated.

**Review by ysv — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/340)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 11 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/340)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/340)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/340)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
