### PR TITLE
Make `MsgSubmitProposal` a nondeterministic message

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/377)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/377)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/377)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`integration-tests/chain.go` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/377#-NNaiyFE83sWpBq6M0zw:-NNb2mST6nsBLkdDK8DM:b29lmqk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/35fb8e755e5790b44da9e93bcc76c755aae49c6c/integration-tests/chain.go#L123)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we need it? What about the `Amount` it seems similar.
</blockquote></details>

Just to not mix the two, Amount is for what account wants to transfer, NondeterministicMessagesGas specifically defines the gas assigned to nondeterministic txs
___
*[`integration-tests/gov.go` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/377#-NNaiqnKArlOxAqs_BMD:-NNb2xKd5_ETZtPQKfN8:b2zvmqc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/35fb8e755e5790b44da9e93bcc76c755aae49c6c/integration-tests/gov.go#L20)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is it enough for any type? Maybe more ?
</blockquote></details>

If we see that tests stop passing we will increase

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/377)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/377)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`integration-tests/chain.go` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/377#-NNaiyFE83sWpBq6M0zw:-NNfNJf09srfJHlzBQCv:bjywhpf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/35fb8e755e5790b44da9e93bcc76c755aae49c6c/integration-tests/chain.go#L123)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But we already use the Amount for such cases, for example WASM. 
</blockquote></details>

Then it should be converted.
___
*[`integration-tests/gov.go` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/377#-NNaiqnKArlOxAqs_BMD:-NNfNU8B3ZsuXSZlT-hC:b-jtpi56) ([raw file](https://github.com/CoreumFoundation/coreum/blob/35fb8e755e5790b44da9e93bcc76c755aae49c6c/integration-tests/gov.go#L20)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Maybe we can estimate before the submission and fund the account with the proper amount instead?
</blockquote></details>

it's nondeterministic so it may change all the time.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/377)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/chain.go` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/377#-NNaiyFE83sWpBq6M0zw:-NNg8AmxDBSflRyikFOr:b5nj10s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/35fb8e755e5790b44da9e93bcc76c755aae49c6c/integration-tests/chain.go#L123)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I still don't see a need for it, the value here is quite random, so just append to the amount.
I would agree if we somehow check that we spend just that amount, but we don't so no need to introduce additional amount.
</blockquote></details>

IMO it's better to clearly separate them. @miladz68 @ysv

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/377)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/chain.go` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/377#-NNaiyFE83sWpBq6M0zw:-NNkNQ5U6H6I6OnlQrlf:bo94hik) ([raw file](https://github.com/CoreumFoundation/coreum/blob/35fb8e755e5790b44da9e93bcc76c755aae49c6c/integration-tests/chain.go#L123)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

IMO it's better to clearly separate them. @miladz68 @ysv 
</blockquote></details>

I think treating it as non deterministic is a better approach. just let the default cosmos behavior take over and estimate the gas and then submit.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/377)* status: 2 of 14 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/gov.go` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/377#-NNaiqnKArlOxAqs_BMD:-NNl9dTPB2Yig54GSLIN:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/35fb8e755e5790b44da9e93bcc76c755aae49c6c/integration-tests/gov.go#L20)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Estimate before the TX execution with gas multiplier = 1.3 and that is about 99% garanty for the znet.
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/377)* status: 1 of 14 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/gov.go` line 20 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/377#-NNaiqnKArlOxAqs_BMD:-NNp03UM-4qCJpcjjCeD:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/35fb8e755e5790b44da9e93bcc76c755aae49c6c/integration-tests/gov.go#L20)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's use prev solution :-)
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 12 files at r3, 3 of 6 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/377)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
