### PR TITLE
bump coreum version to v3

### PR DESCRIPTION
**Pull request by miladz68**
# Description
in this PR we update the coreum version from v2 to v3
# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/644)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 221 of 221 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/644)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @vertex451, and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/644)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 220 of 221 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/644)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/644)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 58 of 58 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/644)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/644)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
