### PR TITLE
Add Burnt NFT invariant.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/452)

### CODE REVIEW

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/452)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — DISMISSED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/452#-:-NR7ir6A9CzB9wzHLRs1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/invariant.go` line 100 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/452#-NR7ii0c-c54fTGuIdGZ:-NR7ii0c-c54fTGuIdG_:b-9j7ejd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8201e1682aaf230c2bc8a6c3e19a44db2c497a42/x/asset/nft/keeper/invariant.go#L100)):*
> ```Go
> 		var (
> 			msg        string
> 			foundCount int
> ```

let's call it `violationCount`

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/452)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/452)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/452)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Pull request merged**
