### PR TITLE
Integrate IBC hooks

### PR DESCRIPTION
**Pull request by ysv**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/contracts/ibc/ibc-hooks-counter/src/contract.rs` line 132 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-Nv7rdLS7YpTZcqO6itn:-Nv7rdLS7YpTZcqO6ito:b-sdehw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/008429d1c98f102266b741d6a494486f8d296f77/integration-tests/contracts/ibc/ibc-hooks-counter/src/contract.rs#L132)):*
> ```XML
>     use super::*;
> 
>     pub fn receive_ack(
> ```

I have question here lets discuss 
https://github.com/cosmos/ibc-apps/tree/main/modules/ibc-hooks#interface-for-receiving-the-acks-and-timeouts

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: 0 of 21 files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @keyleu, @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 11 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvBLIpG45GnYAdTRa3x:-NvCPM7DDYkDsrulf217:b-uholas) ([raw file](https://github.com/CoreumFoundation/coreum/blob/19a8eb610c634dd1857d9e840aff57d076d904a5/go.mod#L11)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Did you try to use it in `require` as normal dependency instead of the `replace` ?
</blockquote></details>

yes, I've tried this and it doesn't work
___
*[`go.mod` line 35 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvBykGzDXJatyQ2kLJi:-NvCPSU9BQ8fN77E-4JR:bwwqua4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/19a8eb610c634dd1857d9e840aff57d076d904a5/go.mod#L35)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you remember that you need to update the version to the latest with the fixed security issue?
Same for integration-tests module.
</blockquote></details>

yes, sure I have a separate task for this
___
*[`app/app.go` line 563 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvBzd8g8hTpaameBHNT:-NvCPekYB1wpFN4b24HP:b6ukui4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/19a8eb610c634dd1857d9e840aff57d076d904a5/app/app.go#L563)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

nit: You can merge 2 lines, since you don't use `wasmHooks` later
</blockquote></details>

yes, but I can't take address `&` without initialising var.
I mean I can't do `app.Ics20WasmHooks = &ibchooks.NewWasmHooks(...)`

I can use `lo.ToPtr` if u prefer.

Also I checked integration in osmosis & juno and they also use pointer for Ics20WasmHooks so I prefer to keep it as pointer
___
*[`app/app.go` line 688 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvC-0gC5olEhtCKgOgO:-NvCQPv34iYbSv9C1oW9:bx4k52s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/19a8eb610c634dd1857d9e840aff57d076d904a5/app/app.go#L688)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Can you pass it as arg in the `ibchooks.NewWasmHooks(&app.IBCHooksKeeper, nil, ChosenNetwork.Provider.GetAddressPrefix())`? Because you set it to nil in`NewWasmHooks` func , and later set it manually,
</blockquote></details>

I was following their integration guideline here: https://github.com/cosmos/ibc-apps/tree/main/modules/ibc-hooks#installation

But I agree with your comment. will try to change
___
*[`integration-tests/contracts/ibc/ibc-hooks-counter/src/contract.rs` line 119 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvCCTicBJN_4rLAsKsp:-NvCRh1wA5_6dxpICUdt:b-7lliop) ([raw file](https://github.com/CoreumFoundation/coreum/blob/19a8eb610c634dd1857d9e840aff57d076d904a5/integration-tests/contracts/ibc/ibc-hooks-counter/src/contract.rs#L119)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We need to have a test to test it.
</blockquote></details>

on it
___
*[`integration-tests/contracts/ibc/ibc-hooks-counter/src/integration_tests.rs` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvC1bIv77K2TfeaMtFa:-NvCRl6-4swOWGgf8Ier:b-jskn03) ([raw file](https://github.com/CoreumFoundation/coreum/blob/19a8eb610c634dd1857d9e840aff57d076d904a5/integration-tests/contracts/ibc/ibc-hooks-counter/src/integration_tests.rs#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you need the rust integration tests, unit tests, etc? I propose to keep only the code you need for the go-based integration test.
</blockquote></details>

as agree, keeping it for now for review purpose & will remove later
___
*[`integration-tests/ibc/hooks_test.go` line 132 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvC2am27OHFrv91sSQf:-NvCUaQB4zAVZlZLZqjg:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/19a8eb610c634dd1857d9e840aff57d076d904a5/integration-tests/ibc/hooks_test.go#L132)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you please explain in the comment how it works?
</blockquote></details>

Done.
___
*[`integration-tests/ibc/hooks_test.go` line 200 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvC6VICBsTW5Kuownko:-NvCSJwl1SZcKLorePZp:bp9bd43) ([raw file](https://github.com/CoreumFoundation/coreum/blob/19a8eb610c634dd1857d9e840aff57d076d904a5/integration-tests/ibc/hooks_test.go#L200)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

nit: I would call it `awaitHooksContractCounterState`
</blockquote></details>

problem here that it sounds like I await for `CounterState` but I also await for total_funds

Changed to `awaitHooksCounterContractState`

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: 0 of 21 files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @keyleu, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`app/app.go` line 688 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvC-0gC5olEhtCKgOgO:-NvCUqIYAFcV560AsRdz:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/19a8eb610c634dd1857d9e840aff57d076d904a5/app/app.go#L688)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I was following their integration guideline here: https://github.com/cosmos/ibc-apps/tree/main/modules/ibc-hooks#installation

But I agree with your comment. will try to change
</blockquote></details>

Done

**Review by keyleu — DISMISSED** [review]
> Reviewed 16 of 21 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvCdhIl7QmC8HMqZY5S:-NvHgizuBbh-CA0cyMji:b-tr0oy8) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Myself: upgrade should probably be added
</blockquote></details>

myself: checked current tests, all ok, pending check for the one with Ack/Timeout processing

___
___
*[`integration-tests/contracts/ibc/ibc-hooks-counter/src/contract.rs` line 164 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvHfD3X3Ti6zF1hbRk6:-NvHfD3X3Ti6zF1hbRk7:b-ors0rx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5b2f5014c3c6b14723023bca3bceacdd37981d6e/integration-tests/contracts/ibc/ibc-hooks-counter/src/contract.rs#L164)):*
> ```XML
> 
> pub fn naive_add_coins(lhs: &Vec<Coin>, rhs: &Vec<Coin>) -> Vec<Coin> {
>     // This is a naive, inneficient  implementation of Vec<Coin> addition.
> ```

nit: some typos here

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 16 of 21 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 678 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvkKTJa4G6aRehFkwei:-NvkKTJa4G6aRehFkwej:b-ll6om7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/300910768d846f7606b50733c5f5d8d174a424a1/app/app.go#L678)):*
> ```Go
> 	ibcRouter.AddRoute(
> 		ibctransfertypes.ModuleName,
> 		wibctransfer.NewPurposeMiddleware(transfer.NewIBCModule(app.TransferKeeper.Keeper)),
> ```

what happened to the purpose middleware ? we will definitely need it.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 14 of 21 files at r1, 3 of 5 files at r2, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: all files reviewed, 5 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: 15 of 23 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @keyleu, @masihyeganeh, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvCdhIl7QmC8HMqZY5S:-NwOtaA7B1wAtUcJNjJK:b-896fix) (no related file):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

myself: checked current tests, all ok, pending check for the one with Ack/Timeout processing
</blockquote></details>

Done.

___
___
*[`app/app.go` line 678 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvkKTJa4G6aRehFkwei:-NwOzxfyBXjh3KPMHbI9:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/300910768d846f7606b50733c5f5d8d174a424a1/app/app.go#L678)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

what happened to the purpose middleware ? we will definitely need it.
</blockquote></details>

Done.
___
*[`integration-tests/contracts/ibc/ibc-hooks-counter/src/contract.rs` line 119 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvCCTicBJN_4rLAsKsp:-NwOw5BjBcRquSxcT2p_:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/19a8eb610c634dd1857d9e840aff57d076d904a5/integration-tests/contracts/ibc/ibc-hooks-counter/src/contract.rs#L119)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

on it
</blockquote></details>

Done.
___
*[`integration-tests/contracts/ibc/ibc-hooks-counter/src/integration_tests.rs` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-NvC1bIv77K2TfeaMtFa:-NwOwgo28oKBxcSLBUsG:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/19a8eb610c634dd1857d9e840aff57d076d904a5/integration-tests/contracts/ibc/ibc-hooks-counter/src/integration_tests.rs#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

as agree, keeping it for now for review purpose & will remove later
</blockquote></details>

Done.

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 5 files at r4, 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @keyleu, @masihyeganeh, and @wojtek-coreum)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: 21 of 25 files reviewed, 3 unresolved discussions (waiting on @keyleu, @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 114 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-Nwd3pOOBjjr5RMmm3j5:-Nwd3pOP5PflCm30qo8a:bkj1m87) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1512b523c3ffd358285b07e8b7d639352616812/.github/workflows/ci.yml#L114)):*
> ```YAML
>         with:
>           path: ~/.cache/golangci-lint
>           key: ${{ runner.os }}-linter-cache-v3-${{ steps.goversion.outputs.GO_VERSION }}
> ```

Why do you need that change?
___
*[`integration-tests/ibc/hooks_test.go` line 258 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-Nwd4TPB0fXZvzf5ek6b:-Nwd4TPB0fXZvzf5ek6c:by5xt3s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1512b523c3ffd358285b07e8b7d639352616812/integration-tests/ibc/hooks_test.go#L258)):*
> ```Go
> 	)
> 
> 	// Sudo IBCAck or IBCTimeout message will be sent to the contract specified in memo.
> ```

Let's discuss it today one more time, please.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @keyleu, @masihyeganeh, @wojtek-coreum, and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: 24 of 25 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/ibc/hooks_test.go` line 258 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/801#-Nwd4TPB0fXZvzf5ek6b:-NwiJoBy9hqa5d8Fo2FJ:b-acwr2f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b1512b523c3ffd358285b07e8b7d639352616812/integration-tests/ibc/hooks_test.go#L258)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok
</blockquote></details>

discussed on call

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, @masihyeganeh, and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @masihyeganeh, and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @masihyeganeh, and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 7 of 10 files at r5, 1 of 3 files at r7, 1 of 1 files at r8, 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @masihyeganeh, and @wojtek-coreum)

**Review by keyleu — APPROVED** [review]
> Reviewed 1 of 5 files at r4, 7 of 10 files at r5, 1 of 3 files at r7, 1 of 1 files at r8, 1 of 6 files at r10, 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/801)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @wojtek-coreum)

**Pull request merged**
