### PR TITLE
NFT full integration 

### PR DESCRIPTION
**Pull request by dzmitryhil**
The PR fully integrates the copied NFT module of the cosmos SDK.

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/270)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/270)* status: 0 of 61 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 203 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/270#-NHcpKg414BDC8ujae2R:-NHcpKg414BDC8ujae2S:b-oiriya) ([raw file](https://github.com/coreumfoundation/coreum/blob/b52fc41e858c6b3be3fe1c0692e8c728d16e58db/app/app.go#L203)):*
> ```Go
> 		wasm.ModuleName:                {authtypes.Burner},
> 		assettypes.ModuleName:          {authtypes.Minter, authtypes.Burner},
> 		nft.ModuleName:                 {}, // the line is required by the nft module to have the module account stored in the account keeper
> ```

@wojtek-coreum we need that line, check the comment

**Review by wojtek-coreum — APPROVED** [review]
"Rebase don't squash !!!" -> you mean that two separate commits should be generated in master?

> Reviewed 61 of 61 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/270#-:-NHcpiDl9mKp93Kb4_ME:b-98k9ch)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by wojtek-coreum — DISMISSED** [review]
Ok, so @ysv must enable this option in the repo

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/270#-:-NHd6ew838x-I__YTzCU:b-xe1ljc)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 60 of 61 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/270)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
