### PR TITLE
added complex integration tests for NFTs

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/425)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/425)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 541 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPanHIwBW-NPlzsRgT-:-NPanHIwBW-NPlzsRgT0:bksgqmj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff9d107f259e6fd9839af8f5674c176b9a4a2b14/integration-tests/modules/assetnft_test.go#L541)):*
> ```Go
> 
> // TestAssetNFTBurnFrozen tests that frozen NFT cannot be burnt.
> func TestAssetNFTBurnFrozen(t *testing.T) {
> ```

Is issuer allowed to burn frozen nft owned by him? In either case it should be tested too.
___
*[`integration-tests/modules/assetnft_test.go` line 602 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPamjHHB_k1-Bingtwd:-NPamjHHB_k1-Bingtwe:bnokk7w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff9d107f259e6fd9839af8f5674c176b9a4a2b14/integration-tests/modules/assetnft_test.go#L602)):*
> ```Go
> 	)
> 	requireT.NoError(err)
> 	requireT.Equal(chain.GasLimitByMsgs(mintMsg), uint64(res.GasUsed))
> ```

here and below: there is no need to verify gas. It is done once in another tests.
___
*[`integration-tests/modules/assetnft_test.go` line 619 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPamxAs5fNxIEVViHfX:-NPamxAs5fNxIEVViHfY:b-yhss4l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff9d107f259e6fd9839af8f5674c176b9a4a2b14/integration-tests/modules/assetnft_test.go#L619)):*
> ```Go
> 	requireT.Equal(chain.GasLimitByMsgs(msgFreeze), uint64(res.GasUsed))
> 
> 	queryRes, err := nftClient.Frozen(ctx, &assetnfttypes.QueryFrozenRequest{
> ```

This is not needed here as it is (or should be) tested in basic test of freezing
___
*[`integration-tests/modules/assetnft_test.go` line 655 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPanCNG6dllsy1PTarj:-NPanCNG6dllsy1PTark:bsa4xwg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff9d107f259e6fd9839af8f5674c176b9a4a2b14/integration-tests/modules/assetnft_test.go#L655)):*
> ```Go
> 	)
> 	requireT.ErrorIs(err, sdkerrors.ErrUnauthorized)
> }
> ```

and then:
1. unfreeze
2. verify that now it's possible to burn
___
*[`integration-tests/modules/assetnft_test.go` line 1119 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPan_n04EFFhmUveIxX:-NPan_n04EFFhmUveIxY:b-ht0yb1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff9d107f259e6fd9839af8f5674c176b9a4a2b14/integration-tests/modules/assetnft_test.go#L1119)):*
> ```Go
> 	)
> 	requireT.NoError(err)
> 	requireT.Greater(res.Height, int64(1))
> ```

why is it here?
___
*[`x/asset/nft/keeper/keeper.go` line 203 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPanrtuAsspwoeYOMZt:-NPanrtuAsspwoeYOMZu:b-787li9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff9d107f259e6fd9839af8f5674c176b9a4a2b14/x/asset/nft/keeper/keeper.go#L203)):*
> ```Go
> 	}
> 
> 	if err = k.isNFTSendable(ctx, classID, id); err != nil {
> ```

Please add a comment because it is not straightforward why `isNFTSendable` is checked inside `Burn`
___
*[`x/asset/nft/keeper/keeper.go` line 203 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPao89VBzu0jTMxq4U0:-NPao89VBzu0jTMxq4U1:b-3yx8rf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff9d107f259e6fd9839af8f5674c176b9a4a2b14/x/asset/nft/keeper/keeper.go#L203)):*
> ```Go
> 	}
> 
> 	if err = k.isNFTSendable(ctx, classID, id); err != nil {
> ```

Also it means that issuer is allowed to burn frozen token. I'm not saying that it is incorrect, just want to ensure that we all understand this.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/425)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 541 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPanHIwBW-NPlzsRgT-:-NPataU3C3IuAoG3doX0:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff9d107f259e6fd9839af8f5674c176b9a4a2b14/integration-tests/modules/assetnft_test.go#L541)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is issuer allowed to burn frozen nft owned by him? In either case it should be tested too.
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetnft_test.go` line 602 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPamjHHB_k1-Bingtwd:-NPatjEo9bmZCdP_ta9D:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff9d107f259e6fd9839af8f5674c176b9a4a2b14/integration-tests/modules/assetnft_test.go#L602)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

here and below: there is no need to verify gas. It is done once in another tests.
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetnft_test.go` line 619 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPamxAs5fNxIEVViHfX:-NPapjrSD0bXesb1tLTd:boob2jv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff9d107f259e6fd9839af8f5674c176b9a4a2b14/integration-tests/modules/assetnft_test.go#L619)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is not needed here as it is (or should be) tested in basic test of freezing
</blockquote></details>

this will help to debug the test if anything goes wrong. 
___
*[`integration-tests/modules/assetnft_test.go` line 655 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPanCNG6dllsy1PTarj:-NPbfsnEEv0lCmQISs4Z:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff9d107f259e6fd9839af8f5674c176b9a4a2b14/integration-tests/modules/assetnft_test.go#L655)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

and then:
1. unfreeze
2. verify that now it's possible to burn
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetnft_test.go` line 1119 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPan_n04EFFhmUveIxX:-NPbehvr3cw10_HdMnay:bx7479s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff9d107f259e6fd9839af8f5674c176b9a4a2b14/integration-tests/modules/assetnft_test.go#L1119)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why is it here?
</blockquote></details>

Done and removed. 
___
*[`x/asset/nft/keeper/keeper.go` line 203 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPanrtuAsspwoeYOMZt:-NPbf6itC2evp1k4fALM:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff9d107f259e6fd9839af8f5674c176b9a4a2b14/x/asset/nft/keeper/keeper.go#L203)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please add a comment because it is not straightforward why `isNFTSendable` is checked inside `Burn`
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 203 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPao89VBzu0jTMxq4U0:-NPbf99x0MhaYbqwZ4f0:b-1ul8s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ff9d107f259e6fd9839af8f5674c176b9a4a2b14/x/asset/nft/keeper/keeper.go#L203)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Also it means that issuer is allowed to burn frozen token. I'm not saying that it is incorrect, just want to ensure that we all understand this.
</blockquote></details>

That's correct.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/425)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 541 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPuuKsSEGRMo1qHYGVV:-NPuuKsSEGRMo1qHYGVW:b-fhz5ul) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/integration-tests/modules/assetnft_test.go#L541)):*
> ```Go
> 
> // TestAssetNFTBurn tests that burning an nft will erase all
> // records for it related to freezing and whitelisting.
> ```

only freezing
___
*[`integration-tests/modules/assetnft_test.go` line 541 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPuucKPAmLPZwh5dKX-:-NPuucKPAmLPZwh5dKX0:b-97edug) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/integration-tests/modules/assetnft_test.go#L541)):*
> ```Go
> 
> // TestAssetNFTBurn tests that burning an nft will erase all
> // records for it related to freezing and whitelisting.
> ```

from what I see you only check that token is removed from nft module after burning, there is nothing about verifying that freezing record is removed.
___
*[`integration-tests/modules/assetnft_test.go` line 817 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPuv4VI4fZ6imnm3Sxw:-NPuv4VI4fZ6imnm3Sxx:bjux6gw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/integration-tests/modules/assetnft_test.go#L817)):*
> ```Go
> 		Features: []assetnfttypes.ClassFeature{
> 			assetnfttypes.ClassFeature_freezing,
> 			assetnfttypes.ClassFeature_burning,
> ```

Burning should work without this feature being enabled
___
*[`integration-tests/modules/assetnft_test.go` line 871 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPuvBYFDF0iKGy4LqTF:-NPuvBYFDF0iKGy4LqTG:b-38wf03) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/integration-tests/modules/assetnft_test.go#L871)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// burn from issuer (burn is allowed even though nft it is frozen)
> ```

nft is frozen
___
*[`x/asset/nft/keeper/keeper.go` line 213 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPutpWQCJ0jrCs8NZnC:-NPutpWQCJ0jrCs8NZnD:b-r7woem) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/x/asset/nft/keeper/keeper.go#L213)):*
> ```Go
> 	}
> 
> 	if err := k.deleteWhitelistingForNFT(ctx, classID, id); err != nil {
> ```

we decided to not do this

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/425)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 209 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPvPbpE6z6P3_jU_SMx:-NPvPbpF2vPXT0DLNZGq:buvva1e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/x/asset/nft/keeper/keeper.go#L209)):*
> ```Go
> 
> 	// if the token is burnt the storage needs to be cleaned up, for both the freezing and whitelisting.
> 	if err := k.SetFrozen(ctx, classID, id, false); err != nil {
> ```

I've incorporated this into my PR: https://reviewable.io/reviews/CoreumFoundation/coreum/429#-

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/425)* status: all files reviewed, 6 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 541 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPuuKsSEGRMo1qHYGVV:-NQ00zNS4Qdy7W-AGxu1:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/integration-tests/modules/assetnft_test.go#L541)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

only freezing
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetnft_test.go` line 541 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPuucKPAmLPZwh5dKX-:-NQ01zLH38ks1LPBrts_:buktcgb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/integration-tests/modules/assetnft_test.go#L541)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

from what I see you only check that token is removed from nft module after burning, there is nothing about verifying that freezing record is removed.
</blockquote></details>

Done.
The test relied on invariant to fail. but now the query is added.
___
*[`integration-tests/modules/assetnft_test.go` line 817 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPuv4VI4fZ6imnm3Sxw:-NQ02KiK5KJLp9Nniph0:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/integration-tests/modules/assetnft_test.go#L817)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Burning should work without this feature being enabled
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetnft_test.go` line 871 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPuvBYFDF0iKGy4LqTF:-NQ02Ojg4JGmgU0g4XEZ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/integration-tests/modules/assetnft_test.go#L871)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

nft is frozen
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 209 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPvPbpE6z6P3_jU_SMx:-NQ03aez0JwD3wMpj-Fk:b-xjli0q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/x/asset/nft/keeper/keeper.go#L209)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I've incorporated this into my PR: https://reviewable.io/reviews/CoreumFoundation/coreum/429#-
</blockquote></details>

I don't understand what you mean and what needs to be done here. 
___
*[`x/asset/nft/keeper/keeper.go` line 213 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPutpWQCJ0jrCs8NZnC:-NQ03eee3MWkv289Pa7c:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/x/asset/nft/keeper/keeper.go#L213)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

we decided to not do this
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/425)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 540 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NQ0OonQ22QFSMHzxcjo:-NQ0OonQ22QFSMHzxcjp:b-rwak5y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/integration-tests/modules/assetnft_test.go#L540)):*
> ```Go
> }
> 
> // TestAssetNFTBurn tests that burning an nft will erase all
> ```

comment start with wrong function name
___
*[`x/asset/nft/keeper/keeper.go` line 209 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPvPbpE6z6P3_jU_SMx:-NQ0P8Y7583N1e9NMAni:bt38r76) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/x/asset/nft/keeper/keeper.go#L209)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't understand what you mean and what needs to be done here. 
</blockquote></details>

Nothing needs to be done, just informing. It's a non-blocking comment.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/425)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 540 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NQ0OonQ22QFSMHzxcjo:-NQ0QLEw-4nzlgw6AUwX:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/integration-tests/modules/assetnft_test.go#L540)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

comment start with wrong function name
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 209 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/425#-NPvPbpE6z6P3_jU_SMx:-NQ0PtrXEuHvWKEPfIUS:b-q8ilnv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/58540b4c0c067b6d77f3309074a967d0dfaf7739/x/asset/nft/keeper/keeper.go#L209)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Nothing needs to be done, just informing. It's a non-blocking comment.
</blockquote></details>

gotcha

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/425)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/425)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/425)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
