### PR TITLE
Authz contract modifications

### PR DESCRIPTION
**Pull request by keyleu**
# Description

- Modified the authz contract to use the types that we have in the coreum wasm sdk instead of extra proto files.
- Added new authz example in our contract:
    1. Seller issues and mints and NFT to himself.
    2. Seller grants send permission to the contract and executes an Offer with an expected price (assetFT).
    3. The contract uses this permission to send the NFT to himself.
    4. Buyer pays the price and the contract sends the NFT to the Buyer and the AssetFT to the Seller.

- Added deprecated comment to our NFT MsgSend so that our Rust protobuf generator generates the types with the flag Deprecated for the message to avoid confusion for developers.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)

### CODE REVIEW

**Review by miladz68 — COMMENTED** [review]
> Reviewed 15 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: 15 of 16 files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @wojtek-coreum, and @ysv)

___
*[`integration-tests/contracts/modules/authz/Cargo.toml` line 37 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-NiEHATMDo4hKEF5Oz6R:-NiEHATMDo4hKEF5Oz6S:b-9x7ce9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65870d6c8cfdd26d23e4e7009f6de967519ec529/integration-tests/contracts/modules/authz/Cargo.toml#L37)):*
> ```TOML
> cw-storage-plus = "1.1.0"
> cosmwasm-schema = "1.5.0"
> # TODO(keyleu): Change to coreum-wasm-sdk = "0.2.1" when it's published
> ```

update this and I will approve.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/contracts/modules/authz/Cargo.toml` line 37 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-NiEHATMDo4hKEF5Oz6R:-NiEP8gQ23286F-1nR4U:b-bk8tu1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/074a5be5dd24b61a36c884fe4f93460892e6cb52/integration-tests/contracts/modules/authz/Cargo.toml#L37)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

update this and I will approve.
</blockquote></details>

Yes, waiting for a coreum_wasm_sdk merge and I will update.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/contracts/modules/authz/Cargo.toml` line 37 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-NiEHATMDo4hKEF5Oz6R:-NiEfWPM46pJEGSGDqJK:bqq2z1a) ([raw file](https://github.com/CoreumFoundation/coreum/blob/074a5be5dd24b61a36c884fe4f93460892e6cb52/integration-tests/contracts/modules/authz/Cargo.toml#L37)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

Yes, waiting for a coreum_wasm_sdk merge and I will update.
</blockquote></details>

Hi @miladz68!  wasm_sdk is published to crates and this is updated with latest version now (for both the PRs)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: 10 of 16 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-NiKQV_p66Cwy6R3VL-d:-NiKQV_p66Cwy6R3VL-e:b-g144mr) (no related file):*
In previous PR I added `Stargate` function to this contract. There were to reasons:
- being able to send messages not covered by cosmos sdk
- avoiding adding new function for each message

Taking those, I suggest to use that stargate function instead of adding new functions for nft. At the end of the day Stargate message is used anyway.

___

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: 10 of 16 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-NiKQV_p66Cwy6R3VL-d:-NiKRpQy1y8akHYe56z1:bnecimy) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

In previous PR I added `Stargate` function to this contract. There were to reasons:
- being able to send messages not covered by cosmos sdk
- avoiding adding new function for each message

Taking those, I suggest to use that stargate function instead of adding new functions for nft. At the end of the day Stargate message is used anyway.
</blockquote></details>

I can't simply use the stargate function, the idea here is to showcase how we can trade an NFT for an AssetFT (or viceversa) using a combination of Authz module + Smart Contract interaction.

For this, we need to use a StargateMsg and modify the state of the contract with the nft information so that someone can come and buy it. I would need a new function anyway because we need to store the nft information somewhere in the contract.

My idea was to have everything in the same contract so that users can easily find in the same place how you can combine the Authz module with our AssetFTs/AssetNFTs because these contracts are example contracts for developers.

I could close this PR and instead put the contract in a different repository only for this use case if you think this doesn't belong here. What do you think @ysv @miladz68?

___

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 10 of 16 files at r1, 2 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 10 of 16 files at r1, 2 of 2 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: all files reviewed, 5 unresolved discussions (waiting on @keyleu, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-NiKQV_p66Cwy6R3VL-d:-Ni_A2Pd3AoGH8t8cs8K:beceh5q) (no related file):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

I can't simply use the stargate function, the idea here is to showcase how we can trade an NFT for an AssetFT (or viceversa) using a combination of Authz module + Smart Contract interaction.

For this, we need to use a StargateMsg and modify the state of the contract with the nft information so that someone can come and buy it. I would need a new function anyway because we need to store the nft information somewhere in the contract.

My idea was to have everything in the same contract so that users can easily find in the same place how you can combine the Authz module with our AssetFTs/AssetNFTs because these contracts are example contracts for developers.

I could close this PR and instead put the contract in a different repository only for this use case if you think this doesn't belong here. What do you think @ysv ?
</blockquote></details>

In general I would agree with Wojtek & my initial idea was to put it into tutorials

But after reviewing PR, I'm ok to keep it here. The main benefits are:
1. we have real usage for authz with custom message so we test 2 things in a single contract (authz.Exec + custom authz permission)
2. the code here is tested & has full logic (both permission grant & contract call) which is opposite to the idea of putting it into tutorial repo which doesn't have testing framework & would cover 1 part

So I don't have very strong opinion but a bit in favour of keeping it here

___
___
*[`integration-tests/contracts/modules/authz/src/msg.rs` line 6 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-Ni_8M045f7UXKA3ZslF:-Ni_8M045f7UXKA3ZslG:b-x4jqi1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2ad14783d976e50ef47300175c11555a3095c54/integration-tests/contracts/modules/authz/src/msg.rs#L6)):*
> ```XML
> #[cw_serde]
> pub struct InstantiateMsg {
>     //Granter used for transfering tokens from the contract in behalf of him.
> ```

this grant is for NFT, right ?
tokens sounds confusing
___
*[`integration-tests/modules/wasm_test.go` line 55 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-Ni_8lkcAerZUPDaWGOi:-Ni_8lkd1YDaPvDGbDZH:b5n77i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2ad14783d976e50ef47300175c11555a3095c54/integration-tests/modules/wasm_test.go#L55)):*
> ```Go
> }
> 
> type authzMethod string
> ```

why authz method ?
this name is confusing 

Is it named like this because of contract name ?
Since now it is not just authz example but kind of NFT auction lets rename it
___
*[`integration-tests/modules/wasm_test.go` line 778 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-Ni_9Ib98kllidded29N:-Ni_9Ib98kllidded29O:b50e981) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2ad14783d976e50ef47300175c11555a3095c54/integration-tests/modules/wasm_test.go#L778)):*
> ```Go
> 	// Make the offer of the NFT for the AssetFT
> 
> 	nftOfferPayload, err := json.Marshal(map[authzMethod]authzNftOfferRequest{
> ```


I can see that we mix NFT & Nft in names

e.g 
`nftOfferPayload, err := json.Marshal(map[authzMethod]authzNftOfferRequest` 

and 
`requireT.ElementsMatch([]assetnfttypes.NFTIdentifier`

I think we should stick to a single convention everywhere

@miladz68 @wojtek-coreum @dzmitryhil WDYT ? 
I prefer NFT but not critical for me

@keyleu  pls don't fix other parts in this PR only this PR related things

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: 12 of 16 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/contracts/modules/authz/src/msg.rs` line 6 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-Ni_8M045f7UXKA3ZslF:-Ni_L17NCW8iQGwv06_I:b-x5yqqo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2ad14783d976e50ef47300175c11555a3095c54/integration-tests/contracts/modules/authz/src/msg.rs#L6)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

No, this has nothing to do with NFT, it's for testing the Authz + BankSend, I updated the comment to avoid confusions.
</blockquote></details>

so within this contract we test both authz + nft case and also authz + bank send ?

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: 12 of 16 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/contracts/modules/authz/src/msg.rs` line 6 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-Ni_8M045f7UXKA3ZslF:-Ni_OfQM8JSiy36nAYxv:bsvhf3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2ad14783d976e50ef47300175c11555a3095c54/integration-tests/contracts/modules/authz/src/msg.rs#L6)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so within this contract we test both authz + nft case and also authz + bank send ?
</blockquote></details>

Correct. The Transfer{} Msg tests BankSend and The Nft Messages test the NFT. 
If the correct authorization was sent before, they both work.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: 12 of 16 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/contracts/modules/authz/src/msg.rs` line 6 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-Ni_8M045f7UXKA3ZslF:-Ni_OuNV0s4g3Qu4IeX5:b-4kbcbm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2ad14783d976e50ef47300175c11555a3095c54/integration-tests/contracts/modules/authz/src/msg.rs#L6)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

Correct. The Transfer{} Msg tests BankSend and The Nft Messages test the NFT. 
If the correct authorization was sent before, they both work.
</blockquote></details>

My idea is since these contracts are fully tested with integration tests, we are sure that they are always correct and developers can trust these contracts and get inspired by them for their developments. I think both BankTransfer and Custom Stargate messages (like AssetNFT) covers the functionality of Authz + Smart Contracts

**Review by ysv — DISMISSED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 10 of 16 files at r1, 2 of 4 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @keyleu, and @miladz68)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-NiKQV_p66Cwy6R3VL-d:-NicWpwsBL4J2hXOWL1Q:b-3vw9uw) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

In general I would agree with Wojtek & my initial idea was to put it into tutorials

But after reviewing PR, I'm ok to keep it here. The main benefits are:
1. we have real usage for authz with custom message so we test 2 things in a single contract (authz.Exec + custom authz permission)
2. the code here is tested & has full logic (both permission grant & contract call) which is opposite to the idea of putting it into tutorial repo which doesn't have testing framework & would cover 1 part

So I don't have very strong opinion but a bit in favour of keeping it here
</blockquote></details>

Unblocked this, but I think that we should split this contract into three different ones

___
___
*[`integration-tests/contracts/modules/authz/src/contract.rs` line 98 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-NicXIL7E3IY6ZCrbpGi:-NicXIL7E3IY6ZCrbpGj:b-ajiuaa) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a13a5d2872edb545e59fddf6e66714ac2c8aaa22/integration-tests/contracts/modules/authz/src/contract.rs#L98)):*
> ```XML
> }
> 
> // The contract must have been granted authorization to send the NFT before execution of it will fail.
> ```

of -> or
___
*[`integration-tests/modules/wasm_test.go` line 778 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-Ni_9Ib98kllidded29N:-NicWawX6esIhPBLqUfm:b-bxg3in) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2ad14783d976e50ef47300175c11555a3095c54/integration-tests/modules/wasm_test.go#L778)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I can see that we mix NFT & Nft in names

e.g 
`nftOfferPayload, err := json.Marshal(map[authzMethod]authzNftOfferRequest` 

and 
`requireT.ElementsMatch([]assetnfttypes.NFTIdentifier`

I think we should stick to a single convention everywhere

@miladz68 @wojtek-coreum @dzmitryhil WDYT ? 
I prefer NFT but not critical for me

@keyleu  pls don't fix other parts in this PR only this PR related things
</blockquote></details>

Voting for "NFT" too

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/contracts/modules/authz/src/contract.rs` line 98 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-NicXIL7E3IY6ZCrbpGi:-Nic_wdUC-ArY381WE2Q:b-7ql1td) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a13a5d2872edb545e59fddf6e66714ac2c8aaa22/integration-tests/contracts/modules/authz/src/contract.rs#L98)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

of -> or
</blockquote></details>

fixed

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 778 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-Ni_9Ib98kllidded29N:-Nicow7W7J251dR2cQyf:bolscqj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2ad14783d976e50ef47300175c11555a3095c54/integration-tests/modules/wasm_test.go#L778)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Voting for "NFT" too
</blockquote></details>

"NFT" is better.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-NiKQV_p66Cwy6R3VL-d:-Nid_IHe8YEzgisu-vH-:b-tt5dr4) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Unblocked this, but I think that we should split this contract into three different ones
</blockquote></details>

With this i agree !

Just I see 2 parts what about 3rd ?

1- bank send
2- NFT offer
3- ?

___
___
*[`integration-tests/modules/wasm_test.go` line 778 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-Ni_9Ib98kllidded29N:-Nid_SRb3nzytxX7XiLU:b-b7gqlh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2ad14783d976e50ef47300175c11555a3095c54/integration-tests/modules/wasm_test.go#L778)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

"NFT" is better.
</blockquote></details>

@keyleu pls fix related to your PR parts

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-NiKQV_p66Cwy6R3VL-d:-Nidfry49RP7hVF6D2eJ:b9m93jx) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

With this i agree !

Just I see 2 parts what about 3rd ?

1- bank send
2- NFT offer
3- ?
</blockquote></details>

3. Stargate

___

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 778 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/701#-Ni_9Ib98kllidded29N:-Nidgoel-OlR73k0XCkY:bb7f2mf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e2ad14783d976e50ef47300175c11555a3095c54/integration-tests/modules/wasm_test.go#L778)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

@keyleu pls fix related to your PR parts
</blockquote></details>

done

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 4 files at r5, 1 of 2 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68)

**Review by keyleu — COMMENTED** [review]
> Dismissed @miladz68 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/701)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
