### PR TITLE
Handle send commisson rate in extension

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description
Handle send commisson rate in extension.
It ignores commission rate if the send amount is 109. Else, it will send half of the commission rate to admin if there is one and keeps the rest

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/843)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/843)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_extension_test.go` line 1655 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/843#-Ny4_lRY8_DRKjZwbAPP:-Ny4_lRZ1l9ZHYOpJ-zq:b-68i68s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5fb454f5f717081445def7f52f5ab38c7e1b83f1/integration-tests/modules/assetft_extension_test.go#L1655)):*
> ```Go
> 	)
> 	requireT.NoError(err)
> 	// assert that we don't receive events with empty amounts
> ```

this is not the correct way to assert events.
___
*[`integration-tests/modules/assetft_extension_test.go` line 1706 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/843#-Ny4aGtqDmewDqRVkjsl:-Ny4aGtqDmewDqRVkjsm:be04jyl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5fb454f5f717081445def7f52f5ab38c7e1b83f1/integration-tests/modules/assetft_extension_test.go#L1706)):*
> ```Go
> 	})
> 
> 	// send from recipient2 to admin (send commission rate must not apply)
> ```

why should it not apply ?  I see no condition on the smart contract, then i guess it should apply.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/843)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_extension_test.go` line 1655 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/843#-Ny4_lRY8_DRKjZwbAPP:-Ny4iQuJ2fIXQBWRVHAX:b-1phi4j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5fb454f5f717081445def7f52f5ab38c7e1b83f1/integration-tests/modules/assetft_extension_test.go#L1655)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this is not the correct way to assert events.
</blockquote></details>

This is and exact copy of what @dzmitryhil did [here](https://github.com/CoreumFoundation/coreum/commit/b72751e1#diff-0c795fb178a142678ba18e8cfa240b37474ec586a39ace71dbbb611ba83e4074R1102). I don't know the reason behind it
___
*[`integration-tests/modules/assetft_extension_test.go` line 1706 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/843#-Ny4aGtqDmewDqRVkjsl:-Ny4j0iX2XK7jg_jFgf6:b3v7d51) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5fb454f5f717081445def7f52f5ab38c7e1b83f1/integration-tests/modules/assetft_extension_test.go#L1706)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

why should it not apply ?  I see no condition on the smart contract, then i guess it should apply.
</blockquote></details>

Done. I just forgot to update the comment

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/843)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/843)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/843)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/843#-Ny5CvcY8FDsnFF-FjyV:-Ny5CvcY8FDsnFF-FjyW:b-o6kzg8) (no related file):*
The same about the usage if the constants in the assertions, the rest if good. 

___
___
*[`integration-tests/modules/assetft_extension_test.go` line 1655 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/843#-Ny4_lRY8_DRKjZwbAPP:-Ny5C7lS2I9NBdPjiBSJ:b-4jydu0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5fb454f5f717081445def7f52f5ab38c7e1b83f1/integration-tests/modules/assetft_extension_test.go#L1655)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

This is and exact copy of what @dzmitryhil did [here](https://github.com/CoreumFoundation/coreum/commit/b72751e1#diff-0c795fb178a142678ba18e8cfa240b37474ec586a39ace71dbbb611ba83e4074R1102). I don't know the reason behind it
</blockquote></details>

That was done to check that we don't send events with empty amounts.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/843)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/843#-Ny5CvcY8FDsnFF-FjyV:-Ny5E0c-A0FhDZNJJO2_:b-896fix) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The same about the usage if the constants in the assertions, the rest if good.
</blockquote></details>

Done.

___
___
*[`integration-tests/modules/assetft_extension_test.go` line 1655 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/843#-Ny4_lRY8_DRKjZwbAPP:-Ny5Dtvd5349BNGr6oMr:bjykbi2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5fb454f5f717081445def7f52f5ab38c7e1b83f1/integration-tests/modules/assetft_extension_test.go#L1655)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

That was done to check that we don't send events with empty amounts.
</blockquote></details>

@dzmitryhil Let me know if I need to keep it as is, or I need to change it somehow

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/843)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/843)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/843)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

___
*[`integration-tests/modules/assetft_extension_test.go` line 1655 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/843#-Ny4_lRY8_DRKjZwbAPP:-NyJoIRe9XMz_uGwXnTl:b-m12lhy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5fb454f5f717081445def7f52f5ab38c7e1b83f1/integration-tests/modules/assetft_extension_test.go#L1655)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

@dzmitryhil Let me know if I need to keep it as is, or I need to change it somehow
</blockquote></details>

discussed with Dima. These checks are used to make sure that events with zero amounts are not generated by the go code. we don't need to make these assertions for extensions.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/843)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`integration-tests/modules/assetft_extension_test.go` line 1655 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/843#-Ny4_lRY8_DRKjZwbAPP:-NyJqbhoBZZ507ByWsKY:b-5mw4c9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5fb454f5f717081445def7f52f5ab38c7e1b83f1/integration-tests/modules/assetft_extension_test.go#L1655)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

discussed with Dima. These checks are used to make sure that events with zero amounts are not generated by the go code. we don't need to make these assertions for extensions.
</blockquote></details>

Done. Removed

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/843)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/843)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/843)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/843)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
