### PR TITLE
added hardware requirements file

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/323)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/323)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`docs/chain/node/hardware-requirements.md` line 7 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmfQWh0-XeDJSGox2R:-NKmfQWh0-XeDJSGox2S:bjonim) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L7)):*
> ```Markdown
> If you are planning a to run a node against our mainnet, please observe the following points
> - use a dedicated bare-metal server, and do not use a VPS or a cloud computing instance.
> - only use SSD or NVMe hard drives
> ```

maybe add sth like "drives directly attached to the mainboard"
___
*[`docs/chain/node/hardware-requirements.md` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmflDPBzhg1NXhybXA:-NKmflDPBzhg1NXhybXB:bywvt7x) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L13)):*
> ```Markdown
> |Validator  |8      |64GB   |500GB-2TB  | 100+ MBPS           |
> |Full       |4      |32GB   |2TB        | 100+ MBPS           |
> |Default    |4      |32GB   |1TB        | 100+ MBPS            |
> ```

What does "Default" mean?
___
*[`docs/chain/node/hardware-requirements.md` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmffl03_SZs4SlrxVs:-NKmffl18kxaZWHAdizr:b-isn1t6) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L15)):*
> ```Markdown
> |Default    |4      |32GB   |1TB        | 100+ MBPS            |
> 
> ### Testnet
> ```

Where the spec for testnet and devnet came from?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/323)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`docs/chain/node/hardware-requirements.md` line 2 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmqk9sALZrfDl7Icva:-NKmqk9sALZrfDl7Icvb:bzxqrm) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L2)):*
> ```Markdown
> # System Requirements
> Running a node against the mainnet can be a resource intensive process. In the table below you may find recommended system requirements for different networks.
> ```

Do we need the `mainnet` mentioning here?
___
*[`docs/chain/node/hardware-requirements.md` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmffl03_SZs4SlrxVs:-NKmqVT7EUseG2lZovdb:biheki3) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Where the spec for testnet and devnet came from?
</blockquote></details>

Why the storage is so different from the mainnet, IMO 1TB should be here as min. And ` Internet Connection` same as mainnet.
___
*[`docs/chain/node/hardware-requirements.md` line 22 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmqLyo5GWl2GU03r6D:-NKmqLyo5GWl2GU03r6E:b-59kznf) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L22)):*
> ```Markdown
> |Default    |2      |16GB   |500GB      |  10+  MBPS           |
> 
> ### Devnet
> ```

IMO we don't need to provide the devnet config.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/323)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`docs/chain/node/hardware-requirements.md` line 2 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmqk9sALZrfDl7Icva:-NKmwj2N1-3Xt6CfQOIP:ba3dfob) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L2)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do we need the `mainnet` mentioning here?
</blockquote></details>

Removed
___
*[`docs/chain/node/hardware-requirements.md` line 7 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmfQWh0-XeDJSGox2R:-NKmwlDw6Yf26V-hxwRU:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L7)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

maybe add sth like "drives directly attached to the mainboard"
</blockquote></details>

Done.
___
*[`docs/chain/node/hardware-requirements.md` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmflDPBzhg1NXhybXA:-NKmh-CV7m08PjXK6v3a:by9wuyi) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What does "Default" mean?
</blockquote></details>

I honestly don't know, I took it from cosmos hub. I guess it means for other nodes like seed or fast sync node
___
*[`docs/chain/node/hardware-requirements.md` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmffl03_SZs4SlrxVs:-NKmgAxXDEYeOh_hjMY7:blaktu2) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why the storage is so different from the mainnet, IMO 1TB should be here as min. And ` Internet Connection` same as mainnet.
</blockquote></details>

these are just guesses, we will need to adjust later after we observe the behavior. 
___
*[`docs/chain/node/hardware-requirements.md` line 22 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmqLyo5GWl2GU03r6D:-NKmw7G81Ihw9l_x9tUP:b-9vdx5e) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L22)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO we don't need to provide the devnet config.
</blockquote></details>

I kinda agree, but I have seen Artem ask about this config so I figured this is something he gets asked about, so I put it here.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/323)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`docs/chain/node/hardware-requirements.md` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmffl03_SZs4SlrxVs:-NKmxDIz27XP-9brfC4c:bwvhvjb) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L15)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

these are just guesses, we will need to adjust later after we observe the behavior. 
</blockquote></details>

@dzmitryhil, but do you think the testnet will be utilized at the same level as the mainnet ?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/323)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`docs/chain/node/hardware-requirements.md` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmffl03_SZs4SlrxVs:-NKqQZnqAKKqGm2SlVHg:bjkd8w9) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L15)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@dzmitryhil, but do you think the testnet will be utilized at the same level as the mainnet ?
</blockquote></details>

Not the same. But 50% is close for the reality as for me. 
___
*[`docs/chain/node/hardware-requirements.md` line 22 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmqLyo5GWl2GU03r6D:-NKqQgddBQ7-Itu7qQyA:b-7p6nr6) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L22)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I kinda agree, but I have seen Artem ask about this config so I figured this is something he gets asked about, so I put it here. 
</blockquote></details>

But he needs it untils we have the testnet

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/323)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`docs/chain/node/hardware-requirements.md` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmffl03_SZs4SlrxVs:-NKrR4rq77ByV3erE-fL:b-a9ji0c) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not the same. But 50% is close for the reality as for me. 
</blockquote></details>

So if these are only guesses maybe we should not publish it until we have good understanding?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/323)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/323)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`docs/chain/node/hardware-requirements.md` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmffl03_SZs4SlrxVs:-NKwMuax1uR1D23-PRAJ:by9xyp1) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

So if these are only guesses maybe we should not publish it until we have good understanding?
</blockquote></details>

Discussed in the call to keep these values. 
___
*[`docs/chain/node/hardware-requirements.md` line 22 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/323#-NKmqLyo5GWl2GU03r6D:-NKwMxu4621-LIhCx_om:bftqmcx) ([raw file](https://github.com/coreumfoundation/coreum/blob/63d700fd71e2c270e3b15e5a03397e994d82e7d6/docs/chain/node/hardware-requirements.md#L22)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But he needs it untils we have the testnet
</blockquote></details>

Discussed in the call to keep it.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/323)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Pull request merged**
