### PR TITLE
Implement strict symbol validation

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/keeper/keeper_test.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGarUoGDn0_Av0ba4dQ:-NGarLjJ5VYQTrM_XxmN:byddlc4) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/keeper/keeper_test.go#L36)):*
> ```Go
> 	ctx := testApp.BaseApp.NewContext(false, tmproto.Header{})
> 	assetKeeper := testApp.AssetKeeper
> 	symbol := "Coreum"
> ```

what about adding "coreum" to the list of forbidden symbols?
___
*[`x/asset/types/ft.go` line 31 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGar0M4-7iAROxUCFHH:-NGar0M4-7iAROxUCFHI:bd4egdj) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/types/ft.go#L31)):*
> ```Go
> 
> // BuildFungibleTokenDenom builds the denom string from the symbol and issuer address.
> func BuildFungibleTokenDenom(symbol string, issuer sdk.AccAddress) string {
> ```

What about merging this and next function into one? They both are used in the same context.
___
*[`x/asset/types/ft.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGaqYNG-uAbdbOeKNK2:-NGaqYNG-uAbdbOeKNK3:b-slrlpj) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/types/ft.go#L38)):*
> ```Go
> func ValidateSymbol(symbol string) error {
> 	symbol = strings.ToLower(symbol)
> 	if symbol == "core" || symbol == "ucore" {
> ```

I would say this should be checked per network, restricting the symbol on devnet, testnet or mainnet accordingly
___
*[`x/asset/types/ft_test.go` line 18 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGar94T3lBzuPIWTda8:-NGar94T3lBzuPIWTda9:b-65t1i4) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/types/ft_test.go#L18)):*
> ```Go
> 
> 	denom := types.BuildFungibleTokenDenom(symbol, addr)
> 	require.Equal(t, "core-devcore172rc5sz2uclpsy3vvx3y79ah5dk450z5ruq2r5", denom)
> ```

this actually uses forbidden symbol :)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/issue.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGb-Agy8OUKXvraiLTJ:-NGb-Agy8OUKXvraiLTK:bqed25l) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/keeper/issue.go#L13)):*
> ```Go
> // IssueFungibleToken issues new fungible token and returns it's denom.
> func (k Keeper) IssueFungibleToken(ctx sdk.Context, settings types.IssueFungibleTokenSettings) (string, error) {
> 	if err := types.ValidateSymbol(settings.Symbol); err != nil {
> ```

Based on the current design that call should be in the basic validation and not here. The idea is the basic vacation will be first time triggered by the client before the tx submission.
___
*[`x/asset/keeper/keeper_test.go` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGb0_zSDIPsIWO1BHEI:-NGb0_zSDIPsIWO1BHEJ:bl3hk9h) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/keeper/keeper_test.go#L52)):*
> ```Go
> }
> 
> func TestKeeper_ValidateSymbol(t *testing.T) {
> ```

I would attach that test to the function directly, not to the Issue.
___
*[`x/asset/types/ft.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGaqYNG-uAbdbOeKNK2:-NGazp6y8j5KNKP-pRAv:b-8ayu6x) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/types/ft.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would say this should be checked per network, restricting the symbol on devnet, testnet or mainnet accordingly
</blockquote></details>

Agree

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/issue.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGb-Agy8OUKXvraiLTJ:-NGuh7b40T4SvVA-RPVW:bldn4ul) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/keeper/issue.go#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Based on the current design that call should be in the basic validation and not here. The idea is the basic vacation will be first time triggered by the client before the tx submission.
</blockquote></details>

that is an excellent point. added this check to ValidateBasics
___
*[`x/asset/keeper/keeper_test.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGarUoGDn0_Av0ba4dQ:-NGuafzz4bJNrcg9dSwD:bzcctwq) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/keeper/keeper_test.go#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what about adding "coreum" to the list of forbidden symbols?
</blockquote></details>

It was decided on the call not to do this. 
___
*[`x/asset/keeper/keeper_test.go` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGb0_zSDIPsIWO1BHEI:-NGubAnG4fjMaH-fE372:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/keeper/keeper_test.go#L52)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would attach that test to the function directly, not to the Issue.
</blockquote></details>

Done
___
*[`x/asset/types/ft.go` line 31 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGar0M4-7iAROxUCFHH:-NGub_dN9Ze2OYeozJUd:bd6th3h) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/types/ft.go#L31)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What about merging this and next function into one? They both are used in the same context.
</blockquote></details>

I considered it, but there are places in tests that we use build fungible token and I rather not to deal with error there.  Also ValidateSymbol is used in validate basics.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/issue.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGb-Agy8OUKXvraiLTJ:-NGvAMu8CK5W-51kd0la:bg09jw1) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/keeper/issue.go#L13)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

that is an excellent point. added this check to ValidateBasics
</blockquote></details>

You still have that check in the `func (k Keeper) IssueFungibleToken` you don't need it now.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: 4 of 20 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/issue.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGb-Agy8OUKXvraiLTJ:-NH3zd8I-w_KzzTk_FTs:b-3g4pj6) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/keeper/issue.go#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You still have that check in the `func (k Keeper) IssueFungibleToken` you don't need it now.
</blockquote></details>

I think this check must be here. If in future, some code calls the keeper directly, it must not go through. 
___
*[`x/asset/types/ft.go` line 38 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGaqYNG-uAbdbOeKNK2:-NH-ph7c1LqObpNlYLMf:bpib806) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/types/ft.go#L38)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree
</blockquote></details>

Implemented as discussed. 
___
*[`x/asset/types/ft_test.go` line 18 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGar94T3lBzuPIWTda8:-NH4QfVBAmZjGL2VqBwl:bt2vr1b) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/types/ft_test.go#L18)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this actually uses forbidden symbol :)
</blockquote></details>

Fixed.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: 3 of 22 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/issue.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGb-Agy8OUKXvraiLTJ:-NH4pZKJCjcKltvn-L2x:beo7ecg) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/keeper/issue.go#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I don't think so. All Keepers are designed with the expectation that data is correct, this on is the same. 
</blockquote></details>

you can see coin validation (includes denom validation) in most of bank keeper methods. 
___
*[`x/asset/types/ft.go` line 40 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NH4id-cCbwp5lP_bGrN:-NH4pl8i9Sq6mxCJcmCk:beskkya) ([raw file](https://github.com/coreumfoundation/coreum/blob/ab2728de8cfaa179b42bb19701c802ed6c8d5561/x/asset/types/ft.go#L40)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Don't you want to move that lit to the constants?
</blockquote></details>

we can make it a variable here, but not as part of the constant package

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: 3 of 22 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/issue.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGb-Agy8OUKXvraiLTJ:-NH4wSUV-Ss5xqeCydXV:bad3e61) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/keeper/issue.go#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Ok, so why we don't validate the coin as well here ? 
</blockquote></details>

well you wrote that code :D, do you want me to add that as well ?
___
*[`x/asset/types/ft.go` line 40 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NH4id-cCbwp5lP_bGrN:-NH4w_OuDVZC2-XpEpFS:b-60zems) ([raw file](https://github.com/coreumfoundation/coreum/blob/ab2728de8cfaa179b42bb19701c802ed6c8d5561/x/asset/types/ft.go#L40)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

I don't think this list is valuable or of concern to that package. it defined an used here to achieve a specific functionality.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: 3 of 22 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/issue.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGb-Agy8OUKXvraiLTJ:-NH4xJUW35ufU53emOtL:bm95g0d) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/keeper/issue.go#L13)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

well you wrote that code :D, do you want me to add that as well ?
</blockquote></details>

I meant that's check is unnecessary. It's fully enough to check it in the ValidateBasic.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: 3 of 22 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/issue.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGb-Agy8OUKXvraiLTJ:-NH8JSkK3ExaDHmX9d6A:bsrcjo9) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/keeper/issue.go#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I meant that's check is unnecessary. It's fully enough to check it in the ValidateBasic.
</blockquote></details>

I think it is a a stateless cheap check. If we remove that check and someone in future calls this keeper directly they will not remember to do this check before call

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: 3 of 22 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/issue.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGb-Agy8OUKXvraiLTJ:-NH9As061xbFqlSNOFhJ:b-tukisf) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/keeper/issue.go#L13)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think it is a a stateless cheap check. If we remove that check and someone in future calls this keeper directly they will not remember to do this check before call
</blockquote></details>

The redundant check might lead to the same defendant check everywhere, that's why I'm still against it.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 18 of 19 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 18 of 19 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`x/asset/keeper/issue.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGb-Agy8OUKXvraiLTJ:-NH9f-ql3X0FHI5yE61o:b8pkav7) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/keeper/issue.go#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The redundant check might lead to the same defendant check everywhere, that's why I'm still against it. 
</blockquote></details>

@ysv @wojtek-coreum 
care to comment ?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

___
*[`x/asset/keeper/issue.go` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NGb-Agy8OUKXvraiLTJ:-NH9fxuN6DsjxNUMqTcw:b-ay8ixu) ([raw file](https://github.com/coreumfoundation/coreum/blob/1ad46fa13e2245168456043037bfb700933928bd/x/asset/keeper/issue.go#L13)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@ysv @wojtek-coreum 
care to comment ?
</blockquote></details>

I don't have strong opinion on this but since it is "free" check in terms of performance I do not mind to keep it here. I sort of agree with case of using keeper directly

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68)

___
*[`x/bank/keeper/benchmark_test.go` line 0 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NHOG8DiCy-BPQiSq3BZ:-NHOG8DiCy-BPQiSq3B_:b-r26xqo) ([raw file](https://github.com/coreumfoundation/coreum/blob/a0de35fabfa5c32a5691cde6d91b917277e762db/x/bank/keeper/benchmark_test.go#L0)):*
Why is it removed? I think it's a valuable piece of code

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

___
*[`x/bank/keeper/benchmark_test.go` line  at r5](https://reviewable.io/reviews/coreumfoundation/coreum/252#-NHOG8DiCy-BPQiSq3BZ:-NHOGg_BD-TzYHeVtQR3:b-6gpyb6) ([raw file](https://github.com/coreumfoundation/coreum/blob/a0de35fabfa5c32a5691cde6d91b917277e762db/x/bank/keeper/benchmark_test.go#L)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why is it removed? I think it's a valuable piece of code
</blockquote></details>

I don't know, I just merge from master :thinking:

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/252)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
