### PR TITLE
Separated build step for tests in CI

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/788)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
What is the difference between the bridge env and coreum, if the bridge build takes 1min, but coreum 3min?

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/788#-:-Nrt5KL_1Mc_DYt9PHZL:bvln0jc)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by miladz68 — COMMENTED** [review]
I don't know the details of the bridge env, but I don't think they are comparable. we do much more for coreum
- here we build the coreum binary inside docker (takes 1.5 mins) . 
- we create multiple images (osmosis, cosmos, relayers, and more) (about 1 minute)
- we download multiple binaries (4 different cored versions, osmosis, hermes, cosmos, and more)
- we intentionally re-build coreum-builder and znet every time (about 1 min). 

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/788#-:-NrtKr5E7lLRnYXE9xQb:b-c2kyf0)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/788)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/788#-Nrtd1eaBbFoB3JLEx_6:-Nrtd1eaBbFoB3JLEx_7:b-lq1jri) (no related file):*
Are we sure this PR resolves the issue we have ?
Shall we discuss it after call ?

___
___
*[`.github/workflows/ci.yml` line 80 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/788#-NrtcFbEBzdSt_bOqszo:-NrtcFbEBzdSt_bOqszp:bqdy74l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1c121cada1ef461b0812c878cbf3f4c9d146ebab/.github/workflows/ci.yml#L80)):*
> ```YAML
>             codecov: false
>           - ci_step: "integration tests faucet"
>             build: |
> ```

*I might be wrong here so don't take it for granted*

I think that ideally all our build commands should be exactly same to make sure we don't cache the fastest one. I think it is the easiest way to make it work correctly by design.

If I understand correctly this faucet build step will finish before all other and it is the one which will be cached.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/788)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/788#-Nrtd1eaBbFoB3JLEx_6:-NrthxS6-jxu7uv71V6c:b-xdsr7o) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Are we sure this PR resolves the issue we have ?
Shall we discuss it after call ?
</blockquote></details>

we don't have an issue per se. As discussed in the call, we meant to separate the build step to observe how long it takes and then decide what to do. this PR separates the build step and I will argue (later in the call :joy:) that there is not much to be done for the build step, unless we change our build in crust significantly. 

___
___
*[`.github/workflows/ci.yml` line 80 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/788#-NrtcFbEBzdSt_bOqszo:-NrtierP1W0pABLunyOy:b3kuxi0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1c121cada1ef461b0812c878cbf3f4c9d146ebab/.github/workflows/ci.yml#L80)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

*I might be wrong here so don't take it for granted*

I think that ideally all our build commands should be exactly same to make sure we don't cache the fastest one. I think it is the easiest way to make it work correctly by design.

If I understand correctly this faucet build step will finish before all other and it is the one which will be cached.
</blockquote></details>

Let's discuss in a call, it will be much faster.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/788)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`.github/workflows/ci.yml` line 80 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/788#-NrtcFbEBzdSt_bOqszo:-NruRRwB51B74zgz0cZE:b-j5win7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1c121cada1ef461b0812c878cbf3f4c9d146ebab/.github/workflows/ci.yml#L80)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Let's discuss in a call, it will be much faster.
</blockquote></details>

discussed on call and decided to try same build command in all steps
Keeping this issue opened

**Review by dzmitryhil — COMMENTED** [review]
Decided to check whether the same build for all commands improves the time.

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/788#-:-Ns7Igy_DRhMuPS8aE-u:b-pqvczz)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by ysv — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/788)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by miladz68 — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/788#-:-NsE-I2099tj9YgrOMyO:bb6un1j)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`.github/workflows/ci.yml` line 80 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/788#-NrtcFbEBzdSt_bOqszo:-NsE-GMq8T9JLqFZu6G5:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1c121cada1ef461b0812c878cbf3f4c9d146ebab/.github/workflows/ci.yml#L80)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

discussed on call and decided to try same build command in all steps
Keeping this issue opened
</blockquote></details>

Done.

**Review by ysv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/788)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/788)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`.github/workflows/ci.yml` line 166 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/788#-NsHABtC0mRf2ZUbg-Xa:-NsHABtC0mRf2ZUbg-Xb:bc1qkti) ([raw file](https://github.com/CoreumFoundation/coreum/blob/215fd9db7f6028180589e6e9aa89586202db506c/.github/workflows/ci.yml#L166)):*
> ```YAML
>           key: ${{ runner.os }}-cache-smart-contracts-${{ hashFiles('./coreum/**/*.rs') }}
>         if: ${{ matrix.wasm-cache }}
>       - name: Build step
> ```

You have now build step which you don't use and build inside the run

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/788)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 166 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/788#-NsHABtC0mRf2ZUbg-Xa:-NsHZ3biChFNcx0lemOV:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/215fd9db7f6028180589e6e9aa89586202db506c/.github/workflows/ci.yml#L166)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You have now build step which you don't use and build inside the run
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/788)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/788)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
