### PR TITLE
added RecommendedGasPrice endpoint

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/feemodel_test.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZ0omZeDaKradMmlipF:-NZ0omZeDaKradMmlipG:byjw9bw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0df749d887fdaa6e3c32e9e4b7c8d5bc349a78fc/integration-tests/modules/feemodel_test.go#L59)):*
> ```Go
> 	requireT.LessOrEqual(res.GetLow().Amount.MustFloat64(), model.CalculateMaxGasPrice().MustFloat64())
> 	requireT.GreaterOrEqual(res.GetMed().Amount.MustFloat64(), model.CalculateGasPriceWithMaxDiscount().MustFloat64())
> 	requireT.LessOrEqual(res.GetMed().Amount.MustFloat64(), model.CalculateMaxGasPrice().MustFloat64())
> ```

And also test that `low <= med <= high`
___
*[`x/feemodel/keeper/keeper.go` line 156 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZ0pdyy9UBcvh1YidY3:-NZ0pdyy9UBcvh1YidY4:b-nrs41r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0df749d887fdaa6e3c32e9e4b7c8d5bc349a78fc/x/feemodel/keeper/keeper.go#L156)):*
> ```Go
> 
> // EstimateFutureGasPrice returns the smallest and highest possible values ofr min gas price in future blocks.
> func (k Keeper) EstimateFutureGasPrice(ctx sdk.Context, after uint32) (sdk.DecCoin, sdk.DecCoin) {
> ```

Could you present some real values this function produces for blocks from +1 to +10?
I'm not sure if the output might be helpful because it might be like saying that future gas price might be somewhere in <gasPriceWithMaxDiscount, maxGas>
___
*[`x/feemodel/keeper/keeper.go` line 176 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZ0p9We1C8t-dh5bS0D:-NZ0p9We1C8t-dh5bS0E:bum5fu1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0df749d887fdaa6e3c32e9e4b7c8d5bc349a78fc/x/feemodel/keeper/keeper.go#L176)):*
> ```Go
> 	highMinGasPrice := minGasPrice
> 
> 	for i := 0; i < int(after); i++ {
> ```

`for i := uint32(0); i < after; i++ {`

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/keeper/keeper.go` line 156 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZ0pdyy9UBcvh1YidY3:-NZ15y0O9d2aKlt7Csbh:bhjvqf6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0df749d887fdaa6e3c32e9e4b7c8d5bc349a78fc/x/feemodel/keeper/keeper.go#L156)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you present some real values this function produces for blocks from +1 to +10?
I'm not sure if the output might be helpful because it might be like saying that future gas price might be somewhere in <gasPriceWithMaxDiscount, maxGas>
</blockquote></details>

look at the keeper_tests. those values are real values with small error margin.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/feemodel/keeper/keeper.go` line 176 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZ0p9We1C8t-dh5bS0D:-NZ1QbwY0dT7tGuCCgI7:b-ugh9x0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0df749d887fdaa6e3c32e9e4b7c8d5bc349a78fc/x/feemodel/keeper/keeper.go#L176)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`for i := uint32(0); i < after; i++ {`
</blockquote></details>

and also put a cap on `after`

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/feemodel_test.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZ0omZeDaKradMmlipF:-NZ5Ko-7BKHVqArUhP3b:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0df749d887fdaa6e3c32e9e4b7c8d5bc349a78fc/integration-tests/modules/feemodel_test.go#L59)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

And also test that `low <= med <= high`
</blockquote></details>

Done.
___
*[`x/feemodel/keeper/keeper.go` line 176 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZ0p9We1C8t-dh5bS0D:-NZ5MH4l8_5dWQFxF8Vv:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0df749d887fdaa6e3c32e9e4b7c8d5bc349a78fc/x/feemodel/keeper/keeper.go#L176)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

and also put a cap on `after`
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/feemodel/keeper/grpc.go` line 51 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZ5OQ785Inil2Xtzunq:-NZ5OQ785Inil2Xtzunr:b-5m1j3r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1444cb1a3fa4a2d3c3a28238897b1fb489c124cb/x/feemodel/keeper/grpc.go#L51)):*
> ```Go
> 
> 	if req.AfterBlocks > maxAfterBlocks {
> 		return nil, status.Errorf(codes.InvalidArgument, "after blocks must be lower than %d", maxAfterBlocks)
> ```

lower than or equal to

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/feemodel/keeper/grpc.go` line 45 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZ61ZgA9rvfcFzrXCqu:-NZ61ZgA9rvfcFzrXCqv:b-eq1jho) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1444cb1a3fa4a2d3c3a28238897b1fb489c124cb/x/feemodel/keeper/grpc.go#L45)):*
> ```Go
> // RecommendedGasPrice returns an estimation of gas in the future blocks.
> func (qs QueryService) RecommendedGasPrice(ctx context.Context, req *types.QueryRecommendedGasPriceRequest) (*types.QueryRecommendedGasPriceResponse, error) {
> 	const maxAfterBlocks uint32 = 50
> ```

We wanted to get the values form the params (ShortEMA) and you can move that check to the `EstimateFutureGasPrice`

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/keeper/grpc.go` line 45 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZ61ZgA9rvfcFzrXCqu:-NZUrnbXDo_C9NJ49RdR:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1444cb1a3fa4a2d3c3a28238897b1fb489c124cb/x/feemodel/keeper/grpc.go#L45)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We wanted to get the values form the params (ShortEMA) and you can move that check to the `EstimateFutureGasPrice`
</blockquote></details>

Done.
___
*[`x/feemodel/keeper/grpc.go` line 51 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZ5OQ785Inil2Xtzunq:-NZUrnqF0wdY2Egig1sH:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1444cb1a3fa4a2d3c3a28238897b1fb489c124cb/x/feemodel/keeper/grpc.go#L51)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

lower than or equal to
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: 8 of 10 files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/feemodel/keeper/keeper.go` line 163 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZ_qJuOBGPby6ss-a_0:-NZ_qJuOBGPby6ss-a_1:b-bsa8lo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2f7dde85269fded79b9a8e7d33579f56d4a9649d/x/feemodel/keeper/keeper.go#L163)):*
> ```Go
> 	}
> 
> 	// if no after value is provide shortEMABlockLength is taken as default value
> ```

is provided

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 4 of 5 files at r3, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 10 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/feemodel/keeper/keeper.go` line 156 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZafu0fAPV9-Ex_UvkE:-NZafu0fAPV9-Ex_UvkF:b-exc3bj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper.go#L156)):*
> ```Go
> }
> 
> // EstimateFutureGasPrice returns the smallest and highest possible values ofr min gas price in future blocks.
> ```

just a general question:
does edge values always lay on the latest block or they could be somewhere in the middle ?
___
*[`x/feemodel/keeper/keeper.go` line 157 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZag1LvDIG5qiqpIbE0:-NZag1LvDIG5qiqpIbE1:b-cn8j0o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper.go#L157)):*
> ```Go
> 
> // EstimateFutureGasPrice returns the smallest and highest possible values ofr min gas price in future blocks.
> func (k Keeper) EstimateFutureGasPrice(ctx sdk.Context, after uint32) (sdk.DecCoin, sdk.DecCoin, error) {
> ```

minor: I would rename to smth like `CalculateEdgeGasPriceAfterBlocks` `CalculateEdgeGasPriceAfterNBlocks`
___
*[`x/feemodel/keeper/keeper.go` line 179 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZaf8vJ6Gx3BaqMppA4:-NZaf8vK5u3LKKnE0zCd:b59j512) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper.go#L179)):*
> ```Go
> 
> 	model := types.NewModel(params.Model)
> 	minGasPrice := sdk.NewDecCoinFromDec(
> ```

IMO it is more reasonable to operate with sdk.Dec everywhere inside this func & return sdk.Dec from it 

Adding denom everywhere is extra & not really needed. Only actual number is important
___
*[`x/feemodel/keeper/keeper.go` line 188 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZagYrS7LdTyBP_yzAN:-NZagYrS7LdTyBP_yzAO:b787la3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper.go#L188)):*
> ```Go
> 
> 	for i := uint32(0); i < after; i++ {
> 		maxShortEMA = types.CalculateEMA(maxShortEMA, params.Model.MaxBlockGas,
> ```

I would store these 2 values in vars before loop for shorter lines:
```
minBlockGas := 0
maxBlockGas := params.Model.MaxBlockGas

```
___
*[`x/feemodel/keeper/keeper.go` line 198 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZaeQFf2crdQPOUwY6A:-NZaeQFf2crdQPOUwY6B:b8o9anp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper.go#L198)):*
> ```Go
> 		minLongEMA = types.CalculateEMA(minLongEMA, 0,
> 			params.Model.LongEmaBlockLength)
> 		minLoadMinGasPrice := sdk.NewDecCoinFromDec(minGasPrice.Denom, model.CalculateNextGasPrice(minShortEMA, minLongEMA))
> ```

you calculate possible gas price for 2 cases:
1. maxShortEMA, maxLongEMA
2. minShortEMA, minLongEMA

is it possible that edge value is achieved for (maxShortEMA, minLongEMA) or (minShortEMA, maxLongEMA) ?
___
*[`x/feemodel/keeper/keeper.go` line 201 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZafWIj79uhfSUrucPa:-NZafWIj79uhfSUrucPb:b-mtlhip) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper.go#L201)):*
> ```Go
> 
> 		if maxLoadMinGasPrice.IsGTE(highMinGasPrice) {
> 			highMinGasPrice = maxLoadMinGasPrice
> ```

once you refactor to use sdk.Dec here all these statements could be simplified
```
highMinGasPrice = sdk.MaxDec(highMinGasPrice, maxLoadMinGasPrice)
...
```
___
*[`x/feemodel/keeper/keeper_test.go` line 140 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZai2oK8hfexpNRTsp7:-NZai2oK8hfexpNRTsp8:b9man0j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper_test.go#L140)):*
> ```Go
> 		assertions  func(t *testing.T, low, high sdk.DecCoin)
> 	}{
> 		{
> ```

I would really love to see actual values you get in all these tests.
Because I want to understand how well this estimation work and if it is really usable

Not sure how to achieve this 
___
*[`x/feemodel/keeper/keeper_test.go` line 149 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZahXzZCpYWFCAZCj8W:-NZahXz_B63F4wKMgQQP:b-4nnm1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper_test.go#L149)):*
> ```Go
> 				model := types.NewModel(defParams.Model)
> 				assertT.EqualValues(low.Amount, model.CalculateGasPriceWithMaxDiscount(), "low amount is max discount")
> 				assertT.EqualValues(high.Amount, model.CalculateGasPriceWithMaxDiscount(), "high amount is max discount")
> ```

I didn't get this assertion
do you mean that both possible values for high and low will both be equal to `CalculateGasPriceWithMaxDiscount` ?

But if there is 0 txs then gas_price should be equal to initial. No ?
___
*[`x/feemodel/keeper/keeper_test.go` line 174 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZajkQtAefNTnhpez0s:-NZajkQu0cE2UTC14JFd:bb9qt7j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper_test.go#L174)):*
> ```Go
> 				assertT.EqualValues(low.Amount, model.CalculateGasPriceWithMaxDiscount())
> 
> 				assertT.Greater(high.Amount.MustFloat64(), model.CalculateGasPriceWithMaxDiscount().MustFloat64())
> ```

I really suggest to define our custom matcher here to decrease num of lines and make tests more clear

concept:

```
assertT.FloatInBetween(1.0, 0.0, 2.0)

assertT.FloatInBetween(high.Amount.MustFloat64(), model.CalculateGasPriceWithMaxDiscount().MustFloat64(), model.Params().InitialGasPrice.MustFloat64())

```

if could be used in integration tests would also be nice

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 10 unresolved discussions (waiting on @miladz68 and @silverspase)

___
*[`x/feemodel/keeper/keeper.go` line 156 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZdtr_a6QUOmgN_lGNT:-NZdtr_b28WSHeT0U_lA:bhzihjw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper.go#L156)):*
> ```Go
> }
> 
> // EstimateFutureGasPrice returns the smallest and highest possible values ofr min gas price in future blocks.
> ```

ofr -> of

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/feemodel/keeper/keeper.go` line 179 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZaf8vJ6Gx3BaqMppA4:-NZei8ai6JJS7bZOca78:b-9wiljl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper.go#L179)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

but MinGasPrice query returns the sdk.DecCoin and we should be uniform. 
</blockquote></details>

yes, returning sdk.DecCoin from query itself is reasonable.
But on keeper level I propose to operate with numbers only and then transform it to coin on Query level.

Or you can do all calculations using bare numbers and transform them into coins right before return statement
___
*[`x/feemodel/keeper/keeper.go` line 188 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZagYrS7LdTyBP_yzAN:-NZeiRRD-4RuaRyIHAjC:b5yxx4g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper.go#L188)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

minor:
`minBlockGas := int64(0)`

for better consistency
___
*[`x/feemodel/keeper/keeper.go` line 198 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZaeQFf2crdQPOUwY6A:-NZek4uB2erfbkx2W3cy:b9kxy9t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper.go#L198)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It is not possible if the value for `after` is less than shortEMABlockLength, because in this case, shortEMA and longEMA change  in the same direction. 
</blockquote></details>

I partially understand your point but need additional explanation on call

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 5 unresolved discussions (waiting on @silverspase and @ysv)

___
*[`x/feemodel/keeper/keeper.go` line 179 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZaf8vJ6Gx3BaqMppA4:-NZfLXwf4gsWuIi4Eq_z:b6hhfk1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper.go#L179)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes, returning sdk.DecCoin from query itself is reasonable.
But on keeper level I propose to operate with numbers only and then transform it to coin on Query level.

Or you can do all calculations using bare numbers and transform them into coins right before return statement
</blockquote></details>

but only the keeper has access to the coin denom. I actually tried what you want and quickly realized that I need to return DecCoin from keeper. 
___
*[`x/feemodel/keeper/keeper.go` line 198 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZaeQFf2crdQPOUwY6A:-NZkTAgH6VMiQ_o6i0u1:b2fe47c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper.go#L198)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I partially understand your point but need additional explanation on call
</blockquote></details>

discussed on the call

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/feemodel/keeper/keeper.go` line 179 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZaf8vJ6Gx3BaqMppA4:-NZkhCcV2qflOeas6-xp:b-hmde9q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper.go#L179)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

but only the keeper has access to the coin denom. I actually tried what you want and quickly realized that I need to return DecCoin from keeper. 
</blockquote></details>

not fixed
___
*[`x/feemodel/keeper/keeper.go` line 201 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZafWIj79uhfSUrucPa:-NZkhGlQ8cDT-tIdMMrA:b-hmde9q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b50351fcd96e4611a22393554c605e7e3106c8d2/x/feemodel/keeper/keeper.go#L201)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's dicuss above
</blockquote></details>

not fixed
___
*[`x/feemodel/keeper/keeper_test.go` line 174 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZkgu1J-YhfNxF0txKh:-NZkgu1J-YhfNxF0txKi:bbbwz0h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9700f59be98a387ac894c2dae11f3244d9d3fcdc/x/feemodel/keeper/keeper_test.go#L174)):*
> ```Go
> 				assertT.EqualValues(low.Amount, model.CalculateGasPriceWithMaxDiscount())
> 
> 				// the high value is about 0.032203830017345169
> ```

lets add this type of comment to all tests

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @silverspase)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @silverspase)

___
*[`x/feemodel/keeper/keeper_test.go` line 174 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZzQU0013nXFkPNQG-z:-NZzQU011Vwdor7JQifD:b2lnvul) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e191d1048497d8ec1b3abf3cb9e1171b7c2b770e/x/feemodel/keeper/keeper_test.go#L174)):*
> ```Go
> 			afterBlocks: 10,
> 			assertions: func(t *testing.T, low, high sdk.DecCoin) {
> 				// observed min: 0.03215
> ```

could you pls add one more case:
```
			shortEMA:    100_000,
			longEMA:     100_000,
			afterBlocks: 50,
```

I guess min will be the same while max will slightly increase
___
*[`x/feemodel/keeper/keeper_test.go` line 200 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZzR9WMBJYt1bYHUx1W:-NZzR9WN0111IvqExZP-:b-poay7v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e191d1048497d8ec1b3abf3cb9e1171b7c2b770e/x/feemodel/keeper/keeper_test.go#L200)):*
> ```Go
> 		{
> 			name:        "short ema is between long ema and escalation region. (10 block after)",
> 			shortEMA:    5_000_000,
> ```

what about case when shortEMA is a bit smaller than long ?
Smth like:
```
			shortEMA:    4_000_000,
			longEMA:     5_000_000,
			afterBlocks: 10, // or 50
```
I guess in this case max will be slightly more than `GasPriceWithMaxDiscount`
and min equal to `GasPriceWithMaxDiscount`

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @silverspase)

___
*[`x/feemodel/keeper/keeper_test.go` line 200 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZzR9WMBJYt1bYHUx1W:-NZzTLO4Agw57U1Mj7UD:b-zdalbl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e191d1048497d8ec1b3abf3cb9e1171b7c2b770e/x/feemodel/keeper/keeper_test.go#L200)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what about case when shortEMA is a bit smaller than long ?
Smth like:
```
			shortEMA:    4_000_000,
			longEMA:     5_000_000,
			afterBlocks: 10, // or 50
```
I guess in this case max will be slightly more than `GasPriceWithMaxDiscount`
and min equal to `GasPriceWithMaxDiscount`

</blockquote></details>

or play with numbers to reproduce this region


Screenshot 2023-07-10 at 13.03.54

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @ysv)

___
*[`x/feemodel/keeper/keeper_test.go` line 174 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZzQU0013nXFkPNQG-z:-N_34OwwBEf7-hUpnn1s:b-l603u7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e191d1048497d8ec1b3abf3cb9e1171b7c2b770e/x/feemodel/keeper/keeper_test.go#L174)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

could you pls add one more case:
```
			shortEMA:    100_000,
			longEMA:     100_000,
			afterBlocks: 50,
```

I guess min will be the same while max will slightly increase
</blockquote></details>

Done.
Your assumption is correct. 
___
*[`x/feemodel/keeper/keeper_test.go` line 200 at r8](https://reviewable.io/reviews/CoreumFoundation/coreum/543#-NZzR9WMBJYt1bYHUx1W:-N_356n_3tMQHOpAeqkA:bs7wun8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e191d1048497d8ec1b3abf3cb9e1171b7c2b770e/x/feemodel/keeper/keeper_test.go#L200)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

or play with numbers to reproduce this region


Screenshot 2023-07-10 at 13.03.54
</blockquote></details>

Done.+

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/543)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
