### PR TITLE
Redo network config

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/472)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/472)* status: 0 of 31 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTTfz8RD3Xjcp0eHCHS:-NTTfz8RD3Xjcp0eHCHT:b-4aria2) (no related file):*
First commit contains network redesign, second one adjusts everything else.
Personally I hate this PR, I did it just because I was requested. I still think that json can't be the source of ground true:
- address prefix is not there at all
- the way I retrieve denom from there is debatable
- all of this does not guarantee consistency (using the same denom and address prefix everywhere)

I highly recommend reintroducing go code as the source of ground true and treating genesis.json as the product of "compilation".

___

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/472)* status: 0 of 31 files reviewed, 9 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/init.go` line 106 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYXNW52xc-5mpfE2S3:-NTYXNW52xc-5mpfE2S4:b1f7hqd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/integration-tests/init.go#L106)):*
> ```Go
> 	grpcClient, err := grpc.Dial(coredAddress, grpc.WithInsecure())
> 	if err != nil {
> 		panic(err)
> ```

Add an error wrapping for all panics to get more detail for the errors. 
___
*[`integration-tests/init.go` line 116 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYYtkR4NAsn91ts0vX:-NTYYtkR4NAsn91ts0vY:bjeclyf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/integration-tests/init.go#L116)):*
> ```Go
> 	feemodelClient := feemodeltypes.NewQueryClient(clientCtx)
> 
> 	ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
> ```

You can take the timeout from `client.DefaultContextConfig()`
___
*[`integration-tests/network.go` line 18 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYYCO51s7EEUoaHSBe:-NTYYCO51s7EEUoaHSBf:b-a2ovgc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/integration-tests/network.go#L18)):*
> ```Go
> 
> // NewNetworkConfig returns the network config used by integration tests.
> func NewNetworkConfig(chainID constant.ChainID) (config.NetworkConfig, error) {
> ```

@ysv @miladz68 
That part still seems weird to me.  I remember about the idea of not having znet in the final binary but I would add the znet to the chainID as well, to simplify the use case, because don't see any issue to have it, if we have `devnet` there.
___
*[`integration-tests/modules/auth_test.go` line 33 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYZTSN7tV5KVAQJ8aB:-NTYZTSN7tV5KVAQJ8aC:b-ks9ui) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/integration-tests/modules/auth_test.go#L33)):*
> ```Go
> 	sender := chain.GenAccount()
> 
> 	maxBlockGas := chain.FeeModelParams.Model.MaxBlockGas
> ```

That part seems a bit unnatural compared with other parameters. 
I know that we don't change them,  but I would also query for them, and remove the `FeeModelParams` from the `chain` variable.
___
*[`pkg/config/network_test.go` line 143 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYVWCt1qVEx2cLH-rJ:-NTYVWCt1qVEx2cLH-rK:bibxgit) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/pkg/config/network_test.go#L143)):*
> ```Go
> 		{
> 			chainID:     constant.ChainIDMain,
> 			genesisHash: "5be3b3e0fee69842c4c73eb5f54eb64684420736473f0f5cef0ba6b81d44f253",
> ```

Prev hash was correct.
___
*[`pkg/config/provider.go` line 35 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYWIS-0wlQB5MvpJP1:-NTYWIS-0wlQB5MvpJP2:b-graset) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/pkg/config/provider.go#L35)):*
> ```Go
> 
> // DirectConfigProvider provides configuration generated from fields in this structure.
> type DirectConfigProvider struct {
> ```

Let's change the name. The `Direct` confuses. We can call it  `Customizable` or any other option.
___
*[`pkg/config/provider.go` line 200 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYVNPrAe3pfkBR9Z9f:-NTYVNPrAe3pfkBR9Z9g:b-powu2o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/pkg/config/provider.go#L200)):*
> ```Go
> // NewJSONConfigProvider creates new JSONConfigProvider.
> func NewJSONConfigProvider(content []byte) JSONConfigProvider {
> 	genesisDoc, err := tmtypes.GenesisDocFromJSON(content)
> ```

This is the mistake, the `JSONConfigProvider` shouldn't decode the JSON to  `tmtypes.GenesisDocFromJSON(content)` and back, because it introduces the attributes to the final JSON (default empty). 



_Code quote:_
```Go
err
```
___
*[`pkg/config/genesis/genesis.tmpl.json` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYUHbP-ePNE0hqujft:-NTYUHbP-ePNE0hqujfu:b-wd1tao) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/pkg/config/genesis/genesis.tmpl.json#L1)):*
> ```JSON
> {
> ```

Why do we need the `genesis.tmpl.json` ? We can generate from the Genesis JSON object.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/472)* status: 0 of 31 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`pkg/config/network_test.go` line 143 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYVWCt1qVEx2cLH-rJ:-NTYfUTbEG4-gcIC3hAy:b-7gqmfg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/pkg/config/network_test.go#L143)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Prev hash was correct.
</blockquote></details>

Nope. Testnet genesis contained an empty line at the end, while mainnet didn't. Now both are unified to have that empty line. Later on I will reenable crust to verify that json files contain new line.
___
*[`pkg/config/provider.go` line 200 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYVNPrAe3pfkBR9Z9f:-NTYgzt48cNN6ewM-OwT:b-erd8zo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/pkg/config/provider.go#L200)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This is the mistake, the `JSONConfigProvider` shouldn't decode the JSON to  `tmtypes.GenesisDocFromJSON(content)` and back, because it introduces the attributes to the final JSON (default empty). 
</blockquote></details>

What attributes? Unit test verifies that regenerated json has the same hash as the persistent file stored in `genesis` directory. So I'm very sure nothing extra is added.
___
*[`pkg/config/genesis/genesis.tmpl.json` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYUHbP-ePNE0hqujft:-NTYhGpE61jEzBX4fely:bz53oks) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/pkg/config/genesis/genesis.tmpl.json#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we need the `genesis.tmpl.json` ? We can generate from the Genesis JSON object. 
</blockquote></details>

Yea, that was a neat idea until I realized that it would require importing wasm package meaning that `pkg/config` would start depending on cgo again.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/472)* status: 0 of 31 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/init.go` line 106 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYXNW52xc-5mpfE2S3:-NTm8ureCWVxdhudvLJf:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/integration-tests/init.go#L106)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Add an error wrapping for all panics to get more detail for the errors. 
</blockquote></details>

Done.
___
*[`integration-tests/init.go` line 116 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYYtkR4NAsn91ts0vX:-NTm995S0xFQ6BjHLWfZ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/integration-tests/init.go#L116)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You can take the timeout from `client.DefaultContextConfig()`
</blockquote></details>

Done.
___
*[`pkg/config/provider.go` line 35 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYWIS-0wlQB5MvpJP1:-NTm9W4552-1pYb-r1kt:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/pkg/config/provider.go#L35)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's change the name. The `Direct` confuses. We can call it  `Customizable` or any other option.
</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/472)* status: 0 of 31 files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/provider.go` line 200 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYVNPrAe3pfkBR9Z9f:-NTn5SiP1Vurqt-umR1B:b-cwhynx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/pkg/config/provider.go#L200)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What attributes? Unit test verifies that regenerated json has the same hash as the persistent file stored in `genesis` directory. So I'm very sure nothing extra is added.
</blockquote></details>

If you add new modules to the repo, for example, because of the migration to v0.47, the `GenesisDocFromJSON` will be generated based on the new modules state, and if there are more params for the gov or staking (which is a real example), those params will be generated with default (empty) values, and that will change your genesis file. That's why we shouldn't decode from JSON to Genesis struct and back to JSON.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/472)* status: 0 of 31 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`integration-tests/network.go` line 18 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYYCO51s7EEUoaHSBe:-NTwn5hF8ydFPxxD1vki:b-9lhalx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/integration-tests/network.go#L18)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv @miladz68 
That part still seems weird to me.  I remember about the idea of not having znet in the final binary but I would add the znet to the chainID as well, to simplify the use case, because don't see any issue to have it, if we have `devnet` there.
</blockquote></details>

@dzmitryhil decided to resolve it on the call
___
*[`integration-tests/modules/auth_test.go` line 33 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYZTSN7tV5KVAQJ8aB:-NTwrTss24HaXp7-jf5W:b-ebi788) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/integration-tests/modules/auth_test.go#L33)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

That part seems a bit unnatural compared with other parameters. 
I know that we don't change them,  but I would also query for them, and remove the `FeeModelParams` from the `chain` variable.
</blockquote></details>

on call decided to query feemodel params directly and in chain initalizaton we also query it but store only initial gas price on proper place (inside faucet)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/472)* status: 0 of 31 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`integration-tests/modules/auth_test.go` line 33 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTYZTSN7tV5KVAQJ8aB:-NTxCIRuA2elJWu1-VsY:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0ab4fab008a150a6bb6fbed9bcde0c16e984c31f/integration-tests/modules/auth_test.go#L33)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

on call decided to query feemodel params directly and in chain initalizaton we also query it but store only initial gas price on proper place (inside faucet)
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/472)* status: 0 of 31 files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/472)* status: 0 of 31 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/chain.go` line 39 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTxM-GiBYayrUfyoSgr:-NTxM-GiBYayrUfyoSgs:b-dj208c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fcf2b368a17977bb5781331ddee9e123d40df855/integration-tests/chain.go#L39)):*
> ```Go
> 		NetworkConfig:          networkCfg,
> 		InitialGasPrice:        initialGasPrice,
> 		DeterministicGasConfig: deterministicgas.DefaultConfig(),
> ```

@ysv @wojtek-coreum @miladz68 
It would be nice in the future to return it as well, to let our consumers keep it up to date after the chain upgrade.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 19 of 31 files at r1, 1 of 2 files at r2, 1 of 6 files at r3, 5 of 5 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/472)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> Reviewed 19 of 31 files at r1, 1 of 2 files at r2, 1 of 6 files at r3, 5 of 5 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/472)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

___
*[`integration-tests/chain.go` line 39 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/472#-NTxM-GiBYayrUfyoSgr:-NU6LfOC4AY-1AS233Le:b-qlv2w1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/06b40a1d7f5260ac7960f6f16fe94f08c93d9e29/integration-tests/chain.go#L39)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv @wojtek-coreum @miladz68 
It would be nice in the future to return it as well, to let our consumers keep it up to date after the chain upgrade. 
</blockquote></details>

do you mean to add an API endpoint to return DeterministicGasConfig ?

**Pull request merged**
