### PR TITLE
Integrate wasm ante decorator

### PR DESCRIPTION
**Pull request by dzmitryhil**
Integrate the Integrate WASM CountTXDecorator into the app ante handler.

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/151)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/151)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`x/auth/ante/ante.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/151#-NAmvgl68Tk_4ZTr6yxx:-NAmvgl68Tk_4ZTr6yxy:b9ikqn0) ([raw file](https://github.com/coreumfoundation/coreum/blob/c4b918c3dd1311119f1cf2f70475b9583209f75b/x/auth/ante/ante.go#L28)):*
> ```Go
> 	SigGasConsumer        func(meter sdk.GasMeter, sig signing.SignatureV2, params types.Params) error
> 	GasRequirements       DeterministicGasRequirements
> 	WasmConfig            *wasmTypes.WasmConfig
> ```

`WasmConfig` is not used anywhere

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/151)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/auth/ante/ante.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/151#-NAmvgl68Tk_4ZTr6yxx:-NAneRxf94hcncSh72-R:b-knovx9) ([raw file](https://github.com/coreumfoundation/coreum/blob/c4b918c3dd1311119f1cf2f70475b9583209f75b/x/auth/ante/ante.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`WasmConfig` is not used anywhere
</blockquote></details>

Agree. Removed.



_Code quote:_
```Go
WasmConfig            *wasmTypes.WasmConfig
```

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/151)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/151)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Pull request merged**
