### PR TITLE
validate token metadata before registering on the bank module

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/379)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/379)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 442 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/379#-NNkq76FEVR0K4lE7HIz:-NNkq76FEVR0K4lE7HJ-:bxpejy5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f9383d04fd4c50df284f0f29707358925b3662f2/x/asset/ft/keeper/keeper.go#L442)):*
> ```Go
> 		DenomUnits: []*banktypes.DenomUnit{
> 			{
> 				Denom:    denom,
> ```

please add a comment explaining why denom must go first
___
*[`x/asset/ft/keeper/keeper_test.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/379#-NNkqgK57xVVgK2SdFjX:-NNkqgK57xVVgK2SdFjY:b-2whsqi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f9383d04fd4c50df284f0f29707358925b3662f2/x/asset/ft/keeper/keeper_test.go#L124)):*
> ```Go
> }
> 
> func TestKeeper_IssueEqualDisplayAndBaseDenom(t *testing.T) {
> ```

could you please explain what this test checks?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/379)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 442 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/379#-NNkq76FEVR0K4lE7HIz:-NNpIT8n5vy5RbEIdHoC:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f9383d04fd4c50df284f0f29707358925b3662f2/x/asset/ft/keeper/keeper.go#L442)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

please add a comment explaining why denom must go first
</blockquote></details>

Done
___
*[`x/asset/ft/keeper/keeper_test.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/379#-NNkqgK57xVVgK2SdFjX:-NNpGwO7Co9sQt0l_ad4:b-36ac48) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f9383d04fd4c50df284f0f29707358925b3662f2/x/asset/ft/keeper/keeper_test.go#L124)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

could you please explain what this test checks?
</blockquote></details>

If base  denom and display denom are the same, then cosmos sdk will fail when importing genesis. this test checks that if such condition is present , we catch it, and the tx fails.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/379)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/keeper/keeper_test.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/379#-NNkqgK57xVVgK2SdFjX:-NNpJGWkBvjTyPvADu_o:bmtpwnz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f9383d04fd4c50df284f0f29707358925b3662f2/x/asset/ft/keeper/keeper_test.go#L124)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

If base  denom and display denom are the same, then cosmos sdk will fail when importing genesis. this test checks that if such condition is present , we catch it, and the tx fails. 
</blockquote></details>

But I see that `Symbol` and `Subunit` are set to different values. It seems to me that `Symbol` shoudl not be set to `types.BuildDenom(subunit, addr)` but to `subunit`, no?
Please add a comment explaining this in the appropriate place in the code (keeper?)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/379)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper_test.go` line 124 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/379#-NNkqgK57xVVgK2SdFjX:-NNpTxkdDCFfOqXZr3ML:b-twxvk0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f9383d04fd4c50df284f0f29707358925b3662f2/x/asset/ft/keeper/keeper_test.go#L124)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But I see that `Symbol` and `Subunit` are set to different values. It seems to me that `Symbol` shoudl not be set to `types.BuildDenom(subunit, addr)` but to `subunit`, no?
Please add a comment explaining this in the appropriate place in the code (keeper?)
</blockquote></details>

subunit is not a denom, subunit is used to create the base denom by adding issuer to it.

**Review by wojtek-coreum — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/379)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/379)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/379)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
