### PR TITLE
Emit deterministic gas event

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

We ant to track real gas consumption by deterministic messages. We decided to emit an event describing deterministic behaviour.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/745)

### CODE REVIEW

**Review by miladz68 — DISMISSED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/745)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/745)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

___
*[`x/deterministicgas/types/gas.go` line 152 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/745#-NlSpNd24RbEhQ3gGJmT:-NlSpNd24RbEhQ3gGJmU:bassu1o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b6f44017f4ba6e1f3eb482042ada73cf22876b8e/x/deterministicgas/types/gas.go#L152)):*
> ```Go
> 	}
> 
> 	err := oldCtx.EventManager().EmitTypedEvent(&EventGas{
> ```

I'm not sure that this is the best place to emit this event. 
The idea & name of the func is to report Metric but this code is not related to metric
___
*[`x/deterministicgas/types/gas.go` line 154 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/745#-NlSps4I5u6t0bqQ8Gix:-NlSps4I5u6t0bqQ8Giy:b-z28gzc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b6f44017f4ba6e1f3eb482042ada73cf22876b8e/x/deterministicgas/types/gas.go#L154)):*
> ```Go
> 	err := oldCtx.EventManager().EmitTypedEvent(&EventGas{
> 		MsgURL:           msgURL,
> 		RealGas:          realGas,
> ```

are we sure we want to expose this info ?
lets discuss with the team 
___
*[`x/deterministicgas/types/gas.go` line 158 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/745#-NlSpE6WAKrB1hfPK1Q3:-NlSpE6WAKrB1hfPK1Q4:brt05i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b6f44017f4ba6e1f3eb482042ada73cf22876b8e/x/deterministicgas/types/gas.go#L158)):*
> ```Go
> 	})
> 
> 	if err != nil {
> ```

nit: this check is not needed

```
func WithStack(err error) error {  
if err == nil {  
return nil  
}  
return &withStack{  
err,  
callers(),  
}  
}
```

but if u find it more obvious I'm ok

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/745)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 152 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/745#-NlSpNd24RbEhQ3gGJmT:-NlSr5PwCiaIeASY7dqv:b2nlxea) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b6f44017f4ba6e1f3eb482042ada73cf22876b8e/x/deterministicgas/types/gas.go#L152)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm not sure that this is the best place to emit this event. 
The idea & name of the func is to report Metric but this code is not related to metric
</blockquote></details>

let's rename the function then
___
*[`x/deterministicgas/types/gas.go` line 154 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/745#-NlSps4I5u6t0bqQ8Gix:-NlSr3y3CiREc5W8-uWU:b78km5l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b6f44017f4ba6e1f3eb482042ada73cf22876b8e/x/deterministicgas/types/gas.go#L154)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

are we sure we want to expose this info ?
lets discuss with the team
</blockquote></details>

why not?
___
*[`x/deterministicgas/types/gas.go` line 158 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/745#-NlSpE6WAKrB1hfPK1Q3:-NlSqupuDn3TPjyCy5hP:bqctp4q) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b6f44017f4ba6e1f3eb482042ada73cf22876b8e/x/deterministicgas/types/gas.go#L158)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: this check is not needed

```
func WithStack(err error) error {  
if err == nil {  
return nil  
}  
return &withStack{  
err,  
callers(),  
}  
}
```

but if u find it more obvious I'm ok
</blockquote></details>

I would do it as you propose, but last time someone (Dima?) commented that having this for nil error is counterintuitive

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/745)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 158 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/745#-NlSpE6WAKrB1hfPK1Q3:-NlTNSqP2Qh5A4ezX0Q2:bphyb7t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b6f44017f4ba6e1f3eb482042ada73cf22876b8e/x/deterministicgas/types/gas.go#L158)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would do it as you propose, but last time someone (Dima?) commented that having this for nil error is counterintuitive
</blockquote></details>

let's remove it

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/745)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 152 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/745#-NlTMG_m-eYISbFIxix_:-NlXFzy82LXSDB4PsRFO:bica28r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b6f44017f4ba6e1f3eb482042ada73cf22876b8e/x/deterministicgas/types/gas.go#L152)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

include index of the message
</blockquote></details>

I have no access to the index there

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/745)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/745)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
