### PR TITLE
Use Flags instead of Parameters & Tags and update crust/build

### PR DESCRIPTION
**Pull request by ysv**
# Description

This PR shows example of usage of Flags & Envs instead of Parameters & CGOEnabled & Tags etc.

Dependent on https://github.com/CoreumFoundation/crust/pull/362

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/783)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/783)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/783#-Nrnzw7QBn2v0K2jvvlX:-Nrnzw7QBn2v0K2jvvlY:b-m3fkuf) (no related file):*
Looks good, let's discuss it today. 

___

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/783)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/783)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`build/go.mod` line 5 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/783#-Nru9kkuAGINqn0fvXDw:-Nru9kkuAGINqn0fvXDx:bw260yp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9ac8359190177c2bdbb73a4adff0c7f0edc0031/build/go.mod#L5)):*
> ```XML
> go 1.21
> 
> replace github.com/CoreumFoundation/crust/build => ../../crust/build
> ```

I assume this is left over

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/783)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/783#-Nrnzw7QBn2v0K2jvvlX:-NsDOmPNConueDYE8lMa:bb6un1j) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Looks good, let's discuss it today.
</blockquote></details>

Done

___
___
*[`build/go.mod` line 5 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/783#-Nru9kkuAGINqn0fvXDw:-NsDOnfBCqFX3HKjiNNZ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d9ac8359190177c2bdbb73a4adff0c7f0edc0031/build/go.mod#L5)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I assume this is left over
</blockquote></details>

Done.

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/783)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/783)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/783)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/783)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
