### PR TITLE
added tests for nondeterministic gas usage

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/216)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/216)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/bank/gas.go` line 57 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhNRnoBWTHitwmPNac:-NDhNRnp05RGLbj-Jm3V:be1p9q3) ([raw file](https://github.com/coreumfoundation/coreum/blob/a42ca3f919cbab1fdd5e4d325d4896a3e1820830/integration-tests/bank/gas.go#L57)):*
> ```Go
> 	fees := testing.ComputeNeededBalance(
> 		chain.NetworkConfig.Fee.FeeModel.Params().InitialGasPrice,
> 		chain.GasLimitByMsgs(&banktypes.MsgSend{}, &banktypes.MsgSend{}),
> ```

you may use `gasExpected` here
___
*[`integration-tests/bank/gas.go` line 59 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhNhQO2ypxJT2GF7A2:-NDhNhQO2ypxJT2GF7A3:bns9hka) ([raw file](https://github.com/coreumfoundation/coreum/blob/a42ca3f919cbab1fdd5e4d325d4896a3e1820830/integration-tests/bank/gas.go#L59)):*
> ```Go
> 		chain.GasLimitByMsgs(&banktypes.MsgSend{}, &banktypes.MsgSend{}),
> 		1,
> 		sdk.NewInt(0),
> ```

You may put `amount` here instead of adding it later. This is exactly why this param exists
___
*[`integration-tests/bank/gas.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhOG_f5ddubjxxI5R_:-NDhOG_f5ddubjxxI5Ra:b-1dhtvm) ([raw file](https://github.com/coreumfoundation/coreum/blob/a42ca3f919cbab1fdd5e4d325d4896a3e1820830/integration-tests/bank/gas.go#L75)):*
> ```Go
> 		FromAddress: sender.String(),
> 		ToAddress:   receiver1.String(),
> 		Amount:      []sdk.Coin{sdk.NewCoin(chain.NetworkConfig.TokenSymbol, sdk.NewInt(1000))},
> ```

use `chain.NewCoin`
___
*[`integration-tests/bank/gas.go` line 80 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhOJyF6emkAgLPLMwU:-NDhOJyF6emkAgLPLMwV:b-1dhtvm) ([raw file](https://github.com/coreumfoundation/coreum/blob/a42ca3f919cbab1fdd5e4d325d4896a3e1820830/integration-tests/bank/gas.go#L80)):*
> ```Go
> 		FromAddress: sender.String(),
> 		ToAddress:   receiver2.String(),
> 		Amount:      []sdk.Coin{sdk.NewCoin(chain.NetworkConfig.TokenSymbol, sdk.NewInt(1000))},
> ```

use `chain.NewCoin`
___
*[`integration-tests/bank/gas.go` line 83 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhONONBcoLmNNnyzoz:-NDhONONBcoLmNNnyzp-:brrazho) ([raw file](https://github.com/coreumfoundation/coreum/blob/a42ca3f919cbab1fdd5e4d325d4896a3e1820830/integration-tests/bank/gas.go#L83)):*
> ```Go
> 	}
> 
> 	clientCtx := chain.ChainContext.ClientContext.WithFromName(senderKeyInfo.GetName()).WithFromAddress(sender)
> ```

AFAIK you don't need to call `WithFromName`, Dima changed everything to use `WithFromAddress` only
___
*[`integration-tests/wasm/gas.go` line 64 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhP0zBC1Iu4k1rqfqw:-NDhP0zBC1Iu4k1rqfqx:b-d8q9iu) ([raw file](https://github.com/coreumfoundation/coreum/blob/a42ca3f919cbab1fdd5e4d325d4896a3e1820830/integration-tests/wasm/gas.go#L64)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// send additional coins to contract directly
> ```

I think `// send additional coins to contract directly` and `// send coin from the contract to test wallet` parts are not needed. This is already tested in  the original wasm test, right?
___
*[`integration-tests/wasm/gas.go` line 100 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhPDowCrh8OCfQiziO:-NDhPDowCrh8OCfQiziP:b-xivswz) ([raw file](https://github.com/coreumfoundation/coreum/blob/a42ca3f919cbab1fdd5e4d325d4896a3e1820830/integration-tests/wasm/gas.go#L100)):*
> ```Go
> 	maxGasExpected := minGasExpected * 10
> 
> 	clientCtx := chain.ChainContext.ClientContext.WithFromName(adminKeyInfo.GetName()).WithFromAddress(adminAddress)
> ```

`WithFromName` not needed. If it is present in original code, please remove it from there too

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/216)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/bank/gas.go` line 57 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhNRnoBWTHitwmPNac:-NDhSS8EBh9l-rSwVPrM:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a42ca3f919cbab1fdd5e4d325d4896a3e1820830/integration-tests/bank/gas.go#L57)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you may use `gasExpected` here
</blockquote></details>

Done.
___
*[`integration-tests/bank/gas.go` line 59 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhNhQO2ypxJT2GF7A2:-NDhSSMN0lSkwiuFc3XV:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a42ca3f919cbab1fdd5e4d325d4896a3e1820830/integration-tests/bank/gas.go#L59)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You may put `amount` here instead of adding it later. This is exactly why this param exists
</blockquote></details>

Done.
___
*[`integration-tests/bank/gas.go` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhOG_f5ddubjxxI5R_:-NDhSfPIE_nJ32IyaiY7:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a42ca3f919cbab1fdd5e4d325d4896a3e1820830/integration-tests/bank/gas.go#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

use `chain.NewCoin`
</blockquote></details>

Done.
___
*[`integration-tests/bank/gas.go` line 80 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhOJyF6emkAgLPLMwU:-NDhSfl839UuuMVs1xh4:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a42ca3f919cbab1fdd5e4d325d4896a3e1820830/integration-tests/bank/gas.go#L80)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

use `chain.NewCoin`
</blockquote></details>

Done.
___
*[`integration-tests/bank/gas.go` line 83 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhONONBcoLmNNnyzoz:-NDhTv5E2ZKZeA_UXbXz:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a42ca3f919cbab1fdd5e4d325d4896a3e1820830/integration-tests/bank/gas.go#L83)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

AFAIK you don't need to call `WithFromName`, Dima changed everything to use `WithFromAddress` only
</blockquote></details>

Done.
___
*[`integration-tests/wasm/gas.go` line 64 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhP0zBC1Iu4k1rqfqw:-NDhTHyaAk39E9QA7Hx1:b-6kr5j2) ([raw file](https://github.com/coreumfoundation/coreum/blob/a42ca3f919cbab1fdd5e4d325d4896a3e1820830/integration-tests/wasm/gas.go#L64)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I think `// send additional coins to contract directly` and `// send coin from the contract to test wallet` parts are not needed. This is already tested in  the original wasm test, right?
</blockquote></details>

I changed the comments since they were misleading, the first part funds the contract address, the second one creates a wasmBankSend, so they are needed.
___
*[`integration-tests/wasm/gas.go` line 100 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhPDowCrh8OCfQiziO:-NDhTuL78GR7wj0gZqqg:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a42ca3f919cbab1fdd5e4d325d4896a3e1820830/integration-tests/wasm/gas.go#L100)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`WithFromName` not needed. If it is present in original code, please remove it from there too
</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/216)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`integration-tests/bank/gas.go` line 51 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhXIDsEOdT-ghfkVoh:-NDhXIDtE_rNdjSZYZCo:bfhjbpr) ([raw file](https://github.com/coreumfoundation/coreum/blob/e22e99633b47a4b34643dae04243c7a2bb8e1f20/integration-tests/bank/gas.go#L51)):*
> ```Go
> 
> // TestTransferDeterministicGas2BankSends checks that transfer takes the deterministic amount of gas
> func TestTransferDeterministicGas2BankSends(ctx context.Context, t testing.T, chain testing.Chain) {
> ```

2 -> Two ?
___
*[`integration-tests/bank/gas.go` line 58 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDh_r8L6pp8deRJCwrY:-NDh_r8L6pp8deRJCwrZ:bpq30o7) ([raw file](https://github.com/coreumfoundation/coreum/blob/e22e99633b47a4b34643dae04243c7a2bb8e1f20/integration-tests/bank/gas.go#L58)):*
> ```Go
> 		gasExpected,
> 		1,
> 		testing.MustNewIntFromString(t, "1000000000000"),
> ```

Why do you need that balance if send just 2k later?
___
*[`integration-tests/bank/gas.go` line 70 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDh_haQ-0Fl3wjEAaaf:-NDh_haQ-0Fl3wjEAaag:b-6r7rsb) ([raw file](https://github.com/coreumfoundation/coreum/blob/e22e99633b47a4b34643dae04243c7a2bb8e1f20/integration-tests/bank/gas.go#L70)):*
> ```Go
> 		FromAddress: sender.String(),
> 		ToAddress:   receiver1.String(),
> 		Amount:      []sdk.Coin{chain.NewCoin(sdk.NewInt(1000))},
> ```

sdk.NewCoins() - same for all places with the same usage
___
*[`integration-tests/wasm/gas.go` line 22 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhXVcc1A7U98m81BeQ:-NDhXVcc1A7U98m81BeR:bk29ev8) ([raw file](https://github.com/coreumfoundation/coreum/blob/e22e99633b47a4b34643dae04243c7a2bb8e1f20/integration-tests/wasm/gas.go#L22)):*
> ```Go
> // TestGasWasmBankSendAndBankSend checks that a message containing a deterministic and a
> // non-deterministic transaction takes gas within appropriate limits.
> func TestGasWasmBankSendAndBankSend(ctx context.Context, t testing.T, chain testing.Chain) {
> ```

Why the prev test name is 2BankSends the this send and sent?
___
*[`integration-tests/wasm/gas.go` line 29 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDha4pG0LYe1j7tmder:-NDha4pG0LYe1j7tmdes:b-ger44l) ([raw file](https://github.com/coreumfoundation/coreum/blob/e22e99633b47a4b34643dae04243c7a2bb8e1f20/integration-tests/wasm/gas.go#L29)):*
> ```Go
> 	requireT.NoError(err)
> 	unsafeKeyRing := keyring.NewUnsafe(chain.ChainContext.ClientContext.Keyring())
> 	adminPrivateKeyHex, err := unsafeKeyRing.UnsafeExportPrivKeyHex(adminKeyInfo.GetName())
> ```

Have you seen the "chain.AccAddressToLegacyWallet" usage?
___
*[`integration-tests/wasm/gas.go` line 96 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhbR4vAQqIN4dARLzE:-NDhbR4vAQqIN4dARLzF:blk1abo) ([raw file](https://github.com/coreumfoundation/coreum/blob/e22e99633b47a4b34643dae04243c7a2bb8e1f20/integration-tests/wasm/gas.go#L96)):*
> ```Go
> 	}
> 
> 	minGasExpected := chain.GasLimitByMsgs(&banktypes.MsgSend{}, &banktypes.MsgSend{})
> ```

I don't understand that test at all. What do you try to archive here?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/216)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/bank/gas.go` line 51 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhXIDsEOdT-ghfkVoh:-NE0UpPTB-q-kVF_Sfwz:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e22e99633b47a4b34643dae04243c7a2bb8e1f20/integration-tests/bank/gas.go#L51)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

2 -> Two ?
</blockquote></details>

Done.
___
*[`integration-tests/bank/gas.go` line 58 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDh_r8L6pp8deRJCwrY:-NE0UvAc-egx2gRQhA3x:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e22e99633b47a4b34643dae04243c7a2bb8e1f20/integration-tests/bank/gas.go#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need that balance if send just 2k later?
</blockquote></details>

Done.
___
*[`integration-tests/bank/gas.go` line 70 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDh_haQ-0Fl3wjEAaaf:-NE0VHWq34fX8AMZ1PDw:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e22e99633b47a4b34643dae04243c7a2bb8e1f20/integration-tests/bank/gas.go#L70)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

sdk.NewCoins() - same for all places with the same usage
</blockquote></details>

Done.
___
*[`integration-tests/wasm/gas.go` line 64 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhP0zBC1Iu4k1rqfqw:-NE0Wze54-3xnNXaQgFe:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/a42ca3f919cbab1fdd5e4d325d4896a3e1820830/integration-tests/wasm/gas.go#L64)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but contract already received some funds here:
```
amount:     chain.NewCoin(sdk.NewInt(10000)),
```
so you don't need to send tokens there again
</blockquote></details>

Done.
___
*[`integration-tests/wasm/gas.go` line 22 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhXVcc1A7U98m81BeQ:-NE0VPoa7T_DAm1g3koj:b-1gc6i9) ([raw file](https://github.com/coreumfoundation/coreum/blob/e22e99633b47a4b34643dae04243c7a2bb8e1f20/integration-tests/wasm/gas.go#L22)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why the prev test name is 2BankSends the this send and sent?
</blockquote></details>

Well it is just English. You say `2 apples` or `apple and banana` right ?
___
*[`integration-tests/wasm/gas.go` line 29 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDha4pG0LYe1j7tmder:-NE0WJY-9tcWwRODV5Ip:butjhm1) ([raw file](https://github.com/coreumfoundation/coreum/blob/e22e99633b47a4b34643dae04243c7a2bb8e1f20/integration-tests/wasm/gas.go#L29)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Have you seen the "chain.AccAddressToLegacyWallet" usage?
</blockquote></details>

I had not. Changed to use that.
___
*[`integration-tests/wasm/gas.go` line 96 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhbR4vAQqIN4dARLzE:-NE0XqTC6YXABBJhTHl1:b7x8ldt) ([raw file](https://github.com/coreumfoundation/coreum/blob/e22e99633b47a4b34643dae04243c7a2bb8e1f20/integration-tests/wasm/gas.go#L96)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I don't understand that test at all. What do you try to archive here? 
</blockquote></details>

we test that a gas estimation works for combination of a deterministic and non-deterministic message in a single tx, work properly by asserting that it uses more gas than 2 bank sends and less gas than 20 bank sends.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/216)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/gas.go` line 22 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/216#-NDhXVcc1A7U98m81BeQ:-NE0s5xMDirhoE2TcXyQ:bbhd0zf) ([raw file](https://github.com/coreumfoundation/coreum/blob/e22e99633b47a4b34643dae04243c7a2bb8e1f20/integration-tests/wasm/gas.go#L22)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Well it is just English. You say `2 apples` or `apple and banana` right ?
</blockquote></details>

I mean the prev test has similar name -> TwoBankSends but the form if different here. What is the reason?

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/216)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @ysv)

**Pull request merged**
