### PR TITLE
added cli for nft send authorization

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/691)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/691)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/nft/client/cli/tx.go` line 25 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/691#-NhkpRVXB6wwXCZVXekP:-NhkpRVXB6wwXCZVXekQ:b-nqjnlz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f7027636ab42de6dd94f7d8635413850bfe81ca8/x/asset/nft/client/cli/tx.go#L25)):*
> ```Go
> // Flags defined on transactions.
> const (
> 	AuthzFlag       = "authz"
> ```

maybe "auth-file"?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/691)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/client/cli/tx.go` line 25 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/691#-NhkpRVXB6wwXCZVXekP:-Nhkxlfd7SXofjX9PSp2:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f7027636ab42de6dd94f7d8635413850bfe81ca8/x/asset/nft/client/cli/tx.go#L25)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

maybe "auth-file"?
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/691)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/691)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`x/asset/nft/client/cli/tx.go` line 556 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/691#-NhlBdS51nh3RJCduRTb:-NhlBdS51nh3RJCduRTc:bt86ytb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5e80c520b88da610e0aade4347ac7e8fbd8e44fc/x/asset/nft/client/cli/tx.go#L556)):*
> ```Go
> func CmdGrantAuthorization() *cobra.Command {
> 	cmd := &cobra.Command{
> 		Use:   "grant [grantee] [message_type=\"send\"] --from <granter> --authz=path/to/authz.json",
> ```

--auth-file, or you may put %s here and pass param

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/691)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/asset/nft/client/cli/tx.go` line 25 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/691#-NhzSO3Q1aBDIICC1u03:-NhzSO3Q1aBDIICC1u04:bcpco6t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/01c0e09382159fc48e97dbc7efe4c84dec9342ab/x/asset/nft/client/cli/tx.go#L25)):*
> ```Go
> // Flags defined on transactions.
> const (
> 	AuthzFlag       = "auth-file"
> ```

AuthFileFlag
___
*[`x/asset/nft/client/cli/tx.go` line 572 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/691#-NhzSe2fDpEeLGkIrsqM:-NhzSe2fDpEeLGkIrsqN:bew46fk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/01c0e09382159fc48e97dbc7efe4c84dec9342ab/x/asset/nft/client/cli/tx.go#L572)):*
> ```Go
> 	]
> }
> `, version.AppName, version.AppName, constant.AddressSampleTest, AuthzFlag),
> ```

You pass the flag here, but you don't refer it inside string

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/691)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/691)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
