### PR TITLE
Bank send batch limits

### PR DESCRIPTION
**Pull request by dzmitryhil**
Add integration test which submits bulk batch send transactions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/288)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/288)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJ4sQ262nU9SZGnV68f:-NJ4sQ271_-VtvG8cyeK:b6972k2) (no related file):*
Should we include these tests as part of our integration tests nad have them run all the time. these look more like benchmarks than tests

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/288)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJ4sQ262nU9SZGnV68f:-NJ5EfA6AbRg2t6FT6LQ:b-luuaxt) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Should we include these tests as part of our integration tests nad have them run all the time. these look more like benchmarks than tests
</blockquote></details>

That's ok, since I set the params for them easy to pass. 

___

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/288)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/bank/batch.go` line 130 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJAPXqD10XmwCQi6YfU:-NJAPXqFBx8Rhl3LRl21:b-dudxbd) ([raw file](https://github.com/coreumfoundation/coreum/blob/0eabb7e2e4e504aba4129ab709d9c302876c4a33/integration-tests/bank/batch.go#L130)):*
> ```Go
> 			FromAddress: issuer.String(),
> 			ToAddress:   recipient.String(),
> 			Amount:      sdk.NewCoins(coinToFund),
> ```

more interesting case to test would be putting hundreds of different tokens here

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/288)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/bank/batch.go` line 130 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJAPXqD10XmwCQi6YfU:-NJAjMBb5Snk4K_IttVj:byxbxii) ([raw file](https://github.com/coreumfoundation/coreum/blob/0eabb7e2e4e504aba4129ab709d9c302876c4a33/integration-tests/bank/batch.go#L130)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

more interesting case to test would be putting hundreds of different tokens here
</blockquote></details>

I've tested with different, the throughput is the same. The difference might be with the multiple Coins, but not significant. The coin/sec remains almost the same.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/288)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJ4sQ262nU9SZGnV68f:-NJBS57R4yWUvpU2x665:b-n6i856) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

That's ok, since I set the params for them easy to pass. 
</blockquote></details>

well if they execute in a reasonable amount of time and don't cause too much load on chain I don't mind keeping them

___
___
*[`integration-tests/bank/batch.go` line 20 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJBSWgfEZcYJZe3ilGG:-NJBSWgfEZcYJZe3ilGH:bs09c9p) ([raw file](https://github.com/coreumfoundation/coreum/blob/0eabb7e2e4e504aba4129ab709d9c302876c4a33/integration-tests/bank/batch.go#L20)):*
> ```Go
> 
> // TestMultiSendBatch tests MultiSend message with maximum amount of addresses.
> func TestMultiSendBatch(ctx context.Context, t testing.T, chain testing.Chain) {
> ```

now I see that we had different understanding of the way you test it
maybe better names would be:
`TestBankMultisendBatchOutputs` (means you batch outputs in a single msg)
`TestBankSendBatchMsgs` (means you batch msgs in a single tx)
___
*[`integration-tests/bank/batch.go` line 70 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJBUJA9DF7Yv-4yOBL_:-NJBUJA9DF7Yv-4yOBLa:b-7kbd9j) ([raw file](https://github.com/coreumfoundation/coreum/blob/0eabb7e2e4e504aba4129ab709d9c302876c4a33/integration-tests/bank/batch.go#L70)):*
> ```Go
> 	requireT.NoError(chain.Faucet.FundAccountsWithOptions(ctx, issuer, testing.BalancesOptions{
> 		Messages: append([]sdk.Msg{issueMsg}, multiSendMsgs...),
> 		Amount:   sdk.NewInt(10_000_000), // add more coins to cover nondeterministic part
> ```

wrong comment
it covers extra bytes out of std included in FixedGas
___
*[`integration-tests/bank/batch.go` line 89 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJBUiCA6y7VB45qyqsQ:-NJBUiCA6y7VB45qyqsR:b-2aq2l0) ([raw file](https://github.com/coreumfoundation/coreum/blob/0eabb7e2e4e504aba4129ab709d9c302876c4a33/integration-tests/bank/batch.go#L89)):*
> ```Go
> 			chain.ClientContext.WithFromAddress(issuer),
> 			// we estimate here since the th size is grater then allowed for the deterministic fee
> 			chain.TxFactory().WithSimulateAndExecute(true),
> ```

does our estimation use DeterministicGas ?
___
*[`integration-tests/bank/batch.go` line 93 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJBUfcf7F6rN-AQNlI1:-NJBUfcf7F6rN-AQNlI2:bdgiw4d) ([raw file](https://github.com/coreumfoundation/coreum/blob/0eabb7e2e4e504aba4129ab709d9c302876c4a33/integration-tests/bank/batch.go#L93)):*
> ```Go
> 		)
> 		requireT.NoError(err)
> 		logger.Get(ctx).Info(fmt.Sprintf("Successfully sent batch MultiSend tx, hash: %s", res.TxHash))
> ```

can you also log gas_used ?
would be nice to assert gas also
___
*[`integration-tests/bank/batch.go` line 171 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJBTN4M2kuoa3usdI5k:-NJBTN4M2kuoa3usdI5l:bs4p0v6) ([raw file](https://github.com/coreumfoundation/coreum/blob/0eabb7e2e4e504aba4129ab709d9c302876c4a33/integration-tests/bank/batch.go#L171)):*
> ```Go
> 	ctx context.Context,
> 	chain testing.Chain,
> 	coinToFund sdk.Coin,
> ```

IMO it is logical to rename `coinToFund -> expectedBalance` and use it instead of  2 args`coinToFund & interactionsToFund `because it is not a logic of assertion to calculate balances

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/288)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJ4sQ262nU9SZGnV68f:-NJE1UvN4Bsy0rKdYsuk:b-hom48f) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

well if they execute in a reasonable amount of time and don't cause too much load on chain I don't mind keeping them
</blockquote></details>

It's already on the test is  a reasonable amount of time.

___
___
*[`integration-tests/bank/batch.go` line 20 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJBSWgfEZcYJZe3ilGG:-NJE0LgF7A_sRZuPBOep:bvzopxc) ([raw file](https://github.com/coreumfoundation/coreum/blob/0eabb7e2e4e504aba4129ab709d9c302876c4a33/integration-tests/bank/batch.go#L20)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

now I see that we had different understanding of the way you test it
maybe better names would be:
`TestBankMultisendBatchOutputs` (means you batch outputs in a single msg)
`TestBankSendBatchMsgs` (means you batch msgs in a single tx)

</blockquote></details>

Called `TestMultiSendBatchOutputs` and `TestSendBatchMsgs` 
___
*[`integration-tests/bank/batch.go` line 70 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJBUJA9DF7Yv-4yOBL_:-NJE0tlD151Hu5MdYBJa:b-bu91xm) ([raw file](https://github.com/coreumfoundation/coreum/blob/0eabb7e2e4e504aba4129ab709d9c302876c4a33/integration-tests/bank/batch.go#L70)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

wrong comment
it covers extra bytes out of std included in FixedGas
</blockquote></details>

Updated



_Code quote:_
```Go
 // add more coins to cover nondeterministic part
```
___
*[`integration-tests/bank/batch.go` line 89 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJBUiCA6y7VB45qyqsQ:-NJE0xM_3pX1JYqrGBKA:b-w0ho5o) ([raw file](https://github.com/coreumfoundation/coreum/blob/0eabb7e2e4e504aba4129ab709d9c302876c4a33/integration-tests/bank/batch.go#L89)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

does our estimation use DeterministicGas ?
</blockquote></details>

We set it here becase of extra bytes. As I mentioned, the `GasLimitByMsgs` doesn't cloud the bytes.
___
*[`integration-tests/bank/batch.go` line 93 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJBUfcf7F6rN-AQNlI1:-NJE1OdbCwZKJ0h51KrN:b-683di9) ([raw file](https://github.com/coreumfoundation/coreum/blob/0eabb7e2e4e504aba4129ab709d9c302876c4a33/integration-tests/bank/batch.go#L93)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can you also log gas_used ?
would be nice to assert gas also
</blockquote></details>

Sure. Updated.



_Code quote:_
```Go
logger.Get(ctx).Info(fmt.Sprintf("Successfully sent batch MultiS
```
___
*[`integration-tests/bank/batch.go` line 171 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJBTN4M2kuoa3usdI5k:-NJE2Sid6FVKE3mA1VhB:b-50i0uf) ([raw file](https://github.com/coreumfoundation/coreum/blob/0eabb7e2e4e504aba4129ab709d9c302876c4a33/integration-tests/bank/batch.go#L171)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO it is logical to rename `coinToFund -> expectedBalance` and use it instead of  2 args`coinToFund & interactionsToFund `because it is not a logic of assertion to calculate balances
</blockquote></details>

We have them separately to be able to adjust them separately. And `coinToFund` becomes the `expectedBalance` just after the submission.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/288)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJ4sQ262nU9SZGnV68f:-NJFm9_-3XkIIjFKxSrS:b-mo5qkx) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's already on the test is  a reasonable amount of time.
</blockquote></details>

I'm ok to keep it

___
___
*[`integration-tests/bank/batch.go` line 20 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJBSWgfEZcYJZe3ilGG:-NJFmn6NBamL-H7zftZE:b-fe4wwp) ([raw file](https://github.com/coreumfoundation/coreum/blob/0eabb7e2e4e504aba4129ab709d9c302876c4a33/integration-tests/bank/batch.go#L20)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Called `TestMultiSendBatchOutputs` and `TestSendBatchMsgs` 
</blockquote></details>

resolved:

but would be also nice to improve comments so it is clear
___
*[`integration-tests/bank/batch.go` line 171 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJBTN4M2kuoa3usdI5k:-NJFnvnB1Mrrh973lvlS:b-8ed76h) ([raw file](https://github.com/coreumfoundation/coreum/blob/0eabb7e2e4e504aba4129ab709d9c302876c4a33/integration-tests/bank/batch.go#L171)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We have them separately to be able to adjust them separately. And `coinToFund` becomes the `expectedBalance` just after the submission. 
</blockquote></details>

I don't understand why we need both args if one should be enough

you just call
```
assertBatchAccounts(ctx, chain, coinToFund.Amount.MulRaw(int64(interactionsToFund), fundedAccounts, denom, requireT)
```

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/288)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJ4sQ262nU9SZGnV68f:-NJFrinF6zL0cTYrYQZr:b-896fix) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm ok to keep it
</blockquote></details>

Done.

___
___
*[`integration-tests/bank/batch.go` line 171 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/288#-NJBTN4M2kuoa3usdI5k:-NJFt03C1xcw9pJvaAhD:b-yjik0x) ([raw file](https://github.com/coreumfoundation/coreum/blob/0eabb7e2e4e504aba4129ab709d9c302876c4a33/integration-tests/bank/batch.go#L171)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't understand why we need both args if one should be enough

you just call
```
assertBatchAccounts(ctx, chain, coinToFund.Amount.MulRaw(int64(interactionsToFund), fundedAccounts, denom, requireT)
```

</blockquote></details>

Got you now. Updated.

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/288)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/288)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/288)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil)

**Pull request merged**
