### PR TITLE
Use relative param definitions for feemodel

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/217)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/217)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/feemodel/proposal.go` line 40 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/217#-NDmRiSN-c-SWd_9kSUr:-NDmRiSN-c-SWd_9kSUs:b-rgp8s) ([raw file](https://github.com/coreumfoundation/coreum/blob/c10ebc234ac73c14ccea2ce50196a89a81905fc9/integration-tests/feemodel/proposal.go#L40)):*
> ```Go
> 	// Create invalid proposal MaxGasPrice = InitialGasPrice.
> 	feeModelParams := feeModelParamsRes.Params.Model
> 	feeModelParams.MaxGasPriceMultiplier = sdk.MustNewDecFromStr("1.0")
> ```

Won't the 'sdk.NewDec' work or 'NewDecWithPrec'?



_Code quote:_
```Go
 sdk.MustNewDecFromStr
```
___
*[`x/feemodel/module.go` line 134 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/217#-NDmRN-j4AeInKhe3dPB:-NDmRN-j4AeInKhe3dPC:b-2y506o) ([raw file](https://github.com/coreumfoundation/coreum/blob/c10ebc234ac73c14ccea2ce50196a89a81905fc9/x/feemodel/module.go#L134)):*
> ```Go
> 
> 	// FIXME (wojtek): remove this
> 	genesis.Params.Model.EscalationStartFraction = sdk.MustNewDecFromStr("0.8")
> ```

Why do you need this?
___
*[`x/feemodel/module_test.go` line 118 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/217#-NDmRYoi6uZyitEf3kY9:-NDmRYoi6uZyitEf3kYA:b-2y506o) ([raw file](https://github.com/coreumfoundation/coreum/blob/c10ebc234ac73c14ccea2ce50196a89a81905fc9/x/feemodel/module_test.go#L118)):*
> ```Go
> 
> 	// FIXME (wojtek): remove this
> 	decodedGenesis.Params.Model.MaxGasPrice = sdk.Dec{}
> ```

Why do you need this?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/217)* status: 0 of 16 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/feemodel/proposal.go` line 40 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/217#-NDmRiSN-c-SWd_9kSUr:-NDmTkGS2xX48xNLnrP8:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/c10ebc234ac73c14ccea2ce50196a89a81905fc9/integration-tests/feemodel/proposal.go#L40)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Won't the 'sdk.NewDec' work or 'NewDecWithPrec'?
</blockquote></details>

Done
___
*[`x/feemodel/module.go` line 134 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/217#-NDmRN-j4AeInKhe3dPB:-NDmTOGAEnFdgeVcPoS6:b3367w3) ([raw file](https://github.com/coreumfoundation/coreum/blob/c10ebc234ac73c14ccea2ce50196a89a81905fc9/x/feemodel/module.go#L134)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need this?
</blockquote></details>

it's needed before crust imports new version of coreum
___
*[`x/feemodel/module_test.go` line 118 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/217#-NDmRYoi6uZyitEf3kY9:-NDmTURBCUY_PRYaVNgk:bb7od0r) ([raw file](https://github.com/coreumfoundation/coreum/blob/c10ebc234ac73c14ccea2ce50196a89a81905fc9/x/feemodel/module_test.go#L118)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need this?
</blockquote></details>

same

**Review by miladz68 — COMMENTED** [review]
> Reviewed 14 of 16 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/217)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`x/feemodel/types/model.go` line 60 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/217#-NE0Cmfh4PyRfVsHAPf7:-NE0Cmfh4PyRfVsHAPf8:b-4058jo) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d54538bb271d77c3c70fe38bdf32910feff9dda/x/feemodel/types/model.go#L60)):*
> ```Go
> // CalculateEscalationStartBlockGas calculates escalation start block gas
> func (m Model) CalculateEscalationStartBlockGas() int64 {
> 	return sdk.NewInt(m.params.MaxBlockGas).ToDec().Mul(m.params.EscalationStartFraction).TruncateInt64()
> ```

non-blocking
I ran a quick bench and this operation takes slightly less than 1ms to run (around 800 ns). That is not very expensive, but definitely not cheap. Do you think it is worth to cache such operations ? these 1ms happens at each block and they can add up.

**Review by miladz68 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/217#-:-NE0Pn_jDb_o9Wpke_uZ:bnfp4nl)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/217)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`x/feemodel/types/model.go` line 60 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/217#-NE0Cmfh4PyRfVsHAPf7:-NE0pdqp0yuG9JxFZb14:b5ml6vy) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d54538bb271d77c3c70fe38bdf32910feff9dda/x/feemodel/types/model.go#L60)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking
I ran a quick bench and this operation takes slightly less than 1ms to run (around 800 ns). That is not very expensive, but definitely not cheap. Do you think it is worth to cache such operations ? these 1ms happens at each block and they can add up. 
</blockquote></details>

To cache it I would have to detect if cache should be invalidated which would be more expensive

**Pull request merged**
