### PR TITLE
Asset features table

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/480)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/480)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/asset/ft/spec/README.md` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/480#-NU6e3hQBe5Ek_EaqeAt:-NU6e3hQBe5Ek_EaqeAu:bxw6gbi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5555b988b80f330c96453c4f7f0bee4678fe8119/x/asset/ft/spec/README.md#L86)):*
> ```Markdown
> - The user can receive tokens as long as their total balance, after the transaction execution, will not be higher than their whitelisted amount
> 
> ## Access table
> ```

technically it is not access table as we were naming it all this time

maybe: `Feature inter behaviour` / `feature compatibility` / `feature interoperability`
___
*[`x/asset/ft/spec/README.md` line 89 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/480#-NU6gZ416-n-RBPhjgaN:-NU6gZ416-n-RBPhjgaO:b6aqv3d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5555b988b80f330c96453c4f7f0bee4678fe8119/x/asset/ft/spec/README.md#L89)):*
> ```Markdown
> 
> | 	                  | **Features**  	  |    	    |       	        |    	    |       	        |    	    |        	        |            	             |         	          |           	           | **Extentions** 	  |          	          |             	              |               	                |
> |--------------------|:----------------:|:-------:|:--------------:|:-------:|:--------------:|:-------:|:---------------:|:------------------------:|:------------------:|:---------------------:|:-----------------:|:-------------------:|:--------------------------:|:------------------------------:|
> ```



these 2 parts doesn't look good
Can't we build complex table in md ?
if we can't simply do this lets inject some HTML because currently it is not readable
___
*[`x/asset/ft/spec/README.md` line 93 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/480#-NU6ezKb72I2apTAkDGO:-NU6ezKb72I2apTAkDGP:b-mwdizw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5555b988b80f330c96453c4f7f0bee4678fe8119/x/asset/ft/spec/README.md#L93)):*
> ```Markdown
> | 	                  |   Issuer    	    | Owner 	 |    Issuer 	    | Owner 	 |    Issuer 	    | Owner 	 |    Issuer  	    |         Owner 	          |    Issuer    	     |      Recipient 	      |   Issuer     	    |       Owner 	       |      Issuer        	       |            Owner 	             |
> | Mint             	 |        	         |    	    |     +    	     |    	    |       	        |    	    |        	        |            	             |         	          |           	           |         	         |          	          |             	              |               	                |
> | Burn             	 |     +      	     |    	    |       	        |    	    |       	        |  +   	  |        	        |            	             |         	          |           	           |         	         |          	          |             	              |               	                |
> ```

lets also use emojis for: 
`!` -> ❗️
`+` -> ➕
___
*[`x/asset/ft/spec/README.md` line 97 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/480#-NU6etLIA9gEflvKfl9P:-NU6etLIA9gEflvKfl9Q:b-qihafg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5555b988b80f330c96453c4f7f0bee4678fe8119/x/asset/ft/spec/README.md#L97)):*
> ```Markdown
> | Unfreeze         	 |        	         |    	    |       	        |    	    |       	        |    	    |     +    	      |            	             |         	          |           	           |         	         |          	          |             	              |               	                |
> | GloballyFreeze   	 |        	         |    	    |       	        |    	    |       	        |    	    |     +    	      |            	             |         	          |           	           |         	         |          	          |             	              |               	                |
> | GloballyUnFreeze 	 |        	         |    	    |       	        |    	    |       	        |    	    |     +    	      |            	             |         	          |           	           |         	         |          	          |             	              |               	                |
> ```

unFreeze -> unfreeze
___
*[`x/asset/nft/spec/README.md` line 57 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/480#-NU6gyL45tBx3kSak8xw:-NU6gyL45tBx3kSak8xx:b-gd497o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5555b988b80f330c96453c4f7f0bee4678fe8119/x/asset/nft/spec/README.md#L57)):*
> ```Markdown
> This feature is related to the DEX, and if it is enabled, every time that an NFT is traded on the DEX, a percentage of the traded value is sent to the issuer as royalty fee.
> 
> ## Access table
> ```

same comments as for FT

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/480)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/480)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/480#-NU6e3hQBe5Ek_EaqeAt:-NULVzmW9ALmqv1MxaJ2:buzkget) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5555b988b80f330c96453c4f7f0bee4678fe8119/x/asset/ft/spec/README.md#L86)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

technically it is not access table as we were naming it all this time

maybe: `Feature inter behaviour` / `feature compatibility` / `feature interoperability`
</blockquote></details>

Called "Features interoperability table"
___
*[`x/asset/ft/spec/README.md` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/480#-NU7BDtm98b5sUtxu1Zn:-NULW1o81bCBYYwR3YHa:bqmjwcz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5555b988b80f330c96453c4f7f0bee4678fe8119/x/asset/ft/spec/README.md#L86)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

add comment to the tool to build this table
</blockquote></details>

Added.
___
*[`x/asset/ft/spec/README.md` line 89 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/480#-NU6gZ416-n-RBPhjgaN:-NULW3iL2DgU67LWSr6o:b-2g03c5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5555b988b80f330c96453c4f7f0bee4678fe8119/x/asset/ft/spec/README.md#L89)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>



these 2 parts doesn't look good
Can't we build complex table in md ?
if we can't simply do this lets inject some HTML because currently it is not readable
</blockquote></details>

Updated with HTML
___
*[`x/asset/ft/spec/README.md` line 93 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/480#-NU6ezKb72I2apTAkDGO:-NULcCDm5ynfi-8VT2ci:b69b9zq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5555b988b80f330c96453c4f7f0bee4678fe8119/x/asset/ft/spec/README.md#L93)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

lets also use emojis for: 
`!` -> ❗️
`+` -> ➕
</blockquote></details>

Updated for `+` and `-`.  (we dont' use the `!`)
___
*[`x/asset/ft/spec/README.md` line 97 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/480#-NU6etLIA9gEflvKfl9P:-NULcNoy-512YTeRitOP:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5555b988b80f330c96453c4f7f0bee4678fe8119/x/asset/ft/spec/README.md#L97)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

unFreeze -> unfreeze
</blockquote></details>

Done.



_Code quote:_
```Markdown
>GloballyUnFreeze
```
___
*[`x/asset/nft/spec/README.md` line 57 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/480#-NU6gyL45tBx3kSak8xw:-NULcP1b9M-G9j8cVSE7:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5555b988b80f330c96453c4f7f0bee4678fe8119/x/asset/nft/spec/README.md#L57)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

same comments as for FT
</blockquote></details>

Done.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/480)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/asset/ft/spec/README.md` line 93 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/480#-NU6ezKb72I2apTAkDGO:-NUNGV-5-CGADZJeXukK:btxh8qb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5555b988b80f330c96453c4f7f0bee4678fe8119/x/asset/ft/spec/README.md#L93)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Updated for `+` and `-`.  (we dont' use the `!`)
</blockquote></details>

should we use ℹ️ for info?
___
*[`x/asset/nft/spec/README.md` line 81 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/480#-NUNGjvnBb-vNW61mkx2:-NUNGjvo6GEDTMI_DorQ:b2k1seo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/01a45ed9ae024b4f84a6ffe868815fcc3ba4e16d/x/asset/nft/spec/README.md#L81)):*
> ```Markdown
>     <th>Owner</th>
>     <th>Issuer</th>
>     <th>Owner</th>
> ```

immature comment:

when I opened it for the second time (first time it was clear) I was confused by word Owner

maybe you have an idea of another word here ? Or  add it to Legend ?

**Review by miladz68 — DISMISSED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/480)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/480)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 93 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/480#-NU6ezKb72I2apTAkDGO:-NUQguJm3y8uYO6k-W1D:b-lsrk89) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5555b988b80f330c96453c4f7f0bee4678fe8119/x/asset/ft/spec/README.md#L93)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should we use ℹ️ for info?
</blockquote></details>

The current is as good as ℹ️  IMO.
___
*[`x/asset/nft/spec/README.md` line 81 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/480#-NUNGjvnBb-vNW61mkx2:-NUQh1vQCaUK9z1HoHm1:bwjeuvy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/01a45ed9ae024b4f84a6ffe868815fcc3ba4e16d/x/asset/nft/spec/README.md#L81)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

immature comment:

when I opened it for the second time (first time it was clear) I was confused by word Owner

maybe you have an idea of another word here ? Or  add it to Legend ?
</blockquote></details>

Agree, updated teh `Legend` with `Owner`, `Issuer` and `Recipient`.

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/480)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/480)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
