### PR TITLE
Create authorization message for miniting with limit

### PR DESCRIPTION
**Pull request by miladz68**
# Description
This PR, creates a minting auth function, which allows grantees to mint but only up to the limit specified in the grant. 
# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/658)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/658)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2582 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/658#-NehLyR59x735AAQQ8Ag:-NehLyR59x735AAQQ8Ah:b-gtxyq8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e8b41d33bf0826ca0f8c24229b968fd9bc8cb131/integration-tests/modules/assetft_test.go#L2582)):*
> ```Go
> 	requireT.EqualValues("921", whitelistingRes.GetBalance().Amount.String())
> }
> ```

Some missing test cases:
- minting is not possible after revoking the grant
- minting is not possible before granting permission
- grant is or is not transitive (depending on design decision)
- grant for one token doesn't work for another token of the same issuer
___
*[`integration-tests/modules/assetft_test.go` line 2696 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/658#-NehLQlWDakaCGLE2FLR:-NehLQlWDakaCGLE2FLS:bdholeh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e8b41d33bf0826ca0f8c24229b968fd9bc8cb131/integration-tests/modules/assetft_test.go#L2696)):*
> ```Go
> 		&execMsg,
> 	)
> 	requireT.Error(err)
> ```

Check the type of error
___
*[`integration-tests/modules/assetft_test.go` line 2781 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/658#-NehLtjA96gm2muRUrz9:-NehLtjA96gm2muRUrzA:becab9h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e8b41d33bf0826ca0f8c24229b968fd9bc8cb131/integration-tests/modules/assetft_test.go#L2781)):*
> ```Go
> 		lo.ToPtr(time.Now().Add(time.Minute)),
> 	)
> 	require.NoError(t, err)
> ```

Shouldn't it fail here?
___
*[`x/asset/ft/types/mint_authorization.go` line 41 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/658#-NehNBVNCbrCtGi75enS:-NehNBVNCbrCtGi75enT:b-ugg7ef) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e8b41d33bf0826ca0f8c24229b968fd9bc8cb131/x/asset/ft/types/mint_authorization.go#L41)):*
> ```Go
> 	return authz.AcceptResponse{
> 		Accept:  true,
> 		Delete:  false,
> ```

Non-blocking; Maybe you could set `Delete: limitLeft.IsZero()` here instead of previous `if`?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/658)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2584 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/658#-NehWKD35Iq1N0z0J_Gg:-NehWKD49XYN8quVbPzN:b-hvzdnq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e8b41d33bf0826ca0f8c24229b968fd9bc8cb131/integration-tests/modules/assetft_test.go#L2584)):*
> ```Go
> 
> // TestAuthzMintAuthorizationLimit tests the authz MintLimitAuthorization msg works as expected.
> func TestAuthzMintAuthorizationLimit(t *testing.T) {
> ```

Is it possible to query granted amount or left amount?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/658)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2584 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/658#-NehWKD35Iq1N0z0J_Gg:-NelfSYqDGO6oHlXFBlU:b-vq3z43) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e8b41d33bf0826ca0f8c24229b968fd9bc8cb131/integration-tests/modules/assetft_test.go#L2584)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is it possible to query granted amount or left amount?
</blockquote></details>

yes, I have done so in the test. 
___
*[`integration-tests/modules/assetft_test.go` line 2781 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/658#-NehLtjA96gm2muRUrz9:-NelfYmw7L82kAvKtp4m:b5p1mgn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e8b41d33bf0826ca0f8c24229b968fd9bc8cb131/integration-tests/modules/assetft_test.go#L2781)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Shouldn't it fail here?
</blockquote></details>

no, authz does not know the internal logic of the module.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/658)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/658)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2696 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/658#-NehLQlWDakaCGLE2FLR:-Nem2bau4tABFfL1WRA0:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e8b41d33bf0826ca0f8c24229b968fd9bc8cb131/integration-tests/modules/assetft_test.go#L2696)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Check the type of error
</blockquote></details>

Done
___
*[`x/asset/ft/types/mint_authorization.go` line 41 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/658#-NehNBVNCbrCtGi75enS:-Nem3MIDB8SXAPQYpk7j:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e8b41d33bf0826ca0f8c24229b968fd9bc8cb131/x/asset/ft/types/mint_authorization.go#L41)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Non-blocking; Maybe you could set `Delete: limitLeft.IsZero()` here instead of previous `if`?
</blockquote></details>

Done

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/658)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/658)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
