### PR TITLE
Burn and send fees are not applied when tokens are set by the smart contract

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

When tokens are sent from smart contract fees don't apply. This is introduced to support chains of smart contract calls. Otherwise transaction would fail if one smart contract wanted to pass funds to another one.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/633)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/633)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 3147 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYyZ-t1Mjw-bQsZuke:-NdYyZ-t1Mjw-bQsZukf:boq4pp2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/integration-tests/modules/assetft_test.go#L3147)):*
> ```Go
> 	initialPayload, err := json.Marshal(struct{}{})
> 	requireT.NoError(err)
> 	contractAddr, _, err := chain.Wasm.DeployAndInstantiateWASMContract(
> ```

I would propose to execute that operation from the `admin` account to check how the balance behaves. 
___
*[`integration-tests/modules/assetft_test.go` line 3171 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYvcUQ2bAtMz_ykxvR:-NdYvcUQ2bAtMz_ykxvS:b-83qg8e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/integration-tests/modules/assetft_test.go#L3171)):*
> ```Go
> 	requireT.NoError(err)
> 	requireT.NotNil(balance.Balance)
> 	requireT.Equal(sdk.NewInt64Coin(denom, 400).String(), balance.Balance.String())
> ```

So the admin doesn't pay fees on the instantiation, right?
___
*[`integration-tests/modules/assetft_test.go` line 3323 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYz4wMBxp1_zakKv4k:-NdYz4wMBxp1_zakKv4l:b93of11) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/integration-tests/modules/assetft_test.go#L3323)):*
> ```Go
> 	requireT.Equal(sdk.NewInt64Coin(denom, 210).String(), balance.Balance.String())
> 
> 	fmt.Println(contractAddr)
> ```

Unnecessary line. 
___
*[`x/asset/ft/keeper/before_send.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYw4rV1K0WUHeLFcMx:-NdYw4rV1K0WUHeLFcMy:bnute0p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/x/asset/ft/keeper/before_send.go#L161)):*
> ```Go
> 	taxableInputSum := sdkmath.ZeroInt()
> 	shares := accountOperationMap{}
> 	for account, amount := range inOps {
> ```

The ` inOps` is a map, and we agreed to use a sorted loop for the maps in keepers (or used keeper). I see that we don't follow it here and in the next loop. WDYTH guys @miladz68 @ysv, is it safe? (BTW the second loop was here before the @wojtek-coreum changes). We might add some logic tomorrow to the loop and forget that this loop is a map loop without an order guarantee. 
 
___
*[`x/asset/ft/keeper/before_send_test.go` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYyHKS9Fqefgtgw5aa:-NdYyHKS9Fqefgtgw5ab:b-tv4zba) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/x/asset/ft/keeper/before_send_test.go#L39)):*
> ```Go
> 	issuer := genAccount()
> 	dummyAddress := genAccount()
> 	assetFTKeeper := assetftkeeper.NewKeeper(nil, nil, nil, nil, nil, nil)
> ```

Why don't you add a test case for the wasm account?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/633)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 3147 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYyZ-t1Mjw-bQsZuke:-NdZKaED9t3xfxUGgpNT:b-4ybz5w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/integration-tests/modules/assetft_test.go#L3147)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would propose to execute that operation from the `admin` account to check how the balance behaves.
</blockquote></details>

Added another test case
___
*[`integration-tests/modules/assetft_test.go` line 3171 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYvcUQ2bAtMz_ykxvR:-NdZDmvzCL--S2m78Wlq:b-dlnl96) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/integration-tests/modules/assetft_test.go#L3171)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

So the admin doesn't pay fees on the instantiation, right?
</blockquote></details>

This is the issuer who instantiated the contract
___
*[`x/asset/ft/keeper/before_send.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYw4rV1K0WUHeLFcMx:-NdZE65yBomOBg-mTY1a:b-s3qlt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/x/asset/ft/keeper/before_send.go#L161)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The ` inOps` is a map, and we agreed to use a sorted loop for the maps in keepers (or used keeper). I see that we don't follow it here and in the next loop. WDYTH guys @miladz68 @ysv, is it safe? (BTW the second loop was here before the @wojtek-coreum changes). We might add some logic tomorrow to the loop and forget that this loop is a map loop without an order guarantee.
</blockquote></details>

Here it doesn't matter.Later on, when store is updated we do sorting.
___
*[`x/asset/ft/keeper/before_send_test.go` line 39 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYyHKS9Fqefgtgw5aa:-NdZI-Po5L2ioR3tJYQk:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/x/asset/ft/keeper/before_send_test.go#L39)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't you add a test case for the wasm account?
</blockquote></details>

Done.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/633)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

___
*[`integration-tests/modules/assetft_test.go` line 3171 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYvcUQ2bAtMz_ykxvR:-NdZmOoN-niR2cGq4A0o:b-6lq0w1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/integration-tests/modules/assetft_test.go#L3171)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is the issuer who instantiated the contract
</blockquote></details>

if issuer instantiates no fees paid
If other acc does it fees are applied as usually

Do I understand it correctly 
Great test case !
___
*[`integration-tests/modules/assetft_test.go` line 3170 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdZlUSF-8CqtyAQ_hL6:-NdZlUSF-8CqtyAQ_hL7:b8e4qr5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bb7e24d43ac0f32d84853588bb87fdf2ea9d5c4c/integration-tests/modules/assetft_test.go#L3170)):*
> ```Go
> 	requireT.NoError(err)
> 	requireT.NotNil(balance.Balance)
> 	requireT.Equal(sdk.NewInt64Coin(denom, 400).String(), balance.Balance.String())
> ```

this pattern is repeated so many times in this test 
Could you move it to some helper func ?



_Code quote:_
```Go
	balance, err := bankClient.Balance(ctx,
		&banktypes.QueryBalanceRequest{
			Address: issuer.String(),
			Denom:   denom,
		})
	requireT.NoError(err)
	requireT.NotNil(balance.Balance)
	requireT.Equal(sdk.NewInt64Coin(denom, 400).String(), balance.Balance.String())
```
___
*[`x/asset/ft/keeper/before_send.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYw4rV1K0WUHeLFcMx:-NdZsvFY5p_5Hwgfhb0Z:b-gohn08) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/x/asset/ft/keeper/before_send.go#L161)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Here it doesn't matter.Later on, when store is updated we do sorting.
</blockquote></details>

I tend to agree with Dima
We can discuss on call if needed
___
*[`x/asset/ft/keeper/before_send.go` line 133 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdZn901BJKoKGQAkvyN:-NdZn901BJKoKGQAkvyO:bz8avv4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bb7e24d43ac0f32d84853588bb87fdf2ea9d5c4c/x/asset/ft/keeper/before_send.go#L133)):*
> ```Go
> 		return nil, nil //nolint:nilnil
> 	}
> 	// Since burning & send commission are not applied when sending to/from token issuer we can't simply apply original burn rate or send commission rate when bank multisend with issuer in inputs or outputs.
> ```

should we also add comment related to contract logic ?
___
*[`x/asset/ft/keeper/before_send.go` line 165 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdZsKbI43lDHMMcs_Bj:-NdZsKbI43lDHMMcs_Bk:boq8eas) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bb7e24d43ac0f32d84853588bb87fdf2ea9d5c4c/x/asset/ft/keeper/before_send.go#L165)):*
> ```Go
> 			continue
> 		}
> 		acc, err := sdk.AccAddressFromBech32(account)
> ```

I can see that inside this file we use both `sdk.AccAddressFromBech32` & `sdk.MustAccAddressFromBech32` for the same set of data

I think we should stick to a single approach and either treat accounts as valid bech 32 in both places or in none. I probably prefer to use `MustAccAddressFromBech32` 

I really like the way this func looked before when it didn't have second returned param err
___
*[`x/asset/ft/spec/README.md` line 51 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdZj7lABBkzawIt2Ute:-NdZj7lB1GQW0YzaSuXR:b-svq2db) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bb7e24d43ac0f32d84853588bb87fdf2ea9d5c4c/x/asset/ft/spec/README.md#L51)):*
> ```Markdown
> If IBC feature is enabled for the token then the burn rate is applied to outgoing IBC transfers.
> 
> Burn rate is never applied if smart contract is the sender.
> ```

also it seems like we should add this into `Feature interoperability table`

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/633)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @vertex451, and @wojtek-coreum)

___
*[`x/asset/ft/keeper/before_send.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYw4rV1K0WUHeLFcMx:-Nd_3GWnEkWh6j314gXj:brjis6v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/x/asset/ft/keeper/before_send.go#L161)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I tend to agree with Dima
We can discuss on call if needed
</blockquote></details>

I know it, and I see that there is no issue with the current code.  But probably we should do it for all maps? Let's discuss after the daily.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/633)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @vertex451, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 3171 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYvcUQ2bAtMz_ykxvR:-Nd_1wnu8H4m3zrTxHjd:bqy64wy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/integration-tests/modules/assetft_test.go#L3171)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

if issuer instantiates no fees paid
If other acc does it fees are applied as usually

Do I understand it correctly 
Great test case !
</blockquote></details>

yes, you do
___
*[`integration-tests/modules/assetft_test.go` line 3170 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdZlUSF-8CqtyAQ_hL6:-Nd_4Z631lHh3N2ZKP0v:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bb7e24d43ac0f32d84853588bb87fdf2ea9d5c4c/integration-tests/modules/assetft_test.go#L3170)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

this pattern is repeated so many times in this test 
Could you move it to some helper func ?
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/before_send.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYw4rV1K0WUHeLFcMx:-Nd_2IUUBX19-aT8N5WE:b-sowsh9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/x/asset/ft/keeper/before_send.go#L161)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I know it, and I see that there is no issue with the current code.  But probably we should do it for all maps? Let's discuss after the daily.
</blockquote></details>

Let's discuss because sorting here doesn't really make any sense. I take the initial values and replace them with another values. The sequence doesn't matter at all. It's like f(x) = 2*x, the sequence you take xes in can't affect the results.
___
*[`x/asset/ft/keeper/before_send.go` line 133 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdZn901BJKoKGQAkvyN:-Nd_5Ipp0hKIGjsYkg2C:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bb7e24d43ac0f32d84853588bb87fdf2ea9d5c4c/x/asset/ft/keeper/before_send.go#L133)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should we also add comment related to contract logic ?
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/before_send.go` line 165 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdZsKbI43lDHMMcs_Bj:-Nd_2bDbEMJm9ggcgg6X:b-y6uwd5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bb7e24d43ac0f32d84853588bb87fdf2ea9d5c4c/x/asset/ft/keeper/before_send.go#L165)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I can see that inside this file we use both `sdk.AccAddressFromBech32` & `sdk.MustAccAddressFromBech32` for the same set of data

I think we should stick to a single approach and either treat accounts as valid bech 32 in both places or in none. I probably prefer to use `MustAccAddressFromBech32` 

I really like the way this func looked before when it didn't have second returned param err
</blockquote></details>

But we also agreed long time ago to return error wherever we can instead of panicking.
___
*[`x/asset/ft/spec/README.md` line 51 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdZj7lABBkzawIt2Ute:-Nd_2t-D8sNqySVrGfe5:bb5kfwz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bb7e24d43ac0f32d84853588bb87fdf2ea9d5c4c/x/asset/ft/spec/README.md#L51)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

also it seems like we should add this into `Feature interoperability table`
</blockquote></details>

Another subcolumn for smart contract?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/633)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @miladz68, @vertex451, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYw4rV1K0WUHeLFcMx:-NddwcHe9mMj4ywFuCtg:bw1ja24) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/x/asset/ft/keeper/before_send.go#L161)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Let's discuss because sorting here doesn't really make any sense. I take the initial values and replace them with another values. The sequence doesn't matter at all. It's like f(x) = 2*x, the sequence you take xes in can't affect the results.
</blockquote></details>

So what do we do here?

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/633)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @vertex451, and @wojtek-coreum)

___
*[`x/asset/ft/keeper/before_send.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdYw4rV1K0WUHeLFcMx:-Nde5WRd2duWLUv0Ssz5:blanmv3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/28cdfa3263091b3d5135f88e974bd0717492487c/x/asset/ft/keeper/before_send.go#L161)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

So what do we do here?
</blockquote></details>

in this PR we can leave with it
But added ticket for future to inspect cosmos collections https://docs.cosmos.network/main/packages/collections

And then we will decide 
___
*[`x/asset/ft/keeper/before_send.go` line 165 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdZsKbI43lDHMMcs_Bj:-Nde5sI_59aYK01yooy4:b2wuhnp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bb7e24d43ac0f32d84853588bb87fdf2ea9d5c4c/x/asset/ft/keeper/before_send.go#L165)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But we also agreed long time ago to return error wherever we can instead of panicking.
</blockquote></details>

that is also true
IMO Then we should change to use `sdk.AccAddressFromBech32` in another place inside this file
___
*[`x/asset/ft/spec/README.md` line 51 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdZj7lABBkzawIt2Ute:-Nde61yU4cnq27lxI1N2:b312758) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bb7e24d43ac0f32d84853588bb87fdf2ea9d5c4c/x/asset/ft/spec/README.md#L51)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Another subcolumn for smart contract?
</blockquote></details>

I guess so :grimacing: 
I think adding it only to Extensions column is enough

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/633)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 51 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/633#-NdZj7lABBkzawIt2Ute:-NdeAlY4DoFj6hAZM11-:b-ese62c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bb7e24d43ac0f32d84853588bb87fdf2ea9d5c4c/x/asset/ft/spec/README.md#L51)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I guess so :grimacing: 
I think adding it only to Extensions column is enough 

</blockquote></details>

I'm not sure that you can cover it using the extensions only. But you can try :-)

**Review by ysv — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/633)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @vertex451)

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/633)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/633)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/633)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/633)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
