### PR TITLE
[WIP] Run CI pipeline on self-hosted runners

### PR DESCRIPTION
**Pull request by alinetskyi**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/608)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/608)* status: all files reviewed, 1 unresolved discussion (waiting on @alinetskyi, @dzmitryhil, @vertex451, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/608#-Nc6a95F3NTDF2OkAg7q:-Nc6a95F3NTDF2OkAg7r:b-vssvz8) (no related file):*
will this only one instance. 

___

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/608)* status: all files reviewed, 2 unresolved discussions (waiting on @alinetskyi, @dzmitryhil, and @vertex451)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/608#-NcRfNv49A0Z1E5qhIT6:-NcRfNv49A0Z1E5qhIT7:bsn9dxw) (no related file):*
Blocking this one since it is a test CI change by DevOps team
To fully finalize it we have to collaborate together

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/608)* status: all files reviewed, 3 unresolved discussions (waiting on @alinetskyi and @vertex451)

___
*[`.github/workflows/ci.yml` line 146 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/608#-NcgH5JGCdFRF-vFZpHx:-NcgH5JGCdFRF-vFZpHy:b-2m3wxa) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5e708bde391173ff085fcac61c32f7f3268e290f/.github/workflows/ci.yml#L146)):*
> ```YAML
>           key: ${{ runner.os }}-cache-smart-contracts-${{ hashFiles('./coreum/**/*.rs') }}
>         if: ${{ matrix.wasm-cache }}
>       - name: Remove previous znet
> ```

You need to specify a random (OS tmp) znet home for each run and clean it after the execution, otherwise, the execution will be synchronous for each step in the CI.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/608)* status: all files reviewed, 3 unresolved discussions (waiting on @alinetskyi and @vertex451)

___
*[`.github/workflows/ci.yml` line 146 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/608#-NcgH5JGCdFRF-vFZpHx:-NcgHvvF62vobDhrVtQk:b-9v2nsk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5e708bde391173ff085fcac61c32f7f3268e290f/.github/workflows/ci.yml#L146)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You need to specify a random (OS tmp) znet home for each run and clean it after the execution, otherwise, the execution will be synchronous for each step in the CI.
</blockquote></details>

Or won't even work.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/608)* status: all files reviewed, 3 unresolved discussions (waiting on @alinetskyi and @vertex451)

**Review by alinetskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/608)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @vertex451)

___
*[`.github/workflows/ci.yml` line 146 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/608#-NcgH5JGCdFRF-vFZpHx:-NcgJewr71eNNe4HulJ9:b-h4bmfq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5e708bde391173ff085fcac61c32f7f3268e290f/.github/workflows/ci.yml#L146)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Or won't even work.
</blockquote></details>

I do run a znet remove before executing everything

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/608)* status: all files reviewed, 3 unresolved discussions (waiting on @alinetskyi and @vertex451)

___
*[`.github/workflows/ci.yml` line 146 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/608#-NcgH5JGCdFRF-vFZpHx:-Ncw2W9T76ylDzNTtTlz:b-96eg8w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5e708bde391173ff085fcac61c32f7f3268e290f/.github/workflows/ci.yml#L146)):*
<details><summary><i>Previously, alinetskyi (Artem Linetskiy) wrote…</i></summary><blockquote>

I do run a znet remove before executing everything
</blockquote></details>

That's clear, but does it mean that we use one machine per job in CI ?

**Review by alinetskyi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/608)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @vertex451)

___
*[`.github/workflows/ci.yml` line 146 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/608#-NcgH5JGCdFRF-vFZpHx:-Ncw5jE45nakv0QBhnGQ:b2nign6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5e708bde391173ff085fcac61c32f7f3268e290f/.github/workflows/ci.yml#L146)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

That's clear, but does it mean that we use one machine per job in CI ?
</blockquote></details>

yes

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/608)* status: all files reviewed, 3 unresolved discussions (waiting on @alinetskyi and @vertex451)

___
*[`.github/workflows/ci.yml` line 146 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/608#-NcgH5JGCdFRF-vFZpHx:-Nd-WluI6CyaZGzp2Ulo:b-vvwkpn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5e708bde391173ff085fcac61c32f7f3268e290f/.github/workflows/ci.yml#L146)):*
<details><summary><i>Previously, alinetskyi (Artem Linetskiy) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Let's discuss after the daily, probably I'm out of scope :-)

**Comment by ysv** [comment]
Closing this PR for now
MIght continue working on it later

**Pull request closed without merging**
