### PR TITLE
added v2 upgrade handler

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/487)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/487)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/487#-NVEl4K1DIAf-LwCfsrX:-NVEl4K1DIAf-LwCfsrY:bnlp2ps) (no related file):*
Now we are upgrading from non-ibc to ibc. It means that some tricks had to be added to crust to prevent relayers from erroring out. But we should remove those tricks asap. But it means that at some point we need to coreum versions, both supporting ibc, to test upgrade. It means that we probably need to introduce fake upgrade like we did in the past for that purpose.

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/487#-NVElnghEOIjjJ1UlW3H:-NVElnghEOIjjJ1UlW3I:b-5pspb) (no related file):*
Does it mean that this PR might reintroduce upgrade test in CI? In that case coreum-ibc tests should be executed after upgrade. Now CI runs coreum-modules.

___
___
*[`integration-tests/upgrade/upgrade_test.go` line 33 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/487#-NVEks7VC-brmRVdgD92:-NVEks7VC-brmRVdgD93:b9vkksu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4d71a6b5aedc246994185b1b346b64eefe4cb5bb/integration-tests/upgrade/upgrade_test.go#L33)):*
> ```Go
> 
> 	// run upgrade v1
> 	upgradeV1(t)
> ```

IMO we should forget about it. Upgrade V1 has been released and it means it reached the end of its life. 
___
*[`integration-tests/upgrade/upgrade_test.go` line 137 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/487#-NVEm2EBD5P912K0YyCF:-NVEm2EBD5P912K0YyCG:b3f7u4w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/add16ab98479b796810910efa08df5891ca4b006/integration-tests/upgrade/upgrade_test.go#L137)):*
> ```Go
> 	assert.NotEqual(t, infoAfterRes.ApplicationVersion.Version, infoBeforeRes.ApplicationVersion.Version)
> 
> 	// Test the upgrade introduces in the v1 upgrade
> ```

Shouldn't we add some IBC checks now?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/487)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/487#-NVElnghEOIjjJ1UlW3H:-NVEwMEDEpO5PaU9soSc:b7nxzwq) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Does it mean that this PR might reintroduce upgrade test in CI? In that case coreum-ibc tests should be executed after upgrade. Now CI runs coreum-modules.
</blockquote></details>

Agree,  the IBC tests should be enabled after.

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/487#-NVEwbyY7ZVNLQZb4zy5:-NVEwbyY7ZVNLQZb4zy6:b-jn0q04) (no related file):*
Can we enable the upgrade now?

___
___
*[`integration-tests/upgrade/upgrade_test.go` line 33 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/487#-NVEks7VC-brmRVdgD92:-NVEwR7V7f0ZeZ8oGNat:bj28csf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4d71a6b5aedc246994185b1b346b64eefe4cb5bb/integration-tests/upgrade/upgrade_test.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

IMO we should forget about it. Upgrade V1 has been released and it means it reached the end of its life. 
</blockquote></details>

Let's discuss. today. 
___
*[`integration-tests/upgrade/upgrade_test.go` line 137 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/487#-NVEm2EBD5P912K0YyCF:-NVEwTc-8CWUroq3a3Gc:bqw1js2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/add16ab98479b796810910efa08df5891ca4b006/integration-tests/upgrade/upgrade_test.go#L137)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Shouldn't we add some IBC checks now?
</blockquote></details>

We can just run the IBC tests.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/487)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/487)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/487)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/487#-NVElnghEOIjjJ1UlW3H:-NVTCLKW9hD-id-MQnIO:b-4xumup) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree,  the IBC tests should be enabled after.
</blockquote></details>

Yes, but that comes after we merge both this and crust changes. 

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/487#-NVEl4K1DIAf-LwCfsrX:-NVTIpf064C9lqNS1D2s:bf3a8oc) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Now we are upgrading from non-ibc to ibc. It means that some tricks had to be added to crust to prevent relayers from erroring out. But we should remove those tricks asap. But it means that at some point we need to coreum versions, both supporting ibc, to test upgrade. It means that we probably need to introduce fake upgrade like we did in the past for that purpose.
</blockquote></details>

upgradev2 is going to serve the purpose of the fake upgrade. but it is not "fake" per se. 

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/487#-NVEwbyY7ZVNLQZb4zy5:-NVTCG9p8FA5qsGlCm0V:b-pqjwwg) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Can we enable the upgrade now?
</blockquote></details>

Yes, after we merge both this and crust changes. 

___
___
*[`integration-tests/upgrade/upgrade_test.go` line 137 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/487#-NVEm2EBD5P912K0YyCF:-NVTIk2h9qWNTW5Q_ogY:b1agiml) ([raw file](https://github.com/CoreumFoundation/coreum/blob/add16ab98479b796810910efa08df5891ca4b006/integration-tests/upgrade/upgrade_test.go#L137)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We can just run the IBC tests. 
</blockquote></details>

we can add one check here, like the ibc handler exitsts, or query ibc params.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/487)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

___
*[`integration-tests/upgrade/upgrade_test.go` line 137 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/487#-NVEm2EBD5P912K0YyCF:-NVTLELmCsDzM4LPpKqW:b-ijuf2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/add16ab98479b796810910efa08df5891ca4b006/integration-tests/upgrade/upgrade_test.go#L137)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we can add one check here, like the ibc handler exitsts, or query ibc params. 
</blockquote></details>

We run the IBC tests ufter it, which checks everything.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/487)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/487)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
