### PR TITLE
Handle burn rate in extensions

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_extension_test.go` line 1484 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-NxvEZtA9oELiZD53xWQ:-NxvEZtA9oELiZD53xWR:b-hlw8ej) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ba46a87e8a320fdbbe02a47e2a52d54d6cd011ef/integration-tests/modules/assetft_extension_test.go#L1484)):*
> ```Go
> 	denom := tokenIssuedEvents[0].Denom
> 
> 	// send from issuer to recipient1 (burn must not apply)
> ```

I am not seeing the check on the contract ! that the issuer (actually the admin) is exempted from the burn rate. then why is it working ? I assume the calculate rate function is not working as intended. I assume it will be fixed in the other PR that you have.
___
*[`integration-tests/modules/assetft_extension_test.go` line 1499 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-NxvEspD01yfNOv9jyUl:-NxvEspE7ztYzmFC43Sd:b3u9knt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ba46a87e8a320fdbbe02a47e2a52d54d6cd011ef/integration-tests/modules/assetft_extension_test.go#L1499)):*
> ```Go
> 	requireT.NoError(err)
> 	// assert that we don't receive events with empty amounts
> 	requireT.NotContains(txRes.RawLog, `{"key":"amount"}`)
> ```

you should filter the events by event type, this is not the correct way to do it. look at other tests to see how events are looked up. 
___
*[`integration-tests/modules/assetft_extension_test.go` line 1546 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-NxvFGn9-ZdQAJ6t4iie:-NxvFGn9-ZdQAJ6t4iif:b-demi3i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ba46a87e8a320fdbbe02a47e2a52d54d6cd011ef/integration-tests/modules/assetft_extension_test.go#L1546)):*
> ```Go
> 	})
> 
> 	// send from recipient2 to issuer (burn must not apply)
> ```

change issuer to admin, we now work with admins from now on. 
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 754 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-NxvHFYx2IywhEU_Fw5X:-NxvHFYx2IywhEU_Fw5Y:b5jaffx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ba46a87e8a320fdbbe02a47e2a52d54d6cd011ef/x/asset/ft/keeper/keeper_extension_test.go#L754)):*
> ```Go
> }
> 
> func TestKeeper_Extension_BurnRate_BankMultiSend(t *testing.T) {
> ```

I assume this is the exact copy from the other test right ? 
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 267 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-NxvE2fbDZLsRj5ZB2fG:-NxvE2fc5rvkkkvRnuMH:bmt6cpw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ba46a87e8a320fdbbe02a47e2a52d54d6cd011ef/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L267)):*
> ```XML
>         };
> 
>         burn_amount = Uint128::zero();
> ```

why are you changing burn_amount to zero ? should you just return here ?

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetft_extension_test.go` line 1484 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-NxvEZtA9oELiZD53xWQ:-NxvahfY-OScDSGM-PQ7:blpnefx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ba46a87e8a320fdbbe02a47e2a52d54d6cd011ef/integration-tests/modules/assetft_extension_test.go#L1484)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I am not seeing the check on the contract ! that the issuer (actually the admin) is exempted from the burn rate. then why is it working ? I assume the calculate rate function is not working as intended. I assume it will be fixed in the other PR that you have.
</blockquote></details>

Done. Yes, it is fixed after rebasing the branch
___
*[`integration-tests/modules/assetft_extension_test.go` line 1499 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-NxvEspD01yfNOv9jyUl:-Nxvm-V17Ch1Oty3rOyf:b-544xwc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ba46a87e8a320fdbbe02a47e2a52d54d6cd011ef/integration-tests/modules/assetft_extension_test.go#L1499)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you should filter the events by event type, this is not the correct way to do it. look at other tests to see how events are looked up.
</blockquote></details>

This test is copied from the assetft integration test. I'm not sure why it is decided to keep it this way, but there should be a reason
___
*[`integration-tests/modules/assetft_extension_test.go` line 1546 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-NxvFGn9-ZdQAJ6t4iie:-NxvmblUC6fTbVrfxD2Q:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ba46a87e8a320fdbbe02a47e2a52d54d6cd011ef/integration-tests/modules/assetft_extension_test.go#L1546)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

change issuer to admin, we now work with admins from now on.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 754 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-NxvHFYx2IywhEU_Fw5X:-Nxvmia18J1SJWo6nBs2:b78vgkr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ba46a87e8a320fdbbe02a47e2a52d54d6cd011ef/x/asset/ft/keeper/keeper_extension_test.go#L754)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I assume this is the exact copy from the other test right ?
</blockquote></details>

This test is copied from the assetft integration test but the extension is added
___
*[`x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs` line 267 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-NxvE2fbDZLsRj5ZB2fG:-NxvobPjBf1KpeRxJNDC:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ba46a87e8a320fdbbe02a47e2a52d54d6cd011ef/x/asset/ft/keeper/test-contracts/asset-extension/src/contract.rs#L267)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

why are you changing burn_amount to zero ? should you just return here ?
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-Ny-Tx-lDZyjNkapqOK8:-Ny-Tx-lDZyjNkapqOK9:bpcpptd) (no related file):*
Wait for my PR for sudo to be merged and make this PR against master. 

___

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-Ny-Tx-lDZyjNkapqOK8:-Ny06uk4AGxTgHsm9L88:b-896fix) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Wait for my PR for sudo to be merged and make this PR against master.
</blockquote></details>

Done.

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 725 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-Ny0G_7B00DEXfxq5SZV:-Ny0G_7B00DEXfxq5SZW:bpq0k3r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cbd34df9861aa72bd26f33dff4f682f77783c0c5/x/asset/ft/keeper/keeper_extension_test.go#L725)):*
> ```Go
> 
> 	ba.assertCoinDistribution(denom, map[*sdk.AccAddress]int64{
> 		&recipient:  392,
> ```

Could you please use `AmountIgnoreBurnRateTrigger` in the assertions when the extensions uses the rate as `initial - AmountIgnoreBurnRateTrigger`. In this way it is easier to validate (in both tests ). 
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 820 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-Ny0J1685A644YvtKCJv:-Ny0J1685A644YvtKCJw:b-nwnsl9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cbd34df9861aa72bd26f33dff4f682f77783c0c5/x/asset/ft/keeper/keeper_extension_test.go#L820)):*
> ```Go
> 	// create 2 recipient for every admin to allow for complex test cases
> 	recipients = append(recipients, sdk.AccAddress(secp256k1.GenPrivKey().PubKey().Address()))
> 	recipients = append(recipients, sdk.AccAddress(secp256k1.GenPrivKey().PubKey().Address()))
> ```

You can simply use and call it once. 
```
	recipients := lo.RepeatBy(4, func(index int) sdk.AccAddress {
		return sdk.AccAddress(secp256k1.GenPrivKey().PubKey().Address())
	})
```

**Review by miladz68 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 725 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-Ny0G_7B00DEXfxq5SZV:-Ny4rBru5yY-f0E-8wCO:byzhr56) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cbd34df9861aa72bd26f33dff4f682f77783c0c5/x/asset/ft/keeper/keeper_extension_test.go#L725)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you please use `AmountIgnoreBurnRateTrigger` in the assertions when the extensions uses the rate as `initial - AmountIgnoreBurnRateTrigger`. In this way it is easier to validate (in both tests ).
</blockquote></details>

I prefer to add comments to each line and keep the calculated number there. Comments added
___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 820 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-Ny0J1685A644YvtKCJv:-Ny4r2X77xxVbMfi-WAl:blofie4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cbd34df9861aa72bd26f33dff4f682f77783c0c5/x/asset/ft/keeper/keeper_extension_test.go#L820)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You can simply use and call it once. 
```
	recipients := lo.RepeatBy(4, func(index int) sdk.AccAddress {
		return sdk.AccAddress(secp256k1.GenPrivKey().PubKey().Address())
	})
```
</blockquote></details>

Thank you. Yeah, it's better

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 725 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-Ny0G_7B00DEXfxq5SZV:-Ny5CgD04MqUieWvA9Vr:b-5i1zm4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cbd34df9861aa72bd26f33dff4f682f77783c0c5/x/asset/ft/keeper/keeper_extension_test.go#L725)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I prefer to add comments to each line and keep the calculated number there. Comments added
</blockquote></details>

But why? If you already have those constants?

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`x/asset/ft/keeper/keeper_extension_test.go` line 725 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/834#-Ny0G_7B00DEXfxq5SZV:-Ny5DBqR41O4pNBFpIsN:b77z7ip) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cbd34df9861aa72bd26f33dff4f682f77783c0c5/x/asset/ft/keeper/keeper_extension_test.go#L725)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But why? If you already have those constants?
</blockquote></details>

Because there are more than one transfer in each test and it helps for each transfer to know the exact balance of accounts after previous transfer to check if the calculations are right

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/834)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
