### PR TITLE
allow more characters to token subunit

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/698)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/698)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/698)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`x/asset/ft/types/token.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/698#-Ni5Vj-VDnH0lpl3HL7l:-Ni5Vj-VDnH0lpl3HL7m:blt9jom) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7f8ee3b00800b0085a93496ca053aafc9619114f/x/asset/ft/types/token.go#L28)):*
> ```Go
> 	subunitRegex    *regexp.Regexp
> 
> 	symbolRegexStr = `^[a-zA-Z][a-zA-Z0-9-]{2,127}$`
> ```

I think we should allow same for symbol. WDYT ?
___
*[`x/asset/ft/types/token.go` line 101 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/698#-Ni5VcvU5NnLuUG6lXXa:-Ni5VcvU5NnLuUG6lXXb:bcftp27) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7f8ee3b00800b0085a93496ca053aafc9619114f/x/asset/ft/types/token.go#L101)):*
> ```Go
> 
> 	if strings.HasPrefix(strings.ToLower(subunit), ibctypes.DenomPrefix) {
> 		return sdkerrors.Wrapf(ErrInvalidInput, "subunit cannot start with ibc")
> ```

good point
Maybe `/` should still be blocked or it should be safe ?
___
*[`x/asset/ft/types/token_test.go` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/698#-Ni5VtHi9EgMsqcRjBnT:-Ni5VtHi9EgMsqcRjBnU:bwct5sh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7f8ee3b00800b0085a93496ca053aafc9619114f/x/asset/ft/types/token_test.go#L86)):*
> ```Go
> 		":abc",
> 		"ibc",
> 		"ibc/1",
> ```

nit:
I would put also real ibc example
e.g `ibc/F3166F4D31D6BA1EC6C9F5536F5DDDD4CC93DBA430F7419E7CDC41C497944A65`

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/698)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/types/token.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/698#-Ni5Vj-VDnH0lpl3HL7l:-Ni8N6GDBwAASbVnIeoA:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7f8ee3b00800b0085a93496ca053aafc9619114f/x/asset/ft/types/token.go#L28)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think we should allow same for symbol. WDYT ?
</blockquote></details>

Done.
___
*[`x/asset/ft/types/token.go` line 101 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/698#-Ni5VcvU5NnLuUG6lXXa:-Ni8Kc1FDY4ziHpGRcKb:b-fq9iom) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7f8ee3b00800b0085a93496ca053aafc9619114f/x/asset/ft/types/token.go#L101)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

good point
Maybe `/` should still be blocked or it should be safe ?
</blockquote></details>

I think it is safe. 
___
*[`x/asset/ft/types/token_test.go` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/698#-Ni5VtHi9EgMsqcRjBnT:-Ni8NJ7-5gjsb10fANIe:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7f8ee3b00800b0085a93496ca053aafc9619114f/x/asset/ft/types/token_test.go#L86)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit:
I would put also real ibc example
e.g `ibc/F3166F4D31D6BA1EC6C9F5536F5DDDD4CC93DBA430F7419E7CDC41C497944A65`
</blockquote></details>

Done

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/698)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/698)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
