### PR TITLE
Add unknown message metric.

### PR DESCRIPTION
**Pull request by dzmitryhil**
Example:
```
# HELP unknown_message unknown_message
# TYPE unknown_message counter
unknown_message{msg_name="/coreum.asset.ft.v1.MsgIssue"} 1
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/368)

### CODE REVIEW

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/368)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/368)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`x/deterministicgas/config.go` line 48 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/368#-NMoD6Bk7Z5g0YzBcFFX:-NMoD6Bk7Z5g0YzBcFFY:ba27kxk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/438ecafcc9977b9051942e770cf65a7e1efc12d4/x/deterministicgas/config.go#L48)):*
> ```Go
> 	cfg.gasByMsg = map[string]gasByMsgFunc{
> 		// asset/ft
> 		//MsgType(&assetfttypes.MsgIssue{}):               constantGasFunc(70000),
> ```

ok, but pls rollback it before merging to master)
___
*[`x/deterministicgas/config.go` line 152 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/368#-NMoDBx1Do749bLeHkko:-NMoDBx1Do749bLeHkkp:b3286dz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/438ecafcc9977b9051942e770cf65a7e1efc12d4/x/deterministicgas/config.go#L152)):*
> ```Go
> 	// In the future other approach could be to return third boolean parameter
> 	// identifying if message is known and report unknown messages to monitoring.
> 	reportUnknownMessageMetric(MsgType(msg))
> ```

are u going to add this to grafana in a next crust PR also ?
___
*[`x/deterministicgas/config.go` line 240 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/368#-NMoDSra-DF-n1GNLcQd:-NMoDSra-DF-n1GNLcQe:b-7s7ihs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/438ecafcc9977b9051942e770cf65a7e1efc12d4/x/deterministicgas/config.go#L240)):*
> ```Go
> 
> func reportUnknownMessageMetric(msgName string) {
> 	metrics.IncrCounterWithLabels([]string{"unknown_message"}, 1, []metrics.Label{
> ```

shouldn't it be `deterministic_gas_unknown_message` ?
Because in general this message is know but unknown only for determ gas module

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/368)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/368#-NN1-P6REzqbozpQcHqt:-NN1-P6REzqbozpQcHqu:bb9p1ir) (no related file):*
Is this PR really needed? We have unit test which verifies that all the messages are handled. So this condition is just impossible.

___

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/368)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/368)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`x/deterministicgas/config.go` line 152 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/368#-NMoDBx1Do749bLeHkko:-NN1Zai2286R6ibekBn6:bwb8ou6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/438ecafcc9977b9051942e770cf65a7e1efc12d4/x/deterministicgas/config.go#L152)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

No need to add it to the grafana, since such dashboard will be always empty. What I can do is to add it as allert. does it make sense?
</blockquote></details>

alert yes

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/368)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/368#-NN1-P6REzqbozpQcHqt:-NN3_EDV1tNbq1PfFp5o:b3hz6u5) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv what about that question?
</blockquote></details>

lets discuss after the daily
Adde to my notes

___

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/368)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/368)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
