### PR TITLE
Refactor integration tests to support 2 way IBC

### PR DESCRIPTION
**Pull request by dzmitryhil**
* Fetch address prefix, chainID, and denom form the chain VIA GRPC.
* Instantiate multiple chains for the testing (coreum, gaia).
* Update the testing utils to support the submission of the TXs using the sdk.Account with different prefixes.
* Integrate the faucet for the gaia chain.
* Refactor IBC helpers and add 2-way integration tests.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/486)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 11 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/486)* status: 11 of 26 files reviewed, 15 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVExN0qAZAk0nsM_633:-NVExN0qAZAk0nsM_634:b-712y66) (no related file):*
Now when parameters are queried, I think `pkg/client/NetworkConfig` might be simplified

___
___
*[`integration-tests/chain.go` line 67 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVEplPTAR4v1kmwRXKy:-NVEplPTAR4v1kmwRXKz:b-xqumm5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/chain.go#L67)):*
> ```Go
> 
> // ConvertToBech32Address converts the address to bech32 address string.
> func (c ChainContext) ConvertToBech32Address(address sdk.AccAddress) string {
> ```

Yay! My dream comes true :-). Does it mean that call to `coreumNetworkConfig.SetSDKConfig()` might be removed now from `init()`?
AFAIK the only reason we had to keep it was decoding/encoding addresses.
___
*[`integration-tests/chain.go` line 76 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVEqCJgDkTr8zTtuEnd:-NVEqCJgDkTr8zTtuEne:b-846hsx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/chain.go#L76)):*
> ```Go
> }
> 
> // ImportMnemonic imports the mnemonic into the ClientContext Keyring and return its address.
> ```

return -> returns
___
*[`integration-tests/gov.go` line 203 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVEuGzI-iLe6FHaZyAz:-NVEuGzI-iLe6FHaZyB-:bm82f99) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/gov.go#L203)):*
> ```Go
> 			WithBroadcastMode(flags.BroadcastSync)
> 
> 		res, err := client.BroadcastTx(ctx, clientCtx.WithFromAddress(staker), txf, msg)
> ```

Couldn't we use BroadcastTxWithSigner everywhere instead of `WithSimulateAndExecute(true)` + `client.BroadcastTx`?
___
*[`integration-tests/init.go` line 71 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVEv501C-r9oMBUKhKr:-NVEv501C-r9oMBUKhKs:bmk94hd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/init.go#L71)):*
> ```Go
> 	flag.StringVar(&coreumFundingMnemonic, "coreum-funding-mnemonic", "sad hobby filter tray ordinary gap half web cat hard call mystery describe member round trend friend beyond such clap frozen segment fan mistake", "Funding account mnemonic required by tests")
> 	flag.Var(&coreumStakerMnemonics, "coreum-staker-mnemonic", "Staker account mnemonics required by tests, supports multiple")
> 	flag.StringVar(&gaiaAddress, "gaia-address", "localhost:9080", "Address of gaia node started by znet")
> ```

Technically this args are required only by coreum-ibc but by putting them in common `init()` they will be everywhere
___
*[`integration-tests/init.go` line 125 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVEvHT3Dt60r9McFZq5:-NVEvHT3Dt60r9McFZq6:b4wglwb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/init.go#L125)):*
> ```Go
> 		coreumFundingMnemonic), coreumStakerMnemonics)
> 
> 	// ********** Gaia **********
> ```

I think it's not a good idea to do it inside common `init()` unconditionally. I have an idea that in the future we could start ibc environment only if ibc tests are requested to make everything faster in other CI steps. But this assumes that IBC apps are always there. IMO we could implement lazy loading. Whenever any test wants to use particular chain for the first time in the workflow, parameters are queried.
___
*[`integration-tests/init.go` line 135 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVEvlQy7vCryat80IWR:-NVEvlQy7vCryat80IWS:bl2e70u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/init.go#L135)):*
> ```Go
> 	gaiaChainSettings.GasPrice = sdk.ZeroDec()
> 	gaiaChainSettings.GasAdjustment = 1.3
> 	gaiaChainSettings.CoinType = 118 // gaia coin type
> ```

there is `sdk.CoinType` constant
___
*[`integration-tests/init.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVEvyqd39ghtjlQTD7x:-NVEvyqd39ghtjlQTD7y:byl1nch) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/init.go#L161)):*
> ```Go
> 
> // NewChainsTestingContext returns the configured chains and new context for the integration tests.
> func NewChainsTestingContext(t *testing.T) (context.Context, Chains) {
> ```

I think all the IBC tests should be considered unsafe
___
*[`integration-tests/tx.go` line 19 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVEtMfg6vOMJ3SWB0P6:-NVEtMfg6vOMJ3SWB0P7:bre4xbz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/tx.go#L19)):*
> ```Go
> // BroadcastTxWithSigner prepares the tx with the provided signer address and broadcasts it.
> // The main difference from the client.BroadcastTx is that this function uses the custom account addresses decoding with
> // the custom chain prefixes, which allows to execute transactions for different chains.
> ```

also I see it always uses gas estimation, ignoring the setting in tx factory
___
*[`integration-tests/ibc/ibc.go` line 29 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVExVR97IZL71Pi8oxH:-NVExVR97IZL71Pi8oxI:b-qbw9wg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/ibc/ibc.go#L29)):*
> ```Go
> type ChannelsConfig struct {
> 	CoreumToGaiaChannelID string
> 	GaiaToCoreumChannelID string
> ```

Let's add osmosis chain too. It is there so we should test that the chain and its relayer works all the time. So this structure should represent any channel, not only the one between gaia and coreum. It will save another refactoring later.
___
*[`integration-tests/ibc/ibc.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVExe8W0LAJSjHWkmFZ:-NVExe8W0LAJSjHWkmF_:b-mons9t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/ibc/ibc.go#L32)):*
> ```Go
> }
> 
> // Ready returns the if the config is fully ready.
> ```

returns the true
___
*[`integration-tests/ibc/ibc.go` line 34 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVExutI0PtGtxwRtmtD:-NVExutI0PtGtxwRtmtE:bnv16jb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/ibc/ibc.go#L34)):*
> ```Go
> // Ready returns the if the config is fully ready.
> func (c ChannelsConfig) Ready() bool {
> 	if c.CoreumToGaiaChannelID == "" || c.GaiaToCoreumChannelID == "" {
> ```

```
return c.CoreumToGaiaChannelID != "" && c.GaiaToCoreumChannelID != ""
```
___
*[`integration-tests/ibc/ibc.go` line 49 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVEyHmnCWdSzmehPNJD:-NVEyHmnCWdSzmehPNJE:bm20yv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/ibc/ibc.go#L49)):*
> ```Go
> 
> 	var ibcConfig ChannelsConfig
> 	err := retry.Do(ctx, time.Second, func() error {
> ```

this ctx should contain a timeout to not create infinitely running test in case of problems
___
*[`integration-tests/ibc/ibc.go` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVEyUqGEZYXbi0kkwmP:-NVEyUqGEZYXbi0kkwmQ:b-z3l7bi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/ibc/ibc.go#L70)):*
> ```Go
> 		}
> 
> 		gaiaChannelsRes, err := gaiaIBCChannelClient.Channels(ctx, &ibcchanneltypes.QueryChannelsRequest{})
> ```

this code is copied, it could be put in a common function, called twice here
___
*[`integration-tests/ibc/ibc.go` line 94 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVEyott7l5RGC2YXK5q:-NVEyott7l5RGC2YXK5r:b-d24afb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/ibc/ibc.go#L94)):*
> ```Go
> 		}
> 
> 		return retry.Retryable(errors.New("waiting for channels to open"))
> ```

if the first channel is retrieved by the second one is not ready yet, the first blockchain will be queried again in the next loop run

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-:-NVTX14OBChNn6yRXZ1b:bnfp4nl)* status: all files reviewed, 15 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 14 of 26 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/486)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/init.go` line 125 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVEvHT3Dt60r9McFZq5:-NVTtiN-4osqjLYGtlS5:b-7vx1b3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/init.go#L125)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I undersand, but we had a call with the @ysv and @miladz68 about it and decided to init it in the common init func. 
</blockquote></details>

It's ok for now but let's discuss lazy loading once @ysv is back
___
*[`integration-tests/init.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVEvyqd39ghtjlQTD7x:-NVTu8gz-6RX5EXnlHUa:b-vgkvjj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/init.go#L161)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree, done.
</blockquote></details>

Non-blocking: Maybe we could remove `NewChainsTestingContext` now and use `NewCoreumTestingContext` (and rename it) everywhere just passing skipUnsafe=true in IBC tests. I fing it to be more elegant rather than creating spearate function just for this purpose.

Or maybe we could remove those functions to `NewSafeTestingContext` and `NewUnsafeTestingContext` and remove `skipUnsafe` argument.
___
*[`integration-tests/ibc/ibc.go` line 29 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVExVR97IZL71Pi8oxH:-NVTuoGzBm8dtSXGqVh4:b-32ik0j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/ibc/ibc.go#L29)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not for that PR, I'll add it to the burn/send rate to test it. For this PR we don't need it.
</blockquote></details>

I still think basic IBC test should be done here for osmosis too. @miladz68 @ysv     
___
*[`integration-tests/ibc/ibc.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVExe8W0LAJSjHWkmFZ:-NVTufrQBI4GgEdqMqtV:brbhylx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/ibc/ibc.go#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

"if" is still required
___
*[`integration-tests/ibc/ibc.go` line 37 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVTv9vM2j0fvdI9GGas:-NVTv9vM2j0fvdI9GGat:bvyo9q5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9e15c4182aa9bd8f5d08c1382253556b474b6e8/integration-tests/ibc/ibc.go#L37)):*
> ```Go
> }
> 
> // AwaitForIBCConfig await for the IBC channels to be opened and returns them.
> ```

await -> awaits
___
*[`integration-tests/ibc/transfer_test.go` line 47 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVTw8jj2xDQL5pQPReB:-NVTw8jj2xDQL5pQPReC:b-gl8t1s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9e15c4182aa9bd8f5d08c1382253556b474b6e8/integration-tests/ibc/transfer_test.go#L47)):*
> ```Go
> 	requireT.NoError(err)
> 	assert.EqualValues(t, sendToGaiaCoin.Amount.String(), gaiaRecipientBalance.Amount.String())
> 	t.Logf("Reveiced %s on gaia", gaiaRecipientBalance.String())
> ```

Reveiced -> Received
___
*[`integration-tests/ibc/transfer_test.go` line 57 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVTw6441BjNi-FIFqkX:-NVTw6441BjNi-FIFqkY:b-gl8t1s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9e15c4182aa9bd8f5d08c1382253556b474b6e8/integration-tests/ibc/transfer_test.go#L57)):*
> ```Go
> 	requireT.NoError(err)
> 	assert.EqualValues(t, gaiaRecipientBalance.Amount.String(), coreumRecipientBalance.Amount.String())
> 	t.Logf("Reveiced %s on coreum", coreumRecipientBalance.String())
> ```

Reveiced -> Received
___
*[`integration-tests/ibc/transfer_test.go` line 94 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVTwekd9q3rY4ukAVOm:-NVTweke2CN_u_f8OESl:b-gl8t1s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9e15c4182aa9bd8f5d08c1382253556b474b6e8/integration-tests/ibc/transfer_test.go#L94)):*
> ```Go
> 	requireT.NoError(err)
> 	assert.EqualValues(t, sendToCoreumCoin.Amount.String(), coreumRecipientBalance.Amount.String())
> 	t.Logf("Reveiced %s on coreum", coreumRecipientBalance.String())
> ```

Reveiced -> Received
___
*[`integration-tests/ibc/transfer_test.go` line 104 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVTwk923xhAiIzTN1sX:-NVTwk923xhAiIzTN1sY:b-gl8t1s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9e15c4182aa9bd8f5d08c1382253556b474b6e8/integration-tests/ibc/transfer_test.go#L104)):*
> ```Go
> 	requireT.NoError(err)
> 	assert.EqualValues(t, gaiaRecipientBalance.Amount.String(), coreumRecipientBalance.Amount.String())
> 	t.Logf("Reveiced %s on gaia", coreumRecipientBalance.String())
> ```

Reveiced -> Received

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/486)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/init.go` line 125 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVEvHT3Dt60r9McFZq5:-NVU-ivKDz4_aHEmxYz6:bqog7zb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/init.go#L125)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It's ok for now but let's discuss lazy loading once @ysv is back
</blockquote></details>

Agree.
___
*[`integration-tests/init.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVEvyqd39ghtjlQTD7x:-NVU-y8Q8MTq29UfIZiU:b-opl0ru) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/init.go#L161)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Non-blocking: Maybe we could remove `NewChainsTestingContext` now and use `NewCoreumTestingContext` (and rename it) everywhere just passing skipUnsafe=true in IBC tests. I fing it to be more elegant rather than creating spearate function just for this purpose.

Or maybe we could remove those functions to `NewSafeTestingContext` and `NewUnsafeTestingContext` and remove `skipUnsafe` argument.
</blockquote></details>

We can't remove `NewChainsTestingContext` this func returns all chain, the `NewCoreumTestingContext` only coreum. But I've added the flag for the `NewChainsTestingContext` to show that it's there.
___
*[`integration-tests/ibc/ibc.go` line 29 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVExVR97IZL71Pi8oxH:-NVU0rCP3KxkP63JdN4A:b-vdvlkq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/ibc/ibc.go#L29)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I still think basic IBC test should be done here for osmosis too. @miladz68 @ysv     
</blockquote></details>

Why? I don't need it for my task, why should it be included than? Here we test the IBC integration of the coreum app, not the crust integration. So we need to include it only when we need it.
___
*[`integration-tests/ibc/ibc.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVExe8W0LAJSjHWkmFZ:-NVU168V3Yyg5-i2P3Eg:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/ibc/ibc.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

"if" is still required
</blockquote></details>

Done.
___
*[`integration-tests/ibc/ibc.go` line 37 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVTv9vM2j0fvdI9GGas:-NVU18lNCjzNVeILO7jg:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9e15c4182aa9bd8f5d08c1382253556b474b6e8/integration-tests/ibc/ibc.go#L37)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

await -> awaits
</blockquote></details>

Done.
___
*[`integration-tests/ibc/transfer_test.go` line 47 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVTw8jj2xDQL5pQPReB:-NVU1EhWAsL2zxozOJgE:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9e15c4182aa9bd8f5d08c1382253556b474b6e8/integration-tests/ibc/transfer_test.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Reveiced -> Received
</blockquote></details>

Done.
___
*[`integration-tests/ibc/transfer_test.go` line 57 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVTw6441BjNi-FIFqkX:-NVU1Eu1AMtvGn37vxsb:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9e15c4182aa9bd8f5d08c1382253556b474b6e8/integration-tests/ibc/transfer_test.go#L57)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Reveiced -> Received
</blockquote></details>

Done.
___
*[`integration-tests/ibc/transfer_test.go` line 94 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVTwekd9q3rY4ukAVOm:-NVU1FKF65nt44LlfjFZ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9e15c4182aa9bd8f5d08c1382253556b474b6e8/integration-tests/ibc/transfer_test.go#L94)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Reveiced -> Received
</blockquote></details>

Done.
___
*[`integration-tests/ibc/transfer_test.go` line 104 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVTwk923xhAiIzTN1sX:-NVU1FdrBV0nzotyzblG:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9e15c4182aa9bd8f5d08c1382253556b474b6e8/integration-tests/ibc/transfer_test.go#L104)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Reveiced -> Received
</blockquote></details>

Done.

**Review by miladz68 — DISMISSED** [review]
> Reviewed 4 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/486)* status: all files reviewed, 7 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/486)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

___
*[`integration-tests/ibc/ibc.go` line 29 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVExVR97IZL71Pi8oxH:-NVU1zk-632okdn5P8rn:b-4u0l30) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/ibc/ibc.go#L29)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why? I don't need it for my task, why should it be included than? Here we test the IBC integration of the coreum app, not the crust integration. So we need to include it only when we need it.
</blockquote></details>

My point is that you refactored the code in the way where only gaia is supported by definition. It's not possible to integrate osmosis later just by adding copule of simple lines of code. It will have to be refactored completely again. IMO it should be done in the universal way where another pair of channels might be added easily later. And once it is done, integrating osmosis is so trivial that it might be done in this PR.

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/486)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/486)* status: 21 of 28 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/ibc.go` line 29 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVExVR97IZL71Pi8oxH:-NVUNQPd-aw66TPL7rSB:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8162f65db2ab511619c8ad7a4623fc40a31e0a92/integration-tests/ibc/ibc.go#L29)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

My point is that you refactored the code in the way where only gaia is supported by definition. It's not possible to integrate osmosis later just by adding copule of simple lines of code. It will have to be refactored completely again. IMO it should be done in the universal way where another pair of channels might be added easily later. And once it is done, integrating osmosis is so trivial that it might be done in this PR.
</blockquote></details>

Updated.

**Review by miladz68 — APPROVED** [review]
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/486)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/486)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/chain.go` line 263 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVUWSZuDGapTNpawSdP:-NVUXUChBJ4KrcXK9M4i:blkt1il) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c246032904550a81d1f8e8fa1b6e9a92b6c66d65/integration-tests/chain.go#L263)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

if channel does not exist yet, are you sure that err is nil instead of sth like ErrNotFound (in which case it should retry)?
</blockquote></details>

Yes no errors will be there.
___
*[`integration-tests/chain.go` line 273 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/486#-NVUWB474M5jLNpr3_zq:-NVU_MZKBIFBkOQB1ixc:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c246032904550a81d1f8e8fa1b6e9a92b6c66d65/integration-tests/chain.go#L273)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

shouldn't `return nil` be inside this `if`?
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/486)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
