### PR TITLE
Add missing testnet configuration (seed nodes & genesis txs & balances)

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/342)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/342)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/network.go` line 96 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/342#-NLdvqQRDZBpVk2xVMXX:-NLdvqQRDZBpVk2xVMXY:b2grq0w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fe7a0db220c8cd79ce463131ef12a082105b3c2f/pkg/config/network.go#L96)):*
> ```Go
> 	// where 100_000 is balances of each of 4 initial validator stakers.
> 	testFoundationInitialBalance := sdk.NewCoins(sdk.NewCoin(constant.DenomDev, sdk.NewInt(124_900_000_000_000)))
> 	testStakerValidatorBalance := sdk.NewCoins(sdk.NewCoin(constant.DenomDev, sdk.NewInt(100_000_000_000)))
> ```

Do we really need 100k here?

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/342)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/genesis/gentx/coreum-testnet-1/create-validator-validator-earth-signed.json` line 27 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/342#-NLe7sRAA8HzWh8bN8U_:-NLe7sRAA8HzWh8bN8Ua:b-empndv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fe7a0db220c8cd79ce463131ef12a082105b3c2f/pkg/config/genesis/gentx/coreum-testnet-1/create-validator-validator-earth-signed.json#L27)):*
> ```JSON
>         "value": {
>           "denom": "utestcore",
>           "amount": "20000000000"
> ```

non-blocking
we should take more than 20K (min_self_delegation), so it will be easier to restore the validator once it is jailed for any reason.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/342)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`pkg/config/network.go` line 96 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/342#-NLdvqQRDZBpVk2xVMXX:-NLf0rFA5hUiQZx6cFj8:b-ti2mjv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fe7a0db220c8cd79ce463131ef12a082105b3c2f/pkg/config/network.go#L96)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do we really need 100k here?
</blockquote></details>


thought that with 100k numbers will be beatufil but they are not with neither 100 nor 50k. 
I agree changed to 50k
___
*[`pkg/config/genesis/gentx/coreum-testnet-1/create-validator-validator-earth-signed.json` line 27 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/342#-NLe7sRAA8HzWh8bN8U_:-NLf3b4_88a93UbHFPSL:b1yuun) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fe7a0db220c8cd79ce463131ef12a082105b3c2f/pkg/config/genesis/gentx/coreum-testnet-1/create-validator-validator-earth-signed.json#L27)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

non-blocking
we should take more than 20K (min_self_delegation), so it will be easier to restore the validator once it is jailed for any reason. 
</blockquote></details>

should be blocking actually )
it is very reasonable comment. Increased to 30k

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/342)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/342)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
