### PR TITLE
GRPC client for the client package.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/378)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/378)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/chain.go` line 177 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/378#-NNbTr5gAe77caqEbz_V:-NNbTr5gAe77caqEbz_W:b-gh84vh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7059b5ce2a1ca24a195d32c1a2c90b7e8006ecfb/integration-tests/chain.go#L177)):*
> ```Go
> 
> 	// TODO(dhil) remove switch once crust is updated
> 	if strings.HasPrefix(cfg.GRPCAddress, "tcp") {
> ```

maybe instead of using `tcp` to differentiate the 2 different endpoints, we should use separate flags ?
___
*[`integration-tests/init.go` line 48 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/378#-NNegUKX2o04AnnHHGfj:-NNegUKYBDdLOrFZ01an:b-irfhbb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7059b5ce2a1ca24a195d32c1a2c90b7e8006ecfb/integration-tests/init.go#L48)):*
> ```Go
> 	)
> 
> 	flag.StringVar(&coredAddress, "cored-address", "localhost:9090", "Address of cored node started by znet")
> ```

I think we can introduce rpc-address and grpc-address and then later remove this `cored-address` flag.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/378)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/378#-NNfzgsh-ztXqqw-IKpY:-NNfzgsiBqRiQkF43qUQ:bg8p1cp) (no related file):*
Shouldn't we test both rpc and grpc endpoints?

___

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/378)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/378#-NNfzgsh-ztXqqw-IKpY:-NNg8_8Y01LhIooghO3O:bim6mpz) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I've tested them locally by running the tests, what additionally do you propose? 
I thought about the round-robin balancing for the transactions, but that might lead to not reproducible tests, which is very bad.
</blockquote></details>

I'm just thinking about single test sending bank send over rpc. It would be also possible to run the full test suite, once using grpc and once using rpc but it would be an overkill IMO.

___

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/378)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/378)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/378)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
