### PR TITLE
NFT issuer does not need whitelisting

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/414)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/414)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/414)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/414)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/414)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`x/asset/nft/keeper/keeper.go` line 469 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/414#-NPSOLYD87FmNU_J6Euq:-NPSOLYD87FmNU_J6Eur:b-h6p5xf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0a5e33a7fdb1d9f0ca9533922f32a63ade5f783a/x/asset/nft/keeper/keeper.go#L469)):*
> ```Go
> 	}
> 
> 	if classDefinition.Issuer == account.String() {
> ```

IMO this check should be moved to `CheckFeatureAllowed` method
I think it is implemented in the same way in FT

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/414)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 469 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/414#-NPSOLYD87FmNU_J6Euq:-NPSRT-YA653Gk9pBa1n:b1on6du) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0a5e33a7fdb1d9f0ca9533922f32a63ade5f783a/x/asset/nft/keeper/keeper.go#L469)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO this check should be moved to `CheckFeatureAllowed` method
I think it is implemented in the same way in FT
</blockquote></details>

Nope, in FT it done in `SetWhitelistedBalance`:

```go
	if def.IsIssuer(addr) {
		return sdkerrors.Wrap(sdkerrors.ErrUnauthorized, "issuer's balance can't be whitelisted")
	}
```

I followed that convention in NFT

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/414)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/414)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`x/asset/nft/keeper/keeper.go` line 469 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/414#-NPSOLYD87FmNU_J6Euq:-NPX5Hnn00WJ3QA325p6:b-p7hjmu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1d640b75ef1c7d02d93fe9928ae46d4dee89b0d7/x/asset/nft/keeper/keeper.go#L469)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Nope, in FT it done in `SetWhitelistedBalance`:

```go
	if def.IsIssuer(addr) {
		return sdkerrors.Wrap(sdkerrors.ErrUnauthorized, "issuer's balance can't be whitelisted")
	}
```

I followed that convention in NFT
</blockquote></details>

Then IMO it is logical to move this logic to CheckFeature allowed in both FT & NFT (freezing & whitelisting) to have centralised place controlling permissions of these features

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/414)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 469 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/414#-NPSOLYD87FmNU_J6Euq:-NPvVK3e9xe-GVc07yS2:bv37vk5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1d640b75ef1c7d02d93fe9928ae46d4dee89b0d7/x/asset/nft/keeper/keeper.go#L469)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree, but we have similar check in the `Is Feature Allowed` so probably that func would be better.
</blockquote></details>

This is not possible. `CheckFeatureAllowed` is called by all the features and it acts based on issuer/sender account only. Here the decision is made based on the `account` address. Passing this address to that function doesn't make sense because it is specific to whitelisting only.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/414)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`x/asset/nft/keeper/keeper.go` line 469 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/414#-NPSOLYD87FmNU_J6Euq:-NPwCMXT8RuhQnyL-ng2:be5cnfb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1d640b75ef1c7d02d93fe9928ae46d4dee89b0d7/x/asset/nft/keeper/keeper.go#L469)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is not possible. `CheckFeatureAllowed` is called by all the features and it acts based on issuer/sender account only. Here the decision is made based on the `account` address. Passing this address to that function doesn't make sense because it is specific to whitelisting only.
</blockquote></details>

I see what you mean 
Decission in usually based on sender but here it should be based on destination

ok resolving it
___
*[`x/asset/nft/types/token.go` line 120 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/414#-NPwCjOP2EwTBUBYp8g6:-NPwCjOP2EwTBUBYp8g7:b-w4e0xa) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bbffdfed853e3d0efcbc5dc68f483cdab175b57a/x/asset/nft/types/token.go#L120)):*
> ```Go
> // CheckFeatureAllowed returns error if feature isn't allowed for the address.
> func (nftd ClassDefinition) CheckFeatureAllowed(addr sdk.AccAddress, feature ClassFeature) error {
> 	switch {
> ```

I personally prefer if version

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/414)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

___
*[`x/asset/nft/types/token.go` line 120 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/414#-NPwCjOP2EwTBUBYp8g6:-NQ--jhO-BCGmPv3Btvf:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7d656c2a4bb2653eafc5e3a741b82ddbbe8690c7/x/asset/nft/types/token.go#L120)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I personally prefer if version 
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/414)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/414)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
