### PR TITLE
Add TokenUpgradeStatuses query.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/asset/ft/keeper/token_upgrade.go` line 71 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/570#-N_E2mMaC4csqpvEThBT:-N_E2mMb3HSVn7OUYplL:b-whyykq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fc61e83808043885cd5e7af22aaebe6dfda5b4eb/x/asset/ft/keeper/token_upgrade.go#L71)):*
> ```Go
> 	bz := ctx.KVStore(k.storeKey).Get(types.CreateTokenUpgradeStatusesKey(denom))
> 	if bz == nil {
> 		return types.TokenUpgradeStatuses{}, sdkerrors.Wrapf(types.ErrTokenNotFound, "no token upgrade statuses for denom: %s", denom)
> ```

I think this query should just return object with empty fields inside in this case:
```
{
  v1: {}
}
```
no ?
I don't think it is really error if user queries for it
Also, we follow logic of bank balance query when it returns 0 even though balance doesn't exist

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/upgrade/ft_test.go` line 543 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/570#-N_ECc_t3CCG5BOwQdaJ:-N_ECc_t3CCG5BOwQdaK:b-sh2qwe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fc61e83808043885cd5e7af22aaebe6dfda5b4eb/integration-tests/upgrade/ft_test.go#L543)):*
> ```Go
> 	v1UpgradeStatus := tokenUpgradeStatusesRes.Statuses.V1
> 	requireT.False(v1UpgradeStatus.IbcEnabled)
> 	requireT.Equal(v1UpgradeStatus.StartTime, v1UpgradeStatus.EndTime)
> ```

you may also check that those values are greater than current time - one hour
___
*[`x/asset/ft/keeper/token_upgrade.go` line 71 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/570#-N_E2mMaC4csqpvEThBT:-N_EBldw9GqnwGv_itCs:bc2mdg7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fc61e83808043885cd5e7af22aaebe6dfda5b4eb/x/asset/ft/keeper/token_upgrade.go#L71)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think this query should just return object with empty fields inside in this case:
```
{
  v1: {}
}
```
no ?
I don't think it is really error if user queries for it
Also, we follow logic of bank balance query when it returns 0 even though balance doesn't exist
</blockquote></details>

agree, upgrade status of non-upgraded token is known so it should not be an error
___
*[`x/asset/ft/keeper/token_upgradev1.go` line 38 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/570#-N_EC3lKASN4ewVZArqs:-N_EC3lKASN4ewVZArqt:bf06csf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fc61e83808043885cd5e7af22aaebe6dfda5b4eb/x/asset/ft/keeper/token_upgradev1.go#L38)):*
> ```Go
> 	}
> 
> 	tokenUpgradeStatuses := types.TokenUpgradeStatuses{
> ```

Please put a comment that you don't read previous status because this is the first and the only existing upgrade at the moment. Otherwise I'm pretty sure someone will copy this code when working on v2

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/upgrade/ft_test.go` line 543 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/570#-N_ECc_t3CCG5BOwQdaJ:-N_EExwR3znmgMkQSuQY:b-waxr2s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fc61e83808043885cd5e7af22aaebe6dfda5b4eb/integration-tests/upgrade/ft_test.go#L543)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you may also check that those values are greater than current time - one hour
</blockquote></details>

But those values are just a bit greater than the current, we have the current block time in case ibc_enabled is false.
___
*[`x/asset/ft/keeper/token_upgrade.go` line 71 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/570#-N_E2mMaC4csqpvEThBT:-N_EE0McEQcpGblx4_Rq:bgckuqw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fc61e83808043885cd5e7af22aaebe6dfda5b4eb/x/asset/ft/keeper/token_upgrade.go#L71)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

agree, upgrade status of non-upgraded token is known so it should not be an error
</blockquote></details>

OK, updated.
___
*[`x/asset/ft/keeper/token_upgradev1.go` line 38 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/570#-N_EC3lKASN4ewVZArqs:-N_EEIokEFOSuZnb0oU_:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fc61e83808043885cd5e7af22aaebe6dfda5b4eb/x/asset/ft/keeper/token_upgradev1.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please put a comment that you don't read previous status because this is the first and the only existing upgrade at the moment. Otherwise I'm pretty sure someone will copy this code when working on v2
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/upgrade/ft_test.go` line 543 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/570#-N_ECc_t3CCG5BOwQdaJ:-N_EJcn28n6zStKc7f2x:b-bouc4p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fc61e83808043885cd5e7af22aaebe6dfda5b4eb/integration-tests/upgrade/ft_test.go#L543)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But those values are just a bit greater than the current, we have the current block time in case ibc_enabled is false.
</blockquote></details>

I mean you don't check here that those values are set. You also can't know the precise time of the block. But you ma check that the value is greater than some reasonable time.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/upgrade/ft_test.go` line 543 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/570#-N_ECc_t3CCG5BOwQdaJ:-N_EM_sl8K_9EK7o2ERE:b-e8mcu1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fc61e83808043885cd5e7af22aaebe6dfda5b4eb/integration-tests/upgrade/ft_test.go#L543)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I mean you don't check here that those values are set. You also can't know the precise time of the block. But you ma check that the value is greater than some reasonable time.
</blockquote></details>

But I can check that the time is greater or equal to the current time, but not sure that this is important, since we have that test in the unit tests.

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 23 of 29 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/570#-N_IKw5U7BUgVkG64X6y:-N_IKw5U7BUgVkG64X6z:biv1qe1) (no related file):*
Fix the PR title

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: 29 of 31 files reviewed, 2 unresolved discussions (waiting on @silverspase)

___
*[`x/deterministicgas/types/gas.go` line 16 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/570#-N_J811g7Bs8a20WVtDQ:-N_J811g7Bs8a20WVtDR:bmjd720) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8fa9fd6e9b05f3a5ea6cef39846aa930236d1890/x/deterministicgas/types/gas.go#L16)):*
> ```Go
> )
> 
> const fuseGasMultiplier = 100
> ```

@miladz68 @wojtek-coreum @ysv 
Faced a tricky issue today and have spent a lot of time on it :-)
I changed the logic for `MsgUpgradeTokenV1` as a result the real gas for it became about 5 times more from 5000 to 25000 (or prev was invalid no matter here), anyways as a result I started getting out of gas error for the message estimation.
I've fixed the message gas and updated fuseGasMultiplier to 100. Because now if our deterministic gas estimation (same as deterministic_gas_factor) is 5 times less than real gas, the transaction fails, and as we know we already have some transactions with a factor close to 4. So 100 should give fewer potential errors. 
Better to discuss it, and probably make it event static or unlimited.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @silverspase)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: 31 of 32 files reviewed, 2 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/570#-N_IKw5U7BUgVkG64X6y:-N_JUTDH23OCuBA-ZU9u:b-896fix) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Fix the PR title
</blockquote></details>

Done.

___

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/570)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase)

**Pull request merged**
