### PR TITLE
Use SDK error wrappers

### PR DESCRIPTION
**Pull request by vertex451**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/567)

I have taken care of one package to check if I am going the right direction.

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/567)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/balance_store.go` line 51 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/567#-N_4-5q_1EIceNUq7bHk:-N_4-5q_1EIceNUq7bHl:bxztj59) ([raw file](https://github.com/CoreumFoundation/coreum/blob/019a209997c64190d2bc966262b506f4d8c2bc5e/x/asset/ft/keeper/balance_store.go#L51)):*
> ```Go
> 	)
> 	if err != nil {
> 		return nil, nil, sdkerrors.Wrap(types.ErrInvalidInput, fmt.Sprintf("failed to paginate: %s", err))
> ```

use `sdkerrors.Wrapf`, so you won't need to import `fmt` package to format your message. 
same goes for all the changes lines.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/567)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/567#-N_82X8X5M1zJSsFBXR2:-N_82X8X5M1zJSsFBXR3:bjo4w03) (no related file):*
Direction is godd but change PR title to sth better like "Use SDK error wrappers"

___
___
*[`x/asset/ft/keeper/balance_store.go` line 50 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/567#-N_82P6r4y3v0ajw1fpQ:-N_82P6s1_uq0bVvOyxb:b-3aq6x0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/99cffa6331c06acfb96103a292ff145260fa72c2/x/asset/ft/keeper/balance_store.go#L50)):*
> ```Go
> 	)
> 	if err != nil {
> 		return nil, nil, sdkerrors.Wrapf(types.ErrInvalidInput, "failed to paginate: %s", err)
> ```

The gneric `error` interface does not offer `String()` method so I believe you need to use `err.Error()`
___
*[`x/asset/ft/keeper/keeper.go` line 342 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/567#-N_824i1CqWDh3ce3z7u:-N_824i1CqWDh3ce3z7v:b5wdwc7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/99cffa6331c06acfb96103a292ff145260fa72c2/x/asset/ft/keeper/keeper.go#L342)):*
> ```Go
> 	})
> 	if err != nil {
> 		return sdkerrors.Wrapf(sdkerrors.ErrInvalidRequest, "can't emit EventFrozenAmountChanged event: %v", err)
> ```

Use `%s` in such cases,

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/567)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/567)* status: all files reviewed, 4 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 226 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/567#-N_8p31c2kzOVwNzBsfG:-N_8p31c2kzOVwNzBsfH:b-7pnbzn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6746d1db35e186a5d7d26bcc4c632bb3aae73b8d/x/asset/ft/keeper/keeper.go#L226)):*
> ```Go
> 		SendCommissionRate: settings.SendCommissionRate,
> 	}); err != nil {
> 		return "", sdkerrors.Wrapf(sdkerrors.ErrInvalidRequest, "can't emit EventIssued event: %s", err)
> ```

IMO the error is wrong here and in other places with `EmitTypedEvent` as well. 
Better to use `types.ErrInvalidState` here and in other places as well.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/567)* status: all files reviewed, 4 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/567)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/567)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Pull request merged**
