### PR TITLE
Add more CLI methods to DEX and FT

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description
Add CLI to DEX to cancel orders by denom, to query the account denom orders count and add CLI to asset FT to update the whitelisted denoms

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/994)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/994)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/994)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/994)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`x/asset/ft/client/cli/tx_test.go` line 704 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/994#-O8qGgfS5kIe6bLV2-nX:-O8qGgfS5kIe6bLV2-nY:b3kr7jq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/36550baf6b28cdc3a2ef832267401ff090030720/x/asset/ft/client/cli/tx_test.go#L704)):*
> ```Go
> 
> 	var resp types.QueryDEXSettingsResponse
> 	coreumclitestutil.ExecQueryCmd(t, ctx, cli.CmdQueryDEXSettings(), []string{denom}, &resp)
> ```

Please a test to check that you can remove all denoms.
___
*[`x/asset/ft/client/cli/tx_test.go` line 710 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/994#-O8qGncp1ZS-QfOGrsVC:-O8qGncp1ZS-QfOGrsVD:bjoiamk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/36550baf6b28cdc3a2ef832267401ff090030720/x/asset/ft/client/cli/tx_test.go#L710)):*
> ```Go
> }
> 
> func TestUpdateDEXWhitelistedDenomsWithoutEnablingFeature(t *testing.T) {
> ```

Actually, you don't need such a test for the CLI. As well as `TestUpdateDEXWhitelistedDenomsWithWrongDenoms` in the CLI we don't test the logic of the modules, just that CLI can pass args properly. 
___
*[`x/dex/client/cli/tx_test.go` line 227 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/994#-O8qHEXt4HcUMDCaAIzC:-O8qHEXt4HcUMDCaAIzD:b-xtin8h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/36550baf6b28cdc3a2ef832267401ff090030720/x/dex/client/cli/tx_test.go#L227)):*
> ```Go
> 	placeOrder(ctx, requireT, testNetwork, order)
> 
> 	args := append(
> ```

Here you can query and check that all orders are cancelled.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/994)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/ft/client/cli/tx_test.go` line 704 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/994#-O8qGgfS5kIe6bLV2-nX:-O8qN19i64GEsK1kkt9j:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/36550baf6b28cdc3a2ef832267401ff090030720/x/asset/ft/client/cli/tx_test.go#L704)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Please a test to check that you can remove all denoms.
</blockquote></details>

Done.
___
*[`x/asset/ft/client/cli/tx_test.go` line 710 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/994#-O8qGncp1ZS-QfOGrsVC:-O8qN1tTDkRFKiQrKVHq:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/36550baf6b28cdc3a2ef832267401ff090030720/x/asset/ft/client/cli/tx_test.go#L710)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually, you don't need such a test for the CLI. As well as `TestUpdateDEXWhitelistedDenomsWithWrongDenoms` in the CLI we don't test the logic of the modules, just that CLI can pass args properly.
</blockquote></details>

Done.
___
*[`x/dex/client/cli/tx_test.go` line 227 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/994#-O8qHEXt4HcUMDCaAIzC:-O8qQ4061MsPrnb8gOej:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/36550baf6b28cdc3a2ef832267401ff090030720/x/dex/client/cli/tx_test.go#L227)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Here you can query and check that all orders are cancelled.
</blockquote></details>

Done.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/994)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/994#-O8uyzpiDId65ZVqHDVo:-O8uyzpiDId65ZVqHDVp:b-z3w2s0) (no related file):*
the title is as long as a pragraph. please shorten it. 

___

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/994)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil and @ysv)

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/994)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/994)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/994)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/994)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/994)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/994)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
