### PR TITLE
Add cored-client-darwin-arm64 to the release.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Add cored-client-darwin-arm64 to the release.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/717)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/717)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`.github/workflows/release.yml` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/717#-NjIdQnD8lj23Tg86Pzs:-NjIdQnD8lj23Tg86Pzt:bi3cy61) ([raw file](https://github.com/CoreumFoundation/coreum/blob/496b7589642c9ce50295b62650136b18e7c32bae/.github/workflows/release.yml#L70)):*
> ```YAML
>             cored-linux-amd64
>             cored-linux-arm64
>             cored-client-darwin-arm64
> ```

do we need darwin-amd ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/717)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/release.yml` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/717#-NjIdQnD8lj23Tg86Pzs:-NjLvR3B6mGJBrr48oBd:b-xpw0i9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/496b7589642c9ce50295b62650136b18e7c32bae/.github/workflows/release.yml#L70)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we need darwin-amd ?
</blockquote></details>

I decided not to add it since I can't test it :-)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/717)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`.github/workflows/release.yml` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/717#-NjIdQnD8lj23Tg86Pzs:-NjMmryj4Lh4_GwRWAcl:b6y9vqr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/496b7589642c9ce50295b62650136b18e7c32bae/.github/workflows/release.yml#L70)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I decided not to add it since I can't test it :-)
</blockquote></details>

well, we will find a way.
Lets add it & I think we have someone in the team with intel mac

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/717)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/717)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/release.yml` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/717#-NjIdQnD8lj23Tg86Pzs:-NjNKxXsBVzPH6LG4ZO-:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/496b7589642c9ce50295b62650136b18e7c32bae/.github/workflows/release.yml#L70)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

well, we will find a way.
Lets add it & I think we have someone in the team with intel mac
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/717)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/717)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/717)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/717)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
