### PR TITLE
Adjust release workflow to the current behaviour of crust

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/477)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/477)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/477)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/477)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @wojtek-coreum)

___
*[`.github/workflows/release.yml` line 38 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/477#-NUM22ET5zBODSXR7Tht:-NUM22ET5zBODSXR7Thu:boy47l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b8a3831f3ec159e739f53da566c9151e94f4c0f4/.github/workflows/release.yml#L38)):*
> ```YAML
>       - name: Link released binaries under right names
>         run: |
>           ln crust/bin/.cache/cored/docker.amd64/bin/cored cored-linux-amd64
> ```

did we change this path somewhere recently ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/477)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`.github/workflows/release.yml` line 38 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/477#-NUM22ET5zBODSXR7Tht:-NUMANZ9-nWjF7_EMdGC:b-asw1dz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b8a3831f3ec159e739f53da566c9151e94f4c0f4/.github/workflows/release.yml#L38)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

did we change this path somewhere recently ?
</blockquote></details>

Yes in the PR releasing binaries - #187 in crust

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/477)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/477)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/477)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
