### PR TITLE
Adjust instructions on running cored

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/137)

### CODE REVIEW

**Review by dzmitryhil — DISMISSED** [review]
Have tested. Works.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/137)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @xlab)

___
*[`README.md` line 90 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/137#-N9aHD876IWZcejUqiMC:-N9aHD876IWZcejUqiMD:bzejnbo) ([raw file](https://github.com/coreumfoundation/coreum/blob/ee117dff07ca3df8dabe15de3613bed0390ffbbd/README.md#L90)):*
> ```Markdown
> 
> ```
> $ `cored status --chain-id=coreum-devnet-1 --node=tcp://35.223.81.227:26657`
> ```

do we really need this back quotes \` here since it is already inside triple back quotes ```

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/137)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @xlab)

___
*[`README.md` line 90 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/137#-N9aHD876IWZcejUqiMC:-N9aITiI1z7GMnLESfCV:b-mw74xg) ([raw file](https://github.com/coreumfoundation/coreum/blob/ee117dff07ca3df8dabe15de3613bed0390ffbbd/README.md#L90)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we really need this back quotes \` here since it is already inside triple back quotes ```
</blockquote></details>

my bad, done

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/137)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @xlab)

**Pull request merged**
