### PR TITLE
added integration test for feegrant module

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/feegrant_test.go` line 29 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKs3H4KDkablZxnK7RB:-NKs3H4KDkablZxnK7RC:b-coasbr) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L29)):*
> ```Go
> 	requireT.NoError(chain.Faucet.FundAccountsWithOptions(ctx, granter, integrationtests.BalancesOptions{
> 		Messages: []sdk.Msg{&banktypes.MsgSend{}},
> 		Amount:   sdk.NewInt(1_000_000),
> ```

Why do you need that amount? If you send just 1 ?
And why don't you charge it for the messages?
___
*[`integration-tests/modules/feegrant_test.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKs3NZu7RBas9sx22cM:-NKs3NZu7RBas9sx22cN:b526uha) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L32)):*
> ```Go
> 	}))
> 	requireT.NoError(chain.Faucet.FundAccountsWithOptions(ctx, grantee, integrationtests.BalancesOptions{
> 		Messages: []sdk.Msg{&banktypes.MsgSend{}},
> ```

Why does the grantee need balance ?
___
*[`integration-tests/modules/feegrant_test.go` line 63 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKs3gIm4KHniGfWlK5D:-NKs3gIm4KHniGfWlK5E:b-9n82yk) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L63)):*
> ```Go
> 	_, err = tx.BroadcastTx(
> 		ctx,
> 		chain.ClientContext.WithFromAddress(grantee).WithFeeGranterAddress(granter),
> ```

How does the `WithFeeGranterAddress` work ? 



_Code quote:_
```Go
WithFeeGranterAddress
```

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/feegrant_test.go` line 18 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKw6wx439IGUZnAvbq9:-NKw6wx439IGUZnAvbqA:b-h7ildk) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L18)):*
> ```Go
> )
> 
> func TestFeeGrant(t *testing.T) {
> ```

`MsgRevokeAllowance` is not tested
___
*[`integration-tests/modules/feegrant_test.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKw6_WU2XQad9I5JR3t:-NKw6_WV5b_SmfwtdWxM:b-e43zfi) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L28)):*
> ```Go
> 
> 	requireT.NoError(chain.Faucet.FundAccountsWithOptions(ctx, granter, integrationtests.BalancesOptions{
> 		Messages: []sdk.Msg{&banktypes.MsgSend{}},
> ```

`&feegrant.MsgGrantAllowance{}` is missing

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`integration-tests/modules/feegrant_test.go` line 18 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKw6wx439IGUZnAvbq9:-NKwGbND2Y58xlbJ6CkY:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L18)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`MsgRevokeAllowance` is not tested
</blockquote></details>

Done
___
*[`integration-tests/modules/feegrant_test.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKw6_WU2XQad9I5JR3t:-NKwGdRpBhS0YQosvgfC:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`&feegrant.MsgGrantAllowance{}` is missing
</blockquote></details>

Done
___
*[`integration-tests/modules/feegrant_test.go` line 29 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKs3H4KDkablZxnK7RB:-NKwGgr43lNr0J8zJzH0:bk3aar0) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L29)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need that amount? If you send just 1 ?
And why don't you charge it for the messages?
</blockquote></details>

Removed that amount
___
*[`integration-tests/modules/feegrant_test.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKs3NZu7RBas9sx22cM:-NKwGpIo9jXH_I7ewYL0:b-wa08xk) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why does the grantee need balance ?
</blockquote></details>

The grantee will send some funds in bank.MsgSend. 
___
*[`integration-tests/modules/feegrant_test.go` line 61 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKs5MFq80eIq6hFZFeW:-NKwHQDaCFdCbz5gsdxS:b-nq9hya) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L61)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you test the deterministic gas?
</blockquote></details>

Added tests for that 
___
*[`integration-tests/modules/feegrant_test.go` line 63 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKs3gIm4KHniGfWlK5D:-NKwHU-97ck7Vr8PHmVQ:b-1hz4q4) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L63)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How does the `WithFeeGranterAddress` work ? 
</blockquote></details>

Discussed in the call.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/feegrant_test.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKwKoWB0G9G16W_K3YK:-NKwKoWB0G9G16W_K3YL:borsaf0) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L1)):*
> ```Go
> //go:build integrationtests
> ```

why removed?
___
*[`integration-tests/modules/feegrant_test.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKs3NZu7RBas9sx22cM:-NKwKxwW3z7U_7DhyTkh:b-6l4jl4) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L32)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

The grantee will send some funds in bank.MsgSend. 
</blockquote></details>

but fee is charged from the balance of granter, right?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/feegrant_test.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKwKoWB0G9G16W_K3YK:-NKwOiYJABnCqLzBLadJ:b19byoh) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why removed?
</blockquote></details>

Added back, I sometimes remove it since my IDE does not work correctly with this comment in place. 
___
*[`integration-tests/modules/feegrant_test.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKs3NZu7RBas9sx22cM:-NKwOtaG6KqFjlxX7-cg:bi6s0u8) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but fee is charged from the balance of granter, right?
</blockquote></details>

@wojtek-coreum that is correct.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`integration-tests/modules/feegrant_test.go` line 1 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKwKoWB0G9G16W_K3YK:-NKwRACE3stHSrwjcoZ6:blvgcu) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Added back, I sometimes remove it since my IDE does not work correctly with this comment in place. 
</blockquote></details>

Golang allows me to add additional build tags which should be processed :D. Maybe there is such option in VS
___
*[`integration-tests/modules/feegrant_test.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKs3NZu7RBas9sx22cM:-NKwRQSQ4ye5jK5XUk_V:bht4pfo) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L32)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@wojtek-coreum that is correct. 
</blockquote></details>

so it means that grantee don't need funds to cover that fee

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/feegrant_test.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NKs3NZu7RBas9sx22cM:-NKxOxwnDGJeOxCbOZVB:b-lm8emu) ([raw file](https://github.com/coreumfoundation/coreum/blob/f9b0d1b81cd45b58f2894dfabb21cdc97fee4be6/integration-tests/modules/feegrant_test.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

so it means that grantee don't need funds to cover that fee
</blockquote></details>

Right, the shouldn't need funds

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @silverspase)

___
*[`integration-tests/modules/feegrant_test.go` line 36 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NL5BbxA93FxwLCsYmkf:-NL5BbxA93FxwLCsYmkg:b5znpkh) ([raw file](https://github.com/coreumfoundation/coreum/blob/631e412222688db961998d8f201e43c09911e8da/integration-tests/modules/feegrant_test.go#L36)):*
> ```Go
> 	}))
> 	requireT.NoError(chain.Faucet.FundAccountsWithOptions(ctx, grantee, integrationtests.BalancesOptions{
> 		Amount: sdk.NewInt(10),
> ```

Do you spend the entire 10 ? If not set the amount to expect you spend :-)



_Code quote:_
```Go
requireT.NoError(chain.Faucet.FundAccountsWithOptions(ctx, grantee, integrat
```

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @silverspase)

___
*[`integration-tests/modules/feegrant_test.go` line 36 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/327#-NL5BbxA93FxwLCsYmkf:-NL5Scxp7LzV54LO4GAg:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/631e412222688db961998d8f201e43c09911e8da/integration-tests/modules/feegrant_test.go#L36)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you spend the entire 10 ? If not set the amount to expect you spend :-)
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/327)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
