### PR TITLE
Implemented the whitelisting for the entire class

### PR DESCRIPTION
**Pull request by miladz68**
# Description
This PR provides the functionality to whitelist an entire class, instead of every nft individually. 
# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`docs/api.md` line 73 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgcUuHJ9BXQTypprM3q:-NgcUuHO2apgdoPRqnPy:b-ajs8ru) ([raw file](https://github.com/CoreumFoundation/coreum/blob/122ad5e8f8e25a8846ddfba42c8091095c61f2dd/docs/api.md#L73)):*
> ```Markdown
>   
> - [coreum/asset/nft/v1/event.proto](#coreum/asset/nft/v1/event.proto)
>     - [EventAddedToClassWhitelist](#coreum.asset.nft.v1.EventAddedToClassWhitelist)
> ```

I had a few comments about renaming but decided to group all them here

It depends on how we word it either: ClassWhitelist or ClassAdded/removedFromWhitelist everywhere. 
Maybe lets discuss one more time

ideas for renaming:
EventAddedToClassWhitelist -> EventNFTClassAddedToWhitelist or EventClassAddedToWhitelist ?
MsgAddToClassWhitelist -> `MsgAddClassToWhitelist` ?
___
*[`docs/api.md` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgcVFmmA2OSPeQM6FLC:-NgcVFmn05nNrjF0ZLcj:b-b7179f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/122ad5e8f8e25a8846ddfba42c8091095c61f2dd/docs/api.md#L83)):*
> ```Markdown
> - [coreum/asset/nft/v1/genesis.proto](#coreum/asset/nft/v1/genesis.proto)
>     - [BurntNFT](#coreum.asset.nft.v1.BurntNFT)
>     - [ClassWhitelistedAccounts](#coreum.asset.nft.v1.ClassWhitelistedAccounts)
> ```


what about:
`WhitelistedNFTClassAccounts `

to follow existing even name logic: (WhitelistedNFTAccounts)
___
*[`integration-tests/modules/assetnft_test.go` line 1500 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgcWbhlCtCvt-MdRAxT:-NgcWbhlCtCvt-MdRAxU:btw94vi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/122ad5e8f8e25a8846ddfba42c8091095c61f2dd/integration-tests/modules/assetnft_test.go#L1500)):*
> ```Go
> 
> // TestAssetNFTClassWhitelist tests nft class whitelisting.
> func TestAssetNFTClassWhitelist(t *testing.T) {
> ```

good test cases
I would also add a few where you try both class & single NFT whitelisting and check how they interact together (here or inside a separate func)

e.g:
1 add both class & nft whitelist -> OK
2 remove nft whitelist (keep class) -> OK
3 remove class whitelist (keep nft) -> OK for this NFT not ok for other


IDK if it makes sense
___
*[`integration-tests/modules/assetnft_test.go` line 1736 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgcWR_LDAfSQ39WU-aU:-NgcWR_N8vdydABa32bN:b-k5u4x2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/122ad5e8f8e25a8846ddfba42c8091095c61f2dd/integration-tests/modules/assetnft_test.go#L1736)):*
> ```Go
> 
> 	// assert the unwhitelisting event
> 	unWhitelistedEvents, err := event.FindTypedEvents[*assetnfttypes.EventRemovedFromClassWhitelist](res.Events)
> ```

nit: unwhitelisted is a single word
___
*[`x/asset/nft/keeper/keeper.go` line 891 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgcamnH19PaR5KHJxxd:-NgcamnI1kPoUfW8WsZR:b-eoqe2g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/122ad5e8f8e25a8846ddfba42c8091095c61f2dd/x/asset/nft/keeper/keeper.go#L891)):*
> ```Go
> }
> 
> func (k Keeper) addToWhitelistOrRemoveFromWhitelistClass(ctx sdk.Context, classID string, sender, account sdk.AccAddress, setWhitelisted bool) error {
> ```

addOrRemoveClassFromWhitelist addOrRemoveFromClassWhitelist ?
___
*[`x/asset/nft/types/msgs.go` line 29 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgcbQdK8J0t-vD2INu1:-NgcbQdK8J0t-vD2INu2:bmk4xl4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/122ad5e8f8e25a8846ddfba42c8091095c61f2dd/x/asset/nft/types/msgs.go#L29)):*
> ```Go
> )
> 
> type msgAndLegacyMsg interface {
> ```

nice :thumbsup: 

could also be `sdkAndLegacyMsg`

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: 26 of 28 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`docs/api.md` line 73 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgcUuHJ9BXQTypprM3q:-Ngd_YC81u7mZ70Tr63a:b85bim9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/122ad5e8f8e25a8846ddfba42c8091095c61f2dd/docs/api.md#L73)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

well my thinking is that we have 2 concepts, `whitelist` and `classWhitelist`. Otherwise we will add the `class` word at the begining and sometime at the end, which will be confusing.
</blockquote></details>

discussed and decided to keep as is. 
___
*[`x/asset/nft/keeper/keeper.go` line 891 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgcamnH19PaR5KHJxxd:-Ngda04d1OxnXO-G4tQx:b-ymvq55) ([raw file](https://github.com/CoreumFoundation/coreum/blob/122ad5e8f8e25a8846ddfba42c8091095c61f2dd/x/asset/nft/keeper/keeper.go#L891)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's disccuss in daily
</blockquote></details>

decided on `addOrRemoveFromClassWhitelist`

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: 26 of 28 files reviewed, 9 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 34 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrPxO51IElWLP0haH-:-NgrPxO51IElWLP0haH0:b-djfph) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/proto/coreum/asset/nft/v1/genesis.proto#L34)):*
> ```proto
> }
> 
> message ClassWhitelistedAccounts {
> ```

You use two name for the same - `ClassWhitelistedAccounts` and `WhitelistedAccountsForClass`, let's take just on and use it everywhere.
___
*[`x/asset/nft/client/cli/query.go` line 218 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrQN555_LE7A5HepmJ:-NgrQN555_LE7A5HepmK:bptx2s5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/x/asset/nft/client/cli/query.go#L218)):*
> ```Go
> 
> Example:
> $ %s query %s whitelisted-accounts [class-id] [id]
> ```

Breaking change ? I'm ok with it but we need to add to the change-log for the upgrade.
___
*[`x/asset/nft/client/cli/query.go` line 259 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrQb9Q5iByLoq53gq8:-NgrQb9Q5iByLoq53gq9:b5mr7f3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/x/asset/nft/client/cli/query.go#L259)):*
> ```Go
> 		Use:   "class-whitelisted-accounts [class-id]",
> 		Args:  cobra.ExactArgs(1),
> 		Short: "Query for the list whitelisted accounts for a class of non-fungible tokens",
> ```

`list whitelisted` -> `list of whitelisted` ? Or use same as in Long. 
___
*[`x/asset/nft/keeper/keeper.go` line 582 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrRG_58XGqwieVS7vD:-NgrRG_58XGqwieVS7vE:b794l17) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/x/asset/nft/keeper/keeper.go#L582)):*
> ```Go
> 	}
> 
> 	if bytes.Equal(ctx.KVStore(k.storeKey).Get(classKey), asset.StoreTrue) {
> ```

I know that it is not your change, but let's re-think the usage of the helper.go in the root. It looks really ugly. 
@miladz68 @ysv @wojtek-coreum .

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: 26 of 28 files reviewed, 10 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/spec/README.md` line 84 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrSXxf49bxRrc0bN-s:-NgrSd27-dwzDqzS-oh3:bkm3q6u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/x/deterministicgas/spec/README.md#L84)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Did you compute that or just took from the nearest value?
</blockquote></details>

Same for the second message

**Review by ysv — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 34 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrPxO51IElWLP0haH-:-NgrwQce0W_X4UQdlRtL:b-7tdf7d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/proto/coreum/asset/nft/v1/genesis.proto#L34)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You use two name for the same - `ClassWhitelistedAccounts` and `WhitelistedAccountsForClass`, let's take just on and use it everywhere.
</blockquote></details>

agree
___
*[`x/asset/nft/keeper/keeper.go` line 582 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrRG_58XGqwieVS7vD:-NgrwZk4B1wePNUdegpD:bjes2zo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/x/asset/nft/keeper/keeper.go#L582)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I know that it is not your change, but let's re-think the usage of the helper.go in the root. It looks really ugly. 
@miladz68 @ysv @wojtek-coreum .
</blockquote></details>

Could you be more specific ?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 34 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrPxO51IElWLP0haH-:-Ngs8QBK0OKIL8N44Iku:b-pnoyvm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/proto/coreum/asset/nft/v1/genesis.proto#L34)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

agree
</blockquote></details>

We have `whitelisting` and `class-whitelisting` so with that logic we should name it `ClassWhitelistedNFTAccounts` but the `NFT` is redundant. It is redundant in the previous naming as well, and we 
___
*[`x/asset/nft/client/cli/query.go` line 218 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrQN555_LE7A5HepmJ:-Ngs7UbQ-hT8s5egxEoS:b-luxieo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/x/asset/nft/client/cli/query.go#L218)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Breaking change ? I'm ok with it but we need to add to the change-log for the upgrade.
</blockquote></details>

it is not a breaking change, the description was incorrect so I fixed it. 
___
*[`x/asset/nft/client/cli/query.go` line 259 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrQb9Q5iByLoq53gq8:-Ngs800ED5eTxDPSC3rc:bn4mfqk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/x/asset/nft/client/cli/query.go#L259)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`list whitelisted` -> `list of whitelisted` ? Or use same as in Long.
</blockquote></details>

removed `the list` to match with description. 
___
*[`x/asset/nft/keeper/keeper.go` line 582 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrRG_58XGqwieVS7vD:-Ngs8AJuAphSEaf3RREM:bt2hj5h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/x/asset/nft/keeper/keeper.go#L582)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Could you be more specific ?
</blockquote></details>

which helper? you mean `bytes.Equal` ? 
___
*[`x/deterministicgas/spec/README.md` line 84 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrSXxf49bxRrc0bN-s:-Ngs8GdZ5Ng-WH0_CzPv:b-32fynf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/x/deterministicgas/spec/README.md#L84)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Same for the second message
</blockquote></details>

I tool the value from the integration test.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: 21 of 28 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 34 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrPxO51IElWLP0haH-:-NgsB0P875Y8Wk6sLP7p:b-adyf9g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/proto/coreum/asset/nft/v1/genesis.proto#L34)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

We have `whitelisting` and `class-whitelisting` so with that logic we should name it `ClassWhitelistedNFTAccounts` but the `NFT` is redundant. It is redundant in the previous naming as well, and we
</blockquote></details>

Actually I read your comment again and I understand it better now. I fixed the query name in proto.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 14 of 25 files at r1, 5 of 6 files at r2, 2 of 2 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil and @miladz68)

___
*[`integration-tests/modules/assetnft_test.go` line 1519 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgsF__q-8CCTjiHEQ_j:-NgsF__q-8CCTjiHEQ_k:b-pdeola) ([raw file](https://github.com/CoreumFoundation/coreum/blob/33ae24db558f06458a819e65c1d836d1134fd78b/integration-tests/modules/assetnft_test.go#L1519)):*
> ```Go
> 			&assetnfttypes.MsgAddToClassWhitelist{},
> 			&assetnfttypes.MsgAddToClassWhitelist{},
> 			&assetnfttypes.MsgRemoveFromWhitelist{},
> ```

It should be `MsgRemoveFromClassWhitelist`

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: 26 of 28 files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 1519 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgsF__q-8CCTjiHEQ_j:-NgsNbFh2QHx_sjH5kxr:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/33ae24db558f06458a819e65c1d836d1134fd78b/integration-tests/modules/assetnft_test.go#L1519)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It should be `MsgRemoveFromClassWhitelist`
</blockquote></details>

Done.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil and @miladz68)

**Review by wojtek-coreum — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: 25 of 28 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 34 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrPxO51IElWLP0haH-:-NgsRp2T91-DoH2Bw2FU:b-b3dy65) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/proto/coreum/asset/nft/v1/genesis.proto#L34)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Actually I read your comment again and I understand it better now. I fixed the query name in proto.
</blockquote></details>

Seach by `WhitelistedAccountsForClass`, you still use it in the method names. 
___
*[`x/asset/nft/client/cli/query.go` line 218 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrQN555_LE7A5HepmJ:-NgsS-yR257Ce_XGFXft:b2odr8o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/x/asset/nft/client/cli/query.go#L218)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it is not a breaking change, the description was incorrect so I fixed it.
</blockquote></details>

Got you.
___
*[`x/asset/nft/keeper/keeper.go` line 582 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrRG_58XGqwieVS7vD:-NgsS7-sDcEBj-qKbvZQ:b-71cnj6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/x/asset/nft/keeper/keeper.go#L582)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

which helper? you mean `bytes.Equal` ?
</blockquote></details>

```asset.StoreTrue``` - in the assets root heler file with one constant.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: 24 of 28 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/nft/v1/genesis.proto` line 34 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrPxO51IElWLP0haH-:-Ngsv1suDVRLtnelfhFB:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/proto/coreum/asset/nft/v1/genesis.proto#L34)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Seach by `WhitelistedAccountsForClass`, you still use it in the method names.
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper.go` line 582 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrRG_58XGqwieVS7vD:-Ngsv3bo8SL61Ytjxn5g:b-bzsmx4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/x/asset/nft/keeper/keeper.go#L582)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

```asset.StoreTrue``` - in the assets root heler file with one constant.
</blockquote></details>

let's discuss it with yaroslav.

**Review by ysv — APPROVED** [review]
> Reviewed 6 of 7 files at r4, 1 of 2 files at r5, 2 of 3 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil)

___
*[`x/asset/nft/keeper/keeper.go` line 582 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrRG_58XGqwieVS7vD:-Ngt93KF0iovvuVewl9B:b-623ohg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/x/asset/nft/keeper/keeper.go#L582)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's discuss it with yaroslav.
</blockquote></details>

will discuss after daily

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 2 of 3 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil)

___
*[`x/asset/nft/keeper/keeper.go` line 582 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/672#-NgrRG_58XGqwieVS7vD:-Ngx8inl3z-Ttr5hQbST:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a78f0ac6c2cceb6ac052a07faf37b00d48c31b0/x/asset/nft/keeper/keeper.go#L582)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

will discuss after daily
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 4 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by ysv — APPROVED** [review]
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/672)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
