### PR TITLE
Implement class freeze for NFTs

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/680)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/680)* status: all files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBcDyEAWmZsgoiVki_:-NhBcDyEAWmZsgoiVkia:bhv9eg8) (no related file):*
Stuff I did for class whitelisting + minting here: https://github.com/CoreumFoundation/coreum/pull/675
must be done in this PR for class freezing + minting

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBceiyCBC8Wg-oUCrw:-NhBceiyCBC8Wg-oUCrx:b8rxn26) (no related file):*
What about freezing class for everyone (like global freeze in FT)?

___
___
*[`x/asset/nft/client/cli/tx_test.go` line 315 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBdhCBAQdptN6IMvmb:-NhBdhCBAQdptN6IMvmc:b-k1ji5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/client/cli/tx_test.go#L315)):*
> ```Go
> 	args = []string{classID, nftID}
> 	requireT.NoError(coreumclitestutil.ExecQueryCmd(ctx, cli.CmdQueryFrozen(), args, &frozenResp))
> 	requireT.False(frozenResp.Frozen)
> ```

This is interesting case. Maybe when someone queries for specific nft, we should return true if its class is frozen?
___
*[`x/asset/nft/keeper/keeper.go` line 522 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBeqSM3fduackJ095m:-NhBeqSM3fduackJ095n:b-yj7gp5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L522)):*
> ```Go
> 		return err
> 	}
> 	s := ctx.KVStore(k.storeKey)
> ```

I think we use this pattern in many places. Maybe we could implement `booleanStore`?
___
*[`x/asset/nft/keeper/keeper.go` line 551 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBezLD9w-z9S2DjQLc:-NhBezLD9w-z9S2DjQLd:b6jfahr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L551)):*
> ```Go
> 	}
> 
> 	if bytes.Equal(ctx.KVStore(k.storeKey).Get(key), types.StoreTrue) {
> ```

Another candidate to implement in `booleanStore`
___
*[`x/asset/nft/keeper/keeper.go` line 924 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBfODw07okg_JamrPd:-NhBfODw07okg_JamrPe:byfqoju) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L924)):*
> ```Go
> 	}
> 
> 	frozen, err := k.IsFrozen(ctx, classID, nftID)
> ```

non-blocking: isFrozen
___
*[`x/asset/nft/keeper/keeper.go` line 935 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBfJnl0NMakjZLPY3c:-NhBfJnl0NMakjZLPY3d:b-u82ilu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L935)):*
> ```Go
> 	}
> 
> 	classFrozen, err := k.IsClassFrozen(ctx, classID, owner)
> ```

non-blocking: isClassFrozen
___
*[`x/asset/nft/keeper/keeper.go` line 1034 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBfYjxDG_GyrioCsWk:-NhBfYjxDG_GyrioCsWl:b-2scnit) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L1034)):*
> ```Go
> 	}
> 
> 	if classDefinition.Issuer == account.String() {
> ```

Could it be moved to `classDeifnition.IsIssuer` like we did in FTs?
___
*[`x/asset/nft/keeper/msg_server.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBdzye4_LqL7_Ki8tC:-NhBdzye4_LqL7_Ki8tD:boi28b7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/msg_server.go#L16)):*
> ```Go
> // MsgKeeper defines subscope of keeper methods required by msg service.
> //
> //nolint:interfacebloat // We accept the fact that this interface declares more than 10 methods.
> ```

This is the third time I see this `nolint` during past week. Maybe it's time to disble that linter?
___
*[`x/asset/nft/types/keys.go` line 109 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBeTu50FWfe609ffhU:-NhBeTu50FWfe609ffhV:bmsh1of) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/types/keys.go#L109)):*
> ```Go
> 	}
> 	if len(parsedKeys) != 2 {
> 		err = sdkerrors.Wrapf(ErrInvalidKey, "key must be composed to 2 length prefixed keys")
> ```

composed of?

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/680)* status: all files reviewed, 10 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/680)* status: all files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBcDyEAWmZsgoiVki_:-NhQL_HK5Cp_bQLCCkjd:bht1mca) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Stuff I did for class whitelisting + minting here: https://github.com/CoreumFoundation/coreum/pull/675
must be done in this PR for class freezing + minting
</blockquote></details>

I don't understand which parts you are reffering to, maybe we can have a quick call and discuss. 

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBceiyCBC8Wg-oUCrw:-NhQRV4I4oV93KDl9ZNe:b-33otfj) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

What about freezing class for everyone (like global freeze in FT)?
</blockquote></details>

we have not discussed that feature, we can add it after we discuss it with reza. 

___
___
*[`x/asset/nft/client/cli/tx_test.go` line 315 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBdhCBAQdptN6IMvmb:-NhQLiIY60nMIFmXFGn_:bjw5tph) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/client/cli/tx_test.go#L315)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is interesting case. Maybe when someone queries for specific nft, we should return true if its class is frozen?
</blockquote></details>

but return true if class is frozen for who exactly ? right now, we return true if the owner of the NFT is class-frozen, which I think is the correct way. 
___
*[`x/asset/nft/keeper/keeper.go` line 522 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBeqSM3fduackJ095m:-NhQSiyrBhglHhlWJIRu:bilal20) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L522)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I think we use this pattern in many places. Maybe we could implement `booleanStore`?
</blockquote></details>

I looked at it and the abstraction saves a line of code. I don't think it is worth to introduce that abstraction. 
@ysv @dzmitryhil wdyt
___
*[`x/asset/nft/keeper/keeper.go` line 551 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBezLD9w-z9S2DjQLc:-NhQSxHV2yl0FpBF6pRf:b-77w3xz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L551)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Another candidate to implement in `booleanStore`
</blockquote></details>

discussed above. 
___
*[`x/asset/nft/keeper/keeper.go` line 924 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBfODw07okg_JamrPd:-NhQMwvn98nEdIPi5cof:b-2vgdlh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L924)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

non-blocking: isFrozen
</blockquote></details>

we expose this function to query server
___
*[`x/asset/nft/keeper/keeper.go` line 935 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBfJnl0NMakjZLPY3c:-NhQN0JP3jXpJHo3ESdx:b-2vgdlh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L935)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

non-blocking: isClassFrozen
</blockquote></details>

we expose this function to query server
___
*[`x/asset/nft/keeper/keeper.go` line 1034 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBfYjxDG_GyrioCsWk:-NhQRCKP0kI--kjuf3qT:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L1034)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could it be moved to `classDeifnition.IsIssuer` like we did in FTs?
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/msg_server.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBdzye4_LqL7_Ki8tC:-NhQRESp77-uhC3WVBEu:b-d4f2qe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/msg_server.go#L16)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is the third time I see this `nolint` during past week. Maybe it's time to disble that linter?
</blockquote></details>

I don't think we should disable it. 
___
*[`x/asset/nft/types/keys.go` line 109 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBeTu50FWfe609ffhU:-NhQRIbi-FwPZuSi3oo3:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/types/keys.go#L109)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

composed of?
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/680)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBcDyEAWmZsgoiVki_:-NhVkRvF0pXovp4mBw8n:b-umbb6z) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't understand which parts you are reffering to, maybe we can have a quick call and discuss.
</blockquote></details>

When new NFT is minted and sent to recipient other than issuer, and class is frozen for that recipient, it means recipient won't be able to send it. We may say that this is ok or we might say that it should be prohibited.

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBceiyCBC8Wg-oUCrw:-NhVkqxh3K9Wes0sGVVz:b5am5bs) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we have not discussed that feature, we can add it after we discuss it with reza.
</blockquote></details>

let's discuss during daily

___
___
*[`x/asset/nft/client/cli/tx_test.go` line 315 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBdhCBAQdptN6IMvmb:-NhVl27F-2jJbr0ZXndN:b-27eax1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/client/cli/tx_test.go#L315)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

but return true if class is frozen for who exactly ? right now, we return true if the owner of the NFT is class-frozen, which I think is the correct way.
</blockquote></details>

Ah I see now that this query is just for class. So if class is frozen for an account and we query for freeze status of the token for an account (providing class id, nft id and address) it will return true?
___
*[`x/asset/nft/keeper/keeper.go` line 522 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBeqSM3fduackJ095m:-NhVj_Df2YeCCEzviRgu:b-hah0dt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L522)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I looked at it and the abstraction saves a line of code. I don't think it is worth to introduce that abstraction. 
@ysv @dzmitryhil wdyt
</blockquote></details>

I'm saying that we could have sth like this:
```go
s := newBooleanStore(ctx.KVStore(k.storeKey))
s.Set(key, boolValue)
s.IsTrue(key)
s.IsFalse(key)
```
___
*[`x/asset/nft/keeper/keeper.go` line 924 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBfODw07okg_JamrPd:-NhVlPCrANshCzeAReBL:b-mew1io) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L924)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we expose this function to query server
</blockquote></details>

I mean variable name
___
*[`x/asset/nft/keeper/keeper.go` line 935 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBfJnl0NMakjZLPY3c:-NhVlSMn22Q-XLyfNvRp:b-mew1io) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L935)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we expose this function to query server
</blockquote></details>

I mean variable name
___
*[`x/asset/nft/keeper/msg_server.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBdzye4_LqL7_Ki8tC:-NhVlUs26slkk5eD6zKr:b-8wb3tv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/msg_server.go#L16)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think we should disable it.
</blockquote></details>

@ysv @dzmitryhil

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/680)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 522 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBeqSM3fduackJ095m:-NhVmi1bExzJnxYstlLx:b-rojuz0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L522)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I'm saying that we could have sth like this:
```go
s := newBooleanStore(ctx.KVStore(k.storeKey))
s.Set(key, boolValue)
s.IsTrue(key)
s.IsFalse(key)
```
</blockquote></details>

I don't see big benifits from it.
___
*[`x/asset/nft/keeper/msg_server.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBdzye4_LqL7_Ki8tC:-NhVmqrc7vCZR592XcVQ:b-5lxh01) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/msg_server.go#L16)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@ysv @dzmitryhil
</blockquote></details>

I don't have strong opining here, but that's the same discussion we had before, where we decide to use nolint.

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/680)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/680)* status: all files reviewed, 6 unresolved discussions (waiting on @wojtek-coreum and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBcDyEAWmZsgoiVki_:-NhVvgRL-lQEcUatVbDh:b-xnc0b3) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

When new NFT is minted and sent to recipient other than issuer, and class is frozen for that recipient, it means recipient won't be able to send it. We may say that this is ok or we might say that it should be prohibited.
</blockquote></details>

prohibiting sending to recipient is related to whitelisting, I see no reason to prohibit it in case of freezing.

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBceiyCBC8Wg-oUCrw:-NhVvxFEEFdHW4khPRvl:bstdex7) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

let's discuss during daily
</blockquote></details>

Sure, let's discuss. 

___
___
*[`x/asset/nft/client/cli/tx_test.go` line 315 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBdhCBAQdptN6IMvmb:-NhVtJjr5w2-APG7qKVK:b-xd489) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/client/cli/tx_test.go#L315)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Ah I see now that this query is just for class. So if class is frozen for an account and we query for freeze status of the token for an account (providing class id, nft id and address) it will return true?
</blockquote></details>

that query does not exist, you either query for NFT freeze (class-id nft-id) or class-freeze (class-id account). 
___
*[`x/asset/nft/keeper/keeper.go` line 522 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBeqSM3fduackJ095m:-NhVvKbA7C3tW0pcZ4Ux:b-ay58i6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L522)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I don't see big benifits from it.
</blockquote></details>

I agree with Dima, I see no tangible benefits. 
___
*[`x/asset/nft/keeper/keeper.go` line 924 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBfODw07okg_JamrPd:-NhVvJ0v3S22udaLtxER:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L924)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I mean variable name
</blockquote></details>

Done
___
*[`x/asset/nft/keeper/keeper.go` line 935 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBfJnl0NMakjZLPY3c:-NhVv6aF3GoiSklraNqL:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/keeper.go#L935)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I mean variable name
</blockquote></details>

Done
___
*[`x/asset/nft/keeper/msg_server.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBdzye4_LqL7_Ki8tC:-NhVv8xB2SPNFSKFFhXT:bult9b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/msg_server.go#L16)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I don't have strong opining here, but that's the same discussion we had before, where we decide to use nolint.
</blockquote></details>

I agree with Dima, it is exactly the same discussion as we had before, nothing has changed since then.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/680)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBceiyCBC8Wg-oUCrw:-Nh_kHSmCeE5ib_xH4Xi:b3av6fo) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Sure, let's discuss.
</blockquote></details>

Changed to non-blocking as it might be implemented separately. But should be discussed.

___
___
*[`x/asset/nft/keeper/msg_server.go` line 16 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/680#-NhBdzye4_LqL7_Ki8tC:-Nh_jy-n2WrEylB1dngB:bmhjvwa) ([raw file](https://github.com/CoreumFoundation/coreum/blob/acdc15a5fabc16eca68408fcd7bd7d8a9bca9c2e/x/asset/nft/keeper/msg_server.go#L16)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I agree with Dima, it is exactly the same discussion as we had before, nothing has changed since then.
</blockquote></details>

My point is that so far we have never decided to split the interface after seeing this issue. That's why my thesis is that this linter is useless. Changed to non-blocking

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/680)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/680)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
