### PR TITLE
Handle global freeze in genesis import & export

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/295)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/295)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/295)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`x/asset/keeper/global_freeze.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/295#-NJK1__y1AZeZ1bPYjyY:-NJK1__y1AZeZ1bPYjyZ:bp22rmu) ([raw file](https://github.com/coreumfoundation/coreum/blob/0e8633bf50b083439af1d81416f566c40392e8d9/x/asset/keeper/global_freeze.go#L49)):*
> ```Go
> 
> // SetFungibleTokenGlobalFreeze enables/disables global freeze on a fungible token depending on frozen arg.
> func (k Keeper) SetFungibleTokenGlobalFreeze(ctx sdk.Context, denom string, frozen bool) {
> ```

IMO the prev version was better,  you had 2 linces now you have 2 + 6 lines.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/295)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

___
*[`x/asset/keeper/global_freeze.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/295#-NJK1__y1AZeZ1bPYjyY:-NJKA0q-8Dq5OIqva_9Z:b-vkf0w5) ([raw file](https://github.com/coreumfoundation/coreum/blob/0e8633bf50b083439af1d81416f566c40392e8d9/x/asset/keeper/global_freeze.go#L49)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO the prev version was better,  you had 2 linces now you have 2 + 6 lines.
</blockquote></details>

yes it has more lines but I want to avoid calling internal global freeze logic in genesis 

I mean this
`ctx.KVStore(k.storeKey).Set(types.CreateGlobalFreezePrefix(denom), globalFreezeEnabledStoreVal)`

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/295)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/295)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`x/asset/keeper/global_freeze.go` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/295#-NJK1__y1AZeZ1bPYjyY:-NJKSBPh6F575h_ZPyP9:b-65aq5e) ([raw file](https://github.com/coreumfoundation/coreum/blob/0e8633bf50b083439af1d81416f566c40392e8d9/x/asset/keeper/global_freeze.go#L49)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes it has more lines but I want to avoid calling internal global freeze logic in genesis 

I mean this
`ctx.KVStore(k.storeKey).Set(types.CreateGlobalFreezePrefix(denom), globalFreezeEnabledStoreVal)`
</blockquote></details>

Got you. Resolved.

**Pull request merged**
