### PR TITLE
Remove IBC integration

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/278)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/278)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 272 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/278#-NIW3ci87CbbA9PWJqsj:-NIW3ci87CbbA9PWJqsk:bjx41sw) ([raw file](https://github.com/coreumfoundation/coreum/blob/43ac89e85c4bb6bdf705b0df33c7a06988583a6e/app/app.go#L272)):*
> ```Go
> 	ScopedTransferKeeper   capabilitykeeper.ScopedKeeper
> 	ScopedMonitoringKeeper capabilitykeeper.ScopedKeeper
> 	ScopedWASMKeeper       capabilitykeeper.ScopedKeeper
> ```

Why don't we need the `app.ScopedWASMKeeper` ?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/278)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/278)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`app/app.go` line 272 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/278#-NIW3ci87CbbA9PWJqsj:-NIWD4z39Bo4cuBh23n7:b-hjdx39) ([raw file](https://github.com/coreumfoundation/coreum/blob/43ac89e85c4bb6bdf705b0df33c7a06988583a6e/app/app.go#L272)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why don't we need the `app.ScopedWASMKeeper` ?
</blockquote></details>

Because it's not referenced by anything

**Review by miladz68 — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/278)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/278)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/278)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/278)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/278)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
