### PR TITLE
Move integration tests from `crust` to `coreum`

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/125)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/125)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`integration-tests/testing/network.go` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/125#-N8wrq4C3mox-kIidUOI:-N8wrq4D896PfE0kQjWU:b-luraja) ([raw file](https://github.com/coreumfoundation/coreum/blob/12c46c9835749959cf756e6bd60dfe002e36d66e/integration-tests/testing/network.go#L11)):*
> ```Go
> 
> // ZNetNetworkConfig is the network config used by znet
> var ZNetNetworkConfig = app.NetworkConfig{
> ```

I see no reason for this to live here, I think it belongs to znet.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/125)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`integration-tests/testing/network.go` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/125#-N8wrq4C3mox-kIidUOI:-N8wuKF69PqPyemjYqMR:b-8ptsae) ([raw file](https://github.com/coreumfoundation/coreum/blob/12c46c9835749959cf756e6bd60dfe002e36d66e/integration-tests/testing/network.go#L11)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I see no reason for this to live here, I think it belongs to znet.
</blockquote></details>

Renamed to `NetworkConfig`

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/125#-:-N8wv4ND657oSaqPjAhO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, @xlab, and @ysv)

**Review by ysv — COMMENTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/125)* status: all files reviewed, 1 unresolved discussion

___
*[`integration-tests/bank/gas.go` line 33 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/125#-N8x0CsR0dwsieMNN7ut:-N8x0CsR0dwsieMNN7uu:bod4npa) ([raw file](https://github.com/coreumfoundation/coreum/blob/926f824c976205997d4fbaf0231a0741d8fab531/integration-tests/bank/gas.go#L33)):*
> ```Go
> 		}
> 
> 		// FIXME (wojciech): Compute fee based on Network once Milad integrates it into crust
> ```

isn't it available now using `app.NetworkConfig` ?

**Comment by xlab** [comment]
*[`integration-tests/bank/gas.go` line 33 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/125#-N8x0CsR0dwsieMNN7ut:-N8y2Zb15-947wZkaQhs:b-w8x5bx) ([raw file](https://github.com/coreumfoundation/coreum/blob/926f824c976205997d4fbaf0231a0741d8fab531/integration-tests/bank/gas.go#L33)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

isn't it available now using `app.NetworkConfig` ?
</blockquote></details>

I think this PR is focusing on mode code around, fixing the old stuff shall go in another PR I guess.

**Pull request merged**
