### PR TITLE
Stop rejecting contract instantiation if account holds funds

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/738)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/738)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 2343 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/738#-Nl3qKDT9xev5chbrJ5Y:-Nl3qKDT9xev5chbrJ5Z:b-fm00s1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/30a562698e426528d4d17e730958dae5e292fd38/integration-tests/modules/wasm_test.go#L2343)):*
> ```Go
> 	})
> 	requireT.NoError(err)
> 	requireT.Equal("/cosmos.vesting.v1beta1.DelayedVestingAccount", accountRes.Account.TypeUrl)
> ```

I correctly remembered that there is a reason for treating vesting accounts differently. this test fails:

```
Error Trace:	/home/wojciech/coreum/integration-tests/modules/wasm_test.go:2343
        	Error:      	Not equal: 
        	            	expected: "/cosmos.vesting.v1beta1.DelayedVestingAccount"
        	            	actual  : "/cosmos.auth.v1beta1.BaseAccount"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-/cosmos.vesting.v1beta1.DelayedVestingAccount
        	            	+/cosmos.auth.v1beta1.BaseAccount
        	Test:       	TestVestingToWASMContract
--- FAIL: TestVestingToWASMContract (4.27s)
```

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/738)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 2343 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/738#-Nl3qKDT9xev5chbrJ5Y:-Nl3tbAa21EOKxJUPStL:b-dgq6bx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/30a562698e426528d4d17e730958dae5e292fd38/integration-tests/modules/wasm_test.go#L2343)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I correctly remembered that there is a reason for treating vesting accounts differently. this test fails:

```
Error Trace:	/home/wojciech/coreum/integration-tests/modules/wasm_test.go:2343
        	Error:      	Not equal: 
        	            	expected: "/cosmos.vesting.v1beta1.DelayedVestingAccount"
        	            	actual  : "/cosmos.auth.v1beta1.BaseAccount"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-/cosmos.vesting.v1beta1.DelayedVestingAccount
        	            	+/cosmos.auth.v1beta1.BaseAccount
        	Test:       	TestVestingToWASMContract
--- FAIL: TestVestingToWASMContract (4.27s)
```
</blockquote></details>

Okay, I found a way to overcome this

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/738)* status: all files reviewed, 9 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`app/app.go` line 596 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/738#-Nl8eZ5v7ZgKtMcn6zgi:-Nl8eZ5v7ZgKtMcn6zgj:b-915j0m) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d4ae60b8e28f9715ac1658c23e23d75ccc2a54c8/app/app.go#L596)):*
> ```Go
> 			&authtypes.BaseAccount{},
> 			&vestingtypes.ContinuousVestingAccount{},
> 			&vestingtypes.DelayedVestingAccount{},
> ```

What about periodic?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/738)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`app/app.go` line 596 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/738#-Nl8eZ5v7ZgKtMcn6zgi:-Nl8r63a9XgHUoTVLAJ4:b-nive5y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d4ae60b8e28f9715ac1658c23e23d75ccc2a54c8/app/app.go#L596)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about periodic?
</blockquote></details>

Added, but without test because this account might only be created in genesis
___
*[`integration-tests/modules/wasm_test.go` line 2152 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/738#-Nl8Ni4v9puL7X-VjhXw:-Nl8mdEEE248eJoajv2I:bc6ebm1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d4ae60b8e28f9715ac1658c23e23d75ccc2a54c8/integration-tests/modules/wasm_test.go#L2152)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it safe to run this test in parallel with other ?
Because if we instantiate contract in a different test we might have wrong prediction ?
</blockquote></details>

It is safe because it uses Instantiate2 - there is no global counter
___
*[`integration-tests/modules/wasm_test.go` line 2165 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/738#-Nl8NM4jBaNlfQSfZMdj:-Nl8o5RSD4wNJMXOHE31:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d4ae60b8e28f9715ac1658c23e23d75ccc2a54c8/integration-tests/modules/wasm_test.go#L2165)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I suggest to send different amounts to different addresses
this will make test less error prone
</blockquote></details>

Done.
___
*[`integration-tests/modules/wasm_test.go` line 2185 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/738#-Nl8MOD44IgbPpJHCWX0:-Nl8o5GJ1YNB7S8oQcGm:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d4ae60b8e28f9715ac1658c23e23d75ccc2a54c8/integration-tests/modules/wasm_test.go#L2185)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think we should assert that our predicted smart contract address is equal to actuall
Otherwise there is no reason to continue tests

`requireT.Equal(contractAddr1, contract)`

same applies to another places
</blockquote></details>

Done.
___
*[`integration-tests/modules/wasm_test.go` line 2185 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/738#-Nl8MqQyCi-YX_1uvnUD:-Nl8oR5aCkJ-6c0ToR2z:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d4ae60b8e28f9715ac1658c23e23d75ccc2a54c8/integration-tests/modules/wasm_test.go#L2185)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

shouldn't we check if balance is equal to some value after instantiation ?
</blockquote></details>

Done.
___
*[`integration-tests/modules/wasm_test.go` line 2407 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/738#-Nl8O3r6ET7Y6He_4zdx:-Nl8oT_VDkj17KgCRCU7:bqhfwlz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d4ae60b8e28f9715ac1658c23e23d75ccc2a54c8/integration-tests/modules/wasm_test.go#L2407)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is there a different acc type for contract ? or they are just `auth.BaseAccount` ?
</blockquote></details>

BaseAccount
___
*[`integration-tests/modules/wasm_test.go` line 2407 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/738#-Nl8PLh9-zsOywAQGJrf:-Nl8p2lZ39QVEhTfC2mn:bqkwr67) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d4ae60b8e28f9715ac1658c23e23d75ccc2a54c8/integration-tests/modules/wasm_test.go#L2407)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

are we sure it is auth.BaseAccount ?

wasm code:
```
type AccountPruner interface {  
// CleanupExistingAccount handles the cleanup process for balances and data of the given account. The persisted account// type is already reset to base account at this stage.  
// The method returns true when the account address can be reused. Unsupported account types are rejected by returning false  
CleanupExistingAccount(ctx sdk.Context, existingAccount authtypes.AccountI) (handled bool, err error)  
}
```
> type is already reset to base account at this stage
</blockquote></details>

yes, it is. Added check fr this.
___
*[`integration-tests/modules/wasm_test.go` line 2434 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/738#-Nl8ODwD0YBP3IfFI2yu:-Nl8pitR4OLHdDkKsfc9:blszk1h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d4ae60b8e28f9715ac1658c23e23d75ccc2a54c8/integration-tests/modules/wasm_test.go#L2434)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so funds are fully vested after 30s ?

But another thing I wanted to check is that funds are not vested before vesting period passes. Even though the contract is instantiated

Vector of attack.
1. airdrop creates vesting accounts
2. you provide contract address as receiver
3. once received you instantiate contract
4. funds are unlocked
</blockquote></details>

Added check for this, all is as expected

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/738)* status: 1 of 3 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/wasm/types/prunner.go` line 14 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/738#-Nl8PVw4BrdzV1gSoh8u:-Nl8tJHxE8yavElfUSs8:b3c4kuf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d4ae60b8e28f9715ac1658c23e23d75ccc2a54c8/x/wasm/types/prunner.go#L14)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

did we find the reason why they burn vesting accounts ?
I think there was a purpose for this
</blockquote></details>

Original burning was introduced here: https://github.com/CosmWasm/wasmd/pull/996
and thn reimplemented here: https://github.com/CosmWasm/wasmd/pull/1003

The only sentence explaining motivation is this:

```
We had long internal discussions which account types should go into the accept and prune lists and came up with some defaults that support many use cases and are still safe to use.
```

**Comment by ysv** [comment]
Closed in #740

**Pull request closed without merging**
