### PR TITLE
Added missing proto to OpenAPI

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/967)

### CODE REVIEW

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/967)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/967)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/967)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`build/coreum/generate-proto-openapi.go` line 55 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/967#-O79U1FhEMuV51NBT9PA:-O79U1FhEMuV51NBT9PB:bexkdae) ([raw file](https://github.com/CoreumFoundation/coreum/blob/441fa438748c1bfc91200ddc209935203bb4b871/build/coreum/generate-proto-openapi.go#L55)):*
> ```Go
> 		filepath.Join(coreumPath, "asset", "nft", "v1"),
> 		filepath.Join(coreumPath, "customparams", "v1"),
> 		filepath.Join(coreumPath, "dex", "v1"),
> ```

Is it possible to write a test not to forget this later?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/967)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`build/coreum/generate-proto-openapi.go` line 55 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/967#-O79U1FhEMuV51NBT9PA:-O7EAcp2-Dwisq0OXT_w:b-3jdp7c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9fb7d6ba6672525fdeccd021e84fe795410934e1/build/coreum/generate-proto-openapi.go#L55)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is it possible to write a test not to forget this later?
</blockquote></details>

I think this is more of a manual check. since we don't want all the modules to be there.

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/967)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
