### PR TITLE
Implement DEX order cancellation.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Implement DEX order cancellation.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/926)

### CODE REVIEW

**Review by masihyeganeh — DISMISSED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/926)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by masihyeganeh — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/926)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 17 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/926)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`proto/coreum/dex/v1/tx.proto` line 19 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/926#-O4Jo3nzBer1BxpkkVIC:-O4Jo3nzBer1BxpkkVID:b-cnlmr7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9fe268f185bc693a251992e11125eb63daebd5bd/proto/coreum/dex/v1/tx.proto#L19)):*
> ```proto
>   // PlaceOrder is a method to place an order on orderbook.
>   rpc PlaceOrder(MsgPlaceOrder) returns (EmptyResponse);
>   // CancelOrder is a method to cancel the order in the orderbook.
> ```

you should remove `is a method` both here and above. replace with:

CancelOrder cancels an order in the orderbook.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/926)* status: 14 of 17 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`proto/coreum/dex/v1/tx.proto` line 19 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/926#-O4Jo3nzBer1BxpkkVIC:-O4K17My2lf3M1PegoIe:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9fe268f185bc693a251992e11125eb63daebd5bd/proto/coreum/dex/v1/tx.proto#L19)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you should remove `is a method` both here and above. replace with:

CancelOrder cancels an order in the orderbook.
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/926)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/926)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
