### PR TITLE
Remove legacy types

### PR DESCRIPTION
**Pull request by dzmitryhil**
* Remove usage of the wallet from the integration test
* Remove the legacy client
* Remove the test which tests the faucet
* Squash the similar fee tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/228)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
Thanks :-)

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/228#-:-NEe-tjw17ObPEwqJ4r7:b-7z4718)* status: 18 of 31 files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/bank/transfer.go` line 63 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/228#-NEdm56FCt2AaX23tyL0:-NEe0TidCjCP7VQ2ubLP:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/c6434f4ee6d6082c0b8f5fe4e36662ecc38b1186/integration-tests/bank/transfer.go#L63)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Here and below: you might query for balance of one token only
</blockquote></details>

Done.



_Code quote:_
```Go
balancesSender, err := bankClient.AllBalances(ctx, &banktypes.QueryAllBalancesRequest{
```
___
*[`integration-tests/testing/event.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/228#-NEdqFGQ8mTfVY2AJHqD:-NEe2MzG8Kse714HSnFi:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/c6434f4ee6d6082c0b8f5fe4e36662ecc38b1186/integration-tests/testing/event.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

FindUint -> FindUint64
</blockquote></details>

Done.



_Code quote:_
```Go
FindUintEventAttribute
```
___
*[`pkg/staking/staking.go` line 21 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/228#-NEdsj7F8O09u4o0eYwo:-NEe3SXeB6WC9E665rjC:b-6j3cx9) ([raw file](https://github.com/coreumfoundation/coreum/blob/c6434f4ee6d6082c0b8f5fe4e36662ecc38b1186/pkg/staking/staking.go#L21)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This function is used:
1. in coreum (only in unit tests) to verify gen txs
2. in crust to prepare znet

Is (1) really needed? Could we verify operations on gentxs using just byte slice which is not a proper transaction?
Then we could move this function to crust (and probably reimplement it).
</blockquote></details>

The function moved to the crust as is. I would try to remove it in the future since there is already command in the cosmos to do the same.
One test removed, since it tested just the func, and one refactored to use empty gen txs. 



_Code quote:_
```Go
PrepareTxStakingCreateValidator(
```
___
*[`integration-tests/testing/error.go` line 9 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/228#-NEdpWnIECAPWA0VCPXb:-NEe2G0FEA7ZPV_qzMJ2:b-29q5od) ([raw file](https://github.com/coreumfoundation/coreum/blob/c6434f4ee6d6082c0b8f5fe4e36662ecc38b1186/integration-tests/testing/error.go#L9)):*
> cosmosErr.Is
Good catch. Updated.

**Review by miladz68 — APPROVED** [review]
> Reviewed 18 of 31 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/228)* status: all files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/228)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/228)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/228)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Pull request merged**
