### PR TITLE
Migrate params from the params module to inside each module

### PR DESCRIPTION
**Pull request by miladz68**
# Description
This PR migrates params for coreum developed module, from the deprecated params module and move them to inside each module.
# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/641)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/641)* status: all files reviewed, 18 unresolved discussions (waiting on @miladz68, @vertex451, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2TBER44lFI6OupoCG:-Ne2TBER44lFI6OupoCH:bwpdgi4) (no related file):*
It seems that PR is a great candidate to be split into multiplier PRs. Since each module could be a separate PR. 

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2URJfDZ2uD_JKHQWb:-Ne2URJfDZ2uD_JKHQWc:b98o2hm) (no related file):*
I remember you wanted to rename the legacy to migration, will you do it in a separate PR?

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2ZTfy-u9gsgJIGWvR:-Ne2ZTfy-u9gsgJIGWvS:bxmycit) (no related file):*
How about adding tests to an upgrade test?

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2ZWhn2DkQhKoRpCKa:-Ne2ZWhn2DkQhKoRpCKb:bd11wcj) (no related file):*
It would be nice to somehow test that any used can't execute the `update params` message. 

___
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 47 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2S2qX6p7NeTQDfU5v:-Ne2S2qX6p7NeTQDfU5w:b-nrnwe3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/proto/coreum/asset/ft/v1/tx.proto#L47)):*
> ```proto
> 
>   // UpdateParams is a governance operation to modify the parameters of the module.
>   // NOTE: all parameters must be provided. 
> ```

Does it work the same for SDK modules, so you need to provide all params? 
And why does that comment only for the assetft params?
___
*[`proto/coreum/asset/nft/v1/tx.proto` line 32 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2Sb5Y7Dib6FzOXmhq:-Ne2Sb5Y7Dib6FzOXmhr:b-pmgwcl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/proto/coreum/asset/nft/v1/tx.proto#L32)):*
> ```proto
>   // RemoveFromWhitelist removes an account from whitelisted list of the NFT
>   rpc RemoveFromWhitelist(MsgRemoveFromWhitelist) returns (EmptyResponse);
>   // UpdateParams is a governance operation that the mint fee. 
> ```

The comment seems incorrect. 
___
*[`x/asset/ft/legacy/v1/params.go` line 28 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2UnQv5_27LeJmAxb8:-Ne2UnQv5_27LeJmAxb9:b-u3oft1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/asset/ft/legacy/v1/params.go#L28)):*
> ```Go
> 	}
> 	// set KeyTable if it has not already been set
> 	if !ftSubspace.HasKeyTable() {
> ```

Why do we need it for the `v1` migration? Also, I see that you added it here, but haven't added it in other places for example in asset nft.
___
*[`x/asset/ft/types/keys.go` line 43 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2G9vt7Vw-_EHXcwDo:-Ne2UzuQ-amW7j-yd8Qn:b-sqn7n8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/asset/ft/types/keys.go#L43)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why 0x30? If the idea is to use a common prefix in all the modules which is far away from the "normal" ones., then maybe `0xff`?
</blockquote></details>

Same question (and same for similar usage).
___
*[`x/asset/ft/types/msgs.go` line 442 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2GYDj5atIM_oSEWuw:-Ne2VX77-hZCPJ8v22oW:b-sqn7n8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/asset/ft/types/msgs.go#L442)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Shouldn't it be required?
</blockquote></details>

Same question (and same for similar usage).
___
*[`x/customparams/keeper/msg_server.go` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2YBTN7J8in2hPH5s8:-Ne2YBTN7J8in2hPH5s9:b-ovcavv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/customparams/keeper/msg_server.go#L21)):*
> ```Go
> }
> 
> // MsgServer serves grpc tx requests for assets module.
> ```

Misleading comment. 
___
*[`x/customparams/types/codec.go` line 9 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2XcOPB9cUkTYnuOhb:-Ne2XcOPB9cUkTYnuOhc:b-lf9pb9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/customparams/types/codec.go#L9)):*
> ```Go
> )
> 
> // RegisterInterfaces registers the asset module tx interfaces.
> ```

Misleading comment.
___
*[`x/customparams/types/mgs.go` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2YcLNAIQxL0LEitx6:-Ne2YcLNAIQxL0LEitx7:b-de1kiq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/customparams/types/mgs.go#L15)):*
> ```Go
> // Type of messages for amino.
> const (
> 	TypeMsgUpdateMinSelfDelegation = "set-min-self-delegation"
> ```

Not sure about that name. The message name is `UpdateStakingParams`, why does that name is different?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/641)* status: 65 of 77 files reviewed, 18 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2URJfDZ2uD_JKHQWb:-Ne3EaDZ3OqlS42B_5ZI:b-d8fog4) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I remember you wanted to rename the legacy to migration, will you do it in a separate PR?
</blockquote></details>

I will do it in a separte PR. 

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2TBER44lFI6OupoCG:-Ne3EkLy3PLIPXof8Y9A:b-l2v39r) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It seems that PR is a great candidate to be split into multiplier PRs. Since each module could be a separate PR.
</blockquote></details>

I did consider it. but it would increase the review rounds. but it is good to discuss this subject in the team. 

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2ZTfy-u9gsgJIGWvR:-Ne3N7I28ogZJ_VIPYbl:b-178dcu) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How about adding tests to an upgrade test?
</blockquote></details>

upgrade tests are there. 

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2ZWhn2DkQhKoRpCKa:-Ne3N8zwBjBCOTcekwVc:b-t320uw) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It would be nice to somehow test that any used can't execute the `update params` message.
</blockquote></details>

I thought about it actually and tried to do it. but I notice authority is check at the time of exection, and logs can only be inspected by reading the binary logs. 

___
___
*[`integration-tests/gov.go` line 95 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2Dh5A-7e9dzqS4zUX:-Ne3GS8T8GB6QdeFPXZX:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/integration-tests/gov.go#L95)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

- creates
- staker accounts
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetft_test.go` line 172 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2E8Qv9jmfEUdLNurp:-Ne3H-ViDlucL8Q7gtWk:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/integration-tests/modules/assetft_test.go#L172)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

maybe it could be the last argument defined as `...sdk.Msg` to provide messages without creating a slice explicitly
</blockquote></details>

Done.
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 47 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2S2qX6p7NeTQDfU5v:-Ne3H3cLCHVp6X6L0f1O:bpw00rg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/proto/coreum/asset/ft/v1/tx.proto#L47)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Does it work the same for SDK modules, so you need to provide all params? 
And why does that comment only for the assetft params?
</blockquote></details>

it works the same for cosmo sdk modules as well. 
the reason that it is there only for assetft, is that other modules only have one field, and leaving that comment would be incorrect. 
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 123 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2F8w5ENKO04zuR7QN:-Ne3HQLG1qkOp6peCNRj:b8ckb7j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/proto/coreum/asset/ft/v1/tx.proto#L123)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Should we migrate all our protos to use it?
</blockquote></details>

it could be a good idea, let's discuss in the team. 
___
*[`proto/coreum/asset/ft/v1/tx.proto` line 124 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2EzPD-CV2R2X9QvOT:-Ne3Hhnk1ud9paQUAM9x:b-e9hzqr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/proto/coreum/asset/ft/v1/tx.proto#L124)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

do we need this amino tag? I saw that all the types in cosmos defines it, but we never did and it worked. Is it a legacy or sth required?
</blockquote></details>

I honestly did not look into it. I don't think it is legacy though, it actually seems something new, I don't think it was present in v0.45
___
*[`proto/coreum/asset/nft/v1/tx.proto` line 32 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2Sb5Y7Dib6FzOXmhq:-Ne3ILOv875JLbYqty_p:b-l0pazu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/proto/coreum/asset/nft/v1/tx.proto#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The comment seems incorrect.
</blockquote></details>

OMG, good catch. Done. 
___
*[`x/asset/ft/legacy/v1/params.go` line 28 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2UnQv5_27LeJmAxb8:-Ne3ImLpDRdI1c3rbI_N:bnz2z72) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/asset/ft/legacy/v1/params.go#L28)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we need it for the `v1` migration? Also, I see that you added it here, but haven't added it in other places for example in asset nft.
</blockquote></details>

we have remove this logic from app.go, but we still have the tests lying around. the tests will fail without this logic (that used to be inside app.go)
It is added in all the places that needed migrations from the old params module. 
___
*[`x/asset/ft/types/keys.go` line 43 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2G9vt7Vw-_EHXcwDo:-Ne3JLwi-hwwSxy7Yl6L:b-7rbb9p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/asset/ft/types/keys.go#L43)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Same question (and same for similar usage).
</blockquote></details>

It is 0x30 is cosmos sdk modules. I have repeated the same practice for the sake of unity. 
___
*[`x/asset/ft/types/msgs.go` line 442 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2GYDj5atIM_oSEWuw:-Ne3Jb787LInsyg3mzaC:bheb703) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/asset/ft/types/msgs.go#L442)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Same question (and same for similar usage).
</blockquote></details>

I don't understand what you mean by required, we are enforcing that it is required here. if you mean in proto, then there we can only enforce that it is not nil. 
___
*[`x/asset/ft/types/msgs_test.go` line 575 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2GoMx8fpG0XLawbF2:-Ne3Jru4Cv9iDBkbYat3:b-17ihnr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f243a831b57d37b5ab7584d8f215936657cb13ae/x/asset/ft/types/msgs_test.go#L575)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

funny, how did it work before?
</blockquote></details>

It was problematic both is code and in test :D 
___
*[`x/asset/nft/keeper/keeper.go` line 69 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2H44b1MzUejroLIed:-Ne3K-kfD-tKE2HwWYvJ:b-39kf54) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/asset/nft/keeper/keeper.go#L69)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I guess this design is driven by cosmos sdk but I feel uncomfortable about the fact that keeper defines the authority, but at the same time it doesn't verify it in `SetParams`, leaving it to the upper layer.

IMO one of two things should happen:
- if `SetParams` does not verify the authority, then authority should not be defined in the scope of the keeper at all
- if authority is defined here, then keeper should verify it
</blockquote></details>

yes this design is done by cosmos sdk, and I also feel confused, but I think deviating from the standard will be even more confusing, let's discuss in the team. 
___
*[`x/customparams/keeper/msg_server.go` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2YBTN7J8in2hPH5s8:-Ne3L_ItE5xdQ9znR9Yd:b-l02ec7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/customparams/keeper/msg_server.go#L21)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Misleading comment.
</blockquote></details>

great catch, I will update
___
*[`x/customparams/types/codec.go` line 9 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2XcOPB9cUkTYnuOhb:-Ne3M_7f5TGoR6t0msMa:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/customparams/types/codec.go#L9)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Misleading comment.
</blockquote></details>

Done.
___
*[`x/customparams/types/mgs.go` line 15 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2YcLNAIQxL0LEitx6:-Ne3Mvm27K7-koHbGAKU:b-46w1sn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/customparams/types/mgs.go#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not sure about that name. The message name is `UpdateStakingParams`, why does that name is different?
</blockquote></details>

Another good catch, it was left over from before I refactored it.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/641)* status: all files reviewed, 14 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 124 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2EzPD-CV2R2X9QvOT:-Ne3PWtkAEwnGY7VmAKX:b-jyc7g7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/proto/coreum/asset/ft/v1/tx.proto#L124)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I honestly did not look into it. I don't think it is legacy though, it actually seems something new, I don't think it was present in v0.45
</blockquote></details>

Then it's funny that deprecated `amino` gets new tags
___
*[`x/asset/ft/types/msgs.go` line 442 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2GYDj5atIM_oSEWuw:-Ne3Phoc-LGTTgF0vi5O:b-tdhbw9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/asset/ft/types/msgs.go#L442)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't understand what you mean by required, we are enforcing that it is required here. if you mean in proto, then there we can only enforce that it is not nil.
</blockquote></details>

I mea that this function does not return error if `len(m.Authority) == 0`

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/641)* status: 69 of 77 files reviewed, 14 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 69 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2H44b1MzUejroLIed:-Ne3qUhy2Bkbq8xk6945:b8ib64c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/asset/nft/keeper/keeper.go#L69)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

yes this design is done by cosmos sdk, and I also feel confused, but I think deviating from the standard will be even more confusing, let's discuss in the team.
</blockquote></details>

Introduce `UpdateParam` to the keeper

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/641)* status: 59 of 77 files reviewed, 14 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/ft/v1/tx.proto` line 47 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2S2qX6p7NeTQDfU5v:-Ne7adlrEySwOpA0gAL0:b-mfe6y8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/proto/coreum/asset/ft/v1/tx.proto#L47)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it works the same for cosmo sdk modules as well. 
the reason that it is there only for assetft, is that other modules only have one field, and leaving that comment would be incorrect.
</blockquote></details>

I will leave the comment in all of the modules.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/641)* status: 56 of 77 files reviewed, 4 unresolved discussions (waiting on @vertex451, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2TBER44lFI6OupoCG:-Ne7sJgs8h5-95UI1N6T:b4c9lyr) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's discuss it today.
</blockquote></details>

:thumbsup: 

___
___
*[`x/asset/ft/types/keys.go` line 43 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2G9vt7Vw-_EHXcwDo:-Ne7l4kS698SGOAJuOdL:b-v3u44n) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/asset/ft/types/keys.go#L43)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO we should use just the next key. BTW how it's done on the WASMd ?
</blockquote></details>

wasmd is using sequential numbers, let's do the same.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/641)* status: 56 of 77 files reviewed, 4 unresolved discussions (waiting on @vertex451, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/types/keys.go` line 43 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/641#-Ne2G9vt7Vw-_EHXcwDo:-Ne7uNAC2rS3_KldyTNz:b-n0hjue) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfd04975276872aacf9f083645d856c737d37f40/x/asset/ft/types/keys.go#L43)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

wasmd is using sequential numbers, let's do the same.
</blockquote></details>

Agree, it makes more sence to use next key.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 6 of 8 files at r4, 9 of 10 files at r5, 5 of 5 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/641)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/641)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @ysv)

**Pull request merged**
