### PR TITLE
block non-core tokens from proposal deposit

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/873)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/873)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/873#-O-4z0AEAS0BH1KC0csQ:-O-4z0AF5isUtWx77IWC:bj4jn3i) (no related file):*
I want to discuss this idea after the daily

___

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/873)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/873#-O-4z0AEAS0BH1KC0csQ:-O-6JkBhCveREVOtE2j3:bsq57bh) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I want to discuss this idea after the daily
</blockquote></details>

Discussed and decided to keep this approach.

___

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/873)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/873#-O-FEX0k-pNl7jtPmm2o:-O-FEX0k-pNl7jtPmm2p:b-pke4sq) (no related file):*
Maybe let's report this issue to the cosmos team. There is no reason for the deposit to accept any other token than the one configured for staking right?

___

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/873)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/wgov/ante/ante.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/873#-O-KuXnLDUyawi6LtJTX:-O-KuXnLDUyawi6LtJTY:b-oi3d8p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/392d696656e492dbb579df1f50cbe9e0655d87e2/x/wgov/ante/ante.go#L17)):*
> ```Go
> // proposals can lead to problems when they are being refunded.
> type GovDepositDecorator struct {
> 	keeer types.GovKeeper
> ```

keeper

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/873)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/wgov/ante/ante_test.go` line 112 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/873#-O-KwqjeAbWf5kmXU4Tt:-O-KwqjeAbWf5kmXU4Tu:bfwdvu9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/392d696656e492dbb579df1f50cbe9e0655d87e2/x/wgov/ante/ante_test.go#L112)):*
> ```Go
> 		},
> 		{
> 			name: "deposit v1beta1",
> ```

nit: Better to use `_` as the delimiter in the table test name (for all cases), since the go will concatitate it using the `_` instead of` `, when printing the failure, so it's easier to search.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/873)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/873)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/873#-O-FEX0k-pNl7jtPmm2o:-O-LDuV97kFjoOmkQxtl:br2kr4y) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Maybe let's report this issue to the cosmos team. There is no reason for the deposit to accept any other token than the one configured for staking right?
</blockquote></details>

It is already added in v0.50

___
___
*[`x/wgov/ante/ante.go` line 17 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/873#-O-KuXnLDUyawi6LtJTX:-O-L8M-uEAqLRu8ME_EV:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/392d696656e492dbb579df1f50cbe9e0655d87e2/x/wgov/ante/ante.go#L17)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

keeper
</blockquote></details>

Done.
___
*[`x/wgov/ante/ante_test.go` line 112 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/873#-O-KwqjeAbWf5kmXU4Tt:-O-L8MXh5fzpYMHJZ6fv:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/392d696656e492dbb579df1f50cbe9e0655d87e2/x/wgov/ante/ante_test.go#L112)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

nit: Better to use `_` as the delimiter in the table test name (for all cases), since the go will concatitate it using the `_` instead of` `, when printing the failure, so it's easier to search.
</blockquote></details>

Done.

**Review by wojtek-coreum — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/873)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/873)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/873)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
