### PR TITLE
Updated readme file

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/470)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/470)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`README.md` line 98 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/470#-NTOThZz3PebBh-yigSD:-NTOThZz3PebBh-yigSE:b-rx9hjb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/84b468cb072f3e26185ed09781b1dd89f746afba/README.md#L98)):*
> ```Markdown
> ```
> 
> You can also find block explorers for each chain in this [link](https://docs.coreum.dev/tools-ecosystem/block-explorer.html),
> ```

Is there a comma at the end of this sentence?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/470)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`README.md` line 98 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/470#-NTOThZz3PebBh-yigSD:-NTTBbs6Dv0dF973VHVj:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/84b468cb072f3e26185ed09781b1dd89f746afba/README.md#L98)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is there a comma at the end of this sentence?
</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/470)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`README.md` line 25 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/470#-NTTDGTKAZBeKBsDTwpy:-NTTDGTKAZBeKBsDTwpz:bxkjgy7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8a7b2d76f2c5b81b153c5afb9dc9b2766cb28811/README.md#L25)):*
> ```Markdown
> 
> Steps to build required binaries:
> 1. Clone our [crust repository](https://github.com/CoreumFoundation/crust) to the directory of your choice (let's call it `$COREUM_PATH`):
> ```

I would use the $PWD instead, and added the remark that all repos should be on the same level.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/470)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`README.md` line 25 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/470#-NTTDGTKAZBeKBsDTwpy:-NTTYKQTAmNL_u4nvmiP:b98rhjo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8a7b2d76f2c5b81b153c5afb9dc9b2766cb28811/README.md#L25)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would use the $PWD instead, and added the remark that all repos should be on the same level. 
</blockquote></details>

`PWD` stands for `Print Current Directory`, which I don't think is a good name.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/470)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`README.md` line 25 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/470#-NTTDGTKAZBeKBsDTwpy:-NTYGhxw1R2Da4r9jb4l:bqt8cqq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8a7b2d76f2c5b81b153c5afb9dc9b2766cb28811/README.md#L25)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

`PWD` stands for `Print Current Directory`, which I don't think is a good name.  
</blockquote></details>

I thought about usage of $PWD/.. / kind of, but now see the disadvantage, of using it. So let's keep the `COREUM_PATH`

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/470)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/470)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @silverspase)

___
*[`README.md` line 25 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/470#-NTrgaTYCnroFyloAz2m:-NTrgaTYCnroFyloAz2n:bsi8rbe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8a7b2d76f2c5b81b153c5afb9dc9b2766cb28811/README.md#L25)):*
> ```Markdown
> 
> Steps to build required binaries:
> 1. Clone our [crust repository](https://github.com/CoreumFoundation/crust) to the directory of your choice (let's call it `$COREUM_PATH`):
> ```

same as crust comment
lets set COREUM_PATH in the first step



_Code quote:_
```Markdown
COREUM_PATH
```
___
*[`README.md` line 95 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/470#-NTrgOoWC9QmWmlkRIET:-NTrgOoWC9QmWmlkRIEU:b-n5tddf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8a7b2d76f2c5b81b153c5afb9dc9b2766cb28811/README.md#L95)):*
> ```Markdown
> 
> ```
> $ cored status --chain-id=coreum-devnet-1 --node=https://full-node.devnet-1.coreum.dev:26657
> ```

advice testnet here it is more stable
___
*[`README.md` line 98 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/470#-NTrgVPH6TmLo14TeIom:-NTrgVPH6TmLo14TeIon:b-myvct3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8a7b2d76f2c5b81b153c5afb9dc9b2766cb28811/README.md#L98)):*
> ```Markdown
> ```
> 
> You can also find block explorers for each chain in this 
> ```

by following this link

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/470)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/470)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
