### PR TITLE
Add extension gas test

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description
Add test to alert on new messages that are not listed in extension gas non-determinism.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/876)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/876)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/876)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 181 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/876#-O-FDDmn76Slrh2ssPLk:-O-FDDmn76Slrh2ssPLl:bjzwcvo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/99ab052aeca9bfbf11abf441bd61f447cb1acf65/x/deterministicgas/types/gas.go#L181)):*
> ```Go
> 
> // TypeAssertMessages type checks the message to find out that it might invoke asset extensions.
> func TypeAssertMessages(msg sdk.Msg) (sdk.Coins, bool, bool, error) {
> ```

please give names to the return params because it's hard to understand what those two bools mean
___
*[`x/deterministicgas/types/gas.go` line 195 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/876#-O-FD6dg-UDf6l5i1Swk:-O-FD6dg-UDf6l5i1Swl:bazwbzp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/99ab052aeca9bfbf11abf441bd61f447cb1acf65/x/deterministicgas/types/gas.go#L195)):*
> ```Go
> 		coins = typedMsg.Amount
> 	case *ibctransfertypes.MsgTransfer:
> 		if typedMsg.Token.IsValid() {
> ```

shouldn't it be done for all the messages?

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/876)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 181 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/876#-O-FDDmn76Slrh2ssPLk:-O-GjyFRD7QJBQZJJqG5:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/db9ce8c9dd646f77d861fa3294a960e44e9715b9/x/deterministicgas/types/gas.go#L181)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

please give names to the return params because it's hard to understand what those two bools mean
</blockquote></details>

Done.
___
*[`x/deterministicgas/types/gas.go` line 195 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/876#-O-FD6dg-UDf6l5i1Swk:-O-Gk3YdAKFeKbF-CCVF:b-13lgnu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/db9ce8c9dd646f77d861fa3294a960e44e9715b9/x/deterministicgas/types/gas.go#L195)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

shouldn't it be done for all the messages?
</blockquote></details>

Not needed. It is the only one with `sdk.NewCoins` that panics if the token is not valid

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/876)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/876)* status: all files reviewed, 2 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/876)* status: all files reviewed, 3 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/config_test.go` line 75 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/876#-O-L53E5Bpz6hcN9AdMU:-O-L53E5Bpz6hcN9AdMV:bknytxc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/aa56946687b93bab475bb8bd6a0c53b49af6c014/x/deterministicgas/config_test.go#L75)):*
> ```Go
> 		assert.True(t, ok, fmt.Sprintf("sdk.Msg %s, not found in the gasByMsg map", msgURL))
> 
> 		_, _, nonExtensionMsg, err := types.TypeAssertMessages(sdkMsg)
> ```

The test is good, but IMO the `TypeAssertMessages` should be merged with the `config.go`, and for each message we should have a func to get a deterministic gas, or understand that it's not deterministic, because now it's spread out across the repo.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/876)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 181 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/876#-O-FDDmn76Slrh2ssPLk:-O-LCtZIAqPHtuxgcOpO:b4x70fy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/db9ce8c9dd646f77d861fa3294a960e44e9715b9/x/deterministicgas/types/gas.go#L181)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I would prefer to rename `notExtensionMsg` to `isExtensionMessage` and change the meaning of `true` and `false`

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/876)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/config_test.go` line 75 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/876#-O-L53E5Bpz6hcN9AdMU:-O-LKXjH8j9fav58LFjZ:b4ir65c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/aa56946687b93bab475bb8bd6a0c53b49af6c014/x/deterministicgas/config_test.go#L75)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The test is good, but IMO the `TypeAssertMessages` should be merged with the `config.go`, and for each message we should have a func to get a deterministic gas, or understand that it's not deterministic, because now it's spread out across the repo.
</blockquote></details>

I saw your message on Milad's PR about the same issue. Let's merge this and continue it there
___
*[`x/deterministicgas/types/gas.go` line 181 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/876#-O-FDDmn76Slrh2ssPLk:-O-LKkl60Vm7tdInjJPz:b80z5bk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/db9ce8c9dd646f77d861fa3294a960e44e9715b9/x/deterministicgas/types/gas.go#L181)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I would prefer to rename `notExtensionMsg` to `isExtensionMessage` and change the meaning of `true` and `false`
</blockquote></details>

then we will have a `hasExtension` and `isExtensionMessage` which is more confusing in my opinion

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/876)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/876)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/876)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Pull request merged**
