### PR TITLE
Implemented interceptor to the NFT module. 

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 163 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NJxyhw59ZoL0SpCCsqa:-NJxyhw59ZoL0SpCCsqb:b-xp2gq9) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/app/app.go#L163)):*
> ```Go
> 		genutil.AppModuleBasic{},
> 		wbank.AppModuleBasic{},
> 		wnft.AppModuleBasic{},
> ```

Why it was moved here? The bank is here since the original was here.
___
*[`x/wnft/keeper/keeper.go` line 29 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NJxyxt25w9U8dNUZGff:-NJxyxt25w9U8dNUZGfg:b-2rww5x) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L29)):*
> ```Go
> 
> // Send overwrites Send method of the original keeper.
> func (wk NFTKeeperWrapper) Send(goCtx context.Context, msg *nft.MsgSend) (*nft.MsgSendResponse, error) {
> ```

Add the comment plz, that it's copy.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`app/app.go` line 163 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NJxyhw59ZoL0SpCCsqa:-NKEE-dK10N_w6BwDcL2:b-l8l7r9) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/app/app.go#L163)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why it was moved here? The bank is here since the original was here.
</blockquote></details>

same question
___
*[`x/asset/nft/keeper/before.go` line 8 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEGJG_-O0eE20VF4bz:-NKEGJG_-O0eE20VF4c-:bmirl8v) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/asset/nft/keeper/before.go#L8)):*
> ```Go
> 
> // BeforeTransfer includes logic that will be run before the Tranfer method of the nft module.
> func (k Keeper) BeforeTransfer(ctx sdk.Context, classID string, nftID string, receiver sdk.AccAddress) error {
> ```

in nft msg is called MsgSend so it should be `BeforeSend` IMO
or we BeforeTransfer in FT ?
___
*[`x/wnft/keeper/keeper.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEL5wp4jVv2HLdKWhA:-NKEL5wqDOAMcRYxAbyO:b-swinc7) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L15)):*
> ```Go
> 
> // NFTKeeperWrapper wraps the original nft keeper and intercepts its original methods if needed
> type NFTKeeperWrapper struct {
> ```

I propose to unify naming logic between wbank & wnft
So there it is named `BaseKeeperWrapper` so we should stick to this name here or rename both of them using the same rule

IMO NFT prefix is redundant here
___
*[`x/wnft/keeper/keeper.go` line 29 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEItCH8vqg6AHhvU2A:-NKEItCICiCvXu-bGOYM:b-c8uvfi) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L29)):*
> ```Go
> 
> // Send overwrites Send method of the original keeper.
> func (wk NFTKeeperWrapper) Send(goCtx context.Context, msg *nft.MsgSend) (*nft.MsgSendResponse, error) {
> ```

I disagree with this approach
In bank wrapper we didn't copy core logic but instead we wrapped original keeper and call `k.BaseKeeper.SendCoins`
But here we copy whole logic from original nft

so I think it should look smth like this:
```golang
func (wk NFTKeeperWrapper) Send(goCtx context.Context, msg *nft.MsgSend) (*nft.MsgSendResponse, error) {

	if err := wk.assetNFTProvider.BeforeTransfer(ctx, classID, nftID, receiver); err != nil {
		return err
	}

        	return wk.BaseKeeper.Send(ctx, classID, nftID, receiver)
}
```
___
*[`x/wnft/keeper/keeper.go` line 63 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEGj_q9DYiRKMzLL0p:-NKEGj_r18a2CTdkccg3:b78zjvm) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L63)):*
> ```Go
> }
> 
> // Transfer overwrites the original transfer function to include the
> ```

finalize comment
___
*[`x/wnft/types/exptected_keepers.go` line 6 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKELfUZ-3Wpu6HAk50-:-NKELfUZ-3Wpu6HAk500:b-i6jp30) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/types/exptected_keepers.go#L6)):*
> ```Go
> 
> // AssetNFTProvider defines the interface to intercept within nft method calls
> type AssetNFTProvider interface {
> ```

unify with bank `FungibleTokenProvider`

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: 4 of 7 files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 163 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NJxyhw59ZoL0SpCCsqa:-NKIY1MG6sK030FRFIUq:b-kebmwu) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/app/app.go#L163)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

same question
</blockquote></details>

are you questioning the ordering of the modules ? in that case the ordering does not really matter , but I will move it back to where the original was. 
___
*[`x/asset/nft/keeper/before.go` line 8 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEGJG_-O0eE20VF4bz:-NKIa9TB9pN05vJzSw6b:bec9o96) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/asset/nft/keeper/before.go#L8)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

in nft msg is called MsgSend so it should be `BeforeSend` IMO
or we BeforeTransfer in FT ?
</blockquote></details>

the keeper Method is called Transfer, hence we have BeforeTransfer. we are actually intercepting the keeper method, not the proto message. 
___
*[`x/wnft/keeper/keeper.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEL5wp4jVv2HLdKWhA:-NKIaOmd1GXtf68hvBKm:b53s1fm) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L15)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I propose to unify naming logic between wbank & wnft
So there it is named `BaseKeeperWrapper` so we should stick to this name here or rename both of them using the same rule

IMO NFT prefix is redundant here
</blockquote></details>

we have BaseKeeperWrapper in FT since the original Keeper is called BaseKeeper. But here we don't have BaseKeeper, only keeper. 
___
*[`x/wnft/keeper/keeper.go` line 29 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NJxyxt25w9U8dNUZGff:-NKIbL1FDzxwriV0ZItZ:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L29)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Add the comment plz, that it's copy.
</blockquote></details>

Done.
___
*[`x/wnft/keeper/keeper.go` line 29 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEItCH8vqg6AHhvU2A:-NKIblbi1zMWXSgg2fI4:b6elt02) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L29)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I disagree with this approach
In bank wrapper we didn't copy core logic but instead we wrapped original keeper and call `k.BaseKeeper.SendCoins`
But here we copy whole logic from original nft

so I think it should look smth like this:
```golang
func (wk NFTKeeperWrapper) Send(goCtx context.Context, msg *nft.MsgSend) (*nft.MsgSendResponse, error) {

	if err := wk.assetNFTProvider.BeforeTransfer(ctx, classID, nftID, receiver); err != nil {
		return err
	}

        	return wk.BaseKeeper.Send(ctx, classID, nftID, receiver)
}
```
</blockquote></details>

the send function is part of the protobuf message handler and not the keeper itself. The reason why we cannot do the same as we did with bank is that the bank module is using an interface, but the nft module is using an struct, so we cannot owerwrite the keeper logic by wrapping the interface. We copy the Send module to change a single line so our custom intercepted logic is called. 
___
*[`x/wnft/keeper/keeper.go` line 63 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEGj_q9DYiRKMzLL0p:-NKIc_SD0X5oCrZ82U0k:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L63)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

finalize comment
</blockquote></details>

Done.
___
*[`x/wnft/types/exptected_keepers.go` line 6 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKELfUZ-3Wpu6HAk50-:-NKIckSaAEmaeLQKWjrs:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/types/exptected_keepers.go#L6)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

unify with bank `FungibleTokenProvider`
</blockquote></details>

Done.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`app/app.go` line 163 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NJxyhw59ZoL0SpCCsqa:-NKIhB1-Cz-lF7qwGzxc:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/app/app.go#L163)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

are you questioning the ordering of the modules ? in that case the ordering does not really matter , but I will move it back to where the original was. 
</blockquote></details>

ok
___
*[`x/asset/nft/keeper/before.go` line 8 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEGJG_-O0eE20VF4bz:-NKIiv19E-MhLIutphf0:bcrcp50) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/asset/nft/keeper/before.go#L8)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the keeper Method is called Transfer, hence we have BeforeTransfer. we are actually intercepting the keeper method, not the proto message. 
</blockquote></details>

Let discuss on the call
___
*[`x/wnft/keeper/keeper.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEL5wp4jVv2HLdKWhA:-NKIgHk-9_n4oVFTdb1m:bzcf33k) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L15)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we have BaseKeeperWrapper in FT since the original Keeper is called BaseKeeper. But here we don't have BaseKeeper, only keeper. 
</blockquote></details>

then just KeeperWrapper since it is already inside nft module
___
*[`x/wnft/keeper/keeper.go` line 29 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEItCH8vqg6AHhvU2A:-NKIiWX34Hge2wPgX8sG:b-qfgd3e) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L29)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the send function is part of the protobuf message handler and not the keeper itself. The reason why we cannot do the same as we did with bank is that the bank module is using an interface, but the nft module is using an struct, so we cannot owerwrite the keeper logic by wrapping the interface. We copy the Send module to change a single line so our custom intercepted logic is called. 
</blockquote></details>

I'm a bit confused by this now
Seems like another strange decision from cosmos

lets discuss on the call 
As far as I got 
keeper has `Send` method but msg server has `Transfer` while you combine both here

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/wnft/keeper/keeper.go` line 29 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEItCH8vqg6AHhvU2A:-NKIkHe966pCl6L1KbAW:b7srvmn) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L29)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm a bit confused by this now
Seems like another strange decision from cosmos

lets discuss on the call 
As far as I got 
keeper has `Send` method but msg server has `Transfer` while you combine both here 
</blockquote></details>

We copy the code in the bank wrapper as well.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/wnft/keeper/keeper.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEL5wp4jVv2HLdKWhA:-NKIlF403-pSa2a2navc:b-th8k6z) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L15)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

then just KeeperWrapper since it is already inside nft module
</blockquote></details>

linter complains, saying that `using KeeperWrapper.Keeper stutters` I will use `BaseKeerpWrapper` which was you original suggestion.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/wnft/keeper/keeper.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEL5wp4jVv2HLdKWhA:-NKInTCT91zb2XULNM8g:bmle038) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L15)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

linter complains, saying that `using KeeperWrapper.Keeper stutters` I will use `BaseKeerpWrapper` which was you original suggestion. 
</blockquote></details>

Linter wants you to call it `Wrapper` :-)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/wnft/keeper/keeper.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEL5wp4jVv2HLdKWhA:-NKIqN687zkFYCGBKxEr:b-f1d3e2) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L15)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Linter wants you to call it `Wrapper` :-)
</blockquote></details>

I am fine with Wrapper as well. @ysv WDYT ?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 1 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/nft/simulation/operations_test.go` line 101 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKMg-BxASxVpenAnM6j:-NKMg-BxASxVpenAnM6k:b5k1lgy) ([raw file](https://github.com/coreumfoundation/coreum/blob/4277d5d4ccad8c21a895b7c0edd69aab3546c957/x/nft/simulation/operations_test.go#L101)):*
> ```Go
> 	// execute operation
> 	registry := suite.app.InterfaceRegistry()
> 	op := simulation.SimulateMsgSend(codec.NewProtoCodec(registry), suite.app.AccountKeeper, suite.app.BankKeeper, suite.app.NFTKeeper.Keeper)
> ```

why is the original kddper passed to the simapp instead of wrapped implementation?
___
*[`x/wnft/keeper/keeper.go` line 16 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKMgSgS-Oh2ZTrOQz0-:-NKMgSgS-Oh2ZTrOQz00:b-hq8ewt) ([raw file](https://github.com/coreumfoundation/coreum/blob/4277d5d4ccad8c21a895b7c0edd69aab3546c957/x/wnft/keeper/keeper.go#L16)):*
> ```Go
> // BaseKeeperWrapper wraps the original nft keeper and intercepts its original methods if needed
> type BaseKeeperWrapper struct {
> 	nftkeeper.Keeper
> ```

I don't like the fact that original keeper is exposed publicly, I would prefer to hide it in unexported field

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: all files reviewed, 5 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/keeper/before.go` line 8 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEGJG_-O0eE20VF4bz:-NKNCrJk1u8UsQeoKY5i:be2vz6k) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/asset/nft/keeper/before.go#L8)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Let discuss on the call
</blockquote></details>

Discussed on the call, and decided to keep it. 
___
*[`x/nft/simulation/operations_test.go` line 101 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKMg-BxASxVpenAnM6j:-NKNEJWh9Bj7BnpdthOo:b-4kw45a) ([raw file](https://github.com/coreumfoundation/coreum/blob/4277d5d4ccad8c21a895b7c0edd69aab3546c957/x/nft/simulation/operations_test.go#L101)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why is the original kddper passed to the simapp instead of wrapped implementation?
</blockquote></details>

actually it is wrapped keeper, in other words there is only one keeper and that is the wrapped keeper. 
I renamed it to `WNFTKeeper` to avoid confusion. 
___
*[`x/wnft/keeper/keeper.go` line 29 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEItCH8vqg6AHhvU2A:-NKNDp10BDDHO19YhxuN:bl68don) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L29)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We copy the code in the bank wrapper as well.
</blockquote></details>

Decided on the call to keep it as it is. 
___
*[`x/wnft/keeper/keeper.go` line 16 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKMgSgS-Oh2ZTrOQz0-:-NKNEa-41vgEuav-alWt:b-hfcuqf) ([raw file](https://github.com/coreumfoundation/coreum/blob/4277d5d4ccad8c21a895b7c0edd69aab3546c957/x/wnft/keeper/keeper.go#L16)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't like the fact that original keeper is exposed publicly, I would prefer to hide it in unexported field
</blockquote></details>

we are embeding the original keeper to avoid copying every method in this module. So it is a tradeoff, if we make it private, we will need to copy every method of the original keeper here.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: 3 of 10 files reviewed, 5 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`x/wnft/keeper/keeper.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEL5wp4jVv2HLdKWhA:-NKJfuD-2IHaJ7jmQxix:b-kzvyw2) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L15)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I am fine with Wrapper as well. @ysv WDYT ?
</blockquote></details>

Wrapper / KeeperWrapper
___
*[`x/wnft/keeper/keeper.go` line 29 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEItCH8vqg6AHhvU2A:-NKJiNhLCfzdGFBpc2k_:bycbpoj) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L29)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We copy the code in the bank wrapper as well.
</blockquote></details>

lets keep it

**Review by ysv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`x/wnft/keeper/keeper.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKEL5wp4jVv2HLdKWhA:-NKOifBJ-fz690jDxsHL:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/7c4d6017c23075c585d901ad17296c926ad579e8/x/wnft/keeper/keeper.go#L15)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Wrapper / KeeperWrapper
</blockquote></details>

ok

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @silverspase)

___
*[`app/app.go` line 250 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKTGQ_v6D4FOCIf4e4c:-NKTGQ_wDkInCDX0wfPQ:b-9oxhco) ([raw file](https://github.com/coreumfoundation/coreum/blob/64f08ea820da68e376f36d9d039cb9eaed6ec739/app/app.go#L250)):*
> ```Go
> 	FeeModelKeeper     feemodelkeeper.Keeper
> 	BankKeeper         wbankkeeper.BaseKeeperWrapper
> 	WNFTKeeper         wnftkeeper.Wrapper
> ```

Actually for wrapped bank keeper we don't use `W` prefix

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

___
*[`app/app.go` line 250 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/311#-NKTGQ_v6D4FOCIf4e4c:-NKXg1XgCGfwWW6gMVGI:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/64f08ea820da68e376f36d9d039cb9eaed6ec739/app/app.go#L250)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Actually for wrapped bank keeper we don't use `W` prefix
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/311)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
