### PR TITLE
Implement mint and burn asset functionality

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)

### CODE REVIEW

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`proto/coreum/asset/v1/event.proto` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NGvhvax9cKt63ikfkCu:-NGvhvax9cKt63ikfkCv:bj7hb7) ([raw file](https://github.com/coreumfoundation/coreum/blob/457492d16235a04a2986b087096c31a658d363bd/proto/coreum/asset/v1/event.proto#L34)):*
> ```protobuf
> }
> 
> message EventFungibleTokenMinted {
> ```

merge 2 events  to updated total supply and provide sender.
Also look into bank module if events are sufficient then we don't need to emit ant events at all.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: 0 of 18 files reviewed, 7 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/asset/mint.go` line 134 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9Eeaf4rpURj4mMRFp:-NH9Eeaf4rpURj4mMRFq:b9e1xba) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/integration-tests/asset/mint.go#L134)):*
> ```Go
> 		mintMsg,
> 	)
> 	requireT.NoError(err)
> ```

What about mint and bun events? Why don't you check them?



_Code quote:_
```Go
requireT
```
___
*[`x/asset/client/cli/tx.go` line 239 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9DO3f6k2Ps10rjbSq:-NH9DO3gDYkhntGBxAm6:b5z95dr) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/client/cli/tx.go#L239)):*
> ```Go
> 		Use:   "mint [amount] --from [sender]",
> 		Args:  cobra.ExactArgs(1),
> 		Short: "mint new supply of fungible token",
> ```

The comment is confusing, the `amount` is a better word here (same for all such comments).
___
*[`x/asset/keeper/issue.go` line 164 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9C15H410od_hsYh2F:-NH9C15H410od_hsYh2G:b5tjclc) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/keeper/issue.go#L164)):*
> ```Go
> 
> 	coinsToBurn := sdk.NewCoins(coin)
> 	if err := k.bankKeeper.SendCoinsFromAccountToModule(ctx, account, types.ModuleName, coinsToBurn); err != nil {
> ```

If the coin is frozen can you burn it?
___
*[`x/asset/keeper/keeper.go` line 41 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9B_MK-6VBPncCai69:-NH9B_MK-6VBPncCai6A:b-962y0c) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/keeper/keeper.go#L41)):*
> ```Go
> 
> // MintFungibleToken mints new fungible token
> func (k Keeper) MintFungibleToken(ctx sdk.Context, sender sdk.AccAddress, coin sdk.Coin) error {
> ```

IMHO it's a good practice to have test for keeper as well as integration tests, in sich tests you can deeply check the functionality 
___
*[`x/asset/keeper/keeper.go` line 51 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9CLnj29hHAW8v7Fo6:-NH9CLnj29hHAW8v7Fo7:b-nfe4ul) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/keeper/keeper.go#L51)):*
> ```Go
> 
> // BurnFungibleToken burns fungible token
> func (k Keeper) BurnFungibleToken(ctx sdk.Context, sender sdk.AccAddress, coin sdk.Coin) error {
> ```

I didn't get the logical location of those functions in the files.
___
*[`x/asset/types/msgs.go` line 93 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9ER7L-PXyGh4d57Kw:-NH9ER7L-PXyGh4d57Kx:b-zdvn8d) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/types/msgs.go#L93)):*
> ```Go
> 
> // ValidateBasic checks that message fields are valid
> func (msg MsgMintFungibleToken) ValidateBasic() error {
> ```

Tests?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/client/cli/mint_burn_test.go` line 28 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9WfSC5UxYHY9RT2t2:-NH9WfSC5UxYHY9RT2t3:b-bdbck9) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/client/cli/mint_burn_test.go#L28)):*
> ```Go
> 
> 	// the denom must start from the letter
> 	symbol := "l" + uuid.NewString()[:4]
> ```

do we need to use uuid? Could we use a constant instead. Accounts are unique anyway so two same tokens won't be created anywaya
___
*[`x/asset/keeper/issue.go` line 164 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9C15H410od_hsYh2F:-NH9VNCp3cSdF2SJZQB_:b-xdsa5o) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/keeper/issue.go#L164)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

If the coin is frozen can you burn it?
</blockquote></details>

The real problem is that asset keeper does not use wrapped bank to make sends. All the limitations checked in the wrapper should apply to operations done by asset keeper.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/asset/mint.go` line 134 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9Eeaf4rpURj4mMRFp:-NHA2hT_9Z-c033LigAJ:b-rjw58w) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/integration-tests/asset/mint.go#L134)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

well those events are emitted by bank module, they seem to be beyond the scope of the asset module.
</blockquote></details>

But we decided not to create our own because of the those events, see they should be checked. 
___
*[`x/asset/client/cli/tx.go` line 239 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9DO3f6k2Ps10rjbSq:-NHA3JDb1GFKNqUKnV4L:boeuhqq) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/client/cli/tx.go#L239)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Don't see the changes
___
*[`x/asset/keeper/issue.go` line 164 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9C15H410od_hsYh2F:-NHA3_MS7LQ9P6BgAbVc:bxgbiv2) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/keeper/issue.go#L164)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

since the issuer is the one who is burning, and they are the admin, they should be able to burn as they wish. 
</blockquote></details>

We should confirm it within the team. 
___
*[`x/asset/keeper/keeper.go` line 51 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9CLnj29hHAW8v7Fo6:-NHA3jo_7OZ4Mj-JispM:b-u28gbp) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/keeper/keeper.go#L51)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Do you want to move these into mint.go and burn.go ?
</blockquote></details>

Not sure. :-) But probably we should re-think the whole idea, it'll resolve that comment.
___
*[`x/asset/types/msgs.go` line 93 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9ER7L-PXyGh4d57Kw:-NHA3xCkEHhqqg2nVUm3:b-x7zxdc) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/types/msgs.go#L93)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Don't see them.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: 15 of 19 files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/client/cli/tx.go` line 239 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9DO3f6k2Ps10rjbSq:-NHA4RYj2C7gGTH8pfIM:bx2vedd) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/client/cli/tx.go#L239)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Don't see the changes
</blockquote></details>

check again plz
___
*[`x/asset/types/msgs.go` line 93 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9ER7L-PXyGh4d57Kw:-NHA4ZRDCQYBjQ5UpyZJ:b-vf66zh) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/types/msgs.go#L93)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Don't see them.
</blockquote></details>

check again

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: 15 of 19 files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/asset/mint.go` line 134 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9Eeaf4rpURj4mMRFp:-NHA4gmRC4umADWZ8lDL:b997rui) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/integration-tests/asset/mint.go#L134)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But we decided not to create our own because of the those events, see they should be checked. 
</blockquote></details>

I mean emitting those events and making sure that it works correctly is the responsiblity of the bank module.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: 15 of 19 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/asset/keeper/keeper.go` line 41 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9B_MK-6VBPncCai69:-NHODyMS0jmcbjRppgOI:b-liuuij) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/keeper/keeper.go#L41)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I agree only if there are use cases which are not covered by integration tests. but here I see no added value. 
</blockquote></details>

I would say there are layers:
1. unit tests
2. integration tests

Lower layer (1) should not depend on the existence of higher layer (2). If sth can be easily tested in unit tests, it should be IMO, despite the fact that scope might overlap with integration tests. 
___
*[`x/asset/types/msgs_test.go` line 203 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHOEu8f0a86G3tpa8GJ:-NHOEu8f0a86G3tpa8GK:b-9qcwa7) ([raw file](https://github.com/coreumfoundation/coreum/blob/a891602a2978d45b4d0b5e27589474007612ef22/x/asset/types/msgs_test.go#L203)):*
> ```Go
> 	}
> 
> 	testCases := []struct {
> ```

I'm not blocking here, but have to say that this is the most indirect way of verifying two error cases I've seen in my life :-)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/keeper/issue.go` line 164 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9C15H410od_hsYh2F:-NHOFgHn01Zgz4d6EAZ8:bpjqhnc) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/keeper/issue.go#L164)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We should confirm it within the team. 
</blockquote></details>

We discussed that we want to call one function everywhere which verifies permissions and will support ACLs in the future.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/issue.go` line 164 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NH9C15H410od_hsYh2F:-NHOENlc7QDL59Bfg-WM:b7dja2i) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d7032d64269effbb49739dc9bacc0421cea8eea/x/asset/keeper/issue.go#L164)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

We discussed that we want to call one function everywhere which verifies permissions and will support ACLs in the future.
</blockquote></details>

I call areCoinsSpendable there.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/keeper/keeper_test.go` line 1 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHOWT9y4ejUIBwTTKLW:-NHOWT9y4ejUIBwTTKLX:bkdmftv) ([raw file](https://github.com/coreumfoundation/coreum/blob/d8996e215e3afb155dc02766affccca0457c017d/x/asset/keeper/keeper_test.go#L1)):*
> ```Go
> package keeper_test
> ```

shouldn't the file be renamed to mintburn_test.go?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/keeper/keeper_test.go` line 1 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHOWT9y4ejUIBwTTKLW:-NHOXnPhDs26rhvNdpd_:b-4zile2) ([raw file](https://github.com/coreumfoundation/coreum/blob/d8996e215e3afb155dc02766affccca0457c017d/x/asset/keeper/keeper_test.go#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

shouldn't the file be renamed to mintburn_test.go?
</blockquote></details>

it could, but I am following the logic that if there is mint.go, then mint_test.go will be there. 
Do you think I should create `mint.go` and `burn.go` and move the corresponding functionalities there ?

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68)

___
*[`x/asset/keeper/keeper.go` line 71 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHP87aaApYypGYdC35m:-NHP87aaApYypGYdC35n:boevgj5) ([raw file](https://github.com/coreumfoundation/coreum/blob/63fd0eef14c5a9c674cfd7e29fc974e36692067c/x/asset/keeper/keeper.go#L71)):*
> ```Go
> 
> 	if ft.Issuer != sender.String() {
> 		return sdkerrors.Wrap(sdkerrors.ErrUnauthorized, "address is unauthorized to perform this operation")
> ```

can you please include address in error msg ?
___
*[`x/asset/types/msgs.go` line 93 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHP6T0TDGJrcusXn58Y:-NHP6T0TDGJrcusXn58Z:b-vaopuu) ([raw file](https://github.com/coreumfoundation/coreum/blob/63fd0eef14c5a9c674cfd7e29fc974e36692067c/x/asset/types/msgs.go#L93)):*
> ```Go
> 	}
> 
> 	return msg.Coin.Validate()
> ```

shouldn't we use our validation here which is more strict than cosmos one ?

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHPAJeeCdiiAge7PODA:-NHPAJef6XkQ9yzuhqqN:bafd5w3) (no related file):*
I didn't review the whole PR because there are already 2 approvals instead I checked the most critical parts only.

___

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHPC_Gz7iMQiV5lhpWM:-NHPC_Gz7iMQiV5lhpWN:b-by585q) (no related file):*
Is there a test where you check that total supply query returns correct values before/after minting/burning ?

___

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 4 unresolved discussions (waiting on @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHPAJeeCdiiAge7PODA:-NHPEFHdBQW4XK7-YJ-c:b32w0x) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I didn't review the whole PR because there are already 2 approvals instead I checked the most critical parts only.
</blockquote></details>

OK

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHPC_Gz7iMQiV5lhpWM:-NHPEAvP5zXztLXU1Jc0:b-67hj82) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Is there a test where you check that total supply query returns correct values before/after minting/burning ?
</blockquote></details>

Yes there is, both integration tests and keeper tests

___
___
*[`x/asset/keeper/keeper.go` line 71 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHP87aaApYypGYdC35m:-NHPFAgh4S3dUsk6SU6c:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/63fd0eef14c5a9c674cfd7e29fc974e36692067c/x/asset/keeper/keeper.go#L71)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can you please include address in error msg ?
</blockquote></details>

Done.
___
*[`x/asset/types/msgs.go` line 93 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHP6T0TDGJrcusXn58Y:-NHPW_716HzazX9QBrrz:bz5b8hf) ([raw file](https://github.com/coreumfoundation/coreum/blob/63fd0eef14c5a9c674cfd7e29fc974e36692067c/x/asset/types/msgs.go#L93)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

shouldn't we use our validation here which is more strict than cosmos one ?
</blockquote></details>

I don't think that actually adds much value. if they provide the wrong token, then simply it will not be found.

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`x/asset/types/msgs.go` line 93 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHP6T0TDGJrcusXn58Y:-NHQIB4Q-RaYpPRmzdhK:b-aisa1t) ([raw file](https://github.com/coreumfoundation/coreum/blob/63fd0eef14c5a9c674cfd7e29fc974e36692067c/x/asset/types/msgs.go#L93)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think that actually adds much value. if they provide the wrong token, then simply it will not be found. 
</blockquote></details>

well I disagree
I think we should validate as much  as possible (stateless things) at this stage. Why would we do partial validation
At least this could save users funds from not paying fees for obviously wrong tx

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/types/msgs.go` line 93 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHP6T0TDGJrcusXn58Y:-NHTHWb28UyBSCiTW0-j:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/63fd0eef14c5a9c674cfd7e29fc974e36692067c/x/asset/types/msgs.go#L93)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

well I disagree
I think we should validate as much  as possible (stateless things) at this stage. Why would we do partial validation
At least this could save users funds from not paying fees for obviously wrong tx

</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: 19 of 21 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/types/msgs.go` line 57 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHUJQAQ6N-Zfbaxy_sJ:-NHUJQAQ6N-Zfbaxy_sK:bmmdthd) ([raw file](https://github.com/coreumfoundation/coreum/blob/83bc8749a60ee2de3fe70ec52283e4142758d186/x/asset/types/msgs.go#L57)):*
> ```Go
> 	}
> 
> 	if err := ValidateSymbol(msg.Coin.Denom); err != nil {
> ```

You don't nee to validate it here and in the next strep as well, if it's invalid it won't be found and that is it

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 6 of 7 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/types/msgs.go` line 57 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHUJQAQ6N-Zfbaxy_sJ:-NHUL3Bx3QlMtnzf5Hcd:btj5m3v) ([raw file](https://github.com/coreumfoundation/coreum/blob/83bc8749a60ee2de3fe70ec52283e4142758d186/x/asset/types/msgs.go#L57)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You don't nee to validate it here and in the next strep as well, if it's invalid it won't be found and that is it
</blockquote></details>

actually if you look below, I made the same argument with yaroslav in the comment, but he thinks otherwise.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/asset/types/msgs.go` line 93 at r6](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHP6T0TDGJrcusXn58Y:-NHY9bI88YT3Pj7xXVFY:bjyayju) ([raw file](https://github.com/coreumfoundation/coreum/blob/63fd0eef14c5a9c674cfd7e29fc974e36692067c/x/asset/types/msgs.go#L93)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't see the change 
</blockquote></details>

look few lines above.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`proto/coreum/asset/v1/asset.proto` line 9 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHYOo7XD7EGbStYwsjy:-NHYOo7XD7EGbStYwsjz:baeppnu) ([raw file](https://github.com/coreumfoundation/coreum/blob/83bc8749a60ee2de3fe70ec52283e4142758d186/proto/coreum/asset/v1/asset.proto#L9)):*
> ```protobuf
> 
> enum FungibleTokenFeature {
>   freezable = 0;
> ```

please rename it to freeze, mint and burn

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: 12 of 24 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`proto/coreum/asset/v1/asset.proto` line 9 at r8](https://reviewable.io/reviews/coreumfoundation/coreum/258#-NHYOo7XD7EGbStYwsjy:-NHYXapgA1sk_bvbksP-:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/83bc8749a60ee2de3fe70ec52283e4142758d186/proto/coreum/asset/v1/asset.proto#L9)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

please rename it to freeze, mint and burn
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: 12 of 24 files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 5 of 17 files at r2, 1 of 4 files at r3, 4 of 7 files at r5, 1 of 1 files at r8, 12 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @wojtek-coreum)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 12 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil)

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/258)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
