### PR TITLE
Add DEX test with IBC

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/996)

### CODE REVIEW

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/996)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/996)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/996)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @ysv)

___
*[`integration-tests/ibc/dex_test.go` line 183 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/996#-O8vAYsv-JqQHVoI8YgJ:-O8vAYsv-JqQHVoI8YgK:b-fulf03) ([raw file](https://github.com/CoreumFoundation/coreum/blob/45b6555eb8948ecf2e058e74efbeb8838f87f50d/integration-tests/ibc/dex_test.go#L183)):*
> ```Go
> }
> 
> func issueFT(
> ```

Are you sure that you need a method for it to call it once?

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/996)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/ibc/dex_test.go` line 183 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/996#-O8vAYsv-JqQHVoI8YgJ:-O8vB9x2BulZDQ1b4eP2:biiy1p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/45b6555eb8948ecf2e058e74efbeb8838f87f50d/integration-tests/ibc/dex_test.go#L183)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Are you sure that you need a method for it to call it once?
</blockquote></details>

This is the first test here. It can be used in future tests. And also it simplifies the test. IMO it doesn't hurt to keep it

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/996)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/996)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/996)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/996)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/996)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
