### PR TITLE
first part of addressing comments

### PR DESCRIPTION
**Pull request by vertex451**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)

### CODE REVIEW

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: 0 of 23 files reviewed, 8 unresolved discussions

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s4XH32mNkdvKfVf7j:-NaBQcor9ibgA5IDDBBz:bv2rvfa) (no related file):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>


</blockquote></details>

So, should we add the mainnet or remove the testnet? Also, if we remove the testnet - there is no tests in testcases - should I remove the whole test in this case?

___

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: 0 of 23 files reviewed, 8 unresolved discussions

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s57UN4YHrvX8HU78D:-NaBRvZp7ACURQRI7vIM:b22hydg) (no related file):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>


</blockquote></details>

Who know the answer?

___

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: 0 of 23 files reviewed, 8 unresolved discussions

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s5E--2aa0PkyjQV6i:-NaBS99R6zrkmTB5obZw:b-8b73xd) (no related file):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>

So, what does `or class is optional mean`? Do you mean suffix in the function name?
</blockquote></details>

@ysv 

___

**Review by vertex451 — COMMENTED** [review]
Ignore this, I added the screenshot with full comment list in the end

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-:-NaBSG8L-8g0dLIRydPm:b-pw78la)* status: 0 of 23 files reviewed, 8 unresolved discussions

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: 0 of 23 files reviewed, 9 unresolved discussions (waiting on @vertex451)

___
*[`README.md` line 107 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-NaBWqeMCbfqVGgaVmk7:-NaBWqeMCbfqVGgaVmk8:b-vemxpp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c147c460e88e436a6ed2b4c6a0d57edeb79dc0fb/README.md#L107)):*
> ```Markdown
> 
> ```
> $ cored status --chain-id=coreum-testnet-1 --node=https://full-node.testnet-1.coreum.dev:26657
> ```

Why testnet here, I thought the example for the znet mostly, which uses the devnet prefix?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: 0 of 23 files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @vertex451, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s5E--2aa0PkyjQV6i:-NaBcelz9KTJ2WNitdK8:b1f0jso) (no related file):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>

@ysv 
</blockquote></details>

Proper name for this func seems to be GetBurntByClass
But I'm not sure if class arg is optional. If it is optional then current name is ok.
If it is required then should be renamed 

___

**Review by ysv — COMMENTED** [review]
> Reviewed 20 of 22 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s4IPM4x88h4zLLa1p:-NaBe997D-RuDd9uWJhV:b-la2vic) (no related file):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>


</blockquote></details>

so is it possible to simplify ?

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s4RSb5OWktZD0LmgM:-NaBeFT_CEm6NNUt1_zf:b893e67) (no related file):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>


</blockquote></details>

saw in PR looks correct
Pls check other places also

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s4XH32mNkdvKfVf7j:-NaBd6r524EmINko9jJe:bfazp71) (no related file):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>

So, should we add the mainnet or remove the testnet? Also, if we remove the testnet - there is no tests in testcases - should I remove the whole test in this case?
</blockquote></details>

remove whole test I think

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s4rvY8shBIWqPDRL5:-NaBdAxT6JRoT_zXVMUK:b-f7ey50) (no related file):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>


</blockquote></details>

@miladz68 @dzmitryhil @wojtek-coreum WDYT ?
I think we agreed to hardcode everything because currently we have some values hardcoded (for denom) while other are still passed

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s50uK1uhVKXkuktXz:-NaBeNnb59n0I9d76jmJ:b-n3m3dh) (no related file):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>


</blockquote></details>

pls do this change

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s57UN4YHrvX8HU78D:-NaBeQgz2dEh4e3AYy5j:b-1znrdm) (no related file):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>

Who know the answer?
</blockquote></details>

maybe @miladz68 or @dzmitryhil  ?

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_sBbKk1OlxeB_jJYCg:-NaBdYO59LjtnJlm-16H:b-lpmae) (no related file):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>


</blockquote></details>

check this in other places 
We should use smth like: `assefttypes.CurrentTokenVersion` directly here

___
___
*[`README.md` line 107 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-NaBWqeMCbfqVGgaVmk7:-NaBdj8SAEvFnynLX8VQ:bseqtb1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c147c460e88e436a6ed2b4c6a0d57edeb79dc0fb/README.md#L107)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why testnet here, I thought the example for the znet mostly, which uses the devnet prefix?
</blockquote></details>

I'm ok with testnet it is more stable

I think the issue was that chain-id is devnet but URL is testnet

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @vertex451, and @wojtek-coreum)

___
*[`README.md` line 107 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-NaBWqeMCbfqVGgaVmk7:-NaBqTF36STTaZty81b5:b2nhll9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c147c460e88e436a6ed2b4c6a0d57edeb79dc0fb/README.md#L107)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm ok with testnet it is more stable

I think the issue was that chain-id is devnet but URL is testnet
</blockquote></details>

Ok.

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: 16 of 26 files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s4RSb5OWktZD0LmgM:-NaHTRtU8bvWsmRmiZNb:bu7duvj) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

saw in PR looks correct
Pls check other places also
</blockquote></details>

Added better error assertion.

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s4XH32mNkdvKfVf7j:-NaGtU4o50i4grLWPPZP:ba3dfob) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

remove whole test I think
</blockquote></details>

Removed

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s4rvY8shBIWqPDRL5:-NaHVDDCDD_T6OtDQlVo:bvfc7b8) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you have a link to prev comment it's hard to understand based on the screenshot. 
</blockquote></details>

https://reviewable.io/reviews/CoreumFoundation/coreum/560#-N_3zYAxAoa69Y_3wpfg @dzmitryhil 

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s50uK1uhVKXkuktXz:-NaGzl8z0NykfIXW38r1:b-wwp26y) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

pls do this change
</blockquote></details>

Changed to:
```
// If the transfer is incoming or rate is nil or negative - return nil  
if wibctransfertypes.IsPurposeIn(ctx) || rate.IsNil() || !rate.IsPositive() {  
   return nil  
}
```

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s57UN4YHrvX8HU78D:-NaHVGrh7fZeHAlmj-wK:bmm962g) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Since by default use uses the SDK defaults, and the denom is stake. 
</blockquote></details>

So, no action items are needed, right?

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s5E--2aa0PkyjQV6i:-NaGtugW4YiDgEDz8Gxv:b1o2tay) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Proper name for this func seems to be GetBurntByClass
But I'm not sure if class arg is optional. If it is optional then current name is ok.
If it is required then should be renamed 
</blockquote></details>

ClassID is used in CreateClassBurningKey, which returns an error in case of classID is not valid. So it is not optional, keeping the name GetBurntByClass.

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_sBbKk1OlxeB_jJYCg:-NaHBFW_2QFwpqCgZ9MX:b-7di9cc) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

check this in other places 
We should use smth like: `assefttypes.CurrentTokenVersion` directly here
</blockquote></details>

changed to `assetfttypes.CurrentTokenVersion`, thanks for the pointing out.

___

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: 16 of 26 files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s4IPM4x88h4zLLa1p:-NaHpEHLAzPz73I7Uh9E:b-4vb90e) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so is it possible to simplify ?
</blockquote></details>

We cannot compare it this way because those classes are from different packages:
x/asset/nft/types/nft.pb.go and integration-tests/contracts/modules/nft.go
That's why we need reassigning

___

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @vertex451, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s4rvY8shBIWqPDRL5:-NaLNNc14gd4e3waMH-R:b-v2ekol) (no related file):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>

https://reviewable.io/reviews/CoreumFoundation/coreum/560#-N_3zYAxAoa69Y_3wpfg @dzmitryhil 
</blockquote></details>

Yes, we decided to keep it as is. 

___

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 7 of 22 files at r1, 4 of 10 files at r3, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68 and @vertex451)

___
*[`pkg/config/network_test.go` line 167 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-NaLOZ2E07C1PrqB_1nT:-NaLOZ2E07C1PrqB_1nU:b-6hc1wl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2b49e30950b47f0967d92e4a787e9fdacfd1c2b6/pkg/config/network_test.go#L167)):*
> ```Go
> }
> 
> func TestGenesisCoreTotalSupply(t *testing.T) {
> ```

why is it removed?
___
*[`x/asset/ft/keeper/before_send.go` line 136 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-NaLOjvF0eGFvS3eqOqk:-NaLOjvF0eGFvS3eqOql:bma6mfk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bfae081d19a9ba637eef53dfdf3406a05bc2a769/x/asset/ft/keeper/before_send.go#L136)):*
> ```Go
> 	// amount * rate * min(non_issuer_inputs_sum, non_issuer_outputs_sum) / non_issuer_inputs_sum
> 
> 	// If the transfer is incoming or rate is nil or negative - return nil
> ```

I think the IBC condition could be moved to separate `if` statement for clarity. The IBC-related comment could say this:

```
Neither burn rate nor send commission is charged on incoming IBC transfer.
```

And now Is ee we should do the same for rejected and timed-out transfers (!!!)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 4 of 22 files at r1, 2 of 3 files at r2, 3 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68 and @vertex451)

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`pkg/config/network_test.go` line 167 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-NaLOZ2E07C1PrqB_1nT:-NaLiKig95g6QRdFv6mK:b-arichz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2b49e30950b47f0967d92e4a787e9fdacfd1c2b6/pkg/config/network_test.go#L167)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why is it removed?
</blockquote></details>

This line is present in my branch, could you specify?

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s50uK1uhVKXkuktXz:-NaLicun7pvhUPkbCHSh:bct5v9m) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

```
If the transfer is incoming
```
but it is not just incoming it is IBC incoming
</blockquote></details>

Renamed to
```
// If the transfer is incoming from IBC or the rate is nil or negative - return nil
```

___

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @vertex451)

___
*[`pkg/config/network_test.go` line 167 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-NaLOZ2E07C1PrqB_1nT:-NaN1zIo7SNCB7pg-8U0:bceu4x5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2b49e30950b47f0967d92e4a787e9fdacfd1c2b6/pkg/config/network_test.go#L167)):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>

This line is present in my branch, could you specify?
</blockquote></details>

I see test `func TestGenesisCoreTotalSupply` is removed

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/config/network_test.go` line 167 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-NaLOZ2E07C1PrqB_1nT:-NaQQtGs2LDYaefXa-Cu:b-hg84un) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2b49e30950b47f0967d92e4a787e9fdacfd1c2b6/pkg/config/network_test.go#L167)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I see test `func TestGenesisCoreTotalSupply` is removed
</blockquote></details>

Ah, I see, yes, @ysv asked me to do it.
Here is the link to the discussion: https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s4XH32mNkdvKfVf7j
@ysv could you please decide with @wojtek-coreum on this?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/config/network_test.go` line 167 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-NaLOZ2E07C1PrqB_1nT:-NaQRwviAFNAW3boVBJ_:b-duxn4u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2b49e30950b47f0967d92e4a787e9fdacfd1c2b6/pkg/config/network_test.go#L167)):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>

Ah, I see, yes, @ysv asked me to do it.
Here is the link to the discussion: https://reviewable.io/reviews/CoreumFoundation/coreum/578#-N_s4XH32mNkdvKfVf7j
@ysv could you please decide with @wojtek-coreum on this?
</blockquote></details>

@ysv As I understand,  because our genesis for mainnet and testnet are hardcoded, we don't need to verify it anymore, right?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`pkg/config/network_test.go` line 167 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-NaLOZ2E07C1PrqB_1nT:-NaQSBdy7MEQcx-Lj8tp:b-kayxn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2b49e30950b47f0967d92e4a787e9fdacfd1c2b6/pkg/config/network_test.go#L167)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@ysv As I understand,  because our genesis for mainnet and testnet are hardcoded, we don't need to verify it anymore, right?
</blockquote></details>

yes, they are fixed forever so not really needed to run this anymore

**Review by wojtek-coreum — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/578#-:-NaQUVXIBVwp-ZIcz4GF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Pull request merged**
