### PR TITLE
Release static darwin binaries

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Release static darwin binaries.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/886)

### CODE REVIEW

**Review by miladz68 — APPROVED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/886)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/886)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/886)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/886)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/886)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/886)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
