### PR TITLE
update variables of mint module in genesis

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/221)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/221)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/config/genesis/genesis.tmpl.json` line 236 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/221#-NEARjcW0zLtyYPhsLhe:-NEARjcW0zLtyYPhsLhf:b56cd28) ([raw file](https://github.com/coreumfoundation/coreum/blob/8df3771cff3c461e037dc51cf630d7e57e94a321/pkg/config/genesis/genesis.tmpl.json#L236)):*
> ```JSON
>           "escalation_start_fraction": "{{ .FeeModelParams.EscalationStartFraction }}",
>           "max_block_gas": {
>             { .FeeModelParams.MaxBlockGas
> ```

What is with the format ?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/221)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/221)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`pkg/config/genesis/genesis.tmpl.json` line 236 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/221#-NEARjcW0zLtyYPhsLhe:-NEAnQF4-CWjoitdzDsT:b-me5uji) ([raw file](https://github.com/coreumfoundation/coreum/blob/8df3771cff3c461e037dc51cf630d7e57e94a321/pkg/config/genesis/genesis.tmpl.json#L236)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is with the format ?
</blockquote></details>

it is my IDE screwing it up

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/221)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/config/genesis/genesis.tmpl.json` line 154 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/221#-NEAtmcC8Kr7-j2QSlx7:-NEAtmcC8Kr7-j2QSlx8:b-ixywrd) ([raw file](https://github.com/coreumfoundation/coreum/blob/da4fdd4d53972024868016b7d8019fc4fb6f1a7c/pkg/config/genesis/genesis.tmpl.json#L154)):*
> ```JSON
>         "inflation_rate_change": "0.130000000000000000",
>         "inflation_max": "0.200000000000000000",
>         "inflation_min": "0.000000000000000000",
> ```

But we also agreed to set initial inflation to be greater than 0

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/221)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
