### PR TITLE
Implement market order matching

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Implement market order matching

* Integrate new order type
* Implement matching
* Update CLI

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/929)

### CODE REVIEW

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/929)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/dex_test.go` line 196 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/929#-O4nE43W5PlKDAil8K4x:-O4nE43W5PlKDAil8K4y:bb7phvt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1e6ce6e16f3d10cfa705dc3f50ab4c1ddadd2a38/integration-tests/modules/dex_test.go#L196)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// place buy market rder to match the sell
> ```

typo

**Review by miladz68 — APPROVED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/929)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/929)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/929)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
