### PR TITLE
moved docs to docs and left links to docs website in Readmes

### PR DESCRIPTION
**Pull request by vertex451**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/350)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/350)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`docs/chain/cli-env.md` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/350#-NM3iN1wChaTqulHZcck:-NM3iN1wChaTqulHZccl:bfseppw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/02e272220eb5da5d3509e1531e1bf787c25ed19e/docs/chain/cli-env.md#L3)):*
> ```Markdown
> # CLI environment setup
> 
> https://docs.coreum.dev/guides/cli-env.html
> ```

I don't think havings these links are really beneficial. The URLs might change and we must keep these updated. just adding a link to the main docs website in the main README.md should be enough IMO.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/350)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`docs/chain/cli-env.md` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/350#-NM3iN1wChaTqulHZcck:-NM3t1zo7fKqY_Vynl9D:b-kkallj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/02e272220eb5da5d3509e1531e1bf787c25ed19e/docs/chain/cli-env.md#L3)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

I am okay with that, lets see what @ysv will say.
</blockquote></details>

I agree with @miladz68 just leave the link to the docs in the main readme file.

**Review by ysv — APPROVED** [review]
> Reviewed 11 of 18 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/350)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`docs/chain/cli-env.md` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/350#-NM3iN1wChaTqulHZcck:-NM570F73YskOYYVk8W4:b-e8g69u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/02e272220eb5da5d3509e1531e1bf787c25ed19e/docs/chain/cli-env.md#L3)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I agree with @miladz68 just leave the link to the docs in the main readme file.
</blockquote></details>

didn't get which URL you are talking about 
But IMO we should have .md files in coreum in 2 cases:
- main README with link to docs
- in module spec folders

everything else should be fully removed

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/350#-:-NM9EMsr10umnutzkneL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
