### PR TITLE
Changed event type for freeze actions

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/273)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/273)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/273)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`integration-tests/asset/freeze.go` line 241 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/273#-NHjrkzcDg2k5rTWvaz0:-NHjrkzcDg2k5rTWvaz1:bm4hk72) ([raw file](https://github.com/coreumfoundation/coreum/blob/e6626596ac8a347b537cd3f1951fc59d44748a6b/integration-tests/asset/freeze.go#L241)):*
> ```Go
> 		Account:        recipient.String(),
> 		PreviousAmount: sdk.NewCoin(denom, sdk.NewInt(400)),
> 		CurrentAmount:  sdk.NewCoin(denom, sdk.NewInt(200)),
> ```

minor:
would be nice to have a test with resulting `CurrentAmount: 0`. In general and to test event also because it is a special case when we remove key from store
___
*[`proto/coreum/asset/v1/event.proto` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/273#-NHjrT3zCzKdfznoKRSH:-NHjrT3zCzKdfznoKRSI:b9vyywn) ([raw file](https://github.com/coreumfoundation/coreum/blob/e6626596ac8a347b537cd3f1951fc59d44748a6b/proto/coreum/asset/v1/event.proto#L24)):*
> ```protobuf
> }
> 
> message EventFungibleTokenFreezeAmountChanged {
> ```

`FrozenAmountChanged` ?
because Freeze is verb/noun while we need adjective here

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/273)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/273)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/asset/freeze.go` line 241 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/273#-NHjrkzcDg2k5rTWvaz0:-NHxZN-G0xNcaY91p66Z:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/e6626596ac8a347b537cd3f1951fc59d44748a6b/integration-tests/asset/freeze.go#L241)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
would be nice to have a test with resulting `CurrentAmount: 0`. In general and to test event also because it is a special case when we remove key from store
</blockquote></details>

Done
___
*[`proto/coreum/asset/v1/event.proto` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/273#-NHjrT3zCzKdfznoKRSH:-NHxZMOM7FR0h6z4Ig-U:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e6626596ac8a347b537cd3f1951fc59d44748a6b/proto/coreum/asset/v1/event.proto#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`FrozenAmountChanged` ?
because Freeze is verb/noun while we need adjective here
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/273)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
