### PR TITLE
Gov feemodel integration test

### PR DESCRIPTION
**Pull request by dzmitryhil**
Remark: The integration tests won't pass, since the PR contains the genesis braking changes.  We need to merge it and update the crust to let them pass.

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/193)

### CODE REVIEW

**Review by dzmitryhil — COMMENTED** [review]
The integration tests won't pass since the params changes are not compatible with the current crust version. Once we finish the review I'll do the according changes in the crust as well.

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/193#-:-NC_KGKX0hrhlmGyU7_G:b73ktw)* status: 0 of 16 files reviewed, all discussions resolved

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 15 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/193)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`app/network_test.go` line 338 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/193#-NCu2v5D1_imA0apbmYE:-NCu2v5D1_imA0apbmYF:bg4x767) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca8c5c0af4fec6f5f4e53e2885acfea28b0d9101/app/network_test.go#L338)):*
> ```Go
> 	assertT := assert.New(t)
> 	for _, cfg := range networks {
> 		assert.NoError(t, feemodeltypes.Params{
> ```

type `Params`, having field `Model`, accepting result of `Params` function :-)

**Review by ysv — DISMISSED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/193)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`integration-tests/feemodel/proposal.go` line 89 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/193#-NCuXfu7B4s28rPDvgRV:-NCuXfu7B4s28rPDvgRW:b-cqvg6o) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca8c5c0af4fec6f5f4e53e2885acfea28b0d9101/integration-tests/feemodel/proposal.go#L89)):*
> ```Go
> }
> 
> func toProposalString(requireT *require.Assertions, modelParams feemodeltypes.ModelParams) string {
> ```

minor:

`jsonMarshalProposal` ?
It is actually similar to custom json marshalling while string sounds a bit too general
___
*[`x/feemodel/types/params.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/193#-NCuYW758DZFWKBR2pW8:-NCuYW758DZFWKBR2pW9:b-nbx01c) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca8c5c0af4fec6f5f4e53e2885acfea28b0d9101/x/feemodel/types/params.go#L30)):*
> ```Go
> func (m *Params) ParamSetPairs() paramtypes.ParamSetPairs {
> 	return paramtypes.ParamSetPairs{
> 		paramtypes.NewParamSetPair(KeyModel, &m.Model, validateModelParams),
> ```

so now we set all of them under a single "Model" key in KV store ?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/193)* status: all files reviewed, 4 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`integration-tests/feemodel/proposal.go` line 21 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/193#-NCxnpcI1Vd92fr0Ub7d:-NCxnpcI1Vd92fr0Ub7e:br2vltm) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca8c5c0af4fec6f5f4e53e2885acfea28b0d9101/integration-tests/feemodel/proposal.go#L21)):*
> ```Go
> 
> // TestFeeModelProposalParamChange checks that feemodel param change proposal works correctly.
> func TestFeeModelProposalParamChange(ctx context.Context, t testing.T, chain *testing.Chain) {
> ```

Now we have two integration tests using single voting account set. If those tests run in parallel it's possible that they broadcast transactions together leading to incorrect account sequence numbers. To prevent this we need some locking so only one test is executed at a time. Two possible ways of doing this:
- create a lock which blocks the account set for one test at a time - simple to implement but will kill our parallelism eventually, because blocked test will block the slot used by the integration test framework so other voting-unrelated tests must wait too
- better solution: declare that test uses voting so testing framework may put them in another queue running one test at a time, leaving the other queue free for regular tests

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/193)* status: 7 of 20 files reviewed, 4 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/feemodel/proposal.go` line 21 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/193#-NCxnpcI1Vd92fr0Ub7d:-NDCiLkg-MkwNVqNC2KU:bt2vr1b) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca8c5c0af4fec6f5f4e53e2885acfea28b0d9101/integration-tests/feemodel/proposal.go#L21)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Now we have two integration tests using single voting account set. If those tests run in parallel it's possible that they broadcast transactions together leading to incorrect account sequence numbers. To prevent this we need some locking so only one test is executed at a time. Two possible ways of doing this:
- create a lock which blocks the account set for one test at a time - simple to implement but will kill our parallelism eventually, because blocked test will block the slot used by the integration test framework so other voting-unrelated tests must wait too
- better solution: declare that test uses voting so testing framework may put them in another queue running one test at a time, leaving the other queue free for regular tests
</blockquote></details>

Fixed.
___
*[`integration-tests/feemodel/proposal.go` line 89 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/193#-NCuXfu7B4s28rPDvgRV:-NDCkqpK2KBwzMs7Kqfe:befecv3) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca8c5c0af4fec6f5f4e53e2885acfea28b0d9101/integration-tests/feemodel/proposal.go#L89)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:

`jsonMarshalProposal` ?
It is actually similar to custom json marshalling while string sounds a bit too general
</blockquote></details>

Found even better sollution:
```go 
tmjson.Marshal(modelParams)
```
Using the tmjson we can marshal to expected format.
___
*[`x/feemodel/types/params.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/193#-NCuYW758DZFWKBR2pW8:-NCxY7t_1f8O5euzH_l4:b-6icatr) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca8c5c0af4fec6f5f4e53e2885acfea28b0d9101/x/feemodel/types/params.go#L30)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

so now we set all of them under a single "Model" key in KV store ?
</blockquote></details>

No, we set just the param in the params module KV as a "Model". 
___
*[`app/network_test.go` line 338 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/193#-NCu2v5D1_imA0apbmYE:-NDCighP8zuYTaT8HLuu:bmtasxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca8c5c0af4fec6f5f4e53e2885acfea28b0d9101/app/network_test.go#L338)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

type `Params`, having field `Model`, accepting result of `Params` function :-)
</blockquote></details>

Updated now.



_Code quote:_
```Go
TestNetworkConfigConditions(t *testing.T) {
```

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/193)* status: all files reviewed, 5 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/feemodel/proposal.go` line 46 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/193#-NDDRGUW91H7WmXIJDJx:-NDDRGUXBv9cAWZUWDah:b-41s8ra) ([raw file](https://github.com/coreumfoundation/coreum/blob/51199e54d5c72cb9c80ad5fb037cd522b5efd933/integration-tests/feemodel/proposal.go#L46)):*
> ```Go
> 		},
> 	))
> 	requireT.Error(err)
> ```

Is it needed? Next line covers it too
___
*[`integration-tests/feemodel/proposal.go` line 47 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/193#-NDDRLSq3vUQWGvWQl63:-NDDRLSr7_YA_AAf5l7K:b-9csvc3) ([raw file](https://github.com/coreumfoundation/coreum/blob/51199e54d5c72cb9c80ad5fb037cd522b5efd933/integration-tests/feemodel/proposal.go#L47)):*
> ```Go
> 	))
> 	requireT.Error(err)
> 	require.True(t, client.IsErr(err, govtypes.ErrInvalidProposalContent))
> ```

require -> requireT ?
___
*[`integration-tests/feemodel/proposal.go` line 50 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/193#-NDDRVET1BgNsnmNV1FC:-NDDRVET1BgNsnmNV1FD:bifltcl) ([raw file](https://github.com/coreumfoundation/coreum/blob/51199e54d5c72cb9c80ad5fb037cd522b5efd933/integration-tests/feemodel/proposal.go#L50)):*
> ```Go
> 
> 	// Fund proposer to have enough deposit for the next proposal.
> 	err = chain.Faucet.FundAccounts(ctx, testing.NewFundedAccount(chain.AccAddressToLegacyWallet(proposer), proposerBalance))
> ```

Could you fund everything in one step at the beginning? It will be faster

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/193)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 11 of 13 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/193)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Pull request merged**
