### PR TITLE
added protodoc-markdown.tmpl

### PR DESCRIPTION
**Pull request by vertex451**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/528)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/528)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`docs/protodoc-markdown.tmpl` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/528#-NYIO06LD4JOL_W7_PTh:-NYIO06LD4JOL_W7_PTi:bgid9ps) ([raw file](https://github.com/CoreumFoundation/coreum/blob/694c875df128d9f54420320c15a35ec2d2ac34a4/docs/protodoc-markdown.tmpl#L1)):*
> ```
> 
> ```

@silverspase @wojtek-coreum @miladz68  Should it be a part of the coreum or crust if the crust uses it for the generation, WDYT ?

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/528#-:-NYMVPgQEYUKvRLuaq9u:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`docs/protodoc-markdown.tmpl` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/528#-NYIO06LD4JOL_W7_PTh:-NYMVF2t7VwEtQmInIwC:bf9f3k1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/694c875df128d9f54420320c15a35ec2d2ac34a4/docs/protodoc-markdown.tmpl#L1)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

We can put it into the crust, but for this, we will pull the crust repo(ensure) for docs generation.
Second point - output will be placed into the Coreum repo, so it would be logical to keep input within this repo as well.

I would have the template in the Coreum repo.
</blockquote></details>

I think it should be here, since the logic for how it should be structured is not part of crust.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/528)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`docs/protodoc-markdown.tmpl` line 1 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/528#-NYIO06LD4JOL_W7_PTh:-NYNIiLY05y34aw32FFS:b-bkrgoz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/694c875df128d9f54420320c15a35ec2d2ac34a4/docs/protodoc-markdown.tmpl#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think it should be here, since the logic for how it should be structured is not part of crust. 
</blockquote></details>

I'm ok then.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/528)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Pull request merged**
