### PR TITLE
Add feature uniqueness check on the FT and NFT asset issuance.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/481)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/481)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/types/msgs.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/481#-NUMBaZX1xh-sbUdfpCX:-NUMBaZY27xcprF_HwD_:ba81rzu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/785e3e6b7947fbf282e891f1681f9c9928c4fcd1/x/asset/ft/types/msgs.go#L58)):*
> ```Go
> 	featuresSet := make(map[Feature]struct{})
> 	for _, feature := range msg.Features {
> 		if _, ok := featuresSet[feature]; ok {
> ```

ok -> exists, because it is not "ok" if value exists
___
*[`x/asset/nft/types/msgs.go` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/481#-NUMBtAK3UiWcS30yeSZ:-NUMBtAK3UiWcS30yeS_:b35nsoc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/785e3e6b7947fbf282e891f1681f9c9928c4fcd1/x/asset/nft/types/msgs.go#L63)):*
> ```Go
> 	featuresSet := make(map[ClassFeature]struct{})
> 	for _, feature := range msg.Features {
> 		if _, ok := featuresSet[feature]; ok {
> ```

ok -> exists

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/481)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/types/msgs.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/481#-NUMBaZX1xh-sbUdfpCX:-NUQMQdtBnpw5w8mV6DT:b4ydk4s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/785e3e6b7947fbf282e891f1681f9c9928c4fcd1/x/asset/ft/types/msgs.go#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Didn't get your comment.
</blockquote></details>

I think wojtek means that `exists` is a better name than `ok`, and I agree
___
*[`x/asset/nft/types/msgs.go` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/481#-NUMBtAK3UiWcS30yeSZ:-NUQMs7I5ffGFBdj50I-:b-t77xc3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/785e3e6b7947fbf282e891f1681f9c9928c4fcd1/x/asset/nft/types/msgs.go#L63)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ok -> exists
</blockquote></details>

agreed

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/481)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/481)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/types/msgs.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/481#-NUMBaZX1xh-sbUdfpCX:-NUQgb8a6mGSReuV9r1L:b-b8fcxk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/785e3e6b7947fbf282e891f1681f9c9928c4fcd1/x/asset/ft/types/msgs.go#L58)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think wojtek means that `exists` is a better name than `ok`, and I agree
</blockquote></details>

Ok, updated.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/481)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/asset/ft/types/msgs.go` line 59 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/481#-NUR9yxX4mtyXQnCZ02H:-NUR9yxX4mtyXQnCZ02I:b-hr214y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05b48026a25dfe461db6475493968e46896400c0/x/asset/ft/types/msgs.go#L59)):*
> ```Go
> 	for _, feature := range msg.Features {
> 		if _, exists := featuresSet[feature]; exists {
> 			return sdkerrors.Wrapf(ErrInvalidInput, "duplicated features in the features list")
> ```

I propose to use `lo.FindDuplicates` instead of duplicating this logic in FT & NFT
___
*[`x/asset/ft/types/msgs.go` line 59 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/481#-NURA3Sb-w145v0gT4kv:-NURA3Sb-w145v0gT4kw:b3jirxf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05b48026a25dfe461db6475493968e46896400c0/x/asset/ft/types/msgs.go#L59)):*
> ```Go
> 	for _, feature := range msg.Features {
> 		if _, exists := featuresSet[feature]; exists {
> 			return sdkerrors.Wrapf(ErrInvalidInput, "duplicated features in the features list")
> ```

I think it would be beneficial to include features which are duplicated in this error ?

**Review by miladz68 — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/481)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/481)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/types/msgs.go` line 59 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/481#-NUR9yxX4mtyXQnCZ02H:-NURHxZW5CIPdkgrLLoZ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05b48026a25dfe461db6475493968e46896400c0/x/asset/ft/types/msgs.go#L59)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I propose to use `lo.FindDuplicates` instead of duplicating this logic in FT & NFT
</blockquote></details>

Done.



_Code quote:_
```Go
exists := featuresSet[feature]; exis
```
___
*[`x/asset/ft/types/msgs.go` line 59 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/481#-NURA3Sb-w145v0gT4kv:-NURHxwI9UEeEs2iawwD:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05b48026a25dfe461db6475493968e46896400c0/x/asset/ft/types/msgs.go#L59)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think it would be beneficial to include features which are duplicated in this error ? 
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/481)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/481)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
