### PR TITLE
Change WASM behaviour to default: burn vesting balance when instantiating contract

### PR DESCRIPTION
**Pull request by ysv**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/740)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/740)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 2229 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/740#-Nl96CSr9rAVKZyg-EoF:-Nl96CSr9rAVKZyg-EoG:bhjau5p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e0f20327271a83cf5ea0adfccd1e3d7269bae9c/integration-tests/modules/wasm_test.go#L2229)):*
> ```Go
> 		},
> 		{
> 			name: "vestingtypes.MsgCreateVestingAccount (delayed, non-vested)",
> ```

the description says non-vested, but it is vested right ?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/740)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/modules/wasm_test.go` line 2229 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/740#-Nl96CSr9rAVKZyg-EoF:-Nl96fPXDx9949GNqw27:bnnwqt0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e0f20327271a83cf5ea0adfccd1e3d7269bae9c/integration-tests/modules/wasm_test.go#L2229)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the description says non-vested, but it is vested right ?
</blockquote></details>

no, this one is different
For others we wait 1 block for vesting to be completed

But this one we define `EndTime:     time.Now().Add(time.Minute).Unix(),` so it is not vested before contract instantiation

Increase it to +1h to be sure

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/740)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @wojtek-coreum)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/740)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/740#-:-Nl9Vc8W6pPk_-yUc2Yl:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/740)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
