### PR TITLE
fixed docs on connecting to devnet

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/316)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/316)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/316)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by ysv — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/316)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/316)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68)

___
*[`docs/chain/node/run-full.md` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/316#-NKIdvxc1nDewpYsj2JM:-NKIdvxc1nDewpYsj2JN:b-ezh22t) ([raw file](https://github.com/coreumfoundation/coreum/blob/8abe85338e35c09e7a6e027f953e01ad54db55d4/docs/chain/node/run-full.md#L3)):*
> ```Markdown
> # Run full
> 
> **Attention!** *If you are planning to run a node against the devnet (either full node or a validator node), be mindful that the devnet might be restarted without prior notice(i.e block height is set to 0 and all state removed), and you should be prepared to act accordingly by removing all state and start from zero.*
> ```

space after notice

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/316)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

___
*[`docs/chain/node/run-full.md` line 3 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/316#-NKIdvxc1nDewpYsj2JM:-NKYFcwt43suB1-t1da1:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/8abe85338e35c09e7a6e027f953e01ad54db55d4/docs/chain/node/run-full.md#L3)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

space after notice
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/316)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/316)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
