### PR TITLE
Update setup instructions

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/894)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/894)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`README.md` line 49 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/894#-O-tXcQBELZWHZ5y3kez:-O-tXcQBELZWHZ5y3kf-:b-x7iceg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d54e1276ed7d4e922a39435f815cb379342bb8ad/README.md#L49)):*
> ```Markdown
> 
> ```
> $ ./bin/coreum-builder znet
> ```

Don't we have the make goal for it?
___
*[`README.md` line 68 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/894#-O-tXmVP7b4HpNHVKks-:-O-tXmVP7b4HpNHVKks0:b-gv19ig) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d54e1276ed7d4e922a39435f815cb379342bb8ad/README.md#L68)):*
> ```Markdown
> 
> ```
> $ ./bin/coreum-builder znet
> ```

It would be nice to move all commands we need to the makefile

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/894)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`README.md` line 49 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/894#-O-tXcQBELZWHZ5y3kez:-O-u68d_9jfCecn10JL9:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d54e1276ed7d4e922a39435f815cb379342bb8ad/README.md#L49)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Don't we have the make goal for it?
</blockquote></details>

Done.
___
*[`README.md` line 68 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/894#-O-tXmVP7b4HpNHVKks-:-O-u68vs-FF7DnSNDMEZ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d54e1276ed7d4e922a39435f815cb379342bb8ad/README.md#L68)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It would be nice to move all commands we need to the makefile
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/894)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/894)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

**Pull request merged**
