### PR TITLE
Fix cored-ext

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/964)

### CODE REVIEW

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/964)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/964)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`build/coreum/build.go` line 29 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/964#-O77jw6AAmymXvxXj-Th:-O77jw6AAmymXvxXj-Ti:brq72y9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ee872e21f589ae63b6e9ed6b62c67f024a5f658f/build/coreum/build.go#L29)):*
> ```Go
> 	extendedBinaryPath  = "bin/" + extendedBinaryName
> 	integrationTestsDir = repoPath + "/integration-tests"
> 	cometBFTCommit      = "099b4104e5b00b3cedd2c06ca3b1270baad2f4e9"
> ```

What about the forked version did you update it ?

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/964)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`build/coreum/build.go` line 29 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/964#-O77jw6AAmymXvxXj-Th:-O78ESWfEGsRhW12l8jk:bhqnxhi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ee872e21f589ae63b6e9ed6b62c67f024a5f658f/build/coreum/build.go#L29)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about the forked version did you update it ?
</blockquote></details>

Exactly. this is the commit hash on the forked repo

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/964)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/964)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/964)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
