### PR TITLE
Add more tests for FT global freeze + IBC

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/549)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/549)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/asset_ft_test.go` line 687 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/549#-NZ67h2P6btdJVGbdIoq:-NZ67h2P6btdJVGbdIor:bch572z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8423adf34cc64d96b847cefebafcb7516cc3b973/integration-tests/ibc/asset_ft_test.go#L687)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	// send some coins to the other account, should work despite global freeze
> ```

Why do you need to test it here is we already test it in the different test>

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/549)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/ibc/asset_ft_test.go` line 687 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/549#-NZ67h2P6btdJVGbdIoq:-NZ69OpL8siKeXRHG9PQ:b-32r3f1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8423adf34cc64d96b847cefebafcb7516cc3b973/integration-tests/ibc/asset_ft_test.go#L687)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need to test it here is we already test it in the different test>
</blockquote></details>

I don't care about it at all, but I need to send IBC transfer from non-issuer account during global freeze, so that another account needs to get tokens from the issuer

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/549)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/asset_ft_test.go` line 687 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/549#-NZ67h2P6btdJVGbdIoq:-NZ6EP0wDPabM2vQ2LWr:btdsfzr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8423adf34cc64d96b847cefebafcb7516cc3b973/integration-tests/ibc/asset_ft_test.go#L687)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't care about it at all, but I need to send IBC transfer from non-issuer account during global freeze, so that another account needs to get tokens from the issuer
</blockquote></details>

I see.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/549)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/549)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
