### PR TITLE
Disallow IBC and BlockSmartContract in conjunction with extension

### PR DESCRIPTION
**Pull request by miladz68**
…ension

# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/864)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/864)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/types/token.go` line 234 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/864#-NzgKF1s8aSFEX0Jyj6E:-NzgKF1s8aSFEX0Jyj6F:bqn06oj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4c75da3e4d7ddfc35c6da0fe50ac7100b7a35930/x/asset/ft/types/token.go#L234)):*
> ```Go
> 			case Feature_block_smart_contracts:
> 				return sdkerrors.Wrapf(ErrInvalidInput, "block_smart_contract feature is not allowed in combination with extension")
> 			}
> ```

You can use `if item == Feature_ibc || tem == Feature_block_smart_contracts `, or with switch `Feature_ibc, Feature_block_smart_contracts` and use `Wrapf` where you put `Feature_....String()`  as error part.



_Code quote:_
```Go
			case Feature_ibc:
				return sdkerrors.Wrapf(ErrInvalidInput, "ibc feature is not allowed in combination with extension")
			case Feature_block_smart_contracts:
				return sdkerrors.Wrapf(ErrInvalidInput, "block_smart_contract feature is not allowed in combination with extension")
			}
```

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/864)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/types/token.go` line 234 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/864#-NzgKF1s8aSFEX0Jyj6E:-NzgN9nS7M6dGeG3G-bi:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4c75da3e4d7ddfc35c6da0fe50ac7100b7a35930/x/asset/ft/types/token.go#L234)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You can use `if item == Feature_ibc || tem == Feature_block_smart_contracts `, or with switch `Feature_ibc, Feature_block_smart_contracts` and use `Wrapf` where you put `Feature_....String()`  as error part.
</blockquote></details>

Done.

**Review by masihyeganeh — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/864)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/spec/README.md` line 132 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/864#-NzgOthh7Vh2J7oHrMOy:-NzgOthh7Vh2J7oHrMOz:b-hkyjwp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f7e3d2c6758c24eda7faf4d515b5514b1a92ecc9/x/asset/ft/spec/README.md#L132)):*
> ```Markdown
> 
> ### BlockSmartContract
> If the BlockSmartContract is enabled, then the token cannot be trafered to any smart contract. The execption is the case where
> ```

typo: transferred
___
*[`x/asset/ft/spec/README.md` line 133 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/864#-NzgP-6I9Ne14XDXDupk:-NzgP-6I9Ne14XDXDupl:b-hkyjwp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f7e3d2c6758c24eda7faf4d515b5514b1a92ecc9/x/asset/ft/spec/README.md#L133)):*
> ```Markdown
> ### BlockSmartContract
> If the BlockSmartContract is enabled, then the token cannot be trafered to any smart contract. The execption is the case where
> the smart contract is the issuer of the token, in which case the transfer to the issuer contract can take place.
> ```

typo: transferred

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/864)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/864)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/864)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/864)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/864)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`x/asset/ft/spec/README.md` line 132 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/864#-NzgOthh7Vh2J7oHrMOy:-NzgT589EXD1a2mG4PVx:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f7e3d2c6758c24eda7faf4d515b5514b1a92ecc9/x/asset/ft/spec/README.md#L132)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

typo: transferred
</blockquote></details>

Done.
___
*[`x/asset/ft/spec/README.md` line 133 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/864#-NzgP-6I9Ne14XDXDupk:-NzgT9hV6SaG5_q-03GF:b-7xa1of) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f7e3d2c6758c24eda7faf4d515b5514b1a92ecc9/x/asset/ft/spec/README.md#L133)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

typo: transferred
</blockquote></details>

Transfer here is a noun.

**Pull request merged**
