### PR TITLE
Set the default consensus/timeout_commit = 1s

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/175)

### CODE REVIEW

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/175)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/175)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @ysv)

___
*[`cmd/cored/cosmoscmd/init.go` line 53 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/175#-NBuqKHP-bcc7ce3RxCg:-NBuqKHQ75BM3dRpvaqr:b-ey935t) ([raw file](https://github.com/coreumfoundation/coreum/blob/a71a3051331ef54f12d0fe7b80a3cb2542d2c2f2/cmd/cored/cosmoscmd/init.go#L53)):*
> ```Go
> 
> 			// Update the default consensus config
> 			config.Consensus.TimeoutCommit = time.Second
> ```

I think the correct place to set this config is `TendermintNodeConfig` in `app/node_config` file.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/175)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/175#-:-NBw6D_JAfERt9jA6fWX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @ysv)

**Pull request merged**
