### PR TITLE
Make time_iota_ms configurable inside network template

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/589)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/589)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`pkg/config/provider.go` line 68 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/589#-Nb-75F-7yjOOdxX9Jzb:-Nb-75F-7yjOOdxX9Jzc:bdjhs8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4ae51c5472365948823329aba39afe6278d30224/pkg/config/provider.go#L68)):*
> ```Go
> 
> // WithBlockTimeIota sets the time_iota_ms variable inside block section of genesis.
> func (dcp DynamicConfigProvider) WithBlockTimeIota(blockTimeIota time.Duration) DynamicConfigProvider {
> ```

do you need this?

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/589)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`pkg/config/provider.go` line 68 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/589#-Nb-75F-7yjOOdxX9Jzb:-Nb0Jget5TJxqjdSJdCC:byrdrnj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4ae51c5472365948823329aba39afe6278d30224/pkg/config/provider.go#L68)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

yes, I need it to modify the value on crust side. 
</blockquote></details>

but we do it there by setting the fields directly

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/589)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`pkg/config/provider.go` line 68 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/589#-Nb-75F-7yjOOdxX9Jzb:-Nb0WyrLB4387L91mNYF:bldn8jk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4ae51c5472365948823329aba39afe6278d30224/pkg/config/provider.go#L68)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but we do it there by setting the fields directly
</blockquote></details>

Yes, I can redo it like that. Removed.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/589)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @vertex451, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/589)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, and @ysv)

___
*[`pkg/config/genesis/genesis.v1.tmpl.json` line 9 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/589#-NbK4pUI3n7unEPAuvG-:-NbK4pUI3n7unEPAuvG0:bhouuej) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b4185f181c7c4cfff42632f528f0148caceb21ce/pkg/config/genesis/genesis.v1.tmpl.json#L9)):*
> ```JSON
>       "max_bytes": "22020096",
>       "max_gas": "50000000",
>       "time_iota_ms": "{{ .BlockTimeIotaMS }}"
> ```

Do we still need it if it's removed from v0.47 ?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/589)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/589)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, and @ysv)

___
*[`pkg/config/genesis/genesis.v1.tmpl.json` line 9 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/589#-NbK4pUI3n7unEPAuvG-:-NbKKhXmAgUTMzX3W9Sk:bqy3tkr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b4185f181c7c4cfff42632f528f0148caceb21ce/pkg/config/genesis/genesis.v1.tmpl.json#L9)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do we still need it if it's removed from v0.47 ?
</blockquote></details>

we will need to run v2 for some time. I guess we can wait for few months and in that time timeout commit less than 1 second will not work.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/589)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451 and @ysv)

**Pull request merged**
