### PR TITLE
Added functions to change gas adjustment on client context

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/457)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/457)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/457#-NRJWD8cCXXd_-8yMdvg:-NRJWD8d8BNGt2G9ksB5:b-7id5aq) (no related file):*
When gas adjustment and gas price adjustment were added initialy some time ago, it was done like in this PR. But during the discussion IIRC @ysv and @dzmitryhil argued that it's better to set them in constructor as a config instead of adding those `With*` methods. Did the situation change that now you find it to be better to set it this way instead?

___

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/457)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/457#-NRJWD8cCXXd_-8yMdvg:-NRYqY34CuPZnAkxSLjG:b-2zn3cw) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

When gas adjustment and gas price adjustment were added initialy some time ago, it was done like in this PR. But during the discussion IIRC @ysv and @dzmitryhil argued that it's better to set them in constructor as a config instead of adding those `With*` methods. Did the situation change that now you find it to be better to set it this way instead?
</blockquote></details>

I recall this discussion but don't remember why we decided to proceed in one or another way

I'm okay to keep this param required inside constructor but also have this setter 

___

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/457)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/457#-NRJWD8cCXXd_-8yMdvg:-NR_ckUb6QkcRpZ9HVfA:b-bohsg8) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I recall this discussion but don't remember why we decided to proceed in one or another way

I'm okay to keep this param required inside constructor but also have this setter 
</blockquote></details>

At that time you said that those params are so important that it's better to require them explicitely in the constructor. Setting them both in constructor and in `With*` is a bit redundant. If we want to go with `With*` then let's remove the constructor.

___

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/457)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/457#-NRJWD8cCXXd_-8yMdvg:-NRbwZSp4frZaeXRYyO7:b-361ao7) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

At that time you said that those params are so important that it's better to require them explicitely in the constructor. Setting them both in constructor and in `With*` is a bit redundant. If we want to go with `With*` then let's remove the constructor.
</blockquote></details>

they should be passed inside constructor because setting them to 0 doesn't make sense since it is obviously a wrong value which will not work.

Having them inside With is beneficial because then it gives ability to use DefaultCtx and override a single param using `With*`

```
ctx := DefaultContextConfig().WithGasAdjustment(1.2)
```
I think it is a reasonable case

___

**Pull request merged**
