### PR TITLE
Update proto `msg` definition

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

`msg.proto`  file has changed in Cosmos v0.47. Our copy must be udpated.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/631)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/631)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @miladz68, @vertex451, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/631)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/631#-Nd9vo3PEPXYykkT30ZQ:-Nd9vo3PEPXYykkT30ZR:bp6swo9) (no related file):*
@wojtek-coreum pls add description to this PR. The change is not obvious

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/631)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @vertex451, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/631#-Nd9vo3PEPXYykkT30ZQ:-Nd9yhBH3xXofLTRsdsW:b-896fix) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

@wojtek-coreum pls add description to this PR. The change is not obvious
</blockquote></details>

Done.

___

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/631)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451 and @ysv)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/631)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
