### PR TITLE
Panic in client if the provided address is without the protocol

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`pkg/client/client.go` line 39 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/157#-NBHG0O-5RYyoluOlakp:-NBHG0O-5RYyoluOlakq:beueftd) ([raw file](https://github.com/coreumfoundation/coreum/blob/13b830050b764fbc5af605c6e6e49fd321552ae6/pkg/client/client.go#L39)):*
> ```Go
> var expectedSequenceRegExp = regexp.MustCompile(`account sequence mismatch, expected (\d+), got \d+`)
> 
> const clientProtocols = "tcp,http,https"
> ```

we can have it as a list
___
*[`pkg/client/client.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/157#-NBHG4IXCq_fwp7DEzoj:-NBHG4IXCq_fwp7DEzok:b-tyyq62) ([raw file](https://github.com/coreumfoundation/coreum/blob/13b830050b764fbc5af605c6e6e49fd321552ae6/pkg/client/client.go#L44)):*
> ```Go
> func New(chainID app.ChainID, addr string) Client {
> 	found := false
> 	for _, protocol := range strings.Split(clientProtocols, ",") {
> ```

I think we might be able use`https://github.com/samber/lo` package to handle this logic. 
___
*[`pkg/client/client.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/157#-NBHGcNL1f1r_n4I5UwE:-NBHGcNL1f1r_n4I5UwF:b-882f2p) ([raw file](https://github.com/coreumfoundation/coreum/blob/13b830050b764fbc5af605c6e6e49fd321552ae6/pkg/client/client.go#L50)):*
> ```Go
> 	}
> 	if !found {
> 		panic(errors.Errorf("the address %q contains not supported propol, supported are: %q", addr, clientProtocols))
> ```

return error instead of panic

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`pkg/client/client.go` line 39 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/157#-NBHG0O-5RYyoluOlakp:-NBHIT4c0as0a6nP8RHE:bem9ta5) ([raw file](https://github.com/coreumfoundation/coreum/blob/13b830050b764fbc5af605c6e6e49fd321552ae6/pkg/client/client.go#L39)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we can have it as a list
</blockquote></details>

using list is definitely better
I also believe we should  move this const  to New method because it is not some sort of global variable but local to this method
___
*[`pkg/client/client.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/157#-NBHG4IXCq_fwp7DEzoj:-NBHI95LE1-UR7UVMmwL:bqcldhn) ([raw file](https://github.com/coreumfoundation/coreum/blob/13b830050b764fbc5af605c6e6e49fd321552ae6/pkg/client/client.go#L44)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think the Filter method is the answer for this
</blockquote></details>

yes
lets start to use it
___
*[`pkg/client/client.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/157#-NBHGcNL1f1r_n4I5UwE:-NBHIGRg2z-T69EihoIv:bsjk1wv) ([raw file](https://github.com/coreumfoundation/coreum/blob/13b830050b764fbc5af605c6e6e49fd321552ae6/pkg/client/client.go#L50)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

return error instead of panic
</blockquote></details>

the idea here is to avoid changing method signature because this will require changes in crust & faucet (probably) and since this code is already deprecated we want to avoid it.
Panic is ok for me

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`pkg/client/client.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/157#-NBHGcNL1f1r_n4I5UwE:-NBHJUA59Gj-4oWmTvmi:b-q8jzb0) ([raw file](https://github.com/coreumfoundation/coreum/blob/13b830050b764fbc5af605c6e6e49fd321552ae6/pkg/client/client.go#L50)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

the idea here is to avoid changing method signature because this will require changes in crust & faucet (probably) and since this code is already deprecated we want to avoid it.
Panic is ok for me
</blockquote></details>

got it

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`pkg/client/client.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/157#-NBHG4IXCq_fwp7DEzoj:-NBHJ_rA7zHI52CHKHsD:b-ayy2ks) ([raw file](https://github.com/coreumfoundation/coreum/blob/13b830050b764fbc5af605c6e6e49fd321552ae6/pkg/client/client.go#L44)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes
lets start to use it
</blockquote></details>

Oh, import new package to find in list? It's too much!
___
*[`pkg/client/client.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/157#-NBHGcNL1f1r_n4I5UwE:-NBHJjnf5SSE8O_ZTzLI:btqzin) ([raw file](https://github.com/coreumfoundation/coreum/blob/13b830050b764fbc5af605c6e6e49fd321552ae6/pkg/client/client.go#L50)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

got it
</blockquote></details>

Right, I tried to do it, but then found that this method is used by the faucet, so decided to keep the signature as is.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`pkg/client/client.go` line 39 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/157#-NBHG0O-5RYyoluOlakp:-NBHM7b7BWdbI9lwl0mn:b-e4sfpt) ([raw file](https://github.com/coreumfoundation/coreum/blob/13b830050b764fbc5af605c6e6e49fd321552ae6/pkg/client/client.go#L39)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

using list is definitely better
I also believe we should  move this const  to New method because it is not some sort of global variable but local to this method
</blockquote></details>

Updarted to the list in func

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`pkg/client/client.go` line 49 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/157#-NBHboPb5lG2SMgj97Us:-NBHboPb5lG2SMgj97Ut:bdebhak) ([raw file](https://github.com/coreumfoundation/coreum/blob/ebbd72974b987af6ba36fee5ec515a13a687491c/pkg/client/client.go#L49)):*
> ```Go
> 	}
> 	if !found {
> 		panic(errors.Errorf("the address %q contains not supported propol, supported are: %q", addr, clientProtocols))
> ```

propol -> protocol

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman and @miladz68)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @ysv)

___
*[`pkg/client/client.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/157#-NBHG4IXCq_fwp7DEzoj:-NBLwtn60oKD8MNTrCaX:bffcoz7) ([raw file](https://github.com/coreumfoundation/coreum/blob/13b830050b764fbc5af605c6e6e49fd321552ae6/pkg/client/client.go#L44)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Oh, import new package to find in list? It's too much!
</blockquote></details>

we will use that package extensively in future.

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @ysv)

**Review by wojtek-coreum — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`pkg/client/client.go` line 44 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/157#-NBHG4IXCq_fwp7DEzoj:-NBMTi8t6Q5tvmU2GgTD:bqva2pf) ([raw file](https://github.com/coreumfoundation/coreum/blob/13b830050b764fbc5af605c6e6e49fd321552ae6/pkg/client/client.go#L44)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we will use that package extensively in future. 
</blockquote></details>

Ok, integrate the lib and code updated as well.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman and @miladz68)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`pkg/client/client.go` line 43 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/157#-NBN1BjC7NzM5LinhQb_:-NBN1BjC7NzM5LinhQba:bqjprnc) ([raw file](https://github.com/coreumfoundation/coreum/blob/f829f0a26688029cc3a95e2727b84b2fabe24b31/pkg/client/client.go#L43)):*
> ```Go
> func New(chainID app.ChainID, addr string) Client {
> 	clientProtocols := []string{"tcp", "http", "https"}
> 	if !lo.ContainsBy[string](clientProtocols, func(protocol string) bool {
> ```

IDK what is the idiomatic way to use generics in go but it works without `[string]` also and seems a bit more friendly to me

like this
```golang
lo.ContainsBy([]string{}, func(protocol string) bool {
		return strings.HasPrefix(addr, protocol)
	})
```

WDYT ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`pkg/client/client.go` line 43 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/157#-NBN1BjC7NzM5LinhQb_:-NBNLzmv-NHSf9xMsD34:bvcs7z6) ([raw file](https://github.com/coreumfoundation/coreum/blob/f829f0a26688029cc3a95e2727b84b2fabe24b31/pkg/client/client.go#L43)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IDK what is the idiomatic way to use generics in go but it works without `[string]` also and seems a bit more friendly to me

like this
```golang
lo.ContainsBy([]string{}, func(protocol string) bool {
		return strings.HasPrefix(addr, protocol)
	})
```

WDYT ?
</blockquote></details>

It will use the generic under the hood anyway, the compiler understands that T is string and set it. 
But agree let's remove just to simplify the line. 
Updated.

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman and @miladz68)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)

**Pull request merged**
