### PR TITLE
report deterministic_gas_factor only if the transaction is successfull

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/355)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/355)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/355#-NMEG4nt3qKN1FuEDpgb:-NMEG4nt3qKN1FuEDpgc:b45yscm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a70cc8301d752a0f4ad2055a77b5f9f57a4b6559/x/deterministicgas/types/gas.go#L99)):*
> ```Go
> 					res, err := handler(sdk.WrapSDKContext(newSDKCtx), req)
> 					if isDeterministic &&
> 						err == nil &&
> ```

I would move the error firt.
Why do we need the `!newSDKCtx.IsCheckTx()` and `!newSDKCtx.IsReCheckTx()`.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/355)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/355)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 99 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/355#-NMEG4nt3qKN1FuEDpgb:-NMSupyR911OG3P5F7n_:bcf9286) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a70cc8301d752a0f4ad2055a77b5f9f57a4b6559/x/deterministicgas/types/gas.go#L99)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

agree on comment with error

`!newSDKCtx.IsCheckTx()` is not obvious also. Maybe worth adding a comment
</blockquote></details>

Done
we need checktx and rechecktx, since we only want the main execution of the message to be reported, not the checktx phase. Also we have ReCheckTx disabled at this point, but just in case that a validator turns it on, we don't want that to be reported as well. we only want DeliverTx.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/355)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/355)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/355)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/355)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
