### PR TITLE
Handle IBC edge cases

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description
Handle IBC edge cases, including these tests:
- TestExtensionIBCAssetFTSendCommissionAndBurnRate
- TestExtensionIBCRejectedTransferWithWhitelistingAndFreezing
- TestExtensionIBCTimedOutTransferWithWhitelistingAndFreezing
- TestExtensionIBCRejectedTransferWithBurnRateAndSendCommission
- TestExtensionIBCTimedOutTransferWithBurnRateAndSendCommission

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/853)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/853)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/853)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/853)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/853)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/853)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/asset_extension_ft_test.go` line 1128 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/853#-Nz8AnKsEL1UoxgLr90m:-Nz8AnKsEL1UoxgLr90n:bj03uqt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ea69a311e9a26fc770b17f09eb2f06ee629be6c7/integration-tests/ibc/asset_extension_ft_test.go#L1128)):*
> ```Go
> 	// - escrow address being frozen
> 	// - sender account not being whitelisted
> 	requireT.NoError(coreumChain.AwaitForBalance(ctx, t, coreumSender, sendCoin))
> ```

are you making an exception for IBCPurpose 'In' in the freezing and whitelisting of the smart contract ? if no? then why is this passing ?

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/853)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/853)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`integration-tests/ibc/asset_extension_ft_test.go` line 1128 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/853#-Nz8AnKsEL1UoxgLr90m:-NzCSL6U-z4Z0gHY0Ms9:b-5upz8b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/93a8bd0fdfcd690ba8df0356a1f9dca51da1de19/integration-tests/ibc/asset_extension_ft_test.go#L1128)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

are you making an exception for IBCPurpose 'In' in the freezing and whitelisting of the smart contract ? if no? then why is this passing ?
</blockquote></details>

It should be handled by the `ack` purpose. I think it is done in go code right? So in that case contract is not called at all. Same for timeouts.

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/853)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
