### PR TITLE
Reset usage of sync broadcast mode in integration-tests/testing/gov.go

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/259)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/259)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/index.go` line 45 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/259#-NGwcbTD3-xjAC1i7zm5:-NGwcbTD3-xjAC1i7zm6:b-k72r2l) ([raw file](https://github.com/coreumfoundation/coreum/blob/8d51fea7ca9d0e72bc36ed0cc91db363914e3a42/integration-tests/index.go#L45)):*
> ```Go
> 				feemodel.TestFeeModelProposalParamChange,
> 				staking.TestStakingProposalParamChange,
> 				staking.TestValidatorCRUDAndStaking,
> ```

according to https://github.com/golang/go/wiki/CodeReviewComments#initialisms
___
*[`integration-tests/testing/network.go` line 11 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/259#-NGwbSRl8pBLDn1iQRFs:-NGwbSRl8pBLDn1iQRFt:b-1rwk62) ([raw file](https://github.com/coreumfoundation/coreum/blob/8d51fea7ca9d0e72bc36ed0cc91db363914e3a42/integration-tests/testing/network.go#L11)):*
> ```Go
> const (
> 	// votingPeriod is the proposal voting period duration
> 	votingPeriod = time.Minute * 2
> ```

I'm actually not sure why we need to override our default voting period of 5d in tests ?
Do we test somewhere voting test beyond this time ?

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/259)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/259)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/259)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/259)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/259)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
