### PR TITLE
Fixed validator key extraction in app export

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/395)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/395)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/395)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`app/export.go` line 153 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/395#-NOP98It-eqUButpSkJ5:-NOP98It-eqUButpSkJ6:bi83vlx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4eeaa27a05f2c52e8db1f9ab4c4ede0245be51d4/app/export.go#L153)):*
> ```Go
> 
> 	for ; iter.Valid(); iter.Next() {
> 		addr := sdk.ValAddress(stakingtypes.AddressFromValidatorsKey(iter.Key()))
> ```

but is it our code or it was generated by ignite ?
Because I don't remember writing it ourself

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/395)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`app/export.go` line 153 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/395#-NOP98It-eqUButpSkJ5:-NOPSWBxDlF91AAVYE1t:b-dz3uai) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4eeaa27a05f2c52e8db1f9ab4c4ede0245be51d4/app/export.go#L153)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but is it our code or it was generated by ignite ?
Because I don't remember writing it ourself
</blockquote></details>

It is generate by ignite (or better to stay starship :P )

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/395)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Pull request merged**
