### PR TITLE
Add more tests for drop FT admin feature

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 80 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxQgvWp7EoTWjyjerXj:-NxQgvWp7EoTWjyjerXk:b-i2kw82) ([raw file](https://github.com/CoreumFoundation/coreum/blob/84e85e620093aa134b318a1291b86a6c88bc3544/x/asset/ft/keeper/before_send.go#L80)):*
> ```Go
> 			}
> 
> 			burnAmount := k.CalculateRate(ctx, def.BurnRate, admin, sender, recipient, coin)
> ```

@ysv @miladz68 @wojtek-coreum @masihyeganeh 

If we don't have the admin
1) Should we compute and send commission to the extensions (IMO - no)?
2) We defenitelisy shouldn't compute/send commission (both burning and sending) to the admin, since the admin doesn't exist!
So if we don't need to compute it, that trick with the `sdk.AccAddress{}` won't be needed.

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 80 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxQgvWp7EoTWjyjerXj:-NxRA2ORD8GIexNdvyxR:b-4j366p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/84e85e620093aa134b318a1291b86a6c88bc3544/x/asset/ft/keeper/before_send.go#L80)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv @miladz68 @wojtek-coreum @masihyeganeh 

If we don't have the admin
1) Should we compute and send commission to the extensions (IMO - no)?
2) We defenitelisy shouldn't compute/send commission (both burning and sending) to the admin, since the admin doesn't exist!
So if we don't need to compute it, that trick with the `sdk.AccAddress{}` won't be needed.
</blockquote></details>

agreed.

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 80 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxQgvWp7EoTWjyjerXj:-NxRmCNs052rziV3MXcr:b4751h4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/84e85e620093aa134b318a1291b86a6c88bc3544/x/asset/ft/keeper/before_send.go#L80)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

agreed.
</blockquote></details>

I mean I agree that we should not compute commision rate anymore. burn rate is fine.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 80 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxQgvWp7EoTWjyjerXj:-NxWXgR504rmXm8EVekH:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/84e85e620093aa134b318a1291b86a6c88bc3544/x/asset/ft/keeper/before_send.go#L80)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I mean I agree that we should not compute commision rate anymore. burn rate is fine.
</blockquote></details>

Done.

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: all files reviewed, 3 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 80 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxXLHai2h-fHxstiLz-:-NxXLHajBxUPFGbGXA_Y:b-6rum2n) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c23d6261b4e218d6f4621e869cef875bcb9e2f4b/x/asset/ft/keeper/before_send.go#L80)):*
> ```Go
> 			}
> 
> 			burnAmount := k.CalculateRate(ctx, def.BurnRate, admin, sender, recipient, coin)
> ```

@ysv @miladz68 @wojtek-coreum 
WDYT, should we keep it as is, or remove `admin` and `recipient` from the `k.CalculateRate` and add that check here?

 What I personally don't like here is that part `admin := sdk.AccAddress{}`. 



_Code quote:_
```Go
			admin := sdk.AccAddress{}
			if def.Admin != "" {
				admin, err = sdk.AccAddressFromBech32(def.Admin)
				if err != nil {
					return sdkerrors.Wrapf(err, "invalid address %s", def.Admin)
				}
			}

			burnAmount := k.CalculateRate(ctx, def.BurnRate, admin, sender, recipient, coin)
```
___
*[`x/asset/ft/keeper/keeper.go` line 734 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxXJzBo-5-RLsIi1R42:-NxXJzBo-5-RLsIi1R43:b-5aw9hi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c23d6261b4e218d6f4621e869cef875bcb9e2f4b/x/asset/ft/keeper/keeper.go#L734)):*
> ```Go
> 
> 	def.Admin = ""
> 	if !def.IsFeatureEnabled(types.Feature_extension) {
> ```

Please add the comment explaining that here.
___
*[`x/asset/ft/keeper/keeper.go` line 734 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxXKBWeCMiNOVE5IglK:-NxXKBWeCMiNOVE5IglL:b9ynqfc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c23d6261b4e218d6f4621e869cef875bcb9e2f4b/x/asset/ft/keeper/keeper.go#L734)):*
> ```Go
> 
> 	def.Admin = ""
> 	if !def.IsFeatureEnabled(types.Feature_extension) {
> ```

What about tests?

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 80 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxXLHai2h-fHxstiLz-:-NxkctFjCWhaiFzS45pZ:b6r8i7l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c23d6261b4e218d6f4621e869cef875bcb9e2f4b/x/asset/ft/keeper/before_send.go#L80)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

@ysv @miladz68 @wojtek-coreum 
WDYT, should we keep it as is, or remove `admin` and `recipient` from the `k.CalculateRate` and add that check here?

 What I personally don't like here is that part `admin := sdk.AccAddress{}`.
</blockquote></details>

I like the idea of having all the criterias needed for calculating them in those functions, so I suggest to keep it as is
___
*[`x/asset/ft/keeper/keeper.go` line 734 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxXJzBo-5-RLsIi1R42:-NxkgfWvA8N5UvXBB2kh:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c23d6261b4e218d6f4621e869cef875bcb9e2f4b/x/asset/ft/keeper/keeper.go#L734)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Please add the comment explaining that here.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/keeper.go` line 734 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxXKBWeCMiNOVE5IglK:-Nxkk4fc4VjrRzdQpQf3:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c23d6261b4e218d6f4621e869cef875bcb9e2f4b/x/asset/ft/keeper/keeper.go#L734)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about tests?
</blockquote></details>

Done.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 72 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxlJPMo-cw3qY7bjdWP:-NxlJPMo-cw3qY7bjdWQ:b-8t7i8d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c787fcc9ff074e95e2b204fd6d75587e73e2eb3a/x/asset/ft/keeper/before_send.go#L72)):*
> ```Go
> 			}
> 
> 			admin := sdk.AccAddress{}
> ```

as Dima mentioned, why are you assigning admin to empty address ? is it so you can assign value to it in if statement ? if it is so, then try to improve the logic if you can. Maybe move the parsing to inside the calculate function so will parse only if necessary. try to see how it can be improved.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 80 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxXLHai2h-fHxstiLz-:-NxmMsLuBZJvjlv2MkeT:b9hbtpl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c23d6261b4e218d6f4621e869cef875bcb9e2f4b/x/asset/ft/keeper/before_send.go#L80)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I like the idea of having all the criterias needed for calculating them in those functions, so I suggest to keep it as is
</blockquote></details>

Done. Let me know if it is better
___
*[`x/asset/ft/keeper/before_send.go` line 72 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxlJPMo-cw3qY7bjdWP:-NxmMpUgDFAAcq2vBI-S:b9hbtpl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c787fcc9ff074e95e2b204fd6d75587e73e2eb3a/x/asset/ft/keeper/before_send.go#L72)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

as Dima mentioned, why are you assigning admin to empty address ? is it so you can assign value to it in if statement ? if it is so, then try to improve the logic if you can. Maybe move the parsing to inside the calculate function so will parse only if necessary. try to see how it can be improved.
</blockquote></details>

Done. Let me know if it is better

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 72 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxqxV5xAx0KF0n7Rmys:-NxqxV5xAx0KF0n7Rmyt:b-2vmbhi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e330b299b8a30e844d820219c2c47e2937687031/x/asset/ft/keeper/before_send.go#L72)):*
> ```Go
> 			}
> 
> 			if def.Admin != "" {
> ```

since you are using `Must` function inside the calculate rate, this function can be safely removed. Actually I see a problem in the logic, look at the next
___
*[`x/asset/ft/keeper/before_send.go` line 79 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-Nxqxkc1DMN5TaehKHK9:-Nxqxkc1DMN5TaehKHKA:b7omevd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e330b299b8a30e844d820219c2c47e2937687031/x/asset/ft/keeper/before_send.go#L79)):*
> ```Go
> 			}
> 
> 			burnAmount := k.CalculateRate(ctx, def.BurnRate, def.Admin, sender, recipient, coin)
> ```

but burn should be calculated and applied even if there is no admin. so the logic needs adjustment.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: all files reviewed, 3 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 80 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxXLHai2h-fHxstiLz-:-NxqyQJa5OFZkOlKJCPO:b-cjnsnf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c23d6261b4e218d6f4621e869cef875bcb9e2f4b/x/asset/ft/keeper/before_send.go#L80)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Done. Let me know if it is better
</blockquote></details>

Let's discuss with team.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 80 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxXLHai2h-fHxstiLz-:-NxrMJvy10TrBvaEM9O6:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c23d6261b4e218d6f4621e869cef875bcb9e2f4b/x/asset/ft/keeper/before_send.go#L80)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's discuss with team.
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/before_send.go` line 72 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-NxqxV5xAx0KF0n7Rmys:-NxrMJZ6BM9SMw0h7iZD:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e330b299b8a30e844d820219c2c47e2937687031/x/asset/ft/keeper/before_send.go#L72)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

since you are using `Must` function inside the calculate rate, this function can be safely removed. Actually I see a problem in the logic, look at the next
</blockquote></details>

Done.
___
*[`x/asset/ft/keeper/before_send.go` line 79 at r7](https://reviewable.io/reviews/CoreumFoundation/coreum/829#-Nxqxkc1DMN5TaehKHK9:-NxrMKF-42GBNiI5GjQh:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e330b299b8a30e844d820219c2c47e2937687031/x/asset/ft/keeper/before_send.go#L79)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

but burn should be calculated and applied even if there is no admin. so the logic needs adjustment.
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 2 files at r5, 1 of 2 files at r7, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/829)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

**Pull request merged**
