### PR TITLE
Upgrade contracts to cosmwasm 2.1.4

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)

### CODE REVIEW

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 31 of 35 files at r1, 4 of 4 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @ysv)

___
*[`x/wasm/handler/query.go` line 168 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/991#-O8g8OI32KK7UMPXzmn1:-O8g8OI32KK7UMPXzmn2:b-vubtbz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/27ea53afaf5dab0772b03037eac4764ba331e238/x/wasm/handler/query.go#L168)):*
> ```Go
> 	}
> 	/*
> 		TODO: Other potential queries to add to the whitelist:
> ```

remove this comment, let's finalize which queries are whitelisted as part of this task either in this PR or the next. either way this list should not go to master branch.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)* status: 35 of 36 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`x/wasm/handler/query.go` line 168 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/991#-O8g8OI32KK7UMPXzmn1:-O8gMMT925GuPhZtnimX:b-x0rd66) ([raw file](https://github.com/CoreumFoundation/coreum/blob/27ea53afaf5dab0772b03037eac4764ba331e238/x/wasm/handler/query.go#L168)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

remove this comment, let's finalize which queries are whitelisted as part of this task either in this PR or the next. either way this list should not go to master branch.
</blockquote></details>

We don't need anymore for now. But isn't it nicer to have the list?

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @ysv)

___
*[`x/wasm/handler/query.go` line 168 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/991#-O8g8OI32KK7UMPXzmn1:-O8k2hVw2ZnDENdhgbpN:b-t3789b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/27ea53afaf5dab0772b03037eac4764ba331e238/x/wasm/handler/query.go#L168)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

We don't need anymore for now. But isn't it nicer to have the list?
</blockquote></details>

I don't think so. too much clutter. 
though it would be nice to use the types themselves with a function to return the string, instead of the string itself.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`x/wasm/handler/query.go` line 168 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/991#-O8g8OI32KK7UMPXzmn1:-O8kJS7wCsu27yu6Lxfb:bgey009) ([raw file](https://github.com/CoreumFoundation/coreum/blob/27ea53afaf5dab0772b03037eac4764ba331e238/x/wasm/handler/query.go#L168)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think so. too much clutter. 
though it would be nice to use the types themselves with a function to return the string, instead of the string itself.
</blockquote></details>

I couldn't find any function that does that. I deleted the list

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 3 of 3 files at r6, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/991)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
