### PR TITLE
fix ibc tests according to migration to 0.47

### PR DESCRIPTION
**Pull request by miladz68**
# Description
This PR, fixed ibc integration tests that were failing because of migration to 0.47
# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/624)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/624)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`app/app.go` line 309 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/624#-NcbFsjU7-ojsoM1S5bj:-NcbFsjU7-ojsoM1S5bk:b-63lqy7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7d2c264033a9d04dfdc8595bd904592da3e4697d/app/app.go#L309)):*
> ```Go
> 	txConfig := encodingConfig.TxConfig
> 	interfaceRegistry := encodingConfig.InterfaceRegistry
> 	// Since 0.47 we all clients must register themselves and are not registered automatically.
> ```

"all clients must be registered themselves and are not registered automatically."
___
*[`app/app.go` line 310 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/624#-NcbG-At7z5S_9BeW0Sf:-NcbG-At7z5S_9BeW0Sg:bl0nq5l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7d2c264033a9d04dfdc8595bd904592da3e4697d/app/app.go#L310)):*
> ```Go
> 	interfaceRegistry := encodingConfig.InterfaceRegistry
> 	// Since 0.47 we all clients must register themselves and are not registered automatically.
> 	// we need to register localhost client since we use it in integration tests.
> ```

really? where?
___
*[`integration-tests/chain_ibc.go` line 101 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/624#-NcbGDzA73urlSxSXRIF:-NcbGDzA73urlSxSXRIG:b645j1b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7d2c264033a9d04dfdc8595bd904592da3e4697d/integration-tests/chain_ibc.go#L101)):*
> ```Go
> 		headerTime = latestBlockRes.GetSdkBlock().GetHeader().Time
> 	} else {
> 		// TODO: remove this if condition once all the connected chains have migrated to cosmos sdk v0.47.
> ```

remove "if condition"

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/624)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 309 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/624#-NcbFsjU7-ojsoM1S5bj:-Ncbi9X52q7IvFNkAHXp:b-svj4x1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05c5b9f22893498a4316d9c9c6c56c70e0edd78c/app/app.go#L309)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

"all clients must be registered themselves and are not registered automatically."
</blockquote></details>

reworded the sentence, please review again. 
___
*[`app/app.go` line 310 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/624#-NcbG-At7z5S_9BeW0Sf:-Ncbi1Ha3OAUumjblB0u:b14jnym) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05c5b9f22893498a4316d9c9c6c56c70e0edd78c/app/app.go#L310)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

really? where?
</blockquote></details>

I changed the sentence to give more information. please let me know if it makes sense. 
___
*[`integration-tests/chain_ibc.go` line 101 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/624#-NcbGDzA73urlSxSXRIF:-Ncbgfq2A07GwBabpwAL:b-a4vovr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05c5b9f22893498a4316d9c9c6c56c70e0edd78c/integration-tests/chain_ibc.go#L101)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

remove "if condition"
</blockquote></details>

putting `if conditon` inside double quotes would be wrong, `if condition` is part of the sentence, not a string literal (i.e is not a noun).

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/624)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`integration-tests/chain_ibc.go` line 101 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/624#-NcbGDzA73urlSxSXRIF:-NcbiSAv7Ms5ZSiECKrf:bijcpmr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05c5b9f22893498a4316d9c9c6c56c70e0edd78c/integration-tests/chain_ibc.go#L101)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

putting `if conditon` inside double quotes would be wrong, `if condition` is part of the sentence, not a string literal (i.e is not a noun).
</blockquote></details>

Actually you are correct. Done.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/624)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @wojtek-coreum)

___
*[`app/app.go` line 310 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/624#-Ncc4ULy-mNqgoLjr7KZ:-Ncc4ULy-mNqgoLjr7K_:b-u45fi1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9e9b406179e6201630285ab26edcbfd9539a69c1/app/app.go#L310)):*
> ```Go
> 	interfaceRegistry := encodingConfig.InterfaceRegistry
> 	// Since 0.47 we all ibc clients must be registered explicitly and are not registered automatically.
> 	// we need to register localhost client since we use cosmos relayer in our integration tests and it
> ```

shouldn't we add localhost into genesis.v3.tmpl ?
```
"params": {  
"allowed\_clients": \[  
"06-solomachine",  
"07-tendermint"  
\]  
},
```
Because in my upgrade I do add localhost

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/624)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 310 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/624#-Ncc4ULy-mNqgoLjr7KZ:-NccGXPAAGZ2APVqEEw2:b-m6qtjn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9e9b406179e6201630285ab26edcbfd9539a69c1/app/app.go#L310)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

shouldn't we add localhost into genesis.v3.tmpl ?
```
"params": {  
"allowed\_clients": \[  
"06-solomachine",  
"07-tendermint"  
\]  
},
```
Because in my upgrade I do add localhost
</blockquote></details>

this is not directly related, the type registration was done inside ibc core package, but now it is not done like that. that is why we need the changes here.

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/624)* status: all files reviewed, 4 unresolved discussions (waiting on @vertex451, @wojtek-coreum, and @ysv)

**Review by ysv — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/624)* status: all files reviewed, 3 unresolved discussions (waiting on @vertex451 and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/624)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @vertex451)

___
*[`app/app.go` line 309 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/624#-NcbFsjU7-ojsoM1S5bj:-Ncg_9b30h4VDwl1sSS1:bvbhdi0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05c5b9f22893498a4316d9c9c6c56c70e0edd78c/app/app.go#L309)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

reworded the sentence, please review again.
</blockquote></details>

what about removing "we"?
___
*[`integration-tests/chain_ibc.go` line 101 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/624#-NcbGDzA73urlSxSXRIF:-Ncg_Mz23DHuHamD5oPA:b-bjuc1h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05c5b9f22893498a4316d9c9c6c56c70e0edd78c/integration-tests/chain_ibc.go#L101)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Actually you are correct. Done.
</blockquote></details>

hehhe, now I understood the initial meaning :-)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/624)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451 and @wojtek-coreum)

___
*[`app/app.go` line 309 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/624#-NcbFsjU7-ojsoM1S5bj:-NcgneO3E0SZwUfZmp1w:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/05c5b9f22893498a4316d9c9c6c56c70e0edd78c/app/app.go#L309)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what about removing "we"?
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/624)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/624)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
