### PR TITLE
Add timeout to IBC tests and fix channel IDs

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/485)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/485)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/ibc/helpers.go` line 37 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/485#-NV9gKEhEn_6wSqVptQh:-NV9gKEhEn_6wSqVptQi:b-c3qsuq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/18730a80dd59d64230f9cfbcf057ce5238406652/integration-tests/ibc/helpers.go#L37)):*
> ```Go
> 	defer retryCancel()
> 
> 	err := retry.Do(retryCtx, time.Second, func() error {
> ```

I'll update it in my PR, don't update it, since it will be hard to merge, since I've refactored that part.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/485)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/485)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/485)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/485)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Pull request merged**
