### PR TITLE
Modified all test-data wasm contracts, added new functionality, messages, queries and added integration tests

### PR DESCRIPTION
**Pull request by keyleu**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
Looks good!

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-:-NY2WmIbChypGti-a_kF:b-vs1prh)* status: 0 of 45 files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY2V2XK-zMbAwgFV7bU:-NY2V2XK-zMbAwgFV7bV:bpdmbvl) (no related file):*
The CI is failed.

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY2WCPuBt3zy7OujnQD:-NY2WCPuBt3zy7OujnQE:b-szy6qr) (no related file):*
Why do we need `packages/coreum-wasm-sdk` commited? What is inside?

___

**Review by keyleu — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-:-NY2bA2R50F_13szefTD:b-ucfknh)* status: 0 of 48 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY2WCPuBt3zy7OujnQD:-NY2aixB2GTOAMTix3sA:b-ahhsdm) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we need `packages/coreum-wasm-sdk` commited? What is inside?
</blockquote></details>

This will be removed after coreum-wasm-sdk v.0.1.2 is on crates.io. I made the PR now with it because so all of you can already check the code. Once I get your approval and the coreum-wasm-sdk is on crates.io I'll remove the package and update the dependencies to use that version.

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY2V2XK-zMbAwgFV7bU:-NY2az5Z5KmgDorG-kFT:bdjxjdf) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The CI is failed.
</blockquote></details>

Yes, I need to discuss this in the meeting because I think it's something related to docker/crust. When building the images it doesn't allow for Cargo.lock to be modified, and since the contract dependencies are updated, this file is automatically updated.

___

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: 0 of 48 files reviewed, 2 unresolved discussions (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY2V2XK-zMbAwgFV7bU:-NY2wcPi3Ww1isFH3ozs:bam1llw) (no related file):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

Yes, I need to discuss this in the meeting because I think it's something related to docker/crust. When building the images it doesn't allow for Cargo.lock to be modified, and since the contract dependencies are updated, this file is automatically updated.
</blockquote></details>

Ok, let's discuss. 

___
*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY2WCPuBt3zy7OujnQD:-NY2wgPw1OtXQNyRaw3X:bx1x6n7) (no related file):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

This will be removed after coreum-wasm-sdk v.0.1.2 is on crates.io. I made the PR now with it because so all of you can already check the code. Once I get your approval and the coreum-wasm-sdk is on crates.io I'll remove the package and update the dependencies to use that version.
</blockquote></details>

Clear. So the `coreum-wasm-sdk v.0.1.2` should be merged first.

___

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 17 of 45 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: 30 of 48 files reviewed, 15 unresolved discussions (waiting on @keyleu and @ysv)

___
*[`integration-tests/modules/testdata/wasm/bank-send/src/lib.rs` line 3 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY2zpWC8SqOcnw2oQCl:-NY2zpWC8SqOcnw2oQCm:bsnnltk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/bank-send/src/lib.rs#L3)):*
> ```XML
> pub mod contract;
> pub mod error;
> pub mod msg;
> ```

you need an empty line. notice the red marker
___
*[`integration-tests/modules/testdata/wasm/bank-send/src/msg.rs` line 14 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY2ztlI327xJFRyTt8a:-NY2ztlI327xJFRyTt8b:b-myyuto) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/bank-send/src/msg.rs#L14)):*
> ```XML
>         recipient: String,
>     },
> }
> ```

you need and empty line
___
*[`integration-tests/modules/testdata/wasm/ft/README.md` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY3-5939BYz14nyKoU-:-NY3-5939BYz14nyKoU0:bycb9td) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/ft/README.md#L1)):*
> ```Markdown
> # FT Contract
> ```

I think this README file is not needed ! 
___
*[`integration-tests/modules/testdata/wasm/ft/packages/coreum-wasm-sdk/Cargo.toml` line 13 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY3-A_jAtjeuLSvEsns:-NY3-A_jAtjeuLSvEsnt:b3xaeg5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/ft/packages/coreum-wasm-sdk/Cargo.toml#L13)):*
> ```TOML
> serde = { version = "1.0.164", default-features = false, features = ["derive"] }
> schemars = "0.8.12"
> cosmwasm-schema = "1.2.6"
> ```

empty line needed.
___
*[`integration-tests/modules/testdata/wasm/ft/packages/coreum-wasm-sdk/.github/workflows/release.yml` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY3-If-8Rv6V2aY-S3K:-NY3-If-8Rv6V2aY-S3L:bt1n7uy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/ft/packages/coreum-wasm-sdk/.github/workflows/release.yml#L1)):*
> ```YAML
> name: release
> ```

this file should not exist.
___
*[`integration-tests/modules/testdata/wasm/ft/packages/coreum-wasm-sdk/src/assetnft.rs` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY3-Sio2gCXPgUInoy-:-NY3-Sio2gCXPgUInoy0:b-frft8n) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/ft/packages/coreum-wasm-sdk/src/assetnft.rs#L1)):*
> ```XML
> use cosmwasm_schema::QueryResponses;
> ```

I assume you have copied the sdk code here, but that seems to not be the right approach. the correct version of the sdk must be used after the other PR is merged. 
___
*[`integration-tests/modules/testdata/wasm/nft/README.md` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY330fP8ZNJ4rR5L3R1:-NY330fP8ZNJ4rR5L3R2:bzbp7jt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/nft/README.md#L1)):*
> ```Markdown
> # NFT Contract
> ```

I don't think we need a README for a test contract ?!
___
*[`integration-tests/modules/testdata/wasm/nft/packages/coreum-wasm-sdk/Cargo.toml` line 13 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY336olB5qd2fXR7yI3:-NY336olB5qd2fXR7yI4:b3xaeg5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/nft/packages/coreum-wasm-sdk/Cargo.toml#L13)):*
> ```TOML
> serde = { version = "1.0.164", default-features = false, features = ["derive"] }
> schemars = "0.8.12"
> cosmwasm-schema = "1.2.6"
> ```

empty line needed.
___
*[`integration-tests/modules/testdata/wasm/nft/packages/coreum-wasm-sdk/.github/workflows/release.yml` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY33BCn4lh9ajeJdxgk:-NY33BCn4lh9ajeJdxgl:b132ve9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/nft/packages/coreum-wasm-sdk/.github/workflows/release.yml#L1)):*
> ```YAML
> name: release
> ```

we should remove the copied package and just point to the new version after it is merged.
___
*[`integration-tests/modules/testdata/wasm/simple-state/Cargo.toml` line 37 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY33T5xAFsxs1RVdI-A:-NY33T5y9pLYJyHdAooX:b3xaeg5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/simple-state/Cargo.toml#L37)):*
> ```TOML
> cosmwasm-schema = "1.2.6"
> cw-storage-plus = "1.0.1"
> ```

empty line needed.
___
*[`integration-tests/modules/testdata/wasm/simple-state/src/lib.rs` line 4 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY33a9E8ITFyb5gM5Dd:-NY33a9E8ITFyb5gM5De:b3xaeg5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/simple-state/src/lib.rs#L4)):*
> ```XML
> pub mod error;
> pub mod msg;
> pub mod state;
> ```

empty line needed.
___
*[`integration-tests/modules/testdata/wasm/simple-state/src/msg.rs` line 23 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY33Yj3EupE4BURpqaR:-NY33Yj3EupE4BURpqaS:b3xaeg5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/simple-state/src/msg.rs#L23)):*
> ```XML
> pub struct CountResponse {
>     pub count: i32,
> }
> ```

empty line needed.
___
*[`integration-tests/modules/testdata/wasm/simple-state/src/state.rs` line 3 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY33bnE1TTxO0a9WKuq:-NY33bnE1TTxO0a9WKur:b7003w6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/simple-state/src/state.rs#L3)):*
> ```XML
> use cw_storage_plus::Item;
> 
> pub const COUNTER: Item<i32> = Item::new("counter");
> ```

empty line neded.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: 30 of 48 files reviewed, 16 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY2WCPuBt3zy7OujnQD:-NY35Nke5TxHvrkK-Tf1:bpcvvhw) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Clear. So the `coreum-wasm-sdk v.0.1.2` should be merged first.
</blockquote></details>

Correct, this one should not be merged yet.

___
___
*[`integration-tests/modules/testdata/wasm/bank-send/src/lib.rs` line 3 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY2zpWC8SqOcnw2oQCl:-NY35WZW2RoeVaiG9_sM:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/bank-send/src/lib.rs#L3)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you need an empty line. notice the red marker
</blockquote></details>

Done.
___
*[`integration-tests/modules/testdata/wasm/bank-send/src/msg.rs` line 14 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY2ztlI327xJFRyTt8a:-NY35Ws-5hgDDViPG1Zd:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/bank-send/src/msg.rs#L14)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you need and empty line
</blockquote></details>

Done.
___
*[`integration-tests/modules/testdata/wasm/ft/README.md` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY35oa8BRGK_vCf7ONM:-NY35oa8BRGK_vCf7ONN:bu9rh9d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/ft/README.md#L1)):*
> ```Markdown
> # FT Contract
> ```

Really? I added all the information here because the coreum-wasm-sdk package links to this repository for new users looking for Smart contract examples.
___
*[`integration-tests/modules/testdata/wasm/ft/packages/coreum-wasm-sdk/Cargo.toml` line 13 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY3-A_jAtjeuLSvEsns:-NY36ALo7tmgllw0w4QY:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/ft/packages/coreum-wasm-sdk/Cargo.toml#L13)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

empty line needed.
</blockquote></details>

Done.
___
*[`integration-tests/modules/testdata/wasm/ft/packages/coreum-wasm-sdk/.github/workflows/release.yml` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY3-If-8Rv6V2aY-S3K:-NY36KJ55PyL93oA7cDi:bss4a2b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/ft/packages/coreum-wasm-sdk/.github/workflows/release.yml#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this file should not exist.
</blockquote></details>

Removed.
___
*[`integration-tests/modules/testdata/wasm/ft/packages/coreum-wasm-sdk/src/assetnft.rs` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY3-Sio2gCXPgUInoy-:-NY36MQzBKNMT9eb6TCa:bjdlhgv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/ft/packages/coreum-wasm-sdk/src/assetnft.rs#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I assume you have copied the sdk code here, but that seems to not be the right approach. the correct version of the sdk must be used after the other PR is merged. 
</blockquote></details>

Yes, that's the plan. We don't merge this until I've removed the package and updated the version. I needed to do it this way for now because the other PR is not merged yet and the new version is not on crates.io
___
*[`integration-tests/modules/testdata/wasm/nft/README.md` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY330fP8ZNJ4rR5L3R1:-NY36YVDBgI8xY8Ajnte:b2nreh6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/nft/README.md#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think we need a README for a test contract ?!
</blockquote></details>

Same as above.
___
*[`integration-tests/modules/testdata/wasm/nft/packages/coreum-wasm-sdk/Cargo.toml` line 13 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY336olB5qd2fXR7yI3:-NY36_fC0ew-nr6D88EI:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/nft/packages/coreum-wasm-sdk/Cargo.toml#L13)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

empty line needed.
</blockquote></details>

Done.
___
*[`integration-tests/modules/testdata/wasm/nft/packages/coreum-wasm-sdk/.github/workflows/release.yml` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY33BCn4lh9ajeJdxgk:-NY36a5d57UsvqZw77x3:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/nft/packages/coreum-wasm-sdk/.github/workflows/release.yml#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we should remove the copied package and just point to the new version after it is merged.
</blockquote></details>

Done.
___
*[`integration-tests/modules/testdata/wasm/simple-state/src/lib.rs` line 4 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY33a9E8ITFyb5gM5Dd:-NY36hFZ3-cxOoHdZnUo:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/simple-state/src/lib.rs#L4)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

empty line needed.
</blockquote></details>

Done.
___
*[`integration-tests/modules/testdata/wasm/simple-state/src/msg.rs` line 23 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY33Yj3EupE4BURpqaR:-NY36hUZ4Ktpex81wUTm:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/simple-state/src/msg.rs#L23)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

empty line needed.
</blockquote></details>

Done.
___
*[`integration-tests/modules/testdata/wasm/simple-state/src/state.rs` line 3 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY33bnE1TTxO0a9WKuq:-NY36hni7j2x11rMLA09:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/simple-state/src/state.rs#L3)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

empty line neded.
</blockquote></details>

Done.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: 26 of 48 files reviewed, 15 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/testdata/wasm/ft/README.md` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY3-5939BYz14nyKoU-:-NY4AVpU7Tlt3QmhL-z8:b-xesutq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c5d61789988fd68aad4311945b5e100adb1e55a3/integration-tests/modules/testdata/wasm/ft/README.md#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think this README file is not needed ! 
</blockquote></details>

Like agreed, we are keeping it.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: 41 of 52 files reviewed, 15 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NY2V2XK-zMbAwgFV7bU:-NYHrvUB3dRcFujzmWbR:bheqabb) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Ok, let's discuss. 
</blockquote></details>

Ok this is fixed now.

___

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 10 of 11 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: all files reviewed, 15 unresolved discussions (waiting on @keyleu, @miladz68, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 11 of 11 files at r3, 4 of 11 files at r4, 27 of 27 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 966 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NYNK5_L7Mp2IBPSROFc:-NYNK5_L7Mp2IBPSROFd:bj8hhp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9aeb49e0d9e545cbb8fa81dcf6d6baf743fc807e/integration-tests/modules/wasm_test.go#L966)):*
> ```Go
> 	requireT.NoError(json.Unmarshal(queryOut, &wasmTokensRes))
> 	requireT.Equal(
> 		expectedToken.Denom, wasmTokensRes.Tokens[0].Denom,
> ```

Why do you validate denom only?

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 966 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NYNK5_L7Mp2IBPSROFc:-NYNMA9q6QXommDVx0GW:b4b98fg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9aeb49e0d9e545cbb8fa81dcf6d6baf743fc807e/integration-tests/modules/wasm_test.go#L966)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you validate denom only?
</blockquote></details>

The wasm sdk version 0.1.1 had a structure 

pub struct Token {
    pub denom: String,
    pub issuer: String,
    pub symbol: String,
    pub subunit: String,
    pub precision: u32,
    pub description: Option<String>,
    pub features: Option<Vec<u32>>,
    pub burn_rate: String,
    pub send_commission_rate: String,
}

But the proto file includes a uint32 version = 6 at the end.
In the individual token test it does this before equaling:
wasmTokenRes.Token.Version = expectedToken.Version // test should work with any version
to make sure version is the same.

If you want I can change it to validate everything and hardcode the version in the same way, I thought checking the denom looks more understandable to see that we receive the same token (all the fields are the same anyways).

I can change it if you want.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1565 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NYNNZvP3cZkd2ZX32Iu:-NYNNZvP3cZkd2ZX32Iv:b6pjcvb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9aeb49e0d9e545cbb8fa81dcf6d6baf743fc807e/integration-tests/modules/wasm_test.go#L1565)):*
> ```Go
> 	requireT.NoError(json.Unmarshal(queryOut, &nftClassesQueryRes))
> 
> 	var found = classInArray(nftClass{
> ```

You can replace with 
```
requireT.Contains(nftClass{
		ID:          expectedClass.Id,
		Name:        expectedClass.Name,
		Symbol:      expectedClass.Symbol,
		Description: expectedClass.Description,
		URI:         expectedClass.URI,
		URIHash:     expectedClass.URIHash,
		Data:        dataString,
	}, nftClassesQueryRes.Classes)
```

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: all files reviewed, 2 unresolved discussions (waiting on @keyleu and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 966 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NYNK5_L7Mp2IBPSROFc:-NYNNkdd72u2UxpmqGtV:b-z3ubjz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9aeb49e0d9e545cbb8fa81dcf6d6baf743fc807e/integration-tests/modules/wasm_test.go#L966)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

The wasm sdk version 0.1.1 had a structure 

pub struct Token {
    pub denom: String,
    pub issuer: String,
    pub symbol: String,
    pub subunit: String,
    pub precision: u32,
    pub description: Option<String>,
    pub features: Option<Vec<u32>>,
    pub burn_rate: String,
    pub send_commission_rate: String,
}

But the proto file includes a uint32 version = 6 at the end.
In the individual token test it does this before equaling:
wasmTokenRes.Token.Version = expectedToken.Version // test should work with any version
to make sure version is the same.

If you want I can change it to validate everything and hardcode the version in the same way, I thought checking the denom looks more understandable to see that we receive the same token (all the fields are the same anyways).

I can change it if you want.
</blockquote></details>

IMO better to set the version validate the entire struct.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 966 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NYNK5_L7Mp2IBPSROFc:-NYNOSQV2ZGidS8GL88j:b-tstj4a) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9aeb49e0d9e545cbb8fa81dcf6d6baf743fc807e/integration-tests/modules/wasm_test.go#L966)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO better to set the version validate the entire struct. 
</blockquote></details>

Ok I'll change it.
___
*[`integration-tests/modules/wasm_test.go` line 1565 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NYNNZvP3cZkd2ZX32Iu:-NYNOLYmAFKe1BBIKEWX:bckjk2b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9aeb49e0d9e545cbb8fa81dcf6d6baf743fc807e/integration-tests/modules/wasm_test.go#L1565)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You can replace with 
```
requireT.Contains(nftClass{
		ID:          expectedClass.Id,
		Name:        expectedClass.Name,
		Symbol:      expectedClass.Symbol,
		Description: expectedClass.Description,
		URI:         expectedClass.URI,
		URIHash:     expectedClass.URIHash,
		Data:        dataString,
	}, nftClassesQueryRes.Classes)
```
</blockquote></details>

I had a problem with this because it returned it in different orders (only happened with nft module)

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: 51 of 52 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1565 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NYNNZvP3cZkd2ZX32Iu:-NYNPAAO1uw_sHDOIg6I:b-cxld07) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9aeb49e0d9e545cbb8fa81dcf6d6baf743fc807e/integration-tests/modules/wasm_test.go#L1565)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

I had a problem with this because it returned it in different orders (only happened with nft module)
</blockquote></details>

There were 3 classes in the array, and sometimes it would be in position 0, sometimes 1 and sometimes 2. So I just checked it was in there to ensure tests didn't fail.

**Review by keyleu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: 51 of 52 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 1565 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/525#-NYNNZvP3cZkd2ZX32Iu:-NYNPTk24TZrJ0P2P7_U:b-x6y7jl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9aeb49e0d9e545cbb8fa81dcf6d6baf743fc807e/integration-tests/modules/wasm_test.go#L1565)):*
<details><summary><i>Previously, keyleu (Keyne) wrote…</i></summary><blockquote>

There were 3 classes in the array, and sometimes it would be in position 0, sometimes 1 and sometimes 2. So I just checked it was in there to ensure tests didn't fail.
</blockquote></details>

Oh nevermind, you meant Contains. My mistake. Ok, will change.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: 51 of 52 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/525)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
