### PR TITLE
Build `cored` binary and docker image with cometBFT replaced

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/858)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/858)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/coreum/build.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/858#-Nz2gmKu7HDv-jMDjba-:-Nz2gmKu7HDv-jMDjba0:bg38qqd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e87c1cb6dc5fb720bfac4ff61ef14b1b488f47b0/build/coreum/build.go#L28)):*
> ```Go
> 	extendedBinaryPath = "bin/" + extendedBinaryName
> 	testsDir           = repoPath + "/integration-tests"
> 	cometBFTCommit     = "2644973fb58663f435aac0c6bdf9502fe78798a0"
> ```

Don't you want to pass it as a flag or argument to the CLI?
___
*[`build/coreum/build.go` line 82 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/858#-Nz2h3Qx3TB12XZMuMcw:-Nz2h3Qx3TB12XZMuMcx:b-iq0qqv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e87c1cb6dc5fb720bfac4ff61ef14b1b488f47b0/build/coreum/build.go#L82)):*
> ```Go
> 	defer f.Close()
> 
> 	_, err = f.WriteString("replace github.com/cometbft/cometbft => github.com/CoreumFoundation/cometbft " +
> ```

I would recommend adding a check that the file contains `github.com/cometbft/cometbft` dependency.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/858)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`build/coreum/build.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/858#-Nz2gmKu7HDv-jMDjba-:-Nz370Z96_ns7-cKBRAY:bwo38oe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e87c1cb6dc5fb720bfac4ff61ef14b1b488f47b0/build/coreum/build.go#L28)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Don't you want to pass it as a flag or argument to the CLI?
</blockquote></details>

builder doesn't support flags
___
*[`build/coreum/build.go` line 82 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/858#-Nz2h3Qx3TB12XZMuMcw:-Nz375ivAO45M5NKCVYF:b-i9x71v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e87c1cb6dc5fb720bfac4ff61ef14b1b488f47b0/build/coreum/build.go#L82)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would recommend adding a check that the file contains `github.com/cometbft/cometbft` dependency.
</blockquote></details>

what for?

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/858)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`build/coreum/build.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/858#-Nz2gmKu7HDv-jMDjba-:-Nz3D6AmCni7odL3Ultu:b15qi2u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e87c1cb6dc5fb720bfac4ff61ef14b1b488f47b0/build/coreum/build.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

builder doesn't support flags
</blockquote></details>

What about args ?
___
*[`build/coreum/build.go` line 82 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/858#-Nz2h3Qx3TB12XZMuMcw:-Nz3D8nJ0KlkvC1lMNzK:b-1l3vqq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e87c1cb6dc5fb720bfac4ff61ef14b1b488f47b0/build/coreum/build.go#L82)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what for?
</blockquote></details>

Because if there is no dependency you are replacing, the replace line will be added, and the build will pass, but shouldn't.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/858)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`build/coreum/build.go` line 28 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/858#-Nz2gmKu7HDv-jMDjba-:-NzCJCQo0aXcrqdW6o6a:b-a7pwx0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e87c1cb6dc5fb720bfac4ff61ef14b1b488f47b0/build/coreum/build.go#L28)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about args ?
</blockquote></details>

it doesn't support args
___
*[`build/coreum/build.go` line 82 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/858#-Nz2h3Qx3TB12XZMuMcw:-NzCJGOS72iluYFxXBoc:b7znszt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e87c1cb6dc5fb720bfac4ff61ef14b1b488f47b0/build/coreum/build.go#L82)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Because if there is no dependency you are replacing, the replace line will be added, and the build will pass, but shouldn't.
</blockquote></details>

but we know the dependency is there by definition

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/858)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`build/coreum/build.go` line 28 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/858#-NzT67_m5Mfr1SRuIkfX:-NzT67_m5Mfr1SRuIkfY:b-gynka9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1eea202a5f77d056a6dfa78468e21a1273c23a0d/build/coreum/build.go#L28)):*
> ```Go
> 	extendedBinaryPath = "bin/" + extendedBinaryName
> 	testsDir           = repoPath + "/integration-tests"
> 	cometBFTCommit     = "2644973fb58663f435aac0c6bdf9502fe78798a0"
> ```

but the PR is directed to the master, why do we need this hardcoded value in master ?

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/858)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/858)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

**Pull request merged**
