### PR TITLE
Add query NFT classes with migration.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/484)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/484)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4YVJc4tc9WuKIGq0i:-NV4YVJc4tc9WuKIGq0j:b-lw3k) (no related file):*
It would be nice to have a full upgrade integration test

___
___
*[`x/asset/nft/keeper/keeper_test.go` line 69 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4V6GkA-KuW4h2JlKH:-NV4V6GkA-KuW4h2JlKI:bvq93u5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e81933643b6de8225d11696e53d605a034bd8a52/x/asset/nft/keeper/keeper_test.go#L69)):*
> ```Go
> 	requireT.True(types.ErrInvalidInput.Is(err))
> 
> 	// try to get non-invalid class
> ```

non-invalid?
___
*[`x/asset/nft/keeper/keeper_test.go` line 73 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4VD0e1OGSyfs50Cuu:-NV4VD0e1OGSyfs50Cuv:b-i1fyss) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e81933643b6de8225d11696e53d605a034bd8a52/x/asset/nft/keeper/keeper_test.go#L73)):*
> ```Go
> 	requireT.ErrorIs(err, types.ErrInvalidInput)
> 
> 	//// try to get nonexistent class
> ```

//// -> //
___
*[`x/asset/nft/keeper/keeper_test.go` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4Vh-r8GjOfRi6-yO_:-NV4Vh-s2CSUQ8SleMGf:bidnbnd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e81933643b6de8225d11696e53d605a034bd8a52/x/asset/nft/keeper/keeper_test.go#L128)):*
> ```Go
> 
> 	for i := range classes {
> 		requireClassSettingsEqualClass(requireT, allSettings[i], classes[i])
> ```

can't you compare slices using built-in functions?
___
*[`x/asset/nft/legacy/v1/store.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4WLZz64CiSKCiAMfi:-NV4WL_--QSMcZ0DJdgQ:bts0whp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e81933643b6de8225d11696e53d605a034bd8a52/x/asset/nft/legacy/v1/store.go#L32)):*
> ```Go
> 	}
> 
> 	return oldStoreIter.Close()
> ```

`Close() should be called in `defer` present immediately after creating the iterator
___
*[`x/asset/nft/types/keys.go` line 45 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4Wox9-uXcaLHt_19G:-NV4Wox9-uXcaLHt_19H:b-9365zl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e81933643b6de8225d11696e53d605a034bd8a52/x/asset/nft/types/keys.go#L45)):*
> ```Go
> // CreateIssuerClassPrefix constructs the key for the non-fungible token class for the specific issuer.
> func CreateIssuerClassPrefix(issuer sdk.AccAddress) []byte {
> 	return store.JoinKeys(NFTClassKeyPrefix, issuer)
> ```

I think we should use length here. This is what comos sdk always does when address is part of the key

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/484)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4YVJc4tc9WuKIGq0i:-NV4xuYv1tguTrWotv9W:bc051ej) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It would be nice to have a full upgrade integration test
</blockquote></details>

It will be,  I'm blocked by muti step upgrade task.

___
___
*[`x/asset/nft/keeper/keeper_test.go` line 69 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4V6GkA-KuW4h2JlKH:-NV4y7-s1OAkn2uqHqJc:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e81933643b6de8225d11696e53d605a034bd8a52/x/asset/nft/keeper/keeper_test.go#L69)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

non-invalid?
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper_test.go` line 73 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4VD0e1OGSyfs50Cuu:-NV4y8PB0dHRPLvBULPB:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e81933643b6de8225d11696e53d605a034bd8a52/x/asset/nft/keeper/keeper_test.go#L73)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

//// -> //
</blockquote></details>

Done.
___
*[`x/asset/nft/keeper/keeper_test.go` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4Vh-r8GjOfRi6-yO_:-NV4yEFWE7Hl3epUChOP:b-c2dz9f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e81933643b6de8225d11696e53d605a034bd8a52/x/asset/nft/keeper/keeper_test.go#L128)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

can't you compare slices using built-in functions?
</blockquote></details>

Nope, since we compare the `Class` and `ClassSettings`
___
*[`x/asset/nft/legacy/v1/store.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4WLZz64CiSKCiAMfi:-NV4y_a58B5AjEzHVsEc:b-10ebgh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e81933643b6de8225d11696e53d605a034bd8a52/x/asset/nft/legacy/v1/store.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`Close() should be called in `defer` present immediately after creating the iterator
</blockquote></details>

But in that case you won't get an error. Or you will have to use the naming returns. 
___
*[`x/asset/nft/types/keys.go` line 45 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4Wox9-uXcaLHt_19G:-NV4zPOHAtRqKKvfKWrl:b-ijut2z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e81933643b6de8225d11696e53d605a034bd8a52/x/asset/nft/types/keys.go#L45)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I think we should use length here. This is what comos sdk always does when address is part of the key
</blockquote></details>

In that case we won't be able to search by address.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 28 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/484)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/legacy/v1/store.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4WLZz64CiSKCiAMfi:-NVEL16O2aAzVQp6AUIt:br5lnuh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e81933643b6de8225d11696e53d605a034bd8a52/x/asset/nft/legacy/v1/store.go#L32)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But in that case you won't get an error. Or you will have to use the naming returns. 
</blockquote></details>

But in this implementation iterator stays open if error is returned in the loop
___
*[`x/asset/nft/types/keys.go` line 45 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4Wox9-uXcaLHt_19G:-NVELIV6Ea6q8mvpTP6p:b-d7bqfh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e81933643b6de8225d11696e53d605a034bd8a52/x/asset/nft/types/keys.go#L45)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

In that case we won't be able to search by address.
</blockquote></details>

why? during the search you just add the length to the prefix too

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/484)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/legacy/v1/store.go` line 32 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4WLZz64CiSKCiAMfi:-NVEreKTDougMM0fLSA5:bmk3113) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e81933643b6de8225d11696e53d605a034bd8a52/x/asset/nft/legacy/v1/store.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But in this implementation iterator stays open if error is returned in the loop
</blockquote></details>

Agree, update to defer 
___
*[`x/asset/nft/types/keys.go` line 45 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/484#-NV4Wox9-uXcaLHt_19G:-NVEqHmP8qJiJ5JosGpr:bolhc7s) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e81933643b6de8225d11696e53d605a034bd8a52/x/asset/nft/types/keys.go#L45)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why? during the search you just add the length to the prefix too
</blockquote></details>

Missed that, agree, updated.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/484)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/484)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 32 of 32 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/484)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
