### PR TITLE
Added doc for deterministic gas

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/308)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/308)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`x/deterministicgas/spec/README.md` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJo_0007hZXvd9Yc25J:-NJo_0007hZXvd9Yc25K:brv1zva) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L13)):*
> ```Markdown
> 
> Coreum is using a deterministic gas model for its transactions. Meaning that given a transaction type (e.g 
> bank.MsgSend) one can know how much gas will be used before hand, and this amount is fixed if some
> ```

the issue here is that bank.MsgSend is bad example 
___
*[`x/deterministicgas/spec/README.md` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJoaBSlBYCcAzVsnF_U:-NJoaBSlBYCcAzVsnF_V:b-14djx3) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L26)):*
> ```Markdown
> 
> `
> GasForExtraBytes = max(0, TxByteSize-FreeBytes) * TxSizeCostPerByte
> ```

would be nice to also have values for
1. TxSizeCostPerByte somewhere
2. SigVerifyCost
___
*[`x/deterministicgas/spec/README.md` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJoaKghEcQ0CiWbCzXo:-NJoaKghEcQ0CiWbCzXp:b-15k4g7) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L30)):*
> ```Markdown
> 
> `
> GasForExtraSignatures = max(0, NumOfSigs-FreeSigs) * SigVerifyCostSecp256k1
> ```

SigVerifyCostSecp256k1
I think we unified value for both sig types so we can use just smth like SigVerifyCost
___
*[`x/deterministicgas/spec/README.md` line 40 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJoa_pN1WT5kNygymHj:-NJoa_pN1WT5kNygymHk:b557njf) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L40)):*
> ```Markdown
> 
> 
> If the transaction size is under the FreeBytes limit and has only 
> ```

`FreeBytes limit and has only has one`

has repeated twice ?
___
*[`x/deterministicgas/spec/README.md` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJoajbvA1Kqi73nybkp:-NJoajbvA1Kqi73nybkq:b-ju1hn8) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L46)):*
> ```Markdown
> There are some special cases where an extra step is introduced to the formula. 
> 
> 1. bank.MsgSend: `DeterministicGasForMsg = DeterministicGasForMsgSend * NumberOfCoins`
> ```

I would make bank a separate section under Special Cases

```
### Special Cases
...
#### Bank
1.
2.
```
___
*[`x/deterministicgas/spec/README.md` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJo_mGj2gC40zBzfUMD:-NJo_mGj2gC40zBzfUME:blofcbo) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L49)):*
> ```Markdown
> 2. bank.MsgMultiSend: `DeterministicGasForMsg = DeterministicGasForMsgMultiSend * (NumberOfInputs + NumberOfOutputs)`
> 
> ## Deterministic Gas Table 
> ```

I would also add section with non deterministic Gas msg types
___
*[`x/deterministicgas/spec/README.md` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJo_KKgAJKhANX48zMQ:-NJo_KKgAJKhANX48zMR:b9copyw) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L52)):*
> ```Markdown
> 
> 
> | Tx Type                                | Gas  |
> ```

Message Type
___
*[`x/deterministicgas/spec/README.md` line 54 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJo_MrZ4FejdSAp6Wxm:-NJo_MrZ4FejdSAp6Wxn:b-7o1rgc) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L54)):*
> ```Markdown
> | Tx Type                                | Gas  |
> |----------------------------------------|------|
> |AssetIssueFungibleToken                  | 80000|
> ```

I would probably prefer to use full msg name with module `cosmos.distribution.v1beta1.MsgFundCommunityPool` or shorter version
`distribution.MsgFundCommunityPool`

Because these names are created by us and unknown for none else

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/308)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/spec/README.md` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJoaBSlBYCcAzVsnF_U:-NJocRQT6tfYapQ2j9Bu:bqog7zb) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

would be nice to also have values for
1. TxSizeCostPerByte somewhere
2. SigVerifyCost
</blockquote></details>

Agree.

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/308)* status: all files reviewed, 8 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/308)* status: all files reviewed, 10 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/spec/README.md` line 13 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJo_0007hZXvd9Yc25J:-NJohggUCyLbr-Na3CL9:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L13)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

the issue here is that bank.MsgSend is bad example 
</blockquote></details>

Done.
___
*[`x/deterministicgas/spec/README.md` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJoaBSlBYCcAzVsnF_U:-NJorKhn7WRh0lMqSuTQ:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L26)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree.
</blockquote></details>

Done.
___
*[`x/deterministicgas/spec/README.md` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJoaKghEcQ0CiWbCzXo:-NJoro7G8kBQ7fHMR07o:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L30)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

SigVerifyCostSecp256k1
I think we unified value for both sig types so we can use just smth like SigVerifyCost
</blockquote></details>

Done.
___
*[`x/deterministicgas/spec/README.md` line 40 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJoa_pN1WT5kNygymHj:-NJorqoF4wsSSV5lNTq4:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L40)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`FreeBytes limit and has only has one`

has repeated twice ?
</blockquote></details>

Done.
___
*[`x/deterministicgas/spec/README.md` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJodAZCC-GVWq9h9eIg:-NJos0BL7ZLHrDoA4Wzh:b-9sviwz) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L41)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

The sentence is not finished
</blockquote></details>

Removed duplicate sentence
___
*[`x/deterministicgas/spec/README.md` line 46 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJoajbvA1Kqi73nybkp:-NJos85i6qoeU3sesd2X:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L46)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would make bank a separate section under Special Cases

```
### Special Cases
...
#### Bank
1.
2.
```
</blockquote></details>

Done.
___
*[`x/deterministicgas/spec/README.md` line 49 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJo_mGj2gC40zBzfUMD:-NJougfk94vJ3SmIRhw8:b-9ge0hn) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L49)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would also add section with non deterministic Gas msg types
</blockquote></details>

added. and mentioned that all the messages related to wasm belong there.
___
*[`x/deterministicgas/spec/README.md` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJo_KKgAJKhANX48zMQ:-NJosYmW1wt_HBPTnlx_:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L52)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Message Type
</blockquote></details>

Done.
___
*[`x/deterministicgas/spec/README.md` line 54 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJo_MrZ4FejdSAp6Wxm:-NJotA4V3b5E5_6qHFND:br5px3h) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L54)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would probably prefer to use full msg name with module `cosmos.distribution.v1beta1.MsgFundCommunityPool` or shorter version
`distribution.MsgFundCommunityPool`

Because these names are created by us and unknown for none else
</blockquote></details>

I went with asset.Mint format
___
*[`x/deterministicgas/spec/README.md` line 54 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJodmtg8ZFLagf-LQqA:-NJowUxZ-0HxyIkDMhSX:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L54)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

Otherwise user will be confused by the difference between this table and his real Gas spending (He can forget about the formula)
</blockquote></details>

Done.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/308)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

___
*[`x/deterministicgas/spec/README.md` line 54 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJodmtg8ZFLagf-LQqA:-NJu5yHr3cz1Vgwz4VK3:bw3qhjn) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L54)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

good point
@silverspase FYI some values in this table are obviously wrong (no 50k of fixed fee subtracted) 
We are going to adjust all these values before testnet

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/308)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/308)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

___
*[`x/deterministicgas/spec/README.md` line 54 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NJodmtg8ZFLagf-LQqA:-NKISjluBazD61b3L4RN:b-2fqcru) ([raw file](https://github.com/coreumfoundation/coreum/blob/de5797f255f68b1bdae7d106edd103f5d60ca5b7/x/deterministicgas/spec/README.md#L54)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

good point
@silverspase FYI some values in this table are obviously wrong (no 50k of fixed fee subtracted) 
We are going to adjust all these values before testnet
</blockquote></details>

Done. please check it is done as you expected @silverspase

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/308)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68 and @silverspase)

___
*[`x/deterministicgas/spec/README.md` line 22 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NKIg1dM6iB0fppaycJP:-NKIg1dM6iB0fppaycJQ:b-eewd81) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff3f6df7896cd367992133b45577d118befc4329/x/deterministicgas/spec/README.md#L22)):*
> ```Markdown
> 
> `
> Gas = FixedGas + Sum(DeterministicGas for each message) + GasForExtraBytes + GasForExtraSignatures
> ```

+ Gas for nondeterministic messages
___
*[`x/deterministicgas/spec/README.md` line 41 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NKIgCdjAb6aTEqsFL-a:-NKIgCdjAb6aTEqsFL-b:bvff5tk) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff3f6df7896cd367992133b45577d118befc4329/x/deterministicgas/spec/README.md#L41)):*
> ```Markdown
> 
> As an example if the transaction has 1 signature on it and is below 
> 2048 bytes, the user will not pay any thing extra, and if one of those values exceed those limits, the user will pay for the extra resources.
> ```

any thing -> anything
exceed -> exceeds
___
*[`x/deterministicgas/spec/README.md` line 44 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NKIgIsF5BuoKPwHQGTc:-NKIgIsG8W89JXy0F4oC:bb6zjod) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff3f6df7896cd367992133b45577d118befc4329/x/deterministicgas/spec/README.md#L44)):*
> ```Markdown
> 
> #### Full example
> lets say we have a transaction with 2 messages of type 
> ```

Lets
___
*[`x/deterministicgas/spec/README.md` line 61 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NKIgTGr-0uhfKQAU9o2:-NKIgTGr-0uhfKQAU9o3:b-2um9rz) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff3f6df7896cd367992133b45577d118befc4329/x/deterministicgas/spec/README.md#L61)):*
> ```Markdown
> #### Bank
> 1. bank.MsgSend: `DeterministicGasForMsg = SendPerEntry * NumberOfCoins`
> 2. bank.MsgMultiSend: `DeterministicGasForMsg = MultiSendPerEntry * (NumberOfInputs + NumberOfOutputs)`
> ```

We take the `max(NumberOfInputs, NumberOfOutputs)`, not the sum.

It is also not explained what SendPerEntry and MultiSendPerEntry are

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/308)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @wojtek-coreum and @ysv)

___
*[`x/deterministicgas/spec/README.md` line 22 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NKIg1dM6iB0fppaycJP:-NKIocrw2_dXhQXXhTzO:bku5ku) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff3f6df7896cd367992133b45577d118befc4329/x/deterministicgas/spec/README.md#L22)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

+ Gas for nondeterministic messages
</blockquote></details>

Fixed to describe nondeterministic, please check. 
___
*[`x/deterministicgas/spec/README.md` line 41 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NKIgCdjAb6aTEqsFL-a:-NKIolsN7yQeEOrLBjhv:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff3f6df7896cd367992133b45577d118befc4329/x/deterministicgas/spec/README.md#L41)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

any thing -> anything
exceed -> exceeds
</blockquote></details>

Done.
___
*[`x/deterministicgas/spec/README.md` line 44 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NKIgIsF5BuoKPwHQGTc:-NKIoorOD5bZaM2gJE0t:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff3f6df7896cd367992133b45577d118befc4329/x/deterministicgas/spec/README.md#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Lets
</blockquote></details>

Done.
___
*[`x/deterministicgas/spec/README.md` line 61 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NKIgTGr-0uhfKQAU9o2:-NKIpO0B5DxkFTYnRHpz:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff3f6df7896cd367992133b45577d118befc4329/x/deterministicgas/spec/README.md#L61)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

We take the `max(NumberOfInputs, NumberOfOutputs)`, not the sum.

It is also not explained what SendPerEntry and MultiSendPerEntry are
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/308)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68)

___
*[`x/deterministicgas/spec/README.md` line 22 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NKIg1dM6iB0fppaycJP:-NKJ0TJE9kUhDoUmzHmW:b8mtfso) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff3f6df7896cd367992133b45577d118befc4329/x/deterministicgas/spec/README.md#L22)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Fixed to describe nondeterministic, please check. 
</blockquote></details>

uhm, reviewable formatte my first comment. I meant `+ Gas for nondeterministic messages` in the formula

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/308)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

___
*[`x/deterministicgas/spec/README.md` line 22 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/308#-NKIg1dM6iB0fppaycJP:-NKMdPKN0B9LXJ8i0_wJ:b-rqcsyt) ([raw file](https://github.com/coreumfoundation/coreum/blob/ff3f6df7896cd367992133b45577d118befc4329/x/deterministicgas/spec/README.md#L22)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

uhm, reviewable formatte my first comment. I meant `+ Gas for nondeterministic messages` in the formula
</blockquote></details>

isn't non deterministic gas is determined for each message type, similar to what I have written ?

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/308)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
