### PR TITLE
benchmark bank transfer in case 100k denoms are defined

### PR DESCRIPTION
**Pull request by miladz68**
Defining 100k Denoms affects bank send performance marginally it goes from 20 ms to 23 ms for single bank send.
```
Benchmark100KDenomBankSend/test-single-send-8         	   74112	     20356 ns/op	   10659 B/op	     172 allocs/op
Benchmark100KDenomBankSend/test-100k-denom-send-8     	   55047	     23165 ns/op	   10982 B/op	     175 allocs/op
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/210)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
what about 1mln?

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/210#-:-NDDbzSW2GHB7LhkFGwX:bqzk5mf)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @begmaroman, @dzmitryhil, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
After reviewing I left a plenty of comments & want to discuss them on call
I also have some other points to discuss:
1. I still don't feel confident after doing these benchmarks about performance
2. Can we somehow dump the sate & use it outside of benchmarks ?
3. how does simapp behave in terms of blocks/tx execute etc here ?

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/210#-:-NDSrG_a6oS9kkUIobHD:b-fi4txy)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`integration-tests/benchmarks/bank_test.go` line 1 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSevAF9pya4daPixW6:-NDSevAICLNLLX6mWGnl:b-hlweyc) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L1)):*
> ```Go
> package benchmarks
> ```

I disagree for this test to be located in `integration-tests`
___
*[`integration-tests/benchmarks/bank_test.go` line 1 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSk3lV2wqrRcHF0-Yr:-NDSk3lV2wqrRcHF0-Ys:bfvzdd8) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L1)):*
> ```Go
> package benchmarks
> ```

how much time do these tests take to execute ?
___
*[`integration-tests/benchmarks/bank_test.go` line 53 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSr56zCX8vXVkj0mhv:-NDSr56zCX8vXVkj0mhw:bqdf18u) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L53)):*
> ```Go
> }
> 
> func Benchmark100KDenomBankSend(b *testing.B) {
> ```

actually test-single-send & test-100k-denom-send are almost equal and could be refactored into a single func to avoid code duplication
___
*[`integration-tests/benchmarks/bank_test.go` line 66 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSjSD7Dkuq9DrEfxNJ:-NDSjSD7Dkuq9DrEfxNK:b-o10of1) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L66)):*
> ```Go
> 		b.StopTimer()
> 		var addresses []sdk.AccAddress
> 		for i := 0; i < b.N; i++ {
> ```

as I can see this for loop is not a part of benchmark and I don't understand why we use `b.N` here.
What is more we can't control the number of accounts used during this test which is also an important part

I propose to  preallocate some fixed number of accs and the just use them in benchmarked part of test. You actually already do this (`addresses[i]`)
___
*[`integration-tests/benchmarks/bank_test.go` line 70 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSjy_89idyIiQiyz3L:-NDSjy_89idyIiQiyz3M:b-j6mrul) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L70)):*
> ```Go
> 			addresses = append(addresses, address)
> 			amount := sdk.NewCoins(sdk.NewCoin(singleCoinDenom, sdk.NewInt(10)))
> 			err = bankKeeper.SendCoinsFromModuleToAccount(sdkContext, minttypes.ModuleName, address, amount)
> ```

shouldn't we assert for error here ?
___
*[`integration-tests/benchmarks/bank_test.go` line 85 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSiwDo0ERt835Ay5jg:-NDSiwDo0ERt835Ay5jh:b-hv6qlu) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L85)):*
> ```Go
> 	b.Run("test-100k-denom-send", func(b *testing.B) {
> 		b.StopTimer()
> 		var denoms []string
> ```

not-critical but it is better to pre-allocate size of underlying array since it is known
```
denoms := make([]string, 0, 100_000)
// and use append

// or
denoms := make([]string, 100_000)
// ...
denoms[i] = denom
```

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/210)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`integration-tests/benchmarks/bank_test.go` line 116 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSs6BQEyjZrUpeQQaV:-NDSs6BQEyjZrUpeQQaW:b2iuhys) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L116)):*
> ```Go
> }
> 
> func Benchmark100KDenomBankModuleSend(b *testing.B) {
> ```

can we also get results for this bench ?
___
*[`integration-tests/benchmarks/bank_test.go` line 171 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSs2OJ6Q7jyr564Rwd:-NDSs2OJ6Q7jyr564Rwe:b2iuhys) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L171)):*
> ```Go
> }
> 
> func Benchmark100KDenomBankGetSupply(b *testing.B) {
> ```

can we also get results for this bench ?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/210)* status: all files reviewed, 8 unresolved discussions (waiting on @begmaroman and @miladz68)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/210)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman and @miladz68)

___
*[`integration-tests/benchmarks/bank_test.go` line 1 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSevAF9pya4daPixW6:-NDTNhi14pceALaWjanN:b3am63e) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I disagree for this test to be located in `integration-tests`
</blockquote></details>

x/bank/benchmark/
or 
x/bank/bank_bench_test
...
___
*[`integration-tests/benchmarks/bank_test.go` line 116 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSs6BQEyjZrUpeQQaV:-NDTPiuk7gkUvV2vTfrj:b1vyu18) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L116)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can we also get results for this bench ?
</blockquote></details>

I think this one could be removed 
___
*[`integration-tests/benchmarks/bank_test.go` line 171 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSs2OJ6Q7jyr564Rwd:-NDTPrUb35HfiowAFAFt:b-dhd1tk) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L171)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can we also get results for this bench ?
</blockquote></details>

Lets bench the method/methods which is repeated mostly in different modules

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/210)* status: all files reviewed, 8 unresolved discussions (waiting on @begmaroman and @miladz68)

___
*[`integration-tests/benchmarks/bank_test.go` line 31 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDWztG0EviZTu-x8V0t:-NDWztG0EviZTu-x8V0u:b76nxsi) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L31)):*
> ```Go
> 	})
> 
> 	encoding := config.NewEncodingConfig(app.ModuleBasics)
> ```

Please list required modules directly instead of taking `app.ModuleBasics` - it elads us to libwasm dependency

**Review by miladz68 — COMMENTED** [review]
results for getSupply
```
Benchmark100KDenomBankGetSupply/test-single-get-supply-8         	  744345	      1574 ns/op	     416 B/op	      18 allocs/op
Benchmark100KDenomBankGetSupply/test-100k-get-supply-8           	  908340	      1289 ns/op	     264 B/op	       7 allocs/op

```

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/210#-:-NDhCAPkCF70UzRMdu8n:b-4gezfe)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @wojtek-coreum, and @ysv)

___
*[`integration-tests/benchmarks/bank_test.go` line 1 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSevAF9pya4daPixW6:-NDh43RI1pMCduXcL83V:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

x/bank/benchmark/
or 
x/bank/bank_bench_test
...
</blockquote></details>

Done.
___
*[`integration-tests/benchmarks/bank_test.go` line 31 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDWztG0EviZTu-x8V0t:-NDh4uOl8r2U8oy9wnOD:b-nvcft2) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L31)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please list required modules directly instead of taking `app.ModuleBasics` - it elads us to libwasm dependency
</blockquote></details>

It is not that simple. since SimApp is registering all the modules (it is using the same NewApp function ) then basically all the modules must be registered. even if we dont register some modules inside ModuleBasics it is will be required in go.mod as it is used in the NewApp. 
Moreover I don't think having a dependency on wasm is an issue since the source is inside coreum and it is using a shared go.mod anyway.
___
*[`integration-tests/benchmarks/bank_test.go` line 53 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSr56zCX8vXVkj0mhv:-NDhCLt9AayXLJN7BLI7:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L53)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

actually test-single-send & test-100k-denom-send are almost equal and could be refactored into a single func to avoid code duplication
</blockquote></details>

Done.
___
*[`integration-tests/benchmarks/bank_test.go` line 66 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSjSD7Dkuq9DrEfxNJ:-NDhCMgz7988VCllsbWY:b-amcmdn) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L66)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

as I can see this for loop is not a part of benchmark and I don't understand why we use `b.N` here.
What is more we can't control the number of accounts used during this test which is also an important part

I propose to  preallocate some fixed number of accs and the just use them in benchmarked part of test. You actually already do this (`addresses[i]`)
</blockquote></details>

I did check it and the for loop is necessary. basically golang gives the test `b.N` and you are responsible to run your action `b.N` times. however golang calls the Run function with different values of N to find a good guesstimation for an appropriate value.
___
*[`integration-tests/benchmarks/bank_test.go` line 70 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSjy_89idyIiQiyz3L:-NDhCqMSAZXopcv0OOjS:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L70)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

shouldn't we assert for error here ?
</blockquote></details>

Done.
___
*[`integration-tests/benchmarks/bank_test.go` line 85 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSiwDo0ERt835Ay5jg:-NDhDbND0Rx0YMUDjIqt:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L85)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

not-critical but it is better to pre-allocate size of underlying array since it is known
```
denoms := make([]string, 0, 100_000)
// and use append

// or
denoms := make([]string, 100_000)
// ...
denoms[i] = denom
```
</blockquote></details>

Done
___
*[`integration-tests/benchmarks/bank_test.go` line 116 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSs6BQEyjZrUpeQQaV:-NDh8_aJ5xAOs6wmNWup:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L116)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think this one could be removed 
</blockquote></details>

Done
___
*[`integration-tests/benchmarks/bank_test.go` line 171 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/210#-NDSs2OJ6Q7jyr564Rwd:-NDhDh2s2U0Y_umf35hF:bmzgcwt) ([raw file](https://github.com/coreumfoundation/coreum/blob/dda313faeb7b5d0f1172e2b9700f90dbbd9398b8/integration-tests/benchmarks/bank_test.go#L171)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Lets bench the method/methods which is repeated mostly in different modules
</blockquote></details>

As discussed in the call, we decided to check the methods that return a list or are iterations and see if they are used in other packages. no such methods are used in other modules. However `GetAllBalances` which returns all balanaces of a single account is used in the cli so if the user runs that query via cli and they have thousands of deoms, they all will be printed out. that is the only place that I could find such methods to be used.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/210)* status: all files reviewed, 6 unresolved discussions (waiting on @begmaroman and @ysv)

**Review by ysv — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/210)* status: all files reviewed, 6 unresolved discussions (waiting on @begmaroman and @ysv)

**Review by ysv — APPROVED** [review]
approving & resolving discussions to not block merging while I'm on vacation
@dzmitryhil @wojtek-coreum pls check

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/210#-:-NDtTSWu4yKCGPuCcs1v:b-sh0764)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/210)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/210)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
