### PR TITLE
Store checksums of released `cored` binaries

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/705)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/705)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/release.yml` line 45 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/705#-NidrpGf2A7fdbpohJRC:-NidrpGf2A7fdbpohJRD:btm9bir) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ddc6c2eab6bf107bfa2eb59207108b3a5b2af6ee/.github/workflows/release.yml#L45)):*
> ```YAML
>           ln crust/bin/.cache/cored/docker.amd64/bin/cored cored-linux-amd64
>           ln crust/bin/.cache/cored/docker.arm64/bin/cored cored-linux-arm64
>           sha256sum cored-* > checksums.txt
> ```

Share please an example of the file.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/705)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/release.yml` line 45 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/705#-NidrpGf2A7fdbpohJRC:-NiiBcCs-QMupRvPn0Sj:bqnc32x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ddc6c2eab6bf107bfa2eb59207108b3a5b2af6ee/.github/workflows/release.yml#L45)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Share please an example of the file.
</blockquote></details>

```
b517e9845c6fd68fa6feae98dc98931f2e414f66dccab52e21b51a4bdd106b68  cored-linux-amd64
bb9b9294aeda673187e3f5b808b88f8dcb1734967a557b486e2c6269902b5298  cored-linux-arm64
```

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/705)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/705)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/705)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/705)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/705)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/705)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/705)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
