### PR TITLE
Add upgrade integration-tests checking gov proposal migration v45->v47

### PR DESCRIPTION
**Pull request by ysv**
# Description

This PR adds upgrade integration-test where we:
1. create gov proposal on deposit status
2. run upgrade of chain
3. deposit funds to previously create proposal
4. vote for the proposal
5. check final proposal status

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/655)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/655)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/upgrade/gov_migration_test.go` line 96 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/655#-NeNfhA80KN3XhQbZnxs:-NeNfhA9CjATeGJQbBby:b-jhut7u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b4f0b2a045e66665f11705cb6cddb453c3ee40d5/integration-tests/upgrade/gov_migration_test.go#L96)):*
> ```Go
> 	requireT.NoError(err)
> 	requireT.Equal(govtypesv1.StatusDepositPeriod, proposal.Status)
> 	requireT.Equal("", proposal.Proposer) // question here
> ```

even though we pass proposer when creating proposal after migration it is not present

This was discussed originally here  [https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgDTM81q-QOMHh9chY](https://reviewable.io/reviews/CoreumFoundation/coreum/625#-NcgDTM81q-QOMHh9chY)

But I'm not sure if we should add step to set proposer inside upgrade since this proposal fails anyway
___
*[`integration-tests/upgrade/gov_migration_test.go` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/655#-NeNfIrDALggA57zhCud:-NeNfIrDALggA57zhCue:bc9fiv8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b4f0b2a045e66665f11705cb6cddb453c3ee40d5/integration-tests/upgrade/gov_migration_test.go#L123)):*
> ```Go
> 	proposalStatus, err := chain.Governance.WaitForVotingToFinalize(ctx, gmt.onDepositProposalId)
> 	requireT.NoError(err)
> 	requireT.Equal(govtypesv1.StatusFailed, proposalStatus)
> ```

So here it wasn't actually what I expected

As @dzmitryhil predicted, there is no handler for old proposal type and it failed.

Logs from cored:

```
11:31AM INF proposal tallied module=x/gov proposal=1 results="passed, but msg 0 (/cosmos.gov.v1.MsgExecLegacyContent) failed on execution: distribution: no handler exists for proposal type"
```

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/655)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

___
*[`integration-tests/upgrade/gov_migration_test.go` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/655#-NeNfIrDALggA57zhCud:-Nebuggc-b4sXDEkAGmH:b-4cp4px) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b4f0b2a045e66665f11705cb6cddb453c3ee40d5/integration-tests/upgrade/gov_migration_test.go#L123)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

So here it wasn't actually what I expected

As @dzmitryhil predicted, there is no handler for old proposal type and it failed.

Logs from cored:

```
11:31AM INF proposal tallied module=x/gov proposal=1 results="passed, but msg 0 (/cosmos.gov.v1.MsgExecLegacyContent) failed on execution: distribution: no handler exists for proposal type"
```
</blockquote></details>

The chain is still running. And the test looks not 100% stable, right?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/655)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

___
*[`integration-tests/upgrade/gov_migration_test.go` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/655#-NeNfIrDALggA57zhCud:-NedFnvYAY1LVCtKebta:b-99cch8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b4f0b2a045e66665f11705cb6cddb453c3ee40d5/integration-tests/upgrade/gov_migration_test.go#L123)):*
chain is running after this test and everything works

> And the test looks not 100% stable, right?
It is stable

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/655)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`integration-tests/upgrade/gov_migration_test.go` line 127 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/655#-NegGPPv9KbetmOJCQJW:-NegGPPv9KbetmOJCQJX:bdwd9nv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a85c98924844075dd5c32364927d2832291ed3f/integration-tests/upgrade/gov_migration_test.go#L127)):*
> ```Go
> 	requireT.Equal(govtypesv1.StatusFailed, proposalStatus)
> 	// Logs produced inside cored for such a proposal:
> 	// "proposal tallied module=x/gov proposal=1 results="passed, but msg 0 (/cosmos.gov.v1.MsgExecLegacyContent) failed on execution: distribution: no handler exists for proposal type"
> ```

It should be fixed, right?

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/655)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`integration-tests/upgrade/gov_migration_test.go` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/655#-NeNfIrDALggA57zhCud:-NegK1g40fC3_E1bqqZL:bnv73g3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b4f0b2a045e66665f11705cb6cddb453c3ee40d5/integration-tests/upgrade/gov_migration_test.go#L123)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

chain is running after this test and everything works

> And the test looks not 100% stable, right?
It is stable
</blockquote></details>

It it's stable let's keep it.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/655)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`integration-tests/upgrade/gov_migration_test.go` line 127 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/655#-NegGPPv9KbetmOJCQJW:-Nem8gfu-JpRNQE1p8oC:bj2qmqz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a85c98924844075dd5c32364927d2832291ed3f/integration-tests/upgrade/gov_migration_test.go#L127)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It should be fixed, right?
</blockquote></details>

No this is expected and we agreed to keep it
I just put the error which is produced during this proposal execution to have better explanation of what happens

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/655)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`integration-tests/upgrade/gov_migration_test.go` line 127 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/655#-NegGPPv9KbetmOJCQJW:-NesA-Jl227l29hyaCtJ:b-8em5r3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/1a85c98924844075dd5c32364927d2832291ed3f/integration-tests/upgrade/gov_migration_test.go#L127)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

No this is expected and we agreed to keep it
I just put the error which is produced during this proposal execution to have better explanation of what happens
</blockquote></details>

change is not needed.

**Pull request merged**
