### PR TITLE
Clean up initParamsKeeper function

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/971)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/971)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`app/app.go` line 1450 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/971#-O7XzoVADCojVqfzubLD:-O7XzoVADCojVqfzubLE:b-vjl144) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e5fc08eb3aca55f22fe39b84c0e343fb226dc41/app/app.go#L1450)):*
> ```Go
> 	paramsKeeper.Subspace(icacontrollertypes.SubModuleName).WithKeyTable(icacontrollertypes.ParamKeyTable())
> 	paramsKeeper.Subspace(icahosttypes.SubModuleName).WithKeyTable(icahosttypes.ParamKeyTable())
> 	paramsKeeper.Subspace(packetforwardtypes.ModuleName).WithKeyTable(packetforwardtypes.ParamKeyTable())
> ```

Why do you need to still keep some?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/971)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

___
*[`app/app.go` line 1450 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/971#-O7XzoVADCojVqfzubLD:-O7Y4qsB3CfBIFscqVsd:bus2ou3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e5fc08eb3aca55f22fe39b84c0e343fb226dc41/app/app.go#L1450)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need to still keep some?
</blockquote></details>

the ibc module needs the legacy keeper because of migrations. those migrations were implemented in v8 and will be applied in the next release. other modules applied their migrations in previous releases.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/971)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/971)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
