### PR TITLE
Document describing IBC integration plan

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIiNzP7ti6EsgGHyOX:-NNIiNzP7ti6EsgGHyOY:b-62950z) (no related file):*
reviewed first part
will continue tomorrow 

___
___
*[`ibc.md` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIgoTH3hv1g3eIPm7S:-NNIgoTH3hv1g3eIPm7T:b-jow74t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/634dc5fbe23be49bd695ffd289d6e0fd7e77f0e2/ibc.md#L14)):*
> ```Markdown
> 
> ## Relayer
> - it is possible to use single relayer for all the channels
> ```

another questions to relayer section is: 
- relayer incintivization
- what if there are multiple relayers and one of them is byzantine 
- what if we "print" token with denom `ibc/...` from another chain and then transfer it to that chain ?
___
*[`ibc.md` line 62 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIfiLJ8iVZ6ousgaZs:-NNIfiLJ8iVZ6ousgaZt:b-3d3xo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/634dc5fbe23be49bd695ffd289d6e0fd7e77f0e2/ibc.md#L62)):*
> ```Markdown
> ### List of receivable tokens
> 
> Do we want to define a set of (token, channel) pairs we allow to be received via IBC?
> ```

another question here is how we define this tokens & channels ? Is it done by gov or hardcoded in code. I vote for gov probably
___
*[`ibc.md` line 67 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIft8F9sHKp2rrCux2:-NNIft8F9sHKp2rrCux3:b-vsgvj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/634dc5fbe23be49bd695ffd289d6e0fd7e77f0e2/ibc.md#L67)):*
> ```Markdown
> ### Received tokens
> 
> Tokens received through IBC must be treated as regular bank tokens (like CORE), without any additional features provided by FT module.
> ```

Review our bank wrapper & make sure we completely ignore all features for such tokens

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`ibc.md` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIgoTH3hv1g3eIPm7S:-NNLdVULCapZ3bG67nnZ:bhpmpvz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/634dc5fbe23be49bd695ffd289d6e0fd7e77f0e2/ibc.md#L14)):*
> relayer incintivization
it is mentioned a few lines below

> what if there are multiple relayers and one of them is byzantine
if it's the only relayer serving particular channel, that channel won't work. We should check if it's possible to run many relayers on single channel

> what if we "print" token with denom ibc/... from another chain and then transfer it to that chain ?
I mentioned it in "Minting" section
___
*[`ibc.md` line 62 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIfiLJ8iVZ6ousgaZs:-NNLe5U91iS3dt5WRIli:b-uov4dk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/634dc5fbe23be49bd695ffd289d6e0fd7e77f0e2/ibc.md#L62)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

another question here is how we define this tokens & channels ? Is it done by gov or hardcoded in code. I vote for gov probably
</blockquote></details>

This is up to us. We must decide.
___
*[`ibc.md` line 67 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIft8F9sHKp2rrCux2:-NNLeCbD44eGF8R69jSk:biffj5f) ([raw file](https://github.com/CoreumFoundation/coreum/blob/634dc5fbe23be49bd695ffd289d6e0fd7e77f0e2/ibc.md#L67)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Review our bank wrapper & make sure we completely ignore all features for such tokens
</blockquote></details>

We already do it for CORE, IBC tokens are visible as regular tokens served by bank module

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: all files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNekB5E9ZFBkg0W_7Bk:-NNekB5E9ZFBkg0W_7Bl:bmgi80s) (no related file):*
Blocking, since it should not be merged into master.

___

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: all files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`ibc.md` line 75 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNalZBX6tNm3_zQ-2TA:-NNlN5LD7Hjo1BYi98BF:bz4ddlu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2419fd5cdf9d42a2391da6097a14eb72c56839f9/ibc.md#L75)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

As far as I know there is a IBC NFT module, but not sure what is the state of the development.
</blockquote></details>

Cronos chain announced NFT+IBC integration

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`ibc.md` line 9 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNladlh-UA-Ak8-iW9N:-NNladlh-UA-Ak8-iW9O:b-2p82gp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2419fd5cdf9d42a2391da6097a14eb72c56839f9/ibc.md#L9)):*
> ```Markdown
> - understand difference between ordered and unordered channels
> - understand data in the exported state of IBC
> - inspect all IBC-related modules
> ```

we need to check if there is way to validate genesis tx to create a channel/light-client

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`ibc.md` line 16 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNakpO-EBRT8amgTVRn:-NNl_kKn9bcLSdUqTs-2:b3cgiex) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2419fd5cdf9d42a2391da6097a14eb72c56839f9/ibc.md#L16)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

BTW, I heard that someone from your validators provides such service.
</blockquote></details>

https://www.zeeve.io/
___
*[`ibc.md` line 25 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNal9GQ8f67Jx6K2m9a:-NNl_xBE09hAir-_bECi:b-hhs7f3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2419fd5cdf9d42a2391da6097a14eb72c56839f9/ibc.md#L25)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Hermes as well. Also the Hermes has a cool feature it emulates the client usage so if you don't use a client it still active, the cosmos relayer doesn't.
</blockquote></details>

Test both relayers, compare features and limitations
- Cosmos relayer does not prevent client from being stopped
___
*[`ibc.md` line 84 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNalgSr0cRp2rMFnfoK:-NNlazzh2Kgycvl_f7W9:b-fup85i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/2419fd5cdf9d42a2391da6097a14eb72c56839f9/ibc.md#L84)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

For example those: https://github.com/tendermint/spn/tree/main/x
</blockquote></details>

let's investigate them - some of them are ibc related

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: all files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`ibc.md` line 62 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIfiLJ8iVZ6ousgaZs:-NNp1Ucv-Q8eD_lBXp7Z:b1vmgmb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/634dc5fbe23be49bd695ffd289d6e0fd7e77f0e2/ibc.md#L62)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is up to us. We must decide.
</blockquote></details>

We discussed it and probably we don't want t define this whitelist
___
*[`ibc.md` line 9 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNladlh-UA-Ak8-iW9N:-NNp0DMt9lUOo2Sty9m6:b-uots4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/46ef8d770f2cf47ccd3ea8497851c636fd3fd55f/ibc.md#L9)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we need to check if there is way to validate genesis tx to create a channel/light-client
</blockquote></details>

After discussing, looks like it is not needed. After channel is created it's enough to compare one block hash to be sure that relayer honestly connects us to the right channel
___
*[`ibc.md` line 11 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNakYnr4mQorihhKWrQ:-NNp0lvLDquTzjowpH6s:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/46ef8d770f2cf47ccd3ea8497851c636fd3fd55f/ibc.md#L11)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Understand what are the reasons to close/stop client, connection, channel, port and etc. and how we can restore them.
</blockquote></details>

Done.
___
*[`ibc.md` line 16 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNakpO-EBRT8amgTVRn:-NNp0xLBBuKEAxHxnptK:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/46ef8d770f2cf47ccd3ea8497851c636fd3fd55f/ibc.md#L16)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

https://www.zeeve.io/
</blockquote></details>

Done
___
*[`ibc.md` line 25 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNal9GQ8f67Jx6K2m9a:-NNp1IaP-OyoQKi6ySdf:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/46ef8d770f2cf47ccd3ea8497851c636fd3fd55f/ibc.md#L25)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Test both relayers, compare features and limitations
- Cosmos relayer does not prevent client from being stopped
</blockquote></details>

Done
___
*[`ibc.md` line 84 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNalgSr0cRp2rMFnfoK:-NNp3w9O-HdRQVkhfxxz:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/46ef8d770f2cf47ccd3ea8497851c636fd3fd55f/ibc.md#L84)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

let's investigate them - some of them are ibc related
</blockquote></details>

Done

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`ibc.md` line 75 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNalZBX6tNm3_zQ-2TA:-NNp2rLU3lyobx7aGaaj:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/46ef8d770f2cf47ccd3ea8497851c636fd3fd55f/ibc.md#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Cronos chain announced NFT+IBC integration
</blockquote></details>

Done

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: all files reviewed, 5 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: all files reviewed, 8 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

___
*[`ibc.md` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIgoTH3hv1g3eIPm7S:-NNMDxwK8PWGHHvkLELY:bhw03i5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/634dc5fbe23be49bd695ffd289d6e0fd7e77f0e2/ibc.md#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> relayer incintivization
it is mentioned a few lines below

> what if there are multiple relayers and one of them is byzantine
if it's the only relayer serving particular channel, that channel won't work. We should check if it's possible to run many relayers on single channel

> what if we "print" token with denom ibc/... from another chain and then transfer it to that chain ?
I mentioned it in "Minting" section
</blockquote></details>

1 - yes I see

2 - I was sure that we can run multiple of them for a single channel. But my question is how the consensus is achieved if they submit different tx ? And what happens if there is a single relayer and it submits wrong txs ?

3 - it is actually a bit different. Lets talk on the call & I will try to explain the case
___
*[`ibc.md` line 62 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIfiLJ8iVZ6ousgaZs:-NOK36Or7MFzCQpBNuil:bcfljpn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/634dc5fbe23be49bd695ffd289d6e0fd7e77f0e2/ibc.md#L62)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

We discussed it and probably we don't want t define this whitelist
</blockquote></details>

did we ?
Lets talk on the call
___
*[`ibc.md` line 67 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIft8F9sHKp2rrCux2:-NOK3EXN1TW_T9sfor4c:b9jrp9d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/634dc5fbe23be49bd695ffd289d6e0fd7e77f0e2/ibc.md#L67)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

We already do it for CORE, IBC tokens are visible as regular tokens served by bank module
</blockquote></details>

I meant just to double check it and make sure we do it properly
___
*[`ibc.md` line 3 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NOK6NuZDeabArREbdg1:-NOK6NuZDeabArREbdg2:bykqs2b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec1761543c9b02cbc9cda328808a8838c2ee0c23/ibc.md#L3)):*
> ```Markdown
> # IBC integration plan
> 
> ## IBC protocol
> ```

Milad covered core messages in his task mostly 
Lets add a task to check application messages in a separate one

```
		// ibc.applications.transfer
		"/ibc.applications.transfer.v1.MsgTransfer",

		// ibc.applications.fee
		"/ibc.applications.fee.v1.MsgRegisterPayee",
		"/ibc.applications.fee.v1.MsgRegisterCounterpartyPayee",
		"/ibc.applications.fee.v1.MsgPayPacketFee",
		"/ibc.applications.fee.v1.MsgPayPacketFeeAsync",
```
___
*[`ibc.md` line 3 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NOK74-L3Age0agQfbQF:-NOK74-M5vYYIO4E5mMe:b-1e6mfa) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec1761543c9b02cbc9cda328808a8838c2ee0c23/ibc.md#L3)):*
> ```Markdown
> # IBC integration plan
> 
> ## IBC protocol
> ```

what should we do with IBC messages & our deterministic gas ?
is IBC able to work properly with dynamic gas price ?
___
*[`ibc.md` line 16 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NOK4vCBB3-eM6i-R2PV:-NOK4vCBB3-eM6i-R2PW:b-wdqjpo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec1761543c9b02cbc9cda328808a8838c2ee0c23/ibc.md#L16)):*
> ```Markdown
> - it is possible to use single relayer for all the channels
> - we should run at least two relayers
> - we should run two full nodes for each blockchain we want to connect to. We may use external service delivering them (check https://www.zeeve.io/)
> ```

I suggest to add a separate section like Devops` and put this question there because it is mostly for Artem
Another topics to be added there:
- setup monitoring & alerts for relayers
- prepare deployment files for relayers
___
*[`ibc.md` line 25 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NOK7I8b5nEIh0SbUCQR:-NOK7I8b5nEIh0SbUCQS:b-1g4xpm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec1761543c9b02cbc9cda328808a8838c2ee0c23/ibc.md#L25)):*
> ```Markdown
>  
> ### Hermes vs Cosmos relayer
> - Cosmos relayer is written in go, Hermes is written in rust
> ```

should we as a final result select a single relayer and advice to use it ?

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: all files reviewed, 6 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

___
*[`ibc.md` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIgoTH3hv1g3eIPm7S:-NOK_3zM7EPY1c_WJ1WU:bv4z5qa) ([raw file](https://github.com/CoreumFoundation/coreum/blob/634dc5fbe23be49bd695ffd289d6e0fd7e77f0e2/ibc.md#L14)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1 - yes I see

2 - I was sure that we can run multiple of them for a single channel. But my question is how the consensus is achieved if they submit different tx ? And what happens if there is a single relayer and it submits wrong txs ?

3 - it is actually a bit different. Lets talk on the call & I will try to explain the case
</blockquote></details>

1 & 2 ok

3 lets test scenario when we send 100k to Osmosis & 100k to Malicious chain. Will malicious chain be able to return 200k ?
___
*[`ibc.md` line 62 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIfiLJ8iVZ6ousgaZs:-NOKeQ7UAQVtnWiK7pdK:b5auom8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/634dc5fbe23be49bd695ffd289d6e0fd7e77f0e2/ibc.md#L62)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

did we ?
Lets talk on the call
</blockquote></details>

decided to keep for now
___
*[`ibc.md` line 24 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NOKcyCc-YbtkDRe6DnT:-NOKcyCd1A1Nr67S5ZGH:b5kmsor) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec1761543c9b02cbc9cda328808a8838c2ee0c23/ibc.md#L24)):*
> ```Markdown
> - check how relayer behaves when client, connection, channel or port is closed due to inactivity or any other reason. How can they be restored?
>  
> ### Hermes vs Cosmos relayer
> ```

vs TS relayer

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: all files reviewed, 6 unresolved discussions (waiting on @silverspase and @ysv)

___
*[`ibc.md` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIgoTH3hv1g3eIPm7S:-NOOURb30AUaBVoMBWiN:b-q7mc8d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/634dc5fbe23be49bd695ffd289d6e0fd7e77f0e2/ibc.md#L14)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1 & 2 ok

3 lets test scenario when we send 100k to Osmosis & 100k to Malicious chain. Will malicious chain be able to return 200k ?
</blockquote></details>

you mean that malicious chain produces 100k coins extra?
___
*[`ibc.md` line 3 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NOK74-L3Age0agQfbQF:-NOOUE3d7rTpx7e3qsbE:b-fnvoev) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ec1761543c9b02cbc9cda328808a8838c2ee0c23/ibc.md#L3)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what should we do with IBC messages & our deterministic gas ?
is IBC able to work properly with dynamic gas price ?
</blockquote></details>

that's related to relayers, IIRC in cosmos relayer you set the constant gas price so it might fail

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: all files reviewed, 6 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

___
*[`ibc.md` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIgoTH3hv1g3eIPm7S:-NOOytFK3c_XtrM6PRMn:b-ldg79y) ([raw file](https://github.com/CoreumFoundation/coreum/blob/634dc5fbe23be49bd695ffd289d6e0fd7e77f0e2/ibc.md#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you mean that malicious chain produces 100k coins extra?
</blockquote></details>

yes and transfers back 200k so Osmosis CORE is locked there forever
___
*[`ibc.md` line 3 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NOK74-L3Age0agQfbQF:-NOOyqqR7pGwC5N2RWX-:bcxdoby) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ee166f7fa3fee22263fb28c0793f1a6ddbb62557/ibc.md#L3)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

that's related to relayers, IIRC in cosmos relayer you set the constant gas price so it might fail
</blockquote></details>

yeah lets put to relayers section

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: all files reviewed, 6 unresolved discussions (waiting on @silverspase and @ysv)

___
*[`ibc.md` line 14 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NNIgoTH3hv1g3eIPm7S:-NPHzaCQ2yeqwaitTUDg:bwva0cf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/634dc5fbe23be49bd695ffd289d6e0fd7e77f0e2/ibc.md#L14)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes and transfers back 200k so Osmosis CORE is locked there forever
</blockquote></details>

I think it doesn't work this way. Each chain should be able to transfer back 100k. And additional 100k should be locked on the malicious chain
___
*[`ibc.md` line 3 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NOK74-L3Age0agQfbQF:-NPHzO8s4DrZraLlZYS4:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c4d9ac3eeeeb308dc922b12ca93b060ff3b6b0e3/ibc.md#L3)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yeah lets put to relayers section
</blockquote></details>

Done.
___
*[`ibc.md` line 16 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NOK4vCBB3-eM6i-R2PV:-NPI-AOGDpXMCIwmoMWA:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c4d9ac3eeeeb308dc922b12ca93b060ff3b6b0e3/ibc.md#L16)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I suggest to add a separate section like Devops` and put this question there because it is mostly for Artem
Another topics to be added there:
- setup monitoring & alerts for relayers
- prepare deployment files for relayers
</blockquote></details>

Done.
___
*[`ibc.md` line 24 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/372#-NOKcyCc-YbtkDRe6DnT:-NPI-DlXDQRyddc_7AQo:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c4d9ac3eeeeb308dc922b12ca93b060ff3b6b0e3/ibc.md#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

vs TS relayer
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/372)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @wojtek-coreum)

**Pull request closed without merging**
