### PR TITLE
Implement coins locking for both ft and native coins.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Implement coins locking for both ft and native coins.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/913)

### CODE REVIEW

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/913)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/913)* status: all files reviewed, 6 unresolved discussions (waiting on @dzmitryhil and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2cpHOh2lnw9VmRdqk_:-O2cpHOiB7clARvMecbB:bqrbeso) (no related file):*
I am not seeing spendable balance query being updated here.

___
___
*[`proto/coreum/asset/ft/v1/event.proto` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2db-XN8ZS2TxHzxZ1X:-O2db-XN8ZS2TxHzxZ1Y:b8neeqg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/event.proto#L70)):*
> ```proto
> }
> 
> message EventLockedAmountChanged {
> ```

the fact that some amounts is locked due for the sake of trading is inernal implementation and should be exposed via events. the event should be OrderCreated/OrderExecuted/OrderCancelled.
___
*[`proto/coreum/asset/ft/v1/query.proto` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2daG818myt3pPCp9jA:-O2daG818myt3pPCp9jB:brtvnmw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L123)):*
> ```proto
>   ];
>   // locked is the balance locked by bank and assetft.
>   string locked = 4 [
> ```

locked could be removed, since adding the 2 values is not very meaningful. 
___
*[`proto/coreum/asset/ft/v1/query.proto` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2d_WQoAVxeyweRc_y6:-O2d_WQp5bEGQtU7g_hb:bnotv02) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L128)):*
> ```proto
>   ];
>   // locked is the balance locked by bank.
>   string locked_by_bank = 5 [
> ```

In the bank module this value is called locked internally but exposed as vesting amount externally, So I think is better to call it in a way to show that this is related to vesting. Maybe `locked_vesting` or `vesting_amount` . 
___
*[`proto/coreum/asset/ft/v1/query.proto` line 133 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2daMn-3FZ7l5Q97lKA:-O2daMn-3FZ7l5Q97lKB:bjt5hqp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L133)):*
> ```proto
>   ];
>   // locked is the balance locked by assetft.
>   string locked_by_ft = 6 [
> ```

this can be called locked in dex or locked in trade. that is more meaningful to the outside world. the fact that the asset ft is doing the locking in inernal implementation and is not meaningful to the user. the outside user only cares that theirs funds are locked in the order book. 
___
*[`x/asset/ft/keeper/before_send.go` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2dgc15ADsnsmaflgTb:-O2dgc15ADsnsmaflgTc:b-jus1lo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/x/asset/ft/keeper/before_send.go#L87)):*
> ```Go
> 			if sdkerrors.IsOf(err, types.ErrInvalidDenom, types.ErrTokenNotFound) {
> 				// if the token doesn't have the definition we validate locking rule only.
> 				if _, err := k.validateCoinIsNotLocked(ctx, sender, coin); err != nil {
> ```

you have to do this check for invoke asset extension as well.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/913)* status: all files reviewed, 6 unresolved discussions (waiting on @miladz68 and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2cpHOh2lnw9VmRdqk_:-O2e3WbZ8IukBy1sCKrq:b-gd02e6) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I am not seeing spendable balance query being updated here.
</blockquote></details>

Good catch. Updated.

___
___
*[`proto/coreum/asset/ft/v1/event.proto` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2db-XN8ZS2TxHzxZ1X:-O2e69ljAYX4fBy5YWJo:banmxkt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/event.proto#L70)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the fact that some amounts is locked due for the sake of trading is inernal implementation and should be exposed via events. the event should be OrderCreated/OrderExecuted/OrderCancelled.
</blockquote></details>

IMO this event is useful if you track all changes regarding the assetft. So I would keep it.
___
*[`proto/coreum/asset/ft/v1/query.proto` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2daG818myt3pPCp9jA:-O2e6Ils455irv1TjRLl:b-f37tj8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L123)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

locked could be removed, since adding the 2 values is not very meaningful.
</blockquote></details>

The `locked` can't be removed to keep the backward compatibility
___
*[`proto/coreum/asset/ft/v1/query.proto` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2d_WQoAVxeyweRc_y6:-O2e6U4G678XrDaUCgW1:b-h686pu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L128)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

In the bank module this value is called locked internally but exposed as vesting amount externally, So I think is better to call it in a way to show that this is related to vesting. Maybe `locked_vesting` or `vesting_amount` .
</blockquote></details>

But we call the `LockedCoins` method of the bank.
___
*[`proto/coreum/asset/ft/v1/query.proto` line 133 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2daMn-3FZ7l5Q97lKA:-O2e6bQe0_CfE3WYl-nb:b-d9a8jn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L133)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this can be called locked in dex or locked in trade. that is more meaningful to the outside world. the fact that the asset ft is doing the locking in inernal implementation and is not meaningful to the user. the outside user only cares that theirs funds are locked in the order book.
</blockquote></details>

I made it more generic to allow more locking use cases in the future.
___
*[`x/asset/ft/keeper/before_send.go` line 87 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2dgc15ADsnsmaflgTb:-O2e7HdGAELXYL7RWR0x:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/x/asset/ft/keeper/before_send.go#L87)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you have to do this check for invoke asset extension as well.
</blockquote></details>

Updated.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/913)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil and @ysv)

___
*[`proto/coreum/asset/ft/v1/event.proto` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2db-XN8ZS2TxHzxZ1X:-O2eShypDzi__gOTZiP6:b53x898) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/event.proto#L70)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO this event is useful if you track all changes regarding the assetft. So I would keep it.
</blockquote></details>

let's discuss in a call. 
___
*[`proto/coreum/asset/ft/v1/query.proto` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2daG818myt3pPCp9jA:-O2eQYxK-3PozTh72kLM:b-tbwk75) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L123)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The `locked` can't be removed to keep the backward compatibility
</blockquote></details>

if it is not released to the public, then reuse the place holder 4 for the new values. renaming is backwards compatible I think. 
___
*[`proto/coreum/asset/ft/v1/query.proto` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2d_WQoAVxeyweRc_y6:-O2eQndJBhx2C0hj2aY-:b-spflrr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L128)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But we call the `LockedCoins` method of the bank.
</blockquote></details>

yes, but that is keeper naming, but it is not exposed to the world as locked coins, it is only related to vesting and people don't know that their vesting amount is named as `locked`, let's not expose it with a new name, or let's not expose it altogether. 
___
*[`proto/coreum/asset/ft/v1/query.proto` line 133 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2daMn-3FZ7l5Q97lKA:-O2eS7gU7XLUZdwzFi4Q:b-fvgxi5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L133)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I made it more generic to allow more locking use cases in the future.
</blockquote></details>

 I understand the generic implementation , but I don't thing the implementation should be exposed to the end user. Imagine that in future we decide to move the locking from assetft to the dex for some reason. then this naming will be incorrect. the naming should reflect the behavior not the implementation. 
___
*[`x/asset/ft/keeper/before_send.go` line 126 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2eQ8hY4Ivgx7sJmitY:-O2eQ8hY4Ivgx7sJmitZ:b-zc8tby) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5350ab22108ff822438914b85d13d04e8a0d9ea9/x/asset/ft/keeper/before_send.go#L126)):*
> ```Go
> 				//	transfers if the token has extensions. It is up to the contract to enforce them as needed.
> 				//	As a result we will skip the next operations in this for loop.
> 				if _, err := k.validateCoinIsNotLocked(ctx, sender, coin); err != nil {
> ```

this must be done before the extension is invoked.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/913)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`proto/coreum/asset/ft/v1/event.proto` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2db-XN8ZS2TxHzxZ1X:-O2eTXCfA1H5TrkCi3lV:b32w0x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/event.proto#L70)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's discuss in a call.
</blockquote></details>

OK
___
*[`proto/coreum/asset/ft/v1/query.proto` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2daG818myt3pPCp9jA:-O2eT6u8CTWIkf8tJQey:bgyyxdt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L123)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

if it is not released to the public, then reuse the place holder 4 for the new values. renaming is backwards compatible I think.
</blockquote></details>

But it's release. The locked already exists and used. 
___
*[`proto/coreum/asset/ft/v1/query.proto` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2d_WQoAVxeyweRc_y6:-O2eTENV54egpxmsxz8c:b-lmma8u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L128)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

yes, but that is keeper naming, but it is not exposed to the world as locked coins, it is only related to vesting and people don't know that their vesting amount is named as `locked`, let's not expose it with a new name, or let's not expose it altogether.
</blockquote></details>

Let's discuss on the call. 
___
*[`proto/coreum/asset/ft/v1/query.proto` line 133 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2daMn-3FZ7l5Q97lKA:-O2eTKDnABVP1hLcwI6v:ba424ko) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L133)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I understand the generic implementation , but I don't thing the implementation should be exposed to the end user. Imagine that in future we decide to move the locking from assetft to the dex for some reason. then this naming will be incorrect. the naming should reflect the behavior not the implementation.
</blockquote></details>

Not really, it depends on use case,  let's discuss on a call.
___
*[`x/asset/ft/keeper/before_send.go` line 126 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2eQ8hY4Ivgx7sJmitY:-O2eTpDYDV1_-2ytXC_Y:b-80tlqk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/5350ab22108ff822438914b85d13d04e8a0d9ea9/x/asset/ft/keeper/before_send.go#L126)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this must be done before the extension is invoked.
</blockquote></details>

Sure.

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/913)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68 and @ysv)

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/913)* status: all files reviewed, 4 unresolved discussions (waiting on @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/913)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`proto/coreum/asset/ft/v1/event.proto` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2db-XN8ZS2TxHzxZ1X:-O2i4J5B2ePrCLxD_hZj:b-t81ll9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/event.proto#L70)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Agreed to call `DEXLocked...`
___
*[`proto/coreum/asset/ft/v1/query.proto` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2daG818myt3pPCp9jA:-O2i5mwI8jmzR05wjT3b:b-3tj4t8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L123)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But it's release. The locked already exists and used.
</blockquote></details>

Decided to keep it.
___
*[`proto/coreum/asset/ft/v1/query.proto` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2d_WQoAVxeyweRc_y6:-O2i7KJMByZ9mu9GZieL:bh9pnej) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L128)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's discuss on the call.
</blockquote></details>

Agreed to call `locked_in_vesting`.
___
*[`proto/coreum/asset/ft/v1/query.proto` line 133 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2daMn-3FZ7l5Q97lKA:-O2i5UJN7jNpjShateE6:b75arfy) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L133)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not really, it depends on use case,  let's discuss on a call.
</blockquote></details>

Agreed to call `locked_in_dex`
___
*[`proto/coreum/asset/ft/v1/query.proto` line 122 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2i7OyH7MvqM_8fl4Zd:-O2i7OyH7MvqM_8fl4Ze:bols8kh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/59beb392be56079a4ebb2daaa9ee0b6f1fb9e3b8/proto/coreum/asset/ft/v1/query.proto#L122)):*
> ```proto
>     (gogoproto.nullable) = false
>   ];
>   // locked is the balance locked by bank and assetft.
> ```

Update comment.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/913)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`proto/coreum/asset/ft/v1/event.proto` line 70 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2db-XN8ZS2TxHzxZ1X:-O2iSr_6Bns7So4bZu_8:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/event.proto#L70)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agreed to call `DEXLocked...`
</blockquote></details>

Done.
___
*[`proto/coreum/asset/ft/v1/query.proto` line 123 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2daG818myt3pPCp9jA:-O2iSuni7BfJAKglUAal:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L123)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Decided to keep it.
</blockquote></details>

Done.
___
*[`proto/coreum/asset/ft/v1/query.proto` line 128 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2d_WQoAVxeyweRc_y6:-O2iSvR181z-8K3GorrE:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L128)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agreed to call `locked_in_vesting`.
</blockquote></details>

Done.
___
*[`proto/coreum/asset/ft/v1/query.proto` line 133 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-O2daMn-3FZ7l5Q97lKA:-O2iSw1y-USP3VDsqQkO:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65f3527bd52446d5c8b97ee5d6eaf695190880c9/proto/coreum/asset/ft/v1/query.proto#L133)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agreed to call `locked_in_dex`
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
> Reviewed 21 of 21 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/913)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/913#-:-O2isewiAnPv9cd0mPsw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/913)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 21 of 21 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/913)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
