### PR TITLE
Test timing out IBC transfer

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/515)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/515)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/515)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/515)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/chain.go` line 223 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/515#-NWgn1Yh8NoS5QUJEl-m:-NWgn1Yi1C6toAp4z8Tl:b26i1a4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c01907e294fa3bf876808e976914f1df398b6193/integration-tests/chain.go#L223)):*
> ```Go
> 		Sender:           sender,
> 		Receiver:         receiver,
> 		TimeoutTimestamp: uint64(latestBlockRes.Block.Header.Time.Add(-10 * time.Second).UnixNano()),
> ```

I wonder we reduce the time by 10 seconds, doing 5 seconds should be enough ?

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/515)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/515#-NXjK4kkABYWx9kCGl6x:-NXjK4kkABYWx9kCGl6y:bbw9eav) (no related file):*
On the call decided: to Try to implement it with the Simapp test and IBC simluation

___

**Pull request closed without merging**
