### PR TITLE
Fund accounts for many integration tests in single transaction

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/202)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
not finished review fully yet. Will continue with logic review tomorrow 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/202#-:-ND--ED0BtWjo-8Cy-dQ:bdelv9o)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/integration_test.go` line 253 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/202#-NCzyZxq6zW8diNjJuq1:-NCzyZxq6zW8diNjJuq2:bxzhx3h) ([raw file](https://github.com/coreumfoundation/coreum/blob/402d2d50d703cf6c3642e8e1ca9694b39948702a/integration-tests/integration_test.go#L253)):*
> ```Go
> 	requests = append(requests, req)
> 	numOfAccounts := len(req.AccountsToFund)
> 	timeout := time.After(100 * time.Millisecond)
> ```

is it a timeout during which new requrest are accepted before sending them ?

If yes then probably it is worth increasing IMO. 
If we wait for 100ms and then submit we still have to wait another block_time-100ms for txs to be submitted. I feel like that this time should be ~block_time/2. It is sort of probability theory task I think.
So my feeling of proper value for it is 500-750ms but I'm not sure if it is a right value

WDYT Wojtek ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/202)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/integration_test.go` line 253 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/202#-NCzyZxq6zW8diNjJuq1:-ND1wWLQ-b9v8hrAe_A7:biylqz8) ([raw file](https://github.com/coreumfoundation/coreum/blob/402d2d50d703cf6c3642e8e1ca9694b39948702a/integration-tests/integration_test.go#L253)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it a timeout during which new requrest are accepted before sending them ?

If yes then probably it is worth increasing IMO. 
If we wait for 100ms and then submit we still have to wait another block_time-100ms for txs to be submitted. I feel like that this time should be ~block_time/2. It is sort of probability theory task I think.
So my feeling of proper value for it is 500-750ms but I'm not sure if it is a right value

WDYT Wojtek ?
</blockquote></details>

This timeout should be driven by the time required by tests to reach the point where they require funds:
1. 5 tests are started in parallel
2. After some time first of them requires funds (timeout for other tests start)
3. Other tests have another 100ms to reach the point where they request funds

I tested it manually and 100ms works pretty well. We may give more, but block time doesn't really matter

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/202)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @begmaroman, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/integration_test.go` line 194 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND30cBa2LwNo1yj6BJx:-ND30cBa2LwNo1yj6BJy:b-am4hjc) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L194)):*
> ```Go
> 	privKey := &cosmossecp256k1.PrivKey{Key: cfg.FundingPrivKey}
> 	keyringDB := keyring.NewInMemory()
> 	err := keyringDB.ImportPrivKey("faucet", crypto.EncryptArmorPrivKey(privKey, "dummy", privKey.Type()), "dummy")
> ```

Let's use the same keyring for the tests.
___
*[`integration-tests/integration_test.go` line 224 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND35wncEM2nGEnTFMEY:-ND35wncEM2nGEnTFMEZ:be1wkmp) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L224)):*
> ```Go
> }
> 
> func (tf *testingFaucet) FundAccounts(ctx context.Context, accountsToFund ...coreumtesting.FundedAccount) (retErr error) {
> ```

Oh, let's not use the naming retruns
___
*[`integration-tests/integration_test.go` line 230 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND39tT568BzuIGqEuTz:-ND39tT568BzuIGqEuU-:b-whospq) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L230)):*
> ```Go
> 	}
> 
> 	requests := make([]fundingRequest, 0, 20)
> ```

t's weird, you use the 20 here for the []fundingRequest which contains the slice of the accounts and later you use the same value to check that you fund < 20 accounts. I didn't get this logic
___
*[`integration-tests/integration_test.go` line 239 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND38541DPrFoijf7Pem:-ND38541DPrFoijf7Pen:bta03m9) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L239)):*
> ```Go
> 		case <-ctx.Done():
> 			return ctx.Err()
> 		case err := <-req.FundedCh:
> ```

When is it achievable?
___
*[`integration-tests/integration_test.go` line 245 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND37Ctr6j_PSLowWyrU:-ND37Ctr6j_PSLowWyrV:b-gcbf60) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L245)):*
> ```Go
> 		defer func() {
> 			tf.muCh <- struct{}{}
> 			for _, req := range requests {
> ```

In what case the "requests" are not empty when the defer is called?
___
*[`integration-tests/integration_test.go` line 246 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND368jNCGOvcAgtcG5a:-ND368jNCGOvcAgtcG5b:b-1nhcxc) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L246)):*
> ```Go
> 			tf.muCh <- struct{}{}
> 			for _, req := range requests {
> 				req.FundedCh <- retErr
> ```

From what I see the "retErr" is always nil
___
*[`integration-tests/integration_test.go` line 253 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND35M3H4gek5tW54fCI:-ND35M3H4gek5tW54fCJ:bg14pco) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L253)):*
> ```Go
> 	requests = append(requests, req)
> 	numOfAccounts := len(req.AccountsToFund)
> 	timeout := time.After(100 * time.Millisecond)
> ```

Let's try to keep all constant at the beginning of the method with the proper names to understand their spouse.
Additionally could you add the description of all blocks in the code, since this logic is not straightforward and should be described.
___
*[`integration-tests/integration_test.go` line 255 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND32EJ1B4tcNTFwJdCQ:-ND32EJ1B4tcNTFwJdCR:bv7zwxh) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L255)):*
> ```Go
> 	timeout := time.After(100 * time.Millisecond)
> loop:
> 	for numOfAccounts < cap(requests) {
> ```

I don't like such practices, lets make the constant and use it in the requests slice and here.
___
*[`integration-tests/integration_test.go` line 260 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND32x3GBz5Dk8yKVUzA:-ND32x3GBz5Dk8yKVUzB:b-jsne72) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L260)):*
> ```Go
> 			return ctx.Err()
> 		case <-timeout:
> 			break loop
> ```

What is purpose of the "loop" here?
___
*[`integration-tests/integration_test.go` line 262 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND38Ltd-Y1d5TVld4Wq:-ND38Ltd-Y1d5TVld4Wr:b8tw9ma) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L262)):*
> ```Go
> 			break loop
> 		case req := <-tf.queue:
> 			requests = append(requests, req)
> ```

Does it mean the we can send more than 20 messages?
___
*[`integration-tests/integration_test.go` line 270 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND39bwJ9smZO3WlZISE:-ND39bwJ9smZO3WlZISF:b-6m4i5e) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L270)):*
> ```Go
> 	for _, req := range requests {
> 		for _, acc := range req.AccountsToFund {
> 			messages = append(messages, &banktypes.MsgSend{
> ```

How about MitiSend?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/202)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/integration_test.go` line 224 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND35wncEM2nGEnTFMEY:-ND3EzDS7UTwzLIUfsaX:b-bx0mmi) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L224)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Oh, let's not use the naming retruns
</blockquote></details>

this is the less weird way of accessing returned error in defer function than assigning it everywhere to variable
___
*[`integration-tests/integration_test.go` line 239 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND38541DPrFoijf7Pem:-ND3FDTWBQ0jEo1DEg80:bwkx7h6) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L239)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

When is it achievable?
</blockquote></details>

when function blocks because other call is in the process of funding requested accounts
___
*[`integration-tests/integration_test.go` line 245 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND37Ctr6j_PSLowWyrU:-ND3FP9r8lgxV3YOvTHE:b-t0b4zn) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L245)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

In what case the "requests" are not empty when the defer is called?
</blockquote></details>

they are always not empty, but how is the question related to this line of code?
___
*[`integration-tests/integration_test.go` line 246 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND368jNCGOvcAgtcG5a:-ND3FYGI2lkAYV8dDInh:b-3nsy7b) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L246)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

From what I see the "retErr" is always nil
</blockquote></details>

Nope, when`BroadcastTx` or `AwaitTx` fail `retErr` is not nil
___
*[`integration-tests/integration_test.go` line 260 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND32x3GBz5Dk8yKVUzA:-ND3G9U06cTUO6Aawm68:b48vj3n) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L260)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is purpose of the "loop" here?
</blockquote></details>

to break from the for loop instead of select block
___
*[`integration-tests/integration_test.go` line 262 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND38Ltd-Y1d5TVld4Wq:-ND3GE5k22sYA1Nmi29k:b-juksbo) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L262)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Does it mean the we can send more than 20 messages?
</blockquote></details>

yes we can
___
*[`integration-tests/integration_test.go` line 270 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND39bwJ9smZO3WlZISE:-ND3GHMxE15ibbMz1lBy:bybd5m8) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L270)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

How about MitiSend?
</blockquote></details>

MultiSend won't work with deterministc gas

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/202)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/integration_test.go` line 285 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND2wVnM1eYUHH6db3ic:-ND2wVnM1eYUHH6db3id:b-bngowd) ([raw file](https://github.com/coreumfoundation/coreum/blob/402d2d50d703cf6c3642e8e1ca9694b39948702a/integration-tests/integration_test.go#L285)):*
> ```Go
> 		ctx,
> 		clientCtx,
> 		tf.chain.TxFactory().WithKeybase(tf.keyring).WithGas(uint64(numOfAccounts)*tf.chain.GasLimitByMsgs(&banktypes.MsgSend{})),
> ```

the idea of `chain.GasLimitByMsgs` was that you can directly pass messages into it without additional logic to multiply.

For this case:
```
tf.chain.GasLimitByMsgs(messages...)
```

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/202)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/integration_test.go` line 285 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND2wVnM1eYUHH6db3ic:-ND3fheZ36rsHkW_j5TJ:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/402d2d50d703cf6c3642e8e1ca9694b39948702a/integration-tests/integration_test.go#L285)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The problem is that it doesn't work this way, because at some point the size of transaction will go above free limit. So at the end of the day we must start using gas estimation
</blockquote></details>

ok

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/202)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @begmaroman, @dzmitryhil, and @miladz68)

___
*[`integration-tests/integration_test.go` line 194 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND30cBa2LwNo1yj6BJx:-ND6x8du1akp5Ty0s3Dt:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L194)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's use the same keyring for the tests.
</blockquote></details>

Done.
___
*[`integration-tests/integration_test.go` line 230 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND39tT568BzuIGqEuTz:-ND6x9vQAmpz6H6gipgy:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L230)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

t's weird, you use the 20 here for the []fundingRequest which contains the slice of the accounts and later you use the same value to check that you fund < 20 accounts. I didn't get this logic
</blockquote></details>

Done.
___
*[`integration-tests/integration_test.go` line 253 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND35M3H4gek5tW54fCI:-ND7-iVn-MPRteOUnwT2:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L253)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's try to keep all constant at the beginning of the method with the proper names to understand their spouse.
Additionally could you add the description of all blocks in the code, since this logic is not straightforward and should be described.
</blockquote></details>

Done.
___
*[`integration-tests/integration_test.go` line 255 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND32EJ1B4tcNTFwJdCQ:-ND7-jccCfB7DntACgPG:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1e2b939ab362bce31406ca3fd02f783739e1a4e/integration-tests/integration_test.go#L255)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I don't like such practices, lets make the constant and use it in the requests slice and here.
</blockquote></details>

Done.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/202)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/integration_test.go` line 221 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND7RrBz-Jxh7ZYLgnzJ:-ND7RrBz-Jxh7ZYLgnzK:b-litzet) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d1682f03517c08e1804c3a3615223f01439e946/integration-tests/integration_test.go#L221)):*
> ```Go
> 
> 	if len(accountsToFund) > maxAccountsPerRequest {
> 		return errors.Errorf("the number of accounts to fund (%d) is greater than the allowed maximu (%d)", len(accountsToFund), maxAccountsPerRequest)
> ```

maximum
___
*[`integration-tests/integration_test.go` line 260 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND7Sn454ZkDMi-dRjF8:-ND7Sn462mEBpNJnN2DU:bhru4ic) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d1682f03517c08e1804c3a3615223f01439e946/integration-tests/integration_test.go#L260)):*
> ```Go
> 
> 	defer func() {
> 		// After transaction is broadcasted we unlock `muCh` so anothet leader for next transaction might be selected
> ```

anothet -> another
___
*[`integration-tests/integration_test.go` line 276 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND7SBi45aJr88XkjUFS:-ND7SBi45aJr88XkjUFT:b-s66vlr) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d1682f03517c08e1804c3a3615223f01439e946/integration-tests/integration_test.go#L276)):*
> ```Go
> 	timeout := time.After(timeoutDuration)
> loop:
> 	for len(requests) < cap(requests) {
> ```

You already have that constant, so no neet to compute the cap.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/202)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/integration_test.go` line 221 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND7RrBz-Jxh7ZYLgnzJ:-ND7UqE-4YMqPeEJ9zjY:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d1682f03517c08e1804c3a3615223f01439e946/integration-tests/integration_test.go#L221)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

maximum
</blockquote></details>

Done
___
*[`integration-tests/integration_test.go` line 260 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND7Sn454ZkDMi-dRjF8:-ND7UuLy6Di1ZtUTMQlL:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d1682f03517c08e1804c3a3615223f01439e946/integration-tests/integration_test.go#L260)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

anothet -> another
</blockquote></details>

Done
___
*[`integration-tests/integration_test.go` line 276 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/202#-ND7SBi45aJr88XkjUFS:-ND7V-wS3ZC9p1U4qEAj:bb6un1j) ([raw file](https://github.com/coreumfoundation/coreum/blob/3d1682f03517c08e1804c3a3615223f01439e946/integration-tests/integration_test.go#L276)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You already have that constant, so no neet to compute the cap.
</blockquote></details>

Done

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/202)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/202)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Pull request closed without merging**
