### PR TITLE
Wait until next block before returning voting result

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

It seems that after applying voting result in the end blocker, despite the fact that transaction is executed, query still might return the old value. This PR mitigates it by waiting until the next block.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/643)

### CODE REVIEW

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/643)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @vertex451)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/643)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @vertex451)

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/643)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @vertex451)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/643)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by miladz68 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/643)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/643)* status: all files reviewed, 1 unresolved discussion (waiting on @vertex451 and @wojtek-coreum)

___
*[`integration-tests/gov_legacy.go` line 310 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/643#-NeCUVfy36s6vCFC-eII:-NeCUVfy36s6vCFC-eIJ:b-ivii8n) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8e773662e3f3ea79679b9cf68d64e0d2945e5213/integration-tests/gov_legacy.go#L310)):*
> ```Go
> 	// query might still return the old value. So, we wait for an additional block before returning.
> 	if proposal.Status == govtypesv1beta1.StatusPassed {
> 		if err := client.AwaitNextBlocks(ctx, g.chainCtx.ClientContext, 1); err != nil {
> ```

I guess we should remove this condition, now that it does not help with the issue ?

**Pull request closed without merging**
