### PR TITLE
[Draft, since blocked by the dex fuzz PR] Implement PlaceOrder with the order save/get capabilities. 

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Implement PlaceOrder with the order save/get capabilities.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/907)

### CODE REVIEW

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/907)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/dex/types/order.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/907#-O1_C6-c8aenteucvSAF:-O1_C6-c8aenteucvSAG:b-taddfv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/80338401be73562b4dbaa76554f63e6e48f10f87/x/dex/types/order.go#L59)):*
> ```Go
> 	}
> 
> 	switch o.Side {
> ```

You could simply check for `Side_unspecified`

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/907)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`x/dex/types/order.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/907#-O1_C6-c8aenteucvSAF:-O1pH18X9TXGpFvm9MZi:bxa2vfm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/80338401be73562b4dbaa76554f63e6e48f10f87/x/dex/types/order.go#L59)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

You could simply check for `Side_unspecified`
</blockquote></details>

Here I don't need to check since check before

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/907)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, and @ysv)

___
*[`x/dex/types/order.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/907#-O1_C6-c8aenteucvSAF:-O1pH8py0IIwUg3Qf-Dk:bmzgw4r) ([raw file](https://github.com/CoreumFoundation/coreum/blob/80338401be73562b4dbaa76554f63e6e48f10f87/x/dex/types/order.go#L59)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Here I don't need to check since check before
</blockquote></details>

Actually - not, since I can create new type as well.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/907)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/dex/types/order.go` line 59 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/907#-O1_C6-c8aenteucvSAF:-O1pHJkp9CGvhubwFKWK:b-tuaa4p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/80338401be73562b4dbaa76554f63e6e48f10f87/x/dex/types/order.go#L59)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually - not, since I can create new type as well.
</blockquote></details>

I mean, you could reverse the check. You are ignoring OK cases, and returning error for the default case (which is Side_unspecified only). You could simplify this check

**Comment by dzmitryhil** [comment]
Closed

**Pull request closed without merging**
