### PR TITLE
Fixed cored name in README docs

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/479)

### CODE REVIEW

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/479)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/479)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/479)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkuvsh and @silverspase)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/479)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @mkuvsh, and @silverspase)

___
*[`README.md` line 83 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/479#-NUMB45t4nObpw5Cz1kM:-NUMB45t4nObpw5Cz1kN:b-t4l0ks) ([raw file](https://github.com/CoreumFoundation/coreum/blob/91e314ea9cc863094d86b80650d51831b3a82af0/README.md#L83)):*
> ```Markdown
> This will generate a wallet and print out the mnemonic at the end. It will also print 
> the address and public key. Use the address in the next commands to query its balance
> and and transfer funds to it
> ```

1. and and
2. period at the end
___
*[`README.md` line 89 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/479#-NUMBA8d9_ZH9VxvyKfM:-NUMBA8d9_ZH9VxvyKfN:bdwqknt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/91e314ea9cc863094d86b80650d51831b3a82af0/README.md#L89)):*
> ```Markdown
> Remember to replace address with the one existing in your keystore.
> 
> You will see the balance is zero
> ```

period at the end
___
*[`README.md` line 95 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/479#-NUMBEzh0Gy6SOtu6uFU:-NUMBEzh0Gy6SOtu6uFV:b-k73153) ([raw file](https://github.com/CoreumFoundation/coreum/blob/91e314ea9cc863094d86b80650d51831b3a82af0/README.md#L95)):*
> ```Markdown
> (znet) [znet] $ cored-00 tx bank send alice {YOUR_GENERATED_ADDRESS} 10udevcore --broadcast-mode=block
> ```
> Run the query again and you will see that there are now funds the in the newly generated account.
> ```

the in

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/479)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkuvsh and @silverspase)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/479)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkuvsh and @silverspase)

**Pull request merged**
