### PR TITLE
Copy cosmos grpc client and modify it to respect ctx

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/197)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/197)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/197)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`pkg/grpc/client.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/197#-NCv1-78-H0bSfv6HxNu:-NCv1-797jqt6AcBSlfz:b8nr2dx) ([raw file](https://github.com/coreumfoundation/coreum/blob/34668aceef9981a09ae882bfb2e0e2c58a170ef5/pkg/grpc/client.go#L34)):*
> ```Go
> // Client contains code copied from https://github.com/cosmos/cosmos-sdk/blob/35ae2c4c72d4aeb33447d5a7af23ca47f786606e/client/grpc_query.go
> // We improved it to respect received context instead of passing context.Background()
> type Client struct {
> ```

what do you think about using our Client everywhere in integraiton-test instead of `cosmosclient.Context` ?
___
*[`pkg/grpc/client.go` line 39 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/197#-NCuy3iF93N10_ESPLTB:-NCuy3iF93N10_ESPLTC:b-hh3rxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/34668aceef9981a09ae882bfb2e0e2c58a170ef5/pkg/grpc/client.go#L39)):*
> ```Go
> 
> // Invoke invokes GRPC method
> func (client Client) Invoke(ctx context.Context, method string, req, reply interface{}, opts ...grpc.CallOption) (err error) {
> ```

I see on their end comment:
```
// Two things can happen here:
	// 1. either we're broadcasting a Tx, in which call we call Tendermint's broadcast endpoint directly,
	// 2. or we are querying for state, in which case we call ABCI's Query.

	// In both cases, we don't allow empty request args (it will panic unexpectedly)
```

But we just handle querying only in our case am I right ?
If yes then it is worth adding comment here 

But why don't we handle both here ? 
If we accidentally pass our implementation to create TX is it going to fail ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/197)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`pkg/grpc/client.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/197#-NCv1-78-H0bSfv6HxNu:-NCxLEpU4SiBSGCWRAJW:b-tuxqoo) ([raw file](https://github.com/coreumfoundation/coreum/blob/34668aceef9981a09ae882bfb2e0e2c58a170ef5/pkg/grpc/client.go#L34)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what do you think about using our Client everywhere in integraiton-test instead of `cosmosclient.Context` ?
</blockquote></details>

WDYM? This client is not a full replacement of client context. It just invokes grpc methods based on the configuration in client context. And I use this client in integration tests already.
___
*[`pkg/grpc/client.go` line 39 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/197#-NCuy3iF93N10_ESPLTB:-NCxL6-xAP9TJkuemPoc:b-70z5wo) ([raw file](https://github.com/coreumfoundation/coreum/blob/34668aceef9981a09ae882bfb2e0e2c58a170ef5/pkg/grpc/client.go#L39)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I see on their end comment:
```
// Two things can happen here:
	// 1. either we're broadcasting a Tx, in which call we call Tendermint's broadcast endpoint directly,
	// 2. or we are querying for state, in which case we call ABCI's Query.

	// In both cases, we don't allow empty request args (it will panic unexpectedly)
```

But we just handle querying only in our case am I right ?
If yes then it is worth adding comment here 

But why don't we handle both here ? 
If we accidentally pass our implementation to create TX is it going to fail ?
</blockquote></details>

Supporting broadcasting would require copying another 300+ lines of code. And we don't need second way of broadcasting (I don't understand why it is like that in cosmos).

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/197)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/197)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`pkg/grpc/client.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/197#-NCv1-78-H0bSfv6HxNu:-NCzp7gtBe88rs-8S7zS:b7bz41u) ([raw file](https://github.com/coreumfoundation/coreum/blob/34668aceef9981a09ae882bfb2e0e2c58a170ef5/pkg/grpc/client.go#L34)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

WDYM? This client is not a full replacement of client context. It just invokes grpc methods based on the configuration in client context. And I use this client in integration tests already.
</blockquote></details>

I mean smth like this:

```
type ClientCtx struct {
  cosmosclient.Context
}

func (client Client) Invoke(ctx context.Context, method string, req, reply interface{}, opts ...grpc.CallOption) (err error) {

// for broadcasting tx call cosmosclient.Context.Invoke since it already respects the ctx
// for queries override to respect ctx
}

type Chain struct {
// ...
  ClientContext grpc.ClientCtx // use our client context with fixed invoke method & all other methods will be called for original   cosmosclient.Context
}
```
___
*[`pkg/grpc/client.go` line 39 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/197#-NCuy3iF93N10_ESPLTB:-NCzppGj40nKyOmWobFh:b-988xdd) ([raw file](https://github.com/coreumfoundation/coreum/blob/34668aceef9981a09ae882bfb2e0e2c58a170ef5/pkg/grpc/client.go#L39)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Supporting broadcasting would require copying another 300+ lines of code. And we don't need second way of broadcasting (I don't understand why it is like that in cosmos).
</blockquote></details>

ok resolving this one. See previous comment

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/197)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)

___
*[`pkg/grpc/client.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/197#-NCv1-78-H0bSfv6HxNu:-ND1w02K9-PpGS_PQ5Rs:b-i1kzd8) ([raw file](https://github.com/coreumfoundation/coreum/blob/34668aceef9981a09ae882bfb2e0e2c58a170ef5/pkg/grpc/client.go#L34)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I mean smth like this:

```
type ClientCtx struct {
  cosmosclient.Context
}

func (client Client) Invoke(ctx context.Context, method string, req, reply interface{}, opts ...grpc.CallOption) (err error) {

// for broadcasting tx call cosmosclient.Context.Invoke since it already respects the ctx
// for queries override to respect ctx
}

type Chain struct {
// ...
  ClientContext grpc.ClientCtx // use our client context with fixed invoke method & all other methods will be called for original   cosmosclient.Context
}
```
</blockquote></details>

It's not possible because most of the shit inside cosmos sdk require `cosmosclient.Context` struct,  not an interface
___
*[`pkg/grpc/client.go` line 39 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/197#-NCuy3iF93N10_ESPLTB:-ND1w9cOAnGnMTLnqgSh:beqt1z1) ([raw file](https://github.com/coreumfoundation/coreum/blob/34668aceef9981a09ae882bfb2e0e2c58a170ef5/pkg/grpc/client.go#L39)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok resolving this one. See previous comment
</blockquote></details>

so please mark it as "Satisfied"

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/197)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/197)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @wojtek-coreum)

___
*[`pkg/grpc/client.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/197#-NCv1-78-H0bSfv6HxNu:-ND7vfLX3H2yPwbVSdXB:bpvtnrd) ([raw file](https://github.com/coreumfoundation/coreum/blob/34668aceef9981a09ae882bfb2e0e2c58a170ef5/pkg/grpc/client.go#L34)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It's not possible because most of the shit inside cosmos sdk require `cosmosclient.Context` struct,  not an interface
</blockquote></details>

it seems to be possible in integration-tests as we discussed in slack
Pls try to make the change

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/197)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`pkg/grpc/client.go` line 34 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/197#-NCv1-78-H0bSfv6HxNu:-ND8ibUG1WX0vwP7oaKZ:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/34668aceef9981a09ae882bfb2e0e2c58a170ef5/pkg/grpc/client.go#L34)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

it seems to be possible in integration-tests as we discussed in slack
Pls try to make the change 
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/197)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 3 of 10 files at r4, 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/197)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman and @miladz68)

**Pull request merged**
