### PR TITLE
Integrate the distribution module.

### PR DESCRIPTION
**Pull request by dzmitryhil**
* Deterministic gas price for all distribution module transactions.
* Integration tests for all distribution module transactions and spend community pool proposal.

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/248)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/248)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/distribution/community-pool.go` line 102 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGLDMcT4BIJvIPzTfLX:-NGLDMcT4BIJvIPzTfLY:bnqqf3j) ([raw file](https://github.com/coreumfoundation/coreum/blob/7f3cbd0af5b6481284e8c21b6c6b2ef1315a7768/integration-tests/distribution/community-pool.go#L102)):*
> ```Go
> 
> 	// check that recipient has received the coins
> 	communityPoolRecipientBalancesRes, err := bankClient.AllBalances(ctx, &banktypes.QueryAllBalancesRequest{
> ```

you may query only for specific denom
___
*[`integration-tests/distribution/withdraw-reward.go` line 55 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGLDkFU-k1-jSyTuwiZ:-NGLDkFV8tjZ1wyso6U1:b-gjdjtj) ([raw file](https://github.com/coreumfoundation/coreum/blob/7f3cbd0af5b6481284e8c21b6c6b2ef1315a7768/integration-tests/distribution/withdraw-reward.go#L55)):*
> ```Go
> 	clientCtx := chain.ClientContext
> 
> 	// *** Create new validator to use it in the test and capture all required balances. ***
> ```

comment is not accurate because validator has been already created
___
*[`integration-tests/distribution/withdraw-reward.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGLE-Zb3wz-uIwUhMnb:-NGLE-Zb3wz-uIwUhMnc:b-qxn73h) ([raw file](https://github.com/coreumfoundation/coreum/blob/7f3cbd0af5b6481284e8c21b6c6b2ef1315a7768/integration-tests/distribution/withdraw-reward.go#L58)):*
> ```Go
> 
> 	logger.Get(ctx).Info("Delegating some coins to validator to withdraw later")
> 	_, err = tx.BroadcastTx(
> ```

Please verify that delegated coins are not available in balance
___
*[`integration-tests/testing/staking.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGLBe5H4JqSnMkJeSqo:-NGLBe5IBhPAibar-j9i:bub6f4n) ([raw file](https://github.com/coreumfoundation/coreum/blob/7f3cbd0af5b6481284e8c21b6c6b2ef1315a7768/integration-tests/testing/staking.go#L25)):*
> ```Go
> 	if err := chain.Faucet.FundAccountsWithOptions(ctx, staker, BalancesOptions{
> 		Messages: []sdk.Msg{&stakingtypes.MsgCreateValidator{}, &stakingtypes.MsgUndelegate{}},
> 		Amount:   initialAmount.MulRaw(2),
> ```

why `MulRaw(2)`?
___
*[`integration-tests/testing/staking.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGLBqgfBUt0ptbWDxKe:-NGLBqgg8LdJXbUEVIIi:bdl4ub2) ([raw file](https://github.com/coreumfoundation/coreum/blob/7f3cbd0af5b6481284e8c21b6c6b2ef1315a7768/integration-tests/testing/staking.go#L36)):*
> ```Go
> 		cosmosed25519.GenPrivKey().PubKey(),
> 		chain.NewCoin(initialAmount),
> 		stakingtypes.Description{Moniker: fmt.Sprintf("testing-staker-%s", uuid.NewString()[:4])},
> ```

uuid -> use address instead
___
*[`integration-tests/testing/staking.go` line 64 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGLBz6A25l-rtDhCRxf:-NGLBz6A25l-rtDhCRxg:bx391zd) ([raw file](https://github.com/coreumfoundation/coreum/blob/7f3cbd0af5b6481284e8c21b6c6b2ef1315a7768/integration-tests/testing/staking.go#L64)):*
> ```Go
> 	}
> 	if initialAmount.String() != resp.Validator.Tokens.String() {
> 		return nil, nil, nil, errors.Errorf("unexpected validators tokens after creation: %s", resp.Validator.Tokens)
> ```

validators -> validator's
___
*[`integration-tests/testing/staking.go` line 67 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGLC2Po2XIsLHN5SyAx:-NGLC2Po2XIsLHN5SyAy:bx391zd) ([raw file](https://github.com/coreumfoundation/coreum/blob/7f3cbd0af5b6481284e8c21b6c6b2ef1315a7768/integration-tests/testing/staking.go#L67)):*
> ```Go
> 	}
> 	if stakingtypes.Bonded != resp.Validator.Status {
> 		return nil, nil, nil, errors.Errorf("unexpected validators status after creation: %s", resp.Validator.Status)
> ```

validators -> validator's

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/248)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/distribution/community-pool.go` line 102 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGLDMcT4BIJvIPzTfLX:-NGLn0L_2GuHB8o6if5x:bltwgns) ([raw file](https://github.com/coreumfoundation/coreum/blob/7f3cbd0af5b6481284e8c21b6c6b2ef1315a7768/integration-tests/distribution/community-pool.go#L102)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you may query only for specific denom
</blockquote></details>

I did it intentionally to check that the user's entire balances are just a community pool.
___
*[`integration-tests/distribution/withdraw-reward.go` line 55 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGLDkFU-k1-jSyTuwiZ:-NGLnLxmBrZj18xLLcJI:b1djn1y) ([raw file](https://github.com/coreumfoundation/coreum/blob/7f3cbd0af5b6481284e8c21b6c6b2ef1315a7768/integration-tests/distribution/withdraw-reward.go#L55)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

comment is not accurate because validator has been already created
</blockquote></details>

Agree, the place is wrong. Moved above. 



_Code quote:_
```Go
// *** Create new validator to use it in the te
```
___
*[`integration-tests/distribution/withdraw-reward.go` line 58 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGLE-Zb3wz-uIwUhMnb:-NGLnS-s73bgkC9xqbaH:b-ytf2r) ([raw file](https://github.com/coreumfoundation/coreum/blob/7f3cbd0af5b6481284e8c21b6c6b2ef1315a7768/integration-tests/distribution/withdraw-reward.go#L58)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please verify that delegated coins are not available in balance
</blockquote></details>

This is tested in the staking, so no need to do it twice. 



_Code quote:_
```Go
logger.Get(ctx).Info("Delegating some coins to validator to
```
___
*[`integration-tests/testing/staking.go` line 25 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGLBe5H4JqSnMkJeSqo:-NGLpBYX3bLiwZrpCJ93:bbxjssg) ([raw file](https://github.com/coreumfoundation/coreum/blob/7f3cbd0af5b6481284e8c21b6c6b2ef1315a7768/integration-tests/testing/staking.go#L25)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why `MulRaw(2)`?
</blockquote></details>

That was the copy/paste from prev logic. I've refactored it now to use correct amounts.



_Code quote:_
```Go
initialAmount.MulRaw(2),
```
___
*[`integration-tests/testing/staking.go` line 36 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGLBqgfBUt0ptbWDxKe:-NGLpKwG6nt6kJ0bsjUn:bfzxmjd) ([raw file](https://github.com/coreumfoundation/coreum/blob/7f3cbd0af5b6481284e8c21b6c6b2ef1315a7768/integration-tests/testing/staking.go#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

uuid -> use address instead
</blockquote></details>

Agree. Good idea. Done.
___
*[`integration-tests/testing/staking.go` line 64 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGLBz6A25l-rtDhCRxf:-NGLpZKSB-b9GgxdG5u_:b5d54jr) ([raw file](https://github.com/coreumfoundation/coreum/blob/7f3cbd0af5b6481284e8c21b6c6b2ef1315a7768/integration-tests/testing/staking.go#L64)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

validators -> validator's
</blockquote></details>

Updated with the validator address.



_Code quote:_
```Go
unexpected validators tokens
```
___
*[`integration-tests/testing/staking.go` line 67 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGLC2Po2XIsLHN5SyAx:-NGLpjc1Ah4TsuCvz3P2:b5d54jr) ([raw file](https://github.com/coreumfoundation/coreum/blob/7f3cbd0af5b6481284e8c21b6c6b2ef1315a7768/integration-tests/testing/staking.go#L67)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

validators -> validator's
</blockquote></details>

Updated with the validator address.

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/248)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/distribution/withdraw-reward.go` line 163 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGQWyFsAie05ScOvEaX:-NGQWyFsAie05ScOvEaY:b-8bqjmb) ([raw file](https://github.com/coreumfoundation/coreum/blob/db686dd5ffe375df9702873a4c4c9c692476130b/integration-tests/distribution/withdraw-reward.go#L163)):*
> ```Go
> 	}
> 
> 	err = chain.Faucet.FundAccountsWithOptions(ctx, validatorStakerAddress, testing.BalancesOptions{
> ```

Maybe not related to this PR but I see that this function is able to fund only one account so `Accounts` should be changed to `Account`

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/248)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/distribution/withdraw-reward.go` line 163 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGQWyFsAie05ScOvEaX:-NGRAGZlBpxJGrszbmKN:basx6d6) ([raw file](https://github.com/coreumfoundation/coreum/blob/db686dd5ffe375df9702873a4c4c9c692476130b/integration-tests/distribution/withdraw-reward.go#L163)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Maybe not related to this PR but I see that this function is able to fund only one account so `Accounts` should be changed to `Account`
</blockquote></details>

Agree. I've left the TODO.



_Code quote:_
```Go
	err = chain.Faucet.FundAccountsWithOptions(ctx, validatorStakerAddress, testing.BalancesOptions{
```

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/248)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`integration-tests/distribution/withdraw-reward.go` line 19 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGR_4xY5okg1lByQ1I6:-NGR_4xY5okg1lByQ1I7:b6z4muj) ([raw file](https://github.com/coreumfoundation/coreum/blob/072e70515480650fcf908f8a92cc8e281728ad24/integration-tests/distribution/withdraw-reward.go#L19)):*
> ```Go
> 
> // TestWithdrawRewardWithDeterministicGas checks that withdraw reward works correctly and gas is deterministic.
> func TestWithdrawRewardWithDeterministicGas(ctx context.Context, t testing.T, chain testing.Chain) { //nolint:funlen // this test covers the full withdrawal scenario
> ```

This comment does not fit into my screen, and I do have a reasonably large screen 
everything else seems ok

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/248)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`integration-tests/distribution/withdraw-reward.go` line 19 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/248#-NGR_4xY5okg1lByQ1I6:-NGWIHlT5gYCXCmuPYGx:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/072e70515480650fcf908f8a92cc8e281728ad24/integration-tests/distribution/withdraw-reward.go#L19)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

This comment does not fit into my screen, and I do have a reasonably large screen 
everything else seems ok
</blockquote></details>

Done.



_Code quote:_
```Go
// TestWithdrawRewardWithDeterministicGas checks that withdraw rewar
```

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/248)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
