### PR TITLE
Add CalculateGas integration-tests & improve deterministicgas docs

### PR DESCRIPTION
**Pull request by ysv**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: 0 of 4 files reviewed, 1 unresolved discussion

___
*[`integration-tests/pkg/client_test.go` line 65 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-NidgGYTE9VPlC4dAGuu:-NidgGYTE9VPlC4dAGuv:byad3cc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed84d5256ab520e24857d85566208263f57f9b1d/integration-tests/pkg/client_test.go#L65)):*
> ```Go
> 				},
> 			},
> 			expectedGas: 65_000 + 1*50_000 + 0*10 + (3-1)*1000, // extra 2 signatures
> ```

here is the error I'm getting when running this test:

```
=== RUN   TestCalculateGas
=== PAUSE TestCalculateGas
=== CONT  TestCalculateGas
    client_test.go:34: Funding accounts for tests, it might take a while...
    client_test.go:34: Test accounts funded
    client_test.go:35: Funding accounts for tests, it might take a while...
    client_test.go:35: Test accounts funded
--- FAIL: TestCalculateGas (1.82s)
=== RUN   TestCalculateGas/single_address_send
estimatedGas: 115000
chainEstimatedGas: 115000
    --- PASS: TestCalculateGas/single_address_send (0.01s)
=== RUN   TestCalculateGas/multisig_bank_send
estimatedGas: 115590
chainEstimatedGas: 115000
    client_test.go:81: 
        	Error:      	Not equal: 
        	            	expected: 117000
        	            	actual  : 115590
        	Test:       	TestCalculateGas/multisig_bank_send
    --- FAIL: TestCalculateGas/multisig_bank_send (0.01s)


Expected :117000
Actual   :115590
```

Either gas estimation or our gas module doesn't work properly lets discuss

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: 0 of 5 files reviewed, 2 unresolved discussions

___
*[`integration-tests/modules/auth_test.go` line 188 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-Nij-lln7h69U6DukMGj:-Nij-lln7h69U6DukMGk:b-5soimx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/aa05082789687de20e31cf1502a74414938b0aa4/integration-tests/modules/auth_test.go#L188)):*
> ```Go
> 	//requireT.Equal(txRes.GasUsed, txRes.GasWanted) // another option to reproduce is to use chain.TxFactory().WithSimulateAndExecute(true) & this assertion.
> 
> 	requireT.Equal(txRes.GasUsed, int64(estimatedGas)) // this shouldn't fail.
> ```

getting this error here:

```
Error:      	Not equal: 
        	            	expected: 115000
        	            	actual  : 126360
        	Test:       	TestAuthMultisig
--- FAIL: TestAuthMultisig (1.69s)
```

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: 0 of 5 files reviewed, 2 unresolved discussions

___
*[`integration-tests/modules/auth_test.go` line 188 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-Nij-lln7h69U6DukMGj:-NijA1zvEldTCF7nHL0o:b-3d2mub) ([raw file](https://github.com/CoreumFoundation/coreum/blob/aa05082789687de20e31cf1502a74414938b0aa4/integration-tests/modules/auth_test.go#L188)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

getting this error here:

```
Error:      	Not equal: 
        	            	expected: 115000
        	            	actual  : 126360
        	Test:       	TestAuthMultisig
--- FAIL: TestAuthMultisig (1.69s)
```
</blockquote></details>

65_000 + 50_000 + x*10

diff: 11_360 / 10

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[`x/deterministicgas/spec/README.tmpl.md` line 18 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-NijscvK0DDGlh8op9HH:-NijscvK0DDGlh8op9HI:bx6w0uk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/aa05082789687de20e31cf1502a74414938b0aa4/x/deterministicgas/spec/README.tmpl.md#L18)):*
> ```Markdown
> 
> `
> Gas = FixedGas + Sum(Gas for each message) + GasForExtraBytes + GasForExtraSignatures
> ```

While implementing this PR I realised that our deterministic gas formula doesn't work like this.
We provide limited amount of gas `func (cfg Config) TxBaseGas` which is equal to `2048*10 + 1*1000 = 21480` but this gas could possibly cover both sig verification & free bytes. And anything over this gas will be charged.

So more correct formula would be:

```
Gas = FixedGas + Sum(Gas for each message) + max((GasForBytes + GasForSignatures - TxBaseGas),0)
```

But I'm not sure if we should change it.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/auth_test.go` line 181 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-NimutuVBIOCjvQwgWxM:-NimutuVBIOCjvQwgWxN:bdh6ycz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7ae72ad12fe52705c3262773d752ad23c02341df/integration-tests/modules/auth_test.go#L181)):*
> ```Go
> 	t.Logf("Fully signed tx executed, txHash:%s, gasUsed:%d, gasWanted:%d", txRes.TxHash, txRes.GasUsed, txRes.GasWanted)
> 
> 	// Real gas used might be less that estimation for multisig account because (especially when there are many signers)
> ```

Do you mean that we put all the signatures there, not the minimum number?
___
*[`integration-tests/modules/auth_test.go` line 294 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-NimvH_KADgG9msZXieb:-NimvH_KADgG9msZXiec:b-e480xo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7ae72ad12fe52705c3262773d752ad23c02341df/integration-tests/modules/auth_test.go#L294)):*
> ```Go
> 			// estimation uses worst case to estimate number of bytes in tx which causes possible overflow of free bytes.
> 			// 10 is price for each extra byte over FreeBytes.
> 			expectedGas: dgc.FixedGas + 1*deterministicgas.BankSendPerCoinGas + 1133*10,
> ```

10 -> constant `TxSizeCostPerByte`
___
*[`x/deterministicgas/spec/README.tmpl.md` line 18 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-NijscvK0DDGlh8op9HH:-Nimu13k4CrnlmkM-KPI:b-zgtr4l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/aa05082789687de20e31cf1502a74414938b0aa4/x/deterministicgas/spec/README.tmpl.md#L18)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

While implementing this PR I realised that our deterministic gas formula doesn't work like this.
We provide limited amount of gas `func (cfg Config) TxBaseGas` which is equal to `2048*10 + 1*1000 = 21480` but this gas could possibly cover both sig verification & free bytes. And anything over this gas will be charged.

So more correct formula would be:

```
Gas = FixedGas + Sum(Gas for each message) + max((GasForBytes + GasForSignatures - TxBaseGas),0)
```

But I'm not sure if we should change it.
</blockquote></details>

In ante handler, we charge for signatures and size using `TxBaseGas` amount. Whatever gas is left is ignored, but if we had to charge more, additional gas is taken from the gas limit declared by user.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/modules/auth_test.go` line 181 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-NimutuVBIOCjvQwgWxM:-Nin_dqCEPWgyeUlyS2V:b-n1lm4i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7ae72ad12fe52705c3262773d752ad23c02341df/integration-tests/modules/auth_test.go#L181)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do you mean that we put all the signatures there, not the minimum number?
</blockquote></details>

we put min num of signatures but inside cosmos-sdk handler they estimate the worst case scenario. I haven't understood all the details but it seems like they consider all signatures to be present and each address to be multisign or smth similar

you can check inside `x/auth/ante/basic.go:99`

Also Lets discuss
___
*[`integration-tests/modules/auth_test.go` line 294 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-NimvH_KADgG9msZXieb:-NinZr9g60kAeaTJPUpQ:batto8p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7ae72ad12fe52705c3262773d752ad23c02341df/integration-tests/modules/auth_test.go#L294)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

10 -> constant `TxSizeCostPerByte`
</blockquote></details>

This value is defined inside auth params
Added query
___
*[`x/deterministicgas/spec/README.tmpl.md` line 18 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-NijscvK0DDGlh8op9HH:-Nin_bKOAbK1fBeNg3Ry:b-1t0ywe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/aa05082789687de20e31cf1502a74414938b0aa4/x/deterministicgas/spec/README.tmpl.md#L18)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

In ante handler, we charge for signatures and size using `TxBaseGas` amount. Whatever gas is left is ignored, but if we had to charge more, additional gas is taken from the gas limit declared by user.
</blockquote></details>

Lets discuss after daily

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-NinfBl_AMFgTxQTcD-p:-NinfBl_AMFgTxQTcD-q:b8r1443) (no related file):*
2 more interesting findings

Let me explain on the call:
```
Consumig gas descriptor: "DeterministicGas (gas required: 50000, message type: \*types.MsgSend)", amount: 50000  
Consumig gas descriptor: "txSize", amount: 11830  
Consumig gas descriptor: "ante verify: secp256k1", amount: 1000  
Consumig gas descriptor: "ante verify: secp256k1", amount: 1000  
Consumig gas descriptor: "ante verify: secp256k1", amount: 1000  
Consumig gas descriptor: "ante verify: secp256k1", amount: 1000  
Consumig gas descriptor: "ante verify: secp256k1", amount: 1000  
Consumig gas descriptor: "ante verify: secp256k1", amount: 1000  
Consumig gas descriptor: "Fixed", amount: 65000  
ChargeFixedGasDecorator: simulate: false  
. gasMeter: BasicGasMeter:  
limit: 115000  
consumed: 65000
```

```
Consumig gas descriptor: "txSize", amount: 7570  
Consumig gas descriptor: "txSize", amount: 25270  
Consumig gas descriptor: "OverBonus", amount: 11360  
Consumig gas descriptor: "Fixed", amount: 65000  
ChargeFixedGasDecorator: simulate: true  
. gasMeter: InfiniteGasMeter:  
consumed: 76360
```

___

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @miladz68)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-NinfBl_AMFgTxQTcD-p:-NioJjkV0wCLXQhh79ts:b-yk8l5u) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

2 more interesting findings

Let me explain on the call:
```
Consumig gas descriptor: "DeterministicGas (gas required: 50000, message type: \*types.MsgSend)", amount: 50000  
Consumig gas descriptor: "txSize", amount: 11830  
Consumig gas descriptor: "ante verify: secp256k1", amount: 1000  
Consumig gas descriptor: "ante verify: secp256k1", amount: 1000  
Consumig gas descriptor: "ante verify: secp256k1", amount: 1000  
Consumig gas descriptor: "ante verify: secp256k1", amount: 1000  
Consumig gas descriptor: "ante verify: secp256k1", amount: 1000  
Consumig gas descriptor: "ante verify: secp256k1", amount: 1000  
Consumig gas descriptor: "Fixed", amount: 65000  
ChargeFixedGasDecorator: simulate: false  
. gasMeter: BasicGasMeter:  
limit: 115000  
consumed: 65000
```

```
Consumig gas descriptor: "txSize", amount: 7570  
Consumig gas descriptor: "txSize", amount: 25270  
Consumig gas descriptor: "OverBonus", amount: 11360  
Consumig gas descriptor: "Fixed", amount: 65000  
ChargeFixedGasDecorator: simulate: true  
. gasMeter: InfiniteGasMeter:  
consumed: 76360
```
</blockquote></details>

recalculate numbers myself one more time

___
___
*[`x/deterministicgas/spec/README.tmpl.md` line 18 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-NijscvK0DDGlh8op9HH:-NioLIFrCl2_RN6ZLZnu:bitshet) ([raw file](https://github.com/CoreumFoundation/coreum/blob/aa05082789687de20e31cf1502a74414938b0aa4/x/deterministicgas/spec/README.tmpl.md#L18)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Lets discuss after daily
</blockquote></details>

decided to update formula here

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @miladz68)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-NinfBl_AMFgTxQTcD-p:-Niozn9O1vvp9dAzHBRd:bnjhjto) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

recalculate numbers myself one more time
</blockquote></details>

calculation for simulate: true:

32,840 - for txSize
6000 - for signatures
total: 38,840

TxBaseGas: 21480
OverBonus: 11360
total: 32840 (signatures are not included)

This means that during estimation they don't include signature validation (they are also not present in logs) and it only works because they overestimate signatures byte-size which later is enough to cover signatures also.

created cosmos-sdk issue: https://github.com/cosmos/cosmos-sdk/issues/18441

___

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: 4 of 9 files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`x/deterministicgas/spec/README.tmpl.md` line 18 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-NijscvK0DDGlh8op9HH:-NitDzJM5S8NvmxkSNAO:bb7f2mf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/aa05082789687de20e31cf1502a74414938b0aa4/x/deterministicgas/spec/README.tmpl.md#L18)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

decided to update formula here
</blockquote></details>

done

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/auth_test.go` line 405 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-NitNpZk0lg1UG6HI8nl:-NitNpZk0lg1UG6HI8nm:b-iga6kj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6c303869326a6c38bd28a8aa5fb7bf70fbc7ba36/integration-tests/modules/auth_test.go#L405)):*
> ```Go
> 	for _, tt := range testsNonDeterm {
> 		tt := tt
> 		t.Run(tt.name, func(t *testing.T) {
> ```

add `t.Parallel()`?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/modules/auth_test.go` line 405 at r5](https://reviewable.io/reviews/CoreumFoundation/coreum/706#-NitNpZk0lg1UG6HI8nl:-Nitt_NI5PchwN_1UIJZ:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6c303869326a6c38bd28a8aa5fb7bf70fbc7ba36/integration-tests/modules/auth_test.go#L405)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

add `t.Parallel()`?
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/706)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
