### PR TITLE
skip checking if chain-id is enabled if the issue command is help

### PR DESCRIPTION
**Pull request by miladz68**
there are 2 changes here.
1. we add chain-id flag to all subcommand of cored. 
2. we skip checking chain-id if no commands are provided or if the help flag is set

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/126)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/126)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`cmd/cored/main.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N8waoQz1x7jQUfS2n5Y:-N8waoQz1x7jQUfS2n5Z:b-tfmun0) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca228d3719d93b3e3b7598b673d13692487c867e/cmd/cored/main.go#L32)):*
> ```Go
> 	)
> 
> 	rootCmd.PersistentFlags().String(flags.FlagChainID, string(app.DefaultChainID), "The network chain ID")
> ```

some commands like `cored tx *` or `cored query *` define `--chain-id` flags themselves. It means that that local flag gets priority over the one defined on root. Did you check how it behaves? I think you need to declare `--chain-id` recursively on each subcommand directly.
___
*[`cmd/cored/main.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N8wbBAcBX7tqhUM0gKz:-N8wbBAcBX7tqhUM0gL-:bf3rx4n) ([raw file](https://github.com/coreumfoundation/coreum/blob/145d09f54b8d6d10f193c1faa0d3258faa5ace16/cmd/cored/main.go#L32)):*
> ```Go
> 	)
> 
> 	rootCmd.AddCommand(initCmd(app.DefaultNodeHome))
> ```

Why  is`init` command removed?
___
*[`cmd/cored/preprocess_flags.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N8wbPFJDyl5WoqgV7HX:-N8wbPFJDyl5WoqgV7HY:bwryq16) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca228d3719d93b3e3b7598b673d13692487c867e/cmd/cored/preprocess_flags.go#L17)):*
> ```Go
> func preProcessFlags() (app.Network, error) {
> 	// define flags
> 	flagHelp := "help"
> ```

it might be defined as `const`
___
*[`cmd/cored/preprocess_flags.go` line 21 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N8wbLwXDtJSA52P3FSe:-N8wbLwXDtJSA52P3FSf:b-d5r2dp) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca228d3719d93b3e3b7598b673d13692487c867e/cmd/cored/preprocess_flags.go#L21)):*
> ```Go
> 	flagSet.ParseErrorsWhitelist.UnknownFlags = true
> 	flagSet.String(flags.FlagHome, app.DefaultNodeHome, "Directory for config and data")
> 	flagSet.BoolP(flagHelp, "h", false, "")
> ```

Please add a comment explaining why this is done

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/126)* status: all files reviewed, 4 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`cmd/cored/main.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N8wbBAcBX7tqhUM0gKz:-N8wix4fBjlJ1W2m5QSM:b-sp8zyj) ([raw file](https://github.com/coreumfoundation/coreum/blob/145d09f54b8d6d10f193c1faa0d3258faa5ace16/cmd/cored/main.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why  is`init` command removed?
</blockquote></details>

removed mistakenly, reverted.
___
*[`cmd/cored/main.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N8waoQz1x7jQUfS2n5Y:-N8wjo-3-bKlpQWEPsVP:b-v29cu9) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca228d3719d93b3e3b7598b673d13692487c867e/cmd/cored/main.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

some commands like `cored tx *` or `cored query *` define `--chain-id` flags themselves. It means that that local flag gets priority over the one defined on root. Did you check how it behaves? I think you need to declare `--chain-id` recursively on each subcommand directly.
</blockquote></details>

I have checked the query command.
___
*[`cmd/cored/preprocess_flags.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N8wbPFJDyl5WoqgV7HX:-N8wjw_V7S5dqQmegtE1:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca228d3719d93b3e3b7598b673d13692487c867e/cmd/cored/preprocess_flags.go#L17)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

it might be defined as `const`
</blockquote></details>

Done.
___
*[`cmd/cored/preprocess_flags.go` line 21 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N8wbLwXDtJSA52P3FSe:-N8wkBno42i0xiSMaBCD:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca228d3719d93b3e3b7598b673d13692487c867e/cmd/cored/preprocess_flags.go#L21)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please add a comment explaining why this is done
</blockquote></details>

Done.



_Code quote:_
```Go
flagSet.BoolP(flagHelp, "h", false, "")
```

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/126)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`cmd/cored/main.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N8waoQz1x7jQUfS2n5Y:-N8wp57EDzQj9Z14G2JO:bv9cp7k) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca228d3719d93b3e3b7598b673d13692487c867e/cmd/cored/main.go#L32)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I have checked the query command.
</blockquote></details>

And what's the result? I'm sure that at least default value for that --chain-id is different that what we provide. Also description could be unified by adding the same flag everywhere

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/126)* status: all files reviewed, 1 unresolved discussion (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`cmd/cored/main.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N8waoQz1x7jQUfS2n5Y:-N91yU5L46cta4Knq9HR:byq3u6s) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca228d3719d93b3e3b7598b673d13692487c867e/cmd/cored/main.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

And what's the result? I'm sure that at least default value for that --chain-id is different that what we provide. Also description could be unified by adding the same flag everywhere
</blockquote></details>

the result was that it worked without a problem.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/126)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`cmd/cored/main.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N8waoQz1x7jQUfS2n5Y:-N95RVRpA2GT3JDpgiMX:b-owc9yf) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca228d3719d93b3e3b7598b673d13692487c867e/cmd/cored/main.go#L32)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the result was that it worked without a problem.
</blockquote></details>

Compare this output where `--chain-id` is delivered by us correctly:

```
$ cored keys list --help

# ...

Global Flags:
      --chain-id string          The network chain ID (default "coreum-mainnet-1")
```

With this where `--chain-id` flag added by cosmos to the command directly takes the precedence over the one you added to the root:

```
$ cored q bank --help

# ...

Global Flags:
      --chain-id string     The network chain ID
```

It would be nice to maintain default value everywhere.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/126)* status: all files reviewed, 1 unresolved discussion (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`cmd/cored/main.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N8waoQz1x7jQUfS2n5Y:-N95T2WUD_jPVBNwxFpA:bpwuudt) ([raw file](https://github.com/coreumfoundation/coreum/blob/ca228d3719d93b3e3b7598b673d13692487c867e/cmd/cored/main.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Compare this output where `--chain-id` is delivered by us correctly:

```
$ cored keys list --help

# ...

Global Flags:
      --chain-id string          The network chain ID (default "coreum-mainnet-1")
```

With this where `--chain-id` flag added by cosmos to the command directly takes the precedence over the one you added to the root:

```
$ cored q bank --help

# ...

Global Flags:
      --chain-id string     The network chain ID
```

It would be nice to maintain default value everywhere.
</blockquote></details>

It would definitely nice. But too much hack is required.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/126)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`cmd/cored/preprocess_flags.go` line 30 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N95_lJ-3oNwyOV4T-Hd:-N95_lJ039ZEwbBX1KDY:b-hc35x6) ([raw file](https://github.com/coreumfoundation/coreum/blob/a4fdac5f969d957c86c2d87ac3bd4f571c219a69/cmd/cored/preprocess_flags.go#L30)):*
> ```Go
> 	// this is introduced only because the the default chain-id is disabled.
> 	// TODO: remove this check after default chain-id (mainnet) is enabled.
> 	if flagSet.Changed(flagHelp) || len(os.Args) == 1 {
> ```

Now I see that instead of introducing this hack, you could just check if error returned from `flagSet.Parse` is `pflag.ErrHelp`: https://github.com/spf13/pflag/blob/master/flag.go#L113

And I think it won't be a hack anymore because if user requests a help you just want to print a help and exit without further processing.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/126)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`cmd/cored/preprocess_flags.go` line 30 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N95_lJ-3oNwyOV4T-Hd:-N95ay4W-d9WR5dP6W7q:b9jtlrj) ([raw file](https://github.com/coreumfoundation/coreum/blob/a4fdac5f969d957c86c2d87ac3bd4f571c219a69/cmd/cored/preprocess_flags.go#L30)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Now I see that instead of introducing this hack, you could just check if error returned from `flagSet.Parse` is `pflag.ErrHelp`: https://github.com/spf13/pflag/blob/master/flag.go#L113

And I think it won't be a hack anymore because if user requests a help you just want to print a help and exit without further processing.
</blockquote></details>

To make it work like this you probsbly need to replace `pflag.ExitOnError` with `pflag.ContinueOnError` and remove `flagSet.BoolP(flagHelp, "h", false, "")` because otherwise `pflag.ErrHelp` is not generated.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/126)* status: all files reviewed, 2 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`cmd/cored/preprocess_flags.go` line 30 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N95_lJ-3oNwyOV4T-Hd:-N95aeCdDg-8CDeOgt0h:byq3ulc) ([raw file](https://github.com/coreumfoundation/coreum/blob/a4fdac5f969d957c86c2d87ac3bd4f571c219a69/cmd/cored/preprocess_flags.go#L30)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

To make it work like this you probsbly need to replace `pflag.ExitOnError` with `pflag.ContinueOnError` and remove `flagSet.BoolP(flagHelp, "h", false, "")` because otherwise `pflag.ErrHelp` is not generated.
</blockquote></details>

if we remove `flagSet.BoolP(flagHelp, "h", false, "")` it prints the usage of pre-process flag.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/126)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`cmd/cored/main.go` line 41 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N96MrxvBPnpnVu6OChi:-N96MrxvBPnpnVu6OChj:b-ul7oqm) ([raw file](https://github.com/coreumfoundation/coreum/blob/7b9fe69a0f0c1e5abf7e6dff64e7160a39b5d1fb/cmd/cored/main.go#L41)):*
> ```Go
> }
> 
> func overwriteDefaultChainIDFlags(parentCmd *cobra.Command) {
> ```

Good job!
___
*[`cmd/cored/preprocess_flags.go` line 30 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N95_lJ-3oNwyOV4T-Hd:-N96I4WuCgIaHuyqqCt-:b-7wmvsd) ([raw file](https://github.com/coreumfoundation/coreum/blob/a4fdac5f969d957c86c2d87ac3bd4f571c219a69/cmd/cored/preprocess_flags.go#L30)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

if we remove `flagSet.BoolP(flagHelp, "h", false, "")` it prints the usage of pre-process flag.
</blockquote></details>

ah, yea, now I remember why I didn't do it this way inside `logger` package
___
*[`cmd/cored/preprocess_flags.go` line 26 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N96ISnC7FqlhIkk87--:-N96ISnC7FqlhIkk87-0:b-suhrgm) ([raw file](https://github.com/coreumfoundation/coreum/blob/7b9fe69a0f0c1e5abf7e6dff64e7160a39b5d1fb/cmd/cored/preprocess_flags.go#L26)):*
> ```Go
> 	//nolint:errcheck // since we have set ExitOnError on flagset, we don't need to check for errors here
> 	flagSet.Parse(os.Args[1:])
> 	var shouldPrintHelp bool
> ```

maybe `flagSet.BoolVarP(&shouldPrintHelp, flagHelp, "h", false, "")`
then `flagp` will do the job for you and later on you will need only `shouldPrintHelp ||= len(os.Args) == 1`

Checking `flagSet.Changed(flagHelp)` is not a good solution because it returns `true` even if I set `--help=false`
___
*[`cmd/cored/preprocess_flags.go` line 39 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N96JwbqEEcCS4DFrmCv:-N96JwbqEEcCS4DFrmCw:b-8g9zmk) ([raw file](https://github.com/coreumfoundation/coreum/blob/7b9fe69a0f0c1e5abf7e6dff64e7160a39b5d1fb/cmd/cored/preprocess_flags.go#L39)):*
> ```Go
> 	// this is introduced only because some chains are disabled.
> 	// TODO: remove this check after all chains are enabled.
> 	if ignoreErr := errors.Is(err, app.ErrDisableNetwork) && shouldPrintHelp; err != nil && !ignoreErr {
> ```

I'm pretty sure that processing here should be stopped even if network is enabled. Because user requested only a help, there should be no additional processing despite printing help later on by the real command

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/126)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`cmd/cored/preprocess_flags.go` line 26 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N96ISnC7FqlhIkk87--:-N97-h5xBEtTREujuFe4:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/7b9fe69a0f0c1e5abf7e6dff64e7160a39b5d1fb/cmd/cored/preprocess_flags.go#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

maybe `flagSet.BoolVarP(&shouldPrintHelp, flagHelp, "h", false, "")`
then `flagp` will do the job for you and later on you will need only `shouldPrintHelp ||= len(os.Args) == 1`

Checking `flagSet.Changed(flagHelp)` is not a good solution because it returns `true` even if I set `--help=false`
</blockquote></details>

Done.
___
*[`cmd/cored/preprocess_flags.go` line 39 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N96JwbqEEcCS4DFrmCv:-N9B1w6A2tfAauWf1X6-:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/7b9fe69a0f0c1e5abf7e6dff64e7160a39b5d1fb/cmd/cored/preprocess_flags.go#L39)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I'm pretty sure that processing here should be stopped even if network is enabled. Because user requested only a help, there should be no additional processing despite printing help later on by the real command
</blockquote></details>

Done.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/126)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`cmd/cored/preprocess_flags.go` line 28 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N9BWiLK3r0w2QX3nlI_:-N9BWiLK3r0w2QX3nlIa:bbm8thq) ([raw file](https://github.com/coreumfoundation/coreum/blob/49c17b7e4bf92de76c30e4b5415a40e46a08cb54/cmd/cored/preprocess_flags.go#L28)):*
> ```Go
> 	// we consider the issued command to be a help command if no args are provided.
> 	// in that case we will not check the chain-id and will return
> 	// TODO: remove this check after all chains are enabled.
> ```

This TODO should be removed because it's not true. If `--help` is requested command should not make any additional processing (like creating configs, parsing arguments etc.). Just help message should be printed.
___
*[`cmd/cored/preprocess_flags.go` line 29 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N9BWPkH6YkoMHg8DrdA:-N9BWPkI6nSWtuVAwuq3:b-4llz4v) ([raw file](https://github.com/coreumfoundation/coreum/blob/49c17b7e4bf92de76c30e4b5415a40e46a08cb54/cmd/cored/preprocess_flags.go#L29)):*
> ```Go
> 	// in that case we will not check the chain-id and will return
> 	// TODO: remove this check after all chains are enabled.
> 	if len(os.Args) == 1 && *help {
> ```

&& -> ||

otherwise it's false if `--help` is provided because `len(os.Args)` equals 2

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/126)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`cmd/cored/preprocess_flags.go` line 28 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N9BWiLK3r0w2QX3nlI_:-N9B_U6r0wd89LcGr3i4:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/49c17b7e4bf92de76c30e4b5415a40e46a08cb54/cmd/cored/preprocess_flags.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This TODO should be removed because it's not true. If `--help` is requested command should not make any additional processing (like creating configs, parsing arguments etc.). Just help message should be printed.
</blockquote></details>

Done.
___
*[`cmd/cored/preprocess_flags.go` line 29 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/126#-N9BWPkH6YkoMHg8DrdA:-N9B_UNB5tFfxMWH89dU:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/49c17b7e4bf92de76c30e4b5415a40e46a08cb54/cmd/cored/preprocess_flags.go#L29)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

&& -> ||

otherwise it's false if `--help` is provided because `len(os.Args)` equals 2
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/126)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliverasistemas, @xlab, and @ysv)

**Pull request merged**
