### PR TITLE
Implemented nondeterministic gas for extensions

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)

### CODE REVIEW

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 131 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NyUtXAm3F1dlnh24HxQ:-NyUtXAn7delRWmSXErt:b220ll9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e55b4d0d9f6c73c0dadace0f4320f1905aa76001/x/deterministicgas/types/gas.go#L131)):*
> ```Go
> }
> 
> func ctxForDeterministicGas(
> ```

I would suggest making `ctxForDeterministicGas` the method and removing keeper and config from the method args. 
___
*[`x/deterministicgas/types/gas.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NyUuHB32xIjkGcb_mm1:-NyUuHB32xIjkGcb_mm2:b-i68948) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e55b4d0d9f6c73c0dadace0f4320f1905aa76001/x/deterministicgas/types/gas.go#L161)):*
> ```Go
> }
> 
> func hasExtensionCall(ctx sdk.Context, msg sdk.Msg, assetFTKeeper AssetFTKeeper) (bool, error) {
> ```

Why are there no tests?
___
*[`x/deterministicgas/types/gas.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NyUunZL8sj1zcMlemll:-NyUunZL8sj1zcMlemlm:b4ek05z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e55b4d0d9f6c73c0dadace0f4320f1905aa76001/x/deterministicgas/types/gas.go#L161)):*
> ```Go
> }
> 
> func hasExtensionCall(ctx sdk.Context, msg sdk.Msg, assetFTKeeper AssetFTKeeper) (bool, error) {
> ```

You also need to update the spec with it. At least one sentence.
___
*[`x/deterministicgas/types/gas.go` line 163 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NyUua015zxn_O631KdF:-NyUua015zxn_O631KdG:bxfmk1k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e55b4d0d9f6c73c0dadace0f4320f1905aa76001/x/deterministicgas/types/gas.go#L163)):*
> ```Go
> func hasExtensionCall(ctx sdk.Context, msg sdk.Msg, assetFTKeeper AssetFTKeeper) (bool, error) {
> 	switch typedMsg := msg.(type) {
> 	case *banktypes.MsgSend:
> ```

What about
* Authz
* WASM call (with attached funds)
* distribution.MsgFundCommunityPool
* ibc.MsgTransfer
___
*[`x/deterministicgas/types/gas.go` line 170 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NyUuMoV5sAj_HNV4tyX:-NyUuMoV5sAj_HNV4tyY:b37h9sz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e55b4d0d9f6c73c0dadace0f4320f1905aa76001/x/deterministicgas/types/gas.go#L170)):*
> ```Go
> 				// type of token (e.g core, ibc, etc) and don't apply asset ft rules.
> 				continue
> 			} else if err != nil {
> ```

You don't need else, if you have the continue.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 131 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NyUtXAm3F1dlnh24HxQ:-Ny_3iDF29vrMYcFGqgp:b-7tdf7d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e6bfe10c68933d5e8ca9bae136cdaccb6b02d987/x/deterministicgas/types/gas.go#L131)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would suggest making `ctxForDeterministicGas` the method and removing keeper and config from the method args.
</blockquote></details>

agree
___
*[`x/deterministicgas/types/gas.go` line 163 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NyUua015zxn_O631KdF:-Ny_4HCR519RwY1rNAQI:b-18coja) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e6bfe10c68933d5e8ca9bae136cdaccb6b02d987/x/deterministicgas/types/gas.go#L163)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What about
* Authz
* WASM call (with attached funds)
* distribution.MsgFundCommunityPool
* ibc.MsgTransfer
</blockquote></details>

WASM is not a problem because smart contract executes `MsgSend`, so it will be handled. 
Also what about MultiSend?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 21 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-Nz1yU0hD0cMy3jCWb12:-Nz1yU0hD0cMy3jCWb13:b-31la3h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0bce27dfa630137ed0a499e534bdb4e8f05f0275/x/deterministicgas/types/gas.go#L21)):*
> ```Go
> 	fuseGasMultiplier    = 1000
> 	expectedMaxGasFactor = 5
> )
> ```

Update the typo, please



_Code quote:_
```Go
once if
```

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 131 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NyUtXAm3F1dlnh24HxQ:-Nz2BhjFE_fr6XANouoU:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e6bfe10c68933d5e8ca9bae136cdaccb6b02d987/x/deterministicgas/types/gas.go#L131)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

agree
</blockquote></details>

Done.
___
*[`x/deterministicgas/types/gas.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NyUuHB32xIjkGcb_mm1:-Nz2Bjwi7F_qwQ5qRjCN:bx2son) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e6bfe10c68933d5e8ca9bae136cdaccb6b02d987/x/deterministicgas/types/gas.go#L161)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why are there no tests?
</blockquote></details>

the tests are added to integration tests now. 
___
*[`x/deterministicgas/types/gas.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NyUunZL8sj1zcMlemll:-Nz2OpAP7A7r8cRzDwTd:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e6bfe10c68933d5e8ca9bae136cdaccb6b02d987/x/deterministicgas/types/gas.go#L161)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You also need to update the spec with it. At least one sentence.
</blockquote></details>

Done.
___
*[`x/deterministicgas/types/gas.go` line 163 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NyUua015zxn_O631KdF:-Nz2MA9D1ukX06dp2Mmn:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e6bfe10c68933d5e8ca9bae136cdaccb6b02d987/x/deterministicgas/types/gas.go#L163)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

WASM is not a problem because smart contract executes `MsgSend`, so it will be handled. 
Also what about MultiSend?
</blockquote></details>

Done.
___
*[`x/deterministicgas/types/gas.go` line 170 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NyUuMoV5sAj_HNV4tyX:-Nz2MC9GCKbt6LWUBD4b:b-mjalgb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e6bfe10c68933d5e8ca9bae136cdaccb6b02d987/x/deterministicgas/types/gas.go#L170)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You don't need else, if you have the continue.
</blockquote></details>

I do need the else for the case that err is none of ErrInvalidDenom or ErrTokenNotFound but the error is still not nil.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NyUuHB32xIjkGcb_mm1:-Nz2fVxW2wpFkgcx_jIA:bx0slpm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e6bfe10c68933d5e8ca9bae136cdaccb6b02d987/x/deterministicgas/types/gas.go#L161)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But you don't cover all of the messages in the integration tests. Also, it would be nice to define a test (similar to the deterministic gas), that fails if we don't specify that we are aware of the message, and we say that extensions do not touch it.  IMO we can move that switch to the deterministic gas config somehow, and for each message, there  `isExtention` function. In that case, you will have to define it for each message.
@masihyeganeh @ysv @wojtek-coreum WDYT ?
</blockquote></details>

BTW I'm OK to merge this PR and do it separately, to unblock the edge-case tests.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 148 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NzCPaCY3RnEMfZIqTCD:-NzCPaCY3RnEMfZIqTCE:b-pinco9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/86674202b0efff7f64b2938c8a9a6addc3d135b1/x/deterministicgas/types/gas.go#L148)):*
> ```Go
> 		}
> 
> 		// // we consider extensions to be nondeterministic.
> ```

remove `//`

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 161 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NyUuHB32xIjkGcb_mm1:-NzS2sK42mjNmPYYQOa5:bdpfmnu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e6bfe10c68933d5e8ca9bae136cdaccb6b02d987/x/deterministicgas/types/gas.go#L161)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

BTW I'm OK to merge this PR and do it separately, to unblock the edge-case tests.
</blockquote></details>

I created a follow up task for it.
___
*[`x/deterministicgas/types/gas.go` line 148 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NzCPaCY3RnEMfZIqTCD:-NzS1Vpw-hzxh-Affiyu:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/86674202b0efff7f64b2938c8a9a6addc3d135b1/x/deterministicgas/types/gas.go#L148)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

remove `//`
</blockquote></details>

Done.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: 7 of 10 files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 31 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NzTP2PJ2rADHYIXwm30:-NzTP2PJ2rADHYIXwm31:b-z7z7ne) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b2ea150c3705c9907edd0e4efe9870545d2607ce/x/deterministicgas/types/gas.go#L31)):*
> ```Go
> 	simFuseGasMultiplier      = 1000
> 	expectedMaxGasFactor      = 5
> 	untrackedMaxGasForQueries = uint64(5_000)
> ```

Is 5k is enough for the normal operation ?

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/types/gas.go` line 31 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/845#-NzTP2PJ2rADHYIXwm30:-NzTWtoLE3nGvG332UQU:bjlxfvp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b2ea150c3705c9907edd0e4efe9870545d2607ce/x/deterministicgas/types/gas.go#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is 5k is enough for the normal operation ?
</blockquote></details>

Yes, normally it is 2k. i choose 5k as upper limit.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: 7 of 10 files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 3 files at r3, 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/845)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Pull request merged**
