### PR TITLE
Implement raw bytes data type for NFTs

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> Reviewed 1 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: 0 of 32 files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 82 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxshezBLwLq3-EHQal:-NJxshezBLwLq3-EHQam:bf78d6i) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/integration-tests/modules/assetnft_test.go#L82)):*
> ```Go
> 
> 	// issue new NFT class
> 	data, err = codectypes.NewAnyWithValue(&assetnfttypes.DataBytes{Data: []byte{0x00, 0x01}})
> ```

Let's use json data instead decoded to the bytes.
___
*[`integration-tests/modules/assetnft_test.go` line 217 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxsr1_7W7EDkoGA9Xu:-NJxsr1_7W7EDkoGA9Xv:bhe3rz) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/integration-tests/modules/assetnft_test.go#L217)):*
> ```Go
> 
> 	// mint new token in that class
> 	data, err = codectypes.NewAnyWithValue(&assetnfttypes.DataBytes{Data: []byte{0x00, 0x01}})
> ```

Same, thing. Let's use json data.
___
*[`x/asset/nft/types/codec.go` line 11 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxtS7-8uVMiFExstbY:-NJxtS701tFRsJj5-HuP:befu1qr) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/x/asset/nft/types/codec.go#L11)):*
> ```Go
> // RegisterInterfaces registers the asset module tx interfaces.
> func RegisterInterfaces(registry cdctypes.InterfaceRegistry) {
> 	registry.RegisterInterface(proto.MessageName((*DataBytes)(nil)), (*proto.Message)(nil), (*DataBytes)(nil))
> ```

Why do we need to register the DataBytes, but don't register other messages?
___
*[`x/asset/nft/types/msgs_test.go` line 60 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxu2YVE0l8E2iEFqVK:-NJxu2YW61pn2wVtP7GP:bt9tkra) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/x/asset/nft/types/msgs_test.go#L60)):*
> ```Go
> 			messageFunc: func() *types.MsgIssueClass {
> 				msg := validMessage
> 				msg.Data = &codectypes.Any{
> ```

In the integration test you use it that way: `codectypes.NewAnyWithValue`. The comment is related for all cases and tests in that file.
___
*[`x/asset/nft/types/nft.go` line 94 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxulRy4UDJZNSdBSRx:-NJxulRy4UDJZNSdBSRy:b3p63c6) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/x/asset/nft/types/nft.go#L94)):*
> ```Go
> 			return sdkerrors.Wrapf(ErrInvalidInput, "invalid data, it's allowed to use %d bytes", MaxDataSize)
> 		}
> 		if data.TypeUrl != "/"+proto.MessageName((*DataBytes)(nil)) {
> ```

Can we extract it differently using the "proto" functions?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 24 of 30 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: all files reviewed, 5 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 82 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxshezBLwLq3-EHQal:-NJym9Hq80YmF95Ppy8L:b-i9x71v) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/integration-tests/modules/assetnft_test.go#L82)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's use json data instead decoded to the bytes.
</blockquote></details>

what for?
___
*[`x/asset/nft/types/codec.go` line 11 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxtS7-8uVMiFExstbY:-NJymEhB6OxCIKckT-YL:b-oh93r2) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/x/asset/nft/types/codec.go#L11)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do we need to register the DataBytes, but don't register other messages?
</blockquote></details>

Because we don't decode `Any` to other types. When `Any` is decoded, object of type specified by `TypeUrl` is created that's why mapping from `TypeUrl` to real type must exist.
___
*[`x/asset/nft/types/msgs_test.go` line 60 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxu2YVE0l8E2iEFqVK:-NJymcQW9CEKc5787ywp:b8fw8a1) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/x/asset/nft/types/msgs_test.go#L60)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

In the integration test you use it that way: `codectypes.NewAnyWithValue`. The comment is related for all cases and tests in that file.
</blockquote></details>

Yes, but here I'm interested only in creating data of very specific particular length. So I do it explicitly.
___
*[`x/asset/nft/types/nft.go` line 94 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxulRy4UDJZNSdBSRx:-NJymseY5xX8DFq2P-HH:b-6qembz) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/x/asset/nft/types/nft.go#L94)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Can we extract it differently using the "proto" functions?
</blockquote></details>

I don't think so. This is exactly what ` codectypes.NewAnyWithValue` does internally



_Code quote (from integration-tests/modules/assetnft_test.go):_
```Go
 codectypes.NewAnyWithValue
```

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 82 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxshezBLwLq3-EHQal:-NJzFOBV9ci-AomI6Tqs:bilp9ie) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/integration-tests/modules/assetnft_test.go#L82)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what for?
</blockquote></details>

Since in the tests we try to keep the data more related to real scenarios. And also to be sure that you can read that data and decode to the initial firmat.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 24 of 30 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/modules/assetnft_test.go` line 61 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKENrbOBfz-Y3tmsKkD:-NKENrbOBfz-Y3tmsKkE:b-7k0ns8) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/integration-tests/modules/assetnft_test.go#L61)):*
> ```Go
> 	// issue new NFT class with too long data
> 
> 	data, err = codectypes.NewAnyWithValue(&assetnfttypes.DataBytes{Data: make([]byte, assetnfttypes.MaxDataSize+1)})
> ```

minor: 
I prefer to use bytes.Repeat instead:

`bytes.Repeat([]byte{0x01}, 10)`
___
*[`integration-tests/modules/assetnft_test.go` line 82 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxshezBLwLq3-EHQal:-NKEQmeOD87MD0LVjDR8:b-qa6uoo) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/integration-tests/modules/assetnft_test.go#L82)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Since in the tests we try to keep the data more related to real scenarios. And also to be sure that you can read that data and decode to the initial firmat.
</blockquote></details>

Agree with Dzmitry
___
*[`integration-tests/modules/assetnft_test.go` line 86 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKEcInH2HZ8uuiuuf3N:-NKEcInH2HZ8uuiuuf3O:bked6dn) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/integration-tests/modules/assetnft_test.go#L86)):*
> ```Go
> 
> 	// we need to do this, otherwise assertion fails because some private fields are set differently
> 	dataToCompare := &codectypes.Any{
> ```

any better option ?

I remember resolving these type of things by using https://github.com/google/go-cmp & defining custom comparer func 
___
*[`integration-tests/modules/assetnft_test.go` line 217 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxsr1_7W7EDkoGA9Xu:-NKES5cBDvC3Vc0_CqTS:b-7tdf7d) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/integration-tests/modules/assetnft_test.go#L217)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Same, thing. Let's use json data.
</blockquote></details>

agree
___
*[`proto/coreum/asset/nft/v1/tx.proto` line 42 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKEUdo_-9Iy5UedqmOp:-NKEUdo_-9Iy5UedqmOq:b-3ps3ic) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/proto/coreum/asset/nft/v1/tx.proto#L42)):*
> ```protobuf
> message EmptyResponse {}
> 
> message DataBytes {
> ```

is it a proper place for defining this proto ?

since it is not a Msg or Response
___
*[`x/asset/nft/types/msgs_test.go` line 31 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKEV1pu5Jbaw8LTHqc8:-NKEV1pu5Jbaw8LTHqc9:bvax3f0) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/x/asset/nft/types/msgs_test.go#L31)):*
> ```Go
> 	requireT := require.New(t)
> 
> 	dataString := "metadata"
> ```

minor:
I would also put some "realistic" json value here
We can even use embedding here and define it in a file
___
*[`x/asset/nft/types/msgs_test.go` line 62 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKEbb8LClODJcaAHPcf:-NKEbb8M8fnJrDPKxDsb:b-7k0ns8) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/x/asset/nft/types/msgs_test.go#L62)):*
> ```Go
> 				msg.Data = &codectypes.Any{
> 					TypeUrl: "/" + proto.MessageName((*types.DataBytes)(nil)),
> 					Value:   make([]byte, types.MaxDataSize),
> ```

minor: 
I prefer to use bytes.Repeat instead:

`bytes.Repeat([]byte{0x01}, 10)`
___
*[`x/asset/nft/types/nft.go` line 94 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKE_zfn9EBnCT-kFWhS:-NKE_zfoEErYDah9PxU1:b-dmwtdi) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/x/asset/nft/types/nft.go#L94)):*
> ```Go
> 			return sdkerrors.Wrapf(ErrInvalidInput, "invalid data, it's allowed to use %d bytes", MaxDataSize)
> 		}
> 		if data.TypeUrl != "/"+proto.MessageName((*DataBytes)(nil)) {
> ```

what if we add test like this ?

```
// Initialize with invalid type
data, err := codectypes.NewAnyWithValue(&types.MsgMint{})
// overwrite type to valid
data.TypeURL = "/"+proto.MessageName((*DataBytes)(nil))
```

I'm interested in the way it work internally. Does `data.Value` is a valid protobuf and contains it's type inside ?

Because I have feeling that we might need to validate `data.Value` somehow
___
*[`x/asset/nft/types/nft.go` line 95 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKEYSgcAYoeAQYeSr4E:-NKEYSgcAYoeAQYeSr4F:b-969ssn) ([raw file](https://github.com/coreumfoundation/coreum/blob/df183e20d79f2ab6d0380a21f9b4d4805a1aafb4/x/asset/nft/types/nft.go#L95)):*
> ```Go
> 		}
> 		if data.TypeUrl != "/"+proto.MessageName((*DataBytes)(nil)) {
> 			return sdkerrors.Wrap(ErrInvalidInput, "data field must contain NFTDataArray type")
> ```

outdated msg error `NFTDataArray`

I mostly prefer to not hardcode types in errors because of this

Here I propose to use `proto.MessageName((*DataBytes))` & it will return full proto path

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 86 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKEcInH2HZ8uuiuuf3N:-NKIhxv7B5Vj20VUjbYy:b-c4b1s5) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fe799ed6c4c9ed5014ce26c26eaabe29961494a/integration-tests/modules/assetnft_test.go#L86)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

any better option ?

I remember resolving these type of things by using https://github.com/google/go-cmp & defining custom comparer func 
</blockquote></details>

I don't think that adding some magic to fix this kind of simple case is needed
___
*[`proto/coreum/asset/nft/v1/tx.proto` line 42 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKEUdo_-9Iy5UedqmOp:-NKIijPr-goYXMaDK6Cm:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fe799ed6c4c9ed5014ce26c26eaabe29961494a/proto/coreum/asset/nft/v1/tx.proto#L42)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it a proper place for defining this proto ?

since it is not a Msg or Response
</blockquote></details>

Done.
___
*[`x/asset/nft/types/msgs_test.go` line 31 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKEV1pu5Jbaw8LTHqc8:-NKIjP0tCifGSjeZQXpL:big0opy) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fe799ed6c4c9ed5014ce26c26eaabe29961494a/x/asset/nft/types/msgs_test.go#L31)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
I would also put some "realistic" json value here
We can even use embedding here and define it in a file
</blockquote></details>

We can, but what for? We don't even have code in the test which tries to parse that json. This is a byte storage and we don't even require people to put json there. They may use any binary format they like.
___
*[`x/asset/nft/types/nft.go` line 95 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKEYSgcAYoeAQYeSr4E:-NKIkK_T0tMjsfklaf0O:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fe799ed6c4c9ed5014ce26c26eaabe29961494a/x/asset/nft/types/nft.go#L95)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

outdated msg error `NFTDataArray`

I mostly prefer to not hardcode types in errors because of this

Here I propose to use `proto.MessageName((*DataBytes))` & it will return full proto path

</blockquote></details>

Done.

**Review by ysv — COMMENTED** [review]
> Reviewed 7 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/assetnft_test.go` line 86 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKEcInH2HZ8uuiuuf3N:-NKIqSrb3qMquQr2pCe4:bm1mf36) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fe799ed6c4c9ed5014ce26c26eaabe29961494a/integration-tests/modules/assetnft_test.go#L86)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't think that adding some magic to fix this kind of simple case is needed
</blockquote></details>

also true
___
*[`x/asset/nft/types/msgs_test.go` line 31 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKEV1pu5Jbaw8LTHqc8:-NKIrPi-AHnaX4HDSzsV:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fe799ed6c4c9ed5014ce26c26eaabe29961494a/x/asset/nft/types/msgs_test.go#L31)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

We can, but what for? We don't even have code in the test which tries to parse that json. This is a byte storage and we don't even require people to put json there. They may use any binary format they like.
</blockquote></details>

ok

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 82 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxshezBLwLq3-EHQal:-NKItM158WgGjGjkzEpe:b3zyjpx) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fe799ed6c4c9ed5014ce26c26eaabe29961494a/integration-tests/modules/assetnft_test.go#L82)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Agree with Dzmitry
</blockquote></details>

My previous comment applies to everywhere where you requested adding real json
___
*[`x/asset/nft/types/nft.go` line 94 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKE_zfn9EBnCT-kFWhS:-NKIt7g09vetDFrihAEr:b-bdjlkw) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fe799ed6c4c9ed5014ce26c26eaabe29961494a/x/asset/nft/types/nft.go#L94)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what if we add test like this ?

```
// Initialize with invalid type
data, err := codectypes.NewAnyWithValue(&types.MsgMint{})
// overwrite type to valid
data.TypeURL = "/"+proto.MessageName((*DataBytes)(nil))
```

I'm interested in the way it work internally. Does `data.Value` is a valid protobuf and contains it's type inside ?

Because I have feeling that we might need to validate `data.Value` somehow
</blockquote></details>

Type is not encoded in the `Value` field. That's why `TypeURL` is required to know what to encode data to

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 82 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxshezBLwLq3-EHQal:-NKItnW8EqS5FXIkMs5f:b-q6j042) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fe799ed6c4c9ed5014ce26c26eaabe29961494a/integration-tests/modules/assetnft_test.go#L82)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

My previous comment applies to everywhere where you requested adding real json
</blockquote></details>

Could you refer me to it, I don't see it.

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 6 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 23 of 30 files at r1, 3 of 8 files at r2, 6 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: all files reviewed, 3 unresolved discussions (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: 32 of 33 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 82 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxshezBLwLq3-EHQal:-NKN228c0DM6WPu9WpSp:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fe799ed6c4c9ed5014ce26c26eaabe29961494a/integration-tests/modules/assetnft_test.go#L82)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Could you refer me to it, I don't see it.
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetnft_test.go` line 217 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NJxsr1_7W7EDkoGA9Xu:-NKN2NJYCQMBEMPAoLaR:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fe799ed6c4c9ed5014ce26c26eaabe29961494a/integration-tests/modules/assetnft_test.go#L217)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

agree
</blockquote></details>

Done.

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

___
*[`integration-tests/modules/assetnft_test.go` line 84 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKOkMx_AKvqU_S1EDpC:-NKOkMx_AKvqU_S1EDpD:bfz251c) ([raw file](https://github.com/coreumfoundation/coreum/blob/0567ac6874a7352c47e0785c49efec855986b163/integration-tests/modules/assetnft_test.go#L84)):*
> ```Go
> 	requireT.True(assetnfttypes.ErrInvalidInput.Is(err))
> 
> 	jsonData := struct {
> ```

I thought that you will just define it as bytes array and assert it as it is
```golang
jsonData := []byte(`{"name": "Name", "description": "Description"}`)

// ...
// and then assert
assertT.Equal(nftClassRes.Class.Data.Value, jsonData)
```
___
*[`x/asset/nft/types/nft.go` line 94 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKE_zfn9EBnCT-kFWhS:-NKOjUQX-SIA7jda-C8O:b-n4p6aj) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fe799ed6c4c9ed5014ce26c26eaabe29961494a/x/asset/nft/types/nft.go#L94)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Type is not encoded in the `Value` field. That's why `TypeURL` is required to know what to encode data to
</blockquote></details>

I see
I thought it works differently and Value there is valid protobuf which has type encoded inside
Or protobuf doesn't have type encoded inside ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: all files reviewed, 2 unresolved discussions (waiting on @silverspase and @ysv)

___
*[`integration-tests/modules/assetnft_test.go` line 84 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKOkMx_AKvqU_S1EDpC:-NKRkJzy39-r67fU1MYD:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/0567ac6874a7352c47e0785c49efec855986b163/integration-tests/modules/assetnft_test.go#L84)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I thought that you will just define it as bytes array and assert it as it is
```golang
jsonData := []byte(`{"name": "Name", "description": "Description"}`)

// ...
// and then assert
assertT.Equal(nftClassRes.Class.Data.Value, jsonData)
```
</blockquote></details>

Done.
___
*[`x/asset/nft/types/nft.go` line 94 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKE_zfn9EBnCT-kFWhS:-NKRiefk6nxwhl3efMEA:b-gzj19h) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fe799ed6c4c9ed5014ce26c26eaabe29961494a/x/asset/nft/types/nft.go#L94)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I see
I thought it works differently and Value there is valid protobuf which has type encoded inside
Or protobuf doesn't have type encoded inside ? 

</blockquote></details>

AFAIK protobuf never contains type of object: https://medium.com/nerd-for-tech/protobuf-what-why-fcb324a64564 (check "Protobuf Internals" section).

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

___
*[`x/asset/nft/types/nft.go` line 94 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/312#-NKE_zfn9EBnCT-kFWhS:-NKSyh2z29tSEFFExBCn:b-fyewyh) ([raw file](https://github.com/coreumfoundation/coreum/blob/0fe799ed6c4c9ed5014ce26c26eaabe29961494a/x/asset/nft/types/nft.go#L94)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

AFAIK protobuf never contains type of object: https://medium.com/nerd-for-tech/protobuf-what-why-fcb324a64564 (check "Protobuf Internals" section).
</blockquote></details>

I see okay than it is my mistake

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: 11 of 33 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 22 of 22 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/312)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase)

**Pull request merged**
