### PR TITLE
Support NFT data in CLI

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

By providing `--data-file [path-to-file]` flag, user is able to attach data to NFT and class.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/709)

### CODE REVIEW

**Review by ysv — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/709)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @miladz68)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/709)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`x/asset/nft/client/cli/query_test.go` line 134 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/709#-NirwQiCEMkxtrxE0OmV:-NirwQiCEMkxtrxE0OmW:bkpvqru) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a35418adab6e3ea22d343526660c1129cecd6981/x/asset/nft/client/cli/query_test.go#L134)):*
> ```Go
> 		fmt.Sprintf("--%s=%s", cli.URIFlag, uri),
> 		fmt.Sprintf("--%s=%s", cli.URIHashFlag, uriHash),
> 		fmt.Sprintf("--%s=%s", cli.DataFileFlag, dataFile),
> ```

Do you use that flag in tests ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/709)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

___
*[`x/asset/nft/client/cli/query_test.go` line 134 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/709#-NirwQiCEMkxtrxE0OmV:-Nis4SKSAr6DPfDmrmcv:b2vwrnp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/82ce7538b6d030f89072af6b0df81176394f5401/x/asset/nft/client/cli/query_test.go#L134)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you use that flag in tests ?
</blockquote></details>

Yes, I updated test in this PR

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/709)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
