### PR TITLE
FT module clean up.

### PR DESCRIPTION
**Pull request by dzmitryhil**
* renaming features to: minting, burning, whitelisting, freezing etc
* logically sort feature
* replace FT with the Token
* remove lines related to starport scaffolding
* structure the FT events to follow the same design
* merge multiple logically grouped files
* allow issuer ignore the freezing

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/344)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 53 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/344)* status: all files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLvc_dw4BIW2aivfqKy:-NLvc_dw4BIW2aivfqKz:bnft0kq) (no related file):*
Now I really like renaming of FT/ft to Token/token everywhere
I propose to finalize it in some other places also where it is a local variable:


___
___
*[`integration-tests/modules/assetft_test.go` line 25 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLwszNHALbPwAVbAExi:-NLwszNHALbPwAVbAExj:b-kr4l7v) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/integration-tests/modules/assetft_test.go#L25)):*
> ```Go
> 
> // TestAssetTokenIssue tests issue functionality of fungible tokens.
> func TestAssetTokenIssue(t *testing.T) {
> ```

the issue with this naming is that it could have conflicts with NFT module because there you can potentially have the same test name. But I don't like this FT acronym in names also
___
*[`x/asset/ft/keeper/keeper.go` line 54 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLvdqLm0X4hVa4y86aH:-NLvdqLm0X4hVa4y86aI:b-xfih7p) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/x/asset/ft/keeper/keeper.go#L54)):*
> ```Go
> 
> // Issue issues new fungible token and returns it's denom.
> func (k Keeper) Issue(ctx sdk.Context, settings types.IssueSettings) (string, error) {
> ```

why & when did we change it to return string but not Definition ?
___
*[`x/asset/ft/keeper/keeper.go` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLvda0j8Ivm7VCseqVe:-NLvda0j8Ivm7VCseqVf:b-1heca0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/x/asset/ft/keeper/keeper.go#L84)):*
> ```Go
> 	if params.IssueFee.IsPositive() {
> 		coinsToBurn := sdk.NewCoins(params.IssueFee)
> 		if err := k.bankKeeper.SendCoinsFromAccountToModule(ctx, settings.Issuer, types.ModuleName, coinsToBurn); err != nil {
> ```

minor:
we have 2 places like this where we sendCoinsFromAccToModule & then burn
Maybe it makes sense to mov it to a single func
___
*[`x/asset/ft/keeper/keeper.go` line 522 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLvlt-i02K3jOVglkUZ:-NLvlt-i02K3jOVglkU_:b438rht) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/x/asset/ft/keeper/keeper.go#L522)):*
> ```Go
> 	}
> 
> 	// the issuer can use token even if it's globally frozen
> ```

commet should be moved before first if
___
*[`x/asset/ft/keeper/keeper.go` line 554 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLvd26K3mnBl_1eztuu:-NLvd26K3mnBl_1eztuv:b-nqokzd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/x/asset/ft/keeper/keeper.go#L554)):*
> ```Go
> 	symbol = types.NormalizeSymbolForKey(symbol)
> 	compositeKey := types.CreateSymbolKey(issuer, symbol)
> 	bytes := ctx.KVStore(k.storeKey).Get(compositeKey)
> ```

bytes coludes with pkg name bytes
___
*[`x/asset/ft/keeper/keeper.go` line 643 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLvmBf3EGFs81fMDbj7:-NLvmBf3EGFs81fMDbj8:b-c95rwo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/x/asset/ft/keeper/keeper.go#L643)):*
> ```Go
> 
> func (k Keeper) getTokensByDefinitions(ctx sdk.Context, definitions []types.Definition) ([]types.Token, error) {
> 	var tokens []types.Token
> ```

since you know final length of slice you can preallocate it with `make`
___
*[`x/asset/ft/keeper/keeper.go` line 657 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLwsEMi4Mny5L84dZrV:-NLwsEMkC6mcU8L1c_6V:bl8kaje) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/x/asset/ft/keeper/keeper.go#L657)):*
> ```Go
> // frozenBalancesStore get the store for the frozen balances of all accounts
> func (k Keeper) frozenBalancesStore(ctx sdk.Context) prefix.Store {
> 	return prefix.NewStore(ctx.KVStore(k.storeKey), types.FrozenBalancesKeyPrefix)
> ```

minor:
I see you mix both approaches with assigning `store := ctx.KVStore(k.storeKey)` to a var and using it directly in return. I would stick to a single approach  everywhere (probably oneliner)
___
*[`x/asset/ft/keeper/keeper.go` line 678 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLva_nPAXH0Otc9XJh9:-NLva_nPAXH0Otc9XJhA:br2u21o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/x/asset/ft/keeper/keeper.go#L678)):*
> ```Go
> 
> // whitelistedBalancesStore get the store for the whitelisted balances of all accounts
> func (k Keeper) whitelistedBalancesStore(ctx sdk.Context) prefix.Store {
> ```

do we really need all 3 methods ?
- whitelistedBalancesStore
- whitelistedAccountBalanceStore
- whitelistedAccountBalancesStore
___
*[`x/wbank/keeper/keeper.go` line 42 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLvbON8-no1QKLeJRP3:-NLvbON8-no1QKLeJRP4:b-5sftsl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f5809647d3c871db8f0e89e9bebd106ac47a6e4d/x/wbank/keeper/keeper.go#L42)):*
> ```Go
> // !!! The code is the copy of the corresponding func of the bank module !!!
> func (k BaseKeeperWrapper) SendCoinsFromModuleToAccount(ctx sdk.Context, senderModule string, recipientAddr sdk.AccAddress, amt sdk.Coins) error {
> 	// TODO (dhil) revise all Send* functions after the FT implementation and decide that we need it or not
> ```

did you revise it ?

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 53 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/344)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`proto/coreum/asset/ft/v1/event.proto` line 12 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLygeZA8ntH1Ke21RUG:-NLygeZBA1afeS4pYHme:b-slik8a) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/proto/coreum/asset/ft/v1/event.proto#L12)):*
> ```protobuf
> 
> // EventIssued is emitted on MsgIssue.
> message EventIssued {
> ```

I actually think that EventTokenIssued is the better name, imagine seeing the event in the event logs as `Issued` which will naturally raise the question what is issued ? Since the events are without much context, then keeping the Token in the name is a good idea.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/344)* status: all files reviewed, 11 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLvc_dw4BIW2aivfqKy:-NLywfM9EHTQh61homU0:b-qu90y0) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Now I really like renaming of FT/ft to Token/token everywhere
I propose to finalize it in some other places also where it is a local variable:


</blockquote></details>

Agree,  updated.

___
___
*[`integration-tests/modules/assetft_test.go` line 25 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLwszNHALbPwAVbAExi:-NLyxDtl0AcA-WNzCLyC:b6p72lq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/integration-tests/modules/assetft_test.go#L25)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

the issue with this naming is that it could have conflicts with NFT module because there you can potentially have the same test name. But I don't like this FT acronym in names also
</blockquote></details>

Agree, update to `TestAssetToken`
___
*[`proto/coreum/asset/ft/v1/event.proto` line 12 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLygeZA8ntH1Ke21RUG:-NLyxGdq9Fr5rJy6ioo2:b-rf7x0w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/proto/coreum/asset/ft/v1/event.proto#L12)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I actually think that EventTokenIssued is the better name, imagine seeing the event in the event logs as `Issued` which will naturally raise the question what is issued ? Since the events are without much context, then keeping the Token in the name is a good idea. 
</blockquote></details>

But compare with other events, their names are without the `Token`. If we add it here we need to add it there as well.
___
*[`x/asset/ft/keeper/keeper.go` line 54 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLvdqLm0X4hVa4y86aH:-NLyxc1Z32UzraWtfXY5:bnu43oo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/x/asset/ft/keeper/keeper.go#L54)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

why & when did we change it to return string but not Definition ?
</blockquote></details>

I guess it was the initial version.
___
*[`x/asset/ft/keeper/keeper.go` line 84 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLvda0j8Ivm7VCseqVe:-NLyzhY7El2ThfGA_-uf:b-8ezbo2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/x/asset/ft/keeper/keeper.go#L84)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
we have 2 places like this where we sendCoinsFromAccToModule & then burn
Maybe it makes sense to mov it to a single func
</blockquote></details>

Agree, updated.



_Code quote:_
```Go
k.bankKeeper.SendCoinsFromAccountToModule
```
___
*[`x/asset/ft/keeper/keeper.go` line 522 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLvlt-i02K3jOVglkUZ:-NLyzmpR915a7-3dOtQV:b-89dqow) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/x/asset/ft/keeper/keeper.go#L522)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

commet should be moved before first if
</blockquote></details>

It should be removed. Removed.



_Code quote:_
```Go
// the issuer can use token even if it's globally frozen
```
___
*[`x/asset/ft/keeper/keeper.go` line 554 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLvd26K3mnBl_1eztuu:-NLz-lk8-QqxSruaDILw:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/x/asset/ft/keeper/keeper.go#L554)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

bytes coludes with pkg name bytes
</blockquote></details>

Updated.



_Code quote:_
```Go
	bytes := ctx.KVStore(k.storeKey).Get(compositeKey)
```
___
*[`x/asset/ft/keeper/keeper.go` line 643 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLvmBf3EGFs81fMDbj7:-NLz0P8d35V8izsjXchE:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/x/asset/ft/keeper/keeper.go#L643)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

since you know final length of slice you can preallocate it with `make`
</blockquote></details>

Done.



_Code quote:_
```Go
getTokensByDefinitions(ctx sdk.Context, defin
```
___
*[`x/asset/ft/keeper/keeper.go` line 657 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLwsEMi4Mny5L84dZrV:-NLz0b3fC7euj9WqceNO:bis0m37) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/x/asset/ft/keeper/keeper.go#L657)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor:
I see you mix both approaches with assigning `store := ctx.KVStore(k.storeKey)` to a var and using it directly in return. I would stick to a single approach  everywhere (probably oneliner)
</blockquote></details>

Agree. Done.



_Code quote:_
```Go
prefix.NewStore(
```
___
*[`x/asset/ft/keeper/keeper.go` line 678 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLva_nPAXH0Otc9XJh9:-NLz1_1H0D5dii1EZWDW:b-8wwwl9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0e25266f7369371a0788ef7a90b60add716730e0/x/asset/ft/keeper/keeper.go#L678)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we really need all 3 methods ?
- whitelistedBalancesStore
- whitelistedAccountBalanceStore
- whitelistedAccountBalancesStore
</blockquote></details>

We just need `whitelistedAccountBalanceStore`.  Other merged directly&
___
*[`x/wbank/keeper/keeper.go` line 42 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLvbON8-no1QKLeJRP3:-NLz2_FMDXsAxEQyGGgu:b-ftfud7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f5809647d3c871db8f0e89e9bebd106ac47a6e4d/x/wbank/keeper/keeper.go#L42)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

did you revise it ?
</blockquote></details>

IMO - Yes, with what we have now we should keep that override. 
Since we don't want to allow any othem module to ignore the bank wrapper. The only dout I had was the IBC but since it sin't included I feel comfortable with it.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/344)* status: all files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper_test.go` line 325 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLzHwIs83-WCBfFjN8W:-NLzHwIs83-WCBfFjN8X:bxcpi18) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cdea19a349de81bc3be7179ee30c9e94913ccd59/x/asset/ft/keeper/keeper_test.go#L325)):*
> ```Go
> 	requireT.Equal(types.BuildDenom(settings.Symbol, settings.Issuer), unmintableDenom)
> 
> 	// try to mintReceivable unmintable token
> ```

mintReceivable seems odd !
___
*[`x/asset/ft/keeper/keeper_test.go` line 419 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLzI15f3_QL4-sB9K9n:-NLzI15f3_QL4-sB9K9o:b-p3vf5l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cdea19a349de81bc3be7179ee30c9e94913ccd59/x/asset/ft/keeper/keeper_test.go#L419)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// try to burnSpendable as non-issuer
> ```

this one seems odd as well, what does burnSpendable mean ?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/344)* status: all files reviewed, 12 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper_test.go` line 325 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLzHwIs83-WCBfFjN8W:-NLzPFSe4cqDzsKPc_om:b-2372so) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cdea19a349de81bc3be7179ee30c9e94913ccd59/x/asset/ft/keeper/keeper_test.go#L325)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

mintReceivable seems odd !
</blockquote></details>

Very good catch, this is the IDE change on the refactoring, restored now.



_Code quote:_
```Go
// try to mintReceivable unmintable token
```
___
*[`x/asset/ft/keeper/keeper_test.go` line 419 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLzI15f3_QL4-sB9K9n:-NLzPLPjELxNxiVebC6p:b-2372so) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cdea19a349de81bc3be7179ee30c9e94913ccd59/x/asset/ft/keeper/keeper_test.go#L419)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this one seems odd as well, what does burnSpendable mean ?
</blockquote></details>

Very good catch, this is the IDE change on the refactoring, restored now.

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/344)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`x/asset/ft/keeper/keeper.go` line 495 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLz_8jV02PA_JVS6xTa:-NLz_8jW2InlQEw3O92i:bio6953) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9dec63469cc2b5a4a4bd684d428781b971bd4fae/x/asset/ft/keeper/keeper.go#L495)):*
> ```Go
> }
> 
> func (k Keeper) burnSpendable(ctx sdk.Context, account sdk.AccAddress, def types.Definition, amount sdk.Int) error {
> ```

the name is not 100% clear
maybe `burnIfSpendable` & `mintIfReceivable` which is not ideal also 

another option: If we can keep just `burn` & `mint` with whole logic inside would probably be better
___
*[`x/wbank/keeper/keeper.go` line 42 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLvbON8-no1QKLeJRP3:-NLza7Xd74PV4siX8QjX:bukl54i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f5809647d3c871db8f0e89e9bebd106ac47a6e4d/x/wbank/keeper/keeper.go#L42)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO - Yes, with what we have now we should keep that override. 
Since we don't want to allow any othem module to ignore the bank wrapper. The only dout I had was the IBC but since it sin't included I feel comfortable with it.
</blockquote></details>

ok
Added to review it once more on IBC integration

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/344)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 495 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/344#-NLz_8jV02PA_JVS6xTa:-NLzf7dS7l_VB7q5zTcK:b-zbgl19) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9dec63469cc2b5a4a4bd684d428781b971bd4fae/x/asset/ft/keeper/keeper.go#L495)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

the name is not 100% clear
maybe `burnIfSpendable` & `mintIfReceivable` which is not ideal also 

another option: If we can keep just `burn` & `mint` with whole logic inside would probably be better
</blockquote></details>

Make sence, updated. 
We can't keep since we have just `burn` and use it in 2 places.

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/344)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 46 of 53 files at r1, 3 of 6 files at r2, 1 of 3 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/344)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
