### PR TITLE
added overhead in gasprice query in cli

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/401)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/401)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`cmd/cored/cosmoscmd/gas_price.go` line 56 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/401#-NOUIM41ASbF1jzsAx3m:-NOUIM41ASbF1jzsAx3n:b4aoijk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9cc2361294579313b5777508634688678c25840d/cmd/cored/cosmoscmd/gas_price.go#L56)):*
> ```Go
> 	}
> 
> 	gasPriceWithOverHead := sdk.DecCoin{
> ```

minor: IMO overhead is a single word in this context so should be `gasPriceWithOverhead`
___
*[`cmd/cored/cosmoscmd/gas_price.go` line 60 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/401#-NOUJFL1-4lpyWrcRASm:-NOUJFL1-4lpyWrcRASn:bdlpxt1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9cc2361294579313b5777508634688678c25840d/cmd/cored/cosmoscmd/gas_price.go#L60)):*
> ```Go
> 		Amount: gasPrice.MinGasPrice.Amount.Mul(sdk.MustNewDecFromStr(defaultGasPriceMultiplier)),
> 	}
> 	return gasPriceFlag.Value.Set(gasPriceWithOverHead.String())
> ```

I understand new approach but can't get how it was implemented before

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/401)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`cmd/cored/cosmoscmd/gas_price.go` line 56 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/401#-NOUIM41ASbF1jzsAx3m:-NOi6o8C9Bz4f6Oao1Wu:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9cc2361294579313b5777508634688678c25840d/cmd/cored/cosmoscmd/gas_price.go#L56)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: IMO overhead is a single word in this context so should be `gasPriceWithOverhead`
</blockquote></details>

Done
___
*[`cmd/cored/cosmoscmd/gas_price.go` line 60 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/401#-NOUJFL1-4lpyWrcRASm:-NOi6ozq7lRxiUJS-BDi:b-1hz4q4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9cc2361294579313b5777508634688678c25840d/cmd/cored/cosmoscmd/gas_price.go#L60)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I understand new approach but can't get how it was implemented before 
</blockquote></details>

Discussed in the call.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/401)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/401)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Pull request merged**
