### PR TITLE
Test queries, multiple submessages and replies in smart contract

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/260)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/260)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/wasm/testdata/issue-fungible-token/src/contract.rs` line 69 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH-UXTXATOIiwBTR7DX:-NH-UXTXATOIiwBTR7DY:b-g1nyn4) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa105b569a46bbd4ff95c1a4af735d6752ed3249/integration-tests/wasm/testdata/issue-fungible-token/src/contract.rs#L69)):*
> ```XML
>     STATE.save(deps.storage, &state)?;
> 
>     let mut symbol1 = symbol.clone();
> ```

In general, it would be nice to have the contract commented on what is going of :-)
___
*[`integration-tests/wasm/testdata/issue-fungible-token/src/contract.rs` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH-XUWH8lwyJcR8t-aW:-NH-XUWH8lwyJcR8t-aX:b3pnxxu) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa105b569a46bbd4ff95c1a4af735d6752ed3249/integration-tests/wasm/testdata/issue-fungible-token/src/contract.rs#L75)):*
> ```XML
>     symbol2.push('2');
> 
>     let mut msg1 = SubMsg::new(sdk::FungibleTokenMsg::MsgIssueFungibleToken {
> ```

Who is the issuer contract or sender? If the sender we need to discuss how the contract can be the recipient. 
@ysv 
___
*[`integration-tests/wasm/testdata/issue-fungible-token/src/contract.rs` line 82 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH-Uq4OBV-TK6YXgS4z:-NH-Uq4OBV-TK6YXgS5-:b-4uowxa) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa105b569a46bbd4ff95c1a4af735d6752ed3249/integration-tests/wasm/testdata/issue-fungible-token/src/contract.rs#L82)):*
> ```XML
>     msg1.reply_on = ReplyOn::Always;
> 
>     let mut msg2 = SubMsg::new(sdk::FungibleTokenMsg::MsgIssueFungibleToken {
> ```

IMHO the better example is to issue an FT and send the initial amount to the TX sender (that will cover 2 txs logic). And have once more method "Send" which queries smth from the chain and then decides whether it's possible to do an action or now. 
In your query example, you provide a proxy only, so it's clear whether I can access the data or not in the execution. 
___
*[`x/asset/wasm/wasm.go` line 31 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH-WJT_0xdm0425-yOm:-NH-WJT_0xdm0425-yOn:bf7p50a) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa105b569a46bbd4ff95c1a4af735d6752ed3249/x/asset/wasm/wasm.go#L31)):*
> ```Go
> 
> // QueryHandler handles queries from smart contracts
> func QueryHandler(keeper keeper.Keeper) wasmtypes.Querier {
> ```

The query handler here is attached to the Keeper, but the keeper should be a dependency, similar like we do for the query service. 



_Code quote:_
```Go
QueryHandler(keeper keeper.Keeper)
```

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/260)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/260)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/wasm/testdata/issue-fungible-token/src/contract.rs` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH-XUWH8lwyJcR8t-aW:-NH4C66n5BQTV2L28KVh:bah208l) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa105b569a46bbd4ff95c1a4af735d6752ed3249/integration-tests/wasm/testdata/issue-fungible-token/src/contract.rs#L75)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Who is the issuer contract or sender? If the sender we need to discuss how the contract can be the recipient. 
@ysv 
</blockquote></details>

contract is the issuer
___
*[`integration-tests/wasm/testdata/issue-fungible-token/src/contract.rs` line 82 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH-Uq4OBV-TK6YXgS4z:-NH4CNb_2BapNs1rsKOd:b-av4xzi) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa105b569a46bbd4ff95c1a4af735d6752ed3249/integration-tests/wasm/testdata/issue-fungible-token/src/contract.rs#L82)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMHO the better example is to issue an FT and send the initial amount to the TX sender (that will cover 2 txs logic). And have once more method "Send" which queries smth from the chain and then decides whether it's possible to do an action or now. 
In your query example, you provide a proxy only, so it's clear whether I can access the data or not in the execution. 
</blockquote></details>

I wanted to test an u case where both messages are our custom actions.
Query is tested in another contract command.

**Review by miladz68 — DISMISSED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/260)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/260)* status: all files reviewed, 5 unresolved discussions (waiting on @wojtek-coreum)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH9cIpfB6Ag98IQkejr:-NH9cIpfB6Ag98IQkejs:by7uxh5) (no related file):*
Can we talk after a daily I need clarification for some parts

___
___
*[`integration-tests/wasm/testdata/issue-fungible-token/src/contract.rs` line 75 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH-XUWH8lwyJcR8t-aW:-NH9ZQe39mHSVfIbjLX-:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa105b569a46bbd4ff95c1a4af735d6752ed3249/integration-tests/wasm/testdata/issue-fungible-token/src/contract.rs#L75)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

contract is the issuer
</blockquote></details>

ok
___
*[`x/asset/wasm/wasm.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH9_3Hx4LD5qJPM0g1o:-NH9_3Hx4LD5qJPM0g1p:bqimsum) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa105b569a46bbd4ff95c1a4af735d6752ed3249/x/asset/wasm/wasm.go#L23)):*
> ```Go
> 				return nil, errors.WithStack(err)
> 			}
> 			msgIssueFungibleToken.Issuer = sender.String()
> ```

what is the purpose of this line ?
___
*[`x/asset/wasm/wasm.go` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH9_ODW1YZjXtUK5_Yh:-NH9_ODW1YZjXtUK5_Yi:bik28ek) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa105b569a46bbd4ff95c1a4af735d6752ed3249/x/asset/wasm/wasm.go#L52)):*
> ```Go
> 				}
> 				return raw, true, nil
> 			}
> ```

do we need to return error for other `qType` ?
is it ok to just ignore it ?

**Review by dzmitryhil — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/260)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/260)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH9cIpfB6Ag98IQkejr:-NHO8kHQ90kXg61jnlwj:b-896fix) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Can we talk after a daily I need clarification for some parts
</blockquote></details>

Done.

___
___
*[`x/asset/wasm/wasm.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH9_3Hx4LD5qJPM0g1o:-NHOB5Pe-NpLYMxLkJUx:bsifkoj) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa105b569a46bbd4ff95c1a4af735d6752ed3249/x/asset/wasm/wasm.go#L23)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what is the purpose of this line ?
</blockquote></details>

To set contract as an issuer of the token
___
*[`x/asset/wasm/wasm.go` line 31 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH-WJT_0xdm0425-yOm:-NHOBFbA5UlPeP_UXpCQ:b-jy224h) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa105b569a46bbd4ff95c1a4af735d6752ed3249/x/asset/wasm/wasm.go#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The query handler here is attached to the Keeper, but the keeper should be a dependency, similar like we do for the query service. 
</blockquote></details>

I don't think that keeper should be involved in the process of decoding the message received from the smart contract. We may discuss after the daily.
___
*[`x/asset/wasm/wasm.go` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH9_ODW1YZjXtUK5_Yh:-NHOBVFT4WV9Ip6W0O8-:bjjdtnn) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa105b569a46bbd4ff95c1a4af735d6752ed3249/x/asset/wasm/wasm.go#L52)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do we need to return error for other `qType` ?
is it ok to just ignore it ?
</blockquote></details>

Message might be handled by the other module. If this module does not handle the message `false` is returned. Later on, the global handle returns an error if nobody returned `true`.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/260)* status: all files reviewed, 3 unresolved discussions (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/260)* status: all files reviewed, 3 unresolved discussions (waiting on @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/260)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum)

___
*[`x/asset/wasm/wasm.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH9_3Hx4LD5qJPM0g1o:-NHP4sXD5mUuRMyBl9ql:bu8vao4) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa105b569a46bbd4ff95c1a4af735d6752ed3249/x/asset/wasm/wasm.go#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

To set contract as an issuer of the token
</blockquote></details>

I see
Because it wasn't actually obvious if sender here means tx sender (one who signed) or WASM contract address
Pls add this comment
___
*[`x/asset/wasm/wasm.go` line 52 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/260#-NH9_ODW1YZjXtUK5_Yh:-NHP52lq5nJ_-cB4RQL8:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/aa105b569a46bbd4ff95c1a4af735d6752ed3249/x/asset/wasm/wasm.go#L52)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Message might be handled by the other module. If this module does not handle the message `false` is returned. Later on, the global handle returns an error if nobody returned `true`.
</blockquote></details>

ok

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/260)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/260)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/260)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
