### PR TITLE
DEX tests with freeze / global freeze

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/966)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/966)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/966#-O78Z3CI9-OU053rwQtf:-O78Z3CI9-OU053rwQtg:b-e0y9nr) (no related file):*
Fix the title

___

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/966)* status: all files reviewed, 3 unresolved discussions (waiting on @masihyeganeh and @ysv)

___
*[`integration-tests/modules/dex_test.go` line 638 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/966#-O78ZvoL2o5k_Tgq5p12:-O78ZvoL2o5k_Tgq5p13:barf6t7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/62703b61a096368566ec441a143e00fb4408b056/integration-tests/modules/dex_test.go#L638)):*
> ```Go
> // TestLimitOrdersMatchingWithAssetFTFreeze tests the dex modules ability to place get and match limit orders
> // with asset ft with freezing.
> func TestLimitOrdersMatchingWithAssetFTFreeze(t *testing.T) {
> ```

It would be also nice to check the DEX locked amount at each step you do.
___
*[`integration-tests/modules/dex_test.go` line 758 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/966#-O78Zf9YCbg9fs4x5yBz:-O78Zf9Z0YjybTRBtVjA:b2cve2c) ([raw file](https://github.com/CoreumFoundation/coreum/blob/62703b61a096368566ec441a143e00fb4408b056/integration-tests/modules/dex_test.go#L758)):*
> ```Go
> 	)
> 	requireT.NoError(err)
> 	// validate the deterministic gas
> ```

You don't need to check it in your test (for all cases)

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/966)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/966#-O78Z3CI9-OU053rwQtf:-O78jnQl06vmSC0No7l3:b-896fix) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Fix the title
</blockquote></details>

Done.

___
___
*[`integration-tests/modules/dex_test.go` line 638 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/966#-O78ZvoL2o5k_Tgq5p12:-O78jmWJDYqZ5r7AZoeo:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/62703b61a096368566ec441a143e00fb4408b056/integration-tests/modules/dex_test.go#L638)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It would be also nice to check the DEX locked amount at each step you do.
</blockquote></details>

Done.
___
*[`integration-tests/modules/dex_test.go` line 758 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/966#-O78Zf9YCbg9fs4x5yBz:-O78dK6o28_NDQH-et5S:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/62703b61a096368566ec441a143e00fb4408b056/integration-tests/modules/dex_test.go#L758)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You don't need to check it in your test (for all cases)
</blockquote></details>

Done.

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/966)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/966)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/966)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/966)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
