### PR TITLE
Bump coreum to `v4`

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/723)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 196 of 205 files at r1, 37 of 37 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/723)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/upgrade/nft_migration_test.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/723#-NkFhYRDBotOPOKQsl3H:-NkFhYRDBotOPOKQsl3I:b-oe8zhi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9a7703d6a0aa3d2011152c10adb196c33075e236/integration-tests/upgrade/nft_migration_test.go#L1)):*
> ```Go
> //go:build integrationtests
> ```

have you migrated all upgrade/* tests to modules ?
Or just removed

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/723)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/723)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

___
*[`integration-tests/upgrade/nft_migration_test.go` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/723#-NkFhYRDBotOPOKQsl3H:-NkFvS-N7ok6wEczO5xm:b-a47wqg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9a7703d6a0aa3d2011152c10adb196c33075e236/integration-tests/upgrade/nft_migration_test.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

have you migrated all upgrade/* tests to modules ?
Or just removed
</blockquote></details>

Just removed because there were no tests worth moving - they were about checking compatibility after upgrading ibc, wasm, etc.

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/723)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
