### PR TITLE
Added docker layers caching in CI

### PR DESCRIPTION
**Pull request by begmaroman**
Reduced CI duration from 16 mins to 9 mins.

This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/186)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/186)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/ci.yml` line 44 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/186#-NCQ3vfvAlFatJWCJOmG:-NCQ3vfvAlFatJWCJOmH:b-s6jhyg) ([raw file](https://github.com/coreumfoundation/coreum/blob/53d7ba14d83e4fc44fff25b767be5002e0744a53/.github/workflows/ci.yml#L44)):*
> ```YAML
>       - name: Lint, run unit tests and build
>         run: |
>           mkdir -p ~/.cache/docker
> ```

is (un)taring worth the benefits?

**Review by begmaroman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/186)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 44 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/186#-NCQ3vfvAlFatJWCJOmG:-NCQYu0z2l3q-vLU3oHp:b-aehkzy) ([raw file](https://github.com/coreumfoundation/coreum/blob/53d7ba14d83e4fc44fff25b767be5002e0744a53/.github/workflows/ci.yml#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

is (un)taring worth the benefits?
</blockquote></details>

It does not build the image again and again anymore

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/186)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/ci.yml` line 44 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/186#-NCQ3vfvAlFatJWCJOmG:-NCU1-YKCbFTFY5lRfe-:buef96t) ([raw file](https://github.com/coreumfoundation/coreum/blob/53d7ba14d83e4fc44fff25b767be5002e0744a53/.github/workflows/ci.yml#L44)):*
<details><summary><i>Previously, begmaroman (Roman Behma) wrote…</i></summary><blockquote>

It does not build the image again and again anymore 
</blockquote></details>

but it tars and untars it again and again. We have only 2 cpus there. Did you check that it's faster than downloading the image?

**Review by begmaroman — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/186)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 44 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/186#-NCQ3vfvAlFatJWCJOmG:-NCUHShV7P0n8_FU-TLT:b2wgp0x) ([raw file](https://github.com/coreumfoundation/coreum/blob/53d7ba14d83e4fc44fff25b767be5002e0744a53/.github/workflows/ci.yml#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but it tars and untars it again and again. We have only 2 cpus there. Did you check that it's faster than downloading the image?
</blockquote></details>

Added third-party action for docker caching, it works better tho

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/ci.yml` line 44 at r4](https://reviewable.io/reviews/coreumfoundation/coreum/186#-NCQ3vfvAlFatJWCJOmG:-NCUVQfS0OB1EDX0Jcpv:b-3qwmhi) ([raw file](https://github.com/coreumfoundation/coreum/blob/53d7ba14d83e4fc44fff25b767be5002e0744a53/.github/workflows/ci.yml#L44)):*
<details><summary><i>Previously, begmaroman (Roman Behma) wrote…</i></summary><blockquote>

Added third-party action for docker caching, it works better tho 
</blockquote></details>

But it still tars and untars images under the hood. Anyway, I'm approving it - we will see how it works

**Review by dzmitryhil — APPROVED** [review]

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
