### PR TITLE
Integrate IBC burn rate and send commission.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/489)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/489)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`app/app.go` line 342 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/489#-NVZSx4B7zErQHdg68e_:-NVZSx4B7zErQHdg68ea:b-tke0zj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/76ea727f4d6d8ae2322f9b15b0b19cdae1b92700/app/app.go#L342)):*
> ```Go
> 	originalBankKeeper := bankkeeper.NewBaseKeeper(appCodec, keys[banktypes.StoreKey], app.AccountKeeper, app.GetSubspace(banktypes.ModuleName), app.ModuleAccountAddrs())
> 	var ibcChannelKeeper ibcchannelkeeper.Keeper
> 	assetFTKeeper := assetftkeeper.NewKeeper(
> ```

can't it be done after initializing ibc keeper to avoid the trick with pointer to predclared `ibcChannelKeeper`?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/489)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 342 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/489#-NVZSx4B7zErQHdg68e_:-NVZdNnz94I_ycqRBBWL:b-io4xis) ([raw file](https://github.com/CoreumFoundation/coreum/blob/76ea727f4d6d8ae2322f9b15b0b19cdae1b92700/app/app.go#L342)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

can't it be done after initializing ibc keeper to avoid the trick with pointer to predclared `ibcChannelKeeper`?
</blockquote></details>

Nope. The IBC keeper uses the staking keeper in the `New` function and checks whether it's nill, and the bank module is used in the staking keeper. So I've not found a better approach.

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/489#-:-NV_3afBEOb-phxPrjnq:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 83 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/489#-NV_2sn-6nnQ5scDlIew:-NV_2sn-6nnQ5scDlIex:bhnj9z1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d6184e2139895c407826f2805c33cb538f72fb64/.github/workflows/ci.yml#L83)):*
> ```YAML
>           repository: CoreumFoundation/crust
>           path: crust
>           ref: dzmitryhil/add-osmosis-testing-flags # FIXME remove once merged
> ```

you can define the flags here, and use the correct default values to pass the tests.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/489)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 83 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/489#-NV_2sn-6nnQ5scDlIew:-NVcVijVA3x0yZlhvPry:b-ra4ym0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d6184e2139895c407826f2805c33cb538f72fb64/.github/workflows/ci.yml#L83)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you can define the flags here, and use the correct default values to pass the tests. 
</blockquote></details>

I wanted to be sure the with the new flags wich the crust intoduces it will pass.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/489)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 83 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/489#-NV_2sn-6nnQ5scDlIew:-NVcWC0e6OBeovXpvTmb:b-glba0n) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d6184e2139895c407826f2805c33cb538f72fb64/.github/workflows/ci.yml#L83)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I wanted to be sure the with the new flags wich the crust intoduces it will pass.
</blockquote></details>

well now that you do, you can remove the branch name right ? there is not need to merge it into master with a `FIXME`

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/489)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/ci.yml` line 83 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/489#-NV_2sn-6nnQ5scDlIew:-NVcWlp188MHD3sCo-gl:b-fznz3t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d6184e2139895c407826f2805c33cb538f72fb64/.github/workflows/ci.yml#L83)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

well now that you do, you can remove the branch name right ? there is not need to merge it into master with a `FIXME` 
</blockquote></details>

The osmosis IBC on the crust master doesn't work so that branch also contains the changes to fix it.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/489)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
