### PR TITLE
Don't burn and send commission with zero amount.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

The PR contains changes to prevent the burning and sending of the token commission with zero amount. Without it , the bank module produces `send/receive` events without `amount`. 

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/711)

### CODE REVIEW

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/711)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/711)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

___
*[`x/asset/ft/keeper/before_send.go` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/711#-Nitup8u-NU3SlGQQRNO:-Nitup8u-NU3SlGQQRNP:b8flvje) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3973564667b8b5247951cf864358ba6c74d54933/x/asset/ft/keeper/before_send.go#L86)):*
> ```Go
> 
> 		burnAmount := k.ApplyRate(ctx, def.BurnRate, issuer, sender, outOps)
> 		if burnAmount.IsPositive() {
> ```

I would say that these checks should be done inside `k.burnIfSpendable` & `SendCoins`
WDYT ?

Because we might call it with 0 from another places

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/711)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/before_send.go` line 86 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/711#-Nitup8u-NU3SlGQQRNO:-Nj66UJ584BVFeWJXHqF:bn7mpms) ([raw file](https://github.com/CoreumFoundation/coreum/blob/3973564667b8b5247951cf864358ba6c74d54933/x/asset/ft/keeper/before_send.go#L86)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would say that these checks should be done inside `k.burnIfSpendable` & `SendCoins`
WDYT ?

Because we might call it with 0 from another places
</blockquote></details>

Updated ``burnIfSpendable``.

The `SendCoins` is a method os an interface, what I can do is creating a new method `sendCoins` and call it there. 
Done.

**Review by ysv — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/711)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/711)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @miladz68)

___
*[`x/asset/ft/keeper/keeper.go` line 664 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/711#-Nj7U1lH2I3zWUhPxcnB:-Nj7U1lI-Yh9NmXCXgqQ:b-i7u6q1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c88fddd61da38469b7fdd5605d4be4e107591055/x/asset/ft/keeper/keeper.go#L664)):*
> ```Go
> }
> 
> func (k Keeper) sendCoins(ctx sdk.Context, fromAddr, toAddr sdk.AccAddress, amount sdk.Coins) error {
> ```

sendCoins -> sendCommission
___
*[`x/asset/ft/keeper/keeper.go` line 664 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/711#-Nj7U7mjADAXUaqUjdPP:-Nj7U7mjADAXUaqUjdPQ:b-vwuc13) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c88fddd61da38469b7fdd5605d4be4e107591055/x/asset/ft/keeper/keeper.go#L664)):*
> ```Go
> }
> 
> func (k Keeper) sendCoins(ctx sdk.Context, fromAddr, toAddr sdk.AccAddress, amount sdk.Coins) error {
> ```

I think amount should be `sdk.Coin` because it is expected to receive one coin only.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/711)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`x/asset/ft/keeper/keeper.go` line 664 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/711#-Nj7U1lH2I3zWUhPxcnB:-Nj7gQBZ1jPg1hOCN1De:b-xvn9n9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c88fddd61da38469b7fdd5605d4be4e107591055/x/asset/ft/keeper/keeper.go#L664)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

sendCoins -> sendCommission
</blockquote></details>

But this is not commission sending, this is sending coins in general.
___
*[`x/asset/ft/keeper/keeper.go` line 664 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/711#-Nj7U7mjADAXUaqUjdPP:-Nj7gVSg8b6p34S8Isc9:b7xt2o6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c88fddd61da38469b7fdd5605d4be4e107591055/x/asset/ft/keeper/keeper.go#L664)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I think amount should be `sdk.Coin` because it is expected to receive one coin only.
</blockquote></details>

Actually this is the private func to wrap SendCoins but check amounts to be not equal zero.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/711)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil and @miladz68)

___
*[`x/asset/ft/keeper/keeper.go` line 664 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/711#-Nj7U1lH2I3zWUhPxcnB:-Nj7jayhD0iglaAgjaFZ:br7bihw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c88fddd61da38469b7fdd5605d4be4e107591055/x/asset/ft/keeper/keeper.go#L664)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But this is not commission sending, this is sending coins in general.
</blockquote></details>

You added this function in this PR and it is used only to send commission

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/711)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @wojtek-coreum)

___
*[`x/asset/ft/keeper/keeper.go` line 664 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/711#-Nj7U1lH2I3zWUhPxcnB:-Nj7tgMb8lPt6JFo1J2r:bqwngds) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c88fddd61da38469b7fdd5605d4be4e107591055/x/asset/ft/keeper/keeper.go#L664)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You added this function in this PR and it is used only to send commission
</blockquote></details>

Reverted the commit.
___
*[`x/asset/ft/keeper/keeper.go` line 664 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/711#-Nj7U7mjADAXUaqUjdPP:-Nj7thtkCiFQUCKHqeWV:bqwngds) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c88fddd61da38469b7fdd5605d4be4e107591055/x/asset/ft/keeper/keeper.go#L664)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually this is the private func to wrap SendCoins but check amounts to be not equal zero.
</blockquote></details>

Reverted the commit.

**Review by wojtek-coreum — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/711)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/711)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/711)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/711)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
