### PR TITLE
Migrate CI to use `coreum-builder`

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

- download go dependencies
- revert to building required components only
- support `--help` command for builder

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798)

### CODE REVIEW

**Review by ysv — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @masihyeganeh, and @miladz68)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @masihyeganeh, and @miladz68)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @miladz68)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @wojtek-coreum)

___
*[`.github/workflows/ci.yml` line 36 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/798#-NuhiRvu-YAIJy21UJRc:-NuhiRvu-YAIJy21UJRd:bjon6lt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b4b3686272a79c020942a752a2da1ea697346984/.github/workflows/ci.yml#L36)):*
> ```YAML
>           - ci_step: "integration tests coreum-modules"
>             command: |
>               coreum-builder build/integration-tests/modules build images
> ```

It was decided to merge all build related steps into a separate step. You should merge all these build commands there

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`.github/workflows/ci.yml` line 36 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/798#-NuhiRvu-YAIJy21UJRc:-Nui-5RX1_TXyYkOsFJb:b-cu2nhf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b4b3686272a79c020942a752a2da1ea697346984/.github/workflows/ci.yml#L36)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It was decided to merge all build related steps into a separate step. You should merge all these build commands there
</blockquote></details>

Now, dependencies are downloaded before building, so cache will be fine

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @wojtek-coreum)

___
*[`.github/workflows/ci.yml` line 36 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/798#-NuhiRvu-YAIJy21UJRc:-NuibQtX80uKHi4TgJLm:bf6xee7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b4b3686272a79c020942a752a2da1ea697346984/.github/workflows/ci.yml#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Now, dependencies are downloaded before building, so cache will be fine
</blockquote></details>

was this discussed in the team ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @miladz68)

___
*[`.github/workflows/ci.yml` line 36 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/798#-NuhiRvu-YAIJy21UJRc:-Nv0W0n83d8n4pLQo9et:b-b9zmqn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b4b3686272a79c020942a752a2da1ea697346984/.github/workflows/ci.yml#L36)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

was this discussed in the team ?
</blockquote></details>

yes, while you was on vacation. We may do it again if you want to

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

___
*[`.github/workflows/ci.yml` line 36 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/798#-NuhiRvu-YAIJy21UJRc:-Nv0ue3p3MQfDWIb-Kl0:bdyflrp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b4b3686272a79c020942a752a2da1ea697346984/.github/workflows/ci.yml#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

yes, while you was on vacation. We may do it again if you want to
</blockquote></details>

No need. Approved.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

**Review by keyleu — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798)* status: 6 of 9 files reviewed, all discussions resolved (waiting on @keyleu and @masihyeganeh)

**Review by ysv — COMMENTED** [review]
> Reviewed 5 of 7 files at r8, 1 of 2 files at r9, 5 of 5 files at r12.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @keyleu and @masihyeganeh)

**Review by dzmitryhil — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798#-:-Nv_Q8Uo1wZrAlcJX56a:bnfp4nl)* status: 10 of 12 files reviewed, all discussions resolved (waiting on @keyleu, @masihyeganeh, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 5 of 7 files at r8, 1 of 2 files at r9, 3 of 5 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/798)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @keyleu and @masihyeganeh)

**Pull request merged**
