### PR TITLE
Set block size to 6MB

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/880)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/880)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/consensus_test.go` line 19 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/880#-O-L3fT29Is6eRSa1nu2:-O-L3fT3EXtRnFaSW1_J:b-25f6jz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/85ff7b60e73714c474803b9e6a930d5ee0ffa4a5/integration-tests/modules/consensus_test.go#L19)):*
> ```Go
> )
> 
> func TestUpdatingMaxBlockSize(t *testing.T) {
> ```

Is the test is test just to check that gov works, and it is not related to the upgrade?
___
*[`integration-tests/upgrade/max_block_size_test.go` line 28 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/880#-O-L43Fk5Nujnh7dcZV0:-O-L43Fk5Nujnh7dcZV1:b3ksv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/85ff7b60e73714c474803b9e6a930d5ee0ffa4a5/integration-tests/upgrade/max_block_size_test.go#L28)):*
> ```Go
> 	requireT.EqualValues(22_020_096, consensusParams.Params.Block.MaxBytes)
> 	mbst.params = consensusParams.Params
> 	mbst.params.Block.MaxBytes = 6_291_456
> ```

t
___
*[`pkg/config/genesis/genesis.v3.tmpl.json` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/880#-O-L3Q139MNCoJm2iZq4:-O-L3Q139MNCoJm2iZq5:bvxuerc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/85ff7b60e73714c474803b9e6a930d5ee0ffa4a5/pkg/config/genesis/genesis.v3.tmpl.json#L1)):*
> ```JSON
> {
> ```

The file iscalled v3 tmpl, but it is v4, right?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/880)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`integration-tests/modules/consensus_test.go` line 19 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/880#-O-L3fT29Is6eRSa1nu2:-O-L4ziW1T7pqZCU79Fu:b-ne7cth) ([raw file](https://github.com/CoreumFoundation/coreum/blob/85ff7b60e73714c474803b9e6a930d5ee0ffa4a5/integration-tests/modules/consensus_test.go#L19)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Is the test is test just to check that gov works, and it is not related to the upgrade?
</blockquote></details>

Initially I thought that we will update the block size using a separate the governance proposal. That's why I added a test.
___
*[`integration-tests/upgrade/max_block_size_test.go` line 28 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/880#-O-L4r1LB09Wn5ETovni:-O-L5RCT3WbEDLpRHzSM:b-b11c8j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/85ff7b60e73714c474803b9e6a930d5ee0ffa4a5/integration-tests/upgrade/max_block_size_test.go#L28)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

you don't need to store `6_291_456` inside a variable it can be a const inside `After` method.
</blockquote></details>

I need other params anyway to update the entire set. I may query again in the `After` but it's already here
___
*[`integration-tests/upgrade/max_block_size_test.go` line 28 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/880#-O-L43Fk5Nujnh7dcZV0:-O-L5aYj021Jiu2YZisI:b3kre) ([raw file](https://github.com/CoreumFoundation/coreum/blob/85ff7b60e73714c474803b9e6a930d5ee0ffa4a5/integration-tests/upgrade/max_block_size_test.go#L28)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

t
</blockquote></details>

?
___
*[`pkg/config/genesis/genesis.v3.tmpl.json` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/880#-O-L3Q139MNCoJm2iZq4:-O-L5iL8Ef3UyRWKaPUH:bghlaz1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/85ff7b60e73714c474803b9e6a930d5ee0ffa4a5/pkg/config/genesis/genesis.v3.tmpl.json#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

We no longer need to change templates.
</blockquote></details>

 modified this file accidentally, then reverted

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/880)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`pkg/config/genesis/genesis.v3.tmpl.json` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/880#-O-L3Q139MNCoJm2iZq4:-O-L5x-f4014IT-P6sMF:b-n4ifm8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9697bdaddbd4b40d16a1336cffcb64ed26f6affe/pkg/config/genesis/genesis.v3.tmpl.json#L1)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

modified this file accidentally, then reverted
</blockquote></details>

So we need rename the to genesis.tmpl.json

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/880)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/upgrade/max_block_size_test.go` line 28 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/880#-O-L4r1LB09Wn5ETovni:-O-L67IJCDrmldwDM3su:b-wtrunv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9697bdaddbd4b40d16a1336cffcb64ed26f6affe/integration-tests/upgrade/max_block_size_test.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I need other params anyway to update the entire set. I may query again in the `After` but it's already here
</blockquote></details>

So you need to store the prev state, and in after check current with updated arg, now it look not dev-friendly :-)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/880)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`integration-tests/upgrade/max_block_size_test.go` line 28 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/880#-O-L4r1LB09Wn5ETovni:-O-L6isSDU4Pdms1cCfj:brjnr4h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9697bdaddbd4b40d16a1336cffcb64ed26f6affe/integration-tests/upgrade/max_block_size_test.go#L28)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

So you need to store the prev state, and in after check current with updated arg, now it look not dev-friendly :-)
</blockquote></details>

but you do query for the param in `After` anyways. you are just holding `6_291_456` in a variable inside Before, only  to compare it in the `After` function. 
___
*[`pkg/config/genesis/genesis.v3.tmpl.json` line 1 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/880#-O-L3Q139MNCoJm2iZq4:-O-L7QlBAm5LbjJBOLah:b-r6a4kh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9697bdaddbd4b40d16a1336cffcb64ed26f6affe/pkg/config/genesis/genesis.v3.tmpl.json#L1)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

So we need rename the to genesis.tmpl.json
</blockquote></details>

Resolved on my side.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/880)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @ysv)

___
*[`integration-tests/upgrade/max_block_size_test.go` line 28 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/880#-O-L4r1LB09Wn5ETovni:-O-L8SX39L4O50eNiEkR:b-50m3gr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9697bdaddbd4b40d16a1336cffcb64ed26f6affe/integration-tests/upgrade/max_block_size_test.go#L28)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

but you do query for the param in `After` anyways. you are just holding `6_291_456` in a variable inside Before, only  to compare it in the `After` function.
</blockquote></details>

I store all the params inside `Before` to verify that none of the other params has been changed during the upgrade.

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/880)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`integration-tests/upgrade/max_block_size_test.go` line 28 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/880#-O-L4r1LB09Wn5ETovni:-O-LI62m80NmEC0u-X7n:btn5jp1) ([raw file](https://github.com/CoreumFoundation/coreum/blob/30c462774d3d6a5ce0ccb896d804995b01d6239d/integration-tests/upgrade/max_block_size_test.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I store all the params inside `Before` to verify that none of the other params has been changed during the upgrade.
</blockquote></details>

Gotcha

**Review by masihyeganeh — DISMISSED** [review]
> Reviewed 2 of 4 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/880)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 2 of 4 files at r1, 5 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/880)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/880)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/880)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/880)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
