### PR TITLE
Describe DEX price tick and precision

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Describe DEX price tick and precision

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/891)

### CODE REVIEW

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/891)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/891)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/dex/spec/price.md` line 6 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/891#-O-kJzyk01b70DHdOtcB:-O-kJzyk01b70DHdOtcC:b-wikpe9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65d66ace859154581cc9740f14aa4d303d36cb8a/x/dex/spec/price.md#L6)):*
> ```Markdown
> each pair. The `price_tick` mostly depends on the price of the assets traded, that's why we can define the variable for
> a token used to define the pair `price_tick`. This variable is named `unified_ref_price`. `unified_ref_price` for token
> represents the amount of the token subunit you need to pay to buy 1 USD dollar. If the token is issued on the Coreum
> ```

1 USD dollar, or 1 USD cent?



_Code quote:_
```Markdown
1 USD dollar
```

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/891)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/dex/spec/price.md` line 6 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/891#-O-kJzyk01b70DHdOtcB:-O-kMQmU3RSm81UU7dzA:b-uks7sm) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65d66ace859154581cc9740f14aa4d303d36cb8a/x/dex/spec/price.md#L6)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

1 USD dollar, or 1 USD cent?
</blockquote></details>

1 USD dollar

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/891)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/dex/spec/price.md` line 6 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/891#-O-kJzyk01b70DHdOtcB:-O-kMSUyDOV1El0wnpCI:bkpcdr9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65d66ace859154581cc9740f14aa4d303d36cb8a/x/dex/spec/price.md#L6)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

1 USD dollar
</blockquote></details>

But actually, any value will work. If all coins have the same reference.

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/891)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/dex/spec/price.md` line 6 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/891#-O-kJzyk01b70DHdOtcB:-O-kvPG791TWoMjvIxIS:br4nr82) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65d66ace859154581cc9740f14aa4d303d36cb8a/x/dex/spec/price.md#L6)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But actually, any value will work. If all coins have the same reference.
</blockquote></details>

Sure. I'm just suggesting to not introduce a new concept if we already have one before. The definition of `unified_ref_price` and `significant_amount` are very much like each other. Try to reuse one if possible

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/891)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/dex/spec/price.md` line 9 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/891#-O-oLVdZ4xMIlRUaM1i4:-O-oLVd_E05IaYg9ygFq:b-781cpg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65d66ace859154581cc9740f14aa4d303d36cb8a/x/dex/spec/price.md#L9)):*
> ```Markdown
> chain, that variable can be set/updated by the token admin. If the token is IBC token, or the token doesn't have and
> admin this variable can be set/updated by the chain governance. If the `unified_ref_price` is not set for a token, the
> `unified_ref_price` is equal to 1. 
> ```

I think 1 is a bad default 10^6 would be better as most of the tokens use that precision

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/891)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/891)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`x/dex/spec/price.md` line 6 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/891#-O-kJzyk01b70DHdOtcB:-O-pGwtf28kS2kNtqMAQ:benigbt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65d66ace859154581cc9740f14aa4d303d36cb8a/x/dex/spec/price.md#L6)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Sure. I'm just suggesting to not introduce a new concept if we already have one before. The definition of `unified_ref_price` and `significant_amount` are very much like each other. Try to reuse one if possible
</blockquote></details>

`unified_ref_price` is better name IMO.
___
*[`x/dex/spec/price.md` line 9 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/891#-O-oLVdZ4xMIlRUaM1i4:-O-pH1O33mA_rSTN07k-:bvwtlob) ([raw file](https://github.com/CoreumFoundation/coreum/blob/65d66ace859154581cc9740f14aa4d303d36cb8a/x/dex/spec/price.md#L9)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I think 1 is a bad default 10^6 would be better as most of the tokens use that precision
</blockquote></details>

Actually, we don't know since it's different from the precision always.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/891)* status: all files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`x/dex/spec/price.md` line 9 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/891#-O-oLVdZ4xMIlRUaM1i4:-O-tXCOpA2p_t0DzidPo:b-bw8e14) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4bec9af68f47659b598a2f03e00cfed06ba3e2c1/x/dex/spec/price.md#L9)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually, we don't know since it's different from the precision always.
</blockquote></details>

Updated.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/891)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh, @miladz68, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/891)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

**Pull request merged**
