### PR TITLE
Rearrange integration tests to return required prefunded accounts directly, not through callback

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This PR is removing hacks required by integration test framework during the transition period:

```go
// FIXME (wojtek): Temporary code for transition
if chain.Fund != nil {
    chain.Fund(wallet, initialBalance)
}
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/146)

### CODE REVIEW

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/146)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/146)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/146)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`integration-tests/auth/gas.go` line 33 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/146#-NAcxxC3Ba68bY_OKR-M:-NAcxxC3Ba68bY_OKR-N:b9pt96v) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b30caad65e52d1703c03da769a84281e7bd2ae7/integration-tests/auth/gas.go#L33)):*
> ```Go
> 	}
> 
> 	return testing.Prerequisites{
> ```

This model with the "testing.Prerequisites" seems overcomplicated taken in account today's state. At the moment of the text execution we have a function to fund any account in the runtime, so we don't need to add and addition code to do it before, meas the entire "Prerequisites" are redundant now. Each test can just call the Fund function at the start of the test. 
___
*[`integration-tests/auth/gas.go` line 178 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/146#-NAcylDT43BnjBeq8Sev:-NAcylDU44OSjIUbDSYc:b-vsegd7) ([raw file](https://github.com/coreumfoundation/coreum/blob/9b30caad65e52d1703c03da769a84281e7bd2ae7/integration-tests/auth/gas.go#L178)):*
> ```Go
> 					Signer:   sender,
> 					GasLimit: uint64(chain.NetworkConfig.Fee.FeeModel.MaxBlockGas),
> 					GasPrice: types.Coin{Amount: chain.NetworkConfig.Fee.FeeModel.InitialGasPrice.BigInt(), Denom: chain.NetworkConfig.TokenSymbol},
> ```

From what I see, that code is duplicated across the tests, so we could move it somewhere to have in just one

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/146)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/146)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @ysv)

___
*[`integration-tests/auth/gas.go` line 33 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/146#-NAcxxC3Ba68bY_OKR-M:-NAd9uq-3k2a01VfZ43S:b-n05k5m) ([raw file](https://github.com/coreumfoundation/coreum/blob/ebd42f203c678a50f1fe5f6e1e38862e0000ec8a/integration-tests/auth/gas.go#L33)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

This model with the "testing.Prerequisites" seems overcomplicated taken in account today's state. At the moment of the text execution we have a function to fund any account in the runtime, so we don't need to add and addition code to do it before, meas the entire "Prerequisites" are redundant now. Each test can just call the Fund function at the start of the test. 
</blockquote></details>

I'm also thinking about it. Wanted to do it in different PR, but may do it here if you want to
___
*[`integration-tests/auth/gas.go` line 178 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/146#-NAcylDT43BnjBeq8Sev:-NAd9hXSCv3qK3r9Xiji:bsreesr) ([raw file](https://github.com/coreumfoundation/coreum/blob/ebd42f203c678a50f1fe5f6e1e38862e0000ec8a/integration-tests/auth/gas.go#L178)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

From what I see, that code is duplicated across the tests, so we could move it somewhere to have in just one
</blockquote></details>

Different tests put different numbers there

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/146)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`integration-tests/auth/gas.go` line 33 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/146#-NAcxxC3Ba68bY_OKR-M:-NAdCznQ6bVGVB7yltmM:b-lhro23) ([raw file](https://github.com/coreumfoundation/coreum/blob/ebd42f203c678a50f1fe5f6e1e38862e0000ec8a/integration-tests/auth/gas.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I'm also thinking about it. Wanted to do it in different PR, but may do it here if you want to
</blockquote></details>

Yes, why not, This PR is already tests run improvement.
___
*[`integration-tests/auth/gas.go` line 178 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/146#-NAcylDT43BnjBeq8Sev:-NAdCoUB1jNtzICYNUww:b3e55m0) ([raw file](https://github.com/coreumfoundation/coreum/blob/ebd42f203c678a50f1fe5f6e1e38862e0000ec8a/integration-tests/auth/gas.go#L178)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Different tests put different numbers there
</blockquote></details>

I mean: types.Coin{Amount: chain.NetworkConfig.Fee.FeeModel.InitialGasPrice.BigInt(), Denom: chain.NetworkConfig.TokenSymbol} this joining to Coin. But guess this will be simplified as soon as we start using the SDK types directly.



_Code quote:_
```Go
types.Coin{Amount: chain.NetworkConfig.Fee.FeeModel.InitialGasPrice.BigInt(), Denom: chain.NetworkConfig.TokenSymbol}
```

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/146)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`integration-tests/auth/gas.go` line 178 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/146#-NAcylDT43BnjBeq8Sev:-NAdDKYC55rWurL7D582:b-26peiv) ([raw file](https://github.com/coreumfoundation/coreum/blob/ebd42f203c678a50f1fe5f6e1e38862e0000ec8a/integration-tests/auth/gas.go#L178)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I mean: types.Coin{Amount: chain.NetworkConfig.Fee.FeeModel.InitialGasPrice.BigInt(), Denom: chain.NetworkConfig.TokenSymbol} this joining to Coin. But guess this will be simplified as soon as we start using the SDK types directly.
</blockquote></details>

It will be replaced by `sdk.Coin` soon. And anyway, `InitialGasPrice` is nto always used here, but it's the most common value.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/146)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @ysv)

___
*[`integration-tests/auth/gas.go` line 33 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/146#-NAcxxC3Ba68bY_OKR-M:-NAdTY6p5vMg-O0VGsdk:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/ebd42f203c678a50f1fe5f6e1e38862e0000ec8a/integration-tests/auth/gas.go#L33)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Yes, why not, This PR is already tests run improvement.
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/146)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/146)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, @oliverasistemas, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/146)* status: all files reviewed, 3 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, and @wojtek-coreum)

___
*[`integration-tests/integration_test.go` line 147 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/146#-NAihal0D0BJHwGM3IoU:-NAihal0D0BJHwGM3IoV:bmdyia8) ([raw file](https://github.com/coreumfoundation/coreum/blob/9fd1b86726ee25cc271a9a6261823ad967eb28d9/integration-tests/integration_test.go#L147)):*
> ```Go
> }
> 
> func (tf *testingFaucet) FundAccounts(ctx context.Context, accountsToFund []coreumtesting.FundedAccount) error {
> ```

non-blocking:
WDYT on having this signature:
```golang
func (tf *testingFaucet) FundAccounts  func(ctx context.Context, accountsToFund ...FundedAccount) error {
 // ...
}

// Usage:
// singe account funding 90% cases we will have
require.NoError(t, chain.FundAccounts(ctx, testing.FundedAccount{
			Wallet: sender,
			Amount: initialBalance,
		},
	))

// multiple accs opt1:
require.NoError(t, chain.FundAccounts(ctx,
		testing.FundedAccount{
			Wallet: wallet1,
			Amount: wallet1InitialBalance,
		},
		testing.FundedAccount{
			Wallet: wallet2,
			Amount: wallet2InitialBalance,
		},
	))

// multiple accs opt2:
require.NoError(t, chain.FundAccounts(ctx, []testing.FundedAccount{
		{
			Wallet: sender,
			Amount: initialBalance,
		},
		{
			Wallet: sender,
			Amount: initialBalance,
		},
	}...))
```

I like it a bit more for a single acc funding
___
*[`integration-tests/integration_test.go` line 151 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/146#-NAibcVW3QlbGrAdCitb:-NAibcVW3QlbGrAdCitc:b3cnmza) ([raw file](https://github.com/coreumfoundation/coreum/blob/9fd1b86726ee25cc271a9a6261823ad967eb28d9/integration-tests/integration_test.go#L151)):*
> ```Go
> 	case <-ctx.Done():
> 		return ctx.Err()
> 	case <-tf.muCh:
> ```

Can you add a comment explaining the logic of this muCh
I sort of understand it but it is not obvious
___
*[`integration-tests/testing/types.go` line 22 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/146#-NAif_tn0lceIEjyPgz_:-NAif_tn0lceIEjyPgza:b-py3ids) ([raw file](https://github.com/coreumfoundation/coreum/blob/9fd1b86726ee25cc271a9a6261823ad967eb28d9/integration-tests/testing/types.go#L22)):*
> ```Go
> 	NetworkConfig app.NetworkConfig
> 	Client        client.Client
> 	FundAccounts  func(ctx context.Context, accountsToFund []FundedAccount) error
> ```

For me it is more natural to use faucet here as field of chain
Because current approach feels like sort of functional programming

```golang
type TestingFaucet struct {
	// ...
}

type Chain struct {
	NetworkConfig app.NetworkConfig
	Client        client.Client
	Faucet      TestingFaucet
}
```

another option is to define faucet as interface but it might be a bit of overkill 

```golang
// testingFaucet implements Faucet interface so we can use it or replace with other faucet impl in the future e.g (using HTTP REST API faucet, generate from genesis)

type Faucet interface {
  FundAccounts(ctx context.Context, accountsToFund []coreumtesting.FundedAccount) error {
}

type Chain struct {
	NetworkConfig app.NetworkConfig
	Client        client.Client
	Faucet      Faucet // use Fauce instead of directly referring to testingFaucet
}
```

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/146)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @ysv)

___
*[`integration-tests/integration_test.go` line 151 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/146#-NAibcVW3QlbGrAdCitb:-NAj61oU2EBX0EkgHFNC:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/9fd1b86726ee25cc271a9a6261823ad967eb28d9/integration-tests/integration_test.go#L151)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Can you add a comment explaining the logic of this muCh
I sort of understand it but it is not obvious
</blockquote></details>

Done.
___
*[`integration-tests/testing/types.go` line 22 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/146#-NAif_tn0lceIEjyPgz_:-NAj64M5DTxCfQG5gHNA:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/9fd1b86726ee25cc271a9a6261823ad967eb28d9/integration-tests/testing/types.go#L22)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

For me it is more natural to use faucet here as field of chain
Because current approach feels like sort of functional programming

```golang
type TestingFaucet struct {
	// ...
}

type Chain struct {
	NetworkConfig app.NetworkConfig
	Client        client.Client
	Faucet      TestingFaucet
}
```

another option is to define faucet as interface but it might be a bit of overkill 

```golang
// testingFaucet implements Faucet interface so we can use it or replace with other faucet impl in the future e.g (using HTTP REST API faucet, generate from genesis)

type Faucet interface {
  FundAccounts(ctx context.Context, accountsToFund []coreumtesting.FundedAccount) error {
}

type Chain struct {
	NetworkConfig app.NetworkConfig
	Client        client.Client
	Faucet      Faucet // use Fauce instead of directly referring to testingFaucet
}
```
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/146)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @miladz68, and @oliverasistemas)

**Pull request merged**
