### PR TITLE
Implement DEX price type marshalling.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Implement DEX price type marshalling.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/904)

### CODE REVIEW

**Review by miladz68 — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/904)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

**Review by masihyeganeh — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/904)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

___
*[`x/dex/types/price_test.go` line 283 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/904#-O1M0BXR7Bf6gjl5QK43:-O1M0BXR7Bf6gjl5QK44:b-h9xnvx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/93623d352ec0b7c89299bbe34cda46355465cbe2/x/dex/types/price_test.go#L283)):*
> ```Go
> 			var buffer [100]byte
> 			n, err := p.MarshalTo(buffer[:])
> 			if err != nil {
> ```

Why not using testify here?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/904)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @ysv)

___
*[`x/dex/types/price_test.go` line 283 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/904#-O1M0BXR7Bf6gjl5QK43:-O1M18WI67AQ-hnQAA-C:b-eb7una) ([raw file](https://github.com/CoreumFoundation/coreum/blob/93623d352ec0b7c89299bbe34cda46355465cbe2/x/dex/types/price_test.go#L283)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Why not using testify here?
</blockquote></details>

Agree ,updated.

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/904)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/904)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
