### PR TITLE
Integrate ICA IBC.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Integrate ICA IBC.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/852)

### CODE REVIEW

**Review by ysv — APPROVED** [review]
> Reviewed 9 of 14 files at r1, 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/852)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`Makefile` line 45 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/852#-NyVgsai7uIO9gWo-n9T:-NyVgsai7uIO9gWo-n9U:b-bl2x67) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8a1dda094e60db9ce52b04f10ead868653ddbec5/Makefile#L45)):*
> ```Makefile
> 	$(CoreumBuilder) wasm build images
> 
> .PHONY: restart-znet
> ```

probably `crust znet restart` is a reasonable command to add
___
*[`integration-tests/ibc/ica_test.go` line 26 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/852#-NyVhu4b2DH1pq99xTj1:-NyVhu4b2DH1pq99xTj2:b-fufhl2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8a1dda094e60db9ce52b04f10ead868653ddbec5/integration-tests/ibc/ica_test.go#L26)):*
> ```Go
> 
> // TestICAController tests the ICA controller capabilities.
> func TestICACoreumControllerAndHost(t *testing.T) {
> ```

nit: I would split this func into 3 separate

- TestICACoreumController
-  TestICACoreumHost
- TestICADeterministicGas

even if 1 & 2 just call a single helper func it is ok IMO

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/852)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`Makefile` line 45 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/852#-NyVgsai7uIO9gWo-n9T:-NyYlIpp79pWdOcMqXOH:bu1kdid) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8a1dda094e60db9ce52b04f10ead868653ddbec5/Makefile#L45)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

probably `crust znet restart` is a reasonable command to add
</blockquote></details>

The idea here is that we have single-line commands. 
___
*[`integration-tests/ibc/ica_test.go` line 26 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/852#-NyVhu4b2DH1pq99xTj1:-NyYmIv81Xgzri7z4NfR:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8a1dda094e60db9ce52b04f10ead868653ddbec5/integration-tests/ibc/ica_test.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: I would split this func into 3 separate

- TestICACoreumController
-  TestICACoreumHost
- TestICADeterministicGas

even if 1 & 2 just call a single helper func it is ok IMO
</blockquote></details>

Done

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/852)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`Makefile` line 45 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/852#-NyVgsai7uIO9gWo-n9T:-NyZy16i5x5vTCtXcAKg:bxxan12) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8a1dda094e60db9ce52b04f10ead868653ddbec5/Makefile#L45)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The idea here is that we have single-line commands.
</blockquote></details>

yes, I'm ok this this
I mean we should add it to crust directly

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 9 of 14 files at r1, 5 of 7 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/852)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @miladz68)

___
*[`Makefile` line 41 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/852#-Ny_97WF1wmyQW98qHWh:-Ny_97WF1wmyQW98qHWi:b-sev6ln) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fff403cc7f07e0166cb9e9d259cfd303aa3f58a3/Makefile#L41)):*
> ```Makefile
> 	$(CoreumBuilder) download
> 
> .PHONY: build-znet
> ```

please don't mix znet stuff in this PR, this is not how it should be done
___
*[`integration-tests/ibc/ica_test.go` line 33 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/852#-Ny_D5AS6sKj-j3uhUu_:-Ny_D5ATA7xp64xHgwRo:blri2u0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fff403cc7f07e0166cb9e9d259cfd303aa3f58a3/integration-tests/ibc/ica_test.go#L33)):*
> ```Go
> 
> // TestICAController tests the ICA host capabilities.
> func TestICACoreumHoat(t *testing.T) {
> ```

Hoat->Host

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/852)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @wojtek-coreum)

___
*[`Makefile` line 41 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/852#-Ny_97WF1wmyQW98qHWh:-NytwBUP4eaNmi16Ex4v:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fff403cc7f07e0166cb9e9d259cfd303aa3f58a3/Makefile#L41)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

please don't mix znet stuff in this PR, this is not how it should be done
</blockquote></details>

Done.
___
*[`integration-tests/ibc/ica_test.go` line 33 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/852#-Ny_D5AS6sKj-j3uhUu_:-NytwJim5LWeDVyJzulq:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/fff403cc7f07e0166cb9e9d259cfd303aa3f58a3/integration-tests/ibc/ica_test.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Hoat->Host
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/852)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @miladz68, and @wojtek-coreum)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 5 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/852)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @miladz68)

**Pull request merged**
