### PR TITLE
Implement queries for `feemodel` module

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: 0 of 15 files reviewed, 7 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`go.mod` line 45 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBHHGu93AYnRDqLPxGN:-NBHHGu93AYnRDqLPxGO:b294mk7) ([raw file](https://github.com/coreumfoundation/coreum/blob/74b497eab60879138a9689105e1f007631a760e5/go.mod#L45)):*
> ```XML
> )
> 
> require github.com/golang/protobuf v1.5.2
> ```

Why it's imported separately from other imports?
___
*[`proto/coreum/feemodel/v1/query.proto` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBHCRry7-wbr69mWpIK:-NBHCRry7-wbr69mWpIL:b-ek232q) ([raw file](https://github.com/coreumfoundation/coreum/blob/74b497eab60879138a9689105e1f007631a760e5/proto/coreum/feemodel/v1/query.proto#L12)):*
> ```protobuf
> 
> // Query defines the gRPC querier service.
> service Query {
> ```

Additionaly you need to generate the swagger. 
```
ignite generate openapi
```
___
*[`x/feemodel/module.go` line 213 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBHIMO403ZTYyEVpo7-:-NBHIMO403ZTYyEVpo70:bp2p3mf) ([raw file](https://github.com/coreumfoundation/coreum/blob/74b497eab60879138a9689105e1f007631a760e5/x/feemodel/module.go#L213)):*
> ```Go
> }
> 
> func (k keeperToQueryServer) MinGasPrice(ctx context.Context, req *types.QueryMinGasPriceRequest) (*types.QueryMinGasPriceResponse, error) {
> ```

Wow :-) Barely found where the queries are implemented.
The queries are usually implemented in the keeper/grpc_query.go since they give you an access to the keeper. The module.go is just a set-up file, keeping here the business logic is a bad idea. 
___
*[`x/feemodel/client/cli/query.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBHDAOdAXSfGj9PqNvx:-NBHDAOdAXSfGj9PqNvy:bp0pzaz) ([raw file](https://github.com/coreumfoundation/coreum/blob/74b497eab60879138a9689105e1f007631a760e5/x/feemodel/client/cli/query.go#L14)):*
> ```Go
> // provided clientCtx should have, at a minimum, a verifier, Tendermint RPC client,
> // and marshaler set.
> func GetQueryCmd() *cobra.Command {
> ```

It's possible to write the tests for the CLI as well. 

Example: https://github.com/dzmitryhil/freezer/blob/main/x/fbank/cli/query_test.go#L26



_Code quote:_
```Go
// and marshaler set.
func GetQueryCmd() *cobra.Command {
```
___
*[`x/feemodel/client/rest/query.go` line 16 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBHDUsr6nSSbLETGKSG:-NBHDUsr6nSSbLETGKSH:b-firbyw) ([raw file](https://github.com/coreumfoundation/coreum/blob/74b497eab60879138a9689105e1f007631a760e5/x/feemodel/client/rest/query.go#L16)):*
> ```Go
> // minimum gas price required by the network.
> func QueryMinGasPriceRequestHandlerFn(clientCtx client.Context) http.HandlerFunc {
> 	return func(w http.ResponseWriter, r *http.Request) {
> ```

This is the legacy way. You don't need that package at all. And don't need to register the rest rotes in the module.go
```
// RegisterGRPCGatewayRoutes registers the gRPC Gateway routes for the fee module.
func (AppModuleBasic) RegisterGRPCGatewayRoutes(clientCtx client.Context, mux *runtime.ServeMux) {
	//nolint:errcheck // Welcome to Cosmos SDK
	types.RegisterQueryHandlerClient(context.Background(), mux, types.NewQueryClient(clientCtx))
}
```
This code already integrates the generated handlers form the "query.pb.gw.go"
___
*[`x/feemodel/types/key.go` line 17 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBHGkSjEg0_PoELKuMk:-NBHGkSjEg0_PoELKuMl:b-hs8gr2) ([raw file](https://github.com/coreumfoundation/coreum/blob/74b497eab60879138a9689105e1f007631a760e5/x/feemodel/types/key.go#L17)):*
> ```Go
> 
> 	// QuerierRoute defines the module's query routing key
> 	QuerierRoute = ModuleName
> ```

Should be removed together with the rest package
___
*[`x/feemodel/types/querier.go` line 5 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBHHCBdEG0UNRxW3Ope:-NBHHCBdEG0UNRxW3Opf:b-hs8gr2) ([raw file](https://github.com/coreumfoundation/coreum/blob/74b497eab60879138a9689105e1f007631a760e5/x/feemodel/types/querier.go#L5)):*
> ```Go
> // Querier path constants
> const (
> 	QueryMinGasPrice = "min_gas_price"
> ```

Should be removed together with the rest package

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/module.go` line 213 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBHIMO403ZTYyEVpo7-:-NBHW1QzBcKuxRF6Qn1n:b46olv5) ([raw file](https://github.com/coreumfoundation/coreum/blob/74b497eab60879138a9689105e1f007631a760e5/x/feemodel/module.go#L213)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Wow :-) Barely found where the queries are implemented.
The queries are usually implemented in the keeper/grpc_query.go since they give you an access to the keeper. The module.go is just a set-up file, keeping here the business logic is a bad idea. 

</blockquote></details>

I've seen how they do it in standard modules but keeping http/grpc specific code inside keeper seems ridiculous to me because keeper is about storing stte, not serving http requests. That's why I did it separately. Maybe the name of this struct is not the best one.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: all files reviewed, 7 unresolved discussions (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/module.go` line 213 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBHIMO403ZTYyEVpo7-:-NBI36cu9NF5VZqeJxO7:burc57t) ([raw file](https://github.com/coreumfoundation/coreum/blob/74b497eab60879138a9689105e1f007631a760e5/x/feemodel/module.go#L213)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I've seen how they do it in standard modules but keeping http/grpc specific code inside keeper seems ridiculous to me because keeper is about storing stte, not serving http requests. That's why I did it separately. Maybe the name of this struct is not the best one.
</blockquote></details>

But that's the standard. Where did you get the info that this pack is specifily for storing?

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 15 files at r1, 2 of 3 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`pkg/client/client.go` line 298 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBR_egk0urbMYD2MI8u:-NBR_egk0urbMYD2MI8v:b-m330pg) ([raw file](https://github.com/coreumfoundation/coreum/blob/8798c242ca669e2d79f0212b31e3cdc197b2c196/pkg/client/client.go#L298)):*
> ```Go
> // FeemodelQueryClient returns a feemodel module querying client, initialized
> // using the internal clientCtx.
> func (c Client) FeemodelQueryClient() feemodeltypes.QueryClient {
> ```

let's stop adding code to the client, let's get a reference to clientCtx (from client or from chain) and create queryclient on integration test.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: 14 of 17 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`pkg/client/client.go` line 298 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBR_egk0urbMYD2MI8u:-NBSLua-BdUz0ydtqirW:b-u9mvvl) ([raw file](https://github.com/coreumfoundation/coreum/blob/8798c242ca669e2d79f0212b31e3cdc197b2c196/pkg/client/client.go#L298)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's stop adding code to the client, let's get a reference to clientCtx (from client or from chain) and create queryclient on integration test.
</blockquote></details>

but this is the convention existing in `master`. There is some work in progress in this topic going on in other PRs. Please let's not invent new approach here. Once new helpers / clients are there we will update everything.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: 14 of 18 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/client/cli/query.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBHDAOdAXSfGj9PqNvx:-NBSaZqk7fYsUkE27mvc:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/74b497eab60879138a9689105e1f007631a760e5/x/feemodel/client/cli/query.go#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

It's possible to write the tests for the CLI as well. 

Example: https://github.com/dzmitryhil/freezer/blob/main/x/fbank/cli/query_test.go#L26
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: 14 of 18 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/client/cli/query.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBHDAOdAXSfGj9PqNvx:-NBW1zCu54mmz7a5h5Ah:bnqxwa6) ([raw file](https://github.com/coreumfoundation/coreum/blob/74b497eab60879138a9689105e1f007631a760e5/x/feemodel/client/cli/query.go#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Glat that we have stated using it :-)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: 14 of 18 files reviewed, 1 unresolved discussion (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`x/feemodel/client/cli/query.go` line 14 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBHDAOdAXSfGj9PqNvx:-NBW2XKe1-I_QbTXQQML:b-ysi8ka) ([raw file](https://github.com/coreumfoundation/coreum/blob/74b497eab60879138a9689105e1f007631a760e5/x/feemodel/client/cli/query.go#L14)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Glat that we have stated using it :-)
</blockquote></details>

I'm not a fan of this because it creates some tmp files and probably starts real socket in the os

**Review by miladz68 — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, and @ysv)

**Review by miladz68 — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: all files reviewed, 1 unresolved discussion (waiting on @begmaroman, @oliverasistemas, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @oliverasistemas, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 6 of 15 files at r1, 2 of 3 files at r2, 6 of 8 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: all files reviewed, 2 unresolved discussions (waiting on @begmaroman, @oliverasistemas, and @wojtek-coreum)

___
*[`x/feemodel/module.go` line 74 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBWuuBQ67iY44pwxhQs:-NBWuuBQ67iY44pwxhQt:b3zm9xz) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1f51e0233e9400a94aac11106dcc0be945072ad/x/feemodel/module.go#L74)):*
> ```Go
> // RegisterGRPCGatewayRoutes registers the gRPC Gateway routes for the fee module.
> func (AppModuleBasic) RegisterGRPCGatewayRoutes(clientCtx client.Context, mux *runtime.ServeMux) {
> 	//nolint:errcheck // Welcome to Cosmos SDK
> ```

is it done on app initialization stage ?
maybe panic here ?
___
*[`x/feemodel/client/cli/query.go` line 34 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBWvocN9VHnG4DcnhrE:-NBWvocN9VHnG4DcnhrF:b-grd6vc) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1f51e0233e9400a94aac11106dcc0be945072ad/x/feemodel/client/cli/query.go#L34)):*
> ```Go
> 	cmd := &cobra.Command{
> 		Use:   "min-gas-price",
> 		Short: "Query for minimum gas price required by the network",
> ```

"Query for minimum gas price for current block required by the network"

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: 17 of 18 files reviewed, 2 unresolved discussions (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @ysv)

___
*[`x/feemodel/module.go` line 74 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBWuuBQ67iY44pwxhQs:-NBX6JdG7HSwAdi3CgKU:b-f9v9x7) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1f51e0233e9400a94aac11106dcc0be945072ad/x/feemodel/module.go#L74)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

is it done on app initialization stage ?
maybe panic here ?
</blockquote></details>

The fact is that `types.RegisterQueryHandlerClient` always returns nil
___
*[`x/feemodel/client/cli/query.go` line 34 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBWvocN9VHnG4DcnhrE:-NBX73lp87RW6UJruZcd:b-896fix) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1f51e0233e9400a94aac11106dcc0be945072ad/x/feemodel/client/cli/query.go#L34)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

"Query for minimum gas price for current block required by the network"
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: 17 of 18 files reviewed, all discussions resolved (waiting on @begmaroman, @dzmitryhil, @miladz68, @oliverasistemas, and @ysv)

___
*[`x/feemodel/module.go` line 74 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/156#-NBWuuBQ67iY44pwxhQs:-NBX86TPBivOyduuq28G:b-fn8mpi) ([raw file](https://github.com/coreumfoundation/coreum/blob/e1f51e0233e9400a94aac11106dcc0be945072ad/x/feemodel/module.go#L74)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The fact is that `types.RegisterQueryHandlerClient` always returns nil
</blockquote></details>

:facepalm:

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/156)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @begmaroman, @dzmitryhil, @miladz68, and @oliverasistemas)

**Pull request merged**
