### PR TITLE
Create ante decorator blocking defined messages

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/399)

### CODE REVIEW

**Review by miladz68 — DISMISSED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/399)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @silverspase, and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/399)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`pkg/config/network.go` line 84 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/399#-NOQNb-i76_So7USjapO:-NOQNb-jD5ikhntyaXpK:bltaki0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b391f3a5d4a5a43306d04324b37500f2604801ff/pkg/config/network.go#L84)):*
> ```Go
> 		}
> 
> 		crisisConfig = CrisisConfig{
> ```

I think crisis module exposes this amount via params as `ConstantFee`
So in integration tests I would prefer to query module params to get this value instead of getting it from network directly. 

We don't have use-case for this amount to be different for different networks what is more I don't want to overload network config with unused things, so I suggest to not keep it here but use hardcoded value in genesis & query params in integration-tests

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/399)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`pkg/config/network.go` line 84 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/399#-NOQNb-i76_So7USjapO:-NOTJw6zAZvNxP_YNlLE:b-5kqub3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ed3bfe42579924817a5ad5523187867b37cf3154/pkg/config/network.go#L84)):*
> I think crisis module exposes this amount via params as ConstantFee

No, it doesn't. There is no single query exposed by `crisis`

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/399)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Review by ysv — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/399)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

___
*[`pkg/config/network.go` line 85 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/399#-NOjuRTg4K50P_WMH_7E:-NOjuRThEmBA6724YlLi:bjpwbg2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/af8173e70f244e7eee053dbe28c7c4f4bf2aecc9/pkg/config/network.go#L85)):*
> ```Go
> 
> 		crisisConfig = CrisisConfig{
> 			Amount: sdk.NewIntFromUint64(500_000_000_000),
> ```

Frankly speaking I wouldn't add it to config just for integraiton tests purpose

The bad fact is that we expose pkg/config publicly for client users & I want to keep it as minimalistic & simple as possible
I would probably prefer to hardocde this value in integration-tests rather than artificially adding it into network config

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/399)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/399)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`pkg/config/network.go` line 85 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/399#-NOjuRTg4K50P_WMH_7E:-NOneWgrA2iI7JiZR58j:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b8e2351962a086d38c1711a667a736cd23974629/pkg/config/network.go#L85)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Frankly speaking I wouldn't add it to config just for integraiton tests purpose

The bad fact is that we expose pkg/config publicly for client users & I want to keep it as minimalistic & simple as possible
I would probably prefer to hardocde this value in integration-tests rather than artificially adding it into network config
</blockquote></details>

Done.

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/399)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/399)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @silverspase)

**Pull request merged**
