### PR TITLE
Update asset issue cli to allow for extensions

### PR DESCRIPTION
**Pull request by masihyeganeh**
# Description
Update asset issue cli to allow for extensions

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/855)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/855)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/client/cli/tx.go` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/855#-Nz209nvDnkCNcs-3ToB:-Nz209nw7pZhePNWr91M:bd8krnz) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e1591191eddd8747659e47d7c8a25bad95866df9/x/asset/ft/client/cli/tx.go#L83)):*
> ```Go
> 	cmd := &cobra.Command{
> 		//nolint:lll // breaking this down will make it look worse when printed to user screen.
> 		Use:   "issue [symbol] [subunit] [precision] [initial_amount] [description] --from [issuer] --features=" + strings.Join(allowedFeatures, ",") + " --burn-rate=0.12 --send-commission-rate=0.2 --uri https://my-token-meta.invalid/1 --uri_hash e000624 --extension_code_id=1 --extension_label=my-extension --extension_funds=1000000core",
> ```

Please use `100000ABC-%s` as in other CLI commands here instead.



_Code quote:_
```Go
1000000core
```

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/855)* status: all files reviewed, 2 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/client/cli/tx.go` line 221 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/855#-Nz2436M0vDITjuX554n:-Nz2436M0vDITjuX554o:b-ntrw46) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e1591191eddd8747659e47d7c8a25bad95866df9/x/asset/ft/client/cli/tx.go#L221)):*
> ```Go
> 	cmd.Flags().String(URIHashFlag, "", "Token URI hash.")
> 	cmd.Flags().Uint64(ExtensionCodeID, 0, "CodeID of the stored WASM smart contract to be used as the asset extension.")
> 	cmd.Flags().String(ExtensionLabel, "", "Optional metadata to be stored with a contract instance.")
> ```

not metadata. optional label to be given to extension contract.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/855)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/client/cli/tx.go` line 83 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/855#-Nz209nvDnkCNcs-3ToB:-Nz7VPQB8lXTKIoQvawB:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e1591191eddd8747659e47d7c8a25bad95866df9/x/asset/ft/client/cli/tx.go#L83)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Please use `100000ABC-%s` as in other CLI commands here instead.
</blockquote></details>

Done.
___
*[`x/asset/ft/client/cli/tx.go` line 221 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/855#-Nz2436M0vDITjuX554n:-Nz7VXU31JY_GLLkFV4o:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e1591191eddd8747659e47d7c8a25bad95866df9/x/asset/ft/client/cli/tx.go#L221)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

not metadata. optional label to be given to extension contract.
</blockquote></details>

Done.

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/855)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/855)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

**Pull request merged**
