### PR TITLE
Copied cosmoscmd code from ignite-hq/cli repository

### PR DESCRIPTION
**Pull request by miladz68**
Copied the code as is, without any modifications in this PR. changes will come in the next PR so the reviewers can easily see what is being changed form the original code. 
only added a statement to top of each file to indicate from where the code is copied.

---
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/108)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/108)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/108#-N6lxA-G3T1w3Cxu3_nF:-N6lxA-G3T1w3Cxu3_nG:bwbdj7b) (no related file):*
Could you make your changes in the next commits in the same PR here? Then we will be able to see what the idea is. Reviewers may easily review PR commit by commit, so we see what was copied and what your modifications are.

___

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/108)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/108#-N6lxA-G3T1w3Cxu3_nF:-N6m7yP086p-X-m3LMEb:b7arimt) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you make your changes in the next commits in the same PR here? Then we will be able to see what the idea is. Reviewers may easily review PR commit by commit, so we see what was copied and what your modifications are.
</blockquote></details>

good idea

___

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/108)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/108#-N6lxA-G3T1w3Cxu3_nF:-N6qVJsq-gKxWLx66SBa:b-ew1bdj) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

good idea
</blockquote></details>

on a second thought I think we should merge the copied code, as is, and introduce changes in a separate PR, right now there 2 independent changes that i want to introduces and discuss 

___

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/108)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/108#-N6lxA-G3T1w3Cxu3_nF:-N6qWdtLAC_N60nZweSw:b-aplava) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

on a second thought I think we should merge the copied code, as is, and introduce changes in a separate PR, right now there 2 independent changes that i want to introduces and discuss 
</blockquote></details>

following a discussion with @wojtek-coreum, we decided to keep these changes in a separate branch and introduce changes against this branch and merge when changes are final.  

___

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/108)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/coreum/108#-N6lxA-G3T1w3Cxu3_nF:-N6qWvQT6JAZzBZNlMFw:b-j3gd23) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

following a discussion with @wojtek-coreum, we decided to keep these changes in a separate branch and introduce changes against this branch and merge when changes are final.  
</blockquote></details>

I will close this PR then. 

___

**Pull request closed without merging**
