### PR TITLE
Add 2 sides, 2 ways order matching algorithm with example.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/872)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/872)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/dex/spec/matching.md` line 8 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LXV6O-gFaB8-CoGOe:-O-LXV6O-gFaB8-CoGOf:b-nk0mp6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L8)):*
> ```Markdown
> 
> The Coreum DEX orders can be created for any-to-any token by any Coreum user. Which meas that the order book
> is bidirectional and permissionless. The user place an order and provides the order attributes:
> ```

 The user places an



_Code quote:_
```Markdown
 user place an
```
___
*[`x/dex/spec/matching.md` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LXnizBTmb-LsSL3cE:-O-LXnizBTmb-LsSL3cF:b-3hxf7k) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L18)):*
> ```Markdown
> * `side`
>     * `sell` - means that the order is to sell `base_denom` `quantity` with the `price`.
>     * `buy` - means that the order is to buy `base_denom` `quantity` with the `price`.
> ```

the different should be explained. meaning that in one case the the base_denom will be used to calculate how much of the order is filled and in the other case quote_denom will be used.
___
*[`x/dex/spec/matching.md` line 36 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LYVbEBAmtcMa-LR0I:-O-LYVbEBAmtcMa-LR0J:b-djso3g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L36)):*
> ```Markdown
> The inverse taker price (1/price) of order2 is greater than the price of order1 (~0.3846 > 0.375)hence orders match.
> The order2 should be executed with the price of the order1 (taker gets the better price). The exact amount of AAA order2
> receives is 10000000 * 1/0.375 = 26_666_666.(6) AAA. The amount we can use must be an integer, so we can't send full
> ```

this paragraph is italic. it should be normal text.
___
*[`x/dex/spec/matching.md` line 41 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LYo0O-DJSGTlUUgEX:-O-LYo0O-DJSGTlUUgEY:b-x0wrb8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L41)):*
> ```Markdown
> ### Tick size
> 
> To avoid significant filling quantity violation and provide a better trading experience we define
> ```

the first sentence is displayed as italic for some reason !
___
*[`x/dex/spec/matching.md` line 45 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LZ-Yw4K6_zSqAmziB:-O-LZ-Yw4K6_zSqAmziC:bhunt2w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L45)):*
> ```Markdown
> of the assets traded, that's why we can define the variable for a token used to define the pair `tick_sizes`. This
> variable is named `significant_amount`. `significant_amount` for token represents minimum valuable amount of a token.
> The recommended targeting price for the significant amount is 1 USD dollar cent.
> ```

we can replacec 1 USD dollar cent with 1 USD dollar for each of calculation.
___
*[`x/dex/spec/matching.md` line 54 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LZAFZDshVltP0oaUk:-O-LZAFZDshVltP0oaUl:b-mvsl33) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L54)):*
> ```Markdown
> 
> The `tick_size_multiplier` is the coefficient used to give better price precision for the token pairs. The default value
> of the `tick_size_multiplier` is  `0.01`, and can be updated by the governance.
> ```

we decided to have 10^-6 for tich_size_multiplier.
___
*[`x/dex/spec/matching.md` line 131 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LZuIZ4R7nHf_D1Zfh:-O-LZuIZ4R7nHf_D1Zfi:b5j2xxt) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L131)):*
> ```Markdown
> ```
> var (order_to_close, order_to_reduce)
> if taker_order(base_denom/quote_denom) == buy
> ```

I have hard time reading and understanding this sudo code. And I don't think we should put this sudo code into the docs. The high level algorithm without implementaion details should be explained in a paragraph 
___
*[`x/dex/spec/matching.md` line 309 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LaH769S6Y9iCFHUzG:-O-LaH769S6Y9iCFHUzH:bjsvh1n) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L309)):*
> ```Markdown
> 
> ```
> taker_order(base_denom/quote_denom) == buy
> ```

looking at this example and also the explanation, I cannot understand how the maker/taker order is decided. we should walk the reader through or provide better description. same goes for all the examples

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/872)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @masihyeganeh, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/dex/spec/matching.md` line 8 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LXV6O-gFaB8-CoGOe:-O-_43TH2EWbnXpO8lHI:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L8)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

The user places an
</blockquote></details>

Done.
___
*[`x/dex/spec/matching.md` line 18 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LXnizBTmb-LsSL3cE:-O-_465w7YPqj54T1QFZ:b-qdwpgx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L18)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the different should be explained. meaning that in one case the the base_denom will be used to calculate how much of the order is filled and in the other case quote_denom will be used.
</blockquote></details>

IMO the current explanation explains exactly this.
___
*[`x/dex/spec/matching.md` line 36 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LYVbEBAmtcMa-LR0I:-O-_5eKM-upBEz83eTdY:bn7txb9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L36)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this paragraph is italic. it should be normal text.
</blockquote></details>

Chech here, look fine: https://github.com/CoreumFoundation/coreum/blob/dzmitryhil/matching-pos-with-price-side/x/dex/spec/matching.md#rounding-issue
___
*[`x/dex/spec/matching.md` line 41 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LYo0O-DJSGTlUUgEX:-O-_4r7SE0KlKRXFNVKi:b9fn4xx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L41)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the first sentence is displayed as italic for some reason !
</blockquote></details>

Chech here, look fine: https://github.com/CoreumFoundation/coreum/blob/dzmitryhil/matching-pos-with-price-side/x/dex/spec/matching.md#rounding-issue
___
*[`x/dex/spec/matching.md` line 45 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LZ-Yw4K6_zSqAmziB:-O-_4vkv1oBf9pp-XTeO:b-iiblnw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L45)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we can replacec 1 USD dollar cent with 1 USD dollar for each of calculation.
</blockquote></details>

I'll update it in separate PR together with all new things regarding the price tick size.
___
*[`x/dex/spec/matching.md` line 54 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LZAFZDshVltP0oaUk:-O-_536J8--5H1K1IlvA:b-iiblnw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L54)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we decided to have 10^-6 for tich_size_multiplier.
</blockquote></details>

I'll update it in separate PR together with all new things regarding the price tick size.
___
*[`x/dex/spec/matching.md` line 131 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LZuIZ4R7nHf_D1Zfh:-O-_56GEBLlXYp5M5vPx:b-riidf8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L131)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I have hard time reading and understanding this sudo code. And I don't think we should put this sudo code into the docs. The high level algorithm without implementaion details should be explained in a paragraph
</blockquote></details>

The plan is to try to simplify it (after the go-implementation to have the tests to pass), and if it's not simple, explain as you propose. 
___
*[`x/dex/spec/matching.md` line 309 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-LaH769S6Y9iCFHUzG:-O-_5M3lEdIbWVRUStxj:b-58plxq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6136bcb8dd3074ec9db27f4978d5472b7d953f6d/x/dex/spec/matching.md#L309)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

looking at this example and also the explanation, I cannot understand how the maker/taker order is decided. we should walk the reader through or provide better description. same goes for all the examples
</blockquote></details>

Answere in prev comment.  For now I need it to have a reference to handle all use-cases, and show you them all. Also each name of the round explains what is unique.

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/872)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/872)* status: all files reviewed, 3 unresolved discussions (waiting on @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`x/dex/spec/matching.md` line 21 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-ku_E2D2YeoBpS0a89:-O-o9U-q4Twg7yZyUonz:bncq7tj) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ee508800ed31457a40976cb253c0870e0ad9819f/x/dex/spec/matching.md#L21)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Does the order of checking matter here? If it always checks the same order book first, would the second order book orders starve?
</blockquote></details>

The order doesn't matter here, but we need to check both always to find the best price.
___
*[`x/dex/spec/matching.md` line 31 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-kFyTACx22A7CS3D_s:-O-oAQo71mSCSFDQHp7T:b4xvtwp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ee508800ed31457a40976cb253c0870e0ad9819f/x/dex/spec/matching.md#L31)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Thousands separator would help here and make it easier to read
</blockquote></details>

It was here initially, but the issue with it is when you use the calculator, if doesn't work. 
___
*[`x/dex/spec/matching.md` line 35 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/872#-O-kHbb53oSy2yoSJoc_:-O-o9vDxBMd4y6kN7wkq:bhl2sh6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/ee508800ed31457a40976cb253c0870e0ad9819f/x/dex/spec/matching.md#L35)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Does it mean that if I put a taker order with a really high price, my order will always match and I won't pay extra money?
Not saying that it is violating anything, it just caught my eyes
</blockquote></details>

Right, that's the limit order.

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/872)* status: all files reviewed, 3 unresolved discussions (waiting on @masihyeganeh and @ysv)

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/872)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
