### PR TITLE
Don't charge burn rate and send commission on failing IBC transfers

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/583)

### CODE REVIEW

**Review by ysv — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/583)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @vertex451)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/583)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @vertex451)

___
*[`integration-tests/ibc/asset_ft_test.go` line 1342 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/583#-NaMORvB4HkERdNh_q6o:-NaMZY5EEwE7y9m0-Q7I:bye8s5o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd0affd3759317a982129908ca5fbd7ac61e633d/integration-tests/ibc/asset_ft_test.go#L1342)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we are getting the same coins back, so no rates are applied ?
</blockquote></details>

Look at how `sendCoin` is computed. It means that the difference between `sendCoin` and `issueMsg.InitialAmount` is charged (as a result of burn rate and send commission fee) when IBC transfer is requested (so the balance on the account is 0). But then when IBC transfer fails the `sendCoin` amount is returned back without charging fees the second time.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/583)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @vertex451, and @wojtek-coreum)

___
*[`integration-tests/ibc/asset_ft_test.go` line 1342 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/583#-NaN83yM5w7cClt8QIWx:-NaN83yNAC0mZ2o9rUqY:b-6jltor) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd0affd3759317a982129908ca5fbd7ac61e633d/integration-tests/ibc/asset_ft_test.go#L1342)):*
> ```Go
> 	// Burn rate and send commission should be charged only once when IBC transfer is requested (we will probably change this in the future),
> 	// but when IBC transfer is rolled back, rates should not be charged again.
> 	requireT.NoError(coreumChain.AwaitForBalance(ctx, t, coreumSender, sendCoin))
> ```

Does it make sence to test the escrow address balance as well?
___
*[`integration-tests/ibc/asset_ft_test.go` line 1417 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/583#-NaN8EJHE1Ot93vQ4O3Q:-NaN8EJHE1Ot93vQ4O3R:b8jz0hk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd0affd3759317a982129908ca5fbd7ac61e633d/integration-tests/ibc/asset_ft_test.go#L1417)):*
> ```Go
> 		require.NoError(t, err)
> 
> 		// Send coins from sender to blocked address on Gaia.
> ```

The comment isn't correct.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/583)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @vertex451, and @wojtek-coreum)

___
*[`integration-tests/ibc/asset_ft_test.go` line 1342 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/583#-NaN83yM5w7cClt8QIWx:-NaN8Mih8na3NQMYLtMJ:b-kepkps) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd0affd3759317a982129908ca5fbd7ac61e633d/integration-tests/ibc/asset_ft_test.go#L1342)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Does it make sence to test the escrow address balance as well?
</blockquote></details>

Same for other test.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/583)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @miladz68, @vertex451, and @ysv)

___
*[`integration-tests/ibc/asset_ft_test.go` line 1342 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/583#-NaN73fC2C5JEMslmwLK:-NaQKKPc--Bpefe6Yp5_:b-kiripo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd0affd3759317a982129908ca5fbd7ac61e633d/integration-tests/ibc/asset_ft_test.go#L1342)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Does it make sence to check the escrow address balance as well ? Same for next test.
</blockquote></details>

Technically, escrow address is the implementation detail and the logic might be changed at any time in the next version of IBC. So I don't think we should count on it. And the operation here is the standard bank send we test in many places, so if if funds were added on one account it means they were deducted from the other one.
___
*[`integration-tests/ibc/asset_ft_test.go` line 1417 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/583#-NaN7Mz-9WzIhk_mNOlx:-NaQNXs77lMFqxyIehsU:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd0affd3759317a982129908ca5fbd7ac61e633d/integration-tests/ibc/asset_ft_test.go#L1417)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The comment isn't corrent. 
</blockquote></details>

Done

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/583)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @vertex451)

___
*[`integration-tests/ibc/asset_ft_test.go` line 1342 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/583#-NaN73fC2C5JEMslmwLK:-NaQX0NO3m7N9QaF33t4:b4wkdoe) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd0affd3759317a982129908ca5fbd7ac61e633d/integration-tests/ibc/asset_ft_test.go#L1342)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Technically, escrow address is the implementation detail and the logic might be changed at any time in the next version of IBC. So I don't think we should count on it. And the operation here is the standard bank send we test in many places, so if if funds were added on one account it means they were deducted from the other one.
</blockquote></details>

I suggest we assert it as extra level of check

We do it in many IBC test I think it makes sense here also

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/583)* status: all files reviewed, 2 unresolved discussions (waiting on @vertex451 and @wojtek-coreum)

___
*[`integration-tests/ibc/asset_ft_test.go` line 1342 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/583#-NaMORvB4HkERdNh_q6o:-NaQdyK26F-yIAqTJvSp:bi2ff5j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd0affd3759317a982129908ca5fbd7ac61e633d/integration-tests/ibc/asset_ft_test.go#L1342)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Look at how `sendCoin` is computed. It means that the difference between `sendCoin` and `issueMsg.InitialAmount` is charged (as a result of burn rate and send commission fee) when IBC transfer is requested (so the balance on the account is 0). But then when IBC transfer fails the `sendCoin` amount is returned back without charging fees the second time.
</blockquote></details>

But we put sendCoin into ExecuteIBCTransfer, and then we get the same value after timeout/reject. it means that the rates were not applied either on send stage, nor in timeout stage.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/583)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @miladz68 and @vertex451)

___
*[`integration-tests/ibc/asset_ft_test.go` line 1342 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/583#-NaN73fC2C5JEMslmwLK:-NaR3hq98tSBhkMGmKPk:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd0affd3759317a982129908ca5fbd7ac61e633d/integration-tests/ibc/asset_ft_test.go#L1342)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I suggest we assert it as extra level of check

We do it in many IBC test I think it makes sense here also
</blockquote></details>

Done
___
*[`integration-tests/ibc/asset_ft_test.go` line 1342 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/583#-NaMORvB4HkERdNh_q6o:-NaR3m2r9ATwjEhj_fni:bpk7j0i) ([raw file](https://github.com/CoreumFoundation/coreum/blob/cd0affd3759317a982129908ca5fbd7ac61e633d/integration-tests/ibc/asset_ft_test.go#L1342)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

But we put sendCoin into ExecuteIBCTransfer, and then we get the same value after timeout/reject. it means that the rates were not applied either on send stage, nor in timeout stage. 
</blockquote></details>

no, this is what happens:
1. sender receives from the issuer entire initial amount
2. `sendCoin` is calculated as a difference between received initial amount and the sum of fees
3. `sendCoin` is sent + fees are charged
4. IBC fails
5. `sendCoin` is refunded but fees are not

So the final balance is `sendCoin`

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/583)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/583)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/583)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vertex451)

**Pull request merged**
