### PR TITLE
Restore the coreum checkout

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/339)

### CODE REVIEW

**Review by miladz68 — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
