### PR TITLE
Stop rejecting contract instantiation if account holds funds

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/776)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/776)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 2238 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/776#-Np4ld_B31NI157mcQ4C:-Np4ld_B31NI157mcQ4D:b-ynkmze) ([raw file](https://github.com/CoreumFoundation/coreum/blob/deaea3a6b5743e08e32d93c81b003802cba506b5/integration-tests/modules/wasm_test.go#L2238)):*
> ```Go
> }
> 
> // TestWASMContractInstantiationIsRejectedIfThereAreTokensOnItsAccount verifies that smart contract instantiation
> ```

`TestWASMContractInstantiationIsRejectedIfThereAreTokensOnItsAccount` is different from the test name.

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/776)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/wasm_test.go` line 2238 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/776#-Np4ld_B31NI157mcQ4C:-Np4mikj5L6LO_SdCCjV:b6mgeu0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/deaea3a6b5743e08e32d93c81b003802cba506b5/integration-tests/modules/wasm_test.go#L2238)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`TestWASMContractInstantiationIsRejectedIfThereAreTokensOnItsAccount` is different from the test name.
</blockquote></details>

Done, funny that linter passed

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/776)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/776)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`app/app.go` line 614 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/776#-NpKCPur3oWgKTOClhly:-NpKG74M8fyKS0XqFDsa:bc8bl1m) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c0d43e495d15007c740ef6a29c03ca935326f66d/app/app.go#L614)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

out of topic:
What happens when you try to instantiate contract with the same address as existing ?
Does This Pruner handle it ?
</blockquote></details>

I believe error saying that address is already taken is returned
___
*[`integration-tests/modules/wasm_test.go` line 2288 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/776#-NpKCiWO69qIOoE0CmcO:-NpKGFEN7fbVbxng6UkR:b-aaic1u) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c0d43e495d15007c740ef6a29c03ca935326f66d/integration-tests/modules/wasm_test.go#L2288)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO endTime should be in the future to properly test that vesting is applied
</blockquote></details>

Here I test that funds existing on the account are not burnt, that's why they are vested immediately.  What you are describing is done separately in the next test below.
___
*[`integration-tests/modules/wasm_test.go` line 2481 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/776#-NpKDN8FBG9AUdTjhdFu:-NpKGYMV3Lv1lZM9bRWV:b2iiu0j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/c0d43e495d15007c740ef6a29c03ca935326f66d/integration-tests/modules/wasm_test.go#L2481)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

what is the responsibility of this func ?
I didn't get the name
</blockquote></details>

It verifies that the account used by the smart contract is in the expected state (account type, balance)

**Review by ysv — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/776)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
