### PR TITLE
Finalize slashing module

### PR DESCRIPTION
**Pull request by vertex451**
I added deterministic gas and slashing genesis params
Tested build after all changes - all good, network started.
Screenshot from 2022-12-20 14-51-15

- - -
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/306)

### CODE REVIEW

**Review by ysv — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/306)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

**Review by ysv — APPROVED** [review]
thats kind of strange decision from explorer to show it as 5/100 & 50/10k instead of 5% & 0.5%

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/306#-:-NJjhjRl8CKz8PAb-tRn:b-nty10a)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`pkg/config/genesis/genesis.tmpl.json` line 197 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/306#-NJjaV-4A02PkBYjzNcH:-NJjhxvQCdtRE3zEo1yG:b32wtd) ([raw file](https://github.com/coreumfoundation/coreum/blob/34dbb8b84d158fc90122d7798c88728a1502cf99/pkg/config/genesis/genesis.tmpl.json#L197)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

I put values discussed and proposed by Reza (See table in the comment section) https://app.clickup.com/t/33nm1fy
</blockquote></details>

ok

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/306#-:-NJjqHfi71n6nH7lGvEH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @wojtek-coreum)

___
*[`pkg/config/genesis/genesis.tmpl.json` line 198 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/306#-NJjq4TN3VsdOlQNsVwU:-NJjq4TN3VsdOlQNsVwV:bmlvlp5) ([raw file](https://github.com/coreumfoundation/coreum/blob/34dbb8b84d158fc90122d7798c88728a1502cf99/pkg/config/genesis/genesis.tmpl.json#L198)):*
> ```JSON
>     "slashing": {
>       "params": {
>         "signed_blocks_window": "34000",
> ```

I see no reason to make this configurable per network, so I will not block this. Just FYI we sometimes make these configurable per network.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/306)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

___
*[`pkg/config/genesis/genesis.tmpl.json` line 198 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/306#-NJjq4TN3VsdOlQNsVwU:-NJjui7iACwwFE2bU63X:bswszyd) ([raw file](https://github.com/coreumfoundation/coreum/blob/34dbb8b84d158fc90122d7798c88728a1502cf99/pkg/config/genesis/genesis.tmpl.json#L198)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I see no reason to make this configurable per network, so I will not block this. Just FYI we sometimes make these configurable per network. 
</blockquote></details>

Let's do it once we find use case. :-)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/306)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
