### PR TITLE
changed default gas-adjustment in cli to 1.1

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/354)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/354)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`cmd/cored/cosmoscmd/gas_price.go` line 64 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/354#-NMDGjrqECODH8C_Kwnv:-NMDGjrr4G3w1SHyxaRU:bob8jmx) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d60342406dea18a9a8a50785ef7dec89fd11c4a2/cmd/cored/cosmoscmd/gas_price.go#L64)):*
> ```Go
> 
> 	if !gasAdjustmentFlag.Changed {
> 		if err := gasAdjustmentFlag.Value.Set("1.1"); err != nil {
> ```

Better to move it to constant

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/354)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/354)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`cmd/cored/cosmoscmd/gas_price.go` line 64 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/354#-NMDGjrqECODH8C_Kwnv:-NMDh1Gm0j7udc0DpnRS:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d60342406dea18a9a8a50785ef7dec89fd11c4a2/cmd/cored/cosmoscmd/gas_price.go#L64)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Better to move it to constant
</blockquote></details>

Done.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/354)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/354)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
