### PR TITLE
Added validate precision and subunit

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/380)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/380)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/ft/types/token.go` line 98 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/380#-NNfudRo31j5VfHYxcE3:-NNfudRo31j5VfHYxcE4:b-nd5g1l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0f2c63e4075708d8f08b25f557b714bf6aa8e051/x/asset/ft/types/token.go#L98)):*
> ```Go
> // ValidatePrecision checks the provided precision is valid.
> func ValidatePrecision(precision uint32) error {
> 	if precision == 0 || precision > maxPrecision {
> ```

precision 0 is a pretty valid usecase

**Review by miladz68 — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/380#-:-NNkOQBQ3D5AF1agrgx-:bb6un1j)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/types/token.go` line 98 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/380#-NNfudRo31j5VfHYxcE3:-NNkO19L64a2uObm2qZj:bwt0btp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/0f2c63e4075708d8f08b25f557b714bf6aa8e051/x/asset/ft/types/token.go#L98)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do we handle a case with zero precision? Seems like we don't need to add additional denom to the metadata in that case.
</blockquote></details>

precision 0 is not supported by cosmos sdk, if we want to regsiter with bank metatdata, a precision higher than zero must be provided.

**Review by wojtek-coreum — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/380)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/380)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/380)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Pull request merged**
