### PR TITLE
In determgas/ante charge Fixed before Bonus & improve descriptor text

### PR DESCRIPTION
**Pull request by ysv**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/744)

### CODE REVIEW

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/744)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`x/deterministicgas/ante/ante.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/744#-NlP5xJH2NCdaFeNoM8p:-NlP5xJH2NCdaFeNoM8q:bort6uc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/03abab279ffacde5858b8a5955cdc34ab42d9a95/x/deterministicgas/ante/ante.go#L31)):*
> ```Go
> 	// fee charged on the real gas meter in `ChargeFixedGasDecorator`. This will save resources on running
> 	// preliminary ante decorators.
> 	ctx.GasMeter().ConsumeGas(sigmd.deterministicGasConfig.FixedGas, "Fixed: signature verification and tx size")
> ```

improved text a bit so it is more clear, bc Nick was confused before
___
*[`x/deterministicgas/ante/ante.go` line 113 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/744#-NlP5n6N1HqX6TnzAmrW:-NlP5n6N1HqX6TnzAmrX:b-j8p94b) ([raw file](https://github.com/CoreumFoundation/coreum/blob/03abab279ffacde5858b8a5955cdc34ab42d9a95/x/deterministicgas/ante/ante.go#L113)):*
> ```Go
> 	gasConsumed := ctx.GasMeter().GasConsumed()
> 	bonus := cfgd.deterministicGasConfig.TxBaseGas(params)
> 	gasMeter.ConsumeGas(cfgd.deterministicGasConfig.FixedGas, "Fixed: signature verification and tx size")
> ```

I find this sequence more logical: charge fixed gas first and only after this charge OverBonus

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/744)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/deterministicgas/ante/ante.go` line 113 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/744#-NlP5n6N1HqX6TnzAmrW:-NlRUuNd2iA18HzMW85K:btxojo4) ([raw file](https://github.com/CoreumFoundation/coreum/blob/03abab279ffacde5858b8a5955cdc34ab42d9a95/x/deterministicgas/ante/ante.go#L113)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I find this sequence more logical: charge fixed gas first and only after this charge OverBonus
</blockquote></details>

What is the difference?

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/744)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/744)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/744)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil)

___
*[`x/deterministicgas/ante/ante.go` line 113 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/744#-NlP5n6N1HqX6TnzAmrW:-NlSjLODEJyuVYVtns9L:b4xitdc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/03abab279ffacde5858b8a5955cdc34ab42d9a95/x/deterministicgas/ante/ante.go#L113)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What is the difference?
</blockquote></details>


1. Because we have `SetInfiniteGasMeterDecorator` (one of first ante) where we pseudo-charge  FixedGas. So we should follow the same logic later and charge it right away so it looks smooth for users

2. Also such logic corresponds better to our business logic:
```
If \`GasForBytes + GasForSignatures > TxBaseGas\` user will have to pay anything above \`TxBaseGas\` on top of \`FixedGas\`.
```

we always charge fixed gas first and then charge anything over bonus

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/744)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil)

**Pull request merged**
