### PR TITLE
Add NFT dynamic data proto files.

### PR DESCRIPTION
**Pull request by dzmitryhil**
# Description

Add NFT dynamic data proto files.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/794)

### CODE REVIEW

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/794)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 7 of 11 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/794)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil and @miladz68)

___
*[`docs/api.md` line 3529 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/794#-NtWcp_T09uQtQdlHYy9:-NtWcp_T09uQtQdlHYyA:bb9mx7e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60fcb260c78c531a4e0b09f5272bef2329326ba2/docs/api.md#L3529)):*
> ```Markdown
> 
> ### DataBytes
> DataBytes represent the data which can't be updated.
> ```

nit: represent immutable data



_Code quote:_
```Markdown
the data which can't be updated.
```
___
*[`docs/api.md` line 3544 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/794#-NtWcz7U3hvFMFANsoU7:-NtWcz7U3hvFMFANsoU8:b-1ar1ru) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60fcb260c78c531a4e0b09f5272bef2329326ba2/docs/api.md#L3544)):*
> ```Markdown
> 
> ### DataDynamic
> DataDynamic is dynamic data which contains the list of the items allowed to be modified base on their modification types.
> ```

nit: 
... allowed to be modified with editor permissions



_Code quote:_
```Markdown
 base on their modification types.
```
___
*[`proto/coreum/asset/nft/v1/tx.proto` line 23 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/794#-NtWdD7Q2r9zY3HWPw59:-NtWdD7Q2r9zY3HWPw5A:b-ke8eor) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60fcb260c78c531a4e0b09f5272bef2329326ba2/proto/coreum/asset/nft/v1/tx.proto#L23)):*
> ```proto
>   rpc Mint(MsgMint) returns (EmptyResponse);
>   // Update updates the existing non-fungible token in the class.
>   rpc Update(MsgUpdate) returns (EmptyResponse);
> ```

I think it should be UpdateData, because here what I expect is update for whole NFT ?

Or you mean that we might use the same msg to update other attributes in the future ?
___
*[`proto/coreum/asset/nft/v1/types.proto` line 24 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/794#-NtWdhuD6DtBM0D0oeE9:-NtWdhuD6DtBM0D0oeEA:b-d0k3au) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60fcb260c78c531a4e0b09f5272bef2329326ba2/proto/coreum/asset/nft/v1/types.proto#L24)):*
> ```proto
> // DataDynamicItem contains the updatable data and modification types.
> message DataDynamicItem {
>   // contains the set of the modification types, if empty no one can update.
> ```

it is more like permission. or authorized editors but not modification type ?



_Code quote:_
```proto
 the modification types
```
___
*[`proto/coreum/asset/nft/v1/types.proto` line 30 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/794#-NtWeG4E4AJOtEWaPUia:-NtWeG4E4AJOtEWaPUib:bc2jgd8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60fcb260c78c531a4e0b09f5272bef2329326ba2/proto/coreum/asset/nft/v1/types.proto#L30)):*
> ```proto
> 
> // DataDynamicIndexed contains the data and it's index in the DataDynamic.
> message DataDynamicIndexedItem {
> ```

nit: DataDynamicIndexedItem -> DataDynamicItemWithIndex



_Code quote:_
```proto
DataDynamicIndexedItem 
```

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/794)* status: 4 of 13 files reviewed, 4 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`docs/api.md` line 3529 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/794#-NtWcp_T09uQtQdlHYy9:-NuNFGTlCMaPMCsL9oSU:bb6un1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60fcb260c78c531a4e0b09f5272bef2329326ba2/docs/api.md#L3529)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: represent immutable data
</blockquote></details>

Done
___
*[`docs/api.md` line 3544 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/794#-NtWcz7U3hvFMFANsoU7:-NuNFSpCBSnbBzRzTUdB:btzmmem) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60fcb260c78c531a4e0b09f5272bef2329326ba2/docs/api.md#L3544)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: 
... allowed to be modified with editor permissions
</blockquote></details>

IMO the original comment is more correct
___
*[`proto/coreum/asset/nft/v1/tx.proto` line 23 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/794#-NtWdD7Q2r9zY3HWPw59:-NuNG0-l5aOPMe_b0bjA:b-8ezbo2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60fcb260c78c531a4e0b09f5272bef2329326ba2/proto/coreum/asset/nft/v1/tx.proto#L23)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I think it should be UpdateData, because here what I expect is update for whole NFT ?

Or you mean that we might use the same msg to update other attributes in the future ?
</blockquote></details>

Agree, updated.
___
*[`proto/coreum/asset/nft/v1/types.proto` line 24 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/794#-NtWdhuD6DtBM0D0oeE9:-NuNKCUg-Rvab8TgirxF:b-8ezbo2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60fcb260c78c531a4e0b09f5272bef2329326ba2/proto/coreum/asset/nft/v1/types.proto#L24)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

it is more like permission. or authorized editors but not modification type ?
</blockquote></details>

Agree, updated.
___
*[`proto/coreum/asset/nft/v1/types.proto` line 30 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/794#-NtWeG4E4AJOtEWaPUia:-NuNKHCJ4mC8z7xanzQU:b11m3le) ([raw file](https://github.com/CoreumFoundation/coreum/blob/60fcb260c78c531a4e0b09f5272bef2329326ba2/proto/coreum/asset/nft/v1/types.proto#L30)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: DataDynamicIndexedItem -> DataDynamicItemWithIndex
</blockquote></details>

IMO current name is better

**Review by ysv — APPROVED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/794)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/794)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @miladz68)

___
*[`proto/coreum/asset/nft/v1/types.proto` line 11 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/794#-NuY3dNJCdMv7yQfqCK5:-NuY3dNK9jx-otmnK0GS:bls5isc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f7e07656604fe47778dd7c7e2d88b2d5e8bf259a/proto/coreum/asset/nft/v1/types.proto#L11)):*
> ```proto
> // DataEditor defines possible data editors.
> enum DataEditor {
>   admin = 0;
> ```

How/Where is the permitted admin address specified?

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/794)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

___
*[`proto/coreum/asset/nft/v1/types.proto` line 11 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/794#-NuY3dNJCdMv7yQfqCK5:-NuYqd-P8fWCFT8_ypcM:b81ynjd) ([raw file](https://github.com/CoreumFoundation/coreum/blob/f7e07656604fe47778dd7c7e2d88b2d5e8bf259a/proto/coreum/asset/nft/v1/types.proto#L11)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

How/Where is the permitted admin address specified?
</blockquote></details>

admin is issuer now, here I call it admin since we plan to migrate to admin during this phase

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/794)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @miladz68)

**Pull request merged**
