### PR TITLE
Refactor DeterministicGasRequirements & add more tests

### PR DESCRIPTION
**Pull request by ysv**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/deterministic_gas.go` line 85 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvoOFD7Stv0DXP2M-m:-NKvoOFD7Stv0DXP2M-n:bfhxaoh) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L85)):*
> ```Go
> 
> 		// staking
> 		MsgName(&stakingtypes.MsgDelegate{}):        constGasFunc(51000),
> ```

Let's use the full names for `underm` and `const` for the functions..] 
___
*[`pkg/config/deterministic_gas.go` line 92 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvoOcWB3A30SPcdV50:-NKvoOcWB3A30SPcdV51:bwdx1ix) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L92)):*
> ```Go
> 
> 		// wasm
> 		MsgName(&wasmtypes.MsgExecuteContract{}): undermGasFunc(),
> ```

What with the other wasm messages?
___
*[`pkg/config/deterministic_gas.go` line 128 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvooHm1wwFUbXbad1p:-NKvooHm1wwFUbXbad1q:betdwt3) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L128)):*
> ```Go
> 
> // NOTE: we need to pass DeterministicGasRequirements by pointer here because
> // it needs initialized later map with all msg types inside to estimate gas recursively.
> ```

to be initialized
___
*[`pkg/config/deterministic_gas.go` line 129 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvoikKCdIRInMZ4Y6S:-NKvoikKCdIRInMZ4Y6T:b-zalbln) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L129)):*
> ```Go
> // NOTE: we need to pass DeterministicGasRequirements by pointer here because
> // it needs initialized later map with all msg types inside to estimate gas recursively.
> func autzMsgExecGasFunc(authzMsgExecOverhead uint64, dgr *DeterministicGasRequirements) gasByMsgFunc {
> ```

Why that func isn't a method ?
Try:
```
func (dgr *DeterministicGasRequirements) autzMsgExecGasFunc(authzMsgExecOverhead uint64) gasByMsgFunc {
```

And 
```
MsgName(&authz.MsgExec{}):   dgr.autzMsgExecGasFunc(2000),
```
___
*[`pkg/config/deterministic_gas.go` line 190 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvnrf08oKrc5RTuAju:-NKvnrf08oKrc5RTuAjv:bbp8ykv) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L190)):*
> ```Go
> // "/cosmos.distribution.v1beta1.MsgFundCommunityPool"
> // "/coreum.asset.ft.v1.MsgMint"
> func MsgName(msg sdk.Msg) string {
> ```

IMO It's easier to read if funcs ordre is: 
* Exported Method 
* Unexported methods 
* Exported Functions 
* Unexported functions 

And sub ordering is call stack.

I would actually recommend to use it everywhere, we disuc :-)

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)* status: all files reviewed, 4 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`pkg/config/deterministic_gas.go` line 58 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKw2hOV45EaGwuUKLys:-NKw2hOV45EaGwuUKLyt:betdk0y) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L58)):*
> ```Go
> 
> 		// authz
> 		MsgName(&authz.MsgExec{}):   autzMsgExecGasFunc(2000, &dgr),
> ```

autz->authz
___
*[`pkg/config/deterministic_gas.go` line 112 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKw4jHrAF1DsJzdQa8R:-NKw4jHrAF1DsJzdQa8S:bj5uf08) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L112)):*
> ```Go
> 	}
> 	// Unknown message.
> 	return 0, false
> ```

Shouldn't it panic in this case? We have a unit test ensuring that all the messages are specified. So if program is here it means sth went wrong
___
*[`pkg/config/deterministic_gas.go` line 190 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKw5Z-6242nUVbGSOAC:-NKw5Z-6242nUVbGSOAD:b-ha8swe) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L190)):*
> ```Go
> // "/cosmos.distribution.v1beta1.MsgFundCommunityPool"
> // "/coreum.asset.ft.v1.MsgMint"
> func MsgName(msg sdk.Msg) string {
> ```

why do we need this function instead of calling `sdk.MsgTypeURL` directly?

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`pkg/config/deterministic_gas.go` line 55 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKsrlSBCU4MK_R9d7bM:-NKsrlSBCU4MK_R9d7bN:b2t5hq7) ([raw file](https://github.com/coreumfoundation/coreum/blob/9be8080e9989de769fe5a8638765555384f49b5c/pkg/config/deterministic_gas.go#L55)):*
> ```Go
> 
> 		// authz
> 		MsgName(&authz.MsgExec{}):   autzMsgExecGasFunc(2000, &gr),
> ```

Note that I used approach you proposed to pass functions here. And to make it work for `authz.MsgExec` I had to make this trick with passing struct by pointer since we need this function on struct initialization while it uses the same struct
___
*[`pkg/config/deterministic_gas.go` line 58 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKw2hOV45EaGwuUKLys:-NKzQqJ96zgCQcAXyMUR:bb7f2mf) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L58)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

autz->authz
</blockquote></details>

done
___
*[`pkg/config/deterministic_gas.go` line 85 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvoOFD7Stv0DXP2M-m:-NKzQyzW8vzH5EsaIXFD:b-hff6wv) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L85)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's use the full names for `underm` and `const` for the functions..] 
</blockquote></details>

renamed
___
*[`pkg/config/deterministic_gas.go` line 92 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvoOcWB3A30SPcdV50:-NKzR-z_DAeu-eTouZFO:b-jukp5o) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L92)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

What with the other wasm messages?
</blockquote></details>

there are a few other WASM msgs like SetContractAdmin etc
Since we have integration of x/wasm module by Milad he is supposed to add them here
I just keep one undeterministic message fully integrated here as an example
___
*[`pkg/config/deterministic_gas.go` line 112 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKw4jHrAF1DsJzdQa8R:-NKzR_qR6bRrcEBdXJWs:b-x35ada) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L112)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Shouldn't it panic in this case? We have a unit test ensuring that all the messages are specified. So if program is here it means sth went wrong
</blockquote></details>

good point
I hate having panics anywhere in code but here it sounds more or less reasonable IMO

Another approach I could advice is to add one more bool return param which identifies if msg is known. If smth wrong happens we can treat it as undeterministic instead of failure but report issue somewhere.

Don't have strong opinion of none of approaches WDYT @dzmitryhil @miladz68 ?
___
*[`pkg/config/deterministic_gas.go` line 128 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvooHm1wwFUbXbad1p:-NKzS6HrBvBCXZt7nbSZ:bb7f2mf) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L128)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

to be initialized
</blockquote></details>

done



_Code quote:_
```Go
needs initialized later map wi
```
___
*[`pkg/config/deterministic_gas.go` line 129 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvoikKCdIRInMZ4Y6S:-NKzS8sE7ZXq6ONpAPnJ:b-bj1heh) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L129)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why that func isn't a method ?
Try:
```
func (dgr *DeterministicGasRequirements) autzMsgExecGasFunc(authzMsgExecOverhead uint64) gasByMsgFunc {
```

And 
```
MsgName(&authz.MsgExec{}):   dgr.autzMsgExecGasFunc(2000),
```

</blockquote></details>

yes I thought about making it a method but then linter complains that we mix pointer & non-pointer receivers. 
And I don't really think it is reasonalbe change it to pointer receiver everywhere because of this

If you want I can change it according to your suggestion
___
*[`pkg/config/deterministic_gas.go` line 190 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvnrf08oKrc5RTuAju:-NKzShdN3l_M5GUv_E8z:b208nvv) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L190)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO It's easier to read if funcs ordre is: 
* Exported Method 
* Unexported methods 
* Exported Functions 
* Unexported functions 

And sub ordering is call stack.

I would actually recommend to use it everywhere, we disuc :-)
</blockquote></details>

agree moved
It was unexported initially actually )
___
*[`pkg/config/deterministic_gas.go` line 190 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKw5Z-6242nUVbGSOAC:-NKzSkjME0Tnn55Q5R4F:b5o14p7) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L190)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why do we need this function instead of calling `sdk.MsgTypeURL` directly?
</blockquote></details>

1 because initially I used proto.MessageName & after Dmitry's suggestions I had to replace 10 places instead of one. So I decided to centralized it so we can easily change it later
2 it is shorter
3 reused in tests

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`pkg/config/deterministic_gas.go` line 92 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvoOcWB3A30SPcdV50:-NKzTVJG78wrZUNK0qDN:bnjb2n1) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L92)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

there are a few other WASM msgs like SetContractAdmin etc
Since we have integration of x/wasm module by Milad he is supposed to add them here
I just keep one undeterministic message fully integrated here as an example
</blockquote></details>

added todo to Milad's ticket
___
*[`pkg/config/deterministic_gas.go` line 129 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvoikKCdIRInMZ4Y6S:-NKzTmbT0xjsltb_AdJC:b-2k9ea9) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L129)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes I thought about making it a method but then linter complains that we mix pointer & non-pointer receivers. 
And I don't really think it is reasonalbe change it to pointer receiver everywhere because of this

If you want I can change it according to your suggestion
</blockquote></details>

don't have strong preference here

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/deterministic_gas.go` line 92 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvoOcWB3A30SPcdV50:-NL5BxXz7Aebn0NtHVmX:b7llvtu) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L92)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

added todo to Milad's ticket
</blockquote></details>

But in that case all Non Deterministic message should be added as a list, not one by one.
___
*[`pkg/config/deterministic_gas.go` line 112 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKw4jHrAF1DsJzdQa8R:-NL5CE4G2VfDBi_D2yfx:b-h4fpg7) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L112)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

good point
I hate having panics anywhere in code but here it sounds more or less reasonable IMO

Another approach I could advice is to add one more bool return param which identifies if msg is known. If smth wrong happens we can treat it as undeterministic instead of failure but report issue somewhere.

Don't have strong opinion of none of approaches WDYT @dzmitryhil @miladz68 ?
</blockquote></details>

The changes of the panic is really low, but I don't like the panics, so would prefer to use an undeterministc instead.
___
*[`pkg/config/deterministic_gas.go` line 129 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvoikKCdIRInMZ4Y6S:-NL5CVWDBE4Vhnl7uqFi:b-x64tns) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L129)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

don't have strong preference here
</blockquote></details>

As for me it looks better, since you don't provided that point directly.

**Review by ysv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`pkg/config/deterministic_gas.go` line 92 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvoOcWB3A30SPcdV50:-NL5uUhLBEqSjKVPX7RH:b-wwrdvp) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L92)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But in that case all Non Deterministic message should be added as a list, not one by one.
</blockquote></details>

ok I see
I've added all wasm messages as undeterministic for now but still left todo for Milad to rewise
Because I think that some maybe even most  could be changed to deterministic
___
*[`pkg/config/deterministic_gas.go` line 112 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKw4jHrAF1DsJzdQa8R:-NL5w8GY7XBxzNBJX6bf:b82x6q) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L112)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The changes of the panic is really low, but I don't like the panics, so would prefer to use an undeterministc instead.
</blockquote></details>

Agree
I prefer to keep it as it is now without panic and 3rd param and change it if needed
___
*[`pkg/config/deterministic_gas.go` line 129 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvoikKCdIRInMZ4Y6S:-NL6-ASY-2qP_wrLJhoM:bb7xr4x) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L129)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

As for me it looks better, since you don't provided that point directly.
</blockquote></details>

ok done

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/deterministic_gas.go` line 92 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKvoOcWB3A30SPcdV50:-NLKWhNKD2LKkcYWFeSA:b-nfebyf) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L92)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok I see
I've added all wasm messages as undeterministic for now but still left todo for Milad to rewise
Because I think that some maybe even most  could be changed to deterministic
</blockquote></details>

All is good now, but move the `// wasm wasm` comment above the messages not the func.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`pkg/config/deterministic_gas_test.go` line 46 at r5](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NLKX75mBeRgUEO4eSHp:-NLKX75mBeRgUEO4eSHq:b-421n2h) ([raw file](https://github.com/coreumfoundation/coreum/blob/6595ff348dc482d28e00c4a0989c2c14162f94d6/pkg/config/deterministic_gas_test.go#L46)):*
> ```Go
> 
> 	// WASM messages will be added here
> 	undetermMsgPrefixes := []string{
> ```

Why do we need it here, if you have already included them? And what will happen if a new message will be introduced?



_Code quote:_
```Go
undetermMsgPrefixes
```

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @wojtek-coreum)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 2 of 3 files at r3, 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

___
*[`pkg/config/deterministic_gas.go` line 112 at r2](https://reviewable.io/reviews/coreumfoundation/coreum/328#-NKw4jHrAF1DsJzdQa8R:-NLML84cCnPNwROrmNSG:b-hqco8l) ([raw file](https://github.com/coreumfoundation/coreum/blob/937a81ce5dc346bf29baa74f02f524aa82f17829/pkg/config/deterministic_gas.go#L112)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Agree
I prefer to keep it as it is now without panic and 3rd param and change it if needed
</blockquote></details>

I think we should keep it as is.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/328)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
