### PR TITLE
Uncomment and fix staking tests

### PR DESCRIPTION
**Pull request by vertex451**
# Description
Task: https://app.clickup.com/t/8685bq8g4

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/623)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/623)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @vertex451, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/staking_test.go` line 92 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/623#-NcXW8G9BA5ueLQPzNYP:-NcXW8GA7vjn1pGuKx2B:bpkghfs) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e27f101399ce7c248a4e0671a65d2410db4b156/integration-tests/modules/staking_test.go#L92)):*
> ```Go
> 
> //nolint:dupword //temp nolint
> /*
> ```

this one test should also be uncommented and fixed.

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/623)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/staking_test.go` line 92 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/623#-NcXW8G9BA5ueLQPzNYP:-NcXXFIh-1U-rzL-TFfw:bauw5r5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e27f101399ce7c248a4e0671a65d2410db4b156/integration-tests/modules/staking_test.go#L92)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this one test should also be uncommented and fixed.
</blockquote></details>

It is out of scope of this task, and this is being fix by @wojtek-coreum I guess (https://app.clickup.com/t/868570r6e)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/623)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @vertex451, and @ysv)

___
*[`integration-tests/modules/staking_test.go` line 47 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/623#-NcaRkLA0kdVB2iH_O80:-NcaRkLA0kdVB2iH_O81:b-gqn5m2) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e27f101399ce7c248a4e0671a65d2410db4b156/integration-tests/modules/staking_test.go#L47)):*
> ```Go
> 	// Since all parameters must be supplied for MsgUpdateParams, we update current staking params and pass it to the proposal
> 	targetMaxValidators := 2 * resp.Params.MaxValidators // Let's increase MaxValidators
> 	resp.Params.MaxValidators = targetMaxValidators
> ```

It would be beneficial to modify all the params this way and verify at the end that they all are updated
___
*[`integration-tests/modules/staking_test.go` line 92 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/623#-NcXW8G9BA5ueLQPzNYP:-NcaSCMwEcg52eRRG9Gq:b-6iyrx7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e27f101399ce7c248a4e0671a65d2410db4b156/integration-tests/modules/staking_test.go#L92)):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>

It is out of scope of this task, and this is being fix by @wojtek-coreum I guess (https://app.clickup.com/t/868570r6e)
</blockquote></details>

There is no separate FIXME describing the problem here. I don't think it is related to deterministic gas. Please at least ensure that there is a task for this one.

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/623)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @vertex451, and @ysv)

___
*[`integration-tests/modules/staking_test.go` line 92 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/623#-NcXW8G9BA5ueLQPzNYP:-NcaYHPw7HWBqNgLA5lY:bd9twhi) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e27f101399ce7c248a4e0671a65d2410db4b156/integration-tests/modules/staking_test.go#L92)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

There is no separate FIXME describing the problem here. I don't think it is related to deterministic gas. Please at least ensure that there is a task for this one.
</blockquote></details>

this test was commented out since it includes param changes to staking. it should be fixed under the same task/PR.

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/623)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/staking_test.go` line 92 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/623#-NcXW8G9BA5ueLQPzNYP:-NcaYl4000Q9h9yMAZJZ:bfk9s0t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e27f101399ce7c248a4e0671a65d2410db4b156/integration-tests/modules/staking_test.go#L92)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this test was commented out since it includes param changes to staking. it should be fixed under the same task/PR.
</blockquote></details>

Okay, fixing it.

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/623)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/staking_test.go` line 47 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/623#-NcaRkLA0kdVB2iH_O80:-Ncb8Fci5T_j8Ip5p0eQ:b6uh3to) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e27f101399ce7c248a4e0671a65d2410db4b156/integration-tests/modules/staking_test.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It would be beneficial to modify all the params this way and verify at the end that they all are updated
</blockquote></details>

Added all params except denom change(because of invalid denom error)

**Review by wojtek-coreum — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/623)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by vertex451 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/623)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`integration-tests/modules/staking_test.go` line 92 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/623#-NcXW8G9BA5ueLQPzNYP:-NcbMvxlBi0c45X9MHLC:b-cbjxi5) ([raw file](https://github.com/CoreumFoundation/coreum/blob/6e27f101399ce7c248a4e0671a65d2410db4b156/integration-tests/modules/staking_test.go#L92)):*
<details><summary><i>Previously, vertex451 (Artem) wrote…</i></summary><blockquote>

Okay, fixing it.
</blockquote></details>

Test is uncommented and fixed

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/623)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/623)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Pull request merged**
