### PR TITLE
Testing transfers to non-whitelisted smart contract

### PR DESCRIPTION
**Pull request by wojtek-coreum**
# Description

Funds might be transferred to smart contract in 3 ways:
1. regular bank send
2. smart contract call
3. smart contract instantiation

In this PR, tests are added to verify that in all 3 cases transfer fails if smart contract is not whitelisted.

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/676)

### CODE REVIEW

**Review by ysv — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/676)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`integration-tests/modules/assetft_test.go` line 2387 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/676#-Nh6f4LI9v6BA-ycpmJD:-Nh6f4LI9v6BA-ycpmJE:b-sp0l5l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/d0769ba17aa4158ccd3af673628fd0c85dd696ec/integration-tests/modules/assetft_test.go#L2387)):*
> ```Go
> // TestAssetFTSendingToNonWhitelistedSmartContractIsDenied verifies that this is not possible to send token to smart contract
> // if it is not whitelisted.
> func TestAssetFTSendingToNonWhitelistedSmartContractIsDenied(t *testing.T) {
> ```

nit: I would squash these 3 into a single test since they test similar functionality and this will reduce amount of code significantly

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/676)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68 and @wojtek-coreum)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/676)* status: all files reviewed, 3 unresolved discussions (waiting on @wojtek-coreum)

___
*[`integration-tests/modules/assetft_test.go` line 2453 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/676#-NhB3t1L-ZUCkY6nJiti:-NhB3t1M2a4MxpEewHqo:b-zh4feh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bea5ecd4e84aa13bc266595f9fadf3890ce5ea23/integration-tests/modules/assetft_test.go#L2453)):*
> ```Go
> 	}
> 	_, err = client.BroadcastTx(ctx, clientCtx.WithFromAddress(issuer), txf, sendMsg)
> 	requireT.Error(err)
> ```

assert error type.
___
*[`integration-tests/modules/assetft_test.go` line 2520 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/676#-NhB3vta-1Qb6DC50TVZ:-NhB3vta-1Qb6DC50TV_:b-ab5b7d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bea5ecd4e84aa13bc266595f9fadf3890ce5ea23/integration-tests/modules/assetft_test.go#L2520)):*
> ```Go
> 	requireT.NoError(err)
> 	_, err = chain.Wasm.ExecuteWASMContract(ctx, txf, issuer, contractAddr, incrementPayload, sdk.NewInt64Coin(denom, 100))
> 	requireT.Error(err)
> ```

assert error type
___
*[`integration-tests/modules/assetft_test.go` line 2583 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/676#-NhB3xSr2pIBJo4VLI-K:-NhB3xSr2pIBJo4VLI-L:b-ab5b7d) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bea5ecd4e84aa13bc266595f9fadf3890ce5ea23/integration-tests/modules/assetft_test.go#L2583)):*
> ```Go
> 		},
> 	)
> 	requireT.Error(err)
> ```

assert error type

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/676)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2453 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/676#-NhB3t1L-ZUCkY6nJiti:-NhBbZWI2gOIgy9fJSK0:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f311bb95a93355c0de76c4d5a08fe0e307caa05/integration-tests/modules/assetft_test.go#L2453)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

assert error type.
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetft_test.go` line 2520 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/676#-NhB3vta-1Qb6DC50TVZ:-NhBbZom3q_HOetfWjX-:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f311bb95a93355c0de76c4d5a08fe0e307caa05/integration-tests/modules/assetft_test.go#L2520)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

assert error type
</blockquote></details>

Done.
___
*[`integration-tests/modules/assetft_test.go` line 2583 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/676#-NhB3xSr2pIBJo4VLI-K:-NhBb_L9BO_91tirfFex:b-896fix) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f311bb95a93355c0de76c4d5a08fe0e307caa05/integration-tests/modules/assetft_test.go#L2583)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

assert error type
</blockquote></details>

Done.

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/676)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @miladz68 and @ysv)

___
*[`integration-tests/modules/assetft_test.go` line 2453 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/676#-NhB3t1L-ZUCkY6nJiti:-NhC8q-x5xT9Ee2v1Ru0:b-jz1nra) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f311bb95a93355c0de76c4d5a08fe0e307caa05/integration-tests/modules/assetft_test.go#L2453)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You should be able to assert `ErrWhitelistedLimitExceeded` type not  string (same in other places).

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/676)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68)

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/676)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68)

___
*[`integration-tests/modules/assetft_test.go` line 2453 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/676#-NhB3t1L-ZUCkY6nJiti:-NhCBWg4DGoY6AL6wfoF:b-hiqlwb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f311bb95a93355c0de76c4d5a08fe0e307caa05/integration-tests/modules/assetft_test.go#L2453)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You should be able to assert `ErrWhitelistedLimitExceeded` type not  string (same in other places).
</blockquote></details>

no, because errors are returned from simulation, and those errors are not typed

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/676)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/676)* status: all files reviewed, 3 unresolved discussions (waiting on @miladz68)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/676)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil)

___
*[`integration-tests/modules/assetft_test.go` line 2453 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/676#-NhB3t1L-ZUCkY6nJiti:-NhQTcAL6bg5raj0obaa:b6bmmch) ([raw file](https://github.com/CoreumFoundation/coreum/blob/4f311bb95a93355c0de76c4d5a08fe0e307caa05/integration-tests/modules/assetft_test.go#L2453)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

no, because errors are returned from simulation, and those errors are not typed
</blockquote></details>

but it is not a simultaion !

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/676)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

**Pull request merged**
