### PR TITLE
Integrate vesting module.

### PR DESCRIPTION
**Pull request by dzmitryhil**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/360)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/360)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/vesting_test.go` line 37 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMZRQ03-UhinZG5VVXw:-NMZRQ03-UhinZG5VVXx:b-kdvjdr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e26a89585687963c2c2a70b0f453fb59b97524b4/integration-tests/modules/vesting_test.go#L37)):*
> ```Go
> 	bankClient := banktypes.NewQueryClient(chain.ClientContext)
> 
> 	amountToVest := sdk.NewInt(100)
> ```

I see that you test it with CORE only and theoretically there should be no big difference between core & asset FT. 
But I would prefer to have at least one test with issued FT just in case and since we can't use issued FT in staking I think that here we should use it.
Or maybe if you plan to add a separate test with FT & whitelisting/freezing I'm ok to keep core here. But FT should be used in at least one place
___
*[`integration-tests/modules/vesting_test.go` line 67 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMZPkdm88WgTRN4AnhD:-NMZPkdn8aiVFpuWpZhH:b8dl8la) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e26a89585687963c2c2a70b0f453fb59b97524b4/integration-tests/modules/vesting_test.go#L67)):*
> ```Go
> 	})
> 	requireT.NoError(err)
> 	requireT.Equal("/cosmos.vesting.v1beta1.DelayedVestingAccount", accountRes.Account.TypeUrl)
> ```

does this mean that we can convert `accountRes.Account` to `vestingtypes.DelayedVestingAccount` type ?
if we can it would be nice to test this and assert some other fields.

It is mostly for purpose of understanding how it works because I see that 
`  repeated google.protobuf.Any accounts = 1 [(cosmos_proto.accepts_interface) = "AccountI"];`
accounts in an interface
___
*[`integration-tests/modules/vesting_test.go` line 136 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMZQqAf96I-lS7v1ENF:-NMZQqAf96I-lS7v1ENG:b2pm4ub) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e26a89585687963c2c2a70b0f453fb59b97524b4/integration-tests/modules/vesting_test.go#L136)):*
> ```Go
> 	}))
> 
> 	versingDuration := 10 * time.Second
> ```

typo: vesting
___
*[`integration-tests/modules/vesting_test.go` line 204 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMZTIEe8egnrZU4oBgt:-NMZTIEe8egnrZU4oBgu:bcl1xhl) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e26a89585687963c2c2a70b0f453fb59b97524b4/integration-tests/modules/vesting_test.go#L204)):*
> ```Go
> 
> // TestVestingAccountWithFTInteraction tests that vesting accounts correctly work with the ft assets.
> func TestVestingAccountWithFTInteraction(t *testing.T) {
> ```

There shouldn't be any difference in case of issuing asset from vesting acc and I guess we don't need to test it, do we ?
___
*[`integration-tests/modules/vesting_test.go` line 253 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMZSR8T4q9fn_Juj0dt:-NMZSR8T4q9fn_Juj0du:b2pm4ub) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e26a89585687963c2c2a70b0f453fb59b97524b4/integration-tests/modules/vesting_test.go#L253)):*
> ```Go
> 	denom := assetfttypes.BuildDenom(issueMsg.Subunit, issuer)
> 
> 	versingDuration := 10 * time.Second
> ```

typo: vesting

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/360)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`integration-tests/modules/vesting_test.go` line 67 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMZPkdm88WgTRN4AnhD:-NMcedOS2dXh1SPCNyHb:bsky1qn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/e26a89585687963c2c2a70b0f453fb59b97524b4/integration-tests/modules/vesting_test.go#L67)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

We can't convert, we can cast in the go code. So the accounts accepts any proto, but then the basic validation checks that the object implements the `AccountI`. Theoretially you can pass any implementation of the `AccountI` here. But the `msg handler` will ignore it for sure, and maybe the basic validation won't allow it as well.
</blockquote></details>

I'm just interested if it is possible to cast  response `accountRes.Account` to `type vestingtypes.DelayedVestingAccount` ?
And how we can do it ?

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/360)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68, @silverspase, and @wojtek-coreum)

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/360)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @silverspase)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/360)* status: all files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @silverspase)

___
*[`integration-tests/modules/vesting_test.go` line 89 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMhnbZj644xmvDtrZEy:-NMhnbZk6WpbW5w6f2SA:bxwkgke) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9b537a455ed83ce3cfdc0715c7114f479ed591c/integration-tests/modules/vesting_test.go#L89)):*
> ```Go
> 	}
> 
> 	// try to send full amount from vesting account before delay is ended
> ```

this is a candidate for random failures because you can't guarantee that 10s hasn't passed already
___
*[`integration-tests/modules/vesting_test.go` line 99 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMhnPNi7miqGS-ww449:-NMhnPNi7miqGS-ww44A:b-6dzxeg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9b537a455ed83ce3cfdc0715c7114f479ed591c/integration-tests/modules/vesting_test.go#L99)):*
> ```Go
> 
> 	// await vesting time to unlock the vesting coins
> 	<-time.After(vestingDuration)
> ```

```go
select {
case <-ctx.Done():
  return
case <-time.After(vestingDuration):
}
```

so test exits immediately f it's canceled
___
*[`integration-tests/modules/vesting_test.go` line 102 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMhnCqSCb_D8hEJxanC:-NMhnCqT91jjDDQ66bYG:b-mktdwn) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9b537a455ed83ce3cfdc0715c7114f479ed591c/integration-tests/modules/vesting_test.go#L102)):*
> ```Go
> 
> 	// fund the vesting account to pay fees one more time
> 	requireT.NoError(chain.Faucet.FundAccountsWithOptions(ctx, vestingAcc, integrationtests.BalancesOptions{
> ```

please do it once for both `MsgSend`, optimally at the beginning of the test, together with the other account
___
*[`integration-tests/modules/vesting_test.go` line 136 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMhnzkHAuipVyhWaEMo:-NMhnzkHAuipVyhWaEMp:b87onf0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9b537a455ed83ce3cfdc0715c7114f479ed591c/integration-tests/modules/vesting_test.go#L136)):*
> ```Go
> 	}))
> 
> 	vestingDuration := 10 * time.Second
> ```

this should be huge like 100h to be sure that you delegate before tokens are vested
___
*[`integration-tests/modules/vesting_test.go` line 155 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMhoElhAxrLz8ajesxP:-NMhoElhAxrLz8ajesxQ:b-6b6cev) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9b537a455ed83ce3cfdc0715c7114f479ed591c/integration-tests/modules/vesting_test.go#L155)):*
> ```Go
> 	requireT.Equal(uint64(txRes.GasUsed), chain.GasLimitByMsgs(createAccMsg))
> 
> 	// check that account is created and it is vesting account
> ```

the first test already ensures that it works
___
*[`integration-tests/modules/vesting_test.go` line 162 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMhoHcK-9_6fhJ86BkV:-NMhoHcLDbclj-1EEqQ_:b-6b6cev) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9b537a455ed83ce3cfdc0715c7114f479ed591c/integration-tests/modules/vesting_test.go#L162)):*
> ```Go
> 	requireT.Equal("/cosmos.vesting.v1beta1.ContinuousVestingAccount", accountRes.Account.TypeUrl)
> 
> 	// check that the balance is full
> ```

the first test already ensures that it works
___
*[`integration-tests/modules/vesting_test.go` line 170 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMhoKINETGEqGk6kbNN:-NMhoKINETGEqGk6kbNO:b-pitmt6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9b537a455ed83ce3cfdc0715c7114f479ed591c/integration-tests/modules/vesting_test.go#L170)):*
> ```Go
> 	requireT.Equal(vestingCoin.String(), balanceRes.Balance.String())
> 
> 	// fund the vesting account to pay fees for the staking
> ```

do it at the beginning
___
*[`integration-tests/modules/vesting_test.go` line 193 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMhoesW6w_zBHupDvd_:-NMhoesW6w_zBHupDvda:b-zaxqb7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9b537a455ed83ce3cfdc0715c7114f479ed591c/integration-tests/modules/vesting_test.go#L193)):*
> ```Go
> 	}
> 
> 	// try to delegate full amount from created vesting account
> ```

You don't verify that validator has higher stake now.
And it should be done with new validator to not possibly interfere with other tests.
___
*[`integration-tests/modules/vesting_test.go` line 232 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMhovU1EmGhTKQjwqzX:-NMhovU1EmGhTKQjwqzY:by8ovo0) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9b537a455ed83ce3cfdc0715c7114f479ed591c/integration-tests/modules/vesting_test.go#L232)):*
> ```Go
> 	// issue a fungible token
> 	issueMsg := &assetfttypes.MsgIssue{
> 		Issuer:        issuer.String(),
> ```

maybe we should check that vesting account is able to issue the ft (so the issuer should be a vesting account too)
___
*[`integration-tests/modules/vesting_test.go` line 322 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMhpLXR0n4hpbU_OMx1:-NMhpLXR0n4hpbU_OMx2:b-hb1jf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9b537a455ed83ce3cfdc0715c7114f479ed591c/integration-tests/modules/vesting_test.go#L322)):*
> ```Go
> 	}))
> 
> 	// try to burn vesting locked coins
> ```

here and below: what if vesting duration has passed?
___
*[`integration-tests/modules/vesting_test.go` line 364 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMhp_PZ0Vjntq15Q-zP:-NMhp_PZ0Vjntq15Q-zQ:b-h34dpq) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9b537a455ed83ce3cfdc0715c7114f479ed591c/integration-tests/modules/vesting_test.go#L364)):*
> ```Go
> 
> 	// await vesting time to unlock the vesting coins
> 	<-time.After(vestingDuration)
> ```

select {...
___
*[`integration-tests/modules/vesting_test.go` line 375 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMhpeTCE7MBY3Ausm6W:-NMhpeTCE7MBY3Ausm6X:bwpcwyw) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9b537a455ed83ce3cfdc0715c7114f479ed591c/integration-tests/modules/vesting_test.go#L375)):*
> ```Go
> 	requireT.NoError(err)
> 
> 	// try to send unlocker coins
> ```

unlocked

**Review by miladz68 — DISMISSED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/360)* status: all files reviewed, 12 unresolved discussions (waiting on @dzmitryhil and @silverspase)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/360)* status: all files reviewed, 12 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

**Review by miladz68 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/360)* status: all files reviewed, 12 unresolved discussions (waiting on @silverspase and @wojtek-coreum)

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/360)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, and @ysv)

___
*[`integration-tests/modules/vesting_test.go` line 193 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/360#-NMhoesW6w_zBHupDvd_:-NN1-3cYA00czcT-3UPs:b9kz471) ([raw file](https://github.com/CoreumFoundation/coreum/blob/b9b537a455ed83ce3cfdc0715c7114f479ed591c/integration-tests/modules/vesting_test.go#L193)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Agree, updated.
</blockquote></details>

But you don't check that validator is really funded

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/360)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/360)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Pull request merged**
