### PR TITLE
Implemented burn authz handler

### PR DESCRIPTION
**Pull request by miladz68**
# Description
This PR intoruduces authz handler to grant burn athorization with quota.
# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [x] Provide a concise and meaningful description
- [x] Review the code yourself first, before making the PR.
- [x] Annotate your PR in places that require explanation.
- [x] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/663)

### CODE REVIEW

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/663)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/types/burn_authorization.go` line 48 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/663#-NfVnX-e7iQY7WlGePJm:-NfVnX-e7iQY7WlGePJn:bxakwnp) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bc597efab7b9e453e927891014c86f52eccdbc1e/x/asset/ft/types/burn_authorization.go#L48)):*
> ```Go
> 	}
> 
> 	if !a.BurnLimit.IsAllPositive() {
> ```

Looks like `IsAllPositive` convers the `len(a.BurnLimit) == 0` condition.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/663)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/types/burn_authorization.go` line 48 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/663#-NfVnX-e7iQY7WlGePJm:-NfjIgIW60p3okNF6Uno:bb9pvrr) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bc597efab7b9e453e927891014c86f52eccdbc1e/x/asset/ft/types/burn_authorization.go#L48)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Looks like `IsAllPositive` convers the `len(a.BurnLimit) == 0` condition.
</blockquote></details>

But I don't check the length in validate basic.

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/663)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @keyleu, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/types/burn_authorization.go` line 48 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/663#-NfVnX-e7iQY7WlGePJm:-NfjKp1i8kmIy3a3Wi7B:b3rzo0e) ([raw file](https://github.com/CoreumFoundation/coreum/blob/bc597efab7b9e453e927891014c86f52eccdbc1e/x/asset/ft/types/burn_authorization.go#L48)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

But I don't check the length in validate basic.
</blockquote></details>

I see I do it for burn and not mint. Removed.

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/663)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @keyleu, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — DISMISSED** [review]
> Reviewed 6 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/663)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu, @wojtek-coreum, and @ysv)

**Review by keyleu — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/663)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/663)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum and @ysv)

**Pull request merged**
