### PR TITLE
update readme for initial setup instructions

### PR DESCRIPTION
**Pull request by miladz68**
# Description

# Reviewers checklist:
- [ ] Try to write more meaningful comments with clear actions to be taken.
- [ ] Nit-picking should be unblocking. Focus on core issues.

# Authors checklist
- [ ] Provide a concise and meaningful description
- [ ] Review the code yourself first, before making the PR.
- [ ] Annotate your PR in places that require explanation.
- [ ] Think and try to split the PR to smaller PR if it is big.

- - -
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1049)

### CODE REVIEW

**Review by masihyeganeh — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1049)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1049)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by masihyeganeh — DISMISSED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1049)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`README.md` line 26 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/1049#-ODzp-BZ8nwHdDQw8Dj_:-ODzp-BZ8nwHdDQw8Dja:bybd9xf) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7270d65742d74c2255d59a438a19d1b451579791/README.md#L26)):*
> ```Markdown
> 
> Entire process of running local chain is automated by our tooling. The only prerequisites are:
> - `docker`, `g++` and `make` installed from your favorite package manager
> ```

I suggest to add an example here. For example `apt install build-essential` installs those and it helps users don't know how to install them

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1049)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

___
*[`README.md` line 26 at r2](https://reviewable.io/reviews/CoreumFoundation/coreum/1049#-ODzp-BZ8nwHdDQw8Dj_:-OEDnAW86ZzBEd2CMlRB:b-c1x2ll) ([raw file](https://github.com/CoreumFoundation/coreum/blob/7270d65742d74c2255d59a438a19d1b451579791/README.md#L26)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

I suggest to add an example here. For example `apt install build-essential` installs those and it helps users don't know how to install them
</blockquote></details>

that is too basic and what if someone is using dnf, nix or pacman ? we cannot support all the package managers.

**Review by masihyeganeh — DISMISSED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1049)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1049)* status: all files reviewed, 1 unresolved discussion (waiting on @masihyeganeh and @ysv)

___
*[`README.md` line 46 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/1049#-OEYMeu38uZKvFr39hk8:-OEYQkZQBx-fVpDHWDAD:b-f89q1j) ([raw file](https://github.com/CoreumFoundation/coreum/blob/57ad88d0e8574a8819196f42ab3996b7fad4f7b2/README.md#L46)):*
<details><summary><i>Previously, masihyeganeh (Masih Yeganeh) wrote…</i></summary><blockquote>

Shouldn't we run both?
```
make build
make build images
```
in some cases we even might need to run `make build/me` first
</blockquote></details>

make build images runs both commands. in this case we don't need to run build/me though.

**Review by masihyeganeh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1049)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/1049)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
