### PR TITLE
Use SDK error wrappers, part 2

### PR DESCRIPTION
**Pull request by vertex451**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)

### CODE REVIEW

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: all files reviewed, 10 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I2Np-9dt8JRoFBCa3:-N_I2Np-9dt8JRoFBCa4:bs77h39) (no related file):*
Better PR title please

___
___
*[`x/asset/nft/keeper/keeper.go` line 246 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I2Wwm7MALbymSQP5l:-N_I2Wwm7MALbymSQP5m:b4hf3si) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/asset/nft/keeper/keeper.go#L246)):*
> ```Go
> 	)
> 	if err != nil {
> 		return nil, nil, sdkerrors.Wrapf(types.ErrInvalidInput, "failed to paginate, err: %s", err)
> ```

Is ErrInvalidInput a good choice for it? Does pagination fails due to user input?
___
*[`x/asset/nft/keeper/keeper.go` line 445 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I2iFLAy-MyDReiUQn:-N_I2iFLAy-MyDReiUQo:b-i4t51g) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/asset/nft/keeper/keeper.go#L445)):*
> ```Go
> 		q, func(key, value []byte) error {
> 			if !bytes.Equal(value, asset.StoreTrue) {
> 				return sdkerrors.Wrapf(types.ErrInvalidInput, "value stored in burning store is not %x, value %x", asset.StoreTrue, value)
> ```

It's definitely not `ErrInvalidInput`
___
*[`x/asset/nft/keeper/keeper.go` line 582 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I3JbZ8cQJhDr0fLQN:-N_I3JbZ8cQJhDr0fLQO:b5nc8l) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/asset/nft/keeper/keeper.go#L582)):*
> ```Go
> 		q, func(key, value []byte) error {
> 			if !bytes.Equal(value, asset.StoreTrue) {
> 				return sdkerrors.Wrapf(sdkerrors.ErrKeyNotFound, "value stored in freezing store is not %x, value %x", asset.StoreTrue, value)
> ```

I think it should return an error comparable to what 500 Internal Server error means in http. Because it's not about key which doesn't exist. It's about the fact we destroyed our system
___
*[`x/asset/nft/keeper/keeper.go` line 638 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I3tH16mfUxYc17VhF:-N_I3tH16mfUxYc17VhG:b-79rtm7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/asset/nft/keeper/keeper.go#L638)):*
> ```Go
> 	compositeKey, err := store.JoinKeysWithLength([]byte(classID), []byte(nftID))
> 	if err != nil {
> 		return nil, nil, sdkerrors.Wrapf(types.ErrInvalidKey, err.Error())
> ```

Maybe sdkerror should be returned directly from `JoinKeysWithLength`?
___
*[`x/asset/nft/keeper/keeper.go` line 645 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I3zl73r-DzAGNuuR5:-N_I3zl73r-DzAGNuuR6:b-5acyo7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/asset/nft/keeper/keeper.go#L645)):*
> ```Go
> 		q, func(key, value []byte) error {
> 			if !bytes.Equal(value, asset.StoreTrue) {
> 				return sdkerrors.Wrapf(sdkerrors.ErrKeyNotFound, "value stored in whitelisting store is not %x, value %x", asset.StoreTrue, value)
> ```

same thing
___
*[`x/asset/nft/keeper/keeper.go` line 669 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I41SjDmz3e1o9qj6L:-N_I41SjDmz3e1o9qj6M:b-5acyo7) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/asset/nft/keeper/keeper.go#L669)):*
> ```Go
> 		q, func(key, value []byte) error {
> 			if !bytes.Equal(value, asset.StoreTrue) {
> 				return sdkerrors.Wrapf(sdkerrors.ErrKeyNotFound, "value stored in whitelisting store is not %x, value %x", asset.StoreTrue, value)
> ```

same thing
___
*[`x/delay/keeper/keeper.go` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I4bbL3AsSabBKUxUf:-N_I4bbL3AsSabBKUxUg:b-ro8s2z) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/delay/keeper/keeper.go#L63)):*
> ```Go
> 	dataAny, err := codectypes.NewAnyWithValue(data)
> 	if err != nil {
> 		return sdkerrors.Wrapf(types.ErrInvalidData, "failed to construct a new Any, err: %s", err)
> ```

a new -> new
___
*[`x/delay/keeper/keeper.go` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I4htl8P50c_fWmUV7:-N_I4htl8P50c_fWmUV8:bc7wu2x) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/delay/keeper/keeper.go#L63)):*
> ```Go
> 	dataAny, err := codectypes.NewAnyWithValue(data)
> 	if err != nil {
> 		return sdkerrors.Wrapf(types.ErrInvalidData, "failed to construct a new Any, err: %s", err)
> ```

That's funny that `NewAnyWithValue` returns sdkerror in one case, but regular error in the other one.
___
*[`x/delay/types/router.go` line 49 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I5SHiChJb10tknR7Z:-N_I5SHiChJb10tknR7_:b5q5fyc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/delay/types/router.go#L49)):*
> ```Go
> 	h, exists := rtr.routes[name]
> 	if !exists {
> 		return nil, sdkerrors.Wrapf(sdkerrors.ErrNotFound, "route %q does not exist", name)
> ```

Again, this should be more like "Internal server error" because it means that we misconfigured the system

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: all files reviewed, 13 unresolved discussions (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 496 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_IWr4T5bSMIT_H_oEu:-N_IWr4T5bSMIT_H_oEv:bedod1h) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/asset/nft/keeper/keeper.go#L496)):*
> ```Go
> // Unfreeze unfreezes a non-fungible token.
> func (k Keeper) Unfreeze(ctx sdk.Context, sender sdk.AccAddress, classID, nftID string) error {
> 	err := k.doTheFreezeChecks(ctx, sender, classID, nftID)
> ```

If you want to unify that action then add the `freeze/unfreeze` action here and bool input to untedrastand the action and return the owner to set in the event. 

Also the unexported functions should be after All Exported, that's the code style we follow.
___
*[`x/asset/nft/keeper/keeper.go` line 750 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_IY_rwACjypb2427it:-N_IY_rwACjypb2427iu:bjzsxbb) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/asset/nft/keeper/keeper.go#L750)):*
> ```Go
> }
> 
> func (k Keeper) doTheWhitelistChecks(ctx sdk.Context, classID, nftID string, sender, account sdk.AccAddress) error {
> ```

Same comment as for the freeze. 
___
*[`x/wnft/keeper/keeper.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_IYrriE2vWyMBkUDQ4:-N_IYrriE2vWyMBkUDQ5:bm38oh8) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/wnft/keeper/keeper.go#L58)):*
> ```Go
> 	})
> 	if err != nil {
> 		return nil, sdkerrors.Wrapf(types.ErrInvalidState, "can't emit EventSend event: %s", err)
> ```

This module shouldn't be touched since it's a copy for the transfer module (check the function comment), so all changed here should reverted.

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 445 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I2iFLAy-MyDReiUQn:-N_InRyj3-KbdDK1mb1F:bbbnmuk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/asset/nft/keeper/keeper.go#L445)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

My other candidate was ErrKeyNotFound, does it work for you?
</blockquote></details>

As I said in the other comment, this is the kind of situation where we realize we made a serious bug in development leading to the invalid state of the system. So it's sth like ErrDevelopersShouldBeKilled. As discussed in another thread `ErrInvalidState` is fine.
___
*[`x/asset/nft/keeper/keeper.go` line 582 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I3JbZ8cQJhDr0fLQN:-N_InkeS5OhJ2dTyvcJR:b-m1dn06) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/asset/nft/keeper/keeper.go#L582)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

in sdkerrors package, there is no good error for it. Does ErrInvalidState work for you, or we should come up with a new custom error like ErrUnexpectedCondition?
</blockquote></details>

Yea, I think `ErrInvalidState` is ok
___
*[`x/asset/nft/keeper/keeper.go` line 638 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I3tH16mfUxYc17VhF:-N_Io3kHAgMj4NcLeTL5:baa2z7w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/asset/nft/keeper/keeper.go#L638)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

I didn't find the good Error type for it in sdkerror package, which will reflect the following errors:
1. "received empty key on index %d", index
2. "key length should be max %d bytes, got %d", maxKeyLen, keyLen
ErrInvalidKey is our custom error, which is registered within a specific module, while `JoinKeysWithLength` is used in different modules.

I was thinking about registering a dedicated error at the store package, where `JoinKeysWithLength` belongs to. With `StoreCodespace` as a module name. 
WDYT about this approach?
</blockquote></details>

I think `ErrInvalidKey` should be registered as global error and used here
___
*[`x/wnft/keeper/keeper.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_IYrriE2vWyMBkUDQ4:-N_IoMlU3qNc2DbM6vdy:be2uyuv) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/wnft/keeper/keeper.go#L58)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

Reverted
</blockquote></details>

But on the other hand we want to fix all the errors. So the fact that cosmos tram does not follow their own ideas should not block us I think

**Review by miladz68 — APPROVED** [review]
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: 5 of 10 files reviewed, 14 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 745 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_J4T-n9G-N5oI3eCK8:-N_J4T-n9G-N5oI3eCK9:b-4w8pqh) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1b84741f4fa3640567baf232bd02033d9baf30c/x/asset/nft/keeper/keeper.go#L745)):*
> ```Go
> }
> 
> func (k Keeper) freezeOrUnfreeze(ctx sdk.Context, sender sdk.AccAddress, classID, nftID string, frozen bool) error {
> ```

IMO better name `frozen` -> `freeze`
___
*[`x/asset/nft/keeper/keeper.go` line 773 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_J4iXcBSPh1Co3wpKz:-N_J4iXcBSPh1Co3wpL-:bhxi0hu) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1b84741f4fa3640567baf232bd02033d9baf30c/x/asset/nft/keeper/keeper.go#L773)):*
> ```Go
> 			Owner:   owner.String(),
> 		}
> 		eventName = "EventFrozen"
> ```

IMO you can remove the evant name at all, and use %v in error: 
```
sdkerrors.Wrapf(types.ErrInvalidState, "can't emit event: %v, err: %s", event, err)
```
(same for another place)
___
*[`x/asset/nft/keeper/keeper.go` line 774 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_J4IST26Q-fDi3LZbJ:-N_J4IST26Q-fDi3LZbK:b-eoo5ea) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1b84741f4fa3640567baf232bd02033d9baf30c/x/asset/nft/keeper/keeper.go#L774)):*
> ```Go
> 		}
> 		eventName = "EventFrozen"
> 	} else {
> ```

You don't need the else here, just call that code inside the else after the if. (same for another place)
___
*[`x/asset/nft/keeper/keeper.go` line 785 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_J4ryG2qseHl0nZkF0:-N_J4ryG2qseHl0nZkF1:b3krc) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1b84741f4fa3640567baf232bd02033d9baf30c/x/asset/nft/keeper/keeper.go#L785)):*
> ```Go
> 	err = ctx.EventManager().EmitTypedEvent(event)
> 	if err != nil {
> 		return sdkerrors.Wrapf(types.ErrInvalidState, "can't emit %s event: %s", eventName, err)
> ```

=
___
*[`x/asset/nft/keeper/keeper.go` line 791 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_J55ZH7xB4rq8pICYB:-N_J55ZH7xB4rq8pICYC:bk6vs4o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1b84741f4fa3640567baf232bd02033d9baf30c/x/asset/nft/keeper/keeper.go#L791)):*
> ```Go
> }
> 
> func (k Keeper) addToWhitelistOrRemoveFromWhitelist(ctx sdk.Context, classID, nftID string, sender, account sdk.AccAddress, whitelisting bool) error {
> ```

IMO better name `whitelisting` -> `addToWhitelist`

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: 5 of 10 files reviewed, 12 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/wnft/keeper/keeper.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_IYrriE2vWyMBkUDQ4:-N_J5OcFANskWcw0J8Yu:bgcxp2t) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/wnft/keeper/keeper.go#L58)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

We need a consensus there, I am not touching it for now 
</blockquote></details>

But if the error is our error it will be already wrapped

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 745 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_J4T-n9G-N5oI3eCK8:-N_JDYyj0kGtQSuyfIjS:b-lwxkpa) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1b84741f4fa3640567baf232bd02033d9baf30c/x/asset/nft/keeper/keeper.go#L745)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO better name `frozen` -> `freeze`
</blockquote></details>

I also thought about it but then I realized that freeze=false would mean "please don't freeze", not "please unfreeze". So `frozen` is a better choice IMO.
___
*[`x/asset/nft/keeper/keeper.go` line 791 at r3](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_J55ZH7xB4rq8pICYB:-N_JE0Mp6e_8Pvj8zgV7:b-fknfyg) ([raw file](https://github.com/CoreumFoundation/coreum/blob/a1b84741f4fa3640567baf232bd02033d9baf30c/x/asset/nft/keeper/keeper.go#L791)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO better name `whitelisting` -> `addToWhitelist`
</blockquote></details>

or `whitelisted` to follow the `frozen`schema
___
*[`x/wnft/keeper/keeper.go` line 58 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_IYrriE2vWyMBkUDQ4:-N_JEMvCAPtMMjKNcWhz:biignbk) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/wnft/keeper/keeper.go#L58)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But if the error is our error it will be already wrapped
</blockquote></details>

But `EmitTypedEvent` is not our function

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 770 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_JLL5v6fivO0YcZUgc:-N_JLL5v6fivO0YcZUgd:b-nopamo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/33e7c2d37cd7d5117945a739be29657c855e2986/x/asset/nft/keeper/keeper.go#L770)):*
> ```Go
> 		Owner:   owner.String(),
> 	}
> 	if !frozen {
> ```

But the flow is weird now. You first create event for freezing and then you say "ohohoh, I really wanted to create event for unfreezing". It's really like a cosmos sdk style now :D
___
*[`x/asset/nft/keeper/keeper.go` line 813 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_JLjR5EdTRhWpxgnvz:-N_JLjR5EdTRhWpxgnw-:b-2guby3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/33e7c2d37cd7d5117945a739be29657c855e2986/x/asset/nft/keeper/keeper.go#L813)):*
> ```Go
> 		Account: account.String(),
> 	}
> 	if !whitelisting {
> ```

same here

**Review by wojtek-coreum — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 770 at r4](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_JLL5v6fivO0YcZUgc:-N_JWPMK0OoUiCOfvlbh:bxomp7o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/33e7c2d37cd7d5117945a739be29657c855e2986/x/asset/nft/keeper/keeper.go#L770)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

is there another way to omit the else statement? @dzmitryhil 
</blockquote></details>

Let's discuss, personally I don't understand @dzmitryhil 's request to do it

**Review by wojtek-coreum — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: all files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 780 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_JulMBB9_4IudZHbKu:-N_JulMBB9_4IudZHbKv:btu8kdo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9010750ef2bde9866568061ee72102f26e6aeabb/x/asset/nft/keeper/keeper.go#L780)):*
> ```Go
> 	}
> 
> 	err = ctx.EventManager().EmitTypedEvent(event)
> ```

Move `err = ctx.EventManager(` to if. 

Also, check please other places in your code. 
___
*[`x/asset/nft/keeper/keeper.go` line 825 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_JutmI0ZOatenESpXM:-N_JutmI0ZOatenESpXN:b-dlrqeo) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9010750ef2bde9866568061ee72102f26e6aeabb/x/asset/nft/keeper/keeper.go#L825)):*
> ```Go
> 	}
> 
> 	err = ctx.EventManager().EmitTypedEvent(event)
> ```

Move `err = ctx.EventManager(` to if. 
___
*[`pkg/store/errors.go` line 7 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_JvvB74dGxPjsNCBIs:-N_JvvB74dGxPjsNCBIt:b-lhmll6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9010750ef2bde9866568061ee72102f26e6aeabb/pkg/store/errors.go#L7)):*
> ```Go
> )
> 
> const globalCodespace = "global"
> ```

Codespace -> CodeSpace
___
*[`pkg/store/errors.go` line 11 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_JvpimAx__YDHUPlkB:-N_JvpimAx__YDHUPlkC:b-e4p697) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9010750ef2bde9866568061ee72102f26e6aeabb/pkg/store/errors.go#L11)):*
> ```Go
> var (
> 	// ErrInvalidKey is returned when the provided store key is invalid.
> 	ErrInvalidKey = sdkerrors.Register(globalCodespace, 1, "invalid key")
> ```

@wojtek-coreum @ysv Are you guys sure that we want to add a global error here?

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: all files reviewed, 4 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

**Review by dzmitryhil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @silverspase, and @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 638 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I3tH16mfUxYc17VhF:-N_XTVHW6veykNX6COy9:bdueri3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/asset/nft/keeper/keeper.go#L638)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

I created errors.go at /pkg/store package and defined the error there with "global" codespace
</blockquote></details>

But see, if you receive it this error it is meaningless for you. I mean is too general, to understand the reason. 
And usually the error cause that `kyes error` is wrong usage of it, which is `invalid argument` error type for the keeper. That's why IMO better to add the wrapping in the keeper with the i`nvalid argument` type and addition meaningfully desription.

**Review by miladz68 — DISMISSED** [review]
> Reviewed 4 of 5 files at r3, 1 of 1 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 638 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I3tH16mfUxYc17VhF:-N_XxTvk39794EHHQxdk:b8od1j3) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/asset/nft/keeper/keeper.go#L638)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But see, if you receive it this error it is meaningless for you. I mean is too general, to understand the reason. 
And usually the error cause that `kyes error` is wrong usage of it, which is `invalid argument` error type for the keeper. That's why IMO better to add the wrapping in the keeper with the i`nvalid argument` type and addition meaningfully desription.
</blockquote></details>

I agree with Dima here. 
___
*[`pkg/store/errors.go` line 11 at r6](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_JvpimAx__YDHUPlkB:-N_XwoS2DNdeNE9dWXCj:b5wau1w) ([raw file](https://github.com/CoreumFoundation/coreum/blob/9010750ef2bde9866568061ee72102f26e6aeabb/pkg/store/errors.go#L11)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Because it looks like a utility function, ann probably should keep returning the current errors, and the consumer might wrap it to the correct error in the module. 
</blockquote></details>

that is a good point. we should not have a new error defined to manage our internal errors/failures.

**Review by wojtek-coreum — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

___
*[`x/asset/nft/keeper/keeper.go` line 638 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_I3tH16mfUxYc17VhF:-N_bhLNT-W4venNR7-81:b-fm3n6) ([raw file](https://github.com/CoreumFoundation/coreum/blob/8c6df6a34a19fe81befec6468f218a77d326d81b/x/asset/nft/keeper/keeper.go#L638)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I agree with Dima here. 
</blockquote></details>

okay, I understand Dima's argument now and it's reasonable

**Review by dzmitryhil — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 2 of 3 files at r2, 1 of 5 files at r3, 2 of 2 files at r8, 3 of 6 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: all files reviewed, 1 unresolved discussion (waiting on @ysv)

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 342 at r11](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_c2eCg2qq4aXXzZbJ8:-N_c2eCg2qq4aXXzZbJ9:bhg6w6o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/033b405d9ea4301c5f1b3c00265830b79466d93b/x/asset/ft/keeper/keeper.go#L342)):*
> ```Go
> 	})
> 	if err != nil {
> 		return sdkerrors.Wrapf(types.ErrInvalidState, "failed to emit EventFrozenAmountChanged event: %s", err)
> ```

Embed error to if.
___
*[`x/asset/ft/keeper/keeper.go` line 383 at r11](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_c2ibk7py2eW61tF9y:-N_c2ibk7py2eW61tF9z:bhg6w6o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/033b405d9ea4301c5f1b3c00265830b79466d93b/x/asset/ft/keeper/keeper.go#L383)):*
> ```Go
> 	})
> 	if err != nil {
> 		return sdkerrors.Wrapf(types.ErrInvalidState, "failed to emit EventFrozenAmountChanged event: %s", err)
> ```

Embed error to if.
___
*[`x/asset/ft/keeper/keeper.go` line 488 at r11](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_c2lgUAtkfpthv-Fn7:-N_c2lgUAtkfpthv-Fn8:bhg6w6o) ([raw file](https://github.com/CoreumFoundation/coreum/blob/033b405d9ea4301c5f1b3c00265830b79466d93b/x/asset/ft/keeper/keeper.go#L488)):*
> ```Go
> 	})
> 	if err != nil {
> 		return sdkerrors.Wrapf(types.ErrInvalidState, "failed to emit EventWhitelistedAmountChanged event: %s", err)
> ```

Embed error to if.

**Review by dzmitryhil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @miladz68, @silverspase, @wojtek-coreum, and @ysv)

___
*[`x/asset/ft/keeper/keeper.go` line 342 at r11](https://reviewable.io/reviews/CoreumFoundation/coreum/572#-N_c2eCg2qq4aXXzZbJ8:-N_c4rST0x0qqGErL-ZR:b-5wz7ft) ([raw file](https://github.com/CoreumFoundation/coreum/blob/033b405d9ea4301c5f1b3c00265830b79466d93b/x/asset/ft/keeper/keeper.go#L342)):*
<details><summary><i>Previously, silverspase (Artem) wrote…</i></summary><blockquote>

Let's keep it separate since we have the whole struct `&types.EventFrozenAmountChanged` as a param, increasing the size of this block code and making the construction harder to read.
</blockquote></details>

But we already use that style everywhere even for functions twice more than this one.

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 3 of 6 files at r9, 2 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: all files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @silverspase, and @ysv)

**Review by wojtek-coreum — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68 and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 3 of 6 files at r9, 1 of 3 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/572)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
