### PR TITLE
changed gas-price auto in cli to initial gas price

### PR DESCRIPTION
**Pull request by miladz68**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/474)

### CODE REVIEW

**Review by ysv — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/474)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, @silverspase, and @wojtek-coreum)

___
*[`cmd/cored/cosmoscmd/gas_price.go` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/474#-NTs2iKh9ZIiwnvg4I9E:-NTs2iKh9ZIiwnvg4I9F:bkcqeni) ([raw file](https://github.com/CoreumFoundation/coreum/blob/aa7af92c22eec2b46cd30702924399d7f0889cdc/cmd/cored/cosmoscmd/gas_price.go#L63)):*
> ```Go
> 	gasPriceWithOverhead := sdk.DecCoin{
> 		Denom:  gasPrice.MinGasPrice.Denom,
> 		Amount: params.GetParams().Model.InitialGasPrice.Mul(sdk.MustNewDecFromStr(defaultGasPriceMultiplier)),
> ```

yes but does it really make sense to multiply it ?
IMO we should just use InitialGasPrice because it couldn't be higher than that val

**Review by miladz68 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/474)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @silverspase, @wojtek-coreum, and @ysv)

___
*[`cmd/cored/cosmoscmd/gas_price.go` line 63 at r1](https://reviewable.io/reviews/CoreumFoundation/coreum/474#-NTs2iKh9ZIiwnvg4I9E:-NTsAnd477OPVhnYfdIJ:b7s1hb9) ([raw file](https://github.com/CoreumFoundation/coreum/blob/aa7af92c22eec2b46cd30702924399d7f0889cdc/cmd/cored/cosmoscmd/gas_price.go#L63)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes but does it really make sense to multiply it ?
IMO we should just use InitialGasPrice because it couldn't be higher than that val
</blockquote></details>

Done. That was an obvious mistake.

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/474)* status: all files reviewed, 1 unresolved discussion (waiting on @silverspase, @wojtek-coreum, and @ysv)

**Review by ysv — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/coreum/474)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @silverspase and @wojtek-coreum)

**Pull request merged**
