### PR TITLE
Add official funded accounts and validators for devnet

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/111)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/111)* status: all files reviewed, 1 unresolved discussion (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/network.go` line 91 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/111#-N7Q0RgX1UgAN_HWD7Dq:-N7Q0RgX1UgAN_HWD7Dr:b-dps9ne) ([raw file](https://github.com/coreumfoundation/coreum/blob/a981c4f64bf0b05e403f896dbcdc2bea424346c1/app/network.go#L91)):*
> ```Go
> 			GenTxs: []json.RawMessage{
> 				// validator 0
> 				json.RawMessage(`{
> ```

we should have these transactions as files and embed them here.
to save on repeating  the common tx structure, we could have a common template and only store and change the signature ?

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/111)* status: all files reviewed, 1 unresolved discussion (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`app/network.go` line 91 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/111#-N7Q0RgX1UgAN_HWD7Dq:-N7Q1dF2BJiqJsOwuVdE:b-97l1ku) ([raw file](https://github.com/coreumfoundation/coreum/blob/a981c4f64bf0b05e403f896dbcdc2bea424346c1/app/network.go#L91)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we should have these transactions as files and embed them here.
to save on repeating  the common tx structure, we could have a common template and only store and change the signature ?
</blockquote></details>

there are a lot of data which are different each time, I will try to make a template out of it

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/111)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`app/network.go` line 91 at r1](https://reviewable.io/reviews/coreumfoundation/coreum/111#-N7Q0RgX1UgAN_HWD7Dq:-N7Q9fs31I64joAN5U7L:bavg149) ([raw file](https://github.com/coreumfoundation/coreum/blob/a981c4f64bf0b05e403f896dbcdc2bea424346c1/app/network.go#L91)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

there are a lot of data which are different each time, I will try to make a template out of it
</blockquote></details>

Done, but without templating

**Review by miladz68 — DISMISSED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/111#-:-N7QN3Md3fKF0TdrIXJc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliverasistemas, @xlab, and @ysv)

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/111)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/111#-N7V2P3H2Sv4mKTywR_a):*
it says that there are conflicts, but I am not seeing conflicts on github ? :thinking:

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/111)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/coreumfoundation/coreum/111#-N7V2P3H2Sv4mKTywR_a):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it says that there are conflicts, but I am not seeing conflicts on github ? :thinking: 
</blockquote></details>

The message means that I solved conflicts in this commit, I haven't written it - it's automatic

**Review by miladz68 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/coreum/111)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliverasistemas, @xlab, and @ysv)

**Pull request merged**
